"""候補 Issue #1(表形式データ)で承認された論文 8 本のカード(バッチ cand_2026_10_b09)。
各論文の主張と評価方法(ベンチマーク・データ規模の上限・ベースラインの調整方法・利益相反)を記録する。結果表の数値は記録しない。
書誌(著者・版・年)は scratchpad のバッチ JSON(arXiv API の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

CLS = ["tabular-classification"]
REG = ["tabular-regression"]
BOTH = CLS + REG

SPECS = [
  {"id": "arxiv-2608.25048", "title": "Tabular Foundation Models for Multi-View Information Cascade Popularity Prediction",
   "authors": ["Wenting Zhu", "Chenghua Gong", "Sanchuan Guo", "Chaozhuo Li", "Yueyue Zhang", "Xi Zhang"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.25048"},
   "tasks": REG, "fam": ["tabular-foundation-model", "deep-learning"], "par": ["in-context-learning", "supervised"],
   "proposes": ["TFM4POP (TabPFN backbone with IA3 adapters over a unified multi-view table plus a Neural-ODE dynamic branch)", "EventCas multi-view cascade dataset"],
   "claims": [
     ("TFM4POP is proposed as the first framework to bring tabular foundation models into cascade popularity prediction, using their pre-trained priors to model multiple heterogeneous information views jointly.", "Abstract",
      "we propose TFM4POP, the first framework to introduce tabular foundation models (TFMs) into popularity prediction, leveraging their pre-trained tabular priors to unify the modeling of multiple heterogeneous information views."),
     ("In the authors' experiments TFM4POP consistently outperforms state-of-the-art baselines across datasets and observation settings.", "Abstract",
      "Extensive experiments show that TFM4POP consistently outperforms state-of-the-art baselines across multiple datasets and observation settings."),
     ("Evaluation uses two real-world datasets, Twitter (from MMCas) and EventCas, which the authors built themselves from Sina Weibo.", "Evaluation datasets",
      "We conduct experiments on two real-world datasets: Twitter and EventCas."),
     ("The main comparison repeats every experiment with five random seeds and reports mean and standard deviation.", "Experimental settings",
      "All experiments are repeated five times with different random seeds, and we report the mean and standard deviation."),
     ("In the ablation, replacing the TabPFN backbone with a parameter-matched MLP over the same static input degrades performance the most of all variants.", "Ablation study",
      "replacing the TFM backbone with a parameter-matched MLP causes the largest degradation among all variants"),
     ("In the ablation, IA3 adaptation of the backbone outperforms full fine-tuning, LoRA and the frozen backbone.", "Ablation study",
      "IA3 outperforms full fine-tuning, LoRA, and the frozen backbone"),
   ],
   "notes": "Not a standard tabular benchmark paper: the task is information-cascade popularity regression (log-scaled incremental popularity) where text, image and graph views are compressed into extra columns of a table for TabPFN; tagged tabular-regression as the closest existing task. The text does not say how the 13 baselines' hyperparameters were set (tuned, defaults, or settings from the original papers), and no train/validation/test split ratio was found. The ablation table caption says its results come from a single fixed random seed."},

  {"id": "arxiv-2609.29523", "title": "Towards Trustworthy Biological Alignment in TabPFN-Probed Pathology Foundation Models",
   "authors": ["Ushashi Bhattacharjee", "Alloy Das", "Saria Hannan", "Tirtho Roy", "Koushik Howlader", "Soumik Sarkar"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.29523"},
   "tasks": REG, "fam": ["tabular-foundation-model", "linear-models", "deep-learning"], "par": ["in-context-learning", "supervised"],
   "proposes": ["Training-free audit of biological alignment in frozen pathology foundation models using a TabPFN regression probe with negative, shift, perturbation and shortcut controls"],
   "claims": [
     ("The paper presents a training-free framework for auditing biological alignment in frozen pathology foundation models, using spatially paired histology and transcriptomics from HEST-1k (240 samples, 3 organs).", "Abstract",
      "We present a training-free framework for auditing biological alignment in frozen PFMs using spatially paired histology and transcriptomics from HEST-1k, evaluated on 240 samples spanning 3 organs."),
     ("TabPFN is used as a pretrained probe to measure how well molecular programs can be decoded from frozen embeddings without task-specific gradient updates.", "Abstract",
      "TabPFN serves as a pretrained probe to measure how well these molecular programs can be decoded without task-specific gradient updates."),
     ("The protocol uses specimen-level grouping with five-fold specimen-level cross-validation and three fixed seeds, reporting mean per-target Pearson correlation.", "Method (leakage-safe protocol)",
      "Five-fold specimen-level cross-validation with three fixed seeds; we report mean per-target Pearson correlation (PCC)."),
     ("Baseline probes (mean, kNN, Ridge and a gradient-trained MLP with one fixed configuration) are run on identical folds and context. No hyperparameter search for the baselines was found in the text.", "Method (baselines)",
      "Beyond TabPFN we run mean, kNN (cosine, distance-weighted), Ridge, and a gradient-trained MLP"),
     ("With the UNI encoder fixed, the training-free probes outperform the gradient-trained MLP.", "Results (label efficiency)",
      "The training-free probes outperform the gradient-trained MLP"),
     ("Limitation: TabPFN is the primary probe family, and absolute PCC and especially label efficiency may remain probe-specific.", "Limitations and Outlook",
      "but absolute PCC and especially label efficiency can remain probe-specific."),
   ],
   "notes": "Not tabular prediction in the usual sense: TabPFNRegressor is used as a frozen probe that regresses gene/pathway targets from frozen pathology-image embeddings. Tagged tabular-regression as the closest existing task."},

  {"id": "arxiv-2608.22594", "title": "Tabular foundation models for non-tabular tasks",
   "authors": ["Goran Nakerst", "John Brennan", "Wouter Beugeling", "Masudul Haque"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.22594"},
   "tasks": CLS, "fam": ["tabular-foundation-model", "gradient-boosted-trees", "deep-learning"], "par": ["in-context-learning", "supervised"],
   "proposes": ["Empirical study of TabPFN v3 on non-tabular classification tasks (MNIST, French/German words, Tiny ImageNet) recast as tables"],
   "claims": [
     ("TabPFN v3 is applied to three non-tabular classification problems: MNIST digits, French vs. German word identification, and Tiny ImageNet.", "Abstract",
      "We address this question by using TabPFN v3 on three non-tabular classification problems: handwritten digit recognition on MNIST, language identification of French and German words, and image classification on Tiny ImageNet."),
     ("Without access to spatial or sequential structure, TabPFN v3 in some cases reaches accuracies comparable to task-specific models.", "Abstract",
      "Despite having no explicit access to the spatial or sequential structure characterizing the data, TabPFN v3 in some cases achieves accuracies comparable with that of models or methods geared specifically toward the corresponding tasks."),
     ("TabPFN v3 is run with library defaults, with one override that disables the pretraining input-size limits. Every experiment exceeds those limits.", "Appendix A (TabPFN v3 configuration)",
      "All TabPFN results use model v3 library defaults with a single override"),
     ("On MNIST, the LightGBM baseline is not hyperparameter-searched. Its regularization is scaled by hand with training size.", "Appendix A (MNIST)",
      "LightGBM sees the same 784 columns, with regularization scaled to the training size rather than searched"),
     ("On the word task, LightGBM is tuned separately at each training size and encoding with randomized search and stratified 5-fold CV on the training set only. The test set is never seen during tuning.", "Appendix A (French/German words)",
      "LightGBM is tuned independently at each training size and encoding."),
     ("On the word task, tuned LightGBM pulls clearly ahead only when data is plentiful.", "Conclusion",
      "Only once data is plentiful does the tuned LightGBM pull clearly ahead."),
   ],
   "notes": "Non-tabular tasks (images, words) recast as tables; tagged tabular-classification as the closest existing task. Each task uses one fixed held-out test set with resampled training/context sets. The CNN baseline uses a fixed architecture and 100 epochs at all training sizes."},

  {"id": "arxiv-2608.22069", "title": "AstroBind: Machine learning prediction of binding energy distributions on interstellar water ice from geometric surface descriptors",
   "authors": ["Aneesa Ahmad", "Catherine Walsh"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.22069"},
   "tasks": REG, "fam": ["gradient-boosted-trees", "random-forests", "linear-models", "gaussian-processes", "kernel-methods"], "par": ["supervised"],
   "proposes": ["AstroBind (XGBoost regression of DFT binding energies on amorphous water ice from geometric descriptors)"],
   "claims": [
     ("An ML model is trained on 27 geometric descriptors of the local ice-adsorbate environment to predict binding energies.", "Abstract",
      "We trained a machine-learning model using 27 geometric descriptors of the local ice–adsorbate environment."),
     ("The model is trained on binding energies of 13 adsorbates and evaluated with pooled leave-one-cluster-out validation across 15 ice surfaces.", "Abstract",
      "The model was trained on binding energies for 13 adsorbates on amorphous solid water clusters and evaluated through pooled leave-one-cluster-out validation across 15 ice surfaces."),
     ("Linear regression, ridge regression, random forest and XGBoost were compared, and XGBoost had the highest test-set accuracy.", "Methods (model training)",
      "XGBoost achieved the highest test-set accuracy"),
     ("XGBoost uses fixed hyperparameters. A randomized-search cross-validation over hyperparameter combinations improved results only marginally.", "Methods (model training)",
      "Hyperparameter tuning via randomised-search cross-validation, in which 80 randomly sampled hyperparameter combinations are each scored by 5-fold cross-validation"),
     ("Gradient-boosted trees were chosen over deep learning because, at this data size, boosted trees are competitive on tabular data and their feature attributions give mechanistic insight.", "Discussion",
      "boosted trees are competitive on tabular data of this scale"),
     ("Limitation: performance collapses for dispersion-dominated adsorbates, which the authors describe as consistent with the absence of electronic information in the descriptors.", "Discussion",
      "performance collapses for dispersion-dominated adsorbates"),
   ],
   "notes": "Domain application (astrochemistry) on a small tabular regression dataset (1,429 configurations, 46 input features). The model comparison between linear, ridge, random forest and XGBoost is reported on the held-out test clusters; no separate validation set for that choice was found in the text. Gaussian process regression and kernel ridge regression were also benchmarked on the same 80/20 cluster-based split."},

  {"id": "arxiv-2608.20024", "title": "Systematic Evaluation of TabPFN-TS for Zero-Shot Probabilistic Heat Load Forecasting in District Heating Networks",
   "authors": ["Ben Spoek", "Karim K. Ben Hicham", "Kai Derzsi", "Philipp Althaus", "Alexander Mitsos", "Dirk Müller"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.20024", "code": "https://github.com/benspoek/tsfm-heatload"},
   "tasks": ["time-series-forecasting"], "fam": ["tabular-foundation-model", "time-series-foundation-model", "gradient-boosted-trees", "deep-learning", "automl-systems"], "par": ["in-context-learning", "supervised"],
   "proposes": ["Evaluation of TabPFN-TS for zero-shot probabilistic heat load forecasting", "Multi-Resolution Residual-Correction (MRRC) Forecaster"],
   "claims": [
     ("The study evaluates TabPFN-TS against time-series foundation models and trained ML baselines for probabilistic heat load forecasting in district heating networks.", "Abstract",
      "This study systematically evaluates TabPFN-TS against state-of-the-art time-series foundation models and trained machine-learning baselines for probabilistic heat load forecasting in district heating networks."),
     ("Chronos-2 has the lowest aggregate full-year error, while TabPFN-TS shows better empirical calibration.", "Abstract",
      "Although Chronos-2 achieves the lowest aggregate full-year error, TabPFN-TS shows better empirical calibration."),
     ("The trained AutoGluon baselines are fitted on 2023 data and evaluated on rolling 24-hour forecasts in 2024. Each model class uses the target history according to its own defaults.", "Methodology (forecasting models)",
      "The predictors are trained on 2023 target values and evaluated on rolling 24-hour forecasts in 2024."),
     ("The TabPFN-TS configuration (context length, resolution, horizon, covariates) is chosen with diagnostics on three representative weeks of 2024, the same year used for the full-year evaluation.", "Case Study and Experimental Design",
      "The selected winter, transitional, and summer weeks in 2024 are January 15–21, April 22–28, and August 12–18, respectively."),
     ("The main experiments feed realized future temperature as the known covariate, which amounts to assuming a perfect weather forecast. A separate sensitivity analysis uses archived forecasts.", "Methodology (forecasting models)",
      "This setting can be interpreted as a perfect-weather-forecast assumption"),
     ("The authors declare no known competing financial interests.", "Declaration of Competing Interest",
      "The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper."),
   ],
   "notes": "Time-series forecasting paper (tabularized forecasting with TabPFN-TS), not tabular prediction; tagged time-series-forecasting. The configuration was chosen on weeks taken from 2024, and the full-year evaluation also covers 2024; the text does not discuss this overlap. The Munich data are proprietary; the Flensburg transfer data are public."},

  {"id": "arxiv-2608.17856", "title": "ARASH: Adaptive Retrieval And Shot Selection for Tabular Prediction",
   "authors": ["Samirasadat Jamalidinan", "Yue Xu", "Kazem Cheshmi"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.17856"},
   "tasks": CLS, "fam": ["tabular-foundation-model", "gradient-boosted-trees", "tabular-mlp", "tabular-attention", "large-language-models"], "par": ["in-context-learning", "supervised"],
   "proposes": ["ARASH (adaptive, query-specific retrieval and shot selection for TFM/LLM in-context tabular prediction)"],
   "claims": [
     ("ARASH selects query-specific context shots for tabular foundation models from local-neighbourhood analysis of the training set.", "Abstract",
      "This paper introduces ARASH (Adaptive, query-specific Retrieval And Shot selection), a method that improves TFM efficiency by selecting optimal shots based on local neighborhood analysis within the training set."),
     ("ARASH reduces TabPFN's prompt length and memory use while giving comparable accuracy.", "Abstract",
      "Our results demonstrate that ARASH reduces the prompt length and memory usage of TabPFN by 1261.5× and 2.56×, respectively, while providing comparable accuracy."),
     ("Evaluation uses OpenML-CC18 plus the Combo collection, with a single 80/20 train-test split (seed 42) shared by all methods.", "Experimental results (setup)",
      "For datasets, we use an 80/20 train–test split with random seed 42, and the same split is used consistently across all compared methods."),
     ("Tabular baselines come from the TALENT toolbox and its standardized implementations and hyperparameter settings. Results are reported only on datasets where each method ran successfully.", "Experimental results (baselines)",
      "We use the latest TALENT release and report results on the datasets for which the corresponding methods are successfully executed."),
     ("ARASH's locality, purity and clustering thresholds are grid-searched on a held-out 10% of datasets that are not used in training, evaluation or test.", "Experimental results (evaluation metrics)",
      "we define a tuning set as random 10% of datasets (seed=42) never appearing in training, evaluation, or test and perform a grid search for locality, purity, and auto-clustering thresholds to avoid bias."),
     ("The LoCalPFN-style comparison is reported only on datasets where both large-budget runs finished within the time limit.", "Experimental results (ICL demonstration-selection baselines)",
      "We therefore report this comparison only on the datasets for which both LoCalPFN-style kNN and DPP runs completed successfully."),
   ],
   "notes": "Whether TALENT baselines were run with default settings or with hyperparameter search is not stated beyond 'standardized implementations and hyperparameter settings'. A single train-test split is used, with no repeated seeds for the main comparison. ARASH is also evaluated with serialized-table language models (LLaMA 3.2, Qwen 2.5, FLAN-T5)."},

  {"id": "arxiv-2608.16429", "title": "Localized TabICLv2: Scaling Tabular In-Context Learning through k-NN",
   "authors": ["Beimnet Bekele Guta"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.16429"},
   "tasks": CLS, "fam": ["tabular-foundation-model", "gradient-boosted-trees"], "par": ["in-context-learning"],
   "proposes": ["Localized TabICLv2 (k-NN retrieval in TabICLv2's Stage 2 representation space, with Stage 2+3 fine-tuning)"],
   "claims": [
     ("Localized TabICLv2 cuts TabICLv2's inference cost by retrieving only the k nearest training neighbours of each test point in the model's Stage 2 representation space, instead of using the full training context.", "Abstract",
      "Localized TabICLv2 introduces a method that reduces the inference cost of TabICLv2 by retrieving only the k nearest training neighbours for each test point, measured by similarity in the model’s Stage 2 row-representation space, rather than using the full training context."),
     ("On TabArena classification tasks, the fine-tuned localized model keeps most of Full TabICLv2's accuracy and speeds up batch inference.", "Abstract",
      "On TabArena classification tasks, the fine-tuned localized model retains 98.64% of Full TabICLv2 accuracy and it achieves a median 2.18× speedup in batch inference"),
     ("Evaluation covers 38 TabArena binary and multiclass classification datasets, using an 80/20 stratified train/test split and three random seeds.", "Results and Discussion",
      "We use an 80/20 stratified train/test split and run each experiment over three random seeds."),
     ("The XGBoost baseline is trained on the full training set. No hyperparameter configuration or tuning for XGBoost was found in the text.", "Results and Discussion",
      "XGBoost trained on the full training set and retrieval-only baselines"),
     ("The localized method does not exceed Full TabICLv2's accuracy.", "Results and Discussion",
      "Overall, the localized method does not surpass the accuracy of Full TabICLv2."),
     ("Limitation: localization may underperform when the retrieved neighbours miss useful evidence, and retrieval overhead can reduce speedups on smaller datasets or large query batches.", "Conclusion",
      "However, localization may underperform when useful evidence is not captured by the retrieved neighbours, and retrieval overhead can reduce speedups on smaller datasets or large query batches."),
   ],
   "notes": "The PDF header names the 2nd ICML Workshop on Foundation Models for Structured Data (2026); venue is not recorded because it is not in the batch metadata. The paper uses its own 80/20 split with 3 seeds instead of TabArena's official splits, and all 38 datasets are classification. The XGBoost baseline (no stated tuning) is compared on ROC AUC / log-loss."},

  {"id": "arxiv-2609.13202", "title": "Do Tabular Foundation Models Still Need Feature Engineering?",
   "authors": ["Yifan WU", "Pinjun Dong", "Jiran Tao", "Binyan Jiang"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.13202"},
   "tasks": BOTH, "fam": ["tabular-foundation-model"], "par": ["in-context-learning"],
   "proposes": ["Controlled within-estimator study of 26 feature-engineering conditions across TabPFN and TabICL versions", "NNRC screening for context augmentation from related datasets"],
   "claims": [
     ("Feature engineering gains are concentrated in earlier TFM generations and become negligible for the strongest models.", "Abstract",
      "We find a consistent pattern: feature engineering gains are concentrated in earlier model generations and become negligible for the strongest models."),
     ("The classification datasets are restricted to TabPFN v1's limits (at most 1,024 training samples and 100 features) so that all model generations are evaluated on the same datasets (13 TabArena datasets in total).", "Experiments",
      "all selected classification datasets satisfy the sample and feature limits of TabPFN v1 (at most 1,024 training samples and 100 features), ensuring that every generation is evaluated on the same datasets."),
     ("Every condition is evaluated on the 30 official TabArena splits, and gains are paired against the identity representation on the same split.", "Experiments",
      "Every condition is evaluated on the 30 official TabArena splits (10 repeats × 3 folds)."),
     ("Each estimator is fixed at its checkpoint with its default configuration, ensemble procedure and native preprocessing. No tuning of the TFMs is part of the comparison.", "Problem Setup and Estimand",
      "Let m denote a fixed tabular foundation model estimator, including its checkpoint, default configuration, ensemble procedure, and native preprocessing pipeline."),
     ("The reported best-observed feature-engineering gain is an oracle maximum over conditions, not a validation-selected choice.", "Results (Figure 1 caption)",
      "the maximum is oracle, not validation-selected"),
     ("The context-augmentation experiment with related source datasets covers only three target tasks and is a feasibility study, not a benchmark-wide evaluation.", "Experiments",
      "The analysis is therefore a feasibility study conditioned on source availability and schema compatibility, rather than a benchmark wide evaluation."),
   ],
   "notes": "Evaluates TabPFN v1/v2/v2.5/v2.6/v3 and TabICL v1/v2 (12 estimator versions) on 8 classification + 5 regression TabArena datasets. Most TabPrep pipeline variants have negative median within-estimator effects here, whereas the TabPrep paper (Tschalzev et al. 2026) reports gains inside the TabArena tuning/ensembling pipeline; the authors frame their question as complementary to that one. No code link was found in the text."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
