"""候補 Issue #1(表データ)で承認された論文のうち、バッチ cand_2026_10_b08 の8本のカード。
各論文の主張と評価方法(ベンチマーク・ベースラインの扱い・選択に使うデータ)の記述を記録する。結果表の数値は記録しない。
書誌(著者・版・年)は scratchpad の batches/cand_2026_10_b08.json(arXiv API の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
  {"id": "arxiv-2609.06080",
   "title": "PhenoBench: Mapping What a Deeply Phenotyped Human Cohort Can Tell Us",
   "authors": ["Gal Sapir", "Alon Diament", "Adva Wolf", "Doron Yaya-Stupp", "Dikla Gelbard Solodkin", "Dana Azouri",
               "Anat Etzion-Fuchs", "Guy Lutsker", "Eran Segal", "Hagai Rossman"],
   "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2609.06080"},
   "tasks": ["tabular-regression"], "fam": ["tabular-foundation-model", "gradient-boosted-trees", "tabular-mlp", "linear-models"],
   "par": ["supervised", "in-context-learning"],
   "proposes": ["PhenoBench: executable benchmark of clinically grounded tasks with Task Cards and evaluation contracts on the Human Phenotype Project cohort"],
   "claims": [
     ("PhenoBench is a versioned collection of clinically grounded tasks with human-readable Task Cards and executable evaluation contracts.", "Introduction",
      "PhenoBench contributes a versioned collection of 90 clinically grounded tasks across 15 domains and 26 input modalities, with human-readable Task Cards and executable evaluation contracts."),
     ("Under a fixed single-estimator protocol with bounded tuning, the pretrained tabular models ranked above the evaluated task-specific baselines, including XGBoost and CatBoost, in aggregate.", "Abstract",
      "Under a fixed single-estimator protocol with bounded tuning, these models ranked above the evaluated task-specific baselines, including XGBoost and CatBoost, in aggregate."),
     ("The XGBoost and CatBoost grids were fixed before the matched comparison, selected by five-fold cross-validation within the training split, and evaluated once on the held-out test split.", "Appendix (method configurations)",
      "The XGBoost and CatBoost grids were fixed before their matched campaign, selected by five-fold cross-validation within the training split, and evaluated once on the held-out test split."),
     ("The tabular comparison uses a single-estimator CPU float32 protocol rather than each model's strongest recommended ensemble.", "Limitations",
      "The tabular comparison evaluates a single-estimator CPU float32 protocol, not each model’s strongest recommended ensemble."),
     ("XGBoost and CatBoost received the same bounded 12-candidate tuning budget rather than exhaustive library-specific optimization, so the small average gains do not settle the best attainable performance of either model family.", "Limitations",
      "XGBoost and CatBoost used the same bounded 12-candidate tuning budget rather than exhaustive library-specific optimization."),
     ("Competing interests: seven authors are employees of Pheno.AI Ltd., and Eran Segal is a paid consultant of Pheno.AI Ltd.", "Competing interests",
      "Gal Sapir, Alon Diament, Adva Wolf, Dikla Gelbard Solodkin, Dana Azouri, Anat Etzion-Fuchs, and Hagai Rossman are employees of Pheno.AI Ltd."),
   ],
   "notes": "Tabular comparison: TabSwift, TabICL, TabDPT, TabPFN v2, Google TabFM, TabPFN 3.5 vs ridge, tuned XGBoost/CatBoost and RealMLP on 160 matched regression cells over 52 tasks (Results). The paper also evaluates 14 language models (PhenoBench-LLM), not recorded here. Pheno.AI is the cohort/benchmark operator, not the developer of the evaluated tabular models."},

  {"id": "arxiv-2609.03003",
   "title": "Causal Foundation Models",
   "authors": ["Christopher Stith", "Hossein Rahmani", "Jesse C. Cresswell"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.03003", "code": "https://github.com/layer6ai-labs/cfms"},
   "tasks": ["causal-effect-estimation"], "fam": ["tabular-foundation-model", "gradient-boosted-trees", "automl-systems"],
   "par": ["in-context-learning"],
   "proposes": ["Tutorial on causal foundation models (CFMs) and a standardized comparison of Do-PFN, CausalPFN and CausalFM on RealCause-Lalonde"],
   "claims": [
     ("One stated contribution is a standardized empirical comparison of three causal foundation models on semi-synthetic observational data.", "Benchmarking CFMs",
      "One contribution of our work is establishing a standardized, fair empirical comparison across these three CFMs for causal inference on more complex semi-synthetic observational data."),
     ("Models are evaluated on the semi-synthetic RealCause-Lalonde benchmark (Lalonde-CPS and Lalonde-PSID cohorts), with metrics aggregated over 10 semi-synthetic realizations.", "Experimental setup",
      "we evaluate models on the semi-synthetic RealCause-Lalonde benchmark (LaLonde, 1986; Neal et al., 2020)."),
     ("Nuisance models of the classical baselines are selected with FLAML AutoML, run separately per nuisance, estimator, realization and cohort, with a 900-second budget and 3-fold cross-validation.", "Experimental setup",
      "To provide strong, competitive baselines, all underlying nuisance models are selected via FLAML AutoML (v2.3.5; Wang et al. (2021)) run independently per nuisance, per estimator, per RealCause realization, and per cohort with a 900-second budget and 3-fold cross-validation."),
     ("The CFMs are frozen pretrained checkpoints applied without any parameter or hyperparameter tuning.", "Experimental setup",
      "These models are downloaded out-of-the-box from their respective sources and applied without any parameter or hyperparameter tuning."),
     ("Without being trained on the Lalonde data distributions, the CFMs are reported to be competitive with the classical estimators.", "Results and Discussion",
      "Despite not being trained on the Lalonde data distributions, CFMs are remarkably competitive with classical estimators."),
     ("Runtime counts training, tuning and inference for classical baselines but only inference for CFMs; CFM pretraining is excluded.", "Experimental setup",
      "This means we include training, tuning, and inference for classical baselines, but only inference for CFMs since this is the only step we perform."),
   ],
   "notes": "Tutorial/introduction paper with its own benchmark section. Authors are affiliated with Layer 6 AI and TD Bank Group; no competing-interest statement was found in the text. No exact family tag for causal foundation models; tabular-foundation-model used as closest."},

  {"id": "arxiv-2609.01262",
   "title": "Solving In-Table Prediction Problems by Deep Neural Networks with Performance Evaluation Using Synthetic Data",
   "authors": ["Xiao Zhao", "Daniela Oelke"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.01262"},
   "tasks": ["tabular-regression"], "fam": ["deep-learning", "tabular-mlp", "tabular-attention"], "par": ["self-supervised"],
   "proposes": ["In-Table Prediction (ITP) problem; self-supervised column masking with an embedding layer for numerical and empty values"],
   "claims": [
     ("The paper applies self-supervised learning to in-table prediction by randomly masking columns and using them as learning targets.", "Abstract",
      "A self-supervised learning approach is applied to address this problem by randomly selecting columns to be masked out and used as learning targets."),
     ("A new neural layer is proposed that embeds both numerical and empty values of continuous features.", "Abstract",
      "To handle missing values in continuous features, a novel neural layer is proposed to embed both numerical and empty values."),
     ("On the synthetic data, the attention-based network outperforms MLP and ResNet when enough training examples are available and a relatively large embedding length is chosen.", "Abstract",
      "We conclude that, the attention-based structure outperforms the other two networks, when a sufficiently large number of training examples is available and a relatively large embedding length is chosen."),
     ("Network structures and learning rate are fixed and no hyperparameter tuning of the model structures is done; early stopping uses a validation set.", "Training strategy",
      "Hyperparameter tuning of selected model structures is not done in this work."),
     ("The evaluation is limited to two synthetic three-column relationships with known dependencies, so the trends may not transfer to larger or real-world tables.", "Conclusion",
      "The evaluation is limited to two synthetic, three-column relationships with predefined, known dependencies."),
   ],
   "notes": "Only the three neural architectures are compared; no comparison against imputation methods (kNNimpute, missForest, MICE are mentioned in related work) or tree models was found in the text. Task tag approximate: ITP predicts masked continuous columns; the paper calls it slightly different from table imputation, so tabular-imputation is not used."},

  {"id": "arxiv-2609.29690",
   "title": "Predicting Symptoms of Amotivation and Anhedonia among University Students with a Novel Oversampling Method",
   "authors": ["Dang Nguyen", "Bao Duong", "Arun Kumar", "Dat Phan-Trong", "Julian Berk", "Taylor Braund", "Kien Do", "Debopriyo Bal",
               "Wu Yi Zheng", "Leonard Hoon", "Jill Newby", "Helen Christensen", "Svetha Venkatesh", "Alexis Whitton", "Sunil Gupta"],
   "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.29690"},
   "tasks": ["tabular-classification"], "fam": ["imbalance-resampling", "gradient-boosted-trees", "random-forests"], "par": ["supervised"],
   "proposes": ["SMOTE-PRED: SMOTE oversampling that predicts nominal variables with a predictive model (XGBoost) instead of interpolating them"],
   "claims": [
     ("SMOTE-PRED generates nominal variables with a predictive model rather than by interpolation.", "Abstract",
      "Our approach leverages a predictive model to generate nominal variables, rather than interpolating them."),
     ("On a GPS location dataset from university students, the method is reported to be significantly better than existing oversampling approaches for predicting elevated amotivation and anhedonia symptoms.", "Abstract",
      "We validate our method on a large-scale GPS location dataset collected from university students and demonstrate that it is significantly better than existing oversampling approaches in predicting elevated symptoms of amotivation and anhedonia."),
     ("The oversampling baselines use default hyperparameters from their libraries.", "Experimental setup",
      "For the baselines, we use default hyper-parameters as suggested in the library/package."),
     ("The downstream classifiers (kNN, SVM, DT, RF, XGBoost) are tuned on the training set with ten-fold cross-validation.", "Experimental setup",
      "We tune their hyper-parameters (see Table 4) on the training set by using ten-fold cross-validation."),
     ("Experiments are repeated ten times with random 90/10 train/test splits and the average AUC is reported.", "Experimental setup",
      "In each time, we construct training and test sets by randomly splitting the dataset into 90% for training and 10% for testing."),
     ("kNN was chosen as the default classifier for the following experiments because it was the most effective classifier in the reported comparison.", "Results and discussions",
      "As kNN is the most effective classifier (it works well with not only our method SMOTE-PRED but also AdaSyn, SMOTE, and SMOTE-NC), we select it as the default classifier for our following experiments."),
   ],
   "notes": "Single private dataset (Vibe Up trial). No statistical significance test was found in the text (searched for significan, t-test, p-value, Wilcoxon) despite the word 'significantly'. Besides imbalance-resampling, the tree family tags reflect the XGBoost predictor inside SMOTE-PRED and the downstream classifiers."},

  {"id": "arxiv-2608.30337",
   "title": "Coarse composition suffices: tabular in-context learning for multi-activity antimicrobial peptide profiling",
   "authors": ["Anuj Pal", "Raunak Kumar", "Dhruvi Solanki", "Parikshit Pareek", "Juhi Singh", "Jitin Singla"],
   "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2608.30337"},
   "tasks": ["tabular-classification"], "fam": ["tabular-foundation-model"], "par": ["in-context-learning"],
   "proposes": ["Sequence-descriptor + TabPFN pipeline with multi-label transforms (label powerset, classifier chains) for ESCAPE"],
   "claims": [
     ("A sequence-only pipeline of 330 interpretable descriptors with TabPFN, without gradient training or hyperparameter search, is reported to match and surpass multimodal structure-conditioned deep models on ESCAPE.", "Abstract",
      "We show that a simple, sequence-only pipeline can match and surpass these methods by combining 330 interpretable sequence descriptors with TabPFN, a tabular foundation model that performs in-context prediction in a single forward pass without gradient-based training or hyperparameter search."),
     ("The gains persist under the prior state of the art's single-fold training protocol and are largest for remote homologues.", "Abstract",
      "The gains persist under the prior state-of-the-art single-fold training protocol, indicating they are not a training-set-size artefact, and are largest for remote homologues (+11.2 points below 30% sequence identity)."),
     ("No hyperparameter was tuned on ESCAPE at any stage.", "Experimental setup",
      "No hyperparameter was tuned on ESCAPE at any stage."),
     ("For a paired comparison, the released ESCAPE baseline checkpoints were re-run without retraining.", "ESCAPE baseline re-run and matched-protocol evaluation",
      "For a paired comparison, we re-ran the released ESCAPE baseline checkpoints (Best_model_Fold1.pth, Best_model_Fold2.pth) on our hardware without any retraining."),
     ("Honest F1 uses per-label thresholds chosen on out-of-fold predictions over the in-context set and frozen before testing; Max-F1, with thresholds chosen on the test set, is reported only as an optimistic upper bound.", "Supplementary (threshold metrics)",
      "Honest F1 uses per-label thresholds selected on 5-fold out-of-fold predictions over the in-context set and frozen before the test set is touched."),
     ("Stated limitations: antiparasitic activity is too sparse for firm conclusions, and homology is handled by stratification on the predefined split rather than holding out identity clusters.", "Discussion (limitations)",
      "Homology is handled by stratification on the predefined split rather than by holding out entire identity clusters."),
   ],
   "notes": "Benchmark: ESCAPE with its predefined split; TabPFN v3 (tabpfn 8.2.0), three seeds. Published baseline numbers are unpaired; paired comparisons are restricted to the 5,495 test peptides with structural maps."},

  {"id": "arxiv-2608.30392",
   "title": "Foundation Models Meet Agriculture: Challenges Beyond Pretraining",
   "authors": ["Vishal Nedungadi", "Xingguo Xiong", "Marc Rußwurm", "Ioannis N. Athanasiadis"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.30392", "code": "https://github.com/vishalned/CropBench"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["tabular-foundation-model", "random-forests", "deep-learning"],
   "par": ["supervised", "in-context-learning"],
   "proposes": ["Analysis of two bottlenecks (modality gap, task heterogeneity) for foundation models in agriculture, benchmarking EO FMs, TabPFN and supervised baselines"],
   "claims": [
     ("Agricultural tasks often need non-imagery modalities that EO foundation models cannot ingest, while a tabular foundation model handles this heterogeneity more naturally.", "Abstract",
      "agricultural downstream tasks frequently require diverse, non-imagery data modalities that earth observation foundation models are architecturally unequipped to ingest, while a foundation model built for tabular data handles this heterogeneity more naturally"),
     ("TabPFN, without geospatial or agricultural pretraining, matches or outperforms the foundation models across several datasets.", "Results",
      "We find that it matches or outperforms FMs across several datasets."),
     ("A standardized set of hyperparameters is used across datasets instead of per-dataset optimization, because labels are limited on several datasets and the goal is robustness rather than best achievable performance.", "Hyperparameter Policy",
      "We adopt a standardized set of hyperparameters across datasets."),
     ("The Random Forest uses 500 trees with default settings for all other hyperparameters.", "Model Configurations",
      "The Random Forest classifier/regressor is trained with 500 trees using the default settings for all remaining hyperparameters."),
     ("CY-Bench yield prediction uses chronological walk-forward validation on the final five years.", "Evaluation Splits",
      "Finally, to simulate operational forecasting for CY-Bench, we employ a chronological walk-forward validation strategy on the final 5 years."),
     ("Stated limitation: the baselines are traditional, simple methods rather than complex domain-specific models.", "Limitations",
      "Thirdly, the study utilizes traditional, simple methods as baselines, whereas a large body of literature exists detailing complex, domain-specific models designed for each individual task."),
   ],
   "notes": "Seven agricultural datasets (crop classification, phenology, yield). The discussion refers to a 'well-tuned tabular baseline', while the stated protocol uses fixed hyperparameters and a default-setting Random Forest. TabPFN version/configuration was not found in the text."},

  {"id": "arxiv-2608.28980",
   "title": "The Illusion of Replacement: Rethinking Specialized Machine Learning Models in the Foundation Model Era",
   "authors": ["Kiyan Rezaee"], "year": 2026, "version": "arXiv v3",
   "links": {"arxiv": "https://arxiv.org/abs/2608.28980", "code": "https://github.com/kiyan-rezaee/language-vs-structure"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["large-language-models", "tabular-foundation-model"], "par": ["in-context-learning"],
   "proposes": ["Review of whether language-mediated models replace specialized architectures, with a regime ladder and a proposed controlled experiment"],
   "claims": [
     ("The review draws on a corpus of 186 papers from 2016 to 2026 across nine modalities to ask whether structural assumptions can be acquired through language.", "Abstract",
      "This review asks whether such assumptions can instead be acquired through language, drawing on a corpus of 186 papers published between 2016 and 2026 across nine modalities"),
     ("Once structure itself is evaluated, no evidence of general replacement survives; where direct tests exist, apparent parity is traced to information asymmetry, benchmark contamination, or computation outside the language model.", "Abstract",
      "No evidence of general replacement survives once structure itself is evaluated: where direct tests exist, apparent parity is traceable to information asymmetry, benchmark contamination, or computation performed outside the language model."),
     ("For tabular data, the review concludes there is only a narrow form of functional replacement, confined to a regime where strong non-linguistic baselines lack the same advantage.", "Tabular Data",
      "Tabular data therefore illustrates a narrow form of functional replacement, confined to a regime in which strong non-linguistic baselines do not hold the same advantage."),
     ("Citing Purucker et al., the review states that TabArena and TALENT are dominated by small-to-medium IID datasets where tabular foundation models do well, and that this advantage weakens substantially under temporal and grouped shift.", "Datasets and Benchmarks",
      "TabArena and TALENT are dominated by small-to-medium IID tabular datasets, the regime in which tabular foundation models perform particularly well, whereas Purucker et al. [109]’s purpose-built alternative shows that this advantage weakens substantially under temporal and grouped shift."),
     ("Averaging over datasets of different structural difficulty, as in TabArena and TALENT, can produce a favorable mean while masking failures in harder or less-represented cases.", "Evaluation",
      "averaging across datasets with different structural difficulty, as in TabArena and TALENT, can produce a favorable mean while masking failures concentrated in harder or less-represented cases [109]."),
     ("Stated limitation: screening was done by a single author, so screening decisions cannot be reproduced by a second screener.", "Survey methodology",
      "Single-author screening introduces an important limitation: screening decisions cannot be independently reproduced by a second screener."),
   ],
   "notes": "Literature review without its own benchmark experiments; covers nine modalities, only the tabular parts are recorded here. Tags approximate."},

  {"id": "arxiv-2608.27489",
   "title": "A Correspondence Score for Validating Learned Patient Representations in Clinical Tabular Data",
   "authors": ["Majid Lotfian Delouee", "Sjors G. J. G. In 't Veld", "Martijn C. Schut"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.27489", "code": "https://github.com/majid-lotfian/Embedding-Space-Discovery"},
   "tasks": ["tabular-classification"], "fam": ["tabular-attention", "deep-learning"], "par": ["unsupervised"],
   "proposes": ["Correspondence score (CR-score / CE-score) combining similarity-preservation metrics with Bayesian-optimized dataset-specific weights"],
   "claims": [
     ("The paper proposes a correspondence score to assess whether learned patient representations preserve clinically meaningful relationships in the original data.", "Abstract",
      "Therefore, we propose a correspondence score to assess whether learned patient representations preserve clinically meaningful relationships observed in the original data."),
     ("Representations from five tabular foundation models and six classical transformation techniques were assessed on four datasets.", "Abstract",
      "Representations generated by five tabular foundation models and six classical transformation techniques were assessed across four datasets to evaluate the robustness and consistency of correspondence estimates across different patient populations and data distributions."),
     ("The models labeled foundation models preserved correspondence more consistently than classical approaches, with reported improvements from about 5% to over 125%.", "Abstract",
      "Foundation models preserved correspondence more consistently than classical approaches, with improvements ranging from approximately 5% to over 125%, providing principled, pre-deployment justification for method selection."),
     ("The evaluated 'foundation models' are deep tabular architectures trained within the experimental setting, not pretrained on large external tabular corpora.", "Results",
      "The evaluated models represent widely used deep tabular architectures and were trained within the experimental setting rather than being pretrained on large external tabular corpora."),
     ("Metric weights of the score are learned per dataset and transformation direction with Bayesian optimization.", "Correspondence Score",
      "We therefore use Bayesian optimization to learn a dataset-specific weight vector over the direction-specific metrics, separately for reduction and expansion."),
     ("Stated limitation: the empirical evaluation focuses on routine blood count data.", "Generalizability and limitations",
      "The empirical evaluation in this study focuses on routine blood count data, a well-standardized clinical modality available across institutions and with established clinical interpretation."),
   ],
   "notes": "The 'tabular foundation models' are TransTab, TabTransformer, FT-Transformer, SAINT and TabNet trained per dataset. Label-free evaluation (outcome labels removed). The weight optimization objective (stated in the method) maximizes the average composite score across the evaluated representations. No task tag fits (representation-quality evaluation); tabular-classification used as closest."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
