"""候補 Issue #1(表形式データ)で承認された論文 10 本のカード(バッチ cand_2026_10_b02)。
各論文の主張と評価方法(ベンチマーク・データ規模の上限・ベースラインの調整方法・利益相反)を記録する。結果表の数値は記録しない。
書誌(著者・版・年)は scratchpad のバッチ JSON(arXiv API の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

CLS = ["tabular-classification"]
REG = ["tabular-regression"]
BOTH = CLS + REG

SPECS = [
  {"id": "arxiv-2608.18919", "title": "Lost in Aggregation: How Benchmarks Overlook Irreplaceable Model Strengths",
   "authors": ["Andrej Tschalzev", "Stefan Lüdtke", "Heiner Stuckenschmidt", "Christian Bartelt"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.18919"},
   "tasks": BOTH, "fam": ["tabular-foundation-model", "gradient-boosted-trees", "tabular-mlp"], "par": ["supervised", "in-context-learning"],
   "proposes": ["Peak-performance-frontier metrics for benchmarks (irreplaceability, sufficiency, fallibility)"],
   "claims": [
     ("Benchmark evaluation should also consider a per-dataset peak performance frontier, defined by the best statistically supported performance on each dataset.", "Abstract",
      "We argue that benchmark evaluation should also consider the data-centric peak performance frontier, defined by the best statistically supported performance achieved on each dataset."),
     ("On TabArena, common aggregation metrics are highly correlated, mostly measure consistency and failure avoidance, and are much less aligned with dataset-level irreplaceability.", "Abstract",
      "Applying this framework to the TabArena benchmark, we find that common aggregation metrics are highly correlated and largely measure consistency and avoiding failures, while being much less aligned with dataset-level irreplaceability."),
     ("The analysis uses TabArena, a maintained benchmark with a live leaderboard and public evaluation results, which currently comprises 27 models on 51 curated datasets.", "Experimental setup",
      "using a stricter data curation and more extensive evaluation protocol, and currently comprises 27 models evaluated on 51 carefully curated datasets."),
     ("All models benefit from tuning on most datasets; foundation models can only be compared adequately when traditional alternatives are appropriately tuned.", "Appendix",
      "This implies that, even though modern foundation models often perform well by default, they can only be compared adequately when the traditional alternatives are appropriately tuned."),
     ("RealMLP, ranked first at TabArena's publication, is never irreplaceable in this analysis; its strength lies mainly in avoiding poor outcomes.", "Results",
      "yet in our analysis it ranks 13th on sufficiency, is never irreplaceable"),
     ("The first author (Tschalzev) is listed as a co-author of the TabArena paper whose results are analysed; the paper does not discuss this as a conflict of interest.", "References",
      "Erickson, N., Purucker, L., Tschalzev, A.,"),
   ],
   "notes": "Analysis paper over TabArena live-leaderboard results (June 2026); no new model is proposed. Per-dataset superiority is decided with a one-sided Wilcoxon signed-rank test (alpha = 0.05) on paired fold-wise differences (method section). A footnote also says TabSTAR's strong performance may result from leaks, since part of the TabArena datasets were used for its pretraining."},

  {"id": "arxiv-2609.36108", "title": "LoopICL: Looping a single transformer block to solve tabular tasks",
   "authors": ["Amir Rezaei Balef", "Katharina Eggensperger"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.36108", "code": "https://github.com/amirbalef/loopicl"},
   "tasks": CLS, "fam": ["tabular-foundation-model", "tabular-attention"], "par": ["in-context-learning"],
   "proposes": ["LoopICL (looped single-block transformer for tabular ICL with learned early exit)"],
   "claims": [
     ("LoopICL is a looped transformer whose design decouples parameter count from computational depth.", "Abstract",
      "We introduce LoopICL, a looped transformer whose core design decouples parameter count from computational depth."),
     ("In its standard setting, LoopICL performs competitively with TabICLv2 on TabArena and TALENT at the same FLOPs while using far fewer parameters.", "Abstract",
      "In its standard setting, LoopICL performs competitively with TabICLv2 on TabArena and TALENT at the same computational cost (FLOPs), while using nearly 90% fewer parameters."),
     ("Ablations use intermediate checkpoints evaluated on synthetic prior tasks and on 10 folds of the 54-dataset development set used by TabICLv2 and TabPFNv2, without ensembling.", "Experiments",
      "We study classification performance averaged across 1,000 synthetic tasks sampled from the prior and across 10 folds of the 54 development set used in TabICLv2 and TabPFNv2 (Hollmann et al., 2025) , without any ensembling."),
     ("The final comparison is on TabArena and TALENT, with LoopICL evaluated as an ensemble of 8 members.", "Experiments",
      "We evaluate LoopICL using an ensemble of 8 members."),
     ("On TALENT all models are run on an A100 under identical conditions; on TabArena competitor runtimes are taken from the published benchmark and should not be used for direct runtime comparison.", "Experiments (Figure 7 caption)",
      "For TabArena, competitor runtimes are taken from the published benchmark and may reflect different hardware; these results should not be used for direct runtime comparisons of LoopICL with other baselines."),
     ("The current model supports classification only; regression is left for future work.", "Limitations",
      "The current model supports classification tasks; extending it to regression tasks is left for future work."),
   ],
   "notes": "How TabArena/TALENT baselines were configured (default vs tuned) is not stated in the text beyond 'Default' / 'Tuned + Ens.' labels in Figure 1."},

  {"id": "arxiv-2609.06912", "title": "From Synthetic Priors to Model Behavior: Structural Coverage in Tabular Foundation Models",
   "authors": ["He Zhao", "Ryan Thompson", "Daniel M. Steinberg", "Ashfaqur Rahman", "Edwin V. Bonilla", "Cheng Soon Ong"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.06912"},
   "tasks": BOTH, "fam": ["tabular-foundation-model"], "par": ["in-context-learning"],
   "proposes": ["Structural coverage and normalized density diagnostics relating synthetic TFM priors to benchmark tasks"],
   "claims": [
     ("The paper recovers or reconstructs the synthetic data generators of four TFMs and compares their generated tasks with datasets from two tabular benchmarks.", "Abstract",
      "We recover or reconstruct the synthetic data generators of four TFMs and compare their generated tasks with datasets from two widely used tabular benchmarks."),
     ("Stronger synthetic-to-benchmark support is generally associated with better relative model performance.", "Abstract",
      "Moreover, stronger synthetic-to-benchmark support is generally associated with better relative model performance."),
     ("TALENT contributes 200 classification and 100 regression datasets (January 15, 2025 archive, single official training split); TabArena contributes 38 classification and 13 regression datasets.", "Experimental settings",
      "TALENT contributes 200 classification and 100 regression datasets from its January 15, 2025 archive, using the single official training split."),
     ("The two benchmark collections are not independent: 26 TabArena dataset names also appear in TALENT.", "Experimental settings",
      "The two benchmark collections are not independent: 26 TABARENA dataset names also appear in TALENT with the same prediction type."),
     ("Predictive results come from released checkpoints; on TabArena they mix leaderboard results, an official processed artifact and a direct run, depending on the model.", "Appendix",
      "on TABARENA, we use leaderboard results for TABICLV2 and TABSWIFT, the official processed artifact for MITRA, and a direct run for TABICLV1."),
     ("The analysis is descriptive, not causal: generator identity is confounded with architecture, optimization, ensembling and inference choices.", "Method",
      "This analysis is descriptive rather than causal: generator identity is confounded with model architecture, optimization, ensembling, inference, and other model-specific choices."),
   ],
   "notes": "Only four TFMs could be analysed; the text says TabPFN, TabFM and EXAONE-Tabular were excluded because their generators are not released or not described in enough detail."},

  {"id": "arxiv-2609.07441", "title": "TabBench-Bio: A Living Benchmark for Machine Learning on High-Dimensional Biomedical Tables",
   "authors": ["Jules Kreuer", "Sofiane Ouaari", "Julia Hellmig", "Julius Braitinger", "Nico Pfeifer"], "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2609.07441", "code": "https://github.com/not-a-feature/TabBench-Bio", "url": "https://tabbench-bio.eu"},
   "tasks": BOTH, "fam": ["tabular-foundation-model", "gradient-boosted-trees", "random-forests", "tabular-mlp", "linear-models", "automl-systems"],
   "par": ["supervised", "in-context-learning"],
   "proposes": ["TabBench-Bio living benchmark (43 high-dimensional low-sample-size biomedical datasets, 4-by-7 feature-by-sample grid)"],
   "claims": [
     ("TabBench-Bio is a living, interactive benchmark of 43 biomedical datasets.", "Abstract",
      "We introduce TabBench-Bio, a living and interactive benchmark of 43 biomedical datasets spanning multiple domains."),
     ("At the reference cell (10,000 features, 100 training samples), RealTabPFN 2.5 has the highest point estimate, closely followed by TabPFN 3 and Logistic Regression.", "Abstract",
      "At the reference cell of 10,000 features and 100 training samples, RealTabPFN 2.5 has the highest point estimate, closely followed by TabPFN 3 and Logistic Regression."),
     ("All peer models use the default configuration of their AutoGluon adapter without per-dataset hyperparameter search, with bagging/stacking/ensembling disabled; tuning effects are not evaluated.", "Models and fitting regime",
      "Results concern these fixed configurations; the effects of bagging and hyperparameter tuning are not evaluated."),
     ("Evaluation uses 5-fold cross-validation with folds shared across all grid cells and models (group folds when biological group identifiers are available).", "Cross-validation and leakage control",
      "We use 5-fold cross-validation, with complementary folds shared across all cells and models."),
     ("Under AUROC (TabArena's binary metric) instead of macro-F1, Logistic Regression drops out of the leading group, so part of the contrast with TabArena reflects threshold placement rather than the domain alone.", "Discussion",
      "under AUROC, the metric TabArena uses for binary classification, Logistic Regression drops out of the leading group and the top 6 places are held by tabular foundation models (Appendix E), so part of the contrast reflects threshold placement rather than the domain alone."),
     ("Three benchmark datasets come from the same collection that supplied datasets used in TabDPT pretraining, so TabDPT results on them should be interpreted with this overlap in mind.", "Limitations",
      "TabDPT performance on these related datasets should therefore be interpreted with this overlap in mind."),
   ],
   "notes": "Dataset selection required (generally) at least 70 samples and 1,000 features. AutoGluon extreme preset (1 h) only at two prespecified cells. Fit and predict each have a 1-hour timeout; failures are imputed with the constant-predictor score."},

  {"id": "arxiv-2608.28209", "title": "Generalized Context in Cross Attention for Transfer Learning of Disjoint Tabular Data",
   "authors": ["Kazi F. Akhter", "Ibna Kowsar", "Manar D. Samad"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.28209"},
   "tasks": CLS, "fam": ["tabular-attention", "deep-learning"], "par": ["supervised", "self-supervised"],
   "proposes": ["CATTLE (Cross-domain Attention Transfer Learning via transferred key/value projection weights)"],
   "claims": [
     ("The paper introduces generalized context learning to remove the requirement of shared features across source and target domains.", "Abstract",
      "This paper introduces generalized context learning to remove the requirement of shared features across domains."),
     ("On ten disjoint source-target pairs, CATTLE learns generalized context from a single source dataset and is rank-wise and statistically superior to nine baselines.", "Abstract",
      "show that CATTLE can learn generalized context from a single source data set and is rank-wise and statistically superior to nine state-of-the-art baselines"),
     ("The study uses 14 OpenML datasets (nine source, five target) with 540 to 70000 samples and 8 to 76 features.", "Experiments",
      "The data sets have varying mixes of numerical and categorical features, sample sizes ranging from 540 to 70000, and feature dimensions ranging from 8 to 76."),
     ("Data are split 70:10:20 and resampled with ten random seeds.", "Model implementation and evaluation",
      "Data with 70:10:20 splits are randomly sampled ten times using ten random seeds to facilitate statistical comparison of model performance."),
     ("Models are tuned with 100 Optuna trials of random sampling evaluated on the validation set; the best validated model is reported on the test fold.", "Model implementation and evaluation",
      "In each of the 100 Optuna trials, a set of hyperparameter values is randomly sampled and evaluated on the validation set."),
     ("Traditional ML (XGBoost, logistic regression) performs strongly across most datasets, ranking better than the deep learning baselines without transfer.", "Results",
      "Traditional machine learning methods, particularly XGBoost and logistic regression, consistently achieve strong performance across most data sets."),
   ],
   "notes": "Code URL in the PDF text is garbled by extraction (contains an em dash), so it is not recorded in links. Tabular foundation models (e.g. TabPFNv2) are not among the nine baselines."},

  {"id": "arxiv-2608.27882", "title": "SOMTab: Set-Order Mamba for Efficient Tabular In-Context Learning",
   "authors": ["Hao Wang", "Siyu Zhang", "Wei Ma"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.27882"},
   "tasks": CLS, "fam": ["tabular-foundation-model"], "par": ["in-context-learning"],
   "proposes": ["SOMTab (Set-Order Mamba encoder with attention-based ICL reader)", "DCH-TailMix synthetic prior"],
   "claims": [
     ("SOMTab is a Set-Order Mamba architecture for efficient tabular in-context learning.", "Abstract",
      "We introduce SOMTab, a Set-Order Mamba architecture for efficient tabular in-context learning."),
     ("Across tabular benchmarks, SOMTab approaches strong Transformer-based TFMs while achieving faster inference and lower GPU memory.", "Abstract",
      "Across tabular benchmarks, SOMTab approaches the performance of strong Transformer-based tabular foundation models while achieving faster inference and lower GPU memory usage"),
     ("The main evaluation covers all TALENT classification datasets using the official splits (train+validation as context, official test split).", "Experimental setup",
      "We evaluate SOMTab on all classification datasets in the TALENT benchmark (Ye et al., 2024)."),
     ("Each baseline uses its official implementation and default configuration, including default preprocessing and ensemble size.", "Experimental setup",
      "For each baseline, we use its official implementation and default configuration, including the default preprocessing and ensemble size."),
     ("TabArena results are contextual only: public TabArena baselines keep their original H100 runs while SOMTab is measured on A100/H200.", "Results",
      "Because the public TabArena baselines retain their original H100 configurations while SOMTab is measured on A100 and H200 GPUs, the runtime comparison provides contextual positioning rather than a hardware-matched speed ranking."),
     ("Ablations are run on 15 TALENT datasets selected because SOMTab performs relatively less favorably than TabICLv2 on them in the main benchmark.", "Ablation studies",
      "To better reveal differences between variants, we evaluate them on 15 TALENT datasets where SOMTab performs relatively less favorably than TabICLv2 in the main benchmark."),
   ]},

  {"id": "arxiv-2608.25774", "title": "EXAONE Tabular 1.0 : Technical Report",
   "authors": ["Moonjung Eo", "Min-Kook Suh", "Hye-Seung Cho", "Jiwon Kim", "Seoyoon Kim", "Sangjun Nam", "Soonyoung Lee"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.25774", "code": "https://github.com/LGAI-Research/EXAONE-Tabular"},
   "tasks": BOTH, "fam": ["tabular-foundation-model", "tabular-attention"], "par": ["in-context-learning"],
   "proposes": ["EXAONE Tabular (Cross-Axis Summary Transformer, CAST)"],
   "claims": [
     ("EXAONE Tabular interleaves feature-axis attention within each item with support-conditioned item-axis attention within each feature at every layer.", "Abstract",
      "EXAONE Tabular interleaves feature-axis attention within each item with support-conditioned item-axis attention within each feature at every Transformer layer"),
     ("On TabArena, the classification model ranks first overall, surpassing tuned ensembles and 4-hour AutoML pipelines, while regression reaches the performance regime of the much larger TabFM.", "Abstract",
      "On TabArena, its 20.81M-parameter classification model ranks first overall, surpassing tuned ensembles and 4-hour AutoML pipelines, while regression reaches the performance regime of the 1.64B-parameter TabFM at roughly 1/11 the inference cost."),
     ("TabArena baselines are taken from the official leaderboard, not re-run, so their preprocessing, hyperparameter optimization and ensembling follow the TabArena protocol.", "Evaluation protocol",
      "For TabArena, we use the results reported on the official leaderboard rather than re-running each comparison model."),
     ("On BCCO and TALENT the comparison is only against six tabular foundation models (no GBDT or neural baselines).", "Evaluation protocol",
      "For BCCO and TALENT, we conduct a controlled comparison against six tabular foundation models: TabSwift [31], TabDPT [23], TabPFN-3 [15], TabICLv2 [16], LimiX [19], and TabFM [18]."),
     ("On BCCO and TALENT the training/in-context support set is capped at 50,000 samples per fold.", "Evaluation protocol",
      "To control computational cost across datasets of different scales, the training or in-context support set was capped at 50,000 samples per fold for both classification and regression."),
     ("The model is developed by LG AI Research (company report on its own model).", "Introduction",
      "EXAONE Tabular is LG AI Research’s first tabular foundation model family"),
   ],
   "notes": "Figure captions state that EXAONE Tabular is evaluated in a single untuned default configuration. In TALENT, 12 datasets with more than 10 classes were excluded. ScoringBench results are taken from its live leaderboard (5-fold CV, at most 3,000 observations per dataset)."},

  {"id": "arxiv-2608.18849", "title": "GEAR: Generative Expansion and Real Anchoring for Two-Stage Distillation of Tabular Foundation Models",
   "authors": ["Qi Qin", "Jiajie Zhu", "Dali Chen", "Yuzhao Zhang", "Jia-Xing Han", "Peng Zhang", "Ying Yan", "Yifan Sun", "Yu Su"], "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2608.18849"},
   "tasks": CLS + ["model-compression"], "fam": ["knowledge-distillation", "tabular-foundation-model", "tabular-mlp", "gradient-boosted-trees"], "par": ["in-context-learning", "supervised"],
   "proposes": ["GEAR (two-stage distillation of TFMs: generative query expansion + out-of-fold real-data anchoring)"],
   "claims": [
     ("GEAR distills TFMs into lightweight MLP or tree-based predictors deployable on commodity CPUs.", "Abstract",
      "We propose GEAR (Generative Expansion and Real Anchoring), a modular two-stage framework that distills TFMs into lightweight MLP or tree-based predictors that can be deployed on commodity CPUs."),
     ("Stage 2 uses out-of-fold teacher predictions on real rows to avoid self-labeling leakage.", "Abstract",
      "Stage 2 re-anchors the student to the target distribution using real labels and out-of-fold teacher predictions, which avoids self-labeling leakage."),
     ("On binary tasks the gains transfer to LightGBM and XGBoost students, and all three student families outperform CatBoost in mean AUC.", "Abstract",
      "On binary tasks, the gains also transfer to LightGBM and XGBoost, and all three student families outperform CatBoost, the strongest non-TFM baseline, in mean AUC."),
     ("Evaluation is on TALENT and TabArena with ROC-AUC (binary) and macro one-vs-rest AUC (multiclass), averaged over five random runs.", "Experimental setup",
      "For all settings, we use ROC-AUC for binary classification and macro one-vs-rest AUC for multiclass classification; reported values are averaged over five random runs."),
     ("Detailed optimization settings and implementation are deferred to the supplementary material; how the supervised baselines (CatBoost, RealMLP, TabM) were tuned, and dataset counts or size limits, were not found in the main text.", "Experimental setup",
      "Detailed optimization settings and implementation are provided in the supplementary material."),
     ("The work covers classification and single-teacher distillation only.", "Conclusion",
      "Although this work focuses on classification and single-teacher distillation, GEAR could be extended to regression and multi-teacher distillation."),
   ],
   "notes": "Company affiliation: most authors are at Ant Digital Technologies, Ant Group (first author's work done during an internship there)."},

  {"id": "arxiv-2608.18026", "title": "TabNSM: Neural Sparse Mixer for Tabular Regression",
   "authors": ["Ali Eslamian", "Qiang Cheng"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.18026"},
   "tasks": REG, "fam": ["tabular-attention", "deep-learning"], "par": ["supervised"],
   "proposes": ["TabNSM (Adaptive Sparse Interaction Module, Multi-Stage Regression Head, GridLoss, RISE sampling)"],
   "claims": [
     ("TabNSM is a regression framework that extends the authors' own earlier sparse-attention and mixer architectures (named TabNSA and TabMixer in the Introduction).", "Abstract",
      "We propose TabNSM, a scalable regression framework that extends our earlier sparse-attention and mixer architectures."),
     ("Across nine real-world regression benchmarks, TabNSM shows strong predictive performance and scalability, with consistent gains on high-dimensional and heterogeneous datasets.", "Abstract",
      "Across nine real-world regression benchmarks, TabNSM achieves strong predictive performance and practical scalability, with consistent gains on high-dimensional and heterogeneous datasets."),
     ("Evaluation uses a single 72/8/20 train/validation/test split with fixed random partitions across methods.", "Experiments and Results",
      "We use a 72/8/20 train/validation/test split with fixed random partitions across methods."),
     ("TabNSM's ASIM hyperparameters are selected with Optuna on the validation set.", "Experiments and Results",
      "The ASIM hyperparameters are selected via Optuna [46] on the validation set and fixed thereafter."),
     ("Baselines are tuned with Optuna using 3-fold CV on training+validation and 20 trials.", "Appendix",
      "Hyperparameter optimization was performed with Optuna (3-fold CV on training+validation, 20 trials, maximizing negative RMSE)."),
     ("Some baselines were not tuned for most large-dataset benchmarks (non-convergence or outlier results) and are not reported in Table 2.", "Appendix",
      "were not tuned for most large-dataset benchmarks, often resulting in non-convergence or outlier performance"),
   ],
   "notes": "Own collection of nine datasets (one, NACC/SCAN, requires a data use agreement). TabNSM's own Optuna trial budget is not stated in the main text."},

  {"id": "arxiv-2608.17957", "title": "Understanding the Surprising Generalization Properties of Tabular Foundation Models",
   "authors": ["Nour Shaheen", "Junwei Ma", "Alex Labach", "Frank Hutter", "Valentin Thomas", "Anthony L. Caterini"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.17957"},
   "tasks": BOTH, "fam": ["tabular-foundation-model"], "par": ["in-context-learning", "self-supervised"],
   "proposes": ["Task-centric, retrieval-based account of TFM generalization", "Column-level pre-processing of real-data pre-training corpora"],
   "claims": [
     ("Surprisingly strong transfer can emerge from self-supervised pre-training on a single real table.", "Abstract",
      "In contrast, we show that surprisingly strong transfer can emerge from self-supervised pre-training on just a single real table."),
     ("Fine-grained column-level pre-processing consistently improves downstream performance, while dataset-level filtering or deduplication does not.", "Abstract",
      "fine-grained column-level pre-processing consistently improves downstream performance, while no improvements are observed when we filter or deduplicate at the dataset level."),
     ("Single-table models are evaluated on the 72 OpenML CC-18 classification and 35 CTR-23 regression datasets, with no overlap between pre-training and evaluation.", "Generalization from single table training",
      "the 72 CC-18 [3] classification datasets and 35 CTR-23 [9] regression datasets."),
     ("Linear and random-forest baselines use scikit-learn defaults; XGBoost is the tuned baseline taken from McElfresh et al.; TabDPT is run from its public repository.", "Generalization from single table training",
      "XGBoost is the tuned baseline from McElfresh et al. [23], and TabDPT is computed from the public repository (Version 1.1, Apache-2.0 license)."),
     ("The large-corpus models are placed on the TabArena leaderboard against default-configuration baselines.", "Corpus experiments",
      "We contextualize these findings within the broader TabArena leaderboard in Figure 5, reporting Elo against some other default-configuration baselines, with details in Appendix C."),
     ("Several authors also authored TabDPT (reference list), whose architecture and pre-training procedure the study reuses; affiliations include Layer 6 AI and Prior Labs.", "References",
      "[22] Junwei Ma, Valentin Thomas, Rasa Hosseinzadeh, Hamidreza Kamkari, Alex Labach, Jesse C."),
   ],
   "notes": "The appendix leaderboard is TabArena-Lite (51 tasks, fold 0). The pre-training corpus excludes CC-18, CTR-23 and TabArena datasets."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
