"""候補 Issue #2(ドリフト検知)で承認された論文のうち、バッチ cand_2026_10_b13a の7本のカード。
各論文の主張と評価方法(検知指標・正解ドリフト点の作り方・比較手法とそのパラメータ・閾値の決め方)の記述を記録する。結果表の数値は記録しない。
書誌(著者・版・年・掲載誌・pdf_url・ライセンス)は scratchpad の batches/cand_2026_10_b13a.json(arXiv API / OpenAlex の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
  {"id": "arxiv-2609.04388",
   "title": "Candidate Comparability Before Promotion: Conditional Validation in Adaptive Network Intrusion Detection",
   "authors": ["Roberto Fernández-Barrios", "Iker Pastor-López", "Amaia Pikatza-Huerga", "Pablo García Bringas"], "year": 2026,
   "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.04388", "code": "https://github.com/roberto-fernandez-barrios/Validate-Before-Commit"},
   "tasks": ["dataset-shift-detection", "stream-classification", "tabular-classification"],
   "fam": ["two-sample-tests", "error-rate-drift-detectors", "window-based-drift-detectors", "kernel-methods"],
   "par": ["supervised", "streaming"],
   "proposes": ["Candidate-comparability audit before promotion in drift-triggered retraining (adaptive NIDS)",
                "Labeled-probe validation gate for incumbent-challenger promotion"],
   "claims": [
     ("The paper separates drift detection from model promotion: a drift alarm in an adaptive intrusion detection system detects change but does not establish that a retrained challenger should replace the deployed model.", "Abstract",
      "Adaptive network intrusion detection systems retrain classifiers after drift alarms, but an alarm detects change; it does not establish that a challenger should replace the deployed incumbent."),
     ("Main finding on construction: incumbent-owned frozen preprocessing amplified the apparent harm of promotion, and with self-contained challenger pipelines the mean full-drift harm did not persist.", "Abstract",
      "Incumbent-owned frozen preprocessing amplified apparent promotion harm; with self-contained challenger pipelines the mean full-drift harm did not persist."),
     ("Drift-monitor threshold: thresholds are set at the 0.95 quantile of detector scores over pre-drift calibration windows, and the retraining trigger requires consecutive alarms followed by a cooldown.", "Experimental setup (shared protocol constants)",
      "thresholds are the 0.95 quantile of detector scores over 30 pre-drift calibration windows; the trigger is 3 consecutive alarms with a 10-window cooldown; windows contain 128 flows."),
     ("In the common-harness comparison, DDM and ADWIN (river reference implementations) were used as retraining triggers at default parameters (default DDM thresholds, ADWIN delta = 0.002) with a small number of monitoring labels per window.", "Common-harness comparison",
      "the river reference implementations of DDM and ADWIN [17, 29] as retraining triggers with always-deploy on fire, run at their registered reference parameters — the implementations’ default DDM thresholds and ADWIN δ = 0.002 — on 8 monitoring labels per window (800 per stream)"),
     ("The authors caution that DDM and ADWIN were not tuned, so their results describe that configuration only; a parameter sweep would be needed before reading them as properties of the methods.", "Limitations",
      "DDM and ADWIN were run at their registered reference parameters and were not tuned; their cells characterize that configuration, and a parameter sweep would be required before reading them as properties of the methods."),
     ("Ground-truth drift is constructed: the core drift trajectories are gradual mixing ramps between real regime pools (covariate/regime drift); a P(y|x) change is not isolated and recurrent drift is not tested.", "Limitations",
      "The core drift trajectories are gradual mixing ramps between real regime pools (covariate/regime drift); we do not isolate a p(y|x) change, and recurrent drift is untested."),
   ],
   "notes": "Benchmarks: CICIDS2017, UNSW-NB15, ToN-IoT (binary benign vs attack). The paper is about promotion after drift alarms rather than about detection accuracy; drift monitors are two-sample statistics (energy distance, RBF-MMD, per-feature KS, JS divergence). "
            "The abstract also reports thirteen chronological replays on real time-ordered traffic in which always-deploy showed no net harm. Primary learner is SVC-RBF on 8-dim PCA; label-free baselines ATC and DoC also compared. Code also archived on Zenodo."},

  {"id": "arxiv-2609.24278",
   "title": "High-Dimensional Online Change Point Detection with Adaptive Thresholding and Interpretability",
   "authors": ["Sven Jacob", "Bardh Prenkaj", "Weijia Shao", "Gjergji Kasneci"], "year": 2026,
   "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.24278", "code": "https://github.com/jsve96/SWCPD_Code"},
   "tasks": ["change-point-detection"],
   "fam": ["two-sample-tests", "window-based-drift-detectors", "feature-attribution"],
   "par": ["unsupervised", "streaming"],
   "proposes": ["SWCPD: Sliced-Wasserstein-based online change point detection with an adaptive (Gamma-motivated) quantile threshold",
                "Contrastive explanations for detected change points"],
   "claims": [
     ("The paper proposes a self-adapting online change point detection algorithm combining a Sliced Wasserstein score with an adaptive quantile-based threshold.", "Abstract",
      "we propose a self-adapting online CPD algorithm that combines this SW-based score with an adaptive quantile-based threshold"),
     ("Main empirical claim: the method reduces false positives on average compared with popular online and offline CPD baselines while keeping competitive or better detection performance.", "Abstract",
      "Empirically, our method reduces false positives by at least 48% on average compared with popular online and offline CPD baselines, while maintaining competitive or superior detection performance"),
     ("Evaluation metrics: AUC and segmentation covering (following the evaluation protocol of Van den Burg & Williams and Ermshaus et al.), average detection delay and the average number of false positives, on one synthetic and four real datasets (MNIST, HAR, HASC, Occupancy) with annotated change points.", "Experiments (Change point detection)",
      "We report Area Under the Curve (AUC), segmentation covering scores (COV), average detection delay (DD), and the average number of false positives (FP)."),
     ("Synthetic ground truth: change points are created by injecting mean offsets into randomly selected features of a simulated stream of segments.", "Experiments (Synthetic Data)",
      "We randomly select a total of 3 features for which we inject a drift by offsetting the mean ci randomly sampled within (−3, 3) for each drifted feature."),
     ("SWCPD hyperparameters were set by a fixed set of heuristic rules (window shorter than the average segment length, small quantile level), with dataset-specific values reported.", "Appendix (Hyperparameter selection)",
      "For all experiments, hyperparameters were selected according to a fixed set of heuristic rules."),
     ("For the RIO-CPD baselines, window size and CUSUM threshold were grid-searched and the reported settings are those giving the best AUC; a separate validation split for this selection was not found in the text.", "Appendix (baseline hyperparameters, RIO)",
      "The following hyperparameter resulted in the best AUC scores for RIO-LE:"),
   ],
   "notes": "Online change point detection (unsupervised, multivariate), framed as closely related to concept drift detection; tagged change-point-detection because it is evaluated on CPD benchmarks with CPD metrics against online and offline CPD baselines. The explanation part is compared with Integrated Gradients, GradientShap and DeepLIFT (hence feature-attribution). Baselines: BOCPD, e-divisive, KCP, OT-CPD, RuLSIF, RIO-LE/RIO-LC, ClaSP, DeepRuLSIF, DeepCLF; several run at package defaults with one varied parameter (e.g. lag). "
            "No error-rate detectors (DDM/ADWIN) compared. Published in TMLR (08/2026) per the PDF header; venue not set because it is not in the batch metadata."},

  {"id": "arxiv-2609.25340",
   "title": "Concept Drift from a Causal Perspective",
   "authors": ["Eduardo V. L. Barboza", "Jean Paul Barddal", "Robert Sabourin", "Rafael M. O. Cruz"], "year": 2026,
   "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.25340", "code": "https://github.com/eduardovlb/CaDrift"},
   "tasks": ["tabular-data-generation", "stream-classification", "concept-drift-detection"],
   "fam": ["error-rate-drift-detectors", "tree-ensembles", "tabular-foundation-model"],
   "par": ["streaming", "supervised"],
   "proposes": ["Causal (SCM-based) taxonomy of concept drift", "CaDrift: SCM-based synthetic data stream generator with mechanism-level drift events"],
   "claims": [
     ("The paper proposes a taxonomy that categorizes drift events by their causal origin within a structural causal model.", "Abstract",
      "We propose a taxonomy that categorizes drift events by their causal origin, including changes in exogenous variables, endogenous mechanisms, confounders, and target-generating processes."),
     ("Main empirical claim: drifts with different causal origins induce distinct patterns of distribution shift and predictive behavior.", "Abstract",
      "Our experiments empirically characterize the distributional effects of each drift type and show that drifts with different causal origins induce distinct patterns of distribution shift and predictive behavior."),
     ("Ground-truth drift is synthetic: CaDrift streams are generated with drift events at known, regular positions (abrupt unless stated otherwise).", "Experimental setup (Distributional impact analysis)",
      "For this analysis, we generate streams of 20,000 samples with a drift event introduced every 2,000 samples."),
     ("Performance protocol: a Hoeffding Tree is evaluated test-then-train with immediate labels and with labels delayed by 100 samples, and is also coupled with DDM; DDM parameter settings were not found in the text.", "Experimental setup (Performance evaluation)",
      "we measure the predictive performance of the Hoeffding Tree (HT) classifier (Domingos & Hulten, 2000) under different drift scenarios in a test-then-train manner, considering a prompt label availability after the test, as well as when label availability is delayed by 100 samples"),
     ("Under endogenous drift with nonlinear mappers, DDM does not seem to help the Hoeffding Tree; its triggers appear to lower immediate accuracy more than not using DDM.", "Results (impact of causal drift events)",
      "DDM does not seem to provide any advantage over the HT – the triggers in concept drift actually seem to decrease the immediate accuracy more than if not using DDM."),
     ("Case study: CaDrift samples generated from a DAG inferred on ELEC2 are used to augment stream learners, including TabPFNv2.5 run with a sliding context window.", "Case study (ELEC2 data augmentation)",
      "In addition to the online learners, we also include TabPFNv2.5 (Grinsztajn et al., 2026), a transformer-based tabular classifier."),
   ],
   "notes": "Off-theme in part: the main contribution is a drift taxonomy and a synthetic stream generator, not a drift detector; no detection metrics (delay, false alarms) are reported. Tagged tabular-data-generation (synthetic stream generator) and stream-classification (Hoeffding Tree / online learners under drift); concept-drift-detection is kept only because drift effects are characterized (MMD, conditional KL) and DDM is used for adaptation. "
            "The augmentation case study compares IncA-DES (Barboza et al., 2025, i.e. the first author's own method), ARF and TabPFNv2.5; the class-generation design is described as similar to the prior-generation of TabPFN (Hollmann et al., 2025)."},

  {"id": "doi-10.1007_s44163-026-02063-9",
   "title": "Awareness based internal reliability monitoring of streaming models using incremental principal component analysis",
   "authors": ["Zainab Nadhim Jawad", "Balázs János Villányi"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Discover Artificial Intelligence",
   "links": {"doi": "https://doi.org/10.1007/s44163-026-02063-9"},
   "pdf_url": "https://link.springer.com/content/pdf/10.1007/s44163-026-02063-9.pdf", "license": "cc-by",
   "tasks": ["drift-detection"],
   "fam": ["reconstruction-based-detectors", "dimensionality-reduction-for-shift"],
   "par": ["unsupervised", "streaming"],
   "proposes": ["Label-free 'awareness' signal from normalized, smoothed Incremental PCA reconstruction residuals"],
   "claims": [
     ("The paper proposes a continuous, label-free internal reliability metric based on Incremental PCA reconstruction residuals.", "Abstract",
      "This paper introduces a continuous, label-free internal reliability metric built on an Incremental Principal Component Analysis (IPCA) backbone."),
     ("The authors state the observed differences are small, so the signal is better suited as a continuous reliability indicator than as a universal detector of frozen adaptation.", "Abstract",
      "The observed differences are small in magnitude, indicating that the awareness signal is more suitable as a continuous internal reliability indicator than as a universal detector of frozen adaptation."),
     ("Ground truth drift is synthetic: a gradual drift ramp is placed at a fixed interval chosen by the experimenters, not at an estimated drift location in the original (AI4I 2020, WSN) data.", "Research design (stream length and temporal segmentation)",
      "The selected interval was an experimental segmentation choice rather than an estimated drift location in the original datasets."),
     ("The injected drift is a small shift-and-scale of the standardized features that stays active after the ramp.", "Controlled drift injection",
      "At maximum drift intensity, every standardized feature was multiplied by 1.05 and shifted by 0.05 standardized units."),
     ("The authors state the synthetic shift-and-scale experiment is a reproducible stress test but does not establish general concept-drift detection performance.", "Discussion (Scope of the synthetic drift experiment)",
      "It is useful as a reproducible stress test, but it does not establish general concept-drift detection"),
     ("Limitation: only one fixed drift strength and two adaptation conditions (full adaptation, complete freezing) are tested.", "Limitations and future research",
      "The present experiment uses one fixed drift strength and two adaptation conditions: full adaptation and complete freezing."),
   ],
   "notes": "Datasets: AI4I 2020 predictive maintenance and a wireless sensor network dataset, both treated as unlabeled streams. No comparison with classical drift detectors (ADWIN, DDM, KSWIN) was found in the text; they appear only in related work. "
            "IPCA component count was chosen by minimizing reconstruction error on a temporal hold-out split. Authors declare no competing interests."},

  {"id": "arxiv-2609.09432",
   "title": "SCCM : Stream Cruise Control Method for Automated Drift Detection and Adaptation",
   "authors": ["Mohammad Abu-Shaira", "Weishi Shi"], "year": 2026,
   "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.09432", "code": "https://github.com/anonymous273800/SCCM"},
   "tasks": ["concept-drift-detection", "tabular-regression"],
   "fam": ["error-rate-drift-detectors", "window-based-drift-detectors", "linear-models"],
   "par": ["streaming", "supervised"],
   "proposes": ["SCCM: KPI-window drift detection with CFAR-inspired adaptive threshold, drift-magnitude-driven hyperparameter control and bounded recalibration for online regression"],
   "claims": [
     ("The paper presents SCCM, a framework combining drift detection and adaptation for online regression.", "Abstract",
      "This paper presents the Stream Cruise Control Method (SCCM ), a comprehensive framework for drift detection and adaptation in online regression."),
     ("Evaluation scope: SCCM is attached to four online regressors and evaluated on synthetic streams with abrupt, incremental and alternating gradual drift plus real-world datasets.", "Abstract",
      "SCCM is integrated with four online regression models and evaluated on 18 synthetic datasets covering abrupt, incremental, and alternating gradual drift, together with eight real-world datasets."),
     ("Baselines combine ADWIN or KSWIN with four adaptation strategies; the detectors use scikit-multiflow default settings.", "Experimental setup (Baseline Configuration Protocol)",
      "Specifically, ADWIN used δ = 0.002, while KSWIN used αKS = 0.005, WKS = 100, and SKS = 30."),
     ("No detector parameter search was done for the baselines; the authors argue that grid search over the evaluated stream would introduce look-ahead bias.", "Experimental setup (Baseline Configuration Protocol)",
      "Consequently, no detector candidate grid, designated pilot seed, separate pilot stream, or data-driven detector-parameter selection procedure was used."),
     ("Detection metrics (TP, FP, missed drifts, delay, precision, recall, F1) are computed only on synthetic streams, because the real datasets have no annotated drift locations.", "Drift-Alarm Quality Metrics and Alignment Protocol",
      "Because the real-world datasets do not provide annotated drift locations or known concept boundaries, ground-truth alarm-quality metrics are evaluated only on the synthetic datasets."),
     ("The alarm-matching parameters were applied identically to SCCM, ADWIN and KSWIN and fixed before the final comparative analysis, with a separate sensitivity analysis.", "Drift-Alarm Quality Metrics and Alignment Protocol",
      "These values are applied identically to SCCM , ADWIN, and KSWIN and were fixed before the final comparative analysis."),
   ],
   "notes": "Ground truth: synthetic streams with known drift points; a true positive is the earliest unmatched raw alarm within a post-drift tolerance window, all other alarms are false positives. "
            "SCCM alarms are scored at the consolidated episode level, while ADWIN/KSWIN raw alarms are scored without cooldown consolidation in the primary analysis (an episode-level comparison is also given). "
            "SCCM's own threshold multiplier is reported as z = 1.5 in the configuration tables; how that value was chosen was not found in the text. Learners: RLS, PA, LMS, OLR-WA (OLR-WA, ref. [40], is an earlier paper by the first author)."},

  {"id": "arxiv-2608.23893",
   "title": "Provenance Guided Incremental Learning Under Evolving Concept Definitions",
   "authors": ["Ismail Lamaakal"], "year": 2026,
   "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.23893"},
   "tasks": ["stream-classification", "tabular-classification", "graph-node-prediction"],
   "fam": ["window-based-drift-detectors", "gradient-boosted-trees", "tabular-mlp"],
   "par": ["supervised", "streaming"],
   "proposes": ["Provenance-guided incremental learning for rule-induced concept shift (rule-delta compilation, provenance tracing, localized relabeling, incremental repair)",
                "RuleShift-Bench"],
   "claims": [
     ("The paper proposes a provenance-guided incremental learning framework for explicitly revised concept definitions, which localizes the records that need relabeling.", "Abstract",
      "We introduce a provenance-guided incremental learning framework that compiles consecutive concept definitions into a structured rule delta, traces the changed components through historical provenance"),
     ("It introduces RuleShift-Bench, where concept shifts are controlled rule revisions over financial, demographic, cybersecurity and graph data (so the shift points are known by construction).", "Abstract",
      "We also introduce RuleShift-Bench, spanning financial, demographic, cybersecurity, and graph-structured data with threshold, predicate, logical, relational, recurring, and mixed concept revisions."),
     ("Main empirical claim on cost: provenance-guided repair has a much lower average update latency than complete relabeling and retraining.", "Abstract",
      "Its average update latency is 179 s compared with 993 s for complete relabeling and retraining."),
     ("Rule thresholds, predicate statistics and provenance structures are built from the training partition only (temporal or official splits with a validation partition).", "Experimental setup",
      "All rule thresholds, predicate statistics, and provenance structures are constructed using training data only."),
     ("An ADWIN-triggered adaptation pipeline is included as a representative drift-detection baseline; its ADWIN parameter settings were not found in the text.", "Comparison Methods",
      "We further include an ADWIN-triggered adaptation pipeline as a representative drift-detection baseline."),
     ("Limitation: the benefit decreases when revisions are global, provenance is incomplete, definitions are not fully executable, or relational/graph dependencies enlarge the candidate region.", "Conclusion",
      "Its main limitations arise when concept revisions are global, historical provenance is incomplete, concept definitions are not fully executable, or highly coupled relational and graph dependencies enlarge the candidate region, in which cases the benefit of selective maintenance decreases."),
   ],
   "notes": "Off-theme: this is not a drift detection paper; the concept change is known explicitly (rule revision) and the paper is about efficient relabeling/repair. Tagged stream-classification (keeping a deployed predictor accurate after concept revisions) rather than a detection task. "
            "Datasets: PaySim, Census-Income (KDD), UNSW-NB15, ogbn-arxiv. Predictors: XGBoost, an MLP, Hoeffding Adaptive Tree, with fixed hyperparameters stated in the text (no tuning described)."},

  {"id": "arxiv-2608.17824",
   "title": "Reshaping the SDLC for Data- and AI-Centric Systems",
   "authors": ["Mamdouh Alenezi"], "year": 2026,
   "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.17824"},
   "tasks": ["drift-detection"],
   "fam": ["two-sample-tests"],
   "par": [],
   "proposes": ["Five-layer adaptive lifecycle framework (artifact, contract, gate, control, governance) for data- and AI-centric systems",
                "Conceptual research model linking data-engineering integration to lifecycle outcomes"],
   "claims": [
     ("The paper proposes a five-layer adaptive lifecycle framework in which maintenance becomes closed-loop control over drifting configurations.", "Abstract",
      "we synthesize these results into an adaptive, five-layer lifecycle framework—artifact, contract, gate, control, and governance layers—articulated as testable design propositions, in which maintenance becomes a closed-loop control problem over drifting configurations."),
     ("Drift monitoring is framed as part of a control loop: monitors estimate distance from the validated operating envelope, and controllers decide among continue, retrain, rollback, fallback or escalate.", "Monitoring, Operations, and Maintenance",
      "In lifecycle terms, drift converts maintenance from a reactive, ticket-driven activity into the closed-loop control problem of Equation (1): monitors estimate the deployed configuration’s distance from its validated operating envelope"),
     ("Citing Rabanser et al., the paper says many practical shift-detection methods fail quietly, so drift detection should be treated as an engineered, tested component (secondary citation, not a new result).", "Monitoring, Operations, and Maintenance",
      "Rabanser et al. showed empirically that many practical shift-detection methods fail quietly, implying that drift detection is itself an engineered, tested component [38]."),
     ("The author notes that the evidence base consists mostly of reviews, taxonomies, interviews/surveys and single-organization reports, with comparable experiments and pooled effect sizes largely absent.", "Evidence Base, Limitations, and Research Agenda",
      "However, the evidence base is dominated by literature reviews, taxonomies, interview and survey studies, and single-organization experience reports; comparable experiments, participant-level statistics, and pooled effect sizes are largely absent."),
     ("Limitation: as a conceptual synthesis it provides no new empirical data, and its formal model is descriptive.", "Evidence Base, Limitations, and Research Agenda",
      "As a conceptual synthesis it does not itself contribute new empirical data; the formal model of Section 3 is descriptive rather than predictive"),
   ],
   "notes": "Off-theme: a conceptual software-engineering (MLOps/DataOps/LLMOps lifecycle) paper with no experiments and no drift detector evaluation. Tagged drift-detection only as the closest task. No method-family tag fits; two-sample-tests is kept as the closest family because the schema requires a non-empty family list and the paper's only specific reference on shift detection (Rabanser et al., c3) concerns shift-detection methods; the paper itself evaluates no method. "
            "Author affiliation: SDAIA Academy, Saudi Data and Artificial Intelligence Authority."},
]

build(SPECS, base_note="Approved from candidate issue #2 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
