"""候補 Issue #1(表データ)で承認された論文のうち batch cand_2026_10_b06 の10本のカード。
主張と評価方法(ベンチマーク・チューニング・利益相反)だけを記録する。結果表の数値は記録しない。
書誌(著者・版・年)は scratchpad の batch メタデータ(arXiv API 由来)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
  {"id": "arxiv-2609.32898",
   "title": "When Less Compute Is More: Adaptive Early Exit Improves Pretrained Outlier Detection",
   "authors": ["Tianyang Zhou", "Leman Akoglu"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.32898"},
   "tasks": ["tabular-classification", "model-compression"], "fam": ["tabular-foundation-model"], "par": ["unsupervised", "in-context-learning"],
   "proposes": ["ROUT (pretrained plug-in router selecting a dataset-specific exit layer for pretrained tabular outlier detectors)"],
   "claims": [
     ("The paper presents what it calls the first study of depth-adaptive early exit for pretrained (tabular) outlier detection models.", "Abstract",
      "we present the first study of depth-adaptive early-exit for pretrained outlier detection models"),
     ("Exiting at the optimal (per-dataset oracle) intermediate layer can improve detection on real-world benchmarks on average, consistently across three foundation models; the paper identifies context pollution (outliers among in-context samples) as a key mechanism.", "Abstract",
      "can also improve detection performance on diverse real-world benchmarks by 4.7–7.3% on average, consistent across three distinct foundation models"),
     ("Evaluation uses three real-world outlier detection benchmarks (ADBench, OddBench, OvRBench) plus the synthetic SynBench, under clean and polluted context.", "Experiments",
      "We evaluate ROUT on ADBench (Han et al., 2022), OddBench, and OvRBench (Ding et al., 2026a), three real-world outlier detection benchmarks comprising 47, 690, and 755 datasets, respectively"),
     ("For the LA-Entropy early-exit baseline, the entropy threshold is tuned on synthetic validation datasets and then fixed for all test datasets (not tuned on test labels).", "Experiments",
      "We tune τ on synthetic validation datasets and keep it fixed across all test datasets."),
     ("The Oracle (per-dataset best exit layer) and Best fixed layer rows are selected with ground-truth test AUROCs and are reported only as references, not as deployable methods.", "Experiments",
      "Both use ground-truth test AUROCs and are reported as references."),
     ("Per the reference list, author Leman Akoglu co-authored OutFormer, one of the three evaluated backbones; the paper does not discuss this as a conflict of interest.", "References",
      "Xueying Ding, Haomin Wen, Simon Klüttermann, and Leman Akoglu."),
   ],
   "notes": "Task is tabular outlier detection, for which no task tag exists; tabular-classification is the closest existing tag. "
            "The reference list also shows Akoglu as a co-author of MacrOData (Ding et al., 2026a), the source of OddBench/OvRBench/SynBench. "
            "model-compression is tagged because depth-adaptive early exit reduces inference compute; no pruning/quantization/distillation family applies, so the family stays tabular-foundation-model."},

  {"id": "arxiv-2609.31306",
   "title": "Benchmarking Attention for Tabular Foundation Models",
   "authors": ["Maximilian Schambach", "Clemens Biehl", "Sam Thelin"], "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2609.31306", "code": "https://github.com/SAP-samples/tabular-attention-benchmark"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["tabular-foundation-model", "tabular-attention"], "par": ["in-context-learning"],
   "proposes": ["Reproducible benchmark of attention backends for row/column attention in tabular foundation models"],
   "claims": [
     ("The paper builds a reproducible benchmark of attention backends (SDPA, FlashAttention-2/3/4, vLLM, SageAttention) for the row/column attention used in tabular in-context learners.", "Abstract",
      "we create a reproducible benchmarking setup and study the unique characteristics of tabular attention across several backends"),
     ("The best backend differs between column and row attention and depends on hardware and model specifics.", "Abstract",
      "We find that the optimal backend choice differs between column and row attention and varies across hardware as well as model specifics"),
     ("The benchmark measures isolated kernel latency/throughput and memory on synthetic tabular tensors, not predictive accuracy.", "Benchmark setup",
      "measuring latency and memory consumption for isolated kernel throughput on synthetic tabular tensors"),
     ("The train-test (context-query) split handled differently by TabPFN/Mitra and ConTextTab is ignored; standard full bidirectional attention is benchmarked instead.", "Benchmark setup",
      "Instead, we evaluate standard full bi-directional attention."),
     ("Stated limitation: only isolated kernels with synthetic tensors are benchmarked, not end-to-end training or inference; only bfloat16, non-causal attention and batch size 1 are used.", "Limitations",
      "Our benchmark focuses on isolated attention kernels with synthetic tensors rather than end-to-end model training or inference"),
     ("Two of the authors (SAP SE) are co-authors of ConTextTab, one of the models whose attention pattern is benchmarked; the main head configuration is taken from that model's reference.", "References",
      "Marco Spinaci, Marek Polewczyk, Maximilian Schambach, and Sam Thelin."),
   ],
   "notes": "Kernel-throughput benchmark; no predictive task is evaluated, so task tags are approximate (tabular foundation models serve both classification and regression)."},

  {"id": "arxiv-2609.29814",
   "title": "SwitchPFN: Shared Switching Dynamics for Frozen In-Context Time Series Classification",
   "authors": ["Zhenyi Zhu", "Jacqueline Pang", "Peilin Shen", "Tianyi Song", "Tingwei Zhang", "Keyi Hu", "Kangjun Yin", "Shiwei Pu", "Yingbo Zhou", "Chen Shao"],
   "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.29814"},
   "tasks": ["time-series-classification"], "fam": ["tabular-foundation-model"], "par": ["in-context-learning", "supervised"],
   "proposes": ["SwitchPFN (shared-projection / regime-codebook time-series featurization for frozen TabPFN-v3)"],
   "claims": [
     ("SwitchPFN learns a shared projection and regime codebook from the training sequences so that local dynamics features are comparable across samples, and feeds the resulting table to a frozen TabPFN.", "Abstract",
      "We propose SwitchPFN, which learns a shared projection and regime codebook from the training sequences, making local dynamic operators and transition features directly comparable across samples."),
     ("On the evaluated benchmarks, SwitchPFN has the highest mean accuracy among the evaluated methods.", "Abstract",
      "Across the evaluated benchmarks, SwitchPFN achieves the highest mean accuracy among the evaluated methods, improving over the strongest baseline by 4.47% relatively."),
     ("Evaluation uses eight UEA multivariate time-series classification tasks with the official train/test splits.", "Experimental setup",
      "We evaluate eight University of East Anglia (UEA) tasks [33] covering five signal domains"),
     ("Several baselines (DTW, XGBoost, LSTM, Informer, DLinear) use historical three-run summaries, whereas the other methods use five repeats; baseline hyperparameter tuning is not described (not found in the text).", "Experimental setup",
      "DTW, XGBoost, LSTM, Informer, and DLinear use historical three-run summaries; other methods use five repeats."),
     ("SwitchPFN's own settings are frozen after a selection that uses only the training data.", "Experimental setup",
      "Settings are frozen after training-only selection."),
     ("The authors declare no conflicts of interest.", "Acknowledgments",
      "The authors declare no conflicts of interest."),
   ],
   "notes": "Time-series classification via a frozen tabular foundation model (TabPFN-v3) on a learned tabular featurization."},

  {"id": "arxiv-2609.29182",
   "title": "ScalarLens: Numerical Embeddings with Stable Coordinates and Contextual Responses for CTR Prediction",
   "authors": ["Heng Yao", "Tianying Liu", "Yulou Shu", "Yong He", "Chuan Yuan", "Kaibin Qiu", "Guowei Chen", "Jiayu Zhao", "Siyun Hou"],
   "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.29182"},
   "tasks": ["tabular-classification"], "fam": ["deep-learning"], "par": ["supervised"],
   "proposes": ["ScalarLens (numerical embedding with a stable per-value coordinate and a contextual response)"],
   "claims": [
     ("ScalarLens is a numerical-feature embedding for CTR models that keeps a stable coordinate for a value while adapting its interpretation to the sample's context.", "Abstract",
      "We introduce ScalaRLens, a numerical embedding that preserves what a value is while adapting how it should be interpreted."),
     ("In the primary evaluation (19 representations, three datasets, nine backbones, three seeds, original numerical scales), ScalarLens ranks first in most settings and second in the rest.", "Abstract",
      "In a 1,539-run primary evaluation covering 19 representations, three datasets, nine backbones, and three seeds, ScalaRLens ranks first in 25 of 27 settings on original numerical scales and second in the remaining two."),
     ("Datasets are AutoML-A/E from AutoML3 and Criteo, with Criteo's numerical fields kept without a log transform; backbones share one fixed training configuration with early stopping on validation AUC.", "Experiments",
      "AutoML-A/E come from AutoML3 [11]; Criteo preserves all 13 numerical fields without a shared logarithmic transformation."),
     ("No method gets dataset-specific hyperparameters, private preprocessing, or a different split.", "Experiments",
      "No method receives private preprocessing, a different split, or hyperparameters specific to a dataset."),
     ("Several baselines (DAE, DEER, NaryDis, DAES) are the authors' re-implementations from published descriptions, not official code.", "Experiments",
      "DAE, DEER, NaryDis, and DAES-Gate/Tran are implementations based on the published descriptions because no official module compatible with our code version was available"),
     ("Stated limitation: AutoML-A/E come from one family, all datasets informed development, and the 27 settings are correlated; random splits do not establish temporal or cross-family transfer.", "Discussion and Limitations",
      "AutoML-A/E share one family, all datasets informed development, and the 27 settings are correlated."),
   ],
   "notes": "CTR prediction (binary classification on tabular features). Most authors are affiliated with Ant Group or Alibaba per the title page."},

  {"id": "arxiv-2609.26855",
   "title": "QUARTET: Quad-branch cross-Attention and Random-walk Traces for Enhancing Transformers on Relational Graphs",
   "authors": ["Kyaw Hpone Myint", "Nan Jiang", "Xiang Li", "Zhe Wu", "Alexandre G. R. Day", "Pranab Mohanty", "Giri Iyengar"],
   "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2609.26855"},
   "tasks": ["tabular-classification", "graph-node-prediction"], "fam": ["graph-neural-networks"], "par": ["supervised"],
   "proposes": ["QUARTET (graph transformer with Causal Random Walk sampler and quad-branch cross-attention for relational databases)"],
   "claims": [
     ("QUARTET is a graph transformer for relational deep learning that uses full self-attention on local subgraphs plus cross-attention branches for global context.", "Abstract",
      "we introduce QUARTET, an expressive graph transformer architecture that applies full self-attention on local subgraphs while enriching global context through cross-attention branches"),
     ("The abstract claims QUARTET consistently matches or outperforms HGT and RelGT on the RelBench v1 classification tasks.", "Abstract",
      "Across the RELBENCH v1 classification tasks, QUARTET consistently matches or outperforms the current state-of-the-art graph transformer baselines (HGT and RelGT)."),
     ("The conclusion is more qualified: QUARTET matches or beats RelGT on eight of twelve tasks, and RelGT keeps an edge on a few large, stationary tasks.", "Conclusion",
      "matching or outperforming the original RelGT model on eight of twelve tasks and securing top test ROC-AUC on seven"),
     ("Evaluation: twelve binary classification tasks from seven RelBench datasets, ROC-AUC, reporting the test score of the model selected on the validation split.", "Experimental Setup",
      "We use ROC-AUC as the primary evaluation metric and report test ROC-AUC for the model selected on the validation split."),
     ("Baselines HGT and RelGT were reproduced from scratch under the shared RelBench v2 pipeline with the original authors' reported hyperparameters; baselines and QUARTET are averaged over four random seeds.", "Experimental Setup",
      "we reproduced both graph-transformer baselines (HGT and RelGT) from scratch under this shared v2 pipeline, utilizing the original authors’ reported hyper-parameters"),
     ("Baselines were not re-tuned because the RelBench v2 classification datasets are unchanged except for a leakage patch to one task.", "Appendix",
      "Re-tuning was deemed unnecessary because the classification datasets in RELBENCH v2 are unchanged to the prior version, aside from a patch to rel-event user-ignore that resolved temporal leakage."),
   ],
   "notes": "Relational-database (multi-table) entity classification, modelled as node prediction on a heterogeneous temporal graph. "
            "Tuning is asymmetric (Appendix A.3.2 and Table 5): baselines use published hyperparameters, the proposed model is tuned per task. Authors are affiliated with Capital One."},

  {"id": "arxiv-2609.23223",
   "title": "Stealing profits: Spread-based temporal hierarchy forecasting for day-ahead electricity markets",
   "authors": ["Arkadiusz Lipiecki", "Nikolaos Kourentzes", "Rafal Weron"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.23223"},
   "tasks": ["time-series-forecasting"], "fam": ["tabular-foundation-model", "linear-models", "deep-learning"], "par": ["in-context-learning", "supervised"],
   "proposes": ["Spread THieF (temporal hierarchy reconciliation of hourly prices and all intraday price spreads)"],
   "claims": [
     ("Jointly reconciling forecasts of hourly prices and all intraday price spreads improves performance across two European markets and three forecasting architectures.", "Abstract",
      "Here we show that a temporal hierarchy forecasting (THieF) framework that jointly reconciles forecasts of hourly electricity prices and all intraday price spreads consistently improves performance across two major European electricity markets and three different forecasting architectures."),
     ("The gains also hold for a pretrained TabPFN model.", "Abstract",
      "The gains persist even for a highly accurate pretrained TabPFN foundation model."),
     ("TabPFN-2 is used zero-shot, without tuning weights or hyperparameters, with a 3-year rolling window as the in-context support set.", "Forecasting models",
      "Forecasts are generated in the so-called zero-shot mode, i.e., without task-specific tuning of the model weights or hyperparameters."),
     ("Data come from two European day-ahead markets, German EPEX-DE and Spanish OMIE (public data spanning eight years).", "Datasets",
      "To ensure a sound assessment of the THieF approach, we consider two major European power markets: EPEX-DE (Germany) and OMIE (Spain)."),
     ("Statistical and economic rankings differ: TabPFN is the most accurate model, but NARX with Spread THieF gives the highest arbitrage profit.", "Conclusions",
      "although TabPFN is the most accurate model, NARX combined with Spread THieF yields the highest arbitrage profit in every market-efficiency combination"),
     ("Stated limitation: the battery arbitrage exercise is stylized (price-taking, one daily cycle, fixed round-trip cost).", "Conclusions",
      "The BESS exercise is deliberately stylized: we assume price-taking behavior, a single daily charge-discharge cycle, and a fixed round-trip cost."),
   ],
   "notes": "Day-ahead electricity price forecasting with regressors on lagged features (ARX, NARX, TabPFN-2). "
            "THieF for EPF was introduced by Lipiecki et al. (2026), i.e. prior work by the first author."},

  {"id": "arxiv-2609.18130",
   "title": "Benchmarking Tabular Foundation Models as Surrogates in Expensive Evolutionary Optimization",
   "authors": ["Lu Han", "Jin Wang", "Yuchen Li", "Haoran Gu", "Shulei Liu", "Ziyang Shi", "Wenao Lu", "Handing Wang"],
   "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.18130"},
   "tasks": ["tabular-regression"], "fam": ["tabular-foundation-model", "gaussian-processes"], "par": ["in-context-learning"],
   "proposes": ["Empirical study of TabPFN as a surrogate model in offline and online surrogate-assisted evolutionary algorithms"],
   "claims": [
     ("The paper studies, experimentally and theoretically, how effective TabPFN is as a surrogate in surrogate-assisted evolutionary algorithms.", "Abstract",
      "this work conducts a comprehensive study that combines extensive experiments with in-depth theoretical analysis to investigate the effectiveness of TabPFN"),
     ("TabPFN's effectiveness is highly problem dependent and it cannot universally replace conventional surrogates.", "Abstract",
      "Results show that the effectiveness of TabPFN is highly problem dependent, and it cannot replace conventional surrogates universally."),
     ("Predictive accuracy is compared between TabPFN v2, GP and RBFN on the CEC 2017 suite with RMSE and Kendall's tau, 25 independent runs per function; hyperparameter settings of GP/RBFN were not found in the text.", "Prediction performance",
      "We evaluate the prediction performance of three models, namely TabPFN, GP, and RBFN, on the CEC 2017 benchmark suite using RMSE and τ as evaluation metrics."),
     ("Training size is 10 times the dimension and test size 1000 for all three models.", "Prediction performance",
      "Across all test functions of different dimensions, we use a training sample size of Ntr = 10D and a test sample size of Nte = 1000 for the three models."),
     ("Limitation: although TabPFN needs no conventional hyperparameter optimization, its 'training' (context encoding) time can exceed RBFN's, which accumulates when surrogates are rebuilt often.", "Limitations and Unsuitable Scenarios",
      "Although TabPFN does not involve conventional hyper-parameter optimization, its training process still requires encoding and caching the training context to construct the predictive mapping."),
     ("Limitation: TabPFN extrapolates conservatively when candidates move away from the training data distribution.", "Limitations and Unsuitable Scenarios",
      "TabPFN exhibits relatively conservative extrapolation behavior when candidate solutions move away from the distribution of the training data."),
   ],
   "notes": "Surrogate regression on benchmark optimization functions (not real tabular datasets); tabular-regression is the closest existing task tag."},

  {"id": "arxiv-2609.16258",
   "title": "The AI-Enabled Scientific Frontier",
   "authors": ["Gabriel Manso", "Emma Fu", "Neil Thompson"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.16258"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["deep-learning", "linear-models", "random-forests", "kernel-methods"], "par": ["supervised"],
   "proposes": ["Corpus of AI-vs-other-method comparisons across scientific disciplines (performance and computational cost)"],
   "claims": [
     ("The authors assemble a corpus of head-to-head comparisons between AI and other analysis techniques across 27 disciplines from papers published 2000 to early 2025.", "Abstract",
      "To assess the claims, we assemble a corpus of 2,507 head-to-head comparisons between AI and other scientific analysis techniques across 27 scientific disciplines from papers published between 2000 and early 2025."),
     ("Relative to traditional statistics, AI often performs better but at a significantly higher computational cost.", "Abstract",
      "Relative to traditional statistics, AI often outperforms, but at a significantly higher computational cost."),
     ("In nearly a quarter of cases AI is both more expensive and worse than traditional statistical techniques, a fraction stable for a decade.", "Abstract",
      "But there are also nearly a quarter of cases where AI is both more expensive and performs worse than traditional statistical techniques and this fraction has been stable for a decade."),
     ("Inclusion required each study to evaluate at least two methods on a shared problem, dataset or setting (comparisons are taken from the published papers, not rerun).", "Supplementary: Corpus Construction",
      "Each retained study had to evaluate at least two methods on a shared problem, dataset, or experimental setting, thereby permitting a meaningful assessment of relative performance and computational cost."),
     ("On the statistical side, the baselines in the corpus are usually strong workhorses (SVMs, random forests, logistic regression, decision trees, k-NN).", "Analysis techniques across scientific domains",
      "On the statistical side, AI is usually compared not with trivial models but with strong workhorses such as support vector machines, random forests, logistic regression, decision trees"),
     ("Stated limitation: only about half of comparisons report numerical cost, in diverse units, and reporting bias cannot be fully corrected.", "Discussion",
      "Only about half of the comparisons in our dataset report numerical cost metrics, and cost is measured in diverse units; we mitigate this with log-ratio encodings and robustness checks but cannot fully correct for reporting bias."),
   ],
   "notes": "Cross-domain meta-analysis of published comparisons; not specific to tabular data, so task and family tags are approximate."},

  {"id": "arxiv-2609.13785",
   "title": "Partition Scores Are Not System Scores: Deployment-Fidelity Gaps in Decomposed Algorithm Selection",
   "authors": ["Jiachen Zhang", "Yu Tang", "Li Zhu"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.13785"},
   "tasks": ["tabular-classification"], "fam": ["automl-systems", "random-forests", "gradient-boosted-trees"], "par": ["supervised"],
   "proposes": ["Deployment-fidelity gap G(R) between partition-level (within-family oracle) and end-to-end scores in decomposed algorithm selection"],
   "claims": [
     ("The paper defines the deployment-fidelity gap as partition-level utility (with a within-family oracle) minus deployable end-to-end utility.", "Abstract",
      "We define the deployment-fidelity gap G(R) as the difference between partition-level and deployable end-to-end utility"),
     ("On five public algorithm-selection benchmarks (including TabZilla, TabRepo and TALENT), every decomposed pipeline has a positive gap.", "Abstract",
      "Across five public algorithm-selection benchmarks spanning tabular AutoML and combinatorial CSP/SAT, every decomposed pipeline has positive G(R), ranging from 0.012 on TabZilla to 0.13 on PROTEUS-2014."),
     ("Tabular benchmarking literature uses best-in-family summaries (best deep model vs. best GBDT) as the primary comparison object, which the paper treats as an oracle-style quantity.", "Related Work",
      "tabular benchmarking literature reports best-in-family summaries – best deep model versus best gradient boosting model – as the primary comparison object"),
     ("Protocol: 5 seeds x 5-fold stratified CV with per-instance utilities; family selectors are random forests and the default within-family selector is a per-algorithm gradient-boosted regressor.", "Benchmarks and protocol",
      "We run 5 seeds × 5-fold stratified CV and convert performance to per-instance utilities in [0, 1]"),
     ("Partition and end-to-end scores should be reported side by side.", "Abstract",
      "Partition and end-to-end scores should be reported side by side."),
     ("Stated limitation: exhaustive HPO or domain-specific meta-learners may shrink the gap further, but such improvements must still be reported end-to-end.", "Limitations and Conclusion",
      "exhaustive HPO or domain-specific meta-learners may shrink G(R) further; such improvements must still be reported end-to-end"),
   ],
   "notes": "Tabular benchmarks used (TabZilla, TabRepo, TALENT) are classification only per Table 1."},

  {"id": "arxiv-2609.13031",
   "title": "Attention Quantization for Tabular Foundation Models",
   "authors": ["Jonas M. Kübler", "Benjamin Jäger", "Klemens Flöge", "Noah Hollmann", "Frank Hutter"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.13031"},
   "tasks": ["tabular-classification", "tabular-regression", "model-compression"], "fam": ["post-training-quantization", "quantization", "tabular-foundation-model"], "par": ["in-context-learning", "post-hoc"],
   "proposes": ["FP8 attention quantization (Triton kernel) for the in-context-learning attention of tabular foundation models"],
   "claims": [
     ("Quantization error must be aligned between test rows and training rows; otherwise accuracy drops drastically.", "Abstract",
      "We find that it is crucial to align the quantization error in the test rows with the quantization error in the training rows, as otherwise the accuracy drops drastically."),
     ("An FP8 attention kernel speeds up attention over 16-bit kernels with no relevant accuracy loss for TabPFN-v3 and TabICLv2 on TabArena and BeyondArena.", "Abstract",
      "Our Triton kernel achieves a speedup up to 1.7x over regular 16-bit kernels, and we show that on TabPFN-v3 and TabICLv2 there is no relevant accuracy loss across TabArena and BeyondArena."),
     ("Quality is tested on the full 51-dataset TabArena suite (and later BeyondArena), over three TabPFN-v3 preprocessing seeds.", "Experiments",
      "We first test the quality impact of our quantization scheme and kernel on TabArena [Erickson et al., 2026], where we run the full suite consisting of 51 datasets."),
     ("Degradation is tested with a one-sided sign test under the assumption that post-training quantization can only make the model worse.", "Experiments",
      "Following Kübler et al. [2026] we assume that post-training quantization can only make the model worse and use a one-sided sign test."),
     ("All authors list Prior Labs as their affiliation; the evaluated models are TabPFN-v3 and TabICLv2; no conflict-of-interest statement was found in the text.", "Title page",
      "Correspondence: jonas@priorlabs.ai"),
     ("Per the reference list, author Frank Hutter is a co-author of TabArena, the benchmark used for evaluation.", "References",
      "Salinas, and Frank Hutter. Tabarena: A living benchmark for machine learning on tabular data."),
   ],
   "notes": "TabArena covers both classification and regression; the paper does not split results by task type in the text."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
