"""候補 Issue #1(表形式データ)で承認された DOI 論文 7 本のカード(バッチ cand_2026_10_b11)。
多くは応用論文(銀行・地盤材料・遺伝統計・教育調査・畜産・保険・医療)。各論文の主張と評価方法
(データ・分割/検証方式・比較モデルと調整方法・データ規模)を記録する。結果表の数値は記録しない。
書誌(著者・版・年・掲載誌・PDF取得元・ライセンス)は scratchpad のバッチ JSON(OpenAlex の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

CLS = ["tabular-classification"]
REG = ["tabular-regression"]

SPECS = [
  {"id": "doi-10.47852_bonviewaia620210522",
   "title": "WHSDA-AI: Interpretable Walsh-Hadamard Spectral Deviation Analysis for Structured Artificial Intelligence Applications in Banking Sector",
   "authors": ["Sergo A. Episkoposian", "Suren H. Parsyan"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Artificial Intelligence and Applications",
   "links": {"doi": "https://doi.org/10.47852/bonviewaia620210522"},
   "pdf_url": "https://ojs.bonviewpress.com/index.php/AIA/article/download/10522/2204", "license": "cc-by",
   "tasks": CLS, "fam": ["linear-models", "gradient-boosted-trees", "random-forests"], "par": ["supervised"],
   "proposes": ["WHSDA-AI (fixed Walsh-Hadamard signed-contrast feature and explanation layer with reference-normalized deviations)"],
   "claims": [
     ("The paper proposes WHSDA-AI, a Walsh-Hadamard spectral deviation framework for structured, profile-based AI in banking and related tabular risk-analysis settings.", "Abstract",
      "This paper proposes WHSDA-AI, a Walsh-Hadamard Spectral Deviation Analysis framework for structured and profile-based AI in the banking sector and related tabular risk-analysis settings."),
     ("The full Walsh-Hadamard transform is an isometry, so it cannot by itself improve Euclidean rankings; any value must come from coefficient selection, reference deviations, weighting or downstream models.", "Abstract",
      "The full Walsh-Hadamard transform is an isometry and cannot improve Euclidean rankings by itself."),
     ("Comparisons are reported against sparse logistic regression, PCA, Haar contrasts, random signed projections, random forests, gradient boosting, XGBoost and LightGBM.", "Introduction",
      "Fourth, it reports comparative results against sparse logistic regression, PCA, Haar contrasts, random signed projections, random forests, gradient boosting, XGBoost, and LightGBM."),
     ("Evaluation uses repeated splits; the reported benchmarks are two controlled risk-style datasets, three public structured-data datasets and one public credit-card fraud dataset.", "Limitations",
      "The reported benchmarks now include two controlled risk-style datasets, three public structured-data datasets, and one public credit-card fraud benchmark."),
     ("The banking and credit-style benchmarks are diagnostic and synthetic; the other benchmarks are public datasets (including an anonymized public credit-card fraud dataset), so no institutional bank data is used.", "Ethical Statement",
      "The reported banking and credit-style benchmarks are diagnostic and synthetic"),
     ("EBM and TabPFN are discussed as adjacent contemporary directions, while XGBoost and LightGBM are treated as the closest production-grade comparators.", "Discussion",
      "EBM and TabPFN are discussed explicitly because they represent two adjacent contemporary directions: interpretable additive prediction and tabular foundation-model prediction [21, 35]."),
   ],
   "notes": "Application domain: banking fraud / AML risk screening. Synthetic sets have 1200 profiles (Table 7); results are mean +/- SD over five splits (two stratified splits on the public credit-card fraud dataset). The number of retained coefficients K is chosen on validation data only. How the baselines' hyperparameters were set was not found in the text (searched 'tuned', 'hyperparam', 'default'). EBM/TabPFN appear only as acknowledged comparators; no TabPFN results were found. Family tags are for the comparators; there is no tag for fixed orthogonal feature transforms."},

  {"id": "doi-10.1186_s44147-026-01203-3",
   "title": "Interpretable TabPFN-Based prediction of unconfined compressive strength in chemically stabilized soft soils for transportation subgrade applications",
   "authors": ["Quynh-Anh Thi Bui", "Son Hoang Trinh", "Khoa Minh Nguyen"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Journal of Engineering and Applied Science",
   "links": {"doi": "https://doi.org/10.1186/s44147-026-01203-3"},
   "pdf_url": "https://link.springer.com/content/pdf/10.1186/s44147-026-01203-3.pdf", "license": "cc-by",
   "tasks": REG, "fam": ["tabular-foundation-model", "gradient-boosted-trees", "random-forests", "kernel-methods", "feature-attribution"], "par": ["in-context-learning", "supervised"],
   "proposes": ["Interpretable TabPFN-based UCS prediction framework for stabilized soft soils (SHAP + PDP)"],
   "claims": [
     ("The study develops an interpretable TabPFN-based framework for preliminary prediction of unconfined compressive strength of stabilized soft soils from the Mekong Delta.", "Abstract",
      "This study develops an interpretable Tabular Prior-data Fitted Network (TabPFN)-based framework for preliminary UCS prediction of stabilized soft soils from the Mekong Delta, Vietnam."),
     ("TabPFN is used with its default configuration and compared with SVR, k-nearest neighbors, Random Forest and CatBoost, each tuned with GridSearchCV.", "Abstract",
      "TabPFN was applied using its default configuration and compared with four GridSearchCV-optimized models: support vector regression, k-nearest neighbors, Random Forest, and CatBoost."),
     ("Evaluation uses an 80/20 train-test split plus five-fold cross-validation on the development part; the dataset has 168 observations with seven predictors.", "Abstract",
      "Performance was assessed using an 80/20 train–test split and five-fold cross-validation, while SHAP and partial dependence plots were used for interpretation."),
     ("Grid search for the baselines minimizes RMSE within the development subset using five-fold cross-validation with fold assignments shared across models.", "Methodology",
      "RMSE was used as the optimization criterion because it penalizes larger prediction errors more strongly, while final model assessment incorporated multiple complementary regression metrics."),
     ("TabPFN had the strongest observed test performance among the five models evaluated.", "Abstract",
      "TabPFN achieved the strongest observed test performance among the five evaluated models"),
     ("The 34-observation hold-out test set comes from the same experimental database, so it is not independent external validation.", "Discussion",
      "Although the independent test subset was excluded from all model development and contained 34 observations reserved for final evaluation, these observations were drawn from the same experimental database and therefore do not constitute independent external validation."),
   ],
   "notes": "Application domain: geotechnical / civil engineering (soil stabilization with cement, lime, fly ash). Very small data (168 observations from three study areas). The authors state the result is specific to this dataset and validation design."},

  {"id": "doi-10.1038_s41467-026-76154-7",
   "title": "Modeling nonlinear and interaction effects of spatiotemporal and nongenetic factors improves prediction for complex traits",
   "authors": ["Ross DeVito", "Melissa Gymrek"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Nature Communications",
   "links": {"doi": "https://doi.org/10.1038/s41467-026-76154-7", "code": "https://github.com/gymrek-lab/DeeperNull"},
   "pdf_url": "https://www.nature.com/articles/s41467-026-76154-7_reference.pdf", "license": "cc-by",
   "tasks": REG, "fam": ["gradient-boosted-trees", "tabular-mlp", "linear-models"], "par": ["supervised"],
   "proposes": ["Nonlinear (XGBoost) covariate null models with spatiotemporal covariates as an added covariate for polygenic scores"],
   "claims": [
     ("An auxiliary nonlinear 'null' model predicts the phenotype from covariates alone, and its prediction is added as a covariate in downstream analysis.", "Abstract",
      "We adopt a null model approach where an auxiliary nonlinear model predicts phenotypes from covariates alone."),
     ("On 16 UK Biobank phenotypes, gradient-boosted tree null models with spatiotemporal features improve covariate modeling.", "Abstract",
      "Using 16 phenotypes in the UK Biobank, we show gradient boosted decision tree nulls including spatiotemporal features improve covariate modeling."),
     ("Participants are randomly split 8:1:1 into train, validation and test sets; null models are trained and evaluated with five-fold cross-validation on the training set only, keeping validation and test sets for the downstream polygenic-score task.", "Results",
      "just the training set was used to train and evaluate the null models on their own using ﬁve-fold cross-validation."),
     ("XGBoost variants were the default parameters plus two larger configurations (up to 1000 or 2500 estimators, lower learning rate, max depth 4), all with early stopping.", "Results",
      "The three variations consisted of the default XGBoost parameters (a maximum of 100 estimators and a learning rate of 0.3), as well as two larger versions with up to 1000 or 2500 estimators, both using a learning rate reduced to 0.25 and a maximum depth of 4 to mitigate overﬁtting."),
     ("Under a Friedman test with Nemenyi post-hoc comparisons, the original DeepNull neural network ranked second-worst, ahead only of LASSO.", "Results",
      "By average rank, the original DeepNull neural network was the second-worst performer, only outperforming the LASSO regression and signiﬁcantly worse than all other model variations."),
     ("Training and polygenic-score evaluation used only individuals of White British ancestry in the UK Biobank.", "Discussion (limitations)",
      "First, the training and PGS evaluation were conducted exclusively on individuals of White British ancestry in the UK Biobank."),
   ],
   "notes": "Application domain: statistical genetics (polygenic scores, UK Biobank, up to 316,867 individuals). The tabular part is covariate-only phenotype regression; three case-control traits are also evaluated. Compares XGBoost vs DeepNull-style MLPs vs linear/LASSO/ridge null models."},

  {"id": "doi-10.3389_fpubh.2026.1911565",
   "title": "AI-related measures and self-reported lesson-aim attainment: an explainable machine-learning analysis of TALIS 2024",
   "authors": ["ZhuFang Mao"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Frontiers in Public Health",
   "links": {"doi": "https://doi.org/10.3389/fpubh.2026.1911565"},
   "pdf_url": "https://www.frontiersin.org/journals/public-health/articles/10.3389/fpubh.2026.1911565/pdf", "license": "cc-by",
   "tasks": CLS, "fam": ["gradient-boosted-trees", "random-forests", "linear-models", "feature-attribution"], "par": ["supervised"],
   "proposes": ["Nested (baseline vs AI-added) LightGBM framework with SHAP to test incremental predictive information of AI-related survey measures"],
   "claims": [
     ("A nested explainable machine-learning framework on TALIS 2024 teacher data tests whether AI-related measures add predictive information.", "Abstract",
      "A nested explainable machine-learning framework was developed using TALIS 2024 teacher data to test the incremental predictive information supplied by AI-related measures."),
     ("Baseline and AI-added regularized LightGBM models are compared with country-by-school grouped validation and early stopping.", "Abstract",
      "Matched baseline and AI-added regularized LightGBM models were compared using country-by-school grouped validation and early stopping."),
     ("Paired bootstrap intervals show the AI-added model's gains are statistically stable but practically modest.", "Abstract",
      "Paired bootstrap intervals indicated statistically stable, but practically modest, gains"),
     ("A descriptive common-split comparison covers L2 logistic regression, random forest, extra-trees, LightGBM, XGBoost and CatBoost.", "Section 4.1",
      "The compared methods were L2-penalized logistic regression, random forest, extra-trees, LightGBM, XGBoost, and CatBoost."),
     ("Hyperparameter budgets were not fully equalized across algorithms, so the comparison is described as descriptive rather than evidence of universal algorithm superiority.", "Section 4.1",
      "Hyperparameter budgets were not exhaustively equalized, so the comparison is descriptive rather than evidence of universal algorithm superiority."),
     ("All focal variables come from one time point, so temporal order and causality cannot be established.", "Limitations",
      "First, all focal variables were measured at one time point, so temporal ordering and causality cannot be established; reverse associations and common-method bias are plausible."),
   ],
   "notes": "Application domain: education survey (TALIS 2024; 88,991 teachers from 55 countries/economies). Outer grouped split: 70,864 training / 18,127 independent test teachers. Target is a within-country upper-quartile indicator of self-reported lesson-aim attainment."},

  {"id": "doi-10.3389_frai.2026.1876396",
   "title": "Evaluation of hybrid models based on image segmentation and inference for pig weight estimation",
   "authors": ["Miguel Angel Valles-Coral", "Kelvin Lleins Rojas-Córdova", "Lloy Pinedo", "Richard Injante", "Pierre Vidaurre-Rojas", "Jorge Saavedra-Ramírez", "Fernando Ruiz-Saavedra", "Williams Ramirez"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Frontiers in Artificial Intelligence",
   "links": {"doi": "https://doi.org/10.3389/frai.2026.1876396"},
   "pdf_url": "https://www.frontiersin.org/journals/artificial-intelligence/articles/10.3389/frai.2026.1876396/pdf", "license": "cc-by",
   "tasks": REG, "fam": ["kernel-methods", "gradient-boosted-trees", "deep-learning"], "par": ["supervised"],
   "proposes": ["Hybrid pipeline: YOLOv8n-seg segmentation + EfficientNet-B0 embeddings + tabular regressors (SVR / XGBoost / CatBoost) for pig weight"],
   "claims": [
     ("The paper proposes a non-invasive computer-vision approach to estimate pig weight under real farm conditions.", "Abstract",
      "This study proposes a non-invasive computer vision–based approach to estimate pig weight under real farm conditions in San Martín, Peru."),
     ("Frozen-CNN image embeddings are fed to SVR, XGBoost and CatBoost, evaluated with repeated stratified cross-validation and an independent test set.", "Abstract",
      "The resulting embeddings were used as input for supervised regression models (SVR, XGBoost, and CatBoost), evaluated using repeated stratified cross-validation and an independent test set, with MAE, RMSE, and R² as performance metrics."),
     ("Hyperparameters are tuned on a separate tuning subset of the development data, distinct from the cross-validation pool and the held-out test set.", "Materials and methods",
      "subset represented 15% of TrainDev and was used for hyperparameter optimization, while CVPool comprised the remaining data."),
     ("Models are compared with a Friedman test followed by Wilcoxon post hoc tests with Holm correction.", "Abstract",
      "Statistical comparisons were conducted using the Friedman test followed by Wilcoxon post hoc analysis with Holm correction."),
     ("SVR gave the best results, with statistically significant differences from the other models.", "Abstract",
      "showing statistically significant differences compared to the other models."),
     ("The authors note a tendency to underestimate weight in higher weight ranges, which they take to indicate a limitation of two-dimensional images in representing the animal's full volume.", "Discussion",
      "However, the observed tendency toward underestimation in higher weight ranges indicates a limitation of two-dimensional images in representing the full volumetric characteristics of the animal, as also reported in previous studies (Liu et al., 2023; Paudel et al., 2023)."),
   ],
   "notes": "Application domain: precision livestock farming (3,800 lateral RGB images from one farm; each row is a 1,280-dimensional embedding). The number of distinct animals and whether splits were grouped by animal were not found in the text. The dataset is not public (available on request). Tuning search method/budget on the Tune subset was not found in the text (only the selected configurations are listed)."},

  {"id": "doi-10.36079_lamintang.ijortas-0802.1081",
   "title": "Interpretable Machine Learning Framework for Personalized Health Insurance Risk Prediction",
   "authors": ["Mohammed M. Al-Mhadawi", "Qahtan Yas"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "International Journal of Recent Technology and Applied Science (IJORTAS)",
   "links": {"doi": "https://doi.org/10.36079/lamintang.ijortas-0802.1081"},
   "pdf_url": "https://lamintang.org/journal/index.php/ijortas/article/download/1081/674", "license": "cc-by-sa",
   "tasks": REG, "fam": ["gradient-boosted-trees", "random-forests", "tabular-mlp", "linear-models", "feature-attribution"], "par": ["supervised"],
   "proposes": ["Interpretable tree-ensemble benchmarking framework for health insurance charge prediction (SHAP)"],
   "claims": [
     ("Six predictive models (five tree ensembles and an MLP control) are benchmarked on one real-world insurance dataset of 1,338 records.", "Abstract",
      "We benchmarked six predictive architectures (five tree ensembles and a multi-layer perceptron control) on a real-world dataset (n=1,338)."),
     ("Gradient Boosting performed best in their experiments.", "Abstract",
      "Experimental results demonstrate that Gradient Boosting achieved superior performance"),
     ("Evaluation uses five folds with an 80/20 train-test partition per fold, with preprocessing fit on each training partition.", "Methodology",
      "The dataset is partitioned using an 80/20 train-test strategy across five folds, resulting in 1,070 training samples and 268 testing samples per fold."),
     ("All models use the fixed 'optimized' configurations listed in a hyperparameter table with a fixed random seed; how these configurations were selected was not found in the text.", "Finding and Discussion",
      "All experiments were conducted using the optimized hyperparameter configurations presented in Table 3, with random_state = 42 applied consistently across all models to ensure experimental reproducibility."),
     ("The MLP was a plain baseline control without tabular-specific adaptations such as TabNet, which the authors take as further support for tree ensembles.", "Finding and Discussion",
      "Since such adaptations were not incorporated into this baseline control, the results further emphasize the suitability of tree-based ensemble approaches for modeling nonlinear insurance risk patterns."),
     ("The single static U.S.-centric dataset limits generalizability across regulatory, demographic and economic contexts.", "Conclusion",
      "dataset, which restricts the generalizability of the findings across different regulatory, demographic, and economic contexts."),
   ],
   "notes": "Application domain: health insurance charge prediction (UCI Medical Cost dataset per Table 2 caption). A GitHub repository is mentioned but no URL was found. The model list is inconsistent in the text: Step 4 says five tree ensembles plus one linear baseline, while the abstract says an MLP control and the framework section also lists linear models, AdaBoost and SVR."},

  {"id": "doi-10.57185_yrw05r30",
   "title": "Penerapan Deep Learning (Artificial Neural Network) Untuk Klasifikasi Diagnostik Kanker Payudara Guna Mendukung Efisiensi Biaya Deteksi Dini",
   "authors": ["Zeny Widianingsih", "Aldi Algino"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Al Makki Health Informatics Journal",
   "links": {"doi": "https://doi.org/10.57185/yrw05r30"},
   "pdf_url": "https://healthinformaticsjournal.al-makkipublisher.com/index.php/hij/article/download/99/85", "license": "cc-by-sa",
   "tasks": CLS, "fam": ["tabular-mlp", "linear-models", "random-forests", "kernel-methods"], "par": ["supervised"],
   "proposes": ["MLP (64-32-16) classifier for WDBC breast-tumor diagnosis, benchmarked against classical models"],
   "claims": [
     ("The study designs and evaluates an MLP-based neural network to classify breast tumors as benign or malignant.", "Abstract (English)",
      "This study aims to design and evaluate a deep learning model based on an Artificial Neural Network (Multi-Layer Perceptron) to classify breast tumors as either benign or malignant."),
     ("Data are the WDBC dataset (569 samples, 30 numerical features), with a stratified 80:20 train-test split.", "Abstract (English)",
      "The study utilized the Wisconsin Diagnostic Breast Cancer (WDBC) dataset, comprising 569 samples and 30 numerical features, split into 455 training samples and 114 test samples (80:20) using a stratified approach."),
     ("The neural network did not outperform classical models (logistic regression, random forest, SVM) on this small tabular dataset.", "Abstract (English)",
      "These findings indicate that the Deep Neural Network model does not outperform classical models on small-scale tabular data."),
     ("The MLP uses scikit-learn MLPClassifier defaults except the stated architecture, Adam, early stopping on a 15% validation split and the random seed.", "Methods",
      "regularisasi L2 (alpha) mengikuti nilai bawaan (default) MLPClassifier scikit-learn kecuali yang telah disebutkan secara eksplisit."),
     ("Evaluation uses a single 80:20 hold-out split, not k-fold cross-validation.", "Methods",
      "Perlu ditegaskan bahwa evaluasi pada penelitian ini menggunakan satu kali pembagian data latih-uji (single hold-out split 80:20), bukan validasi silang k-lipat (k-fold cross-validation)."),
     ("With 114 test samples, accuracy differences of about one percent correspond to about one sample, so the model ranking is not statistically reliable without further testing.", "Methods",
      "sehingga peringkat antar-model tidak dapat dianggap andal secara statistik tanpa pengujian tambahan."),
   ],
   "notes": "Application domain: medical diagnosis (breast cancer cytology features). Paper is in Indonesian with an English abstract; some quotes are Indonesian. Baseline tuning was not found in the text; only Random Forest's 300 trees and SVM's RBF kernel are stated."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
