"""候補 Issue #1(表データ)で承認された論文のうち、バッチ cand_2026_10_b12 の7本のカード(DOI 論文、出版社/リポジトリ PDF)。
各論文の主張と評価方法(データ・検証方式・比較モデルとチューニング)の記述を記録する。結果表の数値は記録しない。
書誌(著者・版・年・掲載誌・pdf_url・ライセンス)は scratchpad の batches/cand_2026_10_b12.json(OpenAlex の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
  {"id": "doi-10.3389_fpsyg.2026.1875261",
   "title": "Cross-economy stability of predictor rankings for adolescent school belonging and mathematics anxiety: an explainable machine-learning analysis of PISA 2022",
   "authors": ["Yuan Liao", "Peng Qin", "Runlin Li"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Frontiers in Psychology",
   "links": {"doi": "https://doi.org/10.3389/fpsyg.2026.1875261"},
   "pdf_url": "https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2026.1875261/pdf", "license": "cc-by",
   "tasks": ["tabular-regression"], "fam": ["gradient-boosted-trees", "linear-models", "feature-attribution"], "par": ["supervised"],
   "proposes": ["Per-economy LightGBM + TreeSHAP rank analysis of PISA 2022 predictors with availability (questionnaire-coverage) filtering"],
   "claims": [
     ("Data and models: PISA 2022 student data were analysed with one LightGBM model per economy, and TreeSHAP rankings were used to estimate the relative predictive salience of predictors for school belonging and mathematics anxiety.", "Abstract",
      "Per-economy LightGBM models and TreeSHAP rankings estimated relative predictive salience."),
     ("Pooled model comparison protocol: LightGBM (fixed hyperparameters, economy code as a categorical feature) was compared with ridge regression using ten student-level folds stratified by economy; the paper notes this design does not evaluate transfer to unseen economies.", "Methods (pooled comparators)",
      "Performance was estimated with ten student-level folds stratified by economy; this design preserves each economy's proportion in every fold and does not evaluate transfer to unseen economies."),
     ("Per-economy models used a fixed LightGBM configuration on a 64%/16%/20% train/validation/test split with early stopping on validation loss; no hyperparameter search is described.", "Methods (per-economy LightGBM with TreeSHAP)",
      "fit an independent LightGBM regressor on a 64%/16%/20% train/validation/test split with early stopping on validation loss."),
     ("Deep tabular networks (e.g. FT-Transformer, TabPFN) were not evaluated; the authors chose LightGBM citing prior findings that GBDTs match or exceed deep tabular networks on data like PISA.", "Methods (pooled comparators)",
      "The choice of LightGBM over deep tabular networks (e.g., FT-Transformer, TabPFN Hollmann et al., 2025) was motivated by the empirical finding that gradient-boosted decision trees match or exceed deep tabular networks on heterogeneous tabular data of the size and structure of PISA"),
     ("In the pooled comparison on untouched outer test folds, LightGBM had higher R2 than ridge regression with penalized economy indicators for both outcomes.", "Results",
      "In the pooled comparison evaluated on untouched outer test folds, LightGBM produced higher R2 than ridge regression with penalized economy indicators"),
     ("Limitation: SHAP values were summarized over the entire per-economy sample rather than only the test split, so the rankings may partly reflect sample-internal fitted structure.", "Limitations",
      "SHAP values were summarized across the entire per-economy sample rather than the test split alone, so the rankings may partly reflect sample-internal fitted structure"),
   ],
   "notes": "Application domain: education / psychology (PISA 2022 student questionnaire; outcomes are school belonging and mathematics anxiety indices). The ML is used for predictor ranking, not for proposing a new learner."},

  {"id": "doi-10.1109_tsg.2026.3676842",
   "title": "Probabilistic Disaggregation of Behind-the-Meter PV Systems Using Conformal Prediction",
   "authors": ["Jialin He", "Tarek A. AlSkaif"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (submittedVersion)", "venue": "IEEE Transactions on Smart Grid",
   "links": {"doi": "https://doi.org/10.1109/tsg.2026.3676842"},
   "pdf_url": "https://edepot.wur.nl/713863", "license": "other-oa",
   "tasks": ["tabular-regression", "uncertainty-estimation"], "fam": ["conformal-prediction", "gradient-boosted-trees", "random-forests", "linear-models", "deep-learning"], "par": ["supervised"],
   "proposes": ["Probabilistic behind-the-meter PV disaggregation framework based on conformal prediction",
                "Adaptive Mondrian Binning (AMB) conformal prediction variant", "Capacity estimation method for BtM PV systems"],
   "claims": [
     ("The paper proposes a conformal-prediction variant, Adaptive Mondrian Binning (AMB), to address the arbitrary bin count of CP with Mondrian Binning.", "Abstract",
      "To address the arbitrary bin count in CP with MB, the paper proposes a novel CP variant, namely: Adaptive Mondrian Binning (AMB)."),
     ("Main claim: with LightGBM as the deterministic regressor, AMB outperforms quantile regression and the other CP variants.", "Abstract",
      "Results show that using LightGBM as the deterministic regressor, AMB outperforms quantile regression and other CP variants."),
     ("Evaluation data: two real datasets (Amsterdam, the Netherlands; Sydney/Ausgrid, Australia); households are split into two groups, once in file order and in thirty random splits.", "Experiment Settings",
      "Multiple splits: Thirty random splits are performed, each dividing the households into a group of 10 and a group of 11, similar to the single split"),
     ("Deterministic regressors compared were MLR, random forest and LightGBM, plus FCNN, ResNet and LSTM; DL models were similar to LightGBM in accuracy but took much longer to train.", "Deterministic Disaggregation Results",
      "In both datasets, DL methods are similar to LGB in terms of accuracy, while incurring significantly longer training time."),
     ("The quantile-regression baseline is LightGBM with a quantile objective. How the regressors' hyperparameters were set is not found in the text (only the capacity-estimation thresholds are given).", "Probabilistic Disaggregation Results",
      "In this study, QR is realized by changing the objective of LGB to \"quantile\"."),
   ],
   "notes": "Application domain: energy (solar PV disaggregation from smart-meter net load and weather features; hourly records). Tagged tabular-regression because a regressor maps tabular weather/net-load features to normalized PV output; the data are time-indexed. "
            "PDF is the author's accepted version from the WUR repository (Taverne)."},

  {"id": "doi-10.70393_6a6374616d.343334",
   "title": "Tabular In-Context Learning for Low-Resource Rare Industrial Fault Detection: a Cost-Sensitive Comparison on Scania APS and SECOM",
   "authors": ["Guoqing Song"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Journal of Computer Technology and Applied Mathematics",
   "links": {"doi": "https://doi.org/10.70393/6a6374616d.343334"},
   "pdf_url": "https://www.suaspress.org/ojs/index.php/JCTAM/article/download/v3n4a01/v3n4a01", "license": "cc-by",
   "tasks": ["tabular-classification"], "fam": ["tabular-foundation-model", "gradient-boosted-trees", "tabular-mlp", "linear-models"],
   "par": ["supervised", "in-context-learning"],
   "proposes": ["Locked-test, cost-sensitive comparison of TabICLv2 vs TabM, XGBoost and logistic regression on Scania APS and SECOM (no new method)"],
   "claims": [
     ("Scania protocol: nested stratified training samples of 5,000 and 10,000 records under five seeds; tunable models selected by out-of-fold AUPRC on shared three-fold splits; decision thresholds fixed by minimizing out-of-fold cost; the official test set stayed locked until all selections were complete.", "Abstract",
      "Shared three-fold splits supported out-of-fold (OOF) evaluation; tunable models were selected by OOF AUPRC, and decision thresholds were locked by minimizing OOF cost, defined as C = 10 × FP + 500 × FN."),
     ("SECOM protocol: three repeats of five-fold outer cross-validation with three-fold inner selection.", "Abstract",
      "SECOM used three repeats of five-fold outer cross-validation with three-fold inner selection."),
     ("Tuning budgets were unequal (TabICLv2 one fixed configuration, TabM four presets, logistic regression eight candidates, XGBoost 12 candidates), and CatBoost, LightGBM and broader tuning were not evaluated.", "Limitations and threats to validity",
      "Search budgets were also unequal: TabICLv2 used one fixed configuration, TabM four presets, logistic regression eight candidates, and XGBoost 12 candidates."),
     ("On the prespecified Scania design, TabICLv2 improved AUPRC, MCC, official cost and Brier score relative to XGBoost, with paired bootstrap intervals supporting all four directions.", "Discussion",
      "Under the prespecified Scania design, TabICLv2 improved AUPRC, MCC, official cost, and Brier score relative to XGBoost, with paired confidence intervals supporting all four directions."),
     ("In a time-ordered SECOM sensitivity analysis (few failures in the test segment), threshold transfer failed for every model; the author treats it as a robustness warning, not a ranking.", "Results (temporal sensitivity on SECOM)",
      "Threshold transfer failed for every model"),
     ("Conclusion: the evidence supports TabICLv2 in this specific low-resource, cost-sensitive setting but does not establish universal superiority or temporal deployment validity.", "Conclusion",
      "The evidence therefore supports TabICLv2 in this specific low-resource, cost-sensitive setting but does not establish universal superiority or temporal deployment validity."),
   ],
   "notes": "Application domain: industrial fault detection (Scania APS truck failures; SECOM semiconductor manufacturing). Single-author study; the paper reports TabICLv2 needed far more task-side time than XGBoost on a 4 GiB laptop GPU. "
            "SECOM record-level AUPRC difference vs XGBoost had an interval crossing zero (described as suggestive, not definitive). The Limitations section states that TabICLv2 also used historical pretraining, so the runtime comparison is task-side rather than total-compute cost."},

  {"id": "doi-10.64898_2026.08.24.746579",
   "title": "DeMoP: A Language-Model-Guided Mixture-of-Experts Framework for Cancer Prognosis",
   "authors": ["Chen Tang", "Lei Yu", "Qiwei Li", "Lin Xu"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (acceptedVersion)", "venue": "bioRxiv (Cold Spring Harbor Laboratory)",
   "links": {"doi": "https://doi.org/10.64898/2026.08.24.746579", "code": "https://github.com/Lin-Xu-lab/DeMoP"},
   "pdf_url": "https://www.biorxiv.org/content/biorxiv/early/2026/08/27/2026.08.24.746579.full.pdf", "license": "cc-by",
   "tasks": ["tabular-classification"], "fam": ["deep-learning"], "par": ["supervised"],
   "proposes": ["DeMoP: patient profiles serialized as text, fine-tuned DeBERTa-v3-large encoder, attention pooling and residual mixture-of-experts head"],
   "claims": [
     ("DeMoP serializes structured patient profiles (clinical variables, copy-number alterations, gene descriptions) as natural-language sequences and learns prognostic representations from them.", "Abstract",
      "we present DeMoP, a language-model-guided mixture-of-experts framework that serializes"),
     ("Main claim: on held-out tests in two pan-cancer cohorts (GENIE and TCGA), DeMoP outperformed the conventional machine-learning and deep-learning baselines that were evaluated.", "Abstract",
      "GENIE (63,090 patients) and TCGA (4,123 patients), DeMoP outperformed the conventional"),
     ("Protocol: within each cohort, DeMoP is trained on 80% and evaluated on the remaining 20% held-out internal test set (single split; no cross-validation described).", "Results (GENIE cohort)",
      "DeMoP using 80% of the GENIE cohort and evaluated it on the remaining 20% held-out internal"),
     ("The baselines (logistic regression, random forest, XGBoost, MLP, CNN, LSTM) used default parameter settings, evaluated on the same training and test sets as DeMoP; no tuning of baselines is described.", "Results (GENIE cohort)",
      "default parameter settings: logistic regression (0.51), random forest (0.58), XGBoost (0.66),"),
     ("Cross-cohort evaluation: a GENIE-trained model was applied directly to the full filtered TCGA cohort.", "Results (cross-cohort transfer)",
      "and evaluated it directly on the full filtered TCGA cohort (n = 4,123). The overall class-1 F1 score"),
     ("Limitation: serializing structured patient features as text may obscure some fine-grained quantitative relationships.", "Discussion (limitations)",
      "serializing structured patient features as natural-language sequences may obscure some fine-"),
   ],
   "notes": "Application domain: oncology (3-year survival classification from clinical + copy-number data; AACR GENIE and TCGA). bioRxiv preprint, not peer reviewed. "
            "The text encoder is DeBERTa-v3-large (an encoder, not a generative LLM), so large-language-models was not used; deep-learning is the closest family. The DeMoP checkpoint is chosen by validation weighted F1; how the validation set is formed is not found in the text. "
            "Tabular deep models (TabPFN, TabTransformer, FT-Transformer) are cited but not used as baselines. Authors declare no competing interests."},

  {"id": "doi-10.1007_s40123-026-01482-2",
   "title": "Machine Learning-Based Prediction of Cycloplegic Refraction Using the Eyerobo Vision Screener: Design—A Cross-Sectional Comparative Device Study",
   "authors": ["Mengmeng Xia", "Boxue Yao", "Yumei Wang", "Fengwei Liang", "Wuxia Zhao", "Li Qin", "Shoukuan Liu", "Muhammad Usama",
               "Zhihui Zhang", "Wu Guo", "Emmanuel Eric Pazo", "Xinjun Ren"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Ophthalmology and Therapy",
   "links": {"doi": "https://doi.org/10.1007/s40123-026-01482-2", "code": "https://github.com/Usama1002/cycloplegic-refraction-prediction"},
   "pdf_url": "https://link.springer.com/content/pdf/10.1007/s40123-026-01482-2.pdf", "license": "cc-by-nc",
   "tasks": ["tabular-regression"], "fam": ["tabular-foundation-model", "gradient-boosted-trees", "random-forests", "linear-models", "kernel-methods", "tabular-mlp"],
   "par": ["supervised", "in-context-learning"],
   "proposes": ["Device comparison (Eyerobo VS vs auto-refractor, with/without IOL Master biometry) for ML prediction of cycloplegic refraction; no new learner"],
   "claims": [
     ("Data and protocol: 1129 eyes of 574 patients aged 6-18; TabPFN (no hyperparameter tuning) evaluated alongside seven conventional ML algorithms with patient-level five-fold grouped cross-validation repeated over three random seeds.", "Abstract",
      "TabPFN, a tabular foundation model requiring no hyperparameter tuning, was evaluated alongside seven conventional machine-learning algorithms using patient-level five-fold grouped cross-validation repeated over three random"),
     ("Tuning: all gradient-boosting baselines (XGBoost, LightGBM, CatBoost) used default hyperparameters without per-dataset tuning, to match TabPFN's zero-tuning design; the authors note tuning may narrow the margin.", "Machine Learning Models",
      "All gradient-boosting models used default hyperparameters without per-dataset tuning to ensure a fair comparison with TabPFN's zero-tuning design"),
     ("TabPFN had the lowest MAE on all Eyerobo scenarios and was competitive with Ridge on auto-refractor scenarios.", "Abstract",
      "TabPFN achieved the lowest mean absolute error (MAE) on all Eyerobo scenarios and was competitive with Ridge on auto-refractor scenarios"),
     ("Screening thresholds: a Youden-optimal cutoff was selected on each training fold, and the cross-validation-averaged cutoff was used as the reported operating point.", "Screening-oriented classification analysis",
      "A noncycloplegic Youden-optimal cutoff was selected on each training fold and the cross-validation-averaged cutoff was used as the reported operating point."),
     ("The authors say the modest margin over linear and gradient-boosting baselines and the lack of external validation preclude recommending TabPFN as the definitive algorithm.", "Conclusions",
      "the modest margin over linear and gradient-boosting baselines and the absence of external validation preclude any recommendation as the definitive algorithm of choice."),
     ("Main limitation: all development and evaluation used internal cross-validation within a single-center cohort.", "Limitations",
      "The most important limitation of this study is that all model development and evaluation were conducted within a single-center cohort using internal cross-validation."),
   ],
   "notes": "Application domain: ophthalmology (pediatric myopia; predicting cycloplegic refraction from non-cycloplegic device readings and biometry). "
            "Although the GBDT baselines are described as default, the paper also lists fixed settings for XGBoost (200 rounds, depth 6, learning rate 0.05) and random forest (100 trees, depth 10). "
            "Authors declare no financial relationships with the device manufacturers."},

  {"id": "doi-10.65542_djei.v2i3.83",
   "title": "Adaptive Multi-Task Learning for Urban Air Quality Assessment",
   "authors": ["Iman Youssif Ibrahim", "Dindar M. Ahmed"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Dasinya Journal for Engineering and Informatics",
   "links": {"doi": "https://doi.org/10.65542/djei.v2i3.83"},
   "pdf_url": "https://dasinya.dpu.edu.krd/index.php/pub/article/download/83/38", "license": "cc-by",
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["tabular-mlp"], "par": ["supervised"],
   "proposes": ["TMTL-AQI: multi-task MLP with cyclical temporal encoding and hard parameter sharing (AQI class + PM2.5/PM10 + auxiliary AQI regression)"],
   "claims": [
     ("TMTL-AQI jointly performs AQI category classification, PM2.5/PM10 regression and auxiliary AQI value regression from structured data with a shared backbone.", "Abstract",
      "The model simultaneously performs three tasks: Air Quality Index category classification, PM2.5 and PM10 particulate matter regression, and auxiliary AQI value prediction."),
     ("Data and split: the TRAQID dataset (26,678 samples, 2022-2024) with a single stratified 80:20 train/test split.", "Dataset Description",
      "The dataset comprises 26,678 samples collected between 2022 and 2024 and was divided into training and testing sets using a stratified 80:20 ratio to preserve the class distribution."),
     ("The evaluated models are a single-task model, a multi-task model and the proposed TMTL-AQI; no tree-based or other tabular baselines were run (the AQC-Net comparison uses results reported for AQC-Net).", "Results",
      "Three models were evaluated: a single-task model, a multi-task model, and the proposed (TMTL-AQI) model."),
     ("Hyperparameters were set empirically through preliminary validation.", "Proposed Approach",
      "The selected hyperparameters were determined empirically through preliminary validation to achieve stable convergence and consistent validation performance."),
     ("The comparison with AQC-Net uses results reported for AQC-Net, not a re-run under the same conditions.", "Discussion",
      "Table 5 provides an additional comparison with the state-of-the-art results reported on the AQC-Net dataset."),
     ("Limitation: no ablation study was conducted for the temporal encoding and the auxiliary AQI head; this and evaluation across multiple random seeds are left to future work.","Discussion",
      "A limitation of this study is that no ablation study was conducted to evaluate the individual contribution of the temporal encoding and the auxiliary AQI regression head."),
   ],
   "notes": "Application domain: environmental / air quality (TRAQID dataset, meteorological and temporal features). Single run with seed 42."},

  {"id": "doi-10.3389_fcvm.2026.1909097",
   "title": "CIN-RiskNet: a dynamic feature-enhanced TabTransformer with hybrid SMOTE-noise augmentation for contrast-induced nephropathy prediction",
   "authors": ["Peng Zhang", "Zehao Yang", "Xue Zhang", "Keyu Gong", "Xiaogang Liu", "Shicheng Yang", "Zhiwei Zhang", "Ximing Li", "Runnan He"], "year": 2026,
   "version": "Publisher PDF via OpenAlex (publishedVersion)", "venue": "Frontiers in Cardiovascular Medicine",
   "links": {"doi": "https://doi.org/10.3389/fcvm.2026.1909097"},
   "pdf_url": "https://www.frontiersin.org/journals/cardiovascular-medicine/articles/10.3389/fcvm.2026.1909097/pdf", "license": "cc-by",
   "tasks": ["tabular-classification"], "fam": ["tabular-attention", "imbalance-resampling"], "par": ["supervised"],
   "proposes": ["CIN-RiskNet: feature-gated TabTransformer encoder with SMOTE + Gaussian-noise augmentation"],
   "claims": [
     ("CIN-RiskNet combines adaptive feature gating, SMOTE oversampling and multi-head self-attention in a TabTransformer.", "Abstract",
      "The approach includes adaptive feature gating to suppress noise, synthetic minority oversampling to address class imbalance, and multi-head self-attention to capture complex feature interactions."),
     ("Data and protocol: single-center cohort of 1,679 PCI patients (103 with CIN), evaluated with five-fold cross-validation; SMOTE and noise were applied only to the training subset of each fold, and 20% of each training set was held out for validation.", "Model training and evaluation protocol",
      "Importantly, in each fold, SMOTE and Gaussian noise were applied strictly to the training subset only, while validation and test subsets were kept untouched to prevent synthetic-sample leakage."),
     ("Baselines (logistic regression, random forest, XGBoost, SVM, MLP) used identical splits and preprocessing; how their hyperparameters were set is not found in the text.", "Results",
      "To ensure fairness in model comparisons, all methods adopted identical training/testing splits, uniform data preprocessing pipelines, and 5-fold cross-validation."),
     ("The paper reports CIN-RiskNet had the highest recall and F1 among the evaluated models, while random forest and XGBoost had slightly higher accuracy.", "Results",
      "Among all compared models, CIN-RiskNet achieved the highest recall (0.9540) and F1-score (0.9542), substantially outperforming traditional machine learning baselines in detecting minority-class samples (Table 4)."),
     ("The Mehran comparator is a modified version built from available variables because several original Mehran variables were not recorded.", "Comparison with clinical scoring",
      "We therefore constructed a modified Mehran-like comparator using available variables (age, diabetes, contrast volume, baseline Scr/eGFR) to provide a pragmatic local benchmark."),
     ("Limitation: single-center retrospective study; external multicenter validation is still required.", "Limitations",
      "First, this was a single-center retrospective study, which limits external generalizability despite the relatively large cohort (n = 1,679)."),
   ],
   "notes": "Application domain: cardiology / nephrology (contrast-induced nephropathy after PCI; 23 pre-/intra-procedural clinical variables). "
            "Reader caution (not a paper claim): the proposed model's reported accuracy and recall are identical, while baseline recall values look like positive-class recall; whether all models use the same averaging is not stated. "
            "The Table 5 ablation column labels also appear not to match the values quoted in the text. The decision threshold is fixed at 0.5 (Figure 3 caption)."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
