"""候補 Issue #1(表形式データ)で承認された論文のバッチ cand_2026_10_b04(10本)のカード。
書誌はバッチのメタデータ(arXiv API の値)を書き写した。結果表の数値は記録せず、主張と評価方法だけを記録する。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
  {"id": "arxiv-2609.36337", "title": "Adapting Linear-Time Architectures for Tabular In-Context Learning",
   "authors": ["David Schnurr", "Felix Sarnthein", "Thomas Hofmann", "Imanol Schlag"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.36337", "code": "https://github.com/schnurrd/ICL-Architectures"},
   "tasks": ["tabular-classification"], "fam": ["tabular-foundation-model", "tabular-attention"], "par": ["in-context-learning"],
   "proposes": ["Final-State DeltaNet with time-dependent write-rate decay for linear-time tabular ICL"],
   "claims": [
     ("Reading out from the final recurrent state (re-introducing non-causality) lets the linear-time model closely match a controlled softmax-attention baseline on OpenML-CC18 and TabArena.", "Abstract",
      "Finally, re-introducing non-causality by reading out from the final state allows us to closely match a controlled softmax attention baseline on OpenML-CC18 and TabArena."),
     ("DeltaNet degrades beyond roughly 2-4x the pretraining context length, and existing mitigations such as bidirectionality only defer the problem.", "Abstract",
      "However, it degrades beyond 2-4× the pretraining context length, and existing mitigation strategies such as bidirectionality defer the problem at best."),
     ("Evaluation protocol: datasets are preprocessed (feature cap; OpenML-CC18 subsampled to the pretraining size), while TabArena is used to measure length generalisation on larger datasets.", "Experimental setup",
      "OpenML-CC18 is further subsampled to at most n = 1000 samples to match the pretraining size, while TabArena measures real-world length generalisation on larger datasets."),
     ("External foundation-model baselines (TabPFN v2.5, TabICLv2, TabFlex) are the released checkpoints and are not controlled for training budget or model size.", "Appendix",
      "Importantly, these baselines are not controlled for training budget or model size: we evaluate the models released by their respective authors."),
     ("CatBoost is used untuned, as a default-configuration baseline, justified by the TabArena finding that it performs well out of the box.", "Appendix",
      "As shown in the TabArena evaluation by Erickson et al. (2026), CatBoost performs very well out of the box without hyperparameter tuning, supporting its use as a default configuration baseline."),
     ("Limitation: the study prioritises a controlled comparison over absolute performance; larger pretraining budgets and further tuning may disproportionately improve performance.", "Limitations",
      "Larger pretraining budgets and further tuning may disproportionately improve performance."),
   ]},
  {"id": "arxiv-2609.28836", "title": "M$^2$PFN: End-to-End Disentangled Alignment for Generalizable Multimodal In-Context Learning in Alzheimer's Disease",
   "authors": ["Lujia Zhong", "Shuo Huang", "Jianwei Zhang", "Xinyu Nie", "Yonggang Shi"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.28836"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["tabular-foundation-model", "deep-learning"], "par": ["in-context-learning", "supervised"],
   "proposes": ["M2PFN (frozen TabPFN as ICL head with end-to-end trained MRI and tabular encoders)"],
   "claims": [
     ("M2PFN is an end-to-end framework that turns TabPFN into a multimodal (MRI + tabular) Alzheimer's disease predictor.", "Abstract",
      "M2PFN, an end-to-end framework that turns this tabular foundation model into a multimodal AD predictor."),
     ("On two external cohorts without retraining, M2PFN achieves the best AUC and lowest MMSE MAE among the baselines.", "Abstract",
      "On two external cohorts (OASIS-3 and SCAN) with no retraining, M2PFN achieves the best AUC and the lowest MMSE MAE across all baselines, and transfers even when the cognitive instrument changes."),
     ("Evaluation protocol: all models are trained only on ADNI; OASIS-3 and SCAN serve only as external test sets.", "Experimental setup",
      "All models are trained exclusively on ADNI; OASIS-3 and SCAN are held out and used solely as external test sets."),
     ("Baselines are run with the default hyperparameters of their published code (no tuning).", "Baselines",
      "For every baseline, we adopt the default hyperparameters specified in the published code."),
     ("The tabular-only baselines are XGBoost, AutoGluon and TabPFN-v2.5.", "Baselines",
      "Unimodal tabular: XGBoost [42], AutoGluon [43], TabPFN-v2.5 [21]."),
     ("Results are reported as mean and standard deviation over 5 random seeds.", "Experimental setup",
      "Both instantiations are trained and evaluated with 5 random seeds, and we report the mean ± standard deviation across seeds"),
   ],
   "notes": "The authors state they contributed the differentiable-input path used here to the official TabPFN library (footnote, Introduction). Single dataset domain (Alzheimer's cohorts); tabular part is one modality."},
  {"id": "arxiv-2609.27679", "title": "What Do Tabular Foundation Models Compute In Context? In-Situ Representation Refinement through Attention-Gated Updates",
   "authors": ["Tian Zhou", "Beverly Jin", "Linxiao Yang", "Xue Wang", "Wenwei Wang", "Bingqing Peng", "Mengni Ye", "Jinjie Gu", "Liang Sun"], "year": 2026, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2609.27679"},
   "tasks": ["tabular-classification"], "fam": ["tabular-foundation-model", "tabular-attention"], "par": ["in-context-learning"],
   "proposes": ["REFINEICL (attention-gated, FFN-free tabular ICL model)", "In-situ representation refinement view of tabular ICL"],
   "claims": [
     ("A leave-one-out derivation separates attention-based reading from state-dependent scaling, which motivates REFINEICL, an attention-gated FFN-free stack with low-rank feature interaction and typed memory.", "Abstract",
      "The leading term separates attention-based reading from state-dependent scaling, motivating REFINEICL: an attention-gated, FFN-free contextual stack with selected low-rank feature interac- tion and typed memory."),
     ("The benchmark-informed REFINEICL continuation also improves all four reported metrics over TabPFN-v3 on both TabZilla views.", "Abstract",
      "It also improves all four reported metrics over TabPFN-v3 on both TabZilla views."),
     ("Evaluation protocol (TabArena): REFINEICL is evaluated on fold 0 only, with eight ensemble members and one support ordering.", "Appendix",
      "REFINEICL uses fold 0, eight ensemble members, and one support ordering shared across model sizes."),
     ("The TabArena comparison uses a fixed v0.1 snapshot with reference methods, which is not interchangeable with the live leaderboard.", "Appendix",
      "This fixed benchmark snapshot contains 77 reference methods and is not interchangeable with the live leaderboard."),
     ("The TabArena checkpoint is a benchmark-informed continuation; the authors call the TabArena result a development-exposed comparison.", "Appendix",
      "continuation’s prior choice; this is a development-exposed comparison."),
     ("The native AMLB29 inference protocol follows the archived TabPFNv2 classifier defaults (fixed number of estimators, seed, temperature and a row ceiling).", "Appendix",
      "The AMLB29 native protocol follows the archived TabPFNv2 classifier defaults: four estimators, seed 0, temperature 0.9, and a 10,000-row ceiling."),
   ],
   "notes": "Authors are affiliated with Ant Group (and independent researchers). Benchmarks: TabArena v0.1 snapshot, AMLB29, OpenML-CC18, Grinsztajn, TabZilla."},
  {"id": "arxiv-2609.25541", "title": "A JEPA Recipe for Tabular Foundation Models",
   "authors": ["Mingyu Jeon", "Suwan Cho", "Jae Young Suh"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.25541"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["tabular-foundation-model"], "par": ["in-context-learning", "self-supervised"],
   "proposes": ["Recipe for training a JEPA latent term beside the value objective of a tabular foundation model without collapse", "Open-horizon plateau stopping rule for comparing training arms"],
   "claims": [
     ("A recipe lets the JEPA latent term survive to convergence beside the value objective: the value head reads the encoder field and the target is an EMA difference.", "Abstract",
      "We report a recipe under which the latent term survives to convergence beside the value objective: the value head reads the encoder field rather than the predictor, and the target is an exponential moving average (EMA) difference."),
     ("The JEPA recipe does not beat the value-only arm at convergence, and the authors do not claim it does.", "Introduction",
      "The recipe does not beat the value-only arm at convergence, and we do not claim that it does (§4.3)."),
     ("Evaluation suite: classification and regression datasets drawn from OpenML-CC18, the Grinsztajn benchmark and TabArena.", "Experimental setup",
      "The real-data suite holds 115 classification and 32 regression datasets from OpenML-CC18, the Grinsztajn benchmark and TabArena (Bischl et al., 2021; Grinsztajn et al., 2022; Erickson et al., 2025)."),
     ("Each model gets a capped context and feature budget (features chosen by an F-test before the split) and is scored on 3 random halves with a capped test size.", "Appendix",
      "give each model at most 1,024 rows of context and 64 features picked by an F-test ahead of the split, average 3 random halves scoring no more than 512 test rows in each"),
     ("Neither foundation-model arm beats gradient-boosted trees (HistGB) on the suite.", "Results",
      "Neither arm beats gradient-boosted trees, with ds at 28:84 on classification and 4:28 on regression and jepa at 27:87 and 3:29 (Figure 4)."),
     ("Limitation: one seed per arm is the sharpest limit on every claim.", "Limitations",
      "One seed per arm is the sharpest limit on every claim, because the sign test spans datasets rather than seeds and the noise floor comes from a second run of the same seed, which a second seed would be expected to widen (§4.1)."),
   ],
   "notes": "HistGB and linear references are fitted on the full training half (more rows than the 1,024-row context of the arms); their hyperparameter settings were not found in the text."},
  {"id": "arxiv-2609.23574", "title": "PACE: Plug-and-Play Contextual Embedding for Feature Screening with Pretrained Tabular Foundation Models",
   "authors": ["Qi Qin", "Erbo Li", "Ting Wei", "Zizhou Huang", "Zixuan Qin", "Wu Wang", "Yifan Sun"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.23574"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["tabular-foundation-model"], "par": ["supervised"],
   "proposes": ["PACE (frozen TFM column encoder inserted before a feature-screening utility)"],
   "claims": [
     ("PACE inserts a frozen tabular foundation model column encoder before an existing feature-scoring rule, expanding each feature into a higher-dimensional contextual representation.", "Abstract",
      "We intro- duce PACE (Plug-and-Play Contextual Embedding), which inserts a frozen tabular foundation model (TFM) column encoder before an existing feature-scoring rule, expanding each feature into a higher-dimensional contextual representation."),
     ("Matched random-weight and random-feature controls indicate the gains come from pretrained structure, not just dimensional expansion.", "Abstract",
      "Matched random-weight and random-feature controls show that PACE gains from pretrained structure beyond generic dimen- sional expansion."),
     ("Evaluation protocol: TALENT datasets are augmented with independent Gaussian nuisance features up to a fixed total width before screening.", "Appendix",
      "the nuisance-augmented table adds independent N(0, 1) features until its total width is 2,000"),
     ("Screened features are evaluated with ten downstream learners in three families (tree models, neural networks, tabular foundation models).", "Experimental setup",
      "We evaluate the selected columns using ten learners in three families"),
     ("When a TALENT training partition is large, embedding and utility estimation use a row-capped subsample.", "Appendix",
      "When a TALENT training partition exceeds 2,000 rows, embedding and utility estimation use at most 2,000 rows, selected by stratified sampling for classification and by sampling without replacement for regression using the corresponding random seed."),
     ("Limitation: screening performance still depends on representation, utility, backbone and extraction strategy.", "Conclusion",
      "Screening performance still depends on the representation, utility, backbone, and extraction strategy."),
   ],
   "notes": "Feature screening method; no dedicated tag, tabular-foundation-model used as closest family. How the downstream learners' hyperparameters were set (defaults vs tuning) was not found in the text."},
  {"id": "arxiv-2609.16091", "title": "Distilling Foundation Models for Agentic What-If Reasoning:Cost, Latency, and Governance in a Hybrid LLM+SLM Architecture",
   "authors": ["Sourish Dey", "Aditya Kumar"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.16091", "code": "https://github.com/nitsourish/Model-Distillation-Agentic-Workflow"},
   "tasks": ["tabular-classification", "tabular-regression", "model-compression"], "fam": ["knowledge-distillation", "tabular-foundation-model", "tabular-mlp", "large-language-models"], "par": ["supervised"],
   "proposes": ["TabPFN-to-MLP knowledge distillation embedded in a hybrid LLM+SLM agentic pipeline"],
   "claims": [
     ("A TabPFN teacher is distilled into a compact feed-forward student on a UCI Adult business-decision simulation and five OpenML datasets.", "Abstract",
      "We distill a TabPFN teacher into a compact feed-forward student across a business-decision simulation on UCI Adult and five OpenML benchmarks"),
     ("The end-to-end latency gain comes almost entirely from removing in-context TabPFN from the hot path.", "Abstract",
      "Span-level attribution shows that this wall-clock gain is almost entirely from removing in-context TabPFN from the hot path; fewer cloud round-trips cut token cost (2.1×) rather than latency."),
     ("Evaluation protocol: classification results use the default settings of the authors' scripts (no per-dataset tuning was found in the text).", "Experimental setup",
      "Unless a caption names an exception, every classification result in Tables 3 and 9 uses the defaults of scripts/run_distillation.py and scripts/run_classification_benchmark.py."),
     ("For the UCI Adult simulation, training used a row-capped stratified subsample (because of the teacher's context limit) with an 80/20 train/test split.", "Experimental setup",
      "Training used a stratified 10,000-row subsample (the tabular foundation-model teacher’s pretrained context window is optimized for ≤10K rows) with an 80/20 train/test split (8,000/2,000)."),
     ("Limitation: the regression target is synthetic (rule-simulated) with no external ground truth.", "Limitations",
      "max_loan is a rule-simulated target with no external ground truth; classification labels are the real Adult income indicator."),
     ("Limitation: distillation results come from a single seed.", "Limitations",
      "Distillation tables use seed 42."),
   ],
   "notes": "First author is affiliated with SumUp (company). Mostly a systems/agentic paper; the tabular part is distillation of TabPFN."},
  {"id": "arxiv-2608.28408", "title": "SymboLLM-FE: LLM-Accelerated Symbolic Regression for Automated Feature Engineering on Tabular Data",
   "authors": ["Zi-Jian Cheng", "Zi-Yi Jia", "Zhi Zhou", "Yu-Feng Li", "Lan-Zhe Guo"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.28408"},
   "tasks": ["tabular-classification", "tabular-regression"], "fam": ["large-language-models", "automl-systems"], "par": ["supervised"],
   "proposes": ["SymboLLM-FE (symbolic regression formulas refined by an LLM for automated feature engineering)"],
   "claims": [
     ("Formulas correlated with the target are extracted by symbolic regression and then refined by an LLM for interpretability.", "Abstract",
      "We extract math- ematically expressive formulas strongly corre- lated with the target via symbolic regression, which can enhance model performance, then refine them by LLMs with rich prior knowl- edge to ensure interpretability."),
     ("On six real-world datasets and four Kaggle competitions, SymboLLM-FE outperforms existing AutoFE methods.", "Abstract",
      "Empirical re- sults on six real-world datasets and four Kaggle competitions demonstrate that SymboLLM-FE outperforms existing AutoFE."),
     ("Evaluation protocol: a fold-wise protocol within cross-validation is used.", "Method",
      "SymboLLM-FE strictly adheres to a fold-wise training protocol within a cross- validation framework."),
     ("The validation set is used only for hyperparameter tuning, to prevent leakage into the test evaluation.", "Method",
      "To strictly prevent data leakage, the validation set is employed exclusively for hyperparameter tuning."),
     ("Downstream models (CatBoost, XGBoost, MLP, TabPFN) have hyperparameter grids reported in the appendix.", "Experimental setup",
      "Appendix C.2 shows these baselines’ information and full hyperparameter grids."),
     ("Limitation: the sliding-window subset construction over importance-sorted features may miss synergies among non-adjacent variables.", "Limitations",
      "Second, the subset construction strategy, which sorts features in descending order of importance and employs a continuous sliding window, may fail to capture synergistic effects among non-adjacent variables."),
   ],
   "notes": "Automated feature engineering (symbolic regression + LLM refinement); no feature-engineering tag exists, so large-language-models (the refinement step) and automl-systems are the closest families."},
  {"id": "arxiv-2608.27076", "title": "Tabular Deep Learning for Algorithmic Trading: Cross-Regime Bayesian Optimisation for Equity Signal Generation",
   "authors": ["Joshua Le Grice"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.27076"},
   "tasks": ["tabular-classification"], "fam": ["gradient-boosted-trees", "tabular-attention", "tabular-mlp", "linear-models", "heterogeneous-ensembles"], "par": ["supervised"],
   "proposes": ["Cross-regime Bayesian hyperparameter optimisation for equity signal models", "XGBoost+TabNet rank-aggregation Hybrid ensemble"],
   "claims": [
     ("Existing evaluations of equity prediction models do not explicitly target regime robustness in hyperparameter selection.", "Abstract",
      "Existing evaluations of equity prediction models do not explicitly target regime robustness during hyperparameter selection."),
     ("No single tabular deep learning architecture outperforms gradient-boosted trees; combining XGBoost and TabNet by rank aggregation gives the Hybrid ensemble.", "Abstract",
      "No individual tabular deep learning architecture outperforms gradient-boosted trees, but combining XGBoost and TabNet using rank aggregation produces a Hybrid ensemble"),
     ("Tuning protocol: all models are tuned with Optuna TPE, with the same trial budget per model.", "Experimental setup",
      "Hyperparameters for all models are selected using Bayesian optimisation via the Optuna framework [54], utilising a Tree-structured Parzen Estimator (TPE) [55] sampler with 30 trials per model."),
     ("The out-of-sample year is excluded from model development and hyperparameter selection.", "Experimental setup",
      "The 2025 period was excluded from model development and hyperparameter selection to provide an uninfluenced estimate of real-world performance."),
     ("Limitation: using index constituents identified at the end of the sample introduces survivorship bias.", "Limitations",
      "Using S&P 500 constituents identified at the end of the sample period introduces survivorship bias."),
     ("Limitation: the reported figures come from selecting the best configuration among many trialled configurations (no deflated Sharpe correction).", "Limitations",
      "Also, reported figures reflect the selection of the best-performing configuration from approximately 161 trialled across the five model classes and their ensemble combinations."),
   ],
   "notes": "MSc project; models: logistic regression, XGBoost, MLP, TabNet, FT-Transformer. Financial time-ordered cross-sectional data with expanding-window validation."},
  {"id": "arxiv-2609.22154", "title": "A Comparative Framework for Evaluating Foundation Models on Tabular Data: A Case Study in Healthcare",
   "authors": ["Majid Lotfian Delouee", "Sjors G. J. G. In 't Veld", "Martijn C. Schut"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2609.22154"},
   "tasks": ["tabular-classification"], "fam": ["tabular-foundation-model"], "par": [],
   "proposes": ["OpTFM (property-based comparative framework for tabular foundation models)", "Taxonomy of 45 tabular foundation models"],
   "claims": [
     ("OpTFM scores and ranks tabular foundation models across six clinically meaningful dimensions.", "Abstract",
      "We introduce OpTFM, a comparative evaluation framework that scores and ranks tabular foundation models (TFMs) across six clinically meaningful dimensions"),
     ("Applied to two healthcare use cases, the same metrics lead to different model rankings depending on clinical priorities.", "Abstract",
      "To show how the framework works in practice, we apply it to two healthcare use cases, screening for iron deficiency and predicting heart failure, demonstrating how the same set of metrics leads to different model rankings depending on what matters most in each clinical context."),
     ("Evaluation protocol: no models are run; sub-metric scores are derived from each model's documented design properties.", "Framework",
      "sub-metric scores are derived from each model’s documented design properties"),
     ("Scores start at a default of 10 and are reduced by 1 for each missing or problematic property.", "Case study",
      "Models start with a default sub-metric score of 10, and each missing or problematic property reduces the relevant sub-metric scores by 1."),
     ("The scores are property-based estimates, not substitutes for empirical measurement.", "Case study",
      "The resulting scores should therefore be interpreted as property- based estimates of model suitability for comparison within the framework, rather than as substitutes for direct empirical measurement."),
     ("Scoring each model only against its own paper rewards papers with narrow or dated baselines and penalises papers candid about limitations, which motivated a second audit pass using independent literature.", "Case study",
      "scoring each model’s properties against its own publication alone systematically rewards models whose papers compare against a narrow or dated set of baselines, and penalizes models whose papers are comparatively candid about their own limitations"),
   ],
   "notes": "No empirical experiments; rankings are property-based from literature, not measured."},
  {"id": "arxiv-2608.24056", "title": "PhysicsBench: A Unified Leaderboard for Generative and Predictive Models in Engineering Design and Simulation",
   "authors": ["Sang Won Lee", "Hyogu Jeong", "Namwoo Kang"], "year": 2026, "version": "arXiv v1",
   "links": {"arxiv": "https://arxiv.org/abs/2608.24056", "code": "https://github.com/Narnialabs/leaderboard"},
   "tasks": ["tabular-regression"], "fam": ["deep-learning", "tabular-foundation-model", "gradient-boosted-trees", "gaussian-processes"], "par": ["supervised"],
   "proposes": ["PhysicsBench leaderboard", "BenchRank (debiased PageRank ranking over a dominance graph)"],
   "claims": [
     ("PhysicsBench is a unified benchmark and leaderboard that evaluates generative and predictive models under one standardized procedure.", "Abstract",
      "We present PhysicsBench, a unified benchmark and leaderboard that evaluates generative and predictive models under one standardized procedure."),
     ("An architecture's large-scale academic standing only weakly predicts its small-data ranking.", "Abstract",
      "Across tasks, an architecture’s large-scale academic standing weakly predicts its small-data ranking."),
     ("The tabular models in the 1D task include MLP, FT-Transformer, NODE, TabNet, TabPFN, gradient-boosted trees, Gaussian processes and ridge regression.", "Experimental setup",
      "The 1D tabular models are an MLP, FT-Transformer [46], NODE [77], TabNet [47], TabPFN [48], gradient-boosted trees [78, 79], Gaussian processes [80], and ridge regression [81]"),
     ("Tuning protocol: splits, epoch/batch budget, early stopping and normalization are shared, but each model's optimizer, learning rate and internal hyperparameters follow its source paper (no re-tuning).", "Experimental setup",
      "This fixes the shared procedure of data splits, resolution, epoch and batch budget, early stopping, and normalization, but not each model’s own optimizer, learning rate, and internal hyperparameters, which follow its source paper."),
     ("The tabular regression part uses Concrete and Airfoil and is ranked separately from time-series models.", "Results",
      "The 1D scalar task is reported as two rows, tabular regression on Concrete and Airfoil and time-series RUL on CMAPSS, because these span disjoint model sets, so a single pooled ranking would compare models that never competed head-to-head."),
     ("Conflict of interest: the leaderboard is vendor-hosted; author-affiliated in-house models are excluded from publication, and the authors say a fuller conflict-of-interest policy is needed.", "Limitations",
      "We exclude all author-affiliated in-house models from publication regardless of their measured rank, so the policy applies whether an in-house model would have won or lost, but a fuller governance and conflict-of-interest policy is needed."),
   ],
   "notes": "Mostly an engineering simulation (CAD/CFD/FEA) benchmark; only the 1D scalar task is tabular regression (small UCI datasets at limited data scales). Authors are affiliated with Narnia Labs, which hosts the leaderboard."},
]

build(SPECS, base_note="Approved from candidate issue #1 (2026-10-02); carded by a subagent. Results tables not recorded; claims only.")
