import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ci_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2101.10943",
     "title": "Nonparametric Estimation of Heterogeneous Treatment Effects: From Theory to Learning Algorithms",
     "authors": ["Alicia Curth", "Mihaela van der Schaar"],
     "year": 2021, "venue": "AISTATS 2021", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2101.10943", "code": "https://github.com/AliciaCurth/CATENets"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners", "treatment-effect-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["A classification of CATE meta-learners following the ATE estimator taxonomy: one-step plug-in learners (S- and T-learners, differencing two outcome regressions) and two-step pseudo-outcome learners based on regression adjustment (RA-learner), propensity weighting (PW-learner) or both (DR-learner)",
                  "An analysis of the remainder terms of RA- and PW-learners (with the DR-learner bound from Kennedy, 2020) under smoothness assumptions and two-sample estimation, plus finite-sample considerations (variance of propensity weighting, selection bias, overlap)",
                  "SNet: a neural architecture with five representations (shared, outcome-specific and propensity-related) that contains TNet, TARNet (SNet-1), DragonNet's architecture (SNet-2) and DR-CFR (SNet-3) as special cases; sklearn-style implementations in the CATENets package"],
     "claims": [
         ("Motivation: meta-learners decompose treatment effect estimation into sub-problems solvable with standard supervised learning, but choosing between them in a data-driven way is difficult because it requires counterfactual information; the authors therefore analyze theoretically when some learners can be expected to perform better a priori.",
          "Abstract",
          "Choosing between diﬀerent meta-learners in a data-driven manner is diﬃcult, as it requires access to counterfactual information."),
         ("Estimand and identification: the target is the CATE tau(x) = E[Y(1) - Y(0) | X = x] for a binary treatment, estimated under Assumption 1 (consistency, unconfoundedness with no unobserved confounders, and overlap 0 < pi(x) < 1); no parametric form is assumed for tau or the nuisance functions, giving a nonparametric problem. The authors note that identification hinges on untestable assumptions.",
          "Section 2",
          "It is well known that the identiﬁcation of causal eﬀects from observational data hinges on the imposition of untestable assumptions."),
         ("Taxonomy: two-step learners regress a pseudo-outcome that is unbiased for CATE when the nuisances are known: the RA-learner (of which Künzel et al.'s X-learner is described as a variant that needs a weighting function g(x)), the PW-learner (Horvitz-Thompson transformation) and the DR-learner (Kennedy, 2020; AIPW pseudo-outcome). The R-learner of Nie and Wager (2020) fits none of these categories, requires specific model-fitting procedures (e.g. manipulating a loss function), and is not considered further.",
          "Section 3",
          "The R-learner proposed in Nie and Wager (2020) does not fall in any of these categories."),
         ("Asymptotic comparison (Theorem 1, assuming bounded propensity estimates, smoothness of mu_w, pi and tau, and the two stages fit on separate samples): the RA-learner remainder depends on the outcome-regression errors, the PW-learner remainder on the propensity error, and the DR-learner remainder on their product; by asymptotic properties the DR-learner is preferred among two-step learners, and the PW-learner over the RA-learner if the propensity score is easier to estimate than the outcome regressions. The authors add that it is commonly assumed that tau(x) is simpler than mu_0(x), so RA-learner reaching the oracle rate is unlikely and RA- and plug-in learners are expected to perform similarly asymptotically.",
          "Section 4",
          "By asymptotic properties, we thus prefer the DR-learner over the other two-step learners"),
         ("Finite samples cannot rely on convergence rates only: inverse-propensity-weighted estimators have high variance, particularly with extreme propensity scores, and the PW-learner pseudo-outcome has very high variance even with constant, known propensities; for small delta the constants in the PW- and DR-learner error bounds can be large, possibly leading to relatively better performance of the RA-learner in smaller samples.",
          "Section 4",
          "the pseudo-outcome associated with the PW-learner has a very high variance even when propensity scores are constant and known"),
         ("Selection bias (pi(x) != 0.5 for some x) does not matter asymptotically but can be severe in finite samples if the propensity bound omega is small, because fitting each outcome surface on factual data gives too much weight to samples with large pi(x) (a similar conclusion is attributed to Alaa and van der Schaar, 2018b); the degree of overlap is therefore of paramount importance, and second-stage regressions on all data can correct for the sub-optimal first-stage weighting.",
          "Section 4",
          "It also shows that the degree of overlap, which determines ω, is of paramount importance."),
         ("Neural architectures: besides TNet (separate networks), SNet-1 is TARNet (Shalit et al., 2017), SNet-2 uses only the architecture of DragonNet (Shi et al., 2019; not its targeted ATE estimation), SNet-3 is DR-CFR (Hassanpour and Greiner, 2020) without propensity re-weighting in the loss, and the proposed SNet learns five representations, allowing features that affect only one potential outcome; the authors expect SNet to perform best on average without knowledge of the problem structure but say it may be more difficult to fit.",
          "Section 5",
          "We expect that such a general architecture should perform best on average in absence of knowledge on the underlying problem structure, but may be more diﬃcult to ﬁt than simpler models."),
         ("Gap between theory and experiments: the theoretical analyses rely on sample splitting for two-step learners, but the authors observed that using all data for both steps can work better in practice (particularly in small samples) and use no sample splitting in the experiments; they suggest cross-fitting when guarantees are desired and data are scarce, and note that hyper-parameters can be tuned using factual hold-out data only.",
          "Section 5",
          "While we implement all strategies in our code base, we do not use any form of sample splitting in our experiments."),
         ("Conclusion: while the DR-learner is asymptotically optimal in theory, the RA-learner and plug-in learners that share information between nuisance tasks can outperform it in finite samples; relative performance depends on the DGP and sample size, so the choice of learner should incorporate an expert's assessment of the most likely DGP. Only NNs were used as base learners; comparing ML methods (e.g. NNs versus random forests) is left as a next step.",
          "Section 7",
          "We demonstrated that while the DR-learner is asymptotically optimal in theory, both the RA-learner and plug-in learners sharing information between nuisance estimation tasks can outperform it in ﬁnite samples."),
         ("Pseudo-outcomes of the two-step learners (Eq. 2-3): the RA-learner regresses W(Y - mu0_hat(X)) + (1 - W)(mu1_hat(X) - Y) on X; the PW-learner uses the Horvitz-Thompson transformation (W / pi_hat(X) - (1 - W)/(1 - pi_hat(X))) Y. The X-learner is described as a variant of the RA-learner that fits two separate regressions combined with a weight g(x); the authors prefer RA-learning because it needs no choice of g.", "Section 3", "We prefer the RA-learning strategy here, as it does not require choice of ‘hyper-parameter’ g(x)."),
     ],
     "notes": "Affiliations: University of Cambridge; van der Schaar also UCLA and The Alan Turing Institute. Venue from the PDF footer ('Proceedings of the 24th International Conference on Artificial Intelligence and Statistics (AISTATS) 2021, San Diego, California, USA. PMLR: Volume 130'), consistent with the arXiv comment. Section numbers from numbered headings in the PDF (6.1 Synthetic Experiments, 6.2 IHDP). Conflict of interest: SNet is proposed by the authors, all architectures were re-implemented in the authors' own code base (CATENets), and the theory builds on the senior author's earlier work (Alaa and van der Schaar 2018a,b). Experimental setup: d = 25 multivariate normal covariates, three stylized DGPs (no effect with confounding; nonzero effect on 5 additional covariates; disjoint covariate sets for mu_1 and mu_0 without confounders), 500 test observations, averaged across 10 runs; IHDP uses an adapted version of the 100 realizations of Shalit et al. (2017) with responses rescaled because the CATE scale varied by orders of magnitude (footnote 5); n = 747, 90% used for training, 19% treated, partial overlap. Results are in figures and Table 1 and are not recorded. The text also states that the DR-learner is best combined with a nuisance estimator that does not share information between pi(x) and mu_w(x) (Section 6.1). In the experiments, equivalent hyper-parameters (based on Shalit et al., 2017) were fixed across architectures and each learner was used 'off-the-shelf' (Section 6). Referred to by arxiv-2107.13346 as reference [9]."},

    {"id": "arxiv-2107.13346",
     "title": "Doing Great at Estimating CATE? On the Neglected Assumptions in Benchmark Comparisons of Treatment Effect Estimators",
     "authors": ["Alicia Curth", "Mihaela van der Schaar"],
     "year": 2021, "venue": "NACI workshop at ICML 2021", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2107.13346"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners", "treatment-effect-networks", "random-forests", "deep-learning"], "par": ["supervised"],
     "proposes": ["Case studies on the IHDP and ACIC2016 semi-synthetic benchmarks that compare RF- and NN-based, direct and indirect CATE estimators to show how benchmark DGP assumptions favor some estimators",
                  "A modified IHDP setting with an additive (linear) treatment effect, and an ACIC2016 check that feeds the DGP's dichotomized covariates to the models"],
     "claims": [
         ("Main claim: even under ignorability, empirical evaluations on semi-synthetic benchmarks can be misleading if the assumptions of the benchmark DGPs and their interplay with baseline algorithms are not discussed; for IHDP and ACIC2016 the inherent characteristics of the datasets favor some algorithms over others, which the authors say is rarely acknowledged.",
          "Abstract",
          "We identify problems with their current use and highlight that the inherent characteristics of the benchmark datasets favor some algorithms over others – a fact that is rarely acknowledged but of immense relevance for interpretation of empirical results."),
         ("Theoretical argument used to predict benchmark outcomes (citing [1, 9, 23, 25]): for indirect estimators (differencing two outcome regressions) the error is driven by the more complex of the two regression surfaces, while some direct estimators can attain the error rate of the effect function f_tau; direct learners thus have a theoretical advantage whenever f_tau is easier to estimate, which diminishes as f_1 and f_0 become less similar.",
          "Section 2.2",
          "direct learners thus have a clear theoretical advantage – which diminishes as f1(x) and f0(x) become less similar (making fτ(x) increasingly complex)."),
         ("Protocol: indirect estimators T-learner RF (TRF), S-learner RF (SRF), TNet and TARNet, and direct estimators Causal Forest and an NN-based R-learner (RNet), implemented with the R package grf and the python package catenets; all models were used off-the-shelf (2000 trees for RFs, NN hyperparameters similar to those of Shalit et al. for IHDP).",
          "Section 3",
          "We use all models off-the-shelf; for all RFs this entails using 2000 trees, and all NNs have hyperparameter settings similar to those used in [36] for the IHDP experiments."),
         ("IHDP reporting problem: the IHDP DGP (setup 'B' of Hill, 2011) fixes the ATT at 4 across runs but lets CATE vary freely, so the within-test-set spread of CATE ranges between 0.04 and 51.51 across the 100 simulations; simply averaging RMSE across runs gives algorithms that perform well mainly in the tails a clear advantage, and the authors suggest it might be more appropriate to use alternatives such as normalized RMSE or paired sample test statistics.",
          "Section 3.1.1",
          "The common practice to simply report an average RMSE score across all runs gives algorithms that perform well mainly in the tails a clear advantage; thus it might be more appropriate to consider alternative metrics (e.g. normalized RMSE or paired sample test statistics)."),
         ("IHDP conclusion: the advantage of TARNet over Causal Forest has multiple sources; the IHDP DGP favours NNs over RFs and indirect over direct estimators, and Causal Forest does worse on runs with extreme CATE spread, which get much more weight. When the DGP was changed so that the treatment effect is additive and linear, the relative performance reversed.",
          "Section 3.1.2",
          "When tweaking the DGP slightly to create a simple and additive treatment effect, the relative performance reverses, highlighting that performance is indeed determined by the interplay between assumptions underlying a learning algorithm and the DGP."),
         ("ACIC2016 hidden DGP choice: the simulated response surfaces are built not from the raw covariates but after the 27 count variables are dichotomized by the organizers (Dorie et al.); the authors describe this as the most natural pattern for an RF and found that feeding the transformed data improved the NNs substantially while the RFs did not change, concluding that some aspects of the DGP may inherently favor tree-based methods.",
          "Section 3.2.1",
          "We found that the simulated response surfaces are not created using the raw data as input, instead the 27 count variables are dichotomized by [12] before they are used in the DGP."),
         ("Composition of ACIC2016: of its 77 settings, only 2 have no treatment-effect heterogeneity, 32 low and 43 high heterogeneity, so the authors expect that indirect learners will generally be favoured on this benchmark on average.",
          "Section 3.2.2",
          "we would expect that – on average – indirect learners will generally be favoured on this benchmark."),
         ("Implications: because relative performance can change across DGPs/assumptions, assessments based on a single dataset/DGP such as IHDP capture only one setting, which the authors think warrants reconsidering the label 'state-of-the-art'.",
          "Section 4",
          "This means that performance assessments based on a single dataset/DGP (e.g. IHDP) capture only one speciﬁc setting of many conﬁgurations of possible drivers of relative performance."),
     ],
     "notes": "Affiliations: University of Cambridge; van der Schaar also UCLA and The Alan Turing Institute. Venue: workshop paper, from the PDF page 1 footer ('Workshop on the Neglected Assumptions in Causal Inference (NACI) at the 38th International Conference on Machine Learning, 2021') and the arXiv comment. Conflict of interest: the NN estimators are run with the authors' own catenets implementations, and the theoretical argument and the TARNet-as-S/T-hybrid view come from the authors' own earlier paper (reference [9] = arxiv-2101.10943). Funding: AC acknowledges funding from AstraZeneca. The tree-boundary-bias explanation for IHDP is introduced as speculation ('let us speculate') and checked with a figure; figure-only results are not recorded. IHDP-100 is evaluated on the pre-determined 10% hold-out with 5 seeds per run; the ACIC2016 case study uses settings 2, 26 and 7 (no, low, high heterogeneity) and only the first 10 of 100 runs (Section 3.2). Section 4 also suggests principled baselines that vary one dimension at a time and experimental knobs, and expects generative benchmarks to favor estimators similar to the generating methods. Hyperparameter effects are listed as future research. The authors acknowledge the study covers only two benchmarks. Critiques the benchmark designed in arxiv-1707.02641 (ACIC2016)."},

    {"id": "arxiv-1707.02641",
     "title": "Automated versus do-it-yourself methods for causal inference: Lessons learned from a data analysis competition",
     "authors": ["Vincent Dorie", "Jennifer Hill", "Uri Shalit", "Marc Scott", "Dan Cervone"],
     "year": 2017, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1707.02641", "code": "https://github.com/vdorie/aciccomp/tree/master/2016"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["tree-ensembles", "decision-trees", "linear-models"], "par": ["supervised"],
     "proposes": ["The 2016 Atlantic Causal Inference Conference competition ('Is Your SATT Where It's At?'): 77 simulation settings built on real covariates from the Collaborative Perinatal Project (4802 observations, 58 covariates) with simulated treatment and outcomes, 100 replications each for the black-box track and 20 data sets for the do-it-yourself track, estimand SATT",
                  "Post-competition methods created by the organizers by combining or tweaking top submissions (e.g. BART with IPTW/TMLE, cross-validated priors, multiple chains, propensity score as covariate)"],
     "claims": [
         ("Motivation: the authors argue that papers proposing new methods have shortcomings as a source of evidence about which method is best; strong performance of a method in a paper written by its inventor is encouraging but should be interpreted cautiously.",
          "Section 2.1",
          "Strong performance of a method in a paper written by its inventor is encouraging but should be interpreted cautiously for the reasons discussed in this section."),
         ("Competition design against unfair comparisons: the researchers creating the simulated testing grounds were distinct from those submitting methods; results are reported for 30 competitors across the black-box and do-it-yourself versions.",
          "Abstract",
          "The researchers creating the data testing grounds were distinct from the researchers submitting methods whose eﬃcacy would be evaluated."),
         ("Organizers' role: the organizers were not allowed to submit methods; for the black-box competition they included a simple main-effects linear model as a baseline, distinct from the methods they created after the competition.",
          "Section 5",
          "The organizers were not allowed to submit methods to the competition; however for the black-box competition we included a simple linear model using main eﬀects to create a baseline for comparison (as distinct from the “created” methods described later)."),
         ("Overlap design choice: since the estimand is the sample average treatment effect on the treated (SATT), overlap is required only for treated units (empirical counterfactuals for all treated), and settings without common support for the inferential group were excluded because changing the estimand would make fair comparison too complicated.",
          "Section 4.1",
          "Given our focus on SATT, to satisfy the overlap assumption we only need to ensure that empirical counterfactuals exist for all treated units."),
         ("Scenario selection: the response surface and assignment mechanism are random generalized additive functions controlled by tunable 'knobs'; all knob combinations yield 216 scenarios, of which the organizers focused on 77 by eliminating trivial or redundant ones (e.g. simple linear models or unconfounded treatment and response).",
          "Section 4.3",
          "Concern about the ability to test multiple replications in that many scenarios led us to focus on the most interesting 77 combinations by eliminating cases that were trivial or redundant, such as simple linear models or unconfounded treatment and response."),
         ("Organizer-created methods: after preliminary results were presented, the organizers created nine additional methods by tweaking and combining submissions (mostly BART variants, plus Super Learner variants); they state that, not surprisingly, the methods created or submitted after the initial deadline all performed particularly well relative to the others, except SL+TMLE Joint (which they say likely failed because many methods in its ensemble library could not fit non-parallel response surfaces).",
          "Section 6.2",
          "In particular, and not surprisingly, the methods created or submitted after the initial deadline all performed particularly well relative to the others with the exception of SL+TMLE joint"),
         ("Predicting performance: the authors could not go beyond a general recommendation of flexible nonparametric response-surface modeling; under almost no condition could they predict which black-box method would outperform others beyond its average performance, and they describe relative performance as much less contextual than imagined.",
          "Section 7",
          "Overall, we ﬁnd that to a surprising degree we could not go beyond a general recommendation of using ﬂexible non-parametric response surface modeling."),
         ("What did well: nonlinear response surfaces and treatment effect heterogeneity were two of the three complexities that created the most difficulty for low bias; methods able to flexibly model the response surface routinely distinguished themselves, even methods like BART that modeled only the response surface, and outperformed approaches that only flexibly modeled the assignment mechanism (Balance Boost, Tree Strat, Adj. Tree Strat).",
          "Section 8",
          "This held true even for methods like BART that only modeled the response surface and not the assignment mechanism."),
         ("Caveat: the authors say there are several good options for accurately estimating causal effects (particularly for reducing bias), but this advice applies only to testing grounds where ignorability holds, overlap for the inferential group is satisfied and the data are i.i.d.; these properties may not hold in practice.",
          "Section 8",
          "Of course that advice comes with the caveat that our testing grounds have been restricted a range of settings where ignorability holds, overlap for the inferential group is satisﬁed, the data are i.i.d., etc.; these properties may not hold in practice"),
     ],
     "notes": "Affiliations (page 1 footnote): New York University (Dorie, Hill, Scott), Technion (Shalit), Los Angeles Dodgers (Cervone). No venue recorded: the arXiv v5 PDF says only 'Submitted to Statistical Science' and the arXiv record has no journal_ref (arxiv-2107.13346 cites a Statistical Science 2019 version, which is not used as a source here). Conflict of interest: the organizers did not submit methods (Section 5, footnote 8), but they created nine post-competition methods after seeing preliminary results, mostly variants of BART; Hill authored the BART-for-causal-inference approach cited for the BART submission (Hill, 2011), and the BART submission came from Douglas Galagate and separately Nicole Bohme Carnegie (Appendix A.6), Carnegie being a co-author with Dorie and Hill of Dorie et al. (2016) in the reference list. The non-oracle alignment metric in Section 7.3 uses BART-estimated unit-level effects. PEHE was available only for the subset of methods that output individual effects (Section 6.2). DIY results rest on 20 data sets and the authors are 'reluctant to draw strong conclusions' about them (Section 6.1). Bias/RMSE/coverage values are from figures and are not recorded. Section 8 also states that good coverage was difficult for most methods even when bias was low, and Section 4.4 lists issues not addressed (non-binary treatment, non-continuous response, non-IID data, varying data size, covariate measurement error, violations of ignorability/overlap). With non-oracle metrics the R^2 of per-method performance models rarely exceeded 0.10 (Section 7.2). The ACIC2016 benchmark designed here is critiqued in arxiv-2107.13346 (dichotomized count covariates, mostly heterogeneous settings)."},

    {"id": "arxiv-1804.05146",
     "title": "A comparison of methods for model selection when estimating individual treatment effects",
     "authors": ["Alejandro Schuler", "Michael Baiocchi", "Robert Tibshirani", "Nigam Shah"],
     "year": 2018, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1804.05146"},
     "tasks": ["causal-effect-estimation", "model-selection"],
     "fam": ["causal-meta-learners", "tree-ensembles", "linear-models"], "par": ["supervised"],
     "proposes": ["A framework relating validation-set metrics for selecting treatment effect models: mu-risk (outcome prediction error, optionally IPTW-weighted), decision value (IPTW and doubly robust estimators), and plug-in tau-risk estimates (matching, IPTW transformed outcome, and the R-learner objective of Nie and Wager)",
                  "Use of the R-learner objective (tau-risk_R) as a model selection metric for treatment effect models fit by arbitrary algorithms"],
     "claims": [
         ("The fundamental problem: data-splitting/cross-validation of prediction risk breaks down for treatment effect models because the true effect is never observed; the quantity of interest is the tau-risk E[l(tau-hat, tau)] (called PEHE by Hill), whose direct validation-set estimator is infeasible.",
          "Introduction",
          "This approach breaks down for treatment eﬀect estimation because the true treatment eﬀect is never observed in any sample."),
         ("mu-risk (validation-set prediction error of the outcome models, applicable when the effect model is built from outcome regressions, e.g. S- and T-learners) is easy to estimate, but citing Rolling and Yang the authors note many simple examples where minimizing outcome MSE badly fails to select the model with the most accurate treatment effect.",
          "Section 2.1",
          "There are many simple examples where minimizing the mean-squared error of predicted outcomes badly fails to select the model with the most accurate treatment eﬀect [24]."),
         ("Value-based selection: the IPTW value estimator (Kapelner et al.; Zhao et al.) depends on the correctness of the propensity model and only uses the individuals whose treatment matches the policy, discarding the rest; the authors note that Athey et al., in the spirit of Dudík et al., overcome this with a doubly robust estimator.",
          "Section 2.2",
          "A problem with this estimator is that it depends on the correctness of the propensity model."),
         ("Plug-in tau-risk estimates: Rolling and Yang's matching-based estimator scales relatively poorly and matches become difficult to find in high-dimensional covariate spaces; an alternative (Gutierrez and Gerardy) uses the IPTW transformed outcome as a plug-in for tau.",
          "Section 2.3",
          "A downside of this approach are that Mahalanobis matching scales relatively poorly and matches become diﬃcult to ﬁnd in high-dimensional covariate spaces."),
         ("tau-risk_R: following Nie and Wager, the validation-set metric is the mean of ((y - m(x)) - (w - p(x)) tau-hat(x))^2, with m(x) an estimate of E[Y|X] (regressing Y on X without W) and p(x) a propensity estimate; Nie and Wager used this objective for fitting, and the authors propose using it to select among models fit by arbitrary means.",
          "Section 2.3",
          "We propose using this same construction to select among models ﬁt by arbitrary means."),
         ("Protocol: the sixteen simulations of Powers et al., each repeated 100 times with 1000 training, 1000 validation and 1000 test samples; all DGPs satisfy ignorability, SUTVA and positivity and vary in nonlinearity and signal-to-noise ratio.",
          "Section 3.1.1",
          "The data-generating process in each simulation all satisfy the usual assumptions made about ignorability, SUTVA, and positivity, but vary in the amount of nonlinearity in the conditional mean functions and signal-to-noise ratio."),
         ("Result as stated in the text: tau-risk_R is the metric that most consistently selects models with low test tau-risk and high value, especially when treatment assignment is randomized but also to a large extent when it is biased; where other approaches win, it is typically by a small margin, and mu-risk and its IPTW version also perform well.",
          "Section 3.2",
          "This is especially true when treatment assignment is randomized, but also to a large extent when the assignment is biased."),
         ("Selection on the IPTW or doubly robust value estimators is generally suboptimal even when the goal is to optimize test-set value, which the authors say is likely because these metrics are 'coarser', turning a regression problem into a classification problem; they nonetheless show low empirical bias for value, so they remain appropriate to gauge the value of the final policy.",
          "Section 4",
          "This is likely because these metrics are in a sense “coarser” than the other metrics we consider, eﬀectively turning a regression problem into a classiﬁcation problem."),
         ("Limitation: the study relies on simulations, which is necessary because test tau-risk and value cannot be computed from real data; the authors say no set of simulations can mimic the full range of real-world DGPs, though theirs span linear and nonlinear outcome functions, noise levels and degrees of assignment bias.",
          "Section 4",
          "The primary limitation of our work is that it relies on simulations."),
     ],
     "notes": "Affiliations: Stanford University. No venue recorded: the arXiv v2 PDF (dated June 15, 2018) states none and the arXiv record has no comment or journal_ref. Conflict of interest: the sixteen simulations are taken from Powers et al. (reference [23]), whose authors include Schuler, Shah and Tibshirani; the R-learner and its objective are by Nie and Wager (not co-authors). Only S-, T- and R-learners with gradient boosted trees (1 to 500 trees, depth 3, shrinkage 0.2, minimum 3 individuals per node) and elastic net (alpha = 0.5, lambda in [e^-5, e^2]) are candidates; causal forests or causal boosting were not included (Section 3.1.2). The authors' recommendation (Section 4) is to fit multiple models with diverse algorithms and select by tau-risk_R on a validation set. Simulations 9-16 use the same data-generating functions as 1-8 but with nonrandom treatment assignment (Table 1 caption). Validation-set nuisances are estimated by cross-validated cross-estimation over the validation set alone (Section 3.1.3). Rolling and Yang prove selection consistency for a more tractable version of their matching algorithm and conjecture it holds for the practical one (Section 2.3). The authors report all tau-risk estimators are biased upwards, which they consider less important for selection since differences between models matter (Section 4). Test-set tau-risk and value per metric are in Tables 1-2 and are not recorded. Cites arxiv-1707.02641 (Dorie et al.) on flexible modeling as the most consistent predictor of success."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
