import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ae_common import BASE_NOTE  # noqa: E402

SPECS = [
    {"id": "arxiv-1511.05644",
     "title": "Adversarial Autoencoders",
     "authors": ["Alireza Makhzani", "Jonathon Shlens", "Navdeep Jaitly", "Ian Goodfellow", "Brendan Frey"],
     "year": 2015, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1511.05644"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["autoencoders"], "par": ["unsupervised"],
     "proposes": ["Adversarial autoencoder (AAE): an autoencoder trained with a reconstruction loss plus an adversarial network on the latent code that matches the aggregated posterior q(z) to an arbitrary prior p(z), so that the decoder becomes a generative model; extensions for supervised, semi-supervised, clustering and dimensionality-reduction settings"],
     "claims": [
         ("Definition: the AAE is an autoencoder regularized by matching the aggregated posterior q(z) (the encoding distribution averaged over the data) to an arbitrary prior p(z), using an adversarial network attached to the latent code; the encoder plays the role of the GAN generator.",
          "Adversarial Autoencoders",
          "The adversarial autoencoder is an autoencoder that is regularized by matching the aggregated posterior, q(z), to an arbitrary prior, p(z)."),
         ("Training: the adversarial network and the autoencoder are trained jointly with SGD in two phases on each mini-batch, a reconstruction phase (encoder and decoder minimize reconstruction error) and a regularization phase (the discriminator is updated, then the encoder is updated to confuse it).",
          "Adversarial Autoencoders",
          "Both, the adversarial network and the autoencoder are trained jointly with SGD in two phases – the reconstruction phase and the regularization phase – executed on each mini-batch."),
         ("Encoder choice: deterministic, Gaussian-posterior and universal-approximator encoders were considered; the authors argue the stochastic ones could smooth q(z), but after an extensive hyperparameter search they obtained similar test likelihood with each, and report only the deterministic encoder in the rest of the paper.",
          "Adversarial Autoencoders",
          "Nevertheless, after extensive hyper-parameter search, we obtained similar test-likelihood with each type of q(z|x)."),
         ("Relation to the VAE regularizer: the VAE bound is rewritten as reconstruction minus the entropy of q(z|x) plus the cross-entropy between the aggregated posterior and the prior; the authors argue the KL/cross-entropy term encourages q(z) to pick the modes of p(z), and the AAE replaces the two regularization terms with an adversarial procedure that matches the whole distribution of p(z).",
          "Relationship to Variational Autoencoders",
          "In adversarial autoencoders, we replace the second two terms with an adversarial training procedure that encourages q(z) to match to the whole distribution of p(z)."),
         ("Qualitative comparison (2-D codes of held-out MNIST, Figure 2, same architecture): with a 2-D Gaussian prior the VAE roughly matches the prior shape but leaves local regions of the code space with no data points, which the authors take to indicate that the VAE may not have captured the data manifold as well as the AAE. Evidence is visual only.",
          "Relationship to Variational Autoencoders",
          "However, no data points map to several local regions of the coding space indicating that the VAE may not have captured the data manifold as well as the adversarial autoencoder."),
         ("Practical difference: backpropagating through the VAE's KL term by Monte Carlo sampling requires the exact functional form of the prior, whereas the AAE only needs samples from the prior (demonstrated with a swiss-roll prior).",
          "Relationship to Variational Autoencoders",
          "However, in AAEs, we only need to be able to sample from the prior distribution in order to induce q(z) to match p(z)."),
         ("Likelihood evaluation protocol (real-valued MNIST and Toronto Face Dataset): since p(x) cannot be computed directly, a Gaussian Parzen window is fitted to samples generated from the model and the test-data likelihood is computed under it, with the Parzen bandwidth chosen by cross-validation; 10K- and 10M-sample estimates are reported.",
          "Likelihood Analysis of Adversarial Autoencoders",
          "We ﬁt a Gaussian Parzen window (kernel density estimator) to 10, 000 samples generated from the model and compute the likelihood of the test data under this distribution."),
         ("Stated caveat on that evaluation: although the AAE achieved superior log-likelihoods in all their comparisons, the authors warn that the currently available likelihood metrics for generative models such as GANs are deeply flawed, citing Theis et al. for problems including the 10K and 10M sample Parzen window estimates.",
          "Likelihood Analysis of Adversarial Autoencoders",
          "However, the reader must be aware that the metrics currently available for evaluating the likelihood of generative models such as GANs are deeply ﬂawed."),
     ],
     "notes": "Affiliations: University of Toronto, Google Brain, OpenAI. Goodfellow (an author) is also the first author of the GAN paper whose adversarial procedure is used and which is a baseline in Table 1. No venue statement was found in the PDF (arXiv v2, May 2016) and the arXiv record has no comment, so no venue is recorded (the WAE paper, arxiv-1711.01558, cites it as 'In ICLR, 2016'; not used as a source). The paper also reports semi-supervised classification (MNIST, SVHN), unsupervised clustering and dimensionality-reduction results (Tables 2-3, Figure 11); results tables not recorded."},

    {"id": "arxiv-1711.01558",
     "title": "Wasserstein Auto-Encoders",
     "authors": ["Ilya Tolstikhin", "Olivier Bousquet", "Sylvain Gelly", "Bernhard Schölkopf"],
     "year": 2017, "venue": "ICLR 2018", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1711.01558", "code": "https://github.com/tolstikhin/wae"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["autoencoders"], "par": ["unsupervised"],
     "proposes": ["Wasserstein Auto-Encoder (WAE): a family of regularized autoencoders minimizing a relaxed optimal-transport cost W_c(P_X, P_G) as reconstruction cost c plus lambda times a divergence D_Z between the encoded distribution Q_Z and the prior P_Z, with two instances: WAE-GAN (adversarial D_Z) and WAE-MMD (MMD D_Z, adversary-free)"],
     "claims": [
         ("Main idea: WAE minimizes a penalized form of the Wasserstein distance between the model and data distributions, which yields a regularizer different from the VAE's; this regularizer encourages the encoded training distribution to match the prior.",
          "Abstract",
          "This regularizer encourages the encoded training distribution to match the prior."),
         ("Objective: for a deterministic decoder, the optimal-transport cost can be written as an optimization over probabilistic encoders whose aggregate Q_Z equals the prior (Theorem 1, from earlier work [4]); relaxing this constraint with a penalty lambda * D_Z(Q_Z, P_Z) gives the WAE objective, which, unlike the VAE, allows deterministic encoders.",
          "Proposed method",
          "Note that as opposed to VAEs, the WAE formulation allows for non-random encoders deterministically mapping inputs to their latent codes."),
         ("Difference from the VAE regularizer: citing [13], the VAE regularizer equals KL(Q_Z, P_Z) plus the mutual information between X and Z, and WAE simply drops the mutual-information term.",
          "Related work",
          "WAEs simply drop the mutual information term IQ(X, Z) in the VAE regularizer."),
         ("Relation to AAE: with squared cost, WAE-GAN is equivalent to adversarial autoencoders, so the theory of [4] suggests AAEs minimize the 2-Wasserstein distance between data and model; WAE generalizes AAE to any input-space cost and any latent discrepancy (e.g. MMD).",
          "Related work",
          "This provides the ﬁrst theoretical justiﬁcation for AAEs known to the authors."),
         ("Stability: in some cases WAE-GAN seems to give better matching and better samples than WAE-MMD, but because of adversarial training it is less stable than WAE-MMD, whose training is very stable much like the VAE.",
          "Experiments",
          "However, due to adversarial training WAE-GAN is less stable than WAE-MMD, which has a very stable training much like VAE."),
         ("Sample quality depends on how accurately Q_Z matches P_Z, because the decoder is trained only on encoded data points; the authors noticed that even slight differences between Q_Z and P_Z may affect sample quality.",
          "Experiments",
          "In our experiments we noticed that even slight diﬀerences between QZ and PZ may aﬀect the quality of samples."),
         ("Experimental setup (MNIST and CelebA): deterministic encoder-decoder pairs, isotropic Gaussian prior, squared cost, DCGAN-like architectures; the regularization weight was set by trying various values, and lambda = 10 seemed to work well across datasets.",
          "Experiments",
          "We tried various values of λ and noticed that λ = 10 seems to work good across all datasets we considered."),
         ("Larger-scale comparison (bigVAE/bigWAE in Table 1): over 3,000 WAE-GAN, WAE-MMD and VAE models with randomly sampled hyperparameters (latent dimension, batch size, learning rates, lambda or the VAE decoder variance, DCGAN-style or ResNet50-v2 architectures), with each algorithm given exactly the same computational budget and three random seeds per configuration.",
          "Supplementary D",
          "In total we trained over 3 thousand WAE-GAN, WAE-MMD, and VAE models with various hyperparameters while making sure each one of the three algorithms gets exactly the same computational budget."),
     ],
     "notes": "Affiliations: Max Planck Institute for Intelligent Systems and Google Brain. Venue from the arXiv comment ('Published at ICLR 2018'); the v4 PDF itself has no venue statement. Disclosure: the theory (Theorem 1) is from the authors' earlier work [4], restated here. Evaluation-protocol notes: in the larger study (Supplementary D) the checkpoint with the lowest FID was selected for each configuration; the text does not say whether FID samples are compared against training or test images (not found). The main text says lambda = 10 seemed to work across datasets, but Supplementary C.2 lists lambda = 100 (WAE-MMD) and lambda = 1 (WAE-GAN) for CelebA. The CelebA VAE uses a Gaussian decoder with fixed sigma^2 = 0.3 and no batch normalization. Results table (FID, sharpness) not recorded."},

    {"id": "arxiv-1810.09136",
     "title": "Do Deep Generative Models Know What They Don't Know?",
     "authors": ["Eric Nalisnick", "Akihiro Matsukawa", "Yee Whye Teh", "Dilan Gorur", "Balaji Lakshminarayanan"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1810.09136"},
     "tasks": ["anomaly-detection", "generative-modeling"],
     "fam": ["variational-autoencoders", "deep-learning"], "par": ["unsupervised"],
     "proposes": ["An empirical study showing that likelihoods of deep generative models (Glow/RealNVP flows, VAEs, PixelCNN) can be higher for out-of-distribution image datasets than for the training distribution, and a second-order analysis for constant-volume flows that explains the gap by the data's mean/variance and the model curvature"],
     "claims": [
         ("Main finding: densities learned by flow-based models, VAEs and PixelCNNs trained on CIFAR-10 assign higher likelihood to SVHN than to CIFAR-10; the authors challenge the assumption that density models can be used to detect out-of-distribution inputs.",
          "Abstract",
          "We ﬁnd that the density learned by ﬂow-based models, VAEs, and PixelCNNs cannot distinguish images of common objects such as dogs, trucks, and horses (i.e. CIFAR-10) from those of house numbers (i.e. SVHN), assigning a higher likelihood to the latter when the model is trained on the former."),
         ("Scope of the phenomenon for Glow: higher likelihood for MNIST under a Glow trained on FashionMNIST, for SVHN under CelebA, and for SVHN, CIFAR-10 and CIFAR-100 under ImageNet (drastic for SVHN, modest for the CIFARs); the same was observed for RealNVP. The effect is not symmetric: CIFAR-10 does not get higher likelihood under a Glow trained on SVHN.",
          "Motivating observations",
          "This phenomenon is not symmetric."),
         ("VAE and PixelCNN were tested only on FashionMNIST vs MNIST and CIFAR-10 vs SVHN (VAE: the convolutional categorical variant of Rosca et al. 2018); in all four histograms the out-of-distribution log p(x) is shifted to higher values. GANs were excluded because evaluating their likelihood is an open problem. Evidence is histograms only, and how log p(x) was estimated for the VAE was not found in the text (searched ELBO, lower bound, importance).",
          "Motivating observations",
          "The red bars are shifted to the right in all four plots, signifying the behavior exists in spite of the differences between model classes."),
         ("The deeper analysis is restricted to flows because they give exact marginal likelihoods (unlike VAEs); decomposing NVP-Glow's likelihood first suggested the volume (log-determinant) term as the cause, but Glow with constant-volume (translation-only) transformations still gave SVHN higher likelihood.",
          "Digging deeper into the flow-based model",
          "At ﬁrst this suggested the volume element was the primary cause of SVHN’s high likelihood, but further experiments with constant-volume ﬂows show the problem exists with them as well."),
         ("Ensembles did not remove the effect: hypothesizing that averaging over parameters may mitigate it, the authors trained five independently initialized Glow models and averaged their likelihoods, and obtained nearly identical results.",
          "Digging deeper into the flow-based model",
          "We see nearly identical results: SVHN is still assigned a higher likelihood than the CIFAR-10 training data."),
         ("Explanation offered (conclusion of the second-order analysis of constant-volume Glow): SVHN 'sits inside' CIFAR-10, with roughly the same mean and smaller variance, giving it higher likelihood; the authors say this also holds for the ImageNet results, that the likelihood differences agree with the variance differences, and that shrinking a dataset's variance (graying the images) artificially increases its likelihood.",
          "Second order analysis",
          "Our conclusion is that SVHN simply \"sits inside of\" CIFAR-10—roughly same mean, smaller variance—resulting in its higher likelihood."),
         ("Conclusion and caveats: comparing likelihoods of deep generative models alone cannot identify the training set or inputs like it, so the authors urge caution; they state they cannot conclude it is a pathology of deep generative models, that the tested models seem to capture low-level statistics rather than high-level semantics, that alternative metrics (Choi & Jang) or modified training (Hendrycks et al.) can detect OOD inputs, and that the problem may be a fundamental limitation of high-dimensional likelihoods.",
          "Discussion",
          "We have shown that comparing the likelihoods of deep generative models alone cannot identify the training set or inputs like it."),
         ("Related evidence on tuning (citing Škvára et al. 2018, not this paper's experiment): VAEs and GANs outperformed k-nearest neighbors for anomaly detection only when known outliers could be used for hyperparameter selection.",
          "Related work",
          "Škvára et al. (2018) experimentally compare VAEs and GANs against k-nearest neighbors (kNNs), showing that VAEs and GANs outperform kNNs only when known outliers can be used for hyperparameter selection."),
     ],
     "notes": "Affiliation: DeepMind (first author's work done during an internship). Venue from the PDF header ('Published as a conference paper at ICLR 2019') and the arXiv comment. Author 'Dilan Gorur' spelled as in the PDF (the arXiv record could not be checked offline). Disclosure: Lakshminarayanan (an author) is a co-author of Rosca et al. (2018), whose VAE configurations are used, and of the deep-ensembles paper (Lakshminarayanan et al. 2017) that motivated the ensemble test. Evaluation protocol: OOD behaviour is shown by average bits-per-dimension on test splits and log-likelihood histograms; no detection threshold or AUROC was found in the text (searched threshold, AUC, ROC). All models were trained with input noise. Numbers in the Figure 1 sub-tables are not recorded. The Glow is smaller than in Kingma & Dhariwal (2018). Other statements not recorded as claims: the Figure 4d caption says the gap persisted over training and could not be prevented by early stopping; constant inputs received the highest likelihood (as prior work had noted); the second-order expansion is described by the authors as a crude approximation that assumes equal means."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, created_at="2026-10-04", created_by="claude-opus-5-5 via Claude Code (subagent)")
