import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1906.02243",
     "title": "Energy and Policy Considerations for Deep Learning in NLP",
     "authors": ["Emma Strubell", "Ananya Ganesh", "Andrew McCallum"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1906.02243"},
     "tasks": ["efficiency-evaluation"], "fam": ["deep-learning"], "par": [],
     "proposes": ["energy / CO2e / cloud-cost estimates for training popular NLP models (measured power draw x training time reported in the original papers x PUE, converted with the U.S. EPA average)",
                  "recommendations: report training time and hyperparameter sensitivity, equitable academic compute access, prioritize efficient hardware and algorithms"],
     "claims": [
         ("Contribution: the paper quantifies the approximate financial and environmental costs of training a variety of recently successful neural NLP models, and proposes recommendations to reduce costs and improve equity.",
          "Abstract",
          "In this paper we bring this issue to the attention of NLP researchers by quantifying the approximate ﬁnancial and environmental costs of training a variety of recently successful neural network models for NLP."),
         ("Measurement: the off-the-shelf models are trained with the default settings provided (each for a maximum of 1 day, on a single NVIDIA Titan X GPU except ELMo on 3 GTX 1080 Ti GPUs) while GPU power is sampled via nvidia-smi (averaged over samples) and CPU power via Intel's RAPL interface; the full training runs are not performed.",
          "Methods",
          "We train the models described in §2.1 using the default settings provided, and sample GPU and CPU power consumption during training."),
         ("Extrapolation: the total training time to completion is not measured but estimated from the training times and hardware reported in the original papers; energy is then the combined GPU, CPU and DRAM power draw multiplied by that time.",
          "Methods",
          "We estimate the total time expected for models to train to completion using training times and hardware reported in the original papers."),
         ("Assumption: data-center overhead (mainly cooling) is accounted for with a fixed Power Usage Effectiveness coefficient equal to the 2018 global data-center average.",
          "Methods",
          "We use a PUE coefﬁcient of 1.58, the 2018 global average for data centers (Ascierto, 2018)."),
         ("Assumption: energy is converted to CO2e using the U.S. EPA average CO2 per kWh; the authors justify this by the U.S. energy mix being comparable to that of Amazon Web Services.",
          "Methods",
          "The U.S. breakdown of energy is comparable to that of the most popular cloud compute service, Amazon Web Services, so we believe this conversion to provide a reasonable estimate of CO2 emissions per kilowatt hour of compute energy used."),
         ("Limitation: for TPU-trained models only cloud compute cost is estimated; power and carbon footprint are omitted because TPU power draw is not publicly available.",
          "Experimental results (Table 3 caption)",
          "Power and carbon footprint are omitted for TPUs due to lack of public information on power draw for this hardware."),
         ("Recommendations: report time to retrain and sensitivity to hyperparameters, give academic researchers equitable access to compute, and prioritize efficient models and hardware.",
          "Introduction",
          "(1) Time to retrain and sensitivity to hyperparameters should be reported for NLP machine learning models; (2) academic researchers need equitable access to computational resources; and (3) researchers should prioritize developing efﬁcient models and hardware."),
     ],
     "notes": "Estimate sources: training hours and hardware for the cost table are those reported by others, not measured - e.g. BERT GPU time is NVIDIA's reported 79.2 hours on 64 V100s, GPT-2's 1 week on 32 TPUv3 chips is 'Via the authors on Reddit' (footnote 6), and the NAS hours are converted by the authors from So et al.'s reported steps and TPU base-model time. Cloud compute cost ranges use pre-emptible (lower bound) and on-demand (upper bound) U.S. GPU/TPU prices (footnote 7); electricity cost uses the average U.S. price per kWh (footnote 9). Case study (Cost of development): the authors use the logs of all training for their own earlier LISA model (Strubell et al., 2018) - 4789 jobs from 123 small grid searches over 172 days on Titan X / M40 GPUs, with cloud cost approximated using P100 pricing, and the cost of tuning for a new dataset assumed ('we estimate here') to require 24 jobs - to estimate the cost of R&D and tuning, i.e. the case-study model is the authors' own. In the Conclusions they also call for a standard hardware-independent measure of training time (e.g. gigaflops to convergence) and for random/Bayesian hyperparameter search APIs instead of grid search. Cited for its cost methodology by arxiv-2007.05558 (reference [53]) and by arxiv-1907.10597 (reference [40])."},

    {"id": "arxiv-1907.10597",
     "title": "Green AI",
     "authors": ["Roy Schwartz", "Jesse Dodge", "Noah A. Smith", "Oren Etzioni"],
     "year": 2019, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1907.10597"},
     "tasks": ["efficiency-evaluation"], "fam": ["deep-learning"], "par": [],
     "proposes": ["Green AI: efficiency as an evaluation criterion alongside accuracy",
                  "Cost(R) proportional to E x D x H (per-example cost x dataset size x number of hyperparameter experiments)",
                  "report total floating point operations (FPO) required to generate a result"],
     "claims": [
         ("Position: the paper advocates making efficiency an evaluation criterion for research alongside accuracy, and reporting the financial cost ('price tag') of developing, training and running models.",
          "Abstract",
          "This position paper advocates a practical solution by making efﬁciency an evaluation criterion for research alongside accuracy and related measures."),
         ("Cost model: the cost of producing a result is described as growing linearly with the cost of processing one example, the training-set size and the number of hyperparameter experiments.",
          "Red AI",
          "The total cost of producing a (R)esult in machine learning increases linearly with each of these quantities."),
         ("Caveat: the authors state that this equation is a simplification and that it ignores other factors such as the number of training epochs.",
          "Red AI",
          "Equation 1 is a simpliﬁcation (e.g., different hyperparameter assignments can lead to different costs for processing a single example)."),
         ("Survey method: for a sample of 60 papers from ACL, NeurIPS and CVPR, the authors classified whether the claimed main contribution is accuracy, efficiency, both, or other.",
          "Red AI",
          "For each paper we noted whether the authors claim their main contribution to be (a) an improvement to accuracy or some related measure, (b) an improvement to efﬁciency, (c) both, or (d) other."),
         ("Drawbacks of alternative measures: carbon emission, though described as appealing, is described as impractical to measure exactly and not comparable across locations or times because it depends on the local electricity infrastructure (electricity use, run time and parameter count are also discussed and judged hardware-dependent or not reflecting work done).",
          "Measures of Efficiency",
          "As a result, it is not comparable between researchers in different locations or even the same location at different times."),
         ("Recommendation: report the total number of floating point operations (FPO) required to generate a result; the authors argue FPO is hardware-agnostic, tied to the amount of energy consumed, and (citing Canziani et al.) strongly correlated with running time.",
          "Measures of Efficiency",
          "As a concrete measure, we suggest reporting the total number of ﬂoating point operations (FPO) required to generate a result"),
         ("Limitations of FPO stated by the authors: it ignores memory consumption, and the amount of work largely depends on the model implementation.",
          "Measures of Efficiency (Discussion)",
          "First, it targets the electricity consumption of a model, while ignoring other potential limiting factors for researchers such as the memory consumption by the model, which can often lead to additional energy and monetary costs [24]."),
     ],
     "notes": "Affiliation: the research was done at the Allen Institute for AI (title page footnote); when discussing large models the paper cites Grover, released by 'AI2, our home organization', with an estimated training cost of $25,000 (an estimate not derived in this paper); some XLNet cost estimates of $250,000 are cited from a tweet (footnote 7). The compute-growth figure (Figure 1) is reproduced from Amodei & Hernandez's 'AI and Compute' (reference [2]) and the carbon estimates are attributed to Strubell et al. (reference [40], card arxiv-1906.02243); these are prior work, not this paper's measurements. The FPO numbers in Figure 4 are per-inference FPO taken from the flops-counter.pytorch repository (footnotes 18-19), not measured by the authors. The paper also recommends reporting budget/accuracy curves (expected validation performance as a function of budget, from the authors' earlier work [9]) and releasing pretrained models."},

    {"id": "arxiv-2202.05924",
     "title": "Compute Trends Across Three Eras of Machine Learning",
     "authors": ["Jaime Sevilla", "Lennart Heim", "Anson Ho", "Tamay Besiroglu", "Marius Hobbhahn", "Pablo Villalobos"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2202.05924"},
     "tasks": ["efficiency-evaluation"], "fam": ["deep-learning"], "par": [],
     "proposes": ["dataset of training compute for milestone ML systems",
                  "three-era framing (Pre Deep Learning, Deep Learning, Large-Scale) with log-linear doubling-time estimates"],
     "claims": [
         ("Main claim: training compute doubled roughly every 20 months before 2010 (in line with Moore's law) and accelerated to roughly every 6 months since the advent of Deep Learning in the early 2010s; a separate large-scale trend emerged in late 2015.",
          "Abstract",
          "Since the advent of Deep Learning in the early 2010s, the scaling of training compute has accelerated, doubling approximately every 6 months."),
         ("Data: the analysis is based on a curated dataset of 123 milestone ML systems (selected by necessary and notability criteria, with a subjective selection for models from 2020 onward) annotated with training compute.",
          "Introduction",
          "We curate a dataset of 123 milestone Machine Learning systems, annotated with the compute it took to train them."),
         ("Estimation method: when a paper does not report training compute, it is estimated with the AI and Compute appendix techniques (from forward-pass compute or from GPU time), with the reasoning annotated per dataset cell.",
          "Appendix A (Methods)",
          "When the training compute is not shared in the paper, we follow the techniques in AI and Compute’s appendix to estimate the training compute of our models (Amodei & Hernandez, 2018)."),
         ("Scope: only the final training run is counted; hyperparameter-search runs are not, as they are often unreported.",
          "Appendix A (Methods)",
          "Our dataset only annotates the compute used for the ﬁnal training run."),
         ("Uncertainty: the authors expect most compute estimates to be accurate within about a factor of two (based on comparing estimation methods) and add noise when bootstrapping to account for it.",
          "Appendix H (Limitations)",
          "We expect most of the compute estimates to be accurate within a factor of about two based on some comparisons we did between different estimation methods (Sevilla et al., 2022)."),
         ("Caveat: assignment of systems to the large-scale trend was an intuitive decision, justified post hoc with a Z-value threshold, and the authors state there is room for alternative interpretations.",
          "Trends in the Large-Scale era",
          "Note that we made an intuitive decision in deciding which systems belong to this new large-scale trend."),
         ("Disagreement with prior work: the results contrast with Amodei & Hernandez (3.4-month doubling, 2012-2018) and Lyzhov (>2-year doubling, 2018-2020); the authors attribute this to small samples and single-trend assumptions in those analyses.",
          "Trends in the Large-Scale era",
          "Our results contrast with Amodei & Hernandez (2018), who ﬁnd a much faster doubling period of 3.4 months between 2012 and 2018, and with Lyzhov (2021), who ﬁnds a much longer doubling period of >2 years between 2018 and 2020."),
     ],
     "notes": "Training compute for systems whose papers do not report it is estimated by the authors (see c3, c5). The Abstract states roughly 20-month doubling before 2010, while the Conclusion states an 18-month doubling time between 1952 and 2010; estimates differ across fits and tables. Doubling times come from log-linear fits with bootstrap (B = 1000) confidence intervals; each estimate is randomly multiplied by a log-uniform factor between 1/2 and 2 during bootstrapping (Appendix A). Low-compute outliers (Z < -2 relative to models published within 1.5 years per the Appendix A text; the Table 5 caption says within 2 years) are excluded (5 of 123 models); large-scale models are those with Z >= 0.76 after 2016, with thresholds chosen after visual inspection. Appendix H also lists non-sampling errors (incorrect calculations) and selection biases (academic publications, English, subjectively 'notable' models, which the authors say makes doubling-time estimates higher). The Conclusion states the authors are not confident in the large-scale vs regular-scale distinction. Funding: Jaime Sevilla is funded by the Open Philanthropy Project (Acknowledgments); affiliations are universities and the Centre for the Governance of AI."},

    {"id": "arxiv-2007.05558",
     "title": "The Computational Limits of Deep Learning",
     "authors": ["Neil C. Thompson", "Kristjan Greenewald", "Keeheon Lee", "Gabriel F. Manso"],
     "year": 2020, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2007.05558"},
     "tasks": ["efficiency-evaluation", "scaling-laws", "image-classification"], "fam": ["deep-learning"], "par": [],
     "proposes": ["meta-analysis of performance vs training computation across deep-learning benchmarks (log(1/error) regressed on log(computation))",
                  "two computation measures: network operations and hardware burden"],
     "claims": [
         ("Main claim: progress across a wide variety of deep-learning applications is strongly reliant on increases in computing power, and the authors state that extrapolating this reliance forward reveals that progress along current lines is rapidly becoming economically, technically and environmentally unsustainable.",
          "Abstract",
          "This article catalogs the extent of this dependency, showing that progress across a wide variety of applications is strongly reliant on increases in computing power."),
         ("Data: performance and computation data were extracted by manual review of deep-learning papers (from arXiv and benchmark sources) on established benchmarks; most papers do not report computational requirements, so analyses are limited to the benchmarks with enough data.",
          "Present",
          "In total, we gathered 1,526 deep learning papers, for which we did a detailed manual review for their performance and computation burden data."),
         ("Computation measure: where network operations (FLOPs per pass x passes) cannot be computed, the paper uses hardware burden (processors x computation rate x time), which the authors say also estimates the computation needed but is less precise because it depends on hardware implementation efficiency.",
          "Present",
          "This also estimates the computation needed, but is less precise since it depends on hardware implementation efficiency."),
         ("Data sources: hardware performance values are mostly taken from hardware designers' official platforms (e.g. NVIDIA, Google) or public databases such as Wikipedia; models with missing details such as training time cannot be estimated.",
          "Supplemental Materials (Data collection)",
          "Hardware performance data are mostly gathered from external sources such as ofﬁcial hardware designers plataforms (e.g. NVIDIA, Google) or publicly-available databases (e.g. Wikipedia)."),
         ("Cost conversion: projected economic and environmental costs follow Strubell et al.'s methodology for V100 GPU training, with 2022 cloud pricing and updated carbon estimates (geometric mean) from Dodge et al.",
          "Future (footnote)",
          "Economic and environmental costs are measured using the methodology provided by [53] for V100 GPU training."),
         ("Disagreement with within-model scaling studies: the authors hypothesize that inconsistencies with other scaling studies arise from measurement approach - 'scaling up' measures improvements to the state of the art while 'scaling down' measures performance deterioration and can yield artificially rosy estimates; they suggest the faster scaling reported for ResNet and NASNet seems to reflect this.",
          "Comparison to other scaling studies",
          "Put simply, the ‘scaling up’ approach measures improvements to the state of the art, whereas the ‘scaling down’ approach measures performance deterioration."),
         ("Limitation: only training costs are analysed (deployment costs depend on usage data that is not available), so the analysis is a lower bound on total computation.",
          "Lessening the Computational Burden",
          "Since total costs must necessarily be higher than just training costs, our analysis provides a lower bound on the total computation needed for any given level of performance."),
     ],
     "notes": "The Introduction and Table 1 total state 1,527 papers while the Present section states 1,526 papers. Network operations count multiply-adds as 2 FLOPs (footnote 10) and include pre-training, training and fine-tuning; neural architecture search cost is included in training cost (footnote 9). For MS COCO and ImageNet models with only network operations, hardware burden is imputed from a regression fitted on ImageNet models (Supplemental Materials, Model Analysis); the imputed values are thus regression-based estimates (for MS COCO the ImageNet regression is reused, footnote 16). The supplement notes that training time is sometimes not reported precisely, that authors generally do not report computing precision (leaving 'some residual uncertainty') and sometimes conflate multiply-adds and FLOPs. Analysis is restricted to benchmarks with exact right/wrong answers (generative language/audio models excluded). Projected CO2 and dollar costs (Table 3) are extrapolations, not measurements. The authors present polynomial and exponential extrapolations as having roughly equivalent fits and state they do not anticipate the extrapolated targets will be hit. Affiliations include MIT and the MIT-IBM Watson AI Lab; funding includes the U.S. Air Force Research Laboratory (Acknowledgments). Uses Strubell et al. (card arxiv-1906.02243) for the cost methodology."},

    {"id": "arxiv-2110.12894",
     "title": "The Efficiency Misnomer",
     "authors": ["Mostafa Dehghani", "Anurag Arnab", "Lucas Beyer", "Ashish Vaswani", "Yi Tay"],
     "year": 2021, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2110.12894"},
     "tasks": ["efficiency-evaluation", "image-classification"], "fam": ["deep-learning", "mixture-of-experts"], "par": [],
     "proposes": ["'efficiency misnomer': no single cost indicator (parameters, FLOPs, speed) is sufficient",
                  "recommendation to report all available cost indicators and narrow efficiency claims to the evaluated setup"],
     "claims": [
         ("Main claim: cost indicators (parameter count, FLOPs, throughput/speed) can contradict each other, and incomplete reporting of them can lead to partial conclusions about model efficiency.",
          "Abstract",
          "We demonstrate how incomplete reporting of cost indicators can lead to partial conclusions and a blurred or incomplete picture of the practical considerations of different models."),
         ("Measurement caveat: reported FLOPs are usually theoretical values that ignore practical factors such as which parts of the model can be parallelized.",
          "A Primer on Cost Indicators",
          "Note that theoretical FLOPs ignores practical factors, like which parts of the model can be parallelized."),
         ("Experimental setup: in controlled ViT experiments (Scenic, 64 TPU-V3) scaling depth vs width, all other hyperparameters were kept fixed at the default values from the referenced papers; which architecture looks better depends on the cost indicator.",
          "Potential disagreement between cost indicators",
          "Note that when changing depth or width of the model (see Table 2 in Appendix A for the exact conﬁgurations) all other hyper-parameters are kept ﬁxed based on the default values given by the referenced papers."),
         ("Measurement source for the ImageNet model comparison: accuracies and cost values are taken from Steiner et al. and Liu et al., with cost indicators from PyTorch implementations and throughput measured on a V100 GPU with timm.",
          "Discussion (Figure 5 caption)",
          "Cost indicators are based on PyTorch implementation of the included models and the throughput is measured on a V100 GPU, using timm (Wightman, 2019)."),
         ("Training time as a metric: the authors warn that training time is prone to Goodhart's law and depends on the whole training recipe; they state that a claim that one method performs almost as well as another with dramatically reduced training cost is not valid, because a method not optimized for training cost may be re-tuned with that in mind (e.g. learning rate, weight decay).",
          "Training or inference cost?",
          "Whilst “training time” can be a great cost indicator, it is also prone to Goodhart’s Law: When used as the main metric, it can and will be gamed and lose its meaning."),
         ("Sparse models / MoE: the authors argue that parameter-matched comparisons do not make sense for sparse models and unnecessarily downplay their strengths.",
          "The issues with parameter matched comparisons",
          "Hence, parameter matched comparisons do not make sense for sparse models and parameter-matching sparse models can be seen as an unfair method of unnecessarily downplaying the strengths of sparse models."),
         ("Recommendation: always report and plot curves with all available cost indicators, avoid highlighting a single one, and narrow efficiency claims to the exact evaluated setup.",
          "Suggestions and Conclusion",
          "Since each indicator stands for something different and comes with its own pros and cons, we suggest always reporting and plotting curves using all available cost indicators, and refraining from highlighting results using just a single one."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2022. Affiliation: all authors list Google Research; the compared models include the Universal Transformer (Dehghani et al., 2018) and the Transformer (Vaswani et al., 2017), co-authored by authors of this paper, and the experiments use Google's Mesh TensorFlow / Scenic on TPU-V3. The authors state parameter count is the most problematic indicator when used alone, and that compute-matched comparisons can also handicap baselines (Perceiver IO vs a shrunk BERT example). The paper cites NVIDIA and Amazon estimates that 80-90% of ML workload is inference (prior work, not measured here)."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model size, data, compute and performance (scaling laws, compute-optimal training, cost measurement); carded by a subagent. Results tables not recorded; claims only.")
