import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ai_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1601.00670",
     "title": "Variational Inference: A Review for Statisticians",
     "authors": ["David M. Blei", "Alp Kucukelbir", "Jon D. McAuliffe"],
     "year": 2016, "venue": "Journal of the American Statistical Association", "version": "arXiv v9",
     "links": {"arxiv": "https://arxiv.org/abs/1601.00670"},
     "tasks": ["posterior-inference"],
     "fam": ["variational-inference", "mcmc"],
     "proposes": ["Review of variational inference (VI) as optimization of KL(q||p) via the ELBO: the mean-field family, coordinate ascent VI (CAVI), VI for conditionally conjugate exponential-family models, and stochastic VI (SVI) for massive data, with a worked Bayesian mixture of Gaussians, a survey of theory and a list of open problems"],
     "claims": [
         ("The KL(q||p) objective cannot be computed because it depends on the evidence log p(x); VI instead maximizes the ELBO = E[log p(z,x)] - E[log q(z)], which equals the negative KL plus log p(x), so maximizing the ELBO is equivalent to minimizing the KL divergence.",
          "Section 2.2",
          "Because we cannot compute the KL, we optimize an alternative objective that is equivalent to the KL up to an added constant,"),
         ("Using the ELBO as a model-selection criterion (premise: the bound approximates the marginal likelihood) sometimes works in practice, but the authors state that selecting based on a bound is not justified in theory.",
          "Section 2.2",
          "Though this sometimes works in practice, selecting based on a bound is not justiﬁed in theory."),
         ("When to use which: MCMC tends to be more computationally intensive but provides guarantees of (asymptotically) exact samples, while VI has no such guarantee and only finds a density close to the target but tends to be faster. Hence VI suits large data sets and quickly exploring many models; MCMC suits smaller data sets where a heavier computational cost is acceptable for more precise samples.",
          "Introduction",
          "Thus, variational inference is suited to large data sets and scenarios where we want to quickly explore many models; MCMC is suited to smaller data sets and scenarios where we happily pay a heavier computational cost for more precise samples."),
         ("Data set size is not the only consideration; posterior geometry matters too. For mixture models (multiple modes from label permutations), Gibbs sampling quickly focuses on one of the modes if the model permits it; where Gibbs is not an option, VI may perform better than a more general MCMC technique such as HMC, even for small datasets (citing Kucukelbir et al., 2015).",
          "Introduction",
          "For mixture models where Gibbs sampling is not an option, variational inference may perform better than a more general MCMC technique (e.g., Hamiltonian Monte Carlo), even for small datasets (Kucukelbir et al., 2015)."),
         ("The relative accuracy of VI and MCMC is stated to be still unknown; what is known is that VI generally underestimates the posterior variance as a consequence of its objective. Depending on the task this may be acceptable; the authors cite empirical work in which VI does not necessarily suffer in accuracy (e.g. posterior predictive densities) and other work (Giordano et al., 2015) focusing on where it falls short, especially around the posterior variance.",
          "Introduction",
          "We do know that variational inference generally underestimates the variance of the posterior density; this is a consequence of its objective function."),
         ("Mean-field family: it can capture any marginal density but not correlation between latent variables. On a correlated 2D Gaussian, the optimal mean-field approximation has the same mean but decoupled covariance and under-represents the marginal variances, a common effect explained by KL(q||p) penalizing mass of q where p has little mass but penalizing the reverse less.",
          "Section 2.3",
          "Further, the marginal variances of the approximation under-represent those of the target density."),
         ("The ELBO is (generally) non-convex and CAVI only guarantees convergence to a local optimum that can be sensitive to initialization; on the mixture example, random initializations reach different ELBO values, indicating many local optima. For assessing convergence the authors suggest monitoring the average log predictive of a small held-out set as a proxy for the full-data ELBO (which, unlike the ELBO, is not guaranteed to increase monotonically under CAVI).",
          "Section 2.5",
          "Each initialization reaches a different value, indicating the presence of many local optima in the ELBO."),
         ("SVI (for conditionally conjugate models): subsample a data point, compute its optimal local parameters, and follow a noisy natural gradient of the global parameters that is unbiased; step sizes must satisfy the Robbins-Monro conditions (e.g. t^-kappa with kappa in (0.5, 1]); stochastic optimization of the ELBO reaches a local optimum. The authors emphasize SVI needs no derivation beyond CAVI.",
          "Section 4.3",
          "We emphasize that SVI requires no new derivation beyond what is needed for CAVI."),
         ("Open problems: the interface between VI and MCMC remains relatively unexplored, and the authors state that a principled analysis of when to use (and combine) VI and MCMC would have both theoretical and practical impact.",
          "Section 5.4",
          "A principled analysis of when to use (and combine) variational inference and MCMC would have both theoretical and practical impact in the ﬁeld."),
     ],
     "notes": "Venue from the arXiv journal_ref (JASA); the v9 PDF itself (dated May 11, 2018) does not state it. Section numbers are from numbered headings in the PDF text (2.2 ELBO, 2.3 mean-field family, 2.5 Practicalities, 4.3 SVI by cross-reference, 5.2 Theory, 5.4 Open problems). The review focuses on KL(q||p)-based VI (footnote 1: expectation propagation, belief propagation, Laplace are mentioned as other 'variational' methods). Theory (Section 5.2) states results are mostly of the type 'VI posterior means as point estimates have the usual frequentist asymptotics', each for a single model and variational family, and cites Wang and Titterington (2005) for the asymptotic variational posterior covariance being 'too small'. Open problems (Section 5.4) also list alternative divergences (e.g. alpha-divergences, EP), and say mean-field independence assumptions can exacerbate local optima and underestimation of posterior variances; the final open problem is understanding VI as an estimator. Self-citation: the geometry argument cites Kucukelbir et al. (2015) (ADVI, by two of the authors), and the SVI section summarizes Hoffman et al. (2013) (co-authored by Blei); see arxiv-1603.00788 and arxiv-1206.7051. No experiments beyond illustrative examples (mixture of Gaussians on images, LDA on 1.8M NYT articles reproduced from Hoffman et al.)."},

    {"id": "arxiv-1711.05597",
     "title": "Advances in Variational Inference",
     "authors": ["Cheng Zhang", "Judith Butepage", "Hedvig Kjellstrom", "Stephan Mandt"],
     "year": 2017, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1711.05597"},
     "tasks": ["posterior-inference"],
     "fam": ["variational-inference", "variational-autoencoders", "bayesian-deep-learning"],
     "proposes": ["Survey of recent VI research along four directions: scalable VI (stochastic VI, variance reduction, collapsed/sparse/distributed inference), generic VI (score-function/REINFORCE and reparameterization gradients for non-conjugate models), accurate VI (alternative divergences, structured families) and amortized VI (inference networks, VAEs)"],
     "claims": [
         ("Positioning VI against MCMC: MCMC is often unbiased by construction and converges to the true posterior in the limit but can be slow to converge; optimization-based methods (VI, loopy BP, EP) are often faster but may suffer from oversimplified posterior approximations (citing Bishop and Wainwright & Jordan).",
          "Section 1 (Introduction)",
          "Optimization-based methods, on the other hand, are often faster but may suffer from oversimpliﬁed posterior approximations [14], [205]."),
         ("Limitations of mean-field VI: it explicitly ignores correlations between variables; citing Wainwright & Jordan [205], the more dependencies are broken by the variational distribution, the more non-convex the optimization becomes, while more structure removes certain local optima.",
          "Section 5.1",
          "The main limitation of mean ﬁeld approximations is that they explicitly ignore correlations between different variables e.g., between the spins in the Ising model."),
         ("Shortcomings of KL(q||p) VI listed by the authors with citations: underestimating posterior variances [128], in some cases inability to break symmetry when multiple modes are close [141], and being a comparably loose bound [221]; these motivate alternative divergence measures.",
          "Section 5.2",
          "In other cases, it is unable to break symmetry when multiple modes are close [141], and is a comparably loose bound [221]."),
         ("With Renyi's alpha-divergence, a smaller alpha leads to more mass-covering behaviour and a larger alpha to zero-forcing behaviour (the approximation avoids areas of low posterior probability); alpha -> 1 recovers standard KL-based VI.",
          "Section 5.2",
          "a smaller α leads to more mass-covering effects, while a larger α results in zero-forcing effects"),
         ("Black-box VI writes the ELBO gradient as an expectation under q of the score function times (log p(x,z) - log q(z)), estimated by sampling from q, so only the joint needs to be specified. A direct implementation suffers from high gradient variance; the authors attribute much of BBVI's success to Rao-Blackwellization and control variates (citing Ranganath et al. [154]).",
          "Section 4.2",
          "A direct implementation of stochastic gradient ascent based on Eq. 14 suffers from high variances of the estimated gradients."),
         ("Reparameterization gradients are empirically often lower-variance than score-function gradients, but a theoretical analysis (cited) shows this is not guaranteed; the trick does not trivially extend to many distributions, in particular discrete ones, which require further approximations (e.g. Gumbel-softmax relaxations with a temperature).",
          "Section 4.3",
          "While the variance of this estimator (Eq. 16) is often lower than the variance of the score function gradient (Eq. 14), a theoretical analysis shows that this is not guaranteed, see Chapter 3 in [48]."),
         ("Open question on theory: few authors address theoretical aspects of VI; quantifying the approximation error of replacing the posterior by a variational distribution, and the related predictive error, are named as important directions.",
          "Section 7 (Discussion)",
          "Despite progress in modeling and inference, few authors address theoretical aspects of VI [95], [133], [213]."),
         ("Automatic VI in probabilistic programming (Stan, Infer.Net, Edward, etc.) is still not straightforward for non-experts: e.g. Infer.Net requires manually identifying and breaking posterior symmetries, and control variates need model-specific design for best performance; the authors state these problems were not yet addressed in toolboxes at the time of writing.",
          "Section 7 (Discussion)",
          "Despite current efforts to make VI more accessible to practitioners, its usage is still not straightforward for non-experts."),
     ],
     "notes": "Affiliations (PDF page 1): Microsoft Research / Disney Research / KTH (Zhang), KTH (Butepage, Kjellstrom), UC Irvine (Mandt). Author names are written with umlauts in the PDF (Bütepage, Kjellström). No venue is stated in the v3 PDF (only 'Member, IEEE' after names); none recorded. Section numbers are from numbered headings in the PDF text. Scalable VI (Section 3): SVI requires the same convergence conditions as SGD (uniform minibatches, Robbins-Monro step sizes), and SVRG-type control variates are stated not to be applicable to BBVI noise because the full gradient is not a finite sum (Section 4.2). Laplace approximation is described as purely local; the authors state KL minimization typically approximates the posterior covariance more accurately (Section 4.1). Amortized VI and the VAE 'dying units' problem are covered in Section 6 (not recorded). Survey only; no experiments. The review's [15] is Blei, Kucukelbir & McAuliffe (arxiv-1601.00670)."},

    {"id": "arxiv-1206.7051",
     "title": "Stochastic Variational Inference",
     "authors": ["Matt Hoffman", "David M. Blei", "Chong Wang", "John Paisley"],
     "year": 2012, "venue": "JMLR", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1206.7051"},
     "tasks": ["posterior-inference", "language-modeling"],
     "fam": ["variational-inference"], "par": ["unsupervised"],
     "proposes": ["Stochastic variational inference (SVI): for models with global and local latent variables whose complete conditionals are in the exponential family, repeatedly subsample data, optimize the local variational parameters, and update the global parameters with a step along a noisy but unbiased natural gradient of the ELBO (Robbins-Monro step sizes)",
                  "SVI algorithms for latent Dirichlet allocation and the hierarchical Dirichlet process topic model"],
     "claims": [
         ("Motivation: neither MCMC nor VI scales easily to massive data; according to the authors, proposed speed-ups of both are usually tailored to specific models or compromise the correctness of the algorithm (or both).",
          "Section 1 (Introduction)",
          "Researchers have proposed speed-ups of both approaches, but these usually are tailored to speciﬁc models or compromise the correctness of the algorithm (or both)."),
         ("Inefficiency of batch coordinate-ascent VI: global parameters are initialized randomly, yet every data point must be analyzed with these uninformative values before even one global update is completed.",
          "Section 2.2",
          "This is wasteful, especially if we expect that we can learn something about the global variational parameters from only a subset of the data."),
         ("SVI update: sample a data point, optimize its local variational parameters, compute intermediate global parameters as if that point were replicated N times, and set the new global parameters to a weighted average of the old ones and the intermediate ones; this is a step along a noisy but unbiased natural gradient of the ELBO.",
          "Section 2.4",
          "This is a weighted average of the previous estimate of λ and the estimate of λ that we would obtain if the sampled data point was replicated N times."),
         ("Step size rho_t = (t + tau)^-kappa with forgetting rate kappa in (0.5, 1] and delay tau >= 0 satisfies the Robbins-Monro conditions; as long as these hold, the algorithm converges to a local optimum of the ELBO (not a global one).",
          "Section 2.4",
          "As long as the step size conditions in Equation 23 are satisﬁed, this iterative algorithm converges to a local optimum of the ELBO."),
         ("Minibatches amortize the cost of global updates and may help find better local optima: SVI is guaranteed to converge to a local optimum, but taking large steps based on very few data points may lead to a poor one.",
          "Section 2.5",
          "Stochastic variational inference is guaranteed to converge to a local optimum but taking large steps on the basis of very few data points may lead to a poor one."),
         ("Evaluation protocol: three corpora (Nature 350K documents, New York Times 1.8M, Wikipedia 3.8M), each with a held-out test set of 10,000 documents; model fit is measured by the per-word predictive log likelihood of held-out words given the observed part of each test document, which the authors prefer over held-out perplexity because it avoids comparing bounds.",
          "Section 4",
          "Unlike previous methods, like held-out perplexity (Blei et al., 2003), evaluating the predictive distribution avoids comparing bounds or forming approximations of the evaluation metric."),
         ("Comparison with batch VI for 100-topic LDA: SVI on the full collection vs batch inference on a subset of 100,000 documents (described as the size batch inference can handle); the authors state SVI converges faster and to a better model (shown in a figure).",
          "Section 3.2",
          "We see that stochastic variational inference converges faster and to a better model."),
         ("Sensitivity to learning parameters (HDP, batch size 500): all three fits were sensitive to the forgetting rate kappa, with values close to one converging to a better local optimum; batch sizes that are too small (e.g. ten documents) can affect performance. Grid: kappa in {0.5,...,1.0}, S in {10, 50, 100, 500, 1000}, tau = 1 (the algorithms were reported not sensitive to tau).",
          "Section 4",
          "All three ﬁts were sensitive to the forgetting rate; we see that a higher value (i.e., close to one) leads to convergence to a better local optimum."),
         ("Scope limitation: the algorithm was developed for conjugate exponential-family models with mean-field VI and closed-form coordinate updates; the general algorithm cannot be used for nonconjugate models (e.g. correlated or dynamic topic models). The authors also ask whether the gradient variance can be reduced while keeping unbiasedness.",
          "Section 5 (Discussion)",
          "We developed our algorithm with conjugate exponential family models."),
     ],
     "notes": "Venue: page 1 of the PDF reads 'Journal of Machine Learning Research (2013, in press)'; recorded as 'JMLR'. Year is the first arXiv version (2012). Section numbers are from numbered headings in the PDF text (2.2 mean-field VI, 2.3 natural gradient, 2.4 SVI, 2.5 extensions, 3.2 LDA, 4 empirical study, 5 discussion). The natural gradient of the ELBO w.r.t. global parameters simplifies to (expected complete-conditional natural parameter) - lambda (Section 2.3). All algorithms were implemented in Python/NumPy/SciPy by the authors (footnote 9). The batch-vs-SVI and LDA-vs-HDP comparisons are figure-only; no numbers recorded. Self-reference: the Discussion lists follow-up work by the authors (Gopalan et al. 2012, Mimno et al. 2012, Ranganath et al. 2013). Blei is a co-author of arxiv-1601.00670, arxiv-1401.0118 and arxiv-1603.00788."},

    {"id": "arxiv-1401.0118",
     "title": "Black Box Variational Inference",
     "authors": ["Rajesh Ranganath", "Sean Gerrish", "David M. Blei"],
     "year": 2013, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1401.0118"},
     "tasks": ["posterior-inference"],
     "fam": ["variational-inference", "mcmc"], "par": ["unsupervised"],
     "proposes": ["Black box variational inference (BBVI): stochastic optimization of the ELBO with noisy unbiased gradients from Monte Carlo samples of the variational distribution using the score function, requiring only evaluation of the log joint",
                  "Model-agnostic variance reduction for the score-function gradient: per-component Rao-Blackwellization over the Markov blanket under a mean-field family, and the score function itself as a control variate; plus AdaGrad step sizes and data subsampling"],
     "claims": [
         ("Motivation: for generic models and variational families, closed-form coordinate ascent is unavailable and practitioners resort to model-specific algorithms; the authors describe deriving these model by model as tedious, which hinders rapid model exploration.",
          "Section 1 (Introduction)",
          "Deriving these algorithms on a model-by-model basis is tedious work."),
         ("Score-function gradient: the ELBO gradient is written as E_q[grad log q(z|lambda) (log p(x,z) - log q(z|lambda))] and estimated with S samples from q; the score function and sampling routines depend only on the variational family, and the only model requirement is evaluating the log joint p(x, z).",
          "Section 2",
          "We emphasize that the score function and sampling algorithms depend only on the variational distribution, not the underlying model."),
         ("Failure mode of the basic estimator: its variance can be too large to be useful; high-variance gradients would require very small steps and lead to slow convergence.",
          "Section 3",
          "In practice, the high variance gradients would require very small steps which would lead to slow convergence."),
         ("Rao-Blackwellization under the mean-field family: each gradient component can use only the terms of the joint that depend on that variable's Markov blanket, giving a lower-variance estimator without model-specific integrals.",
          "Section 3.1",
          "This equation says that Rao-Blackwellized estimators can be computed for each component of the gradient without needing to compute model-speciﬁc conditional expectations."),
         ("Control variate: the score function of the variational approximation is used because it always has expectation zero and depends only on the variational distribution; the scaling a* = Cov(f, h)/Var(h) is estimated from the same Monte Carlo samples.",
          "Section 3.2",
          "This equation implies that good control variates have high covariance with the function whose expectation is being computed."),
         ("Evaluation protocol: longitudinal data of 976 chronic-kidney-disease patients (803 train + 173 test, about 33K visits, 17 labs) with a nonconjugate Gamma-Normal time-series model; fully factorized gamma/normal variational families, AdaGrad and data subsampling, 1,000 samples from q and batch size 25; predictive likelihood on 25% of held-out test data after fitting local parameters on 75%.",
          "Section 5",
          "We use 1,000 samples from the variational distribution and set the batch size at 25 in all our experiments."),
         ("Comparison with sampling (fixed 20-hour budget): standard Metropolis-Hastings is stated to fail on the Gamma-Normal-TS model, so BBVI is compared with Metropolis-Hastings within Gibbs; the authors report BBVI reaches better predictive likelihoods faster (figure). A footnote notes that methods requiring a bit more work, such as HMC, could work in this setting but were not compared.",
          "Section 5.3",
          "We ﬁnd that it fails for the Gamma-Normal-TS model."),
         ("Variance reduction result: Rao-Blackwellization reduced gradient variance by several orders of magnitude and control variates reduced it further; in the time allotted, the algorithm without variance reductions failed to make noticeable progress.",
          "Section 5.4",
          "We found that Rao-Blackwellization reduces the variance by several orders of magnitude."),
     ],
     "notes": "Affiliation: Princeton University. No venue is stated in the v1 PDF; none recorded. Section numbers are from numbered headings in the PDF text. Extensions (Section 4): AdaGrad per-component step sizes (Section 4.1) and doubly stochastic subsampling for hierarchical models following Hoffman et al. (2013) (co-authored by Blei). Stopping rule in the algorithms: 'until change of lambda is less than 0.01'. The MH-within-Gibbs comparator is the authors' own implementation; results (Figure 1, Figure 2, Table 1) are figure/table-only and not recorded (Table 1 values are not extractable as text). Related work: Kingma and Welling's reparameterization is described as limited to continuous latent variables. Future work mentions quasi-Monte Carlo and dynamically set sample sizes."},

    {"id": "arxiv-1603.00788",
     "title": "Automatic Differentiation Variational Inference",
     "authors": ["Alp Kucukelbir", "Dustin Tran", "Rajesh Ranganath", "Andrew Gelman", "David M. Blei"],
     "year": 2016, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1603.00788"},
     "tasks": ["posterior-inference"],
     "fam": ["variational-inference", "mcmc"],
     "proposes": ["Automatic differentiation variational inference (ADVI), implemented in Stan: transform constrained latent variables to real coordinate space, posit a mean-field or full-rank Gaussian there, compute ELBO gradients by Monte Carlo after elliptical standardization (reparameterization) with automatic differentiation, and optimize by stochastic gradient ascent with an adaptive step-size sequence"],
     "claims": [
         ("Model class: differentiable probability models, i.e. continuous latent variables with a gradient of the log joint valid on the support of the prior; no conjugacy assumptions are made. Discrete latent variables must be marginalized out, which the authors note is not tractable for all models (e.g. Ising model, sigmoid belief networks, untruncated Dirichlet process mixtures).",
          "Section 2.1",
          "We make no assumptions about conjugacy, either full (Diaconis et al., 1979) or conditional (Hoffman et al., 2013)."),
         ("Support assumption: minimizing KL(q||p) requires the support of q to lie within that of the posterior; ADVI further assumes the posterior support equals the prior support (holds when the likelihood does not constrain the prior), which the authors call benign.",
          "Section 2.2",
          "This is a benign assumption, which holds for most models considered in machine learning."),
         ("Variational families in the transformed space: a mean-field Gaussian (log standard deviations) or a full-rank Gaussian (Cholesky factor). The full-rank Gaussian captures posterior correlations and is more accurate but has a computational cost; the induced approximation in the original space is non-Gaussian, and its shape depends on the chosen transformation.",
          "Section 2.4",
          "This leads to a more accurate posterior approximation than the mean-ﬁeld Gaussian; however, it comes at a computational cost."),
         ("Known weakness shown on simulated models: on a correlated 2D Gaussian both variants recover the analytic posterior mean, but mean-field ADVI ignores off-diagonal covariance and minimizing KL(q||p) leads to systematic underestimation of marginal variances; on logistic regression (reference: Stan's NUTS) mean-field underestimates marginal variances on most coefficients, and on a stochastic volatility model it struggles even with the posterior mean where full-rank matches sampling.",
          "Section 3.1",
          "ADVI minimizes the KL divergence from the approximation to the exact posterior; this leads to a systemic underestimation of marginal variances (Bishop, 2006)."),
         ("Recommendation: scientists interested in posterior variances and covariances should use full-rank ADVI (though it can be prohibitively slow for large data); those interested in prediction should initially rely on mean-field ADVI, since in practice accurate posterior means dominate predictive accuracy.",
          "Section 3.1",
          "Scientists interested in posterior variances and covariances should use the full-rank approximation."),
         ("Gradient variance: both the ADVI (reparameterization) estimator and the BBVI score-function estimator are unbiased; BBVI is more general (no model gradient needed) but its gradients can suffer from high variance. In the authors' simulations the ADVI gradient had lower variance and a single MC sample sufficed in practice.",
          "Section 3.2",
          "While BBVI is more general—it does not require the gradient of the model and thus applies to more settings—its gradients can suffer from high variance."),
         ("Sensitivity to the transformation T: on Gamma posteriors, T2 = log(exp(theta) - 1) gave lower KL than T1 = log; an optimal transformation (making the Gaussian approximation exact) exists in principle but estimating it requires the posterior CDF, which the authors say is as hard as the original problem. The Discussion lists this sensitivity as an avenue for research.",
          "Section 3.3",
          "this is just as hard as the original goal of estimating the posterior density"),
         ("Evaluation protocol: mean-field ADVI is compared with HMC and NUTS (Stan's default sampler) by held-out predictive likelihood as a function of time on hierarchical regression, matrix factorization, mixture and PPCA models. On the non-negative matrix factorization models HMC produced no useful samples within a one-hour budget and was omitted thereafter; on the GMM the authors attribute NUTS/HMC difficulties likely to label switching.",
          "Section 4.2",
          "In both cases, HMC does not produce any useful samples within a budget of one hour; we omit HMC from here on."),
     ],
     "notes": "Affiliations: Columbia (Kucukelbir, Tran, Gelman, Blei), Princeton (Ranganath). No venue is stated in the v1 PDF (dated March 3, 2016); none recorded. Section numbers are from numbered headings in the PDF text. Extends Kucukelbir et al. (2015) (footnote 1). Conflict of interest: the authors 'implemented and deployed ADVI as part of Stan' (Introduction), and the compared NUTS is Stan's default sampler (footnote 9), i.e. ADVI and its MCMC comparators come from the same system and were run by the authors; the PDF does not itself state Stan team membership of individual authors. Also, and BBVI (compared in Section 3.2) is by co-authors Ranganath and Blei (arxiv-1401.0118). Algorithm details: adaptive step size rho = eta * i^(-1/2+eps) * (tau + sqrt(s_k))^-1 with s_k an exponential moving average of squared gradients (alpha = 0.1, tau = 1, eps = 1e-16); eta is chosen by searching {0.01, 0.1, 1, 10, 100} on a subset of the data for fastest convergence (Section 2.6). Per-iteration cost O(NMK), or O(BMK) with minibatch subsampling scaled by N/B. Initialization: standard Gaussian in the real coordinate space; the Discussion names initialization and step-size scaling as the two practical factors affecting convergence and suggests extending to discrete latent variables via the higher-variance BBVI estimator. Predictive accuracy results are figure-only; Table 2 KL values for the transformation study are not recorded. Smaller GMM minibatches (< 500) led to suboptimal solutions (Section 4.3)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
