import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_bo_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1502.05700",
     "title": "Scalable Bayesian Optimization Using Deep Neural Networks",
     "authors": ["Jasper Snoek", "Oren Rippel", "Kevin Swersky", "Ryan Kiros", "Nadathur Satish",
                 "Narayanan Sundaram", "Md. Mostofa Ali Patwary", "Prabhat", "Ryan P. Adams"],
     "year": 2015, "venue": "ICML 2015", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1502.05700"},
     "tasks": ["hyperparameter-optimization", "image-classification"],
     "fam": ["bayesian-optimization", "deep-learning"],
     "proposes": ["Deep Networks for Global Optimization (DNGO): Bayesian optimization whose surrogate is a neural network trained by SGD (MAP point estimate) with a Bayesian linear regressor on the last hidden layer (adaptive basis regression), so cost scales linearly in the number of observations and cubically in the basis dimension; used with (constrained, parallel Monte Carlo) expected improvement"],
     "claims": [
         ("Motivation: a major drawback of GP-based Bayesian optimization is that inference time grows cubically in the number of observations because a dense covariance matrix must be inverted; the authors argue this has made it infeasible to combine large-scale parallelism with GP-based BO as search spaces and required evaluations grow.",
          "1. Introduction",
          "inference time grows cubically in the number of observations"),
         ("DNGO surrogate: a Bayesian linear regressor is added to the last hidden layer of a deep neural network, marginalizing only the output weights while using a point estimate for the remaining parameters (a pragmatic alternative to fully Bayesian neural networks, which the authors describe as very computationally expensive at large scale).",
          "3. Adaptive Basis Regression with Deep Neural Networks",
          "we take a pragmatic approach and add a Bayesian linear regressor to the last hidden layer of a deep neural network"),
         ("Cost: the resulting adaptive basis regression scales linearly in the number of observations and cubically in the basis function dimensionality, which allows an explicit trade-off between evaluation time and model capacity; the matrix to invert grows with the output dimensionality D rather than the number of observations N.",
          "3. Adaptive Basis Regression with Deep Neural Networks",
          "scales linearly in the number of observations, and cubically in the basis function dimensionality"),
         ("Design choices matter: the activation function significantly altered BO performance; ReLU units can lead to very poor uncertainty estimates and excessive exploration, so bounded tanh units are used (a ReLU network with tanh only on the last layer is suggested if the smoothness assumption needs relaxing).",
          "3.1.1. Network Architecture",
          "the commonly used rectiﬁed linear (ReLU) function can lead to very poor estimates of uncertainty, which causes the Bayesian optimization routine to explore excessively"),
         ("The surrogate network's own hyperparameters (learning rate, momentum, layer sizes, l2 penalties, dropout) were tuned with GP-based BO (Spearmint) to minimize the average relative loss on a series of benchmark global optimization problems; the chosen architecture (3 hidden layers of about 50 units, no dropout) is used throughout the evaluation. The text does not state whether these tuning problems overlap the HPOLib problems used later for evaluation.",
          "3.1.1. Network Architecture",
          "In order to tune any remaining hyperparameters, such as the width of the hidden layers and the amount of regularization, we used GP-based Bayesian optimization."),
         ("Parallelism: following Snoek et al. (2012), pending experiments are handled by averaging EI over fantasy outcomes; with a GP the cost of EI per candidate becomes cubic in the size of the augmented dataset, restricting the number of running experiments and fantasy sets, whereas DNGO allows both to be scaled up.",
          "3.3. Parallel Bayesian Optimization",
          "With DNGO it is possible to scale both of these up to accommodate a much higher degree of parallelism."),
         ("HPOLib benchmark comparison: DNGO is compared with SMAC (random forests), TPE and the input-warped GP method of Snoek et al. (2014) (Spearmint) on continuous HPOLib problems, each method run 10 times; the authors report that DNGO significantly outperforms SMAC and TPE and is competitive with the GP approach in the number of evaluations needed.",
          "4.1. HPOLib Benchmarks",
          "DNGO signiﬁcantly outperforms SMAC and TPE, and is competitive with the Gaussian process approach"),
         ("Massively parallel use case (image caption generation with a log-bilinear model, 11 hyperparameters, average 26.6 hours per evaluation): validation BLEU was optimized with 300-800 experiments in parallel, about 2500 experiments in total; test-set results of the best models are compared with LSTM results reported in other papers.",
          "4.2. Image Caption Generation",
          "we proposed and evaluated approximately 2500 experiments—the equivalent of over 2700 CPU days—in less than one week"),
     ],
     "notes": "Affiliations: Harvard, MIT, University of Toronto, Intel Labs, NERSC/LBNL. Venue from the PDF first page ('Proceedings of the 32nd International Conference on Machine Learning, Lille, France, 2015'). Conflict of interest: the GP baseline (Spearmint with input warping, Snoek et al. 2014) is by overlapping authors, and Spearmint was also used to tune DNGO's own architecture. CIFAR-10/100 CNN tuning: optimized on a 10,000-example validation split from the training set with 40 parallel jobs (200 epochs per run), then the best configuration retrained for 350 epochs on the full training set; compared to published state-of-the-art numbers from other papers (not same-budget baselines). Also models unknown constraints with a Bayesian logistic-regression output layer (Laplace approximation). Fig. 1 (time per suggestion vs GP) is a figure only; values not recorded."},

    {"id": "arxiv-1910.01739",
     "title": "Scalable Global Optimization via Local Bayesian Optimization",
     "authors": ["David Eriksson", "Michael Pearce", "Jacob R Gardner", "Ryan Turner", "Matthias Poloczek"],
     "year": 2019, "venue": "NeurIPS 2019", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1910.01739"},
     "tasks": ["black-box-optimization", "hyperparameter-optimization"],
     "fam": ["bayesian-optimization", "gaussian-processes"],
     "proposes": ["TuRBO (trust region Bayesian optimization): several simultaneous local BO runs, each with an independent GP in a hyperrectangular trust region centred at its best point that expands after consecutive successes and shrinks after consecutive failures (restarted when too small), with batch candidates allocated across trust regions by Thompson sampling (an implicit multi-armed bandit)"],
     "claims": [
         ("Motivation: the authors take the view that BO struggles on high-dimensional problems with thousands of observations because global probabilistic models are implicitly homogeneous and global acquisition over-emphasizes exploration.",
          "Abstract",
          "In this paper we take the view that this is due to the implicit homogeneity of the global probabilistic models and an overemphasized exploration that results from global acquisition."),
         ("Stationarity assumption: commonly used global GP models implicitly suppose that characteristic lengthscales and signal variances are constant across the search space (e.g. RL objectives with sparse rewards are nearly constant in large regions); non-stationary kernels avoid this but are too expensive for the large-scale setting.",
          "Introduction",
          "implicitly suppose that characteristic lengthscales and signal variances of the function are constant in the search space"),
         ("Trust region: a hyperrectangle centred at the best solution (smallest posterior mean under noise), with per-dimension side lengths rescaled by the GP lengthscales; it is doubled after tau_succ consecutive successes, halved after tau_fail consecutive failures, and discarded and restarted when below L_min. These thresholds and initial/maximum lengths are hyperparameters of TuRBO (values in the supplement).",
          "The trust region Bayesian optimization algorithm",
          "We choose our TR to be a hyperrectangle centered at the best solution found so far"),
         ("Global allocation: TuRBO maintains m trust regions with independent local GPs; for each of the q batch candidates a Thompson sample is drawn from every local GP and the point with the smallest sampled value across all trust regions is selected.",
          "The trust region Bayesian optimization algorithm",
          "To solve this problem, we ﬁnd that TS provides a principled solution to both the problem of selecting candidates within a single TR, and selecting candidates across the set of trust regions simultaneously."),
         ("Baseline configuration: BOCK and BOHAMIANN have their EI criterion replaced by batch Thompson sampling so that all BO methods use the same criterion; their original implementations do not support batch suggestions and needed changes. The authors note that NM, BFGS and BOBYQA are inherently sequential and thus have an edge per evaluation but are slower per wall time with large batches.",
          "Numerical experiments",
          "The standard acquisition criterion EI used in BOCK and BOHAMIANN is replaced by (batch) TS, i.e., all methods use the same criterion which allows for a direct comparison."),
         ("Evaluation protocol: five problems (14D robot pushing, 60D rover trajectory, 12D cosmological constants, 12D lunar landing, 200D Ackley) with budgets of 1,500 to 20,000 evaluations and batch sizes of 50 or 100; plots show the mean with one standard error. The number of replications for these main problems was not found in the text (searched for runs, replications, trials, repeated); the supplementary synthetic experiments use 30 runs. For the robot pushing and rover problems the authors compare with EBO values reported by Wang et al. after more evaluations rather than rerunning that setting.",
          "Numerical experiments",
          "Performance plots show the mean performances with one standard error."),
         ("Local vs global GP regression on the robot pushing problem (20 hypercubes x 200 points; isotropic kernel for illustration): local GPs had better held-out log loss than a single global GP on all 4000 points in every one of 50 trials (significant under a t-test, p < 1e-4), and the fitted hyperparameters, especially the signal variance, varied substantially across regions.",
          "The advantage of local models over global models",
          "Furthermore, the local GPs perform better than the global GP in every repeated trial."),
         ("Scaling cost: GP regression uses GPyTorch (conjugate gradients and Lanczos) with a Matérn-5/2 ARD kernel; without it, BO with a GP for more than a few thousand evaluations would be infeasible because classical GP regression scales cubically. Reported algorithm overhead excludes objective-evaluation time.",
          "Supplementary material (Gaussian process regression)",
          "Without GPyTorch, running BO with a GP model for more than a few thousand evaluations would be infeasible as classical approaches to GP regression scale cubically in the number of data points."),
         ("Large batches: for TuRBO-1 on robot pushing with batch sizes 1 to 64 (30 replications), larger batches obtained better results for the same number of batches, and the authors describe the speed-up as essentially linear in terms of evaluations.",
          "The efﬁciency of large batches",
          "We see that the speed-up is essentially linear."),
     ],
     "notes": "Affiliations: Uber AI and University of Warwick. Venue from the PDF footer ('33rd Conference on Neural Information Processing Systems (NeurIPS 2019)') and the arXiv comment. The problems are black-box optimization (control, RL, physics simulator calibration, synthetic) rather than ML hyperparameter tuning; the hyperparameter-optimization task tag is used because no general black-box-optimization task tag is registered (hyperparameter tuning is named as an application in the Introduction). Baselines: BFGS, BOCK, BOHAMIANN, CMA-ES (pycma, default settings, population = batch size), BOBYQA (nlopt), EBO, GP-TS, HeSBO-TS, Nelder-Mead, random search; local optimizers use restarts. TuRBO-1 hyperparameters: tau_succ = 3, tau_fail = ceil(d/q), L_min = 2^-7, L_max = 1.6, L_init = 0.8; candidate sets of min(100d, 5000) Sobol points perturbing about 20 coordinates. The supplement's runtime table reports TuRBO overhead in minutes versus hours to days for global-GP BO methods (table values not recorded). Results figures not recorded."},

    {"id": "arxiv-1910.06403",
     "title": "BoTorch: A Framework for Efficient Monte-Carlo Bayesian Optimization",
     "authors": ["Maximilian Balandat", "Brian Karrer", "Daniel R. Jiang", "Samuel Daulton", "Benjamin Letham",
                 "Andrew Gordon Wilson", "Eytan Bakshy"],
     "year": 2019, "venue": "NeurIPS 2020", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1910.06403"},
     "tasks": ["black-box-optimization", "hyperparameter-optimization"],
     "fam": ["bayesian-optimization", "gaussian-processes", "automl-systems"],
     "proposes": ["BoTorch: a PyTorch-based modular framework for Monte-Carlo (MC) Bayesian optimization (models, posteriors, samplers, MC objectives and acquisition functions), optimizing MC acquisition functions by sample average approximation (fixed base samples, quasi-MC, deterministic L-BFGS-B)",
                  "One-Shot Knowledge Gradient (OKG): knowledge gradient optimized jointly over the candidates and fantasy points as a single deterministic problem under SAA"],
     "claims": [
         ("MC acquisition functions: analytic forms are not available for arbitrary objectives or utilities, non-Gaussian posteriors, or batches of points evaluated in parallel or asynchronously, so the expectation defining the acquisition function is approximated by averaging over posterior samples; randomized quasi-MC can significantly reduce the variance of the estimate and its gradient.",
          "Section 3 (Monte-Carlo Acquisition Functions)",
          "Instead, MC integration can be used to approximate the expectation (1) using samples from the posterior."),
         ("Sample average approximation (SAA): instead of redrawing samples at each evaluation and using stochastic first-order methods, BoTorch draws base samples once and holds them fixed, making the MC estimate deterministic so that deterministic quasi-Newton optimizers (by default multi-start L-BFGS-B) can be used.",
          "Section 4 (MC Bayesian Optimization via Sample Average Approximation)",
          "and hold it ﬁxed between evaluations throughout the course of optimization"),
         ("Theory (Theorem 1): assuming a compact feasible set, a GP prior with continuously differentiable mean and covariance, Lipschitz objective and utility, and i.i.d. normal base samples, the SAA optimum converges almost surely, and under additional regularity conditions at an exponential rate in probability. The authors do not characterize theoretical rate improvements of RQMC over MC, but observe empirically that RQMC works remarkably well.",
          "Section 4 (MC Bayesian Optimization via Sample Average Approximation)",
          "While at this point we do not characterize improvements in theoretical convergence rates of RQMC over MC for SAA, we observe empirically that RQMC methods work remarkably well in practice"),
         ("The authors find that in practice the bias from SAA has only a minor effect relative to the analytic ground truth, often improves on stochastic approaches, and avoids tuning optimization hyperparameters such as learning rates.",
          "Section 4 (MC Bayesian Optimization via Sample Average Approximation)",
          "We ﬁnd that in practice the bias from using SAA only has a minor effect on the performance relative to using the analytic ground truth"),
         ("One-Shot KG: the nested knowledge-gradient problem is solved jointly over candidates and N fantasy points (dimension (q + N)d instead of qd) as a single deterministic problem; its main limitation is the linear growth of the problem dimension in N, though the authors observe good performance for moderate N.",
          "Section 4.2 (One-Shot Formulation of the Knowledge Gradient using SAA)",
          "The main limitation of OKG is the linear growth of the dimension of the optimization problem in N"),
         ("Library comparison protocol: BoTorch is compared with GPyOpt, Cornell MOE and Dragonfly, chosen as the most popular libraries with ongoing support (GPFlowOpt could not be installed), with all packages using their default models and settings; the authors report that BoTorch's algorithms tend to achieve greater sample efficiency.",
          "Section 6 (Experiments)",
          "First, we ﬁnd that BOTORCH’s algorithms tend to achieve greater sample efﬁciency compared to those of other packages (all packages use their default models and settings)."),
         ("Synthetic-benchmark protocol: noisy Branin, Rosenbrock, Ackley and Hartmann with q = 4, means and 95% confidence intervals over 100 trials, all algorithms starting from the same 2d + 2 QMC initial points; performance is the true noiseless value at the suggested point, which is out-of-sample for OKG, MOE KG and NEI and in-sample for the others.",
          "Appendix C.1",
          "We evaluate based on the true noiseless function value at the “suggested point” (i.e., the point to be chosen if BO were to end at this batch)."),
         ("HPO protocol: for hyperparameter tuning the configuration with the best observed performance is reported rather than a suggested point; e.g. DQN on Cartpole (5 hyperparameters, each evaluation an average of 10 training runs, 15 rounds of q = 4, 100 trials) and an HPOlib2 neural-network surrogate for UCI Adult (200 trials of 75 iterations, q = 1).",
          "Appendix C.4",
          "As HPO typically involves long and resource intensive training jobs, it is standard to select the conﬁguration with the best observed performance, rather than to evaluate a “suggested” conﬁguration (we cannot perform noiseless function evaluations)."),
     ],
     "notes": "Affiliations: Facebook (six authors) and New York University. Venue from the PDF footer ('34th Conference on Neural Information Processing Systems (NeurIPS 2020)') and the arXiv journal_ref; arXiv first version 2019. Conflict of interest: the authors evaluate their own open-source library (botorch.org) against other libraries run with default settings; the GPU/fast-predictive-distribution results rely on GPyTorch, which BoTorch integrates closely with. BoTorch primitives are stated to work with any model that provides reparameterized posterior samples, but the paper focuses on GPyTorch GPs. Constrained-BO results (Appendix C.3) show only BoTorch algorithms because other packages do not natively support unknown constraints. SWA on CIFAR-10 (VGG-16, 3 hyperparameters tuned with OKG) is reported against the mean accuracy reported by Izmailov et al.; which data split the tuning objective used was not found in the text (searched for validation, held out, test). High-dimensional, multi-fidelity and multi-objective BO are outside the paper's scope. Figures not recorded."},

    {"id": "arxiv-1907.10902",
     "title": "Optuna: A Next-generation Hyperparameter Optimization Framework",
     "authors": ["Takuya Akiba", "Shotaro Sano", "Toshihiko Yanase", "Takeru Ohta", "Masanori Koyama"],
     "year": 2019, "venue": "KDD 2019 (Applied Data Science track)", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1907.10902"},
     "tasks": ["hyperparameter-optimization"],
     "fam": ["bayesian-optimization", "multi-fidelity-optimization", "automl-systems"],
     "proposes": ["Optuna: a hyperparameter optimization framework with a define-by-run API (the search space is constructed dynamically by trial.suggest calls inside the objective), independent (e.g. TPE) and relational (e.g. CMA-ES, GP-BO) samplers, pruning via a variant of Asynchronous Successive Halving, and a storage-based architecture from in-memory to distributed RDB backends"],
     "claims": [
         ("Define-by-run: borrowing the term from deep-learning frameworks, Optuna lets the user construct the search space dynamically during the objective's execution (via trial suggest calls, with ordinary loops and conditionals), instead of defining the whole space in advance.",
          "Define-by-run API",
          "Following the original deﬁnition, we use the term deﬁne-by-run in the context of optimization framework to refer to a design that allows the user to dynamically construct the search space."),
         ("The authors claim that all previous hyperparameter optimization frameworks require the user to construct the search space statically for each model, which they argue is extremely hard for large experiments with many model types and conditional variables.",
          "Introduction",
          "Firstly, all previous hyperparameter optimization frameworks to date require the user to statically construct the parameter-search"),
         ("Sampling: Optuna supports independent sampling (e.g. TPE) and relational sampling (e.g. CMA-ES, GP-BO), identifying concurrence relations among parameters after some independent samplings; the authors note that independent sampling is not necessarily naive and that cost-effectiveness depends on environment and task. No statement that TPE is the default sampler was found in the text (searched for default).",
          "Efficient Sampling and Pruning Mechanism",
          "The independent sampling is not necessarily a naive option, because some sampling algorithms like TPE [6] are known to perform well even without using the parameter correlations, and the cost eﬀectiveness for both relational and independent sampling depends on environment and task."),
         ("Pruning: intermediate values are reported via report and checked via should_prune; the pruner is a variant of Asynchronous Successive Halving that promotes trials within the top 1/eta of their rung; to avoid storing many checkpointed configurations the implementation does not allow repechage.",
          "Efficient Sampling and Pruning Mechanism",
          "our implementation does not allow repechage"),
         ("Sampler benchmark protocol: on a collection of 56 black-box optimization test cases, TPE+CMA-ES (TPE for the first 40 steps, CMA-ES afterwards) is compared with random search, Hyperopt, SMAC3 and GPyOpt using the best value found in 80 trials, 30 repetitions per study and a paired Mann-Whitney U test with alpha = 0.0005, following Dewancker et al.",
          "Experimental Evaluation",
          "For TPE+CMA-ES, we used TPE for the ﬁrst 40 steps and used CMA-ES for the rest."),
         ("In that benchmark the GP-based GPyOpt performed better than TPE+CMA-ES in 34 of 56 cases, while TPE+CMA-ES took an order of magnitude less time per trial; the authors suggest the user may use a GP-based method if the time of evaluation is a bottleneck.",
          "Experimental Evaluation",
          "Meanwhile, GPyOpt performed better than TPE+CMA-ES in 34/56 cases in terms of the best-attained loss value."),
         ("Pruning evaluation protocol: simplified AlexNet (8 hyperparameters) on SVHN, each study on one Tesla P100 GPU stopped after 4 hours and repeated 40 times; the reported curves are average test errors. Whether the optimized objective was a validation or test error was not found stated for this experiment (searched for validation).",
          "Section 5.2 (Performance Evaluation of Pruning)",
          "We repeated each study 40 times."),
         ("The authors report that their ASHA implementation significantly outperforms median pruning (featured in Vizier) and conclude that a sampling algorithm alone is not sufficient for cost-effective optimization, because per-trial computational cost is the bottleneck.",
          "Section 5.2 (Performance Evaluation of Pruning)",
          "This result also suggests that sampling algorithm alone is not suﬃcient for cost-eﬀective optimization."),
         ("Distributed optimization with TPE on 1, 2, 4 and 8 workers: the authors note that for sequential model-based methods such as TPE the number of workers need not translate into efficiency, but observe that scores per number of trials barely change with the number of workers, i.e. performance scales linearly with workers (also with ASHA pruning).",
          "Performance Evaluation of Distributed Optimization",
          "Note that the optimization scores per the number of trials (i.e., parallelization eﬃciency) barely changes with the number of workers."),
     ],
     "notes": "Affiliation: Preferred Networks, Inc. (all authors). Venue from the arXiv comment ('Accepted at KDD 2019 Applied Data Science track'); the PDF itself is labelled 'Preprint'. Conflict of interest: the authors evaluate their own framework, the real-world applications (Open Images detection, HPL for Preferred Networks' MN-1b supercomputer, RocksDB, FFmpeg) are Preferred Networks projects, and the paper states Optuna has been in production use at Preferred Networks for more than a year. The feature comparison (Table 2) is the authors' own assessment of other frameworks. The Fig. 1 example objective returns 1 - score on a held-out test split (an illustrative code example). Section 5.2 is confirmed by the cross-reference 'Based on the same experimental setup used in Section 5.2'; other locations use section names. Benchmark results are shown in figures (Fig. 9-12) and not recorded."},

    {"id": "arxiv-2012.03826",
     "title": "HEBO Pushing The Limits of Sample-Efficient Hyperparameter Optimisation",
     "authors": ["Alexander I. Cowen-Rivers", "Wenlong Lyu", "Rasul Tutunov", "Zhi Wang", "Antoine Grosnit",
                 "Ryan Rhys Griffiths", "Alexandre Max Maraval", "Hao Jianye", "Jun Wang", "Jan Peters",
                 "Haitham Bou Ammar"],
     "year": 2020, "venue": "JAIR", "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/2012.03826"},
     "tasks": ["hyperparameter-optimization", "tabular-classification", "tabular-regression"],
     "fam": ["bayesian-optimization", "gaussian-processes"],
     "proposes": ["HEBO (Heteroscedastic and Evolutionary Bayesian Optimisation): a GP-based BO solver with Box-Cox/Yeo-Johnson output transformation and Kumaraswamy input warping, a robust (noise-perturbed) acquisition, and a multi-objective ensemble of EI, PI and UCB solved for a Pareto front with NSGA-II (handling mixed continuous/integer variables)"],
     "claims": [
         ("Heteroscedasticity (Section 3.2): applying an output transformation (Box-Cox/Yeo-Johnson) to a vanilla GP gave a more favourable log probability in 70 of 108 Bayesmark tasks, significantly in 58 (two-sided paired t-test); Levene's and Fligner-Killeen tests rejected homoscedasticity in 72 and 73 of 108 tasks, which the authors read as at least 66% of tasks being heteroscedastic.",
          "Section 3.2",
          "In 58/108 tasks, the gain is signiﬁcant at the 95% level of conﬁdence (p-value < 0.025)."),
         ("Non-stationarity (Section 3.1): with Kumaraswamy input warping the stationary GP's log probability was more favourable in 106 of 108 tasks and significantly so in 79 (described as a one-sided t-test, whereas the output-transform test in Section 3.2 is described as two-sided paired).",
          "Section 3.1",
          "In 79/108 tasks, the gain is signiﬁcant at the 95% level of conﬁdence (p-value < 0.025)."),
         ("Modelling fix: Box-Cox (Yeo-Johnson for labels of arbitrary sign) output transformations together with Kumaraswamy input warping are chosen as a balance between simplicity and empirical performance; the output-transform parameter is refit before the GP, and the warping parameters are optimized under the GP marginal likelihood (similar to Balandat et al., 2020).",
          "Section 4.1",
          "We observe that the well-known Box-Cox (Box & Cox, 1964) and Yeo-Jonhson (Yeo & Johnson, 2000) output transformations in conjunction with the Kumaraswamy (Kumaraswamy, 1980) input transformation, oﬀer a balance between simplicity of implementation and empirical performance."),
         ("Robust acquisition: instead of a worst-case max-min formulation (conservative, no known global convergence guarantees in the non-convex non-concave case), HEBO targets the expected acquisition over random perturbations of the GP parameters and approximates it by adding Gaussian noise to the acquisition value; an informal theorem states the approximation holds with high probability for suitable noise scales.",
          "Section 4.2.1",
          "Importantly, this problem seeks to ﬁnd new query locations that perform well on average over a distribution of surrogate models in favour of assuming a perfect surrogate."),
         ("Acquisition ensemble: EI, PI and UCB (which the authors show can conflict in their optima) are optimized jointly as a multi-objective problem for a Pareto front with NSGA-II (pymoo), chosen because evolutionary solvers handle categorical and integer hyperparameters; the authors observed the GP-Hedge alternative to perform poorly compared with individual acquisitions.",
          "Section 4.2.2",
          "We however, observed this formulation to perform poorly when compared against individual acquisitions."),
         ("Evaluation protocol: 108 Bayesmark tasks (nine models, six UCI datasets, two metrics each; objective = cross-validation loss, noise from train-test splits; 2 to 9 hyperparameters), 16 iterations of batch 8 (or 100 iterations of batch 1), 20 random seeds, and a normalised score relative to an estimated optimal loss and the mean loss of random search. The same setup (Section 3) was used for the assumption analysis that motivated HEBO's design. Baselines include SkOpt, pySOT, HyperOpt, OpenTuner, Nevergrad (1+1), BOHB (modified to batch, TPE without Hyperband fidelities), Dragonfly, TuRBO and TuRBO+ (TuRBO with the authors' modelling improvements); no statement on how baseline settings were chosen was found (searched for default, tuned).",
          "Section 5",
          "Each experiment is repeated for 20 random seeds."),
         ("Ablation: removing or adding each component one at a time, the observed order of importance is heteroscedasticity (output transform), multi-objective acquisition, non-stationarity (input warping) and robustness.",
          "Section 5.3",
          "The precedence order observed is: heteroscedasticity, multi-objective acquisition functions, non-stationarity and robustness."),
         ("Black-box challenge: the abstract states that HEBO placed first in the NeurIPS 2020 Black-Box Optimisation challenge; the main text describes the challenge only as using the same UCI testbed (citing Turner et al., 2021) and gives no description of the challenge's evaluation protocol (searched for challenge).",
          "Abstract",
          "We demonstrate HEBO’s empirical eﬃcacy on the NeurIPS 2020 Black-Box Optimisation challenge, where HEBO placed ﬁrst."),
     ],
     "notes": "Affiliations: Huawei Noah's Ark Lab (all authors; some also TU Darmstadt, University of Cambridge, UCL). Venue from the arXiv comment ('Accepted at JAIR') and the PDF header ('Journal of Artificial Intelligence Research 70 (2021) 1-15, Submitted 10/2020; published 1/2021'); the volume/page numbers in that header could not be confirmed (the document is 80 pages), so only 'JAIR' is recorded. Main text carded (Sections 1-7); the appendices (proofs, search spaces, per-task tables) were not carded. Conflict of interest: the authors built HEBO and the TuRBO+ baseline; the asynchronous baselines (Dragonfly-BB, BOHB-BB) are run without their multi-fidelity components, and the authors note this trades sample efficiency for speed. The heteroscedasticity test evaluates k = 50 configurations 10 times each per task. The introduction lists findings with labels (A.I heteroscedasticity, A.II non-stationarity) that are swapped relative to the Section 3.1/3.2 headings. As extracted, the normalised score formula reads 100 x (L - L*)/(L_rand - L*) while the text treats higher scores as better; the orientation could not be confirmed from the extracted text. Section 5 states query computation was under 20 seconds per batch. Figures and tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
