import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

LLM_PTQ = ["quantization", "post-training-quantization", "large-language-models", "deep-learning"]

SPECS = [
    {"id": "arxiv-1712.05877",
     "title": "Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference",
     "authors": ["Benoit Jacob", "Skirmantas Kligys", "Bo Chen", "Menglong Zhu", "Matthew Tang", "Andrew Howard", "Hartwig Adam", "Dmitry Kalenichenko"],
     "year": 2017, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1712.05877"},
     "tasks": ["model-compression"], "fam": ["quantization", "quantization-aware-training", "deep-learning"], "par": ["supervised"],
     "proposes": ["integer-arithmetic-only 8-bit quantization scheme (affine, scale + zero-point)", "training with simulated quantization"],
     "claims": [
         ("Proposes a quantization scheme that lets inference run with integer-only arithmetic, plus a co-designed training procedure to preserve accuracy after quantization.",
          "Abstract",
          "We propose a quantization scheme that allows inference to be carried out using integer-only arithmetic, which can be implemented more efficiently than floating point inference on commonly available integer-only hardware."),
         ("Granularity: one set of quantization parameters (scale and zero-point) per activations array and per weights array (per-tensor), with separate parameters for separate arrays.",
          "Quantized Inference",
          "Our quantization scheme uses a single set of quantization parameters for all values within each activations array and within each weights array; separate arrays use separate quantization parameters."),
         ("The training procedure simulates quantization in the forward pass while backpropagation and weight storage stay in floating point (quantization-aware training).",
          "Training with simulated quantization",
          "We propose an approach that simulates quantization effects in the forward pass of training."),
         ("Failure mode: the authors found that training in float and then quantizing works sufficiently well for large models but leads to significant accuracy drops for small models; the common failure modes they list for simple post-training quantization are large differences in weight ranges across output channels and outlier weight values.",
          "Training with simulated quantization",
          "We found that this approach works sufficiently well for large models with considerable representational capacity, but leads to significant accuracy drops for small models."),
         ("Speed was evaluated on real hardware: MobileNets with varying depth multipliers and resolutions on ImageNet were benchmarked on three types of Qualcomm (Snapdragon) cores.",
          "Experiments",
          "We benchmarked the MobileNet architecture with varying depth-multipliers (DM) and resolutions on ImageNet on three types of Qualcomm cores"),
         ("Evaluation-practice position: rather than only minimizing accuracy loss for a fixed architecture, the authors advocate the latency-vs-accuracy tradeoff as a better measure.",
          "Experiments",
          "While most of the quantization literature focuses on minimizing accuracy loss for a given architecture, we advocate for a more comprehensive latency-vs-accuracy tradeoff as a better measure."),
         ("Affiliation/product disclosure: the authors are at Google, and the described scheme is the one adopted in TensorFlow Lite.",
          "Quantized Inference (footnote)",
          "The quantization scheme described here is the one adopted in TensorFlow Lite [5] and we will refer to specific parts of its code to illustrate aspects discussed below."),
     ],
     "notes": "Experiments are on image models (ImageNet classification, COCO detection); no image-task tag exists, so only model-compression is used as task."},

    {"id": "arxiv-2106.08295",
     "title": "A White Paper on Neural Network Quantization",
     "authors": ["Markus Nagel", "Marios Fournarakis", "Rana Ali Amjad", "Yelysei Bondarenko", "Mart van Baalen", "Tijmen Blankevoort"],
     "year": 2021, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2106.08295"},
     "tasks": ["model-compression"], "fam": ["quantization", "post-training-quantization", "quantization-aware-training", "deep-learning"], "par": ["post-hoc", "supervised"],
     "proposes": ["standard PTQ pipeline", "standard QAT pipeline", "quantization debugging workflow"],
     "claims": [
         ("Survey/guide claim: in most cases PTQ is sufficient for 8-bit quantization with close to floating-point accuracy, without re-training or labelled data.",
          "Abstract",
          "In most cases, PTQ is sufficient for achieving 8-bit quantization with close to floating-point accuracy."),
         ("QAT needs fine-tuning and labelled training data but enables lower-bit quantization with competitive results.",
          "Abstract",
          "QAT requires fine-tuning and access to labeled training data but enables lower bit quantization with competitive results."),
         ("PTQ calibration: in a footnote to the AdaRound step of their standard PTQ pipeline, the authors state that usually 500 to 1000 unlabeled images are sufficient as a calibration set.",
          "Section 3.5 Standard PTQ pipeline (footnote)",
          "Usually, between 500 and 1000 unlabeled images are sufficient as a calibration set."),
         ("Evaluation protocol: all models (ImageNet classifiers, DeepLabV3 on Pascal VOC, EfficientDet on COCO 2017, BERT-base on GLUE) are evaluated on the respective validation sets (Table 6 caption; the same sentence is in the Table 10 QAT caption).",
          "Section 3.6 Experiments (Table 6 caption)",
          "We evaluate all models on the respective validation sets.", 17),
         ("QAT tuning protocol: results are reported with the best learning rate per quantization configuration, with no further hyperparameter tuning. Results are reported on the validation sets; a separate split for selecting the learning rate was not found in the text.",
          "Section 4.5 Experiments",
          "We present the results with the best learning rate per quantization configuration and perform no further hyper-parameter tuning."),
         ("Failure mode: networks with depth-wise separable layers (MobileNetV2, EfficientNet lite, DeeplabV3, EfficientDet-D1) are more challenging to quantize with QAT, a trend the authors say they also observed in their PTQ results and that is discussed in the literature.",
          "Section 4.5 Experiments",
          "Quantizing networks with depth-wise separable layers (MobileNetV2, EfficientNet lite, DeeplabV3, EfficientDet-D1) is more challenging; a trend we also observed from the PTQ results in section 3.6 and discussed in the literature (Chin et al., 2020; Sheng et al., 2018a)."),
         ("Failure mode in BERT-base: a few activation tensors have extreme differences in dynamic range; to make PTQ work, these layers were identified with the debugging procedure and kept in 16 bit.",
          "Section 3.6 Experiments",
          "For BERT-base, we observe that a few activation tensors have extreme differences in their dynamic ranges."),
     ],
     "notes": "All authors are at Qualcomm AI Research (an initiative of Qualcomm Technologies, Inc.), a hardware vendor; the paper is a guide with its own pipelines rather than an independent comparison."},

    {"id": "arxiv-2210.17323",
     "title": "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers",
     "authors": ["Elias Frantar", "Saleh Ashkboos", "Torsten Hoefler", "Dan Alistarh"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2210.17323", "code": "https://github.com/IST-DASLab/gptq"},
     "tasks": ["model-compression"], "fam": LLM_PTQ, "par": ["post-hoc"],
     "proposes": ["GPTQ"],
     "claims": [
         ("Proposes GPTQ, a one-shot weight quantization method using approximate second-order information.",
          "Abstract",
          "we address this challenge, and propose GPTQ, a new one-shot weight quantization method based on approximate second-order information, that is both highly-accurate and highly-efficient."),
         ("Calibration data: 128 random 2048-token segments from C4 (generic web text); the authors say GPTQ sees no task-specific data.",
          "Experimental validation (Setup)",
          "Our entire GPTQ calibration data consists of 128 random 2048 token segments from the C4 dataset (Raffel et al., 2020), i.e., excerpts from randomly crawled websites, which represents generic text data."),
         ("Granularity: standard uniform per-row asymmetric quantization on the min-max grid (weights only).",
          "Experimental validation (Setup)",
          "We perform standard uniform per-row asymmetric quantization on the min-max grid, similar to Dettmers et al. (2022)."),
         ("Metric choice: the main evaluation uses perplexity-based language generation tasks (WikiText2, PTB, C4) because they are known to be sensitive to quantization; zero-shot tasks are a complement.",
          "Experimental validation (Language Generation)",
          "We focus on these perplexity-based tasks, as they are known to be particularly sensitive to model quantization (Yao et al., 2022)."),
         ("Evaluation caveat stated by the authors: since calibration data is sampled from the C4 training set, the C4 perplexity evaluation is not fully zero-shot.",
          "Appendix (Tables 11-12 captions)",
          "We note that the calibration data used by GPTQ is sampled from the C4 training set, this task is thus not fully zero-shot."),
         ("Limitation: speedups come from reduced memory movement, not from computational reductions; the study also does not consider activation quantization.",
          "Summary and limitations",
          "our method obtains speedups from reduced memory movement, and does not lead to computational reductions."),
         ("The authors note that the study focused on standard 'leading accuracy' metrics such as perplexity, and that a thorough study of compression's impact on secondary measures, in particular bias effects, is warranted.",
          "Ethics statement",
          "We believe a thorough study of the impact of compression upon secondary measures, and in particular bias effects (Bender et al., 2021) is warranted, and may be rendered easier through our work."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2023. Speedups reported in the abstract are measured on NVIDIA A100 and A6000 GPUs with the authors' custom kernels."},

    {"id": "arxiv-2211.10438",
     "title": "SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models",
     "authors": ["Guangxuan Xiao", "Ji Lin", "Mickael Seznec", "Hao Wu", "Julien Demouth", "Song Han"],
     "year": 2022, "version": "arXiv v7",
     "links": {"arxiv": "https://arxiv.org/abs/2211.10438", "code": "https://github.com/mit-han-lab/smoothquant"},
     "tasks": ["model-compression"], "fam": LLM_PTQ, "par": ["post-hoc"],
     "proposes": ["SmoothQuant"],
     "claims": [
         ("Proposes SmoothQuant, a training-free PTQ method for 8-bit weight and 8-bit activation (W8A8) quantization of LLMs.",
          "Abstract",
          "We propose SmoothQuant, a training-free, accuracy-preserving, and general-purpose post-training quantization (PTQ) solution to enable 8-bit weight, 8-bit activation (W8A8) quantization for LLMs."),
         ("Mechanism: activation outliers are smoothed by offline migrating quantization difficulty from activations to weights via a mathematically equivalent transformation.",
          "Abstract",
          "SmoothQuant smooths the activation outliers by offline migrating the quantization difficulty from activations to weights with a mathematically equivalent transformation."),
         ("Motivation, stated with citations to prior work (Dettmers et al. 2022; Wei et al. 2022; Bondarenko et al. 2021) rather than as a new finding: LLMs are notoriously difficult to quantize due to outliers in the activations.",
          "Review of Quantization Difficulty",
          "LLMs are notoriously difficult to quantize due to the outliers in the activations (Dettmers et al., 2022; Wei et al., 2022; Bondarenko et al., 2021)."),
         ("Calibration: smoothing factors and static quantization step sizes are calibrated once with 512 random sentences from the Pile and the same model is used for all downstream tasks.",
          "Experimental setup (Activation smoothing)",
          "To get the statistics of activations, we calibrate the smoothing factors and the static quantization step sizes once with 512 random sentences from the pre-training dataset Pile, and apply the same smoothed and quantized model for all downstream tasks."),
         ("Hyperparameter selection: the migration strength alpha is chosen by a quick grid search on a subset of the Pile validation set (the paper reports alpha = 0.5 for OPT/BLOOM and 0.75 for GLM-130B).",
          "Experimental setup (Activation smoothing)",
          "We get a suitable α by running a quick grid search on a subset of the Pile (Gao et al., 2020) validation set."),
         ("Metrics for the OPT-175B comparison (Table 3): average accuracy over 7 zero-shot benchmarks plus 1 language-modeling benchmark (perplexity).",
          "Results (Table 3 caption)",
          "We extensively benchmark the performance on 7 zero-shot benchmarks (by reporting the average accuracy) and 1 language modeling benchmark (perplexity)."),
         ("The authors state that they focus on the relative performance change before and after quantization, not on absolute values.",
          "Experimental setup (Models and datasets)",
          "Note that we focus on the relative performance change before and after quantization but not the absolute value."),
     ],
     "notes": "PDF states: Proceedings of the 40th International Conference on Machine Learning (PMLR 202, 2023). Three authors are affiliated with NVIDIA; one evaluated backend is NVIDIA's FasterTransformer, and all speed experiments are on NVIDIA A100 80GB GPU servers. GLM-130B was evaluated on a different task set because some benchmarks appear in its training set."},

    {"id": "arxiv-2306.00978",
     "title": "AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration",
     "authors": ["Ji Lin", "Jiaming Tang", "Haotian Tang", "Shang Yang", "Wei-Ming Chen", "Wei-Chen Wang", "Guangxuan Xiao", "Xingyu Dang", "Chuang Gan", "Song Han"],
     "year": 2023, "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/2306.00978", "code": "https://github.com/mit-han-lab/llm-awq"},
     "tasks": ["model-compression"], "fam": LLM_PTQ, "par": ["post-hoc"],
     "proposes": ["AWQ (activation-aware weight quantization)", "TinyChat inference framework"],
     "claims": [
         ("Proposes AWQ, a hardware-friendly method for low-bit weight-only quantization of LLMs.",
          "Abstract",
          "We propose Activation-aware Weight Quantization (AWQ), a hardware-friendly approach for LLM low-bit weight-only quantization."),
         ("Key assumption: salient weight channels should be identified from the activation distribution rather than from the weights.",
          "Abstract",
          "To identify salient weight channels, we should refer to the activation distribution, not weights."),
         ("Granularity: grouped weight-only quantization with group size 128 throughout unless otherwise specified (INT4/INT3 focus).",
          "Experiments (Settings)",
          "We used a group size of 128 throughout the work, except otherwise specified."),
         ("Calibration: a small calibration set from the Pile, chosen to avoid overfitting to a specific downstream domain.",
          "Experiments (Settings)",
          "For AWQ, we used a small calibration set from the Pile (Gao et al., 2020) dataset in order not to overfit to a specific downstream domain."),
         ("Critique of GPTQ stated by the AWQ authors in related work: GPTQ's reconstruction process overfits the calibration set and may not preserve the generalist abilities of LLMs for other modalities and domains.",
          "Related work",
          "However, the reconstruction process of GPTQ leads to an over-fitting issue to the calibration set and may not preserve the generalist abilities of LLMs for other modalities and domains."),
         ("Evaluation of instruction-tuned models uses an LLM judge: GPT-4 scores the quantized Vicuna against its FP16 counterpart on 80 sample questions, comparing both response orders because the authors found GPT-4 tends to increase the rating of the first input.",
          "Experiments (instruction-tuned models)",
          "We used the GPT-4 score to evaluate the quantized models' performance against the FP16 counterpart on 80 sample questions (Chiang et al., 2023)."),
         ("Speed measurement: TinyChat benchmarking on RTX 4090 and Jetson Orin following the exllama protocol.",
          "Speedup Evaluation",
          "We conduct benchmarking experiments on RTX 4090 and Jetson Orin following the protocol described in exllama"),
     ],
     "notes": "PDF states: Proceedings of the 7th MLSys Conference, 2024 (Best Paper Award). Some authors are affiliated with NVIDIA. BLOOM was excluded from the study as 'generally worse in quality'. arXiv v6 is dated 2026."},

    {"id": "arxiv-2305.14314",
     "title": "QLoRA: Efficient Finetuning of Quantized LLMs",
     "authors": ["Tim Dettmers", "Artidoro Pagnoni", "Ari Holtzman", "Luke Zettlemoyer"],
     "year": 2023, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2305.14314", "code": "https://github.com/artidoro/qlora"},
     "tasks": ["model-compression"], "fam": ["quantization", "large-language-models", "deep-learning"], "par": ["supervised"],
     "proposes": ["QLoRA", "4-bit NormalFloat (NF4)", "Double Quantization", "Paged Optimizers", "Guanaco models"],
     "claims": [
         ("QLoRA finetunes by backpropagating through a frozen 4-bit quantized pretrained model into LoRA adapters (the base weights are not updated).",
          "Abstract",
          "QLORA backpropagates gradients through a frozen, 4-bit quantized pretrained language model into Low Rank Adapters (LoRA)."),
         ("Assumption behind NF4: the data type is information-theoretically optimal for normally distributed weights.",
          "Abstract",
          "(a) 4-bit NormalFloat (NF4), a new data type that is information theoretically optimal for normally distributed weights"),
         ("Summary claim (GLUE / Super-NaturalInstructions and 5-shot MMLU experiments): 4-bit QLoRA with NF4 matches 16-bit full finetuning and 16-bit LoRA finetuning performance on academic benchmarks with well-established evaluation setups.",
          "QLoRA vs. Standard Finetuning (Summary)",
          "Our results consistently show that 4-bit QLORA with NF4 data type matches 16-bit full finetuning and 16-bit LoRA finetuning performance on academic benchmarks with well-established evaluation setups."),
         ("Evaluation practice: GPT-4 and human (Elo tournament) evaluations largely agree on model ranking but show instances of strong disagreement, so model-based evaluation has uncertainties.",
          "Introduction",
          "We find that GPT-4 and human evaluations largely agree on the rank of model performance in the tournaments, but we also find there are instances of strong disagreement."),
         ("The authors find that current chatbot benchmarks are not trustworthy for accurately evaluating chatbot performance levels.",
          "Abstract",
          "Furthermore, we find that current chatbot benchmarks are not trustworthy to accurately evaluate the performance levels of chatbots."),
         ("Limitation: the paper did not establish that QLoRA matches full 16-bit finetuning at 33B and 65B scales.",
          "Limitations and Discussion",
          "Despite this evidence, we did not establish that QLORA can match full 16-bit finetuning performance at 33B and 65B scales."),
         ("Limitation: other bit-precisions (e.g. 3-bit base models) and other adapter methods were not evaluated; responsible-AI (bias) evaluation is also described as limited.",
          "Limitations and Discussion",
          "An additional limitation is that we did not evaluate different bit-precisions, such as using 3-bit base models, or different adapter methods."),
     ],
     "notes": "No tag for parameter-efficient finetuning / LoRA exists; QLoRA is not quantization-aware training in the usual sense (base weights stay frozen in 4 bit), so only `quantization` is used as quantization family. PDF states: Preprint. Under review. Second code URL in the PDF: https://github.com/TimDettmers/bitsandbytes."},

    {"id": "arxiv-2212.09720",
     "title": "The case for 4-bit precision: k-bit Inference Scaling Laws",
     "authors": ["Tim Dettmers", "Luke Zettlemoyer"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2212.09720"},
     "tasks": ["model-compression"], "fam": LLM_PTQ, "par": ["post-hoc"],
     "proposes": ["k-bit inference scaling laws (model bits vs zero-shot accuracy)"],
     "claims": [
         ("Study design: more than 35,000 experiments with 16-bit inputs and k-bit (3 to 8-bit) parameters, 19M to 176B parameters, across BLOOM, OPT, NeoX/Pythia and GPT-2.",
          "Abstract",
          "We run more than 35,000 experiments with 16-bit inputs and k-bit parameters to examine which zero-shot quantization methods improve scaling for 3 to 8-bit precision at scales of 19M to 176B parameters across the LLM families BLOOM, OPT, NeoX/Pythia, and GPT-2."),
         ("Main finding: 4-bit precision is almost universally optimal for the trade-off between total model bits and zero-shot accuracy.",
          "Abstract",
          "Overall, our findings show that 4-bit precision is almost universally optimal for total model bits and zero-shot accuracy."),
         ("Metrics: perplexity on the CommonCrawl subset of the Pile and mean zero-shot performance from the EleutherAI LM Evaluation harness.",
          "Experimental setup",
          "To measure inference performance for k-bit quantization methods, we use perplexity on the CommonCrawl subset of The Pile (Gao et al., 2020) and mean zero-shot performance on the EleutherAI LM Evaluation harness (Gao et al., 2021)."),
         ("Metric sensitivity: when zero-shot accuracy is used instead of perplexity, the float data type is sometimes better (whereas quantile quantization is best by perplexity), which the authors attribute to zero-shot accuracy being noisier.",
          "Experimental setup",
          "Still, when we use zero-shot accuracy as an evaluation metric, the float data type is sometimes better because zero-shot accuracy is noisier."),
         ("Failure mode: Pythia and OPT are unstable at 3-bit, with performance close to random for the largest models.",
          "Results & Analysis",
          "Pythia and OPT are unstable for 3-bit inference where performance is close to random (35%) for the largest Pythia/OPT models."),
         ("Contrast with prior work: outlier-dependent quantization (citing Dettmers et al. 2022a and Xiao et al. 2022) improves predictive performance but is shown not to be effective for bit-level scaling.",
          "Introduction",
          "While earlier work has shown that it is possible to significantly improve the predictive performance of quantized models by using outlier-dependent quantization (Dettmers et al., 2022a; Xiao et al., 2022), we show that this is not effective for bit-level scaling."),
         ("Limitation: certain classes of quantization methods (e.g. data types optimized with additional input data) were not considered; optimized GPU implementations are also lacking.",
          "Discussion & Limitations",
          "While we ran more than 35,000 experiments, a main limitation is that we did not consider certain classes of quantization methods."),
     ],
     "notes": "The excluded 'optimized with additional input data' class cites Frantar et al. (2022), i.e. GPTQ-style one-shot methods."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): quantization; carded by a subagent. Results tables not recorded; claims only.")
