import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_cpd_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1806.02261",
     "title": "Doubly Robust Bayesian Inference for Non-Stationary Streaming Data with β-Divergences",
     "authors": ["Jeremias Knoblauch", "Jack Jewson", "Theodoros Damoulas"],
     "year": 2018, "venue": "NeurIPS 2018", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1806.02261", "code": "https://github.com/alan-turing-institute/rbocpdms/"},
     "tasks": ["online-change-point-detection"],
     "fam": ["bayesian-changepoint-models", "linear-models"], "par": ["streaming"],
     "proposes": ["Robust BOCPD (β-BOCD): BOCPD in which both the run-length/model posterior and the parameter posterior are replaced by General Bayesian Inference posteriors based on the β-divergence (β = (β_rlm, β_p)), demonstrated on Bayesian linear regression and (spatially structured) vector autoregressions",
                  "A structural variational approximation of the β-divergence posterior within the conjugate family (exact as β → 0), optimized inside BOCPD with a stochastic variance reduced gradient scheme with constant space and linear time",
                  "A procedure to initialize β_p (maximizing the β-divergence influence at a chosen Mahalanobis distance) and to refine β on-line by SGD on a predictive loss"],
     "claims": [
         ("Motivation: BOCPD methods declare changepoints when the posterior predictive has low density for the next observation, which the authors say naturally leads to a high false changepoint discovery rate under outliers; because they run on-line, pre-processing (outlier removal) is not an option. Standard Bayes (KLD) is not robust under outliers or misspecification because its influence function is strictly increasing.",
          "Introduction",
          "Naturally, this leads to a high false CP discovery rate in the presence of outliers and as they run on-line, pre-processing is not an option."),
         ("Robust BOCPD: both the run-length/model posterior and the parameter posteriors are replaced by β-divergence posteriors with β = (β_rlm, β_p) > 0. β_rlm prevents abrupt changes of the run-length posterior caused by a small number of observations; for the run-length part one simply replaces the predictive densities in the BOCPD recursion by their β-D counterparts, and the discrete posterior remains easy to normalize. β_p regulates the robustness of the parameter posterior, which is intractable and is handled by structural variational inference.",
          "Robust BOCPD",
          "This form of robustness is easy to implement and retains the closed forms of BOCPD:"),
         ("Why heavy tails are not enough: the run-length odds after an outlier compare the predictive density under the current segment with the density under the prior; a Student's t error model raises both, so changing the tails has only a very limited effect on the ratio. The authors state the perhaps unintuitive consequence that Student's t error models yield changepoint inference very close to the normal model (numerical examples in the appendix).",
          "Section 2.3 (Quantifying robustness)",
          "In fact, the perhaps unintuitive consequence is that Student’s t error models will yield CP inference that very closely resembles that of the corresponding normal model."),
         ("Theorem 1 (for the Bayesian linear regression model): β_rlm and the hazard can be chosen from a set (defined by an inequality in the appendix) so that the odds never favour a changepoint after any single outlying observation. It requires a lower bound |V|_min > 0 on the determinant of the posterior predictive variance, because the integral term of the β-D loss dominates if |V| is extremely small; the authors say this is not restrictive in practice.",
          "Section 2.3 (Quantifying robustness)",
          "Theorem 1 provides very mild conditions for the β-D robustiﬁed BLR model ensuring that the odds never favor a CP after any single outlying observation"),
         ("Computation: sampling-based General Bayesian inference would make the algorithm on-line in name only and add three sources of approximation error per (run length, model) and time step, so the β-D posterior is approximated within the conjugate family by structural variational inference (exact as β → 0). Full optimization of the variational parameters at every step costs O(T) space and O(T^2) time; the proposed SVRG variant (full optimization every m steps for the first W iterations of a run length, then anchored stochastic updates on a window) has constant space and linear time.",
          "Stochastic Variance Reduced Gradient (SVRG) for BOCPD",
          "The resulting on-line inference has constant space and linear time complexity like SGD, but produces good estimates for small rt and converges faster"),
         ("Choosing β: the authors note there was no principled framework for selecting β. β_p is initialized by solving for the β_p whose point of maximum influence lies at a chosen Mahalanobis distance under the prior (k-th standard deviation for low dimensions, sqrt(d) for larger d); β_rlm initialization matters less (values in [0, 1] give reasonable results). β is then refined on-line by SGD on a predictive loss (a bounded absolute loss in the experiments), with the gradient for β_p approximated numerically. Because the losses need not be convex in β_p, initial values can matter.",
          "Section 4 (Choice of β)",
          "We remedy this by minimizing the expected predictive loss with respect to β on-line."),
         ("Well-log (univariate benchmark whose outliers are usually removed before running CP detection): the maximum of the standard BOCPD run-length distribution is zero 145 times, so declaring CPs at the run-length maximum gives a false discovery rate > 90%; with MAP segmentation standard BOCPD mislabels 8 outliers as CPs (FDR > 40%), whereas the β-D version mislabels none. The robust version has more computational overhead but needs less than 0.5 seconds per observation (3.1 GHz Intel i7, 16GB RAM).",
          "Section 5 (Well-log)",
          "Even using Maximum A Posteriori (MAP) segmentation [11], standard BOCPD mislabels 8 outliers"),
         ("Protocol caveat for the well-log comparison: standard and robust BOCPD were run with different priors. Because of Theorem 1 the robust version can use a much less informative prior; for the standard version a more informative prior (constant hazard 0.01) was used, because with too flat priors it declares far too many changepoints.",
          "Appendix I.1 (Well-log data)",
          "If priors are too ﬂat, the standard version declares far too many changepoints."),
         ("Air pollution (NOX at 29 London stations, spatially structured Bayesian VARs; earlier robust on-line methods cannot be applied because they assume univariate or independent data): robust BOCPD finds one CP corresponding to the congestion charge introduction while standard BOCPD has FDR > 90%. Both find a change in dynamics (models) after the congestion charge, with substantially lower model-posterior variance for the robust algorithm.",
          "Section 5.2 (Air Pollution)",
          "As Figure 5 shows, robust BOCPD ﬁnds one CP corresponding to the introduction of the congestion charge, while standard BOCPD produces an FDR >90%."),
     ],
     "notes": "Affiliations: The Alan Turing Institute; University of Warwick. Venue from the arXiv journal_ref (NeurIPS 2018); the PDF footer reads '32nd Conference on Neural Information Processing Systems (NIPS 2018), Montréal, Canada.' Section numbers 2.3, 3.1, 4, 5 and 5.2 are confirmed by cross-references in the text ('see section 2.3', 'Section 3.1 overcomes', 'Section 4 expands on how β can be initialized', 'see section 5.2'); other locations use heading names. Both experiments also use on-line hyperparameter optimization (Caron et al.) and run-length pruning (50 most likely run lengths kept). The air-pollution baseline results come from the authors' own earlier work (Knoblauch & Damoulas 2018, ref [25]). Changepoints are declared from the run-length maximum or a MAP segmentation; no annotated ground-truth CPs beyond the congestion-charge date are used, and FDR is judged by outlier mislabelling. Appendix I.3: β_p barely moves on the well-log data, while on air pollution it jumps to ~1e-10 after the first iteration (explained by a numerical-stability lower bound). Sampling-free (Student's t) comparison and MCMC timing are in the appendix (not recorded). Section 3.1 notes β_p must decrease as d increases (initialized at 0.05 for d = 1 and 0.005 for d = 29 in the experiments). Appendix I: inference reported fairly stable to the β_p initialization as long as it is chosen reasonably (air pollution: same CP within ±5 days for initial β_p 0.005-0.1). Appendix I.2: the non-robust air-pollution baseline uses more than 20 models with lags 1, 5, 6, 7 versus lags 1-3 for the robust run (chosen, per the authors, to disadvantage the robust model universe); robust processing mostly takes well under 20 s per observation but sometimes over a minute."},

    {"id": "arxiv-2302.04759",
     "title": "Robust and Scalable Bayesian Online Changepoint Detection",
     "authors": ["Matias Altamirano", "François-Xavier Briol", "Jeremias Knoblauch"],
     "year": 2023, "venue": "ICML 2023", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2302.04759", "code": "https://github.com/maltamiranomontero/DSM-bocd"},
     "tasks": ["online-change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["streaming"],
     "proposes": ["Dm-BOCD: BOCPD whose segment parameter posterior is a generalised Bayesian posterior based on diffusion score matching with a weighting matrix m; for natural exponential families with a squared exponential prior it is conjugate (a (truncated) normal), updated exactly in O(p^2 + d^2) per run length",
                  "A choice of the diffusion matrix m that makes the posterior globally bias-robust, and a choice of the learning rate ω by matching (in KL) the generalised posterior to the standard Bayes posterior on the first t* observations"],
     "claims": [
         ("Motivation: BOCD inherits from Bayesian inference a lack of robustness to outliers or model misspecification, which can lead to failures where most points inferred to be CPs are simply mild heterogeneities in the data (Figure 1: standard BOCD flags the Twitter flash-crash blip in the DJIA as a CP, Dm-BOCD does not).",
          "Introduction",
          "This can lead to failures, where most data points inferred to be CPs are simply mild heterogeneities in the data."),
         ("Critique of β-BOCD (Knoblauch et al., 2018, which shares the last author): the β-divergence loss contains an integral that is intractable unless available in closed form; β enters as the exponent of a likelihood, which makes the loss extremely sensitive to very small changes in β and hence very difficult to tune; and the posteriors often need variational approximations for every run length at every step, which the authors say often renders it computationally infeasible, especially in high dimensions.",
          "Section 2.3",
          "Numerically, this makes the loss extremely sensitive to even very minor changes in β, which makes it very difﬁcult to tune β and counteracts the very robustness one hopes to achieve."),
         ("Scalability: for natural-form exponential family likelihoods with a squared exponential prior the diffusion-score-matching posterior is a (truncated) normal whose parameters are updated exactly by adding terms per observation; with the Sherman-Morrison formula each update costs O(p^2 + d^2), which the authors say is also the complexity of standard BOCD with a Gaussian likelihood and conjugate prior.",
          "Section 3.4",
          "This is also the complexity of standard BOCD with the Gaussian likelihood and conjugate prior (Adams & MacKay, 2007)."),
         ("Robustness guarantee and its conditions: Proposition 3.2 gives a diffusion matrix m (depending on a fixed θ* ≠ 0, not on θ) that makes the posterior globally bias-robust when η(θ) = θ and ∇b = 0 with a squared exponential prior. The authors note this m applies only to models with support R^d unless additional boundary conditions hold (appendix shows it also works for some distributions on subsets, e.g. Gamma and exponential).",
          "Section 3.3",
          "Note also that m is only applicable to models with support X = Rd, as the expansion in (3) is otherwise not valid without additional boundary conditions."),
         ("Choice of θ*: the authors found Dm-BOCD not very sensitive to θ*, likely because tuning ω offsets any sensitivity; in all experiments θ* was set to the maximum likelihood estimate computed on the full data set (i.e. using the whole stream, not only past data).",
          "Section 3.4 (Choice of m)",
          "In all experiments, we thus picked θ⋆as the maximum likelihood estimate computed on the full data set."),
         ("Choice of the learning rate ω: existing methods are computationally expensive and asymptotically motivated, so ω* minimizes the KL divergence between the Dm-posterior and the standard Bayes posterior on the first t* observations (computed with automatic differentiation in jax). The authors say this yields reasonable uncertainty quantification if misspecification is mild at the beginning of the stream.",
          "Section 3.4 (Choice of ω)",
          "we match the uncertainty of the generalised posterior to that of its standard counterpart on the ﬁrst t⋆observations of the data stream."),
         ("Detection latency hedge: the authors note a known issue of robust CP methods is latency in detecting actual CPs, and say this is not something they observe in their experiments with their choice of m and θ*.",
          "Section 3.4 (Choice of m)",
          "known issue with robust CP detection method is that they can experience a latency when it comes to detecting actual CPs."),
         ("Accuracy/delay protocol: synthetic data with 600 samples, 2% outliers and 6 CPs, 10 realisations varying the outlier positions; PPV, TPR and detection delay are reported for Dm-BOCD and standard BOCD only. A detection counts as a true positive if it lies in a small neighbourhood of the true CP; no numeric tolerance was found in the text (searched for neighbourhood, margin, tolerance). No hazard (changepoint prior) value was found in the text (searched for hazard, CP prior).",
          "Appendix C.3",
          "We say the method detects a TP changepoint when the changepoint detected for the method is in a small neighbourhood of the true CP."),
         ("Well-log segmentation figure (appendix): the caption states that Dm-BOCD is more robust to outliers than standard BOCD but more sensitive than β-BOCD.",
          "Appendix C (Figure 13 caption)",
          "We observe that our method is more robust to outliers than the standard BOCD, but is more sensitive than β-BOCD."),
     ],
     "notes": "Affiliations: University College London; The Alan Turing Institute. Venue from the PDF first page ('Proceedings of the 40th International Conference on Machine Learning, Honolulu, Hawaii, USA. PMLR 202, 2023'); the arXiv record has no comment. Conflict of interest: the last author (Knoblauch) is the first author of β-BOCD (arXiv 1806.02261), the main robust baseline. Section numbers are confirmed by numbered headings in the PDF. Real-data examples (Twitter flash crash DJIA, FTT/Bitcoin crypto crash, well-log, UK 10-year bond yield) are evaluated visually against known events/outliers without numeric metrics; the multivariate synthetic (exponential + Gaussian) and gamma-modelled bond-yield examples are cases where standard Bayes is not conjugate, so no BOCD comparison is made. Appendix C.2: Dm-BOCD with m = identity (unweighted score matching) also labels outliers as CPs; with k = 1 run length kept no CP is detected. Changepoints are reported as MAP segmentations. Run-length pruning keeps the k = 50 most probable run lengths in all experiments. ω* was selected on the first 50 (Twitter flash crash), 200 (well-log) and 100 (UK bond yield) observations; ω was fixed manually for the crypto crash (0.01) and the multivariate synthetic data (0.15). Section 4: on the well-log data the detected changes are almost identical to β-BOCD and Dm-BOCD took about 10 times less time; Appendix C.1: standard BOCD is faster than Dm-BOCD when sampling is needed, while Dm-BOCD is considerably faster than β-BOCD. Table values not recorded."},

    {"id": "arxiv-1302.3721",
     "title": "Thompson Sampling in Switching Environments with Bayesian Online Change Point Detection",
     "authors": ["Joseph Mellor", "Jonathan Shapiro"],
     "year": 2013, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1302.3721"},
     "tasks": ["online-change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["reinforcement-learning"],
     "proposes": ["Change-Point Thompson Sampling (CTS): Thompson sampling for switching Bernoulli multi-armed bandits that samples a run length from a BOCPD run-length posterior and then samples arm parameters from Beta posteriors using only the data since that change point; variants for Global and Per-Arm switching, known or learned (Wilson et al.) constant switching rate, and tracking only the pulled/best arm ('2' variants)"],
     "claims": [
         ("Environment model: rewards are Bernoulli and switch abruptly according to a hazard function (new means drawn uniformly); two models are considered: Global Switching (all arms change at a change point, constant rate) and Per-Arm Switching (independent change points per arm).",
          "Model of Dynamic Environment",
          "We assume abrupt switching deﬁned by a hazard function, h(t), such that,"),
         ("Switching Thompson sampling: since the arm model depends only on data since the last switch and that time is unknown, the run length is introduced as a latent variable and marginalised; sampling proceeds by drawing a run length from the run-length posterior and then arm parameters given that run length, and pulling the arm that is best under the sample.",
          "Switching Thompson Sampling",
          "Since we do not know the runlength rt we can introduce it as a latent variable and marginalise it out."),
         ("Cost: exact run-length inference has space and time growing linearly in time; instead of Adams-MacKay thresholding (memory known only in expectation) the paper uses Fearnhead and Liu's particle-filter resampling (stratified optimal resampling) to keep at most N run lengths, for a hard memory bound. The hazard is a constant switching rate γ in the basic algorithms.",
          "Bayesian Online Change Detection",
          "As we can only know in expectation how much memory this algorithm will require, an alternative with hard guarantees on memory requirements is desirable."),
         ("Learning the switching rate: a constant switching rate is learned with the method of Wilson et al. (Beta hyperparameters counting switches); the authors note Turner et al.'s gradient-based hazard learning appeared, in initial investigations, not to perform particularly well when adapted every step. Learning the rate makes the number of particles grow quadratically rather than linearly.",
          "Learning the Switching Rate",
          "For the purposes of this paper, a constant switching rate was assumed which was learned using the approach of Wilson et al."),
         ("Evaluation protocol: 6 non-stationary environments (4 synthetic, 2 derived from real-world data). The parameters for all experiments were tuned on the PASCAL challenge (the PASCAL Exploration vs. Exploitation Challenge 2006 is itself one of the evaluation environments).",
          "Experiments",
          "The parameters for all experiments shown were tuned based on the PASCAL challenge."),
         ("In the Per-Arm switching environment the hazard-learning variant NP PA-CTS suffers much more regret than PA-CTS, which the authors say would appear to indicate that the parameters are not learned quickly enough; in the Global environment NP Global-CTS does well, which they say suggests learning the hazard rate for that model may be feasible.",
          "Per-Arm Switching Environment",
          "which would appear to indicate for the particular model the parameters are not being learned quickly enough."),
         ("PASCAL 2006 comparison caveat: the authors could not implement a version of Adapt-EvE (the change-point-based challenge winner) that replicated the reported performance, so Adapt-EvE results are copied from the publication, and Adapt-EvE was not run in the other environments to avoid an unfair comparison.",
          "PASCAL Challenge 2006",
          "so here we are simply replicating the results published."),
         ("Conclusion: the CTS algorithms perform well in the environments they were designed for, but are shown not to perform as well as appropriately tuned competing algorithms in the PASCAL challenge; the results suggest that tracking only changes in the perceived best arm (Global-CTS2, PA-CTS2), similar to Adapt-EvE, works well.",
          "Conclusion",
          "However our results suggest that a strategy that just tracks changes in the perceived best arm (Global-CTS2,PA-CTS2), similar to Adapt-EvE, works well."),
         ("No regret guarantee: the authors state the algorithms are derived from simple models and theoretically motivated, but steps still need to be taken to provide any theoretical justification for their performance.",
          "Conclusion",
          "however steps still need to be taken to provide any theoretic justiﬁcation for their performance."),
     ],
     "notes": "Affiliation: University of Manchester. No venue recorded: the PDF text does not mention AISTATS (searched); per the arXiv comment, a version appeared at AISTATS 2013. Section headings in the extracted text carry no numbers, so locations use heading names. Real-data environments: Yahoo! Front Page click log reduced to a non-contextual 5-article bandit (click-through rates estimated every 1000 ticks, replay as in Li et al. 2011, regret normalised by number of pulls) and a foreign-exchange 2-armed bandit (GBP-USD, USD-JPY, NZD-CHF, EUR-CAD; predict up/down over 100 ticks), where the true payoff is unknown so error rather than regret is reported. Baselines: UCB, DiscountedUCB (Jaksch's PASCAL submission), Random, and published Adapt-EvE results. The hazard definition in the extracted text appears to swap the probabilities (θ unchanged 'with probability h(t)'); not interpreted here. Experiments mostly report the expected number of suboptimal arm pulls; synthetic runs use 10^6 steps (rendered '106' in the extracted text) repeated 100 times. The authors note the PASCAL environments were found to be periodic, which their algorithms were not intended for. Results tables not recorded."},

    {"id": "arxiv-2304.00232",
     "title": "Restarted Bayesian Online Change-point Detection for Non-Stationary Markov Decision Processes",
     "authors": ["Reda Alami", "Mohammed Mahfoud", "Eric Moulines"],
     "year": 2023, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2304.00232"},
     "tasks": ["online-change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["reinforcement-learning"],
     "proposes": ["An extension of Restarted BOCPD (R-BOCPD, Alami et al. 2020) from Bernoulli to multinomial observation streams, with false-alarm and detection-delay guarantees",
                  "R-BOCPD-UCRL2: UCRL2 equipped with one R-BOCPD detector per state-action pair that restarts UCRL2 when a change is detected, with a finite-time regret bound for piecewise-stationary (switching) MDPs"],
     "claims": [
         ("Setting and assumptions: a piecewise-stationary discrete-time MDP whose transition distributions and rewards can change arbitrarily at unknown times (no variation budget); state and action sets are finite and constant; transitions are multinomial; rewards are bounded; and change points are exogenous, i.e. do not depend on the algorithm's behaviour or history.",
          "Section 3 (Problem Formulation)",
          "We assume neither the change-points nor the changes in reward distributions and state transition distributions depend on the previous behavior of the algorithm or the ﬁltration of the MDP parameter history"),
         ("R-BOCPD is not the run-length recursion of standard BOCPD: following Alami et al. (2020), it maintains weights of 'forecasters' (products of Laplace predictors, here extended to multinomial data with a uniform prior) and restarts when some later forecaster's weight exceeds the weight of the forecaster started at the last restart; the last restart time is the change-point estimate.",
          "Change-point detection as remedy to non-stationarity",
          "Recall that in the work of Alami et al. (2020), instead of dealing with a run-length, they deal with the notion of forecaster that is a product of successive Laplace predictors."),
         ("Guarantees for multinomial R-BOCPD: a lower bound on detection delay for any detector with controlled false-alarm rate (Theorem 4.3); false-alarm control with probability 1 - δ if the hyperparameter η_{r,s,t} is small enough (Theorem 4.6); and finite detection delay if η is large enough (Theorem 4.8). Asymptotically (long time since the last restart, δ → 0) the delay is of order log(1/δ) / KL between pre- and post-change distributions, which the authors call asymptotically order optimal.",
          "Change-point detection as remedy to non-stationarity",
          "In this section, we provide sufﬁcient conditions on the parameter ηr,s,t that guarantee the false alarm rate control"),
         ("Hyperparameter: η_{r,s,t} must satisfy both conditions at once; the paper states a choice of η as a function of n_{r:t} that satisfies both (the exact form is lost in the text extraction; it appears to be 1/n_{r:t}). No statement of the η value used in the experiments was found in the text (searched Appendix F for η and hyperparameter).",
          "Change-point detection as remedy to non-stationarity (Discussion 4.10)",
          "In order to guarantee the false alarm rate and detection delay, we need to choose an appropriate form of the parameter ηr,s,t that satisﬁes both conditions in Equation (7) and Equation (6)."),
         ("Asymptotic regret bound: the derivation of Corollary 4.13 (from the finite-time bound of Theorem 4.12, a UCRL2-type term plus the sum of R-BOCPD detection delays, using the asymptotic detection delay) holds with probability at least 1 - δ and assumes a false-alarm rate of 0.",
          "Appendix E.4",
          "which again holds with probability at least 1 −δ, assuming a false-alarm rate of 0."),
         ("Empirical claim: on synthetic switching MDPs (results shown only as cumulative-reward curves) R-BOCPD-UCRL2 is described as (nearly) regret-optimal in practice, close to an oracle UCRL2 that restarts exactly at the true change points; baselines are SWUCRL2, SWUCRL2-CW, Restarted-UCRL2 (which assumes the number of changes is known) and vanilla UCRL2.",
          "Section 5 (Experiments)",
          "Figure 2 shows that R-BOCPD-UCRL2 is (nearly) regret-optimal in practice, as its performance in the deﬁned general setting is very close to that of the change-point aware (optimal) UCRL2 Oracle."),
         ("Baseline tuning: SWUCRL2's window uses the theoretically optimal formula, with the MDP diameter chosen by a hyperparameter search over a large range for each state/action size, keeping the value that maximized cumulative rewards; SWUCRL2-CW's window and widening factor use the optimal formulas with the variation budgets computed beforehand and the true horizon T supplied.",
          "Appendix F.1",
          "The diameter maximizing the cumulative rewards was chosen."),
         ("No realistic environments: the authors are interested in settings such as RiverSwim, MachineReplacement and GridWorld but say it is unclear how to simulate changes there because the underlying transition distributions and rewards are not accessible.",
          "Appendix F.2.1",
          "it is unclear to us at the moment of writing this manuscript how to control the process of changing these variables and relate it to the rather latent changes in the underlying state-transition distributions and rewards."),
         ("Stated limitations: the multinomial assumption (the authors say the detector and its guarantees extend to exponential-family streams) and a bias towards detecting change points where distributions change radically (large variation); they suggest a threshold to decide when to restart given global/local changes, and model-free extensions, as future work.",
          "Discussion & Overall Remarks (Limitations and Future Work)",
          "Next, we highlight that our algorithm is biased towards detecting change-points around which distributions change in a rather radical way, i.e with large enough variation in the sense of a total variation norm for instance."),
     ],
     "notes": "Affiliations: Technology Innovation Institute (Abu Dhabi); Technical University of Munich; Ecole Polytechnique. First two authors contributed equally. The PDF header says 'Preprint.' and code is promised 'upon publication'; no venue recorded. R-BOCPD itself comes from Alami, Maillard and Feraud (ICML 2020 per the reference list), the first author's earlier work. Section 3 and Section 5 are confirmed by cross-references ('as defined in Section 3', 'in Section 5'); other locations use heading names or theorem/appendix labels. The abstract and conclusion claim the regret bound is the first of order Õ(T^{1/2}) and compare it with sliding-window and restart baselines; the exponents are garbled in the text extraction, so these comparisons are not recorded. Abrupt changes of arbitrary magnitude are allowed, but the bound depends on the minimum KL between successive transition kernels. Note the asymmetric tuning: baselines receive searched/oracle quantities (diameter, variation budgets, T, number of changes) while the paper says R-BOCPD-UCRL2 needs no such inputs. In Algorithm 2 one R-BOCPD runs per state-action pair on the observed state sequence and a detection resets all UCRL2 counts. Synthetic MDPs: 4 sizes (4 states/7 actions to 16 states/20 actions), random change points, horizon T = 50000, 100 realizations."},

    {"id": "arxiv-2405.09330",
     "title": "BARO: Robust Root Cause Analysis for Microservices via Multivariate Bayesian Online Change Point Detection",
     "authors": ["Luan Pham", "Huong Ha", "Hongyu Zhang"],
     "year": 2024, "venue": "FSE 2024", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2405.09330", "doi": "https://doi.org/10.1145/3660805", "code": "https://github.com/phamquiluan/baro"},
     "tasks": ["time-series-anomaly-detection", "online-change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["unsupervised"],
     "proposes": ["BARO: an end-to-end anomaly detection and root cause analysis pipeline for microservices that detects the failure time with Multivariate BOCPD (Adams-MacKay BOCPD with the multivariate Gaussian / inverse-Wishart segment likelihood of Xuan & Murphy) on Latency and Errors metrics, then ranks root-cause metrics with RobustScorer",
                  "RobustScorer: ranks each metric by the maximum post-detection deviation |x - median| / IQR, with median and IQR learned from data before the detected anomaly time"],
     "claims": [
         ("Motivation: many metric-based RCA methods assume an accurate anomaly detection module (e.g. CIRCA and RCD require the failure occurrence time) and treat that information as accurately known, so it remains unclear whether they stay effective when combined with imprecise anomaly detectors.",
          "Introduction",
          "However, they assume this information is already known accurately."),
         ("Detector design: Multivariate BOCPD combines BOCPD (Adams & MacKay) with the multivariate change point model of Xuan & Murphy to model dependency among metrics. The authors motivate BOCPD as simple, effective, requiring no user-specified thresholds for univariate series, and citing van den Burg & Williams as among the best CPD methods in many real-world scenarios.",
          "Section 3.3",
          "We then propose to use Multivariate BOCPD, a combination of BOCPD [22] and MultivariateCPD [75], to model the dependency and correlation among metrics to detect anomalies effectively."),
         ("Decision rule: at each step the most probable run length is taken and change points are the steps where it decreases (Algorithm 1: s_t <= s_{t-1}); only Latency and Errors metrics are used for detection, and only the first detected change point is output as the anomaly (failure occurrence time); later change points are attributed to failure propagation.",
          "Section 3.3",
          "Finally, note that following the assumptions in Section 3.1, we use Latency and Errors to detect anomalies, and we only output the first detected change point as the detected anomaly."),
         ("Assumption: based on the failure propagation chain, the first detected anomaly is assumed to correspond to the time the failure first occurs and is used to split normal and abnormal data (not to identify the root cause). The paper also assumes anomalies are visible in Latency/Errors, so Traffic or Saturation surges without abnormal Latency/Errors are treated as normal.",
          "Section 3.1.2 (Failure Propagation Chain)",
          "In this work, based on this failure propagation chain, we assume the first anomaly corresponds to the time when the failure first occurs."),
         ("RobustScorer: median and IQR are learned from data before the detected time and each metric is scored by its maximum robust deviation afterwards; the hypothesis-testing view is used only for ranking, not for accept/reject decisions by p-value. The authors argue median/IQR make the ranking less sensitive than mean/standard-deviation (z-score) methods to early or late detection times.",
          "Section 3.4",
          "Note that we do not use the p-value to reject/accept a possible root cause as in standard hypothesis testing."),
         ("Data: four injected faults (CPU hog, memory leak, network delay, packet loss) into five target services per system, each combination repeated five times, giving 100 failure cases per benchmark system.",
          "Section 4 (Benchmark Microservice Systems & Data Collection)",
          "For each combination of fault type and targeted service, we repeat the operation (i.e. fault injection and metrics data collection) five times, resulting in 100 failure cases for each benchmark microservice system."),
         ("Anomaly detection baselines: N-Sigma, BIRCH, SPOT (dSPOT) and univariate offline Bayesian change point detection (via a third-party implementation), all run with hyperparameter settings from previous works and public code; no description of how BARO's own BOCPD hazard or prior values were chosen was found in the text (searched hazard, lambda, hyperparameter).",
          "Section 4.4 (Baselines)",
          "For all methods, we use the hyperparameter settings as in previous works and in their public source code."),
         ("RCA comparison caveat: CIRCA uses a PC-algorithm causal graph instead of its required call graph, which the authors say could explain why N-Sigma outperforms CIRCA.",
          "RQ2: Effectiveness in Root Cause Analysis",
          "Note that, in this work, as discussed, for CIRCA, we use the causal graphs constructed by the PC algorithm instead of the required call graphs as these graphs are not available for these systems, which could be a cause of this observation."),
         ("Threats to validity: only four fault types are used; each system uses a single deployment setting and a single data collection strategy, which the authors say potentially limits generality; BARO relies on the Section 3.1 assumptions and extending it to other system types (e.g. distributed databases) is future work.",
          "Threats to Validity",
          "In this paper, we employ a single deployment setting for each microservice system and a single data collection strategy, which potentially limits the generality of our work."),
     ],
     "notes": "Affiliations: RMIT University; Chongqing University. Venue from the arXiv comment ('accepted to FSE'24') and the PDF (Proc. ACM Softw. Eng. 1, FSE, Article 98, July 2024; DOI 10.1145/3660805). Section numbers (2.3, 3.1, 3.1.2, 3.3, 3.4, 3.4.2, 4, 4.4) are confirmed by cross-references in the text. The BOCPD variant is standard Adams-MacKay BOCPD with a multivariate Gaussian/inverse-Wishart segment marginal likelihood; it is applied to a fixed T-length window of collected metrics (Algorithm 1), so detection is evaluated retrospectively per case rather than as streaming delay/false-alarm rates. The coarse-grained RCA text says BARO achieves the highest Avg@5 in 10 of 15 (fault type x system) cells while also describing it as consistently top; for fine-grained RCA it 'ranks among the top performers' rather than best everywhere. RQ4 varies the detection time by ±40 around injection on Online Boutique and Sock Shop and varies baseline hyperparameters (BARO's BOCPD parameters are not varied). Datasets and code released (Zenodo). Segment model: zero-mean multivariate Gaussian with an inverse-Wishart prior whose scale uses the mean empirical variance pooled across all metrics (data-dependent prior); hazard is geometric, value not stated. Systems: Online Boutique (12 services), Sock Shop (11), Train Ticket (64) on a 5-worker Kubernetes cluster, restarted after each injection; injection-to-symptom gap usually 1-3 s by visual inspection, and the fault injection time is used as a proxy for the true anomaly time. Anomaly detection is scored per case as binary classification (pre-injection data normal, during-injection abnormal; Precision/Recall/F1 averaged over cases). RCA baselines use hyperparameters from their papers; ε-Diagnosis uses a third-party implementation. Table footnotes: CIRCA on Train Ticket from only 15/100 cases (PC failed), BIRCH-based RCA only on cases BIRCH detected. Results tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
