import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1810.03548",
     "title": "Meta-Learning: A Survey",
     "authors": ["Joaquin Vanschoren"],
     "year": 2018, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1810.03548"},
     "tasks": ["model-selection"],
     "fam": ["automl-systems"], "par": ["meta-learning"],
     "proposes": ["Survey of meta-learning organized by the type of meta-data used: learning from prior model evaluations (task-independent recommendations, portfolios/rankings, configuration-space design, configuration transfer, learning curves), learning from task properties (meta-features, learned meta-features, warm-starting, meta-models for ranking and performance prediction, pipeline synthesis, whether to tune), and learning from prior models (transfer, meta-learning in neural networks, few-shot learning)"],
     "claims": [
         ("Framing: meta-learning observes how different ML approaches perform on a wide range of tasks and learns from this meta-data to learn new tasks faster; the Introduction then categorizes techniques by the type of meta-data they leverage (model evaluations, task properties, prior models).",
          "Abstract",
          "Meta-learning, or learning to learn, is the science of systematically observing how diﬀerent machine learning approaches perform on a wide range of learning tasks, and then learning from this experience, or meta-data, to learn new tasks much faster than otherwise possible."),
         ("Caveat (no free lunch): the more similar previous tasks are, the more meta-data can be leveraged, and defining task similarity is called a key overarching challenge; when a new task is unrelated or random noise, leveraging prior experience will not be effective.",
          "Introduction",
          "When a new task represents completely unrelated phenomena, or random noise, leveraging prior experience will not be eﬀective."),
         ("Per-set (task-independent) recommendation, as described by the survey with citations to prior work: without evaluations on the new task, a candidate set of configurations (a portfolio) is evaluated on many prior tasks, ranked per task and aggregated into a global ranking (e.g. average rank, citing Lin 2010 and Abdulrahman et al. 2018); a simple anytime method (citing Brazdil et al. 2003a) then evaluates the top-K on the new task in turn.",
          "Task-Independent Recommendations",
          "This is typically done by discretizing Θ into a set of candidate conﬁgurations θi, also called a portfolio, evaluated on a large number of tasks tj."),
         ("Meta-feature caveat (citing Bilalli et al., 2017): studies on OpenML meta-data showed the optimal set of meta-features depends on the application; meta-features need aggregation, normalization and feature selection or dimensionality reduction when computing task similarity.",
          "Meta-Features",
          "Studies on OpenML meta-data have shown that the optimal set of meta-features depends on the application (Bilalli et al., 2017)."),
         ("Meta-models for algorithm selection (prior work, citing Kalousis and Hilario 2001 and Kopf and Iglezakis 2002): those experiments showed boosted and bagged trees often gave the best meta-model predictions, although much depends on the exact meta-features used.",
          "Meta-Models",
          "Experiments showed that boosted and bagged trees often yielded the best predictions, although much depends on the exact meta-features used"),
         ("Meta-features versus observations on the new task: the survey states (citing Feurer et al. 2018b, Wistuba et al. 2018, Leite et al. 2012) that, rather than combining per-task predictions by meta-feature similarity, it is ultimately more effective to gather new evaluations on the new task, which refine the task-similarity estimates.",
          "Performance Prediction",
          "While meta-features could also be used to combine per-task predictions based on task similarity, it is ultimately more eﬀective to gather new observations Pi,new, since these allow to reﬁne the task similarity estimates with every new observation"),
     ],
     "notes": "Book-chapter-style survey (the text calls itself 'this chapter'); no experiments of its own. Affiliation: Eindhoven University of Technology; the reference list shows the author is a co-author of OpenML (Vanschoren et al., 2014), which the survey cites as a meta-data repository and source of meta-data. Scope is per-task (per-dataset) selection and configuration; per-instance selection, Rice's framework, the virtual best solver / oracle gap and evaluation pitfalls of selectors were not found in the text (searched 'Rice', 'oracle', 'virtual best'). The survey also describes meta-models proposed to predict whether tuning is worthwhile ('To Tune or Not to Tune?' section, citing Ridd and Giraud-Carrier 2014 and Sanders and Giraud-Carrier 2017) and that multi-objective rankings including training time converge to near-optimal models faster in time-constrained settings (citing Abdulrahman et al. 2018, van Rijn et al. 2015). Tag note: automl-systems is an approximation (the survey covers meta-learning used to warm-start and configure AutoML, not one AutoML system)."},

    {"id": "arxiv-1210.7959",
     "title": "Algorithm Selection for Combinatorial Search Problems: A Survey",
     "authors": ["Lars Kotthoff"],
     "year": 2012, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1210.7959"},
     "tasks": ["model-selection", "combinatorial-optimization"],
     "fam": ["dynamic-ensemble-selection"], "par": ["meta-learning"],
     "proposes": ["Survey of the Algorithm Selection Problem (selecting the best algorithm per problem instance, after Rice 1976) for combinatorial search problems (SAT, constraints, planning, QBF, scheduling), organized by what to select from (static/dynamic portfolios), what and when to select (single algorithm vs schedules; offline vs online), how to select (performance models, types of predictions) and features (low/high-knowledge, static/dynamic/probing, feature selection)"],
     "claims": [
         ("Framework (Rice 1976, as summarized by the survey): given a problem space and an algorithm space, map each problem-algorithm pair to its performance and use the mapping to select the best algorithm; Rice's refined model adds problem features, which the survey calls the crucial difference that often makes an approach feasible.",
          "Introduction",
          "The basic model described in the paper is very simple – given a space of problems and a space of algorithms, map each problem-algorithm pair to its performance."),
         ("Caveat on training samples and features (the survey summarizing Rice 1976 on the difficulty of knowing the problem space): problem spaces are often sampled to evaluate algorithms empirically; if the sample is not representative or the features do not separate problem classes, there is little hope of finding the best or even a good selection mapping.",
          "Introduction",
          "If the sample is not representative, or the features do not facilitate a good separation of the problem classes in the feature space, there is little hope of ﬁnding the best or even a good selection mapping."),
         ("Failure mode of selecting a single algorithm per instance: a wrong selection cannot be mitigated; the system is stuck with a badly performing algorithm even if other portfolio algorithms would do much better (schedules over several algorithms are the surveyed alternative).",
          "What to select",
          "If an algorithm is chosen that exhibits bad performance on the problem, the system is “stuck” with it and no adjustments are made, even if all other portfolio algorithms would perform much better."),
         ("Offline vs online selection: purely offline approaches have no way of mitigating wrong choices, often do not even detect them (they do not monitor the chosen algorithm), and are inherently vulnerable to bad choices, but incur no overhead during solving; online selection allows finer decisions at the price of higher overhead.",
          "When to select",
          "Purely oﬄine approaches are inherently vulnerable to bad choices."),
         ("Selector cost requirement: apart from accuracy, a selector must be relatively cheap to run, since selecting is pointless if it costs more than solving the problem.",
          "Portfolio selectors",
          "Apart from accuracy, one of the main requirements for such a selector is that it is relatively cheap to run – if selecting an algorithm for solving a problem is more expensive than solving the problem, there is no point in doing so."),
         ("Fallback to a default algorithm (described for systems such as SATzilla, Xu et al. 2008): pre-solvers run before feature analysis, and if the predicted feature-analysis time is too high a default algorithm with reasonable performance is chosen; the survey says this matters when problems are hard to analyse but easy to solve.",
          "Portfolio selectors",
          "If the predicted required analysis time is too high, a default algorithm with reasonable performance is chosen and run on the problem."),
         ("No Free Lunch: the survey notes NFL would also apply to selection systems themselves (gains on one part of the problem space, losses elsewhere), but judges from the literature that, if applicable, the ramifications in practice may not be significant.",
          "No Free Lunch theorems",
          "However, a review of the literature suggests that, if the theorems are applicable, the ramiﬁcations in practice may not be signiﬁcant."),
     ],
     "notes": "Survey; no experiments of its own. Affiliation stated: 4c.ucc.ie email address. Rice's four selection criteria include 'best selection for all mappings and problems' (per-instance) and 'best selection for a subclass of problems' (a single algorithm for a subclass, i.e. per-set); the survey says the latter cases are more common in practice. It also cites Guo (2003) that the Algorithm Selection Problem is undecidable in general and says a mapping that generalises well may be preferable to the best-performing one. Dynamic features (computed during search) are the only ones that use performance on the current problem, allowing remedial action when a problem is unlike anything seen before (Features section). Feature cost: Xu et al. (2009) fall back to a default selection when feature computation is predicted too expensive. Misclassification-penalty weighting (Gent et al. 2010) is described for training selectors. The terms 'virtual best solver' and 'oracle' were not found in the text; the Summary only states some systems have come very close to always choosing the best algorithm. Tag note: the family tag dynamic-ensemble-selection is an approximation and does not describe this paper accurately. The survey is about per-instance algorithm selection from solver portfolios (and schedules) for combinatorial search problems, not about ensembles of classifiers; no existing family tag covers algorithm portfolios, and dynamic-ensemble-selection (choosing which models to use for each input) was the closest."},

    {"id": "arxiv-2007.04074",
     "title": "Auto-Sklearn 2.0: Hands-free AutoML via Meta-Learning",
     "authors": ["Matthias Feurer", "Katharina Eggensperger", "Stefan Falkner", "Marius Lindauer", "Frank Hutter"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2007.04074", "code": "https://github.com/automl/ASKL2.0_experiments"},
     "tasks": ["model-selection", "tabular-classification"],
     "fam": ["automl-systems"], "par": ["meta-learning"],
     "proposes": ["PoSH Auto-sklearn: a greedily built, meta-feature-free static portfolio of complementary ML pipelines to warm-start Bayesian optimization, plus successive halving for budget allocation",
                  "Auto-sklearn 2.0: a model-based policy selector that chooses per dataset among eight AutoML policies ({holdout, 3/5/10-fold CV} x {successive halving, full budget}, each with its own portfolio) using pairwise random forests on two meta-features, with a rule-based fallback for out-of-distribution datasets"],
     "claims": [
         ("Portfolio guarantee and its conditions: minimizing a portfolio's test loss on the meta-datasets (choosing a pipeline from the portfolio per dataset by holdout or CV) is shown equivalent to sensor placement; the penalty is submodular, so the greedy portfolio achieves at least (1-1/e) of the penalty reduction of the optimal portfolio of the same size, measured on the meta-train datasets Dmeta ('at the very least'). For new datasets there is no guarantee: the authors only state that the portfolio is a strong set of defaults under the assumption that new datasets come from the same distribution.",
          "Theoretical Properties of the Greedy Algorithm",
          "Under the assumption that we apply the portfolio to datasets from the same distribution of datasets, we have a strong set of default ML pipelines."),
         ("Selector mechanism (per-instance algorithm selection, following HydraMIP): for each pair of policies a random forest predicts whether one outperforms the other from the dataset's meta-features; meta-observations are weighted by the loss difference, errors are rescaled per dataset, pairwise models vote at test time, and the selector's hyperparameters are tuned by BO on cross-validation error (tree depth 0 recovers the single best policy).",
          "Constructing the per-dataset Policy Selector",
          "for each pair of AutoML policies, we ﬁt a random forest to predict whether policy πA outperforms policy πB given the current dataset’s meta-features."),
         ("Meta-features: only two simple meta-features computable in linear time (number of datapoints and number of features) are used, chosen to avoid the time and robustness problems of richer meta-features; the authors describe this as learning the manually designed fallbacks.",
          "Meta-Features",
          "reliably computed in linear time for every dataset: 1) the number of datapoints and 2) the number of features."),
         ("Fallback for out-of-distribution datasets: because the selector is not guaranteed to extrapolate (e.g. to much larger datasets, where a chosen policy could time out), if no meta-dataset has higher or equal values on every meta-feature (number of datapoints and features) the system falls back to holdout with successive halving, described as the most aggressive and cheapest policy considered. The fallback is a fixed rule on the two meta-features, not learned; Figure 3 marks several test datasets as outside the meta-dataset distribution.",
          "Backup strategy",
          "Since there is no guarantee that our model-based policy selector will extrapolate well to datasets outside of the meta-datasets, we implement a fallback measure to avoid failures."),
         ("Ablation: removing the fallback degrades performance for all policy selection strategies, which the authors say can mainly be explained by a few huge datasets the selector cannot extrapolate to; the authors suggest research on an adaptive fallback that switches strategy during execution, and report the selector beats the single best policy at 10 minutes but not at 60 minutes when no fallback is used.",
          "Ablation",
          "The rather stark performance degradation compared to the regular model-based policy selector can mainly be explained by a few, huge datasets, to which the model-based policy selector cannot extrapolate (and which the single best does not account for)."),
         ("Evaluation protocol: portfolios and the selector are built on 208 OpenML meta-datasets (filtered by size and attribute types, synthetic datasets dropped, clusters of highly similar datasets subsampled, manually checked for overlap with the test set) and evaluated on 39 disjoint AutoML-benchmark datasets with one 33.33% holdout test split per task, 10 repetitions, normalized balanced error (ADTM), Wilcoxon signed-rank tests; the ablation adds a random policy and an oracle that picks the best policy on the test set.",
          "Datasets",
          "Finally, we manually checked for overlap with Dtest and ended up with a total of 208 training datasets and used them to train our method."),
         ("Stated limitations: the system optimizes toward a given optimization budget, metric and configuration space; there is no performance guarantee for SH combined with BO; several AutoML-level hyperparameters remain hand-picked; whether other meta-features than the two used would help is open; and building the meta training data is expensive.",
          "Discussion and Conclusion",
          "However, our system also introduces some shortcomings since it optimizes performance towards a given optimization budget, performance metric and conﬁguration space."),
     ],
     "notes": "PDF states: Journal of Machine Learning Research 23 (2022) 1-61. Conflict of interest: the paper calls Auto-sklearn 2.0 'the next generation of our AutoML system' (the authors develop Auto-sklearn) and compares Auto-sklearn 2.0 against Auto-sklearn 1.0 and other AutoML systems (Auto-WEKA, TPOT, H2O AutoML, tuned RF) on the AutoML benchmark (1h8c setting, 10 folds, 5 repeats); they note they cannot compute significance on CV folds there. Affiliations include Bosch Center for Artificial Intelligence; acknowledgements state Robert Bosch GmbH financial support. The authors report the improvement over Auto-sklearn 1.0 is skewed by several large datasets on which Auto-sklearn 1.0's KND initialization only suggested ML pipelines that time out or hit the memory limit. Motivation for the portfolio: meta-feature computation ran over time on one track of the first AutoML challenge even after removing landmarking features (Portfolio Building). Meta-data for the selector built with inner 5-fold CV over meta-datasets to avoid overestimating policy performance; meta-data generation used Auto-sklearn runs at ten times the user budget with the best pipeline picked on the meta-dataset test split. The oracle in Table 6 is defined as always choosing the best policy on the test set; footnote says its normalized error can be non-zero. Results tables not recorded."},

    {"id": "arxiv-1810.01270",
     "title": "META-DES: A Dynamic Ensemble Selection Framework using Meta-Learning",
     "authors": ["Rafael M. O. Cruz", "Robert Sabourin", "George D. C. Cavalcanti", "Tsang Ing Ren"],
     "year": 2018, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1810.01270"},
     "tasks": ["model-selection", "tabular-classification"],
     "fam": ["dynamic-ensemble-selection"], "par": ["meta-learning", "supervised"],
     "proposes": ["META-DES: dynamic ensemble selection framed as a meta-problem; five sets of meta-features (local hard classification and posterior probabilities in a K-NN region of competence, overall local accuracy, agreement on Kp similar output profiles, and distance to the decision boundary) feed a meta-classifier that decides per query whether each base classifier is competent; competent classifiers are combined by majority vote"],
     "claims": [
         ("Mechanism: meta-features extracted from training data train a meta-classifier that predicts whether a base classifier is competent to classify an input; at test time the meta-features are extracted for the query and the meta-classifier decides whether each base classifier is added to the ensemble.",
          "Abstract",
          "The meta-features are extracted from the training data and used to train a meta-classiﬁer to predict whether or not a base classiﬁer is competent enough to classify an input instance."),
         ("Competence signals: three meta-feature sets (f1-f3) come from the region of competence (K nearest neighbours of the query), f4 from the most similar output profiles in decision space, and f5 from the base classifier's confidence on the query itself.",
          "Meta-feature extraction process",
          "Three meta-features, f1, f2 and f3, are computed using information extracted from the region of competence θj."),
         ("Failure mode of local-accuracy competence (from the authors' previous work and discussion of prior DES methods): selection is limited by the algorithm that defines the region of competence, errs when mislabelled outliers lie near the query, and any difference between the validation and test distributions may negatively affect performance.",
          "Classifier accuracy over a local region",
          "Moreover, any difference between the distribution of validation and test datasets may negatively affect the system performance."),
         ("Protocol: 30 classification datasets (UCI, STATLOG, KEEL, LKC, PRTOOLS), with the evaluation focused on small datasets plus a few larger ones; 20 replications of random class-stratified splits (50% training, 25% dynamic selection set DSEL, 25% test) of the same datasets, so test data are not shifted; for META-DES half the training data is used for meta-training and half for generating the pool.",
          "Experimental Protocol",
          "The experiments were conducted using 20 replications."),
         ("Hyperparameter setting: K was fixed at 7 from the authors' previous paper; hC and then Kp were set to the best-performing values on DSEL (Kruskal-Wallis tests; smaller value on ties) using eleven of the thirty datasets. These eleven datasets are also part of the 30 datasets on which the comparison is reported; DSEL, not the test split, was used.",
          "Parameters Setting",
          "Only a subset with eleven of the thirty datasets are used for parameters setting procedure: Pima, Liver, Breast, Blood Transfusion, Banana, Vehicle, Lithuanian, Sonar, Ionosphere, Wine, Haberman’s Survival."),
         ("Baselines: all methods share a pool of 100 Perceptrons (generated by bagging; multi-class perceptrons for multi-class problems); the eight DES techniques (KNORA-E, KNORA-U, DES-FA, LCA, OLA, MLA, MCB, KNOP) use K = 7 because it gave the best result in previous publications, and no re-tuning of the baselines in this paper is described; static baselines are AdaBoost and Bagging (100 iterations), Single Best, static selection, and the Oracle (always selects a correct classifier if one exists); pairs are compared with Kruskal-Wallis at 95%.",
          "Comparison with the state-of-the-art dynamic selection techniques",
          "For all techniques, the pool of classiﬁers C is composed of 100 Perceptrons as base classiﬁer (M = 100)."),
         ("Main empirical claim: META-DES achieved the highest accuracy on the majority of datasets, which the authors attribute to combining five DES criteria (one criterion may fail while others compensate); in the results discussion they also note that no single competence criterion dominated across datasets (invoking no free lunch).",
          "Conclusion",
          "Experimental results show the proposed META-DES achieved the highest classiﬁcation accuracy in the majority of datasets, which can be explained by the fact that the proposed META-DES framework is based on ﬁve different DES criteria."),
     ],
     "notes": "Preprint states 'Preprint submitted to Elsevier'; venue not recorded. Affiliations: LIVIA, Ecole de Technologie Superieure (Montreal) and Universidade Federal de Pernambuco; acknowledgements state support from the Natural Sciences and Engineering Research Council of Canada. The meta-classifier is an MLP with 10 hidden neurons trained with Levenberg-Marquardt and early stopping on a 25% validation split of the meta-training set; only samples whose pool consensus falls below hC are used for meta-training. The authors argue the meta-problem has N x M training vectors, which they relate to gains on small datasets. Conflict of interest: the baseline DES-FA [10] is by authors of this paper (Cruz, Cavalcanti, Ren), and Sabourin co-authored KNORA [4] and the DS survey [3] used to pick baselines. Baseline DES methods used K = 7 from previous publications (no re-tuning described); META-DES's own hC and Kp were set on DSEL of 11 of the 30 datasets; the Oracle is an upper bound, not a deployable selector. Test data are random splits of the same datasets (no shift evaluated). Observation from the text: in Table 3 the META-DES entries for Adult and Weaning are identical (87.15(2.43)); not checked against the published version. Results tables not recorded."},

    {"id": "arxiv-1802.04967",
     "title": "DESlib: A Dynamic ensemble selection library in Python",
     "authors": ["Rafael M. O. Cruz", "Luiz G. Hafemann", "Robert Sabourin", "George D. C. Cavalcanti"],
     "year": 2018, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1802.04967", "code": "https://github.com/scikit-learn-contrib/DESlib"},
     "tasks": ["model-selection"],
     "fam": ["dynamic-ensemble-selection"], "par": ["supervised"],
     "proposes": ["DESlib: scikit-learn-compatible Python library implementing dynamic classifier selection (DCS), dynamic ensemble selection (DES, incl. META-DES, KNORA-E/U, DES-P, KNOP, DES-RRC, DES-KL) and static baselines (Single Best, Static Selection, Oracle, Stacked Generalization)"],
     "claims": [
         ("Rationale of dynamic selection: competence of each pool classifier is estimated per query and only the most competent classifier (or an ensemble of the most competent) predicts, on the premise that each base classifier is an expert in a different local region of the feature space.",
          "Introduction",
          "The rationale for such techniques is that not every classiﬁer in the pool is an expert in classifying all unknown samples; rather, each base classiﬁer is an expert in a different local region of the feature space."),
         ("Modular design following the authors' taxonomy (Cruz et al., 2018): a DS method is defined by how the region of competence is defined, the source of information used to estimate competence, and the selection approach; new methods often only need estimate_competence and select.",
          "Project management",
          "(1) the methodology used to deﬁne the local region, in which the competence level of the base classiﬁers are estimated (region of competence); (2) the source of information used to estimate the competence"),
         ("What is selected: DCS selects only the single base classifier with the highest competence; DES selects all base classifiers that reach a minimum competence level.",
          "Implemented techniques",
          "All base classiﬁers that attain a minimum competence level are selected to compose the ensemble of classiﬁers."),
         ("Baselines provided: static ensembles commonly used as baselines for DS methods, including Single Best, Static Selection, the Oracle and Stacked Generalization.",
          "Implemented techniques",
          "Static Ensembles: This module provides the implementation of static ensemble techniques that are usually used as a baseline for the comparison of DS methods: Single Best (SB), Static Selection (SS), Oracle and Stacked Generalization."),
         ("Usage defaults: from version 0.3 each method has default values and can train its pool inside fit when no trained pool is given; the documented example fits the DS method on a separate dynamic selection set (X_dsel).",
          "Usage",
          "As of version 0.3, each implemented method comes with a list of default values, not requiring a trained list of classiﬁers as input."),
         ("Scope / future work: dynamic selection for other contexts such as one-class classification and regression is listed as future work (the library covers classification).",
          "Conclusion and future plans",
          "Future work on this library includes the implementation of dynamic selection methods in different contexts, such as One-Class-Classiﬁcation (OCC) and regression."),
     ],
     "notes": "Software paper; no experiments, datasets or accuracy comparisons were found in the text. Conflict of interest (from the reference list): the library authors are also authors of several implemented methods, e.g. META-DES (Cruz, Sabourin, Cavalcanti et al.), FIRE-DES++ and Online Local Pool (both including Cruz, Cavalcanti, Sabourin), KNORA-E/U and KNOP (including Sabourin), and of the DS taxonomy and the review cited for DS improvements over static combination (Cruz et al., 2018). Affiliations: LIVIA, ETS - Universite du Quebec (Montreal) and Universidade Federal de Pernambuco. Part of scikit-learn-contrib; v0.3 at time of writing. Also implements Dynamic Frienemy Pruning (FIRE-DES) and dynamic weighting / hybrid selection+weighting variants."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model fallback and model selection in MLOps (meta-learned selection, dynamic selection, abstention/deferral, switching triggers, cascades/routing, monitoring); carded by a subagent. Results tables not recorded; claims only.")
