import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ae_common import BASE_NOTE  # noqa: E402

SPECS = [
    {"id": "arxiv-2009.11732",
     "title": "A Unifying Review of Deep and Shallow Anomaly Detection",
     "authors": ["Lukas Ruff", "Jacob R. Kauffmann", "Robert A. Vandermeulen", "Grégoire Montavon", "Wojciech Samek",
                 "Marius Kloft", "Thomas G. Dietterich", "Klaus-Robert Müller"],
     "year": 2020, "venue": "Proceedings of the IEEE", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2009.11732", "doi": "https://doi.org/10.1109/JPROC.2021.3052449"},
     "tasks": ["anomaly-detection"],
     "fam": ["autoencoders", "reconstruction-based-detectors", "classical-outlier-detectors", "kernel-methods", "deep-learning"],
     "par": ["unsupervised"],
     "proposes": ["A unifying view that describes probabilistic, one-class classification and reconstruction anomaly detectors by five modeling dimensions (loss, model, feature map, regularization, inference mode)",
                  "An AUC comparison of nine shallow and deep detectors (including PCA, kernel PCA and an autoencoder) on MNIST-C and MVTec-AD, plus worked-through examples with explanation (LRP) of anomaly predictions"],
     "claims": [
         ("Positioning: autoencoders were studied early for anomaly detection, and deep autoencoders are today among the most widely adopted methods for deep anomaly detection, which the authors attribute (with 'likely') to their long history and easy-to-use standard variants.",
          "Section V-C (Autoencoders)",
          "Today, deep autoencoders are among the most widely adopted methods for deep anomaly detection in the literature"),
         ("Assumption behind the reconstruction score: without restrictions the reconstruction objective would be solved by the identity map, so structural assumptions (manifold or prototype) are needed; if the model has learned a truthful manifold or prototypical structure, a high reconstruction error would detect off-manifold or non-prototypical points. Most reconstruction methods have no probabilistic motivation, while some (PCA, Bayesian PCA, VAEs) relate to density estimation.",
          "Section V-A (Reconstruction Objective)",
          "For models that have learned some truthful manifold structure or prototypical representation, a high reconstruction error would then detect off-manifold or non-prototypical instances."),
         ("Failure mode (open problem): citing Tong et al. [554], the authors note that an anomalous all-black image can be well reconstructed by an autoencoder trained on MNIST; they state that similar observations suggest reconstruction-based models can systematically reconstruct simpler out-of-distribution points within the convex hull of the data, give the PCA example of perfect reconstruction along the principal subspace far from the training data, and call for more theoretical research on such out-of-distribution generalization.",
          "Section IX-F (Foundation and Theory)",
          "For example, an anomalous all-black image can be well reconstructed by an autoencoder trained on MNIST digits"),
         ("Comparison setup and finding: nine methods (Gaussian, MVE, PCA, KDE, SVDD, kPCA, AGAN, DOCC, AE) are compared by AUC on MNIST-C (trained on the standard MNIST training set, tested on each corruption separately) and on MVTec-AD (one model per image set); performance is heterogeneous across corruptions and defect classes, more powerful nonlinear models are not better on every class, and simple shallow models occasionally outperform deep ones.",
          "Section VII-C (Comparison on MNIST-C and MVTec-AD)",
          "Also, the more powerful nonlinear models are not better on every class, and simple ‘shallow’ models occasionally outperform their deeper counterparts."),
         ("Hyperparameter selection in the comparison: the AE is trained so that the reconstruction error on a small training hold-out set is minimized (64-dimensional code on MNIST-C, 512-dimensional bottleneck on MVTec-AD); PCA and kPCA keep 90% of the variance; KDE bandwidth maximizes the likelihood of a small hold-out set from the training data; for SVDD the kernel scale is selected using a small labeled hold-out set.",
          "Appendix B-B (Training Details)",
          "We train the AE such that the reconstruction error of a small training hold-out set is minimized."),
         ("Worked example (MVTec-AD wood): hyperparameters are selected on hold-out data that may include a few inliers and anomalies extracted from the test set, and performance is evaluated on the remainder of the test set; LRP explanations then show that the best-scoring model (KDE) relies on the wood grain rather than the stain, which the authors call a 'Clever Hans' effect.",
          "Section VIII-B (Example 2: MVTec Industrial Inspection)",
          "Following the standard model training / validation procedure, we train a set of models on the training data, select their hyperparameters on hold out data (e.g., a few inliers and anomalies extracted from the test set), and then evaluate their performance on the remainder of the test set."),
         ("Contamination: in the unsupervised setting, unlabeled training data may be contaminated with undetected anomalies (a mixture with contamination rate eta); the greater the contamination, the more the normal decision boundary is distorted. Assumptions about noise and contamination rate are described as crucial, and robust methods aim to account for them.",
          "Section II-C2 (The Unsupervised Setting)",
          "The greater the contamination, the more the normal data decision boundary will be distorted by including the anomalous points."),
         ("Evaluation advice: the decision threshold is set to minimize type I/II error costs on validation data or to meet deployment constraints; when costs are unspecified, threshold-independent AUC is common, but it can be overly optimistic on highly imbalanced test sets where AUPRC is more informative; the authors recommend ideally reporting both. They also note that k-classes-out benchmarks may not be a good simulacrum of real anomalies.",
          "Section VII-B (Evaluating Anomaly Detectors)",
          "One caveat of AUC is that it can produce overly optimistic scores in case of highly imbalanced test sets [200], [451]."),
     ],
     "notes": "Venue and DOI from the arXiv journal_ref ('Proceedings of the IEEE (2021) 1-40') and arXiv DOI field. Affiliations not recorded. Possible conflict of interest (not stated as such in the paper): the reference list shows that Ruff, Vandermeulen, Kloft and Müller are authors of Deep SVDD [137] and Deep SAD [144], which the review discusses; whether the 'DOCC' model in the MNIST-C/MVTec-AD comparison is the authors' own method is not stated (Appendix B-B describes it as a whitening transform on pre-trained VGG16 / EMNIST-CNN features). AUC values in Fig. 8 labels and in Tables IV-VI are not recorded. Only the reconstruction/autoencoder, evaluation and open-problem parts of the 40-page review were read closely."},

    {"id": "arxiv-1812.02765",
     "title": "Improving Reconstruction Autoencoder Out-of-distribution Detection with Mahalanobis Distance",
     "authors": ["Taylor Denouden", "Rick Salay", "Krzysztof Czarnecki", "Vahdat Abdelzad", "Buu Phan", "Sachin Vernekar"],
     "year": 2018, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1812.02765"},
     "tasks": ["anomaly-detection"],
     "fam": ["autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised"],
     "proposes": ["A hybrid novelty score: the Mahalanobis distance of the encoded sample to the mean of the encoded training set plus the reconstruction error, each scaled by the reciprocal of its standard deviation on an inlier validation set"],
     "claims": [
         ("Thesis: the authors suggest that reconstruction-based approaches fail to capture anomalies that lie far from known inliers in latent space but near the latent manifold defined by the model, and propose adding the latent Mahalanobis distance; the abstract says this 'often' improves over the baseline.",
          "Abstract",
          "Here we suggest that reconstruction-based approaches fail to capture particular anomalies that lie far from known inlier samples in latent space but near the latent dimension manifold deﬁned by the parameters of the model."),
         ("Observed failure: autoencoders sometimes reconstruct OOD samples with less error than many inlier samples, so no threshold can classify those OOD samples correctly while keeping all inliers correct; the authors report observing this for dense and convolutional autoencoders of different depths and hidden-layer sizes, often with OOD samples visibly distinct to humans.",
          "Problem and approach",
          "Experimentally, we have found that autoencoders will sometimes reconstruct OOD samples with less error than many inlier samples."),
         ("Why not enlarge the bottleneck: increasing the latent dimensionality increases model power, and a bottleneck equal to or larger than the input can potentially learn the identity and reconstruct any input; the authors instead add a distance in the latent space.",
          "Problem and approach",
          "An autoencoder with a bottleneck layer dimensionality equal to or greater than the original input can potentially learn the identity function and reconstruct any given input, diminishing its ability to distinguish between inlier and OOD data."),
         ("Score weighting without OOD data: the mixing parameters are set from an inlier-only validation set (alpha = 1/std of the latent Mahalanobis distance, beta = 1/std of the reconstruction error); the authors say tuning this combination may give further improvements in future work.",
          "Experiments and results",
          "α and β are mixing parameters that were determined using a validation set of inliers samples."),
         ("Evaluation setup: for each of ten bottleneck sizes (2 to 798, stated as the original input size), a separate autoencoder is trained on a single MNIST digit class, which is the inlier class for that model; metrics are FPR at 95% TPR, AUROC, AUPR (in) and AUPR (out). MNIST is the only dataset.",
          "Experiments and results",
          "For each of the different architectures, a separate autoencoder was trained using only images from a single digit class from MNIST."),
         ("Result statement (hedged): incorporating the latent distance improved performance over reconstruction error alone 'in most cases'; the conclusion says the hybrid 'often' improves performance.",
          "Experiments and results",
          "Our results show that incorporating the latent distance improved performance over using only the reconstruction error in most cases."),
         ("Model selection for the summary table: Table 1 compares methods at the architecture that gave the best available result for the baseline (reconstruction error); the caption does not say on which data split this best result was determined.",
          "Table 1 caption",
          "Architecture chosen was for the best available result for the baseline method."),
         ("Stated limitations / future work: extend to more complex naturalistic image datasets, optimize how latent distance and reconstruction error are combined, and model multiple inlier classes with a single autoencoder.",
          "Conclusion and future work",
          "In the future, we would like to extend our work to more complex naturalistic image datasets"),
     ],
     "notes": "Affiliation: University of Waterloo. arXiv comment '9 pages, 5 figures'; no venue stated in the PDF. Training (Appendix): MNIST training set randomly split into 50000 training / 10000 validation; Adadelta, binary cross-entropy, up to 500 epochs with early stopping (patience 20) on validation loss. The text says the largest bottleneck, 798, is 'the original input size' (recorded as written; not checked against MNIST's 28x28 = 784). The OOD test samples are not explicitly described in the body; Figure 1 and 3a show other MNIST digits as OOD. Results tables (Tables 1-11) not recorded."},

    {"id": "arxiv-2501.13864",
     "title": "Autoencoders for Anomaly Detection are Unreliable",
     "authors": ["Roel Bouman", "Tom Heskes"],
     "year": 2025, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2501.13864"},
     "tasks": ["anomaly-detection"],
     "fam": ["autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised"],
     "proposes": ["Proofs that PCA and linear autoencoders (at the global optimum) reconstruct with zero loss points arbitrarily far from all training data, plus a ReLU toy construction and experiments (2D tabular, convolutional AE on MNIST) showing out-of-bounds and inter-class reconstruction of anomalies"],
     "claims": [
         ("Thesis: autoencoder anomaly detection assumes normal data is reconstructed more accurately than anomalies; the authors show this assumption does not hold and illustrate that anomalies far from normal data can be perfectly reconstructed in practice.",
          "Abstract",
          "In this work we show that this assumption indeed does not hold, and illustrate that anomalies, lying far away from normal data, can be perfectly reconstructed in practice."),
         ("Linear theory (PCA and linear AE): any point in the span of the first d principal components has zero reconstruction loss, and moving along this subspace outward from the convex hull gives points beyond any distance delta (Euclidean) from all training data; for linear autoencoders the authors assume convergence to the global optimum (citing Baldi & Hornik) so the case reduces to PCA, with bias terms covered in Appendix A.1. The proof holds in the semi-supervised setting (training data contain no anomalies) and hence also the unsupervised one; other distance metrics are only posited.",
          "Out-of-bounds reconstruction: PCA",
          "We can prove this even in the semi-supervised setting, where we guarantee that the model was not exposed to anomalous data at training time."),
         ("Non-linear (ReLU) case: for a 2D dataset on the diagonal, a ReLU autoencoder can find the same weights as a linear one, and far points on the diagonal are perfectly reconstructed; beyond this simple case the authors only theorize that similar linear behavior can occur outside the convex hull, and show it experimentally on synthetic 2D data (100 points per distribution, [2,5,1,5,2] or deeper autoencoders).",
          "Failure of a non-linear network with ReLU activations",
          "We theorize that even beyond this simple case, similar linear behavior can occur beyond the convex hull that the normal data occupies."),
         ("Activation functions: C0 activations such as ReLU suffer most from out-of-bounds reconstruction but are easier to train deep; C-infinity activations such as sigmoid generally have more desirable properties for anomaly detection but suffer from vanishing gradients, and sigmoid autoencoders can still show low-loss regions where the two clusters' sigmoids intersect.",
          "Other activation functions",
          "In summary, activation functions with an order of continuity of C0 suffer most from out-of-bounds reconstruction, but allow for more easily trainable deep networks."),
         ("Image experiment: a convolutional autoencoder (2-layer encoder/decoder, ReLU, sigmoid output) with a 2-dimensional latent space (chosen to rule out the 'identical shortcut') is trained on MNIST subsets (digits 4, 5, 7; digits 0, 1); decoding low-loss latent grid points gives adversarial anomalies with lower reconstruction loss than all training data. The authors note there is no consensus on which digits are normal and that only in some of their tried combinations does out-of-bounds reconstruction occur.",
          "Failure on real-world data: MNIST",
          "In our experiments, both shown and non-shown, we have tried several different combinations and observe that in some cases out-of-bounds reconstruction occurs."),
         ("Instability of the failure: whether out-of-bounds reconstruction is easily detected depends on the random seed and the digits chosen as normal, and it can disappear and reappear between epochs; the authors argue that in semi-supervised or unsupervised settings one cannot accurately judge whether a network will fail on future data. They also note some out-of-bounds reconstruction (an unusual diagonal 1) matches what a user would consider normal.",
          "Failure on real-world data: MNIST",
          "We observe that depending on the random seed used for initialization and the digits selected as normal data, the out-of-bounds reconstruction may or may not be easily detected."),
         ("On proposed fixes (related work): the authors state that, from their experiments, relying on distances or densities in the latent space (as in Zong et al. 2018 and Cheng et al. 2021) does not always work in practice; they also say memory modules reduce reconstruction ability and that they do not think adversarially robust training (Salehi et al. 2021) results in a reliable autoencoder.",
          "Related work",
          "From our experiments we can glean that relying on distances or densities in the latent space does not always work in practice."),
         ("Recommendation: practitioners should at least check whether a trained non-linear autoencoder shows out-of-bounds reconstruction, e.g. by searching for adversarial anomalies in the latent space; for larger latent spaces projected gradient descent 'might be' a feasible strategy (not tested in the paper).",
          "Conclusion",
          "Good practice would be to at least check whether a trained non-linear autoencoder exhibits the undesirable out-of-bounds reconstruction."),
     ],
     "notes": "Affiliation: Radboud University (Nijmegen). arXiv API record has no comment or journal_ref and the PDF states no venue, so no venue recorded. The experiments are illustrative (contour plots and constructed adversarial anomalies); no detection metric (AUC etc.) or threshold-selection protocol is reported, and no optimizer/learning-rate/epoch details were found in the text (searched for optimizer, learning rate, Adam, batch size, trained for). The authors cite their own earlier benchmark (Bouman et al., 2024, JMLR) only as an analogy for tabular benchmarking practice. Figures not converted to numbers; body-text loss values for the MNIST adversarial examples are not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, created_at="2026-10-04", created_by="claude-opus-5-5 via Claude Code (subagent)")
