import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_automl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2006.13799",
     "title": "Auto-PyTorch Tabular: Multi-Fidelity MetaLearning for Efficient and Robust AutoDL",
     "authors": ["Lucas Zimmer", "Marius Lindauer", "Frank Hutter"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2006.13799", "code": "https://github.com/automl/Auto-PyTorch"},
     "tasks": ["tabular-classification", "hyperparameter-optimization", "neural-architecture-search"],
     "fam": ["automl-systems", "multi-fidelity-optimization", "bayesian-optimization", "deep-learning", "heterogeneous-ensembles"],
     "par": ["supervised", "meta-learning"],
     "proposes": ["Auto-PyTorch Tabular: joint optimization of network architecture (funnel-shaped MLPs/ResNets described by a few shape hyperparameters) and training hyperparameters with BOHB, using training epochs as fidelities",
                  "Meta-feature-free warm start: a greedy portfolio of complementary configurations (built offline from BOHB incumbents on meta-training datasets by minimizing mean relative regret) is evaluated in BOHB's first iteration",
                  "Post-hoc ensemble selection over trained DNNs (across fidelities) plus traditional baselines (Random Forest, Extra Trees, LightGBM, CatBoost, kNN)",
                  "LCBench: learning curves of 2,000 randomly sampled configurations of a 7-hyperparameter space on 35 AutoML-Benchmark datasets at three epoch budgets"],
     "claims": [
         ("Motivation: the authors state, citing Zela et al. [9], that because the best architecture and the best hyperparameter configuration interact, AutoDL systems have to optimize both jointly; they also note that doing HPO only as a post-processing step of NAS ignores these interaction effects.",
          "Introduction",
          "Since there are interaction effects between the best architecture and the best hyperparameter conﬁguration for it, AutoDL systems have to jointly optimize both [9]."),
         ("Multi-fidelity search: Auto-PyTorch uses BOHB (Bayesian optimization with KDE models plus Hyperband/successive halving) and chooses the number of training epochs rather than runtime as the budget, for generality and interpretability.",
          "Section 3.2",
          "We choose the number of training epochs as our budgets over the runtime because of its generality and interpretability."),
         ("Ensembling: post-hoc ensemble selection (Caruana-style, following auto-sklearn) greedily adds models from those stored during optimization, considering only the k = 30 best; the authors state that because it is post-hoc, models other than DNNs can easily be included, and that combining model classes is one of the key factors for state-of-the-art tabular performance in their experiments.",
          "Section 3.5",
          "An advantage of our post-hoc ensembling is that we can also include other models besides DNNs easily."),
         ("Warm start by portfolio: instead of meta-features, BOHB's first iteration starts from a greedily built portfolio of complementary configurations; the authors note that this (as all meta-learning approaches) assumes meta-training datasets that are representative of the meta-test datasets, which they believe is particularly possible for tabular data because of platforms such as OpenML.",
          "Section 3.6",
          "This approach assumes (as all meta-learning approaches) that we have access to a reasonable set of meta-training datasets that are representative of meta-test datasets."),
         ("LCBench protocol: 2,000 randomly sampled configurations of the small space (7 hyperparameters, SGD with cosine annealing) evaluated at 12, 25 and 50 epochs with three seeds on 35 of the 39 AutoML Benchmark datasets (1,500 CPU hours); the four largest datasets were omitted to keep runtimes and memory low.",
          "Section 4.1.1",
          "As we designed LCBench to be a cheap benchmark, we omit the four largest datasets (robert, guillermo, riccardo, dilbert), in order to ensure low runtimes and memory footprint."),
         ("Caveat on fidelities: while budget correlations were consistently quite high in the small LCBench space, on the full Auto-PyTorch space the Spearman correlation between budgets is quite low on some meta-training datasets, which the authors attribute to hyperparameters whose settings are more sensitive to budgets; they state that the correlations nevertheless suffice for Auto-PyTorch to perform well in their experiments.",
          "Section 5.2",
          "This indicates that there are speciﬁc hyperparameters in our larger conﬁguration space whose settings are more sensitive to budgets and thus lead to smaller correlations."),
         ("Evaluation protocol: the portfolio is built from BOHB runs (24 h, at most 300 iterations) on 100 OpenML meta-training datasets (overlap with the test datasets was checked, Appendix A) and has size 16; ablations run up to 72 hours or 300 BOHB iterations on 8 OpenML test datasets; tabular baselines (LightGBM, CatBoost, Random Forest, Extra Trees, kNN) follow Erickson et al. and use the same hyperparameter setting, with 6 CPU cores to match an Auto-PyTorch run.",
          "Section 5.1",
          "We choose 8 test datasets from OpenML roughly covering the feature and class distribution of the meta datasets."),
         ("Comparison with other AutoML systems (Auto-Keras, auto-sklearn, hyperopt-sklearn, Auto-Net 2.0): a 1 h runtime where possible, otherwise performance after 1 h inferred from trajectories over increasing trial counts; 5 seeds; AutoKeras and auto-sklearn sometimes ran into memory errors and hyperopt-sklearn could not handle missing data. By a t-test (alpha = 0.05) Auto-PyTorch Tabular was significantly better than each competitor on between 5 and 7 of 7 datasets and significantly worse than auto-sklearn and hyperopt-sklearn on a single dataset; against AutoGluon, the authors report that AutoGluon's auto-stacking gives a small edge over Auto-PyTorch with ensembles.",
          "Section 5.4",
          "Indeed, based on a t-test with α = 0.05, it performed statis-tically signiﬁcantly better than each competitor on between 5 and 7 out of 7 datasets, only performing statistically sig-niﬁcantly worse than auto-sklearn and hyperopt-sklearn on a single dataset."),
         ("Stated limitations: ensembles improve performance overall but are known to be able to overfit (better generalization estimates could help); all ensemble members other than neural networks use default hyperparameter settings; and the hyperparameter-importance results have not yet been used to improve Auto-PyTorch.",
          "Conclusion",
          "First of all, while the ensem-bles improve performance overall, it is also known that they can lead to overﬁtting."),
     ],
     "notes": "Affiliations: University of Freiburg (Zimmer, Hutter), Leibniz University Hannover (Lindauer), Bosch Center for AI (Hutter). The PDF title reads 'Auto-Pytorch: Multi-Fidelity MetaLearning for Efficient and Robust AutoDL'; the arXiv record title (with 'Tabular') is recorded. No venue is stated in the arXiv v3 PDF or in the arXiv comment/journal_ref; none recorded. Conflict of interest: the authors' group developed the components and several compared systems (BOHB, Falkner/Klein/Hutter; auto-sklearn and Auto-sklearn 2.0, Feurer ... Lindauer, Hutter; Auto-Net 2.0, Mendoza ... Lindauer, Hutter; LCBench and the PoSH-style portfolio approach); no explicit conflict-of-interest statement was found in the text. Competitor configuration (Appendix C): Auto-Keras 1.0.2 defaults, AutoGluon 0.0.9 'optimize for deployment' with the same validation split, hyperopt-sklearn with tpe and any classifier/preprocessing, auto-sklearn 0.7.0 with ensemble size 50, 50 best init, 33% holdout, 3 workers; 6 Xeon Gold 6242 cores with 6 GB RAM per core for all. Section 5.1.2 says 8 test datasets while the significance sentence in Section 5.4 says 'out of 7 datasets'; the text does not explain the difference. A NAS-Bench-201 proof of concept (Section 5.5) compares against one-shot results as reported by the NAS-Bench-201 authors (figure only; not recorded). Accuracy tables and figures are not recorded."},

    {"id": "arxiv-1907.00909",
     "title": "An Open Source AutoML Benchmark",
     "authors": ["Pieter Gijsbers", "Erin LeDell", "Janek Thomas", "Sébastien Poirier", "Bernd Bischl", "Joaquin Vanschoren"],
     "year": 2019, "venue": "ICML 2019 AutoML Workshop", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1907.00909", "code": "https://github.com/openml/automlbenchmark"},
     "tasks": ["tabular-classification"],
     "fam": ["automl-systems"],
     "par": ["supervised"],
     "proposes": ["An open, extensible and ongoing AutoML benchmark framework (open-source tool, OpenML-hosted datasets, website with up-to-date results) for comparing AutoML systems under fixed resources",
                  "A first comparison of 4 AutoML systems (Auto-WEKA, auto-sklearn, TPOT, H2O AutoML) against constant-predictor and (tuned) Random Forest baselines on 39 classification datasets"],
     "claims": [
         ("Motivation: the authors argue that many AutoML comparisons use too few, mostly small and old datasets (risking overfitting to a specific dataset set and bias toward older datasets), that authors may knowingly or unknowingly pick datasets on which current systems do well, and that rival methods may not be run correctly, e.g. misunderstood memory management or insufficient compute (citing Balaji and Allen, 2018).",
          "Introduction",
          "Authors may even knowingly or unknowingly select datasets on which current systems perform well."),
         ("Datasets: 39 classification datasets were selected from previous AutoML papers, competitions and ML benchmarks according to predefined criteria, varying in samples and features by orders of magnitude; datasets too easily solved by AutoML or not representing typical AutoML scenarios (e.g. artificial ones) were excluded, some datasets were set aside for future inclusion, and regression datasets were omitted because of computational constraints.",
          "Section 3 (Datasets)",
          "We excluded datasets which were too easily solved with AutoML or did not represent typical AutoML scenario’s (e.g. artiﬁcial datasets)."),
         ("Metrics: AUROC for binary and log loss for multi-class problems (chosen as insightful, commonly used and supported by most tools; the authors state AutoML systems must optimize the same metric they are evaluated on), estimated with ten-fold cross-validation.",
          "Section 3 (Performance metrics)",
          "The measures are estimated with ten-fold cross-validation."),
         ("Framework configuration: all AutoML tools were run with their default hyperparameter values and search spaces (except resource settings fixed to a number of cores, memory and total runtime), because most users use them this way and homogenizing search spaces is practically impossible. Baselines are a constant (class-prior) predictor, an untuned Random Forest and a Random Forest tuned over up to eleven max_features values with cross-validation.",
          "Section 3 (Frameworks and their configuration)",
          "The AutoML tools were all used with their default hyperparameter values and search spaces, since most users will use them in this way."),
         ("Interpretation limit: because no two tools share the same search space or optimization method, the authors state that no conclusions about search spaces or optimization methods can be drawn from the benchmark.",
          "Section 3 (Frameworks and their configuration)",
          "It is important to realize that no two tools share the exact same search space or optimization method, so from this benchmark no conclusions can be drawn about those."),
         ("Meta-learning leakage: a framework whose meta-learning used benchmark datasets has an unfair advantage on them; the authors did not resolve this (left as future work); among the compared frameworks only auto-sklearn uses meta-learning, and affected datasets are marked in the results.",
          "Section 3 (Meta-learning)",
          "An AutoML framework which used datasets of the benchmark in its meta-learning process will have an unfair advantage on them."),
         ("Findings stated in the text (1 h and 4 h budgets per fold, about 8000 hours of computation): no AutoML system consistently outperforms all others; on some datasets the systems are only marginally better than a Random Forest and per-fold score variance can be quite large; the 4 h results are very similar to the 1 h ones (slight improvements, especially for TPOT); Auto-WEKA shows signs of overfitting when running longer, especially on multi-class problems.",
          "Section 4",
          "There is no AutoML system which consistently outperforms all others."),
         ("On dionis and helena all frameworks performed worse than a Random Forest; both have more than 100 quite unbalanced classes, which the authors say seems to be a weak spot for current AutoML techniques, at least under log loss.",
          "Section 4",
          "Both have more more than 100, quite unbalanced classes, which seems to be a weak spot for current AutoML techniques, at least under log loss."),
     ],
     "notes": "Venue from the arXiv comment ('Accepted paper at the AutoML Workshop at ICML 2019') and the PDF header ('6th ICML Workshop on Automated Machine Learning (2019)'). The first four authors contributed equally. Affiliations: TU Eindhoven (Gijsbers, Vanschoren), H2O.ai (LeDell, Poirier), LMU Munich (Thomas, Bischl). Conflict of interest: LeDell and Poirier are at H2O.ai and H2O AutoML is one of the 4 evaluated systems; autoxgboost (Thomas et al., 2018, co-authored by Thomas) is listed among omissions planned for the next version. The paper says the framework was built 'in dialogue with the AutoML framework developers'. No conflict-of-interest statement was found in the text (searched for conflict, competing, disclos). Table 2 (scores scaled between constant predictor = 0 and tuned Random Forest = 1) and Figure 1 are not recorded. Hardware: AWS m5.2xlarge (32 GB memory, 8 vCPUs) (Section 3). The authors say they cannot yet draw clear conclusions about which data properties explain per-dataset differences (Section 4). Superseded by the extended version arxiv-2207.12560."},

    {"id": "arxiv-2207.12560",
     "title": "AMLB: an AutoML Benchmark",
     "authors": ["Pieter Gijsbers", "Marcos L. P. Bueno", "Stefan Coors", "Erin LeDell", "Sébastien Poirier", "Janek Thomas", "Bernd Bischl", "Joaquin Vanschoren"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2207.12560", "code": "https://github.com/openml/automlbenchmark"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["automl-systems", "heterogeneous-ensembles"],
     "par": ["supervised"],
     "proposes": ["AMLB: an open-source tool that automates end-to-end AutoML evaluation (installation, data provisioning from OpenML, resource allocation on local/docker/AWS, scoring) with framework integrations written jointly with their developers",
                  "Two OpenML benchmark suites (71 classification tasks, 33 regression tasks) and an evaluation of 9 AutoML frameworks under 1 h and 4 h budgets",
                  "Analysis protocol: constant-predictor imputation of failures, critical-difference diagrams, scaled-performance boxplots, Bradley-Terry trees over data characteristics, inference-time trade-offs and failure categorization"],
     "claims": [
         ("Integration: the frameworks are integrated with the benchmark tool in agreement and jointly with each framework's developers to ensure correctness; the evaluation covers 9 well-known open-source frameworks (some with multiple configurations) on 71 classification and 33 regression tasks, restricted to tabular data (unstructured data are left to NAS and out of scope).",
          "Section 1.2",
          "The AutoML frameworks are integrated with the benchmarking tool in direct agreement and jointly with the framework’s developers to ensure correctness."),
         ("Selection limitation: because experiments run on machines without GPU, the authors focus on frameworks not significantly affected by its absence; Auto-Keras and AutoPyTorch, which gain large benefits from a GPU, are not evaluated since a CPU-only evaluation might give a pessimistic estimate. Auto-WEKA was excluded based on its 2019 performance and lack of updates; ML-Plan, mlr3automl and ML.NET were excluded due to significant technical problems, and the autoxgboost authors opted out.",
          "Section 3",
          "As our experiments are run on machines without GPU, we focus on AutoML frameworks which are not significantly affected by the lack thereof."),
         ("Dataset criteria: tasks come from earlier AutoML papers, competitions and ML benchmarks and must be sufficiently difficult (not solved by almost any algorithm), representative of real-world problems (few artificial and raw-pixel vision tasks), free of free-form text features, diverse in domain, and i.i.d. (temporal or repeated-measurement data are discarded); the airlines datasets violate the criteria but are included for historical reasons.",
          "Section 5.1.1",
          "If a problem is easily solved by almost any algorithm, it will not be able to differentiate the various AutoML frameworks."),
         ("Missing results: failures are not random but correlate with data properties such as size and class imbalance, so ignoring them (or imputing from other folds of the same framework) can reward frameworks that fail on harder tasks; the authors therefore impute missing results with the constant predictor, which they describe as very penalizing but fairer to well-behaved frameworks.",
          "Section 5.1.3",
          "Ignoring missing values thus means that AutoML frameworks may fail on harder tasks or folds and consequently obtain higher average performance estimates."),
         ("Framework configuration: frameworks are run in their default configuration except for a 'mode' declaring user intent (chosen by the frameworks' developers), the search runtime (plus one hour of leeway for data loading, prediction and cleanup that is not communicated to the frameworks), CPU-core and memory constraints, and the target metric (the same metric used for evaluation); further customization is intentionally prohibited to reflect typical practical use.",
          "Section 5.2.2",
          "The modes used to evaluate each AutoML framework is chosen by their developers."),
         ("Design limitations stated by the authors: performance differences cannot be attributed to any single design aspect (library, search space, preprocessing, search algorithm), only final-model results are recorded (anytime performance is approximated by the 1 h and 4 h budgets), qualitative features are not evaluated, and only a few developer-recommended modes are tried, so better results may be achievable by meta-tuning; they stress that the paper does not state which framework is ultimately best.",
          "Section 5.3",
          "Perhaps the biggest limitation of the design is the inability to attribute the performance of an AutoML framework to any one aspect of its design, as is often done with ablation studies."),
         ("Meta-learning overlap: since the benchmark data are public and well known, overlap with data used for meta-learning is likely. auto-sklearn's lookup can exclude the 39 datasets of the 2019 benchmark by name (identical data under other names cannot be ruled out), but auto-sklearn 2's portfolio and meta-model cannot exclude single datasets, so its results are described as likely optimistic and it is excluded from the critical-difference comparison.",
          "Section 5.3.3",
          "This ultimately means that the result of AUTO-SKLEARN 2 must be considered very carefully and are likely optimistic"),
         ("Findings stated in the text (CD diagrams, Friedman and Nemenyi tests after constant-predictor imputation): AutoGluon(B) and TPOT achieve the best and worst rank among AutoML frameworks in almost every setting; AutoGluon(B) is generally not significantly better than the second-best framework; the baselines rank worse than every AutoML framework except TPOT; and performance generally improves only slightly from 1 h to 4 h. The authors suspect other frameworks are limited by their search space (e.g. if stacking is required).",
          "Section 6.1",
          "Overall, we observe that AUTOGLUON(B) and TPOT respectively achieve the best and worst rank among AutoML frameworks in almost every setting with respect to model accuracy."),
         ("Conclusions on failures and trade-offs: analyzing scenarios in which frameworks fail to produce a model, the authors found that the main cause of failure was data set size, i.e. not all methods scale well; they also found large differences in inference time of the produced models, with the most accurate frameworks paying a large inference-time cost and not all frameworks producing Pareto-optimal models.",
          "Section 7",
          "and found that the main cause for failure was data set size."),
     ],
     "notes": "No venue recorded: the arXiv comment says 'UNDER REVIEW: Revised submission to JMLR, with updated results from June 2023', and the PDF header 'Journal of Machine Learning Research 1 (2000) 1-48, Submitted 4/00; Published 10/00, Editor: TBD' is the unfilled JMLR template. Results are from framework versions of June 2023, with some 2021 runs marked with an asterisk (Section 6). Folds: 10-fold cross-validation is mentioned in Appendix D. Conflict of interest: the organizers include developers of evaluated systems - LeDell and Poirier (H2O.ai) of H2O AutoML (LeDell and Poirier, 2020), and Gijsbers and Vanschoren of GAMA (Gijsbers and Vanschoren, 2021); Thomas co-authored autoxgboost (opted out). Developers of other evaluated frameworks (e.g. Nick Erickson, Matthias Feurer, Piotr Płoński) are thanked for feedback on the manuscript, and modes were chosen by each framework's developers. No explicit conflict-of-interest statement was found in the text (searched for conflict, competing interest, disclos, affiliat). NaiveAutoML was evaluated but excluded from the main analysis (Appendix E: a 5% execution timeout set by the benchmark authors was too strict; the framework authors confirmed). AutoGluon(HQIL) failures caused by a since-fixed calibration bug were imputed with AutoGluon(HQ) values rather than the constant predictor (Appendix D). Bradley-Terry tree findings and inference-speed figures are not recorded beyond the text. Hardware (Section 5.2.1): AWS m5.2xlarge, 32 GB memory, 8 vCPUs, 100 GB gp3 SSD. Metrics (Section 5.1.2): AUC (binary), log loss (multi-class), RMSE (regression); models are not calibrated unless the framework does so by default. Section 6.4: memory and time constraints are the main causes of errors, errors are more common in the classification suite, several frameworks fail on highly imbalanced data, and some frameworks exceed or stop far before the runtime limit. Section 6.3: AutoGluon(B)'s high accuracy comes with extremely slow inference, explained by its multi-layer stacking plus ensembling. Section 5.4: widely used benchmark datasets cannot in general be assumed truly unseen by developers. Earlier version: arxiv-1907.00909."},

    {"id": "arxiv-1908.00709",
     "title": "AutoML: A Survey of the State-of-the-Art",
     "authors": ["Xin He", "Kaiyong Zhao", "Xiaowen Chu"],
     "year": 2019, "venue": "Knowledge-Based Systems", "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/1908.00709"},
     "tasks": ["neural-architecture-search", "hyperparameter-optimization", "image-classification"],
     "fam": ["automl-systems", "bayesian-optimization", "multi-fidelity-optimization", "deep-learning"],
     "par": ["supervised", "reinforcement-learning"],
     "proposes": ["A survey organizing AutoML along the pipeline data preparation -> feature engineering -> model generation (search space; HPO and architecture optimization) -> model evaluation, with a focus on NAS",
                  "Taxonomies of NAS search spaces (entire-structured, cell-based, hierarchical, morphism-based) and architecture optimization methods (RL, evolution, gradient descent, surrogate-model-based, grid/random search, hybrids), plus a list of open problems"],
     "claims": [
         ("Pipeline taxonomy: the AutoML pipeline consists of data preparation, feature engineering, model generation and model evaluation; model generation is split into the search space (traditional ML models vs neural architectures) and optimization methods, the latter classified into hyperparameter optimization (training-related parameters) and architecture optimization (model-related parameters).",
          "Introduction",
          "As Figure 1 shows, the AutoML pipeline consists of several processes: data preparation, feature engineering, model generation, and model evaluation."),
         ("NAS taxonomy: commonly used search spaces are classified into entire-structured, cell-based, hierarchical and morphism-based; architecture optimization methods into reinforcement learning, evolution-based algorithms, gradient descent, surrogate model-based optimization and hybrid methods. The authors state their goal is breadth rather than a thorough investigation of every sub-topic.",
          "Introduction",
          "By reviewing NAS methods, we classify the commonly used search space into entire-structured [12, 13, 14], cell-based [13, 15, 16, 17, 18], hierarchical [19] and morphism-based [20, 21, 22] search space."),
         ("Gradient-based NAS failure mode (citing DARTS+ [159] and P-DARTS [128]): the skip-connect operation dominates at a later search stage in DARTS, making the network shallower and markedly degrading performance; DARTS+ adds an early-stop criterion and P-DARTS uses operation-level dropout to control skip-connects.",
          "Section 4.2.3",
          "For example, several studies [159, 128] have found that skip-connect operation domi-nates at a later search stage in DARTS, which causes the network to be shallower and leads to a marked deterioration in performance."),
         ("Comparability caveat: the CIFAR-10/ImageNet comparison tables collect results obtained under different settings such as training hyperparameters and data augmentation, so the authors say the comparison is not quite fair; they present NAS-Bench-101/201 and NAS-Bench-NLP as improving reproducibility.",
          "Section 6.1.2",
          "In other words, the comparison is not quite fair."),
         ("Search-evaluation gap: noting that random search is comparable to more sophisticated methods (e.g. DARTS and ENAS), the authors describe a usually large gap between the search stage and the evaluation stage, motivating the use of Kendall's tau between the two stages' rankings in several NAS studies.",
          "Section 6.1.1",
          "In other words, the architecture that achieves the best result in the training set is not necessarily the best one for the validation set."),
         ("Weight-sharing ranking problem (citing Yu et al. [11]): weight sharing degrades individual architectures' performance and negatively impacts the true performance ranking of candidates; to reduce weight coupling, many one-shot methods adopt random sampling of single architectures from the supernet.",
          "Section 6.3",
          "Yu et al. [11] experimentally showed that the weight-sharing strat-egy degrades the individual architecture’s performance and negatively impacts the real performance ranking of the candidate architectures."),
         ("Joint hyperparameter and architecture optimization: most NAS methods fix training hyperparameters during search and tune them afterwards, which the authors say may give suboptimal results because different architectures tend to fit different hyperparameters, making the ranking unfair (citing [233]); joint HAO is presented as a promising solution.",
          "Section 6.4",
          "However, this paradigm may result in suboptimal results as diﬀerent architectures tend to ﬁt diﬀerent hyperparameters, making the model ranking unfair [233]."),
         ("Open problem, reproducibility: many NAS algorithms have manually set implementation-level parameters that the original papers do not describe in detail; citing Yang et al. [123], the seed plays an important role in NAS experiments but most studies do not report it; resource consumption is another obstacle, which NAS-Bench datasets aim to reduce.",
          "Section 7.4",
          "For instance, Yang et al. [123] experimentally demonstrated that the seed plays an important role in NAS experiments; however, most NAS studies do not mention the seed set in the experiments."),
     ],
     "notes": "Affiliation: Hong Kong Baptist University. Venue from the arXiv journal_ref ('Knowledge-Based Systems, Volume 212, 5 January 2021, 106622') and comment; the v6 PDF footer reads 'Preprint submitted to Knowledge-Based Systems, April 19, 2021'. Year is the first arXiv version (2019); the PDF does not state the journal publication year (the journal_ref gives 2021). Other open problems listed in Section 7: flexible search spaces free of human bias (7.1), exploring more areas beyond image classification (7.2), interpretability (7.3), robustness to noisy/adversarial data (7.5), a complete AutoML pipeline (7.7; TPOT, Auto-WEKA and Auto-sklearn are described as searching only traditional ML models), and lifelong learning (7.8). The survey describes Zela et al. [34] as showing a weak correlation between performance after short and long training (Section 5.1); this is the survey's characterization, not checked against that paper. The CIFAR-10/ImageNet performance tables (Tables 3 and 4) are compilations of numbers reported in other papers and are not recorded. Section 6.3 also describes coupled one-shot optimization as introducing bias in architecture distribution and supernet weights (citing [197, 229]) and multimodel forgetting (citing [230]); Section 7.6 repeats joint HAO as an open problem. No experiments of its own; no conflict of interest identified."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
