import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_cpd_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1011.2932",
     "title": "Simulation-based Bayesian analysis for multiple changepoints",
     "authors": ["Jason Wyse", "Nial Friel"],
     "year": 2010, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1011.2932"},
     "tasks": ["change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["unsupervised"],
     "proposes": ["An MCMC sampler for retrospective multiple changepoint problems with an unknown number of changepoints: segment parameters are integrated out with conjugate priors, so the sampler moves on (k, changepoint positions) only, with add / delete / move (Gibbs or local random walk) steps whose acceptance ratios are Bayes factors, and with hyperpriors on the segment-length parameter p and the segment hyperparameters"],
     "claims": [
         ("Model assumptions: a changepoint at t means y_1..y_t and y_{t+1}..y_n are generated differently; conditional on a segmentation the data within each segment are independent, segment parameters are independent across segments, and a prior on the changepoint configuration (hyperparameter xi) and a prior on the number of changepoints k complete a hierarchical model similar to Green (1995).",
          "Section 2",
          "Conditional on a segmentation, the data within each segment is assumed independent."),
         ("Collapsing: with conjugate priors the segment parameters are integrated out, so the posterior over (k, z) is a product of closed-form segment marginal likelihoods and a dimension change needs no bijection (unlike RJMCMC). The first term of the acceptance ratio is the Bayes factor between the k+1 and k changepoint configurations, so sampling is a model search over a large space (the authors note up to 5 changepoints in a series of length 200 gives a space of dimension about 2.5 x 10^9).",
          "Section 3",
          "Noting this, it becomes apparent that sampling k and z is equivalent to a model search over large model space."),
         ("Sampler moves and cost: each sweep adds or deletes a changepoint (acceptance needs at most three marginal likelihoods) and moves a changepoint within its neighbours. The Gibbs position update costs O(tau_{j+1} - tau_{j-1}) and may be expensive for long series with distant changepoints or many changepoints, in which case a local random walk may be preferred; the authors suggest a mixture of the two should improve mixing.",
          "Section 4",
          "In this situation a local random walk update may be preferred."),
         ("Prior sensitivity: with a geometric segment-duration prior, the choice of p may impact the analysis: too small and small changes cannot be detected with high power, too large and spurious changepoints are inferred. A hyperprior on p (e.g. Beta, or non-informative Beta(1,1)) and on the segment hyperparameters gamma is therefore introduced and sampled within the MCMC sweep.",
          "Section 5",
          "If too large, then spurious changepoints are inferred."),
         ("Exact filtering recursions (Fearnhead 2006) give independent posterior samples and fast sampling, but their main weakness is that samples are conditional on fixed hyperparameters; updating gamma under a hyperprior would require recomputing recursions that are quadratic in n for each new value, which the authors describe as infeasible for any reasonably large posterior sample.",
          "Section 6",
          "The main weakness of this approach is that the generated samples are dependent on a ﬁxed value of the hyperparameters γ."),
         ("Validation on the coal-mining disasters data (Poisson model, weekly discretisation, Gamma(1, 200/7) intensity prior, the Fearnhead (2006) order-statistics position prior): 500,000 sweeps after 10,000 burn-in, keeping every 50th sample, took 10 seconds on a 2.5GHz processor; the posterior number of changepoints is described as almost identical to long RJMCMC runs and recursion-based methods (comparison shown in a figure).",
          "Section 7",
          "This took 10 seconds on a 2.5GHz processor."),
         ("Streakiness data (Bernoulli segments, Beta(1,1) success prior, geometric segment lengths with a uniform hyperprior on p, 100 sampler runs): the modal number of changepoints from filtering recursions computed over a grid of p is very sensitive to p, whereas the sampler with a hyperprior suggests two changepoints is most likely with relatively strong support for up to five; the authors question whether a fixed-p analysis would be useful to a practitioner.",
          "Streakiness in sports",
          "It is clear that the number of changepoints inferred in the ﬁltering recursions analysis is very sensitive to the value of p for this data."),
         ("Well-log data (outliers removed before analysis; Gaussian piecewise-constant mean with common variance): the modal number of changepoints from filtering recursions is sensitive to both p and sigma over small grids. The Fearnhead (2006) independence-proposal MCMC built from recursions at fixed hyperparameters had a high acceptance rate but a highly degenerate proposal, which the authors say could lead to highly biased sampling on other datasets.",
          "Application to Well-log data",
          "Only ten unique changepoint conﬁgurations were sampled in the 50,000 iterations of the MCMC scheme."),
         ("Conclusion of the comparison with a cost caveat: the proposed sampler explores the posterior with hyperpriors better than the independence proposal, but generating independent samples may be more costly in large datasets with many changepoints; including hyperpriors circumvents the sensitivity of the changepoint posterior to hyperparameter choices, which the authors call the main advantage.",
          "Application to Well-log data",
          "Nonetheless, it is clear that the inclusion of hyperpriors circumvents the sensitivity of posterior distribution of the changepoints to speciﬁcation of the hyperparameters."),
     ],
     "notes": "No venue is stated in the PDF and the arXiv comment ('17 pages') gives none, so venue is omitted. Evaluation uses three real datasets only (coal-mining, Tiger Woods streakiness, Well-log); no simulated data with known changepoints or accuracy metric was found in the text (searched simulat, synthetic, true changepoint). Comparisons with filtering recursions are qualitative (figures of modal number of changepoints / densities); no figure values recorded. Section numbers 2-7 are confirmed by the paper's outline paragraph; the streakiness and Well-log sections are given by name. A C implementation is offered on the first author's web page."},

    {"id": "arxiv-2006.15532",
     "title": "Scalable Bayesian Multiple Changepoint Detection via Auxiliary Uniformization",
     "authors": ["Lu Shaochuan"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2006.15532"},
     "tasks": ["change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["unsupervised"],
     "proposes": ["Attaching auxiliary continuous event times to the observations and modelling changepoints as a left-to-right continuous-time Markov chain on a countably infinite state space with segment-specific exponential run-length rates q_i (Gamma priors), then re-discretising via uniformization (Poisson-randomized blocking) so that a forward-filtering backward-sampling step inside a collapsed Gibbs sampler works on the uniform times rather than on every observation",
                  "A continuous-time Viterbi algorithm for MAP changepoint locations given the MAP number of changepoints"],
     "claims": [
         ("Prior on changepoints: the run length of the i-th segment is exponential with its own rate q_i, i.e. a latent left-to-right Markov chain on a countably infinite state space; this lets the recurrence rate vary across segments (avoiding the potential bias of a constant rate) and lets the number of changepoints grow without a fixed or upper bound as data arrive.",
          "Section 2",
          "We assume the run length of the i-th segment is exponentially distributed with a rate parameter qi."),
         ("Motivation: when changepoints are detected event by event (e.g. Fearnhead 2006 recursions), both computational and memory cost are quadratic in the number of observations, which the author calls prohibitive for large N; pruning or particle filtering are often applied to cope.",
          "Introduction",
          "In this case, both the computational cost and memory cost are quadratic to the number of observations, which is prohibitive for large N."),
         ("Cost and exactness: FFBS on the uniform times has computational and memory cost quadratic in the number of uniform times K rather than in n. If the rate matrix Q is known, changepoints can be sampled exactly; otherwise FFBS is embedded in a two-block Gibbs sampler that samples approximately from the posterior, with conjugate Gamma(a, b) priors on q_i whose hyperparameters are often specified manually.",
          "Section 3",
          "Firstly, both the computational cost and the memory cost of this version of FFBS algorithm are only quadratic to the number of uniform times K, instead of the number of observations, which is otherwise prohibitive when the ﬁltering probabilities are computed and stored in an event-by-event scale."),
         ("Limitation of the basic sampler: with a constant uniformization rate the algorithm is suitable only when run lengths are nearly regular, because highly variable q_i make the Poisson rate dominated by the largest one and inflate cost; a piecewise-constant nonhomogeneous rate simulated by thinning is used instead.",
          "Section 3",
          "The algorithm is suitable only when the run lengths between consecutive changepoints are nearly regular."),
         ("Approximation and bias: consecutive closely spaced uniform times are often sampled as separate changepoints ('knots'); they are pruned by repeating the backward-sampling step and keeping the furthest location, which the author says will possibly lead to slightly biased changepoint location estimates, as a price for avoiding inflated memory and computation. A truncation bound on the number of Poisson events is also imposed.",
          "Section 3",
          "This straightforward approach to pruning knots among changepoints will possibly lead to slightly biased estimation of the locations of changepoints, see simulation studies in the following sections."),
         ("Tuning: the resolution parameter k (uniformization rate = k times q_i) trades accuracy for cost: large k gives finer time scale and more accurate estimates but quadratically inflated memory and computation, small k a coarser scale and lower accuracy, so it needs careful selection.",
          "Section 3",
          "The tuning parameter needs to be carefully selected for a tradeoﬀbetween the accuracies and eﬃciencies."),
         ("Simulation (1200 Gaussian observations, 10 mean changepoints, known variance and conjugate mean prior, 6000 Gibbs iterations keeping the last 3000; k = 5, 11, 15 compared): remaining knots make the posterior of the number of changepoints tend to overestimate it, so the author recommends counting bumps in the posterior location histogram instead, and reports that the MAP locations from the continuous-time Viterbi algorithm were closer to the truth than posterior means.",
          "Simulation Studies",
          "Generally, the posterior of the number of changepoints summarized from this scheme tends to overestimate the number of changepoints."),
         ("Robustness issue: in the sparse long-series simulation (n = 10000 exponential observations, 3 changepoints) the algorithm occasionally broke down at low resolution because all filtering probabilities underflow to zero; the author says pilot runs might be necessary to choose the resolution parameter.",
          "Simulation Studies",
          "It is noted that the algorithm occasionally break down at low resolution (small k), due to that all the ﬁltering probabilities drop to zeros exponentially fast, causing underﬂow problems, which is diﬃcult to deal with for the moment."),
         ("Real data: for New Zealand deep earthquakes (674 events, quarterly Poisson counts over 70 years, k = 15) large uncertainties appear in both the number and locations of changepoints; the MAP number is 2 but the author deduces at least two or three changepoints. Well-log data were analysed after manually removing outliers. No comparison with other changepoint methods was found in the paper.",
          "Real Numerical Examples",
          "From the ﬁgure, it is observed that large uncertainties appear for the number of changepoints and their locations."),
     ],
     "notes": "No venue is stated in the PDF and the arXiv comment ('31 pages, 7 figures') gives none, so venue is omitted. Single author. Evaluation: two simulations and two real datasets, judged visually (posterior histograms, 95% HPD intervals in figures); no competing method is run and no runtime or convergence diagnostic is reported (searched compar, PELT, converge, diagnos, seconds, CPU). Section numbers 2-5 are confirmed by the outline paragraph; subsections are given by name. Simulated changepoint locations and MAP / posterior-mean estimates are written in the text but are not recorded here."},

    {"id": "arxiv-2211.14097",
     "title": "Bayesian variance change point detection with credible sets",
     "authors": ["Lorenzo Cappello", "Oscar Hernan Madrid Padilla"],
     "year": 2022, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2211.14097", "code": "https://github.com/lorenzocapp/prisca"},
     "tasks": ["change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["unsupervised"],
     "proposes": ["PRISCA (PRoduct of Individual SCAle parameters): multiple changes in the variance of a Gaussian sequence modelled as a product of L single-change scale models (multinomial location, Gamma prior on the scale), fitted by a backfitting recursion that is a mean-field variational approximation; each component gives a point estimate and a credible set of time instances",
                  "auto-PRISCA (heuristic choice of L) and extensions TF-PRISCA (smooth mean via trend filtering), AR-PRISCA (autoregression), fractional (power-posterior) PRISCA, non-conjugate priors and periodic data"],
     "claims": [
         ("Credible sets for a single change: the posterior over the change location (vector alpha) gives both the MAP point estimate and a credible set formed by the smallest set of time instances whose posterior probabilities sum above p; the set is not necessarily an interval.",
          "Section 2",
          "We highlight that the credible set built through the above is not necessarily an interval."),
         ("Theory (Theorem 1, single change point only): under alpha-mixing with exponentially decaying coefficients, a 2+delta moment condition (no Gaussianity), the change away from the boundaries (min{t0, T - t0} > cT), a non-negligible variance ratio and proper priors with pi_t of order 1/T, the MAP estimator localizes at rate sqrt(T) log^{1+eps} T, and at sqrt(T log^{1+eps} T) for independent Gaussian data (the Binary Segmentation rate); the authors state it remains unknown whether it is minimax optimal.",
          "Section 2.1",
          "However, in the scenario of independent Gaussian data, it remains unknown whether our estimator is minimax optimal as the Wild Binary Segmentation algorithm from Wang et al. (2021b)."),
         ("Model for multiple changes: L (an upper bound, L >= K needed) single-change components are multiplied; unlike product partition models the model enforces no minimum spacing and nothing prevents two components selecting the same instance, choices motivated by the need for a fast algorithm.",
          "Section 3",
          "Also note that, as opposed to PPM, model (9) does not enforce any minimum spacing between change points"),
         ("MCMC difficulty (citing Cappello et al. 2023, a paper co-authored by the first author): a Gibbs sampler for PRISCA is available but is expected to mix very slowly because the location vectors are highly dependent, and without a very good initialization MCMC chains in Bayesian change point detection often fail to converge.",
          "Section 3.2",
          "The deployment of MCMC in Bayesian change point detection commonly suffers from this problem, and lacking a very good initialization (e.g., the output of another change point detection procedure), chains often fail to converge; see Cappello et al. (2023)."),
         ("Decision rule and cost: a component counts as a detected change only if its credible set has at most T/2 instances (a threshold the authors call somewhat arbitrary but report results to be insensitive to); overlapping sets are removed in post-processing. Each iteration costs O(TL) worst case and few iterations are typically needed.",
          "Section 3.2",
          "Thus, for typical datasets Algorithm 1 has an effective overall computational complexity of O(TL)."),
         ("Approximation: Algorithm 1 is shown to be a mean-field VB approximation of the PRISCA posterior (block-wise coordinate ascent on the ELBO), which converges to a stationary point of the ELBO (Proposition 2, assuming 0 < a0, sigma^2 < infinity); the ELBO change is used as the stopping rule. VB is known to underestimate uncertainty.",
          "Section 3",
          "Proposition 1 and Corollary 2 establish that Algorithm 1 is a VB approximation to the posterior distribution of PRISCA, where the approximation lies in the fact that we have factorized the L effects using a mean-field approximation."),
         ("Simulation protocol (inspired by Killick et al. 2012): zero-mean Gaussian sequences, T in {200, 500, 1000}, K = floor(T^{1/2}/4) changes at random locations with minimum spacing min{T^{1/2}, 30}, segment variances lognormal, 300 data sets per T; compared with PELT, BINSEG and SEGNEI (R package changepoint) and the Bayesian MCP (given the true K); a change is detected if within min{T^{1/2}, 30}/2. PRISCA uses a0 = .001, L = floor(T/30). Credible sets do not attain the target p but are relatively close, which the authors attribute to VB underestimating uncertainty.",
          "Section 5",
          "We can see that PRISCA’s sets do not attain the targeted p level, but they are relatively close."),
         ("Hedge on the comparison: although PRISCA-based methods had the lowest bias in K and Hausdorff distance in this particular study, the authors explicitly do not claim superiority over state-of-the-art estimators, only comparable point-estimation accuracy plus uncertainty quantification, and orders-of-magnitude faster run time than the competing Bayesian methods tested.",
          "Section 5",
          "We do not claim that PRISCA is better than state-of-the-art estimators."),
         ("Limits of theory: consistency is proved only for the single change point problem; the authors explain that for Bayesian multiple change point estimators one defines a distribution over partitions whose marginal likelihoods are not closed-form, making theory difficult, which may explain the small theoretical literature.",
          "Section 7",
          "This challenge can explain the relatively small literature on theoretical results for Bayesian change point methodologies."),
     ],
     "notes": "No venue is stated in the PDF (v3, dated March 4, 2025) and the task gave no journal_ref, so venue is omitted. Main text read; supplementary sections only spot-checked (robustness, Fearnhead 2006 comparison). Possible conflict of interest: the MCMC non-convergence argument and the BLOCKS example rely on Cappello et al. (2023), whose author list includes the first author. Competitor settings: no penalty or tuning choice for PELT / BINSEG / SEGNEI was found in the text (searched default, penalt, MBIC, tuned, tuning). The supplementary comparison with Fearnhead (2006) uses a third-party Python implementation with post-processing thresholds 0.5 / 0.3 that the authors acknowledge as subjective and kept out of the main text. Under non-Gaussian noise, coverage of the sets drops substantially (power-posterior variants partially counterbalance it). Robustness checks report insensitivity to a0 and to a Half-Cauchy prior in their setting; exactness of the recursion is checked only for K = 1. Table values not recorded."},

    {"id": "arxiv-2102.12938",
     "title": "On Posterior consistency of Bayesian Changepoint models",
     "authors": ["Nilabja Guha", "Jyotishka Datta"],
     "year": 2021, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2102.12938"},
     "tasks": ["change-point-detection"],
     "fam": ["bayesian-changepoint-models", "linear-models"], "par": ["unsupervised"],
     "proposes": ["A hierarchical Bayesian changing linear regression model with independent Bernoulli(p_n) changepoint indicators and spike-and-slab priors for per-segment variable selection, with Bayes-factor posterior consistency results for the number and locations of changepoints and for the selected covariates (and for the covariate-free piecewise constant mean model)"],
     "claims": [
         ("Prior on changepoints: each observation carries an independent Bernoulli(p_n) changepoint indicator with p_n of order c_n / n, so c_n is the prior expected number of changepoints; letting c_n grow allows many changepoints for large n. Segment coefficients get spike-and-slab priors (or global-local shrinkage priors as an alternative).",
          "Mathematical/Asymptotic Framework",
          "Here, cn controls the expected numbers of change points apriori, and letting cn increase to inﬁnity provides ﬂexibility to model multiple and potentially large number of change points for large n."),
         ("Claimed contributions: posterior consistency for model selection and change point recovery via Bayes factors, for both the piecewise constant model and changing high-dimensional linear regression, and attainment of the O(n^-1) minimax localization rate of Frick et al. (2014) by the Bayes estimators.",
          "Introduction",
          "We also prove that the minimax rate of O(n−1) (Frick et al., 2014) is attained by the Bayes estimators for change point recovery."),
         ("Assumptions for the consistency theorems include uniformly bounded covariates (A1), coefficients bounded above and below (A2), a growth condition on the maximum model size q_n (A3), slab variance O(1) (A4), true change points at fixed fractions strictly inside (0, 1) (A5) and singular-value conditions on segment design matrices (A6); under A1-A6, Theorem 3 states that the Bayes factor of a model with a wrong number of change points against the true model goes to 0 in probability.",
          "Section 3",
          "(A1) The covariates Xj’s are uniformly bounded."),
         ("Theorem 4 (locations): for models with the true number of change points but some location off by more than eps_n, the Bayes factor against the true model goes to 0; eps_n of order n^-1 up to log factors is allowed if q_n grows logarithmically. The authors state the results hold under misspecification of the variance parameter, and that the bounded-covariate condition can be relaxed to sub-exponential tails.",
          "Section 3",
          "The results hold for misspeciﬁcation of variance parameter."),
         ("Covariate-free case (piecewise constant mean model): Theorem 4 holds for eps_n going to zero with eps_n at least n^-1 (log n)^2, which the authors describe as equivalent to the frequentist minimax rate up to logarithmic factors.",
          "Section 3",
          "which gives us rate equivalent to frequentist minimax rate up to logarithmic factors"),
         ("Unknown variance: Theorems 6-7 replace sigma^2 by a residual-based estimator. Theorems 7, 9, 11 and 12 are stated under assumptions 'A1 - A7', but only A1-A6 are listed in the text; no definition of A7 was found (searched A7).",
          "Section 3",
          "Theorem 7. Under A1 −A7, for (2.1) , for the empirical estimator of σ2,"),
         ("Simulation scope and protocol: the authors state the goal is not to show superiority over existing methods but satisfactory small-sample performance. Example 1 uses the Frick et al. (2014) piecewise constant signal (n = 497, 6 change points), unknown and possibly segment-specific variance, V = 1, I_i ~ Bernoulli(1/n), posterior summaries from 8,000 MCMC samples with the first 4,000 as burn-in, and is compared with PELT and the empirical Bayes method of Martin and Shen (2017) via figures only.",
          "Section 4",
          "Our goal here is not to establish superiority of the Bayesian method used here over extant methods"),
         ("Changing linear regression example (n = 250, p = 250, true change points at 0.3 and 0.7, spike-and-slab prior, 8,000 MCMC iterations): the text reports that almost 93% of posterior samples give the correct number of partitions and almost 90% select the right model; the authors say this agrees with their consistency theory.",
          "Section 4",
          "In particular, from Fig. 4, almost 93% of the posterior samples give the correct number of partitions (3), and almost 90% of the posterior samples select the right model."),
         ("Real data (weekly burglary and breaking-and-entering counts in Little Rock, 2017; square-root transformed and standardized): with no ground truth the analysis is described as preliminary and exploratory; detected change points mostly agree with PELT (BIC penalty in the figure) while the empirical Bayes method seems conservative and detects none.",
          "Real Data Applications",
          "As it is impossible to know if there should be any “true” change-points in 2017 data in the absence of additional information, this can be regarded as a preliminary exploratory analysis."),
     ],
     "notes": "No venue is stated in the PDF and the task gave no arXiv comment or journal_ref, so venue is omitted. Section 3 (theory) and Section 4 (simulation; Example 2 is §4.2) are confirmed by '§3' and '§4.2' cross-references; other locations use section names. The abstract says Gibbs sampling provides an efficient computational strategy, but no sampler details, run times or convergence diagnostics were found in the body (searched Gibbs, mixing, converge). The model builds on Datta et al. (2019), on which co-author Datta is an author (self-citation; not evaluated as a competitor). Results are asymptotic Bayes-factor consistency statements under the listed assumptions; the theory assumes Gaussian errors and independent observations (the AR(1) example is argued to remain covered if (A6) holds)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
