import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_kd_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1710.01878",
     "title": "To prune, or not to prune: exploring the efficacy of pruning for model compression",
     "authors": ["Michael Zhu", "Suyog Gupta"],
     "year": 2017, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1710.01878",
               "code": "https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/model_pruning"},
     "tasks": ["model-compression", "image-classification", "language-modeling"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["Automated gradual pruning: binary masks per pruned layer, the smallest-magnitude weights are masked to reach a sparsity s_t that rises from s_i to s_f over n pruning steps every Delta-t training steps along a cubic schedule s_t = s_f + (s_i - s_f)(1 - (t - t0)/(n Delta-t))^3, applied during training",
                  "A comparison of large-sparse (large model pruned) against small-dense (smaller dense model) at a comparable number of nonzero parameters / memory footprint on InceptionV3, MobileNets, PTB LSTM language models and GNMT-style seq2seq models"],
     "claims": [
         ("Research question: compare large models pruned to few nonzero parameters (large-sparse) with smaller dense models (small-dense) of identical memory footprint, motivated by the possibility that baseline models in earlier pruning reports are severely over-parameterized so that simply shrinking hidden units might give a similar size/accuracy trade-off.",
          "Abstract",
          "We compare the accuracy of large, but pruned models (large-sparse) and their smaller, but dense (small-dense) counterparts with identical memory footprint."),
         ("Method: for each pruned layer a binary mask of the weight's shape is added; weights are sorted by absolute value and the smallest-magnitude weights are masked to zero until sparsity s is reached; weights masked in the forward pass are not updated in back-propagation. Sparsity rises from s_i (usually 0) to s_f over n pruning steps starting at step t0 with frequency Delta-t following a cubic function, and masks stop changing once s_f is reached.",
          "Methods",
          "We introduce a new automated gradual pruning algorithm in which the sparsity is increased from an initial sparsity value si (usually 0) to a ﬁnal sparsity value sf over a span of n pruning steps,"),
         ("Schedule tuning: the authors report that varying the pruning frequency between 100 and 1000 steps had a negligible impact in their experience; pruning with an exceedingly small learning rate made recovery difficult, while pruning with too high a learning rate may prune weights before they converge, so the pruning schedule should be chosen closely with the learning-rate schedule. Pruning starts after a few epochs of training or from a pre-trained model.",
          "Methods",
          "so it is important to choose the pruning schedule closely with the learning rate schedule."),
         ("MobileNets on ImageNet: sparse MobileNets pruned from the dense width-1.0 model are compared with dense models of width multipliers 0.75, 0.5 and 0.25; the authors report that at a given number of nonzero parameters the sparse models outperform the dense ones (e.g. the 75% sparse model with 1.09 million parameters at 67.7% top-1 vs the dense 0.5 MobileNet with 1.32 million parameters at 63.7%). The standard convolution and depthwise layers (1.1% of parameters) are not pruned.",
          "Comparing large-sparse and small-dense models (MobileNets)",
          "We see that for a given number of non-zero parameters, sparse MobileNets are able to outperform dense MobileNets."),
         ("Training budget for the comparison (PTB LSTM language models): sparse models were pruned from the medium and large models to 80-97.5% sparsity using the same hyperparameters as the dense model of that size; the authors report the 90% sparse large model (6.6 million parameters, perplexity 80.24) outperforms the dense medium model (19.8 million parameters, perplexity 83.37). For MobileNet, pruning used the dense learning-rate schedule with a 10 times smaller initial learning rate.",
          "Comparing large-sparse and small-dense models (Penn Tree Bank language model)",
          "When pruning a model of a certain size, we use the same hyperparameters that were used for training the dense model of that size."),
         ("Limit of pruning: on PTB, pruning to 95% sparsity (20x) significantly degraded performance relative to 90% (10x); the authors suggest there is an optimal compression range and that one should train a dense model 5x-10x larger and prune it, rather than prune the largest model by 20x or more, assuming the two dense baselines do not differ much. They note slightly better results at 95%+ sparsity may be possible with more hyperparameter tuning, since they reused the dense configuration.",
          "Comparing large-sparse and small-dense models (Penn Tree Bank language model)",
          "Together, these results suggest that there is an optimal compression range when pruning."),
         ("NMT: because NMT training had high variance, three pruning schemes were tested (standard gradual pruning, 'layerwise constant' sparsity increased one layer at a time, and global magnitude pruning), and the scheme that performed best on average (layerwise constant) is the one reported; error bars are the standard deviation of BLEU over 10 randomly initialized, independently trained models.",
          "Comparing large-sparse and small-dense models (Google Neural Machine Translation)",
          "Overall, the layerwise constant pruning scheme performed best on average, so we report the results with the layerwise constant pruning scheme in Figure 4 and Table 4."),
         ("Storage overhead: the net memory footprint of a sparse model includes indexing structures (bit-mask: 1 bit per element; CSR(C): a 4-5 bit count per nonzero), which diminishes the achievable compression ratio; despite this the authors say large-sparse models appear to be more accurate at comparable footprint. All results use 32-bit floats; with reduced precision (e.g. 8-bit) the sparse-storage overhead would be a bigger fraction, and the interplay with quantization is deferred to future work.",
          "Discussion",
          "In spite of this overhead, large-sparse models appear to achieve higher accuracy than small-dense models with comparable memory footprint."),
         ("Hardware caveat: pruned models have sparse connection matrices, so efficient inference requires purpose-built hardware that can load sparse matrices and/or perform sparse matrix-vector operations, and the sparse representation adds storage overhead; the pruning is unstructured (no specific structure in the sparse weight tensors).",
          "Introduction",
          "The resulting pruned model typically has sparse connection matrices, so efﬁcient inference using these sparse models requires purpose-built hardware capable of loading sparse matrices and/or performing sparse matrix-vector operations"),
     ],
     "notes": "Affiliations: Stanford (Zhu, work done as a Google intern) and Google (Gupta). No venue is stated in the arXiv PDF or metadata; none recorded (other papers cite it as 'Zhu and Gupta [2018]', but no venue is confirmed here). Section numbers are not recorded; section names are used. Accuracy/perplexity/BLEU tables are not recorded; the numbers in claims are those written in the body text. NMT body text: the 90% sparse 1024-unit model is 'comparable to or outperforms' the dense 512-unit model (26.19 vs 26.05 EN-DE, 28.81 vs 28.88 DE-EN) with 23M vs 81M nonzero parameters. Hyperparameter search per scheme is not described beyond the statements recorded. Note the masking description: this paper states masked weights 'do not get updated in the back-propagation step', whereas arxiv-2005.07683 describes automated gradual pruning as allowing masked weights to be updated."},

    {"id": "arxiv-1810.02340",
     "title": "SNIP: Single-shot Network Pruning based on Connection Sensitivity",
     "authors": ["Namhoon Lee", "Thalaiyasingam Ajanthan", "Philip H. S. Torr"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1810.02340", "code": "https://github.com/namhoonlee/snip-public"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["Connection sensitivity: with auxiliary indicators c on each connection, the effect of removing connection j is approximated by g_j = dL(c * w)/dc_j at c = 1 (one forward-backward pass), normalized as s_j = |g_j| / sum_k |g_k|",
                  "SNIP: compute connection sensitivity on one mini-batch at a variance-scaling initialization, keep the top-kappa connections once (single shot) before training, then train the sparse network in the standard way"],
     "claims": [
         ("Criterion: the importance of each connection is measured independently of its weight via auxiliary indicator variables c; removing connection j changes the loss by Delta L_j, which is approximated by the derivative g_j of the loss with respect to c_j at c = 1, computable for all j in one forward-backward pass; connection sensitivity is |g_j| normalized by the sum over all connections, and only the top-kappa connections are kept.",
          "Connection sensitivity: architectural perspective",
          "Based on this hypothesis, we deﬁne connection sensitivity as the normalized magnitude of the derivatives:"),
         ("Critique of prior criteria: magnitude and Hessian-based saliency both depend on the scale of the weights, so they require pretraining and are very sensitive to architectural choices (e.g. normalization layers), and pruning is alternated with optimization many times, giving expensive prune-retrain cycles.",
          "Section 3",
          "Despite being popular, both of these criteria depend on the scale of the weights and in turn require pretraining and are very sensitive to the architectural choices."),
         ("Single-shot at initialization: because the saliency depends on the weights used to evaluate the derivative, the authors advocate variance scaling initialization so that the signal variance is the same throughout the network, and state they empirically show this makes the measure robust to architecture variations; the saliency can be computed on the whole training set, a mini-batch or the validation set, and the experiments use a single mini-batch.",
          "Section 4.2",
          "Thus, we advocate the use of variance scaling methods (e.g., Glorot & Bengio (2010)) to initialize the weights, such that the variance remains the same throughout the network."),
         ("Training cost is argued, not measured: the authors state that pruning once before training removes prune-retrain cycles and that in theory training could be an order of magnitude faster with sparse-matrix software; later they say training only the surviving parameters could potentially expedite training. No measured training-time or FLOP speedup was found in the text (searched for 'speed', 'FLOP', 'runtime').",
          "Section 3",
          "Therefore, our method eliminates the need for the expensive prune – retrain cycles, and in theory, it can be an order of magnitude faster than the standard neural network training as it can be implemented using software libraries that support sparse matrix computations."),
         ("Experimental setup: sensitivity is computed on a batch of 100 (MNIST) or 128 (CIFAR) examples; the pruned network is trained with SGD (momentum 0.9, weight decay 0.0005, initial learning rate 0.1 decayed by 0.1 every 25k or 30k iterations); 10% of the training data is held out as validation and the same standard augmentation is used for reference and sparse models on CIFAR. LeNet experiments are repeated 20 times with different seeds.",
          "Experiments",
          "We spare 10% of the training data as a validation set and used only 90% for training."),
         ("LeNet results stated in the text: errors comparable to the reference, degrading by approximately 0.7% and 0.3% when pruning 98% and 99% of the parameters in LeNet-300-100 and LeNet-5-Caffe; the compared methods (LWC, DNS, LC, SWS, SVD, OBD, L-OBS) are characterized as requiring pretraining, many pruning steps or additional hyperparameters. Whether the Table 1 baseline numbers were rerun or taken from the original papers was not found in the text (searched for 'reported', 'taken from').",
          "Experiments (Comparisons to existing approaches)",
          "We achieve errors that are comparable to the reference model, degrading approximately 0.7% and 0.3% while pruning 98% and 99% of the parameters in LeNet-300-100 and LeNet-5-Caffe respectively."),
         ("Comparison caveat for modern architectures (AlexNet, VGG, WRN variants on CIFAR-10; LSTM/GRU on sequential MNIST): the authors note that direct comparison with others is difficult because network specifications, learning policies, datasets and tasks differ, and they give only a few comparison points found in the literature.",
          "Experiments (Various modern architectures)",
          "We note of a few challenges in directly comparing against others: different network speciﬁcations, learning policies, datasets and tasks."),
         ("Dependence on initialization: comparing random normal, truncated normal and two variance scaling initializations (20 seeds, 90% sparsity), differences are marginal on LeNets but variance scaling is essential for the RNNs; for GRU without variance scaling the pruned networks fail to reach good accuracy even with different optimizers.",
          "Experiments (Effects of data and weight initialization)",
          "Overall, initializing with a variance scaling method seems crucial to making our saliency measure reliable and model-agnostic."),
     ],
     "notes": "Affiliation: University of Oxford. Venue from the PDF header ('Published as a conference paper at ICLR 2019') and the arXiv comment ('ICLR 2019'); year is the first arXiv version (2018). Section 3 and Section 4.2 are confirmed by cross-references in the PDF ('as discussed in Section 3', 'Refer Section 4.2'); other locations use section names. The method is evaluated only on small image/sequence classification benchmarks (MNIST, Fashion-MNIST visualizations, CIFAR-10, Tiny-ImageNet) in this paper. Table numbers and figure values are not recorded. A random-label experiment (LeNet-5-Caffe at 99% sparsity) is reported as a figure only: the pruned model does not fit random labels while the reference does."},

    {"id": "arxiv-2005.07683",
     "title": "Movement Pruning: Adaptive Sparsity by Fine-Tuning",
     "authors": ["Victor Sanh", "Thomas Wolf", "Alexander M. Rush"],
     "year": 2020, "venue": "NeurIPS 2020", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2005.07683", "code": "https://huggingface.co/mvp"},
     "tasks": ["model-compression", "natural-language-understanding"],
     "fam": ["pruning", "knowledge-distillation", "deep-learning"], "par": ["supervised"],
     "proposes": ["Movement pruning: learn importance scores S alongside the weights during fine-tuning, with masks Top_v(S) and a straight-through estimator so that dL/dS_ij = (dL/da_i) W_ij x_j; S accumulates -sum_t (dL/dW_ij) W_ij, i.e. it rewards weights moving away from zero",
                  "Soft movement pruning: a threshold mask M = (S > tau) with a regularizer lambda * sum sigma(S_ij) that controls sparsity"],
     "claims": [
         ("Motivation: magnitude pruning is described as highly effective in standard supervised learning but inherently less useful under transfer learning, because fine-tuned weights are mostly predetermined by the pretrained model, so magnitude selection cannot learn to prune based on the fine-tuning step.",
          "Introduction",
          "In transfer learning, weight values are mostly predetermined by the original model and are only ﬁne-tuned on the end task."),
         ("Definition: magnitude pruning uses zeroth-order information (|W|); movement pruning uses first-order information, retaining connections that move away from zero during training. Masks are Top_v(S) over learned scores S, the gradient through Top_v is approximated straight-through, so scores of masked weights are still updated; after T updates S_ij = -alpha_S sum_t (dL/dW_ij)^(t) W_ij^(t).",
          "Movement Pruning",
          "Intuitively, instead of selecting weights that are far from zero, we retain connections that are moving away from zero during the training process."),
         ("Soft movement pruning replaces the top-v% selection with a fixed global threshold tau and adds a regularizer lambda_mvp * sum sigma(S_ij) that pushes scores down, so lambda_mvp controls the penalty intensity and thus the sparsity level (rather than setting it directly); an L1 penalty on S was reported as harder to tune with similar results.",
          "Movement Pruning",
          "Here we replace hyperparameter v with a ﬁxed global threshold value τ that controls the binary mask."),
         ("Budget: task-specific pruning of BERT-base-uncased (about 84M parameters, embeddings frozen) on SQuAD v1.1, MNLI and QQP; for each task all pruning methods are fine-tuned for the same number of updates (6-10 epochs), with the cubic sparsity schedule of Zhu and Gupta plus a few cool-down steps for magnitude, movement and soft movement pruning; sparsity percentages are relative to BERT-base. A footnote says preliminary experiments suggested more pruning steps tended to improve end performance.",
          "Experimental Setup",
          "we ﬁne-tune the pre-trained model for the same number of updates (between 6 and 10 epochs) across pruning methods"),
         ("Baselines: Reweighted Proximal Pruning (RPP) and LayerDrop numbers are taken from their authors rather than rerun; for structured L0 regularization (McCarley, 2019) no implementation was found, so an unstructured L0 regularization baseline was used instead; mini-BERT models (Turc et al., 2019) are also compared.",
          "Experimental Setup",
          "For RPP and LayerDrop, we report results from authors."),
         ("Sparsity-dependent ranking: at low sparsity (more than 70% of weights remaining) magnitude pruning outperforms all methods with little or no loss versus the dense model, while movement pruning methods degrade quickly even at low sparsity; magnitude pruning performs poorly at high sparsity, and first-order methods are strong with less than 15% of weights remaining.",
          "Results",
          "magnitude pruning outperforms all methods with little or no loss with respect to the dense model whereas the performance of movement pruning methods quickly decreases even for low sparsity levels"),
         ("Hardware caveat: although movement pruning also beats fine-tuned mini-BERT models of the same size, the authors note that current hardware does not support optimized inference for sparse models, so for inference speed a small dense model such as mini-BERT might often be preferable; Appendix A.3 adds that their sparse models gave no significant inference speedup with standard PyTorch.",
          "Results",
          "We do note though that current hardware does not support optimized inference for sparse models: from an inference speed perspective, it might often desirable to use a small dense model such as mini-BERT over a sparse alternative of the same size."),
         ("Distillation combination: using the fine-tuned BERT-base model as teacher, the training objective is a convex combination of the training loss and a distillation loss on output distributions; the authors report that the relative ranking of pruning methods is unchanged while all performances increase.",
          "Results (Distillation further boosts performance)",
          "Overall, we observe that the relative comparisons of the pruning methods remain unchanged while the performances are strictly increased."),
     ],
     "notes": "Affiliations: Hugging Face (Sanh, Wolf) and Cornell (Rush). Venue from the PDF footer ('34th Conference on Neural Information Processing Systems (NeurIPS 2020)') and the arXiv comment. Conflict of interest: the acknowledgments state 'This work is conducted as part the authors’ employment at Hugging Face'; code is released through the Hugging Face Transformers library (Wolf et al., 2019, co-authored by Sanh and Wolf), and the distillation discussion cites the authors' own DistilBERT (Sanh et al., 2019). Section numbers are not recorded; section names are used. No mention of random seeds or run-to-run variance was found in the text (searched for 'seed'). Table 2/3 scores are not recorded. The paper describes automated gradual pruning (Zhu and Gupta) as 'allowing masked weights to be updated', whereas arxiv-1710.01878 itself states masked weights are not updated in back-propagation. Local vs global Top_v selection performed similarly except at high sparsity (body text: 2.3 F1 points with 3% remaining weights for movement pruning). A convergence argument for movement pruning is given in Appendix A.1."},

    {"id": "arxiv-2301.00774",
     "title": "SparseGPT: Massive Language Models Can Be Accurately Pruned in One-Shot",
     "authors": ["Elias Frantar", "Dan Alistarh"],
     "year": 2023, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2301.00774", "code": "https://github.com/IST-DASLab/sparsegpt"},
     "tasks": ["model-compression", "language-modeling"],
     "fam": ["pruning", "quantization", "large-language-models"],
     "proposes": ["SparseGPT: one-shot post-training pruning that solves the layer-wise reconstruction problem approximately, sharing a sequence of inverse Hessians (H_Uj)^-1 across rows with OBS-style partial updates so that the cost is O(d_hidden^3) per Transformer layer",
                  "Adaptive mask selection by iterative blocking (mask chosen every B_s = 128 columns by OBS error w^2/[H^-1]^2), extension to n:m semi-structured sparsity, and joint sparsification and quantization in the GPTQ column-wise framework"],
     "claims": [
         ("Problem: post-training pruning splits the model into layer-wise subproblems that minimize the l2 error between the dense layer output W X and the pruned output (M * W_hat) X on calibration inputs; optimizing the mask and the remaining weights jointly is NP-hard, so existing methods approximate it, typically by selecting a mask (e.g. by magnitude) and then reconstructing the remaining weights.",
          "Section 2",
          "Thus, exactly solving it for larger layers is unrealistic, leading all existing methods to resort to approximations."),
         ("Algorithmic idea: exact reconstruction needs a separate O(d_col^3) Hessian inversion per row because row masks differ, giving runtime scaling with the 4th power of the hidden dimension; SparseGPT reuses one sequence of inverse Hessians for all rows by only updating weights not yet processed (optimal partial OBS updates), giving O(d_col^3 + d_row d_col^2) in total.",
          "Section 3.1",
          "The key towards designing an approximation algorithm that is both accurate and efﬁcient lies in enabling the reuse of Hessians between rows with distinct pruning masks."),
         ("Mask selection: choosing p% per column would impose unnecessary structure, which the authors call problematic given a small number of highly sensitive outlier features in LLMs; instead the mask is chosen for B_s = 128 columns at a time by the OBS reconstruction error using the Hessian-sequence diagonals, taking previous weight updates into account (for a single column the criterion reduces to magnitude).",
          "Section 3.2",
          "We remove this disadvantage via iterative blocking."),
         ("Setup: all experiments are one-shot without fine-tuning; layers are sparsified sequentially on a single 80GB A100 (about 4 hours for the 175B models); calibration data are 128 random 2048-token segments from the first shard of C4, following GPTQ, so no task-specific data is seen. All linear layers except embeddings and head are pruned uniformly.",
          "Section 4",
          "All our experiments are performed in one-shot, without ﬁnetuning, in a similar setup to recent work on post-training quantization of GPT-scale models (Frantar et al., 2022a; Yao et al., 2022; Dettmers et al., 2022)."),
         ("Evaluation practice: the stated focus is accuracy relative to the dense baseline rather than absolute numbers (preprocessing may change absolute values); perplexity follows the HuggingFace procedure, zero-shot tasks use GPTQ's implementation based on the EleutherAI harness, and dense and sparse results are computed with the same code.",
          "Section 4",
          "All dense and sparse results were computed with exactly the same code, available as supplementary material, to ensure a fair comparison."),
         ("Baselines: layer-wise magnitude pruning (Zhu & Gupta) at all scales, and AdaPrune only for models up to 1B parameters, using the authors' own memory-optimized reimplementation (Frantar & Alistarh, 2022) with hyperparameters further tuned from those of the AdaPrune authors (about 3x faster without loss of solution quality, by their account).",
          "Section 4",
          "On models up to 1B parameters, we compare also against AdaPrune (Hubara et al., 2021a), the most efﬁcient among existing accurate post-training pruning methods."),
         ("Scale trend: magnitude-pruned models collapse across all scales (larger variants generally dropping faster), unlike smaller vision models; SparseGPT's perplexity loss shrinks with model size, and the slight improvement over dense at the largest scale 'seems to be dataset specific'. The authors speculate the trend of larger models being easier to sparsify is due to overparametrization and leave a detailed investigation to future work.",
          "Section 4.1",
          "In general, there is a clear trend of larger models being easier to sparsify, which we speculate is due to overparametrization."),
         ("Zero-shot evaluation caveat: zero-shot tasks are described as relatively noisy but more interpretable; e.g. 2:4 pruning appears noticeably more accurate than the dense model on Lambada despite being the most constrained pattern, and the authors say such effects average out over many tasks.",
          "Section 4.1",
          "These evaluations are known to be relatively noisy (Dettmers et al., 2022), but more interpretable."),
         ("Speedups are preliminary: unstructured sparsity speedups are measured end-to-end only on OPT-2.7B on CPU with the DeepSparse engine; for GPUs, 2:4 sparsity is benchmarked per layer with CUTLASS against cuBLAS on OPT-175B matrix shapes (batch of 2048 tokens), and the authors say end-to-end speedups will likely be slightly lower due to overheads such as attention.",
          "Appendix E",
          "end-to-end speedups will likely be slightly lower due to some extra overheads from e.g. attention"),
     ],
     "notes": "Affiliations: IST Austria (both) and Neural Magic (Alistarh). No venue is stated in the arXiv PDF or metadata (no comment/journal_ref); none recorded. Conflict of interest: Frantar and Alistarh are authors of GPTQ (arxiv-2210.17323, carded), OBC (Frantar et al., 2022b) and the AdaPrune reimplementation used as baseline (Frantar & Alistarh, 2022); SparseGPT inherits GPTQ's Cholesky and lazy-batch techniques, zero-shot evaluation uses GPTQ's implementation, and joint 50% + 4-bit is compared with GPTQ 3-bit. The CPU speedup study uses DeepSparse (NeuralMagic, 2022), the company of the second author's affiliation. Section numbers are from numbered headings. Ablations (Appendix A, OPT-2.7B): 5 calibration seeds gave 13.52 +- 0.075 perplexity; Hessian dampening 0.01 and blocksize 128 chosen; reconstruction error about 20% worse than exact reconstruction on average. Perplexity tables are not recorded."},

    {"id": "arxiv-2306.11695",
     "title": "A Simple and Effective Pruning Approach for Large Language Models",
     "authors": ["Mingjie Sun", "Zhuang Liu", "Anna Bair", "J. Zico Kolter"],
     "year": 2023, "venue": "ICLR 2024", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2306.11695", "code": "https://github.com/locuslab/wanda"},
     "tasks": ["model-compression", "language-modeling", "image-classification"],
     "fam": ["pruning", "large-language-models"],
     "proposes": ["Wanda (Pruning by Weights and activations): score S_ij = |W_ij| * ||X_j||_2 with the input-feature norm estimated on calibration data, removing the lowest-scoring weights per output row, layer by layer in one forward pass and with no weight update",
                  "Extension of the same score to N:M structured sparsity (compare every M consecutive weights per output)"],
     "claims": [
         ("Metric: for a linear layer, each weight's importance is |W_ij| times the l2 norm of the j-th input feature aggregated over all N x L tokens of the calibration data; the authors found l2 tended to work better than l1 and l-infinity norms, 'possibly' because it is smoother. Motivation is the emergent large-magnitude features in LLMs (citing Dettmers et al., 2022).",
          "Section 3",
          "For each individual weight, we propose to evaluate its importance by the product of its magnitude and the corresponding input feature norm."),
         ("Comparison group: weights are compared per output (s% removed from each output row) rather than per layer; the authors find this consistently better for LLMs, also for the magnitude metric, but not for image classifiers, suggesting the per-output observation might be unique to LLMs.",
          "Section 3",
          "However, we do not observe similar trend in image classification models, suggesting that our observations regarding pruning per output might be unique to LLMs."),
         ("Relation to SparseGPT: SparseGPT's metric |W|^2 / diag((X^T X + lambda I)^-1) reduces, with lambda = 0 and only the Hessian diagonal kept, to the square of the Wanda metric, which removes matrix inverses; the authors describe Wanda as analogous to OBD applied per neuron with a local output-reconstruction objective.",
          "Section 3",
          "The resulting metric in Equation 4 is the square of our proposed metric."),
         ("Setup: LLaMA 7B-65B and LLaMA-2 7B-70B; baselines are magnitude pruning and SparseGPT; to control the calibration-data factor Wanda uses exactly SparseGPT's calibration set (128 sequences from the C4 training set); all linear layers except the first embedding and final head are pruned with uniform sparsity; magnitude pruning is extended to N:M in the same way as Wanda.",
          "Experiments",
          "To control this variable factor, we use the exact same set of calibration data as SparseGPT, which consists of 128 sequences with context length size sampled from C4 training set (Raffel et al., 2020)."),
         ("Language modeling: without weight update Wanda outperforms magnitude pruning by a large margin and is on par with SparseGPT at unstructured 50% sparsity; for structured sparsity the comparison is mixed (SparseGPT better at 2:4 on smaller models such as 7B; Wanda more favorable on some larger models).",
          "Section 4.2",
          "The comparison between Wanda and SparseGPT is mixed for structured sparsity."),
         ("Large-sparse vs small-dense (zero-shot): for unstructured sparsity large sparse LLMs are often better than small dense ones of similar parameter count (e.g. 50% sparse LLaMA-65B 66.67% vs dense LLaMA-30B 65.38%), but for structured sparsity the trend is reversed without fine-tuning.",
          "Experiments (Zero-shot tasks)",
          "For structured sparsity, the trend is reversed: without any fine-tuning, large sparse LLMs have worse zero-shot performance than small dense LLMs in general."),
         ("Speed: computing the pruning metric is much faster than SparseGPT's (the text says it 'can be 300 times faster'); 2:4 inference speedup is a simulation of linear-layer matrix multiplication with CUTLASS on A6000 GPUs (around 1.6x on LLaMA-65B layers; end-to-end 1.24x on LLaMA-7B, 251ms vs 312ms), and the authors stress that this speedup comes from sparsity itself, not from their method.",
          "Experiments (Speedup)",
          "Last, we emphasize that the inference speedup is not unique to our pruning method but is delivered by the inherent power of sparsity for speeding up computation."),
         ("Weight update and extreme sparsity (LLaMA-7B): applying SparseGPT-style weight updates greatly improves magnitude pruning but brings no improvement to Wanda at unstructured 50% and 4:8 and a marginal one at 2:4; at 70% sparsity it improves Wanda's perplexity from 84.50 to 29.65, which still lags far behind the dense model (5.68).",
          "Analysis (Weight Update)",
          "However, the best pruned model (29.65) lags far behind the dense LLaMA-7B (5.68)."),
         ("Stated limit on older LLM families: there are cases where Wanda slightly underperforms SparseGPT, especially on OPT, suggesting a possible trade-off between pruning speed and accuracy for OPT, with the gap tending to shrink as model size grows; magnitude pruning fails catastrophically on OPT-13B and Pythia-12B even at 20% sparsity.",
          "Appendix B",
          "There are cases where Wanda slightly underperforms SparseGPT, especially for OPT models (see Table 10), suggesting that for OPT, there may be a tradeoff between pruning speed and pruning accuracy."),
     ],
     "notes": "Affiliations: Carnegie Mellon (Sun, Bair, Kolter), Meta AI Research (Liu), Bosch Center for AI (Kolter); Sun and Bair funded by Bosch. Venue from the PDF header ('Published as a conference paper at ICLR 2024') and arXiv comment; year is the first arXiv version (2023). Section 3 and Section 4.2 are confirmed by cross-references in the PDF ('as discussed in Section 3', 'our results in Section 4.2'); other locations use section/paragraph names. Conflict of interest: Zhuang Liu and Mingjie Sun co-authored 'Rethinking the value of network pruning' (Liu et al., 2019), cited here as an example of methods that retrain pruned networks; no evaluation of it is made. Whether SparseGPT was run with its official code is not stated (searched for 'official', 'implementation', 'codebase'). Appendix D.2 reports 5 calibration seeds with variance often lower for Wanda. Fine-tuning (LoRA within 1 GPU/12 hours; full fine-tuning within 4 GPUs/3 days) partly closes the gap to dense on LLaMA-7B. Appendix A: on ConvNeXt-B and DeiT-B (ImageNet-1K, one-shot, no retraining) per-layer comparison was slightly better than per-output; Wanda's metric beat magnitude especially at high sparsity (figure only). Perplexity/accuracy tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
