import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1712.00409",
     "title": "Deep Learning Scaling is Predictable, Empirically",
     "authors": ["Joel Hestness", "Sharan Narang", "Newsha Ardalani", "Gregory Diamos", "Heewoo Jun",
                 "Hassan Kianinejad", "Md. Mostofa Ali Patwary", "Yang Yang", "Yanqi Zhou"],
     "year": 2017, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1712.00409"},
     "tasks": ["scaling-laws", "language-modeling", "image-classification"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["methodology for measuring learning curves (generalization error vs training set size) and best-fit model size vs training set size on training-set shards"],
     "claims": [
         ("Contribution: the paper presents a large-scale empirical characterization of how generalization error and model size grow as training sets grow, tested on machine translation, language modeling, image processing and speech recognition.",
          "Abstract",
          "This paper presents a large scale empirical characterization of generalization error and model size growth as training sets grow."),
         ("Main empirical claim: in real applications the authors find the learning-curve exponent usually settles in a range that is shallower than the exponents predicted by prior theory and is unexplained by that theory.",
          "Introduction",
          "Unfortunately, in real applications, we ﬁnd empirically that βg usually settles between −0.07 and −0.35, exponents that are unexplained by prior theoretical work."),
         ("Architecture vs exponent: model improvements only shift the error and do not appear to affect the power-law exponent (hedged as 'do not appear').",
          "Abstract",
          "Further, model improvements only shift the error but do not appear to affect the power-law exponent."),
         ("Experimental range (protocol): each training set is randomly shuffled and split into shards spanning 2-3 orders of magnitude in steps of roughly 2x, all scored on a single validation set disjoint from every shard.",
          "Measuring model accuracy and size scaling with training data size",
          "We then subdivide T into shard sizes that span 2-3 orders of magnitude in steps of roughly 2×"),
         ("Model size vs data: the best-fit model size grows sublinearly with training set size (equivalently, the data set grows faster than linearly with best-fit model size).",
          "Abstract",
          "We also show that model size scales sublinearly with data size.", 1),
         ("Caveat: as training set sizes grow, optimization becomes harder and models run out of capacity, so the empirical error tends away from the power-law trend; the authors say a more exhaustive hyperparameter search would be needed to get closer to the trend.",
          "Neural machine translation",
          "We also note that as training set sizes grow, optimization becomes more difﬁcult and models run out of capacity, so the empirical error tends away from the power-law trend."),
         ("Limitation: the authors report running into compute limitations (most frequently GPU memory) for the largest data sets of each application domain.",
          "Operational implications",
          "After reviewing the tests performed for this work, we ﬁnd that we have run into compute limitations for the largest data sets of each application domain."),
     ],
     "notes": "Affiliation: all authors list Baidu Research (title page). Compute: a footnote states the data were collected from roughly 50 years worth of GPU time; the longest training sessions took up to 6 weeks (Operational implications). Domains/data as stated: WMT'16 German-English NMT, Billion Word word and character LMs (word LMs on shards from 0.1% up to 40%), ResNets on ImageNet shards from 1 to 800 images per class, Deep Speech 2 and attention models on 11,940 hours of speech. Speech is not covered by an existing task tag. Model setup (Section 3): after replicating SOTA results, the authors remove regularization that might reduce effective capacity (e.g. weight decay) and grid-search reduced model sizes to find the best-fit model per shard; 'model size' here is that best-fit size, e.g. word/character LMs grow with exponent about 0.7 in training set size (Section 4.2). Kaplan et al. (arxiv-2001.08361, Related Work) characterize this paper as finding super-linear scaling of dataset size with model size; this is the same direction as this paper's own statement that model size scales sublinearly with data size, and Kaplan et al. contrast it with their own sub-linear data-vs-model-size finding (which concerns the data needed to avoid overfitting)."},

    {"id": "arxiv-2001.08361",
     "title": "Scaling Laws for Neural Language Models",
     "authors": ["Jared Kaplan", "Sam McCandlish", "Tom Henighan", "Tom B. Brown", "Benjamin Chess", "Rewon Child",
                 "Scott Gray", "Alec Radford", "Jeffrey Wu", "Dario Amodei"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2001.08361"},
     "tasks": ["scaling-laws", "language-modeling", "efficiency-evaluation"],
     "fam": ["large-language-models", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["power-law scaling laws for Transformer LM cross-entropy loss in non-embedding parameters N, dataset size D and compute C, a joint L(N, D) form, and a compute-optimal allocation that favors larger models trained short of convergence"],
     "claims": [
         ("Main claim: language-model cross-entropy loss scales as a power law with model size, dataset size and training compute, with some trends spanning more than seven orders of magnitude.",
          "Abstract",
          "The loss scales as a power-law with model size, dataset size, and the amount of compute used for training, with some trends spanning more than seven orders of magnitude."),
         ("Experimental range: the relations are stated to hold across eight orders of magnitude in minimum compute, six in model size and over two in dataset size; the fitted numerical values are tied to the WebText2 training set (next sentence).",
          "Summary of Scaling Laws",
          "These relations hold across eight orders of magnitude in Cmin, six orders of magnitude in N, and over two orders of magnitude in D."),
         ("Compute counting: training compute is estimated as about 6N floating point operations per training token (forward pass about 2N, backward about twice that), excluding embedding parameters and context-dependent terms.",
          "Parameter and Compute Scaling of Transformers",
          "Accounting for the backwards pass (approximately twice the compute as the forwards pass), we then deﬁne the estimated non-embedding compute as C ≈6N ﬂoating point operators per training token."),
         ("Compute-optimal allocation: as the compute budget increases it should be spent primarily on larger models, without dramatic increases in training time or dataset size (a conclusion drawn from the paper's power-law fits on WebText2 Transformer LMs within the studied range).",
          "Summary of Scaling Laws",
          "As the computational budget C increases, it should be spent primarily on larger models, without dramatic increases in training time or dataset size (see Figure 3)."),
         ("Training protocol: unless otherwise noted, all training runs used a learning-rate schedule with a 3000-step linear warmup followed by cosine decay to zero (models were trained for a fixed number of steps unless otherwise noted).",
          "Training Procedures",
          "Unless otherwise noted, all training runs included in our data used a learning rate schedule with a 3000 step linear warmup followed by a cosine decay to zero."),
         ("Stated limit: far beyond the studied scales, the L(Cmin) and L(D) trends contradict each other, so the authors say the scaling laws must break down before that point (they conjecture the intersection marks maximal Transformer LM performance; values are highly uncertain).",
          "Contradictions and a Conjecture",
          "This implies that our scaling laws must break down before this point, but we conjecture that the intersection point has a deeper meaning: it provides an estimate of the point at which Transformer language models reach maximal performance."),
         ("Disagreement with prior work: the paper states that Hestness et al. ([HNA+17]) found super-linear scaling of dataset size with model size (i.e. data growing faster than model size), whereas this paper finds sub-linear scaling (data growing more slowly than model size; in Section 4 this is the dataset size needed to avoid overfitting as model size grows).",
          "Related Work",
          "Note, however, that [HNA+17] found super-linear scaling of dataset size with model size, whereas we ﬁnd a sub-linear scaling."),
     ],
     "notes": "Affiliation: all authors list OpenAI (Kaplan also Johns Hopkins University). Range (Section 3 list): model size from 768 to 1.5 billion non-embedding parameters, dataset size from 22 million to 23 billion tokens; WebText2 with BPE vocabulary 50257 and 1024-token context. N excludes vocabulary and positional embeddings, which the authors say gives cleaner scaling laws. Appendix C (Caveats) lists: no solid theoretical understanding; low confidence in Bcrit far outside the explored range; small-data regime not thoroughly investigated and no regularization/data augmentation experiments; C ≈ 6NBS omits n_ctx terms; learning rates tuned but other hyperparameters (e.g. initialization scale, momentum) may not have been; no experiments with higher learning rates for runs not trained to convergence."},

    {"id": "arxiv-2010.14701",
     "title": "Scaling Laws for Autoregressive Generative Modeling",
     "authors": ["Tom Henighan", "Jared Kaplan", "Mor Katz", "Mark Chen", "Christopher Hesse", "Jacob Jackson",
                 "Heewoo Jun", "Tom B. Brown", "Prafulla Dhariwal", "Scott Gray", "Chris Hallacy", "Benjamin Mann",
                 "Alec Radford", "Aditya Ramesh", "Nick Ryder", "Daniel M. Ziegler", "John Schulman",
                 "Dario Amodei", "Sam McCandlish"],
     "year": 2020, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2010.14701"},
     "tasks": ["scaling-laws", "image-classification"],
     "fam": ["deep-learning"], "par": ["self-supervised"],
     "proposes": ["power-law plus constant scaling laws (irreducible + reducible loss) for autoregressive Transformers on images, video, multimodal image-text and math, with a near-universal optimal-model-size vs compute exponent"],
     "claims": [
         ("Main claim: in four domains (generative image modeling, video, multimodal image-text, math problem solving) autoregressive Transformers improve smoothly with model size and compute, following a power-law plus constant scaling law.",
          "Abstract",
          "In all cases autoregressive Transformers smoothly improve in performance as model size and compute budgets increase, following a power-law plus constant scaling law."),
         ("Compute-optimal model size: the optimal model size depends on the compute budget through a power law whose exponents are nearly universal across data domains.",
          "Abstract",
          "The optimal model size also depends on the compute budget through a power-law, with exponents that are nearly universal across all data domains."),
         ("Compute counting: C is defined theoretically as 6NE, with N the non-embedding parameter count and E the total tokens processed in training (a footnote explains the factor 6 as 2 for add-multiply times 3 for forward and backward passes); the critical-batch-size adjustment used in Kaplan et al. was not made here.",
          "Compute Scaling and Optimal Model Sizes",
          "We deﬁne C theoretically rather than empirically, and approximate7 it as C ≡6NE where N is the non-embedding parameter count (model size) and E = SB is the total number of tokens processed during training"),
         ("Caveat on convergence: L(N) uses the loss at (or as close as feasible to) convergence, but the largest models did not fully converge, so the authors warn against over-interpreting the irreducible loss as entropy and the reducible loss as KL divergence.",
          "Model Size Scaling and Aspect Ratios",
          "Thus caution is warranted when interpreting L(N) trends according to equation (1.2) and identifying the irreducible loss as an entropy, and the reducible loss as a KL divergence."),
         ("Caveat on extrapolation: the sub-linear data-vs-model-size conclusion for compute-optimal training is stated together with the caution that no models were trained in a regime where compute-optimal training actually implies D much smaller than N.",
          "Compute Scaling and Optimal Model Sizes",
          "As a word of caution, we have yet to train models in a regime where compute optimal training actually implies D ≪N numerically."),
         ("Attribution: the language-modeling compute scaling results are taken from GPT-3 ([BMR+20]) and the language Nopt(C) from Kaplan et al. ([KMH+20]), not from new experiments in this paper.",
          "Summary of scaling laws (Table 1 caption)",
          "The compute scaling results and data for language are from [BMR+20], while Nopt(C) comes from [KMH+20]."),
         ("Downstream: when generative image models are finetuned for ImageNet classification, classification loss follows a power law in model size even beyond where generative loss approaches its irreducible value; the authors conclude that approaching the irreducible loss does not necessarily indicate diminishing returns for representation quality.",
          "Summary of Results",
          "We conclude that the approach to the irreducible loss does not necessarily indicate diminishing returns for representation quality or semantic content."),
     ],
     "notes": "Affiliation: all authors list OpenAI (Kaplan also Johns Hopkins University). Data as stated: about 10^8 YFCC100M web images at 8x8/16x16/32x32 (plus VQ-encoded 64x64), about 7x10^5 web videos (~100 hours) VQ-encoded, web-curated image/text pairs, and procedurally generated math problems; sparse attention is used for image/video models. The math compute scaling law may be affected by weight decay (Table 1 caption). The paper also studies the L(D) vs L(C) inconsistency first noted in Kaplan et al. (Section 6) using low-resolution image models. Footnote 8 notes that accounting for inference compute could make the optimal model size somewhat smaller."},

    {"id": "arxiv-2106.04560",
     "title": "Scaling Vision Transformers",
     "authors": ["Xiaohua Zhai", "Alexander Kolesnikov", "Neil Houlsby", "Lucas Beyer"],
     "year": 2021, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2106.04560"},
     "tasks": ["scaling-laws", "image-classification"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["characterization of the error-rate vs compute frontier of ViT as a double-saturating power law", "improved large-scale ViT training recipe and the ~2B-parameter ViT-G/14"],
     "claims": [
         ("Experimental range: models from five million to two billion parameters, datasets from one million to three billion training images, and compute from below one to beyond 10,000 TPUv3 core-days; the frontier is characterized on two datasets (the paper names public ImageNet-21k and proprietary JFT-3B elsewhere).",
          "Introduction",
          "In particular, we experiment with models ranging from ﬁve million to two billion parameters, datasets ranging from one million to three billion training images and com-pute budgets ranging from below one TPUv3 core-day to beyond 10 000 core-days."),
         ("Cost measurement: since all models were trained on TPUv3, total compute is measured in TPUv3 core-days (not FLOPs).",
          "Core Results",
          "All models are trained on TPUv3, thus total compute is measured in TPUv3 core-days."),
         ("Main claim: with enough training data, the ViT performance-compute frontier roughly follows a saturating power law.",
          "Conclusion",
          "We demonstrate that the performance-compute frontier for ViT models with enough training data roughly follows a (saturating) power law."),
         ("Compute allocation: for ViT within the studied range, staying on the frontier requires scaling compute and model size together; not increasing model size when extra compute is available is suboptimal.",
          "Conclusion",
          "Crucially, in order to stay on this frontier one has to simultaneously scale compute and model size; that is, not increasing a model’s size when extra com-pute becomes available is suboptimal."),
         ("Sample efficiency: bigger models reach the same error with fewer seen images, and the authors suggest that with sufficient data, training a larger model for fewer steps is preferable, mirroring results in language modeling and machine translation.",
          "Big models are more sample efficient",
          "Our results suggest that with sufﬁcient data, training a larger model for fewer steps is preferable."),
         ("Data limitation: the scaling-law study uses the proprietary JFT-3B dataset; to make the insights more reliable, the authors verify that the scaling laws also apply on public ImageNet-21k.",
          "Discussion (Limitations)",
          "This work uses the proprietary JFT-3B dataset for the scaling laws study."),
         ("Scope caveat: the conclusions may not generalize beyond the studied scale or beyond the ViT model family.",
          "Conclusion",
          "Note, that our conclusions may not necessarily generalize beyond the scale we have studied and they may not generalize beyond the ViT family of models."),
     ],
     "notes": "Affiliation: Google Research, Brain Team, Zürich (title page). Evaluation: representation quality measured by few-shot linear transfer on frozen weights and by full fine-tuning (ImageNet; Pets, CIFAR-100, Birds in the appendix). The paper observes that at the largest size the models appear to start to saturate and fall behind the power-law frontier (Section 2.1). Societal impact paragraph mentions the energy cost of the scaling study but gives no energy figure. Broken Neural Scaling Laws (arxiv-2210.14891, Appendix A.9) reuses data from Figure 2 of this paper and describes the upstream task as ViT pretraining on subsets of JFT-300M; this paper's Figure 2 caption does not name the dataset, while its text discusses dataset sizes from 30M up to 3B images for that figure (Section 2.1) and says the scaling-law study uses the proprietary JFT-3B (Section 3.3, Discussion). The two descriptions appear to differ; not resolved here."},

    {"id": "arxiv-2210.14891",
     "title": "Broken Neural Scaling Laws",
     "authors": ["Ethan Caballero", "Kshitij Gupta", "Irina Rish", "David Krueger"],
     "year": 2022, "version": "arXiv v17",
     "links": {"arxiv": "https://arxiv.org/abs/2210.14891"},
     "tasks": ["scaling-laws"],
     "fam": ["deep-learning"],
     "proposes": ["broken neural scaling law (BNSL): a smoothly broken power-law functional form for scaling behavior"],
     "claims": [
         ("Contribution: a smoothly broken power-law functional form (BNSL) that the authors say accurately models and extrapolates how evaluation metrics vary with compute, parameters, dataset size, input size, training steps or upstream performance.",
          "Abstract",
          "We present a smoothly broken power law functional form (referred to by us as a broken neural scaling law (BNSL)) that accurately models and extrapolates the scaling behaviors of deep neural networks"),
         ("Evaluation protocol: the functional form is fit to smaller-x points and evaluated on held-out larger-x points for extrapolation; tabulated extrapolation errors are RMSLE.",
          "Empirical results: fits & extrapolations of functional forms",
          "black points are points used for fitting a functional form, green (gray if color blind) points are held-out points used for evaluating extrapolation of functional form fit to the black points, & a red line is BNSL that has been fit to black points."),
         ("Baseline provenance: the percentages of tasks won by the competing functional forms M1-M4 in the benchmark comparison were obtained via correspondence with the authors of Alabdulmohsin et al. (2022), not recomputed in this paper.",
          "Empirical results (Table 2 caption)",
          "Numbers for M1, M2, M3, and M4 were obtained via correspondence with authors of Alabdulmohsin et al. (2022).", 5),
         ("Data provenance: much of the scaling data is taken from other papers; e.g. the compute-on-x-axis vision experiment uses data from Figure 2 of Zhai et al. (2021) and compares BNSL with M3, the form proposed there.",
          "Appendix A.9",
          "The experimental scaling data was obtained from Figure 2 of Zhai et al. (2021), and as a result in Table 6 we compare extrapolation of BNSL to the extrapolation of M3 (which was proposed in Zhai et al. (2021))"),
         ("Emergence framing: the authors define the 'emergent' / 'breakthrough' / 'phase transition' behaviors advertised in recent papers as any scaling behavior with more than zero breaks in BNSL.",
          "The limit of the predictability of scaling behavior",
          "We define all these quoted phrases as any scaling behaviors with greater than 0 breaks"),
         ("Limit of predictability: if a sufficiently sharp break occurs at a scale sufficiently larger than the largest fitted point, there is currently no way to extrapolate past that break.",
          "The limit of the predictability of scaling behavior",
          "2) If an additional break of sufficient sharpness happens at a scale that is sufficiently larger than the maximum (along the x-axis) of the points used for fitting, there does not (currently) exist a way to extrapolate the scaling behavior after that additional break."),
         ("Stated limitation: a small number of (x, y) samples sometimes may not suffice to fit and extrapolate BNSL, and collecting many samples can be costly; the authors suggest entities with more compute may get more accurate extrapolations.",
          "Ethics statement",
          "A small number of samples sometimes may not be sufficient to accurately fit and extrapolate the BNSL functional form, and obtaining a large number of such samples can sometimes be costly."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2023. Affiliations: Mila (McGill, University of Montreal) and University of Cambridge. Fitting (Appendix A.6): scipy.optimize.brute grid search then scipy.optimize.curve_fit minimizing MSLE; the number of breaks can be chosen by holding out the largest fitting points (not the extrapolation points) as a validation set. The abstract gives a code location written in the text as 'github.com/ethancaballero/broken neural scaling laws' (underscores lost in text extraction), so no code link was recorded. No paradigm tag was assigned because the paper fits curves to results from many settings (supervised, self-supervised, RL). A.9 describes the Zhai et al. (2021) data as ViT pretrained on subsets of JFT-300M; Zhai et al. (arxiv-2106.04560) say their scaling-law study uses the proprietary JFT-3B, although their Figure 2 caption does not name the dataset (see that card's notes). A.9 also describes the x-axis as compute (FLOPs), whereas Zhai et al. measure compute in TPUv3 core-days."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model size, data, compute and performance (scaling laws, compute-optimal training, cost measurement); carded by a subagent. Results tables not recorded; claims only.")
