import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ssl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1901.09005",
     "title": "Revisiting Self-Supervised Visual Representation Learning",
     "authors": ["Alexander Kolesnikov", "Xiaohua Zhai", "Lucas Beyer"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1901.09005", "code": "https://github.com/google/revisiting-self-supervised"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["deep-learning"], "par": ["self-supervised"],
     "proposes": ["A large-scale study of four pretext tasks (Rotation, Exemplar, Jigsaw, Relative Patch Location) across ResNet50 v1/v2, RevNet50 and VGG19-BN with several widening factors, evaluated by linear logistic regression on ImageNet and Places205"],
     "claims": [
         ("Evaluation protocol: a linear logistic regression is trained on representations extracted from the frozen network at the pre-logits level (other layers investigated in Section 4.5); for fast evaluation it is trained with L-BFGS on precomputed representations, while the comparison to prior literature uses SGD with momentum and data augmentation.",
          "Section 3.3",
          "We extract the representation from the (frozen) network at the pre-logits level, but investigate other possibilities in Section 4.5."),
         ("To avoid overfitting to the official ImageNet validation split, all studies report accuracy on the authors' own validation split of 50,000 images held out from the training split; only the comparison with the literature (Table 2) uses the official validation set. Places205 is handled the same way.",
          "Section 3.4",
          "In order to avoid overﬁtting to the ofﬁcial validation split, we report numbers on our own validation split (50 000 random images from the training split) for all our studies except in Table 2, where for a fair comparison with the literature we evaluate on the ofﬁcial validation set."),
         ("Similar models often give representations with significantly different linear-evaluation performance, and neither the ranking of architectures is consistent across pretext methods nor the ranking of methods across architectures; VGG19-BN is consistently the worst although it performs similarly to ResNet50 models on standard supervised benchmarks.",
          "Section 4.1",
          "Importantly, neither is the ranking of architectures consistent across different methods, nor is the ranking of methods consistent across architectures."),
         ("Evaluating the same ImageNet-trained models on Places205 with the same protocol, the authors observe that the ranking of models is consistent with the ImageNet ranking, which they take as indicating that their findings generalize to new datasets.",
          "Section 4.1",
          "ranking of models evaluated on Places205 is consistent with that of models evaluated on ImageNet, indicating that our ﬁndings generalize to new datasets."),
         ("Replacing the linear model by an MLP with one hidden layer (1000 channels) gives only marginal improvement and mostly unchanged relative performance, so the authors conclude a linear model is adequate for evaluation; they note that linear evaluation requires the relevant information to be linearly separable, which is not necessarily a prerequisite for a useful representation.",
          "Section 4.3",
          "Figure 3 clearly shows that the MLP provides only marginal improvement over the linear evaluation and the relative performance of various settings is mostly unchanged."),
         ("Pretext-task accuracy is a good proxy for downstream ImageNet accuracy only when the architecture is fixed; it cannot reliably be used to select the architecture, and the authors call for other label-free model-selection mechanisms.",
          "Section 4.4",
          "but it can unfortunately not be used to reliably select the model architecture."),
         ("Which layer is probed matters: as in prior observations for AlexNet, representation quality in VGG19-BN deteriorates towards the end of the network, whereas in ResNets it consistently increases up to the final pre-logits layer; the authors hypothesize this is due to residual units being invertible under some conditions.",
          "Section 4.5",
          "In contrast, we observe that this is not the case for models with skip-connections: representation quality in ResNet consistently increases up to the ﬁnal pre-logits layer."),
         ("Linear evaluation trained with SGD (batch 2048, initial learning rate 0.1 decayed twice by 10x, first decay after 30, 120 or 480 epochs followed by 40 more epochs) keeps improving after a very large number of epochs (about 500 gave higher accuracy); the authors conclude SGD optimization hyperparameters of the probe play an important role and need to be reported.",
          "Section 4.7",
          "Thus, we conclude that SGD optimization hyperparameters play an important role and need to be reported."),
     ],
     "notes": "Affiliation: Google Brain, Zurich. No venue is stated in the PDF (arXiv v1); none recorded. Self-supervised pre-training: 35 epochs on ImageNet without labels (Appendix A). Results tables (Tables 1-6) and figure values not recorded. The probe-protocol findings come from Rotation (Section 4.7), with the other tasks in the appendix (Figure 9)."},

    {"id": "arxiv-1905.01235",
     "title": "Scaling and Benchmarking Self-Supervised Visual Representation Learning",
     "authors": ["Priya Goyal", "Dhruv Mahajan", "Abhinav Gupta", "Ishan Misra"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1905.01235", "code": "https://github.com/facebookresearch/fair_self_supervision_benchmark"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["deep-learning"], "par": ["self-supervised"],
     "proposes": ["Scaling Jigsaw and Colorization pretext tasks along data size (up to YFCC-100M), model capacity (AlexNet vs ResNet-50) and problem complexity",
                  "A benchmark suite of 9 transfer datasets/tasks (linear classification on Places205/VOC07/COCO2014, low-shot classification, visual navigation, object detection with frozen conv body, surface normal estimation) with a consistent evaluation setup"],
     "claims": [
         ("The benchmark is based on the principle that a good representation transfers to many different tasks and does so with limited supervision and limited fine-tuning; the authors view self-supervised learning as learning features rather than as an initialization method, so they perform limited fine-tuning.",
          "Introduction",
          "Our benchmark is based on the following principle: a good representation (1) transfers to many different tasks, and, (2) transfers with limited supervision and limited ﬁne-tuning."),
         ("The authors report inconsistencies across previous methods' evaluations (image crops, weight re-scaling, pre-processing, longer fine-tuning schedules) that affect final performance, and argue that a consistent setup with hyperparameters set fairly for all methods is needed to separate better representations from better transfer optimization.",
          "Section 6 (footnote 1)",
          "We discovered inconsistencies across previous methods (different image crops for evaluation, weights re-scaling, pre-processing, longer ﬁne-tuning schedules etc.) which affects the ﬁnal performance."),
         ("Linear-classification protocol for VOC07/COCO2014: one linear SVM per class on frozen, L2-normalized features (from several layers: after every conv layer for AlexNet, the last layer of every residual stage for ResNet-50), with the cost chosen per class by 3-fold cross-validation over 26 values on the training data; Places205 uses linear classifiers trained with SGD following Zhang et al.",
          "Appendix D.1",
          "We use 3-fold cross-validation to choose the cost parameter per class and then further calculate the mean average precision."),
         ("The authors found that SGD-trained linear classifiers, although common practice, can give significantly different results depending on optimization hyperparameters (number of iterations, learning-rate decay) because of slow convergence; they obtained more robust results with dual coordinate descent (linear SVM, LIBLINEAR) and use it for VOC07 and COCO2014.",
          "Appendix D.6",
          "Although, using SGD based Linear Classiﬁers is a common practice [80] to evaluate representations, we found that optimization hyperparameters can lead to signﬁcantly different results."),
         ("Pre-training domain matters: for Jigsaw, ImageNet-22k pre-training transfers to VOC07 as well as YFCC-100M, while on Places205 YFCC-1M transfers as well as ImageNet-22k; a similar trend holds for Colorization. A possible explanation offered is that ImageNet is closer to VOC07 (object-centric) and YFCC to Places205 (scene-centric), which motivates evaluating on varied domains and tasks.",
          "Section 5",
          "A possible explanation for this beneﬁt is that the domain (image distribution) of ImageNet is closer to VOC07 (both are object-centric) whereas YFCC is closer to Places205 (both are scene-centric)."),
         ("Low-shot linear SVM evaluation (k positives per class, 5 independent training samples, ResNet-50 best layer res4): a significant gap between supervised and self-supervised features remains, larger at small sample sizes (stated as 30 points at k=1 versus 20 points full-shot on Places205); for lower layers the self-supervised features are competitive.",
          "Section 6.2",
          "This gap is much larger at lower sample size, e.g., at k=1 it is 30 points for Places205, whereas at higher values (full-shot in Table 3) it is 20 points."),
         ("Full fine-tuning is excluded from the benchmark suite (reported only as a legacy task) because, the authors argue, it evaluates not only the representation but also the initialization and optimization method.",
          "Section 7",
          "We argue that this view evaluates not only the quality of the representations but also the initialization and optimization method."),
         ("ImageNet-1k linear classification is excluded from the benchmark suite: evaluating on ImageNet-1k does not test generalization of the supervised baseline trained on it, and most self-supervised methods pre-train on ImageNet-1k, so pre-training and evaluating in the same domain (here on identical images) biases evaluation; results are still reported for comparison.",
          "Section 7",
          "Hence, evaluating also on the same dataset (ImageNet-1k) does not test generalization of the supervised baseline."),
     ],
     "notes": "Affiliation: Facebook AI Research. No venue is stated in the PDF (arXiv v2); none recorded. Investigation setup (Section 4) uses VOC07 linear SVMs on conv4 (AlexNet) / res4 (ResNet-50). The abstract concludes that current methods 'do not seem to learn effective high level semantic representations'; the paper also states self-supervised features are competitive on VOC07 detection with frozen conv body or full fine-tuning (same training schedule for supervised and self-supervised). Tables 3-9 values are not readable in the text dump and not recorded."},

    {"id": "arxiv-2011.13377",
     "title": "How Well Do Self-Supervised Models Transfer?",
     "authors": ["Linus Ericsson", "Henry Gouk", "Timothy M. Hospedales"],
     "year": 2020, "venue": "CVPR 2021", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2011.13377"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["A transfer benchmark of 13 released ImageNet-pre-trained self-supervised ResNet50 models (plus a supervised baseline) on 40 downstream tasks: many-shot linear and fine-tuned recognition, few-shot recognition (incl. CD-FSL), VOC detection, NYUv2 surface normals and ADE20K segmentation, with correlation analysis against ImageNet top-1"],
     "claims": [
         ("Headline finding: ImageNet top-1 accuracy is highly correlated with transfer to many-shot recognition, but increasingly less so for few-shot recognition, object detection and dense prediction.",
          "Abstract",
          "We ﬁnd ImageNet Top-1 accuracy to be highly correlated with transfer to many-shot recognition, but increasingly less so for few-shot, object detection and dense prediction."),
         ("Setup caveat: the authors use released pre-trained weights and cannot control pre-training, so the models differ in training length, data augmentation, loss and additional architectural elements; all share the ResNet50(1x) backbone pre-trained on ImageNet.",
          "Preliminaries",
          "As we cannot control the pre-training setup, there are differences in how long the models were trained for, what data augmentation they applied, what loss they trained with and what additional architectural elements they used."),
         ("Many-shot protocol: hyperparameters are selected on a validation set (author-defined or a random 20% of training data), then the model is retrained on training plus validation and evaluated on test. The linear probe is multinomial logistic regression on 2048-d frozen features, no augmentation, L2 constant chosen from 45 log-spaced values, optimized with L-BFGS; fine-tuning runs 5,000 steps of SGD with Nesterov momentum with learning rate, weight decay and augmentation chosen by grid.",
          "Appendix A.2",
          "The optimal hyperparameters were selected on the validation set, after which we retrained the model on all training and validation images."),
         ("Few-shot protocol: a nearest-centroid classifier (prototypical networks) on frozen backbone features, 5-way 20-shot (5- and 50-shot in the appendix), 15 query images per class, 600 random episodes with 95% confidence intervals, on the Kornblith datasets (except VOC2007) and the four CD-FSL datasets.",
          "Section 4.2",
          "Our evaluation uses a nearest-centroid classiﬁer (also known as Prototypical Networks [50]) on the features extracted from the ResNet50 backbones."),
         ("Few-shot results differ from many-shot linear results: the supervised model dominates on the Kornblith datasets except DTD and Flowers, while on the CD-FSL datasets several self-supervised models outperform it; the authors summarize that self-supervision lags for low-domain-shift few-shot transfer but beats supervision for larger domain shifts.",
          "Section 4.2",
          "Summarising these results, we see that self-supervision still lags behind for low domain shift few-shot transfer while it consistently beats supervision for larger domain shifts."),
         ("For surface normal estimation, the authors trained all methods for a fixed number of iterations because NYUv2 has no validation split, noting that their numbers are therefore not directly comparable to Goyal et al. [16], who selected checkpoints on test performance.",
          "Section 4.4 (footnote 2)",
          "Given the absence of a validation split for NYUv2, we considered it better practice to train all methods for a ﬁxed number of iterations."),
         ("Conclusion: ImageNet performance is broadly representative of downstream natural-image recognition, but not reliably representative of unstructured image recognition or spatially sensitive tasks (detection, surface normals, semantic segmentation); the authors suggest SSL researchers adopt a wider range of benchmarks.",
          "Discussion",
          "ImageNet performance is not reliably representative of downstream performance on unstructured image recognition, or other spatially sensitive tasks such as detection, surface normal prediction and semantic segmentation."),
         ("Stated limitation: the study could not compare ImageNet-pre-trained self-supervised representations with domain-specific self-supervised representations trained on each target dataset.",
          "Discussion",
          "Most notably, we were not able to compare the value of self-supervised representations transferred from ImageNet to domain-speciﬁc self-supervised representations trained on each target dataset."),
     ],
     "notes": "Affiliation: University of Edinburgh (Hospedales also Samsung AI Research, Cambridge). Venue CVPR 2021 from the arXiv comment given by the caller; the PDF itself does not state a venue. InsDis and PIRL weights come from PyContrast rather than the original authors (Appendix A.1). Correlations (Figures 1-2, Pearson r on logit-transformed accuracies and Spearman rho) are shown only as figures; values not recorded. The paper also reports that no single method dominates and that SSL features seem to discard colour information (conjectured to be due to colour augmentation)."},

    {"id": "arxiv-1907.13625",
     "title": "On Mutual Information Maximization for Representation Learning",
     "authors": ["Michael Tschannen", "Josip Djolonga", "Paul K. Rubenstein", "Sylvain Gelly", "Mario Lucic"],
     "year": 2019, "venue": "ICLR 2020", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1907.13625", "code": "https://github.com/google-research/google-research/tree/master/mutual_information_representation_learning"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding", "deep-learning"], "par": ["self-supervised", "unsupervised"],
     "proposes": ["Controlled experiments (MNIST top/bottom halves, CIFAR10 in the appendix) showing that representation quality under linear evaluation is only loosely connected to the MI estimate",
                  "An interpretation of InfoNCE with a symmetric separable critic as the multi-class K-pair (triplet-style) metric-learning loss"],
     "claims": [
         ("Central claim: the success of MI-maximization methods (InfoNCE / NWJ estimators between views) cannot be attributed to properties of MI alone; it strongly depends on inductive biases in the encoder architecture and in the parametrization of the MI estimator.",
          "Abstract",
          "we argue, and provide empirical evidence, that the success of these methods cannot be attributed to the properties of MI alone, and that they strongly depend on the inductive bias in both the choice of feature extractor architectures and the parametrization of the employed MI estimators."),
         ("Evaluation setup: representations of the top half of MNIST images (views = top and bottom halves) are evaluated by a linear classifier (SAGA, scikit-learn) trained with all training labels; estimator values and accuracies are averaged over 20 runs on the test set; a linear classifier on raw top-half pixels gives about 85% and a simple supervised MLP or ConvNet about 94%.",
          "Biases in approximate information maximization (Setup)",
          "Throughout, IEST values and downstream classiﬁcation accuracies are averaged over 20 runs and reported on the testing set (we did not observe large gaps between the training and testing values of IEST)."),
         ("With always-invertible encoders (RealNVP), the true MI is constant for any parameters, yet the estimator value and downstream linear accuracy increase during training, which the authors interpret as the estimators biasing the encoder toward representations useful for linear classification.",
          "Large MI is not predictive of downstream performance",
          "Despite the fact that MI is maximized by any instantiation of g1 and g2, IEST and downstream accuracy increase during training, implying that the estimators provide gradient feedback leading to a representation useful for linear classiﬁcation."),
         ("Conversely, an invertible encoder trained adversarially (without an MI estimator) to make linear classification hard attains globally maximal MI but worse linear accuracy than raw pixels; the authors conclude information content alone does not guarantee a useful geometry of the representation space.",
          "Large MI is not predictive of downstream performance",
          "The information content alone is not sufﬁcient to guarantee a useful geometry in the representation space."),
         ("Critic capacity: higher-capacity critics give tighter MI bounds, but representations trained with an MLP critic barely beat the pixel baseline, whereas bilinear and separable critics clearly do; the simple bilinear critic, despite the smallest NWJ value (loosest bound), gives better downstream performance than separable and MLP critics.",
          "Section 3.2",
          "INWJ testing value, the simple bilinear critic leads to a better downstream performance than the higher-capacity separable and MLP critics."),
         ("Encoder architecture: when MLP and ConvNet encoders are trained to reach the same target estimator value t (t = 2, 4), ConvNet encoders give clearly better linear accuracy for both estimators, while both architectures reach essentially the same accuracy (about 94%) when trained end-to-end with supervision.",
          "Section 3.3",
          "Despite matching lower bounds, ConvNet encoders lead to clearly superior classiﬁcation accuracy, for both INCE and INWJ."),
         ("If negative samples are not drawn independently (as in some practical methods, e.g. CPC patches from the same image), the InfoNCE estimator is in general neither a lower nor an upper bound on MI (proved in Appendix D; in a synthetic Gaussian experiment both estimators exceeded the true MI), so the connection to MI may vanish.",
          "Section 4",
          "Hence, the connection to MI under improper negative sampling is no longer clear and might vanish completely."),
         ("On the evaluation protocol, the authors note that some works report only marginal gains under non-linear evaluation and stress that a highly non-linear evaluation may give better downstream performance but defeats the purpose of learning efficiently transferable representations; they also argue critics, encoders and evaluation protocol are mostly chosen independently and should be co-designed.",
          "Conclusion (Going beyond the widely used linear evaluation protocol)",
          "We stress that a highly-nonlinear evaluation framework may result in better downstream performance, but it defeats the purpose of learning efﬁciently transferable data representations."),
     ],
     "notes": "Affiliation: Google Research, Brain Team (Rubenstein also University of Cambridge / MPI-IS). Venue from the PDF header 'Published as a conference paper at ICLR 2020'. Experiments are small-scale (MNIST, CIFAR10 in Appendix G), all results shown as figures; no numbers recorded beyond those stated in body text. Section numbers used only where confirmed by cross-references (Sections 3.2, 3.3, 4); other sections cited by heading."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
