import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-2205.02302",
     "title": "Machine Learning Operations (MLOps): Overview, Definition, and Architecture",
     "authors": ["Dominik Kreuzberger", "Niklas Kühl", "Sebastian Hirschl"],
     "year": 2022, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2205.02302"},
     "tasks": ["mlops"],
     "fam": ["automl-systems"],
     "proposes": ["Definition of MLOps plus nine principles, nine technical components, seven roles and a technology-agnostic end-to-end architecture/workflow, derived from a mixed-method study (structured literature review, tool review, semi-structured expert interviews)"],
     "claims": [
         ("Method: mixed-method study combining a structured literature review (search in May 2021: 1,864 retrieved, 194 screened in detail, 27 selected, all peer-reviewed), a tool review, and semi-structured interviews (June to August 2021) with eight experts identified via LinkedIn under a theoretical sampling approach, conducted until no new categories and concepts emerged (theoretical saturation).",
          "Methodology",
          "In total, we conduct eight interviews with experts (α - θ), whose details are depicted in Table 2 of the Appendix."),
         ("Definition: MLOps is a paradigm (best practices, concepts, development culture) covering end-to-end conceptualization, implementation, monitoring, deployment and scalability of ML products; the authors describe it as an engineering practice drawing on ML, software engineering (especially DevOps) and data engineering.",
          "Conceptualization",
          "MLOps (Machine Learning Operations) is a paradigm, including aspects like best practices, sets of concepts, as well as a development culture when it comes to the end-to-end conceptualization, implementation, monitoring, deployment, and scalability of machine learning products."),
         ("Monitoring component (C9): continuously monitors model serving performance (e.g., prediction accuracy); monitoring of ML infrastructure, CI/CD and orchestration is also required (both statements are backed in the paper by literature citations and interviewee markers). Tool examples, each attributed to interviewees, include Prometheus with Grafana, the ELK stack and TensorBoard.",
          "Technical Components",
          "The monitoring component takes care of the continuous monitoring of the model serving performance (e.g., prediction accuracy)."),
         ("Alert path in the proposed workflow: the monitoring component observes serving performance and infrastructure in real time, and once a threshold is reached (e.g., low prediction accuracy detected) the information is forwarded via a feedback loop to upstream receivers (experimental stage, data engineering zone, scheduler).",
          "Architecture and Workflow",
          "Once a certain threshold is reached, such as detection of low prediction accuracy, the information is forwarded via the feedback loop."),
         ("Retraining triggers: when the monitoring component detects drift in the data, the scheduler triggers the automated ML workflow pipeline for retraining (continuous training); drift can be detected with distribution comparisons, and retraining can also be triggered by new feature data or run periodically.",
          "Architecture and Workflow",
          "Retraining is not only triggered automatically when a statistical threshold is reached; it can also be triggered when new feature data is available, or it can be scheduled periodically."),
         ("Model registry and promotion: retrained models are pushed to the model registry, the metadata store records model version and status (e.g., staging or production-ready), and switching a well-performing model's status from staging to production hands it over for deployment via the continuous deployment pipeline.",
          "Architecture and Workflow",
          "Once the status of a well-performing model is switched from staging to production, it is automatically handed over to the DevOps engineer or ML engineer for model deployment."),
         ("Operational challenge reported (citing literature [18] and interviewee θ): a constant stream of new data forces retraining capabilities, a repetitive task requiring a high level of automation; the resulting artifacts need strong governance and versioning of data, model and code (further citations).",
          "Open Challenges",
          "Also, a constant incoming stream of new data forces retraining capabilities."),
     ],
     "notes": "Affiliations (PDF): KIT (Kreuzberger, Kühl) and IBM (Hirschl), with the footnote 'This paper does not represent an official IBM statement'. Per Table 2 (Appendix), the eight interviewees' industries are: sporting goods/retail (α), IT services/cloud provider/cloud computing (β), cloud provider (γ, δ, ε), consulting company (ζ), conglomerate (η), music/audio streaming (θ). The tool review covers 11 tools (Figure 1; Table 1 of the Appendix). Searched the full text for rollback, roll back, fallback, fall back, canary, shadow, A/B, replace, revert, previous model, champion and challenger: none found (the only 'switch' hit is the staging-to-production status switch in c6); the architecture describes promotion (staging to production), monitoring with threshold-based feedback, and retraining, but no rollback to a previous model version and no switch to a fallback model at serving time. The Introduction says the paper concludes with 'limitations, and outlook', but no limitations section or limitation statement was found in the text. No experiments. Tag note: the family tag automl-systems is a PLACEHOLDER and does not describe this paper (that tag is for AutoML systems that search over and ensemble model types; this is a conceptual MLOps study with no AutoML system). No existing family tag fits; a user decision on a new tag is pending."},

    {"id": "arxiv-2011.09926",
     "title": "Challenges in Deploying Machine Learning: a Survey of Case Studies",
     "authors": ["Andrei Paleyes", "Raoul-Gabriel Urma", "Neil D. Lawrence"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2011.09926"},
     "tasks": ["mlops"],
     "fam": ["automl-systems"],
     "proposes": ["Survey of published ML deployment case studies, review papers and lessons-learned reports, mapping reported challenges to the stages of the ML deployment workflow of Ashmore et al. (data management, model learning, model verification, model deployment) plus cross-cutting aspects"],
     "claims": [
         ("Main claim: by mapping the challenges found in reports to the steps of the deployment workflow, the authors show that practitioners face issues at each stage of deployment.",
          "Abstract",
          "By mapping found challenges to the steps of the machine learning deployment workﬂow we show that practitioners face issues at each stage of the deployment process."),
         ("Evidence base: case study papers (single deployment project), review papers of a field/industry, and lessons-learned papers, mostly limited to the last five years with a few exceptions; the authors state they conducted no interviews themselves.",
          "Introduction",
          "We have not conducted any interviews ourselves as part of this study."),
         ("Monitoring (citing Sculley et al.): the ML community is said to be early in understanding which data and model metrics to monitor and how to trigger alarms when they deviate; monitoring evolving input data, prediction bias and overall performance is called an open problem.",
          "Monitoring",
          "Monitoring of evolving input data, prediction bias and overall performance of ML models is an open problem."),
         ("Outlier detection (citing Klaise et al.): outlier detection is presented as a key instrument to flag predictions that cannot be used in production; deploying the detector is itself a challenge because labeled outlier data are scarce, making training semi-supervised or unsupervised.",
          "Monitoring",
          "Klaise et al. [72] point out the importance of outlier detection as a key instrument to ﬂag model predictions that cannot be used in a production setting."),
         ("Case study cited (Ackermann et al., early intervention system for two US police departments): data integrity checks, anomaly detection and performance metrics had to be built from scratch; the survey takes this as a sign that out-of-the-box tooling of end-to-end platforms often does not fit problem specifics.",
          "Monitoring",
          "However, the authors explain that they had to build all these checks from scratch in order to maintain good model performance."),
         ("Updating: besides when to retrain (concept drift, linked to monitoring) and how to deliver the model artifact (continuous delivery), the survey notes (citing Bansal et al. and Srivastava et al.) that updates may harm users or downstream systems through behavior changes, e.g. backward-incompatible updates.",
          "Updating",
          "While updating is necessary for keeping a model up to date with recent ﬂuctuations in the data, it may also inﬂict damage on users or downstream systems because of the changes in the model’s behavior, even without causing obvious software errors."),
         ("Stated limitation: the set of reviewed challenges is far from complete; identifying further (especially non-technical) challenges, possibly via interviews with industry representatives, is left as further work.",
          "Further Work",
          "Even though the set of challenges we reviewed covers every stage of the ML deployment workﬂow, it is far from complete."),
     ],
     "notes": "PDF states: ACM Computing Surveys, 2022, https://doi.org/10.1145/3533378. Affiliations (PDF): University of Cambridge (Paleyes, Lawrence) and Cambridge Spark (Urma, a company). Acknowledgments: funding for A.P. and N.L. from a Senior AI Fellowship of the Alan Turing Institute and UKRI. Model-deployment challenges are grouped as integration, monitoring (feedback loops, outlier detection, custom design tooling) and updating (concept drift, continuous delivery) in Table 1. The survey points to dataset-shift detection libraries/services (Rabanser et al. methods implemented in Alibi Detect, Azure ML, AWS SageMaker) in its Discussion of potential solutions. Searched the full text for rollback, roll back, fallback, fall back, canary, shadow, A/B, replace, revert, previous model, champion and challenger: no description of rolling back to a previous model or switching to a fallback model at serving time. The only related hits are 'replacement' in other senses (simulation is not a full replacement for real-world testing; an ML solution replacing a previous pen-and-paper method in the Firebird case study; replacing micro-service architectures with dataflow architectures). Updating (c6) is discussed in terms of when to retrain, continuous delivery and backward compatibility, not rollback. The Klaise et al. [72] paper cited in c4 is carded as arxiv-2007.06299. Conclusion notes a relative shortage of deployment experience reports in the academic literature. Tag note: the family tag automl-systems is a PLACEHOLDER and does not describe this paper (that tag is for AutoML systems that search over and ensemble model types; this survey only mentions AutoML tools briefly in its Discussion of potential solutions and evaluates no AutoML system). No existing family tag fits; a user decision on a new tag is pending."},

    {"id": "arxiv-2007.06299",
     "title": "Monitoring and explainability of models in production",
     "authors": ["Janis Klaise", "Arnaud Van Looveren", "Clive Cox", "Giovanni Vacanti", "Alexandru Coca"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2007.06299"},
     "tasks": ["mlops", "dataset-shift-detection", "model-explanation"],
     "fam": ["two-sample-tests", "dimensionality-reduction-for-shift", "feature-attribution"],
     "par": ["post-hoc"],
     "proposes": ["Position/overview of four post-deployment areas (performance monitoring, input-data metrics, outlier and drift detection, explanations) with deployment patterns: asynchronous monitoring via KNative eventing with KFServing/Seldon Core, and a /predict + /explain design for black-box explainers"],
     "claims": [
         ("Framing (citing Diethe et al.): a big MLOps challenge is designing systems that monitor live deployments and take action or raise alerts when events affecting model performance occur.",
          "Introduction",
          "One of the big challenges in MLOps is to design systems that monitor live deployments and take action or raise alerts when events impacting model performance are encountered (Diethe et al., 2019)."),
         ("Without labels (citing Breck et al.), statistics of input data and output predictions are monitored as a proxy for model performance; labels for live data are seldom available in time due to operational and financial constraints.",
          "Introduction",
          "In the absence of labels it is critical to monitor the statistics of input data and output predictions as these can serve as a proxy for model performance (Breck et al., 2017)."),
         ("Alert thresholds: even with label-dependent metrics, a threshold or decision rule for alerts must be set; such thresholds need domain knowledge and are hard to set to limit false alarms, and the authors say alternatives based on change-point detection may prove more robust (citing Bifet, 2017).",
          "Performance and metrics",
          "Such thresholds require domain knowledge and can be difﬁcult to set appropriately to limit the number of false alarms."),
         ("Outlier detection is motivated by prior work (citing Recht et al., Engstrom et al., Hendrycks & Dietterich; Guo et al.; Lakshminarayanan et al.) showing models often fail to generalize outside the training distribution and are typically not well calibrated, which can lead to overconfident out-of-distribution predictions; flagged predictions are ones the authors say should not be trusted or used in production. They add that unsupervised anomaly detection on real-world data is far from solved.",
          "Outlier detection",
          "Outlier detection is therefore key to ﬂag anomalies whose model predictions we cannot trust and should not use in a production setting."),
         ("Acting on drift: drift detection (described with citations, e.g. Rabanser et al. 2019 for the pre-processing: dimensionality reduction followed by a two-sample test such as MMD with permutation p-values, or feature-wise KS tests with Bonferroni/FDR correction) informs the user when the model should be retrained, which the authors call especially important when performance feedback is not readily available.",
          "Drift detection",
          "Drift detection informs the user when the model should be retrained which is especially important in applications where model performance feedback is not readily available."),
         ("Stated open problem: relating the label-independent measures from metrics, outlier and drift detectors more directly to model performance.",
          "Conclusion",
          "One of the main open research topics is to more directly relate the label-independent measures obtained from the metrics, outlier and drift detectors to the model performance."),
         ("Affiliation: all five authors carry the affiliation Seldon Technologies Ltd (seldon.io e-mail addresses). Self-citation of tools: Seldon Core (Cox et al., 2018), Alibi (Klaise, Van Looveren, Vacanti, Coca, 2019) and Alibi Detect (Van Looveren, Vacanti, Klaise, Coca, 2020), all with github.com/SeldonIO URLs in the references, have authors of this paper among their authors and are among the open-source solutions highlighted in the Conclusion (alongside KFServing and creme by other authors). The paper contains no separate conflict-of-interest statement.",
          "Title page (affiliation footnote)",
          "Seldon Technologies Ltd, London, United Kingdom"),
     ],
     "notes": "PDF states: Workshop on Challenges in Deploying and Monitoring Machine Learning Systems (ICML 2020). Position/overview paper: no experiments or quantitative evaluation of the described detectors. Searched the full text for rollback, roll back, fallback, fall back, canary, shadow, A/B, replace, revert, previous model, champion and challenger: none found, so the paper describes no rollback to a previous model and no switch to a fallback model at serving time. The stated actions on detection are taking action or raising alerts (Introduction, citing Diethe et al.), sending detector events to alerting or storage modules, informing retraining, and not using flagged predictions. A 'carbon copy of the model' is mentioned only to serve explanation requests separately from production predictions (Section 3.2), not as a fallback. Other self-cited works: Vacanti & Van Looveren (2020), Van Looveren & Klaise (2019). Explanations are also described as a follow-up to outlier flags (to judge whether a flagged prediction can be trusted and acted on). The monitoring architecture is asynchronous (payload logging to a KNative broker), so detectors run alongside rather than in the request path."},

    {"id": "arxiv-2003.01668",
     "title": "Model Assertions for Monitoring and Improving ML Models",
     "authors": ["Daniel Kang", "Deepti Raghavan", "Peter Bailis", "Matei Zaharia"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2003.01668"},
     "tasks": ["mlops"],
     "fam": ["deep-learning"],
     "par": ["supervised"],
     "proposes": ["Model assertions: user-written functions over model inputs/outputs returning a severity score that flags likely errors, used for runtime monitoring, label validation, bandit-based active learning (BAL) and consistency-assertion weak supervision; implemented in the Python library OMG"],
     "claims": [
         ("Abstraction: model assertions are arbitrary functions over a model's input and output that indicate when errors may be occurring (e.g., an object rapidly changing its class in a video); they return a Boolean or continuous severity score, 0 meaning abstention.",
          "Abstract",
          "Model assertions are arbitrary functions over a model’s input and output that indicate when errors may be occurring, e.g., a function that triggers if an object rapidly changes its class in a video."),
         ("Runtime use as stated by the authors: assertions can log unexpected behavior or automatically trigger corrective actions such as shutting down an autopilot. The evaluation measures assertion precision, high-confidence errors found, active learning and weak supervision; an experiment where an assertion triggers an automatic runtime corrective action was not found in the text.",
          "Introduction",
          "First, we show that model assertions can be used for runtime monitoring: they can be used to log unexpected behavior or automatically trigger corrective actions, e.g., shutting down an autopilot."),
         ("Settings: four workloads based on industrial and academic use cases: TV news (50 problematic hour-long segments with precomputed outputs; no retraining possible), video analytics (ResNet-34 SSD pretrained on MS-COCO on night-street video), autonomous vehicles (NuScenes; PointPillars LIDAR and SSD camera detectors) and AF classification from ECG (CINC17).",
          "Experimental Setup",
          "We evaluated OMG and model assertions on four diverse ML workloads based on real industrial and academic use-cases: analyzing TV news, video analytics, autonomous vehicles, and medical classiﬁcation."),
         ("Precision protocol: for each assertion, 50 randomly sampled data points that triggered it were checked manually for an incorrect model output. Only precision among flagged points is reported; a recall or miss-rate measurement for assertions was not found in the text.",
          "Evaluation",
          "To test this, we randomly sampled 50 data points that triggered each assertion and manually checked whether that data point had an incorrect output from the ML model."),
         ("High-confidence errors: for the video-analytics assertions, the 10 highest-confidence errors per assertion were placed in the confidence distribution of all boxes; the authors state uncertainty-based monitoring would not catch these errors.",
          "Evaluation",
          "Importantly, uncertainty-based methods of monitoring would not catch these errors."),
         ("Fallback inside BAL (active learning): BAL samples data flagged by assertions in proportion to the marginal reduction in assertions fired; when assertions cannot be reduced (e.g., noisy assertions; all reductions under 1% in Algorithm 2), it defaults to random or uncertainty sampling as the user specifies. The authors state BAL itself has no statistical guarantees and is verified empirically.",
          "Active learning with BAL",
          "In this case, BAL will default to random sampling or uncertainty sampling, as speciﬁed by the user."),
         ("Stated limitations: assertions have not been thoroughly evaluated in real-time systems and may add overhead where actuation has tight latency constraints (e.g., AVs), though they can be run over historical data; the authors also list API expressiveness for some temporal assertions and out-of-scope issues such as training-set bias.",
          "Discussion",
          "Second, we have not thoroughly evaluated model assertions’ performance in real-time systems."),
     ],
     "notes": "PDF states: Proceedings of the 3rd MLSys Conference, Austin, TX, USA, 2020. Affiliation (PDF): Stanford University. Acknowledgments: supported in part by Stanford DAWN affiliates (Ant Financial, Facebook, Google, Infosys, NEC, VMware), Toyota Research Institute, Northrop Grumman, Cisco, SAP and NSF; the authors note they are collaborating with an AV company on real-time issues. Severity scores need not be calibrated because the algorithms use only their relative ordering. Consistency assertions also produce corrective weak labels (e.g., most common attribute value; user-supplied WeakLabel functions), used for retraining rather than runtime replacement of outputs. Active-learning trials: night-street run twice, NuScenes 8 trials (Appendix). Searched the full text for rollback, roll back, fallback, fall back, canary, shadow, A/B, replace, revert, previous model, champion and challenger: no rollback to a previous model and no switch to a fallback model at serving time. Hits are only (a) 'Fall back to baseline method' in Algorithm 2 (BAL data selection falling back to random/uncertainty sampling, c6) and (b) 'replace' in consistency-assertion correction rules that replace an inconsistent attribute to generate weak labels (Section 4) and in an Appendix table of assertion types. Runtime corrective actions (e.g., shutting down an autopilot) are only stated as a possible use (c2); Figure 1 illustrates correcting a missed box with a consistency assertion, but the corrections are evaluated as weak labels for retraining, and the stated runtime-deployment uses are logging and populating dashboards. Tag note: experiments are on object detection (video, LIDAR) and ECG classification, for which no task tag exists; only mlops is used as task."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model fallback and model selection in MLOps (meta-learned selection, dynamic selection, abstention/deferral, switching triggers, cascades/routing, monitoring); carded by a subagent. Results tables not recorded; claims only.")
