import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tabdl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2106.15147",
     "title": "SCARF: Self-Supervised Contrastive Learning using Random Feature Corruption",
     "authors": ["Dara Bahri", "Heinrich Jiang", "Yi Tay", "Donald Metzler"],
     "year": 2021, "venue": "ICLR 2022", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2106.15147"},
     "tasks": ["tabular-classification", "representation-learning"],
     "fam": ["tabular-mlp", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["SCARF: contrastive pre-training for tabular data in which the second view of each example is formed by replacing a random subset of its features (a fixed fraction c, default 0.6) with draws from each feature's empirical marginal distribution; the original and corrupted views pass through an encoder f and an l2-normalizing pre-train head g and are trained with the InfoNCE loss",
                  "Fine-tuning: g is discarded, a classification head h is attached to the pre-trained encoder f, and both f and h are fine-tuned with cross-entropy; pre-training is early-stopped on the InfoNCE loss of a static validation set of corrupted pairs"],
     "claims": [
         ("Corruption procedure: for each example, a fraction of the features is sampled uniformly at random and each of those features is replaced by a random draw from that feature's empirical marginal distribution, defined as the uniform distribution over the values the feature takes across the training dataset; both views are then passed through the encoder f and the pre-train head g.",
          "Section 3",
          "We sample some fraction of the features uniformly at random and replace each of those features by a random draw from that feature’s empirical marginal distribution,"),
         ("Relation to VIME (citing Yoon et al., 2020), which the authors say proposes the same corruption technique: the key differences are that SCARF pre-trains with a contrastive loss, which the authors state they show to be more effective than the denoising auto-encoder loss that partly constitutes VIME, and that after pre-training all weights including the encoder are fine-tuned using task supervision only (VIME fine-tunes only the task head).",
          "Section 2",
          "The key differences with our work is that we pre-train using a contrastive loss, which we show to be more effective than the denoising auto-encoder loss that partly constitutes VIME."),
         ("Datasets and splits: 69 classification datasets from the public OpenML-CC18 benchmark (72 datasets minus MNIST, Fashion-MNIST and CIFAR10); for each dataset 70%/10%/20% train/validation/test splits are formed, a different split for every trial, with all methods using the same splits. Categorical features are one-hot encoded (SCARF's marginal sampling is done before one-hot encoding).",
          "Section 4",
          "For each OpenML dataset, we form 70%/10%/20% train/validation/test splits, where a different split is generated for every trial and all methods use the same splits."),
         ("Fixed settings across experiments (unless specified otherwise): encoder f is a 4-layer ReLU network with hidden dimension 256, heads g and h are 2-layer ReLU networks; Adam with the default learning rate 0.001; batch size 128; early stopping with patience 3 (classification error as the fine-tuning validation metric); max 200 fine-tune and 1000 pre-train epochs; corruption rate 0.6 and temperature 1 for SCARF-based methods; all runs repeated 30 times with different splits; about one million CPU core hours in total.",
          "Section 4",
          "Unless speciﬁed otherwise, we use the following settings across all experiments."),
         ("Comparison method: results are summarized with a win matrix over the 69 datasets in which a 'win' or 'loss' is counted only when the means are not a statistical tie under Welch's t-test (p-value 0.05); box plots of relative improvement use only datasets where the means differ with p-value 0.20.",
          "Section 4",
          "“Beats” and “loses” are only deﬁned when the means are not a statistical tie (using Welch’s t-test with unequal variance and a p-value of 0.05)."),
         ("Fully labeled setting: all five pre-training techniques considered improve over no pre-training (control), SCARF outperforms the other pre-training methods with more statistically significant wins, and SCARF pre-training also boosts mixup, label smoothing, distillation and dropout; the authors say this suggests pre-training complements existing solutions and that a distinct mechanism is at play.",
          "Section 4.1",
          "We observe that SCARF generally outperforms the alternatives and adds a 1-2% relative gain across the board."),
         ("Label-noise setting (30% of training labels replaced by a uniformly drawn class, validation and test uncorrupted): SCARF outperforms the other pre-training methods and boosts all baselines, including label-noise methods such as Deep k-NN and the bi-tempered loss.",
          "Section 4.2",
          "Again, we see SCARF outperforms the rest and boosts all baselines by 2-3%."),
         ("Limited-label setting (only 25% of the training split keeps its labels; autoencoders, SCARF, self-training and tri-training use the unlabeled remainder): SCARF outperforms the other methods.",
          "Section 4.3",
          "SCARF outperforms the rest, adding a very impressive 2-4% to all baselines."),
         ("Ablation on corruption strategies under different feature scalings (z-score and min-max shown in the appendix figure): SCARF marginal sampling generally outperforms the alternatives; the authors note it has no hyperparameters and is invariant to feature scaling, whereas additive noise must be rescaled with the features.",
          "Section 4.4",
          "Marginal sampling is neat in that in addition to not having hyperparameters, it is invariant to scaling and preserves the “units” of each feature."),
     ],
     "notes": "Affiliation: Google Research (all authors). Venue: the PDF header says 'Published as a conference paper at ICLR 2022' and the arXiv comment is 'ICLR 2022 Spotlight'. Section numbers are from numbered headings in the PDF (the XGBoost baseline is in an unnumbered appendix section 'Absolute performance'). Only deep models are compared in the body: a gradient-boosted tree baseline (XGBoost, Python API version 0.6, default XGBClassifier settings: max depth 3, 100 estimators, learning rate 0.1) appears only in the appendix accuracy tables, with no comparative statement about it in the text (searched for xgboost, boost, tree, gbdt); those tables are not recorded. No per-dataset hyperparameter tuning of the networks or baselines was found in the text (searched for tuned, hyperparameter, default, search): the same architecture and optimizer settings are used throughout, except that the three datasets 4134, 28 and 1468 are left unscaled because no scaling was best for the control network. Reported gains are relative to the control network, not to GBDTs. Sensitivity results (batch size past 128 gave no significant improvement; corruption rate stable in 50%-80%; temperature 1 recommended; InfoNCE alternatives no better; pre-training beats co-training and pure data augmentation) are shown as figures in Section 4.4 / Appendix A.3. Conflict of interest: the Deep k-NN label-noise baseline is the authors' own earlier method (Bahri, Jiang and Gupta, 2020). The conclusion notes a potential negative side effect: learned representations may reinforce biases in the input data."},

    {"id": "arxiv-2110.01889",
     "title": "Deep Neural Networks and Tabular Data: A Survey",
     "authors": ["Vadim Borisov", "Tobias Leemann", "Kathrin Seßler", "Johannes Haug", "Martin Pawelczyk", "Gjergji Kasneci"],
     "year": 2021, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2110.01889", "code": "https://github.com/kathrinse/TabSurvey"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["deep-learning", "tabular-mlp", "tabular-attention", "differentiable-trees", "gradient-boosted-trees", "tree-ensembles"],
     "par": ["supervised", "self-supervised"],
     "proposes": ["A taxonomy of deep learning for heterogeneous tabular data: data transformation methods (single- and multi-dimensional encodings), specialized architectures (hybrid models, split into fully and partly differentiable, and transformer-based models), and regularization models",
                  "An open benchmark (TabSurvey code) comparing classical models and GBDTs with deep tabular models on five public datasets (HELOC, Adult, HIGGS, Covertype, California Housing), including run time, model size and an attribution-fidelity test of attention-based explanations"],
     "claims": [
         ("The authors identify four possible reasons why deep learning on tabular data falls short of its success elsewhere: low-quality training data (missing values, outliers, inconsistencies, small size, class imbalance), missing or complex irregular spatial dependencies between features, dependency on preprocessing (especially of categorical features), and the importance of single features (a small change of one categorical feature can flip a prediction, which decision trees handle by selecting single features and thresholds).",
          "Section III-C",
          "In the following, we identify and discuss four possible reasons:"),
         ("Taxonomy: works on deep learning for tabular data are divided into three main categories: data transformation methods, specialized architectures, and regularization models.",
          "Section III-D",
          "We divide the works from the deep learning with tabular data literature into three main categories: data transformation methods, specialized architectures, and regularization models."),
         ("Tuning protocol of their benchmark: each model is tuned with Optuna for 100 iterations, each hyperparameter configuration is cross-validated with five folds, and the search spaces are based on the corresponding papers and recommendations from the frameworks' authors (published with the code).",
          "Section VII-B1",
          "Each hyperparameter conﬁguration was cross-validated with ﬁve folds."),
         ("Preprocessing is the same for every model: zero-mean unit-variance normalization of numerical features and ordinal encoding of categorical features (citing Hancock & Khoshgoftaar that this encoding performs comparably to more advanced methods); missing values are replaced by zeros for linear regression and pure neural networks; categorical features are explicitly specified for LightGBM, DeepFM, DeepGBM, TabNet, TabTransformer and SAINT.",
          "Section VII-B2",
          "We apply the ordinal encoding to categorical values for all models."),
         ("Benchmark result (5 datasets): for all but the very large HIGGS dataset, the best scores are obtained by boosted decision tree ensembles; XGBoost and CatBoost outperform all deep learning approaches on the small and medium datasets, the regression dataset and the multi-class dataset.",
          "Section VII-B4",
          "For all but the very large HIGGS data set, the best scores are still obtained by boosted decision tree ensembles."),
         ("On HIGGS (11 million rows, only numerical features) SAINT outperforms the classical approaches, which the authors say suggests that for very large tabular datasets with predominantly continuous features, modern neural architectures may have an advantage.",
          "Section VII-B4",
          "This suggests that for very large tabular data sets with predominantly continuous features, modern neural network architectures may have an advantage over classical approaches after all."),
         ("Run time: training time of gradient-boosting models is lower than that of most deep models, but on HIGGS their inference time is significantly higher; all gradient-boosting and deep models were trained on the same GPU.",
          "Section VII-C",
          "for XGBoost, the inference time amounts to 5995 seconds whereas inference times for MLP and SAINT are 10.18 and 282 seconds respectively."),
         ("Interpretability check of attention-based attributions (TabTransformer, SAINT): after a feature-removal fidelity test (MoRF/LeRF) and a comparison with KernelSHAP whose Spearman rank correlation with the models' attributions was surprisingly low and sometimes negative, the authors conclude that the transformer models did not produce convincing attributions out of the box and that more profound benchmarks of claimed interpretability are necessary.",
          "Section VII-D",
          "In these two simple benchmarks, the transformer models were not able to produce convincing feature attributions out-of-the-box."),
         ("Stated limitation: the benchmark uses common datasets with varying characteristics, but a different choice of datasets or of hyperparameters such as the categorical encoding (e.g. one-hot) may lead to a different outcome; the authors call for standardized benchmarking, noting that the eighteen works in their Table II use over 100 different datasets.",
          "Section VIII-A",
          "While we chose common data sets with varying characteristics for our experiments, a different choice of data sets or hyperparameter such as the encoding use (e.g., use one-hot encoding) may lead to a different outcome."),
     ],
     "notes": "Affiliation: University of Tübingen (DSAR group); Gjergji Kasneci is also affiliated with Schufa Holding AG (stated on page 1). Venue: the v3 PDF header says 'SUBMITTED TO THE IEEE, JUNE 2022' and page 1 carries an IEEE copyright notice, but the arXiv record has no comment/journal_ref and no publication venue is stated in the PDF, so no venue is recorded. Year is the first arXiv version (2021); the v3 PDF is dated 29 Jun 2022. Section labels (III-C, VII-B4 etc.) are from the PDF headings and table of contents. Benchmark scale: only 5 datasets, results as mean and std over (stratified) 5-fold cross-validation with the same folds for every model (Table V caption); per-model numbers are in a table and not recorded; among deep models the text says SAINT was competitive across datasets while the others' performance was highly dataset-dependent. HIGGS was modified for models that require a categorical feature (the 21st variable binarized into three groups). The summary (Section VIII-A) states that tree ensembles still outperform deep models 'on most data sets that we considered' with significantly less training time, while for very large datasets deep learning 'may still be able to achieve competitive performance'. Conflict of interest: the 'Model Trees' baseline in the benchmark is by an author (Broelemann and Kasneci, ref. [199]), and the counterfactual-explanation section points to the authors' own CARLA library (Pawelczyk ... Kasneci, ref. [157]); the deep models compared are by other groups."},

    {"id": "arxiv-2407.00956",
     "title": "A Closer Look at Deep Learning Methods on Tabular Datasets",
     "authors": ["Han-Jia Ye", "Si-Yang Liu", "Hao-Run Cai", "Qi-Le Zhou", "De-Chuan Zhan"],
     "year": 2024, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2407.00956", "code": "https://github.com/LAMDA-Tabular/TALENT"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["deep-learning", "tabular-mlp", "tabular-attention", "differentiable-trees", "gradient-boosted-trees", "tree-ensembles"],
     "par": ["supervised"],
     "proposes": ["Talent: a collection of 300 common-size tabular datasets (120 binary, 80 multi-class, 100 regression) from UCI, OpenML and Kaggle, with a 45-dataset core subset (Talent-tiny) and a Talent-extension suite for high-dimensional, many-class and very large-scale settings",
                  "A heterogeneity analysis that selects dataset meta-features by how well they help forecast later validation curves of deep tabular models from early training signals, and relates them to the tree-vs-DNN performance gap"],
     "claims": [
         ("Benchmark composition: datasets from UCI, OpenML and Kaggle, filtered by excluding N < 500 or d < 5, > 20% missing values, trivially easy or majority-dominated classification sets, and duplicates; categorical features are ordinally encoded; 22 mis-specified regression datasets with two unique targets were relabelled as binary classification.",
          "Section 4.2",
          "Ultimately, Talent consists of 120 binary-classification, 80 multi-class, and 100 regression datasets, offering both breadth and depth for evaluating tabular learning."),
         ("Known data-quality issues are deliberately retained in the general benchmark: 13 datasets with potential leakage (kept for comparability with prior work and to assess robustness to imperfect data) and 25 datasets whose features are extracted from images or audio; all datasets with identified leakage are excluded from Talent-tiny.",
          "Section 4.2",
          "In our collection, we identify 13 datasets with potential leakage."),
         ("Protocol: each dataset is randomly split 64%/16%/20% into train/val/test (a single fixed hold-out, following Gorishniy et al.); hyperparameters are chosen on validation with Optuna using a fixed budget of 100 trials per method-dataset pair; the best configuration is retrained with 15 random seeds and the mean is reported. Full K-fold CV is described as computationally prohibitive at this scale.",
          "Section 4.3",
          "We use Optuna (Akiba et al., 2019) with a fixed budget of 100 trials per method–dataset pair."),
         ("Unlike the tuned models, pretrained tabular (foundation) models are evaluated from their latest public checkpoints with default inference hyperparameters, without per-dataset tuning; all deep methods use AdamW with batch size 1024 unless noted otherwise, and CatBoost receives the feature types for native categorical handling.",
          "Section 4.3",
          "Pretrained tabular models are evaluated from their latest public checkpoints with default inference hyperparameters (i.e., no per-dataset tuning)."),
         ("Summary observations over 40 methods and 300 datasets: tree-based ensembles (CatBoost, LightGBM, XGBoost) remain strong, reliable and statistically robust baselines, while pretrained foundation models (TabPFN v2, TabICL) deliver state-of-the-art performance across many datasets and significantly narrow, but do not entirely close, the gap between tree-based and DNN-based paradigms.",
          "Section 5.1",
          "Tree-based ensembles (CatBoost, LightGBM, XGBoost) remain strong, reliable, and statistically robust baselines."),
         ("Foundation models, ensembles and the top DNNs (RealMLP, ModernNCA) often remain statistically tied, which the authors say suggests universal superiority has not yet been achieved; in the same paragraph they note that scalability and computational cost remain open challenges for foundation models.",
          "Section 5.1",
          "Despite these advances, the Wilcoxon–Holm tests show that foundation models, ensembles, and top DNNs (RealMLP, ModernNCA) often remain statistically tied, suggesting that universal superiority has not yet been achieved."),
         ("Tree-mimic networks (NODE, TabNet) generally underperform relative to ensembles, whereas neighborhood-based models such as ModernNCA are often statistically comparable to CatBoost and LightGBM; ensembling within deep methods (TabM over MLP, MNCA-ens over ModernNCA) further improves performance.",
          "Section 5.1",
          "Tree-mimic networks such as NODE and TabNet generally underperform relative to ensembles."),
         ("Tree-DNN gap and heterogeneity: the per-dataset rank gap between tree-based methods (RF, XGBoost, LightGBM, CatBoost) and representative DNNs (RealMLP, TabM, ModernNCA, FT-Transformer) correlates most strongly (negatively) with feature-heterogeneity meta-features such as entropy_std (-0.3333), while inst_to_attr (emphasized by McElfresh et al., 2023) correlates more weakly with the gap; the authors say datasets with greater feature heterogeneity tend to favor tree-based methods, likely due to successive partitioning.",
          "Section 6.5",
          "These findings suggest that the degree of heterogeneity among dataset features is a more critical determinant driving the relative model superiority."),
         ("By feature type: raw-feature DNNs such as MLP and RealMLP do worst on datasets with mixed numerical and categorical features and better on purely numerical or purely categorical ones; tree-based methods excel on heterogeneous datasets; FT-Transformer behaves more like the tree-based models, which the authors attribute ('likely') to its learned embeddings of categorical and numerical features; TabPFN v2 is weakest on purely categorical datasets.",
          "Section 6.6",
          "DNN-based methods such as MLP and RealMLP exhibit their worst performance on datasets with mixed feature types (Mixed Data)."),
     ],
     "notes": "Affiliation: Nanjing University (School of AI / National Key Laboratory for Novel Software Technology). No venue recorded: the arXiv record has no comment/journal_ref, and the v4 PDF (7 Nov 2025) uses a journal template with the placeholder 'Editor: My editor', which is not a venue. Year is the first arXiv version (2024); this card is based on v4, which includes foundation models (TabPFN v2, TabICL) that earlier versions may not. Conflict of interest (not stated as such in the paper): the benchmark code is the authors' TALENT repository (LAMDA-Tabular); evaluated methods include the authors' own ModernNCA (Ye, Yin, Zhan and Chao, ICLR 2025), its BatchEnsemble variant MNCA-ens introduced for this analysis, and BETA (Liu and Ye, ICML 2025); ModernNCA is also one of the four DNNs defining the Tree-DNN score (Equation 2) used to choose Talent-tiny datasets and for the gap analysis. PTaRL is by a different author (Hangting Ye et al.), not an overlapping author. The meta-feature selection (Section 6.2) uses validation curves of MLPs trained with default hyperparameters, and the correlation analyses are correlational. Section 7.1 reports on Talent-tiny that CV plus ensembling improves average ranks slightly but leaves the relative order of methods largely unchanged. A hyperparameter-budget study (Table 4, MLP with 50/100/150/200 trials) supports 100 trials as near-saturation for MLP. Section 5.1 also states that the Wilcoxon-Holm analysis shows no significant differences among the gradient boosting methods, that vanilla MLPs are generally weak while tuned MLP-PLR and RealMLP close the gap substantially, and that token-based models (FT-T, ExcelFormer, AutoInt) often cluster with ensembles in the same equivalence group. Per-dataset results and figures (critical-difference diagrams, radar chart, Tree-DNN score distribution) are not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
