import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tabdl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2106.01342",
     "title": "SAINT: Improved Neural Networks for Tabular Data via Row Attention and Contrastive Pre-Training",
     "authors": ["Gowthami Somepalli", "Micah Goldblum", "Avi Schwarzschild", "C. Bayan Bruss", "Tom Goldstein"],
     "year": 2021, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2106.01342"},
     "tasks": ["tabular-classification", "representation-learning"],
     "fam": ["tabular-attention", "deep-learning", "gradient-boosted-trees"], "par": ["supervised", "self-supervised"],
     "proposes": ["SAINT (Self-Attention and Intersample Attention Transformer): every categorical and continuous feature is embedded into a d-dimensional token (a separate one-layer ReLU projection per continuous feature) plus a [CLS] token; L stages each stack a self-attention block over features and an intersample-attention block that attends across the rows of a batch (concatenated feature embeddings of a row act as one token); the [CLS] output goes to an MLP head",
                  "Contrastive self-supervised pre-training for tabular data: views made by CutMix in input space and mixup in embedding space, InfoNCE contrastive loss on projection-head outputs plus a per-feature denoising (reconstruction) loss, followed by finetuning on the labeled subset"],
     "claims": [
         ("Architecture: SAINT projects all features into a combined dense space and passes them as tokens through a transformer encoder with self-attention over the features of a sample and a proposed intersample attention that relates a row to other rows; the authors describe intersample attention as akin to nearest-neighbor classification with a distance metric learned end-to-end, and say it lets SAINT borrow features from similar samples in the batch when a feature is missing or noisy.",
          "Introduction",
          "Intersample attention is akin to a nearest-neighbor classiﬁcation, where the distance metric is learned end-to-end rather than ﬁxed."),
         ("Embedding of continuous features: unlike TabTransformer, which embeds only categorical features (continuous features bypass the transformer, which the authors say loses information about categorical-continuous correlations), SAINT projects each continuous feature with its own single fully-connected layer with ReLU; columns are embedded independently. In a side experiment that keeps TabTransformer's architecture and training hyperparameters fixed, only embedding its continuous features this way raised its average AUROC from 89.38 to 91.72.",
          "Self-Attention and Intersample Attention Transformer (SAINT): Encoding the Data",
          "we use a separate single fully-connected layer with a ReLU nonlinearity for each continuous feature"),
         ("Pre-training: augmented views are generated with CutMix in the raw input space and mixup in the embedding space; the loss is an InfoNCE contrastive loss between projection-head outputs of clean and augmented views plus a denoising loss reconstructing each feature (cross-entropy or MSE) with lambda_pt and temperature described as tuned on validation data. The authors state that, to the best of their knowledge, they are the first to adopt contrastive learning for tabular data.",
          "Related Work",
          "In this paper, to the best of our knowledge, we are the ﬁrst to adopt contrastive learning for tabular data."),
         ("Benchmark: 16 public datasets from UCI or AutoML (14 binary, 2 multi-class: Volkert and MNIST), chosen because they were previously used to evaluate competing methods (TabNet, TabTransformer, VIME); sizes range from 200 to 495,141 samples and 8 to 784 features. AUROC is the main metric for binary tasks and accuracy for the two multi-class datasets.",
          "Experimental Evaluation: Datasets",
          "These datasets were chosen because they were previously used to evaluate competing methods [1, 18, 49]."),
         ("Protocol: all models (including pre-training runs) are trained with AdamW (learning rate 0.0001, batch size 256 except for wide datasets); data split as stated into 65%, 15% and 25% for training, validation and test; each reported number is the mean of 5 trials with different seeds. Baseline results (logistic regression, random forest, XGBoost, LightGBM, CatBoost, MLP, VIME, TabNet, TabTransformer) are quoted from the original papers when possible and reproduced otherwise. No description of how the GBDT baselines' hyperparameters were tuned was found in the text (searched for tun, hyperparam, hyper-param, default, grid).",
          "Table 2 caption",
          "Baseline results are quoted from original papers when possible (denoted with *) and reproduced otherwise."),
         ("Supervised results (within this paper): on 13 of the 16 datasets one of the three SAINT variants (SAINT, SAINT-s with self-attention only, SAINT-i with intersample attention only) outperforms all baselines, including the boosted-tree libraries, and on the remaining 3 it is very close to the best; on average each variant is reported to beat all baselines by a significant margin. Note the count takes the best of three variants per dataset.",
          "Results: Supervised setting",
          "In 13 out of 16 datasets, one of the SAINT variants outperforms all baseline models."),
         ("Semi-supervised results: with 50, 200 and 500 labeled points (rest unlabeled), the pre-trained SAINT model performs best in all cases; when all training samples are labeled, pre-training does not contribute appreciably.",
          "Results: Semi-supervised setting",
          "Interestingly, we note that when all the training data samples are labeled, pre-training does not contribute appreciably, hence the results with and without pre-training are fairly close."),
         ("Interpretability: the authors say attention gives some interpretability (with one transformer stage the maps reveal which features and data points are used); the evidence is visualizations on MNIST treated as tabular data (self-attention focusing on foreground pixels; sparse intersample attention on a few points, which they hypothesize are hard examples) and Volkert, where intersample attention is much denser.",
          "Interpreting attention",
          "One advantage of using transformer-based models is that attention comes with some interpretability, in contrast, MLPs are hard to interpret."),
         ("Stated limitation: real-world datasets may be highly noisy or imbalanced, and SAINT was tuned for the settings in which it was tested, so the authors caution practitioners against assuming that what works on these benchmarks will work in their own setting.",
          "Discussion, Limitations, and Impact",
          "Moreover, we have tuned SAINT for the settings in which we test it."),
     ],
     "notes": "Affiliations: University of Maryland, College Park; C. Bayan Bruss is at Capital One (Center for Machine Learning). No venue recorded: the PDF (arXiv v1) footer says 'Preprint. Under review.' and the arXiv record has no journal_ref. The split percentages are recorded as written (65/15/25 sums to 105%). SAINT-i is reported to outperform the other variants when the number of features is large (e.g. Arcene, Arrhythmia) and to be faster than SAINT-s; robustness to CutMix-style corruption and missing features and the batch-size study are shown only in figures (values not recorded). Hyperparameter tuning of SAINT itself: lambda_pt=10, tau=0.7, p_cutmix=0.3, alpha=0.2 are stated as fixed for all settings, while the pre-training section says lambda_pt and tau are tuned on validation data. Section numbers in locations are avoided because extracted headings carry no numbers. Cross-reference: TabR (arxiv-2307.14338) later compares against SAINT as a retrieval-like baseline."},

    {"id": "arxiv-2203.05556",
     "title": "On Embeddings for Numerical Features in Tabular Deep Learning",
     "authors": ["Yury Gorishniy", "Ivan Rubachev", "Artem Babenko"],
     "year": 2022, "venue": "NeurIPS 2022", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2203.05556", "code": "https://github.com/yandex-research/tabular-dl-num-embeddings"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["tabular-mlp", "tabular-attention", "deep-learning", "gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["Piecewise linear encoding (PLE) of each numerical feature over bins, with bins from empirical quantiles (PLEq) or from a per-feature decision tree fitted to the target (PLEt), optionally followed by linear/ReLU layers",
                  "Periodic embeddings: concat[sin(2*pi*c*x), cos(2*pi*c*x)] with trainable per-feature frequencies c initialized from N(0, sigma), optionally followed by linear/ReLU layers (e.g. PLR = ReLU(Linear(Periodic)))",
                  "Embedding modules for numerical features applied to MLP and ResNet backbones as well as to Transformer (FT-Transformer)"],
     "claims": [
         ("Framework: an embedding for numerical features is a function f_i mapping the scalar value of the i-th feature to a vector; embeddings for different features are computed independently with the same functional form, and parameters are never shared between features. For MLP-like backbones the embeddings are concatenated into one flat vector; for Transformer backbones they are passed as tokens.",
          "Section 3.1",
          "We never share parameters of embedding functions of different features."),
         ("Piecewise linear encoding (PLE): the feature's value range is split into T bins and encoded as a T-dimensional vector (components of bins below the value set to 1, the value's own bin linear, the rest 0); bins come either from empirical quantiles of the training data or from target-aware splits equivalent to growing a one-feature decision tree (in the spirit of C4.5 discretization). PLE is computed once and can be viewed as preprocessing; for attention models a linear layer is added after it.",
          "Section 3.2",
          "PLE produces alternative initial representations for the numerical features and can be viewed as a preprocessing strategy."),
         ("Periodic embeddings: f_i(x) = concat[sin(v), cos(v)] with v = 2*pi*c*x and trainable c initialized from N(0, sigma); unlike some prior work using periodic functions, features are not mixed before the periodic step. The authors observe sigma is an important hyperparameter; sigma and k are tuned on validation sets.",
          "Section 3.3",
          "We observe that σ is an important hyperparameter."),
         ("Benchmark: eleven public datasets mostly from previous tabular DL works and Kaggle competitions; the authors focus on middle and large scale tasks and state that the benchmark is biased towards GBDT-friendly problems. They also say this bias means the observed superiority of tree-based over quantile-based bins may not generalize to more DL-friendly datasets.",
          "Section 4: Datasets",
          "Importantly, we focus on the middle and large scale tasks, and our benchmark is biased towards GBDT-friendly problems, since, as of now, closing the gap with GBDT models on such tasks is one of the main challenges for tabular DL."),
         ("Protocol: the authors mostly follow the tuning, training and evaluation protocols of their own earlier work (Gorishniy et al. [13], FT-Transformer). Every model's hyperparameters are tuned per dataset on the validation set (test set never used for tuning), mostly with Optuna's TPE; each tuned configuration is run with 15 random seeds, and ensembles are formed from three disjoint groups of 5 models. The hyperparameter tables list 100 tuning iterations for CatBoost, XGBoost, MLP and ResNet, and 50 (on SA, CO, MI) or 100 (others) for Transformer. Deep models share the same preprocessing (quantile transformation except on Otto).",
          "Appendix E",
          "For every dataset, we carefully tune each model’s hyperparameters."),
         ("Comparison with GBDT (ensembles of DL models vs ensembles of tuned CatBoost/XGBoost, judged on best metric values without considering efficiency): for the vast majority of backbone-dataset pairs, proper embeddings are reported to be the only thing needed to close the gap with GBDT; stated exceptions are the MI dataset and the pairs ResNet & GE, Transformer & FB, Transformer & GE, Transformer & OT. The authors also say that, to the best of their knowledge, this is the first time DL models perform on par with GBDT on California Housing and Adult, and that efficiency can still be an issue compared to GBDT.",
          "Comparing DL models and GBDT",
          "However, for the vast majority of the “backbone & dataset” pairs, proper embeddings are the only thing needed to close the gap with GBDT."),
         ("Backbones: after MLP-like architectures are coupled with numerical-feature embeddings, they perform on par with Transformer-based models; among embeddings, PLR gives the best average performance and LR is a consistent baseline. Models that also attend over objects (e.g. SAINT, NPT) were deliberately not included because that non-parametric component is considered orthogonal to the paper's topic.",
          "Comparing DL models and GBDT",
          "Importantly, after the MLP-like architectures are coupled with embeddings for numerical features, they perform on par with the Transformer-based models."),
         ("PLE as preprocessing: re-evaluating tuned MLP, MLP-Q and MLP-T under different preprocessing, the vanilla MLP often becomes unusable without preprocessing, while models with PLE are less sensitive to the initial preprocessing; the authors note the observation for MLP-T could be a property of the benchmarks.",
          "Section 5.3",
          "Overall, the results indicate that models using PLE are less sensitive to the initial preprocessing compared to the vanilla MLP."),
         ("Open questions stated by the authors: how exactly the embedding modules help optimization at a fundamental level remains to be explained, and applying the same functional transformation to all features may be suboptimal.",
          "Conclusion & Future work",
          "For example, it is still to be explained how exactly the discussed embedding modules help optimization on the fundamental level."),
     ],
     "notes": "Affiliations: Yandex; HSE (Rubachev). Venue from the PDF footer ('36th Conference on Neural Information Processing Systems (NeurIPS 2022)') and the arXiv comment ('NeurIPS 2022 camera-ready'). Conflict of interest: the backbones (MLP, ResNet, FT-Transformer as 'Transformer-L') and the tuning/evaluation protocol are taken from the authors' own earlier paper arxiv-2106.11959; the same group later builds TabR (arxiv-2307.14338) on these embeddings. Other stated results recorded only here: adding fixed-coefficient Periodic features to XGBoost did not provide benefits on CA, HO, HI (Table 10); embedding modules can increase parameter counts substantially (e.g. almost 2000-fold for MLP-LR on CH) but the authors report only a 1.5-fold training-time increase in that case and MLP/ResNet with embeddings remain faster than Transformers (Section 'Comparing model sizes'). On a synthetic GBDT-friendly dataset (Appendix D.1) CatBoost was trained with default hyperparameters. Section numbers 3.1-3.3 and 5.3 are confirmed by in-text cross-references ('subsection 3.1', 'subsection 3.2', 'subsection 3.3', 'subsection 5.3'); other locations use section names."},

    {"id": "arxiv-2307.14338",
     "title": "TabR: Tabular Deep Learning Meets Nearest Neighbors in 2023",
     "authors": ["Yury Gorishniy", "Ivan Rubachev", "Nikolay Kartashev", "Daniil Shlenskii", "Akim Kotelnikov", "Artem Babenko"],
     "year": 2023, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2307.14338", "code": "https://github.com/yandex-research/tabular-dl-tabr"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["tabular-mlp", "deep-learning", "gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["TabR: a feed-forward network (encoder E, predictor P) with a retrieval module R in a residual branch that retrieves the m = 96 nearest training objects by a key-only negative L2 similarity -||W_K(x) - W_K(x_i)||^2 and aggregates softmax-weighted values W_Y(y_i) + T(W_K(x) - W_K(x_i)) that use the neighbors' labels",
                  "Context freeze: reusing training-object contexts after a fixed number of epochs to speed up training"],
     "claims": [
         ("Architecture: TabR is described as essentially a feed-forward network with a custom kNN-like component in the middle: target and candidate objects are encoded by a shared encoder, a retrieval module enriches the target representation from the top-m candidates (m = 96, candidates = the training set) using a single attention-like module, and a predictor makes the prediction.",
          "Abstract",
          "In this work, we present TabR – essentially, a feed-forward network with a custom k-Nearest-Neighbors-like component in the middle."),
         ("Motivation: the authors report that existing retrieval-augmented tabular models (which often use several layers of multi-head attention between objects and features, e.g. SAINT, NPT) provide at most minor benefits over a properly tuned MLP while being significantly more complex and costly.",
          "Introduction",
          "While multiple retrieval-augmented models for tabular data problems exist, in our experiments, we show that they provide if only minor benefits over the properly tuned multilayer perceptron (MLP; the simplest parametric model), while being significantly more complex and costly."),
         ("Design path: a vanilla self-attention retrieval module performed similarly to MLP, and adding context labels alone gave no improvement; removing queries and using L2 distance (key-only similarity) was the turning point, and removing any of the three ingredients (context labels, key-only representation, L2 distance) drops performance back to MLP level. The authors add that L2 is unlikely to be universally best but seems a reasonable default for tabular data.",
          "Section 3.2",
          "Crucially, in subsection A.3, we show that removing any of the three ingredients (context labels, key-only representation, L2 distance) results in a performance drop back to the level of MLP."),
         ("Protocol: following Gorishniy et al. (2022) (the authors' own earlier work), hyperparameters and early stopping use the validation set, test metrics are averaged over 15 random seeds, comparisons take standard deviations into account, and ensembles are three groups of five models. TabR is tuned with TPE (Optuna) for 100 iterations on the smaller default-benchmark datasets and 50 on WE, CO, MI.",
          "Section 3.1",
          "The most important points are that, for any given algorithm, on each dataset, following Gorishniy et al. (2022), (1) we perform hyperparameter tuning and early stopping using the validation set;"),
         ("GBDT tuning: the authors state they tried to tune GBDT as well as possible for a fair comparison; compared with their prior work they doubled tuning iterations and the number of trees, increased maximum depth and increased early-stopping rounds 4x; on the Grinsztajn et al. benchmark the GBDT budget is described as 20 random warmup iterations plus 180 TPE iterations.",
          "Appendix D (XGBoost implementation details; the same paragraph is repeated for the other GBDT libraries)",
          "In this work, we made our best to tune GBDT models as good as possible to make sure that the comparison is fair, and the conclusions are reliable.", 27),
         ("Default benchmark vs GBDT (ensembles vs ensembles, since gradient boosting is already an ensembling technique): the tuned TabR gives noticeable improvements over tuned GBDT on several datasets (CH, CA, HO, HI, WE, CO) and is competitive on the rest except MI.",
          "Comparing TabR with gradient-boosted decision trees",
          "Table 4 shows that, on the default benchmark, the tuned TabR provides noticeable improvements over tuned GBDT on several datasets (CH, CA, HO, HI, WE, CO), while being competitive on the rest, except for the MI dataset."),
         ("Benchmark of Grinsztajn et al. (2022) (middle-scale tasks, <=50K objects, originally used to show GBDT superiority), adapted to the authors' protocol (same splits; one version per dataset; the 'Eye movements' dataset removed because of a leak): MLP-PLR is slightly inferior to GBDT, while TabR outperforms GBDT on average. Tree-based models are described as remaining a cheaper solution.",
          "Section 4.2",
          "While MLP-PLR (one of the best parametric DL models) indeed is slightly inferior to GBDT on this set of tasks, TabR makes a significant step forward and outperforms GBDT on average."),
         ("Default configuration caveat: the default TabR-S hyperparameters were obtained by averaging tuned hyperparameters over 13 datasets that include the evaluated default-benchmark datasets; the authors acknowledge this is not 100% fair, report that a leave-one-out variant showed no meaningful changes, and point to its performance on the Grinsztajn et al. benchmark as evidence it is not strongly overfitted.",
          "Appendix D.8",
          "Formally, this is not 100% fair to evaluate the obtained default TabR-S on the datasets which contributed to this default hyperparameters as in Table 4."),
         ("Limitations: TabR shares general limitations of retrieval-augmented models (whether using real training objects for predictions is acceptable; retrieval during training must simulate deployment, e.g. only past data for time series); the retrieval module still adds overhead over parametric models so TabR may not scale to truly large datasets as-is; training on the full Weather prediction dataset (3M+ objects) took more than 18 hours, reduced to 3h15min with context freeze.",
          "Appendix B",
          "Lastly, while TabR is significantly more efficient than prior retrieval-based tabular DL models, the retrieval module R still causes overhead compared to purely parametric models, so TabR may not scale to truly large datasets as-is."),
     ],
     "notes": "Affiliations: Yandex and HSE. No venue recorded: the arXiv v2 PDF has no conference footer and the arXiv record has no journal_ref (comment only gives the code URL). Conflict of interest: the protocol, MLP-PLR baseline (arxiv-2203.05556) and FT-Transformer/MLP baselines (arxiv-2106.11959) are the authors' own earlier work; the Grinsztajn et al. benchmark (arxiv-2207.08815) is by another group. The authors also state that the retrieval component is not universally beneficial for all datasets and that retrieval and numerical embeddings are not fully orthogonal (section 'Evaluating retrieval-augmented deep learning models for tabular data'). For ANP, tuning was cut to 20 iterations on large datasets due to cost; ANP and DNNR were evaluated only on regression problems; the SAINT baseline was modified so each sample attends only to itself and training-set context, was tuned with TPE on the smaller datasets and used a slightly modified default configuration on WE, CO, MI. Figure 1 win/tie/loss counts against XGBoost are from a figure and are not recorded. Section numbers 3.1, 3.2, 4.2 and appendix labels are confirmed by in-text cross-references ('subsection 3.1', 'subsection 3.2', 'subsection 4.2', 'subsection D.8')."},

    {"id": "arxiv-2106.11189",
     "title": "Well-tuned Simple Nets Excel on Tabular Datasets",
     "authors": ["Arlind Kadra", "Marius Lindauer", "Frank Hutter", "Josif Grabocka"],
     "year": 2021, "venue": "NeurIPS 2021", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2106.11189", "code": "https://github.com/releaunifreiburg/WellTunedSimpleNets"},
     "tasks": ["tabular-classification"],
     "fam": ["tabular-mlp", "deep-learning", "gradient-boosted-trees", "differentiable-trees"], "par": ["supervised"],
     "proposes": ["Regularization cocktails: per-dataset joint hyperparameter optimization (BOHB) over whether and how strongly to apply 13 regularizers (batch norm, SWA, lookahead, weight decay, dropout, snapshot ensembles, skip connections with Shake-Shake/Shake-Drop, Mix-Up, Cut-Mix, Cut-Out, FGSM adversarial training) on a fixed 9-layer, 512-unit MLP"],
     "claims": [
         ("Method: the regularization cocktail is found by a joint search over the hyperparameters of 13 regularizers, each with a conditional switch deciding whether it is applied, in a 19-dimensional space, using the multi-fidelity Bayesian optimizer BOHB; constraints keep Shake-Shake and Shake-Drop from being active together and allow only one data augmentation technique at once.",
          "Section 4",
          "In total, the optimal cocktail is searched in a space of 19 hyperparameters."),
         ("Fixed backbone: the network is fixed to a 9-layer MLP with 512 units per layer, trained with AdamW and cosine annealing with restarts at a learning rate of 1e-3 chosen by grid search across datasets; the fixed training/architecture hyperparameters were tuned to maximize the performance of an unregularized network on the same dataset collection used for evaluation.",
          "Fixed Architecture and Optimization Hyperparameters",
          "These ﬁxed hyperparameter values, as speciﬁed in Table 4 of Appendix B.1, have been tuned for maximizing the performance of an unregularized neural network on our dataset collection (see Table 9 in Appendix D)."),
         ("Benchmark: 40 classification datasets (31 from the OpenML AutoML Benchmark, the remaining 8 of that benchmark being too large for the cluster, plus 9 UCI/Kaggle datasets with roughly 100K+ instances), 452 to 416,188 data points and 4 to 2,001 features, split 60/20/20; balanced accuracy is the metric, and only a single train-val-test split was evaluated per dataset in order to cover more datasets.",
          "Experimental Setup and Datasets",
          "For the sake of studying the effect on more datasets, we only evaluated a single train-val-test split."),
         ("Baseline fairness: all baselines use the same splits, the same seed and the same HPO resources as the cocktails (4 days on 20 CPU cores with 128GB memory); TabNet, XGBoost and CatBoost are tuned with BOHB (TabNet and CatBoost in the search spaces recommended by their authors), the scikit-learn GBDT via Auto-sklearn's SMAC with its default search space, and AutoGluon Tabular is restricted to neural networks.",
          "Section 5.4",
          "All baselines use the same train, validation, and test splits, the same seed, and the same HPO resources and constraints as for our automatically-constructed regularization cocktails (4 days on 20 CPU cores with 128GB of memory)."),
         ("Exception for NODE: a grid search over the authors' proposed ranges ran into multiple memory and runtime issues, so NODE was run with the default hyperparameters of its public implementation; several baselines also have N/A entries where they exceeded memory (24GB per process) or the 4-day runtime limit.",
          "Section 5.4",
          "To overcome these issues we used the default hyperparameters the authors used in their public implementation."),
         ("Results vs neural baselines: MLP+C is reported to be statistically significantly better than the other neural methods in a Wilcoxon-based critical difference analysis on 40 datasets; apart from AutoGluon, the other neural architectures (TabNet, NODE) are not competitive even against an MLP with only dropout, and adding early stopping to TabNet and NODE did not improve their rank.",
          "Section 6",
          "Apart from AutoGluon (both versions), the other neural architectures are not competitive even against an MLP regularized only with Dropout and optimized with our standard, ﬁxed training pipeline of Adam with cosine annealing."),
         ("Results vs GBDT: the well-regularized MLPs are reported to outperform XGBoost, the Auto-sklearn GBDT and CatBoost with a statistically significant margin (adding early stopping to XGBoost did not improve it), and none of the specialized prior deep methods (TabNet, NODE, AutoGluon Tabular) significantly outperforms GBDT. Over HPO time, the cocktails are reported to be statistically significantly better than XGBoost after 30 minutes.",
          "Section 6",
          "The results show that our MLPs outperform all three GBDT variants (XGBoost, auto-sklearn, and CatBoost) with a statistically signiﬁcant margin."),
         ("Stated limitations: only classification was studied (not regression); only somewhat balanced datasets (minority/majority ratio above 0.05); no extremely small or large data regimes (452 to 416,188 points); no datasets with extreme outliers, missing labels, semi-supervised or streaming data. The authors also note the recent neural architectures could benefit from the cocktails too, but integrating the regularizers into those libraries requires considerable coding effort.",
          "Conclusion: Limitations",
          "We only studied classiﬁcation, not regression."),
     ],
     "notes": "Affiliations: University of Freiburg; Leibniz University Hannover (Lindauer); Bosch Center for Artificial Intelligence (Hutter). Venue from the PDF footer ('35th Conference on Neural Information Processing Systems (NeurIPS 2021), Sydney, Australia'). Conflict of interest: the HPO method (BOHB, Falkner, Klein & Hutter), the Auto-PyTorch framework the method is built on (Zimmer, Lindauer & Hutter) and the Auto-sklearn GBDT baseline (Feurer et al. incl. Hutter) are from the authors' own groups, per the reference list; the paper does not state this as a conflict of interest. Differentiable-trees tag is for the NODE baseline. The authors also state cocktails often include at least one regularizer from every family (frequency analysis in Figure 3, values not recorded) and that cocktails beat XGBoost in only 15 minutes of HPO for the majority of datasets (Table 3, counts not recorded). Section numbers 4, 5.4 and 6 are confirmed by in-text cross-references ('(Section 4)', 'Section 5.4', '(Section 6)'); other locations use section names."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
