import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ci_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1504.01132",
     "title": "Recursive Partitioning for Heterogeneous Causal Effects",
     "authors": ["Susan Athey", "Guido Imbens"],
     "year": 2015, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1504.01132"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["decision-trees"], "par": ["supervised"],
     "proposes": ["Causal Tree (CT): a CART-style partition of the covariate space whose splitting and cross-validation criteria target the mean-squared error of conditional average treatment effects (CATE) rather than outcomes, using unbiased estimates of that infeasible MSE",
                  "Honest estimation: one sample builds the partition (including cross-validation) and an independent sample estimates the treatment effect in each leaf, with splitting/cross-validation criteria (EMSE) that anticipate this by penalizing the variance of leaf estimates"],
     "claims": [
         ("Definition of honesty: a model is honest if it does not use the same information for selecting the model structure (here the partition of the covariate space) and for estimation given that structure; this is done by splitting the training sample into one part for building the tree (including cross-validation) and another for estimating leaf treatment effects. The authors present this as an alternative to sparsity assumptions that places no restrictions on model complexity.",
          "Introduction",
          "We say that a model is “honest” if it does not use the same information for selecting the model structure (in our case, the partition of the covariate space) and for estimation given a model structure."),
         ("Trade-off of honesty: sample splitting loses precision because each estimation step uses fewer units, but there is a benefit for fit from eliminating bias that offsets at least part of that cost.",
          "Introduction",
          "Although there is a loss of precision due to sample splitting (which reduces sample size in each step of estimation), there is a beneﬁt for ﬁt in terms of eliminating bias that oﬀsets at least part of the cost."),
         ("Evaluation without ground truth: cross-validation normally relies on observed outcomes, but for the MSE of treatment effects the unit-level causal effect is never observed (the 'fundamental problem of causal inference', citing Holland); the authors address this by constructing unbiased estimates of the mean-squared error of the treatment effect.",
          "Introduction",
          "We address this by proposing approaches for constructing unbiased estimates of the mean-squared error of the causal eﬀect of the treatment."),
         ("Setting and assumptions: potential outcomes with a binary treatment, i.i.d. exchangeable units and no interference (SUTVA, which the authors note may be violated when units are connected through networks), and unconfoundedness throughout; the estimand is the CATE tau(x) = E[Y(1) - Y(0) | X = x], estimated by functions that are constant within partition elements. For exposition the main body assumes complete randomization, and the authors state that the methods can be adapted to the unconfounded case with propensity score weighting.",
          "The Problem (Unconfoundedness)",
          "Later we show that by using propensity score weighting [19], we can adapt all of the methods to that case."),
         ("Honest splitting criterion for causal trees: the estimated EMSE rewards a partition for finding strong heterogeneity in treatment effects and penalizes partitions that create variance in leaf estimates (the variance term uses within-leaf treated and control variances scaled by p and 1-p). Unlike the prediction case, the two terms are not proportional: a split on a covariate that affects mean outcomes but not treatment effects can still reduce the variance of the effect estimate.",
          "Honest Inference for Treatment Effects (Modifying the Honest Approach)",
          "The criteria reward a partition for ﬁnding strong heterogeneity in treatment eﬀects, and penalize a partition that creates variance in leaf estimates."),
         ("Inference: once the tree is built, using a distinct sample reduces the problem to estimating treatment effects in each element of a given partition, so standard confidence intervals are valid for honest estimates with no assumptions about model complexity; for the adaptive methods standard confidence intervals are not generally valid.",
          "Inference",
          "For the adaptive methods standard approaches to conﬁdence intervals are not generally valid for the reasons discussed above, and below we document through simulations that this can be important in practice."),
         ("Simulation (described by the authors as a small study with three designs; K = 2, 10 or 20 normal covariates, p = 0.5, N^tr = N^est of 500 or 1000, test sample of 6000): honest methods achieved nominal coverage of 90% confidence intervals in all designs while adaptive methods were substantially below nominal; honest estimation had a cost in MSE_tau that varied by design and estimator, which the authors summarize as sacrificing some goodness of fit in exchange for valid confidence intervals.",
          "A Simulation Study",
          "We achieve nominal coverage rates for honest methods in all designs"),
         ("Observational studies: under unconfoundedness the leaf estimates must be modified to remove bias from simple treated-control comparisons, e.g. by propensity score weighting (renormalizing weights within leaves and treatment groups improves efficiency; citing Crump et al. for trimming extreme propensity scores); additional conditions are required for asymptotic normality with propensity weighting, and these results apply without modification to the estimation phase of honest partitioning.",
          "Observational Studies with Unconfoundedness",
          "The proposed methods can be adapted to observational studies under the assumption of unconfoundedness."),
     ],
     "notes": "Affiliation: Stanford GSB and NBER; a footnote says part of the research was conducted while the authors were visiting Microsoft Research. No venue is stated in the arXiv v3 PDF (dated December 2015; first draft October 2013) and the arXiv record has no journal_ref; none recorded. The PDF headings are unnumbered, so locations use section names. Besides CT the paper compares transformed outcome trees (TOT, Y* = Y(W - p)/(p(1-p)) style transformed outcome with off-the-shelf CART; described as not efficient because it ignores the treatment indicator beyond the transformation), fit-based trees (F) and squared t-statistic trees (TS, citing Su et al.), each in adaptive and honest versions. Simulation results are in Table 1 and are not recorded. The appendix says the simulation code is an R package based on rpart 'in preparation for public release', with a minimum of nm = 25 treated and 25 control observations per leaf and covariate bucketing with b = 4; the authors note the bucketing 'can in principle make things worse'. The paper cites Wager & Athey (2015) (causal forests) as related work by an overlapping author."},

    {"id": "arxiv-1706.09523",
     "title": "Bayesian regression tree models for causal inference: regularization, confounding, and heterogeneous effects",
     "authors": ["P. Richard Hahn", "Jared S. Murray", "Carlos Carvalho"],
     "year": 2017, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1706.09523"},
     "tasks": ["causal-effect-estimation", "uncertainty-estimation"],
     "fam": ["tree-ensembles"], "par": ["supervised"],
     "proposes": ["Bayesian causal forest (BCF): E(Y | x, Z = z) = mu(x, pi-hat(x)) + tau(x) z with independent BART priors on the prognostic function mu and the treatment-effect function tau, where pi-hat is an estimated propensity score included as a covariate of mu",
                  "Stronger regularization of tau (fewer trees, stronger depth penalty, half-normal scale prior) to shrink toward homogeneous effects, and a parameter-expanded treatment coding (b0, b1) that makes inference invariant to how Z is coded"],
     "claims": [
         ("Assumptions: SUTVA (no interference, no multiple versions of treatment), strong ignorability (no unmeasured confounders) and overlap 0 < Pr(Z = 1 | x) < 1; under these the CATE tau(x) = E(Y | x, Z = 1) - E(Y | x, Z = 0). The model further restricts to mean-zero additive Gaussian errors.",
          "Section 2",
          "The ﬁrst condition assumes we have no unmeasured confounders, and the second condition (overlap) is necessary to estimate treatment eﬀects everywhere in covariate space."),
         ("Regularization-induced confounding (RIC, from Hahn et al. 2016, an earlier paper by overlapping authors): in a linear model with a ridge prior on control coefficients and a flat prior on tau, the bias of the posterior mean of tau is near zero under completely randomized assignment but, under selection, depends on unknown nuisance parameters; the authors stress that the problem is not bias per se but that its degree is not under the analyst's control, and that it can occur even with all confounders measured and a correctly specified parametric model.",
          "Section 4.1",
          "The use of a naive regularization prior in the presence of counfounding can unwittingly induce extreme bias in estimation of the target parameter, even when all the confounders are measured and the parametric model is correctly speciﬁed."),
         ("Targeted selection: treatment assigned partly on a prediction of the outcome without treatment, so the propensity score is (approximately) monotone in the prognostic function mu(x) = E(Y(0) | x); the authors suspect this is quite common in practice (e.g. physicians treating patients with worse expected untreated outcomes), and it is the setting in which RIC is easiest to reproduce in nonlinear models.",
          "Section 4.2",
          "We suspect this selection process is quite common in practice; for example, in medical contexts where risk factors for adverse outcomes are well-understood physicians are more likely to assign treatment to patients with worse expected outcomes in its absence."),
         ("In the 2-d targeted-selection example (200 datasets, n = 250, tau = -1), the authors explain BART's poor performance by tree priors penalizing the many axis-aligned splits needed for the diagonal 'shelf' while a single split in Z can stand in for them; they caution that the example is stylized, designed to be difficult for tree-based models, but argue that any informative, sparse or nonparametric prior that imposes meaningful regularization is susceptible to similar effects.",
          "Section 4 (Targeted selection and RIC in nonlinear models)",
          "Before discussing how we reduce RIC, we note that this example is somewhat stylized in that we designed it speciﬁcally to be diﬃcult to learn for tree-based models."),
         ("Remedy: include an estimate of the propensity score as a covariate so that representations involving pi(x) are penalized equitably with those involving Z; in the linear model this makes the ridge bias of tau zero, and in the nonlinear example it dramatically mitigates RIC. The authors believe this will be cheap insurance against RIC for other nonparametric priors and machine-learning outcome models (a belief, not shown for those methods).",
          "Section 4.3",
          "Finally, we believe that including an estimated propensity score will be cheap insurance against RIC when estimating treatment eﬀects using outcome models under other nonparametric priors and using more general nonparametric/machine learning approaches."),
         ("Prior specification: mu uses the Chipman et al. (2010) defaults (200 trees, beta = 2, eta = 0.95) with a half-Cauchy prior on the leaf scale; tau is regularized more strongly with 50 trees, beta = 3 and eta = 0.25 (no splits corresponds to homogeneous effects) and a half-normal scale prior with median at the marginal standard deviation of Y. The authors report that inference on tau is typically insensitive to reasonable deviations from the mu settings as long as the prior is not so strong that deconfounding does not take place.",
          "Section 5.2",
          "For τ, we prefer stronger regularization."),
         ("Benchmarking on ACIC 2016 and 2017: since the competition datasets and ground truths are public, the authors evaluate BCF (not entered in either competition) against submitted methods they did not choose, design or implement, and add causal random forests (grf, 4,000 trees, doubly robust SATT as suggested in the package documentation). The ACIC 2017 design, summarized in Hahn et al. (2018), explicitly incorporated targeted selection, unlike 2016.",
          "Section 6.2",
          "The datasets and ground truths are publicly available, so while BCF was not entered into either the 2016 or 2017 competitions we can benchmark its performance against a suite of methods that we did not choose, design, or implement."),
         ("Propensity-score uncertainty: the authors argue the model need not account for uncertainty in pi-hat (by analogy with Zellner's g-prior), but acknowledge that the adjustments only work if pi-hat accurately approximates pi, and suggest fitting BCF with different propensity estimates as a sensitivity analysis, needed only when candidate propensity models tie in cross-validated accuracy.",
          "Section 8",
          "One might consider ﬁtting a series of BCF models with diﬀerent estimates of"),
         ("Not doubly robust and limited theory: the authors do not claim BCF is doubly robust and use the natural Bayesian estimates; they state that theory is only nascent, with none speaking to frequentist coverage of Bayesian credible intervals, and that existing posterior-concentration results for Bayesian trees require modifications to the BART prior that may make them unreliable guides to practice.",
          "Section 8",
          "We do not claim our approach is doubly robust, however, and in all of our examples above we use the natural Bayesian estimates of (conditional) average treatment eﬀects"),
     ],
     "notes": "Affiliations: Arizona State University (Hahn), UT Austin (Murray, Carvalho). No venue recorded: the arXiv v4 PDF uses the Bayesian Analysis LaTeX template with placeholder issue data ('Bayesian Analysis (0000) 00, Number 0', 'DOI: 0000'), which is not a publication statement, and the arXiv record has no comment or journal_ref. Section numbers are confirmed by numbered headings in the PDF and cross-references ('Section 4.2', 'section 5.2', 'Section 6.1', 'section 8'). Conflict of interest: the ACIC 2017 competition used as a benchmark is described in Hahn, Dorie and Murray (2018), co-authored by two of the authors, and the authors state their own simulation protocol was 'designed prior to the model's development, with an eye towards realism'; RIC is from the authors' earlier work (Hahn et al. 2016); BCF is 'the default implmentation in our software package'. The authors also note that ps-BART in ACIC 2016/2017 was based on an early draft of this paper and that Nie & Wager (2017) used ps-BART in a stacked R-learner. Simulation (Section 6.1): 8 DGPs (homogeneous/heterogeneous effects, linear/nonlinear prognostic function, n = 250/500), 200 replications each, comparing BCF, ps-BART, BART, BART(f0, f1), causal RF (grf default specification) and a linear model with horseshoe prior; results are in Tables 2-5 and Figure 6 and are not recorded. The smoking/medical-expenditure application (NMES, n = 6,798 after excluding individuals younger than 28 on overlap grounds) is not recorded as claims."},

    {"id": "arxiv-1711.02582",
     "title": "Overlap in Observational Studies with High-Dimensional Covariates",
     "authors": ["Alexander D'Amour", "Peng Ding", "Avi Feller", "Lihua Lei", "Jasjeet Sekhon"],
     "year": 2017, "venue": "Journal of Econometrics", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1711.02582"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners"],
     "proposes": ["Information-theoretic analysis of the strict overlap assumption (propensity score in [eta, 1 - eta]): rewritten as a bound on the likelihood ratio between treated and control covariate distributions, it implies p-free bounds on mean discrepancy, classifier accuracy and KL divergence that become more restrictive as the covariate dimension p grows"],
     "claims": [
         ("Motivation: adding covariates is often argued to make unconfoundedness more plausible, but the same intuition has the opposite implication for overlap: the richer the covariates, the closer they come to perfectly predicting treatment for at least some subgroups.",
          "Section 1",
          "This intuition, however, has the opposite implications for overlap: the richer the set of covariates, the closer these covariates come to perfectly predicting treatment assignment for at least some subgroups."),
         ("Machine-learning covariate adjustment (citing reviews by Chernozhukov et al., 2019 and Athey & Imbens, 2019) can achieve parametric rates under very weak nonparametric assumptions, but the authors state that the cost of this flexibility is that these methods are highly sensitive to poor overlap.",
          "Section 1",
          "On the other hand, the cost of this nonparametric ﬂexibility is that these methods are highly sensitive to poor overlap."),
         ("Assumptions: the target is the ATE (results extend to ATT) under unconfoundedness given X_{1:p}; population overlap (0 < e(X) < 1) suffices for nonparametric identification but not for efficient semiparametric estimation, so strict overlap (eta <= e(X) <= 1 - eta) is typically invoked. Citing Khan & Tamer (2010), without outcome restrictions strict overlap is necessary for regular uniformly root-n-consistent semiparametric estimators; this necessity may not hold under other conditions on the potential outcomes, and relaxing it involves non-standard asymptotics where uniform inference is difficult.",
          "Section 2",
          "Strict overlap is integral across a range of settings."),
         ("Theorem 1 / Corollary 1: strict overlap bounds the mean difference between treated and control covariates by the covariance operator norm times a p-free constant; consequently, when p is large either the covariates are highly correlated under both groups or the average mean discrepancy per covariate is small (it goes to zero if the smaller operator norm grows slower than p).",
          "Section 3.2",
          "In particular, when p is large, strict overlap implies that either the covariates are highly correlated under both P0 and P1, or the average discrepancy in means across covariates is small."),
         ("Distinguishability: under strict overlap no classifier can predict treatment with accuracy above 1 - eta (Proposition 1), so there is no consistent classifier of treated vs control covariates as p grows; the KL divergence between the two covariate distributions is bounded by a p-free constant (Proposition 2), so the average unique discriminating information per covariate is O(1/p) (Corollary 3).",
          "Section 3.3",
          "Asymptotically, by Proposition 1, strict overlap implies that there exists no consistent classiﬁer of P0 against P1 in the large-p limit."),
         ("Weaker overlap under modeling assumptions: if the propensity depends only on a sufficient summary (sparse or latent-variable propensity models) strict overlap has fewer unique implications; with structural assumptions on outcomes (prognostic score, citing Hansen 2008) or a constant treatment effect (partial linear model), the ATE can be identified and estimated under weaker overlap, e.g. strict overlap holding only with positive probability, because the constant effect justifies extrapolation.",
          "Section 4.2",
          "The average treatment eﬀect can be identiﬁed and estimated under weaker overlap conditions if one is willing to make structural assumptions about the data generating process."),
         ("Trimming: the authors suggest trimming may be needed more often when p is large, but by Proposition 4 the share of units with propensity in [eta~, 1 - eta~] is bounded by the Bayes classifier error divided by eta~, so when covariates classify treatment well a trimming procedure must discard a large proportion of the sample (approaching all of it in the large-p limit if the Bayes classifier is consistent).",
          "Section 4.3",
          "In this case, a trimming procedure must throw away a large proportion of the sample."),
         ("Discussion: strict overlap implies that the information distinguishing treated and control covariate distributions stays fixed as dimension grows; regularization does not avoid these restrictions. The authors note strict overlap is testable for a fixed bound (finite-sample exact tests in separate work) and suggest such empirical validation should be standard practice.",
          "Section 5",
          "Importantly, techniques such as regularization do not avoid these restrictions, though they are often necessary for estimation with high-dimensional covariates."),
     ],
     "notes": "Affiliation: UC Berkeley Statistics (D'Amour now at Google Research; Lei now at Stanford, per page-1 footnotes). Venue: the arXiv comment says 'To appear in Journal of Econometrics'; recorded as 'Journal of Econometrics' with the first arXiv year (2017); the v4 PDF itself does not name the venue. Purely theoretical (no experiments). Section numbers from numbered headings in the PDF. Remark 1 (Section 3.1): for Gaussian covariates in one dimension strict overlap implies P0 = P1, so the authors give no Gaussian examples. Section 4.3 also states that trimming in general changes the estimand unless extra structure such as a constant treatment effect is imposed; a footnote mentions overlap weights (Crump et al.; Li et al.) as smooth trimming that the authors 'anticipate' their argument extends to. Section 5 notes overlap 'appears to play a key role' in bias amplification when unconfoundedness fails. Tag note: no registered method-family tag fits a theory-of-assumptions paper; causal-meta-learners is used because the stated implications target ML-based adjustment estimators such as DML (Section 1)."},

    {"id": "arxiv-2011.04216",
     "title": "DoWhy: An End-to-End Library for Causal Inference",
     "authors": ["Amit Sharma", "Emre Kiciman"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2011.04216", "code": "https://github.com/microsoft/dowhy"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners", "linear-models"],
     "proposes": ["DoWhy: an open-source Python library organized around four steps (Model, Identify, Estimate, Refute) that encodes assumptions as a causal graph, identifies estimands with graph criteria and do-calculus, estimates them with potential-outcome estimators (or EconML/CausalML), and runs refutation/robustness checks on the estimate"],
     "claims": [
         ("API organization: four steps required for any causal analysis, Model (prior knowledge as a causal graph), Identify (graph-based identification), Estimate (statistical estimation of the identified estimand) and Refute (testing robustness to the model's assumptions).",
          "Introduction",
          "Speciﬁcally, DoWhy’s API is organized around the four key steps that are required for any causal analysis: Model, Identify, Estimate, and Refute."),
         ("Motivation: unlike supervised models validated on held-out test data, causal tasks often have no ground-truth answer, so checking core assumptions and applying sensitivity tests is described as critical to gaining confidence in results.",
          "Introduction",
          "Unlike supervised machine learning models that can be validated using held-out test data, causal tasks often have no ground truth answer available."),
         ("Positioning: the authors state that covering all four steps is DoWhy's key differentiator compared with many Python and R libraries that focus only on estimation and leave modeling, identification and robustness checks to the analyst.",
          "Introduction",
          "The focus on all the four steps, going from data to the ﬁnal causal estimate (along with a measure of its robustness) is the key differentiator for DoWhy, compared to many existing libraries for causal inference in Python and R that only focus on estimation (the third step)."),
         ("Model and identification: the causal graph need not be complete; an analyst may give a partial graph and DoWhy treats the remaining variables as potential confounders. Supported identification criteria are back-door, front-door, instrumental variables and mediation.",
          "DoWhy and the Four Steps of Causal Inference",
          "DoWhy automatically considers the rest of the variables as potential confounders."),
         ("Estimation: back-door and IV methods (propensity stratification, matching and IPW; linear regression and GLMs; Wald estimator, two-stage least squares, regression discontinuity; two-stage linear regression for front-door/mediation), with non-parametric confidence intervals and a permutation test; CATE estimators from EconML and CausalML can be called directly (the example uses EconML's double machine learning estimator for high-dimensional confounders).",
          "DoWhy and the Four Steps of Causal Inference",
          "All estimators from these libraries can be directly called from DoWhy."),
         ("Refutation tests and their expected outcomes: add a random common cause (estimate should not change), placebo treatment and dummy outcome (effect should go to zero), simulated outcome from a known DGP closest to the data (should match the DGP's effect), add an unobserved common cause correlated with treatment and outcome (should not be too sensitive), and data-subset and bootstrap validation (should not change significantly).",
          "DoWhy and the Four Steps of Causal Inference",
          "Having access to multiple refutation methods to validate an effect estimate from a causal estimator is a key beneﬁt of using DoWhy."),
         ("Scope of the refuters: some (e.g. placebo treatment, dummy outcome) aim to refute the full analysis including modeling, identification and estimation, whereas data-subset and bootstrap validation test only the estimation step.",
          "DoWhy and the Four Steps of Causal Inference",
          "Many of the above methods aim to refute the full causal analysis, including modeling, identiﬁcation and estimation (as in Placebo Treatment or Dummy Outcome) whereas others refute a speciﬁc step (e.g., Data Subsets and Bootstrap Validation that test only the estimation step)."),
         ("Separation of identification and estimation: the authors state that, given the model, identification is a causal problem and estimation a statistical one, and DoWhy treats them separately so that multiple estimation methods can be used for a single identified estimand and vice versa.",
          "An Example Causal Analysis",
          "Given the model, identiﬁcation is a causal problem."),
     ],
     "notes": "Conflict of interest: both authors are at Microsoft Research and describe their own library (github.com/microsoft/dowhy); the paper also integrates Microsoft's EconML. The paper reports community figures in the text (over 2300 stars and 31 contributors). No empirical evaluation of the estimators or of the refutation tests' power or false-positive rate was found in the text (searched for evaluat, experiment, benchmark, simulat, accuracy; the only hits are the 'Simulated Outcome' refuter and a reference title). No venue: the arXiv comment is only '5 pages' and there is no journal_ref. The PDF has no numbered sections; locations use heading names. The refuters' 'Hint' expectations are stated as guidance without formal guarantees in the text."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
