import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1703.01541",
     "title": "Soft-DTW: a Differentiable Loss Function for Time-Series",
     "authors": ["Marco Cuturi", "Mathieu Blondel"],
     "year": 2017, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1703.01541", "code": "https://github.com/mblondel/soft-dtw"},
     "tasks": ["time-series-classification", "time-series-forecasting"],
     "fam": ["dynamic-programming", "deep-learning"], "par": ["supervised", "unsupervised"],
     "proposes": ["Soft-DTW: dynamic time warping with the min of the Bellman recursion replaced by a soft-minimum (-gamma log-sum-exp) with smoothing parameter gamma, used as a differentiable loss for barycenters, k-means clustering, nearest-centroid classification and training networks that output time series"],
     "claims": [
         ("Contribution: a differentiable loss between time series built on DTW, using a smoothed formulation (soft-DTW) that takes the soft-minimum over the costs of all alignments rather than the minimum.",
          "Abstract",
          "Our work takes advantage of a smoothed formulation of DTW, called soft-DTW, that computes the soft-minimum of all alignment costs."),
         ("Relation to the DP: soft-DTW is computed by a minor modification of Bellman's recursion for DTW (all (min, +) operations replaced by (+, x); the authors attribute such smoothed modifications of Bellman's recursion to prior work on smoothed DP distances and kernels), even though it considers all alignments instead of only the optimal one; setting gamma = 0 recovers the original DTW.",
          "Introduction",
          "Despite considering all alignments and not just the optimal one, soft-DTW can be computed with a minor modification of Bellman’s recursion, in which all (min, +) operations are replaced with (+, ×)."),
         ("Complexity: value and gradient of soft-DTW are computed in quadratic time and space; the authors contrast this with DTW's quadratic time but linear space (the gradient's backward pass needs the full matrix of intermediate costs, while the naive recursion for the expected alignment would be quartic).",
          "Abstract",
          "We show in this paper that soft-DTW is a differentiable loss function, and that both its value and gradient can be computed with quadratic time/space complexity (DTW has quadratic time but linear space complexity)."),
         ("What hard DTW lacks: the gradient of hard DTW (the optimal alignment) is defined almost everywhere for continuous data but is discontinuous where a small change switches the optimal alignment, which the authors say is likely to hamper gradient descent.",
          "The DTW and soft-DTW loss functions",
          "However, that gradient, when it exists, will be discontinuous around those values x where a small change in x causes a change in A⋆, which is likely to hamper the performance of gradient descent methods."),
         ("No optimality guarantee: the soft-DTW barycenter objective is non-convex (a soft minimum of convex functions for squared Euclidean cost), so the authors state that barycenter computations come with no way of ensuring optimality; they argue informally that smoothing gives a better (though slightly different from DTW) optimization landscape.",
          "Learning with the soft-DTW loss",
          "all of the computations involving barycenters should be taken with a grain of salt, since we have no way of ensuring optimality when approximating Eq. (4)."),
         ("Protocol: experiments use a 79-dataset subset of the UCR time series classification archive; barycenters (10 series of a random class, 10 repetitions, at most 100 iterations, L-BFGS) and k-means are compared with DBA and a subgradient method in terms of the hard DTW loss; nearest-centroid classification uses a 50/25/25 train/validation/test split with gamma chosen from 15 log-spaced values; multistep-ahead prediction uses an MLP with one hidden layer predicting the last 40% of each series.",
          "Experimental results",
          "We use a subset containing 79 datasets encompassing a wide variety of fields (astronomy, geology, medical imaging) and lengths."),
         ("Trade-off of the training loss: in the prediction experiment, training with soft-DTW gives lower DTW loss and training with the Euclidean loss gives lower Euclidean loss; the authors argue that DTW-robust errors may be the more judicious choice for many applications.",
          "Experimental results",
          "Unsurprisingly, we achieve lower DTW loss when training with the soft-DTW loss, and lower Euclidean loss when training with the Euclidean loss."),
     ],
     "notes": "PDF states: Proceedings of the 34th International Conference on Machine Learning (ICML), Sydney, 2017. Affiliations: CREST, ENSAE, Universite Paris-Saclay (Cuturi); NTT Communication Science Laboratories (Blondel). The intro says both DTW and soft-DTW have quadratic time and linear space for the value only, while the abstract's 'quadratic time/space' refers to value plus gradient (the backward pass requires the full matrix R). Gradient of soft-DTW is 2/gamma-Lipschitz for squared Euclidean cost (Section 2.3 text). Soft-DTW with gamma > 0 equals -gamma log of the Global Alignment kernel. A custom backward pass in Chainer was implemented instead of autodiff because the forward DP is element-wise. Experiments with gamma below 0.001 were not run since dtw_0.001 is very close to dtw_0 in practice. Results (percentages of datasets, ranks) not recorded."},

    {"id": "arxiv-1802.03676",
     "title": "Differentiable Dynamic Programming for Structured Prediction and Attention",
     "authors": ["Arthur Mensch", "Mathieu Blondel"],
     "year": 2018, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1802.03676"},
     "tasks": ["language-modeling"],
     "fam": ["dynamic-programming", "deep-learning"], "par": ["supervised"],
     "proposes": ["DP_Omega: a general framework that replaces max in a DAG dynamic programming recursion by a max smoothed with a strongly convex regularizer Omega (negentropy or squared l2), giving differentiable value and gradient layers; instantiated as smoothed Viterbi and smoothed DTW"],
     "claims": [
         ("Contribution: smooth the max operator inside the DP recursion with a strongly convex regularizer, relaxing both the optimal value and the optimal solution and making a broad class of DP algorithms differentiable.",
          "Abstract",
          "To address this issue, we propose to smooth the max operator in the dynamic programming recursion, using a strongly convex regularizer."),
         ("Scope: the framework is stated for DPs viewed as finding the highest-scoring path between a start and end node of a weighted DAG; the paper instantiates it for the Viterbi algorithm (sequence prediction) and DTW (time-series alignment).",
          "Differentiable DP layers",
          "Every problem solved by dynamic programming reduces to ﬁnding the highest-scoring path between a start node and an end node, on a weighted directed acyclic graph (DAG)."),
         ("Guarantees: smoothing locally inside the recursion (DP_Omega) generally differs from smoothing the global max over all paths (LP_Omega >= DP_Omega), but Proposition 2 shows DP_Omega is convex and that LP - DP_Omega lies between (N-1) times the lower and upper bounds of Omega on the simplex (Omega strongly convex; N = number of DAG nodes), so DP_{gamma Omega} converges to the hard value LP as gamma -> 0.",
          "Differentiable DP layers",
          "Although LPΩ(θ) and DPΩ(θ) are generally diﬀerent (in fact, LPΩ(θ) ≥DPΩ(θ) for all θ ∈Θ), we now show that DPΩ(θ) is a sensible approximation of LP(θ) in several respects."),
         ("Uniqueness result: for separable regularizers, the negentropy-smoothed max is the only smoothed max that is associative (so DP_Omega equals LP_Omega only for negentropy), the 'only if' part being new to the authors' knowledge (the 'if' part recovers known message-passing results).",
          "Differentiable DP layers",
          "Its proof shows that max−γH is the only maxΩ satisfying associativity, exhibiting a functional equation from information theory (Horibe, 1988)."),
         ("What is lost: the authors note that the CRF-style smoothing (changing the semiring to (+, x) on exponentiated values) loses the sparsity of solutions because hard assignments become soft; with their squared-l2 regularizer the expected path (gradient) is instead typically sparse (smaller gamma, sparser), whereas negentropy always gives dense solutions.",
          "Introduction",
          "While this modiﬁcation smoothes the dynamic program, it looses the sparsity of solutions, since hard assignments become soft ones."),
         ("Complexity: the gradient (an expected path under a random walk on the DAG) is computed by backpropagation in reverse topological order with total cost O(|E|), the same as the hard DP, under the stated assumption that the smoothed max is computable in linear time; Hessian-vector products also cost O(|E|). This holds for any strongly convex Omega in the framework; it is a complexity statement, not an approximation guarantee.",
          "Differentiable DP layers",
          "Assuming maxΩcan be computed in linear time, the total cost is O(|E|), the same as DP(θ)."),
         ("Evaluation: named entity recognition on the four CoNLL 2003 languages (step size and batch size chosen by a small grid search, model selected on the validation set), supervised audio-to-score alignment on Bach10 with leave-one-out cross-validation, and structured attention for French-English translation on a 1M-sentence WMT14 subset; for NER the authors report all losses within 1% F1 of each other with proper parameter selection.",
          "Experiments",
          "With proper parameter selections, all losses perform within 1% F1-score of each other, although entropy-regularized losses perform slightly better on 3/4 languages."),
     ],
     "notes": "Venue not stated in the PDF (dated February 21, 2018). Affiliations: Inria Parietal (Mensch; work done during an internship at NTT Communication Science Laboratories) and NTT Communication Science Laboratories (Blondel). The paper identifies its negentropy DTW instance with soft-DTW (arxiv-1703.01541, same second author); the squared-l2 case and Hessian products are stated as new. In Bach10, training uses the smoothed DTW and test-time alignment uses non-regularized DTW; the baseline is a multinomial classifier pretrained without end-to-end training. For translation, the authors state attention variants were within a small BLEU margin of softmax attention on newstest2014 (numbers not recorded). The DTW layer was implemented in Cython on CPU. Task tag 'language-modeling' covers only the translation experiment (LSTM encoder-decoder with structured attention on WMT14 FR-EN, evaluated by BLEU, i.e. a conditional language model on text); NER and audio-to-score alignment are not covered. No existing task tag fits structured prediction (sequence labelling, alignment); the schema requires at least one task tag, so the closest existing tag is kept. Results tables not recorded."},

    {"id": "arxiv-2203.15544",
     "title": "Graph Neural Networks are Dynamic Programmers",
     "authors": ["Andrew Dudzik", "Petar Veličković"],
     "year": 2022, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2203.15544"},
     "tasks": ["algorithm-learning"],
     "fam": ["graph-neural-networks", "dynamic-programming"], "par": ["supervised"],
     "proposes": ["A category-theoretic framing (integral transform over a 'polynomial span' of finite sets, with values in a semiring) that describes both DP recursions such as Bellman-Ford and message-passing GNNs, and a GNN variant with order-3 (V^3) messages for edge-centric algorithms"],
     "claims": [
         ("Contribution: using category theory and abstract algebra, the authors argue for a connection between GNNs and DP that goes beyond prior observations on single algorithms such as Bellman-Ford, and report CLRS experiments.",
          "Abstract",
          "Here we show, using methods from category theory and abstract algebra, that there exists an intricate connection between GNNs and DP, going well beyond the initial observations over individual algorithms such as Bellman-Ford."),
         ("Critique of prior work: the authors state that the original algorithmic-alignment paper (their reference [37]) only mentioned in passing that DP seems to align with GNNs and demonstrated one example, Bellman-Ford, and that they found no concrete follow-up.",
          "Introduction",
          "Indeed, the original work of [37] merely mentions in passing that the formulation of DP algorithms seems to align with GNNs, and demonstrates one example (Bellman-Ford)."),
         ("Status of the formal claim: the integral transform (pullback, argument pushforward, message pushforward) is a construction; that it can be described as a polynomial functor is stated as a conjecture. No statement labelled as a theorem, proposition or lemma was found in the text (the only 'can be proved' refers to prior work's NTK-regime sample-complexity result), so the GNN-DP correspondence is a framework plus a conjecture, not a proven result.",
          "The integral transform",
          "Taken together, they form an integral transform—and we conjecture that this transform can be described as a polynomial functor, where p⊗and o⊕correspond to the dependent product and dependent sum from type theory (cf. Appendix D for details)."),
         ("Framework rather than theorem: in the conclusion the authors describe their work as deriving a generic integral-transform diagram and arguing that it is general enough to cover both GNN and DP computations (Bellman-Ford is derived over the min-plus semiring; MPNN as the same transform over the reals plus an MLP).",
          "Conclusions",
          "We derived a generic diagram of an integral transform (based on standard categorical concepts like pullback, pushforward and commutative monoids), and argued why it is general enough to support both GNN and DP computations."),
         ("Protocol: six CLRS Algorithmic Reasoning Benchmark tasks with the CLRS data generation and base model code reused exactly (small MLPs, embedding dimension 24), test results out-of-distribution; then 27 CLRS tasks with the PGN processor and 96-dimensional embeddings, comparing V^2 (edge updates without the polynomial-span correction) against the proposed V^3 messages.",
          "Improving GNNs with edge updates, with experimental evaluation",
          "We reuse exactly the data generation and base model implementations in the publicly available code for the CLRS benchmark."),
         ("Empirical claim: the V^3 architecture matched or outperformed V^2 on all edge-centric algorithms up to standard error, with smaller and less consistent gains on other tasks; the authors read this as directly validating their theory's predictions (an empirical reading on CLRS, not a proof).",
          "Improving GNNs with edge updates, with experimental evaluation",
          "We found that the V 3 architecture was equivalent to, or outperformed, the non-polynomial (V 2) one in all edge-centric algorithms (up to standard error)."),
         ("Affiliation and funding: both authors are at DeepMind and the research was funded by DeepMind.",
          "Acknowledgments and Disclosure of Funding",
          "This research was funded by DeepMind."),
     ],
     "notes": "PDF states: 36th Conference on Neural Information Processing Systems (NeurIPS 2022). The value space R is required to be a semiring: reals with (x, +) for GNNs and tropical numbers with (+, min) for DP. The authors say max aggregation in GNNs aligns with the min of Bellman-Ford and that the corrected V^3 span targets algorithms like Floyd-Warshall that reduce over an intermediate node. The six tasks: Dijkstra, Find Maximum Subarray, Floyd-Warshall, Insertion Sort, Matrix Chain Order, Optimal BST. Baselines use fully connected graphs (E = V^2). Results tables not recorded."},

    {"id": "arxiv-1602.02867",
     "title": "Value Iteration Networks",
     "authors": ["Aviv Tamar", "Yi Wu", "Garrett Thomas", "Sergey Levine", "Pieter Abbeel"],
     "year": 2016, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1602.02867", "code": "https://github.com/avivt/VIN"},
     "tasks": ["algorithm-learning"],
     "fam": ["dynamic-programming", "deep-learning"], "par": ["reinforcement-learning", "supervised"],
     "proposes": ["Value Iteration Network (VIN): a policy network containing a differentiable VI module that runs K iterations of value iteration as convolution (per-action Q channels, kernels as discounted transitions) plus max-pooling over actions on a learned planning MDP, followed by attention and a reactive policy, trained end-to-end by IL or RL"],
     "claims": [
         ("Contribution: a neural network with an embedded planning module, based on a differentiable approximation of value iteration that is represented as a CNN and trained end-to-end by backpropagation.",
          "Abstract",
          "Key to our approach is a novel differentiable approximation of the value-iteration algorithm, which can be represented as a convolutional neural network, and trained end-to-end using standard backpropagation."),
         ("How VI is embedded: one VI iteration is seen as a convolution layer (each channel a per-action Q function, kernel weights the discounted transition probabilities) followed by max-pooling over actions; recurrently applying it K times performs K VI iterations on a planning MDP whose reward and transitions are learned from the observation.",
          "The Value Iteration Network Model",
          "Thus by recurrently applying a convolution layer K times, K iterations of VI are effectively performed."),
         ("Guarantees: the planning MDP is not assumed known and its learned rewards/transitions need not match the true task; the authors describe the VI module only as an architecture capable of approximate VI (the convergence of exact VI to V* is cited in the background, not claimed for VIN).",
          "The Value Iteration Network Model",
          "The VI module is simply a NN architecture that has the capability of performing an approximate VI computation."),
         ("Generalization claim (authors' abstract): learning an explicit planning computation makes VIN policies generalize better to new, unseen domains. In the grid-world, 'unseen domains' are new random maps (obstacles, goal, start) of the same size as in training, evaluated per size (8x8, 16x16, 28x28, K set per size); in continuous control, 40 test instances from the same distribution as the 200 training instances. No evaluation on grids larger than those trained on was found.",
          "Abstract",
          "We show that by learning an explicit planning computation, VIN policies generalize better to new, unseen domains."),
         ("Protocol (grid-world): policies are trained by imitation learning on random grid-worlds (5000 instances with 7 shortest-path trajectories each per the appendix) and evaluated on a held-out test set of maps with random obstacles, goals and start states, separately for 8x8, 16x16 and 28x28 sizes (K set per size); baselines are a DQN-inspired CNN and an FCN; metrics are 0-1 action prediction loss, trajectory success rate and path-length difference to the optimal trajectory.",
          "Experiments",
          "In Table 1 we present the average 0 −1 prediction loss of each model, evaluated on a held-out test-set of maps with random obstacles, goals, and initial states, for different problem sizes."),
         ("Finding on reactive baselines: their prediction loss is comparable to VIN's while their success rate is much worse, which the authors interpret as VIN focusing errors on less important parts of the trajectory rather than ordinary over- or underfitting.",
          "Experiments",
          "Importantly, note that the prediction loss for the reactive policies is comparable to the VINs, although their success rate is signiﬁcantly worse."),
         ("Ablation and limitation of the planning prior: untying the weights of the K recurrent layers degrades performance, more so with less training data; in WebNav, VIN was only mildly better than the reactive baseline when starting from the root node (the authors conclude a reactive policy is sufficient there) and significantly better when starting from a random position in the graph.",
          "Experiments",
          "Our results, reported in the supplementary material, show that untying the weights degrades performance, with a stronger effect for smaller sizes of training data."),
     ],
     "notes": "PDF states: 30th Conference on Neural Information Processing Systems (NIPS 2016), Barcelona. Affiliation: Dept. of EECS, UC Berkeley; funded in part by Siemens, ONR, the Army Research Office and NSF. Other domains: Mars rover navigation from terrain images (16x16 grid on 128x128 patches; compared with a planner using a CNN obstacle classifier trained with elevation labels), a 2D continuous-control domain trained with guided policy search (200 training and 40 test instances from the same distribution; VIN pre-trained with grid-world transition weights), and WebNav on Wikipedia for Schools (VIN plans on a small graph of 1st/2nd level categories). Appendix reports RL training on grid-worlds and hierarchical VINs. 'Unseen domains' in the grid-world are new maps from the same random distribution, with results reported per grid size; I did not find an experiment evaluating on grid sizes larger than those used in training. Results tables not recorded."},

    {"id": "arxiv-2102.11756",
     "title": "Deep Policy Dynamic Programming for Vehicle Routing Problems",
     "authors": ["Wouter Kool", "Herke van Hoof", "Joaquim Gromicho", "Max Welling"],
     "year": 2021, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2102.11756", "code": "https://github.com/wouterkool/dpdp"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["dynamic-programming", "graph-neural-networks"], "par": ["supervised"],
     "proposes": ["DPDP: restricted (beam) dynamic programming over DP states for TSP, CVRP and TSPTW, where a GNN-predicted edge heatmap defines the score (heat plus heat-to-go potential) used to keep the B best partial solutions and, via a threshold, a sparse graph of allowed expansions"],
     "claims": [
         ("Contribution: DPDP restricts and prioritizes the DP state space with a policy derived from a neural network trained to predict edges from example solutions (ML used to improve the DP, not DP inside the network).",
          "Abstract",
          "DPDP prioritizes and restricts the DP state space using a policy derived from a deep neural network, which is trained to predict edges from example solutions."),
         ("Guarantees: the algorithm is a beam search over DP states (dominated partial solutions removed per DP state, B best kept by the heatmap score); the authors call it asymptotically optimal because a beam B = n * 2^n for an n-node TSP (i.e. keeping all DP states) guarantees optimal results; with the smaller beams used in practice (e.g. 10K, 100K) no optimality guarantee is stated, and B trades solution quality for computation. The sparse graph (c3) may additionally exclude optimal tours.",
          "Deep Policy Dynamic Programming",
          "DPDP is asymptotically optimal as using B = n · 2n for a TSP with n nodes guarantees optimal results, but choosing smaller B allows to trade performance for computational cost."),
         ("Graph sparsity: the DP runs on a sparse graph defined either by thresholding the heatmap (default 10^-5; a second use of the network that the authors say can be seen as learned problem reduction) or by a kNN graph; the authors state that using a sparse graph significantly reduces runtime but may sacrifice the possibility to find good or optimal tours.",
          "Graph sparsity",
          "As our problems are deﬁned on sets of nodes rather than graphs, the use of a sparse graph is an artiﬁcial design choice, which allows to signiﬁcantly reduce the runtime but may sacriﬁce the possibility to ﬁnd good or optimal tours."),
         ("Tuning: the heatmap threshold and the functional form of the scoring policy are educated guesses or manually tuned on a few validation instances, as are runtime-related implementation choices.",
          "Implementation & hyperparameters",
          "DPDP has very few hyperparameters, but the heatmap threshold of 10−5 and details like the functional form of e.g. the scoring policy are ‘educated guesses’ or manually tuned on a few validation instances and can likely be improved."),
         ("Protocol (TSP): 100-node TSP on a commonly used test set of 10000 instances, with optimality gaps computed using Concorde, LKH and Gurobi and comparison to published neural approaches; the authors caution that running times are rough indications since some come from different machines (typically 1 GPU or an 8-32 core CPU). VRP and TSPTW experiments also use 100-node instances.",
          "Experiments",
          "In Table 1 we report our main results for DPDP with beam sizes of 10K (10 thousand) and 100K, for the TSP with 100 nodes on a commonly used test set of 10000 instances [31]."),
         ("Evaluation practice: for VRP the authors compare against HGS and multiple LKH runs, stressing that most related neural work uses a single LKH run as the strongest baseline, and state that their goal is reasonable performance from a flexible framework rather than beating HGS or LKH.",
          "Experiments",
          "We emphasize that in most related work (e.g. [31]), the strongest baseline considered is one run of LKH, so we compare against a much stronger baseline."),
         ("Limitations: the authors state DPDP is not yet a practical alternative in general and list scalability to larger instances (mainly the fully connected O(n^2) GNN), dependence on example solutions from an existing solver, and the heuristic, manually designed scoring function.",
          "Discussion",
          "We believe such research could yield signiﬁcant further improvement by addressing key current limitations: (1) the scalability to larger instances, (2) the dependency on example solutions and (3) the heuristic nature of the scoring function."),
     ],
     "notes": "Affiliations: University of Amsterdam; Kool and Gromicho also ORTEC (company). Venue not stated in the PDF. Training data: for TSP a pretrained heatmap model from prior work trained to predict optimal solutions; for VRP 1 million 100-node instances solved with one LKH run (not optimal), checkpoint chosen by validation loss; for TSPTW example solutions from heuristic DP with a large beam. Test data: TSP/VRP validation and test sets of prior work, plus a 'more realistic' VRP distribution where LKH by default failed on two instances and was rerun with unlimited routes; TSPTW instances from prior work with small time windows were solved optimally by the DP even with very small beam sizes, 'eliminating the need for a policy', so a larger-time-window distribution was added; TSPTW is compared to GVNS (30 runs), LKH and BaB-DQN*/ILDS-DQN* (the latter not rerun for the larger windows). Hardware: DPDP on 4 GPUs with estimated 1-GPU (1080Ti) times vs 16 or 32 CPUs for HGS/LKH; the authors note GPU vs CPU comparison is hard. Heatmap threshold strategy compared against kNN sparsification. Results tables not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): algorithm design techniques (divide and conquer, dynamic programming, branch and bound, local search) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
