import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_diff_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2102.09672",
     "title": "Improved Denoising Diffusion Probabilistic Models",
     "authors": ["Alex Nichol", "Prafulla Dhariwal"],
     "year": 2021, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2102.09672"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised"],
     "proposes": ["Learned reverse-process variances, parameterized as a log-domain interpolation between beta_t and beta-tilde_t, trained with a hybrid objective L_hybrid = L_simple + lambda * L_vlb (lambda = 0.001, stop-gradient on the mean for the L_vlb term)",
                  "A cosine noise schedule for alpha-bar_t that adds noise more slowly than the linear schedule of Ho et al. (2020)",
                  "Importance sampling of timesteps (p_t proportional to sqrt(E[L_t^2])) to reduce gradient noise when optimizing L_vlb directly",
                  "Sampling with a strided subsequence of timesteps (e.g. 50-100 steps) from models trained with 4000 steps, without fine-tuning"],
     "claims": [
         ("Motivation: Ho et al. (2020) obtained high-fidelity samples by FID and Inception Score but were unable to achieve competitive log-likelihoods with DDPMs; the authors argue it is important to explore why, since this may suggest a fundamental shortcoming such as bad mode coverage.",
          "3. Improving the Log-likelihood",
          "Thus, it is important to explore why DDPMs seem to perform poorly on this metric, since this may suggest a fundamental shortcoming such as bad mode coverage."),
         ("Diagnosis: beta_t and beta-tilde_t (the two fixed variance choices of Ho et al.) are almost equal except near t = 0, which may explain why the choice does not matter for samples; but the first few diffusion steps contribute the most to the variational lower bound, so a better choice of Sigma_theta seems likely to improve log-likelihood (shown in Figures 1-2).",
          "3.1. Learning Σθ(xt, t)",
          "Thus, it seems likely that we could improve log-likelihood by using a better choice of Σθ(xt, t)."),
         ("The linear noise schedule of Ho et al. (2020) worked well for high-resolution images but was sub-optimal at 64x64 and 32x32, because the end of the forward process is too noisy and contributes little to sample quality; the cosine schedule is the proposed fix. The authors say the choice of cos^2 was arbitrary.",
          "3.2. Improving the Noise Schedule",
          "We found that while the linear noise schedule used in Ho et al. (2020) worked well for high resolution images, it was sub-optimal for images of resolution 64 × 64 and 32 × 32."),
         ("Optimizing L_vlb directly was difficult in practice, at least on ImageNet 64x64: the hybrid objective reached better training-set log-likelihoods in the same training time, which the authors attribute to much noisier L_vlb gradients (confirmed by gradient noise scales); importance sampling of timesteps then allowed the best log-likelihoods by optimizing L_vlb.",
          "3.3. Reducing Gradient Noise",
          "With this importance sampled objective, we are able to achieve our best log-likelihoods by optimizing Lvlb."),
         ("Likelihood vs sample quality trade-off: L_hybrid with the cosine schedule improves log-likelihood while keeping FID similar to the Ho et al. baseline, whereas optimizing L_vlb further improves log-likelihood at the cost of a higher FID; the authors generally prefer L_hybrid.",
          "3.4. Results and Ablations",
          "Optimizing Lvlb further improves log-likelihood at the cost of a higher FID."),
         ("Ablation setup: to study the modifications, fixed model architectures with fixed hyperparameters are trained on ImageNet 64x64 and CIFAR-10. In early experiments, increasing T from 1000 to 4000 improved log-likelihood, and T = 4000 is used for the rest of the section.",
          "3. Improving the Log-likelihood",
          "To study the effects of different modiﬁcations, we train ﬁxed model architectures with ﬁxed hyperparameters on the ImageNet 64 × 64 (van den Oord et al., 2016b) and CIFAR-10 (Krizhevsky, 2009) datasets."),
         ("FID protocol: 50K samples were generated except for unconditional ImageNet 64x64, where 10K samples were used; the authors note that 10K samples biases FID upward and accept this because FID is mainly used for relative comparisons there. Reference statistics use the full training set for CIFAR-10 and ImageNet.",
          "Appendix A (Hyperparameters)",
          "Since we mainly use FID for relative comparisons on unconditional ImageNet 64×64, this bias is acceptable."),
         ("Scaling: validation NLL does not fit a power law in training compute as cleanly as FID; the authors list possible causes (an unexpectedly high irreducible loss or overfitting) and note these models were trained with L_hybrid rather than L_vlb, so they do not achieve optimal log-likelihoods.",
          "6. Scaling Model Size",
          "We also note that these models do not achieve optimal log-likelihoods in general because they were trained with our Lhybrid objective and not directly with Lvlb to keep both good log-likelihoods and sample quality."),
     ],
     "notes": "Affiliation: OpenAI. No venue is stated in the PDF (arXiv v1); none recorded. Other protocol facts in the text: the class-conditional ImageNet 64x64 comparison with BigGAN-deep used 50K samples and an own-trained BigGAN-deep (125K iterations, no truncation); dropout was swept over {0.1, 0.2, 0.3} on CIFAR-10 (Appendix A); all models overfit on CIFAR-10 and on class-conditional ImageNet 64x64, and the authors concluded that early stopping was the best way to train for FID (Appendices F-G; the data used for early stopping is not stated in the quoted passages). Sampling: L_simple models with fixed variances lost much more sample quality with fewer sampling steps than the L_hybrid model; 100 steps sufficed for near-optimal FID for fully trained models (Section 4); DDIM was better below 50 steps and worse at 50 or more. Appendix D reports that theta_vlb is better at the start and end of the diffusion process and theta_hybrid in the middle. Tables 1-5 (NLL/FID) not recorded."},

    {"id": "arxiv-2107.00630",
     "title": "Variational Diffusion Models",
     "authors": ["Diederik P. Kingma", "Tim Salimans", "Ben Poole", "Jonathan Ho"],
     "year": 2021, "venue": "NeurIPS 2021", "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/2107.00630"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models", "variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["VDM: a diffusion model whose noise schedule (SNR(t) = exp(-gamma_eta(t)), gamma_eta a monotonic network) is learned jointly with the denoising model by maximizing the VLB, in discrete and continuous time",
                  "An expression of the VLB in terms of the signal-to-noise ratio, showing that in continuous time the VLB depends on the schedule only through SNR at its endpoints",
                  "Fourier features appended to the denoising network input to model fine-scale detail for likelihood",
                  "Learning the schedule between the endpoints to minimize the variance of the VLB estimator"],
     "claims": [
         ("Framing: diffusion probabilistic models can be viewed as a type of VAE whose structure and loss allow efficient training of arbitrarily deep models; optimizing the diffusion process jointly with the rest of the model turns it into a type of VAE.",
          "Related work",
          "DPMs can be viewed as a type of variational autoencoder (VAE) [Kingma and Welling, 2013, Rezende et al., 2014], whose structure and loss function allows for efﬁcient training of arbitrarily deep models."),
         ("Theory: in continuous time, the diffusion loss depends on alpha(t) and sigma(t) only through SNR at the endpoints t = 0 and t = 1; given SNR_min and SNR_max, the VLB is invariant to the shape of SNR(t) in between, and diffusion specifications satisfying the paper's mild constraints (including variance-exploding and variance-preserving) can be seen as equivalent in continuous time.",
          "Equivalence of diffusion models in continuous time",
          "The VLB is thus only impacted by the function SNR(t) through its endpoints SNRmin and SNRmax."),
         ("Discrete vs continuous time: if the denoising model is sufficiently good, doubling the number of timesteps (with a fixed SNR function) lowers the diffusion loss, i.e. more timesteps give a better VLB; this motivates the continuous-time (T -> infinity) model.",
          "More steps leads to a lower loss",
          "We then ﬁnd that if our trained denoising model ˆxθ is sufﬁciently good, we have that L2T (x) < LT (x), i.e. that our VLB will be better for a larger number of timesteps."),
         ("Weighted losses (as used for perceptual quality) put more emphasis on noisier data than the VLB and can sometimes improve FID and Inception Score; the models in this paper use w(v) = 1, the unweighted VLB.",
          "Weighted diffusion loss",
          "For the models presented in this paper, we further use w(v) = 1 as corresponding to the (unweighted) VLB."),
         ("Likelihood vs sample quality: the CIFAR-10 model, with hyperparameters tuned for likelihood, has FID 7.41, worse than recent diffusion models that target FID; with the weighting of Ho et al. (2020) the FID improves to 4.0. The authors did not tune further for FID.",
          "Likelihood and samples",
          "Our CIFAR-10 model, whose hyper-parameters were tuned for likelihood, results in a FID (perceptual quality) score of 7.41."),
         ("Ablation: learning the SNR is necessary to get the most out of Fourier features; with the fixed schedule of Ho et al. (2020) the maximum log-SNR is about 8 and test-set negative likelihood stays above 4 bits per dim, whereas the learned maximum log-SNR ends up at 13.3.",
          "Ablations",
          "In addition, we ﬁnd that learning the SNR is necessary to get the most out of including Fourier features"),
         ("The authors hypothesize that DDPM and improved DDPM report better FID and IS than NCSN and this paper because their implied loss weightings emphasize global consistency and coarse patterns more than fine-scale features.",
          "Appendix K",
          "The latter two works report better FID and Inception Score than Song et al. [2020] and the current paper, which we hypothesize is due to their loss emphasizing the global consistence and coarse level patterns more than the ﬁne scale features of the data."),
         ("Evaluation protocol: the variational bound is regularly evaluated on the validation set and the models were not found to overfit, so no early stopping is used; CIFAR-10 models are trained for 10 million updates and ImageNet for 2 million before reporting test-set numbers. The reported VDM numbers are variational bounds.",
          "Appendix B.1",
          "We therefore do not use early stopping and instead allow the network to be optimized for 10 million parameter updates for CIFAR-10, and for 2 million updates for ImageNet, before obtaining the test set numbers reported in this paper."),
     ],
     "notes": "Affiliation: Google Research. Venue from the PDF footer ('35th Conference on Neural Information Processing Systems (NeurIPS 2021)') and the arXiv comment. Conflict of interest: Jonathan Ho is an author of DDPM (Ho et al., 2020) and Kingma of the VAE, Glow and IAF, and Kingma/Poole are co-authors of EBM-DRL (Gao et al., 2020); these are baselines in Table 1. Table 1 compares bits/dim numbers taken from other papers with differing data augmentations (marked A/B/C). Lossless compression (bits-back, BB-ANS) is also demonstrated; the authors note a gap to the theoretical codelength and high cost for large T_eval. Fourier features gave no benefit when added to PixelCNN++. Tables 1-2 not recorded."},

    {"id": "arxiv-2208.11970",
     "title": "Understanding Diffusion Models: A Unified Perspective",
     "authors": ["Calvin Luo"],
     "year": 2022, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2208.11970"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models", "variational-autoencoders"], "par": ["unsupervised"],
     "proposes": [],
     "claims": [
         ("Tutorial framing: a variational diffusion model is presented as a Markovian hierarchical VAE with three restrictions: latent dimension equal to data dimension, a fixed (not learned) linear Gaussian encoder at each timestep, and encoder parameters chosen so the final latent is a standard Gaussian.",
          "Variational Diffusion Models",
          "The easiest way to think of a Variational Diﬀusion Model (VDM) [4, 5, 6] is simply as a Markovian Hierarchical Variational Autoencoder with three key restrictions:"),
         ("The ELBO derivations use only the Markov assumption, so they hold for any Markovian HVAE, and with T = 1 both forms reduce exactly to the ELBO of a vanilla VAE.",
          "Variational Diffusion Models",
          "Furthermore, when we set T = 1, both of the ELBO interpretations for a VDM exactly recreate the ELBO equation of a vanilla VAE, as written in Equation 19."),
         ("A first ELBO form (consistency terms over two random variables per timestep) may have high-variance Monte Carlo estimates for large T; rewriting encoder transitions via Bayes' rule gives a form where each term is an expectation over at most one random variable, estimable with lower variance.",
          "Variational Diffusion Models",
          "As it is computed by summing up T −1 consistency terms, the ﬁnal estimated value of the ELBO may have high variance for large T values."),
         ("Learning the noise schedule: the per-timestep objective can be written in terms of the SNR, which must decrease monotonically, and the SNR can be parameterized by a neural network and learned jointly with the diffusion model.",
          "Learning Diffusion Noise Parameters",
          "Following the simpliﬁcation of the objective in Equation 110, we can directly parameterize the SNR at each timestep using a neural network, and learn it jointly along with the diﬀusion model."),
         ("Three equivalent objectives: predicting the original image x0, the source noise, or the score at an arbitrary noise level (the latter via Tweedie's formula). Citing [5, 7] (Ho et al.; Saharia et al.), the tutorial notes that some works found noise prediction to perform better empirically.",
          "Three Equivalent Interpretations",
          "We have therefore derived three equivalent objectives to optimize a VDM: learning a neural network to predict the original image x0, the source noise ϵ0, or the score of the image at an arbitrary noise level ∇log p(xt)."),
         ("Score-based link: citing Song and Ermon, vanilla score matching has three problems (ill-defined score on low-dimensional manifolds, inaccurate scores in low-density regions, Langevin dynamics that may not mix), which adding multiple levels of Gaussian noise addresses; the resulting objective almost exactly matches the VDM objective.",
          "Score-based Generative Models",
          "It turns out that these three drawbacks can be simultaneously addressed by adding multiple levels of Gaussian noise to the data."),
         ("Stated drawbacks of diffusion models: no interpretable latents (the encoder is a fixed linear Gaussian, so intermediate latents are just noisy versions of the input), latents restricted to the input dimensionality, and expensive sampling because all timesteps must be iterated.",
          "Closing",
          "The VDM does not produce interpretable latents."),
         ("The author suggests that the success of diffusion models highlights the power of hierarchical VAEs, and that further gains may be achieved with general deep HVAEs with complex encoders and semantically meaningful latent spaces.",
          "Closing",
          "As a ﬁnal note, the success of diﬀusion models highlights the power of Hierarchical VAEs as a generative model."),
     ],
     "notes": "Tutorial / review paper (Google Research, Brain Team); it derives existing results and reports no experiments. 'Variational Diffusion Model' is used here as a name for diffusion models in general (citing Sohl-Dickstein et al., Ho et al., Kingma et al. [4, 5, 6]). No venue stated in the PDF; none recorded. Also covers classifier and classifier-free guidance, stating that guidance trades sample diversity for adherence to conditioning information."},

    {"id": "arxiv-2209.00796",
     "title": "Diffusion Models: A Comprehensive Survey of Methods and Applications",
     "authors": ["Ling Yang", "Zhilong Zhang", "Yang Song", "Shenda Hong", "Runsheng Xu", "Yue Zhao", "Wentao Zhang", "Bin Cui", "Ming-Hsuan Yang"],
     "year": 2022, "venue": "ACM Computing Surveys", "version": "arXiv v15",
     "links": {"arxiv": "https://arxiv.org/abs/2209.00796"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised"],
     "proposes": [],
     "claims": [
         ("Taxonomy: research on diffusion models is categorized into efficient sampling (Section 3), improved likelihood estimation (Section 4) and handling data with special structures (Section 5), with connections to other generative models in Section 6.",
          "Introduction",
          "categorizing it into three key areas: efficient sampling (Section 3), improved likelihood estimation (Section 4), and methods for handling data with special structures (Section 5)"),
         ("Improved likelihood: the training objective is a variational lower bound that, citing VDM [155], may not be tight in many cases, leading to potentially suboptimal log-likelihoods; the survey covers noise schedule optimization, reverse variance learning and exact log-likelihood evaluation.",
          "Diffusion Models with Improved Likelihood",
          "This bound, however, may not be tight in many cases [155], leading to potentially suboptimal log-likelihoods from diffusion models."),
         ("Summary of VDM: noise schedules do not affect the VLB as long as they share the same endpoint SNR values, and only affect the variance of Monte Carlo estimators of the VLB.",
          "Noise Schedule Optimization",
          "As a result, noise schedules do not affect the VLB as long as they share the same values at Rmin and Rmax, and will only affect the variance of Monte Carlo estimators for VLB."),
         ("Summary of reverse variance learning: classical diffusion models fix the reverse-kernel variance, and many methods train it to further maximize the VLB and log-likelihood (iDDPM's interpolation with a hybrid objective; Analytic-DPM's optimal variance from a pre-trained score model).",
          "Reverse Variance Learning",
          "Many methods propose to train the reverse variances as well to further maximize VLB and log-likelihood values."),
         ("Exact likelihood: the probability-flow-ODE likelihood can be computed accurately but cannot be directly optimized because it requires an expensive ODE solve per data point; Song et al. (2021) maximize the SDE variational bound as a proxy (ScoreFlows).",
          "Exact Likelihood Computation",
          "Unfortunately, this formula cannot be directly optimized to maximize 𝑝ode 𝜃 on data, as it requires calling expensive ODE solvers for each data point x0."),
         ("VAE connection: DDPM can be conceptualized as a hierarchical Markovian VAE with a fixed encoder (the linear Gaussian forward process), a decoder shared across decoding steps, and latents of the same size as the data.",
          "Variational Autoencoders and Connections with Diffusion Models",
          "The DDPM can be conceptualized as a hierarchical Markovian VAE with a fixed encoder."),
         ("Future directions: the assumption that the forward process completely erases information may not always hold, since complete removal is unachievable in finite time; when to halt the forward process to balance sampling efficiency and sample quality is open.",
          "Future Directions",
          "In reality, complete removal of information is unachievable in finite time."),
         ("Future directions: diffusion models are less effective than VAEs or GANs at providing good latent representations, and because the latent space often has the data's dimensionality, sampling efficiency suffers and the models may not learn representation schemes well.",
          "Future Directions",
          "Unlike variational autoencoders or generative adversarial networks, diffusion models are less effective for providing good representations of data in their latent space."),
     ],
     "notes": "Survey paper (Peking University and others). Venue: the PDF footer states 'Accepted by ACM Computing Surveys' (ACM reference format lists 2023); the year recorded is the arXiv year 2022. Conflict of interest: co-author Yang Song is an author of several surveyed methods (score-based models, Score SDE, ScoreFlow). No experiments. Section 3 (efficient sampling) splits methods into learning-free and learning-based sampling, motivated by the large number of evaluation steps. Note: on p.14 the survey describes the iDDPM reverse variance as an interpolation between beta_t and 1 - alpha-bar_t, whereas p.15 (and the iDDPM paper) use beta-tilde_t; this inconsistency is in the source. Applications (Section 7) not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
