import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tree_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-0804.2752",
     "title": "Boosting Algorithms: Regularization, Prediction and Model Fitting",
     "authors": ["Peter Bühlmann", "Torsten Hothorn"],
     "year": 2008, "venue": "Statistical Science", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/0804.2752", "doi": "10.1214/07-STS242"},
     "tasks": ["tabular-regression", "tabular-classification"],
     "fam": ["gradient-boosted-trees", "linear-models"], "par": ["supervised"],
     "proposes": ["A statistical review of boosting as functional gradient descent (FGD) for fitting structured models (linear, additive, survival), with degrees of freedom and information criteria (corrected AIC) for choosing the stopping iteration, illustrated with the authors' R package mboost"],
     "claims": [
         ("Citing Breiman [15, 16], the authors state that AdaBoost can be represented as a steepest-descent algorithm in function space, which they call functional gradient descent (FGD); Friedman, Hastie and Tibshirani [33] and Friedman [32] then developed a more general statistical framework ('stagewise, additive modeling').",
          "Section 2",
          "showed that the AdaBoost algorithm can be represented as a steepest descent algorithm in function space which we call functional gradient descent (FGD)."),
         ("Generic FGD algorithm (as given by Friedman [32]): repeatedly fit the negative gradient of the loss at the current fit with a real-valued base procedure and add it with a step-length factor 0 < nu <= 1; the stopping iteration mstop is the main tuning parameter, chosen by cross-validation or an information criterion.",
          "Section 2.1",
          "The stopping iteration, which is the main tuning parameter, can be determined via cross-validation or some information criterion; see Section 5.4."),
         ("Step length (shrinkage): the choice of nu is described as of minor importance as long as it is small (e.g. 0.1); a smaller nu typically requires more iterations and computing time, while predictive accuracy has been empirically found (citing Friedman [32]) to be potentially better and almost never worse.",
          "Section 2.1",
          "The choice of the step-length factor ν in step 4 is of minor importance, as long as it is “small,” such as ν = 0.1."),
         ("Early stopping: after the earlier debate on whether AdaBoost is immune to overfitting, the authors state (citing [7, 51, 64]) that AdaBoost and other boosting algorithms eventually overfit, so early stopping is necessary, although AdaBoost is quite resistant to overfitting (slow overfitting) as iterations increase.",
          "Section 1.3",
          "It is clear nowadays that Ada-Boost and also other boosting algorithms are overﬁtting eventually, and early stopping"),
         ("Tree base learners: regression trees are invariant under monotone transformations of the predictors and handle continuous, ordinal and nominal covariates in a unified way; boosting stumps gives an additive model, and boosting trees with at most d terminal nodes gives a model with interactions of order at most d - 2, so the interaction degree can be constrained via the number of nodes.",
          "Section 4.3",
          "Similarly, boosting trees with (at most) d terminal nodes result in a nonparametric model having at most interactions of order d −2."),
         ("Low-variance principle: the authors advise choosing a base procedure (with the desired structure) with low variance at the price of larger estimation bias; a small step-size factor can be seen as shrinking the base procedure by nu, implying low variance but potentially large estimation bias.",
          "Section 4.4",
          "Note that a small step-size factor can be seen as a shrinkage of the base procedure by the factor ν, implying low variance but potentially large estimation bias."),
         ("For L2Boosting with a linear base procedure, the boosting hat matrix B_m = I - (I - H)^m converges to the identity, i.e. the fit eventually interpolates the responses, so iterations must be stopped early; the eigen-analysis (Section 1.3 summary) shows variance increasing in exponentially small increments while squared bias decreases exponentially fast, which the authors use to explain why overfitting sets in slowly.",
          "Section 5.1",
          "Thus, we see here explicitly that we have to stop early with the boosting iterations in order to prevent overﬁtting."),
         ("Limitation of the information-criterion stopping rule: the degrees of freedom df(m) = trace(B_m) used in the corrected AIC neglect the selection effect of the componentwise base procedure, because B_m depends on the response through the selected components.",
          "Section 5.3",
          "should be viewed as an approximate hat matrix only."),
     ],
     "notes": "Affiliations: ETH Zürich (Bühlmann) and LMU München (Hothorn; paper written while at Universität Erlangen-Nürnberg). Venue from the arXiv journal_ref and the PDF header (Statistical Science 2007, Vol. 22, No. 4, 477-505; DOI 10.1214/07-STS242; discussed paper with rejoinder). The arXiv record year (2008) is used as year. Disclosure: the illustrations use the mboost R package, whose authors are the same two authors (reference [43]: Hothorn, T. and Bühlmann, P. Mboost: Model-based boosting); the tree-based illustration compares mboost's blackboost with the gbm package only visually (Figure 4). The paper is a review; it also covers componentwise linear/spline base learners, variable selection, twin boosting and survival analysis, which are not recorded here."},

    {"id": "arxiv-1505.01866",
     "title": "DART: Dropouts meet Multiple Additive Regression Trees",
     "authors": ["K. V. Rashmi", "Ran Gilad-Bachrach"],
     "year": 2015, "venue": "AISTATS 2015", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1505.01866"},
     "tasks": ["tabular-regression", "image-classification"],
     "fam": ["gradient-boosted-trees", "random-forests"], "par": ["supervised"],
     "proposes": ["DART: MART (gradient boosted regression trees) with dropout of whole trees: the gradient for each new tree is computed against a random subset of the existing ensemble, and the new and dropped trees are rescaled (by 1/k and k/(k+1)) to avoid overshooting"],
     "claims": [
         ("Problem defined: MART suffers from what the authors call over-specialization, where trees added at later iterations affect the prediction of only a few instances and contribute negligibly for the rest; the authors say this hurts performance on unseen data and makes the model over-sensitive to the first few trees.",
          "Abstract",
          "However, it suﬀers an issue which we call over-specialization, wherein trees added at later iterations tend to impact the prediction of only a few instances, and make negligible contribution towards the remaining instances."),
         ("Shrinkage, the most common remedy, reduces the impact of the first trees, but according to the authors the problem reappears as the ensemble grows (illustrated on CTSlice in Figures 1-2; similar observations reported on the other datasets).",
          "Introduction",
          "As we will see in Section 2, shrinkage does help in reducing the impact of the ﬁrst trees, nevertheless, however, as the size of the ensemble increases, the problem of over-specialization reappears."),
         ("Proposed mechanism: in MART without shrinkage, adding a constant to all labels would only change the first tree, so in a sense the first tree learns the bias and the remaining trees learn deviations from it, making the ensemble very sensitive to the first tree's decisions.",
          "Overcoming the Over-specialization in MART",
          "Therefore, in a sense, the ﬁrst tree learns the bias of the problem while the rest of the trees in the ensemble learn the deviation from this bias."),
         ("Algorithm: DART differs from MART in two places: the gradient for the next tree is computed using only a random subset of the existing ensemble, and a normalization step scales the new tree by 1/k (k = number of dropped trees) and then the new and dropped trees by k/(k+1), because the new tree and the dropped trees would otherwise both close the same gap and overshoot.",
          "Description of the DART Algorithm",
          "First, when computing the gradient that the next tree will ﬁt, only a random subset of the existing ensemble is considered."),
         ("The number of dropped trees controls the amount of regularization: dropping none gives MART and dropping all gives (in the authors' description) random forest; the experiments use a 'Binomial-plus-one' rule (each tree dropped with probability p_drop, and one random tree if none was selected).",
          "Description of the DART Algorithm",
          "On the other extreme, if all the trees are dropped, the DART is no diﬀerent than random forest."),
         ("Ranking evaluation protocol (LambdaMART with dropout on MSLR-WEB10K, 60/20/20 train/validation/test): parameter grids were scanned for both algorithms by training on the training data and comparing NDCG@3 on validation, and the best validation models were applied to the test set.",
          "Evaluation: Ranking",
          "We selected the best performing models based on their scores on the validation set, and applied them to the test set to obtain the reported results."),
         ("Regression evaluation protocol (UCI CT slices, 53500 histograms from 74 individuals): 10-fold cross-validation with folds grouped by individual; Table 4 reports the L2 error of the optimal parameter combinations per ensemble size. A separate validation split for this task was not found in the text (searched for validation, nested, held-out).",
          "Evaluation: Regression",
          "The folds were selected such that either all the images of an individual are in the train set or all of them are in the test set."),
         ("Classification (Pascal Large Scale Learning Challenge face detection; first 300K examples train, next 200K validation, next 200K test; parameters selected on validation): the authors describe DART and MART as comparable, with MART winning at 3 of 5 ensemble sizes but the best model being a DART model; they report the best-model difference as statistically significant.",
          "Table 6",
          "The results are comparable between DART and MART: while MART “wins” on 3 out of the 5 diﬀerent ensembles sizes, however, the best model is a DART model."),
     ],
     "notes": "Affiliations: UC Berkeley (Rashmi) and Microsoft Research (Gilad-Bachrach); acknowledgments state the work was done while the first author was an intern at Microsoft Research. Venue from the PDF footnote ('Appearing in Proceedings of the 18th International Conference on Artificial Intelligence and Statistics (AISTATS) 2015') and the arXiv comment. Over-specialization evidence is shown as figures on one dataset (CTSlice). The ranking task (MSLR-WEB10K) has no matching task tag. No discussion of the computational cost of dropout (e.g. recomputing predictions of the reduced ensemble) was found in the text (searched for time, cost, slow, comput). Results tables not recorded."},

    {"id": "arxiv-1802.05640",
     "title": "Gradient Boosting With Piece-Wise Linear Regression Trees",
     "authors": ["Yu Shi", "Jian Li", "Zhize Li"],
     "year": 2018, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1802.05640", "code": "https://github.com/GBDT-PL/GBDT-PL.git"},
     "tasks": ["tabular-regression", "tabular-classification"],
     "fam": ["gradient-boosted-trees", "linear-models"], "par": ["supervised"],
     "proposes": ["GBDT-PL: second-order gradient boosting with piecewise linear regression trees (linear models in the leaves) as base learners, made scalable with incremental feature selection, half-additive fitting, histogram statistics for linear models and SIMD/cache-oriented implementation"],
     "claims": [
         ("Contribution: gradient boosting is extended to use piecewise linear regression trees (PL Trees) instead of piecewise constant trees as base learners; the authors state that PL Trees can accelerate convergence and improve accuracy, with optimizations reducing training time at little sacrifice of accuracy.",
          "Abstract",
          "Speciﬁcally, we extend gradient boosting to use piecewise linear regression trees (PL Trees), instead of piecewise constant regression trees, as base learners."),
         ("Regularization: the second-order (XGBoost-style) objective is used with an L2 penalty on the parameters of each leaf's linear model; leaf linear models are fitted analytically and split gain is the loss reduction when both children are refitted.",
          "Gradient Boosting with PL Trees",
          "This prevents the linear models in the leaves from being too steep."),
         ("Difference from M5/M5' model trees (used in Weka and Cubist), which fit linear models after the tree structure is fixed: the PL Tree chooses each split by the largest loss reduction considering the linear models in both children. Citing Sun et al., the authors also contrast their second-order gradients with the first-order algorithm of Wang and Hastie (2014).",
          "Related Work and Discussions",
          "By contrast, PL Tree used in our work is designed to greedily reduce the loss at each step of its growing."),
         ("Cost of the speedups: incremental feature selection (regressors limited to split features of ancestor nodes, up to a preset number) restricts the linear model size, and half-additive fitting gives suboptimal linear-model parameters; the authors report great speedup with a small sacrifice of accuracy (Table 1, one dataset setting).",
          "Effects of Optimization Techniques on Accuracy",
          "Incremental feature selection restricts the size of linear models, and half-additive ﬁtting results in suboptimal linear model parameters."),
         ("Evaluation protocol: 10 public datasets (6 regression with RMSE, 4 binary classification with AUC) against XGBoost, LightGBM and CatBoost over a grid of leaves, bins, min sum hessians, learning rate and L2 regularization, with number of trees set by learning rate x num trees = 50 (200 for CatBoost SymmetricTree) and the number of regressors fixed at 5; for the three baselines the best iteration over all settings on the test set is recorded, whereas GBDT-PL's setting is picked on a 20% validation split of the training data.",
          "Accuracy",
          "For XGBoost, LightGBM and CatBoost, result of the best iteration over all settings on test set is recorded."),
         ("The authors state that GBDT-PL achieves better accuracy on these dense numerical datasets, with a greater advantage on regression tasks.",
          "Accuracy",
          "With linear models on leaves, GBDT-PL achieves better accuracy in these dense numerical datasets."),
         ("Convergence (fixed setting: 256 leaves, 63 bins, 500 iterations, learning rate 0.1; shown only as figures): in most datasets GBDT-PL needs fewer trees to reach comparable accuracy.",
          "Convergence Rate",
          "In most datasets, GBDT-PL uses fewer trees to reach a comparable accuracy."),
         ("Limitation: GBDT-PL currently handles only numerical features; the authors suggest categorical features could first be converted to numerical ones as CatBoost does; GPU support is left for future work.",
          "Related Work and Discussions",
          "Currently GBDT-PL only handles numerical features."),
     ],
     "notes": "Affiliation: Institute for Interdisciplinary Information Sciences, Tsinghua University; acknowledgments list a grant from Microsoft Research Asia among others. No venue stated in the PDF (arXiv v3, 2019 revision) or in the arXiv comment. The baseline/proposed selection protocol is asymmetric (baselines: best on test; GBDT-PL: chosen on validation), as stated in the text. Results tables (Table 2) and the convergence/time figures not recorded."},

    {"id": "arxiv-1909.09223",
     "title": "InterpretML: A Unified Framework for Machine Learning Interpretability",
     "authors": ["Harsha Nori", "Samuel Jenkins", "Paul Koch", "Rich Caruana"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1909.09223", "code": "https://github.com/microsoft/interpret"},
     "tasks": ["model-explanation", "tabular-classification"],
     "fam": ["interpretable-models", "feature-attribution"], "par": ["supervised", "post-hoc"],
     "proposes": ["InterpretML: an open-source Python package with a unified API for glassbox models and blackbox explanation methods",
                  "Explainable Boosting Machine (EBM): a GAM (optionally with pairwise interactions, a fast implementation of GA2M) whose per-feature functions are learned by bagging and round-robin, low-learning-rate gradient boosting on one feature at a time"],
     "claims": [
         ("The package exposes two forms of interpretability: glassbox models designed for interpretability (e.g. linear models, rule lists, GAMs) and blackbox explanation techniques for existing systems (e.g. Partial Dependence, LIME), under a unified scikit-learn-style API with a visualization dashboard for comparing methods.",
          "Abstract",
          "InterpretML exposes two types of interpretability – glassbox, which are machine learning models designed for interpretability (ex: linear models, rule lists, generalized additive models), and blackbox explainability techniques for explaining existing systems (ex: Partial Dependence, LIME)."),
         ("EBM design: a GAM whose feature functions are learned with bagging and gradient boosting, with boosting restricted to one feature at a time in round-robin order and a very low learning rate so that feature order does not matter; round-robin cycling is said to mitigate the effects of co-linearity.",
          "Section 3",
          "The boosting procedure is carefully restricted to train on one feature at a time in round-robin fashion using a very low learning rate so that feature order does not matter."),
         ("EBM can automatically detect and include pairwise interaction terms; it is described as a fast, parallelizable C++/Python implementation of GA2M, citing Lou et al. (2013), with algorithmic details deferred to Lou et al. (2012, 2013) and Caruana et al. (2015).",
          "Section 3",
          "EBM is a fast implementation of the GA2M algorithm (Lou et al., 2013), written in C++ and Python."),
         ("Intelligibility argument: each feature's contribution can be visualized by plotting f_j, and because the model is additive each feature contributes modularly; individual predictions are sums of per-feature lookup-table contributions passed through the link function.",
          "Section 3",
          "Because EBM is an additive model, each feature contributes to predictions in a modular way that makes it easy to reason about the contribution of each feature to the prediction."),
         ("Accuracy claim (hedged): EBM often performs surprisingly well and is comparable with Random Forest and XGBoost; the evidence is an AUROC comparison on five classification datasets (heart-disease, breast-cancer, telecom-churn, adult-income, credit-fraud) shown in Figure 3, also including LightGBM and logistic regression.",
          "Section 3",
          "In terms of predictive power, EBM often performs surprisingly well, and is comparable with state of the art methods like Random Forest and XGBoost."),
         ("Evaluation protocol: all models were trained with their default parameters, and EBM's defaults are said to be chosen for computational speed; for best accuracy and interpretability the authors recommend reference parameters (100 inner bags, 100 outer bags, 5000 epochs, learning rate 0.01). No description of train/test splits or repetitions was found in the text (searched for split, fold, cross, test set, held).",
          "Section 3 (footnote 1)",
          "All models were trained with their default parameters."),
         ("Cost: to keep terms additive EBM pays an additional training cost and is somewhat slower to train than similar methods, but prediction (additions and lookups) is among the fastest; computational performance is shown in Figure 4.",
          "Section 3",
          "To keep the individual terms additive, EBM pays an additional training cost, making it somewhat slower than similar methods."),
         ("Disclosure: the package (from Microsoft) includes what the authors call the first implementation of EBM, i.e. the evaluated glassbox model is the authors' own, compared against third-party baselines.",
          "Abstract",
          "InterpretML also includes the ﬁrst implementation of the Explainable Boosting Machine, a powerful, interpretable, glassbox model that can be as accurate as many blackbox models."),
     ],
     "notes": "Affiliation: Microsoft Corporation (all four authors). Conflict of interest: the authors developed EBM/InterpretML, and Caruana is a co-author of the cited GA2M/intelligible-model papers (Lou et al. 2012, 2013; Caruana et al. 2015) on which EBM is based. The PDF header reads 'InterpretML - Draft'; no venue recorded. The text says EBM's feature functions are learned with gradient boosting but does not state the base learner type; the gradient-boosted-trees tag is therefore not applied (the method family is not stated); XGBoost and LightGBM appear only as comparison baselines. Results (Figure 3 AUROC, Figure 4 times) not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
