import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1810.00337",
     "title": "Learning to Perform Local Rewriting for Combinatorial Optimization",
     "authors": ["Xinyun Chen", "Yuandong Tian"],
     "year": 2018, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1810.00337", "code": "https://github.com/facebookresearch/neural-rewriter"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["local-search", "deep-learning"], "par": ["reinforcement-learning"],
     "proposes": ["NeuRewriter: an improvement policy that starts from a feasible solution and repeatedly picks a region (region-picking policy) and a rewriting rule (rule-picking policy) to rewrite it locally, trained with Q-Actor-Critic RL; applied to Halide expression simplification, online job scheduling and capacitated VRP"],
     "claims": [
         ("Contribution: NeuRewriter learns a policy that picks heuristics and rewrites local components of the current solution, iteratively improving it until convergence (instead of constructing a solution from scratch).",
          "Abstract",
          "In this paper, we propose NeuRewriter that learns a policy to pick heuristics and rewrite the local components of the current solution to iteratively improve it until convergence."),
         ("Training: the policy factorizes into a region-picking and a rule-picking component, each a neural network trained with actor-critic reinforcement learning (reward = cost reduction per rewriting step).",
          "Abstract",
          "The policy factorizes into a region-picking and a rule-picking component, each parameterized by a neural network trained with actor-critic methods in reinforcement learning."),
         ("Relation to local search: the authors describe the framework as closely connected to the local search pipeline, with the learned RL policy guiding the local search by deciding which neighbour solution to move to.",
          "Related Work",
          "Speciﬁcally, we can leverage our learned RL policy to guide the local search, i.e., to decide which neighbor solution to move to."),
         ("Protocol (time budgets and hardware): all algorithms run on the same server; neural networks use 1 GPU while search algorithms use 4 CPU cores, and search algorithms get a 10-second timeout per instance; no wall-clock limit is stated for the neural networks, so hardware (GPU vs CPU) and budgets are not matched.",
          "Experiments",
          "We set the timeout of search algorithms to be 10 seconds per instance."),
         ("Runtime caveat stated by the authors: OR-Tools' VRP solver is highly tuned and implemented in C++, while the RL approaches are in Python and their runtimes are measured decoding one instance at a time; the authors note potential room for speed-up by batching.",
          "Vehicle Routing Problem",
          "Note that the OR-Tools solver for vehicle routing problems is highly tuned and implemented in C++, while the RL-based approaches in comparison are implemented in Python."),
         ("Job-scheduling baseline setting: OR-Tools (offline setting) gets a 10-second timeout per workload; the authors state it cannot reach good performance even with a larger timeout (Appendix E attributes this to schedules that prioritize long jobs).",
          "Job Scheduling Problem",
          "For OR-tools, we set the timeout to be 10 seconds per workload, but we ﬁnd that it can not achieve a good performance even with a larger timeout, and we defer the discussion to Appendix E."),
         ("Limitation: because the approach rewrites locally it can become time-consuming when large changes are needed per iteration; in extreme cases where each step must change the global structure, starting from scratch becomes preferable.",
          "Conclusion",
          "In extreme cases where each rewriting step needs to change the global structure, starting from scratch becomes preferrable."),
     ],
     "notes": "PDF states: NeurIPS 2019. Affiliations: UC Berkeley and Facebook AI Research (first author's work partially done while interning at FAIR). No TSP experiments; routing experiments are CVRP with 20/50/100 customers (VRP20 Cap30, VRP50 Cap40, VRP100 Cap50), uniformly random in the unit square, following the setups of Nazari et al. and Kool et al. (AM). Baselines for VRP: AM, Nazari et al., OR-Tools, Clarke-Wright and sweep heuristics; Gurobi optimal is reported only for VRP20 (Table 6). Initial VRP routes are built by a nearest-feasible-node heuristic that the authors note is worse than the classic heuristics (Appendix F). Generalization: models trained on one VRP size are tested on other sizes (Figure 5b); expression models trained on short expressions are tested on longer ones (Test>100). No LKH or Concorde baseline. Rewriting steps: T_iter = 50 (expression, scheduling) and 200 (VRP) (Appendix D, hyper-parameters of Algorithm 2); at evaluation, inference also terminates early when the predicted Q falls below epsilon or the chosen rule does not apply (Appendix D). VRP rule set: each node can swap with another node in the route (problem setup section). Appendix F compares the VRP50-trained model's VRP100 result with a number reported in Nazari et al. (not rerun). Table 1c gives per-instance OR-Tools VRP runtimes well below the 10-second timeout. No optimality or approximation guarantee is claimed; the method is a heuristic. Results not recorded."},

    {"id": "arxiv-2004.01608",
     "title": "Learning 2-opt Heuristics for the Traveling Salesman Problem via Deep Reinforcement Learning",
     "authors": ["Paulo R. de O. da Costa", "Jason Rhuggenaath", "Yingqian Zhang", "Alp Akcay"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2004.01608", "code": "https://github.com/paulorocosta/learning-2opt-drl"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["local-search", "graph-neural-networks", "deep-learning"], "par": ["reinforcement-learning"],
     "proposes": ["A policy-gradient (actor-critic style) RL method that learns a stochastic 2-opt improvement policy for Euclidean TSP: GCN + bidirectional LSTM encoders of the current and best-so-far tours, and a pointer-attention decoder that outputs the two node positions of a 2-opt move"],
     "claims": [
         ("Contribution: the paper learns a local search (improvement) heuristic based on 2-opt operators via deep RL, in contrast to most learned TSP methods, which learn construction heuristics.",
          "Abstract",
          "In this work, we propose to learn a local search heuristic based on 2-opt operators via deep reinforcement learning."),
         ("How the move is learned: a policy gradient algorithm learns a stochastic policy selecting the 2-opt operation (a pair of node positions) given the current solution; the reward is the improvement of the best-found tour.",
          "Abstract",
          "We propose a policy gradient algorithm to learn a stochastic policy that selects 2-opt operations given a current solution."),
         ("Comparison with classical 2-opt: learned policies and 2-opt first-improvement / best-improvement heuristics (with and without random restarts) are run on 512 TSP100 instances from the same starting solutions with an equal step budget of 1,000 steps (steps, not wall-clock time, are matched).",
          "Experimental Results and Analysis",
          "We run all heuristics and learned policies on 512 TSP100 instances for a maximum of 1,000 steps starting from the same solutions."),
         ("Protocol: training instances are uniform random in the unit square (TSP20/50/100); test uses the 10,000-instance sets of Kool et al. and Joshi et al., with Concorde optima rerun to compute optimality gaps.",
          "Experiments and Results",
          "we use the same test dataset as reported in Kool et al. (2019); Joshi et al. (2019) containing 10,000 instances for each TSP size."),
         ("Evaluation practice: results for Wu et al. (2019) are copied from the original paper (no implementation was available) and are on a different test set generated by the same process; most baseline running times are also taken from earlier papers, and only Kool et al.'s method is rerun on the authors' hardware.",
          "Experiments and Results",
          "Since at the time of submission no implementation is available, we report the optimality gaps reported in the original paper."),
         ("Generalization to TSPLIB: the TSP100-trained policy never sees instances over 100 nodes; on the extended set of 35 TSPLIB instances (supplement) with 2,000 sampling steps its average optimality gap is larger than OR-Tools' (in the main text, on 10 instances, it beats OR-Tools on 5).",
          "Generalization to Real-world TSP instances",
          "On the 35 instances the gaps are 8.61% (ours) and 3.70% (OR-Tools)."),
         ("Limitation: the policy gradient method needs a large number of samples to train a good policy.",
          "Conclusions and Future Work",
          "One drawback of our policy gradient method is the large number of samples required to train a good policy."),
     ],
     "notes": "PDF states: Proceedings of ACML 2020 (Proceedings of Machine Learning Research). Affiliation: Eindhoven University of Technology. Train vs test sizes: separate policies trained on TSP20, TSP50 and TSP100; a TSP50-trained policy is also tested on TSP100 (Table 2); TSPLIB instances up to pr439 (supplement Table 6). Baselines: Concorde (optimal reference), OR-Tools (described as containing 2-opt and LKH as improvement heuristics, citing Bello and Pham), insertion heuristics, and learned construction/improvement methods. OR-Tools time limit or settings: not found in the text (searched 'time limit', 'timeout', 'default', 'tuned'). LKH itself is not run as a separate baseline. Hardware: training on one RTX 2080Ti GPU. Running-time comparison is restricted to learning methods 'as classical heuristics and solvers are efficiently implemented using multi-threaded CPUs'; Table 1 times are mostly copied from Kool et al., Joshi et al. and Wu et al. (OR-Tools row has no time); the speed comparison with GAT-T (Wu et al.) is across GPUs (RTX 2080Ti vs Tesla V100, copied times); only GAT (Kool et al.) is rerun on the same hardware with the same number of samples (Table 4). The authors note they cannot compete in speed with greedy construction methods because they start from poor (random) solutions and need sampling (Running Times and Sample Efficiency). Hyperparameters chosen on a fixed validation set with optimal solutions. No optimality guarantee is claimed. Results tables not recorded (the TSPLIB quote above is a sentence from a footnote)."},

    {"id": "arxiv-2107.10201",
     "title": "Learning a Large Neighborhood Search Algorithm for Mixed Integer Programs",
     "authors": ["Nicolas Sonnerat", "Pengming Wang", "Ira Ktena", "Sergey Bartunov", "Vinod Nair"],
     "year": 2021, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2107.10201", "code": "https://github.com/deepmind/neural_lns"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["local-search", "graph-neural-networks"], "par": ["supervised"],
     "proposes": ["Learned LNS for MIPs: Neural Diving for the initial assignment plus a Neural Neighborhood Selection (NNS) GCN policy that chooses which integer variables to unassign at each LNS step, trained by imitation of a local-branching expert; the resulting sub-MIP is solved with SCIP"],
     "claims": [
         ("Contribution and relation to local search: a learned LNS for MIPs where a Neural Neighborhood Selection policy chooses the search neighbourhood (variables to unassign) at each step, and the neighbourhood itself is searched with a MIP solver (SCIP 7.0.1).",
          "Abstract",
          "Formulating the subsequent search steps as a Markov Decision Process, we train a Neural Neighborhood Selection policy to select a search neighborhood at each step, which is searched using a MIP solver to ﬁnd the next assignment."),
         ("Training (imitation, not RL): the imitation target is an expert that, under certain assumptions, is guaranteed to pick the neighbourhood containing the optimal next assignment (local branching within a Hamming ball); the expert is too slow for use at test time and is only used offline to generate data.",
          "Introduction",
          "We propose an imitation learning approach to train the neighborhood selection policy using as the imitation target an expert policy that, under certain assumptions, is guaranteed to select the neighborhood containing the optimal next assignment at a given LNS step."),
         ("Guarantees given up: the method is a primal heuristic (it seeks a good feasible assignment, not a proof of optimality or a lower bound), motivated by production applications.",
          "Background",
          "This work focuses on primal heuristics as production applications often only require ﬁnding a good feasible assignment quickly."),
         ("Baseline tuning: SCIP's metaparameters (presolve, cuts, heuristics) are tuned per dataset by grid search to give the best validation average primal gap curves, to make it behave more like a primal heuristic; other baselines are random neighbourhood selection (with Neural Diving start) and Neural Diving alone. Gurobi is not used.",
          "Baselines",
          "for each dataset separately using grid search to achieve the best validation set average primal gap curves."),
         ("Compute is not matched across all methods: the learned heuristics and random-LNS baselines get the same parallel resources, but SCIP is run single-core only.",
          "Baselines",
          "SCIP is evaluated only in the single core setting, as the main focus of this work is to evaluate the beneﬁt of easily parallelizable primal heuristics."),
         ("Datasets and affiliation: five datasets (Neural Network Verification, Electric Grid Optimization, Production Packing, Production Planning, MIPLIB), each split 70/15/15 with a separate model per dataset; two come from the production systems of a large technology company, which the text does not name (author affiliations: DeepMind, Charm Therapeutics, Google Research).",
          "Datasets",
          "In particular, Production Packing and Planning datasets are obtained from a large technology company’s production systems."),
         ("Limitations: models are not trained end-to-end on the final metric (average primal gap), and the conditionally independent policy does not approximate the expert perfectly; the authors suggest RL/offline RL and autoregressive models as possible remedies.",
          "Discussion",
          "Our approach does not currently train models in an end-to-end fashion to directly optimize a ﬁnal performance metric such as the average primal gap."),
     ],
     "notes": "PDF states: affiliations DeepMind (London), Charm Therapeutics, Google Research (Bangalore); work done at DeepMind. Metrics: average primal gap vs a precomputed best-known objective and survival curves with dataset-specific gap thresholds, both against 'calibrated time' (a time measure on a shared heterogeneous cluster normalized by repeatedly solving MIPLIB2003 vpm2; reference machine Intel Xeon 3.50GHz). Expert guarantee conditions (Section 3.2): the expert finds the best assignment within a Hamming ball of radius eta_t around the current assignment (a neighbourhood of a specified number of unassigned integer variables), and the policy reaches that assignment only if the sub-MIP is solved optimally. Parallel setting: the number of parallel workers and the test-time inference hardware were not found in the text (searched 'cores', 'workers', 'CPU', 'GPU'); training used one V100 GPU per dataset (Appendix A.2). Expert data: 10 local-branching steps per training instance using SCIP with default parameters and a 3-hour time limit per step (Appendix A.1). Training/test from the same dataset distribution (no cross-size generalization test). Evaluation: 50 LNS steps, sub-MIP time limit per step 60-300 s tuned on validation (Appendix A.3). Appendix A.7 (preliminary, limited tuning) on NeurIPS'21 ML4CO datasets: NNS gives no benefit over random neighbourhood selection on Anonymous, and NNS and RNS both fail to improve over Neural Diving on Load Balancing ('However, NNS and RNS both fail to provide any improvements over ND.'). The sub-MIP solve is optimal within its neighbourhood only if SCIP finishes; no global optimality certificate. Tag 'supervised' used for imitation learning. Results not recorded."},

    {"id": "arxiv-2005.02960",
     "title": "Exploring the Loss Landscape in Neural Architecture Search",
     "authors": ["Colin White", "Sam Nolen", "Yash Savani"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2005.02960", "code": "https://github.com/naszilla/naszilla"},
     "tasks": ["neural-architecture-search"],
     "fam": ["local-search"],
     "proposes": ["Using simple local search (hill-climbing over architectures differing by one operation or edge) as a NAS baseline, an analysis of how evaluation noise changes the number of local minima on NAS benchmarks, and a probabilistic theoretical characterization of local search performance"],
     "claims": [
         ("Main claim: the simplest hill-climbing algorithm is a powerful NAS baseline, and when noise in popular NAS benchmark datasets is reduced to a minimum, hill-climbing outperforms many popular state-of-the-art algorithms.",
          "Abstract",
          "In this work, we show that (1) the simplest hill-climbing algorithm is a powerful baseline for NAS, and (2), when the noise in popular NAS benchmark datasets is reduced to a minimum, hill-climbing to outperforms many popular state-of-the-art algorithms."),
         ("Protocol: NASBench-101, NASBench-201 (CIFAR-10, CIFAR-100, ImageNet16-120) and NASBench-301 (DARTS space); local search is compared with random search, regularized evolution, Bayesian optimization and BANANAS, each with a budget of 300 evaluations and 200 trials; 'denoising' is done artificially by averaging the three seeds (101/201) or the surrogate ensemble (301).",
          "Experiments",
          "However, for each architecture, we can average all three validation accuracies to obtain a less noisy estimate."),
         ("Result depends on noise: on NASBench-101 and 301 local search beats all other algorithms when noise is minimal but performs similarly to Bayesian optimization in the standard (noisy) setting.",
          "Experiments",
          "On both NASBench-101 and 301, local search outperforms all other algorithms when the noise is minimal, amd performs similarly to Bayesian optimization in the standard setting."),
         ("Exception: on NASBench-201 ImageNet16-120, the initial noise is so high that all NAS algorithms perform worse in the reduced-noise version.",
          "Appendix A",
          "Note that for the case of ImageNet16-120, the initial level of noise is so high that all NAS algorithms actually perform worse in the reduced noise version of the problem."),
         ("Theory and its assumptions: validation losses are modelled as drawn from a global distribution, with neighbours' losses drawn from a local distribution conditioned on the current loss; with fixed neighbourhood size s and a vertex-transitive neighbourhood graph, Theorem 5.1 gives the expected number of local minima and of starting points converging within epsilon of the global optimum (the authors say this makes local search similar to a Markov process and that their experiments in Figure 4.2 suggest this is a reasonable assumption in practice).",
          "Theoretical Characterization",
          "Therefore, we assume that the validation loss for a trained architecture is sampled from a global probability distribution, and for each architecture, the validation losses of its neighbors are sampled from a local probability distribution.", 6),
         ("Limits of the theory: estimating the required distributions is not feasible for large search spaces; the theory is meant only to give understanding; in the simulation, it exactly predicts the uniform-random NASBench-201 variant, and on the three NASBench-201 image datasets predicts performance fairly accurately but not perfectly, which the authors attribute to their assumption that the accuracy distribution is unimodal.",
          "Theoretical Characterization",
          "We note that approximating these distributions are not feasible for large search spaces; the purpose of our theoretical results are meant only to provide a deeper understanding of local search and lay the groundwork for future studies."),
         ("Affiliation: the work was done while all authors were employed at Abacus.AI.",
          "Acknowledgments",
          "This work done while all authors were employed at Abacus.AI."),
     ],
     "notes": "PDF states: UAI 2021. Baselines run from their open-source code; regularized evolution population size changed from 50 to 30, other baselines' hyperparameters unchanged; local search has two boolean hyperparameters and was not tuned (Appendix A). Local search variant differs by benchmark: query_until_lower on NASBench-101/301, continue_at_min on NASBench-201. Possible conflict of interest not stated as such in the text: the baseline BANANAS is by the same first and third authors (White, Neiswanger, Savani, AAAI 2021, per the reference list). Critiques/independent confirmation: the paper says a prior work (Wang et al., 2018) suggested local search performs poorly due to many local minima and killed runs at a local minimum instead of restarting; concurrent work (Ottelander et al., 2020) independently found local search a strong baseline on NASBench-101 for multi-objective NAS. Lemma 5.3 gives a closed form under uniform local/global distributions; the authors state that Theorem 5.1 and Lemma 5.2 hold without any assumptions on the local and global distributions (the fixed neighbourhood size, vertex-transitivity and neighbour-loss model still apply); Lemma B.3 additionally assumes n large relative to s. Corollary B.1 (Appendix B): with Gaussian noise on each architecture's accuracy, the expected number of local minima is bounded in terms of the noise standard deviation. Budgets: all algorithms get 300 queries on tabular/surrogate benchmarks (matched by number of evaluations). Results are figures only; not recorded."},

    {"id": "arxiv-1704.01665",
     "title": "Learning Combinatorial Optimization Algorithms over Graphs",
     "authors": ["Hanjun Dai", "Elias B. Khalil", "Yuyu Zhang", "Bistra Dilkina", "Le Song"],
     "year": 2017, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1704.01665", "code": "https://github.com/Hanjun-Dai/graph_comb_opt"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["greedy-methods", "graph-neural-networks"], "par": ["reinforcement-learning"],
     "proposes": ["S2V-DQN: a greedy construction meta-algorithm whose node-evaluation function Q is a structure2vec graph embedding network trained with n-step fitted Q-learning; applied to Minimum Vertex Cover, Max Cut, TSP (and Set Cover in the appendix)"],
     "claims": [
         ("Relation to greedy algorithms: the learned algorithm keeps the classical greedy pattern (build a feasible solution by successively adding nodes, maintained to satisfy the problem's constraints); only the node-evaluation function is learned instead of hand-crafted.",
          "Introduction",
          "We will adopt a greedy meta-algorithm design, whereby a feasible solution is constructed by successive addition of nodes based on the graph structure, and is maintained so as to satisfy the problem’s graph constraints."),
         ("Training: the greedy policy is learned with fitted Q-learning (n-step Q-learning with experience replay), parametrized by the structure2vec graph embedding network, optimizing the original objective directly.",
          "Introduction",
          "We will use ﬁtted Q-learning to learn a greedy policy that is parametrized by the graph embedding network."),
         ("Framing on guarantees: the authors describe heuristics as fast and effective but lacking theoretical guarantees; no approximation guarantee for the learned heuristic is stated in the text (the MVC baselines are 2-approximations).",
          "Introduction",
          "Heuristics are often fast, effective algorithms that lack theoretical guarantees, and may also require substantial problem-speciﬁc research and trial-and-error on the part of algorithm designers."),
         ("Protocol: instances are synthetic (Erdos-Renyi and Barabasi-Albert graphs for MVC/MaxCut; DIMACS-generator uniform or clustered points for TSP); 100 validation and 1000 test graphs; approximation ratios are relative to the best solution found by CPLEX (MVC, MaxCut) or Concorde (TSP) within 1 hour, which may not be optimal.",
          "Experimental Evaluation",
          "All approximation ratios reported in the paper are with respect to the best (possibly optimal) solution found by the solvers within 1 hour."),
         ("Train vs test sizes: to test size generalization, S2V-DQN is trained on graphs with 50-100 nodes and tested on graphs of up to 1200 nodes.",
          "Generalization to larger instances",
          "To investigate this, we train S2V-DQN on graphs with 50–100 nodes, and test its generalization ability on graphs with up to 1200 nodes."),
         ("TSP caveat: on synthetic random TSP the hand-designed Farthest insertion and 2-opt perform as well as S2V-DQN and slightly better in some cases (the authors add that S2V-DQN still performs better on real-world TSP data; that TSPLIB comparison uses per-instance Active Search rather than the greedy policy used on synthetic test sets, see c7).",
          "Comparison of solution quality",
          "For TSP, The Farthest and 2-opt algorithm perform as well as S2V-DQN, and slightly better in some cases."),
         ("TSPLIB protocol differs from the synthetic one: on 38 TSPLIB instances (51-318 cities) S2V-DQN is run in 'Active Search' mode, i.e. RL is applied on the fly to each instance without upfront training, keeping the best tour found; larger instances were not attempted due to single-GPU memory.",
          "Appendix C.3",
          "We apply S2V-DQN in “Active Search\" mode, similarly to [6]: no upfront training phase is required, and the reinforcement learning algorithm 1 is applied on-the-ﬂy on each instance."),
     ],
     "notes": "PDF states: NIPS 2017. Affiliations: Georgia Institute of Technology; Le Song also Ant Financial. Training sizes: MVC trained up to 400-500 nodes (with 'pre-training' on smaller graphs); MaxCut and TSP trained up to 200-300 nodes 'due to the limited computation resource'; tests up to 1000-1200 nodes. Baselines: PN-AC (pointer network actor-critic, reimplemented; for graph problems nodes are described by rank-8 SVD of the adjacency matrix), MVCApprox / MVCApprox-Greedy, MaxcutApprox, SDP (Goemans-Williamson, best of 100), TSP heuristics (MST, Farthest/Cheapest/Closest insertion, Christofides, 2-opt, Nearest Neighbor); CPLEX 12.6.1 and Concorde with 1-hour cutoffs as references. At test time the greedy policy is used (no Active Search) on synthetic data. Running-time comparison: S2V-DQN runs on GPU; the authors note the comparison with MaxcutApprox is 'not exactly fair, since we use GPUs'. Hyperparameters selected via preliminary results on small graphs, then fixed. Real-world sets: MemeTracker (MVC, SCP), Physics (MaxCut), TSPLIB. LKH and Gurobi are not used. Reference solutions: CPLEX/Concorde 1-hour best solutions are reported as 'optimal' when optimality is not proven (Appendix D.1); the authors note the 'optimal' value may not be truly optimal, CPLEX's solutions typically get worse as size grows, and S2V-DQN sometimes beats 1-hour CPLEX, giving ratios below 1.0. TSPLIB ratios are against the known optima listed in Table C.2. The number of Active Search episodes or running time on TSPLIB was not found in Appendix C.3, so per-instance compute is not matched with the one-shot TSP heuristics. Hyperparameters tuned on graphs with fewer than 50 nodes (Appendix D.4). Family tag local-search not used: the method is greedy construction (MaxcutApprox baseline is a local-search heuristic). Results not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): algorithm design techniques (divide and conquer, dynamic programming, branch and bound, local search) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
