import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-2009.06732",
     "title": "Efficient Transformers: A Survey",
     "authors": ["Yi Tay", "Mostafa Dehghani", "Dara Bahri", "Donald Metzler"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2009.06732"},
     "tasks": ["efficiency-evaluation"], "fam": ["efficient-attention", "mixture-of-experts", "deep-learning"], "par": [],
     "proposes": ["taxonomy of efficient Transformer (\"X-former\") models by core technique and primary use case"],
     "claims": [
         ("Scope: the survey characterizes a selection of efficiency-oriented \"X-former\" Transformer variants (e.g. Reformer, Linformer, Performer, Longformer), many of which target computational and memory efficiency, across multiple domains.",
          "Abstract",
          "With the aim of helping the avid researcher navigate this ﬂurry, this paper characterizes a large and thoughtful selection of recent eﬃciency-ﬂavored “X-former” models, providing an organized and comprehensive overview of existing work and models across multiple domains."),
         ("Contribution: the paper proposes a taxonomy of efficient Transformer models organized by technical innovation and primary use case.",
          "Introduction",
          "We propose a taxonomy of eﬃcient Transformer models, characterizing them by their technical innovation and primary use case."),
         ("Definition of efficiency used: the survey says efficiency can mean memory footprint (relevant when accelerator memory is limited) or computational cost such as FLOPs in training and inference, and it uses both senses, with particular interest in large inputs.",
          "Introduction",
          "Throughout this survey, we refer to the eﬃciency of Transformers both in terms of memory and computation."),
         ("Cost composition: the survey notes that self-attention is only part of a Transformer's compute; the survey states that the two-layer feed-forward layers account for approximately half the compute time and/or FLOPs and notes that much recent work (citing Lepikhin et al., 2020; Fedus et al., 2021) has explored sparsity to scale up the FFN without incurring compute costs; it calls efficiency and computational cost a complicated affair and refers readers to Dehghani et al. (2021).",
          "Background on Transformers",
          "A non-trivial amount of compute still stems from the two layer feed-forward layers at every Transformer block (approximately half the compute time and/or FLOPs)."),
         ("Evaluation caveat: there is no easy way to compare efficient Transformers side by side; papers choose their own benchmarks and differ in model sizes and configurations (and some conflate with pretraining), making it difficult to attribute performance gains.",
          "Discussion (On Evaluation)",
          "This is also coupled with diﬀerent hyperparameter set-tings like model sizes and conﬁgurations which can make it diﬃcult to correctly attribute the reason for the performance gains."),
         ("Benchmark caveat: the survey notes that Long Range Arena (an attempt to unify evaluation that benchmarked 10 xformer variants) was designed for encoder-only mode and does not cover autoregressive tasks that need causal masking.",
          "Discussion (On Evaluation)",
          "It is good to note that LRA was designed for evalu-ating Transformers in encoder-only mode and do not consider generative (or autoregressive tasks) that require causal masking."),
         ("'Efficiency misnomer' caveat: in the retrospective of the updated version (Section 4.4), the authors state that efficient attention models do not always make the Transformer fast; many may make the model much slower, many linear attention models observe no speed or memory gain at all when the sequence length is short, and many have painful requirements for causal masking (or TPU packing) (citing Choromanski et al., 2020b; Peng et al., 2021; Wang et al., 2020c), often substantially trading off throughput for linear complexity. They refer to Dehghani et al. (2021) for more on this efficiency misnomer.",
          "Retrospective (Discussion)",
          "Moreover, many linear attention models do not observe any speed or memory gain at all if the sequence length is short."),
     ],
     "notes": "Survey; no experiments of its own. Taxonomy categories (Section 3.1 bullets): Fixed Patterns, Combination of Patterns, Learnable Patterns, Neural Memory, Low-Rank Methods, Kernels, Recurrence, Downsampling, Sparse Models and Conditional Computation; orthogonal directions listed separately (weight sharing, quantization/mixed precision, pruning, distillation, NAS, task adapters, alternative architectures). The retrospective also says (citing other work) that linear attention models struggle to be competitive on common benchmarks and that local attention can be a tough baseline; it refers readers to Dehghani et al. (2021) for the efficiency misnomer. Affiliation: all four authors list Google Research on the title page. PDF header states 'Preprint, Version 2, Updated Mar 2022'."},

    {"id": "arxiv-2205.14135",
     "title": "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
     "authors": ["Tri Dao", "Daniel Y. Fu", "Stefano Ermon", "Atri Rudra", "Christopher Ré"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2205.14135",
               "code": "https://github.com/HazyResearch/flash-attention"},
     "tasks": ["efficiency-evaluation", "language-modeling"], "fam": ["efficient-attention", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["FlashAttention (IO-aware exact attention using tiling and recomputation in a fused CUDA kernel)",
                  "block-sparse FlashAttention (approximate attention)"],
     "claims": [
         ("Method: FlashAttention is an IO-aware exact attention algorithm that uses tiling to reduce reads/writes between GPU HBM and on-chip SRAM; the paper analyzes its IO complexity and claims fewer HBM accesses than standard attention and optimality for a range of SRAM sizes.",
          "Abstract",
          "We propose FlashAttention, an IO-aware exact attention algorithm that uses tiling to reduce the number of memory reads/writes between GPU high bandwidth memory (HBM) and GPU on-chip SRAM."),
         ("Critique of FLOP-based efficiency: the authors argue that many approximate attention methods reduce compute to linear or near-linear in sequence length but do not show wall-clock speedups, mainly because they focus on FLOP reduction, which may not correlate with wall-clock speed, and ignore memory-access overheads.",
          "Introduction",
          "One main reason is that they focus on FLOP reduction (which may not correlate with wall-clock speed) and tend to ignore overheads from memory access (IO)."),
         ("Complexity/memory claim: despite more FLOPs from recomputation in the backward pass, FlashAttention runs faster than standard attention and uses memory linear in sequence length, attributed to much less HBM access (the paper proves O(N^2 d^2 / M) HBM accesses vs Omega(Nd + N^2) for standard attention, and says that for typical d and M this means many times fewer accesses). The 'up to 7.6x' in the quote is, per the Figure 1 caption, the speedup on the attention computation over the PyTorch attention implementation on GPT-2, not an end-to-end training speedup.",
          "Introduction",
          "Even with the increased FLOPs due to recomputation, our algorithm both runs faster (up to 7.6x on GPT-2 [67], Figure 1 right) and uses less memory—linear in sequence length—than standard attention, thanks to the massively reduced amount of HBM access."),
         ("Quality at matched model: in GPT-2 small and medium training on OpenWebText, FlashAttention reaches the same perplexity as the HuggingFace and Megatron-LM implementations because the model definition is unchanged (the reported speedups, up to 3x vs HuggingFace and up to 1.7x vs Megatron-LM, are end-to-end training time; Table 2 reports training time on 8xA100 GPUs).",
          "Experiments (GPT-2)",
          "achieves the same perplexity as the other two implementations, as we do not change the model deﬁnition."),
         ("Benchmark protocol: attention runtime and memory are measured while varying sequence length on one A100 GPU with 40 GB HBM, with dropout and a padding mask, against reference implementations of exact, approximate and sparse attention; the paper reports that FlashAttention is faster than approximate and sparse attention for short sequences and that approximate attention runtimes begin to cross over with FlashAttention at sequence lengths between 512 and 1024 (in this single-GPU benchmark).",
          "Benchmarking Attention",
          "We vary sequence length and measure runtime and memory usage of FlashAttention and block-sparse FlashAttention against various attention baselines on one A100 GPU with 40 GB HBM, with dropout and a padding mask."),
         ("Hardware dependence: the appendix states that speedup differs across GPU types and generations depending on HBM bandwidth and SRAM size, and profiles A100, RTX 3090 and T4 (less speedup on T4 with its smaller SRAM).",
          "Appendix (Speedup on different hardware)",
          "Speedup varies between diﬀerent types of GPU types and generations depending on HBM bandwidth and SRAM size."),
         ("Limitations: each new attention variant needs a new hand-written CUDA kernel, requiring significant engineering effort, implementations may not transfer across GPU architectures, and the IO analysis/optimality covers a single GPU (multi-GPU left to future work).",
          "Limitations and Future Directions",
          "Implementations may also not be transferrable across GPU architectures."),
     ],
     "notes": "Affiliations: Stanford University and University at Buffalo, SUNY. Acknowledgments list funding including cloud-credit programs and members of the Stanford DAWN project (e.g. Facebook, Google). End-to-end speedups reported in the abstract: BERT-large vs MLPerf 1.1 record (seq. 512), GPT-2 (seq. 1K), LRA (seq. 1K-4K); BERT timing is to a target MLM accuracy averaged over 10 runs on 8xA100 (appendix: 8xA100-80GB). The Experiments overview says 1.8x over Megatron for GPT-2 while Table 2 and its text say 1.7x. Results tables not recorded."},

    {"id": "arxiv-2101.03961",
     "title": "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity",
     "authors": ["William Fedus", "Barret Zoph", "Noam Shazeer"],
     "year": 2021, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2101.03961",
               "code": "https://github.com/google-research/t5x"},
     "tasks": ["scaling-laws", "efficiency-evaluation", "language-modeling"],
     "fam": ["mixture-of-experts", "large-language-models", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["Switch Transformer (top-1 expert routing MoE replacing the FFN layer)",
                  "training techniques for sparse models (selective bfloat16 precision, reduced initialization scale)"],
     "claims": [
         ("Motivation/method: MoE models select different parameters per example, giving a sparsely-activated model with very many parameters but constant computational cost; Switch Transformer simplifies MoE routing to reduce complexity, communication cost and instability.",
          "Abstract",
          "The result is a sparsely-activated model—with an outrageous number of parameters—but a constant computational cost."),
         ("Main claim: models built from T5-Base and T5-Large obtain up to 7x increases in pre-training speed with the same computational resources; pre-training up to trillion-parameter models on C4 achieves a 4x speedup over T5-XXL (the Table 9 caption specifies the 1.6T Switch-C as 4x faster to a fixed perplexity with the same compute budget; footnote 10 says the T5-XXL quality gap is a lower bound because T5-XXL was pretrained on an easier C4 version). The contributions list phrases the 7x+ speedup as using the same FLOPS per token.",
          "Abstract",
          "We design models based oﬀT5-Base and T5-Large (Raﬀel et al., 2019) to obtain up to 7x increases in pre-training speed with the same computational resources."),
         ("Scaling regime: following Kaplan et al., the scaling study considers a regime not bottlenecked by compute or data, using C4 with over 180B target tokens and training until diminishing returns.",
          "Scaling Properties",
          "To avoid the data bottleneck, we use the large C4 corpus with over 180B target tokens (Raﬀel et al., 2019) and we train until diminishing returns are observed."),
         ("Step-basis vs wall-clock: since Switch models have roughly the same FLOPs per token as the baseline but add cross-device communication and routing computation, the authors caution that higher sample efficiency per step does not necessarily translate to better quality per wall-clock time, and therefore also compare on a time basis.",
          "Scaling Results on a Time-Basis",
          "Therefore, the increased sample eﬃciency observed on a step-basis doesn’t necessarily translate to a better model quality as measured by wall-clock."),
         ("Time-basis protocol: in the time comparison all models are trained on 32 TPUv3 cores with equal FLOPs per example, and, for a fixed amount of computation and training time, the 64-expert Switch-Base reaches the same quality as T5-Base in one-seventh of the time.",
          "Scaling Results on a Time-Basis (Figure 5)",
          "All models trained on 32 TPUv3 cores with equal FLOPs per example."),
         ("Versus a larger dense model: Switch-Base (64 experts) is compared to T5-Large, which applies 3.5x more FLOPs per token, and on a wall-clock basis Switch-Base is still faster (2.5x speedup).",
          "Scaling Versus a Larger Dense Model (Figure 6)",
          "Right Plot: As before, on a wall-clock basis, we ﬁnd that Switch-Base is still faster, and yields a 2.5x speedup over T5-Large."),
         ("Limitation: despite similar C4 perplexities, the 1.6T-parameter Switch-C scores lower on SQuAD than the smaller Switch-XXL, which uses about 10x the FLOPs per token; the authors say this suggests a poorly understood dependence between fine-tuning quality, FLOPs per token and parameter count (they also report Switch-XXL training instability as unsolved).",
          "Future Work",
          "This suggests a poorly understood dependence between ﬁne-tuning quality, FLOPS per token and number of parameters."),
     ],
     "notes": "PDF states: Journal of Machine Learning Research 23 (2022) 1-40. Affiliation: all authors list Google, Mountain View (title page); reported hardware is TPUv3 (Table 1 setup: 32 cores; Figure 5: 32 TPUv3 cores). In the Table 1 Switch-vs-MoE benchmark, Switch is FLOP-matched to T5-Base (same computation per token) and all models were trained for the same number of steps on identical hardware. Footnote 10 caveat: the T5-XXL comparison gap is described as a lower bound because T5-XXL was pre-trained on an easier C4 version with duplicated snippets. Distillation into dense models preserves about 30% of the quality gain (Discussion). Results tables not recorded."},

    {"id": "arxiv-2312.00752",
     "title": "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
     "authors": ["Albert Gu", "Tri Dao"],
     "year": 2023, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2312.00752",
               "code": "https://github.com/state-spaces/mamba"},
     "tasks": ["scaling-laws", "efficiency-evaluation", "language-modeling"],
     "fam": ["state-space-models", "large-language-models", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["selective state space models (input-dependent SSM parameters) with a hardware-aware parallel scan",
                  "Mamba (attention-free, MLP-free architecture built from selective SSMs)"],
     "claims": [
         ("Method: SSM parameters are made functions of the input so the model can selectively propagate or forget information; because this prevents efficient convolutions, a hardware-aware parallel algorithm in recurrent mode is designed, and the resulting blocks form an architecture without attention or MLP blocks (Mamba).",
          "Abstract",
          "First, simply letting the SSM parameters be functions of the input addresses their weakness with discrete modalities, allowing the model to selectively propagate or forget information along the sequence length dimension depending on the current token."),
         ("Main claims (abstract wording): fast inference (5x higher throughput than Transformers; the measurement conditions behind this figure are the end-to-end generation benchmark in c4/c5, not an unconditional speedup), linear scaling in sequence length, and on language modeling Mamba-3B outperforms Transformers of the same size and matches Transformers twice its size in pretraining and downstream evaluation.",
          "Abstract",
          "On language modeling, our Mamba-3B model outperforms Transformers of the same size and matches Transformers twice its size, both in pretraining and downstream evaluation."),
         ("Scaling-law range and protocol: language-model scaling laws use the Chinchilla protocol on models from about 125M to 1.3B parameters on the Pile (Figure 4 panels at sequence lengths 2048 and 8192), comparing against GPT3-style Transformer and a stronger Transformer++ recipe; the appendix says training tokens were roughly matched to Chinchilla scaling laws (tokens proportional to model size).",
          "Language Modeling (Scaling Laws)",
          "Figure 4 shows scaling laws under the standard Chinchilla (Hoffmann et al. 2022) protocol, on models from ≈125𝑀to ≈1.3𝐵"),
         ("Throughput claim and mechanism: Mamba achieves 4-5x higher inference throughput than a similar-size Transformer, attributed to not needing a KV cache and thus being able to use much higher batch sizes (end-to-end generation benchmark: A100 80GB, prompt length 2048, HuggingFace Transformer baseline, batch sizes 1-128; see c5). Separately, the SSM scan core operation alone (state expansion N=16; A100 80GB PCIe, BF16, batch size 1; see c6) is reported faster than FlashAttention-2 beyond sequence length 2K and up to 20-40x faster than a standard PyTorch scan.",
          "Speed and Memory Benchmarks",
          "Mamba achieves 4-5× higher inference throughput than a Transformer of similar size, since without the KV cache it can use much higher batch sizes."),
         ("End-to-end throughput protocol: a Mamba 1.4B and an untrained Mamba 6.9B are compared to GPT3-architecture Transformers (1.3B, 6.7B) using the standard HuggingFace transformers implementation, with prompt length 2048 and 128 generated tokens over batch sizes 1-128, averaged over 3 repeats on an A100 80GB PCIe GPU.",
          "Appendix (Efficiency Benchmark)",
          "We measure the inference throughput of a Mamba 1.4B model and an untrained Mamba 6.9B model, against a standard Transformer (GPT3 architecture) at 1.3B and 6.7B size."),
         ("Scope of the scan benchmark: the core-operation comparison of scan vs convolution vs attention (A100 80GB PCIe, BF16, batch size 1) excludes other operations such as computing convolution kernels or QKV projections.",
          "Appendix (Efficiency Benchmark)",
          "Note that these do not include the cost of other operations outside of this core operation, such as computing the convolutional kernel in global-convolution models, or computing the QKV projections in attention."),
         ("Limitation (scale): the empirical evaluation is limited to small model sizes, below strong open-source LLMs and the 7B+ scale at which RWKV and RetNet were evaluated; whether Mamba still compares favorably at larger sizes remains to be assessed, and scaling SSMs may need further engineering.",
          "Limitations (Scaling)",
          "It remains to assess whether Mamba still compares favorably at these larger sizes."),
     ],
     "notes": "Affiliations: Carnegie Mellon University and Princeton University (title page). How FLOPs on the scaling-law x-axis are counted was not found in the text (searched FLOPs, FLOP count, non-embedding). Note that the end-to-end throughput baseline is the standard HuggingFace Transformer implementation, while the scan micro-benchmark uses FlashAttention-2 as the attention baseline. Memory benchmark (Table 15, 125M models): memory footprint described as comparable to Transformer with FlashAttention-2. Zero-shot comparisons are against Pythia and RWKV trained on the same tokenizer/dataset/300B tokens. Results tables not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model size, data, compute and performance (scaling laws, compute-optimal training, cost measurement); carded by a subagent. Results tables not recorded; claims only.")
