"""トピック記事(量子化)用に選んだ論文のうち、バッチ topic_quant_b の8本のカード(arXiv 論文)。
何を量子化したか(重み・活性・KV、ビット幅、粒度)、PTQ/QAT と較正データ、評価モデルと評価指標の種類
(perplexity / 下流タスク / 信頼性・公平性・サブグループ指標)、どこで劣化するか、速度・メモリ主張の測定条件、限界を記録する。
結果表の数値は記録しない。書誌は scratchpad の batches/topic_quant_b.json(arXiv API の値)をそのまま書き写した。"""

import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
  {"id": "arxiv-2403.15447",
   "title": "Decoding Compressed Trust: Scrutinizing the Trustworthiness of Efficient LLMs Under Compression",
   "authors": ["Junyuan Hong", "Jinhao Duan", "Chenhui Zhang", "Zhangheng Li", "Chulin Xie", "Kelsey Lieberman",
               "James Diffenderfer", "Brian Bartoldson", "Ajay Jaiswal", "Kaidi Xu", "Bhavya Kailkhura",
               "Dan Hendrycks", "Dawn Song", "Zhangyang Wang", "Bo Li"],
   "year": 2024, "version": "arXiv v3",
   "links": {"arxiv": "https://arxiv.org/abs/2403.15447"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "pruning", "large-language-models"], "par": ["post-hoc"],
   "proposes": ["Trustworthiness evaluation of compressed LLMs (GPTQ/AWQ quantization, magnitude/SparseGPT/Wanda 2:4 pruning) on eight DecodingTrust dimensions plus MMLU and refusal rates"],
   "claims": [
     ("Main claim: quantization is currently more effective than pruning for obtaining efficiency and trustworthiness together (the abstract's example: 4-bit quantization keeps the original's trustworthiness while pruning degrades it even at 50% sparsity).", "Abstract",
      "We find that quantization is currently a more effective approach than pruning in achieving efficiency and trustworthiness simultaneously."),
     ("What is compressed: weights only, with GPTQ and AWQ at 3, 4 and 8 bits (post-training, calibration set of 128 samples), compared with 2:4 semi-structured pruning; models are LLAMA2 13b, LLAMA2 13b Chat and Vicuna 13b Chat.", "Experimental setup",
      "In this paper, we study three pre-trained models: LLAMA2 13b, LLAMA2 13b Chat (Touvron et al., 2023b), and Vicuna 13b Chat (Chiang et al., 2023)."),
     ("Evaluation metrics: benign performance by MMLU average accuracy, trustworthiness by DecodingTrust's eight dimensions (stereotype, privacy, toxicity, fairness, AdvGLUE++, OOD robustness, adversarial demonstrations, ethics), and additionally refusal rates.", "Experimental setup",
      "The benchmark includes 8 trustworthy dimensions: Stereotype, Privacy, Toxicity, Fairness, Adversarial Robustness (AdvGLUE++), Out-Of-Distribution (OOD) Robustness, Robustness to Adversarial Demonstrations (AdvDemo), and Ethics."),
     ("Extreme quantization (3 bits) tends to reduce trustworthiness significantly, and this risk is not visible from benign performance alone, so the authors call for comprehensive trustworthiness evaluation in practice.", "Abstract",
      "This increased risk cannot be uncovered by looking at benign performance alone, in turn, mandating comprehensive trustworthiness evaluation in practice."),
     ("Moderate-bit quantization may unexpectedly improve some trust dimensions such as ethics and fairness.", "Abstract",
      "Moreover, employing quantization within a moderate bit range could unexpectedly improve certain trustworthiness dimensions such as ethics and fairness."),
     ("Calibration-set randomness matters: GPTQ at 4 bits can vary by over 5 points in fairness, ethics and adversarial demonstrations depending on the randomly sampled calibration set, and this variance is not predictable from MMLU.", "Bag of tricks (discussion)",
      "Note that such variance is not predictable from the standard MMLU benchmark."),
     ("The authors modified the DecodingTrust benchmark (to mitigate score variance caused by high refusal rates) and release it with the compressed models.", "Conclusion",
      "To benefit the reproducibility of our experiments, we release all models tested in the benchmark and the modified DecodingTrust benchmark to mitigate the large score variances caused by the large refusal rates."),
   ],
   "notes": "PDF states: Proceedings of the 41st International Conference on Machine Learning (ICML 2024), PMLR 235. "
            "SparseGPT at 50% sparsity was repeated with three randomly sampled C4 calibration sets and averaged; 3-bit AWQ was run on three seeds. "
            "No speed/memory measurements of their own were found; the introduction cites AWQ's reported speedup. Project page in the PDF: https://decoding-comp-trust.github.io (not a code repository URL, so not added to links). "
            "Ajay Jaiswal and Zhangyang Wang are also authors of arxiv-2310.01382 (LLM-KICK), which this paper cites as motivation."},

  {"id": "arxiv-2310.01382",
   "title": "Compressing LLMs: The Truth is Rarely Pure and Never Simple",
   "authors": ["Ajay Jaiswal", "Zhe Gan", "Xianzhi Du", "Bowen Zhang", "Zhangyang Wang", "Yinfei Yang"],
   "year": 2023, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2310.01382", "code": "https://github.com/VITA-Group/llm-kick"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "pruning", "large-language-models"], "par": ["post-hoc"],
   "proposes": ["LLM-KICK (Knowledge-Intensive Compressed LLM BenchmarK): a curated task collection to evaluate compressed LLMs beyond perplexity"],
   "claims": [
     ("Critique of evaluation practice: state-of-the-art LLM compression methods are evaluated mostly with perplexity, a metric that is widely questioned even for dense LLMs; the paper re-evaluates them with LLM-KICK.", "Abstract",
      "As recent research efforts are focused on developing increasingly sophisticated compression methods, our work takes a step back and re-evaluates the effectiveness of existing SoTA compression methods, which rely on a fairly simple and widely questioned metric, perplexity (even for dense LLMs)."),
     ("Setup: compression methods are SparseGPT, Wanda and one-shot magnitude pruning (unstructured and N:M sparsity) plus GPTQ quantization, applied to Vicuna models without fine-tuning.", "LLM-KICK setup",
      "our work primarily focuses on the top-2 existing training-free and data-free LLM pruning techniques (i.e., SparseGPT (Frantar & Alistarh, 2023) and Wanda (Sun et al., 2023)), along with the baseline of One-shot Magnitude-based Pruning (Han et al., 2016), plus a popular quantization technique (GPTQ)"),
     ("Evaluation metric definition: a compressed LLM is called 'matching' if its task performance drops by at most 5% relative to the dense model, a tolerance the authors deliberately relaxed from prior work, which used the dense performance itself or a 1% margin as the matching threshold.", "LLM-KICK setup",
      "In this work, we consider ϵ0 to be ≤5% of the performance of f(x; θ, T)."),
     ("Tasks: factoid QA (FreebaseQA), multiple-choice reasoning QA (MMLU), in-context retrieval-augmented QA, in-context summarization (CNN/DailyMail, judged by GPT-4 against GPT-3.5 summaries) and instruction following.", "LLM-KICK tasks",
      "For evaluation, similar to Zheng et al. (2023), we propose to use GPT-4 as a judge, which compares the compressed LLM generated summaries wrt. GPT-3.5 (text-davinci-003) generated summaries."),
     ("Main findings: pruning methods fail for N:M sparsity on knowledge-intensive tasks; current quantization methods are more successful than pruning; pruned LLMs at 50% or more sparsity remain robust in-context retrieval and summarization systems.", "Abstract",
      "and fail for N:M sparsity in knowledge-intensive tasks; current quantization methods are more successful than pruning; yet, pruned LLMs even at ≥50% sparsity are robust in-context retrieval and summarization systems"),
     ("Even non-aggressive 8-bit GPTQ quantization shows a roughly 8-10% drop on factoid QA, so the authors argue 8-bit quantization is not yet solved.", "Results (factoid QA)",
      "3 ∼8-10% drop in performance for non-aggressive 8-bit quantization indicates that along with chasing for aggressive quantization levels (1-2 bits), it is also important to focus on yet unsolved 8-bit quantization."),
     ("Limitation: the evaluation is restricted mainly to Vicuna (decoder-only) models.", "Conclusion and limitations",
      "We primarily restrict our evaluation to Vicuna (decoder-only architecture) due to its open-source license, high performance, and instruction-following ability."),
   ],
   "notes": "PDF states: Published as a conference paper at ICLR 2024. First author's work was done during an internship at Apple; four co-authors are at Apple. "
            "Quantization is weight-only GPTQ at 8 and 4 bits (figure legends also list 16-bit GPTQ); calibration data for GPTQ and GPTQ group size were not found in the main text. No speed/memory measurements were found. The introduction states that methods are run 'in their most common, default settings'. The main text says Vicuna models are used, but the Figure 2 (factoid QA) panels are labelled 'LLama-7B'."},

  {"id": "arxiv-2402.18158",
   "title": "Evaluating Quantized Large Language Models",
   "authors": ["Shiyao Li", "Xuefei Ning", "Luning Wang", "Tengxuan Liu", "Xiangsheng Shi", "Shengen Yan",
               "Guohao Dai", "Huazhong Yang", "Yu Wang"],
   "year": 2024, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2402.18158", "code": "https://github.com/thu-nics/qllm-eval"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "large-language-models"], "par": ["post-hoc"],
   "proposes": ["Systematic evaluation of PTQ of weights, activations and KV cache across 11 LLM families (125M-180B) and five task types, with bit-width recommendations"],
   "claims": [
     ("Scope: PTQ of weights, activations and KV cache on 11 model families from 125M to 180B parameters, evaluated on basic NLP, emergent ability, trustworthiness, dialogue and long-context tasks.", "Abstract",
      "The evaluation encompasses five types of tasks: basic NLP, emergent ability, trustworthiness, dialogue, and long-context tasks."),
     ("Quantization format: uniform quantization; weight-only uses asymmetric group-wise quantization, weight-activation uses group-wise weights with symmetric per-token activations, and KV cache uses asymmetric group-wise quantization of keys and values.", "Preliminaries",
      "For Weight-only Quantization, we apply asymmetric group-wise quantization as shown in Figure 1 (b)."),
     ("Tensor-type finding: in most cases larger models tolerate weight-only and KV cache quantization better but tolerate activation quantization worse, which the authors relate to activation kurtosis (outliers) increasing with model size.", "Results (basic NLP tasks)",
      "Notably, the Kurtosis of the Activation increases significantly with the size of the model, which means more outliers in the Activation tensors of larger LLMs."),
     ("Task-dependent degradation: in the Ethics benchmark, a W3-quantized model stops refusing some ethical questions and gives informative answers, so the measured accuracy increases after quantization; the paper notes this kind of effect appears only in small models (< 7B), while for larger models lower bit-width means lower performance.", "Results (trustworthiness)",
      "The FP16 LLM refrains from answering some ethical questions, but for W3, the model breaks this limitation and begins to provide informative answers."),
     ("Dialogue is scored by GPT-4 (MT-bench single-answer grading); most families can be quantized to W8, W8A8 and KV4 without significant loss of GPT-4 score, while lower bit-widths lead to sentence-level and then token-level repetition.", "Results (dialogue)",
      "Most LLM families can be quantized to W8, W8A8, and KV4 without significant loss of GPT-4 score (< 2%), as shown in Table 1."),
     ("Long-context tasks are more sensitive to KV cache quantization than to weight-only or weight-activation quantization for most LLMs.", "Results (long-context)",
      "For long-context tasks (≥4k), most LLMs are more sensitive to KV Cache Quantization than Weight-only and Weight-Activation Quantization."),
     ("SOTA methods: AWQ improves weight-only quantized LLMs but cannot restore W2 models, and SmoothQuant only partially recovers W4A4.", "Appendix (SOTA quantization methods)",
      "However, in the case of W2 quantization, where quantized LLMs lose their abilities entirely, AWQ cannot restore the corrupted performances."),
     ("Limitations: only PTQ (no QAT), no ablation of group size, not all small LLMs evaluated, and bit-width recommendations may not transfer to new tasks or LLMs.", "Limitations",
      "In this paper, we focused solely on Post-training Quantization (PTQ) and did not consider Quantization-Aware Training (QAT)."),
   ],
   "notes": "PDF states: Proceedings of the 41st International Conference on Machine Learning (ICML 2024), PMLR 235. "
            "The baseline quantizer is round-to-nearest (labeled RTN in the AWQ/SmoothQuant comparison tables); bit-width recommendations are defined as within 2% accuracy loss on the evaluated tasks. "
            "Tensor statistics for activations and KV cache are computed on pile-val. No measured speedups were found (the efficiency discussion is qualitative: memory-bound decoding vs compute-bound prefill). "
            "Affiliations include Infinigence AI (a company) besides Tsinghua University and Shanghai Jiaotong University."},

  {"id": "arxiv-1911.05248",
   "title": "What Do Compressed Deep Neural Networks Forget?",
   "authors": ["Sara Hooker", "Aaron Courville", "Gregory Clark", "Yann Dauphin", "Andrea Frome"],
   "year": 2019, "version": "arXiv v3",
   "links": {"arxiv": "https://arxiv.org/abs/1911.05248"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "pruning", "deep-learning"], "par": ["supervised", "post-hoc"],
   "proposes": ["Pruning Identified Exemplars (PIEs) and a class-level statistical audit (Welch's t-test over 30-model populations) of the disparate impact of compression"],
   "claims": [
     ("Main claim: top-line accuracy hides that compressed models with very different weight counts diverge on a narrow subset of the data, which the authors call Pruning Identified Exemplars (PIEs).", "Abstract",
      "We ﬁnd that models with radically different numbers of weights have comparable top-line performance metrics but diverge considerably in behavior on a narrow subset of the dataset."),
     ("Compression methods: magnitude pruning during training at 30-90% sparsity, and three post-training quantization variants (float16, hybrid dynamic-range int8 weights, and fixed-point int8 using a small representative dataset).", "Experimental framework",
      "All quantization methods we evaluate are implemented post-training, in contrast to the pruning which is applied progressively over the course of training."),
     ("Evaluation protocol: a population of independently trained models per compression method, dataset and model (30 per pruning level); for each class a two-tailed Welch's t-test on mean-shifted class accuracy decides (p <= 0.05) whether compression impacts that class disproportionately; tasks are CIFAR-10 (wide ResNet), ImageNet (ResNet-50) and CelebA (ResNet-18).", "Methodology",
      "If the p-value <= 0.05, we reject the null hypothesis and consider the class to be disparately impacted by t level of compression relative to the baseline."),
     ("PIEs are more difficult for models and humans: a human study finds they are more often mislabelled, lower quality, multi-object or fine-grained, and compression impairs prediction on the long tail of less frequent instances.", "Introduction (contributions)",
      "Compression impairs the model’s ability to predict accurately on the long-tail of less frequent instances."),
     ("Quantization versus pruning: all evaluated techniques have non-uniform impact, but quantization appears to introduce less disparate harm than (high levels of) pruning.", "Results",
      "While all the techniques we benchmark evidence disparate class level impact, we note that quantization appears to introduce less disparate harm."),
     ("Pruned networks are more sensitive to distribution shift (ImageNet-C corruptions and ImageNet-A natural adversarial images), increasingly so at higher sparsity.", "Introduction (contributions)",
      "Pruned networks are more sensitive to natural adversarial images and corruptions."),
     ("Limitations: implications for fairness remain open, and other domains such as language and audio were not evaluated.", "Limitations",
      "Underserved areas worthy of future consideration include evaluating the impact of compression on additional domains such as language and audio, and leveraging these insights to explicitly optimize for compressed models that also minimize the disparate impact on underrepresented data attributes."),
   ],
   "notes": "Image classification only. Pruning schedule and hyperparameters were chosen by a limited grid search to maximize top-1 accuracy. PIEs are defined from modal-label disagreement between compressed and uncompressed model populations, which needs no true labels. "
            "The distribution-shift analysis (ImageNet-C/A) is for pruned models only; quantized models are not included there. "
            "The PDF says the code is publicly available but the link text did not survive extraction, so no code link is recorded. All authors list Google affiliations except Aaron Courville (MILA)."},

  {"id": "arxiv-2010.03058",
   "title": "Characterising Bias in Compressed Models",
   "authors": ["Sara Hooker", "Nyalleng Moorosi", "Gregory Clark", "Samy Bengio", "Emily Denton"],
   "year": 2020, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2010.03058"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "pruning", "deep-learning"], "par": ["supervised", "post-hoc"],
   "proposes": ["Compression Identified Exemplars (CIE; Modal and Taxicab variants) as a label-free, human-in-the-loop auditing tool for compression-induced bias"],
   "claims": [
     ("Main claim: overall accuracy hides disproportionately high errors on a small subset (CIE), and for these examples compression amplifies existing algorithmic bias.", "Abstract",
      "We further establish that for CIE examples, compression ampliﬁes existing algorithmic bias."),
     ("Setup: ResNet-18 on CelebA predicting Blonde hair; protected attributes Male and Young and their intersection; metrics are sub-group error rate, false positive rate and false negative rate relative to the non-compressed baseline.", "Methodology",
      "To characterize the impact of compression on age and gender sub-groups we compare sub-group error rate, false positive rate (FPR) and false negative rate (FNR) between a baseline (i.e. non-compressed) and models pruned and quantized to different levels of compression (i.e. compressed)."),
     ("Quantization protocol: post-training 8-bit quantization (hybrid dynamic range and fixed-point), with the first 100 training examples as representative (calibration) examples, via TensorFlow Lite; pruning is magnitude pruning during training.", "Methodology",
      "We use the MLIR implementation via TensorFlow Lite (Jacob et al., 2018; Lattner et al., 2020)."),
     ("Pruning hyperparameters were chosen by a limited grid search minimizing test-set accuracy degradation, and 30 models were trained per compression level to separate effects from training noise.", "Methodology",
      "These hyperparameter choices were based upon a limited grid search which suggested that these particular settings minimized degradation to test-set accuracy across all pruning levels."),
     ("Failure mode: compression cannibalizes performance on low-frequency attributes to preserve overall performance; for example the false positive rate for Male rises much more than for not Male at 95% pruning, which the authors note appears closely tied to the attributes' representation in the training data.", "Results",
      "Compression cannibalizes performance on low-frequency attributes in order to preserve overall performance."),
     ("CIE requires no attribute labels, but this becomes a limitation in an overfit regime with 0% training error, where neither CIE measure can be computed on the training set.", "Divergence measures",
      "That said, note that this turns into a limitation in an overﬁt 0% training error regime as without any predictive difference it would not be possible to compute CIE using either measure in the training set."),
   ],
   "notes": "Single dataset (CelebA, binary task). The disaggregated sub-group error/FPR/FNR table reported in the main text is for 95% pruning; for quantized models only overall and CIE accuracy are tabulated, so the sub-group bias evidence is mainly from pruning. "
            "The methodology says 30 models are trained per compression level, while the Table 3 caption says error rates are averaged over 10 models. All authors list Google affiliations. Builds on arxiv-1911.05248 (Modal CIE = PIE)."},

  {"id": "arxiv-2411.04330",
   "title": "Scaling Laws for Precision",
   "authors": ["Tanishq Kumar", "Zachary Ankner", "Benjamin F. Spector", "Blake Bordelon", "Niklas Muennighoff",
               "Mansheej Paul", "Cengiz Pehlevan", "Christopher Ré", "Aditi Raghunathan"],
   "year": 2024, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2411.04330"},
   "tasks": ["model-compression", "scaling-laws", "language-modeling"],
   "fam": ["quantization", "post-training-quantization", "quantization-aware-training", "large-language-models"],
   "proposes": ["Precision-aware scaling laws: an effective parameter count N_eff for low-precision training and a post-training-quantization degradation term delta_PTQ that grows with data"],
   "claims": [
     ("Main claim: PTQ degradation increases as models are trained on more data, eventually making additional pretraining data harmful; the authors propose that training in lower precision reduces the effective parameter count.", "Abstract",
      "For inference, we find that the degradation introduced by post-training quantization increases as models are trained on more data, eventually making additional pretraining data actively harmful."),
     ("Setup: OLMo-style models on Dolma V1.7 with 30-220M non-embedding parameters and 1.5-26B tokens, sweeping 8 precisions each for weights, activations and attention (KV); over 465 pretraining runs, with predictions validated up to 1.7B parameters.", "Setup",
      "Our experiments consist of a sweep of language model pretraining runs over N ∈[30, 60, 110, 220] million parameters (non-embedding) and D ∈[1.5, 3, 6, 13, 26] billion tokens."),
     ("PTQ setting: BF16-trained models are weight-quantized after training with GPTQ, with findings replicated with AWQ and round-to-nearest in the appendix.", "Scaling laws for post-train quantization",
      "In this section, we consider models trained in BF16 and use GPTQ [Frantar et al., 2022] to post-train quantize them, replicating our findings with two other methods in Appendix F."),
     ("Within a model size, degradation from PTQ grows with training data, while for a fixed dataset size larger models degrade less; degradation grows exponentially as the post-training precision is lowered.", "Scaling laws for post-train quantization",
      "We find that the degradation δPTQ increases in training data size across all model sizes, but that for a fixed dataset size larger models incur a smaller degradation."),
     ("For training, the fitted laws suggest that training larger models in lower precision may be compute optimal (under the paper's cost model).", "Abstract",
      "For training, our scaling laws allow us to predict the loss of a model with different parts in different precisions, and suggest that training larger models in lower precision may be compute optimal."),
     ("The authors stress that the contribution is the trends and functional forms rather than the fitted numerical constants, which can vary with small implementation differences.", "Background",
      "For this reason, we emphasize our contribution is not the numerical values we fit, but the trends and functional forms we identify."),
     ("Limitations: a fixed architecture, compute gains from halving precision usually below 2x due to systems overhead, and only loss scaling without downstream evaluations; trends are meant to be suggestive.", "Conclusion and limitations",
      "Third, we only consider loss scaling without downstream model evaluations."),
   ],
   "notes": "Evaluation metric is validation loss only (no perplexity-on-benchmark or downstream tasks). Quantization-aware training here means weight-only quantization during training; low-precision training quantizes weights, activations and attention. "
            "Integer-type precision is used in the main sweeps (floating-point replication in an appendix). No measured kernel speedups; compute costs come from a cost model. Affiliations include Databricks for two authors. No paradigm tag fits language-model pretraining, so paradigms are omitted."},

  {"id": "arxiv-2208.07339",
   "title": "LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale",
   "authors": ["Tim Dettmers", "Mike Lewis", "Younes Belkada", "Luke Zettlemoyer"],
   "year": 2022, "version": "arXiv v2",
   "links": {"arxiv": "https://arxiv.org/abs/2208.07339", "code": "https://github.com/TimDettmers/bitsandbytes"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "large-language-models"], "par": ["post-hoc"],
   "proposes": ["LLM.int8(): vector-wise Int8 quantization plus mixed-precision decomposition that keeps outlier feature dimensions in 16-bit"],
   "claims": [
     ("Method: Int8 matrix multiplication for feed-forward and attention projection layers, combining vector-wise quantization with a mixed-precision decomposition that isolates outlier feature dimensions into 16-bit multiplication while more than 99.9% of values are multiplied in 8-bit.", "Abstract",
      "However, for the emergent outliers, we also include a new mixed-precision decomposition scheme, which isolates the outlier feature dimensions into a 16-bit matrix multiplication while still more than 99.9% of values are multiplied in 8-bit."),
     ("Post-training use without retraining: a 16/32-bit checkpoint can be converted to Int8 and used immediately; the paper claims no performance degradation up to 175B parameters.", "Abstract",
      "With our method, a 175B parameter 16/32-bit checkpoint can be loaded, converted to Int8, and used immediately without performance degradation."),
     ("Failure mode of regular 8-bit quantization: systematic large-magnitude outlier features emerge in all transformer layers from about 6.7B parameters, and regular quantization methods fail from that scale (shown with C4 perplexity and OPT zero-shot accuracy).", "Introduction",
      "the need to explicitly represent the sparse but systematic large magnitude outlier features that ruin quantization precision once they emerge in all transformer layers starting at scales of 6.7B parameters"),
     ("Evaluation metrics: C4 validation perplexity on fairseq-pretrained models (125M-13B) to compare quantization baselines, and zero-shot accuracy on OPT models (up to 175B) via the EleutherAI evaluation harness compared only against a 16-bit baseline.", "Section 3.3",
      "Additionally, we evaluate zeroshot accuracy degradation on OPT models for a range of different end tasks, where we compare our methods with a 16-bit baseline."),
     ("Speed: the main focus is memory; quantization overhead can slow inference for models below 6.7B parameters relative to FP16, while large matrix multiplications equivalent to 175B models run about two times faster (appendix benchmarks).", "Section 3.4",
      "The quantization overhead can slow inference for models with less than 6.7B parameters, as compared to a FP16 baseline."),
     ("End-to-end BLOOM-176B inference in Hugging Face with Int8 is slightly slower but close to 16-bit per-token latency.", "Appendix D.2",
      "Overall Int8 inference is slightly slower but close to the millisecond latency per token compared to 16-bit inference."),
     ("Limitations: only the Int8 data type (no FP8), only models up to 175B, no Int8 for the attention function, and only inference (not training or fine-tuning).", "Discussion and limitations",
      "The main limitation of our work is that our analysis is solely on the Int8 data type, and we do not study 8-bit ﬂoating-point (FP8) data types."),
         ("Absmax quantization: X_i8 = round(127 X_f16 / max_ij |X_f16,ij|), i.e. scaling into [-127, 127] by 127 divided by the absolute maximum (infinity norm) of the entire tensor.", "Section 2.1", "Absmax quantization scales inputs into the 8-bit range [−127, 127] by multiplying with sxf16 which is 127 divided by the absolute maximum of the entire tensor."),
   ],
   "notes": "PDF states: 36th Conference on Neural Information Processing Systems (NeurIPS 2022). Quantization of weights and hidden-state inputs of linear layers is done on the fly (absmax / vector-wise), with no calibration dataset; the outlier threshold alpha = 6.0 was chosen from perplexity degradation analysis. "
            "Perplexity evaluation on NVIDIA A40 GPUs; matrix-multiplication speed benchmarks compare cuBLASLt Int8 with cuBLAS 16-bit, and the authors note default PyTorch/NVIDIA quantization kernels slow down most matrix multiplications. "
            "Affiliations: University of Washington, Facebook AI Research, Hugging Face (the method is integrated into Hugging Face Transformers)."},

  {"id": "arxiv-2404.14047",
   "title": "An empirical study of LLaMA3 quantization: from LLMs to MLLMs",
   "authors": ["Wei Huang", "Xingyu Zheng", "Xudong Ma", "Haotong Qin", "Chengtao Lv", "Hong Chen", "Jie Luo",
               "Xiaojuan Qi", "Xianglong Liu", "Michele Magno"],
   "year": 2024, "version": "arXiv v3",
   "links": {"arxiv": "https://arxiv.org/abs/2404.14047"},
   "tasks": ["model-compression"],
   "fam": ["quantization", "post-training-quantization", "quantization-aware-training", "large-language-models"], "par": ["post-hoc"],
   "proposes": ["Empirical evaluation of 9 PTQ and 2 LoRA-fine-tuning quantization methods on LLaMA3-8B/70B (1-8 bits) and of PTQ on the LLaMA3-based LLaVA-Next-8B (2-4 bits)"],
   "claims": [
     ("Main claim: LLaMA3 still suffers non-negligible degradation from quantization in linguistic and visual contexts, particularly at ultra-low bit widths.", "Abstract",
      "Our experimental results indicate that LLaMA3 still suffers from non-negligible degradation in linguistic and visual contexts, particularly under ultra-low bit widths."),
     ("Evaluation metrics: perplexity on WikiText2, PTB and part of C4, zero-shot accuracy on PIQA, Winogrande, ARC-e, ARC-c and HellaSwag, 5-shot MMLU for LoRA-FT methods, and visual-language benchmarks for LLaVA-Next-8B.", "Introduction (evaluation datasets)",
      "For the PTQ methods, we evaluate quantized LLaMA3 on the WikiText2 [18], PTB [20], and a portion of the C4 dataset [19], using perplexity (PPL) as the evaluation metric."),
     ("Calibration protocol: WikiText2 is the calibration set for all PTQ methods (128 samples, sequence length 2048), and group size is fixed at 128 for grouped methods; WikiText2 is also one of the perplexity evaluation sets.", "Introduction (evaluation datasets)",
      "To ensure fairness in evaluation of different PTQ methods, we set WikiText2 as the calibration dataset for all quantization methods, with a sample size of 128 and a sequence length of 2048."),
     ("LoRA fine-tuning (QLoRA, IR-QLoRA on Alpaca) does not compensate for quantization error on LLaMA3-8B below 4 bits and actually worsens MMLU, in contrast to LLaMA and LLaMA2, where 4-bit LoRA-FT versions could even outperform FP16 on MMLU.", "Track 2: LoRA-FT quantization",
      "On the MMLU dataset, the most notable observation with LLaMA3-8B under LoRA-FT quantization is that low-rank fine-tuning on the Alpaca [36] dataset not only fails to compensate for the errors introduced by quantization, but actually exacerbates the degradation."),
     ("The authors find that LLaMA3-70B shows significant robustness to the different quantization methods, even for ultra-low bit widths.", "Track 1: post-training quantization",
      "Moreover, we find that the LLaMA3-70B model shows significant robustness to different quantization methods, even for ultra-low bit-width quantization."),
     ("Multimodal failure: with GPTQ or AWQ, the 2-bit LLaVA-Next-8B collapses completely on the multimodal QA tasks; SliM-LLM mitigates the collapse but still degrades strongly.", "Track 3: MLLM quantization",
      "Notably, regardless of GPTQ or AWQ, we observe that the 2-bit LLaVA-Next-8B completely collapses in the six multi-modal QA tasks, with scores dropping to zero."),
     ("Possible conflict of interest not discussed in the paper: three evaluated methods (SliM-LLM, BiLLM, IR-QLoRA) have reference entries whose author lists include authors of this study, while the paper's competing-interests statement declares none.", "References",
      "Wei Huang, Haotong Qin, Yangdong Liu, Yawei Li, Xianglong Liu, Luca Benini, et al. SliM-LLM: Salience-driven mixed-precision quantization for large language models."),
   ],
   "notes": "Version 3 (retitled by the authors); title copied from arXiv API metadata. The PDF text lists 9 PTQ methods but Fig. 1 also shows SpinQuant and OmniQuant; the text says '6 visual language benchmarks' while listing 5. "
            "LoRA-FT methods (QLoRA, IR-QLoRA) are tagged quantization-aware-training as the closest family: the base model is quantized and low-rank adapters are fine-tuned. "
            "Evaluation used 8 NVIDIA A800 80GB GPUs; GPU memory, training time and inference latency are reported only for LoRA-FT methods (Table 10). Calibration and perplexity evaluation both use WikiText2 (splits not stated in the text found)."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): quantization; carded by a subagent. Results tables not recorded; claims only.")
