import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ad_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1811.02141",
     "title": "Extended Isolation Forest",
     "authors": ["Sahand Hariri", "Matias Carrasco Kind", "Robert J. Brunner"],
     "year": 2018, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1811.02141"},
     "tasks": ["anomaly-detection"],
     "fam": ["classical-outlier-detectors", "tree-ensembles"], "par": ["unsupervised"],
     "proposes": ["Extended Isolation Forest (EIF): isolation trees whose branch cuts are hyperplanes with a random slope (normal vector with N(0,1) components, i.e. uniform on the unit sphere) and a random intercept drawn uniformly over the range of the data at the node, instead of axis-parallel cuts on one randomly chosen feature",
                  "Extension levels: zeroing coordinates of the normal vector gives N levels for N-dimensional data; level 0 is identical to the standard Isolation Forest",
                  "Rotated trees: running the standard Isolation Forest on a randomly rotated sub-sample per tree (presented as a less desirable alternative)"],
     "claims": [
         ("Diagnosis: on 2-D normally distributed data, the standard Isolation Forest score map shows rectangular regions of lower anomaly score along the x and y directions compared with points at the same radial distance; the authors attribute these differences to the algorithm and note that two points of similar importance can then be categorized differently depending on the threshold.",
          "Section 2 (Motivation)",
          "As we will see in later sections, the diﬀerence in the anomaly score in the x and y directions are indeed an artifacts introduced by the algorithm."),
         ("With two Gaussian clusters, the artifact is amplified where the bands intersect, producing low-score \"ghost\" clusters near (0, 0) and (10, 10); an anomaly near the origin would most likely be categorized as nominal. The authors state this increases the chances of false positives and indicates a non-existent structure.",
          "Section 2 (Motivation)",
          "Not only does this increase the chances of false positives, it also wrongly indicates a non-existent structure in the data."),
         ("Mechanism: because each cut picks one random feature and a random value, all branch cuts are parallel to the coordinate axes; cuts still concentrate where the data are, but regions with few data points end up with many cuts through them, so e.g. a point near (4, 0) receives many more branching operations than one near (3, 3) although both are anomalies relative to the center.",
          "Section 3 (Generalization of Isolation Forest)",
          "However, because of the constraint that the branch cuts are only vertical and horizontal, regions that don’t necessarily contain many data points end up with many branch cuts through them."),
         ("Rotating each tree's sub-sample by a random angle averages the bias out across trees and improves the score maps, but the authors call it not the ideal fix: each tree still has the rectangular bias, every tree must store its rotation, rotation is not obvious beyond 2-D and the approach can become cumbersome for large, high-dimensional data. They suggest EIF should be preferred over rotation.",
          "Rotated Trees",
          "In a sense the problem is not resolved, but only averaged out."),
         ("EIF branch cuts: a random slope is chosen by drawing each component of the normal vector from N(0, 1), which gives a uniform selection on the N-sphere; the intercept is drawn uniformly over the range of values at the branching point, and a point goes left if (x - p) . n <= 0. Intercepts still accumulate where the data are, but no region artificially receives more cuts.",
          "Extended Isolation Forest",
          "This results in a uniform selection of points on the N-sphere."),
         ("Extension levels: setting coordinates of the normal vector to zero gives levels Ex 0 to Ex N-1; Ex 0 is identical to the standard Isolation Forest. The authors suggest lower extension levels may be useful when the dynamic ranges of dimensions differ strongly, and that for data essentially distributed along a line the standard Isolation Forest would probably give the best result.",
          "High Dimensional Data and Extension Levels",
          "Isolation Forest method would probably yield the most optimal result."),
         ("AUC protocol: on the synthetic examples both algorithms are trained on 2000 points and then 200 anomalous points are added and scored; AUROC and AUPRC are also reported on five real benchmark datasets (Cardio, ForestCover, Ionosphere, Mammography, Satellite). The only comparison is EIF vs the standard Isolation Forest; no number of trees, sub-sample size, train/test split or number of repeats for the benchmark runs was found in the text (searched for sub-sample, trees, split, repeat, runs, contamination).",
          "Section 4 (AUC Comparison)",
          "In order to obtain the AUC values for the example datasets, we ﬁrst train both algorithms on 2000 data points in each case distributed as seen previously."),
         ("On the real benchmarks the authors report improved AUC for EIF but note the improvement may seem modest in some cases and appreciable in others, because the axis-parallel limitation affects some datasets more than others.",
          "Section 4 (AUC Comparison)",
          "Naturally, the axis-parallel limitation has more eﬀects on some datasets than other."),
         ("Cost: in convergence plots of the score versus forest size (2-D, 3-D and 4-D blobs), the scores settle quickly and the authors find no appreciable difference in convergence rate between the standard Isolation Forest and EIF at any extension level, concluding that the number of trees should be the same and that EIF does not sacrifice computational efficiency. No wall-clock timing table was found in the body (the abstract's statement on computation time is supported by the convergence plots).",
          "Convergence of Anomaly Scores",
          "Moreover we ﬁnd no appreciable diﬀerence between the standard Isolation Forest and the Extended Isolation Forest, including all the extension levels."),
     ],
     "notes": "Affiliation: University of Illinois at Urbana-Champaign / NCSA. The PDF says 'Manuscript received April 10, 2018' and states no venue, so no venue is recorded (Deep Isolation Forest, arxiv-2206.06602, cites it as IEEE Trans. Knowl. Data Eng. vol. 33, but that is not confirmed by this PDF or its arXiv comment). Section numbers 2-5 are confirmed by the outline in the Introduction ('Section 2 provides...', 'In section 4 we compare...'); subsections are named because the extracted headings carry no numbers. Variance-of-score analyses (concentric circles at 1-3 sigma, sine curve, 3-D and 4-D blobs) are shown as figures only. Python implementation: https://github.com/sahandha/eif. 9 claims: the ghost-cluster claim is kept separately because later work (DIF) uses it as a benchmark of algorithmic bias."},

    {"id": "arxiv-2206.06602",
     "title": "Deep Isolation Forest for Anomaly Detection",
     "authors": ["Hongzuo Xu", "Guansong Pang", "Yijie Wang", "Yongjun Wang"],
     "year": 2022, "venue": "IEEE TKDE", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2206.06602"},
     "tasks": ["anomaly-detection", "time-series-anomaly-detection"],
     "fam": ["tree-ensembles", "deep-learning"], "par": ["unsupervised"],
     "proposes": ["Deep Isolation Forest (DIF): an ensemble of r random representations produced by randomly initialised, never-trained neural networks, with t isolation trees using axis-parallel cuts built on each representation (equivalent to non-linear partitions of the original space); iForest and EIF are shown to be special cases with a single linear layer",
                  "CERE: computing all ensemble members in one mini-batch with rank-one (Hadamard) perturbations of a base weight matrix",
                  "DEAS: an anomaly score combining iForest's path-length score with the average deviation of the feature value from the split threshold along the path"],
     "claims": [
         ("Hard anomalies: iForest cannot handle anomalies that can only be isolated in higher-order subspaces (combinations of features) because it treats features separately with one feature per isolation operation; e.g. anomalies surrounded by ring-shaped normal data end up with isolation depths indistinguishable from normal data, causing false negatives.",
          "Introduction",
          "because it treats all features separately and considers only one feature per isolation operation."),
         ("On existing extensions: PID still uses axis-parallel isolation and shows the same algorithmic bias; EIF works better thanks to random-slope hyperplanes, but its partitions are still linear, which the authors say is ineffective where only non-linear partitions isolate anomalies (reflected in wrinkled score contours).",
          "Introduction",
          "However, the partitions still operate linearly, which works ineffectively on challenging datasets where only non-linear partitions are useful in isolating anomalies from the other data."),
         ("Method: DIF maps the data with an ensemble of randomly initialised neural networks that are never optimised and builds isolation trees with random axis-parallel cuts on each representation; the authors argue the randomness gives high freedom of partition in the original space and a synergy between random representations and random-partition isolation.",
          "Introduction",
          "These networks are only casually initialised and do not involve any optimisation or training process."),
         ("Why random rather than optimised representations: the authors state that optimised representations are more expressive if the objective fits the data, but (i) such losses are not versatile across data and (ii) optimisation might strongly control the downstream partition, weakening the randomness and diversity that isolation-based scoring requires.",
          "Discussions",
          "(ii) The downstream data partition might be strongly controlled by the optimisation process."),
         ("Settings: DIF uses r = 50 representations, t = 6 trees each and subsampling size 256; the IF-based baselines (iForest from scikit-learn, EIF from the eif package at maximum extension level, PID, LeSiNN) use 300 trees and subsampling 256 (LeSiNN 8). Deep baselines (deep-ensemble versions of RDP, REPEN, Deep SVDD, an autoencoder) are trained 50 epochs x 30 steps with Adam 1e-3; RDP used 1e-4 because it was empirically found to work significantly better; other parameters of competitors are default/recommended.",
          "Section 6.1.3 (Parameter Settings and Implementations)",
          "The default/recommended settings are used for the other parameters of these competing methods."),
         ("Evaluation: 10 tabular datasets (4 UNSW-NB15 attack types, R8, Cover, Fraud, Pageblocks, Shuttle, Thrombin), 4 Tox21 graph datasets and 4 UCR time-series datasets with natural anomalies; metrics are AUC-ROC and AUC-PR with a paired Wilcoxon signed-rank test. Tables report mean ± standard deviation, but no number of runs and no train/test protocol for the tabular datasets in the main comparison was found in the text (searched for runs, repeat, seed, independent, trained, test set).",
          "Section 6.1.4 (Evaluation Metrics and Computing Infrastructure)",
          "the detection accuracy is evaluated by two complementary metrics including Area Under the ROC Curve (AUC-ROC) and Area Under the PR Curve (AUC-PR)."),
         ("Exception where a classical distance-based method wins: DIF is the best isolation-based detector on all ten tabular datasets except AUC-PR on Fraud, where the nearest-neighbour-based LeSiNN is more effective; the authors explain that Fraud's features are PCA-transformed, so distances reflect proximity well.",
          "Section 6.2 (Tabular Data)",
          "The features in Fraud are the results of PCA transformation due to the confidentiality issues, and thus the distance concept used in the nearest neighbour information can well reflect the proximity relationship."),
         ("Contamination protocol: graph and time-series datasets have pre-defined splits with anomaly-free training sets, so only tabular datasets are used; following prior work, anomalies are injected/removed to set training contamination from 0% to 10%, models are trained on the adjusted data and tested on the original version. Performance of all detectors degrades as contamination increases (results shown as a figure).",
          "Section 6.4 (Robustness w.r.t. Anomaly Contamination)",
          "Time-series datasets and graph datasets have pre-defined train-test split and their training sets do not contain anomalies, and thus we use tabular datasets as our bases here."),
         ("Cost: on synthetic data of varying size and dimensionality, isolation-based methods (including DIF) scale well on CPU compared with deep-ensemble methods, which benefit from GPU on high-dimensional data; the authors attribute DIF's efficiency relative to the deep ensembles to needing a single feed-forward pass instead of many training epochs.",
          "Section 6.3 (Scalability to High-dimensional, Large-scale Data)",
          "DIF shows outstanding time efficiency compared to its deep ensemble-based counterparts since it only requires one feed-forward step instead of a large number of training epochs."),
     ],
     "notes": "Affiliations: National University of Defense Technology; Singapore Management University (Guansong Pang). Venue from the arXiv comment ('Accepted by IEEE Transactions on Knowledge and Data Engineering'); the PDF header also reads 'IEEE TRANSACTIONS ON KNOWLEDGE AND DATA ENGINEERING'. Conflict of interest (from the reference list, not stated as such in the paper): co-author G. Pang is an author of the baselines REPEN [10] and RDP [13] and of the cited protocol work [15]; the comparison is therefore partly authors-vs-their-own-earlier-methods. Graph/time-series baselines (iForest, EIF, LeSiNN) are run on representations learned by InfoGraph/TS2Vec, while DIF uses the same GIN/CNN architectures untrained. Other stated limitations: DIF is inferior to its variants (DIF-ECOD/KNN/LOF on random representations) on Shuttle, and those scoring methods give markedly better individual scores on Exploits, R8 and Thrombin; KNN and LOF took around 60 hours on Cover and Fraud. Section numbers are confirmed by in-text cross-references (Sec. 6.1-6.6, 6.1.3, 6.1.4). Uses the UCR anomaly archive (points/segments), hence time-series-anomaly-detection. Code: https://github.com/xuhongzuo/deep-iforest. 9 claims."},

    {"id": "arxiv-2103.16440",
     "title": "Neural Transformation Learning for Deep Anomaly Detection Beyond Images",
     "authors": ["Chen Qiu", "Timo Pfrommer", "Marius Kloft", "Stephan Mandt", "Maja Rudolph"],
     "year": 2021, "venue": "ICML 2021", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2103.16440"},
     "tasks": ["anomaly-detection"],
     "fam": ["deep-learning", "joint-embedding"], "par": ["self-supervised"],
     "proposes": ["NeuTraL AD: K learnable neural transformations and an encoder trained jointly on a deterministic contrastive loss (DCL) that pulls each transformed view towards the original sample's embedding and pushes views of the same sample apart; the same loss evaluated on a test sample is the anomaly score (no negative samples from other data)"],
     "claims": [
         ("Motivation: hand-crafted transformations give excellent image anomaly detectors with transformation-prediction or contrastive losses, but since transformations are not always easy to design for new domains (time series, tabular), the authors study learning them.",
          "Section 3.2",
          "Since it is not always easy to design transformations for new application domains, we study their suitability for learning data transformations."),
         ("Theory: with learnable transformations, the transformation-prediction loss tends to its minimum in a 'constant' edge case (views not depending on the input) and the SimCLR loss is minimized by the 'identity' edge case (no diversity); in both cases normal and abnormal inputs incur the same loss. The authors prove that neither edge case minimizes the DCL.",
          "Section 3.2",
          "Proposition 3. The edge-cases of Propositions 1 and 2 do not minimize L (DCL, Equation (2)).", 5),
         ("Scope: the method targets data beyond images; for image data strong self-supervised baselines with hand-crafted transformations exist and the authors do not expect any benefit from NeuTraL AD there (images are not evaluated).",
          "Section 4 (Empirical Study)",
          "We do not expect any beneﬁt from using NeuTraL AD there."),
         ("Setting and model selection: evaluation is one-vs-rest (train on one class, other classes are anomalies) and n-vs-rest, i.e. training on clean normal-class data. A footnote states that 10% of the test set is used as the validation set to allow parameterization selection.",
          "Section 4.3 (Implementation Details, footnote)",
          "We use 10% of the test set as the validation set to allow parameterization selection."),
         ("Baseline configuration: OC-SVM, IF and LOF are run from scikit-learn with default parameters; for DAGMM the number of mixture components (4 to 12) and for GOAD the reduced dimension r of the affine transformations are each set to the best-performing value. The set on which 'best performing' was judged is not stated (searched for validation, select, tune).",
          "Appendix B.2",
          "OC-SVM, IF, and LOF are taken from scikit-learn library with default parameters."),
         ("Time series (whole-sequence anomaly detection on five UEA datasets selected because supervised classifiers do well on them), one-vs-rest: NeuTraL AD outperforms all shallow baselines in all experiments and the deep baselines in 4 of 5, losing on RS to transformation prediction with hand-crafted transformations; the shallow methods perform well on SAD and CT but worse than deep methods on the other data.",
          "Section 4.3 (Anomaly Detection of Time Series)",
          "the shallow methods perform well on SAD and CT, but perform worse than the deep learning based methods on other data."),
         ("When the normal class becomes more varied (n-vs-rest), all methods drop; LOF, a k-nearest-neighbor method, beats NeuTraL AD and all baselines on SAD when n > 3, and for n = N - 1 LOF performs better than the deep learning methods on CT and SAD.",
          "Section 4.3 (Anomaly Detection of Time Series)",
          "The traditional method LOF performs better than deep learning methods on CT and SAD."),
         ("Tabular protocol (Arrhythmia, Thyroid, KDD, KDDRev): following Zong et al. (2018), models are trained on half of the normal data and tested on the rest of the normal data plus the anomalies, reporting F1 as in prior work. Results for OC-SVM, LOF, DAGMM and GOAD are taken from Bergman & Hoshen (2020) and DROCC results were provided by its authors (a footnote notes their own study used a different setting). How the F1 decision threshold is set was not found in the text (searched for threshold).",
          "Section 4.4 (Anomaly Detection of Tabular Data)",
          "We follow the conﬁguration of (Zong et al., 2018) to train all models on half of the normal data, and test on the rest of the normal data as well as the anomalies."),
         ("Limitations: with K <= 4 transformations performance has larger variance because, without labels, the learned transformations are not guaranteed to be useful for anomaly detection (performance stabilizes for large enough K); transformation-based methods need roughly K times the memory of other deep methods such as Deep SVDD.",
          "Section 4.5 (Design Choices for the Transformations)",
          "The transformation based methods (including NeuTraL AD) have roughly K times the memory requirement as other deep learning methods (e.g. Deep SVDD)."),
     ],
     "notes": "Affiliations: Bosch Center for AI, TU Kaiserslautern, UC Irvine. Venue confirmed by the PDF first page ('Proceedings of the 38th International Conference on Machine Learning, PMLR 139, 2021') and the arXiv journal_ref. The time-series task is detection of whole anomalous sequences (the authors contrast it with per-time-point detection), so time-series-anomaly-detection (points or segments) was not assigned. Co-author M. Kloft is a co-author of the Deep SVDD baseline (Ruff et al., 2018), from the reference list. Number of runs behind the reported standard deviations not found in the text. Section 3.2 is confirmed by its heading. 9 claims: the test-set-as-validation footnote is kept as a separate claim."},

    {"id": "arxiv-2005.02359",
     "title": "Classification-Based Anomaly Detection for General Data",
     "authors": ["Liron Bergman", "Yedid Hoshen"],
     "year": 2020, "venue": "ICLR 2020", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2005.02359"},
     "tasks": ["anomaly-detection"],
     "fam": ["deep-learning"], "par": ["self-supervised"],
     "proposes": ["GOAD: each sample is transformed by M transformations, a feature extractor is trained (center triplet loss plus softmax cross-entropy) so that each transformation's features cluster around its own center, and the anomaly score is the sum of -log of the distance-based (open-set, epsilon-smoothed) probability of predicting the correct transformation",
                  "Random affine transformations T(x, m) = W_m x + b_m to apply transformation-based anomaly detection to tabular (non-image) data"],
     "claims": [
         ("Setting: the paper addresses what it calls the semi-supervised scenario, where the training set contains only normal examples and the test data contain both normal and anomalous examples.",
          "Introduction",
          "In this setting, we have a training set of normal examples (which contains no anomalies)."),
         ("Problem with transformation classification (GEOM): the learned classifier is only valid for samples from the normal training subspace; for anomalies all transformed points fall outside every subspace, which the authors say makes the score have very high variance for anomalies. Using anomaly examples (Outlier Exposure) would fix this but is not possible in general, e.g. for tabular data.",
          "Classification-Based Anomaly Detection",
          "This makes the anomaly score P(m′|T(x, m)) have very high variance for anomalies."),
         ("Transformations and architecture: random affine matrices did not perform competitively on CIFAR-10 because they do not preserve pixel order, which CNNs exploit; as a rule of thumb, fully-connected networks can fully utilize random affine matrices. Image experiments therefore use the geometric transformations of GEOM.",
          "Image Experiments",
          "Random afﬁne matrices did not perform competitively as they are not pixel order preserving, this information is effectively used by CNNs and removing this information hurts performance."),
         ("Tabular protocol (Arrhythmia, Thyroid, KDDCUP99, KDDRev, following Zong et al. 2018): train on 50% of the normal data, evaluate on the other 50% plus all anomalies. OC-SVM, E2E-AE and DAGMM results are copied from Zong et al.; LOF and the feature-bagging autoencoder were computed by the authors. Large-scale experiments are repeated 5 times and small-scale GOAD experiments 500 times (due to high variance).",
          "Tabular Data Experiments",
          "OC-SVM, E2E-AE and DAGMM results are directly taken from those reported by Zong et al. (2018)."),
         ("Threshold for F1: following Zong et al. (2018), the decision threshold is set so that the number of test samples classified as anomalous equals the true number of anomalies in the test set (the top-N_a scores).",
          "Tabular Data Experiments",
          "Following the protocol in Zong et al. (2018), the decision threshold value is chosen to result in the correct number of anomalies e.g. if the test set contains Na anomalies, the threshold is selected so that the highest Na scoring examples are classiﬁed as anomalies."),
         ("Per-dataset choices: on Arrhythmia a linear classifier performed better than deeper networks (which overfit) and early stopping after a single epoch gave the best results; the same held on Thyroid; on KDDCUP99 and KDDRev deep networks are used and results are reported after 25 epochs. How these choices were selected (e.g. a validation set) was not found in the text (searched for validation, held-out, select).",
          "Tabular Data Experiments",
          "Early stopping after a single epoch generated the best results."),
         ("Deep vs shallow: the authors state that deep networks are beneficial for large datasets (particularly full KDDCUP99) but not needed for the smaller ones, indicating deep learning has not benefited the smaller datasets; the approach may be used in a linear setting for performance-critical operations.",
          "Discussion",
          "For performance critical operations, our approach may be used in a linear setting."),
         ("Contamination: although most results assume anomaly-free training data, on KDDCUP99 with X% anomalies added to training GOAD outperforms DAGMM at all impurity levels (figure), and it degrades gracefully on other datasets (Thyroid omitted for lack of anomalies; there, anomalies are split between training contamination and test); the authors say it might therefore be considered for unsupervised settings.",
          "Discussion",
          "Our method might therefore be considered in the unsupervised settings."),
     ],
     "notes": "Affiliation: The Hebrew University of Jerusalem. Venue from the PDF header ('Published as a conference paper at ICLR 2020') and the arXiv comment. Image evaluation is one-class-vs-rest on CIFAR-10 and FashionMNIST with the architecture of Golan & El-Yaniv (2018); GEOM with Dirichlet numbers were copied from that paper. Stated negative result: the closed-set softmax variant was better on KDD (F1 = 0.99) (Discussion). Fewer than 16 auxiliary tasks gave poor results on KDDRev; more tasks reduced F1 variance on small datasets. The paper describes its own setting as semi-supervised (clean normal training data), for which no paradigm tag exists. Section names are used because the extracted headings carry no numbers (appendix A.2-A.4 are numbered)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
