import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_kd_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1803.03635",
     "title": "The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks",
     "authors": ["Jonathan Frankle", "Michael Carbin"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1803.03635"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["The lottery ticket hypothesis: a randomly-initialized dense network contains a subnetwork (a 'winning ticket') that, trained in isolation from its original initialization, matches the original network's test accuracy in at most the same number of iterations",
                  "Identifying winning tickets by (iterative) magnitude pruning with reset: train, prune the smallest-magnitude weights, reset the surviving weights to their values at initialization theta_0, and repeat over n rounds"],
     "claims": [
         ("The lottery ticket hypothesis is stated as: a randomly-initialized dense network contains a subnetwork, initialized such that, trained in isolation it can match the original network's test accuracy after at most the same number of iterations. Formally, with a mask m on the parameters and initialization m ⊙ theta_0, it predicts a mask exists with j' <= j (commensurate training time, measured as the iteration of minimum validation loss), a' >= a (commensurate accuracy) and ||m||_0 << |theta| (fewer parameters).",
          "Section 1",
          "A randomly-initialized, dense neural network contains a subnet-work that is initialized such that—when trained in isolation—it can match the test accuracy of the original network after training for at most the same number of iterations."),
         ("Procedure for identifying winning tickets: randomly initialize f(x; theta_0), train for j iterations, prune p% of the parameters (smallest magnitudes) to create a mask m, and reset the remaining parameters to their values in theta_0. The authors describe the reset to the original initialization as unique to their work. This is one-shot; the paper focuses on iterative pruning, which repeats train-prune-reset over n rounds, each round pruning p^(1/n)% of the surviving weights.",
          "Section 1",
          "Unique to our work, each unpruned connection’s value is then reset to its initialization from original network before it was trained."),
         ("Iterative pruning finds winning tickets that match the original network's accuracy at smaller sizes than one-shot pruning does; in the Lenet experiments the authors add that iteratively pruned tickets are costly to find because of repeated training, whereas one-shot pruning also finds winning tickets without it, and they focus on iterative pruning because their goal is the smallest possible tickets.",
          "Section 1",
          "Our results show that iterative pruning ﬁnds winning tickets that match the accuracy of the original network at smaller sizes than does one-shot pruning."),
         ("Random reinitialization control: keeping the winning ticket's mask but sampling a new initialization theta'_0 ~ D_theta makes the subnetworks perform far worse, which the authors take to mean that structure alone cannot explain a winning ticket's success.",
          "Section 1",
          "When randomly reinitialized, winning tickets perform far worse, meaning structure alone cannot explain a winning ticket’s success."),
         ("Learning-rate sensitivity on deeper networks: for Resnet-18 and VGG-19 on CIFAR10, iterative pruning finds winning tickets only when training uses learning rate warmup (at the original learning rate 0.1 without warmup, iterative pruning did not find winning tickets and performed no better than random reinitialization, Section 4); the authors list explaining why warmup is necessary as future work.",
          "Section 6",
          "On deeper networks (Resnet-18 and VGG-19), iterative pruning is unable to ﬁnd winning tickets unless we train the networks with learning rate warmup."),
         ("Relation to Liu et al. (2019), who find pruned networks trainable when randomly reinitialized: the authors say their VGG-19 experiments confirm this at that level of sparsity (pruned by up to 80%), but that after further pruning initialization matters; they hypothesize that up to a certain sparsity highly overparameterized networks can be pruned, reinitialized and retrained successfully, while beyond it extremely pruned networks only maintain accuracy with fortuitous initialization.",
          "Section 5",
          "We hypothesize that—up to a certain level of sparsity—highly overparameterized networks can be pruned, reinitialized, and retrained successfully; however, beyond this point, extremely pruned, less severely overparamterized networks only maintain accuracy with fortuitous initialization."),
         ("Scale limitation: only vision classification on smaller datasets (MNIST, CIFAR10) is considered; larger datasets such as Imagenet are not investigated because iterative pruning is computationally intensive, requiring training a network 15 or more times consecutively for multiple trials.",
          "Section 6",
          "We only consider vision-centric classiﬁcation tasks on smaller datasets (MNIST, CIFAR10)."),
         ("Hardware limitation: sparse (unstructured magnitude) pruning is the only method used to find winning tickets; although parameter counts fall, the resulting architectures are not optimized for modern libraries or hardware, and structured pruning (which would produce hardware-friendly networks) and non-magnitude pruning are left for future work.",
          "Section 6",
          "Although we reduce parameter-counts, the resulting architectures are not optimized for modern libraries or hardware."),
     ],
     "notes": "Affiliation: MIT CSAIL. Venue: PDF header 'Published as a conference paper at ICLR 2019' and arXiv journal_ref 'ICLR 2019'; year is the first arXiv version (2018). Section numbers are from numbered headings in the PDF (1 Introduction, 2 fully-connected, 3 convolutional, 4 VGG and Resnet, 5 Discussion, 6 Limitations, 7 Related work). Pruning heuristic: layer-wise removal of the lowest-magnitude weights (as in Han et al., 2015), output connections pruned at half the rate (Section 2); Resnet-18 and VGG-19 are pruned globally across all convolutional layers (Section 4). Per-architecture pruning rates, optimizers and iterations are in Figure 2. The 'lottery ticket conjecture' (SGD seeks out and trains a subset of well-initialized weights) is explicitly described as untested. The paper refers to the CIFAR10 residual network as 'Resnet-18'; the later arxiv-1912.05671 (same first and last author) states this was a mistaken name for ResNet-20. Accuracy/early-stopping results are figures (some percentages are in body text) and are not recorded as results. The authors are the originators of the hypothesis evaluated here; follow-up work by the same first author: arxiv-1912.05671, arxiv-2003.03033. Section 3 adds that for Conv-2 and Conv-4 the test accuracy of randomly reinitialized networks at early stopping initially remains steady or improves, which the authors read as structure alone possibly helping at moderate pruning (moved here from c4 because it comes from a different paragraph than the c4 quote)."},

    {"id": "arxiv-1810.05270",
     "title": "Rethinking the Value of Network Pruning",
     "authors": ["Zhuang Liu", "Mingjie Sun", "Tinghui Zhou", "Gao Huang", "Trevor Darrell"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1810.05270", "code": "https://github.com/Eric-mingjie/rethinking-network-pruning"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["An evaluation of the three-stage pruning pipeline (train large, prune, fine-tune) against training the pruned target architecture from random initialization under two budgets: Scratch-E (same epochs) and Scratch-B (same computation budget)",
                  "Viewing automatic structured pruning as implicit architecture search, tested by comparing pruning-obtained architectures with uniformly pruned ones, both trained from scratch"],
     "claims": [
         ("Main finding: for all the structured pruning algorithms examined (four predefined: Li et al. 2017, Luo et al. 2017, He et al. 2017b, He et al. 2018a; two automatic: Liu et al. 2017, Huang & Wang 2018), fine-tuning a pruned model gives only comparable or worse performance than training that model from random initialization; for predefined target architectures the authors say one can skip the pipeline and train the target network directly.",
          "Abstract",
          "For all state-of-the-art structured pruning algorithms we examined, ﬁne-tuning a pruned model only gives comparable or worse performance than training that model with randomly initialized weights."),
         ("Training budget: Scratch-E trains the pruned model for the same number of epochs as the large model and Scratch-B for the same computation (FLOPs) budget; on ImageNet, if the pruned model saves more than 2x FLOPs the epochs are just doubled (less budget than large-model training), and learning-rate decay schedules are extended proportionally. Fine-tuning compute is not counted, which the authors say if anything favors the pruning and fine-tuning pipeline; they found Scratch-E enough in most cases and Scratch-B needed in others.",
          "Section 3",
          "In our experiments, we use Scratch-E to denote training the small pruned models for the same epochs, and Scratch-B to denote training for the same amount of computation budget"),
         ("Unstructured magnitude pruning (Han et al., 2015) behaves differently: on CIFAR, Scratch-B is at least on par with fine-tuning at small prune ratios (<= 80%), but in some cases at a large prune ratio (95%) fine-tuning can outperform training from scratch; on ImageNet, Scratch-B is mostly worse than fine-tuning by a noticeable margin. Suggested (hedged) reasons: difficulty of training highly sparse networks, dataset scale/complexity, or the changed weight distribution.",
          "Section 4.3",
          "On the large-scale ImageNet dataset, we note that the Scratch-B result is mostly worse than ﬁne-tuned result by a noticable margin, despite at a decent accuracy level."),
         ("The authors suggest the contradiction between some of their results and those reported in the literature might be explained by less carefully chosen hyper-parameters, data augmentation schemes, and unfair computation budgets for the baseline approaches.",
          "Introduction",
          "The contradiction between some of our results and those reported in the literature might be explained by less carefully chosen hyper-parameters, data augmentation schemes and unfair computation budget for evaluating baseline approaches."),
         ("Interpretation: inheriting weights from a large model is not necessarily optimal and might trap the pruned model in a bad local minimum; the results suggest the value of automatic structured pruning sometimes lies in identifying efficient structures (implicit architecture search) rather than selecting 'important' weights.",
          "Introduction",
          "identifying efﬁcient struc-tures and performing implicit architecture search, rather than selecting “important” weights."),
         ("Caveat on the architecture-search view: there are cases where architectures obtained by pruning are not significantly more efficient than uniformly pruned ones (all trained from scratch), more likely on modern architectures such as ResNets and DenseNets, whose pruned sparsity patterns are near-uniform across stages; for VGG the pruned patterns beat uniform ones.",
          "Section 5",
          "This phenomenon happens more likely on modern architectures like ResNets and DenseNets."),
         ("Comparison with the lottery ticket hypothesis (CIFAR-10, momentum SGD, initial learning rates 0.1 and 0.01, iterative 20% and one-shot pruning): in the evaluated settings the winning-ticket initialization only helps for unstructured pruning with the small learning rate, which itself yields lower accuracy than the widely used large rate; for structured L1-norm filter pruning it is only on par with random initialization at both rates. Listed setting differences: structured vs unstructured pruning, large modern models vs mostly small shallow networks (< 6 layers), momentum SGD at lr 0.1 vs mostly Adam at lower rates, and ImageNet vs MNIST/CIFAR only. A suggested (hedged) reason is that with a small step size the final weights might stay close to the initialization.",
          "Section 6",
          "To summarize, in our evaluated settings, the winning ticket only brings improvement in the case of unstructured pruning, with small initial learning rate, but this small learning rate yields inferior accuracy compared with the widely-used large learning rate."),
         ("Where pruning and fine-tuning can still be preferable: even if it fails to outperform training from scratch in accuracy, it can be much faster when a pre-trained large model is already given and little or no training budget is available (if the method does not modify large-model training), or when multiple models of different sizes are needed or the desired size is unknown.",
          "Section 7",
          "Even if pruning and ﬁne-tuning fails to outperform the mentioned baselines in terms of accuracy, there are still some cases where using this conventional wisdom can be much faster than training from scratch"),
     ],
     "notes": "Affiliations: UC Berkeley (Liu, Zhou, Darrell), Tsinghua (Sun, Huang). Venue: PDF header 'Published as a conference paper at ICLR 2019' and arXiv comment 'ICLR 2019'; year is the first arXiv version (2018). Section numbers come from numbered headings and the paper's own roadmap (Sections 2-7; 4.1 predefined, 4.2 automatic, 4.3 unstructured). Protocol: same (target model, dataset) pairs as the original papers for six methods; CIFAR runs use 5 random seeds (mean and std reported); training/fine-tuning 160/40 epochs on CIFAR and 90/20 on ImageNet; fine-tuning uses the lowest learning rate of large-model training; for ThiNet and He et al. 2017b only relative accuracy drops are compared because of framework differences (PyTorch vs Caffe). Conflict of interest: one of the evaluated automatic methods, Network Slimming (Liu et al., 2017), is co-authored by Zhuang Liu and Gao Huang (reference list), and DenseNet (Huang, Liu et al.) is among the evaluated architectures; Network Slimming is also the method used in the architecture-search analysis (Section 5). The Lottery Ticket comparison concerns arxiv-1803.03635, whose Discussion in turn says its VGG-19 experiments confirm these findings up to about 80% pruning. Accuracy tables are not recorded as results."},

    {"id": "arxiv-2003.03033",
     "title": "What is the State of Neural Network Pruning?",
     "authors": ["Davis Blalock", "Jose Javier Gonzalez Ortiz", "Jonathan Frankle", "John Guttag"],
     "year": 2020, "venue": "MLSys 2020", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2003.03033", "code": "https://github.com/jjgo/shrinkbench"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["A meta-analysis of 81 pruning papers documenting missing comparisons, dataset/architecture and metric fragmentation, and confounding variables",
                  "A list of best practices for reporting pruning results (compression ratio and theoretical speedup, tradeoff curves with at least 5 operating points, means and standard deviations, identical code for compared methods)",
                  "ShrinkBench: an open-source PyTorch library for standardized pruning evaluation, with global/layerwise magnitude, gradient-magnitude and random pruning baselines"],
     "claims": [
         ("After aggregating results across 81 papers and pruning hundreds of models in controlled conditions, the authors' clearest finding is that the community lacks standardized benchmarks and metrics, to the extent that it is hard to compare pruning techniques or determine how much progress the field has made over three decades.",
          "Abstract",
          "our clearest ﬁnding is that the community suffers from a lack of standardized benchmarks and metrics."),
         ("Missing comparisons in the corpus: a quarter of papers compare to no other pruning method, half compare to at most one other method, and dozens of methods have never been compared to by any subsequent work.",
          "Section 1",
          "For example, a quarter of papers compare to no other pruning method, half of papers compare to at most one other method, and dozens of methods have never been compared to by any subsequent work."),
         ("Dataset/architecture fragmentation: among the 81 papers there are results on 49 datasets, 132 architectures and 195 (dataset, architecture) combinations; even the most common combination (VGG-16 on ImageNet) is used in only 22 of 81 papers, and three of the top six most common combinations involve MNIST, whose results the authors say may be particularly unlikely to generalize.",
          "Section 4.2",
          "Among 81 papers, we found results using 49 datasets, 132 architectures, and 195 (dataset, architecture) combinations."),
         ("Among findings the authors call consistent in the literature: when holding the number of fine-tuning iterations constant, many methods produce pruned models that outperform retraining from scratch with the same sparsity pattern (citing Zhang et al. 2015, Yu et al. 2018, Louizos et al. 2017, He et al. 2017, Luo et al. 2017, Frankle & Carbin 2019), at least with a large enough amount of pruning (citing Suau et al. 2018). The same paragraph lists that many methods outperform random pruning at least for large amounts of pruning, and that uniform layer-wise pruning tends to be worse than allocating parameters across layers or pruning globally.",
          "Section 3.2",
          "Lastly, when holding the number of ﬁne-tuning iterations constant, many methods produce pruned models that outperform retraining from scratch with the same sparsity pattern"),
         ("From reported ImageNet accuracies and compression/speedup levels plotted against unpruned architecture families, the authors conclude that pruning can improve the time or space vs accuracy tradeoff of a given architecture, but that it suggests pruning generally does not help as much as switching to a better architecture, and that pruning is more effective for architectures that are less efficient to begin with.",
          "Section 3.3",
          "Second, it suggests that pruning generally does not help as much as switching to a better architecture."),
         ("Metrics ambiguity: 'Pruned%' sometimes means the fraction remaining and sometimes the fraction removed; 'compression ratio' and 'speedup' are defined inconsistently; FLOPs are measured differently and the formula is most often omitted. The authors found up to a factor of four variation in reported FLOPs for the same architecture and dataset (AlexNet on ImageNet reported as 371, 724 and 1500 MFLOPs by Yang et al. 2017, Choi et al. 2019 and Han et al. 2015).",
          "Section 5.2",
          "We found up to a factor of four variation in the reported FLOPs of different papers for the same architecture and dataset"),
         ("Recommended practices: report the exact architectures, datasets and metrics; use at least three (dataset, architecture) pairs including modern large-scale ones (MNIST and toy models do not count); report both compression ratio (original size / new size) and theoretical speedup (original multiply-adds / new multiply-adds); report Top-1 and Top-5 on ImageNet; report the same metrics for an appropriate control; plot tradeoff curves with at least 5 operating points (e.g. ratios {2, 4, 8, 16, 32}); report means and sample standard deviations; use identical libraries, data loading and code for all compared methods. They also recommend that reviewers demand more rigor.",
          "Section 6",
          "Compression ratio is deﬁned as the original size divided by the new size."),
         ("ShrinkBench baselines: Global Magnitude, Layerwise Magnitude, Global Gradient Magnitude and Layerwise Gradient Magnitude pruning (lowest |weight x gradient| on a batch of inputs), and Random Pruning; the authors note these baselines are not reproductions of the cited methods, only inspired by their heuristics. Using them on over 800 pruned networks, they report that parameter-count and FLOP reductions are correlated differently for each method, so reporting one metric is not sufficient, and that relative method rankings change across models, datasets and compression ratios.",
          "Section 7.2",
          "Note that these baselines are not reproductions of any of these methods, but merely inspired by their pruning heuristics."),
         ("Initial model as confounder: with two ResNet-56 models trained with Adam at learning rates 1e-3 and 1e-4, Global vs Layerwise Magnitude pruning appear better on different models, and reporting change in accuracy does not correct for this: one method can artificially appear better than another by starting from a different model.",
          "Section 7.3",
          "Even when reporting changes, one pruning method can artiﬁcially appear better than another by virtue of beginning with a different model."),
     ],
     "notes": "Affiliation: MIT CSAIL (all authors). Venue: PDF page 1 footer 'Proceedings of the 3rd MLSys Conference, Austin, TX, USA, 2020' and arXiv comment 'Published in Proceedings of Machine Learning and Systems 2020 (MLSys 2020)'. Section numbers are from numbered headings and cross-references (Section 4.5, Section 7). Corpus: 79 pruning papers since 2010 plus LeCun et al. 1990 and Hassibi et al. 1993. Conflict of interest: co-author Jonathan Frankle is first author of arxiv-1803.03635 (Frankle & Carbin, 2019) and Frankle et al. 2019, which are cited among the 'consistent findings' (global pruning, pruned models vs retraining from scratch, magnitude baselines being competitive) and appear as data points (e.g. 'Frankle 2019, ResetToEpoch') in the meta-analysis figures; ShrinkBench is the authors' own library and is evaluated here by them; Blalock et al. 2018 is cited in the compression-ratio discussion. The paper also notes that Liu et al. (2019) and Frankle & Carbin (2019) have circular references to each other that cannot be resolved because of simultaneous revisions (Section 5.1), and names Gale et al. (2019) and Liu et al. (2019) as arguably the only papers that control for confounders by using the same code and averaging enough runs (Section 4.5). A seed effect is quoted in body text: for Global Gradient at compression 16, different seeds gave 0.88 vs 0.61 accuracy (Section 7.3). ShrinkBench accuracy curves are figure-only and not recorded."},

    {"id": "arxiv-1912.05671",
     "title": "Linear Mode Connectivity and the Lottery Ticket Hypothesis",
     "authors": ["Jonathan Frankle", "Gintare Karolina Dziugaite", "Daniel M. Roy", "Michael Carbin"],
     "year": 2019, "venue": "ICML 2020", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1912.05671"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["Instability analysis: train two copies of a network (from initialization or from step k) with different SGD noise and measure the error barrier height along the linear path between the results; the network is stable to SGD noise when the copies are linearly mode connected",
                  "IMP with rewinding: iterative magnitude pruning that rewinds surviving weights to their values at an early iteration k instead of initialization"],
     "claims": [
         ("Definition: the linear interpolation instability of a network to SGD noise is the error barrier height on the linear path between the two trained copies, sup over alpha of E(alpha W1 + (1 - alpha) W2) minus the mean of E(W1) and E(W2). A network is considered stable when instability < 2%, a margin that accounts for noise and matches error increases along paths in Draxler et al. (2018) and Garipov et al. (2018); 30 evenly spaced alpha values are used and instability is averaged over three initializations x three runs.",
          "Section 2",
          "Empirically, we con-sider instability < 2% to be stable; this margin accounts for noise and matches increases in error along paths found by Draxler et al. (2018, Table B.1) and Garipov et al. (2018, Table 2)."),
         ("Unpruned networks: all but the smallest MNIST network (LeNet) are unstable to SGD noise at initialization, but all become stable early in training (3% for ResNet-20 on CIFAR-10 and 20% for ResNet-50 on ImageNet); from then on the outcome of optimization is determined to a linearly connected minimum. For ResNet-50 and Inception-v3, train-set instability is slightly higher, and train-set stability does not occur within the analyzed range for Inception-v3 (Section 3).",
          "Section 1",
          "However, by a point early in training (3% for ResNet-20 on CIFAR-10 and 20% for ResNet-50 on ImageNet), all networks become stable to SGD noise."),
         ("Control for training time: because starting instability analysis at step k also shortens the copies' training to T - k steps, the authors retrain the copies for T steps with the learning rate schedule reset to 0 for ResNet-20 and VGG-16 on CIFAR-10; instability is indistinguishable, indicating that the different numbers of training steps did not play a role.",
          "Section 3",
          "Instability is indistinguishable in both cases, indicating that the different numbers of training steps did not play a role in the earlier results."),
         ("IMP with rewinding: IMP trains to completion, prunes the lowest-magnitude weights globally and rewinds surviving weights to their values at iteration k, run iteratively (pruning 20% per round, as in Frankle & Carbin 2019) or in one shot (used for ImageNet networks for efficiency). Frankle & Carbin only reset to initialization (k = 0); generalizing to any k is a stated contribution, and subnetworks reaching full-network accuracy with k > 0 are called 'matching' rather than winning tickets because they are no longer randomly initialized.",
          "Section 4.2",
          "IMP trains a network to completion, prunes weights with the lowest magnitudes globally, and rewinds the remaining weights back to their values at iteration k (Algorithm 2)."),
         ("Failure of the original lottery ticket procedure at scale: rewinding to step 0, IMP subnetworks of LeNet and of ResNet-20/VGG-16 with lower learning rates or warmup (changes Frankle & Carbin proposed so IMP could find matching subnetworks) are matching, but those of standard ResNet-20, standard VGG-16, ResNet-50 and Inception-v3 are not, and are no more accurate than randomly pruned or reinitialized subnetworks, suggesting neither the structure nor the initialization found by IMP gives an advantage there.",
          "Section 4.3",
          "However, IMP subnetworks of standard ResNet-20, standard VGG-16, ResNet-50, and Inception-v3 are not matching."),
         ("Main finding at the extreme sparsities studied: IMP subnetworks are matching only when they are stable to SGD noise. Subnetworks unstable at k = 0 become stable when rewound later (ResNet-20 and VGG-16 at iterations 500 and 1000; ResNet-50 and Inception-v3 at epochs 5 and 6), and the rewinding points where they become matching closely coincide with those where they become stable. Randomly pruned and reinitialized subnetworks are unstable and non-matching at all rewinding points (LeNet excepted).",
          "Section 4.3",
          "In summary, at these extreme sparsities, IMP subnetworks are matching when they are stable."),
         ("Other sparsities (ResNet-20 and VGG-16 only, due to computational cost; matching = accuracy drop < 0.2%, stable = instability < 2%): above 80.0% / 16.8% weights remaining even random pruning is matching (trivial sparsities); between 80.0%-13.4% / 16.8%-1.2% only IMP subnetworks are matching; below 13.4% / 1.2% IMP subnetworks are not matching at any rewinding iteration considered, though their error still decreases when they become stable, which the authors say potentially suggests a broader relationship.",
          "Section 4.4",
          "This range occurs when fewer than 13.4% and 1.2% of weights remain for ResNet-20 and VGG-16."),
         ("Implication for pruning (hedged): since in larger-scale settings IMP subnetworks only become stable and matching after some training, the authors suggest that pruning at initialization (citing Lee et al. 2019; Wang et al. 2020) may not be the best time and that there is an unexploited opportunity to prune much earlier than methods that sparsify late in or after training. They also state that matching subnetworks are found in larger settings only 'from early in training rather than initialization'.",
          "Section 5",
          "Recent proposals attempt to prune networks at initialization (Lee et al., 2019; Wang et al., 2020), but our results suggest that the best time to do so may be after some training."),
     ],
     "notes": "Affiliations: MIT CSAIL (Frankle, Carbin), Element AI (Dziugaite), University of Toronto / Vector Institute (Roy). Venue: PDF footer 'Proceedings of the 37th International Conference on Machine Learning, Vienna, Austria, PMLR 119, 2020' and arXiv comment 'Published in ICML 2020' (the submission subsumes arXiv:1903.01611); year is the first arXiv version (2019). Section numbers are from numbered headings (2 Preliminaries and Methodology, 3 unpruned networks, 4.1-4.4 lottery tickets, 5 Discussion, 6 Conclusions). Conflict of interest: the first and last authors are the authors of arxiv-1803.03635, whose IMP procedure and lottery ticket hypothesis are re-evaluated and extended here; the 'low' and 'warmup' hyperparameters are adapted from Frankle & Carbin (2019). Table 1 notes that 'Frankle & Carbin mistakenly refer to ResNet-20 as \"ResNet-18\"'. Hyperparameters for VGG-16 standard come from Liu et al. (2019) (arxiv-1810.05270). The Discussion cites follow-ups that use rewinding (Morcos et al. 2019 transfer; Renda et al. 2020 claiming state-of-the-art sparsities), Renda et al. 2020 is co-authored by Frankle and Carbin (reference list: Renda, A., Frankle, J., and Carbin, M.). Instability/error curves are figures and Table 2 accuracies are not recorded as results."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
