import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ci_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1605.03661",
     "title": "Learning Representations for Counterfactual Inference",
     "authors": ["Fredrik D. Johansson", "Uri Shalit", "David Sontag"],
     "year": 2016, "venue": "ICML 2016", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1605.03661"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["treatment-effect-networks", "deep-learning", "linear-models"], "par": ["supervised"],
     "proposes": ["Balancing counterfactual regression: learn a representation Phi(x) that trades off factual prediction error, a nearest-neighbour counterfactual fitting term and a discrepancy distance (imbalance) between the treated and control distributions over Phi, then fit a ridge regression on [Phi(x), t]",
                  "Two instantiations: Balancing Linear Regression (BLR, a sparse simplex-constrained feature re-weighting) and Balancing Neural Network (BNN, a feed-forward net whose first d_r layers form Phi and whose later layers take t as an extra input)",
                  "The News semi-synthetic benchmark (NY Times word counts, simulated device assignment and reader opinion)"],
     "claims": [
         ("Framing: the factual distribution P(x)P(t|x) and the counterfactual distribution P(x)P(not t|x) differ only in the treatment assignment mechanism; in observational studies this mechanism generally depends on x, so predicting counterfactual outcomes requires inference on a distribution different from the training one, which the authors cast as covariate shift, a special case of domain adaptation.",
          "Section 2",
          "The difference between the observed (factual) sample and the sample we must perform inference on lies precisely in the treatment assignment mechanism, P(t|x)."),
         ("Estimands: the individualized treatment effect ITE(x) = Y1(x) - Y0(x) for binary treatment and the average treatment effect ATE = E_x[ITE(x)] (Rubin-Neyman potential outcomes); because only one potential outcome is observed per context, the ITE cannot be known directly.",
          "Section 2",
          "The fundamental problem of causal inference is that only one potential outcome is observed for a given context x:"),
         ("Objective: B(Phi, h) = mean factual absolute error + alpha * disc_H(empirical factual, empirical counterfactual distributions over Phi) + gamma * mean error between the counterfactual prediction and the factual outcome of the nearest neighbour (computed once in input space) in the opposite treatment group; after learning Phi, a final hypothesis is fit by regularized squared loss on the factual data (Algorithm 1).",
          "Section 3",
          "where α, γ > 0 are hyperparameters to control the strength of the imbalance penalties, and disc is the discrepancy measure deﬁned in 4.1."),
         ("Theorem 1 (based on Cortes & Mohri, 2014) assumes a metric input space, Lipschitz potential outcome functions and linear hypotheses (ridge regression) over a fixed representation; its representation-independent term (average cross-group nearest-neighbour distance scaled by the Lipschitz constants) is small when the outcome functions are smooth and treated and control overlap. The authors note (citing Rosenbaum, 2009) that with little overlap causal inference is generally harder.",
          "Section 4",
          "It is well-known that when there is not much overlap between treated and control, causal inference in general is more difﬁcult since the extrapolation from treated to control and vice-versa is more extreme (Rosenbaum, 2009)."),
         ("Limits of the bound: it bounds the relative error of a ridge regression fit on factual outcomes and evaluated on the counterfactual versus one fit on the unobserved counterfactuals, for any fixed Phi, without accounting for how Phi is obtained; one term involves the unknown counterfactual outcomes and can only be upper-bounded by fitting and nearest-neighbour terms.",
          "Section 4",
          "In general however, we cannot directly control its magnitude."),
         ("For linear hypotheses the discrepancy has a closed form that depends on v = p*mu1(Phi) - (1-p)*mu0(Phi), the size-weighted difference between treated and control means in representation space, so minimizing it amounts to matching means in feature space.",
          "Section 4.1",
          "As a consequence, minimizing the discrepancy with linear hypotheses constitutes matching means in feature space."),
         ("Limitation: with variable re-weighting or a neural net with a single linear outcome layer, the hypothesis is linear in [Phi, t] with no interactions between Phi(x) and t, so these models cannot capture heterogeneity of the individual effect; adding interactions (feature expansion or non-linear layers after the concatenation) removes the closed form of the discrepancy.",
          "Section 3.3",
          "A less desirable consequence is that such models cannot capture difference in the individual treatment"),
         ("Model selection: standard hyperparameter selection such as cross-validation is unavailable on real data because counterfactual outcomes are never observed; since all outcomes in the experiments are simulated, the authors generate repeated experiments with different outcome functions and choose hyperparameters once for all models (and baselines) on a held-out set of experiments, which they say is not possible for real-world data.",
          "Section 6",
          "While not possible for real-world data, this approach gives an indication of the robustness of the parameters."),
         ("The BART baseline (BayesTree R package) was run with default parameters without tuning, following Hill (2011); in the results section the authors write that BART's performance on News is likely hurt by the dataset's dimensionality and could improve with hyperparameter tuning.",
          "Section 6",
          "Like (Hill, 2011), we do not attempt to tune the parameters, but use the default."),
     ],
     "notes": "Venue: page 1 footer 'Proceedings of the 33rd International Conference on Machine Learning, New York, NY, USA, 2016' and arXiv comment 'Appeared in ICML 2016'. Section numbers are from numbered headings in the PDF. No explicit unconfoundedness/ignorability or positivity assumption is stated (searched the text for unconfound, ignorab, confound, hidden, overlap; the only overlap mention is the Theorem 1 discussion). The nearest-neighbour term of the objective 'did not improve empirical performance, and was omitted for the BNN models' (Section 6), so the BNN experiments do not use the full objective. Evaluation: IHDP (Hill 2011; 747 subjects, 139 treated, 608 control, 25 covariates, imbalance introduced by removing a subset of the treated, NPCI setting 'A'; 100 repeated experiments for hyperparameter selection and 1000 for evaluation) and the new News dataset (n = 5000 items, 50 LDA topics, vocabulary 3477 words, C = 50, kappa = 10, 50 realizations). Metrics: RMSE of ITE, absolute ATE error, PEHE. Results are in Tables 1-2 and Figure 4 and are not recorded. Open questions listed in the Conclusion: more than one treatment, better optimization, richer discrepancy measures. Overlapping authors with arxiv-1606.03976 (which builds on and criticizes this paper's relative bound) and arxiv-1705.08821."},

    {"id": "arxiv-1606.03976",
     "title": "Estimating individual treatment effect: generalization bounds and algorithms",
     "authors": ["Uri Shalit", "Fredrik D. Johansson", "David Sontag"],
     "year": 2016, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1606.03976"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["treatment-effect-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["A generalization-error bound for ITE estimation: the expected PEHE of a representation Phi and hypothesis h is bounded by the factual treated and control losses plus B_Phi times an integral probability metric (IPM) between the treated and control distributions induced by Phi",
                  "CFR (Counterfactual Regression): a shared representation network with two outcome heads h0, h1, trained on a group-size-weighted factual loss plus alpha times an IPM (MMD or Wasserstein) between treated and control representations; TARNet is the variant with alpha = 0"],
     "claims": [
         ("Estimand: tau(x) = E[Y1 - Y0 | x] = m1(x) - m0(x), called the Individual Treatment Effect (a footnote says it is sometimes known as CATE); under the Consistency assumption the observed outcome is y = Y0 if t = 0 and y = Y1 if t = 1, so only one potential outcome is seen per unit.",
          "Introduction",
          "this is known as the Consistency assumption."),
         ("Identification: the paper assumes 'no hidden confounders', formalized as strong ignorability ((Y1, Y0) independent of t given x, and 0 < p(t = 1|x) < 1 for all x), which is sufficient for tau(x) to be identifiable (proof in the supplement); the authors state that its validity cannot be checked from data.",
          "Introduction",
          "The validity of strong ignorability cannot be assessed from data, and must be determined by domain knowledge and understanding of the causal relationships between the variables."),
         ("Theorem 1: under the conditions of Lemma 1 (one-to-one, twice-differentiable representation Phi; a constant B_Phi such that B_Phi times the per-unit expected loss lies in the IPM function family G) and squared loss, PEHE is bounded by twice the sum of the factual treated and control losses plus B_Phi * IPM_G(treated, control distributions over Phi), minus a variance term; the proof bounds PEHE by factual plus counterfactual loss and the unestimable counterfactual-minus-factual gap by an IPM.",
          "Section 3.2",
          "We therefore bound the difference ϵCF −ϵF using an IPM."),
         ("Gap between theory and algorithm: B_Phi can be made explicit only under further assumptions (for Wasserstein: the loss, Lipschitz constants of p(Y_t|x) and h, and the condition number of the Jacobian of Phi; for MMD: RKHS representability and norms); in the algorithm B_Phi is generally not computed but absorbed into alpha, which makes the objective sensitive to the scaling of Phi, so Phi is normalized by projection or batch normalization with fixed scale.",
          "Section 4",
          "For most IPMs, we cannot compute the factor Bφ in Equation 2, but treat it as part of the hyperparameter α."),
         ("Architecture choice: Johansson et al. (2016) fed the concatenation of Phi and t to a single network; the authors argue this risks losing the influence of t when Phi is high-dimensional, so they use two separate heads h1(Phi) and h0(Phi) on a shared representation, and each sample updates only the head of its observed treatment.",
          "Section 4",
          "When the dimension of Φ is high, this risks losing the inﬂuence of t on h during training."),
         ("Objective: minimize the weighted factual loss (weights w_i = t_i/(2u) + (1-t_i)/(2(1-u)) compensating for treatment group sizes, u the treated proportion) + lambda * model complexity + alpha * empirical IPM between control and treated representations, by SGD on mini-batches; with alpha > 0 this is CFR and with alpha = 0 it is named TARNet.",
          "Section 4",
          "We refer to the model minimizing (3) with α > 0 as Counterfactual Regression (CFR) and the variant without balance regularization (α = 0) as Treatment-Agnostic Representation Network (TARNet)."),
         ("Evaluation: real data rarely have ground-truth effects, so the paper uses semi-synthetic IHDP (Hill, 2011) and the Jobs data (LaLonde, 1986), which has randomized and non-randomized components; both are used for training, but only the randomized component can be used for evaluation (ATT error and a 'policy risk' measure, since PEHE cannot be evaluated on Jobs).",
          "Section 5",
          "This alleviates, but does not solve, the issue of a completely balanced dataset being unsuited for our method."),
         ("Hyperparameter selection: because only one potential outcome is observed, the authors use a nearest-neighbour approximation of PEHE (the observed outcome of the nearest unit in the opposite treatment group as a surrogate counterfactual) for hyperparameter selection on IHDP, the validation objective for early stopping, and validation policy risk on Jobs; the same selection procedure is applied to all methods.",
          "Appendix C.1",
          "Standard methods for hyperparameter selection, such as cross-validation, are not generally applicable for estimating the PEHE loss since only one potential outcome is observed (unless the outcome is simulated)."),
         ("Relation to the authors' earlier work (overlapping authors: Johansson, Shalit, Sontag): the paper builds on Johansson et al. (2016), which bounded the relative error of ridge regression under the reversed treatment assignment; the authors say that relative bound is not informative about the absolute quality of the representation, and here give a bound on the absolute quality.",
          "Section 2",
          "Unfortunately, the relative error bound is not at all informative regarding the absolute quality of the representation."),
     ],
     "notes": "No venue is printed in the arXiv v5 PDF (dated 16 May 2017) and the arXiv comment/journal_ref give none; none recorded. Section numbers are from numbered headings in the PDF; the supplement (proofs, Appendix C) is included in the v5 PDF. Conflict of interest: the paper builds on and compares with BLR and BNN from Johansson et al. (2016), by the same three authors (arxiv-1605.03661); overlapping authors (Shalit, Sontag) also on arxiv-1705.08821. In the RCT setting (t independent of x) the IPM term is 0 and the bound reduces to learning two functions (Introduction). The authors note their theory does not immediately apply to log-loss, which they use for binary outcomes (Section 5). Experiments: IHDP NPCI setting 'A', 1000 realizations, 63/27/10 splits; an imbalance experiment removes controls with probability q by propensity; Jobs uses the LaLonde experimental sample plus PSID comparison group, 10 splits 56/24/20. Results tables/figures not recorded. Open questions in the Conclusion: choosing alpha, confidence intervals, and integrating hidden confounding or instrumental variables. Related work states 'we only deal with the ignorable case'."},

    {"id": "arxiv-1906.02120",
     "title": "Adapting Neural Networks for the Estimation of Treatment Effects",
     "authors": ["Claudia Shi", "David M. Blei", "Victor Veitch"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1906.02120", "code": "https://github.com/claudiashi57/dragonnet"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["treatment-effect-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["Dragonnet: a three-headed network with a shared representation Z(X), two outcome heads Q(0, .) and Q(1, .) and a linear-plus-sigmoid propensity head, trained on squared outcome error plus alpha times treatment cross-entropy, motivated by the sufficiency of the propensity score",
                  "Targeted regularization: an extra parameter epsilon and a penalty beta * mean (y - Q(t, x) - epsilon * (t/g(x) - (1-t)/(1-g(x))))^2 so that the fitted model satisfies the non-parametric (efficient influence curve) estimating equation, with the plug-in estimator psi_treg"],
     "claims": [
         ("Setting: the paper estimates the average effect of a binary treatment from observational data and works throughout in the 'no hidden confounding' setting, where the effect is identified if the covariates contain all confounding variables.",
          "Introduction",
          "We will work in this ‘no hidden confounding’ setting throughout the paper."),
         ("Motivation from the sufficiency of the propensity score (Theorem 2.1, citing Rosenbaum & Rubin 1983): if adjusting for X identifies the ATE, adjusting for g(X) also suffices, so covariate information relevant to the outcome but not the treatment is noise for adjustment and is expected to hurt finite-sample performance; a footnote cautions that with high-variance outcomes and small samples modeling all covariates may help as variance reduction.",
          "Dragonnet",
          "In words: it sufﬁces to adjust for only the information in X that is relevant for predicting the treatment."),
         ("Architecture: a deep net produces a representation Z(X); two 2-hidden-layer heads predict the outcome under control and treatment, and the propensity head is a simple linear map followed by a sigmoid, chosen so that the representation is tightly coupled to the estimated propensity score; removing the propensity head gives (essentially) TARNET (Shalit et al.).",
          "Dragonnet",
          "The simple map forces the representation layer to tightly couple to the estimated propensity scores."),
         ("Theory recalled (citing Chernozhukov et al. and van der Laan & Rose): if the tuple (Q-hat, g-hat, psi-hat) satisfies the efficient-influence-curve estimating equation, psi-hat is asymptotically robust in the double machine-learning sense and efficient; these guarantees require consistent Q-hat and g-hat. The A-IPTW estimator satisfies the equation but, with g-hat in denominators, can be unstable in finite samples.",
          "Targeted Regularization",
          "These asymptotic guarantees hold if (i) ˆQ and ˆg are consistent estimators for the conditional outcome and propensity scores, and (ii) the tuple satisﬁes the non-parametric estimating equation,"),
         ("Targeted regularization: minimizing the objective forces the estimating equation to hold at the optimum of epsilon, so psi_treg has the non-parametric asymptotic properties as long as Q_treg and g-hat are consistent; the authors argue consistency is plausible because the model can set epsilon to 0. Estimators satisfying the equation are also doubly robust (consistent if either the outcome or propensity model is consistent).",
          "Targeted Regularization",
          "Consistency is plausible—even with the addition of the targeted regularization term—because the model can choose to set ϵ to 0, which (essentially) recovers the original training objective."),
         ("Overlap: some ACIC 2018 datasets have overlap violations (P(T = 1|x) very close to 0 or 1 for many x); as a simple heuristic the authors exclude datasets where Dragonnet's held-out treatment accuracy exceeds 90%, leaving 101 datasets.",
          "Experiments",
          "Although overlap violations are an important area of study, this is not our focus and the methods of this paper are not expected to be appropriate in this setting."),
         ("Evaluation design: since ground truth is rarely available, evaluation relies on semi-synthetic data, which must be faithful to the real world; the paper uses IHDP (1000 NPCI realizations, 747 observations, following Shalit et al.) and the IBM ACIC 2018 framework built from linked birth and infant death data (63 data-generating settings; 3 randomly picked datasets of size 5k or 10k per setting).",
          "Experiments",
          "For the conclusions to be useful, the semi-synthetic data must have good ﬁdelity to the real world."),
         ("On IHDP, the de-facto standard benchmark for neural treatment-effect methods, the authors caution that its small sample size and limited simulation settings make conclusions difficult; they also note that the established 63/27/10 split procedure is not clearly motivated for parameter estimation and additionally report estimates using all data for both training and estimation.",
          "Experiments",
          "However, the small sample size and limited simulation settings of IHDP make it difﬁcult to draw conclusions about the methods."),
         ("The non-parametric guarantees are asymptotic; when datasets are split by the error of the baseline Q-only estimator, the authors report that TMLE and targeted regularization behave similarly when the initial estimate is good, while TMLE significantly degrades estimation when it is poor and targeted regularization does not; they say it appears that adapting the whole learning process avoids some bad finite-sample effects but they lack a theoretical explanation.",
          "Experiments",
          "We do not have a satisfactory theoretical explanation for this."),
     ],
     "notes": "No venue is printed in the arXiv v2 PDF (dated 17 Oct 2019) and the arXiv comment/journal_ref are empty; none recorded. Section numbers are not printed as headings in the text dump, so locations use section names (Dragonnet, Targeted Regularization, Experiments). Hyperparameters alpha and beta set to 1; hidden sizes 200 (shared) and 100 (outcome); SGD with momentum, and the authors note 'the choice of optimizer has a signiﬁcant impact on estimation performance' for the baseline and their methods. Data points with estimated propensity outside [0.01, 0.99] are excluded for estimation, and Appendix B reports that the trimming level affects results. Footnote 4 says Shalit et al.'s 'setting A' of NPCI corresponds to setting B in Hill (2011). Table 1 entries for BNN/TARNET/CFR/CEVAE/GANITE are 'as reported in the cited papers' (not re-run). The A-IPTW estimator 'consistently under-performs' the naive estimator in their experiments; on ACIC TMLE 'hurts more than it helps on average'; Dragonnet and targeted regularization help 'about half the time' (text, Experiments). Results tables not recorded. No author-overlap conflict with the compared estimators found; TARNET (Shalit et al., arxiv-1606.03976) is reimplemented as the main baseline."},

    {"id": "arxiv-1705.08821",
     "title": "Causal Effect Inference with Deep Latent-Variable Models",
     "authors": ["Christos Louizos", "Uri Shalit", "Joris Mooij", "David Sontag", "Richard Zemel", "Max Welling"],
     "year": 2017, "venue": "NIPS 2017", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1705.08821"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["treatment-effect-networks", "variational-autoencoders", "deep-learning"],
     "proposes": ["Causal Effect Variational Autoencoder (CEVAE): a latent-variable model p(z) p(x|z) p(t|z) p(y|t, z) with a TARnet-style outcome model, a TARnet-style inference network q(z|x, t, y), and auxiliary networks q(t|x), q(y|x, t) for out-of-sample prediction, trained on the ELBO plus the auxiliary log-likelihoods",
                  "The Twins benchmark: same-sex US twin pairs born 1989-1991 under 2 kg, treatment = being the heavier twin, outcome = first-year mortality, with simulated hidden confounding through gestation length and noisy one-hot proxies"],
     "claims": [
         ("Hidden confounding: if a confounder is hidden or unmeasured, the effect of the intervention on the outcome cannot be estimated in the general case without further assumptions (citing Pearl).",
          "Introduction",
          "On the the other hand, if a confounder is hidden or unmeasured, it is impossible in the general case (i.e. without further assumptions) to estimate the effect of the intervention on the outcome [40]."),
         ("Proxy variables (noisy views X of a hidden confounder Z) are commonly used, but treating them as ordinary confounders is often incorrect and would induce bias (citing prior work; a simple binary example is given in Appendix A).",
          "Introduction",
          "it’s well known [20, 15, 18, 31, 41] that it is often incorrect to treat the proxies X as if they are ordinary confounders, as this would induce bias."),
         ("Prior proxy-based methods are guaranteed to recover the true effect only under strong assumptions: a categorical hidden confounder with a known number of categories, or a linear-Gaussian model; the authors argue the nature of Z (continuous, categorical, mixed or high-dimensional) is not known in practice.",
          "Introduction",
          "In particular, it is assumed that the hidden confounder is either categorical with known number of categories, or that the model is linear-Gaussian."),
         ("Key assumption: the causal model of Figure 1 holds and the joint p(Z, X, t, y) can be approximately recovered from (X, t, y) alone; the authors note this is impossible if the hidden confounder has no relation to the observed variables, and list cases where it is possible (e.g. three independent views of Z). They also note (citing [51]) that certain VAEs can recover a large class of latent-variable models, with the caveat that optimization is not guaranteed to reach the true minimum.",
          "Identification of causal effect",
          "We further assume that the joint distribution p (Z, X, t, y) of the latent confounders Z and the observed confounders X can be approximately recovered solely from the observations (X, t, y)."),
         ("Estimands and identification: ITE(x) = E[y|X = x, do(t = 1)] - E[y|X = x, do(t = 0)] (also called CATE) and ATE = E[ITE(x)]; Theorem 1 states that recovering p(Z, X, t, y) recovers the ITE under the Figure 1 model, by back-door adjustment over Z.",
          "Identification of causal effect",
          "Theorem 1. If we recover p (Z, X, t, y) then we recover the ITE under the causal model in Figure 1."),
         ("Caveat of the VAE approach: little theory is available on when learning with VAEs identifies the true model, though VAEs make substantially weaker assumptions about the data-generating process and the structure of the hidden confounders than prior proxy methods.",
          "Introduction",
          "This has the disadvantage that little theory is currently available to justify when learning with VAEs can identify the true model."),
         ("Because the posterior over z depends on x, t and y, predicting for new subjects requires t and y before inferring z; CEVAE therefore adds auxiliary distributions q(t|x) and q(y|x, t) whose log-likelihoods are added to the variational lower bound, and outcomes under do(t) are computed by averaging over 100 samples from the approximate posterior q(Z|X).",
          "Causal effect variational autoencoder",
          "Notice that for out of sample predictions, i.e. new subjects, we require to know the treatment assignment t along with its outcome y before inferring the distribution over z."),
         ("Twins benchmark construction: 11984 same-sex twin pairs both under 2 kg, 46 covariates; one twin is hidden to simulate an observational study, treatment assignment is based on GESTAT10 (gestation weeks, ordinal 0-9) plus the 45 other features, and proxies are the one-hot GESTAT10 coding replicated 3 times with each bit flipped independently with probability from 0.05 to 0.5 (0.5 meaning no direct information). The authors note other variables (e.g. incompetent cervix) may still be proxies for the confounder.",
          "Binary treatment outcome on Twins",
          "In order to simulate the case of hidden confounding with proxies, we based the treatment assignment on a single variable which is highly correlated with the outcome: GESTAT10, the number of gestation weeks prior to birth."),
         ("Scope limitation: the method does not currently deal with selection bias, which the authors leave to future work.",
          "Introduction",
          "Finally, we note that our method does not currently deal with the related problem of selection bias, and we leave this to future work."),
     ],
     "notes": "Venue: page 1 footer '31st Conference on Neural Information Processing Systems (NIPS 2017), Long Beach, CA, USA' and arXiv comment 'Published as a conference paper at NIPS 2017'. Section headings other than the Introduction are unnumbered in the text dump, so locations use section names. Conflict of interest: Shalit and Sontag co-authored the TARnet/CFR baseline [48] (arxiv-1606.03976) and the BNN baseline [25] (arxiv-1605.03661), and the acknowledgements thank Fredrik D. Johansson for providing the IHDP and Jobs data. Evaluation: IHDP and Jobs are used as existing benchmarks 'where there is no need to model proxies' (Experiments); a toy mixture-of-Gaussians dataset with binary hidden z, and Twins. Architecture follows TARnet: 3 hidden ELU layers, 20-dimensional z, weight decay 1e-4, Adamax with learning rate 0.01, early stopping on the validation lower bound. Qualitative text statements (from figures, not recorded as results): on Twins CEVAE is described as 'much more robust to increasing proxy noise', but at low noise levels 'CEVAE does slightly worse than the other methods' for ATE. The Twins ATE (-2.5%, mortality 18.9% vs 16.4%) is a property of the data. Twins treatment assignment: t ~ Bern(sigmoid(w_o^T x + w_h(z/10 - 0.1))), w_o ~ N(0, 0.1 I), w_h ~ N(5, 0.1)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
