import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

TSFM = ["time-series-foundation-model", "deep-learning"]

SPECS = [
    {"id": "arxiv-2403.07815",
     "title": "Chronos: Learning the Language of Time Series",
     "authors": ["Abdul Fatir Ansari", "Lorenzo Stella", "Caner Turkmen", "Xiyuan Zhang", "Pedro Mercado", "Huibin Shen",
                 "Oleksandr Shchur", "Syama Sundar Rangapuram", "Sebastian Pineda Arango", "Shubham Kapoor",
                 "Jasper Zschiegner", "Danielle C. Maddix", "Hao Wang", "Michael W. Mahoney", "Kari Torkkola",
                 "Andrew Gordon Wilson", "Michael Bohlke-Schneider", "Yuyang Wang"],
     "year": 2024, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2403.07815",
               "code": "https://github.com/amazon-science/chronos-forecasting"},
     "tasks": ["time-series-forecasting"], "fam": TSFM, "par": ["self-supervised"],
     "proposes": ["Chronos (time series tokenized by mean scaling + quantization, trained with existing T5/GPT-2 language-model architectures via cross-entropy)",
                  "KernelSynth synthetic data (Gaussian processes) and TSMixup augmentation"],
     "claims": [
         ("Method: Chronos scales and quantizes time series values into a fixed vocabulary and trains existing transformer language-model architectures on these tokens with the cross-entropy loss.",
          "Abstract",
          "Chronos tokenizes time series values using scaling and quantization into a fixed vocabulary and trains existing transformer-based language model architectures on these tokenized time series via the cross-entropy loss."),
         ("Zero-shot definition: datasets are split into pretraining-only (13), Benchmark I (15; used for both training and in-domain evaluation) and Benchmark II (27; used only for evaluation, i.e. zero-shot).",
          "Datasets",
          "(b) Benchmark I datasets, employed for both training and evaluation, representing an in-domain evaluation (15 datasets); and (c) Bench-mark II datasets, used solely for evaluation, constituting a zero-shot evaluation (27 datasets)."),
         ("Leakage caveat (footnote): the authors acknowledge that strictly preventing leakage would require Benchmark II data to start after the last pretraining observation, but they consider the risk minimal because the datasets share no overlap beyond high-level conceptual categorization.",
          "Results (Benchmark II footnote)",
          "From a rigorous standpoint, to prevent information leakage, the start time of any dataset within this category must be after the timestamp of the last observation from the pretraining dataset and Benchmark I."),
         ("Evaluation protocol: probabilistic forecasts are scored with WQL on 9 quantile levels and point forecasts with MASE (median forecast); per-dataset scores are divided by Seasonal Naive and aggregated with a geometric mean, and failed/timed-out models get relative score 1.",
          "Evaluation Metrics",
          "For each dataset, we compute the relative score of each model as the model’s score divided by the score of a baseline model (here, Seasonal Naive)."),
         ("Baseline tuning: statistical baselines used StatsForecast defaults (with frequency-implied season lengths), and unless otherwise specified baseline implementations kept their default hyperparameters with no dataset-specific or global hyperparameter tuning.",
          "Appendix (Baselines)",
          "Unless otherwise specified, the default hyperparameter configurations provided in baseline implementations were kept as is, and no dataset specific or global hyperparameter tuning was performed."),
         ("Cross-model leakage remark: the authors note that the evaluation setup may have favored Moirai-1.0-R on Benchmark II because many Benchmark II datasets were in Moirai's pretraining corpus.",
          "Results (Benchmark II)",
          "Moirai-1.0-R obtains the best performance after Chronos, although the evaluation setup may have been advantageous for Moirai-1.0-R as many datasets in Benchmark II were part of its pretraining corpus."),
         ("Affiliation: the title page lists AWS AI Labs and Amazon Supply Chain Optimization Technologies (some authors also list universities; two contributed as AWS interns), and the footnote states that three authors hold concurrent Amazon/university appointments and that the paper describes work performed at Amazon.",
          "Title page (footnote)",
          "Hao Wang, Michael W. Mahoney, and Andrew Gordon Wilson hold concurrent appointments at Amazon and their corresponding universities, and this paper describes work performed at Amazon."),
     ],
     "notes": "PDF states: Published in Transactions on Machine Learning Research (10/2024). Chronos uses LM architectures (T5, GPT-2) but the paper reports random initialization works as well as LLM weights, so the large-language-models family tag was not used. Pretraining data (Datasets section): 28 training datasets, about 890K univariate series, approximately 84B observations, plus KernelSynth Gaussian-process synthetic data. Ablation (Analysis of Hyperparameters): the authors report that LLM-weight initialization offers relatively little advantage over random initialization, which they suggest may be preferable. Stated limitations include the bounded tokenization range [-15s, 15s] (overflow / loss of precision) and, as a potential limitation, the inference speed of the larger models compared to task-specific deep learning models."},

    {"id": "arxiv-2510.15821",
     "title": "Chronos-2: From Univariate to Universal Forecasting",
     "authors": ["Abdul Fatir Ansari", "Oleksandr Shchur", "Jaris Küken", "Andreas Auer", "Boran Han", "Pedro Mercado",
                 "Syama Sundar Rangapuram", "Huibin Shen", "Lorenzo Stella", "Xiyuan Zhang", "Mononito Goswami",
                 "Shubham Kapoor", "Danielle C. Maddix", "Pablo Guerron", "Tony Hu", "Junming Yin", "Nick Erickson",
                 "Prateek Mutalik Desai", "Hao Wang", "Huzefa Rangwala", "George Karypis", "Yuyang Wang",
                 "Michael Bohlke-Schneider"],
     "year": 2025, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2510.15821",
               "code": "https://github.com/amazon-science/chronos-forecasting"},
     "tasks": ["time-series-forecasting"], "fam": TSFM, "par": ["self-supervised", "in-context-learning"],
     "proposes": ["Chronos-2 (group attention for in-context learning across related series, variates and covariates)",
                  "multivariatizers: synthetic multivariate data built from univariate generators"],
     "claims": [
         ("Method: Chronos-2 uses a group attention mechanism that enables in-context learning by sharing information across the series in a group (related series, variates of a multivariate series, or targets and covariates).",
          "Abstract",
          "Chronos-2 employs a group attention mechanism that facilitates in-context learning (ICL) through efficient information sharing across multiple time series within a group"),
         ("Leakage on GIFT-Eval: the pretraining corpus was checked not to overlap with GIFT-Eval test portions, but it does partially overlap with the training portions of some GIFT-Eval datasets; for strictly zero-shot results the authors point to a synthetic-data-only variant.",
          "Results (GIFT-Eval)",
          "Nonetheless, the corpus does include partial overlap with the training portions of some GIFT-Eval datasets."),
         ("Zero-shot status on fev-bench: according to the authors, none of the fev-bench datasets or tasks were seen by Chronos-2 during training.",
          "Results (fev-bench)",
          "None of these datasets or tasks were seen by Chronos-2 during training."),
         ("Evaluation practice: on fev-bench, both the baseline results and the imputation strategy for handling data leakage in certain tasks were taken from Shchur et al. (2025).",
          "Results (fev-bench, Table 3 caption)",
          "Baseline results and the imputation strategy for handling data leakage in certain tasks are both taken from Shchur et al. (2025)."),
         ("Baseline scope: only pretrained models and statistical baselines (AutoARIMA, AutoETS, AutoTheta and their ensemble) are compared; task-specific deep learning models are excluded, citing prior studies (GIFT-Eval, Chronos) that found pretrained models comparable or better on average.",
          "Experiments",
          "We compare Chronos-2 only with the aforementioned models and exclude task-specific deep learning models from our evaluation"),
         ("Mixed finding: on the multivariate subset of fev-bench, ICL gave only modest gains over univariate inference, which the authors read as suggesting the benefits of explicit multivariate modeling can be limited; the largest ICL gains were on tasks with covariates.",
          "Improvements with In-context Learning",
          "This suggests that while these tasks involve multiple variates with potentially shared dynamics, the benefits of explicit multivariate modeling can be limited."),
         ("Affiliation: the title page lists Amazon Web Services / Amazon (some authors also list universities; two contributed as AWS interns), and the footnote states that the report describes work performed at Amazon. The compared models include Chronos-Bolt, described in the paper as the latest publicly released version of Chronos.",
          "Title page (footnote)",
          "Hao Wang and Pablo Guerron hold concurrent appointments at Amazon and their corresponding universities, and this report describes work performed at Amazon."),
         ("Zero-shot status on Chronos Benchmark II: according to the authors, none of its datasets were included in the training corpus of Chronos-2.",
          "Results (Chronos Benchmark II)",
          "None of these datasets were included in the training corpus of Chronos-2."),
     ],
     "notes": "PDF header: 'Technical Report of Chronos-2'. Evaluated model: base Chronos-2 with 120M parameters. Training data: multivariate and covariate-informed tasks rely entirely on synthetic data; univariate data mixes selected Chronos and GIFT-Eval pretraining datasets with synthetic generators (TSI, TCM). The fev-bench reference (Shchur et al., 2025) lists authors who are also authors of this report (e.g. Oleksandr Shchur, Abdul Fatir Ansari, Michael Bohlke-Schneider), per the reference list. Stated future work: only numeric and categorical covariates are supported (no text/multimodal inputs). The GIFT-Eval results table caption states that baseline results were taken from the GIFT-Eval leaderboard (Aksu et al., 2024)."},

    {"id": "arxiv-2310.10688",
     "title": "A decoder-only foundation model for time-series forecasting",
     "authors": ["Abhimanyu Das", "Weihao Kong", "Rajat Sen", "Yichen Zhou"],
     "year": 2023, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2310.10688"},
     "tasks": ["time-series-forecasting"], "fam": TSFM, "par": ["self-supervised"],
     "proposes": ["TimesFM (decoder-only patched attention model pretrained on Google Trends, Wiki pageviews, synthetic and public data)"],
     "claims": [
         ("Method: TimesFM pretrains a decoder-style attention model with input patching on a large corpus of real-world and synthetic time series.",
          "Abstract",
          "Our model is based on pretraining a decoder style attention model with input patching, using a large time-series corpus comprising both real-world and synthetic datasets."),
         ("Pretraining data: the bulk comes from Google Trends, Wiki Pageviews and synthetic series; M4, hourly/15-min Electricity, hourly Traffic and the 10-minute Weather dataset of the Informer benchmark were also added.",
          "Pretraining Details",
          "We address this problem by sourcing the bulk of data used to train our models from three major sources: Google trends, Wiki Pageview statistics and synthetic time-series."),
         ("Zero-shot definition: the evaluation dataset groups (Monash, Darts, Informer/ETT) were intentionally held out from pretraining; from the Informer collection only the ETT datasets are used because a few others were used in pretraining.",
          "Empirical Results",
          "These datasets have been intentionally held out from our pretraining data."),
         ("Evaluation protocol: Monash is filtered (following llmtime) to 18 datasets without missing values, scored by MAE scaled by a naive last-value baseline and aggregated with a geometric mean; ETT uses horizons 96 and 192 with context 512 and, following llmtime, only the last test window.",
          "Zero-shot Evaluation",
          "Therefore, following llmtime, we compare all methods on the last test window."),
         ("Contamination remark about a baseline: for the Darts datasets the authors state that data contamination for llmtime (GPT-3) cannot be ruled out, and that ARIMA needed manual seasonality tuning.",
          "Zero-shot Evaluation",
          "Further, since these datasets are used in numerous time series blog posts for illustrative purposes, data contamination for llmtime cannot be ruled out."),
         ("Ablation finding: a PatchTST pretrained on the same data loader to the same FLOPS (PatchTST(ZS)) did not do as well on Monash but performed similarly to TimesFM(ZS) and PatchTST on ETT; the authors call both outcomes expected, citing the pretraining loader's predominant context length of 512 (vs shorter Monash contexts, plus fewer PatchTST iterations at equal FLOPS) and the 512 context used on ETT.",
          "Appendix (Pretraining PatchTST)",
          "On ETT datasets, the PatchTST(ZS) model is performs similarly to TimesFM(ZS) and PatchTST."),
         ("Affiliation: the title page lists all four authors under Google Research (Google Trends, one of the main pretraining sources, is covered in c2).",
          "Title page",
          "Google Research"),
     ],
     "notes": "The 'Google Research' quote is the affiliation line on the title page. The paper reports point forecasts (MAE-based); probabilistic forecasting is listed as future work. Appendix A.1 limitations: little hyper-parameter tuning in pretraining due to cost; no covariate pretraining."},

    {"id": "arxiv-2402.02592",
     "title": "Unified Training of Universal Time Series Forecasting Transformers",
     "authors": ["Gerald Woo", "Chenghao Liu", "Akshat Kumar", "Caiming Xiong", "Silvio Savarese", "Doyen Sahoo"],
     "year": 2024, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2402.02592",
               "code": "https://github.com/SalesforceAIResearch/uni2ts"},
     "tasks": ["time-series-forecasting"], "fam": TSFM, "par": ["self-supervised"],
     "proposes": ["Moirai (masked encoder-based universal forecasting Transformer with multi patch sizes and any-variate attention)",
                  "LOTSA (Large-scale Open Time Series Archive)"],
     "claims": [
         ("Method: Moirai modifies the time series Transformer to address cross-frequency learning, arbitrary numbers of variates and varying distributional properties.",
          "Abstract",
          "To address these challenges, we present novel enhancements to the conventional time series Transformer architecture, resulting in our proposed Masked EncOder-based UnIveRsAl TIme Series Forecasting Transformer (MOIRAI)."),
         ("Pretraining data: LOTSA, over 27B observations across nine domains; the authors report competitive or superior zero-shot performance versus full-shot models.",
          "Abstract",
          "Trained on our newly introduced Large-scale Open Time Series Archive (LOTSA) featuring over 27B observations across nine domains, MOIRAI achieves competitive or superior performance as a zero-shot forecaster when compared to full-shot models."),
         ("In-distribution evaluation: LOTSA includes the Monash archive as a data source; for a large portion of the Monash datasets only the train set is included, and the held-out test sets are used for in-distribution (not zero-shot) evaluation.",
          "Experiments",
          "For a large portion of these datasets, we only include the train set, holding out the test set which we now use for in-distribution evaluation."),
         ("Evaluation-practice remark: the authors say comparing zero-shot methods is made harder by not having a standard held-out test split, making it challenging to collate datasets that none of the models were trained on; in the same paragraph they state that the datasets used for their out-of-distribution evaluation were not included in LOTSA.",
          "Out-of-distribution / Zero-shot Forecasting",
          "Furthermore, the problem of comparing zero-shot methods is exacerbated by not having a standard held-out test split, making it challenging to collate a set of datasets which all the models have not been trained on."),
         ("Tuning protocol (probabilistic forecasting): full-shot baselines were hyperparameter-tuned per dataset on validation CRPS and averaged over five seeds; Moirai itself received inference-time tuning of context length and patch size on validation CRPS. Metrics: CRPS and MSIS with rolling evaluation.",
          "Out-of-distribution / Zero-shot Forecasting",
          "For each dataset and baseline, we perform hyperparameter tuning on a validation CRPS, and report results averaged over five training runs with different seeds."),
         ("Long sequence forecasting protocol: datasets with same-source data in pretraining were omitted (the appendix names the LSF Traffic dataset, omitted because LOTSA includes PeMS-sourced LargeST data); full-shot baseline results were copied from Liu et al. (2023b); Moirai was tuned on average validation MSE.",
          "Out-of-distribution / Zero-shot Forecasting",
          "We evaluate on a subset of the popular long sequence forecasting benchmark (Wu et al., 2021), omitting datasets which have datasets from the same source present in our pre-training data and cannot be considered zero-shot."),
         ("Limitations: little to no hyperparameter tuning due to resource constraints; the multi patch size mapping is somewhat heuristic; limited support for high-dimensional time series.",
          "Limitations & Future Work",
          "Due to resource constraints, little to no hyperparameter tuning was performed – efficient tuning techniques such as µP (Yang et al., 2022a) can be applied."),
     ],
     "notes": "PDF states: Proceedings of the 41st International Conference on Machine Learning (ICML), Vienna, Austria, PMLR 235, 2024. Affiliations on the title page: Salesforce AI Research; School of Computing and Information Systems, Singapore Management University. In long sequence forecasting the authors call the performance/model-size relationship tenuous in that setting while not taking it as strong evidence against scaling. Chronos (arxiv-2403.07815) later remarks that many Chronos Benchmark II datasets were in Moirai's pretraining corpus."},

    {"id": "arxiv-2310.08278",
     "title": "Lag-Llama: Towards Foundation Models for Probabilistic Time Series Forecasting",
     "authors": ["Kashif Rasul", "Arjun Ashok", "Andrew Robert Williams", "Hena Ghonia", "Rishika Bhagwatkar",
                 "Arian Khorasani", "Mohammad Javad Darvishi Bayazi", "George Adamopoulos", "Roland Riachi",
                 "Nadhir Hassen", "Marin Biloš", "Sahil Garg", "Anderson Schneider", "Nicolas Chapados",
                 "Alexandre Drouin", "Valentina Zantedeschi", "Yuriy Nevmyvaka", "Irina Rish"],
     "year": 2023, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2310.08278"},
     "tasks": ["time-series-forecasting"], "fam": TSFM, "par": ["self-supervised"],
     "proposes": ["Lag-Llama (decoder-only transformer using lag features as covariates, univariate probabilistic forecasting)"],
     "claims": [
         ("Method: Lag-Llama is a general-purpose foundation model for univariate probabilistic forecasting built on a decoder-only transformer that uses lags as covariates.",
          "Abstract",
          "We present Lag-Llama, a general-purpose foundation model for univariate probabilistic time series forecasting based on a decoder-only transformer architecture that uses lags as covariates."),
         ("Pretraining data: the pretraining corpus comprises 7,965 univariate series (around 352 million data windows/tokens); it is the pretraining part of a collated collection of 27 datasets in six domains, from which held-out test datasets were also taken.",
          "Datasets",
          "Our pretraining corpus comprises a total of 7, 965 different univariate time series, each of different lengths, when put together, comprising a total of around 352 million data windows (tokens) for our model to train on."),
         ("Zero-shot definition: some datasets from each pretraining domain are held out as unseen test datasets, and datasets from entirely different domains are also set aside; 'domain' is only a grouping label.",
          "Datasets",
          "We leave out a few datasets from each domain for testing the few-shot generalization abilities of the pretrained model, whle using the remaining datasets for pretraining the founda-tion model."),
         ("Evaluation protocol: following Shchur et al. (2023), all reported results are on the last prediction window of each test split.",
          "Appendix (Protocol Details)",
          "Following typical evaluation setups (Shchur et al., 2023), all results reported in the paper are on the last prediction window of the test splits defined in App. §A."),
         ("Baseline training: supervised baselines (via AutoGluon and others) were trained with the same setup as Lag-Llama fine-tuning; a dataset-specific hyperparameter search for baselines was not found in the text (Lag-Llama itself used a 100-configuration random search on pretraining validation loss).",
          "Appendix (Protocol Details)",
          "We use the same setup as fine-tuning Lag-Llama, for all supervised baselines that we produce results for in the paper."),
         ("Main empirical claim: zero-shot Lag-Llama is comparable to baselines, and after fine-tuning it reaches the best average rank among the compared methods on the unseen datasets.",
          "Zero-Shot & Finetuning Performance on New Data",
          "In the zero-shot setting, Lag-Llama achieves comparable performance to all baselines, with an average rank of 6.714."),
         ("In-distribution caveat: on its pretraining datasets Lag-Llama is not the best model on each dataset, which the authors attribute to its training budget being split across all pretraining datasets.",
          "Appendix (Results on the Pretraining Datasets)",
          "This is reflected in the results, as Lag-Llama is not the best performing model in each dataset."),
         ("Metrics: CRPS computed from 100 empirical samples, averaged over the prediction horizon and all series of a dataset; the average rank across datasets is also reported.",
          "Inference and Model Evaluation",
          "We use 100 empirical samples and report the CRPS averaged over the prediction horizon and across all the time series of a dataset."),
     ],
     "notes": "Affiliations on the title page: Morgan Stanley; ServiceNow Research; Université de Montréal; Mila; McGill University. Table 3 lists ETT H1, ETT H2, ETT M1 in the pretraining corpus and ETT M2 among the unseen datasets (same source, different dataset). No code URL found in the PDF text."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): time-series foundation models and forecasting; carded by a subagent. Results tables not recorded; claims only.")
