import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1903.08850",
     "title": "Stochastic Optimization of Sorting Networks via Continuous Relaxations",
     "authors": ["Aditya Grover", "Eric Wang", "Aaron Zweig", "Stefano Ermon"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1903.08850", "code": "https://github.com/ermongroup/neuralsort"},
     "tasks": ["image-classification"],
     "fam": ["differentiable-sorting", "deep-learning"], "par": ["supervised"],
     "proposes": ["NeuralSort: relaxation of the sort operator's permutation-matrix output to unimodal row-stochastic matrices (softmax over a pairwise-difference construction, temperature tau)",
                  "reparameterized gradient estimator for Plackett-Luce distributions over permutations (Gumbel-perturbed scores + NeuralSort)"],
     "claims": [
         ("Problem statement: the sorting operator is non-differentiable with respect to its inputs, which prevents end-to-end gradient-based optimization of pipelines that contain a sort.",
          "Abstract",
          "However, the sorting operator is non-differentiable with respect to its inputs, which prohibits end-to-end gradient-based optimization."),
         ("Contribution: NeuralSort relaxes the output of sorting from permutation matrices to unimodal row-stochastic matrices (rows sum to one, each row has a distinct argmax), so a hard permutation can still be read off by a row-wise argmax.",
          "Abstract",
          "In this work, we propose NeuralSort, a general-purpose continuous relaxation of the output of the sorting operator from permutation matrices to the set of unimodal row-stochastic matrices, where every row sums to one and has a distinct arg max."),
         ("Complexity: the relaxation needs O(n^2) operations (pairwise absolute differences), versus O(n log n) for the best known sorting algorithms; the authors add that in practice it is highly parallelizable on GPUs.",
          "NeuralSort: the relaxed sorting operator",
          "The relaxation requires O(n2) operations to compute As, as opposed to the O(n log n) overall complexity for the best known sorting algorithms."),
         ("Guarantee and its assumption: for every temperature the row-wise argmax of the relaxed matrix equals sort(s); convergence of the relaxed matrix to the exact permutation matrix as temperature goes to 0 is stated almost surely under the assumption that the entries are drawn independently from an absolutely continuous distribution (so ties have probability zero).",
          "NeuralSort: the relaxed sorting operator (Theorem 4)",
          "If we assume that the entries of s are drawn independently from a distribution that is absolutely continuous w.r.t. the Lebesgue measure in R, then the following convergence holds almost surely:"),
         ("Approximation trade-off: lower temperature gives a tighter approximation, but the variance of the gradient estimates is typically lower at higher temperatures.",
          "NeuralSort: the relaxed sorting operator",
          "In practice however, the trade-off is in the variance of these estimates, which is typically lower for larger temperatures."),
         ("Evaluation protocol (large-MNIST sorting, n in {3, 5, 7, 9, 15}): the temperature of both the Sinkhorn-based baselines and NeuralSort was tuned over {1, 2, 4, 8, 16} by best validation accuracy on predicting entire permutations; all methods share the same CNN and are trained with a cross-entropy loss against the ground-truth permutation matrix.",
          "Appendix D.1 (Sorting handwritten numbers, Hyperparameters)",
          "We tuned this hyperparameter on the set {1, 2, 4, 8, 16} by picking the model with the best validation accuracy on predicting entire permutations"),
         ("Main empirical claim (sorting large-MNIST sequences): both NeuralSort variants significantly outperform the vanilla row-stochastic, Sinkhorn and Gumbel-Sinkhorn baselines for all sequence lengths n considered.",
          "Experiments (Sorting handwritten numbers)",
          "Table 1 demonstrates that the approaches based on the proposed sorting relaxation signiﬁcantly outperform the baseline approaches for all n considered."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2019. Affiliation: Stanford University (title page). Tasks as stated: (1) sorting sequences of 'large-MNIST' images (main text: concatenations of 4 MNIST digits; Appendix D.1 instead describes a '5-digit large-MNIST image' of 140x28 for the sorting experiment and D.2 says quantile regression used 4-digit 'instead of 5-digit' numbers -- the text is internally inconsistent here) using only ground-truth permutations as supervision (metric: proportion of fully correct permutations, following Mena et al. 2018, plus proportion of correct individual ranks); (2) median (50th quantile) regression over such sequences; (3) differentiable kNN on MNIST, Fashion-MNIST, CIFAR-10 (no augmentation) vs kNN in pixel/PCA/autoencoder spaces and a plain CNN; kNN hyperparameters (temperature {1,16,64}, lr, k in {1,3,5,9}) chosen by best evaluation loss, and the authors 'suspect that accuracy improvements can be made by a more expensive hyperparameter search'. The authors hedge that the poor performance of Sinkhorn baselines is 'partly because these methods were designed and evaluated for matchings' (Experiments). REINFORCE-based estimators were 'empirically observed to be worse than almost all baselines' (Appendix D). Cross-paper (reviewer comparison of the tables, not stated in any of the texts): Cuturi et al. (arxiv-1905.11885, Table 1, 10 runs, the NeuralSort authors' code, 100 epochs) report NeuralSort exact-match values below this paper's own Table 1 at every n, with the gap growing with n; Petersen et al. (arxiv-2105.04019) copy Cuturi's rows. Neither later paper comments on the discrepancy, and training budgets/inputs may differ (see the digit-count inconsistency above), so the numbers should not be read as a failed reproduction. Task tag image-classification covers only the kNN experiment; no existing task tag covers sorting supervision."},

    {"id": "arxiv-2002.08871",
     "title": "Fast Differentiable Sorting and Ranking",
     "authors": ["Mathieu Blondel", "Olivier Teboul", "Quentin Berthet", "Josip Djolonga"],
     "year": 2020, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2002.08871", "code": "https://github.com/google-research/fast-soft-sort/"},
     "tasks": ["image-classification", "tabular-regression"],
     "fam": ["differentiable-sorting", "deep-learning", "linear-models"], "par": ["supervised"],
     "proposes": ["soft sorting and ranking operators defined as regularized (quadratic or entropic) projections onto the permutahedron, computed exactly via reduction to isotonic optimization (pool adjacent violators) in O(n log n) time and differentiated in O(n)"],
     "claims": [
         ("Problem statement: sorting is piecewise linear (differentiable almost everywhere but with many kinks), while ranking is piecewise constant, so its derivatives are null or undefined and block backpropagation.",
          "Introduction",
          "As piecewise constant functions, ranks are unfortunately much more problematic than sorting: their derivatives are null or undeﬁned, preventing gradient backpropagation."),
         ("Contribution and stated complexity: the paper claims the first differentiable sorting and ranking operators with O(n log n) time and O(n) space complexity, and says prior differentiable proxies do not achieve O(n log n).",
          "Abstract",
          "In this paper, we propose the ﬁrst differentiable sorting and ranking operators with O(n log n) time and O(n) space complexity."),
         ("Relaxation used: sorting and ranking are written as linear programs over the permutahedron (convex hull of permutations); adding strongly convex regularization turns them into projections, which reduce to isotonic optimization.",
          "Abstract",
          "We achieve this feat by constructing differentiable operators as projections onto the permutahedron, the convex hull of permutations, and using a reduction to isotonic optimization."),
         ("Exactness and where the O(n log n) comes from: the isotonic subproblems are solved exactly by pool adjacent violators in O(n) time, so no iteration count or precision level must be chosen (unlike Sinkhorn); the overall O(n log n) is due to first sorting the input vector, which the projection requires.",
          "Fast computation and differentiation",
          "This means that we do not need to choose a number of iterations or a level of precision, unlike with Sinkhorn."),
         ("Comparison with prior relaxations as stated by this paper: Taylor et al. take O(n^3), Qin et al. O(n^2) (refined by Grover et al. with unimodal row-stochastic matrices), and Cuturi et al.'s optimal transport method differentiates through Sinkhorn iterates at O(Tmn) cost, where T is the number of Sinkhorn iterations and m a hyperparameter trading cost for precision (Blondel et al. state that convergence to hard sort/ranks is only guaranteed if m = n).",
          "Introduction",
          "Their method is based on differentiating through the iterates of the Sinkhorn algorithm (Sinkhorn & Knopp, 1967) and costs O(Tmn) time, where T is the number of Sinkhorn iterations"),
         ("Top-k classification (reproducing Cuturi et al.'s CIFAR-10/CIFAR-100 experiment with the same vanilla CNN, Adam step 1e-4, k = 1, 12 runs): the proposed soft ranks reach accuracy comparable to the OT formulation while being significantly faster.",
          "Experiments (Top-k classification loss function)",
          "On both CIFAR-10 and CIFAR-100, our soft rank formulations achieve comparable accuracy to the OT formulation, though signiﬁcantly faster, as we elaborate below."),
         ("Caveat on runtime: in the 600-epoch CIFAR-100 training, the proposed operators were faster than OT but slower than the O(n^2) All-pairs baseline, which the authors attribute to All-pairs being efficient on GPU at n = 100 while their PAV implementation runs on CPU.",
          "Experiments (Top-k classification loss function)",
          "While our soft operators are several hours faster than OT, they are slower than All-pairs, despite its O(n2) complexity."),
     ],
     "notes": "PDF states: Proceedings of the 37th International Conference on Machine Learning, PMLR 119, 2020. Affiliation: Google Research, Brain team (all authors). Asymptotics (Proposition 2): soft operators are differentiable a.e. and order-preserving for every epsilon > 0, converge to hard sort/rank as epsilon -> 0 for inputs without ties, and collapse to a constant vector as epsilon -> infinity; Appendix B.3 gives an epsilon below which they equal the hard operators exactly. On tuning epsilon: not necessary for label ranking, but for top-k classification squashing scores to [0,1] and tuning epsilon 'is important, confirming the empirical finding of Cuturi et al. (2019)'. Runtime experiment: random N(0,1) score vectors, n from 100 to 5000, batch of 128, Intel Xeon W-2135 + GTX 1080 Ti; OT and All-pairs run out of GPU memory for large n. Label ranking: 21 datasets (Hullermeier et al. 2008; Cheng et al. 2009), linear models, two 10-fold runs with internal 5-fold CV grid search; ablation drops the soft rank layer. Soft least trimmed squares: LIBSVM datasets, synthetic label outliers on training labels only, 5-fold CV for k, epsilon (and Huber tau), 10 train-test splits; hard LTS 'worked well on all datasets'. Petersen et al. (arxiv-2105.04019) evaluate this method ('Fast Sort & Rank') on four-digit MNIST/SVHN sorting with an MSE loss on ranks because it does not produce permutation matrices, and confirm it is the fastest method for large n in their runtime table."},

    {"id": "arxiv-1905.11885",
     "title": "Differentiable Ranks and Sorting using Optimal Transport",
     "authors": ["Marco Cuturi", "Olivier Teboul", "Jean-Philippe Vert"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1905.11885"},
     "tasks": ["image-classification", "tabular-regression"],
     "fam": ["differentiable-sorting", "deep-learning"], "par": ["supervised"],
     "proposes": ["Kantorovich (K-) and Sinkhorn (S-) rank and sort operators: sorting cast as optimal transport to an increasing target measure with m (possibly != n) weighted points, made differentiable by entropic regularization and Sinkhorn iterations",
                  "soft top-k/0-1 classification loss and soft quantile operator for least quantile regression"],
     "claims": [
         ("Problem statement: sorting outputs the sorted values (piecewise linear) and the permutation/ranks (integer-valued), neither of which is differentiable.",
          "Abstract",
          "Indeed, sorting procedures output two vectors, neither of which is differentiable: the vector of sorted values is piecewise linear, while the sorting permutation itself (or its inverse, the vector of ranks) has no differentiable properties to speak of, since it is integer-valued."),
         ("Relation to sorting: sorting is viewed as an optimal assignment of the n values to any increasing family of n target values (the introduction notes this OT result holds 'pending a simple condition on the matching cost'); the paper generalizes this to optimal transport targets with m weighted points.",
          "Abstract",
          "Our proxy builds upon the fact that sorting can be seen as an optimal assignment problem, one in which the n values to be sorted are matched to an auxiliary probability measure supported on any increasing family of n target values."),
         ("Relaxation and cost: the OT problem is entropically regularized and solved by Sinkhorn iterations at O(nm l) operations, l being the number of iterations to converge (the paper adds that m can be as small as 3 in some applications and l rarely exceeds 100 in its settings).",
          "Introduction",
          "To recover tractable and differentiable operators, we regularize the OT problem and solve it using the Sinkhorn algorithm [10], at a cost of O(nmℓ) operations, where ℓis the number of Sinkhorn iterations needed for the algorithm to converge."),
         ("Approximation trade-off: smaller regularization epsilon brings the outputs closer to the true ranks and sorted values (larger epsilon collapses them toward averages); the authors caution that very small epsilon brings back the differentiability problems of hard sorting.",
          "The Sinkhorn Ranking and Sorting Operators",
          "the smaller ε is, the closer the Sinkhorn operator’s output is to the original vectors of ranks and sorted values"),
         ("Evaluation protocol for top-k (k = 1) classification on CIFAR-10/CIFAR-100 with a vanilla CNN and ResNet18: fixed epsilon and tolerance, squared-distance cost, Adam with step 1e-4; the comparison is against cross-entropy (Figures 4-5, 12 runs).",
          "Learning with Smoothed Ranks and Sorts",
          "We used ε = 10−3, η = 10−3, a squared distance cost h(u) = u2 and a stepsize of 10−4 with the ADAM optimizer."),
         ("Comparison with NeuralSort on its large-MNIST sorting benchmark (same network architecture, the NeuralSort authors' code, 100 epochs, epsilon = 0.005, Table 1 averaged over 10 runs): the table caption states the OT method performs better than NeuralSort for all sorting tasks, while the running text says it performs on par.",
          "Learning with Smoothed Ranks and Sorts (Table 1)",
          "Our method performs better than the method presented in [18] for all the sorting tasks, with the exact same network architecture."),
         ("Least quantile regression: the soft quantile operator gives overall better quantile errors on the training set (the stated main goal) but comparable test/MSE errors; the caption hedges that the training gain may be due to a smoothed optimization landscape.",
          "Learning with Smoothed Ranks and Sorts",
          "We notice that our algorithm reaches overall better quantile errors on the training set—this is our main goal—but comparable test/MSE errors."),
     ],
     "notes": "PDF states: 33rd Conference on Neural Information Processing Systems (NeurIPS 2019). Affiliation: Google Research, Brain Team (all authors). Unregularized Kantorovich operators are said to be costly (O(nm(n+m) log(nm))) and still non-differentiable (Section 2 text). The paper relates prior soft ranks: Taylor et al. O(n^3), Qin et al. O(n^2) pairwise logistic, Grover et al. (NeuralSort) unimodal row-stochastic on the same pairwise matrix, and says its m != n targets are a departure from methods requiring pairwise comparisons. The MNIST sorting text says 'We use 100 epochs, and confirm experimentally that S-sort performs on par with their neural-sort function' (epsilon = 0.005), which is weaker than the Table 1 caption. Reviewer comparison (not stated in this paper): the NeuralSort rows in this paper's Table 1 are lower than those in Grover et al.'s own Table 1 (arxiv-1903.08850) at every n, with the gap growing with n, and Grover et al.'s own NeuralSort values for n >= 5 are also higher than this paper's OT row; the text says only that the NeuralSort authors' code was used with 100 epochs, and does not discuss the difference, so setups may differ. Least quantile regression uses datasets from Romano et al. (conformalized quantile regression) with a 2-hidden-layer NN, baseline = gradient step on the empirical quantile point. Conclusion (open questions): cost function, target vector and squashing strongly shape differentiability for epsilon > 0; 'empirical findings suggest' whitening and squashing into [0,1] is crucial for numerical stability and consistent gradients."},

    {"id": "arxiv-2105.04019",
     "title": "Differentiable Sorting Networks for Scalable Sorting and Ranking Supervision",
     "authors": ["Felix Petersen", "Christian Borgelt", "Hilde Kuehne", "Oliver Deussen"],
     "year": 2021, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2105.04019", "code": "https://github.com/Felix-Petersen/diffsort"},
     "tasks": ["image-classification"],
     "fam": ["differentiable-sorting", "deep-learning"], "par": ["supervised"],
     "proposes": ["differentiable odd-even and bitonic sorting networks (min/max conditional swaps relaxed with logistic-sigmoid softmin/softmax) producing a relaxed permutation matrix",
                  "activation replacement trick (ART) against vanishing gradients and blurring in deep relaxed sorting networks"],
     "claims": [
         ("Contribution and relation to classical sorting: classical sorting networks (fixed, data-oblivious compare-and-swap structures; odd-even and Batcher's bitonic sorter) are made differentiable by relaxing their pairwise conditional swap operations.",
          "Abstract",
          "For that, we propose differentiable sorting networks by relaxing their pairwise conditional swap operations."),
         ("Why sorting networks are non-differentiable: they use min and max operators for the conditional swaps, which the paper relaxes with softmin/softmax.",
          "Introduction",
          "Sorting networks are conventionally non-differentiable as they use min and max operators for conditionally swapping elements."),
         ("Stated complexity: the differentiable odd-even network runs in O(n^3) and the differentiable bitonic network in O(n^2 (log n)^2), with the layer-wise permutation-matrix product computed as a sparse multiplication.",
          "5.5 Runtime and Memory Analysis",
          "The asymptotic runtime of differentiable odd-even sort is in O(n3) and for bitonic sort the runtime is in O(n2(log n)2)."),
         ("Runtime comparison with other relaxations: for large n the authors empirically confirm FastRank (Blondel et al.) is the fastest method, partly because it outputs only ranks/sorted values rather than differentiable permutation matrices, which they say are necessary for their cross-entropy objective.",
          "5.5 Runtime and Memory Analysis",
          "For large n, we empirically conﬁrm that FastRank (Blondel et al., 2020) is the fastest method, i.a., because it produces only output ranks / sorted output values and not differentiable permutation matrices."),
         ("Evaluation protocol caveat: in the four-digit MNIST comparison, the NeuralSort and Optimal Transport rows are copied from Cuturi et al. rather than rerun (same CNN architecture; averaged over 5 runs for the new rows).",
          "5.1 Sorting and Ranking Supervision (Table 1 caption)",
          "The ﬁrst three rows are duplicated from Cuturi et al. (2019)."),
         ("Evaluation protocol caveat: Blondel et al.'s Fast Sort & Rank was trained with a mean-squared-error loss on ranks, because it does not produce differentiable permutation matrices (the proposed method uses a cross-entropy loss on relaxed permutation matrices).",
          "Appendix B.3 (Fast Sort & Rank)",
          "To evaluate the fast sorting and ranking method by Blondel et al. (2020), we used the mean-squared-error loss between predicted and ground truth ranks as this method does not produce differentiable permutation matrices."),
         ("Main empirical claim (four-digit MNIST sorting benchmark of Grover et al. / Cuturi et al., n in {3, 5, 7, 9, 15}): the authors state the odd-even network outperforms current methods on all metrics and input set sizes; the NeuralSort and OT figures it is compared with are the rows copied from Cuturi et al.",
          "5.1.1 Results (Comparison to State-of-the-Art (MNIST))",
          "Our approach outperforms current methods on all metrics and input set sizes."),
     ],
     "notes": "PDF states: Proceedings of the 38th International Conference on Machine Learning, PMLR 139, 2021. Affiliations: University of Konstanz, University of Salzburg, University of Frankfurt, MIT-IBM Watson AI Lab (title page). Benchmarks: four-digit MNIST sorting supervision (following Grover et al. and Cuturi et al.) and SVHN multi-digit images; metrics exact match (EM), element-wise correct ranks (EW), and EM at n = 5 (EM5) because EM becomes unreliable as n grows. Training: Adam lr 10^-3.5, up to 10^6 steps, lambda = 0.25 fixed for all n (authors note higher accuracy is possible by optimizing lambda per n), steepness tied to the number of layers. Scalability: bitonic networks trained on up to n = 1024 (10^4 steps, steepness values {30,...,40}, lambda 0.4); the abstract claims stable training on input sets of up to 1024 elements, and the authors suggest prioritizing larger n over larger batch size. ART: without it, networks up to 21 layers (bitonic n <= 64) work with moderate steepness; for more layers ART becomes necessary (Section 4.1 text). Top-k (k = 1) on CIFAR-10/100 with ResNet18 and a vanilla CNN: Softmax CE and the differentiable top-k operator 'perform similar'. Related work notes that learned sorters (NTM, Vinyals et al. set2seq, Gumbel-Sinkhorn) 'learn to sort, while sorting networks and differentiable sorting functions sort provably correct'. Sorting networks background: bitonic O(log^2 n) layers; AKS O(log n) parallel time, but its constants are unknown and 'optimistic approximations' put it faster than bitonic only for n >> 10^80 (Related work). Reviewer comparison (not stated in this paper): Grover et al.'s own Table 1 (arxiv-1903.08850) reports NeuralSort exact-match values higher than the copied rows, and at n = 15 higher than the odd-even network's value here, so the 'outperforms on all metrics' claim depends on the copied baseline numbers; setups may differ."},

    {"id": "arxiv-1506.03134",
     "title": "Pointer Networks",
     "authors": ["Oriol Vinyals", "Meire Fortunato", "Navdeep Jaitly"],
     "year": 2015, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1506.03134"},
     "tasks": ["algorithm-learning"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["Pointer Network (Ptr-Net): LSTM encoder-decoder whose content-based attention distribution over input positions is used directly as the output (a pointer), giving an output dictionary whose size equals the input length"],
     "claims": [
         ("Contribution: instead of using attention to blend encoder states into a context vector, Ptr-Net uses the attention distribution itself as a pointer that selects an input element as the output, so outputs are positions in the input (e.g. permutations or subsets of the input).",
          "Abstract",
          "It differs from the previous attention attempts in that, instead of using attention to blend hidden units of an encoder to a context vector at each decoder step, it uses attention as a pointer to select a member of the input sequence as the output."),
         ("Motivation: problems whose output dictionary size depends on the input length, such as sorting variable-sized sequences and various combinatorial optimization problems, cannot be trivially handled by sequence-to-sequence models or Neural Turing Machines.",
          "Abstract",
          "Problems such as sorting variable sized sequences, and various combinatorial optimization problems belong to this class."),
         ("Sorting is not among the evaluated tasks: the paper lists applying Ptr-Net to sorting as future work.",
          "Conclusions",
          "Future work will try and show its applicability to other problems such as sorting where the outputs are chosen from the inputs."),
         ("Evaluated tasks: learning approximate solutions, from input-output examples alone, to planar convex hull, Delaunay triangulation and planar symmetric TSP.",
          "Abstract",
          "We show Ptr-Nets can be used to learn approximate solutions to three challenging geometric problems – ﬁnding planar convex hulls, computing Delaunay triangulations, and the planar Travelling Salesman Problem – using training examples alone."),
         ("Length generalization (convex hull): a single model trained on lengths 5 to 50 extrapolates to lengths never seen in training (tested up to n = 500), whereas the LSTM baselines must be retrained for each n.",
          "Empirical Results (Convex Hull)",
          "More impressive is the fact that the model does extrapolate to lengths that it has never seen during training."),
         ("Limitation of length generalization (TSP): trained on optimal tours with 5 to 20 cities, the model is near perfect at n = 25 and good at n = 30 but appears to break at 40 and beyond; the authors contrast this with the factor-of-10 generalization on convex hull and suggest that the underlying algorithms being of far greater complexity than O(n log n) could explain it.",
          "Empirical Results (Travelling Salesman Problem)",
          "The results are virtually perfect for n = 25, and good for n = 30, but it seems to break for 40 and beyond (still, the results are far better than chance)."),
         ("Evaluation protocol: no extensive architecture or hyperparameter search was done for Ptr-Net; virtually the same architecture was used for all experiments and datasets.",
          "Empirical Results (Architecture and Hyperparameters)",
          "No extensive architecture or hyperparameter search of the Ptr-Net was done in the work presented here, and we used virtually the same architecture throughout all the experiments and datasets."),
     ],
     "notes": "Affiliations: Google Brain (Vinyals, Jaitly) and UC Berkeley Department of Mathematics (Fortunato) (title page). Data: planar point sets sampled uniformly in [0,1]^2, 1M training pairs; single-layer LSTM with 256 or 512 hidden units, SGD lr 1.0, batch 128. TSP labels: exact Held-Karp O(2^n n^2) up to n = 20; for larger n approximate solvers A1, A2 (O(n^2)) and A3 (Christofides, within 1.5x of optimal) are used as training targets; Ptr-Net trained on the worst solver's (A1) outputs outperforms A1. For TSP, beam search was constrained to valid tours because for n > 20 at least 10% of instances would otherwise produce no valid tour. The paper states attention-based decoding costs O(n^2) at inference and that Ptr-Net 'implements an O(n^2) algorithm'. Convex hull errors mostly come from aligned points; input order at inference affects performance (Empirical Results). Delaunay triangulation: no exactly correct triangulation at n = 50 (triangle coverage only). Baselines: LSTM seq2seq and LSTM with input attention, which must be trained on the same n they are tested on."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): classical algorithms (sorting, binary search, greedy) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
