import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tree_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1603.02754",
     "title": "XGBoost: A Scalable Tree Boosting System",
     "authors": ["Tianqi Chen", "Carlos Guestrin"],
     "year": 2016, "venue": "KDD 2016", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1603.02754"},
     "tasks": ["tabular-classification"],
     "fam": ["gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["XGBoost: an open-source, end-to-end scalable tree boosting system",
                  "Sparsity-aware split finding: a learned default direction per tree node for missing/absent entries, visiting only non-missing entries",
                  "Weighted quantile sketch for proposing candidate splits in the approximate algorithm, with second-order gradients as instance weights",
                  "Cache-aware column block structure, block compression and sharding for parallel and out-of-core tree learning",
                  "A regularized learning objective (penalty on number of leaves and L2 norm of leaf weights), included for completeness"],
     "claims": [
         ("Contributions stated in the abstract: a sparsity-aware algorithm for sparse data and a weighted quantile sketch for approximate tree learning, plus insights on cache access patterns, data compression and sharding for a scalable system.",
          "Abstract",
          "We propose a novel sparsity-aware algorithm for sparse data and weighted quantile sketch for approximate tree learning."),
         ("Regularized objective: a complexity penalty (gamma times the number of leaves plus an L2 penalty on leaf weights) is added to the loss to smooth the learnt weights and avoid over-fitting; with the regularization parameter set to zero the objective falls back to traditional gradient tree boosting. The authors describe the objective as a minor improvement included for completeness, resembling Regularized Greedy Forest but simpler and easier to parallelize.",
          "Regularized Learning Objective",
          "When the regularization parameter is set to zero, the objective falls back to the traditional gradient tree boosting."),
         ("Citing Friedman et al. [12], the tree is fitted with a second-order (gradient and Hessian) approximation of the loss; the authors state the derivation follows existing gradient boosting literature.",
          "Gradient Tree Boosting",
          "Second-order approximation can be used to quickly optimize the objective in the general setting [12]."),
         ("Besides shrinkage, column (feature) subsampling is used against over-fitting; the authors report, based on user feedback, that it prevents over-fitting even more than traditional row subsampling (which is also supported), and that it speeds up the parallel algorithm.",
          "Shrinkage and Column Subsampling",
          "According to user feedback, using column sub-sampling prevents over-ﬁtting even more so than the traditional row sub-sampling (which is also supported)."),
         ("Split finding: the exact greedy algorithm enumerates all splits on pre-sorted features; the approximate algorithm proposes candidate splits from feature percentiles either once per tree (global) or after each split (local). In the Higgs 10M comparison (shown as a figure), the authors find the local proposal needs fewer candidates and the global one can be as accurate given enough candidates.",
          "Approximate Algorithm",
          "The global proposal can be as accurate as the local one given enough candidates."),
         ("Sparsity-aware split finding learns, for each node, a default direction for missing entries from the data, and only visits non-missing entries so that cost is linear in their number; on Allstate-10K (sparse mainly due to one-hot encoding) it ran 50 times faster than a naive implementation.",
          "Sparsity-aware Split Finding",
          "We ﬁnd that the sparsity aware algorithm runs 50 times faster than the naive version."),
         ("Evaluation protocol: four datasets (Allstate, Higgs Boson, Yahoo LTRC, Criteo); all experiments use a common setting of maximum depth 8 and shrinkage 0.1 with no column subsampling unless specified. No per-library hyperparameter tuning procedure was found in the text (searched for tun, hyperparameter, grid, default).",
          "Dataset and Setup",
          "In all the experiments, we boost trees with a common setting of maximum depth equals 8, shrinkage equals 0.1 and no column subsampling unless explicitly speciﬁed."),
         ("Single-machine exact greedy comparison on dense Higgs-1M (chosen because scikit-learn only handles non-sparse input; 1M subset so scikit-learn finishes in reasonable time): both XGBoost and scikit-learn performed better than R's GBM (which expands only one branch of a tree), and XGBoost ran more than 10x faster than scikit-learn. Column subsampling gave slightly worse performance here, which the authors say could be due to few important features.",
          "Classification",
          "Both XGBoost and scikit-learn give better performance than R’s GBM, while XGBoost runs more than 10x faster than scikit-learn."),
     ],
     "notes": "Affiliation: University of Washington. Venue from the ACM block on page 1 ('KDD ’16, August 13-17, 2016, San Francisco') and the arXiv comment. The authors are the developers of XGBoost and compare it with other libraries (scikit-learn, R GBM, pGBRT, Spark MLLib, H2O); the comparisons are mostly about running time and scalability. Results tables (Tables 3-4) and figure-only results not recorded. The introduction also reports usage in Kaggle 2015 winning solutions and KDDCup 2015 (not recorded as claims)."},

    {"id": "arxiv-1706.09516",
     "title": "CatBoost: unbiased boosting with categorical features",
     "authors": ["Liudmila Prokhorenkova", "Gleb Gusev", "Aleksandr Vorobev", "Anna Veronika Dorogush", "Andrey Gulin"],
     "year": 2017, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1706.09516"},
     "tasks": ["tabular-classification"],
     "fam": ["gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["Ordered target statistics: encoding a categorical value by target statistics computed only from examples preceding it in a random permutation",
                  "Ordered boosting: a permutation-driven variant of gradient boosting in which the residual of an example is computed by a model not trained on that example, to avoid prediction shift",
                  "An analysis of prediction shift in gradient boosting as a form of target leakage",
                  "CatBoost: an open-source gradient boosting library with Ordered and Plain modes, oblivious trees and greedy categorical feature combinations"],
     "claims": [
         ("Contribution: ordered boosting and a new algorithm for categorical features, both designed against a prediction shift caused by a special kind of target leakage that the authors say is present in all existing gradient boosting implementations.",
          "Abstract",
          "Both techniques were created to ﬁght a prediction shift caused by a special kind of target leakage present in all currently existing implementations of gradient boosting algorithms."),
         ("Ordered target statistics compute each training example's statistic only from examples preceding it in a random permutation (an artificial 'time'), satisfying no conditional shift (P1) while using all data (P2); the stated cost is that with a single permutation, early examples have much higher-variance statistics, so different permutations are used at different boosting steps.",
          "Section 3.2",
          "Note that, if we use only one random permutation, then preceding examples have TS with much higher variance than subsequent ones."),
         ("Theorem 1 is proved for a simplified setting only: regression with quadratic loss, two i.i.d. Bernoulli(1/2) features, a linear target, two boosting steps with depth-1 stumps and step size 1. Reusing the same dataset at both steps gives a bias inversely proportional to n, while independent samples give an unbiased estimate (up to an exponentially small term).",
          "Section 4.1",
          "We formally analyze the problem of prediction shift in a simple case of a regression task with the quadratic loss function"),
         ("The idealized ordered boosting algorithm (n supporting models, each trained on a prefix of the permutation) is not feasible in most practical tasks because it multiplies complexity and memory by n; CatBoost implements a modification based on GBDT with decision trees.",
          "Section 4.2",
          "Unfortunately, this algorithm is not feasible in most practical tasks due to the need of training n different models, what increase the complexity and memory requirements by n times."),
         ("Comparison protocol (Appendix D.2): random 80/20 train-test split; for XGBoost, LightGBM and CatBoost, key parameters tuned by 50 steps of Hyperopt's Tree Parzen Estimator minimizing logloss with 5-fold cross-validation on the training set, then the number of trees chosen by exhaustive search in [1, 5000]; for Epsilon, default parameters were used (only the number of trees tuned) due to running time. Library versions: catboost 0.3, xgboost 0.6, lightgbm 0.1.",
          "Appendix D.2",
          "We tune all the key parameters of each algorithm by 50 steps of the sequential optimization algorithm Tree Parzen Estimator implemented in Hyperopt library21 (mode algo=tpe.suggest) by minimizing logloss."),
         ("In the baseline comparison, categorical features for all learning algorithms (including XGBoost and LightGBM) were preprocessed with CatBoost's own ordered TS method; CatBoost used Ordered boosting mode; metrics are logloss and zero-one loss on nine binary classification datasets.",
          "Section 6",
          "For all learning algorithms, we preprocess categorical features using the ordered TS method described in Section 3.2."),
         ("The authors report that CatBoost outperforms XGBoost and LightGBM on all considered datasets, with improvements statistically significant (paired one-tailed t-test) except on Appetency, Churn and Upselling.",
          "Section 6",
          "except three datasets (Appetency, Churn and Upselling) the improvements are statistically signiﬁcant with p-value ≪0.01 measured by the paired one-tailed t-test."),
         ("Ordered vs Plain mode: the largest benefit of Ordered mode is on the relatively small datasets (Adult and Internet, under 40K training examples), consistent with the bias of Theorem 1 being larger for smaller datasets; the authors note the bias can also depend on other dataset properties.",
          "Section 6",
          "It can be clearly seen that Ordered mode is particularly useful on small datasets."),
         ("Cost: in the running-time comparison on Epsilon (Appendix C.2), CatBoost Plain and LightGBM were the fastest, followed by Ordered mode, about 1.7 times slower.",
          "Section 6",
          "To summarize, we obtained that CatBoost Plain and LightGBM are the fastest ones followed by Ordered mode, which is about 1.7 times slower."),
     ],
     "notes": "Affiliations: Yandex and Moscow Institute of Physics and Technology. Conflict of interest: the authors are the CatBoost developers (the paper presents CatBoost as their open-source library) and compare it with XGBoost and LightGBM; all three libraries were tuned with the same Hyperopt TPE budget (50 steps), but categorical features for the baselines were encoded with CatBoost's ordered TS rather than the baselines' own handling. The PDF says 'Preprint. Work in progress.'; no venue is stated in the PDF, so none recorded. Appendix G compares a 'raw' CatBoost setting (Plain mode, oblivious trees, no categorical options) with the baselines and reports the difference as insignificant. Results tables (Tables 2-4, 8) not recorded."},

    {"id": "arxiv-1810.11363",
     "title": "CatBoost: gradient boosting with categorical features support",
     "authors": ["Anna Veronika Dorogush", "Vasily Ershov", "Andrey Gulin"],
     "year": 2018, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1810.11363"},
     "tasks": ["tabular-classification"],
     "fam": ["gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["CatBoost library description: categorical feature handling during training (one-hot, ordered target statistics, greedy feature combinations, counters), a gradient-bias-reducing scheme for choosing tree structures, oblivious trees with a fast scorer, and a GPU training implementation"],
     "claims": [
         ("One-hot encoding of categorical features can be done at preprocessing or during training; CatBoost does it during training, which the authors say is more efficient in training time.",
          "Categorical features",
          "One-hot encoding can be done during the preprocessing phase or during training, the latter can be implemented more efﬁciently in terms of training time and is implemented in CatBoost."),
         ("Feature combinations: since the number of combinations of categorical features grows exponentially, CatBoost considers them greedily: none for the first split, then combinations of categorical features already in the current tree with all categorical features, converted to numbers on the fly; splits on numerical features are also used in combinations as two-valued categorical features.",
          "Categorical features",
          "When constructing a new split for the current tree, CatBoost considers combinations in a greedy way."),
         ("Gradient bias: gradients at each step are estimated on the same data points the current model was built on, which the authors say shifts the distribution of estimated gradients and leads to overfitting; the formal analysis is referenced to the authors' earlier paper [5] (arXiv:1706.09516).",
          "Fighting Gradient Bias",
          "Gradients used at each step are estimated using the same data points the current model was built on."),
         ("CatBoost uses the modified (unbiased-gradient) scheme only for choosing the tree structure, setting leaf values with the traditional GBDT scheme; the per-example models are relaxed so that all share the same tree structures.",
          "Fighting Gradient Bias",
          "CatBoost implementation uses the following relaxation of this idea: all Mi share the same tree structures."),
         ("Quality comparison protocol against XGBoost, LightGBM and H2O: categorical features preprocessed with statistics on a random permutation, tuning and training on 4/5 of the data, testing on 1/5, final training repeated with 5 seeds and logloss averaged; the detailed setup (including the tuning procedure) is said to be on the authors' GitHub rather than in the paper.",
          "Experiments",
          "The parameter tunning and training was performed on 4/5 of the data and the testing was performed on the other 1/5."),
         ("The authors state CatBoost outperforms the other algorithms on all datasets in the classification comparison, and point to their GitHub repository (not shown in the paper) for results of default-parameter CatBoost against tuned baselines.",
          "Experiments",
          "In our repo on github you can also see that CatBoost with default parameters outperforms tunned XGBoost and H2O on all datasets and LightGBM on all but one datasets."),
         ("The authors say training speed is very hard to compare across boosting libraries because parameters affect speed, quality and model size in non-obvious ways, so they only compare the time to train ensembles of fixed size (8000 trees on Epsilon, 15 bins, depth 6 or 64 leaves).",
          "GPU training performance: comparison with baselines",
          "As a result, we can’t compare libraries by time we need to obtain certain level of quality."),
         ("Cost of the bias-fighting scheme: by design 2-3 times slower than classical boosting; the GPU speed benchmark used the classic scheme instead.",
          "GPU training performance: comparison with baselines",
          "This scheme is by design 2-3 times slower then classical boosting approach."),
     ],
     "notes": "Affiliation: Yandex. Conflict of interest: the authors are CatBoost developers comparing it with XGBoost, LightGBM and H2O. The tuning budget/search method for each library is not described in the paper (only referred to GitHub). No venue is stated in the PDF; the MVS paper (arXiv:1910.13204) cites it as 'Workshop on ML Systems at NIPS (2017)', but this is not confirmed by the PDF itself, so no venue recorded. Results tables (Tables 1-3) not recorded."},

    {"id": "arxiv-1910.13204",
     "title": "Minimal Variance Sampling in Stochastic Gradient Boosting",
     "authors": ["Bulat Ibragimov", "Gleb Gusev"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1910.13204"},
     "tasks": ["tabular-classification"],
     "fam": ["gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["Minimal Variance Sampling (MVS): row sampling for stochastic gradient boosting with probabilities proportional to a regularized gradient magnitude sqrt(g^2 + lambda h^2), capped at 1, with inverse-probability weights, derived from minimizing the variance of split-score estimates",
                  "MVS Adaptive: a hyperparameter-free variant setting lambda from the squared mean of the initial leaf"],
     "claims": [
         ("Problem formulation: randomization in stochastic gradient boosting is cast as optimizing sampling probabilities to maximize the estimation accuracy of split scores used to train the trees.",
          "Abstract",
          "In this paper, we formulate the problem of randomization in SGB in terms of optimization of sampling probabilities to maximize the estimation accuracy of split scoring used to train decision trees."),
         ("Assumptions of the derivation: the squared deviation between sampled and full-data split scores is minimized assuming previous splits of the tree are fixed and the same for subsampled and full data; an upper bound is minimized and the unknown leaf values are replaced by a universal constant (the parameter lambda), giving a nearly optimal closed-form solution.",
          "Problem setting",
          "under the assumption that previous splits of the tree are ﬁxed and the same for subsampled and full data."),
         ("Setting lambda to 0 recovers Importance Sampling, which the authors say is of limited use in GBDT because the number of instances in each node must still be estimated accurately and it is numerically unstable for near-zero gradients; the lambda term acts as a regularizer against enormous weights. (The next paragraph states that lambda to infinity gives SGB.)",
          "Theoretical analysis",
          "It is easy to derive that setting λ to 0 implies the procedure of Importance Sampling."),
         ("Cost of sampling: a sort-and-binary-search threshold search is O(N log N), versus O(N) for SGB and GOSS; the authors propose a quickselect-like algorithm with O(N) complexity.",
          "Algorithm",
          "To compare with, SGB and GOSS algorithms have O(N) complexity for sampling."),
         ("CatBoost benchmark setup: MVS (80% sampling ratio) implemented in CatBoost and compared with default CatBoost without sampling on 153 public and proprietary binary classification datasets (up to 45 million instances), counting ROC-AUC wins.",
          "Experiments",
          "We implemented MVS in CatBoost and performed benchmark comparison of MVS with sampling ratio 80% and default CatBoost with no sampling on 153 publicly available and proprietary binary classiﬁcation datasets of different sizes up to 45 millions instances."),
         ("Result stated in the text for the CatBoost benchmark: 97 wins for MVS versus 55 for the default setting and +0.12% mean ROC-AUC.",
          "Experiments",
          "The results show signiﬁcant improvement over the existing default: 97 wins of MVS versus 55 wins of default setting and +0.12% mean ROC-AUC improvement."),
         ("LightGBM comparison protocol (MVS vs GOSS vs SGB, all implemented in LightGBM): baselines use the tuned parameters and train-test splits from the CatBoost benchmark repository [5] with sampling ratio 1; only the sampling parameters of each method are tuned by 5-fold cross-validation on the training subset; evaluation on the 20% test subset with 1 - ROC-AUC, averaged over 10 seeds; seven public datasets.",
          "Experiments",
          "We used the tuned parameters and train-test splitting for each dataset from [5] as baselines, presetting the sampling ratio to 1."),
         ("Tuning cost: GOSS and MVS each have one hyperparameter beyond the sample rate, so tuning them may potentially take more time than SGB; MVS Adaptive is introduced to remove the lambda hyperparameter.",
          "Experiments",
          "So tuning GOSS and MVS may potentially take more time than SGB."),
     ],
     "notes": "Affiliations: Yandex / Moscow Institute of Physics and Technology (Ibragimov) and Sberbank (Gusev; 'The study was done while working at Yandex'). Conflict of interest: MVS was implemented in and made the default subsampling option of CatBoost, the authors' organisation's library; the LightGBM implementation of MVS was also written by the authors. The PDF says 'Preprint. Under review.'; no venue recorded. Possible typo in the Large datasets paragraph: the Recsys time differences list 'SGB (sample rate 20%)' twice (presumably one is GOSS); not recorded. Results tables (Tables 2-4) not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
