import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_diff_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2010.02502",
     "title": "Denoising Diffusion Implicit Models",
     "authors": ["Jiaming Song", "Chenlin Meng", "Stefano Ermon"],
     "year": 2020, "venue": "ICLR 2021", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2010.02502"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised"],
     "proposes": ["A family of non-Markovian forward (inference) processes, indexed by sigma, whose variational objectives share the DDPM surrogate objective, so a DDPM-trained noise-prediction network can be reused for all of them",
                  "DDIM: the deterministic (sigma = 0) generative process of this family, an implicit model; sampling on a sub-sequence of the time steps gives shorter generative processes without retraining"],
     "claims": [
         ("Contribution: DDIMs are iterative implicit probabilistic models with the same training procedure as DDPMs; DDPMs are generalized via non-Markovian diffusion processes that lead to the same training objective, and these can correspond to deterministic generative processes.",
          "Abstract",
          "To accelerate sampling, we present denoising diffusion implicit models (DDIMs), a more efﬁcient class of iterative implicit probabilistic models with the same training procedure as DDPMs."),
         ("No retraining: Theorem 1 states that for all sigma > 0 the variational objective J_sigma equals some weighted DDPM objective L_gamma up to a constant; if parameters are not shared across t, the optimum does not depend on the weights, so pretrained DDPM models can be used and only the generative process (sigma) is changed. The deterministic case sigma = 0 is not covered by Theorem 1 and is approximated by making sigma very small (footnote 5).",
          "Sampling from generalized generative processes",
          "Therefore, we can essentially use pretrained DDPM models as the solutions to the new objectives, and focus on ﬁnding a generative process that is better at producing samples subject to our needs by changing σ."),
         ("Fewer steps: because the denoising objective does not depend on the specific forward procedure as long as the marginals q_sigma(x_t|x_0) are fixed, forward processes defined on a sub-sequence tau of [1, ..., T] can be used, which accelerates the generative process without training a different model.",
          "Accelerated generation processes",
          "which accelerates the corresponding generative processes without having to train a different model."),
         ("Relation to ODEs: the DDIM iterate can be seen as an Euler method for an ODE; with the optimal model this ODE is equivalent to the probability flow ODE of the Variance-Exploding SDE of Song et al. (2020) (Proposition 1), but the sampling procedures differ (Euler steps in d sigma(t) vs in dt), which the authors say makes a difference with fewer sampling steps.",
          "Relevance to neural ODEs",
          "While the ODEs are equivalent, the sampling procedures are not, since the Euler method for the probability ﬂow ODE will make the following update:"),
         ("Evaluation setup: the same trained model (T = 1000, gamma = 1 objective) is used per dataset and only the sampling (tau, and sigma via eta) is changed; pretrained checkpoints from the original DDPM implementation are used for CIFAR10, LSUN Bedroom and Church, and the authors trained their own CelebA 64x64 model.",
          "Appendix D.1",
          "For CIFAR10, Bedroom and Church, we obtain the pretrained checkpoints from the original DDPM implementation; for CelebA, we trained our own model using the denoising objective L1."),
         ("Step-sub-sequence choice: tau is selected linearly or quadratically; quadratic was used for CIFAR10 and linear for the other datasets because these choices gave slightly better FID than the alternative on the respective dataset (i.e. the schedule was chosen by FID).",
          "Appendix D.2",
          "These choices achieve slightly better FID than their alternatives in the respective datasets."),
         ("Steps-vs-quality trade-off (CIFAR10 and CelebA FID, Table 1): quality improves as dim(tau) increases; DDIM (eta = 0) is best when dim(tau) is small, and DDPM (eta = 1 and sigma-hat) is typically worse at the same dim(tau), except for dim(tau) = 1000 with sigma-hat as reported by Ho et al. (2020), where DDIM is marginally worse; sigma-hat becomes much worse for small dim(tau).",
          "Sample quality and efficiency",
          "As expected, the sample quality becomes higher as we increase dim(τ), presenting a trade-off between sample quality and computational costs."),
         ("The authors state that DDIM reaches sample quality comparable to 1000-step models within 20 to 100 steps (a 10x to 50x speed-up over the original DDPM), and that sampling time scales linearly with trajectory length (Figure 4).",
          "Sample quality and efficiency",
          "Notably, DDIM is able to produce samples with quality comparable to 1000 step models within 20 to 100 steps, which is a 10× to 50× speed up compared to the original DDPM."),
     ],
     "notes": "Affiliation: Stanford University. Venue from the PDF header ('Published as a conference paper at ICLR 2021') and the arXiv comment. Uses pretrained DDPM checkpoints (Ho et al., 2020) for CIFAR10/LSUN; CelebA model trained by the authors. The number of samples used for FID and the reference statistics were not found in the text (searched for 50k, 10k, 50000, Inception, number of samples); 50k appears only in the sampling-time statements. The Discussion suggests multi-step ODE methods such as Adams-Bashforth might further improve few-step quality (not tested). Stefano Ermon is a co-author of NCSN (Song & Ermon, 2019), discussed as related work. FID tables (Table 1, Table 3) not recorded."},

    {"id": "arxiv-2206.00927",
     "title": "DPM-Solver: A Fast ODE Solver for Diffusion Probabilistic Model Sampling in Around 10 Steps",
     "authors": ["Cheng Lu", "Yuhao Zhou", "Fan Bao", "Jianfei Chen", "Chongxuan Li", "Jun Zhu"],
     "year": 2022, "venue": "NeurIPS 2022", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2206.00927"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised"],
     "proposes": ["An exact formulation of diffusion-ODE solutions that computes the linear part analytically and, after a change of variable to the half-log-SNR lambda, leaves an exponentially weighted integral of the noise-prediction network",
                  "DPM-Solver-1/2/3: training-free k-th order solvers (k network evaluations per step) for this integral, with a uniform-in-lambda or adaptive step-size schedule, applicable to discrete- and continuous-time DPMs"],
     "claims": [
         ("Method: diffusion ODEs are semi-linear; the proposed exact formulation computes the linear part of the solution analytically instead of leaving all terms to black-box ODE solvers, and by change of variable reduces to an exponentially weighted integral of the neural network.",
          "Abstract",
          "The formulation analytically computes the linear part of the solution, rather than leaving all terms to black-box ODE solvers as adopted in previous works."),
         ("Requirements: DPM-Solver applies to both discrete-time and continuous-time DPMs without any further training; for discrete-time models the noise-prediction network is fed non-integer (continuous) time inputs, which the authors find still works and hypothesize is due to smooth time embeddings.",
          "Abstract",
          "DPM-Solver is suitable for both discrete-time and continuous-time DPMs without any further training."),
         ("Positioning: the authors divide fast samplers into training-based ones (knowledge distillation, noise-level or trajectory learning), which require a possibly expensive training stage and whose applicability and flexibility might be limited, and training-free ones, which (citing [21]) still require about 50 function evaluations for high-quality samples.",
          "Introduction",
          "Such methods require a possibly expensive training stage before they can be used for efﬁcient sampling."),
         ("Cost per step and theory: DPM-Solver-k needs k function evaluations per step (k = 1, 2, 3); higher orders are usually more efficient because they need far fewer steps. Theorem 3.2 states DPM-Solver-k is a k-th order solver under regularity conditions on the noise-prediction model (Appendix B.1); orders k >= 4 are not considered.",
          "High-order solvers for diffusion ODEs",
          "As shown in the algorithm, DPM-Solver-k requires k function evaluations per step for k = 1, 2, 3."),
         ("DDIM's update is shown to be identical to DPM-Solver-1, which the authors say explains DDIM's advantage over the first-order Euler discretization (it uses the semi-linearity of diffusion ODEs).",
          "Comparison with existing fast sampling methods",
          "Although motivated by entirely different perspectives, we show that the updates of DPM-Solver-1 and Denoising Diffusion Implicit Models (DDIM) [19] are identical."),
         ("Citing progressive distillation [13], the authors note it can give a sampler within 4 steps but needs further training and loses part of the original model's information (the distilled model cannot predict the noise at every time step), whereas training-free samplers keep the original model and can be combined with an external classifier for guidance.",
          "Training-based fast sampling methods for DPMs",
          "Although the progressive distillation method [13] can obtain a fast sampler within 4 steps, it needs further training costs and loses part of the information in the original DPM"),
         ("Evaluation protocol: NFE is the number of calls to the noise-prediction model; FID is computed from 50K samples; existing pre-trained checkpoints are used (e.g. Ho et al. for CIFAR-10, Dhariwal & Nichol for ImageNet 128x128 with classifier guidance scale 1.25 and LSUN bedroom); a solver combination with uniform step size is used for NFE <= 20 and the adaptive DPM-Solver otherwise. Some baseline results are taken from the original papers (GGDM, and the improved-Euler SDE solver).",
          "Experiments",
          "For each experiment, We draw 50K samples and use the widely adopted FID score [37] to evaluate the sample quality, where lower FID usually implies better sample quality."),
         ("With the continuous-time 'VP deep' CIFAR-10 model, the authors report FID 4.70 at 10 NFE, 3.75 at 12 NFE, 3.24 at 15 NFE and 2.87 at 20 NFE; they state other solvers have large discretization error even at 50 NFE.",
          "Experiments: comparison with continuous-time sampling methods",
          "In particular, we achieve 4.70 FID with 10 NFE, 3.75 FID with 12 NFE, 3.24 FID with 15 NFE, and 2.87 FID with 20 NFE, which is the fastest sampler on CIFAR-10."),
         ("Limitations stated: DPM-Solver is designed for fast sampling and may not be suitable for accelerating likelihood evaluation; compared with GANs, diffusion models with DPM-Solver are still not fast enough for real-time applications.",
          "Conclusions (Limitations and broader impact)",
          "Besides, compared to the commonly-used GANs, diffusion models with DPM-Solver are still not fast enough for real-time applications."),
     ],
     "notes": "Affiliations: Tsinghua University and Renmin University of China. Venue from the PDF footer ('36th Conference on Neural Information Processing Systems (NeurIPS 2022)') and the arXiv comment. Conflict of interest: Analytic-DPM/Analytic-DDIM [21] (F. Bao, C. Li, J. Zhu, B. Zhang), used as a training-free baseline, is by co-authors of this paper. Some baseline numbers are copied from the original papers (GGDM [18]; improved-Euler SDE solver [20]). DDIM on CelebA uses quadratic steps as the 'strongest baseline'. Most comparisons are shown as figures (Fig. 2); FID tables not recorded."},

    {"id": "arxiv-2202.00512",
     "title": "Progressive Distillation for Fast Sampling of Diffusion Models",
     "authors": ["Tim Salimans", "Jonathan Ho"],
     "year": 2022, "venue": "ICLR 2022", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2202.00512"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models", "knowledge-distillation"], "par": ["unsupervised"],
     "proposes": ["Progressive distillation: repeatedly distill an N-step deterministic DDIM sampler of a teacher diffusion model into a student (initialized from the teacher) that needs N/2 steps, the student becoming the next teacher",
                  "Parameterizations stable at low SNR (predicting x, (x, epsilon) combined, or v = alpha*epsilon - sigma*x) and loss weightings ('truncated SNR', 'SNR+1') suited to distillation"],
     "claims": [
         ("Procedure: the student is initialized as a copy of the teacher; training is like standard diffusion training except that the denoising target is the value that makes one student DDIM step match two teacher DDIM steps (computed by running the teacher and inverting one DDIM step); after convergence the student becomes the new teacher and the number of steps is halved.",
          "Progressive distillation",
          "At every iteration of progressive distillation, we then initialize the student model with a copy of the teacher, using both the same parameters and same model deﬁnition."),
         ("Rationale: the distillation target is fully determined given the teacher and z_t, unlike the original data point, so the student can make sharp rather than blurry (averaged) predictions.",
          "Progressive distillation",
          "By making sharper predictions, the student model can make faster progress during sampling."),
         ("Parameterization requirement: the standard epsilon-prediction with SNR-weighted loss is not well suited for distillation, because as distillation progresses the model is evaluated at lower SNR, where the implied x-prediction amplifies small errors and, at zero SNR, the link between epsilon- and x-prediction breaks down.",
          "Diffusion model parameterization and training loss",
          "Although this standard speciﬁcation works well for training the original model, it is not well suited for distillation:"),
         ("Ablation protocol (undistilled CIFAR-10 models, Table 1): results are averages over 3 seeds of the best metrics obtained over 2 million training steps, with about +-0.1 noise; the epsilon output with truncated-SNR weighting diverged.",
          "Experiments: model parameterization and training loss (Table 1 caption)",
          "All reported results are averages over 3 random seeds of the best metrics obtained over 2 million training steps; nevertheless we ﬁnd results are still ±0.1 due to the noise inherent in training our models."),
         ("Training cost: distillation starts from 8192 teacher steps on CIFAR-10 and 1024 on the larger datasets, with 50 thousand parameter updates per iteration (100 thousand for 2 and 1 steps); with these settings, distilling to 4 steps costs comparable to or less than training the original model.",
          "Experiments: progressive distillation",
          "Using these settings, the computational cost of progressive distillation to 4 sampling steps is comparable or less than for training the original model."),
         ("Step-quality trade-off: progressive distillation gives near-optimal results down to 4 or 8 steps, quality degrades relatively faster at 2 or 1 steps, while undistilled DDIM and stochastic samplers degrade very sharply below 128 steps; the authors conclude it is attractive for budgets of 128 steps or fewer.",
          "Experiments: progressive distillation",
          "At 2 or 1 sampling steps, the sample quality degrades relatively more quickly."),
         ("Baseline protocol (Figure 4): DDIM and the stochastic sampler use the same models that initialize distillation; the stochastic sampler's variance interpolation coefficient is tuned separately for each number of steps and only the best result is reported; CIFAR-10 results average 4 seeds, other datasets a single run because of compute.",
          "Figure 4 caption",
          "We then tune this interpolation coefﬁcient separately for each number of sampling steps and report only the best result for that number of steps:"),
         ("Compared with Luhman & Luhman (2021), whose one-step distillation requires building a large dataset by running the original model at its full number of steps, progressive distillation never runs the original model at the full number of steps, so total distillation time grows logarithmically with the number of teacher steps.",
          "Related work on fast sampling",
          "In contrast, our method never needs to run the original model at the full number of sampling steps:"),
         ("Limitation: the student has the same architecture and number of parameters as the teacher; smaller students are left to future work.",
          "Discussion",
          "In the current work we limited ourselves to setups where the student model has the same architecture and number of parameters as the teacher model:"),
     ],
     "notes": "Affiliation: Google Research, Brain team. Venue from the PDF header ('Published as a conference paper at ICLR 2022') and the arXiv comment. Jonathan Ho is first author of DDPM (Ho et al., 2020), whose training setup and code the experiments follow. Table 2 compares with numbers from the literature (Improved DDPM respacing marked 'our reimplementation'). Table 1 reports the best metrics over training (checkpoint selection on the evaluation metric). The number of samples used for FID was not found in the main text. Appendix I reports faster schedules (fewer updates per iteration) with larger losses at very few steps. Results tables not recorded."},

    {"id": "arxiv-2303.01469",
     "title": "Consistency Models",
     "authors": ["Yang Song", "Prafulla Dhariwal", "Mark Chen", "Ilya Sutskever"],
     "year": 2023, "venue": "ICML 2023", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2303.01469"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models", "knowledge-distillation"], "par": ["unsupervised"],
     "proposes": ["Consistency models: networks f(x_t, t) trained so that all points on the same probability flow ODE trajectory map to its origin, with a boundary condition f(x, eps) = x built into the parameterization; one network evaluation per sample, optionally multistep",
                  "Consistency distillation (CD) from a pre-trained diffusion (score) model and consistency training (CT) without any pre-trained model"],
     "claims": [
         ("Contribution: consistency models map noise directly to data, support one-step generation by design, and allow multistep sampling that trades compute for sample quality; they can be trained by distilling a pre-trained diffusion model or as standalone generative models.",
          "Abstract",
          "They support fast one-step generation by design, while still al-lowing multistep sampling to trade compute for sample quality."),
         ("Requirements: consistency distillation uses a numerical ODE solver and a pre-trained diffusion model to generate adjacent points on a PF ODE trajectory, whereas consistency training needs no pre-trained diffusion model; neither uses adversarial training. CD models are initialized from the pre-trained diffusion models; CT models are randomly initialized.",
          "Introduction",
          "By contrast, our second method eliminates the need for a pre-trained diffusion model altogether, allowing us to train a consistency model in isolation."),
         ("Positioning: citing Luhman & Luhman (2021) and Zheng et al. (2022), most distillation methods collect a large dataset of diffusion-model samples beforehand, which is computationally expensive; the authors state progressive distillation is the only one they know without this drawback, and that ODE solvers still need more than 10 steps for competitive samples.",
          "Diffusion Models (Section 2)",
          "However, ODE solvers still need more than 10 evaluation steps to generate competitive samples."),
         ("Multistep sampling protocol: the intermediate time points of Algorithm 1 are found greedily, one at a time, by ternary search optimizing the FID of the samples, assuming FID is unimodal in the next time point (which they found to hold empirically).",
          "Section 3 (Sampling)",
          "where the time points are pinpointed one at a time using ternary search to optimize the FID of samples obtained from Algorithm 1."),
         ("Theory (Theorem 1): assuming the consistency model is Lipschitz and the ODE solver has bounded local error of order p+1, zero CD loss implies the estimation error is O((Delta t)^p); the authors say that under some regularity conditions the model can become arbitrarily accurate if the ODE step size is small enough. Theorem 2 relates CT to CD assuming the Euler solver and a score model equal to the ground truth.",
          "Section 4",
          "the estimated consistency model can become arbitrarily accurate, as long as the step size of the ODE solver is sufficiently small."),
         ("CT trade-off: convergence of consistency training is highly sensitive to the number of discretization steps N (smaller N converges faster but gives worse samples), which motivates progressively increasing N and the EMA rate during training; these schedules were tuned separately per image resolution.",
          "Section 6.1",
          "As demonstrated in Fig. 3d, the con-vergence of CT is highly sensitive to N—smaller N leads to faster convergence but worse samples, whereas larger N leads to slower convergence but better samples upon convergence."),
         ("Continuous-time CD and CT losses avoid choosing N but require Jacobian-vector products and forward-mode automatic differentiation, which may not be well supported in some deep learning frameworks.",
          "Section 4",
          "Nonetheless, they involve Jacobian-vector products and require forward-mode automatic dif-ferentiation for efficient implementation, which may not be well-supported in some deep learning frameworks."),
         ("Comparison protocol with progressive distillation: both PD and CD distill the same EDM models pre-trained in-house; LPIPS improved PD over the squared L2 distance used originally, but the tables report PD with L2 (its default). CD outperforms PD across datasets, steps and metrics considered, except single-step generation on LSUN Bedroom 256x256 where CD with L2 slightly underperforms PD with L2. CD settings (LPIPS, Heun, N = 18) were chosen on CIFAR-10 and N was tuned separately on other datasets.",
          "Section 6.2",
          "All methods distill from an EDM (Karras et al., 2022) model that we pre-trained in-house."),
         ("As standalone models, the authors conclude that consistency models generate better samples than existing single-step generation models except for GANs (CT reaching quality comparable to one-step PD without distillation).",
          "Section 7 (Conclusion)",
          "Furthermore, as a standalone generative model, consistency models generate better samples than existing single-step generation models except for GANs."),
     ],
     "notes": "Affiliation: OpenAI. Venue from the PDF footer ('Proceedings of the 40th International Conference on Machine Learning ... PMLR 202, 2023') and the arXiv comment. Main text read; Appendix C read for training details (EDM teachers trained in-house; PD used Salimans & Ho settings, and their ImageNet settings for LSUN). Conflict of interest: Yang Song co-authored Score SDE (Song et al., 2021), and Prafulla Dhariwal co-authored ADM (Dhariwal & Nichol, 2021); both appear as baselines in Tables 1-2 and their architectures are used. Abstract reports one-step FID 3.55 (CIFAR-10) and 6.20 (ImageNet 64x64). Number of samples for FID not found in the main text. Results tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
