import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1906.02694",
     "title": "Deep Semi-Supervised Anomaly Detection",
     "authors": ["Lukas Ruff", "Robert A. Vandermeulen", "Nico Görnitz", "Alexander Binder", "Emmanuel Müller", "Klaus-Robert Müller", "Marius Kloft"],
     "year": 2019, "venue": "ICLR 2020", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1906.02694", "code": "https://github.com/lukasruff/Deep-SAD-PyTorch"},
     "tasks": ["anomaly-detection"],
     "fam": ["deep-learning", "autoencoders"], "par": ["unsupervised", "semi-supervised", "supervised"],
     "proposes": ["Deep SAD: a generalization of Deep SVDD to general semi-supervised anomaly detection; unlabeled and labeled normal samples are pulled towards a fixed center c in output space, labeled anomalies are pushed away via an inverse squared-distance loss weighted by eta; the anomaly score is the distance to c",
                  "An information-theoretic interpretation of deep anomaly detection (Infomax with a regularizer asking for low entropy of the latent distribution of normal data and high entropy for anomalies)",
                  "Experimental scenarios for general semi-supervised AD (labeled-anomaly ratio, pollution ratio, number of known anomaly classes) and a hybrid SSAD baseline on autoencoder codes"],
     "claims": [
         ("Setting: in addition to n unlabeled samples (mostly normal but possibly containing anomalous contamination), one may have m labeled samples verified as normal or anomalous, e.g. hand labeled by a domain expert; the authors call this semi-supervised AD and note that most existing 'semi-supervised' AD methods only use labeled normal samples (i.e. learning from positive and unlabeled examples).",
          "Introduction",
          "Unlike the standard unsupervised AD setting, in many real-world applications one may also have access to some veriﬁed (i.e., labeled) normal or anomalous samples in addition to the unlabeled data."),
         ("Why not plain (semi-)supervised classification: semi-supervised classifiers typically make the cluster assumption (similar points are likely of the same class), which according to the authors only holds for the normal class in AD, not for the anomaly class, since anomalies are not necessarily similar to one another.",
          "Introduction",
          "only holds for the “normal class” in AD, but is crucially invalid for the “anomaly class” since anomalies are not necessarily similar to one another."),
         ("Deep SVDD (Ruff et al., 2018, by overlapping authors), the unsupervised special case: a network is trained to minimize the mean squared distance of mapped training samples to a center c plus weight decay; following Ruff et al. (2018), the network is initialized from a pre-trained autoencoder's encoder and c is set to the mean of the network outputs from an initial forward pass; the anomaly score is the distance to c.",
          "Section 3.1",
          "For initialization, Ruff et al. (2018) ﬁrst pre-train an autoencoder and then initialize the weights W of the network φ with the converged weights of the encoder."),
         ("Architecture constraint adopted from Ruff et al. (2018) to prevent 'hypersphere collapse' (the network mapping everything to c): the network must have no bias terms and no bounded activation functions; c is fixed rather than optimized, since a free c would allow the trivial collapse in the fully unlabeled setting. With sufficiently many labeled anomalies, collapse is not a problem for Deep SAD.",
          "Appendix C",
          "Most importantly, network φ must have no bias terms and no bounded activation functions."),
         ("Deep SAD keeps the Deep SVDD loss on unlabeled data and therefore incorporates the assumption that most unlabeled data is normal (recovering Deep SVDD when m = 0); labeled normal samples get a quadratic loss to c and labeled anomalies an inverse squared-distance loss, weighted by eta. The authors found that simply setting eta = 1 yields a consistent and substantial improvement; other anomaly losses (negative squared norm, robust losses, hinge) diverged, needed hard-to-select scale parameters, or performed worse.",
          "Deep SAD",
          "In doing this we also incorporate the assumption that most of the unlabeled data is normal."),
         ("Image benchmark: ten one-vs-rest setups each on MNIST, Fashion-MNIST and CIFAR-10 (one class normal, the other nine anomalies), using the clean training data of the normal class as unlabeled data; in scenario (i) labeled anomalies come from one of the nine anomaly classes and all nine are anomalies at test time (eight novel classes), averaged over 90 experiments per ratio, with AUC on the original test sets.",
          "Experimental Scenarios on MNIST, Fashion-MNIST, and CIFAR-10",
          "We do this to simulate the unpredictable nature of anomalies."),
         ("Hyperparameter selection: the shallow and hybrid methods (OC-SVM/SVDD and SSAD, RBF kernel) are deliberately given an unfair advantage by selecting their hyperparameters to maximize AUC on 10% of the test set; the deep methods share the same LeNet-type networks to control for architecture, and Deep SAD uses fixed eta = 1 and lambda = 10^-6 with Adam defaults and a fixed two-phase learning-rate schedule (Appendix E). Isolation Forest uses the original recommended defaults and KDE bandwidth is chosen by 5-fold cross-validation on log-likelihood.",
          "Competing Methods",
          "In our experiments we deliberately grant the shallow and hybrid methods an unfair advantage by selecting their hyperparameters to maximize AUC on a subset (10%) of the test set to minimize hyperparameter selection issues."),
         ("The supervised classifier is vulnerable to novel anomalies at test time when only little labeled data is available; it catches up as the number of known anomaly classes grows except on CIFAR-10. The authors state Deep SAD is particularly beneficial on the more complex data; Deep SAD is fairly robust to eta in their sensitivity analysis (Section 4.3).",
          "Experimental Scenarios on MNIST, Fashion-MNIST, and CIFAR-10",
          "Figure 2 moreover conﬁrms that a supervised classiﬁcation approach is vulnerable to novel anomalies at testing time when only little labeled training data is available."),
         ("Classical vs deep: on six classic (ODDS) tabular benchmarks (60:40 train-test splits, 10 seeds, 1% labeled anomalies, no pollution, standardized features), the shallow kernel methods seem to have a slight edge on the relatively small, low-dimensional benchmarks; the authors say Deep SAD is competitive and the small differences might be explained by the hyperparameter-selection advantage granted to the shallow methods.",
          "Classic Anomaly Detection Benchmark Datasets",
          "Here we observe that the shallow kernel methods seem to have a slight edge on the relatively small, low-dimensional benchmarks."),
     ],
     "notes": "Affiliations: TU Berlin, 123ai.de, SUTD, b-it Bonn, Korea University, MPI Informatics, TU Kaiserslautern. Venue from the PDF header ('Published as a conference paper at ICLR 2020'); year is the arXiv submission year (2019). Conflict of interest / self-citation: Deep SVDD (Ruff et al., 2018), the main deep unsupervised baseline, is by overlapping authors (Ruff, Vandermeulen, Görnitz, Binder, Müller, Kloft); Görnitz and Kloft also co-authored the SSAD baseline (Görnitz et al., 2013). Ruff et al. also wrote the review arxiv-2009.11732 and the follow-up critique arxiv-2006.00339 (which recasts Deep SAD as 'unsupervised OE'). Semi-supervised setting: no 'semi-supervised' paradigm tag exists; tagged unsupervised + supervised as closest. Scenarios (ii) pollution (gamma_l = 0.05, k_l = 1, 90 experiments) and (iii) number of known anomaly classes (gamma_l = 0.05, gamma_p = 0.1, 10 seeds x 10 setups) are reported as figures only; Wilcoxon signed-rank tests between 1st and 2nd best. No threshold is chosen (AUC only). Section 3.1 confirmed by the cross-reference 'from Section 3.1' and Section 4.3 by 'A sensitivity analysis on η is in Section 4.3'; other locations use section names. Results not recorded."},

    {"id": "arxiv-2006.00339",
     "title": "Rethinking Assumptions in Deep Anomaly Detection",
     "authors": ["Lukas Ruff", "Robert A. Vandermeulen", "Billy Joe Franks", "Klaus-Robert Müller", "Marius Kloft"],
     "year": 2020, "venue": "ICML 2021 Workshop on Uncertainty and Robustness in Deep Learning", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2006.00339", "code": "https://github.com/lukasruff/Classification-AD"},
     "tasks": ["anomaly-detection"],
     "fam": ["deep-learning"], "par": ["unsupervised", "semi-supervised"],
     "proposes": ["Hypersphere classification (HSC): a cross-entropy objective with a radial-basis output l(z) = exp(-h(z)) (pseudo-Huber h) that concentrates nominal data and pushes outlier-exposure samples away; recovers Deep SVDD with c = 0 when there are no anomalies",
                  "An empirical comparison of unsupervised, unsupervised-OE and supervised-OE (plain binary classifier against auxiliary outliers) approaches on the one-vs-rest image AD benchmarks, varying OE set size, OE diversity and blurring of OE images"],
     "claims": [
         ("Terminology: the paper delineates unsupervised AD (trained on mostly nominal data), unsupervised OE (unsupervised methods adapted to incorporate auxiliary non-nominal data; elsewhere called semi-supervised AD) and supervised OE (a standard classifier discerning nominal data from an auxiliary non-nominal dataset).",
          "Section 1 (Introduction)",
          "Unsupervised OE: Adaptations of unsupervised methods that incorporate auxiliary data that is not nominal."),
         ("Main finding: using the same experimental OE setup as Hendrycks et al. (2019b), a standard classifier is able to outperform the authors' listed state-of-the-art AD methods on the one-vs-rest benchmarks on MNIST and CIFAR-10.",
          "Section 1 (Introduction)",
          "We ﬁnd that, using the same experimental OE setup as Hendrycks et al. (2019b), a standard classiﬁer is able to outperform current state-of-the-art AD methods on the one vs. rest AD benchmarks on MNIST and CIFAR-10."),
         ("Few OE samples suffice: with 128 OE samples a classifier is competitive with state-of-the-art unsupervised methods on CIFAR-10 one-vs-rest, and with only 64 OE samples a classifier outperforms unsupervised methods (with or without OE) on the ImageNet one-vs-rest benchmark of Hendrycks et al. (2019b). The authors say this seems to contradict the common wisdom that anomalies are unconcentrated and hard to characterize with data.",
          "Section 1 (Introduction)",
          "With only 64 OE samples a classiﬁer outperforms unsupervised methods (with or without OE) on the ImageNet one vs. rest benchmark (Hendrycks et al., 2019b)."),
         ("Benchmark critique: the one-vs-rest benchmark (one class nominal, the remaining classes anomalous at test time) on these datasets is, according to the authors, used as a litmus test in virtually all deep AD papers published at top-tier venues.",
          "Section 1 (Introduction)",
          "This benchmark applied to the aforementioned datasets is used as a litmus test in virtually all deep AD papers published at top-tier venues"),
         ("OE data assumption: the nominal and OE training data are exactly those used by Hendrycks et al. (2019b) and contain no representatives of the ground-truth anomaly classes (EMNIST-Letters for MNIST, 80 Million Tiny Images without CIFAR-10/100 for CIFAR-10, ImageNet-22K without ImageNet-1K for 30 ImageNet-1K classes); the OE data is not tailored to the test anomalies. Drawing OE samples from just one class (not present as anomaly at test time) already gave good performance on CIFAR-10 (Appendix B).",
          "Section 1 (Introduction)",
          "The OE data is not tailored to be representative of the anomalies used at test time."),
         ("Deep SAD (Ruff et al., 2020, by overlapping authors) is classed as an unsupervised OE approach; the authors' HSC modification is reported to significantly improve on Deep SAD and is used as the representative unsupervised OE method.",
          "Section 2 (Deep One-Class Classification)",
          "We found this modiﬁcation to signiﬁcantly improve upon the performance of Deep SAD and use it in our experiments as a representative of the unsupervised OE approach to AD."),
         ("Multiscale hypothesis: increasingly blurring OE images (removing small-scale features) quickly drops performance on ImageNet and CIFAR-10, and with sufficient blurring HSC performs better than BCE; on MNIST HSC outperforms BCE at any degree of blurring. The authors take this to suggest two regimes: on high-dimensional multiscale images OE samples are highly informative and standard and hypersphere classification perform similarly well, while on low-dimensional images like MNIST hypersphere classification performs better, reflecting the classic intuition that AD requires a compact model.",
          "Section 3.3",
          "This suggests that their are two regimes in deep image AD"),
         ("Protocol: all of the authors' implementations (HSC, Deep SAD, Focal, BCE) use the same network per setting (LeNet-style for MNIST/CIFAR-10, the WideResNet of Hendrycks et al. (2019b) for ImageNet), Adam with fixed epoch counts and learning-rate milestones, batches balanced to 128 nominal and 128 OE samples, and data augmentation; Focal gamma = 2 as recommended by Lin et al. (2017). Evaluation is mean AUC over classes and seeds; no threshold is chosen. No description of how these hyperparameters were selected or of a validation set was found in the text (searched for valid, tun, select, hyperparam, grid, search).",
          "Appendix F",
          "We always use the same underlying network φθ in each experimental setting for our HSC, Deep SAD, Focal, and BCE implementations to control architectural effects."),
         ("Scope caveat: the authors do not claim that supervised OE is the solution to AD in general or that unsupervised OE has no utility, but suggest it may be time to move to more challenging benchmarks such as MVTec-AD.",
          "Section 4 (Conclusion)",
          "that it may be time for the community to move to more challenging benchmarks (e.g., MVTec-AD (Bergmann et al., 2019)) to gauge the signiﬁcance of deep AD works."),
     ],
     "notes": "Affiliations: Aignostics (work mostly done at TU Berlin), TU Berlin, TU Kaiserslautern, Korea University, MPII; Ruff and Vandermeulen contributed equally. Venue from the PDF first page ('Presented at the ICML 2021 Workshop on Uncertainty and Robustness in Deep Learning.') and the arXiv comment; a workshop presentation. Conflict of interest / self-citation: Deep SVDD and Deep SAD (arxiv-1906.02694) are by overlapping authors and are among the evaluated methods; Ruff et al. also wrote the review arxiv-2009.11732. Results marked * (DSVDD*, GT+*, Focal*, etc.) are taken from the literature rather than re-run; the authors say they are unsure why Focal* from Hendrycks et al. (2019b) is so poor since that code is not public, and found Focal insensitive to gamma (Appendix E). Seed counts differ between the Table 2 caption (30 classes and 10 seeds) and the Figure 2(b)/3 captions (30 classes x 5 seeds) for ImageNet. OE-size, OE-diversity and blurring results are figures only. If fewer OE samples than the OE batch size (128), sampling is with replacement and augmentation adds variety. Results not recorded."},

    {"id": "arxiv-1812.04606",
     "title": "Deep Anomaly Detection with Outlier Exposure",
     "authors": ["Dan Hendrycks", "Mantas Mazeika", "Thomas Dietterich"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1812.04606", "code": "https://github.com/hendrycks/outlier-exposure"},
     "tasks": ["anomaly-detection", "dataset-shift-detection", "image-classification"],
     "fam": ["deep-learning"], "par": ["semi-supervised", "supervised"],
     "proposes": ["Outlier Exposure (OE): training (usually fine-tuning) an anomaly/OOD detector with an extra loss on an auxiliary dataset of real, diverse outliers that is disjoint from the test-time outliers, e.g. cross-entropy to the uniform distribution for the maximum softmax probability detector and a margin ranking loss on log-likelihoods for density estimators"],
     "claims": [
         ("Setting: the distribution of test-time outliers D_out is assumed unknown; the model is trained to distinguish in-distribution data from an OE dataset that is disjoint from the test outliers, and the learned heuristics are found to generalize to unseen outlier distributions.",
          "Outlier Exposure",
          "Thus, we consider the realistic setting where Dout is unknown."),
         ("OE loss is a design choice per detector: for the maximum softmax probability baseline (Hendrycks & Gimpel, 2017), L_OE is the cross-entropy from f(x') to the uniform distribution (following Lee et al., 2018); for density estimation without labels, a margin ranking loss on the log probabilities.",
          "Outlier Exposure",
          "For example, when using the maximum softmax probability baseline detector (Hendrycks & Gimpel, 2017), we set LOE to the cross-entropy from f(x′) to the uniform distribution (Lee et al., 2018)."),
         ("Hyperparameter selection: unlike Liang et al. (2018) and Lee et al. (2018), hyperparameters are not tuned for each test outlier distribution; the OE weight lambda was determined early in experimentation with validation outlier distributions (Appendix A), and chosen so that the impact on classification accuracy is negligible: lambda = 0.5 for vision and 1.0 for NLP.",
          "Multiclass Classification",
          "In particular, we use λ = 0.5 for vision experiments and λ = 1.0 for NLP experiments."),
         ("Validation outliers used for tuning are uniform noise and synthetic corruptions of in-distribution data (arithmetic/geometric means of image pairs, jigsaw patch permutation, speckle noise, RGB ghosting, channel inversion), i.e. no samples from the test outlier datasets.",
          "Appendix A",
          "generated by corrupting in-distribution data, so that the data becomes out-of-distribution."),
         ("Metrics: AUROC, AUPR and FPR at N% TPR (FPR95 for vision, FPR90 for NLP), with OOD examples as the positive class; AUROC and AUPR summarize performance across thresholds while FPRN represents performance at one strict threshold.",
          "Section 4.1",
          "Whereas the previous two metrics represent the detection performance across various thresholds, the FPRN metric represents performance at one strict threshold."),
         ("Synthetic outliers: distorting images with noise and using them as OE did not help, since the classifier quickly memorized the statistical pattern; compared with a classifier trained with GAN-generated outliers (Lee et al., 2018's code with default hyperparameters, one model for all test distributions), real and diverse OE data gave large gains.",
          "Section 4.3",
          "Note that we made an attempt to distort images with noise and use these as outliers for OE, but the classiﬁer quickly memorized this statistical pattern and did not detect new OOD examples any better than before (Hafner et al., 2018)."),
         ("Diversity of the OE data matters, not just size: a CIFAR-100 classifier with CIFAR-10 as OE hardly improves over the baseline, and for a CIFAR-10 classifier exposed to 10, 30 and 50 CIFAR-100 classes the average AUPR is 78.5%, 85.1% and 85.3%, with further classes barely helping. Experiments often used around 1% of 80 Million Tiny Images, and using only 50,000 examples gave negligible degradation.",
          "Section 5 (Discussion)",
          "This suggests that dataset diversity is important, not just size."),
         ("Closeness: the OE data need not be close to the test outliers, but closeness of the OE data to the in-distribution data can matter; in NLP, without preprocessing the OE data the network may discover easy cues and optimize the OE objective in unintended ways. Online hard example mining improved the hardest anomalies but slightly worsened detection of anomalies like noise, so hard or close-to-distribution examples do not necessarily teach all useful heuristics.",
          "Section 5 (Discussion)",
          "Without preprocessing, the network may discover easy-to-learn cues which reveal whether the input is in- or out-of-distribution, so the OE training objective can be optimized in unintended ways."),
         ("Density estimation: PixelCNN++ trained on CIFAR-10 (score: bits per pixel) without OE unexpectedly assigns lower BPP to SVHN images than to CIFAR-10 images; fine-tuning with OE (a margin loss on the log-likelihood difference) is reported to significantly improve results for all test outlier datasets.",
          "Density Estimation",
          "Notice that PixelCNN++ without OE unexpectedly assigns lower BPP from SVHN images than CIFAR-10 images."),
     ],
     "notes": "Affiliations: UC Berkeley, University of Chicago, Oregon State University. Venue from the PDF header ('Published as a conference paper at ICLR 2019') and the arXiv comment. Setting is OOD detection for (mostly) multiclass classifiers trained on labeled in-distribution data (SVHN, CIFAR-10/100, Tiny ImageNet, Places365, 20 Newsgroups, TREC, SST) plus language models; it is not a one-class benchmark. OE datasets: 80 Million Tiny Images with CIFAR images removed, ImageNet-22K with ImageNet-1K removed, WikiText-2. Base rate of test outliers to test inliers is 1:5 in all experiments. Most results are averages over 10 runs. OE is mostly applied by fine-tuning a pre-trained network (10 epochs for vision); Appendix C reports training from scratch with OE tends to be better but needs more time and sometimes more GPU memory. Related work notes that Liang et al. (2018) and Lee et al. (2018) tune on samples from each test outlier distribution, so results are not directly comparable. Builds on the MSP baseline by the first author (arxiv-1610.02136). Section 4.1 is confirmed by 'described in Section 4.1', 4.3 by 'we found in Section 4.3' and 5 by 'In Section 5 we note'; other locations use section names. Results tables not recorded."},

    {"id": "arxiv-1805.10917",
     "title": "Deep Anomaly Detection Using Geometric Transformations",
     "authors": ["Izhak Golan", "Ran El-Yaniv"],
     "year": 2018, "venue": "NeurIPS 2018", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1805.10917", "code": "https://github.com/izikgo/AnomalyDetectionTransformations"},
     "tasks": ["anomaly-detection"],
     "fam": ["deep-learning"], "par": ["self-supervised"],
     "proposes": ["GEOM: train a multi-class classifier (WRN) to predict which of 72 geometric transformations (compositions of horizontal flip, translations and rotations) was applied to normal training images; at test time apply all transformations and score normality with the combined log-likelihood of the softmax outputs under per-transformation Dirichlet distributions fitted on the training images (or a simplified mean-softmax score)"],
     "claims": [
         ("Setting: only a sample of normal images is given (no contamination, no labeled anomalies); the authors note that the positive-and-unlabeled variant with a contaminated unlabeled sample is easier (citing Blanchard et al.) and focus on the basic, harder version for vision, where deep models are essential.",
          "Introduction",
          "In the present paper, we focus on the basic (and harder) version of anomaly detection, and consider only machine vision applications for which deep models (e.g., convolutional neural networks) are essential."),
         ("Normality score: the combined log-likelihood of the softmax responses on each transformed image, under a naive (typically incorrect) assumption that the per-transformation conditional distributions are independent, each approximated by a Dirichlet whose parameters are estimated from the training set S; the authors note an independent image set for that estimation may improve performance, and a simplified mean-softmax score was only slightly worse.",
          "Section 4.2 (Dirichlet Normality Score)",
          "under a naïve (typically incorrect) assumption that all of these conditional distributions are independent"),
         ("Threshold and metric: the paper learns only the scoring function and completely ignores the choice of anomaly threshold, measuring performance with AUROC computed from the ground-truth test labels (AUPR in the supplementary material). Protocol: one-vs-all on CIFAR-10, CIFAR-100 (20 superclasses), Fashion-MNIST and CatsVsDogs, training only on the normal class's training images.",
          "Experimental Protocol",
          "As stated in Section 3, we completely ignore the problem of choosing the appropriate anomaly threshold (λ) on the normality score, and quantify performance using the area under the ROC curve metric, which is commonly utilized as a performance measure for anomaly detection models."),
         ("Hyperparameters: WRN depth/width (10, 4 for 32x32 data; 16, 8 for CatsVsDogs) were selected before any experiment and fixed for all runs; Adam with default hyperparameters, batch 128, ceil(200/|T|) epochs on the self-labeled set. A footnote says 16, 8 improved CIFAR-10 results but smaller values were chosen for computational cost.",
          "Hyperparameters and Optimization Methods",
          "These hyperparameters were selected prior to conducting any experiment, and were ﬁxed for all runs."),
         ("Baseline advantage: OC-SVM (raw pixels and on convolutional-autoencoder codes) gets an unfair advantage by choosing nu and gamma in hindsight to maximize AUROC over a grid, i.e. the tuning was given a two-class problem; the authors note methods exist to tune without hindsight and are likely to degrade OC-SVM. One-Class Deep SVDD (E2E) results on CIFAR-10 are copied from its paper; OC-SVM and ADGAN were run once, the others over five runs.",
          "Baseline Methods",
          "Note that the hyperparameter optimization procedure has been provided with a two-class classiﬁcation problem."),
         ("Classical vs deep by image size: the relative advantage is most prominent on larger images; on CatsVsDogs (64x64) all baselines, including the hindsight-tuned OC-SVM variants, are only slightly better than random guessing, whereas on smaller images the baselines can perform much better; on Fashion-MNIST all methods except DAGMM performed very well.",
          "Results",
          "Our relative advantage is most prominent when focusing on the larger images."),
         ("Failure mode: on CIFAR-100 superclasses the method was challenged by the diversity inside the normal class and did not perform well on a few normal classes (e.g. non-insect invertebrates, insects, household electrical devices).",
          "Results",
          "Inspecting the results on CIFAR-100 (where 20 super-classes deﬁned the partition), we observe that our method was challenged by the diversity inside the normal class."),
         ("Choice of transformations: only geometric transformations are used; non-geometric ones (Gaussian blur, sharpening, gamma correction) degraded performance in early stages and were abandoned. The authors hypothesize this is because they can eliminate important features, and speculate that effectiveness depends on preserving spatial information and on the classifier being able to predict the applied transformation.",
          "Section 6",
          "In the earlier stages of this work, we tried a few non-geometric transformations (e.g., Gaussian blur, sharpening, gamma correction), which degraded performance and we abandoned them altogether."),
         ("Invariance failure mode (MNIST, two transformations): with normal digit '8' and anomaly '3' using identity and horizontal flip, the method did not perform well (AUROC 0.646), which the authors attribute to the invariance of '8' to horizontal flip; with normal '3' vs anomaly '8' it achieved 0.957, and with '8' vs '3' using a 7-pixel translation 0.919.",
          "Section 6",
          "It can be expected that due to the invariance of ‘8’ to horizontal ﬂip, the classiﬁer will have difﬁculties learning distinguishing features."),
     ],
     "notes": "Affiliation: Technion. Venue from the PDF footer ('32nd Conference on Neural Information Processing Systems (NIPS 2018), Montréal, Canada.'); recorded as NeurIPS 2018 following the repository convention. The paper calls its training set 'self-labeled' rather than 'self-supervised'; the self-supervised paradigm tag is applied by analogy (arxiv-2006.00339 describes it as self-supervision). Novelty setting: clean normal training data only. Also reports OOD detection in labeled multi-class data (CIFAR-10 vs resized Tiny ImageNet) with a two-headed WRN using the simplified score, compared to ODIN numbers. DSEBM and DAGMM were run with deeper architectures than in their original papers. Section 3 (Problem Statement) confirmed by 'As stated in Section 3'; Section 4.2 by 'as described in section 4.2'; Section 6 by 'see also Section 6 discussing the intuition'. Results table not recorded."},
]

from topic_ad_common import BASE_NOTE, CREATED  # noqa: E402

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
