import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tabdl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1810.11921",
     "title": "AutoInt: Automatic Feature Interaction Learning via Self-Attentive Neural Networks",
     "authors": ["Weiping Song", "Chence Shi", "Zhiping Xiao", "Zhijian Duan", "Yewen Xu", "Ming Zhang", "Jian Tang"],
     "year": 2018, "venue": "CIKM 2019", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1810.11921", "code": "https://github.com/DeepGraphLearning/RecommenderSystems"},
     "tasks": ["tabular-classification"],
     "fam": ["tabular-attention", "deep-learning"], "par": ["supervised"],
     "proposes": ["AutoInt: categorical fields (one-hot, or multi-hot averaged) and numerical fields (scalar times a per-field vector) are embedded into the same low-dimensional space; stacked interacting layers (multi-head key-value self-attention over feature fields with residual connections and ReLU) model feature interactions of increasing order; the concatenated outputs go through a sigmoid for click-through-rate prediction",
                  "AutoInt+: AutoInt jointly trained with a two-layer feed-forward network (implicit interactions)"],
     "claims": [
         ("Setting: the paper addresses click-through rate (CTR) prediction, defined as predicting the probability that user u clicks item v from the concatenation x of user and item features, with categorical features one-hot encoded; the authors note that x is very sparse and high-dimensional, so off-the-shelf classifiers such as logistic regression overfit easily.",
          "Section 3 (Problem Definition)",
          "The problem of click-through rate prediction aims to predict the probability of user u clicking on item v according to the feature vector x."),
         ("Motivation: DNN-based CTR models learn high-order interactions with fully-connected layers, which the authors say has two limitations: fully-connected networks have been shown inefficient at learning multiplicative interactions (citing Beutel et al. [4]), and implicit interactions lack a good explanation of which feature combinations are meaningful.",
          "Introduction",
          "First, fully-connected neural networks have been shown inefficient in learning multiplicative feature interactions [4]."),
         ("Embedding: each categorical field is embedded with a field-specific embedding matrix (multi-valued fields are the average of the value embeddings), and each numerical field m is embedded as v_m x_m with a learned field vector v_m, so that categorical and numerical features live in the same low-dimensional space and can interact.",
          "Section 4 (Embedding Layer)",
          "To allow the interaction between categorical and numerical features, we also represent the numerical features in the same low-dimensional feature space."),
         ("Interacting layer: attention weights between feature fields are computed per head from inner products of query/key projections (key-value attention over fields, not over samples), heads are concatenated, and a residual projection plus ReLU is added; the authors argue that stacking layers lets the maximum interaction order grow with depth, so a few layers suffice for high-order interactions.",
          "Section 4 (Analysis Of AutoInt)",
          "Therefore a few interacting layers will suffice to model high-order feature interactions."),
         ("Evaluation protocol: four public CTR/recommendation data sets (Criteo, Avazu, KDD12, MovieLens-1M, the last two binarized), infrequent features merged into '<unknown>', a random 80% train split with the rest split equally into validation and test, embedding size 16 and batch size 1024 for all methods, grid search of hyperparameters for baselines after fixing their structures, and results averaged over 10 runs; only CTR-style models (LR, FM, AFM, DeepCrossing, NFM, CrossNet, CIN, HOFM) are compared, with no gradient-boosted trees.",
          "Section 5 (Experiment Setup)",
          "Third, we randomly select 80% of all samples for training and randomly split the rest into validation and test sets of equal size."),
         ("The authors state that a slightly higher AUC or lower Logloss at the 0.001 level is regarded as significant for CTR prediction, as pointed out in existing works.",
          "Section 5 (Evaluation Metrics)",
          "It is noticeable that a slightly higher AUC or lower Logloss at 0.001-level is regarded significant for CTR prediction task, which has also been pointed out in existing works [8, 11, 38]."),
         ("Within-paper relation: AutoInt achieves the best performance over the baselines on three of four data sets; on Avazu CIN is a little better in AUC while AutoInt has lower Logloss. The authors also note that some deep models (DeepCrossing, NFM) do not guarantee improvement over FM and AFM, which they say may be attributed to learning interactions implicitly.",
          "Section 5.2",
          "AutoInt achieves the best performance overall baseline methods on three of four real-world data sets."),
         ("Explainability evidence is visual: attention-score heat maps on MovieLens-1M for one case and averaged over the data, from which the authors read combinations such as <Gender, Genre> and <Age, Genre> as strongly correlated and call them explainable rules for this domain.",
          "Explainable Recommendations (RQ3)",
          "We can see that AutoInt is able to identify the meaningful combinatorial feature <Gender=Male, Age=[18-24), MovieGenre=Action&Triller> (i.e., red dotted rectangle)."),
         ("Limitation and future work: the model is evaluated only on CTR prediction; the authors plan to extend AutoInt to general machine learning tasks such as regression, classification and ranking, and to incorporate contextual information for online recommender systems.",
          "Section 6 (Conclusion and Future Work)",
          "Besides, we also plan to extend AutoInt for general machine learning tasks, such as regression, classification and ranking."),
     ],
     "notes": "Affiliations: Peking University, UCLA, Mila/HEC Montreal. Venue from the PDF (ACM Reference Format: 'Proceedings of the 28th ACM International Conference on Information and Knowledge Management (CIKM ’19)') and the arXiv comment 'Accepted at CIKM2019'; year is the first arXiv version (2018). Tagged tabular-classification because CTR prediction is binary classification on sparse categorical/numerical fields; the paper's setting is recommender/advertising data, not general tabular benchmarks, and GBDTs are not among the baselines. Section numbers come from cross-references in the text (Sections 2-6, 5.2, 5.5); subsection names are used otherwise. AutoInt's dropout was grid-searched only on MovieLens-1M ('we found dropout is not necessary for other three large data sets'); AutoInt's own architecture (3 layers, d'=32, 2 heads) is described as a default setting, while baselines got grid search once structures were fixed. Significance is an unpaired t-test against the strongest baseline (Table 2 footnote). Run time (Figure 4), parameter counts (Table 3), ablations (Table 4, Figures 5-6) and AutoInt+ results (Table 5) are not recorded. Later reuse: DCN V2 (arxiv-2008.13535) reran AutoInt as a tuned baseline."},

    {"id": "arxiv-2008.13535",
     "title": "DCN V2: Improved Deep & Cross Network and Practical Lessons for Web-scale Learning to Rank Systems",
     "authors": ["Ruoxi Wang", "Rakesh Shivanna", "Derek Z. Cheng", "Sagar Jain", "Dong Lin", "Lichan Hong", "Ed H. Chi"],
     "year": 2020, "venue": "WWW 2021", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2008.13535"},
     "tasks": ["tabular-classification"],
     "fam": ["deep-learning", "tabular-mlp"], "par": ["supervised"],
     "proposes": ["DCN-V2 cross layer x_{l+1} = x0 ⊙ (W_l x_l + b_l) + x_l with a full weight matrix (DCN is the special case W = 1 w^T), combined with a ReLU deep network in a stacked or parallel structure; accepts embeddings of different sizes",
                  "DCN-Mix: a mixture of low-rank cross layers (U V^T experts, optional nonlinearity in the projected space) combined by a gating function, for a better cost/accuracy trade-off"],
     "claims": [
         ("Motivation: in models serving web-scale traffic with billions of training examples, the original DCN's cross network showed limited expressiveness, and many production models still rely on feed-forward networks to learn feature crosses inefficiently.",
          "Abstract",
          "Unfortunately, in models that serve web-scale traffic with billions of training examples, DCN showed limited expressiveness in its cross network at learning more predictive feature interactions."),
         ("Architecture: an embedding layer, a cross network of cross layers modeling explicit bounded-degree crosses, and a deep network for implicit interactions, combined either stacked or in parallel; the authors state that the function class of DCN-V2 is a strict superset of DCN's, and that which combination works better is data dependent.",
          "Section 3",
          "The function class modeled by DCN-V2 is a strict superset of that modeled by DCN."),
         ("Low-rank motivation: the authors observe that the learned cross-layer matrix from a production model shows much faster singular-value decay than at initialization, and impose a low-rank structure (U V^T) on W, extended to a gated mixture of low-rank experts (DCN-Mix).",
          "Section 3 (Cost-Effective Mixture of Low-Rank DCN)",
          "In many settings, we indeed observe that the learned matrix is numerically low-rank in practice."),
         ("Synthetic study (mean RMSE over 5 runs on polynomial targets with inputs uniform on [-1, 1]): for simple cross patterns both DCN and DCN-V2 are accurate, for more complicated patterns DCN degrades while DCN-V2 remains accurate, and ReLU DNNs remain poor even when wider and deeper; the authors read this as suggesting DNNs are inefficient at modeling monomial patterns.",
          "Section 6",
          "This suggests the inefficiency of DNN in modeling monomial patterns."),
         ("Protocol: all models were implemented identically except for the feature-interaction component; every baseline got a coarse-level then a finer-level grid search over shared hyperparameters (learning rate, training steps, depth/width of hidden layers, L2) and model-specific ones, total parameters were capped at 1024^2 x 5, and the mean and standard deviation over 5 independent runs of the best configuration are reported. Public data: Criteo (first 6 days train, last day split into validation and test) and MovieLens-1M (random 80/10/10).",
          "Section 7 (Experiment Setup)",
          "For all the baselines, we conducted a coarse-level (larger-range) grid search over the hyper-parameters, followed by a finer-level (smaller-range) search."),
         ("Within-paper relation with a tuned DNN: the authors finely tuned the ReLU DNN with larger layers than in prior literature, and found that it performed neck to neck with most feature-interaction baselines and even outperformed some; once integrated with a DNN the gaps among baselines close up, which they say suggests the power of a well-tuned DNN. The baselines' numbers were also improved over those reported in previous papers.",
          "Section 7.3",
          "To our surprise, DNN performed neck to neck with most baselines and even outperformed certain models."),
         ("Hedged hypothesis: because a cross-layer-only network achieved the best LogLoss under each fixed memory budget on Criteo, the authors suggest cross layers may potentially replace ReLU layers entirely for certain applications, but state that significantly more analysis and experiments are needed to verify this.",
          "Section 7.4",
          "Obviously we need significant more analysis and experiments to verify the hypothesis."),
         ("Production case study (Google-internal data: sampled user logs with hundreds of billions of training examples, sparse vocabularies from 2 to millions, baseline a ReLU MLP): DCN-V2 yielded a 0.6% AUCLoss (1 - AUC) improvement over the production model, where 0.1% is considered significant for that model, and significant online gains on key metrics are reported without numbers.",
          "Section 8",
          "When compared with production model, DCN-V2 yielded 0.6% AUCLoss (1 - AUC) improvement."),
         ("Practical lessons from productionizing: insert cross layers between the input and the hidden layers; gains plateau beyond 2 cross layers; both stacking and concatenating cross layers work well; and low-rank DCN with rank (input size)/4 consistently preserved the accuracy of full-rank DCN-V2.",
          "Section 8 (Practical Learnings)",
          "We observed that using low-rank DCN with rank (input size)/4 consistently preserved the accuracy of a full-rank DCN-V2."),
         ("Cross layer (Eq. 1): x_{l+1} = x_0 ⊙ (W_l x_l + b_l) + x_l, where x_0 is the base (embedding) layer containing the original features of order 1, x_l and x_{l+1} are the input and output of the (l+1)-th cross layer, W_l is a learned d x d weight matrix and b_l a learned bias vector.", "Section 3.2", "The core of DCN-V2 lies in the cross layers that create explicit feature crosses."),
     ],
     "notes": "Affiliation: Google Inc. (all authors). Venue from the arXiv journal_ref ('In Proceedings of the Web Conference 2021 (WWW ’21)'); the arXiv PDF itself does not name the venue. Year is the first arXiv version (2020). Conflict of interest / data: the first author is the first author of the original DCN (reference [50], Wang, Fu, Fu and Wang, ADKDD'17), which is a baseline; the production results (Section 8, Table 8) are on proprietary Google data and cannot be reproduced; feature names in Figure 6(a) are hidden 'for proprietary reasons'. The paper's setting is CTR / learning-to-rank on sparse categorical plus dense features (tagged tabular-classification; MovieLens-1M is described as formalized as a regression problem but with binarized ratings and a log loss); GBDTs are not compared. Section numbers come from the PDF headings/cross-references (Sections 3, 4.1, 6, 7.2-7.6, 8; the tuning paragraph is referred to as Section 7.1.3). Interpretability: the authors say the cross-layer weight matrix W 'exactly reveals' which crosses were learned, with evidence only as visualizations (Figure 6) - not recorded as a claim. Table 5/6/7 numbers (LogLoss, AUC, params, FLOPS) are not recorded. Number-of-experts study: more lower-rank experts did not beat a single higher-rank expert, which the authors say might be caused by naive gating and optimization."},

    {"id": "arxiv-2305.18446",
     "title": "Trompt: Towards a Better Deep Neural Network for Tabular Data",
     "authors": ["Kuan-Yu Chen", "Ping-Han Chiang", "Hsin-Rung Chou", "Ting-Wei Chen", "Tien-Hao Chang"],
     "year": 2023, "venue": "ICML 2023", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2305.18446"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["deep-learning", "tabular-attention", "gradient-boosted-trees", "tree-ensembles"], "par": ["supervised"],
     "proposes": ["Trompt (Tabular Prompt): stacked Trompt Cells sharing one Trompt Downstream head; each cell derives sample-specific feature importances as a softmax over columns of (prompt embeddings fused with the previous cell's output) times (input-independent column embeddings), multiplies them with per-prompt expanded feature embeddings and sums over columns",
                  "Training sums the losses of the predictions from every cell; inference averages the cells' predictions"],
     "claims": [
         ("Motivation (citing Grinsztajn et al., 2022): on a recently published tabular benchmark, deep neural networks still fall behind tree-based models.",
          "Abstract",
          "However, based on a recently published tabular benchmark, we can see deep neural networks still fall behind tree-based models on tabular datasets (Grinsztajn et al., 2022)."),
         ("Design hypothesis: the authors argue that column importances in tabular data are not invariant across samples and can be grouped into multiple modalities; Trompt separates learning into intrinsic column information (analogous to a pre-trained model) and sample-specific feature importances (analogous to prompts), and learns separated column importances instead of focusing on interactions among columns as transformer-based models do.",
          "Section 2.3",
          "We argue that the column importances of tabular data are not invariant for all samples and can be grouped into multiple modalities."),
         ("Architecture: column embeddings and prompt embeddings are input independent and trainable; prompt embeddings are fused with the previous cell's output (a zero tensor for the first cell) and multiplied with the column embeddings, followed by a softmax over the column axis, to obtain feature importances per prompt; categorical features are embedded with an embedding layer and numerical features with a dense layer, as in prior work.",
          "Section 3.1.1",
          "Notice that the column embeddings are not connected to the input and the prompt embeddings are fused with the previous cell’s output."),
         ("Protocol on Grinsztajn45 (45 datasets, medium- and large-sized, numerical-only and heterogeneous): the authors follow its train/test split, preprocessing and metrics, omit MLP and HistGradientBoostingTree because of incomplete results in the benchmark, add LightGBM and CatBoost, and give Trompt a search space of only 40 parameter combinations, smaller than the hundreds explored for the other models, due to limited computing resources.",
          "Appendix A.4",
          "Due to limited computing resources, we have chosen a small search space (Table 30) consisting of 40 parameter combinations."),
         ("Search-curve handling: because the benchmark truncates every model's random search at the minimum iteration count among compared models, the authors duplicated (oversampled) Trompt's grid-search results beyond the lowest iteration count so that the other models, whose search results come from Grinsztajn45, keep their original number of search iterations.",
          "Appendix A.4",
          "To avoid unfairly truncating random search results of other models, and compromising the low search iterations of Trompt, we duplicated the grid search results of Trompt to exceed the lowest search iteration count among the models provided by Grinsztajn45."),
         ("Within-paper relation, classification: on medium-sized tasks Trompt's curve is above the other deep models (SAINT, FT-Transformer, ResNet) and narrows the gap to tree-based models, seeming to join the leading cluster of four tree-based models on heterogeneous features; on large-sized tasks tree-based models remain in the lead but the gap to deep networks is obscure, which the authors say echoes that deep networks require more samples.",
          "Section 4.2.1",
          "On the large-sized classification tasks, tree-based models remain the leading positions but the gap to deep neural networks is obscure."),
         ("Within-paper relation, regression: on medium-sized tasks Trompt is comparable to random forest with numerical features only, and on heterogeneous features it narrows the gap but is below all tree-based models; on large-sized numerical-only tasks it is slightly worse than SAINT and FT-Transformer at the end of the search.",
          "Section 4.2.2",
          "On the tasks with heterogeneous features, Trompt narrows the gap but is below all the tree-based models."),
         ("Interpretability: following TabNet's setup, feature importances (prompt-weighted Mimportance averaged over cells) are visualized on Syn2/Syn4 (20 randomly picked test samples) and compared with tree models' top-3 features on the mushroom dataset; the authors conclude Trompt's important features are consistent with those of tree-based models.",
          "Section 4.4",
          "Overall speaking, the important features selected by Trompt are consistent with those by tree-based models, and can therefore be used in various analyses that are familiar in the field of machine learning."),
         ("On datasets chosen by FT-Transformer, Trompt was not hyperparameter-searched, FT-Transformer numbers were taken from its original paper, results are averaged over three seeds, and Trompt is generally comparable or slightly inferior to FT-Transformer with default hyperparameters; on SAINT's datasets numbers were likewise copied from SAINT's paper and Trompt's are from a single seed.",
          "Appendix B.2",
          "It’s important to note that due to limited computing resources, Trompt did not undergo hyperparameter search."),
     ],
     "notes": "Affiliations: SinoPac Holdings (all authors) and National Cheng Kung University (Chang). Venue from the PDF footer ('Proceedings of the 40th International Conference on Machine Learning, Honolulu, Hawaii, USA. PMLR 202, 2023') and the arXiv comment 'ICML'23 (poster)'. The arXiv author list gives 'Tien-Hao Chang'; the PDF prints 'Darby Tien-Hao Chang' - the arXiv form is recorded. No conflict of interest found: none of the baselines (Grinsztajn45 models, LightGBM, CatBoost, FT-Transformer, SAINT) are by these authors. Main comparisons are figure-only (normalized score vs number of search iterations, Figures 1, 5-8); numbers in Appendix B.1 tables are not recorded. The authors note the flat curve 'suggests' Trompt performs well with default hyperparameters and that its performance after an exhaustive search is left for future exploration (Section 4.2.1). Appendix C: standardization of regression targets gave better Trompt results than the benchmark's quantile transformation, but Section 4.2 used the Grinsztajn45 configuration. LightGBM search space follows practitioners' blog posts and CatBoost follows FT-Transformer (Appendix F). The tabular-attention tag reflects the attention-based baselines (FT-Transformer, SAINT) and Trompt's softmax-over-columns importances; the authors contrast Trompt with self-attention (Section 5.1)."},

    {"id": "arxiv-2301.02819",
     "title": "ExcelFormer: A neural network surpassing GBDTs on tabular data",
     "authors": ["Jintai Chen", "Jiahuan Yan", "Qiyuan Chen", "Danny Ziyi Chen", "Jian Wu", "Jimeng Sun"],
     "year": 2023, "venue": "KDD 2024", "version": "arXiv v8",
     "links": {"arxiv": "https://arxiv.org/abs/2301.02819", "doi": "https://doi.org/10.1145/3637528.3671893",
               "code": "https://github.com/whatashot/excelformer"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["tabular-attention", "deep-learning", "gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["Semi-permeable attention (SPA): self-attention over feature tokens with a fixed mask, from mutual-information feature importance, that lets only more informative features pass information to less informative ones; with interaction-attenuated initialization (SPA weight variance scaled by gamma = 1e-4)",
                  "GLU-based attentive feed-forward network (tanh gating) replacing the Transformer MLP, and a GLU feature embedding",
                  "Hid-Mix (swapping embedding dimensions between two samples) and Feat-Mix (swapping features, labels mixed by mutual-information importance) data augmentation"],
     "claims": [
         ("The paper names three drawbacks of deep tabular models, following Grinsztajn et al. [13]: (P1) lack of rotational variance, (P2) large data demand, and (P3) over-smooth solutions; SPA targets P1, the tabular Mixup variants target P2, and the attentive feed-forward network targets P3.",
          "Abstract",
          "We delve into three key drawbacks of deep tabular models, encompassing: (P1) lack of rotational variance property, (P2) large data demand, and (P3) over-smooth solution."),
         ("SPA: an unoptimizable mask built from feature importance (mutual information) blocks attention from a less informative feature to a more informative one, so information flows only from more to less informative features while pathways between any two features remain; the authors argue this partially disrupts DNNs' rotational invariance.",
          "Solving (P1) with Semi-Permeable Attention",
          "In this way, only more informative features are permitted to propagate information to the less informative ones, and the reverse is not allowed."),
         ("Attentive feed-forward network: because the two-layer MLP feed-forward network of Transformers has lesser non-linear fitting capability for irregular feature-target relationships, it is replaced by a GLU layer with tanh instead of sigmoid; the authors say both use two fully connected layers and have similar computational cost.",
          "Solving (P3) with GLU layer",
          "Therefore, we replace the vanilla FFN by a Gated Linear Unit (GLU) layer."),
         ("Data augmentation: the authors say vanilla Mixup regularizes DNNs toward linear behavior between samples, which may conflict with irregular target functions; Hid-Mix swaps random embedding dimensions between two samples and Feat-Mix swaps random features, mixing labels by the mutual-information importance of the swapped features.",
          "Solving (P2) with Data Augmentation",
          "To address this challenge, we introduce two Mixup variants, Hid-Mix and Feat-Mix, which mitigate the conflicts in creating samples."),
         ("Datasets: 96 small datasets (fewer than 10,000 samples) from the Taptap dataset benchmark and 21 larger public datasets ranging from over 10,000 to 581,835 samples; data are split randomly 80% train / 20% test (20% of training held out for validation), with the same split for all approaches, and ranks are averaged over 5 seeds.",
          "Experimental Setups",
          "A total of 96 small datasets sourced from the Taptap dataset benchmark2 were utilized."),
         ("Tuning protocol: XGBoost and CatBoost follow Gorishniy et al. [12] with the maximum number of trees raised from 2000 to 4096 and tuning iterations from 100 to 500 (Optuna); TransTab and XTab use default hyperparameters because their tuning spaces are not given; FT-Transformer, SAINT and TabPFN on large datasets use the hyperparameters of their papers; on small datasets 50 tuning iterations are run per dataset; ExcelFormer is reported with defaults, 'Mix Tuned' (only augmentation hyperparameters) and 'Fully Tuned' (50 iterations).",
          "Experimental Setups (Compared Models)",
          "from 2000 to 4096 and the number of tuning iterations from 100 to 500, which give a more stringent setting and better performances."),
         ("Within-paper relation on the 96 small datasets (average rank): ExcelFormer outperforms all hyperparameter-tuned baselines (XGBoost, CatBoost, FT-Transformer, MLP, DCN v2, AutoInt, SAINT) whether or not its own hyperparameters are tuned; even without Feat-Mix and Hid-Mix it still outperforms previous approaches.",
          "Section 6.2",
          "See Table 1, our ExcelFormer consistently outperforms other models that undergo dataset-adaptive hyperparameter tuning, regardless of whether the hyperparameters of the ExcelFormer are tuned or not, which underscores the superiority of our proposed ExcelFormer."),
         ("On the 21 larger datasets only XGBoost, CatBoost and FT-Transformer are compared (others excluded for relatively inferior performance and computational load), each with default and tuned hyperparameters; the authors report ExcelFormer outperforms them under both settings and that the default Hid-Mix version is comparable to tuned prior models.",
          "Section 6.2",
          "We excluded other models from the comparison due to their relatively inferior performances and the significant computational load when dealing with large datasets."),
         ("Subgroup analysis (task type, sample size, number of features; all existing models tuned): default Hid-Mix ExcelFormer has the best rank in all subgroups except regression, where it slightly lags behind tuned XGBoost, while Mix Tuned ExcelFormer is best in all subgroups; runner-up positions are held by different models (TabPFN, FT-Transformer, XGBoost, CatBoost) in different subgroups.",
          "Can ExcelFormer be a sure bet solution across various types of datasets?",
          "As shown in Table 3, ExcelFormer with Hid-Mix (default) exhibits the best performance in all subgroups except for regression tasks, where it slightly lags behind hyperparameter-tuned XGboost."),
     ],
     "notes": "Affiliations: UIUC, Zhejiang University, University of Notre Dame. Version: arXiv v8 (25 Jul 2024), the KDD camera-ready; earlier arXiv versions may differ in protocol and results and were not read. Venue from the PDF ('KDD ’24, August 25–29, 2024, Barcelona, Spain', DOI 10.1145/3637528.3671893); year is the first arXiv version (2023). Conflict of interest: Jimeng Sun is a co-author of the compared TransTab (reference [44], Wang and Sun), which was run with default hyperparameters; the authors' own earlier tabular models (DANets, TabCaps, T2G-Former, refs [5], [6], [49]) are cited but not compared. Protocol caveats: (1) the tuning budget is stated inconsistently - XGBoost/CatBoost 500 tuning iterations (Experimental Setups; Tables 9-10), 'On small datasets, we tuned 50 iterations for each datasets', ExcelFormer tuned for 50 iterations (Appendix C), and Appendix D says 'even with just 50 iterations of hyperparameter tuning applied to XGBoost and CatBoost' for the timing comparison; which budget the GBDTs got on the 96 small datasets is not clear from the text. (2) ExcelFormer uses only one augmentation scheme per dataset ('our tests suggest that the effect of ExcelFormer on a certain dataset could be better by using only Feat-Mix or Hid-Mix'); how the scheme is picked for the default setting is reported as separate Feat-Mix (d) and Hid-Mix (d) rows. (3) A single 80/20 split per dataset; no statistical significance test was found in the text (searched for 'significan', 'p-value', 't-test', 'Wilcoxon'; 'significantly' is used only descriptively). Results are ranks in Tables 1-5 and per-dataset tables (Appendix G), not recorded. The headline 'surpassing GBDTs' is a within-paper rank relation under this protocol. Section numbers: only Sec. 6.2 is confirmed by cross-reference for the results; other locations use section names. The 'TapPFN'/'TapFPN' spelling in the text refers to TabPFN [17]."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
