import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ai_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1505.05770",
     "title": "Variational Inference with Normalizing Flows",
     "authors": ["Danilo Jimenez Rezende", "Shakir Mohamed"],
     "year": 2015, "venue": "ICML 2015", "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/1505.05770"},
     "tasks": ["posterior-inference", "generative-modeling"],
     "fam": ["variational-inference", "variational-autoencoders", "deep-learning"], "par": ["unsupervised"],
     "proposes": ["Normalizing-flow variational posteriors: a simple initial density (e.g. a diagonal Gaussian) is transformed by a chain of K invertible maps, and the log density of the result is the initial log density minus the sum of the log-det-Jacobian terms",
                  "Planar and radial flows: invertible transformations whose log-det-Jacobian can be computed in linear time, used inside amortized variational inference (an inference network outputs the initial-density and flow parameters)"],
     "claims": [
         ("Motivation: the approximating class is often limited (e.g. mean-field), so no solution can resemble the true posterior; the authors describe this as a widely raised objection to variational methods, since unlike MCMC, even asymptotically the true posterior cannot be recovered.",
          "Introduction",
          "even in the asymptotic regime we are unable recover the true posterior distribution"),
         ("Citing Turner & Sahani (2011), the authors list two problems of limited posterior approximations: under-estimation of the posterior variance (which can result in poor predictions and unreliable decisions) and biases in the MAP estimates of model parameters (e.g. in time-series models).",
          "Introduction",
          "The ﬁrst is the widely-observed problem of under-estimation of the variance of the posterior distribution"),
         ("Definition: a normalizing flow transforms a density through a sequence of invertible mappings by repeatedly applying the change-of-variables rule; for a chain of K maps the log density of z_K is ln q0(z0) minus the sum of the log absolute Jacobian determinants, and expectations under q_K can be computed as expectations under q0 without knowing q_K (LOTUS).",
          "Section 3",
          "A normalizing ﬂow describes the transformation of a probability density through a sequence of invertible mappings."),
         ("Planar flows f(z) = z + u h(w^T z + b) allow the log-det-Jacobian to be computed in O(D) time via the matrix determinant lemma; radial flows also allow linear-time determinants. The authors motivate this by noting that general invertible neural networks typically cost O(LD^3) for the Jacobian determinant and its gradients and involve matrix inverses that can be numerically unstable.",
          "Section 4.1",
          "For this mapping we can compute the logdet-Jacobian term in O(D) time (using the matrix determinant lemma):"),
         ("Not every planar or radial map is invertible. For planar flows with h = tanh, a sufficient condition is w^T u >= -1, which is enforced by reparameterizing u; for radial flows it suffices to impose beta >= -alpha, enforced by reparameterizing beta.",
          "Appendix A.1",
          "When using h(x) = tanh(x), a sufﬁcient condition for f(z) to be invertible is that"),
         ("Infinitesimal flows based on Langevin or Hamiltonian dynamics tend to the true posterior as the number of transitions grows, but the authors note a disadvantage: they need one or more evaluations of the likelihood and its gradients (depending on the number of leapfrog steps) per iteration at both training and test time.",
          "Section 5",
          "A disadvantage of using the Langevin or Hamiltonian ﬂow is that they require one or more evaluations of the likelihood and its gradients (depending in the number of leapfrog steps) per iteration during both training and test time."),
         ("Experimental protocol (deep latent Gaussian models): training follows a single-sample Monte Carlo gradient of an annealed free energy with inverse temperature beta_t = min(1, 0.01 + t/10000); minibatches of 100, RMSprop (learning rate 1e-5, momentum 0.9), 500,000 parameter updates, each experiment repeated 100 times; the marginal likelihood is estimated by importance sampling with 200 samples from the inference network. The table compares HVI and DARN numbers taken from other papers; for HVI the authors note the model specification is different, so it only indicates attainable performance.",
          "Section 6",
          "The true marginal likelihood is estimated by importance sampling using 200 samples from the inference network as in (Rezende et al., 2014, App. E)."),
         ("The authors argue that with normalizing flows the space of solutions is, in the asymptotic regime, rich enough to contain the true posterior, and that combined with consistency results for maximum likelihood (citing Wang & Titterington, 2004) this addresses objections to VI; they state that making such statements rigorous is an important line of future research.",
          "Section 7",
          "Making such statements rigorous is an important line of future research."),
     ],
     "notes": "Affiliation: Google DeepMind. Venue from the PDF footer ('Proceedings of the 32nd International Conference on Machine Learning, Lille, France, 2015'). Section numbers are from numbered headings in the PDF. The stated complexity of sampling plus log-det-Jacobian terms is O(LN^2) + O(KD) (Section 4.3). On the 2D toy densities the authors found that NICE and planar flows 'may achieve the same asymptotic performance' as flow length grows but planar flows need far fewer parameters (Section 6.1); MNIST/CIFAR-10 results are in a table/figures and are not recorded. No diagnostic of approximation quality other than the bound / KL / importance-sampled marginal likelihood is used."},

    {"id": "arxiv-2108.03782",
     "title": "Pathfinder: Parallel quasi-Newton variational inference",
     "authors": ["Lu Zhang", "Bob Carpenter", "Andrew Gelman", "Aki Vehtari"],
     "year": 2021, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2108.03782", "code": "https://github.com/LuZhangstat/Pathfinder"},
     "tasks": ["posterior-inference"],
     "fam": ["variational-inference", "mcmc"],
     "proposes": ["Pathfinder: run L-BFGS from a random initialization, form a normal approximation at each point of the optimization path (covariance from the L-BFGS low-rank-plus-diagonal inverse Hessian estimate), estimate each ELBO by Monte Carlo in parallel, and return draws from the approximation with the highest ELBO (lowest estimated KL)",
                  "Multi-path Pathfinder: several independent Pathfinder runs combined by Pareto-smoothed importance resampling (PS-IR), intended among other uses to initialize MCMC"],
     "claims": [
         ("Method: starting from a random initialization, Pathfinder locates normal approximations along a quasi-Newton (L-BFGS) optimization path, with local covariance from the optimizer's inverse Hessian estimates, and returns draws from the approximation with the lowest estimated KL divergence; the Monte Carlo KL estimates are embarrassingly parallel, while L-BFGS itself is the serial bottleneck.",
          "Abstract",
          "Pathﬁnder returns draws from the approximation with the lowest estimated Kullback-Leibler (KL) divergence to the true posterior."),
         ("Failure handling: in some cases the optimization path terminates at the initialization point and in others it fails to produce a positive definite inverse Hessian estimate; in both cases Pathfinder essentially fails, and it then returns the last iterate with infinite approximate log density so that the failed fit gets zero importance weight in multi-path Pathfinder.",
          "Section II.1",
          "In both of these settings, Pathﬁnder essentially fails."),
         ("Multi-path Pathfinder runs I independent Pathfinder instances and importance-resamples among their draws using Pareto-smoothed importance weights (building on Vehtari et al., 2019), so that paths stuck in minor modes, saddle points or plateaus can be down-weighted; the authors state that, as far as they know, Pareto smoothing had not been applied to importance resampling before.",
          "Section II.7",
          "As far as we know, Pareto smoothing has not been previously applied to importance resampling, but only to importance sampling."),
         ("Evaluation protocol: 20 posteriordb models, each with a reference posterior of 10,000 roughly independent draws; 100 repetitions each of single-path Pathfinder (defaults L_max = 1000, relative tolerance 1e-13, history J = 6, K = 5 ELBO draws, M = 100 draws), multi-path Pathfinder (I = 20 runs, R = 100 draws), Stan phase I warmup (NUTS, last of 75 iterations), and dense and mean-field ADVI with Stan default settings, all initialized from uniform(-2, 2); approximations are compared by 1-Wasserstein distance on the unconstrained scale.",
          "Section III.1",
          "We evaluate Pathﬁnder using the 20 models and data sets from posteriordb (Magnusson et al., 2021), each of which is supplied with reference posteriors in the form of 10,000 roughly independent draws."),
         ("Cost is counted as log density and gradient evaluations (implementation agnostic); since gradients typically take closer to 80% of compute for Stan phase I and ADVI (citing Carpenter et al., 2015), the authors conclude the other methods require around 30 to 50 times more operations than Pathfinder. These counts consider serial execution only; multi-path Pathfinder needs 20 times the evaluations of single-path plus resampling.",
          "Section III.1",
          "Because gradients are more expensive with automatic differentiation than log density evaluations, the results indicate that other methods require around 30 to 50 times more operations than Pathﬁnder."),
         ("Failure mode with multiple modes: on the hidden Markov model bball_drive_event_0 (multiple meaningful posterior modes) mean-field ADVI did much better than single-path Pathfinder, which the authors attribute to SGD noise letting ADVI escape minor modes that trap L-BFGS; multi-path Pathfinder removed this problem for that model.",
          "Section III.1",
          "The noise inherent in the stochastic gradient descent approach used by ADVI allows it to escape minor modes than can trap the L-BFGS optimizer used by Pathﬁnder."),
         ("For posteriors far from normal (e.g. the gp_pois_regr model), Pathfinder's draws concentrate in a small part of the high-probability region; the authors say this is expected because selecting the normal approximation by minimizing KL to the target favors more concentrated approximations, so Pathfinder tends to make a conservative guess.",
          "Section III.3",
          "Therefore, Pathﬁnder tends to make a conservative guess on the high probability region when the posterior cannot be well approximated by a normal distribution."),
         ("Limitations shown on challenging posteriors: results are sensitive to the initial distribution (underdispersed draws when started in a high-density region of a funnel); importance resampling cannot recover when all optimization paths are trapped in minor modes; on a 3075-parameter horseshoe logistic regression with many modes, optimization from random inits tends to find the mode at the origin, so in high dimensions Pathfinder can miss other relevant modes; weakly identified posteriors also frustrate it.",
          "Section III.3",
          "Thus, even though Pathﬁnder is ﬁnding a single region of high probability, in high dimensions it can fail to ﬁnd other relevant high probability modes."),
         ("Use for MCMC initialization: the stated motivation is to cheaply generate draws to initialize MCMC; initialization only needs draws inside the high-probability volume, not coverage of the posterior, and the authors say problems with Pathfinder's distributional approximation can be diagnosed with the Pareto-k statistic (citing Yao et al., 2018). In the birthday Gaussian process example, 5 of 20 randomly initialized adaptive HMC chains were trapped in minor modes, and Pathfinder initialization avoided them.",
          "Section IV",
          "Initialization to remove most of the transient bias of MCMC can succeed by producing draws within the high probability volume of the posterior without covering that posterior—it only requires draws to look reasonable."),
     ],
     "notes": "Affiliations: Columbia (Zhang, Gelman), Flatiron Institute (Carpenter), Aalto (Vehtari). No venue is stated in the arXiv PDF (dated May 17, 2022); none recorded. Conflict of interest: the compared ADVI is co-authored by Gelman (reference list: Kucukelbir, Tran, Ranganath, Gelman and Blei, 2017), the posteriordb benchmark is co-authored by Vehtari (Magnusson, Bürkner and Vehtari, 2021), and the compared ADVI/NUTS are Stan's implementations ('We use Stan's implementation of ADVI and dynamic HMC'); the PS-IR step builds on the authors' own PSIS (Vehtari et al.). Sensitivity analyses (L_max/tolerance, K = 30, J = 60, I in {5, 20, 40}) are shown as figures plus a few summary percentages in the text; not recorded. The 1-Wasserstein comparisons are figure-only. Single-path uses K = 5 ELBO draws; the paper reports Pathfinder approximations range from slightly worse to much better than ADVI and are comparable to short dynamic HMC chains (abstract, Introduction)."},

    {"id": "arxiv-1507.02646",
     "title": "Pareto Smoothed Importance Sampling",
     "authors": ["Aki Vehtari", "Daniel Simpson", "Andrew Gelman", "Yuling Yao", "Jonah Gabry"],
     "year": 2015, "venue": "JMLR", "version": "arXiv v9",
     "links": {"arxiv": "https://arxiv.org/abs/1507.02646"},
     "tasks": ["posterior-inference"],
     "fam": ["mcmc", "variational-inference"],
     "proposes": ["Pareto smoothed importance sampling (PSIS): fit a generalized Pareto distribution to the M largest importance ratios and replace them by the expected order statistics of the fitted distribution",
                  "Pareto k-hat diagnostic: the estimated shape parameter of the fitted tail, used as a finite-sample convergence-rate diagnostic for importance sampling and any Monte Carlo estimator, with a sample-size-dependent threshold min(1 - 1/log10(S), 0.7)"],
     "claims": [
         ("Method: the M largest importance ratios, M = floor(min(0.2S, 3 sqrt(S))), are used to fit a generalized Pareto distribution (k and sigma estimated with the method of Zhang and Stephens (2009) plus an additional weak prior, Appendix G); these ratios are replaced by the inverse CDF evaluated at (z - 1/2)/M, z = 1..M (an approximation of expected order statistics), truncated at the largest raw ratio.",
          "Section 2.2",
          "We propose a new method to stabilize the importance weights by replacing the M largest weights above the threshold u by a set of well-spaced values that are consistent with the tails of the importance distribution,"),
         ("Assumption: the method assumes, as a working assumption that usually cannot be verified, that the distribution of the ratios lies in the domain of attraction of an extremal distribution (citing Pickands (1975) that most textbook continuous distributions do); for finite S, k-hat can be read as saying the sample of ratios is not statistically distinguishable from one with tail index k-hat.",
          "Section 2.1",
          "Although in most cases we cannot verify that the distribution of rs lies in the domain of attraction for an extremal distribution, we will use this as a working assumption for building our method."),
         ("Warning rule in the algorithm: if the estimated shape k-hat exceeds min(1 - 1/log10(S), 0.7), PSIS reports that the importance sampling estimates are likely to be unstable or have high bias; for S > 2000 this threshold is 0.7.",
          "Section 2.2 (Algorithm 1)",
          "For S > 2000 this threshold is 0.7."),
         ("Why not 0.5: trusting importance sampling only when k-hat < 0.5 (finite variance, CLT holds) would be simple, but because the theory shows PSIS is valid for any integrable density, the authors consider requiring k-hat < 0.5 unnecessarily stringent; extensive experiments show PSIS is reliable (low bias, low variance) when k-hat < 0.7 for typical moderate sample sizes (approximately S > 2000).",
          "Section 3",
          "This suggests that requiring the estimated shape parameter be less than 0.5 would be unnecessarily stringent."),
         ("Justification of 0.7: by numerical analysis of truncated Pareto means, when k < 0.7 the variance dominates the PSIS RMSE (so the variance-based MCSE works even for k > 0.5); when k > 0.7 bias dominates regardless of S and the variance-based MCSE starts to fail, so accuracy is harder to diagnose even if S is increased.",
          "Section 3.2.3",
          "When k > 0.7, independently of S the effect of bias dominates and the variance based MCSE starts to fail (also demonstrated by the examples)."),
         ("Sample-size-specific threshold 1 - 1/log10(S) (rule of thumb for S >= 10): sample sizes 1000, 2000, 4000 and 10 000 give thresholds 0.67, 0.7, 0.72 and 0.75, all approximated by 0.7; S = 100 gives 0.5 and S = 100 000 gives 0.8.",
          "Section 3.2.4",
          "For a much smaller sample size 100, the threshold would be 0.5, and for a much bigger sample size 100 000 the threshold would be 0.8."),
         ("Summary recommendations: if k-hat < 1 - 1/log10(S) the PSIS estimate is expected to be accurate; if k-hat < min(1 - 1/log10(S), 0.7) the PSIS MCSE estimate is expected to be reliable; if k-hat > 0.7 it quickly becomes too expensive to get an accurate estimate; if k-hat > 1 the mean is expected not to exist and any estimate of it is invalid.",
          "Section 6",
          "If ˆk > 1, it is expected that the mean does not exist and any estimate for the mean is invalid."),
         ("k-hat is a pre-asymptotic diagnostic: in Example 2 (D-dimensional standard normal target, Student-t proposal with 7 degrees of freedom, S = 10 000, D from 1 to 1024) the ratios are always bounded with finite variance, yet the finite-sample behavior becomes indistinguishable from the infinite-variance case as D grows, and k-hat diagnoses the collapse of effective sample size and convergence rate.",
          "Section 3.3",
          "Although the importance ratios are always bounded and the variance is finite, the finite sample behavior is indistinguishable from the infinite variance case when the number of dimensions grows large enough."),
         ("Known blind spot: one could construct an artificial example (citing a discrete-distribution example of Chatterjee and Diaconis, 2018) in which the tail looks thin (low k-hat) for small S with high probability while the true tail is thick; the authors report not observing this, except for very small S, in their simulations and applications.",
          "Section 3.2.9",
          "It would be possible to construct also an artificial example where the tail would look thin (low Pareto ˆk) for small S with large probability, while the true tail is thick (high Pareto ˆk)."),
         ("Self-normalized importance sampling (Eq. 1): E_p[h] is estimated by sum_s r_s h(theta_s) / sum_s r_s with importance ratios r_s = p(theta_s)/g(theta_s), using draws from a proposal g; when g poorly approximates the target, the ratios can have a heavy right tail and the estimate can be unstable, sometimes with infinite variance.", "Introduction", "When the proposal distribution is a poor approximation to the target distribution, the distribution of importance ratios can have a heavy right tail."),
     ],
     "notes": "Venue: page 1 of the PDF says 'Accepted for publication in Journal of Machine Learning Research' and the arXiv journal_ref gives JMLR 25(72); recorded as 'JMLR'. Year is the first arXiv version (2015); the v9 PDF is dated 2024 and licensed CC-BY 4.0 (stated on page 1). Asymptotic theory (Section 4) covers an idealized PSIS with k and sigma known: consistency and vanishing variance under listed conditions (R absolutely continuous, M = O(S^1/2), h in L2(p)); asymptotic normality is left as 'an open question' (Section 4.2). Table 1 gives rules of thumb (minimum sample size 10^(1/(1-k-hat)), approximate ESS) where the constant 10 is described as an ad hoc choice. Section 5.1 and 6.1 list uses of k-hat to diagnose variational approximations (Yao et al. 2018, Dhaka et al., Zhang et al. 2022 (Pathfinder)); these are by overlapping authors. The PSIS-LOO examples (stack loss, protein data) are not recorded. Overlapping authors with arxiv-1802.02538 (which cites an earlier version of this paper as Vehtari et al., 2017) and arxiv-2108.03782."},

    {"id": "arxiv-1802.02538",
     "title": "Yes, but Did It Work?: Evaluating Variational Inference",
     "authors": ["Yuling Yao", "Aki Vehtari", "Daniel Simpson", "Andrew Gelman"],
     "year": 2018, "venue": "ICML 2018", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1802.02538"},
     "tasks": ["posterior-inference"],
     "fam": ["variational-inference"],
     "proposes": ["PSIS diagnostic for VI: draw from q, compute importance ratios p(theta, y)/q(theta), fit a generalized Pareto distribution to the largest ratios and use the shape estimate k-hat to judge the joint approximation (and PSIS to adjust estimates)",
                  "Variational simulation-based calibration (VSBC): simulate parameters from the prior and data from the model, refit VI on each data set, and test the marginal calibration probabilities for symmetry around 0.5 to detect bias of point estimates"],
     "claims": [
         ("The ELBO alone cannot assess fit: an unknown multiplicative constant in p(theta, y) changes with reparametrization, making ELBO comparisons across approximations meaningless, and its scale is uninterpretable, so it is not clear at what value the approximation can be trusted.",
          "Introduction",
          "This makes it next to useless as a method to assess how well the variational inference has ﬁt."),
         ("PSIS diagnostic: k-hat estimates the smallest k such that the 1/k-th moment of p/q under q is finite; it is invariant to constant multiplication of p or q (so the unnormalized joint can be used) and relates to Rényi divergence: k > 0.5 means infinite chi-square divergence and k > 1 means KL(p, q) is infinite, even though KL(q, p) is minimized in the family.",
          "Section 2.2",
          "ˆk is invariant under any constant multiplication of p or q, which explains why we can suppress the marginal likelihood (normalizing constant) p(y) and replace the intractable p(θ|y) with p(θ, y) in (2)."),
         ("Thresholds (set according to the empirical study in Vehtari et al., 2017): k-hat < 0.5 means q is close enough to the true density; 0.5 < k-hat < 0.7 means q is not perfect but still useful (PSIS recommended to shrink errors in both cases); k-hat > 0.7 means PSIS convergence is impractically slow with an even larger error for plain VI, so the VI should be tuned (reparametrization, more iterations, larger minibatch, smaller learning rate, etc.) or exact MCMC used. In finite samples k-hat may exceed 1, indicating even worse performance. Algorithm 1 uses a single cut at 0.7.",
          "Section 2.2",
          "If ˆk > 0.7, the PSIS convergence rate becomes impractically slow, leading to a large mean square error, and a even larger error for plain VI estimate."),
         ("k-hat is invariant to any reparametrization of the same distribution, but a reparametrization that changes the approximation family changes the result, so comparing k-hat across parametrizations can guide the choice.",
          "Section 2.3",
          "A nice property of PSIS diagnostics is that the ˆk quantity is invariant under any re-parametrization."),
         ("Marginal PSIS diagnostics do not work: the true marginal density is typically unknown, and a small marginal k-hat does not guarantee good marginal estimates because VI marginals can under-estimate tail thickness; in the eight-school example marginal k-hats were misleadingly small while the joint k-hat was large.",
          "Section 2.4",
          "Secondly, a smaller ˆki does not necessary guarantee a well-performed marginal estimation."),
         ("VSBC (building on Cook et al., 2006) assesses average calibration over data sets simulated from the model, requiring a VI fit for each of M simulated data sets, and tests symmetry of marginal calibration probabilities (visually or with a KS test, interpreted through a multiple-testing lens). Drawbacks: average behavior need not hold for the observed data, and misspecification is not covered; the authors suggest a conservative reading in which failing implies poor performance but passing does not guarantee it.",
          "Section 3.2",
          "We suggest interpreting the diagnostic conservatively: if a variational inference scheme fails the diagnostic, then it will not perform well on the model in question."),
         ("Limitation: the PSIS diagnostic is local; with a multimodal posterior, draws from q may miss modes and k-hat ignores unseen modes (in a two-mode example Gaussian VI gives k = 0). Any divergence based on draws from q, such as KL(q, p), is local; bimodality can be detected by multiple over-dispersed initializations, whereas VSBC draws parameters from the prior and may detect a missing mode unless the prior is too restrictive.",
          "Section 5.1",
          "In this sense, the PSIS diagnostic is a local diagnostic that will not detect unseen modes."),
         ("Evaluation protocol: both diagnostics are applied to mean-field Gaussian ADVI on Bayesian linear regression (n = 10000, K = 100, VSBC with M = 1000 replications), logistic regression with design-matrix correlation from 0 to 0.99, the eight-school hierarchical model (centered vs non-centered), and a horseshoe logistic regression on leukemia microarray data (D = 7129, n = 72), with NUTS as the reference.",
          "Section 4",
          "Without loss of generality, we implement mean-ﬁeld Gaussian automatic differentiation variational inference (ADVI) in this section."),
         ("ADVI is sensitive to the stopping rule: in the linear-regression example, changing the relative ELBO-change threshold from a conservative 1e-5 to the default 1e-2 raised k-hat from 0.61 to 4.4, so k-hat can be used as a convergence check; simulations were repeated 100 times.",
          "Section 4.1",
          "However, the performance of ADVI is sensitive to the stopping time, as in any other optimization problems."),
     ],
     "notes": "Venue from the PDF footer ('Proceedings of the 35th International Conference on Machine Learning, Stockholm, Sweden, PMLR 80, 2018'). Conflict of interest: the evaluated ADVI is co-authored by Gelman (reference list: Kucukelbir, Tran, Ranganath, Gelman and Blei, 2017), and the PSIS method and thresholds come from the authors' own earlier work (cited as Vehtari et al., 2017; the later version is arxiv-1507.02646, which sets the threshold as min(1 - 1/log10(S), 0.7) rather than the fixed 0.5/0.7 bands used here). The PSIS tail size here is written as min(S/5, 3 sqrt(S)). Body-text numbers: eight schools joint k-hat 1.00 (centered) vs 0.64 (non-centered); horseshoe ADVI k-hat 9.8. Sections numbered from PDF headings. arxiv-1910.04102 argues small k-hat is only a heuristic for approximation quality."},

    {"id": "arxiv-1910.04102",
     "title": "Validated Variational Inference via Practical Posterior Error Bounds",
     "authors": ["Jonathan H. Huggins", "Mikołaj Kasprzak", "Trevor Campbell", "Tamara Broderick"],
     "year": 2019, "venue": "AISTATS 2020", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1910.04102", "code": "https://github.com/jhuggins/viabel"},
     "tasks": ["posterior-inference", "uncertainty-estimation"],
     "fam": ["variational-inference"],
     "proposes": ["Bounds on errors of posterior means, standard deviations, mean absolute deviations and covariances via the Wasserstein distance, which is bounded using the 2-divergence (or KL) and moment constants of the variational approximation, which in turn are bounded by CUBO and ELBO estimates",
                  "A validated variational inference workflow: heavy-tailed (Student-t mean-field) family, CUBO minimization, a k-hat check, then computed divergence and Wasserstein bounds deciding whether to use the approximation directly, refine it with PSIS, or change the family/parameterization"],
     "claims": [
         ("Scope and assumptions: the bounds apply when the approximating and exact posteriors have polynomial moments (tighter bounds when exponential moments exist), and are computed from standard variational objectives, analytic calculations and simple Monte Carlo (not MCMC) estimates.",
          "Abstract",
          "Our bounds are widely applicable, as they require only that the approximating and exact posteriors have polynomial moments."),
         ("Counterexamples: small KL(q | p) does not control posterior summaries; for any t there are one-dimensional unimodal pairs (Weibull distributions; a standard normal approximating a t distribution) with KL below 0.9, 0.3 or 0.12 where the squared mean error or variance ratio exceeds t, and similarly small D2 (below 0.4) can coexist with arbitrarily poor mean and variance.",
          "Error bounds via posterior discrepancies",
          "To get a sense of scale for the KL divergence, we note that the KL divergence from a variational approximation to the exact posterior can easily range from 1 to nearly 500."),
         ("Theorem 3.4: if the 1- or 2-Wasserstein distance is at most epsilon, the mean error is at most epsilon and the MAD error at most 2 epsilon; if W2 <= epsilon, the marginal standard-deviation error is at most epsilon and the covariance error is below 2 epsilon (S + epsilon).",
          "Error bounds via posterior discrepancies",
          "Our next result conﬁrms that the Wasserstein distance controls the error in these quantities."),
         ("Wasserstein bounds: assuming the variational approximation has polynomial (resp. exponential) tails and the posterior is absolutely continuous with respect to it, W_p is bounded via the 2-divergence (resp. KL) times a moment constant of q; the divergence is in turn bounded by H2 = 2(CUBO2(q) - ELBO(eta)) for any distribution eta (Lemma 4.5, Theorem 4.6). Because the divergences are scale-free and Wasserstein is not, the moment constants supply the scale.",
          "Computationally efficient error bounds",
          "Assuming the variational approximation ˆπ has polynomial (respectively, exponential) tails, our next result provides a bound on the p-Wasserstein distance using the 2-divergence (respectively, the KL divergence)."),
         ("Workflow cost and steps: use a mean-field Student-t family (40 degrees of freedom, described as somewhat arbitrary) so the 2-divergence is finite, minimize CUBO2, then separately maximize the ELBO to find eta, estimate both by simple Monte Carlo, and compute the bounds; the CUBO objective is usually non-convex, so the global minimum may not be found. Before computing bounds, k-hat <= 0.7 is checked because otherwise the CUBO2 estimate, and hence the bounds, are not reliable.",
          "A workﬂow for black box variational inference",
          "However, before going to the effort of ﬁnding η, in step 3 we check that ˆk ≤0.7, since otherwise our estimate of CUBO2(ˆπ) is not reliable and thus we should not trust any bounds on the 2-divergence or Wasserstein distance computed using Lemma 4.5 and Theorem 4.6."),
         ("Decision thresholds (step 8): what counts as small for the W2 bound depends on the desired accuracy and the natural scale of the problem; the 2-divergence bound has a more universal scale, with values below 4.6 treated as moderately small (importance-weight variance below 100, so PSIS should be effective) and values below some delta* << 1 (e.g. 0.01) as very small (use the approximation directly).",
          "A workﬂow for black box variational inference",
          "For step 8, what qualiﬁes as a moderately or very small ¯w2 value will depend on the desired accuracy and natural scale of the problem."),
         ("On prior work: Yao et al. (2018), based on the empirical results and informal arguments of Vehtari et al. (2019), propose k-hat <= 0.5 as a good approximation and k-hat in [0.5, 0.7] as minimally acceptable; the authors call the link between small k-hat and approximation quality only heuristic and report finding poor approximations with small k-hat.",
          "Previous work on validating variational approximations",
          "However, the link between a small ˆk value and a high-quality posterior approximation is only heuristic."),
         ("Eight schools case study (HMC in Stan as ground truth): with the centered parameterization k-hat > 0.7 and the bounds agree that the approximation is poor; with a heavier-tailed mean-field t family (8 degrees of freedom) k-hat was smaller (0.40) than with 40 degrees of freedom (0.55) although accuracy was worse, which the larger bounds reflected; hence the workflow uses k-hat only to validate importance sampling, not the quality of the approximation.",
          "Case study #1: the eight schools model",
          "Hence, our workﬂow uses ˆk only to validate the use of importance sampling, but not the quality of ˆπ."),
         ("Robust regression case study (d = 2, N = 25, correlated covariates): mean-field CHIVI no longer underestimated marginal variances but could not capture the posterior correlation; its large covariance error was reflected in large divergence and Wasserstein bounds but not in its small k-hat (0.34), although its PSIS errors were small, so k-hat and the bounds give complementary information.",
          "Case study #2: robust regression",
          "The poor covariance approximation is reﬂected in large ¯d2 and ¯w2 values; however, it is not reﬂected in the small ˆk value (0.34)."),
     ],
     "notes": "Affiliations: Boston University, University of Luxembourg, University of British Columbia, MIT. Venue from the PDF footer ('Proceedings of the 23rd International Conference on Artificial Intelligence and Statistics (AISTATS) 2020, Palermo, Italy. PMLR: Volume 108'). Locations use paragraph/section names because the extracted headings carry no numbers (theorem numbers like 3.4 and 4.6 are as stated in the PDF). Methods compared (KLVI, CHIVI by Dieng et al. 2017, PSIS by Vehtari et al.) are not by these authors; the workflow is implemented in the authors' own viabel package. Only two case studies (eight schools; a toy robust regression); table values (bounds, errors) not recorded. Proofs are in Appendix D. Cross-references: critiques the k-hat thresholds of arxiv-1802.02538 / arxiv-1507.02646."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
