import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_kd_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1910.01348",
     "title": "On the Efficacy of Knowledge Distillation",
     "authors": ["Jang Hyun Cho", "Bharath Hariharan"],
     "year": 2019, "venue": "ICCV 2019", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1910.01348"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["knowledge-distillation", "deep-learning"], "par": ["supervised"],
     "proposes": ["Early-stopped knowledge distillation (ESKD): use the KD loss only early in student training and then train on the cross-entropy loss alone for the rest of training",
                  "Early-stopped teachers: regularize a large teacher by stopping its training early (a third to a fourth of the usual epochs) so that its solution is more reachable by a small student"],
     "claims": [
         ("The authors report that larger models often do not make better teachers, attribute this to mismatched capacity (small students are unable to mimic large teachers), find typical workarounds such as a sequence of distillation steps ineffective, and show the effect can be mitigated by stopping the teacher's training early.",
          "Abstract",
          "We ﬁnd crucially that larger models do not often make better teachers."),
         ("Background (following Hinton et al.): teacher scores are softened with temperature tau > 1 because trained networks produce peaky distributions that may be less informative; the student loss is L = alpha * L_cls + (1 - alpha) * L_KD with L_KD = -tau^2 * sum_k p~t_k log p~s_k; the authors cite tau in {3, 4, 5} and alpha = 0.9 as popular choices. No explanation of the tau^2 factor is given in this section.",
          "Section 3",
          "Trained neural networks produce peaky probability distributions, which may be less informative."),
         ("Setup: on CIFAR10 each model is trained for 200 epochs with SGD (momentum 0.9, initial learning rate 0.1, dropped by 0.2 every 60 epochs) with standard augmentation; KD hyperparameters are set consistent with the popular choice (tau = 4, alpha = 0.9, beta = 1000 for attention transfer); each experiment is repeated 5 times. ImageNet experiments closely follow Zagoruyko et al. with the same tau and alpha.",
          "Section 4",
          "The same experiment was repeated 5 times and median, mean, and standard deviation are reported."),
         ("On CIFAR10, student accuracy rises and then falls as the teacher grows (in depth or width) even though teacher accuracy keeps rising; on ImageNet with a ResNet18 student and ResNet18/34/50/152 teachers, larger and more accurate teachers give less accurate students. The hypothesis that confident teachers approach one-hot labels was rejected because softening with a high temperature did not change this result.",
          "Section 5.1",
          "As can be seen, as the teacher becomes larger and more accurate, the student becomes less accurate."),
         ("The KD error (fraction of examples where student and teacher predictions differ, CIFAR) and KD loss (ImageNet) are much higher for the largest teacher, which leads to the least accurate student; the authors posit that, due to much lower capacity, the student cannot find a solution in its space that corresponds well to the largest teacher.",
          "Section 5.2",
          "This suggests that the student is unable to mimic large teachers"),
         ("On ImageNet all teachers gave lower student accuracy than training from scratch under full KD. Comparing training curves, KD improves validation accuracy initially but hurts it towards the end; hypothesizing that the student underfits and trades the cross-entropy loss against the KD loss, the authors stop KD early (ESKD), which is better than full KD for all three teachers, but larger teachers still do not give more accurate students.",
          "Section 5.3",
          "it begins to hurt accuracy towards the end of training."),
         ("Sequential (repeated) distillation is not a fix: on CIFAR the last student of a 5-generation sequence underperforms a scratch-trained student for some models (ResNet8, ResNet14), an ensemble of the sequence does not beat an equal-size ensemble trained from scratch, a teacher trained by 5 KD iterations is more accurate but not a better teacher, and large -> medium -> small distillation performs almost the same as large -> small; sequential distillation is also reported ineffective on ImageNet.",
          "Section 5.4",
          "Sequential distillation cannot help make large models better teachers."),
         ("Since grid search over teacher architectures is too expensive, the authors propose stopping the large teacher's training early (citing evidence that a large network trained for few epochs behaves like a small one); on CIFAR10 with teachers trained for n in {35, 50, 65, 80} total epochs, all early-stopped teachers produce better students than the optimal fully-trained teacher for both students.",
          "Section 5.5",
          "Notice that for both student models (WRN16-1 and WRN28-1), all early-stopped teachers produce better students than the optimal fully-trained teacher (WRN16-3 and WRN28-3)."),
     ],
     "notes": "Affiliation: Cornell University. Venue from the arXiv journal_ref (ICCV 2019); the arXiv v1 PDF itself has no venue line. Section numbers are from numbered headings in the PDF. Tables 1-10 are not recorded. Body-text numbers: the best ESKD students (early-stopped ResNet34 and fully-trained ResNet18 teachers) reach about 29.01% top-1 error, about 1.23 points better than scratch (Section 5.5); some Table 7/8 entries are numbers inherited from the original papers (marked *), not re-run. With tau = 20 on ImageNet, high temperature improved ESKD but showed no visible difference for full KD (Section 5.6). Section 5.6 also reports that conclusions hold for mixed DenseNet/WideResNet pairs and for transfer to Places365 (the authors write 'proving' for the latter). Conclusion: KD 'is not a panacea and cannot succeed when student capacity is too low to successfully mimic the teacher'. Cited by arxiv-2106.05945 (Stanton et al.)."},

    {"id": "arxiv-2106.05945",
     "title": "Does Knowledge Distillation Really Work?",
     "authors": ["Samuel Stanton", "Pavel Izmailov", "Polina Kirichenko", "Alexander A. Alemi", "Andrew Gordon Wilson"],
     "year": 2021, "venue": "NeurIPS 2021", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2106.05945", "code": "https://github.com/samuelstanton/gnosis"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["knowledge-distillation", "deep-learning"], "par": ["supervised"],
     "proposes": ["Separating distillation fidelity (agreement with the teacher: top-1 agreement, predictive KL) from student generalization (accuracy, NLL, ECE), with an independent-teacher student as a control",
                  "An analysis attributing low fidelity mainly to optimization difficulty rather than to identifiability of the distillation data"],
     "claims": [
         ("The authors show that while KD can improve student generalization, there often remains a surprisingly large discrepancy between teacher and student predictive distributions, even when the student has the capacity to match the teacher perfectly; they identify difficulties in optimization as a key reason, and report that matching the teacher more closely paradoxically does not always improve generalization.",
          "Abstract",
          "there often remains a surprisingly large discrepancy between the predictive distributions of the teacher and the student, even in cases when the student has the capacity to perfectly match the teacher."),
         ("Objective (Hinton et al.): L_s = alpha * L_NLL + (1 - alpha) * L_KD with L_KD = -tau^2 * sum_j sigma_j(z_t / tau) log sigma_j(z_s / tau); as tau -> infinity the gradient approaches z_t - z_s (equal weight to every logit). Because the study focuses on fidelity, alpha = 0 is used for all main-text experiments (only a limited alpha ablation in the appendix).",
          "Section 3.1",
          "Since we focus on distillation ﬁdelity, we choose α = 0 for all experiments in the main text to avoid any confounding from true labels"),
         ("Metrics: generalization is measured by top-1 accuracy, NLL and ECE; fidelity by average top-1 agreement and average predictive KL from teacher to student. Because agreement can be confounded by accuracy, they also distill a second student through an identical procedure from an independent teacher, so that a generic gain in generalization can be distinguished from a gain in fidelity.",
          "Section 3.2",
          "To account for such confounding when evaluating the distillation of a student s from a teacher t, we also evaluate another student s′ distilled through an identical procedure from an independent teacher."),
         ("In self-distillation (ResNet-56 on CIFAR-100) the student can exceed the teacher, which the authors note is only possible because distillation fails; for a 3-ResNet-56 ensemble teacher, fidelity becomes positively correlated with generalization but a significant fidelity gap remains.",
          "Section 4.2",
          "This result is only possible by virtue of failing at the distillation procedure: if the student matched the teacher perfectly then the student could not outperform the teacher."),
         ("Distilling a 5-ResNet-56 ensemble into a ResNet-56 on CIFAR-100, the augmentations best for generalization (MixUp, GAN) are not the best for fidelity, and even the best-fidelity policy reaches only 86% test agreement (baseline with tau = 4: 84.5%); since the gain from augmentation is small compared with logit tempering, the authors judge it very unlikely that an insufficient quantity of teacher labels is the primary obstacle to high fidelity.",
          "Section 5.1",
          "even the best augmentation policy, Mixup (τ = 4), only achieves a modest 86% test agreement."),
         ("Distilling on held-out data the teacher did not see (D1) gives higher fidelity but lower test accuracy than distilling on the teacher's own training data (D0); distilling on both combines their best attributes. The best agreement is still only around 85%, and the authors conclude the evidence does not support blaming poor fidelity on the wrong choice of distillation data.",
          "Section 5.2",
          "In fact, the best teacher-student agreement is only around 85%, no improvement when compared to the results from extensive data augmentation in the last section."),
         ("On the distillation data itself, the student often fails to match the teacher: enlarging the data with GAN samples or heavier augmentation lowers train agreement (to 60% for combined augmentations in self-distillation), and the authors write that the results suggest the optimizer cannot reach high fidelity even on the distillation dataset in these settings.",
          "Section 6.1",
          "However, the results presented in this section suggest that in practice the optimization method is unable to achieve high ﬁdelity even on the distillation dataset when extensive data augmentation or synthetic data is used."),
         ("In ResNet-20 (LayerNorm) self-distillation on CIFAR-100, training longer or switching to Adam does not substantially improve fidelity; initializing the student as a convex combination of teacher and random weights shows that students initialized far from the teacher converge to a distinct sub-optimal basin, while sharing only the teacher's initial weights gives no observable functional change. The authors conclude the sub-optimal convergence appears to be a consequence of optimization dynamics, not simply initialization bias.",
          "Section 6.2",
          "Furthermore, the suboptimal convergence of knowledge distillation appears to be a consequence of the optimization dynamics speciﬁcally, and not simply initialization bias."),
     ],
     "notes": "Affiliations: NYU (Stanton, Izmailov, Kirichenko, Wilson) and Google Research (Alemi). Venue from the PDF footer ('35th Conference on Neural Information Processing Systems (NeurIPS 2021)'); also the arXiv comment. Section numbers are from numbered headings in the PDF. Most results are figures (not recorded). Body-text numbers in Section 6.2: with SGD, 83.3% train agreement after 5k epochs vs 78.95% after 300 epochs; Adam only reduced fidelity; a sudden change at lambda = 0.375 gives nearly 100% agreement. Discussion findings: good student accuracy does not imply good fidelity; the highest-fidelity student is always the best calibrated when distilling ensembles; enlarging distillation data helps identifiability but makes optimization harder. Appendix results (VGG, ImageNet, IMDB text classification, larger students, alpha ablation) are mentioned in Section 4.4 but not carded. Section 4.1: LeNet-5 self-distillation on MNIST with extra EMNIST distillation data reaches over 99% test agreement, while ResNet-56 on CIFAR-100 with GAN data improves fidelity only modestly. Ensemble teacher logits are the log of the averaged component probabilities (Section 3). Cites arxiv-1910.01348 (Cho & Hariharan). No evaluation of the authors' own earlier methods was found."},

    {"id": "arxiv-1506.02626",
     "title": "Learning both Weights and Connections for Efficient Neural Networks",
     "authors": ["Song Han", "Jeff Pool", "John Tran", "William J. Dally"],
     "year": 2015, "venue": "NIPS 2015", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1506.02626"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "deep-learning"], "par": ["supervised"],
     "proposes": ["Three-step pruning: train the dense network, remove all connections whose weight magnitude is below a per-layer threshold, and retrain the remaining sparse connections (keeping the surviving weights)",
                  "Iterative pruning: repeat pruning and retraining to reach higher compression without accuracy loss"],
     "claims": [
         ("Abstract: a train / prune / retrain method reduces the parameters of AlexNet on ImageNet by 9x (61 million to 6.7 million) without accuracy loss, and of VGG-16 by 13x (138 million to 10.3 million) with no loss of accuracy.",
          "Abstract",
          "On the ImageNet dataset, our method reduced the number of parameters of AlexNet by a factor of 9×, from 61 million to 6.7 million, without incurring accuracy loss."),
         ("Method: connectivity is first learned by normal training, then all connections with weights below a threshold are removed (dense to sparse), and the network is retrained to learn the final weights of the remaining connections. The authors call retraining critical: without it, accuracy is significantly impacted.",
          "Section 3",
          "If the pruned network is used without retraining, accuracy is signiﬁcantly impacted."),
         ("Regularization: L1 regularization pushes more parameters near zero and gives better accuracy after pruning but before retraining, whereas L2 gives higher accuracy after retraining; overall L2 gives the best pruning results.",
          "Section 3.1",
          "Overall, L2 regularization gives the best pruning results."),
         ("During retraining, the surviving weights from the initial training should be kept rather than re-initializing pruned layers (citing fragile co-adapted features); to limit vanishing-gradient effects, CONV parameters are fixed while FC layers are retrained after pruning FC layers, and vice versa.",
          "Section 3.3",
          "So when we retrain the pruned layers, we should keep the surviving parameters instead of re-initializing them."),
         ("Iterative pruning (pruning followed by retraining, repeated) increases the pruning rate on AlexNet from 5x to 9x without loss of accuracy compared with single-step aggressive pruning; probabilistic pruning based on absolute value gave worse results.",
          "Section 3.4",
          "Without loss of accuracy, this method can boost pruning rate from 5× to 9× on AlexNet compared with single-step aggressive pruning."),
         ("Criterion and implementation: pruning is implemented in Caffe with a mask per weight tensor, and the per-layer threshold is a quality parameter multiplied by the standard deviation of that layer's weights.",
          "Section 4",
          "The pruning threshold is chosen as a quality parameter multiplied by the standard deviation of a layer’s weights."),
         ("Cost: the original AlexNet took 75 hours to train on an NVIDIA Titan X, and retraining the pruned AlexNet (at 1/100 of the original initial learning rate) took 173 hours; the authors argue this is less of a concern because pruning is used for model reduction when the model is ready for deployment.",
          "Section 4.2",
          "It took 173 hours to retrain the pruned AlexNet."),
         ("Hardware caveat: the authors target fixed-function hardware specialized for sparse DNNs, citing the limitation of general-purpose hardware on sparse computation; they note that after pruning AlexNet and VGGNet are small enough to store all weights on chip.",
          "Section 5",
          "We are targeting our pruning method for ﬁxed-function hardware specialized for sparse DNN, given the limitation of general purpose hardware on sparse computation."),
     ],
     "notes": "Affiliations: Stanford University (Han, Dally) and NVIDIA (Pool, Tran, Dally). Venue from the arXiv comment ('Published as a conference paper at NIPS 2015'); the arXiv v3 PDF itself has no venue line. Section numbers are from numbered headings in the PDF. Retraining dropout ratio is set to D_r = D_o * sqrt(C_ir / C_io) (Section 3.2). Discussion (Section 5): without retraining accuracy starts dropping at 1/3 of the original connections vs 1/10 with retraining (read from the trade-off curve and stated in text); CONV layers are more sensitive than FC layers, the first conv layer most; two pruned points were slightly better than the original, which the authors 'believe' is due to reduced overfitting; sparse storage overhead 15.6%; L1-then-L2 did not beat L2 for both phases; layer sensitivity is used to set each layer's threshold. Table 6 baselines (data-free pruning, Fastfood, Collins & Kohli, naive cut, SVD) are numbers from other papers' methods and not recorded. Reference [14] is the authors' own Deep Compression (arxiv-1510.00149), cited as orthogonal quantization."},

    {"id": "arxiv-1510.00149",
     "title": "Deep Compression: Compressing Deep Neural Networks with Pruning, Trained Quantization and Huffman Coding",
     "authors": ["Song Han", "Huizi Mao", "William J. Dally"],
     "year": 2015, "venue": "ICLR 2016", "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1510.00149"},
     "tasks": ["model-compression", "image-classification"],
     "fam": ["pruning", "quantization", "deep-learning"], "par": ["supervised"],
     "proposes": ["Deep Compression: a three-stage pipeline of magnitude pruning with retraining, trained quantization by per-layer k-means weight sharing with fine-tuned centroids, and Huffman coding of weights and sparse indices"],
     "claims": [
         ("Abstract: pruning, trained quantization and Huffman coding together reduce the storage of neural networks by 35x to 49x without affecting accuracy; AlexNet goes from 240MB to 6.9MB (35x) and VGG-16 from 552MB to 11.3MB (49x); pruning cuts connections by 9x to 13x and quantization reduces bits per connection from 32 to 5.",
          "Abstract",
          "On the ImageNet dataset, our method reduced the storage required by AlexNet by 35×, from 240MB to 6.9MB, without loss of accuracy."),
         ("The pruning stage builds on Han et al. (2015) (the authors' own earlier work, arxiv-1506.02626): train, remove connections with weights below a threshold, and retrain; the sparse structure is stored in CSR/CSC with index differences encoded in 8 bits for conv layers and 5 bits for fc layers.",
          "Section 2",
          "We build on top of that approach."),
         ("Weight sharing: per layer (not across layers), k-means clustering on the trained weights minimizes the within-cluster sum of squares, so each connection stores only a log2(k)-bit index into a codebook; unlike HashedNets, sharing is determined after the network is fully trained.",
          "Section 3.1",
          "We use k-means clustering to identify the shared weights for each layer of a trained network, so that all the weights that fall into the same cluster will share the same weight."),
         ("Trained quantization: the shared weights (centroids) are fine-tuned, with the gradient of each centroid being the sum of the gradients of the weights assigned to it.",
          "Section 3.3",
          "During back-propagation, the gradient for each shared weight is calculated and used to update the shared weight."),
         ("Among Forgy (random), density-based and linear centroid initialization, linear initialization gives better accuracy in all cases except at 3 bits; the authors explain this by linear initialization keeping large centroids, citing their earlier pruning work for the claim that large weights matter more.",
          "Section 6.2",
          "Linear initialization outperforms the density initialization and random initialization in all cases except at 3 bits."),
         ("Huffman coding the biased distributions of quantized weights and sparse index differences saves 20% to 30% of network storage; it requires no training and is applied offline after fine-tuning.",
          "Section 4",
          "Experiments show that Huffman coding these non-uniformly distributed values saves 20%"),
         ("Individually, pruned or quantized AlexNet loses accuracy significantly when compressed below 8% of its original size, but combined the network can be compressed to 3% with no loss of accuracy; the authors explain that quantization works well on the pruned network because fewer weights (6.7 million vs 60 million) are quantized with the same number of centroids.",
          "Section 6.1",
          "But when combined, as shown in the red line, the network can be compressed to 3% of original size with no loss of accuracy."),
         ("Speed/energy benchmarks cover only the FC layers of the pruned (not quantized) model at batch size 1, because current BLAS libraries do not support indirect look-up and relative indexing; pruned layers give 3x to 4x speedup over dense on average, but with batching (matrix-matrix multiplication) the pruned network no longer shows its advantage.",
          "Section 6.3",
          "In this scenario, pruned network no longer shows its advantage."),
     ],
     "notes": "Affiliations: Stanford University (Han, Dally), Tsinghua University (Mao), NVIDIA (Dally). Venue from the PDF header ('Published as a conference paper at ICLR 2016') and the arXiv comment (ICLR 2016 oral); year is the first arXiv version (2015). Section numbers are from numbered headings in the PDF. Conflict of interest: the pruning stage and the 'Pruning (Han et al., 2015)' row of the AlexNet comparison (Table 7) are the authors' own earlier method (arxiv-1506.02626, Han and Dally); the EIE accelerator mentioned in the Introduction is also by overlapping authors; speed/energy benchmarks run on NVIDIA hardware while Dally is affiliated with NVIDIA. The paper does not state these as a conflict. Compression rates include codebook and sparse-index overhead (Section 5.1, Section 6.4). Table 6: 8/5-bit quantization has no loss; 8/4-bit 0.01% loss; 4/2-bit 1.99% and 2.60% loss (caption). Future work (Section 8): the quantized network with weight sharing has not been benchmarked on hardware, so 'the full advantage of Deep Compression ... is not fully unveiled'. Energy: pruned layers use 3x to 7x less energy at batch size 1 (Section 6.3)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
