import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1705.08500",
     "title": "Selective Classification for Deep Neural Networks",
     "authors": ["Yonatan Geifman", "Ran El-Yaniv"],
     "year": 2017, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1705.08500"},
     "tasks": ["selective-prediction", "image-classification"],
     "fam": ["deep-learning"], "par": ["post-hoc"],
     "proposes": ["Selection with Guaranteed Risk (SGR): given an already trained classifier and a confidence-rate function (softmax response or MC-dropout), binary-search a rejection threshold on a labeled sample so that the selective risk is at most a user-chosen target with probability at least 1 - delta"],
     "claims": [
         ("Contribution: a method to construct a selective classifier from a trained neural network in which the user sets a desired risk level and, at test time, instances are rejected as needed to grant that risk with high probability.",
          "Abstract",
          "At test time, the classiﬁer rejects instances as needed, to grant the desired risk (with high probability)."),
         ("Selection mechanism: the classifier f is fixed; a rejection function is learned by choosing a threshold over one of two known confidence-rate functions, softmax response (SR, the maximal softmax output) or MC-dropout (minus the variance of the most probable class's response over dropout passes).",
          "Introduction",
          "To this end, we consider the above two known techniques for rejection (SR and MC-dropout), and devise a learning method that chooses an appropriate threshold that ensures the desired risk."),
         ("Guarantee and its assumptions (Theorem 3.2): if the labeled set S_m used by SGR is sampled i.i.d. from P, then with probability at least 1 - delta over the draw of S_m, every selective classifier computed in the k = ceil(log2 m) SGR iterations has true selective risk (w.r.t. P restricted to its accepted region) no larger than its computed bound (Lemma 3.1 applied with delta/k, plus a union bound). The guarantee is for the 0/1 loss and for test data from the same P; nothing is assumed about the confidence-rate function beyond using it to rank inputs (Section 3).",
          "Selection with Guaranteed Risk Control",
          "Theorem 3.2 (SGR) Let Sm be a given labeled set, sampled i.i.d. from P, and consider an application of the SGR procedure."),
         ("Caveat on the confidence function: the theorem always holds, but if the confidence-rate function is severely skewed (far from ideal), the bound of the resulting selective classifier can be far from the target risk.",
          "Confidence-Rate Functions for Neural Networks (footnote)",
          "While Theorem 3.2 always holds, we note that if κf is severely skewed (far from ideal), the bound of the resulting selective classiﬁer can be far from the target risk."),
         ("Choice of signal: risk-coverage curves computed on validation data show SR and MC-dropout nearly identical on CIFAR-10/100, while on ImageNet SR is significantly better on both top-1 and top-5, so the remaining experiments use SR only.",
          "Empirical Results",
          "see that SR is signiﬁcantly better than MC-dropout on both tasks."),
         ("Evaluation protocol: for CIFAR-10 the standard validation set is randomly split into two equal halves, one used as the SGR training set and the other reserved for testing the bounds (the paper states CIFAR-100 and ImageNet repeat the same experimental design); the test half is thus a random split of the same validation data (no shifted test data), and all SGR runs use delta = 0.001.",
          "Selective Guaranteed Risk for CIFAR-10",
          "The other half, which was not consumed by SGR for training, was reserved for testing the resulting bounds."),
         ("Stated limitations / open questions: only the 0/1 loss is studied (extension to other losses and regression, and control of false-positive/false-negative rates, is left open), and the classifier and selection function are not trained jointly.",
          "Concluding Remarks",
          "In this paper we only studied selective classiﬁcation under the 0/1 loss."),
     ],
     "notes": "Affiliation: Technion - Israel Institute of Technology; supported by The Israel Science Foundation (grant No. 1890/14). No experiment with shifted or out-of-distribution test data was found in the text (searched 'shift', 'out-of', 'distribution'): the SGR train/test sets are random halves of the standard validation sets. The risk guarantee is a high-probability bound over the draw of the i.i.d. calibration sample (Eq. 2, Lemma 3.1 of Gascuel and Caraux, Theorem 3.2). The paper does not compare against other selective-classification methods beyond SR vs MC-dropout as confidence functions. Evaluation caveat (footnote 2, Section 5.1): 'With this small δ, and small number of reported experiments (6-7 lines in each table) we did not perform a Bonferroni correction (which can be easily added).' - i.e. delta applies per risk target, not jointly across the rows of a table."},

    {"id": "arxiv-1901.09192",
     "title": "SelectiveNet: A Deep Neural Network with an Integrated Reject Option",
     "authors": ["Yonatan Geifman", "Ran El-Yaniv"],
     "year": 2019, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1901.09192", "code": "https://github.com/geifmany/SelectiveNet"},
     "tasks": ["selective-prediction", "image-classification", "tabular-regression"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["SelectiveNet: a three-headed network (prediction f, selection g, auxiliary h) trained end-to-end for a user-specified target coverage with a quadratic interior-point-style coverage penalty, plus a post-training coverage calibration of the selection threshold on an unlabeled validation set"],
     "claims": [
         ("Contribution: unlike rejection mechanisms that threshold the confidence of a pre-trained network, SelectiveNet optimizes prediction (classification or regression) and rejection jointly, end-to-end, for a target coverage.",
          "Abstract",
          "In contrast, SelectiveNet is trained to optimize both classiﬁcation (or regression) and rejection simultaneously"),
         ("Selection signal: a learned selection head whose final layer is a single sigmoid neuron; at inference the network predicts only if g(x) is at least 0.5 and abstains otherwise.",
          "SelectiveNet Architecture",
          "At inference time, a sample x is fed to SelectiveNet, which predicts f(x) if and only if g(x) ≥0.5; otherwise, SelectiveNet abstains from predicting the label of x."),
         ("Coverage is not guaranteed by training: on CIFAR-10 both SR (threshold chosen on the training set) and SelectiveNet (trained with target coverage c) miss the target coverage on the test set in all cases (in Table 1 SR falls below the target, SelectiveNet lands above it), with a smaller average violation for SelectiveNet.",
          "Coverage Accuracy",
          "Clearly, both SR and SelectiveNet violate the target coverage rate in all cases."),
         ("Guarantee and its assumptions: a post-training calibration sets the threshold tau at the 100(1-c) percentile of g over an independent unlabeled validation set of n samples; treating each event g(x_i) >= tau as a Bernoulli variable, a Hoeffding bound gives, with probability at least 1 - delta, coverage in [c - epsilon, c + epsilon] with epsilon = sqrt(ln(2/delta)/(2n)). (The Hoeffding step presumes independent draws from the distribution the coverage refers to; shift is not discussed.) This is a coverage guarantee only, not a risk guarantee; Section 2 states such a model can be converted into a risk-controlling one with the technique of Geifman & El-Yaniv (2017b).",
          "Coverage Accuracy",
          "This goal can be achieved easily using the following simple post-training coverage calibration technique, which relies on an independent unlabeled validation set Vn containing n samples."),
         ("Evaluation protocol: datasets SVHN, CIFAR-10, Cats vs. Dogs (image classification) and UCI Concrete Compressive Strength (regression); baselines are SR and MC-dropout, rejection mechanisms composed over a standard network trained for full coverage (MC-dropout as recommended by its creators: p = 0.5 and 100 passes in classification, p = 0.05 and 200 passes in regression); SR is not applied to regression because there is no softmax layer.",
          "Baseline Methods",
          "We compare the proposed method with two baselines: SR and MC-dropout, which are described below."),
         ("Hyperparameters: alpha (weight between selective and auxiliary loss) was 0.5 in all experiments (Section 4.2 adds: without any hyperparameter optimization); lambda was set to 32, a value found large enough to preserve the coverage constraint through training.",
          "Architectures and Hyperparameters",
          "The value of α (the convex combination between the selective loss and the auxiliary loss) was set to 0.5 for all experiments, and λ was set to 32"),
         ("Stated limitations / future work: the capacity (architecture) of the selection head was not optimized, and the authors anticipate that different datasets and perhaps different coverage rates may require different selection-head architectures; whether ensembling improves SelectiveNet is left open.",
          "Concluding Remarks",
          "Here, we have not tried to optimize this choice, but we anticipate that different datasets and perhaps different coverage rates may require different architectures also for the selection head."),
     ],
     "notes": "PDF states: Proceedings of the 36th International Conference on Machine Learning, Long Beach, California, PMLR 97, 2019. Affiliation: Technion - Israel Institute of Technology; supported by The Israel Science Foundation (grant No. 710/18). No experiment with shifted or out-of-distribution test data was found in the text (searched 'shift', 'out-of'); test sets are the standard splits (Cats vs. Dogs: a random stratified 20,000/5,000 split). Cost note from Related Work: the authors state effective MC-dropout can require hundreds of forward passes per prediction, which motivates a single-pass selector. Coverage-mismatch note (Section 8.1, Table 6, CIFAR-10, averages of three runs): SelectiveNet trained for coverage c and calibrated to c is nearly optimal among models trained for other coverages; calibration costs little 'provided that we calibrate towards a coverage rate that is close to the trained (target) coverage', and off-diagonal (mismatched) entries often have inferior selective risk."},

    {"id": "arxiv-2006.01862",
     "title": "Consistent Estimators for Learning to Defer to an Expert",
     "authors": ["Hussein Mozannar", "David Sontag"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2006.01862", "code": "https://github.com/clinicalml/learn-to-defer"},
     "tasks": ["selective-prediction", "image-classification"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["Learning to defer via a reduction to cost-sensitive learning: a K+1-way softmax (K classes plus a defer output) trained with the convex surrogate L_CE, consistent for the 0-1 system loss of the classifier-plus-expert system, and an alpha-reweighted variant L^alpha_CE (consistent only for alpha = 1) used as a tunable hyperparameter"],
     "claims": [
         ("Contribution: predictors that either predict or defer to a downstream expert, learned from samples of the expert's decisions by training a classifier and a rejector, based on a reduction to cost-sensitive learning with a consistent surrogate loss that generalizes cross entropy.",
          "Abstract",
          "Our approach is based on a novel reduction to cost sensitive learning where we give a consistent surrogate loss for cost sensitive learning that generalizes the cross entropy loss."),
         ("Guarantee (Theorem 1): L_CE (= L^alpha_CE with alpha = 1) is convex in g, upper-bounds the 0-1 system loss, and is classification-consistent: its minimizer over all measurable functions matches the Bayes classifier and Bayes rejector (defer when the expert's probability of being correct is at least the classifier's maximal class posterior, Proposition 2). Setting (Section 3): samples (x, y, m) with (x, y) i.i.d. from P and m drawn from the expert's distribution given (x, y); the guarantee is asymptotic/population-level, not a finite-sample or restricted-class statement.",
          "Proposed Surrogate Loss",
          "The proposed surrogate LCE is in fact consistent and upper bounds L0−1 as the following theorem demonstrates."),
         ("Authors' caveat on the guarantee: with the specific (restricted) hypothesis classes used in practice, if the Bayes predictor is not in the class, consistency might not guarantee much; the paper therefore also defines realizable (H, R)-consistency. It then defines a mixture-of-experts loss L_mix, which in the authors' words extends the approach of [MPZ18] (Madras, Pitassi, Zemel) to the multiclass setting, and shows (Proposition 3) that this L_mix is realizable (H, R)-consistent for classes closed under scaling (including linear models and neural networks) but not classification-consistent; which property matters more in practice is stated to be not immediately clear.",
          "Inconsistency of mixtures of experts loss and Realizable-consistency",
          "So far we have focused on classiﬁcation consistency to verify the soundness of proposed approaches, however, we usually have speciﬁc hypothesis classes H, R in mind, and if the Bayes predictor is not in our class then consistency might not guarantee much [BDLSS12]."),
         ("Failure mode of an alternative deferral loss (Mozannar & Sontag's finding about their own multiclass implementation of the [MPZ18] approach, not a result of Madras et al.): in the CIFAR-10 experiment with synthetic experts, the mixture-of-experts loss learns never to defer; the authors' explanation is that the classifier's training loss converges to zero while validation accuracy keeps improving, whereas the expert's loss stays constant.",
          "Experiments: CIFAR-10",
          "the mixtures of experts loss of [MPZ18] fails in this setup and learns never to defer."),
         ("How the expert is obtained (Section 6): simulated throughout. CIFAR-10 uses synthetic experts that are perfect on the first k classes and uniform otherwise; CIFAR-100 and CheXpert use probabilistic synthetic experts; hate speech uses a synthetic expert whose probability of being correct depends on whether a language model predicts the tweet to be African-American English (AAE); CIFAR10H simulates an average human annotator by sampling from real crowdworker class counts.",
          "Experiments: CIFAR-10",
          "We simulate multiple synthetic experts of varying competence in the following way: let k ∈[10], then if the image belongs to the ﬁrst k classes the expert predicts perfectly, otherwise the expert predicts uniformly over all classes."),
         ("Fairness of the combined system (hate speech, synthetic experts): with the synthetic fair expert (correct with probability 0.9 on both AAE and non-AAE tweets), the confidence-score baseline doubles the system's discrimination (difference in false positive rates between AAE and non-AAE tweets) relative to the classifier alone; the proposed method does not achieve significantly lower discrimination than the baseline.",
          "Hate Speech and Offensive Language Detection",
          "While our method does not achieve signiﬁcantly lower discrimination than the baseline"),
         ("Input-noise robustness test (CheXpert, synthetic expert with q = 0.7, p = 1; main text, Section 6.6 'Further Analysis'): models trained on original X-rays are evaluated on X-rays with a randomly placed rectangle erased (area varied from 0.1 to 0.66). The text for Figure 8 reports that all methods' maximum achievable AU-ROC/AU-PR (averaged over the 5 tasks) degrade with the noise scale, and the gap between methods stays constant in AU-PR but diminishes in AU-ROC.",
          "Synthetic Experts on CheXpert: Further Analysis (Impact of input noise)",
          "In the second experiment, we train with the original chest X-rays but evaluate with noisy X-rays with noise in the form of erasing a randomly placed rectangular region of the X-ray."),
     ],
     "notes": "Affiliation: Massachusetts Institute of Technology; supported by NSF CAREER award #1350965. Measured quantities: system accuracy, coverage and classifier accuracy on non-deferred examples (CIFAR, CIFAR10H), discrimination (FPR difference) for hate speech, system AU-ROC/AU-PR versus coverage for CheXpert. Evaluation-practice note: in the CheXpert experiments coverage is fixed by setting the deferral threshold tau at a percentile of the score q(x) computed over the test set ('The deﬁnition of τ ensures that we obtain exactly c% coverage'); alpha was chosen on a validation set (grid search for hate speech; validation AU-ROC for CheXpert), and temperature scaling on the validation set calibrates the baselines. The only real human labels used are the CIFAR10H crowdworker annotations, and even there the expert is sampled from label counts. Stated future work (Conclusion): limited expert data, biased expert data, and deferring to multiple experts. No text-classification task tag exists in registry/tags.yaml, so the hate-speech experiment is not reflected in the task tags. Consistency caveat (Section 4): 'note that for α ≠ 1 the loss LCE is no longer consistent', yet alpha is treated as a hyperparameter and tuned (e.g. alpha chosen on validation AU-ROC for CheXpert), so reported results for alpha != 1 are not covered by Theorem 1. Section 5.1 ('Failure of Confidence Scores Method') argues that comparing separately learned classifier and expert confidences [RBC+19] does not allow the classifier to adapt to the expert's strengths and weaknesses and can fail when H and R are restricted."},

    {"id": "arxiv-1711.06664",
     "title": "Predict Responsibly: Improving Fairness and Accuracy by Learning to Defer",
     "authors": ["David Madras", "Toniann Pitassi", "Richard Zemel"],
     "year": 2017, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1711.06664"},
     "tasks": ["selective-prediction", "tabular-classification"],
     "fam": ["deep-learning", "model-cascades"], "par": ["supervised"],
     "proposes": ["Learning to defer (adaptive rejection learning): a two-stage cascade in which a model either predicts or passes to an external decision maker (DM), trained on the system loss (a mixture-of-experts-like objective where only the model expert is learned), with post-hoc threshold and differentiable variants and an equalized-odds regularizer"],
     "claims": [
         ("Contribution: learning to defer generalizes rejection learning by accounting for the external decision maker (DM; e.g. a human user or a proprietary black-box model) that makes the decision when the model says pass, with a learning algorithm that accounts for potential biases of that DM.",
          "Abstract",
          "We extend this concept by proposing learning to defer, which generalizes rejection learning by considering the eﬀect of other agents in the decision-making process."),
         ("Formal result (Theorem, Section 2.3): if the DM has constant loss on each example (e.g. is an oracle), there exist pass penalties gamma_reject, gamma_defer for which the learning-to-defer and rejection-learning objectives are equivalent; i.e. rejection learning is the special case of learning to defer with a constant-loss DM.",
          "Why Learn to Defer?",
          "The proof in Sec. 2.3 shows the central point of learning to defer: rejection learning is exactly a special case of learning to defer: a DM with constant loss α on each example."),
         ("Deferral signal: the post-hoc variant thresholds the model's own score (two thresholds giving a pass region), while the differentiable variant lets the deferral probability depend on the input X as well, because the DM's expected loss may vary with X differently from the model's; at test time it defers when the deferral probability exceeds 0.5.",
          "Learning a Differentiable Model",
          "This is advantageous because a DM’s actions may depend heterogenously on the data: the DM’s expected loss may change as a function of X, and it may do so diﬀerently than the model’s."),
         ("How the DM is obtained: semi-synthetic. Real datasets (COMPAS recidivism with race as sensitive attribute; Heritage Health Charlson Index with age) and a simulated DM trained as a separate classifier with extra information the model does not see; biased DMs are trained with a negative fairness coefficient and inconsistent DMs have predictions flipped with 30% probability on a subgroup.",
          "Experiments",
          "Due to diﬃculty obtaining and evaluating real-life decision-making data, we use “semi-synthetic data”: real datasets, and simulated DM data by training a separate classiﬁer under slightly diﬀerent conditions (see Experiment Details)."),
         ("Reporting protocol: results are shown across sweeps of the fairness coefficient and the defer/reject penalty, each point a median of 5 runs, and in the accuracy-fairness plots only the Pareto front is shown; all results are on held-out test sets. The Pareto front is therefore formed from test-set points; the text does not describe a separate selection set for choosing which settings are plotted.",
          "Experiments",
          "In Fig. 3, we only show the Pareto front, i.e., points for which no other point had both better accuracy and fairness."),
         ("Threshold selection for the post-hoc model uses the test set: 1000 random threshold combinations are sampled, the best on one half of the test set is picked, and it is evaluated on the other half.",
          "Appendix D (Details on Optimization: Hard Thresholds)",
          "We sampled 1000 combinations of thresholds, picked the thresholds which minimized the loss on one half of the test set, and evaluated these thresholds on the other half of the test set."),
         ("Generalization across decision makers is suggested, not tested: the authors note decision data could be sampled from many DMs and cite research suggesting common trends in DM behavior, so a model trained on some DM could generalize to unseen DMs.",
          "Why Learn to Defer?",
          "Research suggests that common trends exist in DM behavior [6, 11], suggesting that a model trained on some DM could generalize to unseen DMs."),
     ],
     "notes": "Affiliation: University of Toronto, Vector Institute. No surrogate-loss consistency guarantee is given (searched 'consisten'; the only matches concern 'inconsistent' DMs); the formal result is the equivalence to rejection learning when the DM has constant loss. Measured quantities: accuracy, disparate impact (equalized-odds gap), deferral rate overall and per subgroup, and minimum subgroup accuracy. Models and DMs are fully connected two-layer networks (5 hidden units for COMPAS, 20 for Health), early stopping on a 20% validation split of training data (Appendix C). Mozannar & Sontag (arxiv-2006.01862, claim c3) later show that their multiclass extension of this mixture-of-experts style loss is not classification-consistent and (claim c4) that it learns never to defer in their CIFAR-10 setup. Tag note: no fairness tag exists in registry/tags.yaml. 'model-cascades' is justified by the text: Section 2.1 states 'The decision-making ﬂow is modeled as a cascade, where the ﬁrst-step model can either predict (positive/negative) or say pass', and the second stage may be a human or 'a proprietary black-box model'; it is an approximation in that the second stage is a fixed external DM, not a stronger model chosen for cost/quality. The paper draws inspiration from mixture-of-experts but the 'mixture-of-experts' family tag was not added because only the model 'expert' is learned."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model fallback and model selection in MLOps (meta-learned selection, dynamic selection, abstention/deferral, switching triggers, cascades/routing, monitoring); carded by a subagent. Results tables not recorded; claims only.")
