import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ae_common import BASE_NOTE  # noqa: E402

SPECS = [
    {"id": "arxiv-1206.5538",
     "title": "Representation Learning: A Review and New Perspectives",
     "authors": ["Yoshua Bengio", "Aaron Courville", "Pascal Vincent"],
     "year": 2012, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1206.5538"},
     "tasks": ["representation-learning"],
     "fam": ["autoencoders"], "par": ["unsupervised"],
     "proposes": ["A review of unsupervised representation learning (probabilistic models, regularized auto-encoders, manifold learning, deep architectures); for auto-encoders, it frames sparse, denoising and contractive variants as regularizers that prevent learning the identity, and relates them to score estimation and manifold tangents"],
     "claims": [
         ("Why plain reconstruction is not enough: since the identity function has zero reconstruction error everywhere, something in the training criterion or the parametrization must prevent the auto-encoder from learning it; the authors call auto-encoders with such means regularized auto-encoders, a low-dimensional code (as in the classical auto-encoder or PCA) being one particular form.",
          "Section 7.1",
          "To capture the structure of the data-generating distribution, it is therefore important that something in the training criterion or the parametrization prevents the auto-encoder from learning the identity function, which has zero reconstruction error everywhere."),
         ("A linear auto-encoder with squared reconstruction error learns the same subspace as PCA; citing Bourlard and Kamp (1988), this also holds with a sigmoid encoder, but not when encoder and decoder weights are tied.",
          "Section 7.1",
          "In the case of a linear auto-encoder (linear encoder and decoder) with squared reconstruction error, minimizing Eq. 19 learns the same subspace"),
         ("Overcomplete codes (more hidden units than inputs), favoured by sparse coding and RBM approaches, can let the auto-encoder simply copy the input into the features and reconstruct perfectly without extracting meaningful features; regularized auto-encoders are presented as ways to constrain the representation even when it is overcomplete.",
          "Section 7.2",
          "This can allow the auto-encoder to simply duplicate the input in the features, with perfect reconstruction without having extracted more meaningful features."),
         ("Sparse auto-encoders: sparsity has been obtained by penalizing hidden biases (which risks the weights compensating for the bias) or the hidden activations directly (L1, Student-t, or a KL penalty towards a target mean activation); the authors state that a clear comparative analysis of the activation-penalty variants is still lacking.",
          "Section 7.2.1",
          "When directly penalizing the hidden unit outputs, several variants can be found in the literature, but a clear comparative analysis is still lacking."),
         ("Denoising auto-encoders (citing Vincent et al. 2008, 2010) are trained to reconstruct the clean input from an artificially corrupted one, so learning the identity is no longer enough; the reconstruction is described as essentially a nearby point of higher density than the corrupted input.",
          "Section 7.2.2",
          "Learning the identity is no longer enough: the learner must capture the structure of the input distribution in order to optimally undo the effect of the corruption process, with the reconstruction essentially being a nearby but higher density point than the corrupted input."),
         ("Contractive auto-encoders (citing Rifai et al. 2011a) add the Frobenius norm of the encoder Jacobian; the authors list three differences from DAEs (feature rather than reconstruction sensitivity is penalized, the penalty is analytic rather than stochastic, and a hyper-parameter controls the trade-off) that may be partly responsible for the better performance CAE features seem to show, and note that the analytic penalty only encourages robustness to infinitesimal input variations.",
          "Section 7.2.3",
          "There are at least three notable differences with DAEs, which may be partly responsible for the better performance that CAE features seem to empirically demonstrate"),
         ("Implication of the score interpretation (citing Vincent 2011 and Alain and Bengio 2012): the reconstruction-minus-input vector is aligned with the estimated score, which can be zero at local maxima but also at local minima of the log-density, so low reconstruction error cannot be equated with high estimated probability.",
          "Section 9.2",
          "It means that we cannot equate low reconstruction error with high estimated probability."),
         ("Evaluation caveat: test-set reconstruction error of auto-encoder and sparse coding variants may be misleading, because larger capacity (more features, more training time) tends to lower it even on the test set, so it cannot be used reliably to select most hyper-parameters; denoising reconstruction error is stated to be immune to this, but not for the hyper-parameter controlling the amount of noise or contraction.",
          "Section 9.5",
          "Hence it cannot be used reliably for selecting most hyper-parameters."),
     ],
     "notes": "Affiliation: U. Montreal (Bengio and Vincent also CIFAR). No venue is stated in the PDF and none was given in the arXiv metadata; no venue recorded. Review paper without own experiments. Disclosure: the authors review their own methods (Vincent: denoising auto-encoders; Bengio: co-author of the contractive/score results cited, e.g. Alain and Bengio 2012 = arxiv-1211.4246). In Section 9.5 the sentence reads 'this immunity can be extended to DAEs' after a sentence about DAEs (as printed; possibly meant CAEs) - not paraphrased in the claim."},

    {"id": "arxiv-1211.4246",
     "title": "What Regularized Auto-Encoders Learn from the Data Generating Distribution",
     "authors": ["Guillaume Alain", "Yoshua Bengio"],
     "year": 2012, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1211.4246"},
     "tasks": ["representation-learning", "generative-modeling"],
     "fam": ["autoencoders"], "par": ["unsupervised"],
     "proposes": ["Theorems showing that the optimal reconstruction function of a denoising auto-encoder with small Gaussian noise and squared error (and of a reconstruction contractive auto-encoder, RCAE) satisfies r(x) - x proportional to the score d log p(x)/dx (and its Jacobian estimates the Hessian) as the noise goes to 0, independent of parametrization; and an approximate Metropolis-Hastings sampler using the estimated energy differences"],
     "claims": [
         ("Main result: the (regularized) auto-encoder captures the score, i.e. the derivative of the log-density with respect to the input; the theorems are generic (not parametrization-specific) and describe what the auto-encoder would tend to given enough capacity and examples.",
          "Abstract",
          "We show that the auto-encoder captures the score (derivative of the log-density with respect to the input)."),
         ("Link between regularizers: the analysed contractive criterion is shown to be similar to the denoising criterion with small corruption noise, with the contraction applied to the whole reconstruction function rather than only the encoder (Proposition 1, via a Taylor expansion).",
          "Abstract",
          "These results are for a contractive training criterion we show to be similar to the denoising auto-encoder training criterion with small corruption noise, but with contraction applied on the whole reconstruction function rather than just encoder."),
         ("Assumptions behind recovering the score: the 'perfect world' scenario assumes no constraint on r (non-parametric), infinite training data and perfect minimization, plus a known and sufficiently small sigma; the theorems are asymptotic as sigma goes to 0. Later subsections drop these assumptions one by one.",
          "Section 3.2",
          "As a starting point, we will assume that we are in a perfect situation, i.e., with no constraint on r (non-parametric setting), an inﬁnite amount of training data, and a perfect minimization."),
         ("Reconstruction error is not an energy: the analysis suggests that in regularized auto-encoders reconstruction error is the norm of an approximate score (contradicting Ranzato et al. 2008's energy view); its norm is small near training examples but could also be small at local minima of density, which happened in the spiral example between two arms of the manifold.",
          "Section 3.4",
          "Note that the norm of the score should be small near training examples (corresponding to local maxima of density) but it could also be small at other places corresponding to local minima of density."),
         ("Protocol of the 2-D spiral experiment: a DAE (tanh encoder, linear decoder, 1000 hidden units, untied weights, Gaussian noise sigma = 0.01) was trained with BFGS on a fixed training set of 10 000 samples; because the solution depends on initialization, corruption noise and finite sample, the model was trained multiple times and the two most visually appealing outcomes were shown (Figure 5). The noise levels in Figure 4 were also selected for visual appeal.",
          "Section 3.4",
          "For those reasons, we trained the model multiple times and selected two of the most visually appealing outcomes."),
         ("Limited parametrization: with a specific parametrization r(x) - x need not be a conservative vector field; for the DAE used, a potential exists only with tied weights, yet untied weights gave much better results and the tied-weight energy is not normalizable, which the authors take to suggest not worrying too much about the exact parametrization as long as it is flexible enough.",
          "Section 3.6",
          "In that sense, this suggests that we should not worry too much about the exact parameterization of the denoising auto-encoder as long as it has the required ﬂexibility to approximate the optimal reconstruction function suﬃciently well."),
         ("Noise-level trade-off when sampling (1-d manifold in 10-D, sigma_train = sigma_MH = 0.1 found after some hyperparameter tweaking): too large a training noise gives a 'blurry' density estimate missing details; too small a noise means the DAE never sees examples far from the manifold, which can lead to strange behaviour when the sampler enters those regions.",
          "Section 4.2",
          "When σtrain is too large, the DAE trained learns a “blurry” version of the density that fails to represent the details that we are interested in."),
         ("Failure mode: spurious probability maxima arise from inadequate DAE training, when the auto-encoder lacks capacity or training ends in a bad local minimum; Figure 7 shows a DAE whose vector field is out of control away from the spiral because the training noise was so small, and the caption states that training with enough examples with sufficiently large corruption noise typically eliminated the problem in the experiments.",
          "Section 4.3",
          "It happens when an auto-encoder lacks the capacity to model the density with enough precision, or when the training procedure ends up in a bad local minimum (in terms of the DAE parameters)."),
     ],
     "notes": "Affiliation: University of Montreal. No venue is stated in the PDF and none was given in the arXiv metadata; no venue recorded. Experiments are toy/artificial (1-D density, 2-D spiral, 1-d manifold in 10-D) and results are figures only; no numbers recorded. The conclusion lists generalization to discrete data as an open question (addressed by the same group in arxiv-1305.6663)."},

    {"id": "arxiv-1305.6663",
     "title": "Generalized Denoising Auto-Encoders as Generative Models",
     "authors": ["Yoshua Bengio", "Li Yao", "Guillaume Alain", "Pascal Vincent"],
     "year": 2013, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1305.6663"},
     "tasks": ["generative-modeling"],
     "fam": ["autoencoders"], "par": ["unsupervised"],
     "proposes": ["Generalized denoising auto-encoder: a DAE viewed as learning the reverse conditional P(X | corrupted X) for any corruption process and any reconstruction loss interpretable as a log-likelihood, with a Markov chain alternating corruption and sampling from the learned conditional whose stationary distribution consistently estimates P(X)",
                  "Walkback training: a corruption process that uses the current model's own chain to generate additional corrupted examples, to remove spurious modes"],
     "claims": [
         ("Limitations of the earlier score result (Alain and Bengio 2013, whose authors are co-authors here): it applies only to Gaussian corruption, continuous inputs and squared error, and only in the limit of small noise, although the authors note that in practice the best results are obtained with large noise levels comparable to the range of the input.",
          "Introduction",
          "it applies to one kind of corruption (Gaussian), only to continuous-valued inputs, only for one kind of loss (squared error), and it becomes valid only in the limit of small noise"),
         ("Proposed interpretation: valid for any data type, any corruption process with broad enough support, and any reconstruction loss that can be viewed as a log-likelihood.",
          "Introduction",
          "What we propose here is a different probabilistic interpretation of DAEs, which is valid for any data type, any corruption process (so long as it has broad enough support), and any reconstruction loss (so long as we can view it as a log-likelihood)."),
         ("Main result (Theorem 1 and Corollary 1): if the learned denoising conditional is a consistent estimator and the chain is ergodic (sufficient conditions: positivity of the data distribution, model and corruption on a bounded region), the stationary distribution of the chain alternating denoising and corruption converges to the data-generating distribution as the number of examples grows.",
          "Conclusion and Future Work",
          "We have proven that training a model to denoise is a way to implicitly estimate the underlying data-generating process, and that a simple Markov chain that alternates sampling from the denoising model and from the corruption process converges to that estimator."),
         ("Why corruption is needed: the conditions of the corollary exclude the case of no corruption, in which the DAE would simply learn a Dirac on its input and give a wrong estimate, and the case of the chain wandering to infinity (handled by assuming a bounded volume).",
          "Consistency",
          "We avoid the case where there is no corruption (which would yield a wrong estimation, with the DAE simply learning a dirac probability its input)."),
         ("Locality trade-off: with a local corruption the reverse conditional is expected to be much simpler (often roughly unimodal) than P(X), which is the expected gain over modelling P(X) directly; but the conditional is only trained for corrupted points near X, so energy estimates may be poor far from the conditioning point.",
          "Locality of the Corruption and Energy Function",
          "Hence, although in theory (with inﬁnite amount of data and capacity) the above estimator should be good, in practice it might be poor when X is far from ˜X."),
         ("Spurious modes: experience with sampling in high dimensions suggests that too local a corruption lets the DAE's behaviour far from the training examples create spurious modes in insufficiently visited regions; more training or more noise helps substantially, and walkback training (which uses the model's own chain to pick corrupted points to walk back from) gave an even bigger boost.",
          "Reducing the Spurious Modes with Walkback Training",
          "if the corruption is too local, the DAE’s behavior far from the training examples can create spurious modes in the regions insufﬁciently visited during training"),
         ("MNIST protocol: a 784-2000-784 DAE on binarized MNIST (salt-and-pepper noise, cross-entropy loss, 200 epochs on 50000 examples); sample quality was estimated by a non-parametric lower bound on test log-likelihood built from 10000 consecutive chain samples; this bound was not used to select architectures, but visual inspection of samples guided the preliminary search, and optimization hyper-parameters were selected on the training objective.",
          "Experimental Validation",
          "The test set log-likelihood bound was not used to select among model architectures, but visual inspection of samples generated did guide the preliminary search reported here."),
         ("Stated outcome and caveat (body text): the DAE bound was higher with walkback than without, which the authors take as confirming the visual impression of fewer spurious samples; the RBM baseline, evaluated with the same estimator, could be improved by a tuned spatial blur, which did not help the auto-encoder.",
          "Experimental Validation",
          "The DAE log-likelihood bound with and without walkback is respectively -116 and -142, conﬁrming visual inspection suggesting that the walkback algorithm produces less spurious samples."),
     ],
     "notes": "Affiliation: Universite de Montreal. No venue is stated in the PDF and none was given in the arXiv metadata; no venue recorded. Disclosure: Vincent is the originator of denoising auto-encoders (Vincent et al. 2008) and Alain and Bengio authored the earlier score result (arxiv-1211.4246) whose limitations are discussed. The RBM baseline (Cho et al. 2013) is reported with an AIS estimate of -64.1 and the authors note that AIS estimates tend to be optimistic; with the same non-parametric estimator it scored -233 (and -112 with tuned blur). Numbers from body text only; no table recorded."},

    {"id": "arxiv-1312.5663",
     "title": "k-Sparse Autoencoders",
     "authors": ["Alireza Makhzani", "Brendan Frey"],
     "year": 2013, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1312.5663"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["autoencoders"], "par": ["unsupervised"],
     "proposes": ["k-sparse autoencoder: a tied-weight autoencoder with linear activations in which only the k largest hidden activities are kept during training (and the alpha*k largest at encoding time), interpreted as an approximation of sparse coding with iterative thresholding with inversion (ITI)"],
     "claims": [
         ("Motivation: sparse autoencoders usually combine activation functions, sampling steps and penalties and are sometimes not guaranteed to give sparse representations for each input; e.g. a 'lifetime sparsity' KL penalty (citing Lee et al. 2007; Nair & Hinton 2009) makes hidden units sparse across training points but not each input's code.",
          "Introduction",
          "This results in sparse activation of hidden units across training points, but does not guarantee that each input has a sparse representation."),
         ("Contribution claim: relying solely on sparsity as the regularizer and as the only nonlinearity, the authors report much better results than the other methods compared, including RBMs, denoising autoencoders and dropout.",
          "Introduction",
          "by solely relying on sparsity as the regularizer and as the only nonlinearity"),
         ("Mechanism: once the k largest activities are selected the network is linear, so the only nonlinearity is the selection, which acts as a regularizer preventing the use of too many hidden units in the reconstruction.",
          "Section 2.2",
          "This selection step acts as a regularizer that prevents the use of an overly large number of hidden units when reconstructing the input."),
         ("Encoding differs from training: features for classification use the alpha*k largest hidden units, with alpha >= 1 selected using validation data, which the authors observed to give slightly better performance (citing Coates & Ng 2011 for mismatched training/encoding stages).",
          "Section 2.2",
          "we have observed that slightly better performance is obtained by using the αk largest hidden units where α ≥1 is selected using validation data."),
         ("Theory: the k-sparse autoencoder is derived as an approximation of a sparse coding algorithm that uses ITI for sparse recovery; Theorem 3.1 shows the first ITI step recovers the support if the dictionary is incoherent enough, and the authors argue that the learnt dictionary must be sufficiently incoherent when training converges.",
          "Section 3.2",
          "In summary, we can view k-sparse autoencoders as the approximation of a sparse coding algorithm which uses ITI in the sparse recovery stage."),
         ("Training failure mode: with low k, the first epochs greedily assign hidden units to groups of examples (similar to k-means) and other units become 'dead'; the authors address this by starting from a large k and linearly decreasing it over the first half of the epochs.",
          "Section 4.2.1",
          "That is, too much sparsity can prevent gradient back-propagation from adjusting the weights of these other ‘dead’ hidden units."),
         ("Effect of sparsity level (qualitative, from filter visualizations): large k gives very local features too primitive for a linear classifier (but usable for pre-training deep nets), smaller k gives more global features, and too much sparsity gives features that are too global and do not factor the input into parts.",
          "Section 4.3",
          "Nevertheless, forcing too much sparsity (e.g., k = 10 on MNIST), results in features that are too global and do not factor the input into parts, as depicted Figure 1d and 2c."),
         ("Evaluation protocol: MNIST training set split into 50,000 training and 10,000 validation, small NORB training set into 20,000 and 4,300; momentum, learning rate and initialization differ per task and dataset and are selected on validation; unsupervised features are evaluated by training logistic regression on fixed features, and baseline feature choices (all hidden units for dropout AE, uncorrupted input for denoising AE) are described as 'this worked best'.",
          "Section 4.2.2",
          "We use diﬀerent momentum values, learning rates and initializations based on the task and the dataset, and validation is used to select hyperparameters."),
     ],
     "notes": "Affiliation: University of Toronto. Venue not recorded: page 1 carries the line 'International Conference on Learning Representations, ICLR 2014' without stating publication status (not confirmed as accepted), and no arXiv comment/journal_ref was given. Results tables (error rates on MNIST and NORB, Tables 1-4) not recorded; the dump's table numbers were not read."},

    {"id": "arxiv-2003.05991",
     "title": "Autoencoders",
     "authors": ["Dor Bank", "Noam Koenigstein", "Raja Giryes"],
     "year": 2020, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2003.05991"},
     "tasks": ["representation-learning", "generative-modeling", "anomaly-detection"],
     "fam": ["autoencoders", "variational-autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised"],
     "proposes": ["A book-chapter survey of autoencoder types (regularized: sparse, denoising, contractive; variational and disentangled) and applications (generation, classification, clustering, anomaly detection, recommendation, dimensionality reduction) and of combinations with GANs"],
     "claims": [
         ("When the hidden layer is at least as large as the input, there is a risk that the encoder learns the identity function; regularization is described as a way to prevent this without a bottleneck.",
          "Section 2",
          "In cases where the size of the hidden layer is equal or greater than the size of the input, there is a risk that the encoder will simply learn the identity function."),
         ("A bottleneck alone is not sufficient: even with a bottleneck of a single node, overfitting is still possible if encoder and decoder have enough capacity to encode each sample to an index.",
          "Section 2",
          "overﬁtting is still possible if the capacity of the encoder and the decoder is large enough to encode each sample to an index."),
         ("Citing [38], a linear autoencoder achieves the same latent representation as PCA; the authors therefore describe an autoencoder as a generalization of PCA that can learn a non-linear manifold.",
          "Section 1",
          "Therefore, an autoencoder is in fact a generalization of PCA, where instead of ﬁnding a low dimensional hyperplane in which the data lies, it is able to learn a non-linear manifold."),
         ("Anomaly detection use: the objective is to learn a normal profile from normal data only, assuming a trained autoencoder learns the latent subspace of normal samples and thus gives low reconstruction error for normal samples and high error for anomalies (citing [21, 18, 62, 61]). No discussion of how the anomaly threshold is set, or of failure modes such as anomalies being reconstructed well, was found in the text (searched for threshold, anomal, outlier, novelty, limitation, weakness).",
          "Section 4.4",
          "The use of autoencoders for this tasks, follows the assumption that a trained autoencoder would learn the latent subspace of normal samples."),
         ("Clustering use: the main disadvantage of vanilla autoencoders for clustering is that the embeddings are trained solely for reconstruction, not for clustering; modifications add a cluster-distance term or a prior on the embeddings.",
          "Section 4.3",
          "The main disadvantage of using vanilla autoencoders for clustering is that the embeddings are trained solely for reconstruction and not for the clustering application."),
         ("Limitation of reconstruction losses: autoencoder reconstructions of images are usually blurry, which the authors attribute to a loss that does not take into account how realistic the results are; combinations with GANs are presented as addressing this.",
          "Section 5",
          "On the other hand, by looking at the reconstruction quality of autoencoders for images, one of its major weaknesses becomes clear, as the resulting images are usually blurry."),
         ("Dimensionality reduction: PCA is optimal as a linear projection, while non-linear methods such as autoencoders 'may and often do' achieve superior results (stated without supporting experiments in the chapter).",
          "Section 4.6",
          "However, non-linear methods such as autoencoders, may and often do achieve superior results."),
         ("Open problem: for generative modelling, choosing the size and distribution of the hidden state is still done by experimentation (reconstruction error and varying the hidden state after training), and the authors call for research to set these parameters better.",
          "Section 6",
          "As for modeling generative processes, despite the success of variational and disentangled autoencoders, the way to choose the size and distribution of the hidden state is still based on experimentation, by considering the reconstruction error, and by varying the hidden state at post training."),
     ],
     "notes": "Affiliation: Tel Aviv University. arXiv comment: 'Book chapter' without naming the book; no venue recorded. Survey chapter without own experiments (one illustrative figure of VAE samples on MNIST)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, created_at="2026-10-04", created_by="claude-opus-5-5 via Claude Code (subagent)")
