import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_unc_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1904.06019",
     "title": "Conformal Prediction Under Covariate Shift",
     "authors": ["Ryan J. Tibshirani", "Rina Foygel Barber", "Emmanuel J. Candès", "Aaditya Ramdas"],
     "year": 2019, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1904.06019"},
     "tasks": ["uncertainty-estimation", "tabular-regression"],
     "fam": ["conformal-prediction", "linear-models", "random-forests"], "par": ["supervised", "post-hoc"],
     "proposes": ["Weighted conformal prediction: under covariate shift, each nonconformity score is weighted in proportion to the likelihood ratio w(x) = dP~X/dPX of test to training covariate distributions, and the band uses a quantile of this weighted empirical distribution (plus a point mass at infinity weighted by w at the test point); a weighted split conformal variant is also given",
                  "Weighted exchangeability: a generalization of exchangeability (joint density factorizes as a product of per-point weight functions times a permutation-invariant function) under which a weighted quantile lemma and weighted conformal prediction give valid coverage"],
     "claims": [
         ("Setting and assumption: training points are i.i.d. from P = PX x PY|X and the test point from P~ = P~X x PY|X, independently; the conditional distribution of Y given X is assumed to be the same for training and test data (covariate shift). Ordinary conformal prediction relies only on exchangeability, which no longer holds here.",
          "Section 2 (Covariate shift)",
          "Notice that the conditional distribution of Y |X is assumed to be the same for both the training and test data."),
         ("Guarantee (Corollary 1): if P~X is absolutely continuous with respect to PX and the weights use w = dP~X/dPX, the weighted conformal band has marginal coverage P{Y_{n+1} in C_n(X_{n+1})} >= 1 - alpha for any score function; the same holds if w is known only up to a normalization constant (Remark 3). For weighted split conformal, coverage holds conditional on the preliminary data used to fit the regression function.",
          "Section 2 (Weighted conformal prediction)",
          "Assume that ePX is absolutely continuous with respect to PX"),
         ("Unlike the unweighted case (upper bound 1 - alpha + 1/(n+1) when there are no ties), the authors state that a meaningful upper bound on coverage for the weighted quantile lemma does not seem possible without further conditions on the weights, because a single weight can be very large.",
          "Section 3 (Remark 5)",
          "does not seem possible without further conditions on the weight functions in consideration"),
         ("Cost: in general the weighted methodology requires quantiles of a weighted discrete distribution of scores, which is combinatorially hard, but under covariate shift with a known likelihood ratio the computation simplifies and weighted conformal is as easy computationally as ordinary conformal prediction.",
          "Section 4 (Discussion)",
          "In this case, known as covariate shift, the new weighted conformal prediction methodology is just as easy, computationally, as ordinary conformal prediction."),
         ("Airfoil experiment (UCI, N = 1503, d = 5; 5000 random splits into 25% for fitting a linear-regression mu0, 25% calibration, 50% test; nominal 90%, alpha = 0.1). The shifted test set is synthetic: 25% of the test points resampled with probabilities proportional to exp(x^T beta), so the likelihood ratio is known. Ordinary split conformal had average coverage 90.2% on the unshifted test set but considerably undercovered on the shifted one (82.2%).",
          "Section 2 (Airfoil data example)",
          "but for the nonuniformly subsampled test data Dshift (covariate shift, in blue), split conformal considerably undercovers, with its average coverage being 82.2%."),
         ("With oracle weights, weighted split conformal brought average coverage back to 90.8%, but the coverage histogram was more dispersed than without shift because the weighted quantile relies on a reduced effective sample size; unweighted split conformal run with that effective number of calibration points lined up very closely with the weighted method.",
          "Section 2 (Airfoil data example)",
          "This is because, by using a quantile of the weighted empirical distribution of nonconformity scores, we are relying on a reduced “effective sample size”."),
         ("Estimated weights: the likelihood ratio is estimated by a classifier distinguishing training from (unlabeled) shifted test covariates, using the odds p(x)/(1 - p(x)); logistic regression (well-specified here because the tilt is log-linear) and random forests (probabilities clipped to [0.01, 0.99] to avoid infinite weights) each gave 91.0% average coverage, with histograms only a little more dispersed than with oracle weights; random-forest-weighted intervals were more variable and in some cases much longer.",
          "Section 2 (Airfoil data example)",
          "Both classiﬁcation approaches deliver weights that translate into good average coverage, being 91.0% for each approach."),
         ("Scope of the evidence for estimated weights: the authors state that when the likelihood ratio is not known it can be estimated from unlabeled test covariates, which they showed empirically on a low-dimensional example can still yield correct coverage (the theorem itself assumes the true ratio).",
          "Section 4 (Discussion)",
          "When the likelihood ratio d ePX/dPX is not known, it can be estimated given access to unlabeled data (test covariate points), which we showed empirically, on a low-dimensional example, can still yield correct coverage."),
         ("Conditional coverage: citing Vovk (2012) and Lei and Wasserman (2014), exact conditional coverage for almost all x0 and all distributions forces infinite expected length at non-atom points. Weighted conformal with a kernel weight centred at x0 gives a locally weighted guarantee, but only for a centre point specified in advance (the band must be recomputed for each x0), so the authors state that many problems in assumption-lean conditional predictive inference remain open.",
          "Section 4 (Towards local conditional coverage?)",
          "We have only described a way to satisfy such a property if the center point x0 were speciﬁed in advance."),
     ],
     "notes": "No venue recorded: the PDF text has no venue statement (searched for NeurIPS, Neural Information, proceedings, journal) and no journal_ref/comment venue was given. Section 2 and Section 3/3.1/4 numbers are confirmed by cross-references in the introduction and proofs ('In Section 2, we describe...', 'Section 3.1', 'Section 3.5', 'Section 2.2'); subsection names are used otherwise. Interval lengths (Figure 3): oracle-weighted intervals were longer than unweighted ones at equal effective sample size, which the authors attribute to mu0 not being adjusted for the shift. With no actual shift (Figure 4), logistic-regression weights behaved like unweighted conformal and random-forest weights gave slightly more dispersed coverage and lengths. Coverage values are histogram averages written in the body text; the histograms themselves were not read. Other applications discussed (graphical models with covariate shift, missing covariates with known summaries) are not recorded as claims."},

    {"id": "arxiv-2202.13415",
     "title": "Conformal prediction beyond exchangeability",
     "authors": ["Rina Foygel Barber", "Emmanuel J. Candès", "Aaditya Ramdas", "Ryan J. Tibshirani"],
     "year": 2022, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/2202.13415"},
     "tasks": ["uncertainty-estimation", "tabular-regression"],
     "fam": ["conformal-prediction", "linear-models"], "par": ["supervised", "post-hoc"],
     "proposes": ["Nonexchangeable conformal prediction (NexCP): split and full conformal (and jackknife+) using fixed, prespecified weights w_i in [0, 1] on the calibration residuals (weighted quantiles), e.g. geometrically decaying weights under drift",
                  "A random swap step (swap the test point's tag with that of a point K drawn with probability proportional to the weights) that allows nonsymmetric fitting algorithms (e.g. weighted least squares, changepoint-aware or autoregressive fits) inside full conformal",
                  "A coverage-gap bound: coverage >= 1 - alpha - sum_i w~_i d_TV(R(Z), R(Z^i)), with no assumption on the joint distribution"],
     "claims": [
         ("Conformal validity relies on two assumptions: exchangeability of the data and a model-fitting algorithm that treats data points symmetrically. The paper drops both, generalizing split conformal, full conformal and the jackknife+.",
          "Abstract",
          "Its validity relies on the assumptions of exchangeability of the data, and symmetry of the given model ﬁtting algorithm as a function of the data."),
         ("What the guarantee becomes: the coverage gap ((1 - alpha) minus the actual coverage) is bounded by a weighted sum of total-variation distances between the data (or, more tightly, the residual vectors) and the same with the test point swapped with point i, with no assumption on the joint distribution. The weights must be fixed (not data-dependent), and the authors state that using these methods implicitly assumes this weighted TV sum is small.",
          "Introduction",
          "In particular, if we use these methods, we are implicitly assuming that this weighted sum of total variation terms is small."),
         ("Under exchangeability the bound is zero, so introducing fixed weights loses no coverage; with unit weights and a symmetric algorithm the theorems also give a new robustness result for standard split/full conformal (gap at most sum_i d_TV / (n + 1)), which the authors say helps explain their success on real data where exchangeability may not hold. Theorem 3 gives an upper bound on coverage (no substantial overcoverage) when w~_{n+1} is small.",
          "Theory (Remarks on the theorems)",
          "These new bounds ensure robustness of existing methods against mild violations of the exchangeability (or i.i.d.) assumption, and thus help explain the success of these methods on real data, where the exchangeability assumption may not hold."),
         ("Cost of weighting: low weights reduce the effective sample size (e.g. for estimating the residual quantile), so overly low weights often widen intervals; all-zero weights give zero coverage gap but an uninformative interval (the whole real line). Optimal weight choice is left open.",
          "Theory (Remarks on the theorems)",
          "How to choose weights optimally (and, even how to quantify optimality) is an interesting and important question that we leave for future work."),
         ("When the guarantee is useful: the bound holds with no distributional assumption but is meaningless if large, so the weights should be chosen in advance from (at least qualitative) prior knowledge of the likely deviation, e.g. geometric decay under gradual drift; if the test point comes from a distribution bearing no resemblance to the training data, no method can guarantee coverage without further assumptions. Whether coverage will likely hold for a particular data set is named as an open question.",
          "Theory (Is the guarantee useful?)",
          "On the other hand, if the test point comes from a new distribution that bears no resemblance to the training data, neither our bound nor any other method would be able to guarantee valid coverage without further assumptions."),
         ("Examples with weights w_i = rho^(n+1-i): for independent data with Lipschitz-type bounded drift (d_TV(Z_i, Z_{n+1}) <= eps (n + 1 - i)) the gap is at most 2 eps / (1 - rho); after a changepoint k steps ago the gap is at most rho^k, small only when plenty of data has been observed since the changepoint.",
          "Section 4.4 (Examples)",
          "This yields a small coverage gap as long as k is large, i.e., as long as we have plenty of data observed after the most recent changepoint."),
         ("Nonsymmetric algorithms need the random swap step for the guarantee; the swap may alter the fitted model and could make predictions far less accurate in some settings (e.g. autoregressive models where the most recent point matters most). The theory does not rely on stability assumptions, and practical implementation in such settings is left to future work.",
          "Section 3 (The swap step)",
          "We leave the important question of practical implementation for such settings, and the question of how to choose algorithms A that will not be too sensitive to the swap, to future work."),
         ("Contrast with weighted conformal under covariate shift (citing Tibshirani et al. 2019): that method needs the covariate-shift assumption and a known or well-approximated, possibly high-dimensional likelihood ratio, with data-dependent weights; here the weights are fixed and can compensate for unknown but small violations. The authors state that if the data were in fact exchangeable, the covariate-shift weighted algorithm has no coverage guarantee, while theirs retains exact coverage.",
          "Section 2 (Further related work)",
          "Finally, and importantly, if there was actually no distribution shift, and the data happened to be exchangeable, their weighted algorithm does not have any coverage guarantee, while ours retains exact coverage."),
         ("Simulations (N = 2000, Gaussian covariates; Setting 1 i.i.d., Setting 2 two changepoints in the coefficients, Setting 3 linear drift; online after a 100-point burn-in, 200 replications, target 90%): full conformal with least squares (CP+LS) undercovers after changepoints and as drift grows, while NexCP+LS and NexCP+WLS (weights and tags 0.99^(n+1-i)) better maintain coverage; NexCP+WLS gives narrower intervals than CP+LS, and weighted methods have slightly higher width variability under i.i.d. data (lower effective sample size).",
          "Section 5.1 (Simulations)",
          "The NexCP+LS and NexCP+WLS methods are better able to maintain coverage in these settings."),
     ],
     "notes": "No venue recorded: the PDF text has no venue statement (searched for Annals, journal, to appear, accepted) and no journal_ref/comment was given. Overlapping authors with arXiv-1904.06019 (weighted conformal under covariate shift), which this paper contrasts with its own method (claim c8). Section numbers: Section 2, 3.1, 4.3-4.5, 5.1, 5.2 confirmed by in-text cross-references; Section 3 and 4 headings are cited by name where the exact number is not confirmed. Additional caveat (Extensions): the coverage reduction is additive (alpha + Delta), which may be a substantial increase in error probability if alpha is very low; a multiplicative bound under Huber contamination (symmetric algorithms only) is in Appendix C. Real data: ELEC2 electricity (N = 3444 after filtering, with a randomly permuted copy as an exchangeable control) and 2020 US election counties (Eastern-time counties as training, 1119 train / 1957 test; weights from 2016 covariates with gamma set so the effective sample size is 100; also quantile-regression scores). Tables 1-3 values not recorded. Jackknife+ and split conformal versions are in the appendices (not read in detail)."},

    {"id": "arxiv-2106.00170",
     "title": "Adaptive Conformal Inference Under Distribution Shift",
     "authors": ["Isaac Gibbs", "Emmanuel Candès"],
     "year": 2021, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2106.00170"},
     "tasks": ["uncertainty-estimation", "time-series-forecasting", "tabular-regression"],
     "fam": ["conformal-prediction"], "par": ["supervised", "post-hoc"],
     "proposes": ["Adaptive conformal inference (ACI): in an online setting, the nominal miscoverage level alpha_t passed to the conformal quantile is updated after each observed label by alpha_{t+1} = alpha_t + gamma (alpha - err_t), as a wrapper around any score function and quantile estimate"],
     "claims": [
         ("Setting and guarantee: an online setting where the data-generating distribution may vary over time in an unknown fashion; previous conformal methods rely on exchangeability, while ACI provably achieves the desired coverage frequency over long time intervals regardless of the true data-generating process.",
          "Abstract",
          "our adaptive approach provably achieves the desired coverage frequency over long-time intervals irrespective of the true data generating process."),
         ("Method: since under non-stationarity the realized miscoverage M_t(alpha) need not equal alpha, the argument of the fitted quantile function is recalibrated online, lowering (raising) alpha_t when past sets under-covered (over-covered), via alpha_{t+1} = alpha_t + gamma (alpha - err_t); this requires the label Y_t to be observed after each prediction. A weighted-history variant gave almost identical results in their experiments.",
          "Adapting conformal inference to distribution shifts",
          "To perform this calibration we will use a simple online update."),
         ("Distribution-free result (Proposition 4.1): with probability one, |(1/T) sum_t err_t - alpha| <= (max{alpha_1, 1 - alpha_1} + gamma) / (T gamma) for all T, so the long-run miscoverage frequency converges to alpha with no assumptions on the data. The authors argue that without assumptions on the initialization this cannot be improved in the worst case right after initialization.",
          "Section 4.1",
          "Proposition 4.1 puts no constraints on the data generating distribution."),
         ("Long-run versus per-time coverage: the large-deviation bound on the average miscoverage (Theorem 4.1) says nothing about marginal coverage at a single time step; Theorem 4.2 bounds the expected squared gap between realized marginal miscoverage and alpha by the size of the shift in the optimal alpha*_t, under a hidden Markov model with a stationary chain, a quantile/score function fixed over time and a Lipschitz miscoverage function.",
          "Section 4.2",
          "On the other hand, it provides no information about the marginal coverage frequency at a single time step."),
         ("The hidden-Markov-model assumptions behind the per-time results are simplifications: the authors do not expect them to hold exactly in any real-world setting, though they consider the results representative and expect similar results under other models.",
          "Section 4.2",
          "While we do not expect these assumptions to hold exactly in any real-world setting, we do consider our results to be representative of the true behaviour of adaptive conformal inference and we expect similar results to hold under alternative models."),
         ("Step size: gamma trades adaptability against stability (large gamma lets alpha_t oscillate between small conservative and large anti-conservative sets); the experiments use gamma = 0.005, chosen because it was found to give relatively stable trajectories while still adapting; too small a gamma behaves like fixed alpha. The data on which this choice was made is not stated (searched for tuned, validation, held out).",
          "Section 2.1",
          "The choice of γ gives a tradeoff between adaptability and stability."),
         ("Volatility experiment: GARCH(1,1) point predictions refit on the last 1250 trading days, a normalized absolute-residual score, alpha = 0.1, compared with fixed alpha via local coverage over about two years. The four stocks shown were selected out of 12 examined because they showed a clear failure of the non-adaptive method; ACI was found to perform well in all cases (appendix figure).",
          "Section 2.2",
          "These stocks were selected out of a total of 12 stocks that we examined because they showed a clear failure of the non-adaptive method."),
         ("Score choice: coverage of ACI is governed by the size of the shift in alpha*_t, which corresponds to the 1 - alpha quantile of the score, so it depends on how close the score is to stationary; an unnormalized residual score gave much wider swings in local coverage than the normalized one (partially mitigated by a larger gamma). Interval length depends on the fitted model, so the model should be refit on recent data.",
          "Impact of St(·) on the performance",
          "Thus, the coverage properties of adaptive conformal inference depend on how close St(Xt, Yt) is to being stationary."),
         ("Limitations stated by the authors: the method assumes Y_t is revealed at every time point (delayed or batched feedback is not covered); the per-time theory covers a single data model with a fixed quantile function; gamma should ideally be chosen adaptively without prior knowledge; experiments cover only two domains.",
          "Discussion",
          "The methods we develop are speciﬁc to cases where Yt is revealed at each time point."),
     ],
     "notes": "No venue recorded: page 1 footer says 'Preprint. Under review.' and no journal_ref/comment venue was given. Sections 2.1, 2.2, 4.1, 4.2 and 6 are confirmed by in-text cross-references; other locations use heading names. Second experiment (Section 6): county-level 2020 election vote totals with conformalized quantile regression (linear quantile regression per the appendix algorithm), counties ordered by time zone (random within zone) to mimic reporting drift; the non-adaptive method had troughs in local coverage at time-zone changes, while ACI stayed near 90% with deviations comparable to a Bernoulli sequence (figure-based statements; no numbers recorded). Local coverage is compared visually with i.i.d. Bernoulli(0.1) sequences. Related work notes that likelihood-ratio reweighting (Tibshirani et al.) requires an unchanged Y|X and a known or very accurately estimated ratio."},

    {"id": "arxiv-2107.03342",
     "title": "A Survey of Uncertainty in Deep Neural Networks",
     "authors": ["Jakob Gawlikowski", "Cedrique Rovile Njieutcheu Tassi", "Mohsin Ali", "Jongseok Lee", "Matthias Humt",
                 "Jianxiang Feng", "Anna Kruspe", "Rudolph Triebel", "Peter Jung", "Ribana Roscher", "Muhammad Shahzad",
                 "Wen Yang", "Richard Bamler", "Xiao Xiang Zhu"],
     "year": 2021, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2107.03342"},
     "tasks": ["uncertainty-estimation"],
     "fam": ["deep-learning", "bayesian-deep-learning", "post-hoc-calibration"], "par": ["supervised"],
     "proposes": ["A survey (no new method): sources of uncertainty in DNNs (five factors), data vs model (and distributional) uncertainty, a four-way taxonomy of estimation methods, uncertainty measures, calibration methods and measures, data sets/baselines, applications, and open challenges"],
     "claims": [
         ("Data vs model uncertainty: predictive uncertainty is separated into data (aleatoric) and model (epistemic) uncertainty; model uncertainty covers four of the authors' five factors (real-world variability, model structure, training procedure, unknown data) and data uncertainty covers measurement error and noise (including label noise). Model uncertainty can (theoretically) be reduced, data uncertainty cannot.",
          "Section II (Predictive Uncertainty Model)",
          "While model uncertainty can be (theoretically) reduced by improving the architecture, the learning process, or the training data set, the data uncertainties cannot be explained away [60]."),
         ("Taxonomy: uncertainty estimation methods are split into four types by the number and nature of the networks: single deterministic methods (one forward pass), Bayesian methods (stochastic networks), ensemble methods (several deterministic networks), and test-time augmentation (one network, augmented inputs).",
          "Section III",
          "In general, the methods for estimating the uncertainty can be split in four different types based on the number (single or multiple) and the nature (deterministic or stochastic) of the used DNNs."),
         ("Single deterministic methods are computationally efficient (one network, one or at most two forward passes, often applicable to pretrained networks), but because they rely on a single opinion they can be very sensitive to architecture, training procedure and training data.",
          "Section III (Summing Up Single Deterministic Methods)",
          "A drawback of single deterministic neural network approaches is the fact that they rely on a single opinion and can therefore become very sensitive to the underlying network architecture, training procedure, and the training data."),
         ("Ensemble cost and caveats: ensembles are easy to apply and parallelize, but memory and computation grow linearly with the number of members for training and testing, limiting deployment under compute/memory/time constraints; the main challenge is member diversity, and overconfidence of single members can transfer to the whole ensemble.",
          "Section III (Sum Up Ensemble Methods)",
          "The independence of the single ensemble members leads to a linear increase in the required memory and computation power with each additional member."),
         ("Ensembles vs Bayesian approaches: citing Gustafsson et al. [56], the survey reports that in their tests ensembles outperformed the considered Bayesian approaches, which it takes to indicate that multi-mode evaluation is a powerful property; it adds that Bayesian approaches have also delivered strong results with a strong theoretical foundation, and that prior-network-style deterministic methods often need separate in- and out-of-distribution sets for training.",
          "Section III (Neural Network Uncertainty Quantification Approaches for Real Life Applications)",
          "Interestingly, they found for their tests ensembles to outperform the considered Bayesian approaches."),
         ("Calibration methods are grouped as regularization during training, post-processing after training, and uncertainty estimation methods; post-processing methods require a held-out calibration set, only work if its distribution equals the inference distribution, and their result can depend on the size of that set.",
          "Section V (Calibration Methods)",
          "They only work under the assumption that the distribution of the left-out validation set is equivalent to the distribution, on which inference is done."),
         ("Recalibration does not reduce model uncertainty: the survey states that explicit calibration methods propagate model uncertainty onto the representation of data uncertainty (e.g. mapping an overfitted classifier's outputs to 0.5).",
          "Section V (Calibration)",
          "It is important to note that these methods do not reduce the model uncertainty, but propagate the model uncertainty onto the representation of the data uncertainty."),
         ("Calibration measures: ECE uses M equal-width bins and only the top-label confidence; SCE averages over all classes; adaptive (equal-mass) versions aECE and aSCE are, citing empirical results in [280] and [288], more robust to the number of bins. Classwise or not, calibration errors are weighted by class sizes, so larger classes can shadow poor calibration on small classes.",
          "Section V (Evaluating Calibration Quality)",
          "As has been empirically shown in [280] and [288], the adaptive binning calibration measures aECE and aSCE are more robust to the number of bins than the corresponding equal-width binning calibration measures ECE and SCE."),
         ("Open challenges named for real-world adoption: missing validation on real-world problems (baselines mostly developed on standard data sets such as CIFAR/ImageNet), lack of a standardized evaluation protocol, inability to evaluate the uncertainty of a single decision (measures such as ECE aggregate over the test set), lack of ground-truth uncertainties (and calibration not transferring across shifted data), and an explainability issue.",
          "Section VIII (Conclusion)",
          "However, a clear standardized protocol of tests that should be performed on uncertainty quantiﬁcation methods is still not available."),
     ],
     "notes": "No venue recorded: the PDF text has no venue statement (searched for submitted, accepted, transactions on, under review, preprint in the front matter) and no journal_ref/comment was given. Author list from the PDF first page (IEEE membership grades omitted). Section numbers are the survey's Roman numerals as listed in its introduction; subsection names are given in parentheses. Section IV notes evaluation is hard because quality depends on the estimation method, ground-truth uncertainties are lacking, and there is no unified metric across classification, regression and segmentation; regression intervals are evaluated with PICP and MPIW. Test-time augmentation: augmentations must stay within the target distribution, can turn correct predictions into incorrect ones (citing Shanmugam et al.), and the number/kind of augmentations needed is an open question. Conformal prediction is not covered in the survey (searched for conformal). The survey cites Gustafsson et al. for the ensemble-vs-Bayesian finding; it does not run its own comparison."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
