import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tree_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1910.03225",
     "title": "NGBoost: Natural Gradient Boosting for Probabilistic Prediction",
     "authors": ["Tony Duan", "Anand Avati", "Daisy Yi Ding", "Khanh K. Thai", "Sanjay Basu", "Andrew Y. Ng", "Alejandro Schuler"],
     "year": 2019, "venue": "ICML 2020", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1910.03225", "code": "https://github.com/stanfordmlgroup/ngboost"},
     "tasks": ["uncertainty-estimation", "tabular-regression"],
     "fam": ["gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["NGBoost: multiparameter gradient boosting that fits base learners to the natural gradient of a proper scoring rule with respect to the parameters of a conditional distribution (e.g. Normal with mean and log-scale), modular in base learner, distribution family and scoring rule"],
     "claims": [
         ("Motivation: in regression, GBMs output only a scalar; under squared-error loss this can be read as the mean of a Gaussian with constant variance, which the authors say has little use; predicted distributions need at least two parameters to convey both magnitude and uncertainty.",
          "Introduction",
          "However, such probabilistic interpretations have little use if the variance is assumed constant."),
         ("Design choice: the parameters of the conditional distribution are boosted jointly (one base learner per parameter per stage), and natural gradients are used because ordinary gradients are not invariant to reparameterization and the parameterization can drastically change training dynamics.",
          "The Generalized Natural Gradient",
          "Thus the choice of parameterization can drastically impact the training dynamics, even though the minima are unchanged."),
         ("Failure mode of ordinary gradients (Figure 4, toy data): examples that happen to lie close to the initial mean dominate learning, because their variances are adjusted much more aggressively than the wrong means of the other examples, giving simultaneous overfitting and underfitting; the natural gradient balances the updates.",
          "Figure 4",
          "With ordinary gradients, we observe that “lucky” examples that are accidentally close to the initial predicted mean dominate the learning."),
         ("Cost: one series of learners per distribution parameter (cost linear in the number of parameters p) and a p x p matrix inversion per observation; the authors state NGBoost scales like other boosting algorithms in N but with larger constants depending on p.",
          "Analysis and Discussion",
          "The relative increase in computational cost is thus linear in the number of distributional parameters (p)."),
         ("Evaluation protocol (UCI regression, following Hernández-Lobato and Adams 2015): 10% random test split; 20% of the remaining 90% held out to choose the number of boosting stages M by log-likelihood, then retraining on the full 90%; repeated 20 times (Protein 5 times, Year MSD once). NGBoost used a Normal distribution, depth-3 trees, log score, learning rate 0.01 (0.1 for Year MSD).",
          "Experiments",
          "This entire process is repeated 20 times for all datasets except Protein and Year MSD, for which it is repeated 5 times and 1 time respectively."),
         ("Baseline caveat: MC dropout, Deep Ensembles and Concrete Dropout results are taken from their original papers rather than re-run; GAMLSS and Distributional Forest (200 trees, default hyperparameters) and a GP were run by the authors.",
          "Probabilistic regression",
          "We use the results from Gal and Ghahramani (2016) as our benchmark."),
         ("Ablation: plain multiparameter boosting with ordinary gradients most often did worse than assuming homoscedasticity, likely due to poor training dynamics, and second-order (Newton) boosting did even worse; natural gradients correct this.",
          "Conclusions",
          "However, us- ing multiparameter boosting to relax the homoscedasticity assumption most often results in worse performance, likely due to poor training dynamics."),
         ("Point-estimation comparison with scikit-learn baselines: gradient boosting was tuned over learning rate, depth and iterations, random forest used 500 trees with other parameters at default; the authors note that NGBoost was optimized for NLL rather than RMSE and was less aggressively tuned than the comparators.",
          "Conclusions",
          "This is despite the fact that the NGBoost mod- els were (a) optimized for NLL, not to minimize RMSE and (b) less aggressively tuned."),
     ],
     "notes": "Affiliations: Stanford University, Unlearn.ai, Harvard Medical School. Venue from the PDF footer ('Proceedings of the 37th International Conference on Machine Learning, Vienna, Austria, PMLR 108, 2020') and the arXiv comment. The authors also release the evaluated method as the open-source ngboost package. Results tables (Tables 1-3, NLL and RMSE on UCI) not recorded. The Malinin et al. paper (arxiv-2006.10562) points out that NGBoost models only data (aleatoric) uncertainty."},

    {"id": "arxiv-2006.10562",
     "title": "Uncertainty in Gradient Boosting via Ensembles",
     "authors": ["Andrey Malinin", "Liudmila Prokhorenkova", "Aleksei Ustimenko"],
     "year": 2020, "venue": "ICLR 2021", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2006.10562", "code": "https://github.com/yandex-research/GBDT-uncertainty"},
     "tasks": ["uncertainty-estimation", "tabular-classification", "tabular-regression"],
     "fam": ["gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["Ensemble-based estimation of total, data and knowledge uncertainty for GBDT models using ensembles of SGB or SGLB models",
                  "Virtual SGLB ensemble (vSGLB): truncated sub-models of a single SGLB model (every K-th iteration from the second half) used as ensemble members at the cost of one model"],
     "claims": [
         ("Gap identified: NGBoost-style GBDT models that predict a mean and variance capture only data (aleatoric) uncertainty, not knowledge (epistemic) uncertainty about inputs far from or sparsely covered by the training data.",
          "Introduction",
          "However, such models only capture data uncertainty (Gal, 2016; Malinin, 2019), also known as aleatoric uncertainty, which arises due to inherent class overlap or noise in the data."),
         ("Ensemble generation: SGB ensembles (independent stochastic gradient boosting models with different seeds) have no guarantee of approximating the true posterior; SGLB (Stochastic Gradient Langevin Boosting, by two of the authors) is used because its models are asymptotically sampled from the true posterior.",
          "Generating ensembles of GDBT models",
          "Unfortunately, there are no guarantees on how well the distribution q(θ) estimates the true posterior p(θ|D)."),
         ("Virtual ensembles trade quality for cost: members are truncated sub-models of one GBDT and are strongly correlated; on synthetic data the authors conclude that vSGLB knowledge-uncertainty estimates are very cheap but inferior to ensembles of independent models.",
          "Analysis on synthetic data",
          "This shows that while vSGLB yields very cheap estimates of knowledge uncertainty by exploiting the ‘ensemble of trees’ structure of GBDT models, the quality of these estimates is inferior to ensembles of independent models."),
         ("Failure mode on continuous features: traces of class boundaries remain in knowledge-uncertainty maps, possibly because split values vary across ensemble members near class borders (decision-boundary 'jitter'); outside the training domain, trees extend the boundary behaviour outward.",
          "Analysis on synthetic data",
          "However, we still can see traces of the class boundaries in Figure 3(c)."),
         ("On real datasets, ensembles do not outperform single models for error detection (PRR); the authors believe this is because GBDT models are already ensembles and because knowledge uncertainty contributes little to total uncertainty.",
          "Detection of errors and anomalous inputs",
          "However, ensembles do not outperform single models."),
         ("Knowledge-uncertainty measures give better out-of-domain detection (AUC-ROC) than total uncertainty; the OOD data are synthetic, sampled from another dataset (Year MSD, or CT slices for KDD datasets and Year MSD) because real OOD examples were hard to obtain.",
          "Detection of errors and anomalous inputs",
          "However, obtaining ‘real’ OOD examples for the datasets considered in this work is challenging, so we instead create synthetic OOD data as follows."),
         ("Evaluation protocol: all GBDT models are built with CatBoost; ensembles have 10 models of 1000 trees; hyperparameters were tuned by grid search over learning rate {0.001, 0.01, 0.1} and depth {3, 4, 5, 6}, with subsample fixed to 0.5 for SGB and 1 for SGLB; UCI regression uses standard splits, classification a 65/15/20 split.",
          "Appendix A.2",
          "For all approaches, we use grid search to tune learning-rate in {0.001, 0.01, 0.1}, tree depth in {3, 4, 5, 6}."),
         ("Conflict of interest: the methods were implemented within the open-source CatBoost library, which is the library used for all GBDT models in the experiments (and the paper cites Prokhorenkova et al., 2018 for CatBoost).",
          "Introduction",
          "Our methods have been implemented within the open-source CatBoost library."),
     ],
     "notes": "Affiliations: Yandex, HSE University, Moscow Institute of Physics and Technology (Yandex is the developer of CatBoost). Venue from the PDF header ('Published as a conference paper at ICLR 2021'). Disclosure: Prokhorenkova is an author of the cited CatBoost paper (Prokhorenkova et al., 2018), and Ustimenko & Prokhorenkova are the authors of SGLB, the method evaluated here. Appendix A.1 compares the authors' implementation with NGBoost and Deep Ensembles (Table 2); Appendix C evaluates random-forest ensembles. Results tables not recorded."},

    {"id": "arxiv-1911.01914",
     "title": "A Comparative Analysis of XGBoost",
     "authors": ["Candice Bentéjac", "Anna Csörgő", "Gonzalo Martínez-Muñoz"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1911.01914"},
     "tasks": ["tabular-classification"],
     "fam": ["gradient-boosted-trees", "random-forests"], "par": ["supervised"],
     "proposes": ["A comparison of XGBoost, scikit-learn gradient boosting and random forest with default and grid-search-tuned hyperparameters on 28 UCI classification datasets, and a proposed default parametrization and reduced tuning grid for XGBoost"],
     "claims": [
         ("Setup: 28 UCI classification datasets; scikit-learn random forest and gradient boosting and the XGBoost package, each evaluated with package defaults and with grid-search tuning; accuracy estimated by stratified 10-fold cross-validation, with tuning by a nested stratified 10-fold cross-validation inside each training set.",
          "Experimental results",
          "The comparison was carried out using stratiﬁed 10-fold cross-validation."),
         ("Fixed choices: all ensembles had 200 trees (the authors argue ensemble size need not be tuned), and XGBoost's own missing-value handling was not used; missing values were mean-imputed for a fairer comparison with scikit-learn trees.",
          "Experimental results",
          "All ensembles were composed of 200 decision trees."),
         ("Tuning budgets differ between methods: the grids had 3840, 256 and 1920 configurations for XGBoost, random forest and gradient boosting, so the tuning time is not directly comparable between classifiers.",
          "Experimental results",
          "Since the size of the grid is diﬀerent for diﬀerent classiﬁers (i.e. 3840, 256 and 1920 for XGB, RF and GB respectively), the time dedicated to ﬁnding the best parameters is not directly comparable between classiﬁers."),
         ("Default vs tuned: default random forest performs closest to its tuned counterpart, while default XGBoost and gradient boosting generally perform worse than tuned versions, though not always.",
          "Experimental results",
          "Default random forest is the method that performs more evenly with respect to its tuned counterpart."),
         ("On some datasets default XGBoost beat tuned XGBoost; the authors attribute this to noisy data plus good defaults, noting that parameter estimation, even within training cross-validation, may overfit the training set especially on noisy datasets.",
          "Experimental results",
          "The parameter esti- mation process, even though it is performed within train cross-validation, may overﬁt the training set specially in noisy datasets."),
         ("No statistically significant differences in average rank among the six tested configurations (Nemenyi test).",
          "Experimental results",
          "From Figure 1, it can be observed that there are not any statistically sig- niﬁcant diﬀerences among the average ranks of the six tested methods."),
         ("Conclusion on tuning: a meticulous parameter search is necessary for accurate gradient-boosting-based models, but not for random forest, whose performance was slightly better on average with default (Breiman's) values.",
          "Conclusion",
          "In consequence, we conclude that a meticulous parameter search is necessary to create accurate models based on gradient boosting."),
         ("Which XGBoost hyperparameters matter: tuning the randomization parameters (subsampling rate, features per split) seems unnecessary provided reasonable values are used; including the gamma complexity term may give a small, not statistically significant edge.",
          "Analysis of XGBoost parametrization",
          "A conclusion that may be clearer is that it seems unnecessary to tune the number of random features and the subsampling rate provided that those techniques are applied with reasonable values (in our case subsampling to 0.75 and feature sampling to sqrt)."),
     ],
     "notes": "Affiliations: University of Bordeaux, Pázmány Péter Catholic University, Universidad Autónoma de Madrid. No venue is stated in the PDF (arXiv v1). LightGBM and CatBoost are not evaluated (no mention found in the text; searched for 'LightGBM' and 'CatBoost'); 'gradient boosting' here is scikit-learn's implementation. The proposed XGBoost defaults were selected using the same 28 datasets on which they are then evaluated. Results tables (Tables 3, 4, 11, 12) not recorded."},

    {"id": "arxiv-1802.09596",
     "title": "Tunability: Importance of Hyperparameters of Machine Learning Algorithms",
     "authors": ["Philipp Probst", "Bernd Bischl", "Anne-Laure Boulesteix"],
     "year": 2018, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1802.09596", "code": "https://github.com/PhilippPro/tunability"},
     "tasks": ["tabular-classification"],
     "fam": ["gradient-boosted-trees", "random-forests", "decision-trees", "linear-models", "kernel-methods"],
     "par": ["supervised"],
     "proposes": ["Definitions of data-based optimal defaults, the tunability of an algorithm and of individual hyperparameters (risk of the default minus risk of the best configuration), joint gains of hyperparameter pairs, and tuning ranges from quantiles of per-dataset optima, estimated with surrogate models"],
     "claims": [
         ("Definition: the tunability of an algorithm on a dataset is the difference between the risk of a reference default configuration (package defaults or the data-based optimal defaults) and the risk of the best configuration on that dataset; per-hyperparameter tunability tunes only that hyperparameter with the others at defaults.",
          "Measuring overall tunability of a ML algorithm",
          "A general measure of the tunability of an algorithm per dataset can then be computed based on the diﬀerence between the risk of an overall reference conﬁguration (e.g., either the software defaults or deﬁnition (3)) and the risk of the best possible conﬁguration on that dataset:"),
         ("Data: the 38 binary classification tasks without missing values from the OpenML100 suite; algorithms: glmnet, rpart, kknn, svm, ranger (random forest) and xgboost.",
          "Datasets from the OpenML platform",
          "For our study we only use the 38 binary classiﬁcation tasks that do not contain any missing values."),
         ("Protocol: configurations are sampled uniformly at random within the ranges of Table 1 by an OpenML bot and evaluated by 10-fold cross-validation; a random-forest surrogate per dataset is fitted to the results, and defaults and per-dataset optima are found by random search on the surrogates.",
          "Random Bot sampling strategy for meta data",
          "In an embarrassingly parallel manner it chooses in each iteration a random dataset, a random classiﬁcation al- gorithm, samples a random conﬁguration and evaluates it via cross-validation."),
         ("Overfitting caveat: the new defaults are chosen with the same datasets used to measure performance, so the authors also evaluate them by a 10-fold cross-validation across datasets.",
          "Optimizing surrogates to obtain optimal defaults",
          "Of course one has to be careful with overﬁtting here, as our new defaults are chosen with the help of the same datasets that are used to determine the performance."),
         ("Algorithm-level result (AUC): glmnet and svm are much more tunable than the others, while ranger (random forest) is the least tunable; some datasets are outliers where tuning has a much larger impact.",
          "Optimal defaults and tunability",
          "Clearly, some algorithms such as glmnet and svm are much more tunable than the others, while ranger is the algorithm with the smallest tunability, which is in line with common knowledge in the web community."),
         ("Hyperparameter-level result (AUC, w.r.t. optimal defaults): for xgboost, eta and booster (tree vs linear model) are quite tunable; for ranger, mtry is the most tunable; for rpart, minbucket and minsplit seem the most important.",
          "Tunability of speciﬁc hyperparameters",
          "For xgboost there are two parameters that are quite tunable: eta and the booster."),
         ("For random forest, the best mtry values on quite a few datasets seem much higher than the package default; all optimal defaults fall inside the proposed tuning space while some package defaults do not.",
          "Hyperparameter space for tuning",
          "Note that for quite a few data sets much higher values than the package defaults seem advantageous."),
         ("Stated limitations: only binary classification; uniform random sampling may not scale to very high-dimensional spaces; defaults are static and cannot depend on dataset characteristics; initial ranges must still be set.",
          "Conclusion and Discussion",
          "Our study has some limitations that could be addressed in the future: a) We only con- sidered binary classiﬁcation, where we tried to include a wider variety of datasets from diﬀerent domains."),
     ],
     "notes": "Author order follows the arXiv record; the PDF title block lists 'Philipp Probst, Anne-Laure Boulesteix and Bernd Bischl'. No venue is stated in the PDF (arXiv v3, dated October 23, 2018); arXiv comment is '22 pages, 10 tables, 8 figures'. The benchmark data come from the authors' own OpenML random bot (Kühn, Probst, Thomas, Bischl 2018), and experiments use mlr, whose authors include Bischl. Mainly AUC results are discussed; accuracy and Brier score are in the appendix. Results tables (Tables 2-5) not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
