import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_unc_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1506.02142",
     "title": "Dropout as a Bayesian Approximation: Representing Model Uncertainty in Deep Learning",
     "authors": ["Yarin Gal", "Zoubin Ghahramani"],
     "year": 2015, "venue": "ICML 2016", "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/1506.02142"},
     "tasks": ["uncertainty-estimation", "tabular-regression", "image-classification"],
     "fam": ["bayesian-deep-learning", "deep-learning"], "par": ["supervised"],
     "proposes": ["A theoretical framework casting dropout training (dropout before every weight layer) as approximate variational inference in a deep Gaussian process",
                  "MC dropout: keeping dropout on at test time and averaging T stochastic forward passes to estimate the predictive mean, with the predictive variance given by the sample variance of the passes plus the inverse model precision"],
     "claims": [
         ("Motivation: predictive probabilities from the softmax are often erroneously interpreted as model confidence; a model can be uncertain in its predictions even with a high softmax output, and passing a point estimate through a softmax gives unjustifiably high confidence far from the training data.",
          "Section 1",
          "A model can be uncertain in its predictions even with a high softmax output (ﬁg. 1)."),
         ("Core result: a NN of arbitrary depth and non-linearities with dropout applied before every weight layer is mathematically equivalent to an approximation to the deep Gaussian process (marginalised over its covariance function parameters); the dropout objective in effect minimises the KL divergence between an approximate distribution (weight matrices with randomly zeroed columns) and the deep GP posterior. The derivation is deferred to a separate appendix document.",
          "Section 3",
          "We show that a neural network with arbitrary depth and non-linearities, with dropout applied before every weight layer, is mathematically equivalent to an approximation to the probabilistic deep Gaussian process"),
         ("MC dropout estimates the first two moments of the approximate predictive distribution by moment matching: the predictive mean is the average of T stochastic forward passes, and the predictive variance is the sample variance of the passes plus the inverse model precision tau^-1, where tau is obtained from the weight decay, dropout probability and an assumed prior length-scale.",
          "Section 4",
          "In practice this is equivalent to performing T stochastic forward passes through the network and averaging the results."),
         ("Hedge: the approximate predictive distribution is expected to be highly multi-modal (the variational distribution over each weight-matrix column is bi-modal), so the mean/variance approximations only give a glimpse into its properties.",
          "Section 4",
          "and the above approximations only give a glimpse into its properties"),
         ("Cost as stated by the authors: the dropout model itself is not changed, so the method can be used with existing networks trained with dropout; the forward passes can be done concurrently, giving constant running time identical to standard dropout. T = 1000 passes were used in the regression figures for drawing purposes, and the authors state much smaller numbers (e.g. T = 10) give a reasonable estimate.",
          "Section 4",
          "Furthermore, the forward passes can be done concurrently, resulting in constant running time identical to that of standard dropout."),
         ("The uncertainty depends on modelling choices: on the CO2 extrapolation task, the uncertainty grows far from the data for the ReLU model but stays bounded for the TanH model, which the authors attribute to ReLU and TanH approximating different GP covariance functions; none of the models capture the periodicity.",
          "Section 5.1",
          "Note that the uncertainty is increasing far from the data for the ReLU model, whereas for the TanH model it stays bounded."),
         ("UCI regression protocol (replicating the PBP setup): 1-hidden-layer networks of 50 units, dropout probabilities 0.05 and 0.005, prior length-scale set to 10^-2 for most datasets based on the range of the data, and the model precision tau chosen by Bayesian optimisation over validation log-likelihood; 20 random splits (5 for Protein, 1 for Year). After BO, 10x more iterations were used because dropout takes longer to converge.",
          "Section 5.3",
          "over validation log-likelihood to ﬁnd optimal τ"),
         ("Result as stated in the text: dropout significantly outperforms VI and PBP in RMSE and test log-likelihood on all datasets apart from Yacht, where PBP obtains better RMSE. MC dropout averaging also improved over standard dropout weight averaging and over near-zero dropout probabilities.",
          "Section 5.3",
          "Dropout signiﬁcantly outperforms all other models both in terms of RMSE as well as test log-likelihood on all datasets apart from Yacht, for which PBP obtains better RMSE."),
         ("Correction (October 2016 update): in an earlier version the reported dropout standard errors were erroneously scaled up by a factor of 4.5 (e.g. Boston RMSE standard error 0.85 instead of 0.19).",
          "Section 5.3 (footnote 3)",
          "Note that in an earlier version of this paper our reported dropout standard error was erroneously scaled-up by a factor of 4.5"),
     ],
     "notes": "Affiliation: University of Cambridge. Venue from the PDF first page ('Proceedings of the 33rd International Conference on Machine Learning, New York, NY, USA, 2016'). The arXiv comment of v6 notes a fixed mistake with the standard error, recorded as a claim (footnote 3). Footnote 4 (October 2016 update) says the Table 1 epochs were chosen to match PBP's run time, and that 10x more epochs or a second hidden layer gives a considerable improvement (Table 2). The main derivation lives in a separate appendix (arXiv:1506.02157), not in this PDF. MNIST: LeNet with dropout 0.5 before the last fully connected layer, evaluated on a rotated digit; uncertainty quantified by entropy or variation ratios (qualitative only). RL experiment (Thompson sampling with a dropout Q-network) shown as figures only. No calibration metric such as ECE is used; uncertainty quality is assessed through predictive log-likelihood. Calibration/coverage guarantees: none claimed."},

    {"id": "arxiv-1612.01474",
     "title": "Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles",
     "authors": ["Balaji Lakshminarayanan", "Alexander Pritzel", "Charles Blundell"],
     "year": 2016, "venue": "NeurIPS 2017", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1612.01474"},
     "tasks": ["uncertainty-estimation", "tabular-regression", "image-classification", "selective-prediction"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["Deep ensembles: train M networks independently (random initialization and data shuffling, full training set) with a proper scoring rule as the loss, optionally with adversarial training, and combine them as a uniformly weighted mixture; for regression each network outputs a mean and a variance trained with the Gaussian negative log-likelihood"],
     "claims": [
         ("Motivation, a hedged argument: dropout can also be interpreted as an ensemble with parameter sharing, and this interpretation seems more plausible when dropout rates are not tuned on the training data, since any sensible approximation to the true Bayesian posterior has to depend on the training data.",
          "Introduction",
          "The ensemble interpretation seems more plausible particularly in the scenario where the dropout rates are not tuned based on the training data"),
         ("Ensembles vs Bayesian model averaging: BMA assumes the true model lies in the prior's hypothesis class and performs soft model selection, whereas ensembles perform model combination and can be expected to be better when the true model is not in the class; the authors note that even exact BMA is not guaranteed to be robust to misspecification with respect to domain shift.",
          "Introduction",
          "It is important to note that even exact BMA is not guaranteed be robust to mis-speciﬁcation with respect to domain shift."),
         ("Calibration is used in the frequentist sense (discrepancy between forecasts and long-run frequencies) and is measured with proper scoring rules, namely log predictive probability (NLL) and the Brier score; the authors note calibration is orthogonal to accuracy.",
          "Introduction",
          "The quality of calibration can be measured by proper scoring rules [17] such as log predictive probabilities and the Brier score [9]."),
         ("Recipe: (1) a proper scoring rule as the training criterion (softmax cross-entropy or Brier for classification; Gaussian NLL with a predicted mean and variance for regression), (2) adversarial training (fast gradient sign, epsilon = 1% of each input dimension's range) to smooth predictive distributions, (3) an ensemble; recommended default M = 5.",
          "Deep Ensembles: A Simple Recipe For Predictive Uncertainty Estimation",
          "We suggest a simple recipe: (1) use a proper scoring rule as the training criterion, (2) use adversarial training [18] to smooth the predictive distributions, and (3) train an ensemble."),
         ("Cost: the ensemble has M times more parameters than a single network (training is independent and parallelizable); for memory-constrained applications the authors suggest distilling the ensemble into a simpler model. Bagging deteriorated performance in their experiments, so each member is trained on the entire dataset.",
          "Discussion",
          "The ensemble has M times more parameters than a single network; for memory-constrained applications, the ensemble can be distilled into a simpler model [10, 26]."),
         ("UCI regression protocol: the PBP setup (20 train-test folds, 5 for Protein, 1 for Year; 1 hidden layer of 50 or 100 ReLU units; 40 epochs; 5 networks). PBP and MC-dropout numbers are taken from their respective papers, not rerun. The authors report better or competitive NLL but slightly worse RMSE on some datasets, which they attribute to optimizing NLL instead of MSE.",
          "Regression on real world datasets",
          "Our results are shown in Table 1, along with the PBP and MC-dropout results reported in their respective papers."),
         ("Out-of-distribution (unseen classes: MNIST to NotMNIST, SVHN to CIFAR-10, ImageNet dogs vs non-dogs): the entropy of deep ensembles on unseen classes rises faster with M than that of MC-dropout, and MC-dropout seems to give high-confidence predictions for some unseen-class examples. In these comparisons M is the number of networks for ensembles and the number of MC samples for MC-dropout (dropout rate 0.1 on MNIST; 0.5 was tried and performed worse).",
          "Uncertainty evaluation: test examples from known vs unknown classes",
          "In particular, MC-dropout seems to give high conﬁdence predictions for some of the test examples, as evidenced by the mode around 0 even for unseen classes."),
         ("Hedge on the components: ensembles even with M = 5 significantly improve uncertainty quality in all cases studied, while adversarial training helps on some datasets for some metrics and is not strictly necessary (on SVHN its effect drops as M increases).",
          "Discussion",
          "Adversarial training helps on some datasets for some metrics and is not strictly necessary in all cases."),
         ("Regression calibration check (Year Prediction MSD, Gaussian prediction intervals at 10%-90%): an ensemble of five networks trained with MSE, using the empirical variance of their predictions, consistently underestimates uncertainty, whereas learning the variance with NLL gives a well-calibrated regressor.",
          "Appendix A.2",
          "For instance, the 80% prediction interval contains only 20% of the test observations, which means the empirical variance signiﬁcantly underestimates the true predictive uncertainty."),
     ],
     "notes": "Affiliation: DeepMind. Venue from the PDF first page ('31st Conference on Neural Information Processing Systems (NIPS 2017)') and the arXiv comment. Classification results (MNIST, SVHN, ImageNet) and the accuracy-vs-confidence (selective prediction on MNIST+NotMNIST) results are shown as figures only and are not recorded. ImageNet: only the effect of ensembles was evaluated, due to computational constraints. Training details stated in the text: batch size 100, Adam with a fixed learning rate of 0.1 unless otherwise specified, default Torch initialization. No expected calibration error (ECE) or binning-based metric is used (searched for ECE, expected calibration, bins). The abstract says the method 'requires very little hyperparameter tuning'; no statement of how hyperparameters were selected on validation data was found (searched for tun, validation, held). Ensemble disagreement is defined as the sum of KL divergences of members to the ensemble mean (footnote 9). Co-author Charles Blundell is an author of the Bayes-by-backprop variational method cited as [6]; VI is not compared directly (footnote 6: PBP and MC-dropout outperform VI on these benchmarks)."},

    {"id": "arxiv-1703.04977",
     "title": "What Uncertainties Do We Need in Bayesian Deep Learning for Computer Vision?",
     "authors": ["Alex Kendall", "Yarin Gal"],
     "year": 2017, "venue": "NeurIPS 2017", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1703.04977"},
     "tasks": ["uncertainty-estimation"],
     "fam": ["bayesian-deep-learning", "deep-learning"], "par": ["supervised"],
     "proposes": ["A framework combining input-dependent (heteroscedastic) aleatoric uncertainty, learned as a predicted variance from the task loss, with epistemic uncertainty from MC dropout, for regression and classification",
                  "A heteroscedastic classification loss: Gaussian noise placed on the logits and integrated by Monte Carlo sampling, interpreted as learned loss attenuation"],
     "claims": [
         ("Definitions: aleatoric uncertainty captures noise inherent in the observations (e.g. sensor or motion noise) and cannot be reduced by collecting more data; epistemic uncertainty is uncertainty in the model parameters, which can be explained away given enough data. Aleatoric uncertainty is further split into homoscedastic (constant) and heteroscedastic (input-dependent).",
          "Introduction",
          "This could be for example sensor noise or motion noise, resulting in uncertainty which cannot be reduced even if more data were to be collected."),
         ("How each is modelled: epistemic uncertainty by a prior over weights with dropout variational inference (MC dropout); aleatoric uncertainty by placing a distribution over the model output and learning its variance as a function of the input with MAP inference, which on its own does not capture epistemic uncertainty.",
          "Section 2.2",
          "This approach does not capture epistemic model uncertainty, as epistemic uncertainty is a property of the model and not of the data."),
         ("Learned loss attenuation: predicting the (log) variance tempers the residual loss per input, so inputs with high predicted uncertainty have less effect on the loss, while the log-variance term penalizes predicting high uncertainty everywhere; no uncertainty labels are needed. The classification analogue places Gaussian noise on the logits and samples only the logits, which the authors say does not significantly increase test time.",
          "Section 3",
          "This makes the model more robust to noisy data: inputs for which the model learned to predict high uncertainty will have a smaller effect on the loss."),
         ("Protocol: DenseNet adapted for dense prediction (own implementation), MC dropout with p = 0.2 after each convolutional layer and 50 samples; aleatoric losses are derived with a Laplacian rather than Gaussian likelihood (L1 on residuals), which deviates from the Gaussian derivation. Datasets: CamVid and NYUv2 (segmentation), Make3D and NYUv2 Depth (depth regression).",
          "Section 4",
          "However, we derive the loss function using a Laplacian prior, as opposed to the Gaussian prior used for the derivations in §3."),
         ("On CamVid, modelling aleatoric uncertainty improves more than modelling epistemic uncertainty and combining both improves further; the authors take this to suggest epistemic uncertainty can be mostly explained away in this large-data setting (per-pixel prediction).",
          "Semantic Segmentation",
          "This shows that for this application it is more important to model aleatoric uncertainty, suggesting that epistemic uncertainty can be mostly explained away in this large data setting."),
         ("Precision-recall curves for aleatoric-only and epistemic-only models are very similar, which the authors say suggests that when only one uncertainty is modelled it attempts to compensate for the missing one when possible.",
          "Quality of Uncertainty Metric",
          "This suggests that when only one uncertainty is explicitly modeled, it attempts to compensate for the lack of the alternative uncertainty when possible."),
         ("Calibration evaluation: classification calibration plots are formed by binning predicted probabilities over all classes and all pixels of the test set and plotting the frequency of correct labels per bin (the number of bins is not stated in the text); regression calibration compares the frequency of residuals within thresholds of the predicted distribution.",
          "Quality of Uncertainty Metric",
          "To form calibration plots for classiﬁcation models, we discretize our model’s predicted probabilities into a number of bins, for all classes and all pixels in the test set."),
         ("Distance from training data (Table 3, reduced training sets and unrelated test datasets): aleatoric uncertainty stays roughly constant with more data, epistemic uncertainty decreases with more data and increases considerably on test points far from the training set, so aleatoric uncertainty alone cannot identify out-of-data examples.",
          "Uncertainty with Distance from Training Data",
          "Testing the models with a different test set (bottom two lines) shows that epistemic uncertainty increases considerably on those test points which lie far from the training sets."),
         ("Cost: aleatoric models add negligible compute, but epistemic models require MC dropout sampling; for DenseNet, where the entire architecture must be sampled, this is hard to parallelize due to GPU memory and often gives a 50x slow-down for 50 samples (cheaper for models with dropout only in the last layers). The authors leave real-time epistemic uncertainty as future work.",
          "Real-Time Application",
          "This is difﬁcult to parallelize due to GPU memory constraints, and often results in a 50× slow-down for 50 Monte Carlo samples."),
     ],
     "notes": "Affiliation: University of Cambridge. Venue from the PDF first page ('31st Conference on Neural Information Processing Systems (NIPS 2017)') and the arXiv comment. Section numbers 2.1, 2.2, 3 and 4 are confirmed by in-text cross-references (§2.1, §2.2, §3, §4); other locations use section names. Overlapping authorship: Yarin Gal is an author of the MC dropout method used here for epistemic uncertainty, and Alex Kendall is an author of Bayesian SegNet [22] and SegNet [28], which appear as baselines in Table 1. The equation for the classification aleatoric loss is referenced as being 'in the appendix' (eq. 12), which is not in this arXiv PDF. Calibration MSE values appear only in a figure legend and are not recorded. Tasks are semantic segmentation and monocular depth regression; no registered task tag fits these (reported for possible new tags), so only uncertainty-estimation is used."},

    {"id": "arxiv-2002.02405",
     "title": "How Good is the Bayes Posterior in Deep Neural Networks Really?",
     "authors": ["Florian Wenzel", "Kevin Roth", "Bastiaan S. Veeling", "Jakub Świątkowski", "Linh Tran",
                 "Stephan Mandt", "Jasper Snoek", "Tim Salimans", "Rodolphe Jenatton", "Sebastian Nowozin"],
     "year": 2020, "venue": "ICML 2020", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2002.02405", "code": "https://github.com/google-research/google-research/tree/master/cold_posterior_bnn"},
     "tasks": ["uncertainty-estimation", "image-classification"],
     "fam": ["bayesian-deep-learning", "deep-learning"], "par": ["supervised"],
     "proposes": ["An empirical study of the 'cold posterior' effect: posterior predictive performance of SG-MCMC ensembles as a function of the posterior temperature T, with systematic tests of hypotheses for why T = 1 performs poorly",
                  "Kinetic and configurational temperature diagnostics for the simulation accuracy of SG-MCMC, and a layerwise preconditioner that is re-estimated only periodically"],
     "claims": [
         ("Cold posterior effect: for a ResNet-20 on CIFAR-10 and a CNN-LSTM on IMDB, the Bayes posterior predictive at T = 1 (approximated by SG-MCMC) performs worse than SGD-trained point estimates, and the best predictive performance on holdout data among tempered posteriors is achieved at T < 1. Appendix G reports that Brier score and ECE also improve with cold posteriors (ECE binning not stated).",
          "Section 1.1",
          "Cold Posteriors: among all temperized posteriors the best posterior predictive performance on holdout data is achieved at temperature T < 1."),
         ("Why T < 1 is a problem: it artificially sharpens the posterior, which is equivalent to a Bayes posterior on 1/T replications of the data (with a rescaled prior), giving too strong evidence to individual models; and gains for T < 1 point to a problem with the prior, likelihood or inference.",
          "Section 2.2",
          "This is equivalent to a Bayes posterior obtained from a dataset consisting of 1/T replications of the original data, giving too strong evidence to individual models."),
         ("Literature: SG-MCMC papers on deep networks temper the posterior (in some cases inadvertently), and variational BNN papers down-weight the KL term (lambda < 1), which Appendix E shows corresponds to a partially tempered posterior; the authors are not aware of any published work showing well-performing Bayesian deep learning at T = 1.",
          "Section 2.3",
          "in fact we are not aware of any published work demonstrating well-performing Bayesian deep learning at temperature T = 1"),
         ("Inference accuracy: new kinetic/configurational temperature diagnostics indicate accurate simulation, and on small MLPs with synthetic data generated from the prior (where T = 1 is optimal by construction, full-batch) SG-MCMC agrees closely with HMC; the authors conclude, for the cases tested, that missing accept-reject corrections cannot explain cold posteriors. Minibatch noise (batch sizes 32-256) and ensemble variance (an asymptotic extrapolation in Appendix F) were also judged unable to explain it.",
          "Section 4.2",
          "For the cases tested we conclude that SG-MCMC is almost as accurate as HMC and the lack of accept-reject correction cannot explain cold posteriors."),
         ("Dirty likelihood hypothesis: batch normalization, dropout and data augmentation are not formal likelihoods (the CIFAR-10 experiments use flip and pad-crop augmentation); an experiment with a clean likelihood in a modified ResNet, described as slightly inconclusive, still showed cold posteriors.",
          "Section 5.1",
          "demonstrates that cold posteriors remain when a clean likelihood is used in a suitably modiﬁed ResNet model"),
         ("Prior: typical draws from the N(0, I) prior for ResNet-20 give concentrated class distributions, which the authors call a poor prior from a subjective Bayesian view; varying the prior variance did not remove the effect. The training-set-size experiment is called inconclusive but somewhat implicating the prior, and the conclusion states the prior may not be the only cause.",
          "Section 5.2",
          "The cold posterior effect cannot be resolved by using the right scaling of the Normal prior."),
         ("Capacity: for MLPs on CIFAR-10, the cold posterior effect becomes more prominent with increasing depth and width.",
          "Section 5.2",
          "This indicates a connection between model capacity and strength of the cold posterior effect."),
         ("Practical conclusion: tempered SG-MCMC ensembles improve predictions over individual models, but given the added computation of evaluating ensembles there may be more practical methods (citing deep ensembles and other ensemble methods). The ensembles here have 27 (ResNet-20, 1500 epochs) and 7 (CNN-LSTM, 500 epochs) members.",
          "Section 8",
          "However, taking into account the added computation from evaluating ensembles, there may be more practical methods, (Lakshminarayanan et al., 2017; Wen et al., 2019; Ashukha et al., 2020)."),
         ("Protocol caveat: the CNN-LSTM/IMDB SGD baseline overfits, so its reported performance is the best end-of-epoch evaluation on the test set (test-set selection); the ResNet-20 SGD baseline uses the Keras example settings tuned for generalization, with no overfitting observed over 200 epochs.",
          "Appendix A.4",
          "We report the optimal test set performance from all end-of-epoch test evaluations."),
     ],
     "notes": "Affiliations: Google Research, ETH Zurich, University of Amsterdam, University of Warsaw, Imperial College London, UC Irvine, Microsoft Research (several authors marked 'work done while at Google'); Wenzel, Roth and Veeling contributed equally. Venue: ICML 2020 is based on the arXiv comment (full version of the ICML paper) as given in the task; the PDF itself only says 'Copyright 2020 by the author(s)' and thanks 'the four anonymous ICML 2020 reviewers', so the PDF text alone does not confirm acceptance. The paper argues that the claim in Wilson & Izmailov (2020, Section 8.3) that cold posteriors equal untempered posteriors of a modified likelihood is wrong (Section 6, Appendix M); it also points to 'Masegosa posteriors' as a possibly better target. SG-MCMC uses a fully tempered energy (likelihood and prior), cyclical cosine step size and layerwise preconditioning; HMC comparison only on small MLPs with synthetic data. All results are figures; none recorded. IMDB is sentiment text classification, for which no registered task tag exists."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
