import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_diff_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1706.08500",
     "title": "GANs Trained by a Two Time-Scale Update Rule Converge to a Local Nash Equilibrium",
     "authors": ["Martin Heusel", "Hubert Ramsauer", "Thomas Unterthiner", "Bernhard Nessler", "Sepp Hochreiter"],
     "year": 2017, "venue": "NeurIPS 2017", "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/1706.08500"},
     "tasks": ["generative-modeling"],
     "fam": ["deep-learning"], "par": ["unsupervised"],
     "proposes": ["TTUR: training GANs with separate learning rates for the discriminator and the generator, with a convergence proof to a stationary local Nash equilibrium via two time-scale stochastic approximation",
                  "FID (Fréchet Inception Distance): the Fréchet (Wasserstein-2) distance between Gaussians fitted to the mean and covariance of Inception-v3 coding-layer features of real and generated images"],
     "claims": [
         ("TTUR (briefly): with separate learning rates for discriminator and generator, the authors prove via stochastic approximation theory that GAN training converges under mild assumptions to a stationary local Nash equilibrium; the convergence carries over to Adam.",
          "Abstract",
          "Using the theory of stochastic approximation, we prove that the TTUR converges under mild assumptions to a stationary local Nash equilibrium."),
         ("Motivation for FID: the drawback of the Inception Score is that it does not use the statistics of real-world samples and compare them with those of synthetic samples.",
          "Experiments (Performance Measure)",
          "Drawback of the Inception Score is that the statistics of real world samples are not used and compared to the statistics of synthetic samples."),
         ("FID definition and its assumption: only the first two moments (mean and covariance) of the Inception coding layer are used, the coding units are assumed to follow a multidimensional Gaussian (justified as the maximum-entropy distribution for given mean and covariance), and the two Gaussians are compared with the Fréchet (Wasserstein-2) distance.",
          "Experiments (Performance Measure)",
          "The Gaussian is the maximum entropy distribution for given mean and covariance, therefore we assume the coding units to follow a multidimensional Gaussian.", 6),
         ("Evidence offered for FID: on CelebA, six disturbances (Gaussian noise, Gaussian blur, implanted black rectangles, swirl, salt-and-pepper noise, contamination with ImageNet images) are applied at increasing levels, and the authors state that FID captures the disturbance level very well (shown as a figure). The text claims FID is consistent with 'disturbances and human judgment', but no human study was found in the text (searched for human, judg).",
          "Experiments (Performance Measure)",
          "The FID captures the disturbance level very well.", 6),
         ("Comparison with the Inception Score (Appendix A1, figure caption): across the disturbances, FID increases monotonically with the disturbance level, whereas the Inception Score (converted to a distance) fluctuates, stays flat or decreases; the comparison is shown only as a figure.",
          "Appendix A1 (Figure A8)",
          "The FID captures the disturbance level very well by monotonically increasing whereas the Inception Score ﬂuctuates, stays ﬂat or even, in the worst case, decreases."),
         ("FID computation protocol: reference statistics are computed from all training images passed through the pretrained Inception-v3 (last pooling layer as coding layer), and model statistics from 50,000 generated images.",
          "Experiments (Model Selection and Evaluation)",
          "To approximate these moments for the model distribution, we generate 50,000 images, propagate them through the Inception-v3 model, and then compute the mean m and the covariance matrix C."),
         ("Model selection used the evaluation metric: learning rates were optimized to be large while keeping training stable as indicated by a decreasing FID (or JSD), and the stopping time was fixed to the update step when the FID or JSD of the best models stopped decreasing; Table 1 reports the best FID for optimized number of updates and learning rates.",
          "Experiments (Model Selection and Evaluation)",
          "We further ﬁxed the time point for stopping training to the update step when the FID or Jensen-Shannon-divergence of the best models was no longer decreasing."),
         ("Scope limitation: FID only works for images, so the character-level language experiments (One Billion Word) are evaluated with the Jensen-Shannon divergence instead, as done previously [23].",
          "Experiments (WGAN-GP on Language Data)",
          "Since the FID criterium only works for images, we measured the performance by the Jensen-Shannon-divergence (JSD) between the model and the real world distribution as has been done previously [23]."),
     ],
     "notes": "Affiliation: LIT AI Lab & Institute of Bioinformatics, Johannes Kepler University Linz. Venue from the PDF footer ('31st Conference on Neural Information Processing Systems (NIPS 2017)'). FID is introduced here and is also used by the same paper to select learning rates and stopping points for its own TTUR comparison. No dependence of FID on the number of samples is discussed in the text (searched for 'sample'/'number of samples'). Results tables (Table 1, Table A2) not recorded."},

    {"id": "arxiv-2203.06026",
     "title": "The Role of ImageNet Classes in Fréchet Inception Distance",
     "authors": ["Tuomas Kynkäänniemi", "Tero Karras", "Miika Aittala", "Timo Aila", "Jaakko Lehtinen"],
     "year": 2022, "venue": "ICLR 2023", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2203.06026"},
     "tasks": ["generative-modeling"],
     "fam": ["deep-learning"], "par": ["unsupervised"],
     "proposes": ["A Grad-CAM-based visualization of which image regions FID is most sensitive to",
                  "Resampling generated sets (Top-1 histogram matching, FID-optimized sampling weights, Top-N histogram matching) to probe the 'perceptual null space' of FID"],
     "claims": [
         ("Main finding: the feature space in which FID is typically computed is so close to the ImageNet classifications that aligning Top-N class histograms between generated and real images can reduce FID substantially without improving result quality; the authors conclude FID is prone to intentional or accidental distortions.",
          "Abstract",
          "We show that the feature space that FID is (typically) computed in is so close to the ImageNet classiﬁcations that aligning the histograms of Top-N classiﬁcations between sets of generated and real images can reduce FID substantially — without actually improving the quality of results."),
         ("Evaluation protocol: StyleGAN2 models (256x256, AFHQ-V2 DOG at 512x512 with ADA) on FFHQ, LSUN CAT/CAR/PLACES and AFHQ-V2 DOG; FID computed against the training set with 50k random real and generated images and the official TensorFlow Inception-V3.",
          "Probing the perceptual null space in FID",
          "Following standard practice, we compute FID against the training set, using 50k randomly chosen real and generated images and the ofﬁcial TensorFlow version of Inception-V3."),
         ("Grad-CAM heatmaps of FID sensitivity seem to correspond to the region of the image's ImageNet Top-1 class prediction; on FFHQ (ImageNet has no 'person' or 'face' class) the most important regions are typically outside the face.",
          "What does FID look at in an image?",
          "Interestingly, we observe that the heatmaps seem to correspond very well with the areas that the image’s ImageNet Top-1 class prediction would occupy."),
         ("Simply resampling generated images to match the Top-1 class histogram of 50k real images consistently improved FID by about 10% over several datasets; FID in a ResNet-50 ImageNet feature space dropped almost as much, while SwAV and CLIP feature-space FIDs dropped less, which the authors read as no clear quality increase.",
          "Probing the perceptual null space in FID (Top-1 histogram matching)",
          "Over multiple datasets, this simple Top-1 histogram matching consistently improves FID, by ∼10% (Table 1)."),
         ("Optimizing per-image sampling weights over 250k candidates (generator unchanged) to minimize FID reduced FID drastically, with substantially smaller improvement in non-ImageNet feature spaces; the authors allow that results may have improved in some minor way but conclude most of the improvement lies in FID's perceptual null space. They state they do not advocate this resampling to improve models.",
          "Probing the perceptual null space in FID (Matching all fringe features)",
          "In other words, FID can be manipulated to a great extent through the ImageNet classiﬁcation probabilities, without meaningfully improving the generated results."),
         ("Practical case: a Projected FastGAN (ImageNet pre-trained EfficientNet in the discriminator) and StyleGAN2 on FFHQ at roughly equal FID and Recall; citing the human preference study of Sauer et al. (2021) and the authors' visual inspection, Projected FastGAN is worse, and FID computed with CLIP features agrees; the authors believe information leaks from the pre-trained network.",
          "Practical example: ImageNet pre-trained GANs",
          "This observation does not mean that ImageNet pre-training is a bad idea, but it does mean that such pre-training can make FID unreliable in practice."),
         ("Where FID remains useful: large values reliably indicate training failures, FID appears dependable for monitoring convergence, and improvements from hyperparameter sweeps generally seem to translate to better subjective results; the caveats arise when sufficiently different architectures or training setups are compared.",
          "Conclusions",
          "The caveats arise when two sufﬁciently different architectures and/or training setups are compared."),
         ("Recommendation: when ImageNet pre-training is introduced to generative models, FID improvements should at least be verified with a Fréchet distance in a non-ImageNet-trained feature space (e.g. CLIP, SwAV, an uninitialized network); KID and Precision/Recall also rely on ImageNet classifier features.",
          "Conclusions",
          "As a partial solution, the FID improvements should at least be veriﬁed using a non-ImageNet trained Fr´echet distance."),
         ("Numerical sensitivity (Appendix A, citing prior work such as Binkowski et al. 2018): FID depends strongly on the number of real and generated samples, so the sample count must be standardized; the appendix also reports sensitivity to the exact Inception-V3 instance (TensorFlow vs PyTorch weights) and, citing Parmar et al. (2022), to resizing artifacts.",
          "Appendix A (Numerical sensitivity of FID)",
          "FID depends strongly on the number of samples used in evaluation (Figure 8a)."),
     ],
     "notes": "Affiliations: Aalto University and NVIDIA. Venue from the PDF header ('Published as a conference paper at ICLR 2023'). Disclosure: co-authors Karras, Aittala, Aila and Lehtinen are authors of StyleGAN2, the model used throughout and the one favoured in the Projected FastGAN comparison. The human assessment in the practical example comes from Sauer et al. (2021) plus the authors' visual inspection; no new human study was run (searched for 'human', 'participants'). Appendix A also states the official TensorFlow Inception network must be used for comparable results. The conclusions' remark that FID improvements from hyperparameter sweeps translate to better results is based on personal communication (footnote 7). Results tables (Tables 1-2, Figure 8 tables) not recorded."},

    {"id": "arxiv-2306.04675",
     "title": "Exposing flaws of generative model evaluation metrics and their unfair treatment of diffusion models",
     "authors": ["George Stein", "Jesse C. Cresswell", "Rasa Hosseinzadeh", "Yi Sui", "Brendan Leigh Ross", "Valentin Villecroze", "Zhaoyan Liu", "Anthony L. Caterini", "J. Eric T. Taylor", "Gabriel Loaiza-Ganem"],
     "year": 2023, "venue": "NeurIPS 2023", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2306.04675"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models", "deep-learning"], "par": ["unsupervised"],
     "proposes": ["A large human study (two-alternative forced choice, human error rate) of 41 generative models on CIFAR10, ImageNet, FFHQ and LSUN-Bedroom",
                  "Replacing Inception-V3 with DINOv2 ViT-L/14 as the encoder for Fréchet distance and related metrics",
                  "A released library (dgm-eval) computing 17 metrics for 9 encoders, plus the generated images and human evaluation data"],
     "claims": [
         ("Headline finding: in what the authors call the largest human experiment evaluating generative models to date, designed with psychophysics best practices, no existing metric strongly correlates with human evaluations of realism.",
          "Abstract",
          "Using best practices in psychophysics, we measure human perception of image realism for generated samples by conducting the largest experiment evaluating generative models to date, and find that no existing metric strongly correlates with human evaluations."),
         ("Human study design: each trial shows one image, either generated by one model or from the training set, and the participant chooses real or fake; models are scored by human error rate. The study targets realism only (not diversity or memorization), with over 1000 paid participants and 207k responses.",
          "Human evaluation of generated data",
          "Each trial is a two alternative forced choice task where a participant is shown either a generated image from one model, or an image from the training dataset, and must choose if it is real or fake."),
         ("Generation protocol: 100k images per model (equal per class for class-conditional models), using for each model the checkpoint and hyperparameters that achieved the lowest FID; only models trained without data external to the respective dataset are included.",
          "Datasets, metrics, and encoders",
          "We chose to generate 100k images from each model, with an equal number of images per-class for class conditional models, and used the checkpoints and hyperparameters that achieved the lowest FID for each model; Appendix A details the full generation procedure."),
         ("Model-type comparison (one-way ANOVAs per dataset, Bonferroni-corrected post hoc tests): diffusion models stand out on human error rate on all datasets except FFHQ, where they are on par (only GANs appeared in more than one FFHQ experiment); combined with FID rankings, diffusion models are judged most realistic but downranked by FID.",
          "Human evaluation of generated data (Results and analysis)",
          "Coupling the results in Table 1 with the FID rankings in Figure 2, we conclude that current diffusion models produce the most realistic images according to human perception, but are downranked by FID."),
         ("Encoder dependence: with Inception, FID prefers GANs over diffusion models, while Fréchet distance computed with self-supervised encoders trained on large, diverse data does not; this also holds on ImageNet. CLIP ViT-L/14, DINOv2 and MAE align much better with human error rate, SwAV relatively poorly, DreamSim except on ImageNet.",
          "The (mis)alignment of evaluation metrics and human assessment",
          "We find that diffusion models are often driving the discrepancy in alignment with human evaluation for the Inception network: FID prefers GANs over diffusion while FD determined by self-supervised models trained on very large and diverse datasets does not."),
         ("Ruling out alternative explanations: per-class Vendi diversity scores do not explain the FID-human discrepancy on ImageNet, and human errors on real images are not correlated with rarity scores, so the authors treat human error rate as ground truth for fidelity. They also note FD with DINOv2 emphasizes fidelity more than diversity.",
          "Alternative explanations: diversity, rarity, and memorization",
          "Combined with the diversity analysis above, this rules out diversity as an alternative explanation for the lack of alignment between human assessment and FID, and proves that alignment of FD metrics with human error rate is a desirable property for the studied generative models."),
         ("Memorization check: using the calibrated l2 distance of Carlini et al. [13] on 100k images from each of 41 models, most CIFAR10 models show exact memorization, while no conclusive pixel-wise memorization was found on ImageNet, FFHQ or LSUN-Bedroom (reconstructive memory was found on ImageNet and LSUN-Bedroom). The study was not designed to detect 'copy-paste' combinations of training images.",
          "Memorization",
          "We found no conclusive evidence of pixel-wise memorization by any model on ImageNet, FFHQ, or LSUN-Bedroom, but found evidence of models exhibiting reconstructive memory on ImageNet and LSUN-Bedroom [101]."),
         ("Memorization metrics: AuthPct, the CT score and FLS-POG are not reliable; with a test set substituted for the training set, CT and AuthPct behave almost the same, which the authors postulate reflects mode shrinkage and image fidelity rather than memorization. They recommend directly searching for memorized images with the calibrated l2 distance, though it is labour-intensive and requires tuning.",
          "Memorization (Evaluating memorization metrics)",
          "In conclusion, we find that none of AuthPct, the CT score, or FLS-POG is a reliable metric for memorization."),
         ("Limitations: human perception is taken as ground truth, but for uses such as data augmentation for classifiers the end user is a classifier; all datasets were 3-channel RGB images of human-identifiable objects, and transfer to medical, astronomical or other scientific data is open.",
          "Limitations",
          "It is an open question whether our proposed methods of evaluating generative models translate to e.g. medical images or astronomical images, which are also RGB, or more broadly to scientific data of N-dimensions."),
     ],
     "notes": "Affiliation: Layer 6 AI. Venue from the PDF footer ('37th Conference on Neural Information Processing Systems (NeurIPS 2023)'). Human study details (Appendix C): participants recruited on Prolific, required to be fluent in English and hold at least a Bachelor's-level degree, comparisons between models are between-subjects, small incentive per correct answer. Appendix D.3 (FD bias): FD-infinity has less bias than FD but does not remove it, and self-supervised encoders show less biased FD than Inception (DINOv2 with 20k samples has the same relative error as Inception with 50k); 50k samples are kept for all encoders. Appendix D.3 also hypothesizes FD works because encodings are approximately Gaussian and the bias may behave similarly across models (stated as untested hypotheses). Correlation tables and per-model metric tables (Appendix E) not recorded."},

    {"id": "arxiv-2301.13188",
     "title": "Extracting Training Data from Diffusion Models",
     "authors": ["Nicholas Carlini", "Jamie Hayes", "Milad Nasr", "Matthew Jagielski", "Vikash Sehwag", "Florian Tramèr", "Borja Balle", "Daphne Ippolito", "Eric Wallace"],
     "year": 2023, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2301.13188"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised"],
     "proposes": ["(l, delta)-diffusion extraction and (k, l, delta)-eidetic memorization definitions for image models",
                  "A generate-and-filter extraction attack (many generations per prompt, clique-based membership inference on near-identical generations)",
                  "Membership inference (loss threshold, LiRA) and inpainting attacks on diffusion models, with comparisons to GANs"],
     "claims": [
         ("Definition: because verbatim definitions do not suit high-resolution images, memorization is defined approximately: an example is extractable if an efficient algorithm that does not receive it outputs an image within distance delta (normalized Euclidean l2 by default), and (k, l, delta)-eidetic memorized if, additionally, at most k training examples are within delta of it (k counts near-duplicates).",
          "Defining Image Memorization",
          "Instead, we deﬁne a notion of approximate memorization based on image similarity metrics."),
         ("The definition is intentionally conservative: e.g. a recognizable but not near-identical generated photograph of a person (Barack Obama) does not count as memorized, although such generations could still cause privacy harms. A footnote stresses this is a very restricted definition of memorization.",
          "Defining Image Memorization (Restrictions of our definition)",
          "Our deﬁnition of extraction is intentionally conservative as compared to what privacy concerns one might ultimately have."),
         ("Stable Diffusion attack setup: the search is biased toward training images that are near-duplicated (CLIP-embedding cosine similarity) because these are much more likely to be memorized; for the 350,000 most-duplicated examples, 500 images per caption are generated (175 million in total) and flagged when at least 10 of 500 generations are near-identical. 94 images were (l2, 0.15)-extracted and 13 more were judged near-copies by manual inspection of the top 1000.",
          "Extracting Data from Stable Diffusion",
          "To reduce the computational load of our attack, as is done in [65], we bias our search towards duplicated training examples because these are orders of magnitude more likely to be memorized than non-duplicated examples [47, 41]."),
         ("Role of duplication: little eidetic memorization is found for k < 100, which the authors say is expected because the prompts were chosen from highly duplicated images (the figure caption calls the result an upper bound for this reason); they conclude duplication is a major factor behind extraction.",
          "Extracting Data from Stable Diffusion (Measuring eidetic memorization)",
          "These results show that duplication is a major factor behind training data extraction."),
         ("Imagen (2B parameters, non-public data): 23 of the top-1000 most duplicated prompts yielded memorized examples, and 3 of the 500 most out-of-distribution (unique) images were extracted, whereas no memorization was found for Stable Diffusion even among the 10,000 most-outlier samples; the authors believe higher capacity, more training iterations and a smaller dataset explain the difference.",
          "Extracting Outlier Examples",
          "Thus, Imagen appears less private than Stable Diffusion both on duplicated and non-duplicated images."),
         ("CIFAR-10: 16 diffusion models, each trained on a random half of CIFAR-10, each generate 2^16 images; an uncalibrated l2 threshold or perceptual distances (SSIM, CLIP) failed, so an image counts as extracted if its l2 distance to the nearest training image is abnormally low relative to its 50 nearest training neighbours. The authors note this is a check of capability rather than an attack per se.",
          "Untargeted Extraction",
          "Using the above methodology we identify 1,280 unique extracted images from the CIFAR-10 dataset (2.5% of the entire dataset)."),
         ("Diffusion vs GANs on off-the-shelf CIFAR-10 models (1 million unconditional generations each, non-duplicated images counted): diffusion models memorize more than GANs even at similar FID, and both families memorize more as FID improves.",
          "Comparing Diffusion Models to GANs (Data extraction results)",
          "Overall, we ﬁnd that diffusion models memorize more data than GANs, even when the GANs reach similar performance, e.g., the best DDPM model memorizes 2× more than StyleGAN-ADA but reaches the same FID."),
         ("Deduplication as a defense: retraining on CIFAR-10 after removing 5,275 near-duplicates (imagededup similarity > 0.85) reduced regenerated examples from 1280 to 986; the authors expect deduplication to be more effective for larger datasets such as Stable Diffusion's. DP-SGD caused training to diverge even at epsilon around 50.",
          "Defenses and Recommendations (Deduplicating Training Data)",
          "While not a substantial drop, these results show that deduplication can mitigate memorization."),
         ("Open question: the success of the attacks does not settle whether large models generate novel output or copy and interpolate training examples; the authors also note that more human-aligned definitions of data copying will need a more comprehensive analysis than their l2-based measurement.",
          "Discussion and Conclusion",
          "If our extraction attacks had failed, it may have refuted the hypothesis that models copy and interpolate training data; but because our attacks succeed, this question remains open."),
     ],
     "notes": "Affiliations: Google, DeepMind, ETHZ, Princeton, UC Berkeley. No venue statement was found in the v1 PDF and the arXiv record has no comment/journal_ref given, so no venue is recorded. Disclosure: authors are from Google/DeepMind, and one attacked model (Imagen) is a Google model whose training data is not public, so its extracted examples cannot be shown; the paper states an advance copy was shared with the authors of each large model studied. Membership inference results (e.g. LiRA TPR at fixed FPR, better FID associated with higher attack success over training) are shown in figures and partly in text; not recorded as claims. Table 1 (images extracted per model) not recorded."},

    {"id": "arxiv-2212.03860",
     "title": "Diffusion Art or Digital Forgery? Investigating Data Replication in Diffusion Models",
     "authors": ["Gowthami Somepalli", "Vasu Singla", "Micah Goldblum", "Jonas Geiping", "Tom Goldstein"],
     "year": 2022, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2212.03860"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised"],
     "proposes": ["A benchmark of 10 feature extractors for replication detection on 5 real retrieval datasets and 5 purpose-built synthetic copy datasets, and a split-product similarity",
                  "Retrieval-based search for content replication in DDPMs (CelebA, Oxford Flowers), an ImageNet LDM, and Stable Diffusion v1.4"],
     "claims": [
         ("Working definition (informal): a generated image has replicated content if an object in the foreground or background appears identically in a training image, ignoring minor variations explainable by data augmentation; style or semantic similarity is deliberately excluded as highly subjective.",
          "3. What Counts as Replication?",
          "We say that a generated image has replicated content if it contains an object (either in the foreground or background) that appears identically in a training image, neglecting minor variations in appearance that could result from data augmentation."),
         ("The authors state that the similarity level needed to count as replication is subjective, and instead of choosing an arbitrary definition they present quantitative and qualitative results for readers to judge.",
          "1. Introduction",
          "Rather than choosing an arbitrary deﬁnition, we focus on presenting quantitative and qualitative results to the reader, leaving each person to draw their own conclusions based on their role and stake in the process of generative AI."),
         ("Choosing the detector: among 10 feature extractors evaluated by mAP on 5 real retrieval datasets and 5 synthetic copy datasets, DINO with split-product had the best average rank; Swin Transformer was best on real datasets and SSCD on synthetic ones. SSCD, Swin and DINO are used afterwards.",
          "4.1. Choosing the Best Replication Detector",
          "DINO [12] with split-product performed the best on average across all 10 datasets."),
         ("Training-set size: DDPMs trained on Celeb-A subsets (300, 3000, full) and Oxford Flowers (100, 1083, 8189 images), each for at least 300k steps and until FID < 50, show frequent copying for small training sets that decreases as training data grows; for the full Celeb-A model the generation-to-train similarity histogram overlaps the train-to-train baseline. Displayed examples come from the 20 generations with highest similarity.",
          "5. Do Diffusion Models Copy?",
          "We observe that the diffusion models trained on smaller datasets tend to generate images that are copied from the training data."),
         ("ImageNet LDM (off-the-shelf, class-conditional; 100 random classes, 1000 samples each): no significant copying was observed; similarity scores never exceeded 0.65 and the closest matches, though very similar, were never exact copies and may be explained by low intra-class diversity.",
          "6. Case Study: ImageNet LDM",
          "Qualitatively, we observe no signiﬁcant copying in any of the generations by this model."),
         ("Stable Diffusion v1.4: 9000 captions sampled from LAION Aesthetics v2 6+ (12M images) were used as prompts; among about 170 generations with top-1 similarity > 0.5 (top 1.88 percentile) a significant amount of copying (whole objects, backgrounds) was observed, though no generation matched its own caption's source image. Some replication depended on key phrases in the caption.",
          "7. Case Study: Stable Diffusion",
          "Above this 0.5 threshold, we observe a signiﬁcant amount of copying."),
         ("Duplication (duplicate = SSCD score > 0.95 in LAION-Aesthetics): a random source image is duplicated 11.6 times on average and a typical matched image 3.1 times, but very close matches (> .5 SSCD) 34.1 times; the authors conclude replicated content seems to come from images duplicated more than a typical image.",
          "7. Case Study: Stable Diffusion (Role of duplicate training data)",
          "It seems that replicated content tends to be drawn from training images that are duplicated more than a typical image."),
         ("Duplication alone is not the explanation: the small-dataset models of Section 5 replicate strongly without duplicated images; the authors speculate that Stable Diffusion's replication comes from an interaction of text conditioning, a highly skewed distribution of image repetitions, and enough gradient updates to overfit a subset of the data.",
          "8. Possible causes of replication",
          "However this explanation is incomplete and oversimpliﬁed; Our models in Section 5 consistently show strong replication when they are trained with small datasets that are unlikely to have any duplicated images."),
         ("Limitation: only the 12M LAION Aesthetics v2 6+ subset (less than 0.6% of the training data) was searched, replication exists outside it, and the retrieval method likely misses some replication, so the results systematically underestimate replication.",
          "9. Limitations & Conclusion",
          "For both of these reasons, the results here systematically underestimate the amount of replication in Stable Diffusion and other models."),
     ],
     "notes": "Affiliations: University of Maryland, College Park and New York University. The v3 PDF (arXiv, Dec 2022, 'updated draft') contains no venue statement (searched for CVPR, conference), so no venue is recorded. The authors also note that sampling captions from LAION may itself raise replication rates because some captions contain key phrases tied to dataset images, and that there is no baseline sampler for 'typical' captions. Table 1 (mAP per extractor/dataset) not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
