import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ad_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2206.09426",
     "title": "ADBench: Anomaly Detection Benchmark",
     "authors": ["Songqiao Han", "Xiyang Hu", "Hailiang Huang", "Minqi Jiang", "Yue Zhao"],
     "year": 2022, "venue": "NeurIPS 2022 Datasets and Benchmarks Track", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2206.09426"},
     "tasks": ["anomaly-detection"],
     "fam": ["classical-outlier-detectors", "deep-learning", "tree-ensembles"], "par": ["unsupervised", "semi-supervised", "supervised"],
     "proposes": ["ADBench: a tabular anomaly detection benchmark of 30 algorithms (14 unsupervised, 7 semi-supervised, 9 supervised) on 57 datasets (47 existing, 10 new CV/NLP datasets turned into embeddings), compared from three angles: level of supervision (fraction of labeled anomalies), synthetic anomaly types (local, global, dependency, clustered) and robustness to noisy and corrupted data (duplicated anomalies, irrelevant features, annotation errors)"],
     "claims": [
         ("Datasets: besides more than 40 existing benchmark datasets (kept only if the anomaly ratio is below 40%), 10 CV and NLP datasets are added as embeddings from pretrained models (BERT [CLS] token for NLP, ImageNet-pretrained ResNet18 after the last average pooling for CV). For these, one class is set as normal, the remaining classes are downsampled to 5% of the total instances as anomalies, and results are averaged over all classes, following previous works.",
          "Section 3.2",
          "Following previous works [151, 152], we set one of the multi-classes as normal, downsample the remaining classes to 5% of the total instances as anomalies, and report the average results over all the respective classes."),
         ("Protocol: although unsupervised detectors are primarily designed for the transductive setting, all algorithms are adapted to the inductive setting (as is common in PyOD, TODS and PyGOD): 70% of the data for training and 30% for testing with stratified sampling to keep the anomaly ratio, each experiment repeated 3 times and averaged.",
          "Section 4.1",
          "We repeat each experiment 3 times and report the average.", 6),
         ("Hyperparameters: all algorithms use their default hyperparameter settings from the original paper (specific values in Appendix B.1 and the codebase). The authors acknowledge that a small hold-out set could be used to tune semi- and fully-supervised methods, but this setting is not considered.",
          "Appendix C (Details on Experiment Setting)",
          "It is also acknowledged that it is possible to use a small hold-out data for hyperparameter tuning for semi- and fully-supervised methods [164], while we do not consider this setting in this work."),
         ("Unsupervised setting (57 datasets, AUCROC): none of the 14 unsupervised methods is statistically better than the others in the critical difference diagram, where most algorithms are connected without statistical significance.",
          "Section 4.2",
          "None of the unsupervised methods is statistically better than the others, as shown in the critical difference diagram of Fig. 4a"),
         ("Some deep unsupervised methods such as DeepSVDD and DAGMM are surprisingly worse than shallow methods; the authors attribute this to deep unsupervised methods being harder to train (more hyperparameters) and harder to tune without label guidance.",
          "Section 4.2",
          "We also note that some DL-based unsupervised methods like DeepSVDD and DAGMM are surprisingly worse than shallow methods."),
         ("Few labels: for most semi-supervised methods, 1% labeled anomalies suffice to surpass the best unsupervised method, while most supervised methods need 10%; with few labels (5% or less) semi-supervised methods are generally better than fully-supervised ones, and with many labeled anomalies both are comparable.",
          "Section 4.2",
          "For most semi-supervised methods, merely 1% labeled anomalies are sufﬁcient to surpass the best unsupervised method (shown as the dashed line in Fig. 4b), while most supervised methods need 10% labeled anomalies to achieve so."),
         ("Anomaly types (synthetic anomalies injected into benchmark datasets): unsupervised performance depends on how well the method's assumptions match the anomaly type; LOF is statistically best for local anomalies and KNN for global anomalies, and no algorithm performs well on all types (LOF does poorly on clustered anomalies). The authors advise selecting algorithms by the characteristics of the task.",
          "Section 4.3",
          "Performance of unsupervised algorithms highly depends on the alignment of its assumptions and the underlying anomaly type."),
         ("For local, global and dependency anomalies, most label-informed (semi- and fully-supervised) methods perform worse than the best unsupervised method of each type; only for clustered anomalies do label-informed (especially semi-supervised) methods beat the best unsupervised method. The authors believe partial labels cannot capture all characteristics of a given anomaly type, so knowing the anomaly type may outweigh partial labels.",
          "Section 4.3",
          "The “power” of prior knowledge on anomaly types may overweigh the usage of partial labels."),
         ("Conflict of interest stated in the text: most unsupervised algorithms are taken from PyOD, which the authors call their early work; the semi-supervised methods are implemented by the authors and released with ADBench.",
          "Section 3.2",
          "Most unsupervised algorithms are readily available in our early work Python Outlier Detection (PyOD) [198], and some supervised methods are available in scikit-learn [133] and corresponding libraries."),
     ],
     "notes": "Authors from Shanghai University of Finance and Economics and Carnegie Mellon University; all authors contributed equally and are listed alphabetically. Venue from the PDF footnote ('36th Conference on Neural Information Processing Systems (NeurIPS 2022) Track on Datasets and Benchmarks') and the arXiv comment. Section numbers are taken from cross-references in the text (§3.2, §4.1-§4.4, Appx. C); the extracted headings carry no numbers. Metrics: AUCROC and AUCPR (main text reports AUCROC; the footnote says AUCPR gives similar results), with critical difference diagrams (Wilcoxon-Holm, p <= 0.05). 98,436 experiments in total (Appx. C). Appendix B.1 says the default hyperparameters in PyOD are used for the unsupervised algorithms deployed by PyOD; tree ensembles use the default settings of their official repositories and SVM/MLP/RF scikit-learn defaults. Training data for unsupervised detectors is the 70% split including its anomalies (inductive, contaminated); labeled fraction gamma_l refers to anomalies in the train set. The anomaly-type and robustness experiments use only the 47 classical datasets with synthetic anomalies generated from a model of the normal samples (GMM for local/clustered, uniform for global, vine copula/KDE for dependency; original anomalies discarded). Robustness results (duplicated anomalies hurt unsupervised methods most; irrelevant features hurt supervised methods least) and runtime (HBOS, COPOD, ECOD, NB fastest; XGBOD, ResNet, FTTransformer heavy) not recorded as claims. Conflict of interest: Yue Zhao is the first author of PyOD [198], XGBOD [195] and LSCP [197]; COPOD [96] and ECOD [97] (both benchmarked) are co-authored by Y. Zhao and X. Hu. Results tables/figures not recorded."},

    {"id": "arxiv-2305.00735",
     "title": "Unsupervised anomaly detection algorithms on real-world data: how many do we need?",
     "authors": ["Roel Bouman", "Zaharah Bukhsh", "Tom Heskes"],
     "year": 2023, "venue": "JMLR", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2305.00735"},
     "tasks": ["anomaly-detection"],
     "fam": ["classical-outlier-detectors", "deep-learning", "autoencoders"], "par": ["unsupervised"],
     "proposes": ["A comparison of 32 unsupervised anomaly detection algorithms on 52 real-world multivariate tabular datasets without hyperparameter optimization (ROC AUC averaged over a range of sensible hyperparameters), with Nemenyi post-hoc tests and a two-way clustering that separates 'local' and 'global' datasets"],
     "claims": [
         ("No hyperparameter optimization: each algorithm is run with several sensible hyperparameter settings per dataset and the ROC-AUC is averaged over them; hyperparameters are not optimized (e.g. by cross-validation) to reflect that no labels are available in practice.",
          "Section 3 (Materials and Methods)",
          "We refrain from optimizing hyperparameters, e.g., using cross-validation, to reﬂect the real-world situation in which no labels are available for training the models."),
         ("Implementations: 27 of the 32 methods are used as implemented in PyOD, and as part of this research the authors contributed to PyOD (a memory-efficient COF and the Birgé-Rozenholc histogram size selection used in HBOS and LODA); EIF uses the authors' 'eif' package, ODIN is implemented by the authors, and DeepSVDD uses Lukas Ruff's public code modified for general tabular datasets.",
          "Section 3.1",
          "As part of this research, we made several contributions to this open source library"),
         ("Evaluation: anomaly scores are computed on all available data at once, without cross-validation or train-test splits, and compared with the ground-truth labels by ROC AUC; R-precision, average precision and their chance-adjusted variants were considered but found less stable and harder to interpret. Differences are tested with the Iman-Davenport statistic and the Nemenyi post-hoc test.",
          "Section 3.3",
          "For each dataset, we calculate anomaly scores on all available data at once, without using any cross-validation or train-test splits."),
         ("Dataset handling: duplicates are removed and variables are centered by the median and scaled by the interquartile range; three datasets on which nearly every algorithm had AUC between 0.4 and 0.6 were excluded, and for two datasets (skin, vertebral) where the more heterogeneous group had been chosen as the normal class, labels were inverted and AUC recalculated.",
          "Section 4.1",
          "These datasets, the ‘hrss anomalous standard’, ‘wpbc’ and ‘yeast’ dataset, were therefore excluded from further analysis."),
         ("Overall: kth-NN significantly outperforms 14/15 algorithms at p = 0.05/0.10, and Isolation Forest and its extended version show similarly consistent performance; since their cost scales linearly with the number of samples, this may give them a clear edge over kNN-type methods on large datasets. The original CBLOF is by far the worst.",
          "Section 4.1",
          "Since the computational complexity of Isolation Forest and variants thereof scales linearly with the number of samples n, this may give them a clear edge over methods such as kNN and derivatives for large datasets"),
         ("Neural networks: many of them do not perform well ((soft-boundary) DeepSVDD, ALAD and SO-GAAL are in the lower segment). The authors surmise two reasons: they were not designed for tabular data and cannot leverage the feature extraction that helps them in computer vision, and they are complex, making general hyperparameters and architectures hard to specify. The autoencoder and its variants and LUNAR perform about average, likely due to more straightforward optimisation criteria.",
          "Section 4.1",
          "From these overall results it is clear that many of the neural networks do not perform well."),
         ("Local vs global: clustering the results splits the datasets into roughly a quarter 'local' and three quarters 'global' problems. Local methods (COF, ensemble-LOF, LOF) are among the worst overall but among the best on the local datasets, which the authors call an example of Simpson's paradox and a partial explanation of the difference from Campos et al. (2016). On local datasets kNN and ABOD are the top performers; on global datasets the Extended Isolation Forest has the highest mean, closely followed by Isolation Forest.",
          "Section 4.3",
          "This phenomenon is a ﬁne example of Simpson’s paradox (Simpson, 1951)."),
         ("Conclusion: the authors are 'tempted' to answer 'three': k-thNN, kNN and EIF seem sufficient for the type of multivariate datasets in the study (k-thNN without prior knowledge of anomaly type, kNN for local, EIF/IF for global, with IF/EIF having the lowest computational complexity). The conclusion is stated as open to revision when other algorithms or datasets are added; raw images, texts and time series are left to future work.",
          "Section 6 (Conclusion)",
          "a toolbox with k-thNN, kNN, and EIF seems suﬃcient to perform well on the type of multivariate datasets considered in our study"),
         ("Caveat: the authors are aware that the local/global characterization may be an oversimplification with more datasets and algorithms; local and global problems likely overlap with, but need not equal, multimodal and unimodal problems, and further theoretical and simulation studies are needed.",
          "Section 5 (Discussion)",
          "However, we are well aware that this characterization may turn out to be an"),
     ],
     "notes": "Affiliations: Radboud University and Eindhoven University of Technology. Venue from the arXiv journal_ref given by the caller (the v1 PDF shows only '©2023 Bouman, Bukhsh, and Heskes. License: CC-BY 4.0', no journal header). Same first author as arxiv-2501.13864. Purely unsupervised (transductive) evaluation on real anomalies; no synthetic datasets. Hyperparameter grids per method in Table 1 (e.g. IF 1000 trees with 128-1024 samples; kNN/LOF k = 5..30; AE/VAE/DeepSVDD 1-3 layers with shrinkage factors). The text gives two different significance levels for kNN on local datasets: Section 4.3 says kNN and ABOD 'significantly outperform 16 other methods at p = 0.05', while the Conclusion says kNN 'outperforms 16 out of 32 methods at p = 0.10'. The paper describes ADBench (Han et al., 2022) as subsampling to 10,000 samples and generating anomalies synthetically; ADBench's own main text was not found to state the subsampling, and it evaluates real anomalies on its 47 datasets with synthetic anomalies only in the anomaly-type experiments (not verified further). Conflict of interest: the authors contributed code to PyOD (the library of 27 of the 32 implementations) and implemented ODIN themselves; they are not authors of the benchmarked methods as far as the text shows. Ensembles (meta-techniques) were deliberately not covered. Results tables not recorded."},

    {"id": "arxiv-2007.02500",
     "title": "Deep Learning for Anomaly Detection: A Review",
     "authors": ["Guansong Pang", "Chunhua Shen", "Longbing Cao", "Anton van den Hengel"],
     "year": 2020, "venue": "ACM Computing Surveys", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2007.02500", "doi": "https://doi.org/10.1145/3439950"},
     "tasks": ["anomaly-detection"],
     "fam": ["deep-learning", "autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised", "semi-supervised", "supervised"],
     "proposes": ["A taxonomy of deep anomaly detection into three paradigms (deep learning for feature extraction, learning feature representations of normality, end-to-end anomaly score learning) and 11 fine-grained categories, mapped to six detection challenges (CH1-CH6), plus collections of open-source code and 21 datasets with real anomalies"],
     "claims": [
         ("The authors argue that deep methods offer end-to-end optimization and representations tailored to anomaly detection, which traditional methods lack, and that although shallow methods exist for complex data (high-dimensional, image, video, graph, heterogeneous sources), they are generally substantially weaker and less adaptive than deep methods (summarized in Table 1). This is an argument in the review, not an empirical comparison carried out in it.",
          "Section 2.2",
          "Although there are shallow methods for handling those complex data, they are generally substantially weaker and less adaptive than the deep methods."),
         ("Terminology: methods trained on purely normal training data, which some studies call unsupervised, are referred to in this review as semi-supervised (following [2, 28]); weakly-supervised detection instead assumes partial, inexact or inaccurate anomaly labels.",
          "Section 2.2",
          "To avoid unnecessary confusion, following [2, 28], these methods are referred to as semi-supervised methods hereafter."),
         ("Challenge CH3: fully supervised detection is often impractical because labeled anomalies are costly, and unsupervised methods have no prior knowledge of true anomalies and rely heavily on their assumption about the anomaly distribution; leveraging readily available labeled normal data and some labeled anomalies is therefore suggested.",
          "Section 2.2",
          "However, unsupervised methods do not have any prior knowledge of true anomalies."),
         ("Disadvantages of using deep models only as feature extractors (e.g. pre-trained networks followed by a conventional detector): fully disjoint feature extraction and scoring often give suboptimal anomaly scores, and pre-trained deep models are typically limited to specific types of data; the projection may not preserve enough information for detection.",
          "Section 4",
          "Pre-trained deep models are typically limited to specific types of data."),
         ("No meta-analysis of performance: because the methods are evaluated on diverse datasets, the review does not compare their empirical performance; it observes instead that most methods are unsupervised or semi-supervised, deep-learning tricks (augmentation, dropout, pre-training) are under-explored, and most networks have no more than five layers.",
          "Section 7.1",
          "Since these methods are evaluated on diverse datasets, it is difficult to have an universal meta-analysis of their empirical performance."),
         ("Evaluation datasets: a main obstacle is the lack of real-world datasets with real anomalies; many studies evaluate on datasets converted from classification data, which may fail to reflect performance in real-world applications. The review lists 21 public datasets with real anomalies, restricted to large-scale and/or high-dimensional ones.",
          "Section 7.2",
          "This way may fail to reflect the performance of the methods in real-world anomaly detection applications."),
         ("Most methods learning representations of normality implicitly assume that the training data is clean (free of anomalies), so large-scale normality learning needs anomaly-free unlabeled data or robustness to contamination.",
          "Section 8.3",
          "This is because most methods in Sections 5 implicitly assume that the training data is clean and does not contain any noise/anomaly instances."),
         ("The review states that most deep anomaly detection methods focus on point anomalies and show substantially better performance than traditional methods, while deep models for conditional/group anomalies are much less explored. No supporting comparison is given in this sentence, and Section 7.1 says a universal meta-analysis is difficult.",
          "Section 8.4",
          "Most deep anomaly detection methods focus on point anomalies, showing substantially better performance than traditional methods."),
     ],
     "notes": "Affiliations: University of Adelaide and University of Technology Sydney. Venue from the PDF (ACM Comput. Surv., DOI 10.1145/3439950) and the arXiv journal_ref. Survey without its own experiments; claims record its arguments and stated limitations. Section numbers are from the numbered headings in the PDF. Other stated disadvantages (not recorded as claims): autoencoder representations can be biased by outliers in the training data and the reconstruction objective is not designed for anomaly detection (Section 5.1.1); deep one-class models may work ineffectively with complex normal-class distributions (Section 5.2.3); ranking models need labeled anomalies and may not generalize to unseen anomalies (Section 6.2). Conflict of interest: the first author's own methods (REPEN [112], deep weakly-supervised detection/PReNet line [114], DevNet [115]) are reviewed, and Section 8.2 cites [113-115, 133] (three of them by Pang et al.) for the statement that deep detectors can learn abnormality beyond the given anomaly examples; CH1 cites [115] for high false positives of unsupervised methods."},

    {"id": "arxiv-1901.01588",
     "title": "PyOD: A Python Toolbox for Scalable Outlier Detection",
     "authors": ["Yue Zhao", "Zain Nasrullah", "Zheng Li"],
     "year": 2019, "venue": "JMLR", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1901.01588"},
     "tasks": ["anomaly-detection"],
     "fam": ["classical-outlier-detectors", "deep-learning"], "par": ["unsupervised"],
     "proposes": ["PyOD: an open-source Python toolbox with more than 20 outlier detection algorithms (proximity-based, linear models, ensembles, neural networks) and detector combination methods under a single scikit-learn-like API"],
     "claims": [
         ("Motivation: Python lacked a dedicated outlier detection toolkit; existing implementations were single-algorithm tools (e.g. PyNomaly) or part of general frameworks such as scikit-learn that do not cater specifically to anomaly detection, while ELKI, RapidMiner (Java) and outliers (R) exist in other languages.",
          "Introduction",
          "However, Python, one of the most important languages in machine learning, still lacks a dedicated toolkit for outlier detection."),
         ("Coverage: more than 20 algorithms, from classical techniques such as local outlier factor to neural network architectures such as autoencoders and adversarial models, plus combination methods for merging detector results and outlier ensembles (version 0.7.0 summarized in Table 1).",
          "Introduction",
          "Firstly, it contains more than 20 algorithms which cover both classical techniques such as local outlier factor and recent neural network architectures such as autoencoders or adversarial models."),
         ("Unified API inspired by scikit-learn: every detector inherits from a base class with fit (train statistics), decision_function (raw outlier scores for unseen data), predict (binary labels) and predict_proba (probability by normalization or unification); fitted training scores and labels are available as attributes.",
          "Section 3 (Library Design and Implementation)",
          "fit processes the train data and computes the necessary statistics"),
         ("Scalability: selected algorithms are JIT-compiled with numba and some support multi-core execution via joblib; the toolbox relies on numpy, scipy and scikit-learn, and neural networks additionally require Keras.",
          "Section 3 (Library Design and Implementation)",
          "To enhance model scalability, select algorithms (Table 1) are optimized with JIT using numba."),
         ("Engineering practices: continuous integration on several Python versions and operating systems, PEP8 and CodeClimate checks, refactoring of complex code, and unit tests for 95% overall code coverage.",
          "Section 2 (Project Focus)",
          "code blocks with high cognitive complexity are actively refactored and a standard set of unit tests exist to ensure 95% overall code coverage"),
         ("The helper data generator used in the example creates inliers from a Gaussian distribution and outliers from a uniform distribution (two-dimensional artificial data); the paper's only performance output is this demo, and it reports no benchmark comparison of the detectors.",
          "Section 3 (Library Design and Implementation)",
          "which generates inliers from a Gaussian distribution and outliers from a uniform distribution"),
         ("Stated future work (current gaps): models for time series and geospatial data, computational efficiency through distributed computing, and engineering issues such as sparse matrices and memory limitations.",
          "Section 4 (Conclusion and Future Plans)",
          "As avenues for future work, we plan to enhance the toolbox by implementing models that work well with time series and geospatial data, improving computational eﬃciency through distributed computing and addressing engineering challenges such as handling sparse matrices or memory limitations."),
     ],
     "notes": "Venue from the PDF header ('Journal of Machine Learning Research 20 (2019) 1-7') and the arXiv journal_ref; the PDF states CC-BY 4.0. Library paper without experiments: no benchmark of the included detectors (the documentation is said to contain algorithm benchmarks, not part of the paper). Table 1 includes the first author's own methods XGBOD (Zhao and Hryniewicki, 2018b) and LSCP (Zhao et al., 2019). Relation to ADBench (arxiv-2206.09426): Yue Zhao is an author of both; ADBench calls PyOD 'our early work' and takes most unsupervised algorithms from it, and ADBench criticizes fully synthetic anomaly generation 'such as PyOD' for failing to create complex anomalies. The paper says PyOD has been used in academic and commercial projects (self-reported usage statistics not recorded)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
