import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_cpd_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2003.06222",
     "title": "An Evaluation of Change Point Detection Algorithms",
     "authors": ["Gerrit J. J. van den Burg", "Christopher K. I. Williams"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2003.06222",
               "code": "https://github.com/alan-turing-institute/TCPDBench"},
     "tasks": ["change-point-detection", "online-change-point-detection"],
     "fam": ["bayesian-changepoint-models"], "par": ["unsupervised"],
     "proposes": ["TCPD: a data set of 37 real-world time series (plus 5 hidden simulated quality-control series) annotated for change points by five human annotators each, with an annotation tool",
                  "Evaluation metrics for multiple ground-truth annotations: the segmentation covering metric averaged over annotators, and an F1-score whose precision uses the union of annotations and whose recall is macro-averaged over annotators (margin of error M)",
                  "TCPDBench: a benchmark of 14 change point methods (including bocpd, bocpdms, rbocpdms and a zero baseline) under a Default and an Oracle (best-over-grid) protocol"],
     "claims": [
         ("Data set and annotation: 37 real series (33 univariate, 4 multivariate) from sources such as WorldBank, EuroStat and Wikipedia, plus 5 simulated quality-control series added without the annotators' knowledge (42 in total). Annotators were data scientists and machine learning researchers deliberately chosen without domain background; the tool assigned series randomly, and each series was annotated by five of the eight annotators.",
          "Section 4 (Annotation Collection)",
          "In total, eight annotators provided annotations for the 42 time series, with ﬁve annotators assigned to each time series."),
         ("Metrics: the covering metric (Jaccard-based, averaged over annotators) is used as the clustering metric (Hausdorff is disregarded because it can obscure methods with many false positives); the F1-score treats detections within a margin M of an annotation as true positives without double counting, with precision against the combined set of annotations and recall averaged over annotators. t = 1 is added as a trivial change point to keep precision and recall defined; M = 5 in the experiments.",
          "Section 3",
          "In the experiments we use a margin of error of M = 5."),
         ("Annotator consistency: in one-vs-rest evaluation the median annotator score was approximately 0.8 (covering) and 0.9 (F1); F1 values are generally higher because of the margin of error and because precision uses the union of annotations. The few low-agreement cases are often due to one or two annotators disagreeing with the others.",
          "Section 4.4",
          "The ﬁgures show that on average there is a high degree of agreement between annotators, with the median annotator score approximately 0.8 for the covering metric and 0.9 for the F1-score"),
         ("Protocol: two evaluations. Default uses each method's default settings from the package documentation (a data analyst without prior knowledge of parameter choices); Oracle reports the maximum score over a grid search of hyperparameters per series. The authors emphasize that Oracle is not necessarily a realistic measure because, in unsupervised CPD, users cannot in general tune parameters to match the unknown ground truth. Univariate and multivariate series are analysed separately, series are standardized, and computation time is not reported because implementation languages differ.",
          "Section 5 (Experimental Setup)",
          "It should be emphasized that while the Oracle experiment is important from a theoretical point of view, it is not necessarily a realistic measure of practical algorithm performance."),
         ("Decision rule for Bayesian online methods: BOCPD-type algorithms following Adams and MacKay (2007) compute a full distribution over change point locations and do not return a single segmentation, so the maximum a posteriori (MAP) segmentation is used to compare them with the other methods.",
          "Section 5 (Experimental Setup)",
          "To allow for comparisons to the other methods we use the maximum a posteriori (MAP) segmentation of the series (see, e.g., Fearnhead and Liu, 2007)."),
         ("bocpd settings: R package ocp with a Gaussian likelihood and its conjugate prior (described in the text as a 'negative inverse gamma prior'), prior mean 0 (data standardized), no run-length truncation. Default: intensity lambda_gap = 100, alpha0 = beta0 = kappa0 = 1. Grid: intensity in {10, 50, 100, 200} and alpha0, beta0, kappa0 each in {0.01, 0.1, 1, 10, 100}. bocpdms used the same settings but with run-length pruning to the best 100 run lengths during the grid search (for speed); rbocpdms used pruning and timeouts.",
          "Appendix A",
          "For the default experiment the intensity (λgap) was set to 100, the prior variables were set to α0 = 1, β0 = 1, and κ0 = 1."),
         ("Default setting: the zero baseline (always no change points) outperforms many methods, which the authors attribute partly to the small number of change points per series and say also suggests many methods return many false positives; no method performed significantly better than zero in the Default experiment, while this does not hold for Oracle.",
          "Section 5",
          "We also see that in our experiments no method performs signiﬁcantly better than the zero method on the Default experiment, while this does not hold for the Oracle experiment."),
         ("Oracle setting (rank analysis: Friedman test, pairwise Wilcoxon signed-rank tests with Holm correction, critical-difference diagrams): bocpd achieves the highest average rank, and the authors find it noteworthy that bocpd, with a simple Gaussian constant-mean segment model, outperforms methods allowing trend and seasonality (prophet) or autoregressive structure (bocpdms).",
          "Section 5",
          "It is noteworthy that even though bocpd assumes a simple Gaussian model with constant mean for each segment, it outperforms methods that allow for more complex time series behavior such as trend and seasonality (prophet), or autoregressive structures (bocpdms)."),
         ("Conclusion: with default parameters binseg performs best on univariate series but is not statistically significantly different from several other methods; with hyperparameter tuning bocpd outperforms all other methods on univariate and multivariate series, but its differences from some algorithms (binseg, segneigh and rfpop, among others) are not statistically significant. Future work could add automated hyperparameter tuning to bridge the Default-Oracle gap (perhaps inspired by Turner et al., 2009 for bocpd).",
          "Section 6 (Discussion)",
          "However, the diﬀerences between it and some other algorithms (binseg, segneigh, and rfpop, among others) have been shown to not be statistically signiﬁcantly diﬀerent."),
     ],
     "notes": "Affiliations: The University of Edinburgh and The Alan Turing Institute (first author's work done at the Turing Institute; supported by The Alan Turing Institute under EPSRC grant EP/N510129/1); the code repositories (TCPDBench, AnnotateChange, and the bocpdms/rbocpdms code used) are under the alan-turing-institute GitHub organization. No venue: the PDF states none (it carries an arXiv changelog; v3 expanded the Oracle grid search, switched to critical-difference diagrams and updated results; v2 corrected an F1 computation error). Section numbers 2-6 and 4.4 are confirmed by the outline paragraph and cross-references; subsection names are used otherwise. Motivation: algorithms are typically evaluated on simulated data and a few reused real series with unreliable ground truth. Annotation tool: no dates, values or series names shown; introductory synthetic series with feedback, repeated if the annotator's F1 is too low. Methods use existing (mostly author-provided) packages; rfpop's grid has 2,424 configurations, and the authors note the Oracle is not indicative of real-world performance since a data scientist cannot identify the most accurate segmentation among grid results. rbocpdms failed on two univariate series in Default (scored zero); uk_coal_employ (missing values) excluded. Quality-control series excluded from the benchmark. Appendix B simulates chance agreement (Poisson/uniform annotations) and finds agreement significantly above chance for most series. Results tables (Table 2) not recorded."},

    {"id": "arxiv-1801.00718",
     "title": "Selective review of offline change point detection methods",
     "authors": ["Charles Truong", "Laurent Oudre", "Nicolas Vayatis"],
     "year": 2018, "venue": "Signal Processing", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1801.00718"},
     "tasks": ["change-point-detection"],
     "fam": ["kernel-methods", "linear-models"], "par": ["unsupervised"],
     "proposes": ["A typology organizing offline multiple change point detection methods by three elements: a cost function, a search method, and a constraint (penalty) on the number of changes",
                  "ruptures: a Python library implementing the main reviewed methods"],
     "claims": [
         ("Framework: offline detection is cast as minimizing a sum of segment costs, with a known number of changes (P1) or with a complexity penalty (P2). Methods are characterized by a cost function (a measure of homogeneity that encodes the type of change detectable), a search method (exact or approximate, trading complexity and accuracy), and a constraint; too small a penalty detects many changes, even noise, while too much penalization detects only the most significant changes or none.",
          "Section 2.3",
          "Precisely, detection methods are expressed as the combination of the following three elements."),
         ("Scope limitation: Bayesian approaches are not covered by the review's framework, although the authors note they provide state-of-the-art results in several domains such as speech and sound processing.",
          "Section 2.4",
          "In particular, Bayesian approaches are not considered in the remainder of this article, even though they provide state-of-the-art results in several domains, such as speech and sound processing."),
         ("Where Bayesian methods are pointed to: the HMM is named as the most well-known Bayesian algorithm, later extended with Dirichlet processes or product partition models; readers are referred to other reviews for Bayesian approaches. Apart from this paragraph and the BIC/mBIC penalties, no further discussion of Bayesian change point methods was found in the text (searched for Bayes, posterior, prior).",
          "Section 2.4",
          "The interested reader can ﬁnd reviews of Bayesian approaches in [4] and [6]."),
         ("Theoretical evaluation: asymptotic consistency is defined on change point fractions (t/T), since the distances between true and estimated change point indexes in general do not converge to 0 even for simple models.",
          "Section 3.1",
          "As a result, consistency results in the literature only deal with change point fractions."),
         ("Empirical metrics reviewed: AnnotationError (difference in the number of changes), Hausdorff (worst temporal error), RandIndex, and F1-score with a user-defined margin M; precision and recall are well defined only if M is smaller than the minimum spacing between true change points, and over-segmentation drives precision toward zero and recall toward one.",
          "Section 3.2.4",
          "A breakpoint is considered detected up to a user-deﬁned margin of error M > 0; true positives Tp are true change points for which there is an estimated one at less than M samples, i.e."),
         ("Search costs (assuming O(1) cost evaluation): Opt (dynamic programming for a known K) is of order O(KT^2); Pelt solves the linearly penalized problem exactly with pruning and is of order O(T) under the assumption that regime lengths are randomly drawn from a uniform distribution; binary segmentation (greedy) is of order O(T log T).",
          "Section 5.1.2",
          "This results in a considerable speed-up: under the assumption that regime lengths are randomly drawn from a uniform distribution, the complexity of Pelt is of the order O(T)."),
         ("Penalty calibration: the linear (l0) penalty generalizes BIC and AIC; its smoothing parameter can be set by model-selection criteria that assume a model on the data, by heuristics such as cross-validation or the slope heuristics when no model is assumed, or by supervised procedures that minimize an approximation of the segmentation error on an annotated set of signals.",
          "Section 6.1",
          "In [138, 139], supervised algorithms are proposed: the chosen β is the one that minimizes an approximation of the segmentation error on an annotated set of signals."),
         ("The authors describe their own library ruptures (which implements most reviewed procedures) as the most comprehensive change point detection library.",
          "Section 9 (Conclusion)",
          "Most detection procedures described above are available within the Python language from the package ruptures [37], which is the most comprehensive change point detection library."),
     ],
     "notes": "Affiliations: CMLA, CNRS, ENS Paris Saclay; L2TI, University Paris 13. Venue from the given journal_ref ('Signal Processing, 167:107299, 2020') and the PDF first page ('Accepted to Signal Processing'). Conflict of interest: ruptures is the authors' own package (reference [37] is by Charles Truong); the review is linked to it. The review is a survey without an empirical benchmark of its own. Other Bayes-related content: the BIC penalty and the modified BIC (mBIC), which 'consists in maximizing the asymptotic posterior probability of the data' (Section 6.3); mBIC and penLeb are 'complex' penalties requiring optimal segmentations for K = 1..Kmax. Fused-lasso (l1) relaxation for the L2 cost is O(T log T). Cost functions reviewed: parametric (maximum likelihood, multiple linear / AR, Mahalanobis-type) and non-parametric (empirical cdf, rank-based, kernel-based). Section numbers are confirmed by numbered headings in the PDF."},

    {"id": "arxiv-2306.05265",
     "title": "Linking Frequentist and Bayesian Change-Point Methods",
     "authors": ["David Ardia", "Arnaud Dufays", "Carlos Ordas Criado"],
     "year": 2023, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2306.05265"},
     "tasks": ["change-point-detection"],
     "fam": ["bayesian-changepoint-models", "linear-models"],
     "proposes": ["A calibration of Normal Inverse-Gamma (g-prior type) hyperparameters under which the marginal likelihood of a piecewise-linear Gaussian regression change-point model equals the two-stage MDL criterion (up to a small remainder)",
                  "BSMDL, WBSMDL, GMDL and PGMDL: binary segmentation, wild binary segmentation, the Bai-Perron global method, and a pruned global method adapted to the MDL marginal likelihood; SEL selects among local methods by posterior probability",
                  "A full Bayesian model, conditional on the number of breaks found by a CP method, with a truncated binomial prior around the estimated breaks and an optional out-of-sample break prior, for credible intervals and forecasting"],
     "claims": [
         ("Main result: the MDL criterion corresponds to the marginal likelihood of a Bayesian model with a specific class of prior distributions, so that the marginal likelihood inherits the MDL criterion's asymptotic properties and can be used to detect CPs, assign posterior probabilities to competing CP methods, and select or combine them.",
          "Introduction",
          "Our paper addresses this gap by showing that the MDL criterion corresponds to the marginal likelihood of a Bayesian model with a specific class of prior distributions."),
         ("Background as framed by the authors: frequentist and Bayesian CP approaches have mostly evolved independently; frequentists mostly use SIC variants, sums of squared residuals or MDL, while Bayesians typically maximize the marginal likelihood; consistency of the estimated number and locations of breaks is rarely investigated in the Bayesian framework (citing Du et al., 2016 as an exception for a piecewise-constant model).",
          "Introduction",
          "most criteria used by frequentists consistently estimate the number and locations of the breaks, this is rarely investigated in the Bayesian framework."),
         ("Model assumptions: a piecewise-linear regression with m breaks, i.i.d. standard normal errors scaled by a segment variance, independent regimes in the marginal likelihood product, nonsingular X_i'X_i, and the number of breaks bounded by M. In a footnote the authors call the normality assumption restrictive while noting that several recent Bayesian and frequentist CP frameworks rely on it.",
          "Section 2",
          "several recent theoretical and empirical CP frameworks rely on the normality assumption"),
         ("Proposition 2: with NIG hyperparameters set per segment to the segment's OLS estimate as prior mean, M_i = X_i'X_i (a g-prior), and shape/scale scaled by sqrt(n_i), the log marginal likelihood equals MDL(m, tau) plus a remainder of order O(min_i(n_i)^-7); the hyperparameters therefore depend on the data of each segment.",
          "Section 2.3",
          "Proposition 2 formally establishes the link between a class of Bayesian CP models and the MDL criterion."),
         ("Consistency transfer: Davis et al. (2013) show MDL consistently estimates the number and locations of CPs, AR order and segment parameters for a broad class of piecewise-linear stationary AR processes; the authors state these properties also apply to the MDL marginal likelihood under Davis et al.'s regularity conditions and the Proposition 2 presets, extending Du et al. (2016) from piecewise-constant to piecewise-linear regression.",
          "Section 2.3",
          "These asymptotic properties also apply to the MDL marginal likelihood under the regularity conditions stated in Davis et al. (2013) and under the presets given in Proposition 2."),
         ("Decision rule: replacing the CUSUM statistic in binary and wild binary segmentation by the log ratio of MDL marginal likelihoods (break vs no break on an interval) gives the threshold a probabilistic meaning; a threshold of 0 means the break model has higher posterior probability, and a threshold of 3 is used (posterior probability in favour of a break greater than 95%).",
          "Section 3",
          "When δT > 3, the probability in favor of a break is greater than 95%."),
         ("Simulation protocol caveat: six AR DGPs from Yau and Zhao (2016), T = 1,024, 1,000 replications, scored by the proportion of correct numbers of breaks and an 'exact frequency' (correct number and every location within 50); BS and WBS use package defaults. All local methods except BS and WBS are given the true autoregressive lag orders (the MDL-based criteria need segment OLS estimates), whereas BS and WBS do not require a particular DGP.",
          "Section 4",
          "Note, however, that all local methods except BS and WBS detect the CPs assuming the true lag orders of the autoregressive processes."),
         ("Simulation result as stated by the authors: WBSMDL outperforms all methods in Table 2 (including the global GMDL) for both metrics in all DGPs, and the SEL method performs equally well as GMDL in this Monte Carlo exercise; BS and WBS show the worst overall performance.",
          "Section 4",
          "Notice that WBSMDL outperforms all methods investigated in Table 2 (including the global method GMDL) for both performance metrics in all investigated DGPs."),
         ("Computational cost: in the long-series experiment (DGP B, T up to 16,384, 100 replications), the slowest local algorithm takes about twelve minutes for the largest sample size, while the global GMDL takes more than eleven minutes at T = 4,096 and was too demanding for larger samples over 100 replications.",
          "Section 4",
          "It takes about twelve minutes on a standard computer for the slowest local algorithm to run for the largest sample size."),
     ],
     "notes": "Affiliations: HEC Montreal (GERAD), EDHEC Business School, Laval University. No venue: the PDF states only that preliminary versions were presented at R/Finance 2019, the Econometric Society & Bocconi Virtual World Congress 2020 and the EEA Virtual Congress 2020 (not recorded as venue); no arXiv comment. Section numbers are confirmed by the outline paragraph ('In Section 2 ... Section 7 concludes') and the cross-reference 'see Section 2.3'. The proposed MDL-based methods (BSMDL, WBSMDL, GMDL, PGMDL, SEL) are the authors' own adaptations compared against existing BS/WBS (wbsts package defaults) and LRSM; footnote 5 notes their LRSM results are more favorable than Yau and Zhao's because of estimator differences. Full Bayesian model (Section 5): conditions on the number of breaks from an existing CP method, uses a truncated binomial prior centred at the estimated CPs (an informative, data-derived prior), integrates out segment parameters and samples CPs with D-DREAM (Bauwens, Dufays and De Backer, 2014a, co-authored by A. Dufays); an optional geometric out-of-sample break prior follows Pesaran et al. (2006). The introduction argues Bayesian credible intervals for break locations do not overlap and remain in-sample. Applications: Fama-French five-factor model on daily bank-portfolio returns 1963-2022 (32 factor subsets x 11 local methods) and monthly U.S. CPI forecasting (expanding window, 817 out-of-sample points, model confidence set). Results tables not recorded."},

    {"id": "arxiv-2507.01558",
     "title": "A Bayesian framework for change-point detection with uncertainty quantification",
     "authors": ["Davis Berlind", "Lorenzo Cappello", "Oscar Hernan Madrid Padilla"],
     "year": 2025, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2507.01558",
               "code": "https://github.com/davis-berlind/MICH"},
     "tasks": ["change-point-detection"],
     "fam": ["bayesian-changepoint-models"],
     "proposes": ["Single change-point (SCP) Bayesian models for a change in the mean (multivariate), the variance, or both, with a categorical prior on the location, conjugate jump priors, a MAP location estimate and alpha-level credible sets",
                  "MICH (Multiple Independent CHange-point): stacks many SCP components and fits them by a deterministic backfitting algorithm equivalent to mean-field variational Bayes; detection rule |CS| <= log^(1+delta) T"],
     "claims": [
         ("Motivation: the authors state that Bayesian CPD methods remain an order of magnitude slower than state-of-the-art approaches, tend to lack theoretical development, and return joint posteriors without a clear way to summarize them as credible sets; in practice most only return the marginal posterior probability that each index is a change-point.",
          "Introduction",
          "In practice, the majority of BCPD methods simply return the marginal posterior probability that any given index t is a change-point."),
         ("Uncertainty output: for a single change-point model the posterior of the location tau is categorical with closed-form weights (conditionally conjugate priors); the point estimate is the posterior mode (MAP), and an alpha-level credible set is the smallest index set with posterior mass at least 1 - alpha, computed by adding indices in decreasing posterior probability (a knapsack problem).",
          "Section 2",
          "This is an example of a knapsack problem (Santini and Malaguti, 2024), which we solve by adding indices to"),
         ("Guarantees (single change-point only): for an independent sub-Gaussian sequence with one change in mean and/or variance, the MAP localization rate is minimax optimal up to a log T factor; for an alpha-mixing dependent sequence, up to a log^2 T factor; for d-dimensional mean changes with d >> log T and a dense mean signal, the location is recovered exactly.",
          "Abstract",
          "In the case of a single change in the mean and/or the variance of an independent sub-Gaussian sequence, we prove that our method attains a localization rate that is minimax optimal up to a log T factor."),
         ("Assumption on detectability (Assumption 1): minimum spacing of order at least log T and spacing times the scaled squared jump norm much larger than d log T; citing Wang et al. (2020), this is necessary for consistent localization when d = 1. In high dimensions it cannot be met for sparse jumps but is met for dense changes. Theorem 1 additionally requires a bounded location prior (max |log pi_t| <= C log T, satisfied by a uniform prior).",
          "Section 2.4",
          "making Assumption 1 a necessary condition for detection when only the mean of y1:T changes"),
         ("Detection rule: because the MAP is defined even without a change and posterior weights are diffuse under the null, a criterion is needed; the earlier rule |CS| <= T/2 (Cappello and Padilla, 2025) is described as somewhat ad hoc and liable to an inflated false positive rate. The proposed rule |CS| <= log^(1+delta) T gives a false negative rate converging to zero with high probability for independent data with fixed jumps (delta > 1 needed for dependent data), with fewer false positives than T/2.",
          "Section 2.5",
          "This rule is somewhat ad hoc and can lead to an inflated false positive rate in practice."),
         ("Approximation: Gibbs sampling over discrete, highly correlated change-point locations may mix poorly or fail to converge, so MICH is fitted by deterministic backfitting; under a mean-field factorization over components this is coordinate ascent on the ELBO and converges to a stationary point of the ELBO (a variational approximation, not the exact posterior). Because components are independent a priori, two components can sit on the same change (unlike product partition models); a merge step is proposed.",
          "Section 3",
          "Then Algorithm 1 is a coordinate ascent procedure that maximizes ELBO(q) on QMF, and q(n) converges to a stationary point of ELBO(q)."),
         ("Number of components: MICH needs upper bounds L, K, J on the numbers of mean, variance and joint changes; it is robust to overstating them (extra components get diffuse posteriors that fail the detection rule), but some prior knowledge is still needed not to underestimate them. The conservative default ceil(T/log T) raises the cost to O(T^2/log T); the ELBO is proposed to select L, K, J automatically.",
          "Section 3",
          "Some prior knowledge is still required to ensure we do not underestimate the true number of components."),
         ("Simulation protocol: joint mean-variance changes adapted from Pein et al. (2017), 5,000 replicates per setting with T in {100, 500, 1000}, minimum spacing in {15, 30, 50} and J* in {2, 5, 10}; MICH with non-informative priors (0.001), MICH-Auto (J by ELBO) and MICH-Ora (oracle J = J*), versus H-SMUCE, MOSUM, PELT, NOT and NSP. MICH is on par in estimating the number and locations of changes, but slightly lags PELT in average FNSLE, indicating it may miss some true changes even when J = J*.",
          "Section 4",
          "while MICH slightly lags behind PELT in terms of the average FNSLE"),
         ("Uncertainty quantification result: both MICH variants achieve the nominal 90% coverage (coverage conditional on detection) in each setting with credible sets smaller than those of H-SMUCE, MOSUM and NSP by a factor of 10-50; however, MICH's fitting time lags behind all other methods except NSP (a looser convergence tolerance brings it in line, per the appendix sensitivity analysis).",
          "Section 4",
          "Both MICH-Ora and MICH-Auto achieve the nominal coverage level of 90% in each setting, while at the same time returning credible sets that are smaller than those returned by H-SMUCE, MOSUM, and NSP by a factor of 10-50."),
     ],
     "notes": "Affiliations: UCLA Statistics & Data Science; Universitat Pompeu Fabra / Barcelona School of Economics. No venue: the PDF states none and there is no arXiv comment. Main text (pp. 1-19) read; appendices only for competitor software settings (Appendix D.2: H-SMUCE and PELT with package defaults, MOSUM alpha = 0.1, NSP with M = 1,000). Section numbers 2-6, 2.4 and 2.5 are confirmed by the outline and cross-references. Conflict of interest / own prior work: the var-scp component and the T/2 detection rule come from Cappello and Padilla (2025, PRISCA) and the ion-channel subsequence was previously analyzed by Cappello et al. (2021), both by co-authors; MICH reduces to PRISCA or to a CPD version of SuSiE (Wang et al., 2020) as special cases. Remark 8: each outer loop of Algorithm 1 is O(NT); the number of iterations is indeterminate. The authors state MICH 'requires virtually no hyperparameter tuning' outside L, K, J (defaults 0.001; sensitivity analysis in Appendix D.7.1, 'so long as these values are not too large'). Model asymmetry (activation via 1{t >= tau}) can inflate posterior mass near T; MICH is also fitted on the reversed series and the better-ELBO fit kept. Appendix D experiments with autocorrelation and heavy tails are described as 'somewhat robust'. Applications: ion channel gating (T = 2,956 after subsampling) and the Shankle well log (d = 6, T = 346, core-sample ground truth). The Discussion mentions online CPD only as a future direction. Results tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
