import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1305.5029",
     "title": "Divide and Conquer Kernel Ridge Regression: A Distributed Algorithm with Minimax Optimal Rates",
     "authors": ["Yuchen Zhang", "John C. Duchi", "Martin J. Wainwright"],
     "year": 2013, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1305.5029"},
     "tasks": ["tabular-regression"],
     "fam": ["divide-and-conquer", "kernel-methods"], "par": ["supervised"],
     "proposes": ["Fast-KRR: randomly partition N samples into m equal subsets, solve kernel ridge regression on each subset independently with a regularization parameter chosen as if all N samples were used, and average the m local estimates; with mean-squared-error bounds showing the minimax rate is retained when m is below a kernel-dependent threshold"],
     "claims": [
         ("Partition scheme: the data set is split uniformly at random into m equal-size subsets, an independent KRR estimator is computed on each subset, and the local solutions are averaged into a global predictor (divide = random partition, conquer = averaging; no learned or data-dependent partition).",
          "Abstract",
          "it randomly partitions a dataset of size N into m subsets of equal size, computes an independent kernel ridge regression estimator for each subset, then averages the local solutions into a global predictor."),
         ("Statistical guarantee (theory, with assumptions): the two main theorems state that, as long as the number of partitions m is not too large, the averaged estimator attains the statistical minimax rate over all estimators that use the N samples, despite the computational speed-up. The guarantee is conditional: Theorem 1 assumes f* in the RKHS with bounded conditional noise variance (Assumption B) and a moment bound on the kernel eigenfunctions (Assumption A; A' = uniform boundedness), and the rate-optimal corollaries additionally fix lambda (r/N, (1/N)^(2nu/(2nu+1)) or 1/N depending on eigendecay) and require m below an explicit threshold; Theorem 2 (f* not in H) allows a smaller m.",
          "Abstract",
          "Our two main theorems establish that despite the computational speed-up, statistical optimality is retained: as long as m is not too large, the partition-based estimator achieves the statistical minimax rate over all estimators using the set of N samples."),
         ("Allowed number of partitions depends on kernel eigendecay: the theory guarantees that m may grow nearly linearly in N for finite-rank and Gaussian kernels and polynomially in N for Sobolev spaces. These are the Corollary 1-3 thresholds, which hold under Assumption B and Assumption A (or A') with the corollary's specific lambda; under Assumption A the exponent depends on the number of eigenfunction moments k (the paper's summary says the thresholds grow with N when the basis functions have more than four moments).",
          "Abstract",
          "As concrete examples, our theory guarantees that the number of processors m may grow nearly linearly for ﬁnite-rank kernels and Gaussian kernels and polynomially in N for Sobolev spaces, which in turn allows for substantial reductions in computational cost."),
         ("What makes the averaging work: each sub-problem must be regularized as though it had all N samples, so locally it is under-regularized; this keeps each local bias small but blows up the variance, which the m-fold averaging then reduces enough to retain the optimal rate.",
          "Introduction",
          "Consequently, from a local point of view, each sub-problem is under-regularized."),
         ("Simulation check of the threshold (first-order Sobolev kernel, 1-D synthetic regression, f*(x)=min(x,1-x)): the error appears to begin increasing around log(m) of about 0.45 log(N) for reasonably large N, somewhat better than the m of order N^(1/3) threshold predicted by Corollary 2 (nu = 1); the authors read this as confirming that m can scale polynomially in N while retaining minimax optimality (an empirical check, not a proof of the empirical threshold).",
          "Simulation studies",
          "This empirical performance is somewhat better than the (1/3) thresholded predicted by Corollary 2, but it does conﬁrm that the number of partitions m can scale polynomially with N while retaining minimax optimality."),
         ("Real-data comparison (Million Song year prediction, Gaussian kernel): at a fixed training-time budget Fast-KRR gives the lowest test error among Fast-KRR, Nystrom subsampling and random features, but the authors state the margin over Nystrom sampling is not substantial (they add that Fast-KRR parallelizes trivially).",
          "Real data experiments",
          "As we see in Figure 3, for a ﬁxed time budget, Fast-KRR enjoys the best performance, though the margin between Fast-KRR and Nystr¨om sampling is not substantial."),
         ("Stated open problem: the guarantees use a specific choice of the regularization lambda, but the authors note the optimal lambda may not be known a priori in practice, and say it is unclear how to choose it adaptively (e.g. by cross-validation or unbiased risk estimation) in the distributed setting where each local estimate depends only on its own subset.",
          "Main results and their consequences",
          "Cross-validation or other types of unbiased risk estimation are natural choices, however, it is at this point unclear how to achieve such behavior in the distributed setting we study"),
     ],
     "notes": "Trade-off: with naive KRR the decomposition costs O(N^3/m^2) time and O(N^2/m^2) memory instead of O(N^3)/O(N^2) (Introduction); the estimates must still be communicated. Theorem 1 assumes f* in the RKHS; Theorem 2 (oracle inequality, f* not in H) only allows m growing as about sqrt(N/gamma^2(lambda)) rather than N/gamma^2(lambda), so the authors note that, at least in their current analysis, the more general case prevents finer partitions. Simulations: f*(x)=min(x,1-x) on [0,1], Gaussian noise, N from 2^8 to 2^13, m in {1,4,16,64}, 20 repetitions; an ablation without under-regularization (lambda chosen from the local n) shows a clear gap to m=1. Timing table: Matlab, single-threaded 3.4GHz, 16GB; m=1 fails (out of memory) from N=2^15. Million Song Dataset: 463,715 train / 51,630 test, 90 features, bandwidth sigma=6 chosen by cross-validation, lambda=1/N set from Corollary 3; Nystrom ranks 1000-6000, random features 2000-10000, m in {32,...,256}, 10 runs each. A sanity check shows averaging beats standard KRR on a 1/m fraction of the data. Discussion contrasts kernel-evaluation counts with Bach's Nystrom analysis and says the two scalings are currently not comparable. Task tag tabular-regression is used for the Million Song timbre-feature regression; the simulation study is 1-D synthetic. Results (figures/table values) not recorded."},

    {"id": "arxiv-1311.0914",
     "title": "A Divide-and-Conquer Solver for Kernel Support Vector Machines",
     "authors": ["Cho-Jui Hsieh", "Si Si", "Inderjit S. Dhillon"],
     "year": 2013, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1311.0914", "code": "http://www.cs.utexas.edu/~cjhsieh/dcsvm"},
     "tasks": ["tabular-classification", "image-classification"],
     "fam": ["divide-and-conquer", "kernel-methods"], "par": ["supervised"],
     "proposes": ["DC-SVM: partition the kernel SVM dual by (two-step) kernel k-means, solve the per-cluster subproblems independently, and use the concatenated solution to warm-start a global coordinate descent solver; multilevel version with adaptive clustering on support vectors and an early-prediction mode that predicts with the nearest cluster's model"],
     "claims": [
         ("Partition scheme and its justification: the paper shows that kernel k-means clustering minimizes the difference between the subproblem solution and the whole-problem solution, and that support vectors found in the subproblems are very likely to be support vectors of the whole problem.",
          "Introduction",
          "We theoretically show that the kernel kmeans algorithm is able to minimize the diﬀerence between the solution of subproblems and of the whole problem, and support vectors identiﬁed by subproblems are very likely to be support vectors of the whole problem."),
         ("Conquer step: the local subproblem solutions are not just combined but used to initialize a global coordinate descent solver on the full problem, which the analysis suggests converges quickly from that start.",
          "Abstract",
          "In the conquer step, the local solutions from the subproblems are used to initialize a global coordinate descent solver, which converges quickly as suggested by our analysis."),
         ("Exactness (top level only): the authors state that, unlike model-combination approaches such as BCM, DC-SVM solves the original SVM problem, not just an approximated one; this holds when the global coordinate descent is run at the top level on the whole problem, not for the DC-SVM (early) prediction mode, which uses the lower-level (approximate-kernel) models.",
          "Related Work",
          "More importantly, DC-SVM solves the original SVM problem, not just an approximated one."),
         ("Assumption behind the guarantee: the approximation bound (Theorem 1) depends on D(pi), the sum of absolute between-cluster kernel values, which is strongly related to the kernel parameters (for the RBF kernel, small gamma makes D(pi) larger and the subproblem solution may not be close to the optimum).",
          "Experimental Results",
          "As shown in Theorem 1 the quality of approximation depends on D(π), which is strongly related to the kernel parameters."),
         ("What is traded for speed in early prediction: DC-SVM (early) stops at a lower level and classifies a test point with the model trained on its nearest cluster only, i.e. it uses the block-diagonal approximate kernel instead of the exact SVM solution.",
          "Divide and Conquer SVM with multiple levels",
          "Therefore, the testing procedure for early prediction is: (1) ﬁnd the nearest cluster that x belongs to, and then (2) use the model trained by data within that cluster to compute the decision value."),
         ("Main empirical claim: DC-SVM reduces the SVM objective faster than state-of-the-art exact SVM solvers (relative error measured against LIBSVM run to 1e-8 accuracy); online and approximate solvers are excluded from this objective comparison because they do not solve the exact problem.",
          "Experimental Results",
          "We observe that DC-SVM achieves faster convergence in objective function compared with the state-of-the-art exact SVM solvers."),
         ("Protocol: C and the kernel parameter gamma are chosen by 5-fold cross-validation on a grid (2^-10..2^10 for most datasets; smaller gammas for the unscaled image datasets cifar and mnist8m).",
          "Experimental Results",
          "We chose the balancing parameter C and kernel parameter γ by 5-fold cross validation on a grid of points"),
     ],
     "notes": "Single-level cost: k equal subproblems take O(n^3/k^2) time and O(n^2/k^2) memory instead of O(n^3)/O(n^2). Theorem 1: 0 <= f(alpha_bar) - f(alpha*) <= (1/2) C^2 D(pi); Theorem 2 gives a sufficient condition under which a non-support vector of the subproblem is not a support vector of the whole problem; Theorem 3 refines the bound to the support-vector set. Kernel k-means is O(n^2 d), so a two-step kernel k-means on m=1000 sampled points is used (later levels sample from current support vectors). Multilevel: 5 levels with k=4 (1, 4, 16, 64, 256 clusters); DC-SVM (early) stops at 64 clusters. Hardware: Intel Xeon X5355 2.66GHz, 8GB RAM. Datasets: ijcnn1, cifar (animals vs non-animals), census, covtype, webspam, kddcup99, mnist8m (round vs non-round digits); random 80/20 splits for covtype/webspam/kddcup99. Baselines: LIBSVM (modified to drop the bias term), CascadeSVM, LaSVM (1 pass), SpSVM (200 basis vectors), LLSVM (rank 3000), FastFood (about 3000 Fourier features), LTPU (3000 clusters); stopping tolerance 1e-3 (LIBSVM default) for LIBSVM and DC-SVM; baselines' rank/feature counts are varied in Figure 3. A grid of 25 (C, gamma) settings per dataset (Tables 7-10, appendix) reports DC-SVM faster than LIBSVM on 96/100 settings. Polynomial-kernel experiments on covtype and webspam exclude LLSVM/FastFood/LTPU (developed for shift-invariant kernels). The paper criticises Cascade SVM for not identifying support vectors accurately (no kernel k-means; cannot correct false negatives from lower levels). Task tags: tabular-classification for the UCI/LIBSVM sets, image-classification for cifar/mnist8m binary tasks. Results not recorded."},

    {"id": "arxiv-1611.02401",
     "title": "Divide and Conquer Networks",
     "authors": ["Alex Nowak-Vila", "David Folqué", "Joan Bruna"],
     "year": 2016, "version": "arXiv v7",
     "links": {"arxiv": "https://arxiv.org/abs/1611.02401", "code": "https://github.com/alexnowakvila/DiCoNet"},
     "tasks": ["algorithm-learning", "combinatorial-optimization"],
     "fam": ["divide-and-conquer", "graph-neural-networks", "deep-learning"], "par": ["supervised", "reinforcement-learning"],
     "proposes": ["Divide-and-Conquer Networks (DiCoNet): a split network (set/graph neural network producing binary partition probabilities) applied recursively to build a partition tree, and a merge network (Pointer Network or GNN) applied fine-to-coarse to combine partial solutions; split trained by policy gradient, merge by backpropagation, with an optional computational-complexity regularizer"],
     "claims": [
         ("Both division and merging are learned: the architecture learns two scale-invariant operations, how to split an input into smaller sets and how to merge two partial solutions, each a single network applied recursively with shared parameters across scales.",
          "Abstract",
          "by learning two scale-invariant atomic operations: how to split a given input into smaller sets, and how to merge two partially solved tasks into a larger partial solution."),
         ("Training: because the split is discrete, its parameters are trained with policy gradient (REINFORCE), while the merge is trained by standard backpropagation; the model can learn from input-output pairs only or from a non-differentiable reward.",
          "Introduction",
          "Since our split block is inherently discrete, we resort to policy gradient to train the split parameters, while using standard backpropagation for the merge phase"),
         ("Heuristic, not exact: optimizing the cost over set partitions is described as intractable in general; if the cost is subadditive, the recursive splitting can be used as an efficient greedy strategy because the sum over the two halves is a surrogate upper bound that depends only on smaller sets (the paper presents this as a greedy surrogate, not as an optimality guarantee).",
          "Learning from non-differentiable rewards",
          "then the hierarchical splitting from (3) can be used as an efﬁcient greedy strategy, since the right hand side acts as a surrogate upper bound that depends only on smaller sets."),
         ("Size generalization protocol (knapsack): the model is trained on 20000 instances with n = 50 and evaluated on new instances with n = 50, 100 and 200 (uniform weights/values, capacity uniform in [0.2n, 0.3n]).",
          "Knapsack",
          "We generate 20000 problem instances of size n = 50 to train the model, and evaluate its performance on new instances of size n = 50, 100, 200."),
         ("Limitation: Dantzig's greedy algorithm eventually outperforms DiCoNet at n = 200, which the authors say suggests relaxing the scale-invariance assumption or adding task-specific prior knowledge.",
          "Knapsack",
          "However, we observe that the Dantzig greedy algorithm eventually outperforms the DiCoNet for sufﬁciently large input n = 200, suggesting that further improvements may come from relaxing the scale invariance assumption, or by incorporating extra prior knowledge of the task."),
         ("Comparison with prior learned knapsack work: the authors state their knapsack approach does not match Bello et al. (2016) in best approximation, while arguing it uses a simpler GNN with lower complexity and generalizes to larger n than trained on.",
          "Knapsack",
          "This approach of the knapsack problem does not perform as good as (Bello et al., 2016) in obtaining the best approximation."),
         ("TSP (appendix, preliminary): scale invariance is weaker for TSP since it is not straightforward to build a tour from two partial tours, but the authors observe some degree of it suffices to improve scalability when testing beyond the training size.",
          "Appendix C (Travelling Salesman Problem)",
          "Although the scale invariance of the TSP is not as clear as in the previous problems (it is not straightforward how to use two TSP partial solutions to build a larger one), we observe that some degree of scale invariance it is enough in order to improve on scalability."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2018. Tasks: planar convex hull (train sizes 6-50 in the unit square as in Vinyals et al. 2015; test n=25, 50, 100, 200; baseline Pointer Network; merge initialized from the trained baseline), k-means clustering (split only, GNN, reward = k-means cost; compared to Lloyd's and recursive binary Lloyd's on Gaussian mixtures and CIFAR-10 3x3x3 patches), 0-1 knapsack (GNN split filling a fraction alpha=0.5 of the capacity recursively; baselines: non-recursive GNN trained with REINFORCE, Dantzig greedy, optimum), and Euclidean TSP (appendix C: trained on n=20 with J=1, tested n=10-80; ground-truth tours from LKH (Helsgaun 2006); baseline = QAP-GNN of Nowak et al. 2017; beam search width 40). The abstract states the computational complexity can be used as a regularization term optimized by backpropagation (Appendix A); for convex hull the recursion depth is fixed by input size range rather than learned dynamically. The authors relate the convex-hull divide and conquer to its Theta(n log n) classical algorithm. Clustering: the non-recursive baseline beats DiCoNet when k is small (Table 2 caption). TSP results described as preliminary; future work mentions more splits and other NP-hard tasks. The extracted text also contains pages of an earlier version marked 'Under review as a conference paper at ICLR 2016'. Results not recorded."},

    {"id": "arxiv-2012.10658",
     "title": "Generalize a Small Pre-trained Model to Arbitrarily Large TSP Instances",
     "authors": ["Zhang-Hua Fu", "Kai-Bin Qiu", "Hongyuan Zha"],
     "year": 2020, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2012.10658", "code": "https://github.com/Spider-scnu/TSP"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["divide-and-conquer", "local-search", "graph-neural-networks", "deep-learning"], "par": ["supervised", "reinforcement-learning"],
     "proposes": ["Att-GCRN+MCTS: a small supervised graph convolutional residual network with attention (trained on fixed-size instances with Concorde labels) is applied to overlapping k-nearest-neighbour sub-graphs that are rescaled to the unit square; the sub heat maps are merged into an edge heat map that prunes edges and guides a Monte Carlo tree search over k-opt moves on complete tours"],
     "claims": [
         ("Proposal: train a small fixed-size model in a supervised way and reuse it repeatedly to build heat maps for TSP instances of arbitrary size via graph sampling, graph converting and heat-map merging, aimed at the lack of size generalization of supervised TSP models.",
          "Abstract",
          "this paper tries to train (in supervised manner) a small-scale model, which could be repetitively used to build heat maps for TSP instances of arbitrarily large size, based on a series of techniques such as graph sampling, graph converting and heat maps merging."),
         ("The division is not learned: sub-graphs of exactly m vertices are extracted by repeatedly taking the least-covered vertex as a centre and its k nearest neighbours (sub-graphs may overlap); only the sub heat-map predictor is learned, and merging uses a fixed formula over the sub-graphs containing each edge.",
          "Building and merging heat maps",
          "use the k-nearest neighbors algorithm [10] to extract a sub-graph G′ which consists of exactly m vertices (including the clustering center)."),
         ("Relation to local search: the search operates on complete tours, and every action is a k-opt move that deletes k edges and adds k new ones; 2-opt improvements are applied first, then MCTS samples larger k-opt moves guided by the heat map.",
          "Reinforcement learning for solutions optimization",
          "Since each TSP solution consists of a subset of n edges, any action could be viewed as a k-opt (2 ≤k ≤n) transformation, which deletes k edges at ﬁrst, and then adds k different edges to form a new tour."),
         ("Baseline protocol: learning-based baselines were not retrained; their public source code and pre-trained models were downloaded and rerun (some baselines' parameters such as beam width were adapted to prolong running time).",
          "Experiments",
          "Notice that, for the baselines, we just directly download and rerun the source codes, based on the pre-trained models (only for learning based baselines) which are publicly available."),
         ("Hardware asymmetry and scope: learning-based methods run on one GTX 1080 Ti GPU, while Concorde, Gurobi and LKH3 run on an 8-core CPU and are listed for indicative purposes only; the authors do not aim to strictly outperform the non-learning algorithms.",
          "Experiments",
          "Notice that our method is a learning based algorithm, thus we do not aim to strictly outperform the non-learning algorithms."),
         ("Main empirical claim: on instances with up to 10,000 vertices the approach is reported to clearly outperform existing machine-learning TSP algorithms and to significantly improve the trained model's generalization (the learning baselines were rerun from their public pre-trained models on the same GPU; the non-learning solvers Concorde, Gurobi and LKH3 are listed only as indicative CPU references).",
          "Abstract",
          "Experimental results based on a large number of instances (with up to 10,000 vertices) show that, this new approach clearly outperforms the existing machine learning based TSP algorithms, and signiﬁcantly improves the generalization ability of the trained model."),
         ("Copied baseline numbers: two MCTS-based TSP methods ([36] Shimomura and Takashima; [43] Xing and Tu) could not be rerun because their code is not publicly available; for [43] the authors compare against the average gaps that paper reports, evaluated on different platforms, and describe their method as roughly producing overall better results within reasonable time.",
          "Results on data set 2",
          "The source codes of these two papers are both not publicly available, thus we cannot evaluate them uniformly on the same platform to make strictly fair comparisons."),
     ],
     "notes": "PDF states: Copyright 2021, Association for the Advancement of Artificial Intelligence (AAAI). Training: 990,000 random instances of size m with Concorde solutions as labels; m=20 for data set 1 (10,000 instances each of n=20, 50, 100, a set widely used by prior learning work) and m=50 for data set 2 (128 instances each of n=200, 500, 1000 and 16 of n=10,000), all uniform in the unit square. Merge: P_ij averages the sub-graph probabilities over the O_ij sub-graphs containing edge (i,j); edges with P_ij < 1e-4 are eliminated. Hyperparameters omega=5, alpha=1, beta=10, H=10n set as defaults; time budget T=10n ms (set 1) and 40n ms (set 2), chosen so the method uses no more time than the best learning algorithm of each reference paper. Gaps are w.r.t. Concorde for n <= 1000 and w.r.t. LKH3 for n = 10,000, where Concorde, Gurobi and two GAT models exceeded the 5-hour limit and the three GCN models of Joshi et al. ran out of memory. No optimality guarantee is claimed: MCTS returns the best tour found when the time limit T elapses. The comparison with the MCTS method of Xing et al. [43] uses that paper's reported gaps on different platforms (code unavailable), which the authors acknowledge. The method avoids hand-crafted rules such as LKH's alpha-nearness and POPMUSIC to keep generality. End-to-end ML models without post-optimization were omitted as producing very poor results. Ablation (Table 4): giving every edge equal probability and running MCTS alone degrades performance drastically, with a huge gap to optimality on each data set. For data set 1 some learning baselines' parameters (e.g. beam-search width) were adapted to prolong their running time, marked in blue in Table 1. Paradigm tag reinforcement-learning follows the paper's description of MCTS as an RL method. Results not recorded."},

    {"id": "arxiv-1507.03133",
     "title": "Best Subset Selection via a Modern Optimization Lens",
     "authors": ["Dimitris Bertsimas", "Angela King", "Rahul Mazumder"],
     "year": 2015, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1507.03133"},
     "tasks": ["tabular-regression"],
     "fam": ["branch-and-bound", "linear-models"], "par": ["supervised"],
     "proposes": ["Best subset selection (cardinality-constrained least squares or least absolute deviation) solved as a mixed integer quadratic/linear program with Gurobi, warm-started by discrete first-order (projected-gradient/hard-thresholding) solutions and strengthened by data-driven bounds on coefficients"],
     "claims": [
         ("Method: discrete first-order methods produce high-quality feasible solutions that warm-start an MIO solver, which finds provably optimal solutions; the resulting algorithm gives a suboptimality guarantee even if stopped early and accommodates side constraints and LAD loss.",
          "Abstract",
          "We develop a discrete extension of modern ﬁrst order continuous optimization methods to ﬁnd high quality feasible solutions that we use as warm starts to a MIO solver that ﬁnds provably optimal solutions."),
         ("Guarantee vs heuristics: MIO solvers provide feasible solutions together with lower bounds on the optimal value, so the gap certifies suboptimality when stopped early; heuristic methods give no such certificate.",
          "Brief Background on MIO",
          "In contrast, heuristic methods do not provide such a certiﬁcate of suboptimality."),
         ("Finding vs proving optimality: for high-dimensional problems (n in {50, 100}, p in {1000, 2000}) the approach finds near-optimal solutions in minutes, with warm starts and problem-specific information, but takes hours to prove optimality.",
          "Introduction",
          "For high-dimensional problems with n ∈{50, 100} and p ∈{1000, 2000}, with the aid of warm starts and further problem-speciﬁc information, our approach ﬁnds near optimal solutions in minutes but takes hours to prove optimality."),
         ("Warm starts: on the Diabetes data (n = 350, p = 64), warm starts from the discrete first-order algorithm plus problem-specific bounds let the MIO close the optimality gap significantly faster than a cold start.",
          "Improving MIO Performance via Warm Starts",
          "The ﬁgure shows that in the presence of warm starts and problem speciﬁc side information, the MIO closes the optimality gap signiﬁcantly faster."),
         ("Solver settings: the authors observed 2-4x speedups from tuning the solver to a problem but used default solver parameters for generality, and say the reported times are not meant as best-possible benchmarks.",
          "MIO model training",
          "We observed that it was possible to obtain speedups of a factor of 2-4 by carefully tuning the optimization solver for a particular problem, but chose to maintain generality by solving with default parameters."),
         ("Comparison with Lasso / Sparsenet / stepwise (n > p regime, synthetic Example 1 with n = 500, p = 100, k0 = 10, averaged over ten random instances; each method's tuning parameter chosen on a held-out validation set): MIO performs best, followed by Sparsenet and Lasso, with stepwise regression worst, though Sparsenet marginally outperforms MIO in prediction error in a few instances. In this experiment the MIO for each k was stopped at a 1% optimality gap or a 15-minute time limit (MIO model training subsection), so the 'MIO' models are not necessarily certified optimal.",
          "Statistical Performance",
          "Among the methods, MIO performs the best, followed by Sparsenet, Lasso with Step(wise) exhibiting the worst performance."),
         ("Qualification in the high-dimensional regime (synthetic p >> n designs; competitors Lasso, Sparsenet and the discrete first-order method alone, models selected on validation sets): for Examples 2 and 3, MIO gives predictive models similar to Lasso but much sparser, and Lasso seems to perform marginally better than MIO as a predictive model for small SNR.",
          "The High-Dimensional Regime",
          "In fact, Lasso seems to perform marginally better than MIO, as a predictive model for small values of SNR."),
     ],
     "notes": "Software/hardware: Gurobi 5.5 (Matlab and Python interfaces); discrete first-order methods in Matlab; 8-core Xeon 1.8GHz 16GB for n > p, 16-core Xeon 3.1GHz 128GB for p >> n. Upper-bound experiments: 50 random initializations of Algorithm 2 vs MIO cold start vs MIO warm start, each with a 500-second limit; Leukemia data runs 4000 s per k. Sequence-of-k training stops at a 1% optimality gap or 15 minutes per k, using solver callbacks to add cardinality cuts. On Diabetes the optimum is found in seconds but certifying it takes 10-20 minutes (Figure 2 caption). In p >> n, lower bounds evolve slowly even with warm starts; a bounding-box formulation around a local solution certifies optimality only inside that box. The discrete first-order algorithm converges to a first-order stationary point (Proposition 6), not necessarily the global optimum. Introduction: the problem is NP-hard and leaps in R does not scale beyond p = 30; the authors relate prior leaps-and-bounds and tailored branch-and-bound work. Baselines: Lasso (glmnet), Sparsenet (MCP family), stepwise regression (R stats), debiased Lasso variants (appendix). The authors argue Lasso brings in many shrunken noise variables under correlation and noise. Branch-and-bound tag: the MIO solver (Gurobi) is used as the exact engine; the paper itself does not design a branching scheme. greedy-methods not tagged: stepwise regression is a baseline only. Results not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): algorithm design techniques (divide and conquer, dynamic programming, branch and bound, local search) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
