import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1904.12847",
     "title": "Optimal Sparse Decision Trees",
     "authors": ["Xiyang Hu", "Cynthia Rudin", "Margo Seltzer"],
     "year": 2019, "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/1904.12847", "code": "https://github.com/xiyanghu/OSDT"},
     "tasks": ["tabular-classification"],
     "fam": ["decision-trees", "interpretable-models"], "par": ["supervised"],
     "proposes": ["OSDT: branch-and-bound search for provably optimal sparse binary-split decision trees over binary features, minimizing misclassification error plus a per-leaf penalty, with analytical bounds and a bit-vector implementation"],
     "claims": [
         ("Critique of greedy induction: CART and C4.5 grow trees top-down without backtracking, so if a suboptimal split is introduced near the top the algorithm could spend many extra splits trying to undo it, leading to less accurate and less interpretable trees.",
          "Introduction",
          "CART and C4.5 grow decision trees from the top down without backtracking, which means that if a suboptimal split was introduced near the top of the tree, the algorithm could spend many extra splits trying to undo the mistake it made at the top, leading to less-accurate and less-interpretable trees."),
         ("Contribution: the paper presents what it calls the first practical algorithm for optimal decision trees, restricted to binary variables.",
          "Abstract",
          "This work introduces the first practical algorithm for optimal decision trees for binary variables."),
         ("Objective: optimal trees are defined by a regularized loss that trades off accuracy against the number of leaves (misclassification error plus lambda times the number of leaves), rather than a fixed tree topology.",
          "Introduction",
          "We find optimal trees according to a regularized loss function that balances accuracy and the number of leaves."),
         ("Optimization approach: the objective is minimized with branch and bound, using a series of specialized bounds that eliminate a large part of the search space (the hierarchical objective lower bound and the equivalent points bound adapted directly from CORELS, several others adapted from CORELS with minor changes; proofs in the supplement).",
          "Optimization Framework",
          "We minimize the objective function based on a branch-and-bound framework."),
         ("Protocol: OSDT is compared against CART and BinOCT on 7 datasets (5 UCI datasets plus ProPublica COMPAS and FICO); both BinOCT and OSDT get a 30-minute time limit.",
          "Experiments",
          "The time limits for both BinOCT and our algorithm are set to be 30 minutes."),
         ("Finding on baselines (training accuracy, Figure 1): with provably optimal trees as reference, the authors state that other methods are often close to optimal or optimal, though sometimes the baselines are not optimal.",
          "Experiments",
          "(i) We can now evaluate how close to optimal other methods are (and they are often close to optimal or optimal)."),
         ("Limitation (scalability): runtime can in theory grow exponentially with the number of features (the authors add that, empirically, extra features not in the optimal tree let the search prune faster).",
          "Experiments",
          "Runtime can theoretically grow exponentially with the number of features."),
     ],
     "notes": "PDF states: NeurIPS 2019. Datasets: Tic Tac Toe, Car Evaluation, Monk1, Monk2, Monk3 (UCI), ProPublica recidivism (N = 7,215) and FICO. OSDT is warm-started with the objective value of CART's solution, so the authors state its models can never be worse than CART's even when stopped early (Experiments). OSDT runs single-threaded while BinOCT uses eight threads (Experiments). Hardware: personal laptop (i5-8259U, 16GB RAM); ablation on AWS m5a.4xlarge single-threaded. Ablation (Appendix I): lookahead and equivalent points bounds are by far the most significant. Scalability experiment (Figure 3) duplicates the ProPublica data set to increase sample size. Appendix L: 10-fold cross-validation; the authors write that higher training accuracy at the same sparsity tends to yield higher test accuracy in general, but not always. Comparison to BinOCT: BinOCT is restricted to complete binary trees of a given depth and the authors show it producing useless splits. Formulation: binary classification over binary features (x_n in {0,1}^M); the paper does not discuss continuous features (the follow-up GOSDT, arxiv-2006.08690, targets continuous variables via threshold binarization). Family tag greedy-methods not used because OSDT itself is not greedy; CART is the greedy baseline. Results (accuracy figures) not recorded."},

    {"id": "arxiv-2006.08690",
     "title": "Generalized and Scalable Optimal Sparse Decision Trees",
     "authors": ["Jimmy Lin", "Chudi Zhong", "Diane Hu", "Cynthia Rudin", "Margo Seltzer"],
     "year": 2020, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2006.08690", "code": "https://github.com/Jimmy-Lin/GeneralizedOptimalSparseDecisionTrees"},
     "tasks": ["tabular-classification"],
     "fam": ["decision-trees", "interpretable-models"], "par": ["supervised"],
     "proposes": ["GOSDT: dynamic programming with bounds (DPB) for provably optimal sparse decision trees over many objectives (accuracy, balanced/weighted accuracy, F-score, AUC of the ROC convex hull, partial AUC), keyed by support-set bit vectors, with an incremental similar support bound that makes all-threshold encodings of continuous features tractable"],
     "claims": [
         ("Motivation: new optimal-tree techniques could allow sparse trees to be built for various objectives without the greedy splitting and pruning heuristics that, in the authors' words, often lead to suboptimal solutions.",
          "Abstract",
          "without relying on greedy splitting and pruning heuristics that often lead to suboptimal solutions."),
         ("Theory cited from prior work (Laurent & Rivest, 1976): full decision tree optimization is NP-hard with no polynomial-time approximation, which makes proving optimality or bounding the optimality gap hard even for small datasets.",
          "Introduction",
          "Full decision tree optimization is NP-hard, with no polynomial-time approximation (Laurent & Rivest, 1976), leading to challenges in proving optimality or bounding the optimality gap in a reasonable amount of time, even for small datasets."),
         ("Optimization approach: for additive loss functions GOSDT uses dynamic programming with bounds (DPB); non-additive losses use PyGOSDT, a variant closer to OSDT's branch and bound.",
          "GOSDT's DPB Algorithm",
          "For optimizing additive loss functions we use GOSDT which uses dynamic programming with bounds (DPB) to provides a dramatic run time improvement."),
         ("Critique of other optimal-tree methods: the 'bucketization' preprocessing used by DL8.5 and BinOCT to handle continuous variables is proven (by construction) to possibly lower the maximum attainable training accuracy.",
          "Section 3",
          "The maximum training accuracy for a decision tree on a dataset preprocessed with bucketization can be lower (worse) than the maximum accuracy for the same dataset without bucketization."),
         ("Baseline role of greedy CART: CART (scikit-learn, with depth and leaf count constrained to vary tree size) is run as a reference for what a greedy algorithm without optimality guarantee achieves.",
          "Appendix I",
          "We run CART as a reference point for what is achievable with a greedy algorithm that makes no optimality guarantee."),
         ("Protocol: a 5-minute time limit is used on all experiments unless otherwise stated (30 minutes for the rank-statistic experiments), and multi-threaded algorithms are run sequentially.",
          "Appendix I",
          "We set a 5-minute time limit on all experiments, unless otherwise stated."),
         ("Limitation (scalability): GOSDT is stated to be most effective for datasets with a small or medium number of features, while scaling well in the number of observations (tens of thousands).",
          "Discussion and Future Work",
          "GOSDT is most effective for datasets with a small or medium number of features."),
     ],
     "notes": "PDF states: Proceedings of the 37th International Conference on Machine Learning (ICML 2020), PMLR 119. Objective: loss plus lambda times number of leaves (Eq. 1). All features are binarized prior to running the algorithm; continuous features get one split point between every pair of adjacent unique values (Section 2 and Section 4.5). Datasets (Appendix I.1): monk1-3, tic-tac-toe, balance scale, car evaluation, iris (UCI), FourClass (LIBSVM), COMPAS (N = 5,020), FICO, coupon (bar-7). Accuracy-vs-sparsity experiment: 5-fold CV; runs over the 5-minute limit are discarded; CART/BinOCT/DL8.5 run with depth limits 1-6, OSDT/GOSDT with 29 regularization values; medians with 25th/75th percentiles. Appendix I.6 notes that if CART achieves an almost optimal training solution it tends to achieve high test accuracy as well, and that without methods like GOSDT/OSDT one could not tell whether CART is close to optimal. Scalability experiment (Appendix I.7): BinOCT never completed at max depth log2(32) within 5 minutes and was excluded. The paper notes BinOCT and DL8.5 use hard depth constraints whereas OSDT/GOSDT use soft (penalty) constraints. Early stopping returns an optimality gap (Discussion). Family tag greedy-methods not used because GOSDT itself is not greedy (it extracts the optimal tree from the dependency graph by greedily choosing the lowest-objective split after optimization). Results not recorded."},

    {"id": "arxiv-1904.09751",
     "title": "The Curious Case of Neural Text Degeneration",
     "authors": ["Ari Holtzman", "Jan Buys", "Li Du", "Maxwell Forbes", "Yejin Choi"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1904.09751", "code": "https://github.com/ari-holtzman/degen"},
     "tasks": ["language-modeling"],
     "fam": ["large-language-models", "greedy-methods", "deep-learning"],
     "proposes": ["Nucleus (top-p) Sampling: sample from the smallest set of tokens whose cumulative probability exceeds p, truncating the unreliable tail"],
     "claims": [
         ("Main observation (framed in the abstract as a counter-intuitive empirical observation): maximization-based decoding methods such as beam search lead to degeneration, i.e. output text that is bland, incoherent, or stuck in repetitive loops.",
          "Abstract",
          "maximization-based decoding methods such as beam search lead to degeneration — output text that is bland, incoherent, or gets stuck in repetitive loops."),
         ("Contribution: Nucleus Sampling, proposed as a simple method that draws considerably higher quality text from neural language models than previous decoding strategies.",
          "Abstract",
          "To address this we propose Nucleus Sampling, a simple but effective method to draw considerably higher quality text out of neural language models than previous decoding strategies."),
         ("Against a search-error explanation: asking whether beam search merely fails to find higher-probability, higher-quality text, the authors point to Figures 2 and 6, where the per-token probability of natural text is on average much lower than that of beam-search text; they conjecture that human text not being the most probable is an intrinsic property of human language.",
          "Natural Language Does Not Maximize Probability",
          "Yet Figures 2 & 6 show that the per-token probability of natural text is, on average, much lower than text generated by beam search."),
         ("Protocol: GPT-2 Large (762M parameters) generates 5,000 passages conditioned on WebText held-out paragraphs, each ending at an end-of-document token or 200 tokens; methods are compared against human text on perplexity, Zipf coefficient, Self-BLEU, repetition and HUSE.",
          "Experimental setup",
          "Our analysis is based on generating 5,000 text passages, which end upon reaching an end-of-document token or a maximum length of 200 tokens."),
         ("Repetition metric: a phrase of at least two tokens counts as a repetition when it repeats at least three times at the end of the generation (within the first 200 tokens).",
          "Distributional Statistical Evaluation",
          "A phrase (minimum length 2) is considered a repetition when it repeats at least three times at the end of the generation."),
         ("Link to greedy decoding: all stochastic methods show repetition issues when their parameters are set too low, which over-truncates and mimics greedy search.",
          "Distributional Statistical Evaluation",
          "Further, all stochastic methods face repetition issues when their tuning parameters are set too low, which tends to over-truncate, mimicking greedy search."),
         ("Caveat on beam width: beam search looks less repetitive on this metric as beam width grows largely because generations get shorter as the beam width increases.",
          "Distributional Statistical Evaluation",
          "Finally, although beam search becomes less repetitive according to this metric as beam width increases, this is largely because average length gets shorter as b increases (see Appendix A)."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2020. Affiliations: University of Washington, Allen Institute for Artificial Intelligence, University of Cape Town; acknowledgments include support from the Allen Institute for AI. Scope: the analysis is for open-ended generation; the paper notes directed generation (translation, summarization) usually uses beam search where repetition is less problematic, though similar issues were reported with large beams and exact inference (citing Koehn & Knowles 2017; Stahlberg & Byrne 2019). Figure 1: with b >= 64, GPT-2 Large and XL prefer to stop generating immediately after the context. Greedy decoding is one of the methods in Table 1. HUSE: 200 generations per decoding method, each with 20 annotations from 20 annotators; for top-k and Nucleus Sampling HUSE uses interpolation (mass 0.1) with the full distribution because truncation gives near-zero scores; KNN with k = 13. Self-BLEU uses 1000 sampled generations against the other 4999. The paper argues solving the problem by larger models or better architectures with standard per-word objectives is 'unlikely' (conjecture, Natural Language Does Not Maximize Probability). Paradigm tag omitted (no model training). Table 1 numbers not recorded."},

    {"id": "arxiv-1409.7938",
     "title": "Lazier Than Lazy Greedy",
     "authors": ["Baharan Mirzasoleiman", "Ashwinkumar Badanidiyuru", "Amin Karbasi", "Jan Vondrak", "Andreas Krause"],
     "year": 2014, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1409.7938"},
     "tasks": ["data-subset-selection"],
     "fam": ["greedy-methods"],
     "proposes": ["STOCHASTIC-GREEDY: at each of k steps, evaluate marginal gains only on a random sample of (n/k) log(1/epsilon) elements, giving (1-1/e-epsilon) in expectation with O(n log(1/epsilon)) function evaluations independent of k"],
     "claims": [
         ("Classical guarantee cited (Nemhauser, Wolsey and Fisher 1978): for maximizing a non-negative monotone submodular function under a cardinality constraint (|A| <= k), the simple greedy algorithm (add the element with largest marginal gain, k times; O(n k) evaluations) achieves a (1-1/e) approximation to the optimal (intractable) solution.",
          "Introduction",
          "states that for non-negative monotone submodular functions a simple greedy algorithm provides a solution with (1−1/e) approximation guarantee to the optimal (intractable) solution."),
         ("Prior accelerated greedy (LAZY-GREEDY, Minoux 1978): its exact cost in function evaluations is unknown, although it gives orders-of-magnitude speedups in practice.",
          "Introduction",
          "Even though the exact cost (i.e., number of function evaluations) of LAZY-GREEDY is unknown, this algorithm leads to orders of magnitude speedups in practice."),
         ("Guarantee of the proposed method (theoretical; for monotone submodular maximization under a cardinality constraint): the randomized STOCHASTIC-GREEDY achieves a (1-1/e-epsilon) approximation in expectation, in time linear in the data size and independent of the cardinality constraint.",
          "Abstract",
          "We show that our randomized algorithm, STOCHASTIC-GREEDY, can achieve a (1 −1/e −ε) approximation guarantee, in expectation, to the optimum solution in time linear in the size of the data and independent of the cardinality constraint."),
         ("Assumptions of the guarantee (Theorem 1): f non-negative, monotone and submodular, problem (1) with a cardinality constraint, and sample size s = (n/k) log(1/epsilon) per step; the bound is in expectation and uses O(n log(1/epsilon)) function evaluations.",
          "STOCHASTIC-GREEDY Algorithm",
          "Let f be a non-negative monotone submoduar function."),
         ("Cost measurement: computational cost is measured as the number of function evaluations, to be independent of implementation and platform; baselines are random selection, LAZY-GREEDY, SAMPLE-GREEDY (lazy greedy on a random subsample) and THRESHOLD-GREEDY.",
          "Experimental Results",
          "In order to compare the computational cost of different methods independently of the concrete implementation and platform, in our experiments we measure the computational cost in terms of the number of function evaluations used."),
         ("Data subset selection setting: active set selection for Gaussian Process regression (information gain, Informative Vector Machine) on the Parkinsons Telemonitoring dataset.",
          "Experimental Results",
          "We used the Parkinsons Telemonitoring dataset (Tsanas et al. 2010) consisting of 5,875 bio-medical voice measurements with 22 attributes from people with early-stage Parkinsons disease."),
         ("Empirical claim: STOCHASTIC-GREEDY practically reaches the same utility as lazy greedy while running much faster.",
          "Abstract",
          "We observe that STOCHASTIC-GREEDY practically achieves the same utility value as lazy greedy but runs much faster."),
     ],
     "notes": "PDF states: In Proc. Conference on Artificial Intelligence (AAAI), 2015. Affiliation: Ashwinkumar Badanidiyuru lists Google Research Mountain View (title page). Other experiments: exemplar-based clustering (k-medoid as a monotone submodular function) on 10,000 Tiny Images, and on 50,000 Tiny Images where LAZY-GREEDY and THRESHOLD-GREEDY could not be run (compared only with RANDOM-SELECTION / SAMPLE-GREEDY); sensor placement on the 12,527-node BWSN water network. Fixed k = 200 for the utility-vs-cost plots. Fairness: the authors implemented an accelerated (lazy) THRESHOLD-GREEDY not specified in the original paper and report its best results; SAMPLE-GREEDY's p was chosen so its cost roughly matches STOCHASTIC-GREEDY. Speedup is reported via function-evaluation counts (figures only), not wall-clock time. The guarantee is in expectation (randomized). STOCHASTIC-GREEDY is reused as a subroutine reference by CRAIG (arxiv-1906.01827, cited there as Mirzasoleiman et al. 2015a). Results not recorded."},

    {"id": "arxiv-1906.01827",
     "title": "Coresets for Data-efficient Training of Machine Learning Models",
     "authors": ["Baharan Mirzasoleiman", "Jeff Bilmes", "Jure Leskovec"],
     "year": 2019, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1906.01827", "code": "https://github.com/baharanm/craig"},
     "tasks": ["data-subset-selection", "tabular-classification", "image-classification"],
     "fam": ["greedy-methods", "linear-models", "deep-learning"], "par": ["supervised"],
     "proposes": ["CRAIG: select a weighted subset (coreset) whose weighted gradient approximates the full gradient by greedily maximizing a submodular facility-location function on (upper bounds of) gradient differences, then run incremental gradient methods on it"],
     "claims": [
         ("Contribution: CRAIG selects a weighted training subset (coreset) that closely estimates the full gradient, found by maximizing a submodular function.",
          "Abstract",
          "Here we develop CRAIG, a method to select a weighted subset (or coreset) of training data that closely estimates the full gradient by maximizing a submodular function."),
         ("Greedy guarantee (classical greedy results applied, not new theory): the subset problem is NP-hard; turned into a monotone submodular facility-location surrogate F, the budgeted version (|S| <= r) is approximated by greedy within (1-1/e) of the optimal F value, and the cover version gets a logarithmic approximation on subset size (Wolsey 1982). The approximation is for the surrogate (an upper bound on gradient-estimation error), not directly for the gradient error.",
          "CRAIG with Limited Budget",
          "For the above submodular maximization problem, the greedy algorithm discussed in Section 3.2 provides a (1 − 1/e)-approximation to the optimal solution."),
         ("Convergence guarantee and its assumptions: IG on the subset is proved to converge to a (near)optimal solution at the same rate as IG for convex optimization (Theorems 1-2 assume a strongly convex f and a subset whose weighted gradient is within epsilon of the full gradient over the parameter domain; Theorem 2 additionally assumes convex, twice-differentiable components with Lipschitz gradients; both leave an extra epsilon-dependent error term).",
          "Abstract",
          "We prove that applying IG to this subset is guaranteed to converge to the (near)optimal solution with the same convergence rate as that of IG for convex optimization."),
         ("Main empirical claim: while reaching practically the same solution, CRAIG speeds up various IG methods by up to 6x for logistic regression and 3x for deep neural networks.",
          "Abstract",
          "Our extensive set of experiments show that CRAIG, while achieving practically the same solution, speeds up various IG methods by up to 6x for logistic regression and 3x for training deep neural networks"),
         ("Speedup measurement: run time is wall-clock time for CRAIG's subset selection plus loss minimization with IG or other optimizers.",
          "Experiments",
          "In our experiments, we report the run-time as the wall-clock time for subset selection with CRAIG, plus minimizing the loss using IG or other optimizers with the specified learning rates."),
         ("Tuning: each method is tuned separately to perform at its best (for the convex experiments, learning rates for each method including the random baseline were tuned by preferring smaller training loss).",
          "Experiments",
          "We separately tune each method so that it performs at its best."),
         ("Limitation for deep networks: the gradient-difference bound depends on the changing parameters, so the subset must be reselected after a number of parameter updates rather than once as preprocessing.",
          "Application of CRAIG to Deep Networks",
          "Thus, we need to use CRAIG to update the subset S after a number of parameter updates."),
     ],
     "notes": "PDF states: Proceedings of the 37th International Conference on Machine Learning, Vienna, Austria, PMLR 119, 2020. Convex experiments: L2-regularized logistic regression with SGD, SVRG and SAGA on LIBSVM covtype.binary (581,012 points, 54 dims; random half split for test) and Ijcnn1 (49,990 train / 91,701 test, 22 dims); learning rates tuned by preferring smaller training loss over many combinations of exponential-decay and k-inverse schedules; lambda = 1e-5. Non-convex: 2-layer MLP on MNIST (CRAIG subset of 50% reselected each epoch) and ResNet-20 on CIFAR10 (subsets of 1%-20% reselected every epoch or every 5 epochs), average test accuracy across 10 trials. Baselines: random subsets of the same size and the full dataset. Subsets are selected per class keeping class ratios, because the gradient-difference bounds hold only for points with similar labels. A footnote notes that in the worst case the subset may need to be nearly the whole dataset, though in practice a small subset sufficed. The greedy step can be made O(|V|) with stochastic greedy (Mirzasoleiman et al. 2015a = arxiv-1409.7938) and lazy evaluation. Theorem 1/2 state the |V|/|S| speedup comes at the price of an extra error term (neighborhood 2eps R/mu^2 or 2eps/mu). Results not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): classical algorithms (sorting, binary search, greedy) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
