import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_gnn_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1810.00826",
     "title": "How Powerful are Graph Neural Networks?",
     "authors": ["Keyulu Xu", "Weihua Hu", "Jure Leskovec", "Stefanie Jegelka"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1810.00826", "code": "https://github.com/weihua916/powerful-gnns"},
     "tasks": ["graph-level-prediction", "representation-learning"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["A framework that abstracts neighbor aggregation as a function over the multiset of neighbor features and relates GNN discriminative power to the Weisfeiler-Lehman (WL) graph isomorphism test",
                  "Graph Isomorphism Network (GIN): h_v^(k) = MLP^(k)((1 + eps^(k)) * h_v^(k-1) + sum_{u in N(v)} h_u^(k-1)), with eps learnable (GIN-eps) or fixed to 0 (GIN-0), and a graph readout that concatenates sum (or other) readouts over all iterations"],
     "claims": [
         ("Upper bound (Lemma 2): if a GNN maps two non-isomorphic graphs to different embeddings, the WL test also decides they are not isomorphic; hence any aggregation-based GNN is at most as powerful as the WL test in distinguishing graphs. The WL test is described as a heuristic that works well in general with a few exceptions, e.g. regular graphs.",
          "Section 4",
          "Hence, any aggregation-based GNN is at most as powerful as the WL test in distinguishing different graphs."),
         ("Theorem 3: with a sufficient number of layers, a GNN maps any two graphs that the WL test decides are non-isomorphic to different embeddings if (a) it updates node features as h_v^(k) = phi(h_v^(k-1), f({h_u^(k-1) : u in N(v)})) with f (on multisets) and phi injective, and (b) its graph-level readout over the multiset of node features is injective.",
          "Section 4",
          "if the neighbor aggregation and graph-level readout functions are injective, then the resulting GNN is as powerful as the WL test."),
         ("Assumption of the analysis: input node features are taken from a countable set; the authors state that uncountable (continuous) node features need further considerations, which they leave for future work.",
          "Section 4",
          "Uncountable sets, where node features are continuous, need some further considerations."),
         ("GIN layer: Lemma 5 (extending Zaheer et al. (2017) from sets to multisets) states that sum aggregators can represent injective, indeed universal, multiset functions for countable inputs, whereas the mean aggregator, although an injective set function, is not an injective multiset function. Corollary 6 gives (1 + eps) f(c) + sum_{x in X} f(x) as injective for infinitely many eps (including all irrational numbers); f and phi are modeled with MLPs, giving h_v^(k) = MLP^(k)((1 + eps^(k)) h_v^(k-1) + sum_{u in N(v)} h_u^(k-1)) with eps learnable or fixed.",
          "Section 4.1",
          "Our next lemma states that sum aggregators can represent injective, in fact, universal functions over multisets."),
         ("Graph readout of GIN: because features from earlier iterations may sometimes generalize better, the graph representation concatenates READOUT over all iterations k = 0..K (similar to Jumping Knowledge Networks); with sum readout, GIN is stated to provably generalize the WL test and the WL subtree kernel.",
          "Section 4.2",
          "To consider all structural information, we use information from all depths/iterations of the model."),
         ("1-layer perceptrons are not sufficient: Lemma 7 shows there exist different finite multisets whose sums of ReLU(Wx) coincide for any linear map W (the proof relies on the missing bias term); the authors note that with a bias and large output dimension 1-layer perceptrons might distinguish multisets, but they are not universal approximators of multiset functions.",
          "Section 5.1",
          "Lemma 7 suggests that there are indeed network neighborhoods (multisets) that models with 1-layer perceptrons can never distinguish."),
         ("Mean and max-pooling aggregators (as in GCN and GraphSAGE) are permutation invariant but not injective: with identical node features, mean and max yield the same representation everywhere and capture no structural information, while sum distinguishes them; mean captures the distribution (proportions) of a multiset (Corollary 8) and max only the underlying set (Corollary 9), giving the ranking sum > mean > max.",
          "Section 5.2",
          "Mean and max-pooling aggregators are still well-deﬁned multiset functions because they are permutation invariant."),
         ("The authors suggest that the mean aggregator may perform well when distributional information matters more than exact structure, and that when node features are diverse and rarely repeat it is as powerful as sum; they say this may explain why mean-aggregation GNNs are effective for node classification tasks with rich node features.",
          "Section 5.3",
          "Moreover, when node features are diverse and rarely repeat, the mean aggregator is as powerful as the sum aggregator."),
         ("Evaluation protocol: 9 graph classification benchmarks (MUTAG, PTC, NCI1, PROTEINS, COLLAB, IMDB-BINARY, IMDB-MULTI, REDDIT-BINARY, REDDIT-MULTI5K), 10-fold cross-validation following Yanardag & Vishwanathan (2015) and Niepert et al. (2016); reported numbers are the mean and standard deviation of validation accuracies across the 10 folds, with hyperparameters (hidden units, batch size, dropout) and the single epoch with the best cross-validation accuracy averaged over folds selected per dataset; a separate validation set was avoided as 'extremely unstable' (MUTAG's would have only 18 data points).",
          "Section 7",
          "We report the average and standard deviation of validation accuracies across the 10 folds within the cross-validation."),
     ],
     "notes": "Venue from the PDF header on every page ('Published as a conference paper at ICLR 2019'); no arXiv comment/journal_ref. Section numbers confirmed by numbered headings in the PDF text (3, 4, 4.1, 4.2, 5, 5.1-5.5, 6, 7, 8). Other protocol details (Section 7): social network graphs have no node features, so REDDIT nodes get identical features and the other social graphs use one-hot degrees; 5 GNN layers, 2-layer MLPs, batch norm, Adam lr 0.01 halved every 50 epochs; sum readout on bioinformatics and mean readout on social datasets 'due to better test performance'; max-pooling not run on REDDIT-BINARY, REDDIT-MULTI5K and COLLAB due to GPU memory; deep-learning baselines and AWL accuracies are copied from their original papers; mean-1-layer and max-1-layer are said to correspond to GCN and GraphSAGE 'up to minor architecture modifications'. The paper reports that training accuracies of the GNNs never exceed those of the WL subtree kernel on their datasets (Section 7), and that GIN-0 slightly but consistently outperforms GIN-eps in test accuracy, which 'may be explained by its simplicity'. Conflict of interest: Leskovec is a co-author of GraphSAGE (Hamilton, Ying and Leskovec, 2017a), one of the variants shown to be less powerful, and the readout design follows the first author's Jumping Knowledge Networks (Xu et al., 2018); the authors evaluate their own proposed GIN. Test results are in Table 1 and training curves in Figure 4; not recorded."},

    {"id": "arxiv-1704.01212",
     "title": "Neural Message Passing for Quantum Chemistry",
     "authors": ["Justin Gilmer", "Samuel S. Schoenholz", "Patrick F. Riley", "Oriol Vinyals", "George E. Dahl"],
     "year": 2017, "venue": "ICML 2017", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1704.01212"},
     "tasks": ["graph-level-prediction"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["Message Passing Neural Networks (MPNNs): a common framework with message functions M_t, vertex update functions U_t (T message-passing steps, m_v^{t+1} = sum_{w in N(v)} M_t(h_v^t, h_w^t, e_vw), h_v^{t+1} = U_t(h_v^t, m_v^{t+1})) and a permutation-invariant readout R",
                  "MPNN variants for QM9: edge network message function A(e_vw) h_w, GRU update with weight tying, set2set readout, virtual edges / master node for long-range interactions, and 'towers' that split node embeddings into k copies to reduce cost"],
     "claims": [
         ("Framework: the forward pass has a message passing phase of T steps (messages summed over neighbors via message functions M_t, node states updated by vertex update functions U_t) and a readout phase computing a graph-level feature vector with a readout function R; M_t, U_t and R are learned differentiable functions, and R must be invariant to permutations of node states for the MPNN to be invariant to graph isomorphism.",
          "Section 2",
          "R operates on the set of node states and must be invariant to permutations of the node states in order for the MPNN to be invariant to graph isomorphism."),
         ("The authors reformulate at least eight existing models as MPNNs (including Duvenaud et al. 2015, GG-NN, Interaction Networks, Kearnes et al. 2016, DTNN, and Laplacian-based methods); for Kipf & Welling the message is c_vw h_w with c_vw = (deg(v) deg(w))^(-1/2) A_vw and the update is ReLU(W^t m_v^{t+1}).",
          "Section 2",
          "There are at least eight notable examples of models from the literature that we can describe using our Message Passing Neural Networks (MPNN) framework."),
         ("Critique of an existing MPNN: in Duvenaud et al. (2015) the message vector separately sums over connected nodes and connected edges, so the authors conclude that this message passing cannot identify correlations between edge states and node states.",
          "Section 2",
          "It follows that the message passing implemented in Duvenaud et al. (2015) is unable to identify correlations between edge states and node states."),
         ("Best variant: an edge network message function (a neural network maps the edge vector e_vw to a d x d matrix A(e_vw) applied to h_w), a set2set readout, and explicit hydrogen atoms as nodes; the authors found including the complete edge feature vector (bond type, spatial distance) and explicit hydrogens very important for a number of targets, and further improved test performance by ensembling the five models with lowest validation error.",
          "Section 8",
          "Our best MPNN variant used the edge network message function, set2set output, and operated on graphs with explicit hydrogens."),
         ("Long-range interactions: virtual edges between unconnected pairs and a latent master node connected to every node are introduced so information can travel long distances during propagation; without spatial information, the authors find that augmenting the MPNN with some means of capturing long-range interactions greatly improves performance, and they conclude that allowing long-range interactions via the master node or set2set output is important.",
          "Section 9",
          "Moreover, our results also reveal the importance of allowing long range interactions between nodes in the graph with either the master node or the set2set output."),
         ("Caveat on the no-spatial-information and towers experiments (Tables 3 and 4): they were run with a partial charge node feature that is an output of the DFT calculation and so could not be used in an applied setting; the state-of-the-art numbers in Table 2 do not use this feature.",
          "Section 8",
          "This feature is an output of the DFT calculation and thus could not be used in an applied setting."),
         ("Protocol: QM9 (130462 molecules, 13 regression targets); 10000 random molecules for validation, 10000 for test, the rest for training; each model/target combination tuned by uniform random hyperparameter search with 50 trials; the validation set is used for early stopping and model selection; targets normalized to mean 0 and variance 1, MSE minimized but MAE evaluated, and results reported as the ratio of MAE to the chemical-accuracy estimate of each target (from Faber et al. 2017). Unless stated otherwise, one model is trained per target.",
          "Section 7",
          "We use the validation set to do early stopping and model selection and we report scores on the test set."),
         ("Comparability caveat: the authors use the same train/validation/test split as the baseline study of Faber et al. (2017), but the DTNN numbers are taken as reported in Schütt et al. (2017), whose model was trained on a different split with 100k training samples versus 110k in this paper.",
          "Section 8",
          "The model was trained on a different train/test split with 100k training samples vs 110k used in our experiments."),
         ("Limitation and future work: the towers variant improves scalability but further improvements are needed for much larger graphs; the authors name generalization to graphs larger than those in training as an important direction, which 'seems particularly challenging' with spatial information because pairwise distance distributions and the number of incoming messages in fully connected graphs depend on the number of atoms.",
          "Section 9",
          "An important future direction is to design MPNNs that can generalize effectively to larger graphs than those appearing in the training set or at least work with benchmarks designed to expose issues with generalization across graph sizes."),
     ],
     "notes": "Venue from the PDF first-page footer ('Proceedings of the 34th International Conference on Machine Learning, Sydney, Australia, PMLR 70, 2017'); arXiv comment only says '14 pages'. Affiliations: Google Brain, Google, Google DeepMind. Section numbers from numbered headings in the PDF. Other findings stated in the text: training one model per target consistently outperformed joint training on all 13 targets ('In some cases the improvement was up to 40%'); a dense-graph message passing step costs O(n^2 d^2) and towers reduce it to O(n^2 d^2/k) with a reported 2x inference speedup for k = 8, n = 9, d = 200; the pair message function performed worse than the edge network (average error ratio 1.53 vs 3.98 when trained jointly). Conflict of interest: Riley is a co-author of the Kearnes et al. (2016) GC baseline, and Vinyals is first author of set2set (Vinyals et al., 2015) used in the readout. Results (Tables 2-4) are not recorded."},

    {"id": "arxiv-1801.07606",
     "title": "Deeper Insights into Graph Convolutional Networks for Semi-Supervised Learning",
     "authors": ["Qimai Li", "Zhichao Han", "Xiao-Ming Wu"],
     "year": 2018, "venue": "AAAI 2018", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1801.07606"},
     "tasks": ["graph-node-prediction"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["semi-supervised"],
     "proposes": ["Interpretation of the GCN graph convolution as symmetric Laplacian smoothing, and a convergence theorem showing that repeated Laplacian smoothing makes features within each connected component converge (over-smoothing)",
                  "Co-training a GCN with a partially absorbing random walk (ParWalks) model, GCN self-training, and their Union / Intersection combinations, which expand the label set and train without an extra validation set"],
     "claims": [
         ("GCN layer as described (citing Kipf & Welling 2017): the K-localized ChebNet filter is simplified by limiting K = 1 and approximating the largest eigenvalue of L_sym by 2, then the renormalization trick I + D^(-1/2) A D^(-1/2) -> D~^(-1/2) A~ D~^(-1/2) with A~ = A + I is applied, giving H^(l+1) = sigma(D~^(-1/2) A~ D~^(-1/2) H^(l) Theta^(l)); the semi-supervised model is a two-layer GCN with softmax output and cross-entropy over labeled vertices.",
          "Section 2",
          "In (Kipf and Welling 2017), Kipf and Welling simpliﬁed this model by limiting K = 1 and approximating the largest eigenvalue λmax of Lsym by 2."),
         ("Laplacian smoothing view: Laplacian smoothing (citing Taubin 1995) is y_i = (1 - gamma) x_i + gamma sum_j (a~_ij / d_i) x_j; with gamma = 1 and the symmetrically normalized Laplacian in place of D~^(-1) L~, it becomes exactly the GCN graph convolution D~^(-1/2) A~ D~^(-1/2) X, which the authors call symmetric Laplacian smoothing (still including the vertex's own features through the self-loop).",
          "Section 3",
          "We thus call the graph convolution a special form of Laplacian smoothing – symmetric Laplacian smoothing."),
         ("Why GCNs work: on Cora with 20 labels per class, the only difference between a GCN and a fully connected network is the graph convolution matrix, and even a one-layer GCN outperformed a one-layer FCN by a very large margin; the authors explain this by smoothing making features of densely connected same-cluster vertices similar, and attribute the further gain of a 2-layer GCN to applying smoothing again.",
          "Section 3",
          "Surprisingly, even a one-layer GCN outperformed a one-layer FCN by a very large margin."),
         ("When GCNs fail: more layers are 'certainly not the more the better' since a many-layer GCN is difficult to train and repeated Laplacian smoothing may mix features from different clusters; this is illustrated with untrained, randomly initialized GCNs of 1-5 layers on Zachary's karate club (34 vertices, 78 edges), where points become mixed after repeated smoothing (the authors note mixing happens quickly on this small dataset with many inter-class connections).",
          "Section 3",
          "On the other hand, repeatedly applying Laplacian smoothing may mix the features of vertices from different clusters and make them indistinguishable."),
         ("Theorem 1 (over-smoothing) and its assumptions: if a graph has no bipartite components, then for any w and alpha in (0, 1], (I - alpha L_rw)^m w and (I - alpha L_sym)^m w converge as m -> infinity to linear combinations of the connected-component indicator vectors and of D^(-1/2) times them, respectively; since the self-loops remove bipartite components, the authors conclude over-smoothing will make features indistinguishable and hurt accuracy. The theorem is stated for repeated application of the linear smoothing operator.",
          "Section 3",
          "Based on the above theorem, over-smoothing will make the features indistinguishable and hurt the classiﬁcation accuracy."),
         ("Shallow GCNs have the opposite limit: because the graph convolution is a localized filter, a shallow GCN cannot sufficiently propagate label information to the whole graph with few labels; in Fig. 1 GCN accuracy drops quickly as the training size shrinks and faster than label propagation, which the authors read as an inability to explore global graph structure.",
          "Section 3",
          "However, since the graph convolution is a localized ﬁlter – a linear combination of the feature vectors of adjacent neighbors, a shallow GCN cannot sufﬁciently propagate the label information to the entire graph with only a few labels."),
         ("Evaluation critique: the GCN of Kipf & Welling (2017) uses an additional 500 labeled vertices for early stopping, i.e. validation-set model selection, which is more than the total training labels; optimizing without validation causes a significant drop, and the authors argue this defeats the purpose of semi-supervised learning and makes comparisons with methods like label propagation unfair.",
          "Section 3",
          "Furthermore, it makes the comparison of GCNs with other methods unfair as other methods such as label propagation may not need the validation data at all."),
         ("Protocol: CiteSeer, Cora and PubMed (data from Yang et al. 2016 and Kipf & Welling 2017); GCN hyperparameters copied from Kipf & Welling (learning rate 0.01, 200 max epochs, dropout 0.5, L2 5e-4, 2 layers, 16 hidden units, validated on Cora by Kipf and Welling); each run randomly splits labels into a small training set and 1000 test samples; label rates 0.5-5% on Cora/CiteSeer and 0.03-0.3% on PubMed; mean accuracy of 50 runs except PubMed results from Yang et al., averaged over 10 runs. In the 20-labels-per-class comparison, other baselines' results are copied from Kipf & Welling.",
          "Section 5",
          "For each run, we randomly split labels into a small set for training, and a set with 1000 samples for testing."),
         ("Depth in the experiments: following Kipf and Welling, 2 convolutional layers were used, 2-layer GCNs performed best, and accuracy decreased drastically as layers grew, which the authors attribute (with 'probably') to overfitting rather than to over-smoothing.",
          "Section 5",
          "When the number of convolutional layers grows, the classiﬁcation accuracy decreases drastically, which is probably due to overﬁtting."),
     ],
     "notes": "Venue from the arXiv comment ('AAAI-2018 Oral Presentation'); the PDF itself has no venue header. Section numbers from numbered headings and the outline paragraph in the Introduction ('Section 2 introduces the preliminaries ... In Section 3, we analyze ...'). The proposed methods optimize on the expanded label set without any validation data and estimate a lower bound on the number of labels by solving (d^)^tau * eta ~ n (Section 4; 3*eta used, 2/3/4*eta reported to perform similarly). Conflict of interest: the co-training uses ParWalks (Wu et al. 2012) and its analysis (Wu, Li, and Chang 2013), prior work of the last author Xiao-Ming Wu; the LP baseline is also ParWalks-based. Results (Tables 1, 3-6, Fig. 1) are not recorded; improvement percentages in the text are not recorded either."},

    {"id": "arxiv-1905.10947",
     "title": "Graph Neural Networks Exponentially Lose Expressive Power for Node Classification",
     "authors": ["Kenta Oono", "Taiji Suzuki"],
     "year": 2019, "venue": "ICLR 2020", "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1905.10947", "code": "https://github.com/delta2323/gnn-asymptotics"},
     "tasks": ["graph-node-prediction"],
     "fam": ["graph-neural-networks", "deep-learning"],
     "proposes": ["Analysis of deep GCNs as a dynamical system X^(l+1) = MLP_l(P X^(l)) with ReLU, showing exponential approach to an invariant subspace M that carries only connected-component and degree information when s*lambda < 1",
                  "A weight-scaling guideline: keep the maximum singular value s of the weights away from the region s < lambda^-1 determined by the spectrum of the augmented normalized Laplacian"],
     "claims": [
         ("Setting: GCN layers are formulated as f_l(X) = sigma(P X W_l) with ReLU sigma and P = I - Delta~, where Delta~ is the augmented normalized Laplacian (citing Wu et al., 2019a) built from A~ = A + I and D~ = D + I; following Kipf & Welling one-layer MLPs are used, but the authors state the result holds for the multi-layer case. The GCN is considered without readout operations and the interest is the output as the number of layers L -> infinity.",
          "Section 4",
          "GCNs iteratively update signals on V using the connection information and weights."),
         ("Theorem 1 and its assumptions: for a symmetric P and an M-dimensional subspace U with (Assumption 1) an orthonormal basis of non-negative vectors and (Assumption 2) invariance under P, d_M(f_l(X)) <= s_l lambda d_M(X), where s_l is the product of maximum singular values of the layer's weights and lambda is the operator norm of P restricted to the orthogonal complement of U; the proof hinges on ReLU not increasing the distance to M, using the non-negativity of the basis vectors.",
          "Section 3.3",
          "We use the non-negativity of em to prove this claim."),
         ("Theorem 2 (GCN case): d_M(X^(l)) <= (s lambda)^l d_M(X^(0)), so it converges exponentially to 0 when s lambda < 1; within M, nodes in the same connected component with identical degrees have identical representations, so the authors interpret this as exponential information loss with depth; even with s >= 1 the loss can occur when s < lambda^-1, and the rate depends on the spectrum of the augmented normalized Laplacian.",
          "Section 4",
          "In this sense, M only has information about connected components and node degrees and we can interpret this theorem as the exponential information loss of GCNs in terms of the layer size."),
         ("The non-negativity assumption matters: in a 2-node synthetic one-step-transition experiment, choosing an eigenvector whose entries have different signs (violating Assumption 1) makes M not invariant and the transition does not uniformly decrease the distance to M.",
          "Section 6.1",
          "Therefore, we cannot remove the non-negativity assumption from Theorem 1."),
         ("Theorem 3 (Erdős-Rényi graphs G_{N,p} with log N/(Np) = o(1)): for any eps > 0, if the supremum s of maximum singular values is below a threshold s0 that grows with N and p, then for sufficiently large N the GCN satisfies the condition of Theorem 2 with probability at least 1 - eps; the authors stress the graph must not be extremely sparse, and conclude that for sufficiently large and not extremely sparse graphs most GCNs suffer the information loss.",
          "Section 5",
          "Theorem 3 requires that an underlying graph is not extremely sparse."),
         ("Applicability limit: the authors acknowledge that real-world graphs are often not dense, so Theorem 2 applies to very limited GCNs; citing Coja-Oghlan (2007), with bounded expected average degree the smallest positive normalized-Laplacian eigenvalue of G_{N,p} is o(1) with high probability, and the behavior on sparse graphs is left for future research.",
          "Section 7",
          "However, real-world graphs are not often dense, which means that Theorem 2 is applicable to very limited GCNs."),
         ("Real-data experiment design: the citation networks are too sparse for the theory to say anything non-trivial (for Cora only when 1 <= s < lambda^-1 ~ 1 + 3.62e-3), so the authors make 'noisy' versions by randomly adding edges, raising lambda^-1 to 1.11; they report that GCNs with s outside the region s < lambda^-1 outperform those inside it in almost all configurations, and conclude the results are consistent with the theorems.",
          "Section 6.3",
          "To circumvent this, we make noisy versions of citation networks by randomly adding edges to graphs."),
         ("Scope limitations: the analysis covers only ReLU activations (it uses ReLU as a projection onto the non-negative cone), so extending to sigmoid or Leaky ReLU is 'far from trivial'; it considers update operations only, not readout.",
          "Section 7",
          "In particular, we cannot directly apply our theory to graph classiﬁcation tasks in which each sample is a graph."),
         ("Residual connections: by the Markov-process analogy (residual links correspond to a lazy process) the authors imagine residual links might not help against over-smoothing, but citing Li et al. (2019), who reported graph NNs with as many as 56 layers performing well with residual connections, they say the situation could be more complicated than their intuitions and leave it for future research.",
          "Section 7",
          "However, Li et al. (2019) reported that graph NNs with as many as 56 layers performed well if they added residual connections."),
     ],
     "notes": "Venue from the arXiv comment ('Accepted in International Conference on Learning Representations (ICLR) 2020') and the PDF header ('Published as a conference paper at ICLR 2020'). Year is the first arXiv version (2019). Section numbers from numbered headings and cross-references in the PDF ('See Sections 3.3 (general case) and 4 (GCN case)', 'The discussion in Section 5', 'see Section 6.3'). The paper frames itself as extending over-smoothing explanations for linear GNNs (citing Li et al. 2018, i.e. arxiv-1801.07606, and others) to non-linear GNNs; Remark 2 gives a counterexample (Appendix C) to a theorem in an old preprint of Luan et al. (2019). The upper bound l*log(s*lambda) is reported to approximate actual distances when s*lambda is small but to be loose for large s*lambda (Section 6.2). Appendix H.3: noisy Cora/CiteSeer/PubMed built by uniformly adding 2500/5000, 5000 and 25000 edges; Kipf & Welling data split ('a transductive learning ... setting'); hyperparameters chosen by TPE via Optuna from 3 training runs per configuration, test accuracy averaged over 3 runs; weights rescaled at initialization so their maximum singular value equals s in {0.5, s1, 3, 10}. Discussion also conjectures that too-large weights may hurt generalization (a 'sweet spot' trade-off), stated as a conjecture. Affiliation/COI: the first author lists Preferred Networks, and the implementation uses Chainer Chemistry (footnote URL under github.com/pfnet-research) and Optuna; the paper does not benchmark these tools, so no direct conflict for the reported comparisons. Accuracies are figure-only (Figures 3, 4) and not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
