import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_unc_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2107.07511",
     "title": "A Gentle Introduction to Conformal Prediction and Distribution-Free Uncertainty Quantification",
     "authors": ["Anastasios N. Angelopoulos", "Stephen Bates"],
     "year": 2021, "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/2107.07511"},
     "tasks": ["uncertainty-estimation"],
     "fam": ["conformal-prediction"], "par": ["post-hoc"],
     "proposes": [],
     "claims": [
         ("Framing: given a fitted model and a small set of fresh i.i.d. calibration pairs unseen during training (e.g. about 500), split conformal prediction returns sets with 1 - alpha <= P(Y_test in C(X_test)) <= 1 - alpha + 1/(n+1); the authors call this marginal coverage because the probability is averaged over the randomness in the calibration and test points.",
          "Section 1 (Conformal Prediction)",
          "In words, the probability that the prediction set contains the correct label is almost exactly 1 −α; we call this property marginal coverage, since the probability is marginal (averaged) over the randomness in the calibration and test points."),
         ("Assumptions of the guarantee: Theorem 1 (attributed to Vovk, Gammerman and Saunders) assumes the calibration pairs and the test pair are i.i.d.; the appendix restates it and remarks that it also holds under the weaker condition of exchangeability. The proof given handles only the case of distinct scores (ties are referred to another work), and the upper bound needs a tie-breaking randomization that the authors say is usually ignored in practice.",
          "Appendix D",
          "As a technical remark, the theorem also holds if the observations to satisfy the weaker condition of exchangeability; see [1]."),
         ("The guarantee holds for any score function, but the usefulness of the sets depends on it: if the scores rank inputs by magnitude of model error, sets are smaller for easy inputs and bigger for hard ones; if the scores are random noise, the sets are a random sample of the label space just large enough for valid marginal coverage.",
          "Section 1 (Choice of score function)",
          "although the guarantee always holds, the usefulness of the prediction sets is primarily determined by the score function."),
         ("What is not guaranteed: conditional coverage P[Y_test in C(X_test) | X_test] >= 1 - alpha is stronger than the marginal coverage conformal prediction achieves and, citing Vovk [14], is impossible to achieve in the most general case, so procedures must be checked for how close they come. Example given: if sets always cover group A (90% of people) and never cover group B (10%), marginal coverage is 90% but conditional coverage fails.",
          "Section 3 (Evaluating Conformal Prediction)",
          "This is a stronger property than the marginal coverage property in (1) that conformal prediction is guaranteed to achieve—indeed, in the most general case, conditional coverage is impossible to achieve [14]."),
         ("Evaluation advice on set size and adaptivity: the procedure with the smallest average set size is not necessarily the best; sets should be small on easy and large on hard inputs, which the coverage guarantee does not imply. Suggested checks are set-size histograms, a feature-stratified coverage metric (minimum coverage over predefined groups) and a size-stratified coverage metric (minimum coverage over set-size bins), with the caveat that a good spread of set sizes does not by itself show that large sets occur for hard examples.",
          "Section 3 (Evaluating Conformal Prediction)",
          "It is extremely important to keep in mind that the conformal prediction procedure with the smallest average set size is not necessarily the best."),
         ("Calibration set size: the guarantee holds for any n, but coverage conditional on a fixed calibration set is random (Beta(n + 1 - l, l) with l = floor((n+1) alpha), citing Vovk); the authors' rough guideline is that about n = 1000 calibration points suffices for most purposes, and the n needed for coverage within 1 - alpha +/- epsilon with probability 1 - delta can be computed explicitly.",
          "Section 3.2",
          "Roughly speaking, our conclusion will that be choosing a calibration set of size n = 1000 is suﬃcient for most purposes."),
         ("Checking correct coverage: run the procedure over R random calibration/validation splits of the available data (caching scores), and check that the histogram of empirical coverages is centered near 1 - alpha; finite n, n_val and R cause benign fluctuations, and the authors note these evaluations are computationally intensive (at least 100 splits).",
          "Checking for Correct Coverage",
          "So, we compute the coverage values by randomly splitting the n + nval data points R times into calibration and validation datasets, then running conformal."),
         ("Cost of data splitting: split conformal prediction needs only one model fit but sacrifices statistical efficiency by splitting data into training and calibration sets; full conformal prediction avoids splitting at the cost of many more model fits, and cross-conformal and CV+/Jackknife+ lie in between.",
          "Section 6.2",
          "Split conformal prediction requires only one model ﬁtting step, but sacriﬁces statistical eﬃciency."),
         ("Distribution shift breaks the standard guarantee: Theorem 1 assumes test points come from the same distribution as the calibration points. Weighted conformal prediction handles covariate shift using the likelihood ratio dP_test/dP, which the authors describe as a somewhat restricted case (a known covariate shift).",
          "Conformal Prediction Under Covariate Shift",
          "All previous conformal methods rely on Theorem 1, which assumes that the incoming test points come from the same distribution as the calibration points."),
         ("Conformal score in the classification example: s_i = 1 - fhat(X_i)_{Y_i}, one minus the softmax output of the true class, which is high when the model is badly wrong.", "Section 1 (Conformal Prediction)", "The score is high when the softmax output of the true class is low, i.e., when the model is badly wrong."),
         ("Calibration quantile: qhat is the ceil((n+1)(1-alpha))/n empirical quantile of the calibration scores s_1, ..., s_n, i.e. essentially the 1 - alpha quantile with a small correction.", "Section 1 (Conformal Prediction)", "Next comes the critical step: deﬁne ˆq to be the ⌈(n+1)(1−α)⌉/n empirical quantile of s1, ..., sn, where ⌈·⌉is the ceiling function (ˆq is essentially the 1 −α quantile, but with a small correction)."),
         ("Prediction set: C(X_test) = {y : fhat(X_test)_y >= 1 - qhat}, the classes with a high enough softmax output; this procedure is guaranteed to satisfy the coverage property (1) regardless of the model or the (unknown) data distribution.", "Section 1 (Conformal Prediction)", "Remarkably, this algorithm gives prediction sets that are guaranteed to satisfy (1), no matter what (possibly incorrect) model is used or what the (unknown) distribution of the data is."),
     ],
     "notes": "Tutorial/survey; proposes no new method. No venue recorded: the PDF title page gives only the date (December 8, 2022), and 'Foundations and Trends' was not found in the text. Conflict of interest: the authors are authors of the RAPS paper (ref [4], arXiv 2009.14193) and cite it for the APS implementation details and for the size-stratified coverage metric ('introduced in [4]'); several other cited extensions (conformal risk control, Learn then Test) are also by the authors. The tutorial notes that the simple 1 - softmax score gives the smallest average set size (citing [6]) but tends to undercover hard subgroups and overcover easy ones, motivating APS; CQR (Section 2.2) is presented as often the best way to get intervals in regression, inheriting asymptotic near-conditional coverage from quantile regression. Under distribution drift, Theorem 4 (citing [26]) gives a coverage lower bound reduced by a TV-distance term. Section numbers used only where a heading or cross-reference in the PDF confirms them (Section 1, 2.2, 3, 3.2, 4.6, 6, 6.1, 6.2)."},

    {"id": "arxiv-1604.04173",
     "title": "Distribution-Free Predictive Inference For Regression",
     "authors": ["Jing Lei", "Max G'Sell", "Alessandro Rinaldo", "Ryan J. Tibshirani", "Larry Wasserman"],
     "year": 2016, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1604.04173"},
     "tasks": ["uncertainty-estimation", "tabular-regression"],
     "fam": ["conformal-prediction", "linear-models", "random-forests"], "par": ["supervised"],
     "proposes": ["A general framework for distribution-free predictive inference in regression with conformal inference, analysing full and split conformal prediction (and a jackknife method), with interval-length (accuracy) guarantees under stability or consistency assumptions",
                  "Extensions: rank-one-out (in-sample) split conformal inference, locally-weighted conformal bands for heteroskedastic data, and LOCO (leave-one-covariate-out) variable importance"],
     "claims": [
         ("Goal and setting: i.i.d. regression data (X_i, Y_i) with no assumptions on the regression function or P; the band must satisfy P(Y_{n+1} in C(X_{n+1})) >= 1 - alpha with the probability taken over the n + 1 i.i.d. draws, with finite-sample (nonasymptotic) validity.",
          "Introduction",
          "The main goal of this paper is to construct prediction bands as in (1) that have ﬁnite-sample (nonasymptotic) validity, without assumptions on P."),
         ("The naive interval from quantiles of the fitted (in-sample) residuals is only approximately valid for large samples under regularity conditions (e.g. a correctly specified model or appropriate tuning) and can grossly undercover because the fitted residual distribution is often biased downwards.",
          "Conformal Prediction Sets (Section 2)",
          "In general, the naive method (3) can grossly undercover since the ﬁtted residual distribution can often be biased downwards."),
         ("Theorem 2.1 (full conformal): with i.i.d. data, coverage is at least 1 - alpha; if the fitted absolute residuals have a continuous joint distribution, coverage is also at most 1 - alpha + 1/(n+1). The lower bound is a standard property due to Vovk; the upper bound is new, and a random tie-breaking rule could remove the continuity assumption. The estimator must be a symmetric function of the data points, and the i.i.d. assumption can be weakened to exchangeability.",
          "Section 2",
          "The ﬁrst part of the theorem, on the ﬁnite-sample validity of conformal intervals in regression, is a standard property of all conformal inference procedures and is due to Vovk."),
         ("Remark 2.3: the guarantees are marginal (average) coverage and must not be confused with conditional coverage given X_{n+1} = x, a much stronger property that, citing Lei & Wasserman (2014, an earlier paper by an overlapping author), cannot be achieved by finite-length prediction intervals without regularity and consistency assumptions on the model and the estimator; it holds asymptotically under certain conditions (Theorem 3.5).",
          "Section 2",
          "Conditional coverage does hold asymptotically under certain conditions; see Theorem 3.5 in Section 3."),
         ("Split conformal (Algorithm 2): randomly split the data into two equal halves, fit on one half and rank absolute residuals on the other; its computational cost is that of the fitting step. Theorem 2.2: with i.i.d. data coverage is at least 1 - alpha, and at most 1 - alpha + 2/(n+2) if the residuals have a continuous joint distribution.",
          "Section 2.2",
          "The split conformal method separates the ﬁtting and ranking steps using sample splitting, and its computational cost is simply that of the ﬁtting step."),
         ("Multiple splits: splitting introduces extra randomness; intersecting N split-conformal bands at level 1 - alpha/N keeps marginal coverage (Bonferroni), but Theorem 2.4 shows that under the paper's assumptions the band becomes wider with probability tending to 1, so the authors suggest using a single split.",
          "Multiple Splits",
          "Therefore, we suggest using a single split."),
         ("Simulations (Settings A-C, 50 repetitions, 90% nominal level): in the low-dimensional linear-regression comparison, full conformal intervals were shorter than split conformal intervals but at a higher computational cost; in the high-dimensional case (n = 500, d = 490) split conformal with linear regression had to be omitted because the regression is not well defined on half the sample.",
          "Section 4",
          "The full conformal interval is shorter than the split conformal interval, but comes at a higher computational cost."),
         ("Constant width: full and split conformal bands have roughly constant width over x (exactly constant for split conformal), which is undesirable when the residual spread varies with X. The locally-weighted extension divides residuals by an estimated conditional mean absolute deviation (fit on the first half for split conformal), and the validity properties carry over.",
          "Section 5.2",
          "In fact, for split conformal, the width is exactly constant over x."),
         ("Conclusion: the distribution-free coverage is marginal; conditional coverage may be above 1 - alpha at some x and below at others. The authors do not view this as a disadvantage, since accuracy of the band is tied to the base estimator: an accurate estimator gives a near-optimal band and a bad one still gives valid marginal coverage.",
          "Conclusion",
          "The distribution-free coverage oﬀered by conformal intervals is marginal."),
     ],
     "notes": "Affiliation: Department of Statistics, Carnegie Mellon University. No venue recorded: the PDF (dated March 9, 2017) states none; other papers cite it as JASA 2018, which is not confirmed by this PDF. Remark 2.7: an unbalanced split (rho > 0.5) may be beneficial for complex regression procedures, but the paper uses rho = 0.5 and does not pursue the choice. The jackknife (leave-one-out residuals) can give shorter intervals but has no finite-sample out-of-sample guarantee. Section 5.2 also notes that under homoskedastic noise the locally-weighted band will generally have inflated average length due to estimating the MAD. Interval-length accuracy results (Section 3) require stability or consistency assumptions (A0-A2 etc.), unlike coverage. Ridge tuning parameter lambda = 10 was used for all methods in Table 3. Section numbers confirmed by cross-references in the text (Section 2, 2.2, 3, 4, 5.2). Numerical tables not recorded."},

    {"id": "arxiv-1905.03222",
     "title": "Conformalized Quantile Regression",
     "authors": ["Yaniv Romano", "Evan Patterson", "Emmanuel J. Candès"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1905.03222"},
     "tasks": ["uncertainty-estimation", "tabular-regression"],
     "fam": ["conformal-prediction", "random-forests", "deep-learning", "linear-models"], "par": ["supervised"],
     "proposes": ["Conformalized quantile regression (CQR): fit lower and upper conditional quantile regressors on a proper training set, compute conformity scores E_i = max{q_lo(X_i) - Y_i, Y_i - q_hi(X_i)} on a calibration set, and widen (or shrink) the interval by their (1 - alpha)(1 + 1/|I2|)-th empirical quantile"],
     "claims": [
         ("Setting and guarantee: samples are assumed exchangeable (e.g. i.i.d.) from an arbitrary joint distribution; the target is marginal coverage P{Y_{n+1} in C(X_{n+1})} >= 1 - alpha with probability over all n + 1 samples. The training data are split into a proper training set and a calibration set, and the conformalized interval satisfies the guarantee regardless of the choice or accuracy of the quantile regression estimator.",
          "Introduction",
          "Unlike the original interval, the conformalized prediction interval is guaranteed to satisfy the coverage requirement (1) regardless of the choice or accuracy of the quantile regression estimator."),
         ("Plain quantile regression is adaptive to heteroscedasticity but is not guaranteed to cover in finite samples (validity only for specific models under regularity and asymptotic conditions); the authors state that the absence of a finite-sample guarantee can sometimes be disastrous and that their experiments show neural-network quantile intervals can substantially undercover.",
          "Section 2",
          "Indeed, the absence of any ﬁnite sample guarantee can sometimes be disastrous."),
         ("Limitation of standard split conformal regression: the interval length is fixed (twice the calibrated residual quantile) and independent of X_{n+1}; citing Lei et al., full conformal intervals also vary only slightly with X_{n+1} if the regression algorithm is moderately stable. Split conformal avoids the infinitely many refits of full conformal at the cost of splitting the data.",
          "Section 3",
          "A closer look at the prediction interval (8) reveals a major limitation of this procedure"),
         ("Theorem 1: if (X_i, Y_i), i = 1..n+1, are exchangeable, split CQR has coverage >= 1 - alpha; if the conformity scores are almost surely distinct, coverage is also <= 1 - alpha + 1/(|I2| + 1). The result holds even conditionally on the proper training set.",
          "Section 4",
          "The result even holds, and we will prove it, conditionally on the proper training set."),
         ("Hyperparameters of the underlying quantile regressor may be tuned by cross validation on the proper training set (minimizing average interval length); because quantile regression forests are often and quantile networks occasionally overly conservative, the nominal quantiles can be tuned as hyperparameters, which does not invalidate the coverage guarantee but may yield shorter intervals.",
          "Section 4",
          "Notably, this tuning does not invalidate the coverage guarantee, but it may yield shorter intervals, as our experiments conﬁrm."),
         ("Limitations of locally adaptive (scaled-residual) split conformal: when data are homoskedastic it inflates intervals (noted by Lei et al., presumably due to extra variability from estimating the scale); more fundamentally, the scale model is fit on proper-training residuals, which are biased by the fitting, so it tends to systematically underestimate prediction error, forcing a large correction and less adaptive intervals (severe for neural networks that nearly interpolate the training data).",
          "Section 5",
          "Because it uses the proper training residuals (as it must to ensure valid coverage), the locally adaptive method tends to systematically underestimate the prediction error."),
         ("Protocol: eleven regression benchmark datasets; features standardized and response rescaled using statistics from the proper training set only (to preserve exchangeability); 20 random 80/20 training-test splits; proper training and calibration sets of equal size; alpha = 0.1. Random forests use sklearn defaults except 1000 trees; network epochs are tuned by cross validation (upper limit 1000); gamma = 1 for the locally adaptive offset. Quantile forests' coverage parameters are tuned by cross validation.",
          "Section 6",
          "The proper training and calibration sets for split conformal prediction have equal size."),
         ("Results summary (Table 1, 2,200 experiments): on average CQR achieves shorter intervals than standard and locally adaptive conformal prediction; the authors call it possibly surprising that CQR also beats non-conformalized quantile regression (which uses more training data) and give possible explanations (signed scores mitigating overcoverage; tuning quantiles by cross validation, where CQR selects quantiles below nominal).",
          "Section 6",
          "On average, our method achieves shorter prediction intervals than both standard and locally adaptive conformal prediction."),
         ("All conformal methods reached the nominal 90% coverage; non-conformalized quantile forests were slightly conservative and quantile networks tended to undercover. Citing Tagasovska & Lopez-Paz, quantile-network coverage depends greatly on hyperparameter tuning, which the authors take as showing the importance of the finite-sample guarantee.",
          "Section 6",
          "Turning to the issue of valid coverage, all methods based on conformal prediction successfully construct prediction bands at the nominal coverage rate of 90%, as the theory suggests they should."),
     ],
     "notes": "Affiliation: Department of Statistics (and Mathematics), Stanford University. No venue recorded: the PDF footer says 'Preprint. Work in progress.' (other papers cite it as NeurIPS 2019, not confirmed by this PDF). Theorem 2 gives separate lower/upper tail control (coverage of each tail); the stated price is slightly longer intervals. CQR random forests were overly conservative on the two Facebook datasets, which the authors attribute to ties among conformity scores (the upper bound of Theorem 1 then does not apply). A two-output network shares parameters between quantiles to reduce cost; a quantile-crossing post-processing gave a slight improvement. A variant without data splitting is mentioned (footnote 2) but not studied. Section numbers confirmed by cross-references in the text (Sections 2-6). Numerical table values not recorded."},

    {"id": "arxiv-2009.14193",
     "title": "Uncertainty Sets for Image Classifiers using Conformal Prediction",
     "authors": ["Anastasios Angelopoulos", "Stephen Bates", "Jitendra Malik", "Michael I. Jordan"],
     "year": 2020, "venue": "ICLR 2021", "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/2009.14193"},
     "tasks": ["uncertainty-estimation", "image-classification"],
     "fam": ["conformal-prediction", "post-hoc-calibration", "deep-learning"], "par": ["post-hoc"],
     "proposes": ["Regularized Adaptive Prediction Sets (RAPS): add a penalty lambda * (rank - k_reg)_+ to the cumulative sorted (Platt-scaled) class probabilities of the APS score, then conformally calibrate the threshold on held-out data; APS is the special case lambda = 0",
                  "Size-stratified coverage violation (SSCV): the worst-case deviation from 1 - alpha of coverage stratified by prediction-set size, as a measure of adaptiveness / conditional-coverage violation"],
     "claims": [
         ("The coverage guarantee P(Y in C(X)) >= 1 - alpha is marginal over X and Y: it holds on average, not for a particular image.",
          "Introduction",
          "Note that the guarantee in Eq. (1) is marginal over X and Y —it holds on average, not for a particular image X."),
         ("Motivation: the naive approach (include classes by Platt-scaled softmax probability until the sum exceeds 1 - alpha) fails because CNN probabilities are known to be incorrect (citing Nixon et al., 2019), so the sets do not achieve coverage, and badly miscalibrated tail probabilities lead to large sets.",
          "Introduction",
          "There are two problems with naive: ﬁrst, the probabilities output by CNNs are known to be incorrect (Nixon et al., 2019), so the sets from naive do not achieve"),
         ("Theorem 1 (conformal calibration): assumes an i.i.d. calibration set not used for model training, nested set families that eventually contain all labels, and picks the smallest tau with empirical coverage >= ceil((n+1)(1-alpha))/n; it also holds under exchangeability, and a matching upper bound 1 - alpha + 1/(n+1) holds for most families (roughly, when sets grow smoothly in tau). The authors state the result is not new.",
          "Section 2.1",
          "The result is not new—a special case of this result leveraging sample-splitting ﬁrst appears in the regression setting in Papadopoulos et al. (2002), and the core idea of conformal prediction was introduced even earlier; see Vovk et al. (2005)."),
         ("Three desiderata: coverage, small set size, and adaptiveness (smaller sets for easy, larger for hard examples). Coverage and size compete, and size and adaptiveness are also often in tension; e.g. always predicting a set of size five could achieve coverage without being adaptive.",
          "Section 2 (Methods)",
          "Coverage and size are obviously competing objectives, but size and adaptiveness are also often in tension."),
         ("Why regularize: in their experiments APS sets are larger than necessary because APS is sensitive to noisy probability estimates far down the class list, where the ordering of unlikely classes is mostly random (a 'permutation problem'); RAPS regularization makes the algorithm avoid these unreliable tail probabilities.",
          "Section 2.3",
          "This noise leads to a permutation problem of unlikely classes, where ordering of the classes with small probability estimates is determined mostly by random chance."),
         ("Protocol: nine pretrained torchvision ImageNet classifiers; before naive, APS and RAPS, classifiers are temperature/Platt scaled on the calibration set; randomized versions of the algorithms are used; Imagenet-Val experiments use 100 trials with random calibration and evaluation subsets of 20K each, and RAPS parameters are chosen from data (Appendix E: k_reg and lambda picked on separate tuning data, m = 10000 for ImageNet and 1000 for ImageNet-V2, which the authors say does not invalidate the guarantee because calibration still uses fresh data).",
          "Section 3 (Experiments)",
          "Before applying naive, APS, or RAPS, we calibrated the classiﬁers using the standard temperature scaling/Platt scaling procedure as in Guo et al. (2017) on the calibration set."),
         ("ImageNet-V2 (5K calibration and evaluation sets): the authors state the method still provides coverage for models trained on a different distribution as long as the conformal calibration set comes from the new distribution; coverage variance is higher because of less data.",
          "Section 3.2",
          "The result shows that our method can still provide coverage even for models trained on different distributions, as long as the conformal calibration set comes from the new distribution."),
         ("Size vs adaptiveness trade-off: with large lambda, RAPS undercovers hard examples and must compensate with larger sets for easy examples to keep 1 - alpha marginal coverage; the size increase is described as slight because easy images are more common. If undesired, lambda can be chosen to optimize adaptiveness instead.",
          "Section 3 (Experiment 4: Adaptiveness of RAPS on Imagenet)",
          "Since RAPS with large λ undercovers hard examples, it must compensate by taking larger sets for easy examples to ensure the 1 −α marginal coverage guarantee."),
         ("Conditional coverage: distribution-free conditional coverage is impossible (citing Vovk 2012; Lei & Wasserman 2014). Stratifying coverage by set size shows APS overcovers large sets and undercovers easy ones, so it does not achieve exact conditional coverage. The authors argue that for high-signal problems exact conditional coverage requires a perfect classifier, so it is not the right goal at realistic sample sizes, and propose requiring coverage within every set-size stratum (measured by SSCV) instead.",
          "Section 4",
          "Therefore, conditional coverage isn’t the right goal for prediction sets with realistic sample sizes."),
     ],
     "notes": "Affiliation: UC Berkeley (EECS and Statistics); Angelopoulos and Bates contributed equally. Venue from the arXiv comment ('ICLR 2021 Spotlight'); the PDF text itself does not state the venue. APS is from Romano et al. (2020), not by these authors. Proposition 2: with lambda = 1 and k_reg <= k* (smallest top-k size covering on calibration data), RAPS sets are contained in the top-k* set. Proposition 1's upper bound requires all class probabilities > 0. Appendix B: randomization is needed for exact 1 - alpha coverage; turning it off gives slightly conservative sets. Appendix F compares to LAC (Least Ambiguous Set-valued Classifier; the citation is unresolved ('?') in the PDF): LAC has slightly smaller sets but worse adaptiveness. The automatic lambda for adaptiveness (Section 4.2) is chosen from a small grid minimizing SSCV on the tuning set. The same authors later wrote the conformal tutorial arXiv 2107.07511. Numerical table values not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
