import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_unc_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1904.01685",
     "title": "Measuring Calibration in Deep Learning",
     "authors": ["Jeremy Nixon", "Mike Dusenberry", "Ghassen Jerfel", "Timothy Nguyen", "Jeremiah Liu", "Linchuan Zhang", "Dustin Tran"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1904.01685"},
     "tasks": ["uncertainty-estimation", "image-classification"],
     "fam": ["post-hoc-calibration", "deep-learning"], "par": ["post-hoc", "supervised"],
     "proposes": ["Static Calibration Error (SCE): ECE extended to every class probability, binned separately per class and averaged over classes",
                  "Adaptive Calibration Error (ACE): class-wise calibration error with adaptive ranges that each contain an equal number of predictions (and a thresholded variant, TACE)",
                  "General Calibration Error (GCE): a space of 32 calibration metrics spanned by binning scheme (even/adaptive), maximum-probability-only or all probabilities, class conditionality, thresholding and L1/L2 norm"],
     "claims": [
         ("Main critique: the authors claim that ECE has numerous pathologies and that recent calibration methods shown to recalibrate models according to ECE cannot be properly evaluated via ECE.",
          "Introduction",
          "In this paper, we show that ECE has numerous pathologies, and that recent calibration methods, which have been shown to successfully recalibrate models according to ECE, cannot be properly evaluated via ECE."),
         ("ECE as framed by Naeini et al. (2015) leaves ambiguity in the binning implementation and in how to handle multiple classes; the paper's ECE implementation follows Guo et al. (2017): equally spaced bins on [0, 1] and only the maximum (predicted-class) probability per data point.",
          "Background & Related Work (Expected Calibration Error)",
          "ECE as framed in Naeini et al. (2015) leaves ambiguity in both its binning implementation and how to compute calibration for multiple classes."),
         ("Choosing the number of bins is a bias-variance tradeoff: more bins give a more granular (low-bias) measure but higher variance per bin as bins become sparsely populated; because of sharpness (confident predictions), some bins hold many more points than others, which compounds the problem.",
          "Issues With Calibration Metrics (Bias-Variance Tradeoff)",
          "Selecting the number of bins has a bias-variance tradeoff as it determines how many data points fall into each bin and therefore the quality of the estimate of calibration from that bin’s range."),
         ("Static binning allows cancellation: overconfident and underconfident predictions in the same bin can give near-zero calibration error. The authors hedge that these effects may not always be extreme enough to bring a very miscalibrated model to zero, but say it can be difficult to judge whether a measured improvement is real or due to cancellation (an appendix code example constructs a near-zero ECE for an extremely miscalibrated softmax).",
          "Issues With Calibration Metrics (Pathologies in Static Binning Schemes)",
          "Metrics that depend on static binning schemes like ECE suffer from issues where you can get near 0 calibration error due to overconﬁdent and underconﬁdent predictions overlapping in the same bin."),
         ("ECE focuses only on the maximum probability per data point; SCE extends it to every class probability (binned separately per class, then averaged over classes). The authors state that, unlike ECE, SCE is guaranteed to be zero if and only if the model is calibrated, under the assumption of infinite data and infinite bins.",
          "Analyzing The Space of Calibration with General Calibration Error (Maximum Probability)",
          "Unlike ECE, assuming inﬁnite data and inﬁnite bins, SCE is guaranteed to be zero if only if the model is calibrated."),
         ("Class conditionality: histogram binning optimizes directly for a notion of calibration error and is therefore measured overconfidently by a metric that matches its assumptions; on CIFAR-10 the ECE of histogram binning was one-third of the class-conditional ECE (and one-fifth on ImageNet, after controlling with the uncalibrated score). Histogram-binning probabilities come from average accuracy on the validation dataset.",
          "Experiments (Class Conditionality)",
          "We ﬁnd that on CIFAR 10 the ECE estimate of the calibration error is one-third that of the class conditional variant, which is the same as ECE in all respects but class conditionality (Table 1)."),
         ("Metric choice changes conclusions: ranking 8 recalibration techniques (histogram binning variants, isotonic regression, temperature scaling, ECE-optimized temperature scaling, vector/matrix scaling, neural network scaling) on CIFAR-10 predictions of a Wide ResNet with 32 metric variants gave dramatically different orderings.",
          "Recalibration Experiments",
          "This demonstrates that varying the properties of the calibration error metric can lead to different conclusions about which model has the best calibration."),
         ("Sensitivity to the number of bins (10, 20, 30, 40, 50) was measured by mean rank correlation over recalibration techniques on a Wide ResNet on CIFAR-10: adaptive-binning metrics had 0.5927 versus 0.3677 for even binning, which leads the authors to recommend adaptive binning; they also recommend class conditioning and the L2 norm.",
          "Experiments (Sensitivity to the Number of Bins Hyperparameter)",
          "This result leads us to recommend adapative binning as a method to improve rank order robustness to the number of bins hyperparameter."),
         ("Limitation acknowledged: adaptive metrics can create excessively large ranges where outputs are sparse; a very large number of ranges would recover granularity at the cost of interpretability and higher within-range variance.",
          "Discussion (Criticisms & Limitations)",
          "Adaptive calibration metrics can create excessively large ranges if there is very sparse output in a region."),
     ],
     "notes": "Affiliation: Google Brain / Google Research. The PDF first page says 'Preprint. Under review.'; no venue recorded (none stated in the PDF or the arXiv comment as given). Section headings in the PDF text carry no numbers, so locations use section names. Datasets: MNIST, Fashion-MNIST, CIFAR-10/100, ImageNet; temperature-scaling optimization for each metric used Nelder-Mead. The split on which the recalibrators were fit is only described for histogram binning ('validation dataset'); no fuller statement was found (searched for validation, held-out, hyperparameter). Table numbers not recorded."},

    {"id": "arxiv-1909.10155",
     "title": "Verified Uncertainty Calibration",
     "authors": ["Ananya Kumar", "Percy Liang", "Tengyu Ma"],
     "year": 2019, "venue": "NeurIPS 2019", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1909.10155"},
     "tasks": ["uncertainty-estimation", "image-classification"],
     "fam": ["post-hoc-calibration", "deep-learning"], "par": ["post-hoc", "supervised"],
     "proposes": ["Scaling-binning calibrator: fit a parametric scaling function on one split, build uniform-mass bins on a second split, and output the mean of the function values per bin estimated on a third split, so the calibration error is measurable with O(1/eps^2 + B) samples",
                  "Analysis showing the debiased (meteorological) estimator of squared calibration error needs samples proportional to sqrt(B) instead of B for the plugin estimator, for well-balanced binned models"],
     "claims": [
         ("Claim about scaling methods: Platt scaling and temperature scaling are less calibrated than reported, and it is difficult to tell how miscalibrated they are; the authors argue that, if f(X) is continuous, estimating E[Y | f(X)] (needed for the calibration error) is impossible without smoothness assumptions that cannot be verified in practice.",
          "Section 3 (Is Platt scaling calibrated?)",
          "In this section, we show that methods like Platt scaling and temperature scaling are (i) less calibrated than reported and (ii) it is difﬁcult to tell how miscalibrated they are."),
         ("Multiclass definitions: the paper distinguishes top-label calibration error (top prediction only) from marginal calibration error (each class, one-vs-all, weighted), and notes that prior multiclass methods were evaluated only on top-label calibration; citing other work, temperature scaling is worse than vector scaling on per-class metrics despite better top-label calibration.",
          "Section 2 (Setup and background)",
          "Prior works [9, 15, 17] propose methods for multiclass calibration but only measure top-label calibration"),
         ("Binned estimates can severely underestimate calibration error: for any binning scheme there is a distribution where the binned calibration error is 0 while the true error is at least 0.49 (Example 3.2); binning never increases calibration error (Proposition 3.3). Both hold for any lp calibration error including ECE.",
          "Section 3 (Is Platt scaling calibrated?)",
          "A simple example shows that using binning to estimate the calibration error can severely underestimate the true calibration error."),
         ("Experiment protocol (ImageNet, VGG16): the ImageNet validation set was split into three sets, used respectively to recalibrate with Platt scaling, to select an equal-mass binning scheme, and to measure the binned calibration error, with 1,000-bootstrap 90% intervals. Because binning lower-bounds calibration error, finer bins give a tighter bound; measured error grew with the number of bins (the authors say with 15 bins as in Guo et al. one would think it is around 0.02 when it is at least twice as high), and Appendix C reportedly extends this to ECE and other binning strategies.",
          "Section 3 (Experiments)",
          "We split the validation set into 3 sets of sizes (20000, 5000, 25000)."),
         ("Scaling-binning calibrator guarantee (Theorem 4.1): with n of order B log B + log B / eps^2 samples, its squared calibration error is at most twice the best squared calibration error in the scaling family G plus eps^2, with probability 1 - delta; this assumes regularity conditions on G and requires splitting the recalibration data into three sets (function fitting, uniform-mass bin construction, discretization). The uniform-mass binning is described as essential for estimating the calibration error.",
          "The scaling-binning calibrator",
          "Assume regularity conditions on G (ﬁnite parameters, injectivity, Lipschitz-continuity, consistency, twice differentiability).", 6),
         ("Cost of binning: binning worsens sharpness and can increase the mean-squared error; the authors show (Proposition D.4) that with many bins the MSE cannot increase by much, and list better binning schemes as future work.",
          "The scaling-binning calibrator (Analysis)",
          "While binning worsens the sharpness and can increase the mean-squared error of the model, in Proposition D.4 we show that if we use many bins, binning the outputs cannot increase the mean-squared error by much."),
         ("Verification: citing older meteorology work, the plugin estimator of squared calibration error is biased and a debiased estimator subtracts an approximate correction term; the authors' contribution is to show the plugin estimator needs samples proportional to B while the debiased one needs samples proportional to sqrt(B), for binned models with a 2-well-balanced binning scheme. A debiasing heuristic for the l1 error (ECE) is proposed in Appendix G without a proof.",
          "Section 5 (Verifying calibration)",
          "Older work in meteorology [18, 19] notices that this is a biased estimate, and proposes a debiased estimator that subtracts off an approximate correction term to reduce the bias."),
         ("CIFAR-10 recalibration protocol: from the 10,000-point validation set, a recalibration set of 1,000 points was sampled with replacement; each class was recalibrated separately with B bins per class (sigmoid as the scaling function), marginal calibration error was measured on the entire 10K set, and the procedure was repeated 100 times. The authors report 35% lower calibration error than histogram binning at 100 bins per class.",
          "The scaling-binning calibrator (Experiments)",
          "We sampled, with replacement, a recalibration set of 1,000 points.", 7),
         ("Open problem on dataset shift: with a small amount of labeled target data one can simply re-calibrate since only a few parameters are tuned, but the authors ask whether calibration can be maintained without labeled target examples.",
          "Conclusion",
          "However, can we maintain calibration when we do not have labeled examples from the target dataset?"),
     ],
     "notes": "Affiliation: Stanford University. Venue from the PDF first-page footer ('33rd Conference on Neural Information Processing Systems (NeurIPS 2019)') and the arXiv comment. Section numbers 2, 3 and 5 are confirmed by in-text cross-references; Section 4 is referred to by name. Debiased-estimator experiment: CIFAR-10 validation split into 3,000 (recalibrate/discretize VGG-16) and 7,000 (evaluation, resampled 1,000 times). ImageNet scaling-binning results are in Appendix E (5x lower top-label calibration error than histogram binning is stated in the text). Library: pypi 'uncertainty-calibration'."},

    {"id": "arxiv-2106.07998",
     "title": "Revisiting the Calibration of Modern Neural Networks",
     "authors": ["Matthias Minderer", "Josip Djolonga", "Rob Romijnders", "Frances Hubis", "Xiaohua Zhai", "Neil Houlsby", "Dustin Tran", "Mario Lucic"],
     "year": 2021, "venue": "NeurIPS 2021", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2106.07998"},
     "tasks": ["uncertainty-estimation", "image-classification", "selective-prediction"],
     "fam": ["deep-learning", "post-hoc-calibration"], "par": ["supervised", "post-hoc"],
     "proposes": ["A large-scale study relating calibration (top-label ECE, NLL, Brier) and accuracy of recent image classifiers (MLP-Mixer, ViT, BiT, ResNeXt-WSL, SimCLR, CLIP, AlexNet) in-distribution and under distribution shift, before and after temperature scaling"],
     "claims": [
         ("Revisiting Guo et al. (2017): several recent families (MLP-Mixer, ViT, BiT) are both highly accurate and well calibrated compared to AlexNet or the models studied by Guo et al., which the authors say suggests there may be no continuing trend for highly accurate modern networks to be poorly calibrated.",
          "In-Distribution Calibration",
          "This suggests that there may be no continuing trend for highly accurate modern neural networks to be poorly calibrated"),
         ("Recalibration protocol: 20% of the ImageNet validation set (randomly sampled) is reserved to fit the temperature-scaling parameter and all metrics are computed on the remaining 80%; for ImageNet-C, images derived from that 20% are excluded too. All models are trained or fine-tuned on ImageNet except CLIP (zero-shot). Out-of-distribution sets: ImageNetV2, ImageNet-C (synthetic corruptions), ImageNet-R, ImageNet-A.",
          "Experimental Setup",
          "For the post-hoc recalibration of models, we reserve 20% of the IMAGENET validation set (randomly sampled) for ﬁtting the temperature scaling parameter."),
         ("Metric: the paper focuses on top-label (argmax) calibration and estimates ECE with equal-mass binning and 100 bins throughout; Appendix E reportedly shows the results hold for other ECE variants and are consistent with Brier score and likelihood.",
          "Experimental Setup",
          "Throughout the paper, we estimate ECE using equal-mass binning and 100 bins."),
         ("Temperature scaling as a confounder remover: after temperature scaling, clearer separation between families and consistent within-family trends appear, and the BiT (ResNet) results become consistent with Guo et al.'s ResNets on ImageNet; models pretrained without labels (SimCLR) or with noisy labels (ResNeXt-WSL) tend to be worse calibrated for a given accuracy.",
          "In-Distribution Calibration",
          "Notably, temperature scaling reconciles our results for BiT (a ResNet architecture) with the results reported by Guo et al. for ResNets trained on IMAGENET."),
         ("Within most families larger models have somewhat higher in-distribution ECE but lower error (ResNeXt-WSL is an exception); model size and pretraining amount do not fully explain family differences. Because the best-calibrated families are non-convolutional, the authors speculate that architecture, in particular its spatial inductive bias, plays an important role; the conclusion adds that further work is needed to tell whether this generalizes.",
          "In-Distribution Calibration",
          "Given that the best-calibrated families (MLP-Mixer and ViT) are non-convolutional, we speculate that model architecture, and in particular its spatial inductive bias, play an important role."),
         ("Under distribution shift (ImageNet-C, synthetic corruptions at five severities), classification and calibration error generally increase, but calibration decays more slowly for MLP-Mixer and ViT; the in-distribution trend of larger models being worse calibrated reverses for most families out of distribution, especially after temperature scaling.",
          "Accuracy and Calibration Under Distribution Shift",
          "In other words, the calibration of larger models is more robust to distribution shift (Figure 5)."),
         ("ECE estimator pitfalls: binning bias is always negative (citing Kumar et al., 2019) and finite-sample per-bin bias is always positive and depends on accuracy, so the estimate can be too low or too high and model rankings depend on the ECE variant (citing Nixon et al., 2019); on BiT models, the sign of the ECE-vs-error relationship flipped with the number of bins. Mitigations: careful bin choice and considering accuracy and calibration jointly (Pareto-optimal models rarely change).",
          "Section 5 (Pitfalls and Limitations)",
          "It is therefore possible to arrive at opposite conclusions about the relationship between accuracy and calibration, depending on the chosen bin size (Figure 9), especially when comparing models with widely varying accuracies."),
         ("Selective-prediction cost scenario: comparing a more accurate and a better-calibrated BiT variant, the more accurate one had lower cost for abstention rates up to 70%, and likewise for the other families; the authors conclude a practitioner should choose the most accurate model for these families and this cost scenario, while noting real-world cost structures are complex and may yield different results.",
          "Relating Accuracy and Calibration Within Model Families",
          "For these families and this cost scenario, a practitioner should therefore always choose the most accurate available model regardless of differences in calibration."),
         ("Label smoothing: the authors argue it creates artificially underconfident models that may improve calibration for a specific amount of shift but not intrinsic calibration; after temperature scaling on a held-out part of the ImageNet validation set, training without label smoothing gave the lowest ECE across ImageNet-C severities, and the data suggest training without label smoothing and recalibrating post hoc.",
          "Appendix D (Model Confidence)",
          "These data suggest that, from a calibration perspective, models should be trained without label smoothing and then recalibrated by temperature scaling post hoc."),
     ],
     "notes": "Affiliation: Google Research, Brain Team. Venue from the PDF first-page footer ('35th Conference on Neural Information Processing Systems (NeurIPS 2021)') and the arXiv comment. Overlapping authorship (from the paper's own reference list): Minderer, Zhai and Houlsby are authors of ViT; Zhai and Houlsby of BiT; Houlsby, Zhai and Lucic of MLP-Mixer - the families found best calibrated. The paper states 'The authors declare no competing interests.' The Related Work paragraph describes temperature scaling as optimizing likelihood 'on a held-out portion of the training data', while the experiments fit it on 20% of the ImageNet validation set. Section 5 confirmed by in-text cross-references; other sections cited by name. 180 models from 16 families, 79 datasets, 28 metric variants (code and data released). Numbers from figures not recorded."},

    {"id": "arxiv-1910.12656",
     "title": "Beyond temperature scaling: Obtaining well-calibrated multiclass probabilities with Dirichlet calibration",
     "authors": ["Meelis Kull", "Miquel Perello-Nieto", "Markus Kängsepp", "Telmo Silva Filho", "Hao Song", "Peter Flach"],
     "year": 2019, "venue": "NeurIPS 2019", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1910.12656"},
     "tasks": ["uncertainty-estimation", "image-classification", "tabular-classification"],
     "fam": ["post-hoc-calibration", "deep-learning"], "par": ["post-hoc", "supervised"],
     "proposes": ["Dirichlet calibration: a natively multiclass calibration map derived from class-conditional Dirichlet likelihoods (generalizing beta calibration), implemented as log-transformed probabilities followed by a linear layer and softmax (multinomial logistic regression on log-probabilities)",
                  "ODIR (Off-Diagonal and Intercept Regularisation) for Dirichlet calibration and matrix scaling on deep nets",
                  "classwise-ECE and classwise-reliability diagrams for evaluating classwise calibration"],
     "claims": [
         ("Calibration notions: full multiclass calibration, classwise calibration (each one-vs-rest probability calibrated) and confidence calibration (only the top-class probability, as used by Guo et al.); the authors note that some authors use the weaker confidence calibration and that the multiclass setting has subtleties not always recognised.",
          "Introduction",
          "some authors use the weaker notion of conﬁdence calibration (our term), which requires only that the classiﬁer’s predicted probability for what it considers the most likely class is calibrated"),
         ("Temperature scaling (one parameter fit on a hold-out validation set) made a wide ResNet on CIFAR-10 nearly confidence-calibrated (the Vaicenavicius et al. test did not reject at alpha = 0.01), yet it systematically mis-estimated individual classes; with a single parameter it cannot act differently on different classes, motivating classwise-ECE.",
          "Section 2 (Evaluation of calibration and temperature scaling)",
          "Having only a single tuneable parameter, temperature scaling cannot learn to act differently on different classes."),
         ("Fundamental limitation of reliability diagrams and ECE measures: predicting the overall class distribution regardless of the instance gives almost perfect calibration, so other measures (error rate, proper losses such as Brier score or log-loss) should always be considered too.",
          "Section 2 (Evaluation of calibration and temperature scaling)",
          "Namely, it is easy to obtain almost perfectly calibrated probabilities by predicting the overall class distribution, regardless of the given instance."),
         ("Relationship to other families: for 2 classes Dirichlet calibration coincides with beta calibration; temperature-scaling maps are contained in the Dirichlet family; matrix scaling uses the same layer but on logits, and because softmax followed by log loses information, matrix scaling has an informational advantage on deep nets.",
          "Section 3 (Dirichlet calibration)",
          "As softmax followed by log-transform is losing information, matrix scaling has an informational advantage over Dirichlet calibration on deep neural networks, which we will turn back to in the experiments section."),
         ("Assumption: although derived from Dirichlet-distributed likelihoods, the method does not assume the probability vectors are actually Dirichlet-distributed within each class (analogous to Platt scaling and Gaussian likelihoods).",
          "Section 5 (Conclusion)",
          "While derived from Dirichlet-distributed likelihoods, it does not assume that the probability vectors are actually Dirichlet-distributed within each class"),
         ("Overfitting: responding to Guo et al.'s view that calibration models with many parameters overfit a small validation set, the authors agree some overfitting happens, but find L2 regularisation suffices on non-neural models and propose ODIR for deep nets; fitting minimises log-loss on validation instances plus ODIR terms whose weights are tuned by internal cross-validation on the validation data.",
          "Section 3 (Fitting and ODIR regularisation)",
          "We agree that some overﬁtting happens, but in our experiments a simple L2 regularisation sufﬁces on non-neural models"),
         ("Non-neural protocol: 21 UCI datasets x 11 classifiers; calibration maps trained with 3-fold internal cross-validation inside 5x5-fold external cross-validation, the 3 maps averaged as an ensemble; calibrator hyperparameters chosen on the classifier's training fold by lowest log-loss; 8 measures (including conf-ECE, cw-ECE and their significance-test variants) compared with Friedman and Bonferroni-Dunn tests. The authors note svc-linear and svc-rbf have an unfair advantage because sklearn applies Platt scaling internally.",
          "Section 4 (Calibration of non-neural models)",
          "We used 3-fold internal cross-validation to train the calibration maps within the 5 times 5-fold external cross-validation."),
         ("Deep-net protocol: 11 CNNs on CIFAR-10, CIFAR-100 and SVHN; following Guo et al., 5,000 training instances (6,000 for SVHN) were set aside for calibration, except for 3 pretrained models where 5,000 test instances were set aside; regularisation chosen by 5-fold cross-validation on the validation set and the 5 resulting calibrators averaged. Unregularised matrix scaling was excluded as reported to perform very poorly.",
          "Section 4 (Calibration of deep neural networks)",
          "On other models we followed [9], setting aside 5,000 training instances (6,000 in SVHN) for calibration purposes and training the models as in the original papers."),
         ("Deep-net results are hedged: the best general-purpose calibrator depends heavily on model and dataset; Dir-L2 is poor on CIFAR-100 while Dir-ODIR beats temperature scaling on cw-ECE at a minor log-loss cost; by average rank Dir-ODIR is best but without statistical significance. Logit-based MS-ODIR beat Dir-ODIR in most cases but the effect is numerically usually very small (under 1% average relative reduction).",
          "Section 4 (Calibration of deep neural networks)",
          "According to the average rank across all deep net experiments, Dir-ODIR is best, but without statistical signiﬁcance."),
     ],
     "notes": "Affiliations: University of Tartu, University of Bristol, Universidade Federal da Paraíba, The Alan Turing Institute. Venue from the PDF first-page footer ('33rd Conference on Neural Information Processing Systems (NeurIPS 2019)') and the arXiv comment. Conflict of interest: the OvR beta calibration baseline is the authors' own earlier method (Kull, Silva Filho, Flach 2017, reference [15]). Sections 2-5 are confirmed by the Introduction's outline; subsections are cited by name. Non-neural classifiers include logistic regression, naive Bayes, random forest, AdaBoost, LDA/QDA, decision tree, kNN, MLP and SVMs. The conclusion notes that on many deep nets Dirichlet calibration learns a map very close to the temperature-scaling family, and suggests it may be useful after dataset shift (not evaluated). Results tables not recorded."},

    {"id": "arxiv-1807.00263",
     "title": "Accurate Uncertainties for Deep Learning Using Calibrated Regression",
     "authors": ["Volodymyr Kuleshov", "Nathan Fenner", "Stefano Ermon"],
     "year": 2018, "venue": "ICML 2018", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1807.00263"},
     "tasks": ["uncertainty-estimation", "tabular-regression"],
     "fam": ["post-hoc-calibration", "bayesian-deep-learning", "deep-learning", "linear-models"], "par": ["post-hoc", "supervised"],
     "proposes": ["Recalibration of regression models (Algorithm 1): fit an auxiliary model R (e.g. isotonic regression) mapping predicted CDF values F_t(y_t) to their empirical frequencies, so that R composed with F_t is quantile-calibrated",
                  "Diagnostics for regression: a calibration plot of expected vs observed confidence levels, a calibration error score, and a sharpness score (mean predictive variance)"],
     "claims": [
         ("Motivation: Bayesian uncertainty estimates often fail to capture the true data distribution (e.g. a 90% credible interval not containing the outcome 90% of the time); the authors attribute this to model bias, i.e. a predictor not being expressive enough. The abstract also cites model misspecification and approximate inference.",
          "Section 1 (Introduction)",
          "This problem arises because of model bias: a predictor may not be sufﬁciently expressive to assign the right probability to every credible interval, just as it may not be able to always assign the right label to a datapoint."),
         ("Definition: a forecaster is calibrated if, over the dataset, the fraction of y_t below the predicted p-quantile converges to p for all p (sufficient condition under i.i.d. data: P(Y <= F_X^{-1}(p)) = p), which extends to any interval; related to Gneiting et al.'s probabilistic calibration.",
          "Section 3.1 (Calibration)",
          "In other words, the empirical and the predicted CDFs should match as the dataset size goes to inﬁnity."),
         ("Calibration is not sufficient: the unconditional forecast F(y) = P(Y <= y) is calibrated but ignores the features; forecasts must also be sharp (small predictive variance).",
          "Section 3.1 (Calibration and Sharpness)",
          "In order to be useful, forecasts must also be sharp."),
         ("Guarantee as stated: the procedure produces calibrated forecasts given enough i.i.d. data and applies to any regression model; the authors contrast this with existing methods (concrete dropout, deep ensembles) that require modifying the forecaster and may not be calibrated even with large data. No formal theorem or proof of this guarantee was found in the text (searched for theorem, proof, guarantee).",
          "Section 3.2",
          "This approach is simple, produces calibrated forecasts given enough i.i.d. data"),
         ("Protocol recommendation: as in classifier recalibration, R should be fit on a separate calibration set to reduce overfitting, or by K-fold training with hold-out folds as calibration sets and averaging the K models; isotonic regression is recommended because the target function is monotone and it is non-parametric.",
          "Section 3.2",
          "As in classiﬁer recalibration, it is advisable to ﬁt R on a separate calibration set in order to reduce overﬁtting."),
         ("Protocol actually used: in the experiments the recalibrator (isotonic regression) was fit on the same training set as the base model; the authors state they did not observe significant overfitting and did not use a distinct calibration set.",
          "Section 4.1 (Setup)",
          "We didn’t observe signiﬁcant overﬁtting and did not use a distinct calibration set."),
         ("Evaluation setup: eight UCI datasets (194 to 8192 examples), 25% random test split, averages over 5 random splits; models: Bayesian ridge regression and MC-dropout feedforward/recurrent networks; baselines: concrete dropout and a deep ensemble of 5 heteroscedastic networks; calibration error with unit weights. Also Make3D depth estimation, grocery sales forecasting, and a model-based RL inventory task.",
          "Section 4.1 (Setup)",
          "There is generally no standard train/test split, hence we randomly assign 25% of each dataset for testing, and use the rest for training."),
         ("Using only the distance from a point forecast as the feature yields calibrated forecasts even for a non-probabilistic regressor, but intervals then have the same width everywhere, making them less useful for identifying uncertain inputs; heteroscedastic features are suggested instead.",
          "Section 3.4 (Features for Recalibration)",
          "However, conﬁdence intervals will have the same width everywhere independently of x (e.g. Figure 4, left); this makes them less useful at identifying points x where the model is uncertain."),
         ("Limitations: recalibration preserves the accuracy of point estimates; a recalibrated quantile only becomes worse with insufficient recalibration data or distribution shift, and forecasts may become less sharp if the original model underestimated its uncertainty.",
          "Section 5 (Discussion)",
          "A recalibrated estimate of the median (or any other quantile) only becomes worse if there is insufﬁcient data for recalibration, or there is a shift in the data distribution."),
     ],
     "notes": "Affiliations: Stanford University and Afresh Technologies. Venue from the PDF first page ('Proceedings of the 35th International Conference on Machine Learning, Stockholm, Sweden, PMLR 80, 2018') and the arXiv comment. The calibration error score averages squared gaps over m confidence levels (w_j = 1); the paper notes in Section 3.5 that for best results the diagnostic dataset should be distinct from the calibration and training sets. The calibration definition is a frequency over all data points; no discussion of calibration conditional on x was found in the text (searched for conditional). Uses MC dropout (Gal and Ghahramani) for uncalibrated Bayesian forecasts. Results tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
