import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tabdl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1908.07442",
     "title": "TabNet: Attentive Interpretable Tabular Learning",
     "authors": ["Sercan O. Arik", "Tomas Pfister"],
     "year": 2019, "venue": "AAAI 2021", "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/1908.07442"},
     "tasks": ["tabular-classification", "tabular-regression", "representation-learning"],
     "fam": ["tabular-attention", "deep-learning"], "par": ["supervised", "self-supervised"],
     "proposes": ["TabNet: a sequential multi-step encoder in which, at each decision step, an attentive transformer produces an instance-wise sparse feature mask (sparsemax over prior-scaled features) that multiplies the input features; a feature transformer (shared and step-dependent FC-BN-GLU layers) processes the selected features, and ReLU outputs of all steps are summed into the decision",
                  "Aggregate feature-importance masks obtained by weighting each step's mask by that step's decision contribution",
                  "Self-supervised pre-training by predicting randomly masked feature columns from the others with a TabNet decoder"],
     "claims": [
         ("Motivation and design: TabNet uses sequential attention to choose which features to reason from at each decision step; the authors state this enables interpretability and more efficient learning because learning capacity is used for the most salient features.",
          "Abstract",
          "TabNet uses sequential attention to choose which features to reason from at each decision step, enabling interpretability and more efﬁcient learning as the learning capacity is used for the most salient features."),
         ("Feature selection mechanism: a learnable multiplicative mask is computed by an attentive transformer from the previous step's processed features and normalized with sparsemax (citing Martins and Astudillo 2016), which the authors say was observed to be superior in performance and aligned with sparse feature selection for explainability; a prior scale with relaxation parameter gamma controls how often a feature can be reused across steps, and an entropy-form sparsity regularizer is added to the loss.",
          "TabNet for Tabular Learning",
          "Sparsemax normalization (Martins and Astudillo 2016) encourages sparsity by mapping the Euclidean projection onto the probabilistic simplex, which is observed to be superior in performance and aligned with the goal of sparse feature selection for explainability."),
         ("Input handling: raw numerical features are used, categorical features are mapped with trainable embeddings, and no global feature normalization is applied (only batch normalization); in the experiments categorical inputs are mapped to a single-dimensional trainable scalar and numerical columns are input without preprocessing.",
          "TabNet for Tabular Learning",
          "We do not consider any global feature normalization, but merely apply batch normalization (BN)."),
         ("Interpretability argument: if a mask entry is 0 the feature should have no contribution at that step; masks are interpretable as feature importance only in an approximate sense, since the coefficient would correspond to feature importance if the step function were linear, while steps are non-linear but their outputs are combined linearly. Step masks are aggregated by weighting each step with its summed ReLU decision output.",
          "TabNet for Tabular Learning (Interpretability)",
          "Although each decision step employs non-linear processing, their outputs are combined later in a linear way."),
         ("Evidence for interpretability: on synthetic data the aggregate masks focus on the relevant features (the visualized models were trained with 10M rather than 10K samples to get sharper masks); on Mushroom, TabNet assigns 43% importance to 'Odor' while LIME, Integrated Gradients and DeepLift assign less than 30% (the latter figures cited from Ibrahim et al. 2019); on Adult the rankings are described as consistent with well-known methods.",
          "Interpretability",
          "TabNet assigns an importance score ratio of 43% for it, while other methods like LIME (Ribeiro, Singh, and Guestrin 2016), Integrated Gradients (Sundararajan, Taly, and Yan 2017) and DeepLift (Shrikumar, Greenside, and Kundaje 2017) assign less than 30% (Ibrahim et al. 2019)."),
         ("Evaluation protocol as stated in the appendix: for all the comparison models a hyperparameter tuning with the same number of search steps is run (per-dataset sources of baseline numbers and settings are listed in notes).",
          "Appendix (Experiment hyperparameters)",
          "For all the comparison models, we run a hyperparameter tuning with the same number of search steps."),
         ("On the KDD datasets (described as performance-saturated), TabNet achieves very similar or slightly worse performance than XGBoost and CatBoost, which the authors describe as robust because they contain a high amount of ensembles.",
          "Appendix (Performance on KDD datasets)",
          "Table 8 shows that TabNet achieves very similar or slightly worse performance than XGBoost and CatBoost, that are known to be robust as they contain high amount of ensembles."),
         ("Self-supervised pre-training (masked feature-column prediction with a decoder) is reported to significantly improve supervised accuracy on Higgs (TabNet-M, mean and std over 15 runs, 1k/10k/100k labeled samples), especially when the unlabeled dataset is much larger than the labeled one, and to speed convergence.",
          "Self-supervised learning",
          "Table 7 shows that unsupervised pre-training signiﬁcantly improves performance on the supervised classiﬁcation task, especially in the regime where the unlabeled dataset is much larger than the labeled dataset."),
         ("Hyperparameter sensitivity: the paper states TabNet is not very sensitive to most hyperparameters, but the Forest Cover ablation reports that high performance needs capacity adjusted to the dataset and that increasing units or decision steps beyond some value causes optimization issues without performance benefit.",
          "Appendix (Ablation studies)",
          "On the other hand, increasing these parameters beyond some value causes optimization issues and do not yield performance beneﬁts."),
         ("Mask and prior scale: M[i] = sparsemax(P[i-1] . h_i(a[i-1])) is applied multiplicatively to the features (M[i] . f), each row of M[i] sums to 1, and the prior scale P[i] = prod_{j=1}^{i} (gamma - M[j]) records how much each feature has been used in previous steps; gamma = 1 enforces a feature to be used at only one step, and larger gamma allows more reuse.", "TabNet for Tabular Learning", "is the prior scale term, denoting how much a particular feature"),
     ],
     "notes": "Moved from c6/c7 during review (these come from other paragraphs than the c6/c7 quotes): per-dataset, many baseline numbers or settings are taken from prior work (Forest Cover GBDT hyperparameters from Mitchell et al. 2018; Sarcos baselines follow Tanno et al. 2018; Rossmann baseline performance from the CatBoost benchmark; KDD baselines from Prokhorenkova et al. 2018), while GBDTs are tuned on Poker Hand; the main text reports TabNet outperforming XGBoost/LightGBM/CatBoost on Forest Cover Type, Poker Hand and Rossmann and a single TabNet outperforming Google's AutoML Tables on Forest Cover Type. Affiliation: Google Cloud AI (PDF page 1). Venue: the PDF page 1 carries 'Copyright © 2021, Association for the Advancement of Artificial Intelligence (www.aaai.org)'; recorded as 'AAAI 2021' on that basis (the arXiv record has no comment/journal_ref, so this rests on the copyright line only). Year is the first arXiv version (2019); the v5 PDF is dated 9 Dec 2020. Section headings are unnumbered, so locations use heading names. Conflict of interest: AutoML Tables, which TabNet is compared against on Forest Cover Type, is a Google Cloud product (reference 'AutoML Tables – Google Cloud'); the authors are at Google Cloud AI. All evaluation datasets named are public (UCI, Kaggle, KDD Cup, synthetic from Chen et al. 2018); no company-internal dataset was found. Number of random seeds for the supervised real-world tables is not stated (searched for runs, seed, repeat); only Table 7/10 (self-supervised) state 15 runs. The appendix lists TabNet search ranges; GBDT search spaces are not listed. Result tables not recorded."},

    {"id": "arxiv-1909.06312",
     "title": "Neural Oblivious Decision Ensembles for Deep Learning on Tabular Data",
     "authors": ["Sergei Popov", "Stanislav Morozov", "Artem Babenko"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1909.06312", "code": "https://github.com/Qwicen/node"},
     "tasks": ["tabular-classification", "tabular-regression"],
     "fam": ["differentiable-trees", "deep-learning"], "par": ["supervised"],
     "proposes": ["NODE layer: an ensemble of m differentiable oblivious decision trees in which the splitting-feature choice is a weighted sum of features with alpha-entmax weights over a learnable selection matrix and the Heaviside comparison is relaxed to a scaled two-class entmax; leaf responses are combined with the outer-product choice tensor",
                  "Multi-layer NODE: DenseNet-style stacking where each layer takes the concatenation of the input features and all previous layers' tree outputs, with the prediction averaged over all trees, trained end-to-end"],
     "claims": [
         ("Differentiable oblivious trees: instead of REINFORCE or Gumbel-softmax, which the authors say typically require long training time, NODE uses alpha-entmax to learn sparse splitting-feature choices that depend on only a few features, and a scaled two-class entmax to relax the threshold comparison; the relaxation equals a classic oblivious tree when both reach one-hot states.",
          "Section 3.1",
          "Instead, we propose to use the α-entmax transformation (Peters et al., 2019) as it is able to learn sparse choices, depending only on a few features, via standard gradient descent."),
         ("Deep architecture: a sequence of k NODE layers, each taking the concatenation of all previous layers (including the input features) as input, following DenseNet; the final prediction is a simple average of all trees from all layers, and tree outputs can have dimension l > number of classes so that early layers produce features for later ones.",
          "Section 3.2",
          "Similar to DenseNet, our architecture is a sequence of k NODE layers (see Section 3.1), where each layer uses a concatenation of all previous layers as its input."),
         ("Training protocol: each feature is quantile-transformed to a normal distribution (observed to be important for stable training and faster convergence), data-aware initialization is used, training uses Quasi-Hyperbolic Adam with parameters from the original paper, parameters are averaged over 5 consecutive checkpoints, and the stopping point is chosen on a hold-out validation set.",
          "Section 3.3",
          "In experiments, we observed that this step was important for stable training and faster convergence."),
         ("Evaluation protocol: six open-source datasets (Epsilon, YearPrediction, Higgs, Microsoft, Yahoo, Click) with provided train/test splits and 20% of the train set as validation, fixed splits for all methods (the appendix says Yahoo uses the split provided by its authors); baselines are CatBoost, XGBoost and a fully connected network (FCNN); mean and standard deviation over ten runs with different random seeds are reported. Ranking datasets are treated as regression with MSE.",
          "Section 4.1",
          "For all methods, we report mean performance and standard deviations computed over ten runs with different random seeds."),
         ("Tuning budget: CatBoost, XGBoost and FCNN are tuned with 50 steps of TPE (Hyperopt), with the number of trees (max 2048) set on validation at each step; NODE is tuned by grid search over number of layers {2, 4, 8}, total tree count {1024, 2048} and tree output dimension {2, 3} with learning rate fixed at 1e-3, so the budgets differ in form between NODE and the baselines.",
          "Appendix (Optimization of hyperparameters)",
          "For each method, we perform 50 steps of Tree-structured Parzen Estimator (TPE) optimization algorithm."),
         ("Default-hyperparameter regime: GBDTs use package defaults with only the number of trees (up to 2048) set on validation, NODE uses a single layer of 2048 trees of depth six (inherited from CatBoost defaults), and FCNN is not compared because it typically requires much tuning and no setting suitable for all datasets was found.",
          "Section 4.1",
          "We do not compare with FCNN in this regime, as it typically requires much tuning, and we did not ﬁnd the set of parameters, appropriate for all datasets."),
         ("Relation to GBDTs within the paper: with default hyperparameters NODE is reported to outperform CatBoost and XGBoost on all six datasets; with tuned hyperparameters it outperforms them on most tasks, the exceptions being Yahoo and Microsoft where tuned XGBoost is best, which the authors speculate means oblivious trees are an inappropriate inductive bias for Yahoo.",
          "Section 4.1",
          "Given the large advantage of XGBoost over CatBoost on Yahoo, we speculate that the usage of oblivious decision trees is an inappropriate inductive bias for this dataset."),
         ("Critique of prior work: the authors state that earlier tabular DNN architectures mostly did not compare with properly tuned GBDT implementations, and that a preprint reporting marginal gains over default-parameter GBDT faced much stronger baselines in their experiments.",
          "Section 2",
          "The recent preprint (Ke et al., 2018) reports the marginal improvement over GBDT with default parameters, but in our experiments, the baseline performance is much higher."),
         ("Ablation of choice functions (YearPrediction and Epsilon): entmax with alpha = 1.5 is reported to outperform softmax, sparsemax and Gumbel-softmax across the experiments; sparsemax and softmax are not universal (each wins on one dataset), and Gumbel-softmax could not learn deep architectures, probably because its stochasticity makes early-layer responses too noisy.",
          "Section 4.2",
          "Another observation is that Gumbel-Softmax is unable to learn deep architectures with both constant and annealed temperature schedules."),
         ("Oblivious decision tree (Eq. 1): a depth-d ODT with splitting features f_1..f_d and thresholds b_1..b_d outputs h(x) = R[1(f_1(x) - b_1), ..., 1(f_d(x) - b_d)], where 1 is the Heaviside function and R is a table of 2^d responses indexed by the binary comparison results.", "Section 3.1", "In this notation, the tree output is deﬁned as:"),
         ("Differentiable relaxation (Eq. 2): the feature choice becomes a weighted sum fhat_i(x) = sum_j x_j entmax_alpha(F_ij) with weights from entmax over a learnable feature-selection matrix F, and the Heaviside comparison becomes c_i(x) = sigma_alpha((f_i(x) - b_i)/tau_i), with sigma_alpha(x) = entmax_alpha([x, 0]) a two-class entmax and learnable thresholds b_i and scales tau_i.", "Section 3.1", "with weights computed as entmax over the learnable feature selection matrix"),
     ],
     "notes": "Affiliations: Yandex (all authors), plus Lomonosov Moscow State University and HSE (PDF page 1). No venue is stated in the v2 PDF (dated 19 Sep 2019) and the arXiv record has no comment/journal_ref; none recorded. Section numbers are from numbered headings in the PDF. Comparison with mGBDT and DeepForest was partial (OOM on many datasets; DeepForest classification-only), with tuned GBDTs reported better than both. Runtime (Section 4.2, Table 4): 1024 trees of depth six on YearPrediction, single 1080Ti GPU vs 28-core Xeon; NODE inference is described as on par with GBDT libraries. The Click subset was built by sampling 500,000 objects per class, categorical features via leave-one-out encoding. Babenko is a co-author of later tabular DL benchmarks that evaluate NODE; this paper itself does not state a conflict of interest. Result tables not recorded."},

    {"id": "arxiv-2309.17130",
     "title": "GRANDE: Gradient-Based Decision Tree Ensembles for Tabular Data",
     "authors": ["Sascha Marton", "Stefan Lüdtke", "Christian Bartelt", "Heiner Stuckenschmidt"],
     "year": 2023, "venue": "ICLR 2024", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2309.17130"},
     "tasks": ["tabular-classification"],
     "fam": ["differentiable-trees", "tree-ensembles"], "par": ["supervised"],
     "proposes": ["GRANDE: an ensemble of hard, axis-aligned decision trees learned jointly by end-to-end gradient descent using GradTree's dense representation and a straight-through operator for rounding/hardmax",
                  "Scaled softsign as the differentiable split function used in the backward pass",
                  "Instance-wise estimator weights: one learnable weight per leaf, softmax over the weights of the leaves each sample reaches",
                  "Per-tree feature and data subsets and estimator dropout as regularization"],
     "claims": [
         ("Method: GRANDE extends the authors' earlier GradTree (Marton et al., 2023) from single trees to a jointly optimized weighted tree ensemble with hard, axis-aligned splits, using a dense representation and the straight-through operator; the authors contrast this with NODE's soft, oblique splits.",
          "Introduction",
          "We extend GradTree (Marton et al., 2023) from individual trees to an end-to-end gradient-based tree ensemble, maintaining efficient computation (Section 3.1)."),
         ("Motivation (citing Rahaman et al., 2019 and Grinsztajn et al., 2022): DL methods are typically biased towards smooth solutions while target functions in tabular data are usually not smooth; hard, axis-aligned trees learn piece-wise constant functions and do not show this bias.",
          "Introduction",
          "As the target function in tabular datasets is usually not smooth, DL methods struggle to find these irregular functions."),
         ("Softsign split function: sigmoid gradients decline smoothly and entmoid gradients drop to zero for large differences from the threshold, so a softsign scaled to (0, 1) is proposed to keep responsive gradients for samples far from the threshold; an ablation (Table 4) reports it outperforms sigmoid and entmoid.",
          "Section 3.2",
          "Therefore, we propose using a softsign function, scaled to (0, 1), as a differentiable split function:"),
         ("Instance-wise weighting: instead of one weight per estimator (which the authors say forces a homogeneous ensemble), each leaf has a learnable weight, and a softmax over the weights of the leaves a sample reaches gives a per-sample weighted average; the ablation reports this significantly enhances performance compared with a single weight per estimator.",
          "Section 3.3",
          "To address this, we propose an advanced weighting scheme that allows calculating instance-wise weights that can be learned within the gradient-based optimization."),
         ("Benchmark: 19 binary classification datasets selected by the predefined procedure of Bischl et al. (2021) from OpenML benchmark suites, which the authors argue is not biased towards their method (CC18 and the Grinsztajn et al. benchmark were rejected; multi-class tasks were excluded for scope); one-hot/leave-one-out encoding and quantile transformation; mean and std of test macro F1 over 5-fold cross-validation.",
          "Section 4.1",
          "The selection process was adopted from Bischl et al. (2021) and therefore is not biased towards our method."),
         ("Tuning protocol: baselines in the main comparison are XGBoost, CatBoost and NODE (SAINT, RandomForest and ExtraTrees in the appendix); all are tuned with Optuna for 250 trials with search spaces and default parameters following Borisov et al. (2022), best parameters chosen by 5x2 cross-validation with each fold's test data held out, and class weights for imbalance. Default-hyperparameter results are also reported.",
          "Section 4.1",
          "We optimized the hyperparameters using Optuna (Akiba et al., 2019) with 250 trials and selected the search space as well as the default parameters for related work in accordance with Borisov et al. (2022)."),
         ("Asymmetry in tuned hyperparameters acknowledged: GRANDE has 11 tuned hyperparameters versus 4 for XGBoost and 3 for CatBoost; in an additional HPO with only 4 GRANDE parameters the authors report GRANDE still achieves SOTA results but benefits from the larger grid. The number of estimators for XGBoost and CatBoost was not tuned (early stopping), checked in an extra HPO; a 30-trial HPO is also reported.",
          "Appendix E",
          "In contrast, for XGBoost and CatBoost we only optimized 4 and 3 hyperparameters, respectively."),
         ("Relation to GBDTs within the paper (tuned): GRANDE has the highest mean reciprocal rank (0.702) and normalized mean (0.776), followed by CatBoost (0.570, 0.671), XGBoost (0.417, 0.483) and NODE (0.395, 0.327); the authors add that this is in line with there being no universal method for tabular data, that differences are substantial on some datasets, and that results are especially good for small datasets.",
          "Section 4.2",
          "GRANDE outperformed existing methods and achieved the highest mean reciprocal rank (MRR) of 0.702 and the highest normalized mean of 0.776."),
         ("Interpretability claim and its evidence: instance-wise weights let one inspect the highest-weighted estimators for a given instance; the evidence is a case study of one PhishingWebsites instance where a single depth-two tree carries 94% of the weight and its rule matches the Anchors explanation, with GRANDE's anchor simpler than those of the other methods at equal precision.",
          "Section 4.3",
          "In contrast, existing ensemble methods require a global interpretation of the model and do not provide simple, local explanations out-of-the-box."),
     ],
     "notes": "Affiliations: University of Mannheim and University of Rostock (PDF page 1). Venue from the PDF page header 'Published as a conference paper at ICLR 2024'; year is the first arXiv version (2023). Section numbers are from numbered headings. Conflict of interest: GRANDE builds on the first author's own GradTree (Marton et al., 2023), stated in the paper; GradTree is not a compared baseline in the main table. Runtime (Section 4.2): GRANDE averaged 47 s per dataset (max 107 s) vs about 130 s for NODE, but the authors note GBDT frameworks, especially XGBoost on GPU, have significantly lower runtimes than gradient-based methods; hardware listed in Table 9 caption (NVIDIA RTX A6000). Only binary classification is evaluated. Default-parameter results: highest normalized mean 0.6371 and MRR 0.6404 (Section 4.2). SAINT could not be tuned with 250 trials due to its runtime (Appendix C). Result tables not recorded."},

    {"id": "arxiv-2012.06678",
     "title": "TabTransformer: Tabular Data Modeling Using Contextual Embeddings",
     "authors": ["Xin Huang", "Ashish Khetan", "Milan Cvitkovic", "Zohar Karnin"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2012.06678"},
     "tasks": ["tabular-classification", "representation-learning"],
     "fam": ["tabular-attention", "deep-learning"], "par": ["supervised", "self-supervised"],
     "proposes": ["TabTransformer: categorical features are embedded with per-column embeddings (a shared column identifier concatenated with a value-specific embedding, no positional encoding), passed through a stack of Transformer layers to produce contextual embeddings, then concatenated with the raw continuous features and fed to an MLP",
                  "Two-phase semi-supervised training: pre-training the Transformer layers on unlabeled data with masked language modeling (MLM) or replaced token detection (RTD, with a separate binary classifier per column), then fine-tuning on labeled data"],
     "claims": [
         ("Architecture: a column embedding layer, a stack of N Transformer layers and an MLP; only categorical features pass through the Transformer, and the resulting contextual embeddings are concatenated with the continuous features before the MLP.",
          "Section 2",
          "The contextual embeddings {h1, · · · , hm} are concatenated along with the continuous features xcont to form a vector of dimension (d × m + c)."),
         ("Column embedding: each categorical column has its own lookup table with an extra embedding for missing values; each embedding concatenates a column-shared unique identifier with a value-specific part, and positional encodings are not used because tabular features have no order.",
          "Section 2",
          "Since, in tabular data, there is no ordering of the features, we do not use positional encodings."),
         ("Pre-training: MLM masks k% of categorical features and predicts them; RTD replaces features with random values of that feature and trains a binary classifier per column (no auxiliary generator, since columns have few classes); k = 30 in the experiments.",
          "Section 2",
          "We explore two different types of pre-training procedures, the masked language modeling (MLM) (Devlin et al. 2019) and the replaced token detection (RTD) (Clark et al. 2020)."),
         ("Pre-training is applied only in the semi-supervised setting; the authors report not finding much benefit from it when all data is labeled, with its benefit evident when there are many unlabeled and few labeled examples.",
          "Section 3",
          "We do not ﬁnd much beneﬁt in using it when the entire data is labeled."),
         ("Evaluation protocol: 15 public binary classification datasets (UCI, AutoML Challenge, Kaggle), five cross-validation splits with 65/15/20% train/validation/test, AUC as metric, 20 HPO rounds per model per split; TabTransformer's embedding dimension, layers and heads are fixed to 32, 6 and 8, chosen by 50 rounds of HPO on 5 datasets. Semi-supervised runs use the first p = 50, 200 or 500 training rows as labeled.",
          "Section 3",
          "For hyperparameter optimization (HPO), each model is given 20 HPO rounds for each cross-validation split."),
         ("Baselines were re-implemented for consistent preprocessing (the authors state their results are close to published ones where available); GBDT is LightGBM tuned over number of leaves, minimum data per leaf, learning rate and number of trees; TabNet was implemented as described but with an added softmax-attention option and without the sparsification term in the loss.",
          "Appendix B.1",
          "For the competing models mentioned in the experiment, we re-implemented all of them for consistency of pre-processing."),
         ("Relation to GBDT and other deep models (supervised): TabTransformer outperforms the baseline MLP (14 of 15 datasets, average 1.0% AUC gain) and performs comparably with GBDT; it is reported significantly better than TabNet and VIB.",
          "Section 3.3",
          "The TabTransformer outperforms the baseline MLP with an average 1.0% gain and perform comparable with the GBDT."),
         ("Robustness and interpretability of contextual embeddings: on 3 datasets, with noise or missing values injected into categorical test features, TabTransformer degrades less than the MLP, which the authors conjecture comes from the contextual property of the embeddings; t-SNE of last-layer embeddings on BankMarketing groups semantically similar classes, and linear probes improve with layer depth.",
          "Section 3.2",
          "We conjecture that the robustness comes from the contextual property of the embeddings."),
         ("Semi-supervised results: with many unlabeled examples TabTransformer-RTD/MLM is reported to outperform the other methods (at least 1.2%, 2.0% and 2.1% mean AUC for 50, 200 and 500 labels); with fewer unlabeled examples the improvement is marginal, and with only 50 labels MLP (ER) and MLP (PL) beat TabTransformer-RTD/MLM, which the authors attribute to the classifier weights not being trained with unlabeled data.",
          "Section 3.4",
          "In Table 4, with only 50 labeled data points, MLP (ER) and MLP (PL) beat our TabTransformer-RTD/MLM."),
     ],
     "notes": "Affiliations: Amazon AWS (Huang, Khetan, Karnin) and PostEra (Cvitkovic) (PDF page 1). No venue is stated in the v1 PDF (11 Dec 2020); the arXiv comment is only '7 pages, 5 figures'; none recorded. All 15 datasets are public (UCI, AutoML Challenge, Kaggle); no company-internal dataset was found. Inconsistency in the PDF: the text of Section 3.4 splits the 15 datasets into 6 with more than 30K points and 9 others, while the captions of Table 3 and Table 4 say 8 and 12 datasets. Number of seeds: splits are fixed with one random seed so all models see the same conditions (Appendix B.1); no repeated seeds beyond the 5 CV splits were found. GBDT is represented only by LightGBM. Experiments ran on a single NVIDIA V100. Result tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
