import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ci_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1706.03461",
     "title": "Meta-learners for Estimating Heterogeneous Treatment Effects using Machine Learning",
     "authors": ["Sören R. Künzel", "Jasjeet S. Sekhon", "Peter J. Bickel", "Bin Yu"],
     "year": 2017, "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/1706.03461", "code": "https://github.com/soerenkuenzel/hte"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners", "random-forests", "tree-ensembles"], "par": ["supervised"],
     "proposes": ["X-learner: estimate the control and treatment response functions with any base learners, impute individual treatment effects for treated units (observed outcome minus predicted control outcome) and for control units (predicted treated outcome minus observed outcome), regress each set of imputed effects on the covariates, and combine the two CATE estimates with a weight function g(x) (an estimated propensity score is suggested)",
                    "A unified meta-learner framing of CATE estimation (S-, T- and X-learners) with RF and BART base learners, and minimax-rate comparisons of the T- and X-learners"],
     "claims": [
         ("Definitions: the T-learner estimates the control and treatment response functions separately (possibly with different base learners) and takes their difference; the S-learner fits a single model on all features plus the treatment indicator, without giving the indicator a special role, and takes the difference of predictions with the indicator set to treatment vs control.",
          "Introduction",
          "We refer to this meta-algorithm as the S-learner, since it uses a “single” estimator."),
         ("Estimand and assumptions: the target is the CATE tau(x) = E[Y(1) - Y(0) | X = x]; the individual treatment effect is not identifiable without strong additional assumptions, but the best CATE estimator is also the best ITE estimator in MSE. The authors assume no hidden confounders (Condition 1) and note that this alone is not sufficient to identify the CATE, adding a propensity score bounded away from 0 and 1 (Condition 2).",
          "Framework and Definitions",
          "This assumption is, however, not suﬃcient to identify the CATE."),
         ("The X-learner is motivated by the observation that individual treatment effects are never observed: it uses the observed outcomes and first-stage response-function estimates to impute the unobserved individual effects, and then estimates the CATE in a second step as if those effects were observed.",
          "Introduction",
          "The X-learner uses the observed outcomes to estimate the unobserved individual treatment eﬀects."),
         ("Choice of the weight function in the X-learner's final stage: based on their experience, the authors find it good to use an estimated propensity score for g, but say it also makes sense to set g to 1 or 0 when the number of treated units is very large or small relative to the number of controls; with an estimated covariance of the two stage-2 estimates, g could be chosen to minimize variance.",
          "X-learner",
          "Based on our experience, we observe that it is good to use an estimate of the propensity score for g,"),
         ("Simulation summary (synthetic data; RF and BART base learners): for each meta-learner there exist cases where it is best. The S-learner can ignore the treatment indicator, which helps when the CATE is often 0 but can bias it toward 0; the T-learner does well when the CATE is very complicated and mu0, mu1 share no trends; the X-learner does particularly well with structural assumptions on the CATE or very unequal group sizes. As a rule of thumb, unless one strongly believes the CATE is mostly 0, the authors suggest the X-learner with BART for small data sets and RF for bigger ones.",
          "Simulation Results",
          "These simulation results lead us to the conclusion that unless one has a strong belief that the CATE is mostly 0, then, as a rule of thumb, one should use the X-learner with BART for small data sets and RF for bigger ones."),
         ("Theorem 2: with m control and n treated units, under bounded-variance independent errors, finite second moments of X, ignorability, a control-response estimator with EMSE <= C0 m^(-a), a CATE that is linear in x, and a well-conditioned sample covariance of the treated covariates, the X-learner with OLS in the second stage and g = 0 has EMSE <= C(m^(-a) + n^(-1)); if there are many controls (m >= c3 n^(1/a)) it attains the parametric rate in n. The T-learner, in contrast, in general cannot be expected to beat O(m^(-a_mu) + n^(-a_mu)) (Theorem 1).",
          "Smoothness conditions for the CATE",
          "The following theorem deals carefully with this estimation error when τ is linear, but the response functions can be estimated at any nonparametric rate."),
         ("Beyond the linear-CATE case (and a Lipschitz case with no CATE assumptions, where T and X attain the same minimax rate), the faster X-learner rates are stated only as a conjecture: the authors say it is mathematically very challenging to state the extra conditions needed, while believing the conjecture holds much more generally.",
          "Comparison of Convergence Rates",
          "It turns out to be mathematically very challenging to give a satisfying statement of the extra conditions needed on P."),
         ("Observational setting: the authors state that all of the meta-learners discussed can handle confounding as long as ignorability holds, and test this in one confounded simulation (propensity depending on an observed covariate, following Wager & Athey); causal forests are excluded there because, as their authors note, they are not designed for observational studies with only conditional unconfoundedness.",
          "Supporting Information, A.3 Confounding",
          "All of the meta-learners we discuss can handle confounding, as long as the ignorability assumption holds."),
     ],
     "notes": "Affiliation: UC Berkeley. PDF dated April 25, 2019 (arXiv v6). The arXiv record has no journal_ref/comment and the PDF text does not name a venue, so none is recorded. The Simulation Results footnote defines 'confounding' as an unobserved covariate influencing W and an outcome, whereas the confounded simulation in SI A.3 uses a propensity that depends on an observed covariate; no sensitivity analysis for hidden confounding was found in the text (searched for hidden, unobserved, sensitivity). Conflict of interest: the RF base learner is the authors' own honest RF in their R package hte, which they also recommend for choosing among CATE estimators (Conclusion). Applications (GOTV mailer, door-to-door canvassing) are randomized experiments; in the canvassing data S-RF shrinks estimates toward zero (Applications). Simulation errors are figure-only; not recorded."},

    {"id": "arxiv-1608.00060",
     "title": "Double/Debiased Machine Learning for Treatment and Causal Parameters",
     "authors": ["Victor Chernozhukov", "Denis Chetverikov", "Mert Demirer", "Esther Duflo", "Christian Hansen",
                 "Whitney Newey", "James Robins"],
     "year": 2016, "version": "arXiv v7",
     "links": {"arxiv": "https://arxiv.org/abs/1608.00060"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners"],
     "proposes": ["Double/debiased machine learning (DML): estimate a low-dimensional target parameter from a Neyman-orthogonal score with nuisance functions learned by arbitrary ML methods, combined with K-fold cross-fitting (DML1: average fold-wise estimates; DML2: solve the pooled fold-wise moment equation)",
                  "Aggregation over repeated sample splits by the mean or (recommended) median, with variance estimates that include the across-split variation"],
     "claims": [
         ("Regularization bias: in the partially linear model, a naive estimator that plugs an ML estimate of g0 into the estimating equation (even with sample splitting) generally converges slower than 1/sqrt(n), because the regularization bias term is not centered and diverges in general; regularized learners (lasso, ridge, boosting, penalized nets) typically converge at n^(-phi) with phi < 1/2.",
          "Section 1.1",
          "Term b is the regularization bias term, which is not centered and diverges in general."),
         ("Orthogonalization: partialling out the effect of X from D (V = D - m0(X), with m0 estimated by ML on the auxiliary sample) and subtracting an estimate of g0 yields a debiased estimator; because this requires an auxiliary prediction of D given X, the authors call it 'double prediction' or 'double machine learning'.",
          "Section 1.1",
          "We are now solving an auxiliary prediction problem to estimate the conditional mean of D given X, so we are doing “double prediction” or “double machine learning”."),
         ("Cross-fitting: sample splitting controls remainder terms that otherwise may not vanish when nuisance estimates overfit (an artificial overfitting estimator that converges at nearly the parametric rate still makes the full-sample estimator explode); swapping the main and auxiliary samples and averaging regains full efficiency.",
          "Section 1.1",
          "We call this sample splitting procedure where we swap the roles of main and auxiliary samples to obtain multiple estimates and then average the results cross-fitting."),
         ("Definition 2.1 (Neyman orthogonality): the score satisfies the moment condition at the true values and its pathwise (Gateaux) derivative with respect to the nuisance parameter, at the truth, vanishes for all nuisance values in a nuisance realization set (typically a shrinking neighborhood of eta0); a near-orthogonal variant allows the derivative to be bounded by lambda_N = o(N^(-1/2)).",
          "Section 2.1",
          "The Neyman orthogonality condition requires that the derivative in (2.2) vanishes for all η ∈TN."),
         ("Rate requirement: Assumption 3.2 states conditions on the quality of nuisance estimators in terms of statistical rates; in smooth problems this translates, in the worst cases, to the crude requirement that nuisance parameters be estimated at the rate o(N^(-1/4)), which the authors say is achievable for many ML methods under structured assumptions (citing results for l1-penalized methods, boosting, trees/forests and a class of neural nets).",
          "Section 3.2",
          "However, in smooth problems, as discussed below this translates, in the worst cases, to the crude requirement that the nuisance parameters are estimated at the rate"),
         ("ATE and ATTE under unconfoundedness with binary treatment (interactive model): the ATE score is the doubly robust form based on the influence function of Robins & Rotnitzky (1995); under Assumption 5.1 (including overlap, eps <= m0(X) <= 1 - eps, and a product of propensity and outcome-regression L2 errors <= delta_N N^(-1/2)), DML1 and DML2 are root-N asymptotically normal with uniformly valid confidence intervals (Theorem 5.1), and the authors state that the scores are efficient, reaching Hahn's (1998) semiparametric efficiency bound.",
          "Section 5.1",
          "The scores ψ in (5.3) and (5.4) are efficient, so both estimators are asymptotically efficient, reaching the semi-parametric efficiency bound of Hahn (1998)."),
         ("The authors describe the conditions of Assumption 5.1 as fairly sharp though simplified for presentation: in sparse models estimated by l1-penalized methods, the product-rate condition requires s_g s_m << N (ignoring logs), much weaker than (s_g)^2 + (s_m)^2 << N needed without sample splitting, so a very sparse propensity score allows a quite dense outcome regression and vice versa; with a known propensity score only consistency of the outcome regression is needed.",
          "Section 5.1 (Remark 5.2)",
          "The conditions in Assumption 5.1 are fairly sharp though somewhat simplified for ease of presentation."),
         ("Without unconfoundedness (conditional exogeneity), the ATE and ATTE targets measure association rather than causal effects; the authors suggest calling them the average predictive effect (APE) and average predictive effect for the exposed (APEX), and state that inference for them follows from Theorem 5.1.",
          "Section 5.1 (footnote 10)",
          "Without unconfoundedness/conditional exogeneity, these quantities measure association, and could be referred to as average predictive effect (APE) and average predictive effect for the exposed (APEX)."),
         ("Practical recommendations: the number of folds K has no asymptotic impact under the conditions but may matter in small samples; the authors found K = 4 or 5 to work better than K = 2 in a variety of empirical examples and simulations, generally recommend DML2 over DML1 (no difference for the ATE in the interactive model), and recommend reporting the median over repeated sample splits because it is more robust to outliers (Section 3.4).",
          "Section 3.1 (Remark 3.1)",
          "We have found moderate values of K, such as 4 or 5, to work better than K = 2 in a variety of empirical examples and in simulations."),
     ],
     "notes": "Affiliations: MIT, UCLA, University of Chicago, Harvard. Title: the arXiv API record gives '... for Treatment and Causal Parameters', while the v7 PDF (3 Nov 2024) title reads 'Double/Debiased Machine Learning for Treatment and Structural Parameters'; the arXiv record title is used here. The PDF carries 'Received: June 2014' but names no journal, and the arXiv record has no journal_ref, so no venue is recorded. The paper also covers the partially linear IV model and LATE, and three empirical examples (results tables not recorded). The Figure 1/2 simulations (naive vs orthogonal estimator, overfitting with and without sample splitting) are figure-only. Conflict of interest: the sample-splitting device builds on the authors' own earlier work (Belloni, Chernozhukov, Hansen et al.; Robins et al. 2013), which the paper states."},

    {"id": "arxiv-1712.04912",
     "title": "Quasi-Oracle Estimation of Heterogeneous Treatment Effects",
     "authors": ["Xinkun Nie", "Stefan Wager"],
     "year": 2017, "venue": "Biometrika", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1712.04912", "code": "https://github.com/xnie/rlearner"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners", "linear-models"], "par": ["supervised"],
     "proposes": ["R-learner: estimate the conditional mean outcome m(x) and propensity e(x) with cross-fitting, then estimate the CATE by minimizing the R-loss (sum of [{Y - m_hat(X)} - {W - e_hat(X)} tau(X)]^2) plus a regularizer, using any loss-minimization method (lasso, kernel ridge regression, boosting) tuned by cross-validation on the R-loss",
                  "A quasi-oracle regret bound for the penalized-kernel-regression R-learner, and the RS-learner lasso variant"],
     "claims": [
         ("Setup and identification: with potential outcomes and the unconfoundedness assumption (Assumption 1), the CATE can be written via Robinson's decomposition Y - m*(X) = {W - e*(X)} tau*(X) + eps, where m* is the conditional mean outcome and e* the propensity; the authors note the decomposition was originally used by Robinson (1988) for parametric components of partially linear models.",
          "Introduction",
          "This decomposition was originally used by Robinson (1988) to estimate parametric components in partially linear models, and has received considerable attention in recent years."),
         ("R-learner definition: Step 1 fits m_hat and e_hat with cross-fitting over Q folds (typically 5 or 10), using methods tuned for predictive accuracy; Step 2 minimizes the plug-in R-loss plus a regularizer. The name recognizes Robinson (1988) and the role of residualization.",
          "Introduction",
          "We refer to this approach as the R-learner in recognition of the work of Robinson (1988) and to emphasize the role of residualization."),
         ("Practical claim: because the R-loss removes spurious correlations through its structure, the second step is an ordinary empirical minimization that off-the-shelf software (glmnet, XGBoost, TensorFlow) can solve, and any of these methods can be tuned by cross-validating on the R-loss rather than with model-assisted cross-validation procedures; the method only needs to find good minimizers on holdout data.",
          "Introduction",
          "Furthermore, we can tune any of these methods by cross validating on the loss"),
         ("Critique of separate fits (T-learner style): fitting separate lassos to treated and controls regularizes each toward 0 and may regularize the treatment-effect estimate away from 0 even when the true CATE is zero; the authors say this is especially acute with different treated and control sample sizes (citing Künzel et al. 2019 for examples).",
          "Related Work",
          "This problem is especially acute when the treated and control samples are of diﬀerent sizes;"),
         ("Quasi-oracle result (Theorem 3): for the penalized kernel regression R-learner, under RKHS eigenvalue-decay and boundedness conditions (Assumption 2), a smoothness condition on tau* (Assumption 3, with 2 alpha < 1 - p), overlap (eta < e*(x) < 1 - eta), a uniformly consistent propensity estimate, and nuisance L2 errors of order n^(-kappa) with kappa > 1/4, and with a properly chosen (slightly stronger) penalty, the feasible estimator attains the same regret bound as the oracle that knows m* and e*.",
          "Section 5",
          "with penalized kernel regression, the R-learner can match the best available performance guarantees available for the oracle learner (10)"),
         ("Overlap caveat: under overlap, regret bounds translate into squared-error bounds for tau and vice versa, but the authors note that as the overlap parameter eta approaches 0 this coupling becomes fairly loose.",
          "Section 5",
          "We note that when the overlap parameter η gets close to 0, the coupling (12) gets fairly loose."),
         ("The quasi-oracle property relies on a local robustness property of the R-loss and does not hold for general meta-learners: the authors argue that o(n^(-1/4)) shifts of the X-learner's nuisance estimates shift its CATE estimate enough to break convergence at the oracle rate. They interpret Künzel et al.'s X-learner result, which covers many more controls than treated units, as qualitatively a special case where the R-learner is roughly equivalent to the X-learner.",
          "Section 5",
          "We emphasize that our quasi-oracle result depends on a local robustness property of the R-loss function, and does not hold for general meta-learners"),
         ("Lasso simulations (synthetic Setups A-D: difficult nuisance with easy CATE, randomized trial, strong confounding with easy propensity, and unrelated arms; 10-fold CV for penalties and 10-fold cross-fitting): the R- and RS-learners stand out in Setups A and C, all methods do reasonably in the randomized Setup B, and the T-learner performs well in Setup D; overall the authors report that R- and RS-learners in most specifications essentially match the lasso oracle in MSE, while the U-learner suffers from instability.",
          "Section 6.2",
          "simulation speciﬁcations, essentially match the performance of the oracle (3) in terms of the mean-squared error."),
     ],
     "notes": "Affiliation: Stanford. Venue from the arXiv comment ('Biometrika, forthcoming'); the PDF (v4, 'Draft version August 2020') does not name the venue; year = first arXiv version (2017). Conflict of interest: the authors provide the rlearner R package, and the stacking example (Section 4) and related discussion use causal forests (Wager & Athey; Athey, Tibshirani & Wager), co-authored by Wager. The quasi-oracle guarantee is proven only for penalized kernel regression; lasso and boosting variants are evaluated empirically. Simulation MSEs are in figures and Appendix B tables; not recorded."},

    {"id": "arxiv-2004.14497",
     "title": "Towards optimal doubly robust estimation of heterogeneous causal effects",
     "authors": ["Edward H. Kennedy"],
     "year": 2020, "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/2004.14497"},
     "tasks": ["causal-effect-estimation"],
     "fam": ["causal-meta-learners"], "par": ["supervised"],
     "proposes": ["DR-Learner analysis: regress the doubly robust (AIPW) pseudo-outcome, built from nuisance estimates on a separate sample, on covariates, with optional cross-fitting; a model-free oracle inequality for regression with estimated pseudo-outcomes under a new stability condition",
                  "lp-R-Learner: a local-polynomial, double-sample-split adaptation of the R-learner with faster rates outside the oracle regime in Hölder models"],
     "claims": [
         ("Setup: the target is tau(x) = mu1(x) - mu0(x); under no unmeasured confounding, consistency and positivity/overlap (assumed throughout) it equals the CATE E(Y^1 - Y^0 | X = x). The author notes the results hold regardless of whether the causal assumptions do (i.e., for the difference in regression functions).",
          "Section 2",
          "noting that our results hold regardless of whether the causal assumptions do"),
         ("Motivating illustration: when mu1 and mu0 are individually complex and non-smooth but their difference is zero, and treated/untreated units are unevenly spread over x, separately fit regressions over- and under-smooth in different regions, so the plug-in difference is a poor, overly complex CATE estimate; the author calls this an interesting but likely common phenomenon. Pseudo-outcome regressions (IPW, doubly robust) adapt to the CATE's smoothness, with the doubly robust versions more efficient.",
          "Section 2.2",
          "An interesting but likely common phenomenon occurs in this simple example."),
         ("The author states that the meta-learners of Künzel et al. (2019) do not include the DR-Learner and none of them are doubly robust, so in general they would inherit larger error rates from the underlying regression estimators.",
          "Section 4.1",
          "further, none of their methods are doubly robust, and so in general would inherit larger error rates from the underlying regression estimators."),
         ("DR-Learner construction (Algorithm 1): estimate the propensity and both outcome regressions on one sample, form the pseudo-outcome (A - pi_hat)/(pi_hat(1 - pi_hat)) (Y - mu_hat_A) + mu_hat_1 - mu_hat_0, regress it on X in an independent sample, and optionally cross-fit; the motivation is that this is the uncentered efficient influence function of the ATE, so where the standard doubly robust ATE estimator averages it, the DR-Learner regresses it on covariates.",
          "Section 4.2",
          "The DR-Learner approach is motivated by the fact that (2) is the (uncentered) efficient influence function for the ATE [Hahn, 1998, Robins and Rotnitzky, 1995]; this drives many of its favorable properties."),
         ("Theorem 2: if the second-stage regression is stable (Definition 1) and the estimated pseudo-outcome is consistent, the DR-Learner differs from an oracle that regresses the true pseudo-outcome by a smoothed product of propensity and outcome-regression errors (plus a term of smaller order than the oracle risk), so it is oracle efficient when that product term is small; the author states the result is agnostic about the methods and needs no special tuning or undersmoothing, and contrasts it with Foster & Syrgkanis (2019), whose bounds are second-order but not doubly robust (L4 errors of all nuisances).",
          "Section 4.2",
          "Importantly the result is agnostic about the methods used, and requires no special tuning or undersmoothing."),
         ("Corollary 1 (Hölder-smooth propensity alpha, regressions beta, CATE gamma; minimax-optimal linear smoother second stage): the DR-Learner adapts to CATE smoothness, with a sufficient condition for oracle efficiency that approaches the ATE root-n condition sqrt(alpha beta) >= d/2 as the CATE becomes smoother; the author contrasts this with Nie & Wager and Zimmert & Lechner, which required ATE-like n^(-1/4) nuisance rates.",
          "Section 4.3",
          "First, as the CATE smoothness gets larger, the suﬃcient condition (4) for the CATE approaches that for the ATE, as should be expected (intuitively, an inﬁnitely smooth CATE should be nearly as easy to estimate as the ATE)."),
         ("Caveat for the sparse-model analogue of Corollary 1: the author notes that it has not been proved that second-stage estimators attaining the stated sparse rates satisfy the stability condition.",
          "Section 4.3",
          "However we note that we have not proved second-stage estimators attaining these rates satisfy the stability condition of Deﬁnition 1."),
         ("Simulations (plug-in/T-learner, X-learner, DR-Learner, oracle DR-Learner): in the piecewise-polynomial model (n = 2000, 500 simulations, propensity estimates with controlled convergence rate, truncated to [0.01, 0.99]) the DR-Learner's MSE approaches the oracle's as the propensity error shrinks, with the X-learner between plug-in and DR; in a high-dimensional sparse logistic model with zero CATE (d = 500, alpha = beta = 50, n = 200 and 2000, 100 simulations, cross-validated lasso, median MSE reported), the DR-Learner is closer to the oracle and its relative performance seems to improve with sample size.",
          "Section 4.4",
          "The relative performance of the DR-Learner seems to improve with sample size."),
         ("Limits: the lp-R-Learner attains oracle efficiency under weaker nuisance-smoothness conditions than the DR-Learner bound in a Hölder model (but is harder to compute and requires undersmoothing, Remark 8); the abstract conjectures that these conditions are minimal in a minimax sense, but the Discussion states that whether the rates of Corollaries 2 and 3 are minimax optimal is one of the deepest open questions.",
          "Section 6",
          "One of the deepest open questions is whether the rates given in Corollaries 2 and 3 are minimax optimal or not (in the ﬁxed and random design setups, respectively)."),
     ],
     "notes": "Affiliation: Carnegie Mellon University. PDF is arXiv v5 (21 Aug 2023); no venue is stated in the PDF and the arXiv record has no journal_ref, so none is recorded. Single author; the paper cites the author's own earlier work (Kennedy et al. 2017 dose-response; Kennedy 2022 review) for related phenomena, but no own-software benchmarking. Simulation MSEs are figure-only; not recorded. Section 2.2 also reports, across 500 simulations of the illustration, bias and variance ratios between IPW and doubly robust estimators (body text); not recorded as a claim."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
