import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1906.01629",
     "title": "Exact Combinatorial Optimization with Graph Convolutional Neural Networks",
     "authors": ["Maxime Gasse", "Didier Chételat", "Nicola Ferroni", "Laurent Charlin", "Andrea Lodi"],
     "year": 2019, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1906.01629", "code": "https://github.com/ds4dm/learn2branch"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["branch-and-bound", "graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["GCNN branching policy: a bipartite (variable-constraint) graph convolutional network that selects the branching variable in MILP branch-and-bound, trained by behavioral cloning (cross-entropy) of strong branching decisions"],
     "claims": [
         ("Relation to B&B: the paper uses ML to improve branch-and-bound, specifically learning the variable selection (branching) policy, with a graph convolutional network over the variable-constraint bipartite graph of the MILP.",
          "Abstract",
          "We propose a new graph convolutional neural network model for learning branch-and-bound variable selection policies, which leverages the natural variable-constraint bipartite graph representation of mixed-integer linear programs."),
         ("Learned decision and training target: the policy imitates strong branching via behavioral cloning with a cross-entropy loss, which the authors describe as an easier task than predicting strong branching scores or rankings (as done in earlier works they cite).",
          "Introduction",
          "Second, we approximate strong branching decisions by using behavioral cloning with a cross-entropy loss, a less difficult task than predicting strong branching scores [4] or rankings [30; 24]."),
         ("Exactness: in the B&B framework described, the solving process stops when upper and lower bounds are equal (or the feasible regions no longer decompose), giving a certificate of optimality or infeasibility. The learned policy replaces only the choice of the fractional variable to branch on, so B&B keeps this stopping rule (our reading; the paper calls B&B 'the exact method of choice' for MILPs but does not separately prove or state that the learned policy preserves exactness, and instances can remain unsolved within the 1-hour time limit).",
          "Background",
          "The solving process stops whenever both the upper and lower bounds are equal or when the feasible regions do not decompose anymore, thereby providing a certificate of optimality or infeasibility, respectively."),
         ("Solver settings: SCIP 6.0.1 is the backend with a 1-hour time limit; cutting planes are allowed at the root node only and solver restarts are deactivated (following prior work), with all other SCIP parameters at default.",
          "Experiments",
          "Throughout all experiments we use SCIP 6.0.1 as the backend solver, with a time limit of 1 hour."),
         ("Train vs test sizes: models are trained on small (Easy) instances and evaluated on Easy, Medium and Hard instances; e.g. for set covering (1,000 columns) training uses 500 rows and evaluation uses 500, 1,000 and 2,000 rows. The other benchmarks (combinatorial auction, capacitated facility location, maximum independent set) are scaled analogously.",
          "Experiments",
          "We train and test on instances with 500 rows, and we evaluate on instances with 500 (Easy), 1,000 (Medium) and 2,000 (Hard) rows."),
         ("Critique of prior learned-branching work (Khalil et al., Alvarez et al., Hansknecht et al.): those works evaluated on a simplified solver, whereas this paper compares against a full-fledged solver with primal heuristics, cuts and presolving activated (the authors also note those works did not evaluate generalization to larger instances).",
          "Related work",
          "Finally, in each case performance was evaluated on a simplified solver, whereas we compare, for the first time and favorably, against a full-fledged solver with primal heuristics, cuts and presolving activated."),
         ("Limitation (size generalization): the authors expect the improvement to decrease on progressively larger problems, and in early experiments on even larger ('huge') instances observed a performance drop for the model trained on small instances (a model trained on medium instances did perform well there).",
          "Discussion",
          "In early experiments with even larger instances (huge), we observed a performance drop for the model trained on our small instances."),
     ],
     "notes": "PDF states: NeurIPS 2019. Baselines: SCIP default reliability pseudocost branching (RPB), full strong branching (FSB, the expert), and re-implementations of TREES (Alvarez et al., ExtraTrees), SVMRANK (Khalil et al.) and LMART (Hansknecht et al.) within SCIP. Training data per benchmark: 100,000 branching samples from 10,000 random instances; evaluation on 20 new instances per difficulty with five seeds (100 solves per method). Metrics: imitation accuracy (acc@1/5/10), 1-shifted geometric mean of solving time (unsolved instances counted at their running time without extra penalization), wins, and hardware-independent node counts on instances solved by all methods. All instances are synthetic generator families (set covering after Balas and Ho, combinatorial auctions after Leyton-Brown et al., capacitated facility location after Cornuejols et al., maximum independent set on Erdos-Renyi graphs); no MIPLIB evaluation. The authors state maximum independent set is particularly challenging for generalization (all ML approaches solve fewer instances than RPB). Hardware (supplement): Intel Xeon Gold 6126 CPU and an Nvidia Tesla V100 GPU; the text does not state whether GCNN inference during evaluation ran on the GPU, nor discuss GPU-vs-CPU fairness against RPB (searched 'GPU', 'CPU'). Supplement: ML competitors could not be trained on the full dataset due to computational limitations. Results tables not recorded."},

    {"id": "arxiv-1803.10150",
     "title": "Learning to Branch",
     "authors": ["Maria-Florina Balcan", "Travis Dick", "Tuomas Sandholm", "Ellen Vitercik"],
     "year": 2018, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1803.10150"},
     "tasks": ["combinatorial-optimization", "algorithm-learning"],
     "fam": ["branch-and-bound"], "par": ["supervised"],
     "proposes": ["Data-driven configuration of branch-and-bound variable selection: learn a convex combination of existing scoring rules from samples of an instance distribution by ERM over an adaptive partition of the parameter space, with pseudo-dimension / Rademacher sample complexity guarantees"],
     "claims": [
         ("Relation to B&B: ML is used to configure B&B, learning a weighting of existing partitioning (variable selection) procedures for the instance distribution at hand from sample instances; B&B itself is unchanged.",
          "Abstract",
          "We show how to use machine learning to determine an optimal weighting of any set of partitioning procedures for the instance distribution at hand using samples from the distribution."),
         ("Guarantee type: sample complexity bounds ensuring that empirical performance (e.g. tree size) over sampled instances nearly matches expected performance on the unknown instance distribution; the authors call these the first such guarantees for tree search configuration.",
          "Abstract",
          "These guarantees bound the number of samples sufficient to ensure that the empirical performance of an algorithm over the samples nearly matches its expected performance on the unknown instance distribution."),
         ("Assumptions: an unknown distribution over MILPs with sample access, a cap on the cost range (e.g. tree size capped at kappa), instances over n binary variables, a tree-constant cost function, and everything in tree search except variable selection (e.g. node selection) held fixed.",
          "Section 3",
          "Throughout the remainder of this paper, we assume that all aspects of the tree search algorithm except the variable selection policy, such as the node selection policy, are fixed."),
         ("Worst-case bound for path-wise scoring rules (a class including the most fractional, product and linear scoring rules but not pseudo-cost or reliability branching): for a convex combination of two path-wise rules with a tree-constant cost, over instances with n binary variables and a cost range capped at kappa, the number of samples sufficient for (epsilon, delta)-learning grows only quadratically with the number of variables (pseudo-dimension O(n^2), Theorem 3.7); for d arbitrary scoring rules (Section 3.3.2) the bound instead depends on the tree-size limit imposed on B&B.",
          "Section 3.3",
          "In this case, the number of samples is surprisingly small given the complexity of these problems: it grows only quadratically with the number of variables."),
         ("Impossibility result for data-independent tuning (Theorem 3.1): for the mixing parameter mu in [0, 1] of two specific scoring rules (the min and the max of the objective-value changes of the two children), with cost = B&B tree size, for any discretization of [0, 1] there exists an infinite family of distributions over MILPs with n variables (n even, n >= 6) such that every parameter in the discretization gives expected tree size exponential in n, while infinitely many other parameters (an interval (a, b) with 1/3 < a < b < 1/2) give constant-size trees with probability 1; the authors prove it holds for any node selection policy.",
          "Section 3.2",
          "We show that for any discretization of the parameter space [0, 1], there exists an infinite family of distributions over MILP problem instances such that for any parameter in the discretization, the expected tree size is exponential in n."),
         ("Experimental setup: the variable selection rule of CPLEX 12.8.0.0 is overridden via a branch callback that enumerates all parameter values giving distinct trees; CPLEX cuts, primal heuristics and root-node preprocessing are disabled and node selection is best bound; the measure is average B&B tree size.",
          "Experiments",
          "We use the C API of IBM ILOG CPLEX 12.8.0.0 to override the default variable selection rule using a branch callback."),
         ("Empirical finding: across synthetic distributions (combinatorial auctions from CATS, facility location, clustering, agnostic linear separators) the relationship between the linear scoring rule's parameter and average tree size varies greatly by application, so the authors conclude parameters should be tuned per application and no value is universally effective.",
          "Experiments",
          "This implies that the parameters should be tuned on a per-application basis, and that no parameter value is universally effective."),
     ],
     "notes": "Exactness (our reading, not a statement of the paper): only the variable selection scoring rule changes, so a B&B run to completion remains exact and what is learned affects tree size; note that the theory assumes the cost is capped at kappa (e.g. terminating B&B when the tree grows beyond a bound), so capped runs need not finish. Cited worst case (Liberatore 2000): finding an approximately optimal branching variable, even at the root, is NP-hard (Introduction). The authors contrast their results with SCIP fixing the product/linear mixing parameter at 5/6 (Achterberg 2009) regardless of input (Introduction). Data-dependent Rademacher bounds are given as tighter alternatives when the number of parameter intervals is small. Experiments: m = 100 combinatorial auction instances (CATS 'arbitrary' 200 bids/100 goods, 'regions' 400 bids/200 goods), m = 500 facility location (70x70), clustering (35 points, k = 5), linear separator (50 points) instances; run on 64 AWS c3.large instances. No train/test generalization experiment in the main text figures (tree size vs parameter averaged over samples). Results not recorded."},

    {"id": "arxiv-2012.13349",
     "title": "Solving Mixed Integer Programs Using Neural Networks",
     "authors": ["Vinod Nair", "Sergey Bartunov", "Felix Gimeno", "Ingrid von Glehn", "Pawel Lichocki", "Ivan Lobov", "Brendan O'Donoghue", "Nicolas Sonnerat", "Christian Tjandraatmadja", "Pengming Wang", "Ravichandra Addanki", "Tharindi Hapuarachchi", "Thomas Keck", "James Keeling", "Pushmeet Kohli", "Ira Ktena", "Yujia Li", "Oriol Vinyals", "Yori Zwols"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2012.13349"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["branch-and-bound", "graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["Neural Diving: a generative GNN that produces partial integer assignments whose remaining sub-MIPs are solved by SCIP (primal heuristic)",
                  "Neural Branching: a GNN branching policy imitating an ADMM-based, GPU-batched variant of Full Strong Branching, integrated in SCIP"],
     "claims": [
         ("Relation to B&B: two learned components are plugged into a base MIP solver (SCIP): Neural Diving for finding high-quality assignments (primal side) and Neural Branching for variable selection in branch-and-bound (bounding the gap).",
          "Abstract",
          "Our approach constructs two corresponding neural network-based components, Neural Diving and Neural Branching, to use in a base MIP solver such as SCIP."),
         ("Neural Branching's expert: because a CPU-based Full Strong Branching implementation can be too expensive on large-scale MIPs even for offline data generation, the authors build an FSB variant using ADMM that batches the LP computations on GPU (solving the LPs approximately) to generate imitation data.",
          "Introduction",
          "We develop a variant of FSB using the alternating directions method of multipliers (ADMM) (Boyd et al. 2011) that scales to large-scale MIPs by performing the required computation in a batch manner on GPU."),
         ("Exactness / metric: B&B tracks global primal and dual bounds; a zero primal-dual gap certifies optimality, but in practice B&B is terminated at an application-dependent relative gap, and evaluation reports average primal, dual or primal-dual gap over time plus survival plots.",
          "Background",
          "The gap is always nonnegative by construction, and if it is zero then we have solved the problem, the feasible point that corresponds to the primal bound is optimal and the dual bound is a certificate of optimality."),
         ("Baseline and tuning: the main baseline is SCIP 7.0.1 with its presolving, primal heuristics and cuts emphasis settings tuned per dataset by exhaustive grid search on 200 validation MIPs with a 3-hour limit ('Tuned SCIP').",
          "Evaluation",
          "The main baseline we compare against is SCIP 7.0.1 with its parameters tuned for each test dataset."),
         ("Hardware fairness: in the joint comparison (only the sequential version of Neural Diving), Neural Diving (Sequential) and Neural Branching each use a CPU core and a GPU, so their combination uses two cores and two GPUs; Tuned SCIP is given two cores, used as two independent solves with different seeds (best bounds across the two runs), and GPU use is explicitly not controlled for.",
          "Joint evaluation",
          "Since SCIP does not use GPUs, we do not control for that resource when comparing Tuned SCIP and Neural Solvers."),
         ("Data splits: all datasets except MIPLIB are split randomly into disjoint 70/15/15% train/validation/test subsets (so, in our reading, test instances come from the same dataset rather than from a larger size class); for MIPLIB the 2017 Benchmark Set is the test set, and the 2017 Collection Set and the 2010 set (after removing overlaps with the Benchmark Set) are the training and validation sets, respectively.",
          "Datasets",
          "For MIPLIB, we use instances from the MIPLIB 2017 Benchmark Set as the test set, since that is the set on which solvers are evaluated."),
         ("Limitation (Neural Diving): the authors believe its strength is finding good solutions quickly but that it sometimes fails to find optimal or near-optimal solutions, e.g. losing to SCIP at the end on Electric Grid Optimization and MIPLIB survival plots.",
          "Neural Diving results",
          "We believe that the strength of our approach is in quickly finding good solutions, but it sometimes fails to find an optimal or near-optimal solution."),
     ],
     "notes": "Affiliations: DeepMind and Google Research (two datasets are Google production datasets). Datasets: CORLAT, NN Verification, Google Production Packing, Google Production Planning, Electric Grid Optimization, MIPLIB; most instances have 10^3-10^6 variables and constraints after SCIP presolve. Commercial solvers: the authors state lack of access to solver internals makes a fair comparison to commercial solvers infeasible; a partial Gurobi comparison (Neural Diving with Gurobi as sub-MIP solver, non-calibrated time) is reported on two datasets. Time is 'calibrated time' measured via periodic calibration-MIP solves on a heterogeneous shared cluster (>160,000 MIP solves, nearly a million CPU and GPU hours). Best known primal bound p* precomputed by SCIP default with a 24-hour limit. SCIP relative gap set to 0 in Neural Diving experiments to avoid premature stopping. When Neural Diving is used inside SCIP, SCIP's built-in primal heuristics are disabled. Imitation learning variant (behavioral cloning, distillation with random moves, one DAgger iteration) chosen per dataset on validation dual gap. Exactness (our reading, not stated as such by the paper): Neural Branching only selects the branching variable inside SCIP's B&B; Neural Diving solves sub-MIPs with fixed variables, so on its own it gives primal solutions without an optimality proof. Results not recorded."},

    {"id": "arxiv-1704.01701",
     "title": "Learning Certifiably Optimal Rule Lists for Categorical Data",
     "authors": ["Elaine Angelino", "Nicholas Larus-Stone", "Daniel Alabi", "Margo Seltzer", "Cynthia Rudin"],
     "year": 2017, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1704.01701", "code": "https://github.com/nlarusstone/corels"},
     "tasks": ["tabular-classification"],
     "fam": ["branch-and-bound", "interpretable-models", "decision-trees"], "par": ["supervised"],
     "proposes": ["CORELS: a specialized branch-and-bound algorithm over pre-mined antecedents that finds rule lists minimizing misclassification error plus lambda times rule-list length, with a certificate of optimality, using a prefix trie, priority queue and symmetry-aware map"],
     "claims": [
         ("Relation to B&B: B&B is used inside an ML method (rule-list learning) to find the optimal rule list according to the training objective (a regularized empirical risk, within the class of rule lists assembled from pre-mined frequent itemsets), with a certificate of optimality that allows investigating how close other models (e.g. from greedy algorithms) are to optimal.",
          "Introduction",
          "Specifically, we introduce a special branch-and bound algorithm, called Certifiably Optimal RulE ListS (CORELS), that provides the optimal solution according to the training objective, along with a certificate of optimality."),
         ("Bounds: CORELS keeps a lower bound on the objective achievable by each incomplete rule list (prefix) and prunes the prefix and all its extensions when the bound exceeds the best rule list found so far; the hierarchical bound is the fraction of data captured and misclassified by the prefix plus lambda times the prefix length.",
          "Introduction",
          "Within its branch-and-bound procedure, CORELS maintains a lower bound on the minimum value of R that each incomplete rule list can achieve."),
         ("Scope of the optimality guarantee: optimality is with respect to the regularized training objective R (misclassification + lambda x length) over rule lists built from pre-mined rules; because each rule in an optimal rule list must have sufficiently large support (Theorem 10), rule lists can be built from frequent itemsets while preserving the guarantee of finding a globally optimal rule list from the pre-mined rules.",
          "Optimization Framework",
          "This allows us to construct rule lists from frequent itemsets, while preserving the guarantee that we can find a globally optimal rule list from pre-mined rules."),
         ("Contrast with greedy learners (as characterized by the authors): because the optimal decision tree problem is hard, algorithms such as CART and C4.5 do not explore the search space beyond greedy splitting, and many decision-list and associative classification methods construct rule lists greedily; the authors view their problem as a version of the optimal decision tree problem changed by regularization.",
          "Related Work",
          "Because the optimal decision tree problem is hard, there are a huge number of algorithms such as CART (Breiman et al., 1984) and C4.5 (Quinlan, 1993) that do not perform exploration of the search space beyond greedy splitting."),
         ("Baseline protocol: logistic regression, SVM, AdaBoost, CART, C4.5, random forests and RIPPER were run with standard R packages at default parameter settings (a separate figure varies CART/C4.5/RIPPER/SBRL parameters), with 10-fold cross-validation on the ProPublica COMPAS and NYCLU stop-and-frisk data; CORELS and SBRL receive the same antecedent sets, while the other algorithms receive binary features corresponding to the single-clause antecedents.",
          "Experiments",
          "We use standard R packages, with default parameter settings, for the first seven algorithms."),
         ("Finding (ProPublica recidivism): no statistically significant differences in test accuracy across algorithms; variation across folds exceeded variation across algorithms, and all were similar to the COMPAS black box.",
          "Experiments",
          "Figure 9 shows that for the ProPublica data set, there were no statistically significant differences in test accuracies across algorithms, the difference between folds was far larger than the difference between algorithms."),
         ("Limitation: although scaling well in the number of observations, CORELS could have difficulty proving optimality with many possibly relevant, highly correlated features (it also does not directly handle continuous variables and is not designed for non-interpretable raw features such as images).",
          "Conclusion",
          "While our approach scales well to large numbers of observations, it could have difficulty proving optimality for problems with many possibly relevant features that are highly correlated, when large regions of the search space might be challenging to exclude."),
     ],
     "notes": "PDF states: Journal of Machine Learning Research 18 (2018). Objective R = misclassification + lambda * K (e.g. lambda = 0.01 equals misclassifying 1% of data per extra rule). The authors report that the equivalent support and equivalent points bounds gave the most significant improvements, sometimes critical even on small problems (Summary and Future Work on Bounds); the authors state the approach can provide useful results even for incomplete executions, and that on the evaluated data sets CORELS is generally able to find an optimal rule list in seconds and certify optimality within about 10 minutes (Introduction); they report better or similar out-of-sample accuracy compared to CART and C4.5 on these data sets. They state MIP solvers in general cannot compete with CORELS' speed on the Rudin and Ertekin MIP formulation (Related Work). Baselines' defaults: CART cp = 0.01, C4.5 C = 0.25 (footnote). Datasets: ProPublica COMPAS (Broward County) recidivism and NYPD/NYCLU stop-and-frisk weapon prediction; class imbalance handled by resampling training sets for the weapon task. Timing on a single hardware thread of an Intel Xeon E5-2699 v4 server. The authors note the models are predictive, not causal, and not suitable for policy-making on their own. Results not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): algorithm design techniques (divide and conquer, dynamic programming, branch and bound, local search) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
