import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ae_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1312.6114",
     "title": "Auto-Encoding Variational Bayes",
     "authors": ["Diederik P Kingma", "Max Welling"],
     "year": 2013, "version": "arXiv v11",
     "links": {"arxiv": "https://arxiv.org/abs/1312.6114"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["SGVB: a reparameterized, differentiable Monte Carlo estimator of the variational lower bound for models with continuous latent variables",
                  "AEVB: jointly learning a recognition model (probabilistic encoder) and a generative model (probabilistic decoder) with SGVB; with neural networks for both, the variational auto-encoder (VAE)"],
     "claims": [
         ("Contribution: reparameterizing the variational lower bound gives a lower-bound estimator that can be optimized with standard stochastic gradient methods; for i.i.d. data with continuous per-datapoint latent variables, an approximate inference (recognition) model is fitted to the intractable posterior with this estimator.",
          "Abstract",
          "First, we show that a reparameterization of the variational lower bound yields a lower bound estimator that can be straightforwardly optimized using standard stochastic gradient methods."),
         ("Link to autoencoders: in the objective, the KL divergence of the approximate posterior from the prior acts as a regularizer and the second term is an expected negative reconstruction error.",
          "Section 2.3",
          "The ﬁrst term is (the KL divergence of the approximate posterior from the prior) acts as a regularizer, while the second term is a an expected negative reconstruction error."),
         ("Citing Bengio, Courville & Vincent [BCV13], the authors note that the reconstruction criterion alone is known not to be sufficient for learning useful representations, which motivated denoising, contractive and sparse autoencoder variants.",
          "Related work",
          "However, it is well known that this reconstruction criterion is in itself not sufﬁcient for learning useful representations [BCV13]."),
         ("In contrast to those regularized autoencoders, the regularization term in the SGVB objective is dictated by the variational bound, without the usual regularization hyperparameter.",
          "Related work",
          "The SGVB objective contains a regularization term dictated by the variational bound (e.g. eq. (10)), lacking the usual nuisance regularization hyperparameter required to learn useful representations."),
         ("The diagonal-Gaussian approximate posterior used in the VAE example is described as a simplifying choice, not a limitation of the method.",
          "Example: Variational Auto-Encoder (footnote 2)",
          "Note that this is just a (simplifying) choice, and not a limitation of our method."),
         ("Evaluation setup: generative models of MNIST and Frey Face images are compared on the variational lower bound and on an estimated marginal likelihood, against the wake-sleep algorithm (same encoder) and, for marginal likelihood, Monte Carlo EM; the Adagrad step size was chosen from three values based on training-set performance in the first few iterations.",
          "Experiments",
          "the Adagrad global stepsize parameters were chosen from {0.01, 0.02, 0.1} based on performance on the training set in the ﬁrst few iterations."),
         ("The authors state (Figure 2 caption) that AEVB converged considerably faster than wake-sleep and reached a better lower bound in all experiments; the comparison is shown only as a figure.",
          "Figure 2",
          "Our method converged considerably faster and reached a better solution in all experiments."),
         ("Adding superfluous latent variables did not cause overfitting in these experiments, which the authors attribute to the regularizing nature of the variational bound.",
          "Experiments",
          "Interestingly, superﬂuous latent variables did not result in overﬁtting, which is explained by the regularizing nature of the variational bound."),
         ("Limitation of the evaluation: the marginal likelihood could only be estimated (by MCMC) for a 3-dimensional latent space, because for higher-dimensional latent spaces the estimates became unreliable.",
          "Experiments",
          "for higher dimensional latent space the estimates became unreliable."),
         ("Decomposition of the marginal likelihood (Eq. 1-2): for each datapoint, log p_theta(x) equals the KL divergence of the approximate posterior from the true posterior plus L(theta, phi; x); since the KL divergence is non-negative, L is a (variational) lower bound on the marginal log-likelihood.", "Section 2.2", "The ﬁrst RHS term is the KL divergence of the approximate from the true posterior."),
         ("Reparameterization in the univariate Gaussian case: if z ~ N(mu, sigma^2), a valid reparameterization is z = mu + sigma * epsilon with an auxiliary noise variable epsilon ~ N(0, 1), so expectations over z can be written as expectations over epsilon and estimated by Monte Carlo in a way that is differentiable in the variational parameters.", "Section 2.4", "Take, for example, the univariate Gaussian case: let z ∼p(z|x) = N(µ, σ2)."),
         ("Closed-form KL in the VAE example (Eq. 10): with a standard Gaussian prior p(z) = N(0, I) and a diagonal Gaussian approximate posterior with mean mu and standard deviation sigma output by the encoder, the KL term can be computed and differentiated without estimation, giving the estimator (1/2) sum_j (1 + log sigma_j^2 - mu_j^2 - sigma_j^2) + (1/L) sum_l log p_theta(x | z^(l)) with z^(l) = mu + sigma ⊙ epsilon^(l).", "Example: Variational Auto-Encoder", "where the KL divergence can be computed and differentiated without estimation"),
     ],
     "notes": "Affiliation: Universiteit van Amsterdam. No venue is stated in the PDF (arXiv v11, 2022 revision). Results are shown as figures only (Figures 2-3); no numbers recorded. The paper also mentions that Rezende et al. (2014) independently made the same connection [RMW14]."},

    {"id": "arxiv-1509.00519",
     "title": "Importance Weighted Autoencoders",
     "authors": ["Yuri Burda", "Roger Grosse", "Ruslan Salakhutdinov"],
     "year": 2015, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1509.00519"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["IWAE: a model with the VAE architecture trained on the k-sample importance-weighted lower bound L_k, which is strictly tighter than the VAE bound (k = 1) and approaches log p(x) as k grows"],
     "claims": [
         ("Motivation: VAEs typically assume an approximately factorial posterior whose parameters can be predicted by nonlinear regression; the authors show empirically that the VAE objective can lead to overly simplified representations that do not use the network's full capacity.",
          "Abstract",
          "VAE objective can lead to overly simpliﬁed representations which fail to use the network’s entire modeling capacity."),
         ("Theorem 1: the bounds are monotone in the number of samples, log p(x) >= L_{k+1} >= L_k, and if p(h,x)/q(h|x) is bounded, L_k approaches log p(x) as k goes to infinity; k = 1 equals the standard VAE objective.",
          "Importance weighted autoencoder",
          "Observe, however, that the special case of k = 1 is equivalent to the standard VAE objective"),
         ("Cost: in the basic implementation the forward and backward passes are done independently for each of the k samples, so the number of operations scales linearly with k.",
          "Training procedure",
          "Therefore, the number of operations scales linearly with k."),
         ("Evaluation protocol: held-out log-likelihood on binarized MNIST and Omniglot (standard splits), estimated as the mean of L_5000 on the test set (a stochastic lower bound); VAE and IWAE trained for k in {1, 5, 50} for about the same time; the learning-rate schedule was chosen from preliminary experiments with a one-layer VAE on MNIST.",
          "Evaluation on density estimation",
          "All log-likelihood values were estimated as the mean of L5000 on the test set."),
         ("The authors note that the generative-modelling literature binarizes MNIST inconsistently and that different binarizations can lead to considerably different log-likelihood values.",
          "Evaluation on density estimation (footnote 2)",
          "Unfortunately, the generative modeling literature is inconsistent about the method of binarization, and different choices can lead to considerably different log-likelihood values."),
         ("Inactive latent dimensions: both VAEs and IWAEs learned representations with effective dimensions far below their capacity (a dimension counted as active if the covariance over x of its posterior mean exceeds 10^-2); with k > 1 the IWAE learned more active dimensions than the VAE in all cases.",
          "Latent space representation",
          "We have observed that both VAEs and IWAEs tend to learn latent representations with effective dimensions far below their capacity."),
         ("Swapping objectives after training (VAE continued with the IWAE objective and vice versa) changed the number of active dimensions and the log-likelihood in the direction of the new objective, which the authors take as strong evidence that inactivation is driven by the objective rather than by optimization, while noting that optimization also appears to play a role.",
          "Latent space representation",
          "The fact that training with the VAE objective actively reduces both the number of active dimensions and the log-likelihood strongly suggests that inactivation of the latent dimensions is driven by the objective functions rather than by optimization issues."),
     ],
     "notes": "Affiliation: University of Toronto; acknowledgments list support from NSERC, the Fields Institute and Samsung. The PDF header says 'Under review as a conference paper at ICLR 2016'; no venue recorded. The paper notes that the importance-weighted bound for VAEs was independently explored by Laurent Dinh and Vincent Dumoulin. Results tables (Table 1, Table 2) not recorded."},

    {"id": "arxiv-1511.06349",
     "title": "Generating Sentences from a Continuous Space",
     "authors": ["Samuel R. Bowman", "Luke Vilnis", "Oriol Vinyals", "Andrew M. Dai", "Rafal Jozefowicz", "Samy Bengio"],
     "year": 2015, "venue": "CoNLL 2016", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1511.06349"},
     "tasks": ["generative-modeling", "language-modeling", "representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["An LSTM-based VAE for sentences with a global latent code, trained with KL cost annealing and word dropout in the decoder; an adversarial-classifier evaluation for imputing missing words"],
     "claims": [
         ("Motivating observation: decoding points on a path between two sentence encodings of a conventional (sequence) autoencoder gives intermediate sentences that are generally ungrammatical (Table 1), which the authors take to suggest that standard autoencoders do not learn a smooth, interpretable sentence feature space.",
          "Background",
          "Standard autoencoders are not eﬀective at extracting for global semantic features."),
         ("Optimization failure (posterior collapse): straightforward implementations fail to encode information in the latent variable; except in vanishingly rare cases, most training runs with most hyperparameters set the approximate posterior equal to the prior, bringing the KL term to zero, and the model then behaves as an RNN language model.",
          "Optimization challenges",
          "Straightforward implementations of our vae fail to learn this behavior"),
         ("Proposed mechanism: the LSTM decoder is sensitive to small variations in the hidden state, so the model first learns to ignore the latent code; afterwards the decoder ignores the encoder and little gradient passes between them, an undesirable stable equilibrium with the KL term at zero.",
          "Optimization challenges",
          "Once this has happened, the decoder ignores the encoder and little to no gradient signal passes between the two, yielding an undesirable stable equilibrium with the kl cost term at zero."),
         ("KL cost annealing: the weight on the KL term starts at zero and is gradually increased to 1, so the true lower bound is not optimized early in training; the authors describe it as annealing from a vanilla autoencoder to a VAE, with the rate tuned as a hyperparameter.",
          "KL cost annealing",
          "This can be thought of as annealing from a vanilla autoencoder to a vae."),
         ("Word dropout: replacing a fraction of the conditioned-on previous words with an unknown-word token weakens the decoder and forces it to rely on the latent variable; standard dropout on decoder input embeddings did not help the model use the latent variable.",
          "Word dropout and historyless decoding",
          "This forces the model to rely on the latent variable"),
         ("Without both word dropout and KL annealing, training in the standard setting reliably gives models equivalent to the baseline RNN language model with zero KL divergence.",
          "Results: Language modeling",
          "Training a vae in the standard setting without both word dropout and cost annealing reliably results in models with equivalent performance to the baseline rnnlm, and zero kl divergence."),
         ("Evaluation caveats on Penn Treebank language modelling: the VAE hyperparameter search was restricted to models encoding a non-trivial amount in the latent variable, and the VAE is reported with a variational lower bound while the RNNLM is reported with its exact likelihood, which the authors note puts the VAE at a potential disadvantage. In the standard setting the VAE performs slightly worse than the RNNLM.",
          "Results: Language modeling",
          "This discrepancy puts the vae at a potential disadvantage."),
         ("Even with these techniques the authors could not train models in which the KL term dominates the reconstruction term, which they take to suggest that it is substantially easier to model the data with local statistics, so the encoder only encodes what those statistics cannot describe.",
          "Results: Language modeling",
          "This suggests that it is still substantially easier to learn to factor the data distribution using simple local statistics"),
     ],
     "notes": "Affiliations: Stanford University, University of Massachusetts Amherst, Google Brain; the footnote states that the work was done when all authors were at Google. Venue from the arXiv journal_ref (SIGNLL Conference on Computational Natural Language Learning (CONLL), 2016). Results tables (Penn Treebank, imputation) not recorded."},

    {"id": "arxiv-1611.02731",
     "title": "Variational Lossy Autoencoder",
     "authors": ["Xi Chen", "Diederik P. Kingma", "Tim Salimans", "Yan Duan", "Prafulla Dhariwal", "John Schulman", "Ilya Sutskever", "Pieter Abbeel"],
     "year": 2016, "venue": "ICLR 2017", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1611.02731"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["Variational Lossy Autoencoder (VLAE): a VAE with an autoregressive-flow prior and a small-receptive-field autoregressive (PixelCNN) decoder, so that the latent code only carries information the decoder cannot model locally (a lossy code)"],
     "claims": [
         ("Thesis: VAEs are often interpreted as regularized autoencoders, but they do not always autoencode; the paper explains why earlier sequence VAEs did not use the latent code unless the decoder was weakened.",
          "VAEs do not autoencode in general",
          "In this section, we discuss the often-neglected fact that VAEs do not always autoencode"),
         ("Argument from bits-back coding: ignoring the latent code is not only an optimization problem; even with exact optimization, the code should be ignored at the optimum for most practical VAEs with intractable true posteriors and sufficiently powerful decoders.",
          "Section 2.2",
          "the latent code should still be ignored at optimum for most practical instances of VAE that have intractable true posterior distributions and sufﬁciently powerful decoders."),
         ("Information preference: information that the decoder can model locally without the latent code will be modelled by the decoder, and only the remainder is put into the code.",
          "Section 2.2",
          "information that can be modeled locally by decoding distribution p(x|z) without access to z will be encoded locally and only the remainder will be encoded in z."),
         ("Factorized decoders: because the required independence structure rarely exists in images, common VAEs with factorized decoders autoencode almost exactly.",
          "Section 2.2",
          "This kind of independence structure rarely exists in images so common VAEs that have factorized decoder autoencode almost exactly."),
         ("The information-preference argument is asymptotic (it holds only when the bound can be optimized well); the authors still use free bits and KL annealing to smooth optimization in their experiments.",
          "Lossy code via explicit information placement",
          "We want to additionally emphasize the information preference property is an asymptotic view in a sense that it only holds when the variational lowerbound can be optimized well."),
         ("Limitation: the lossy code does not always capture the global information one cares about; on OMNIGLOT, decompressions sometimes did not preserve semantics, so the decoder constraint has to be designed for the statistics that matter in each task and dataset.",
          "Lossy compression",
          "However, we remark that the lossy code z doesn’t always capture the kind of global information that we care about and it’s dependent on the type of constraint we put on the decoder."),
         ("Evaluation protocol for density estimation: one VLAE architecture with hyperparameters chosen manually on statically binarized MNIST is applied to dynamically binarized MNIST, OMNIGLOT and Caltech-101 Silhouettes; marginal NLL is estimated with importance sampling (4096 samples). The authors note that per-dataset tuning gives better results and report a fine-tuned VLAE on OMNIGLOT separately.",
          "Density estimation",
          "We choose hyperparameters manually on statically binarized MNIST and use the same hyperparameters to evaluate on dynamically binarized MNIST, OMNIGLOT and Caltech-101 Silhouettes."),
     ],
     "notes": "Affiliations: UC Berkeley and OpenAI. Venue from the PDF header ('Published as a conference paper at ICLR 2017'). Disclosure: Kingma (an author) is also first author of the VAE paper (arxiv-1312.6114) and of the IAF VAE baseline (Kingma et al., 2016) that VLAE is compared with. Results tables (NLL on MNIST, OMNIGLOT, Caltech-101, CIFAR10) not recorded."},

    {"id": "arxiv-1911.02469",
     "title": "Don't Blame the ELBO! A Linear VAE Perspective on Posterior Collapse",
     "authors": ["James Lucas", "George Tucker", "Roger Grosse", "Mohammad Norouzi"],
     "year": 2019, "venue": "NeurIPS 2019", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1911.02469", "url": "https://sites.google.com/view/dont-blame-the-elbo"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["An analysis of posterior collapse through linear VAEs and their correspondence with probabilistic PCA, and an (epsilon, delta)-collapse definition for measuring posterior collapse in trained VAEs"],
     "claims": [
         ("Prevailing view being challenged: most existing papers attribute posterior collapse to the KL term in the ELBO, and many heuristics try to diminish the effect of the KL term.",
          "Introduction",
          "Most existing papers suggest that posterior collapse is caused by the KL-divergence term in the ELBO objective, which directly encourages the variational distribution to match the prior [7, 25, 38]."),
         ("Theoretical result: for a linear VAE, the ELBO does not introduce any spurious local maxima beyond those of the log marginal likelihood of probabilistic PCA, and its global optimum recovers the (scaled) principal components as the decoder columns.",
          "Analysis of linear VAE",
          "Theorem 1. The ELBO objective for a linear VAE does not introduce any additional local maxima to the pPCA model.", 5),
         ("Posterior collapse can occur when optimizing the exact log marginal likelihood even without powerful decoders: in pPCA, collapsed stationary points (zeroed decoder columns) become stable local maxima as the observation noise sigma^2 grows, so learning sigma^2 is necessary for a full latent representation.",
          "Analysis of linear VAE",
          "Therefore, learning σ2 is necessary for gaining a full latent representation."),
         ("Critique of KL annealing (with Bowman et al. cited among its users): during annealing one is no longer optimizing a bound on the log-likelihood, schedules are hard to design, and the authors found that the posterior typically collapses again once regular ELBO training resumes.",
          "Related work",
          "Also, it is difﬁcult to design these annealing schedules and we have found that once regular ELBO training resumes the posterior will typically collapse again (Section 6.2)."),
         ("Measurement: the authors note that posterior collapse has not been measured or defined consistently and define a latent dimension as (epsilon, delta)-collapsed if its per-example KL to the prior is below epsilon for at least a 1 - delta fraction of the data (delta fixed at 0.01).",
          "Section 6.2",
          "Despite the large volume of work studying posterior collapse it has not been measured in a consistent way (or even deﬁned so)."),
         ("Deep nonlinear VAEs (MNIST, CelebA, Gaussian observation model): many public implementations fix sigma^2 = 1, which the linear analysis suggests is suboptimal; with large initial sigma^2 the variational distribution matched the prior closely even when sigma^2 was learned, suggesting that local optima may contribute to posterior collapse in deep VAEs.",
          "Section 6.2",
          "This was true even when σ2 is learned — suggesting that local optima may contribute to posterior collapse in deep VAEs."),
         ("The gap between different sigma^2 initializations when sigma^2 is learned is not predicted by the linear VAE, which the authors take to suggest that learning sigma^2 correctly is more challenging in the nonlinear case.",
          "Section 6.2",
          "The linear VAE does not predict this gap which suggests that learning σ2 correctly is more challenging in the nonlinear case."),
     ],
     "notes": "Affiliations: University of Toronto and Google Brain (first author an intern at Google Brain). Venue from the PDF footer ('33rd Conference on Neural Information Processing Systems (NeurIPS 2019)'). The nonlinear experiments report training-set ELBO only (Table 1). Results tables not recorded."},
    {"id": "arxiv-1804.03599",
     "title": "Understanding disentangling in β-VAE",
     "authors": ["Christopher P. Burgess", "Irina Higgins", "Arka Pal", "Loic Matthey", "Nick Watters", "Guillaume Desjardins", "Alexander Lerchner"],
     "year": 2018, "venue": "NIPS 2017 Workshop on Learning Disentangled Representations", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1804.03599"},
     "tasks": ["representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["An information-bottleneck / rate-distortion account of why beta-VAE learns axis-aligned disentangled representations, and a training regime that replaces the fixed beta-weighted KL with a penalty on the deviation of the KL from a target capacity C that is increased gradually during training (called AnnealedVAE by later work, e.g. arxiv-1811.12359)"],
     "claims": [
         ("Citing the original beta-VAE paper [15], the authors state that the higher beta values needed for disentangling often trade reconstruction fidelity against how disentangled the latent code is, due to information lost through the restricted-capacity bottleneck.",
          "β-VAE",
          "Higher values of β necessary to encourage disentangling often lead to a trade-off between the ﬁdelity of β-VAE reconstructions and the disentangled nature of its latent code z (see Fig. 6 in [15])."),
         ("Information-theoretic view: treating each latent unit of the diagonal-Gaussian posterior as an additive white Gaussian noise channel, the KL term can be seen as an upper bound on the information transmitted through the latent channels per data sample.",
          "β-VAE through the information bottleneck perspective",
          "can be seen as an upper bound on the amount of information that can be transmitted through the latent channels per data sample"),
         ("Key hypothesis: beta-VAE finds latent components that make different contributions to the log-likelihood term, and the diagonal posterior covariance pushes these components into separate latent dimensions, which may align them with the generative factors.",
          "β-VAE aligns latent dimensions with components that make different contributions to reconstruction",
          "Our key hypothesis is that β-VAE ﬁnds latent components which make different contributions to the log-likelihood term of the cost function (Eq. 5)."),
         ("Illustration on a dataset with two factors (x and y position of a Gaussian blob): the standard VAE (beta = 1) spread the two factors across four latent dimensions with representational discontinuities, while beta-VAE (beta = 150) represented them in two.",
          "Comparing disentangling in β-VAE and VAE",
          "The standard VAE learns to represent these two factors across four latent dimensions, whereas β-VAE represents them in two."),
         ("Proposed modification: the objective penalizes the absolute deviation of the KL from a target capacity C, and C is gradually increased from zero to a value large enough for good reconstructions.",
          "Improving disentangling in β-VAE with controlled capacity increase",
          "Similar to the generator model, C is gradually increased from zero to a value large enough to produce good quality reconstructions (see Sec. A.2 for more details)."),
         ("Evaluation is qualitative: results on coloured dSprites and 3D Chairs are shown as latent traversals and reconstructions judged by eye; no quantitative disentanglement metric was found in the text (searched for 'metric' and 'quantitative').",
          "Improving disentangling in β-VAE with controlled capacity increase",
          "Furthermore, the quality of the traversal images are high, and by eye, the model reconstructions (second row) are quite difﬁcult to distinguish from the corresponding data samples used to generate them (top row)."),
         ("On 3D Chairs, the authors note that it is unclear what the disentangled axes should correspond to.",
          "Improving disentangling in β-VAE with controlled capacity increase",
          "With this richer dataset it is unclear exactly what the disentangled axes should correspond to"),
     ],
     "notes": "Affiliation: DeepMind. Venue from the arXiv comment ('Presented at the 2017 NIPS Workshop on Learning Disentangled Representations'); the PDF footer reads '31st Conference on Neural Information Processing Systems (NIPS 2017)'. Disclosure: several authors (Higgins, Burgess, Matthey, Lerchner and others) are authors of the original beta-VAE paper [15] that this paper analyses and modifies. arxiv-1811.12359 includes this method as 'AnnealedVAE' in its large-scale study."},

    {"id": "arxiv-1811.12359",
     "title": "Challenging Common Assumptions in the Unsupervised Learning of Disentangled Representations",
     "authors": ["Francesco Locatello", "Stefan Bauer", "Mario Lucic", "Gunnar Rätsch", "Sylvain Gelly", "Bernhard Schölkopf", "Olivier Bachem"],
     "year": 2018, "venue": "ICML 2019", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1811.12359", "code": "https://github.com/google-research/disentanglement_lib"},
     "tasks": ["representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["An impossibility theorem for unsupervised disentanglement without inductive biases on models and data", "A large-scale reproducible study (disentanglement_lib) of six VAE-based disentanglement methods and six disentanglement metrics on seven datasets"],
     "claims": [
         ("Theoretical result: unsupervised learning of disentangled representations is fundamentally impossible without inductive biases on both the models and the data (for factorized priors, there are infinitely many completely entangled bijections of z with the same marginal distribution, so observations alone cannot distinguish them).",
          "Abstract",
          "We ﬁrst theoretically show that the unsupervised learning of disentangled representations is fundamentally impossible without inductive biases on both the models and the data."),
         ("Study design: six methods (beta-VAE, AnnealedVAE, FactorVAE, beta-TCVAE, DIP-VAE-I, DIP-VAE-II) with the same convolutional architecture, optimizer, batch size, Gaussian encoder, Bernoulli decoder and 10 latent dimensions; six regularization strengths per method chosen a priori (partly from ranges in the literature); 50 random seeds per setting; more than 12 000 models on seven datasets.",
          "Section 4",
          "We ﬁx our experimental setup in advance and we run all the considered methods on each data set for 50 different random seeds and evaluate them on the considered metrics."),
         ("The methods are effective at making the dimensions of the sampled aggregated posterior uncorrelated, but this does not seem to make the dimensions of the mean representation (the one usually used) uncorrelated; the total correlation of the mean representation generally increases with regularization strength (DIP-VAE-I is an exception).",
          "Section 5.1",
          "this does not seem to imply that the dimensions of the mean representation (usually used for representation) are uncorrelated.", 5),
         ("Across methods, the attainable disentanglement scores overlap heavily; the authors (qualitatively) conclude that hyperparameters and random seeds seem substantially more important than the choice of objective, and that a good run with a bad hyperparameter can beat a bad run with a good one. They note that the fixed hyperparameter grid means specific models might have done better with other values.",
          "Section 5.3",
          "the choice of hyperparameters and the random seed seems to be substantially more important than the choice of objective function.", 5),
         ("Model selection: unsupervised scores (reconstruction error, KL, ELBO, estimated total correlation) showed no clear pattern of correlation with the disentanglement metrics, so the authors consider selecting models with them unlikely to succeed in practice.",
          "Section 5.4",
          "While we do observe some correlations, no clear pattern emerges which leads us to conclude that this approach is unlikely to be successful in practice.", 7),
         ("Transferring good hyperparameters across datasets or metrics does not allow distinguishing good from bad random seeds on the target task; the authors conclude that unsupervised model selection remains unsolved.",
          "Section 5.4",
          "Unsupervised model selection remains an unsolved problem.", 7),
         ("Downstream usefulness: on the simplest downstream task (predicting the true factors with logistic regression or gradient boosted trees), higher disentanglement scores did not reliably lead to higher sample efficiency.",
          "Section 5.5",
          "We do not observe that higher disentanglement scores reliably lead to a higher sample efﬁciency.", 7),
         ("Cost of the study: reproducing the experiments requires approximately 2.52 GPU years (NVIDIA P100); the authors release more than 10 000 trained models.",
          "Section 1 (footnote 1)",
          "Reproducing these experiments requires approximately 2.52 GPU years (NVIDIA P100)."),
     ],
     "notes": "Affiliations: ETH Zurich, Max Planck Institute for Intelligent Systems, Google Research (Brain Team). Venue from the arXiv journal_ref and the PDF (Proceedings of the 36th International Conference on Machine Learning, PMLR 97, 2019). The methods studied include AnnealedVAE (Burgess et al., 2017; arxiv-1804.03599). All datasets are synthetic or rendered with known ground-truth factors (dSprites and three variants, Cars3D, SmallNORB, Shapes3D). Results are shown as figures; Table 1 (transfer vs random selection) not recorded."},

    {"id": "arxiv-1711.00937",
     "title": "Neural Discrete Representation Learning",
     "authors": ["Aaron van den Oord", "Oriol Vinyals", "Koray Kavukcuoglu"],
     "year": 2017, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1711.00937"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["VQ-VAE: an autoencoder whose encoder output is mapped to the nearest vector in a learned codebook (discrete latent), trained with a straight-through gradient, a codebook (VQ) loss and a commitment loss; an autoregressive prior (PixelCNN or WaveNet) is fitted over the discrete codes after training"],
     "claims": [
         ("VQ-VAE differs from VAEs in two ways: the encoder outputs discrete codes, and the prior is learnt rather than static; the authors state that using vector quantisation lets the model circumvent posterior collapse with powerful autoregressive decoders.",
          "Abstract",
          "Using the VQ method allows the model to circumvent issues of “posterior collapse”"),
         ("Training: since the nearest-neighbour lookup has no gradient, gradients are copied from the decoder input to the encoder output (straight-through estimator).",
          "Learning",
          "we approximate the gradient similar to the straight-through estimator [3] and just copy gradients from decoder input zq(x) to encoder output ze(x)."),
         ("The loss adds a codebook term and a commitment term weighted by beta; the authors report that results did not vary for beta between 0.1 and 2.0 and use beta = 0.25 throughout, noting that in general this depends on the scale of the reconstruction loss.",
          "Learning",
          "We found the resulting algorithm to be quite robust to β, as the results did not vary for values of β ranging from 0.1 to 2.0."),
         ("With a deterministic one-hot posterior and a uniform prior, the KL term is a constant (log K) and is ignored in training; the prior is kept uniform during VQ-VAE training and an autoregressive prior is fitted afterwards (joint training left to future work).",
          "Prior",
          "Whilst training the VQ-VAE, the prior is kept constant and uniform."),
         ("The authors could not train with a soft-to-hard relaxation of vector quantisation from scratch because the decoder always learned to invert the continuous relaxation, so no actual quantisation took place.",
          "Related Work",
          "In our experiments we were unable to train using the soft-to-hard relaxation approach from scratch as the decoder was always able to invert the continuous relaxation during training, so that no actual quantisation took place."),
         ("Comparison on CIFAR10 with the same architecture (lower bounds in bits/dim): the continuous VAE obtains a better bound than VQ-VAE, and VQ-VAE a better bound than VIMCO; all reported likelihoods are lower bounds.",
          "Comparison with continuous variables",
          "The VAE, VQ-VAE and VIMCO models obtain 4.51 bits/dim, 4.67 bits/dim and 5.14 respectively."),
         ("ImageNet 128x128 images compressed to a 32x32x1 discrete latent (K = 512) are reconstructed with an MSE-trained deconvolutional decoder and look only slightly blurrier than the originals (qualitative, Figure 2); a perceptual or GAN loss is left to future work.",
          "Images",
          "Even considering that we greatly reduce the dimensionality with discrete encoding, the reconstructions look only slightly blurrier than the originals."),
     ],
     "notes": "Affiliation: DeepMind. No venue recorded: the arXiv record has no comment or journal_ref, and the PDF footer ('31st Conference on Neural Information Processing Systems (NIPS 2017)') also appears on a workshop paper in this set (arxiv-1804.03599), so it is not treated as confirmation. Bowman et al. (arxiv-1511.06349) and VLAE (arxiv-1611.02731) describe the posterior collapse problem that this paper says VQ-VAE avoids. NVAE (arxiv-2007.03898) notes that VQ-VAE's objective does not correspond to a lower bound on data log-likelihood."},

    {"id": "arxiv-2007.03898",
     "title": "NVAE: A Deep Hierarchical Variational Autoencoder",
     "authors": ["Arash Vahdat", "Jan Kautz"],
     "year": 2020, "venue": "NeurIPS 2020", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2007.03898", "code": "https://github.com/NVlabs/NVAE"},
     "tasks": ["generative-modeling"],
     "fam": ["variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["NVAE: a deep hierarchical VAE for images built from depthwise-separable residual cells with batch normalization, Swish and squeeze-and-excitation, a residual parameterization of the approximate posterior relative to the prior, and spectral regularization to stabilize training"],
     "claims": [
         ("Positioning: VAEs offer fast sampling and easy-to-access encoders but are currently outperformed by normalizing flows and autoregressive models; most VAE research focuses on statistical challenges, while this paper focuses on neural architecture design for hierarchical VAEs.",
          "Abstract",
          "However, they are currently outperformed by other models such as normalizing ﬂows and autoregressive models."),
         ("Training instability: due to the unbounded KL term, training very deep hierarchical VAEs is often unstable; the authors observe that instability remains a major roadblock as the number of hierarchical groups increases, independent of batch normalization.",
          "Introduction",
          "We also observe that instability of training remains a major roadblock when the number of hierarchical groups is increased, independent of the presence of BN."),
         ("Batch normalization: earlier state-of-the-art VAEs omitted BN; the authors observed that BN's negative impact occurs during evaluation (running statistics shift the outputs), and address it by adjusting the BN momentum and regularizing the norm of BN scaling parameters.",
          "Section 3.1",
          "In our early experiments, we observed that the negative impact of BN is during evaluation, not training."),
         ("Spectral regularization: residual Normal distributions alone do not stabilize training because the KL is still unbounded; the authors add a penalty on the largest singular value of each layer to keep encoder outputs bounded.",
          "Section 3.2",
          "The residual Normal distributions do not sufﬁce for stabilizing VAE training as KL in Eq. 2 is still unbounded."),
         ("Architecture over statistics: NVAE's performance is only slightly improved by adding normalizing flows in the encoder, which the authors take to indicate that network architecture is an important component of VAEs.",
          "Section 4.1",
          "This indicates that the network architecture is an important component in VAEs and a carefully designed network with Normal distributions in encoder can compensate for some of the statistical challenges."),
         ("Sampling protocol for the shown images: samples are drawn with a reduced prior temperature (which often improves quality but reduces diversity), and BN statistics are readjusted by sampling 500 times at that temperature; the quantitative evaluation uses the default BN setting.",
          "Section 4.2",
          "This is done by scaling down the standard deviation of the Normal distributions in each conditional in the prior, and it often improves the quality of the samples, but it also reduces their diversity."),
         ("Comparison with VQ-VAE-2 (Related Work): although VQ-VAE is motivated by VAEs, its objective does not correspond to a lower bound on the data log-likelihood, whereas NVAE is trained directly with the VAE objective.",
          "Introduction (Related Work)",
          "Although VQ-VAE’s formulation is motivated by VAEs, its objective does not correspond to a lower bound on data log-likelihood."),
     ],
     "notes": "Affiliation: NVIDIA (no conflict-of-interest statement found; mixed precision uses the NVIDIA APEX library). Venue from the arXiv comment (NeurIPS 2020, spotlight) and the PDF footer. Results tables (bits/dim on MNIST, CIFAR-10, ImageNet 32, CelebA 64, CelebA HQ, FFHQ; ablations on CIFAR-10) not recorded; the abstract's state-of-the-art claim is among non-autoregressive likelihood-based models."},
    {"id": "arxiv-1903.12436",
     "title": "From Variational to Deterministic Autoencoders",
     "authors": ["Partha Ghosh", "Mehdi S. M. Sajjadi", "Antonio Vergari", "Michael Black", "Bernhard Schölkopf"],
     "year": 2019, "venue": "ICLR 2020", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1903.12436", "code": "https://github.com/ParthaEth/Regularized_autoencoders-RAE-"},
     "tasks": ["generative-modeling", "representation-learning"],
     "fam": ["autoencoders", "variational-autoencoders"], "par": ["unsupervised"],
     "proposes": ["Regularized Autoencoders (RAE): deterministic autoencoders whose loss is reconstruction + a latent-norm penalty + an explicit decoder regularizer (weight decay, gradient penalty or spectral normalization), replacing the VAE's noise injection and KL term",
                  "Ex-post density estimation: fitting a Gaussian or a 10-component GMM to the latent codes after training, to sample from RAEs and to reduce the aggregated-posterior mismatch of VAEs and WAEs"],
     "claims": [
         ("Citing several works, the authors state that even after convergence the learned aggregated posterior of a VAE rarely matches the assumed prior, which hurts the quality of generated samples.",
          "Introduction",
          "Lastly, even after a satisfactory convergence of the objective, the learned aggregated posterior distribution rarely matches the assumed latent prior in practice (Kingma et al., 2016; Bauer & Mnih, 2019; Dai & Wipf, 2019), ultimately hurting the quality of generated samples."),
         ("Key observation: with the common Gaussian assumptions and a 1-sample estimate, a VAE can be viewed as a deterministic autoencoder whose decoder input is perturbed with Gaussian noise; the authors argue this noise injection is a key factor in regularizing the decoder.",
          "Deterministic regularized autoencoders",
          "In this light, a VAE can be seen as a deterministic autoencoder where (Gaussian) noise is added to the decoder’s input."),
         ("Proposal: replace noise injection with explicit decoder regularization, giving a deterministic Regularized Autoencoder; without the KL term there is no fixed prior, so a generative mechanism must be regained separately.",
          "Deterministic regularized autoencoders",
          "We propose to substitute noise injection with an explicit regularization scheme for the decoder."),
         ("Ex-post density estimation (fitting a density to the latent codes after training) is proposed for RAEs and, according to the authors, can be applied to any VAE or WAE as a remedy for aggregated-posterior mismatch without adding cost to training.",
          "Ex-post density estimation",
          "This simple approach not only ﬁts our RAE framework well, but it can also be readily adopted for any VAE or variants thereof such as the WAE as a practical remedy to the aggregated posterior mismatch without adding any computational overhead to the costly training phase."),
         ("Citing earlier work, the authors note that generative use of denoising and contractive autoencoders via MCMC was hard to diagnose for convergence, required considerable tuning and did not scale beyond MNIST, so they were superseded by VAEs.",
          "Related works",
          "However, they are hard to diagnose for convergence, require a considerable effort in tuning (Cowles & Carlin, 1996), and have not scaled beyond MNIST, leading to them being superseded by VAEs."),
         ("Evaluation protocol: VAE, constant-variance VAE, WAE (MMD) and 2-stage VAE baselines and RAE variants use the same network architecture on MNIST, CIFAR-10 and CelebA; quality is measured with FID on reconstructions, random samples and interpolations (precision/recall in an appendix).",
          "RAEs for image modeling",
          "For a fair comparison, we use the same network architecture for all models."),
         ("Tuning caveat: when comparing their best FIDs with a large-scale VAE study, the authors note a slightly different architecture and that their models underwent only modest fine-tuning rather than an extensive hyperparameter search.",
          "RAEs for image modeling",
          "While we are employing a slightly different architecture than theirs, our models underwent only modest ﬁnetuning instead of an extensive hyperparameter search."),
         ("No clear winner among the decoder regularizers (gradient penalty, L2, spectral normalization), and even an autoencoder without explicit regularization obtained strong FIDs when the latent density was fitted with a GMM, which the authors relate to neural networks being surprisingly smooth by design.",
          "RAEs for image modeling",
          "Surprisingly, the implicitly regularized RAE and AE models are shown to be able to score impressive FIDs when qδ(z) is ﬁt through GMMs."),
         ("Ex-post density estimation consistently improved sample quality across all settings and models in Table 1, including the VAE and WAE baselines.",
          "RAEs for image modeling",
          "In Table 1, ex-post density estimation consistently improves sample quality across all settings and models."),
     ],
     "notes": "Affiliations: Max Planck Institute for Intelligent Systems (Tübingen) and UCLA; Ghosh and Sajjadi contributed equally. Venue from the PDF header ('Published as a conference paper at ICLR 2020'). Also evaluates a Grammar RAE on molecule and expression generation (Kusner et al. settings). Results tables (FID, Table 1; structured data) not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
