import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1607.00148",
     "title": "LSTM-based Encoder-Decoder for Multi-sensor Anomaly Detection",
     "authors": ["Pankaj Malhotra", "Anusha Ramakrishnan", "Gaurangi Anand", "Lovekesh Vig", "Puneet Agarwal", "Gautam Shroff"],
     "year": 2016, "venue": "ICML 2016 Anomaly Detection Workshop", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1607.00148"},
     "tasks": ["time-series-anomaly-detection"],
     "fam": ["autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised"],
     "proposes": ["EncDec-AD: an LSTM encoder-decoder trained to reconstruct normal multi-sensor time-series windows; the reconstruction error vector is scored by its Mahalanobis-type distance under a Gaussian fitted on errors of held-out normal sequences"],
     "claims": [
         ("Training data assumption: EncDec-AD is trained on normal sequences only, which the authors present as useful when anomalous data is unavailable or sparse (e.g. machines serviced before anomalies appear).",
          "Introduction",
          "EncDec-AD uses only the normal sequences for training."),
         ("Detection premise (hedged): since the encoder-decoder has only seen normal instances, it may not reconstruct an anomalous sequence well, which would give higher reconstruction errors than for normal sequences.",
          "Introduction",
          "When given an anomalous sequence, it may not be able to reconstruct it well, and hence would lead to higher reconstruction errors compared to the reconstruction errors for the normal sequences."),
         ("Anomaly score: normal data is split into sN (training), vN1 (early stopping), vN2 and tN, and anomalous data into vA and tA; a Normal distribution is fitted by maximum likelihood to the point-wise absolute reconstruction-error vectors on vN1, and the anomaly score of a point is (e - mu)^T Sigma^-1 (e - mu).",
          "Section 2.2",
          "are used to estimate the parameters µ and Σ of a Normal distribution N(µ, Σ)"),
         ("Threshold selection uses labeled anomalies: when enough anomalous sequences are available, the threshold tau is learnt to maximize an F-beta score (beta < 1, anomalous = positive class); tau and the number of LSTM units c are chosen on the validation sets vN2 (normal) and vA (anomalous).",
          "Section 2.2",
          "The parameters τ and c are chosen with maximum Fβ score on the validation sequences in vN2 and vA."),
         ("Window-level labels: a window containing an anomalous pattern is labelled anomalous as a whole, which the authors find helpful when the exact position of an anomaly is unknown; for the engine data the only information is a repair date, and the last runs before repair are assumed anomalous and the first runs after repair normal.",
          "Section 2.2",
          "is helpful in many real-world applications where the exact position of anomaly is not known."),
         ("ECG exception: with only one anomaly in the ECG series, vN2 and vA are not created; c is chosen by minimum reconstruction error on vN1, and the threshold is set from normal data only as the mean plus one standard deviation of the anomaly scores on vN1.",
          "Section 3.1",
          "We choose τ = µa + σa, where µa and σa are the mean and standard deviation of the anomaly scores of the points from vN1."),
         ("Data provenance: power demand, space shuttle valve and ECG are taken from Keogh et al. (2005); the engine data (Engine-P, Engine-NP; 12 sensors reduced to the first principal component) is proprietary, from a real-life project.",
          "Section 3",
          "whereas the engine dataset is a proprietary one encountered in a real-life project."),
         ("Comparison with the authors' own prediction-based LSTM-AD (Malhotra et al., 2015, which shares authors with this paper): LSTM-AD gives better results on the predictable datasets (Space Shuttle, Power, Engine-P; F0.1 of 0.84, 0.90, 0.89 as stated in the text), while EncDec-AD gives better results on the unpredictable Engine-NP.",
          "Section 3.2",
          "On the other hand, EncDec-AD gives better results for Engine-NP where the sequences are not predictable."),
         ("The authors conclude (hedged) that because EncDec-AD detects anomalies even in unpredictable time series, it may be more robust than models that rely on predictability.",
          "Discussion",
          "and hence may be more robust compared to such models."),
     ],
     "notes": "Affiliation: TCS Research, New Delhi (Tata Consultancy Services); the first page carries a Tata Consultancy Services copyright notice. Venue from the PDF ('Presented at ICML 2016 Anomaly Detection Workshop') and the arXiv comment. Disclosure: Malhotra, Vig, Shroff and Agarwal are also authors of the LSTM-AD baseline (Malhotra et al., 2015). Thresholds (except ECG) are tuned with labelled anomalous validation sequences (vA), so the detector is unsupervised in training but not in threshold selection. Table 2 (P, R, F-beta, TPR/FPR per dataset; beta differs by dataset) not recorded."},

    {"id": "arxiv-1802.03903",
     "title": "Unsupervised Anomaly Detection via Variational Auto-Encoder for Seasonal KPIs in Web Applications",
     "authors": ["Haowen Xu", "Wenxiao Chen", "Nengwen Zhao", "Zeyan Li", "Jiahao Bu", "Zhihan Li", "Ying Liu", "Youjian Zhao", "Dan Pei", "Yang Feng", "Jie Chen", "Zhaogang Wang", "Honglin Qiao"],
     "year": 2018, "venue": "WWW 2018", "version": "arXiv v1", "license": "CC BY 4.0",
     "links": {"arxiv": "https://arxiv.org/abs/1802.03903", "doi": "https://doi.org/10.1145/3178876.3185996", "code": "https://github.com/korepwx/donut"},
     "tasks": ["time-series-anomaly-detection"],
     "fam": ["variational-autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised"],
     "proposes": ["Donut: a fully-connected VAE over sliding windows of seasonal KPIs, trained with a modified ELBO (M-ELBO) that excludes labelled anomalies and missing points, with missing-data injection during training and MCMC imputation of missing points at detection; scored by reconstruction probability, with a KDE interpretation of that score"],
     "claims": [
         ("Claimed contribution: the authors state that adopting VAEs (or generative models in general) for anomaly detection requires training on both normal and abnormal data, contrary to common intuition.",
          "Introduction",
          "For the first time in the literature, we discover that adopting VAE (or generative models in general) for anomaly detection requires training on both normal data and abnormal data, contrary to common intuition."),
         ("Training on contaminated data: the authors note that the earlier VAE-based detector of An & Cho [2] assumes training only on clean data, which is infeasible in their context, and that the VRNN-based work [36] does not discuss this problem.",
          "Previous Work",
          "Fifth, [2] assumes training only on clean data, which is infeasible in our context, while [36] does not discuss this problem."),
         ("M-ELBO: training windows are not filtered; missing points are filled with zeros and an indicator removes labelled anomalies and missing points from the reconstruction term, with the prior term scaled by the fraction of normal points; the objective still applies when there are no anomaly labels (the unsupervised case), in which unlabelled anomalies remain in the training windows.",
          "Training",
          "Note that Eqn (3) still holds when there is no labeled anomalies in the training data."),
         ("Anomaly score: following An & Cho [2], the score is the reconstruction probability E_q(z|x)[log p(x|z)], computed after MCMC imputation of known missing points and only for the last point of each window; the authors report that Monte Carlo estimation of p(x) by sampling on the prior does not work well enough in practice.",
          "Detection",
          "Since only the ordering rather than the exact values of anomaly scores are concerned in anomaly detection, we follow [2] and use the latter one."),
         ("Threshold: the paper does not propose a way to choose the detection threshold, calling it a difficult problem especially in the unsupervised scenario, and points to existing work (e.g. [21]) that might be applicable.",
          "Future Work",
          "We did not discuss how to choose the right threshold for detection."),
         ("Evaluation metric uses an oracle threshold: the headline metric is the best F-score over all thresholds on the test set, which the authors describe as the best possible performance given an optimal global threshold (AUC and alert delay are also reported).",
          "Performance Metrics",
          "The best F-score indicates the best possible performance of a model on a particular testing set, given an optimal global threshold."),
         ("Segment-level adjustment of the metric: if any point of a ground-truth anomaly segment is detected at a threshold, all points of that segment are counted as detected; points outside segments are treated as usual.",
          "Performance Metrics",
          "We instead use a simple strategy: if any point in an anomaly segment in the ground truth can be detected by a chosen threshold, we say this segment is detected correctly, and all points in this segment are treated as if they can be detected by this threshold."),
         ("Acknowledged failure mode: despite M-ELBO, missing-data injection and MCMC imputation, Donut may still fail to find a good posterior if a window contains too many anomalies; the authors argue that for long-lasting anomalies correct scores in the first few minutes suffice in their context.",
          "Find Good Posteriors for Abnormal x",
          "Despite these techniques, Donut may still fail to find a good posterior, if there are too many anomalies in x."),
     ],
     "notes": "Affiliations: Tsinghua University and Alibaba Group; acknowledgments list support from NSFC and Alibaba Innovative Research (AIR). Data provenance: 18 business KPIs at 1-minute intervals obtained from 'a large Internet company' (the abstract says 'a top global Internet company'; not named in the text), of which 3 (A, B, C) were evaluated, split 49%/21%/30% train/validation/test, with all anomalies labelled by the company's operators; the data is not stated to be released. Venue from the PDF (ACM reference format 'In WWW 2018: The 2018 Web Conference' and the IW3C2 CC BY 4.0 notice); the arXiv comment says 'submitted to WWW 2018'. Disclosure: the supervised baseline Opprentice [25] is earlier work by Xu, Zhao and Pei (authors of this paper). Latent dimension K was chosen empirically (3 for B and C, 8 for A); Fig 10 shows test-set F-scores across K, which the authors say cannot be used to pick K, and choosing K unsupervised is left as future work. Labels were down-sampled to 0%/10%/100% of anomaly segments for the unsupervised/occasional-label settings. Results (Fig 8-10) are figures only; no numbers recorded beyond the abstract range."},

    {"id": "arxiv-1904.02639",
     "title": "Memorizing Normality to Detect Anomaly: Memory-augmented Deep Autoencoder for Unsupervised Anomaly Detection",
     "authors": ["Dong Gong", "Lingqiao Liu", "Vuong Le", "Budhaditya Saha", "Moussa Reda Mansour", "Svetha Venkatesh", "Anton van den Hengel"],
     "year": 2019, "venue": "ICCV 2019", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1904.02639", "url": "https://donggong1.github.io/anomdec-memae"},
     "tasks": ["anomaly-detection"],
     "fam": ["autoencoders", "reconstruction-based-detectors"], "par": ["unsupervised"],
     "proposes": ["MemAE: an autoencoder whose encoding is used as a query to a learned memory of prototypical normal patterns (cosine-similarity attention with hard shrinkage and an entropy loss for sparse addressing); the decoder reconstructs only from retrieved memory items, and the reconstruction error is the anomaly score"],
     "claims": [
         ("Motivation (failure mode of AE detectors): the assumption that anomalies get higher reconstruction error may not always hold; sometimes the AE 'generalizes' so well that it also reconstructs anomalous inputs well, an observation the authors attribute to existing literature ([47, Figure 1]) and to their own Figures 4 and 6.",
          "Introduction",
          "However, this assumption may not always hold, and sometimes the AE can “generalize” so well that it can also reconstruct the abnormal inputs well."),
         ("Proposed explanation: since there are no anomalous training samples, reconstruction behaviour on anomalies should be unpredictable; if anomalies share compositional patterns with normal data (e.g. local edges in images) or the decoder is 'too strong', the AE is very likely to reconstruct them well.",
          "Introduction",
          "AE is very likely to reconstruct the anomalies well."),
         ("Anomaly score: at test time the anomaly criterion is the l2-norm based mean squared reconstruction error between the input and its reconstruction.",
          "Section 3.2",
          "to measure of the reconstruction quality, which is used as the criterion for anomaly detection."),
         ("Sparse addressing is motivated by a remaining failure mode: some anomalies might still be reconstructed well by a complex combination of memory items through dense addressing weights, so a hard shrinkage operator (threshold lambda, suggested in [1/N, 3/N]) is applied to the weights.",
          "Section 3.3.3",
          "To alleviate this issue, we apply a hard shrinkage operation to promote the sparsity of w:"),
         ("Image protocol (MNIST, CIFAR-10, one class as normal): the training set contains only normal samples and does not overlap the test set; anomalies from other classes make up around 30% of the test data; performance is reported as AUC over a varying threshold, so no operating threshold is selected.",
          "Section 4.1",
          "Following the setting used in [42, 47], the training set only consists of normal samples and has no overlapping with the testing set."),
         ("Observed AE failure: in the MNIST visualization, the AE without memory tends to learn more local representations, so an abnormal sample may also be reconstructed well, whereas MemAE reconstructs a normal-class digit.",
          "Section 4.1",
          "Thus an abnormal sample may also be reconstructed well."),
         ("Video protocol (UCSD-Ped2, CUHK Avenue, ShanghaiTech), following [9, 24]: the frame normality score is the reconstruction error min-max normalized to [0, 1] using the minimum and maximum error over the frames of the same video episode; frame-level AUC is reported.",
          "Section 4.2",
          "where eu denotes the reconstruction error the u-th frame in a video episode."),
         ("Cybersecurity protocol (KDDCUP99 10 percent, following [47]): 80% of the samples labelled 'attack' in the original dataset are treated as normal, half of the data is randomly sampled for training, and only normal-class samples are used for training; precision, recall and F1 are averaged over 20 runs. How the decision threshold for these metrics is set was not found in the text (searched for 'threshold'); the paper refers to the standard protocol of [47].",
          "Section 4.3",
          "Only data samples from normal class are used for training."),
     ],
     "notes": "Affiliations: The University of Adelaide, A2I2 Deakin University, University of Western Australia. Venue from the arXiv comment ('Accepted to appear at ICCV 2019'); the arXiv PDF itself does not state the venue. No time-series data is evaluated (images, video clips, KDDCUP99 tabular vectors), so the time-series task tag is not used. Hyperparameters: alpha = 0.0002 for all experiments; memory size N is stated to be non-trivial to optimize but MemAE is described as insensitive to it given a large enough N (Fig 7, UCSD-Ped2); how hyperparameters were selected is not described beyond 10% of the image training data being held out for validation, whose use is not specified. Results tables (Table 1-4: AUC on MNIST/CIFAR-10 and video, P/R/F1 on KDDCUP, ablations) not recorded."},
]

from topic_ae_common import BASE_NOTE  # noqa: E402

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, created_at="2026-10-04", created_by="claude-opus-5-5 via Claude Code (subagent)")
