import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1811.06128",
     "title": "Machine Learning for Combinatorial Optimization: a Methodological Tour d'Horizon",
     "authors": ["Yoshua Bengio", "Andrea Lodi", "Antoine Prouvost"],
     "year": 2018, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1811.06128"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["branch-and-bound", "deep-learning"], "par": ["supervised", "reinforcement-learning"],
     "proposes": ["Survey and methodology for integrating machine learning into combinatorial optimization algorithms, organized by how ML and the CO algorithm interact (end-to-end learning, learning to configure algorithms, ML alongside optimization algorithms), with optimization problems viewed as data points drawn from a distribution of instances"],
     "claims": [
         ("Taxonomy (1) end-to-end learning: the ML model is trained to output solutions directly from the input instance (the survey's examples are mostly Euclidean TSP: pointer networks, RL-trained pointer networks, GNN encoders).",
          "End to end learning",
          "A ﬁrst idea to leverage machine learning to solve discrete optimization problems is to train the ML model to output solutions directly from the input instance, as shown in Figure 7."),
         ("Taxonomy (2) learning to configure algorithms: rather than using ML alone, ML provides additional information to a CO algorithm, e.g. a parametrization of the algorithm in a broad sense (algorithm configuration, deciding whether to apply a decomposition or a linearization).",
          "Learning to configure algorithms",
          "Instead, ML can be applied to provide additional pieces of information to a CO algorithm as illustrated in Figure 8."),
         ("Taxonomy (3) ML alongside optimization algorithms: a master CO algorithm repeatedly queries the same ML model for low-level decisions; for learned branching in MILP branch and bound, the authors note the framework keeps the same guarantees on lower and upper bounds while only the branching decisions are learned.",
          "Machine learning alongside optimization algorithms",
          "In this case, the general algorithm remains a branch-and-bound framework, with the same software architecture and the same guarantees on lower and upper bounds, but the branching decisions made at every node are left to be learned."),
         ("Guarantees: using only ML (end-to-end) gives no optimality guarantee and only weak feasibility guarantees; ML that selects or parametrizes a CO algorithm keeps exactness if all choices lead to complete algorithms; in repeated interactions all possible decisions must be valid (the authors give Hottung et al. 2017, where an ML bound can overestimate lower bounds and prune invalidly, as a non-exact counter-example).",
          "Exactness and approximation",
          "Using only ML as surveyed in Section 3.2.1 cannot give any optimality guarantee, and only weak feasibility guarantees (see Section 6.1)."),
         ("Generalization caveat: current ML generalizes within the training distribution but tends to have more difficulty out of distribution, so the authors expect ML-based CO algorithms may fail on unseen instances too far from the training instances; they also note traditional CO algorithms tend to be adapted to particular problem structures.",
          "Introduction",
          "we may expect CO algorithms that leverage ML models to fail when evaluated on unseen problem instances that are too far from what has been used for training the ML predictor"),
         ("Scaling caveat: according to the survey, all the cited papers that tackle TSP with ML and attempt larger instances (Vinyals et al., Bello et al., Khalil et al., Kool and Welling) see degrading performance as size increases much beyond the training sizes; learning on larger instances may itself be a computational and generalization issue.",
          "Scaling",
          "Indeed, all of the papers tackling TSP through ML and attempting to solve larger instances see degrading performance as size increases much beyond the sizes seen during training (Vinyals et al., 2015; Bello et al., 2017; Khalil et al., 2017a; Kool and Welling, 2018)."),
         ("Conclusion (authors' belief): end-to-end ML approaches can be improved by combining ML with current CO algorithms to benefit from their theoretical guarantees and state-of-the-art algorithms; the authors also recommend learning on a distribution small enough for the policy to exploit the problem structure.",
          "Conclusions",
          "We believe end-to-end machine learning approaches to combinatorial optimization can be improved by using machine learning in combination with current combinatorial optimization algorithms to beneﬁt from the theoretical guarantees and state-of-the-art algorithms already available."),
     ],
     "notes": "PDF states: Accepted to the European Journal of Operations Research. Survey; no experiments of its own. Affiliations: Canada Excellence Research Chair in Data Science for Decision Making (Ecole Polytechnique de Montreal), Universite de Montreal, Mila. The survey states the literature it covers is exploratory rather than mature algorithms (Introduction). Evaluation/data-generation remarks (Data generation section) quote Smith-Miles and Bowly (2015): confidence in an algorithm 'depends on how carefully we select test instances' and new algorithms are too often claimed superior on well-studied instances. On generalization to larger sizes it reports Gasse et al. (2019) pushing test distributions to larger sizes with a 'largely affirmative' answer (Section 4.3 discussion). Tag note: no exact family tag for 'survey'; branch-and-bound chosen because learned branching/cut selection inside B&B is a central example."},

    {"id": "arxiv-1803.08475",
     "title": "Attention, Learn to Solve Routing Problems!",
     "authors": ["Wouter Kool", "Herke van Hoof", "Max Welling"],
     "year": 2018, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1803.08475", "code": "https://github.com/wouterkool/attention-learn-to-route"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["deep-learning", "graph-neural-networks"], "par": ["reinforcement-learning"],
     "proposes": ["Attention Model (AM): attention-based encoder-decoder that constructs routing solutions node by node, trained with REINFORCE using a deterministic greedy-rollout baseline; applied with one hyperparameter set to TSP, CVRP, SDVRP, OP and (stochastic) PCTSP"],
     "claims": [
         ("Contribution: an attention-layer model with stated benefits over the Pointer Network, trained with REINFORCE and a greedy-rollout baseline that the authors find more efficient than a value function.",
          "Abstract",
          "we propose a model based on attention layers with beneﬁts over the Pointer Network and we show how to train this model using REINFORCE with a simple baseline based on a deterministic greedy rollout, which we ﬁnd is more efﬁcient than using a value function"),
         ("Scope of the claim: the stated goal is not to beat a specialized non-learned TSP solver such as Concorde, but to show flexibility across several routing problems of reasonable size with a single set of hyperparameters.",
          "Introduction",
          "specialized TSP algorithm such as Concorde (Applegate et al., 2006)"),
         ("TSP baselines: optimal results by Gurobi and by Concorde (faster, TSP-specialized), LKH3 as a state-of-the-art heuristic, plus nearest/random/farthest insertion and nearest neighbor, and previously reported learned heuristics (Bello et al., OR Tools as reported by Bello et al., Christofides + 2OPT as reported by Vinyals et al.).",
          "Experiments",
          "For the TSP, we report optimal results by Gurobi, as well as by Concorde (Applegate et al., 2006) (faster than Gurobi as it is specialized for TSP) and LKH3 (Helsgaun, 2017), a state-of-the-art heuristic solver that empirically also ﬁnds optimal solutions in time comparable to Gurobi."),
         ("Run-time comparison protocol: the authors note run times can differ by two orders of magnitude due to implementation and hardware; they report time to solve the 10000-instance test set on a single GPU (1080Ti) or 32 instances in parallel on a 32 virtual CPU system, and call this conservative because most baselines are single-thread CPU implementations.",
          "Experiments",
          "Run times are important but hard to compare: they can vary by two orders of magnitude as a result of implementation (Python vs C++) and hardware (GPU vs CPU)."),
         ("Size generalization (appendix): models tested on sizes other than trained for generalize, but quality degrades as the size difference grows; the authors read this as models specializing to the trained sizes and suggest selecting the trained model with best validation performance per size.",
          "Appendix",
          "The models generalize when tested on different sizes, although quality degrades as the difference becomes bigger, which can be expected as there is no free lunch (Wolpert & Macready, 1997)."),
         ("Limitation / future work: scaling to larger instances is named as an important direction; the authors also note that many practical feasibility constraints cannot be satisfied by simple masking and suggest combining heuristic learning with backtracking.",
          "Discussion",
          "Scaling to larger problem instances is an important direction for future research, where we think we have made an important ﬁrst step by using a graph based method, which can be sparsiﬁed for improved computational efﬁciency."),
         ("Funding / affiliation: the research was funded by ORTEC Optimization Technology (first author affiliated with University of Amsterdam and ORTEC).",
          "Acknowledgements",
          "This research was funded by ORTEC Optimization Technology."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2019. Instances: TSP node locations sampled uniformly at random in the unit square (Appendix); models trained on n = 20, 50 and 100; 10000 test instances per problem; greedy decoding vs sampling 1280 solutions and reporting the best. Gurobi is used as the 'best possible solution' (intractable for n > 20 except TSP) and also with time limits as a heuristic baseline; the authors state they picked reasonable runtime/performance trade-off points rather than full curves. CVRP compared against Nazari et al. RL and LKH3. Hardware: training on 1080Ti GPUs (TSP100 on 2 GPUs). The text reports the AM outperforms the Pointer Network under any baseline, and that the authors could not reproduce Bello et al.'s 1.5% with a critic baseline. Relation to classical techniques: the AM is a learned construction heuristic (end-to-end); no local search is used for its results (2OPT appears only with the Deudon et al. comparison). Results tables not recorded."},

    {"id": "arxiv-1810.10659",
     "title": "Combinatorial Optimization with Graph Convolutional Networks and Guided Tree Search",
     "authors": ["Zhuwen Li", "Qifeng Chen", "Vladlen Koltun"],
     "year": 2018, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1810.10659"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["graph-neural-networks", "local-search", "greedy-methods", "deep-learning"], "par": ["supervised"],
     "proposes": ["GCN trained with a hindsight (min-over-M-maps) loss to output multiple per-vertex probability maps for MIS, used to guide a parallelized breadth-first-like tree search of greedy labellings, combined with graph reduction and 2-improvement local search; MVC, MC and SAT solved by reduction to MIS"],
     "claims": [
         ("Core idea: a graph convolutional network is trained (supervised) to estimate, for each vertex, the likelihood that it belongs to the optimal solution.",
          "Abstract",
          "The central component is a graph convolutional network that is trained to estimate the likelihood, for each vertex in a graph, of whether this vertex is part of the optimal solution."),
         ("Relation to search: the trained GCN guides a parallelized tree search that generates many candidate solutions, one of which is chosen after refinement (the basic variant uses the GCN output as the heuristic in a greedy procedure).",
          "Introduction",
          "This trained GCN is used to guide a parallelized tree search procedure that rapidly generates a large number of candidate solutions, one of which is chosen after subsequent reﬁnement."),
         ("Classical components: two ideas adopted from classic heuristics are added, described as complementary to learning: 2-improvement local search to refine candidates and graph reduction that shrinks the graph while preserving the optimal MIS size.",
          "Method",
          "Finally, Section 4.3 describes two ideas adopted from classic heuristics that are complementary to the application of learning and are useful in accelerating computation and reﬁning candidate solutions."),
         ("Protocol (training): a single network is trained on SATLIB 3-SAT instances converted to MIS graphs (about 1,200 vertices each; 38,000/1,000/1,000 split) and applied to all other problems and datasets (SAT Competition 2017, BUAA-MC, SNAP social networks, citation networks).",
          "Experimental setup",
          "The network trained on this training set will be applied to all other problems and datasets described below."),
         ("Protocol (baselines and time): baselines are S2V-DQN, a classic greedy heuristic (also with graph reduction + local search), Z3, ReduMIS and Gurobi; the tree search runs with 16 threads and the other methods get 16x the running time (time limits 10 minutes on SAT datasets, 30 minutes on large graphs), on one desktop with an i7-5960X CPU and Titan X GPU.",
          "Results",
          "For fair comparison, we give the other methods 16× running time, though we don’t reboot them if they terminate earlier based on their stopping criteria."),
         ("Ablation (SATLIB validation set, single-threaded): Basic, Basic+Tree, no local search and no reduction variants are compared, and the authors state that all components contribute to the results.",
          "Results",
          "This experiment demonstrates that all components presented in this paper contribute to the results."),
         ("Generalization claim (Li et al.'s own reading of their MIS/MVC results on SNAP and citation graphs; see notes for the re-evaluation arxiv-2201.10494): the authors state the approach generalizes from synthetic to real graphs, from SAT graphs to social networks, and from about 1,000-node to about 100,000-node graphs; they add ReduMIS works as well, presumably because both find optimal solutions on those graphs.",
          "Results",
          "In particular, it generalizes from synthetic graphs to real ones, from SAT graphs to real-world social networks, and from graphs with roughly 1,000 to graphs with roughly 100,000 nodes and more than 10 million edges."),
     ],
     "notes": "PDF states: 32nd Conference on Neural Information Processing Systems (NIPS 2018). Affiliations: Intel Labs (Li, Koltun) and HKUST (Chen). The paper states the authors 'will release code' but gives no URL in the PDF. Limitation (Conclusion): Maximal Clique was not solved on large SNAP/citation graphs because complement graphs are very dense; the authors call the approach 'not a universal solution'. No optimality guarantee is claimed; the method is a heuristic search. Re-evaluated by arxiv-2201.10494 (Boether et al., ICLR 2022); the following are Boether et al.'s statements, not this paper's: using the original Intel code (with the original weights and with newly trained weights) and their DGL re-implementation, the default configuration (no reduction, no local search) rarely finds solutions on SATLIB within their 30 s SATLIB time limit (this paper used 10 minutes with 16 threads), so they report the claimed SATLIB results as not reproduced; replacing the GCN output with random values gave identical performance in the configuration with reduction and local search (randomness beat the GCN on some datasets); they attribute solution quality mainly to KaMIS's reduction and local search, and report undocumented code details (the parallel variant uses one randomly chosen probability map; an 'epoch' iterates over 2000 of the 38000 training samples). The ablation statement in c6 and the generalization statement in c7 are this paper's own claims. Results tables not recorded."},

    {"id": "arxiv-2201.10494",
     "title": "What's Wrong with Deep Learning in Tree Search for Combinatorial Optimization",
     "authors": ["Maximilian Böther", "Otto Kißig", "Martin Taraz", "Sarel Cohen", "Karen Seidel", "Tobias Friedrich"],
     "year": 2022, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2201.10494", "code": "https://github.com/MaxiBoether/mis-benchmark-framework"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["graph-neural-networks", "branch-and-bound", "local-search"], "par": ["supervised", "reinforcement-learning"],
     "proposes": ["Open-source benchmark suite for maximum (weighted) independent set with a unified interface to Gurobi, KaMIS, Intel-TreeSearch (Li et al. 2018), Learning What To Defer, and DGL-TreeSearch (a re-implementation of Li et al.'s tree search); re-evaluation of the GCN-guided tree search"],
     "claims": [
         ("Main finding on Li et al. (2018), per Boether et al.: after re-implementing Li et al.'s algorithm and testing various configurations on small and large synthetic and real-world MIS graphs, they report that the GCN in the guided tree search does not learn a meaningful representation of the solution structure and can be replaced by random values; they state the tree search instead relies on algorithmic techniques like graph kernelization and conclude that the original publication's results are not reproducible.",
          "Abstract",
          "By re-implementing their algorithm with a focus on code quality and extensibility, we show that the graph convolution network used in the tree search does not learn a meaningful representation of the solution structure, and can in fact be replaced by random values."),
         ("Attribution of performance (Boether et al.'s conclusion): the GCN guidance does not help their tree search (randomness beats the GCN on some datasets, no difference on others); in what they consider the production configuration (reduction and local search enabled) random outputs give identical performance with very minor differences in time to the final solution; overall they name KaMIS's reduction and local search as the major contributors to solution quality and call the tree search a 'smarter brute-force' approach that does not gain performance from ML guidance (they recall the default version cannot solve SATLIB without reduction and local search).",
          "Analysis of the tree search",
          "Overall, major contributing factors to solution quality are the reduction and local search by KAMIS, and in fact, the tree search algorithm is a “smarter brute-force” approach that does not gain any performance by being guided by a machine learning model."),
         ("Reproducibility (Boether et al.): on SATLIB, with the default configuration (no reduction, no local search) and their time limits (30 s for SATLIB in Tables 1/2), both implementations rarely find solutions; they state their results contradict Li et al.'s claimed SATLIB average MIS of 426 and Ahn et al. (2020)'s 418, that testing the official Intel-TreeSearch weights made no difference, and that neither the original code with the original weights, nor the original code with newly trained weights, nor their re-implementation perform as originally claimed; they contacted Li et al. unsuccessfully (their suspicion of an undocumented modification refers to Ahn et al.'s default-configuration results).",
          "Analysis of the tree search",
          "Overall, neither the original code with the original weights, nor the original code with newly trained weights, nor our reimplementation are performing as originally claimed."),
         ("Undocumented implementation details of the original code (Appendix C, per Boether et al.): the multi-threaded variant uses just one randomly chosen probability map instead of all, which is not documented in the paper; also one 'epoch' iterates over only 2000 random samples of the 38000 training samples although the paper states 200 epochs.",
          "Appendix",
          "Third, the multi-threaded variant of the algorithm (demo parallel.py) uses just one randomly chosen probability map of the GCN outputs instead of all."),
         ("Comparison with classical solvers (Boether et al., on their main benchmark datasets before the separate large-scale analysis): they find state-of-the-art algorithmic techniques are required for the tree searches to find good solutions; because the fully configured tree searches use KaMIS-internal routines, they argue ('one can argue') purely algorithmic solvers are the better choice, as the quality difference is negligible and KaMIS is faster; they say this is in line with Joshi et al. (2021) (arxiv-2006.07054), who in their description observe DL-based TSP solutions are often outperformed, especially on larger instances.",
          "Comparing tree search solvers to other solvers",
          "As the fully-conﬁgured versions of the tree searches employ these KAMIS-internal routines, one can argue that the purely algorithmic solvers are the better choice, because the quality difference is negligible, while KAMIS is faster than the tree searches."),
         ("Contrast with an RL solver (Boether et al.): for Learning What To Defer (Ahn et al. 2020), trained by them for 20,000 PPO iterations on SATLIB with Ahn et al.'s SATLIB hyperparameters and run without local search or reduction, replacing the network output with a random tensor degrades solution quality noticeably, unlike for the tree searches, so they conclude the GNN is responsible for its competitive solution quality.",
          "Abstract",
          "Additionally, we analyze a recent solver based on reinforcement learning and observe that for this solver, the GNN is responsible for the competitive solution quality."),
         ("Hardware fairness: Gurobi and KaMIS run on CPU while the tree search uses one or more GPUs; even with eight V100 GPUs the tree search does not outperform the other solvers, which the authors read as the workload not being GPU-bound.",
          "Comparing tree search solvers to other solvers",
          "Evening when assigning eight V100 GPUs to the multithreaded tree search, the computational advantage of the tree search does not help to outperform the other solvers, showing that the workload is not GPU-bound."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2022. Ethics statement: the authors declare no conflicts of interest. Affiliations: Hasso Plattner Institute / University of Potsdam, Academic College of Tel Aviv-Yaffo. Setup: NVIDIA DGX-1 (2x 20-core Xeon E5-2698, 8 V100 GPUs). GCNs trained on SATLIB for 20 epochs with Adam and hindsight loss, 32 probability maps 'to enable comparison with Li et al. (2018)'. Time limits: 15 s for random graphs of 50-100 nodes, 30 s for SATLIB and PPI, 5 min for VC-BM and DIMACS (Table 1 caption); multithreaded runs use 8 threads sharing one GPU. Datasets: ER, BA, HK, WS, hyperbolic random graphs; SATLIB, VC-BM, DIMACS, PPI, citation, reddit; large-scale graphs 500,000 to 5,000,000 vertices; weighted graphs and Amazon MWIS. Further findings: with reduction enabled the reductions often single-handedly solve random-graph instances; without reduction/local search vanilla tree searches rarely find solutions on SATLIB within the limit; on reddit graphs randomness increased performance. On large graphs KaMIS performed best; the authors could not verify LWD's reported scalability to 2,000,000 vertices. On weighted ER graphs DGL-TreeSearch with queue pruning found the best result and Gurobi was the only solver handling the large Amazon MWIS instances. Appendix D tunes Gurobi with grbtune. Conclusion states the LWD results 'indicate that reinforcement learning is superior to supervised approaches' (authors' reading). KaMIS uses graph kernelization and branch and bound (hence the branch-and-bound tag). Re-evaluates arxiv-1810.10659. Reviewer cross-check (not stated by Boether et al.): Li et al. report a 10-minute SATLIB time limit with 16 threads (arxiv-1810.10659 c5), while Boether et al.'s tables use 30 s for SATLIB; no discussion of this difference was found in Boether et al.'s text. Results tables not recorded."},

    {"id": "arxiv-2206.13211",
     "title": "Modern graph neural networks do worse than classical greedy algorithms in solving combinatorial optimization problems like maximum independent set",
     "authors": ["Maria Chiara Angelini", "Federico Ricci-Tersenghi"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2206.13211"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["graph-neural-networks", "greedy-methods"], "par": ["unsupervised"],
     "proposes": ["Comment (matters arising) comparing the physics-inspired unsupervised GNN of Schuetz et al. (Nature Machine Intelligence 2022) against a degree-based greedy algorithm (DGA) for MIS on random regular graphs, and proposing MIS on d-regular random graphs with d > 16 as a hard benchmark"],
     "claims": [
         ("Paper evaluated: the comment targets the physics-inspired unsupervised GNN of Schuetz, Brubaker and Katzgraber ('Combinatorial Optimization with Physics-Inspired Graph Neural Networks', Nat Mach Intell 2022), which was tested on maximum cut and MIS on sparse graphs.",
          "Introduction",
          "The recent work “Combinatorial Optimization with Physics-Inspired Graph Neural Networks” [Nat Mach Intell 4 (2022) 367] introduces a physics-inspired unsupervised Graph Neural Network (GNN) to solve combinatorial optimization problems on sparse graphs."),
         ("Main claim (instance setting: MIS on random regular graphs of fixed degree d, with d = 3 and 5 in Fig. 1): a simple greedy algorithm running in almost linear time finds MIS solutions of much better quality than the Schuetz et al. GNN in a much shorter time; the GNN numbers are taken from the original paper, not re-run.",
          "Introduction",
          "In this comment, we show that a simple greedy algorithm, running in almost linear time, can ﬁnd solutions for the MIS problem of much better quality than the GNN in a much shorter time."),
         ("Instance setting: the comparison is on d-regular random graphs with d = 3 and 5; the greedy baseline (DGA) repeatedly picks a node of smallest degree in the residual graph; quality is reported as approximation ratio to the current best theoretical upper bounds, which the authors note are likely not strict.",
          "Comparison with simple greedy algorithms",
          "In Fig. 1 we compare the performances of the GNN of Ref. [4] (empty symbols) and DGA (full symbols) in ﬁnding MIS on d-RRG with d = 3, 5."),
         ("Critique of the original baselines: according to the comment, Schuetz et al. compared only against the Boppana-Halldorsson approximation algorithm, while many faster MIS algorithms exist.",
          "Introduction",
          "The authors of Ref. [4] consider only the Boppana-Halldorsson (BH) approximated algorithm [8]"),
         ("Run-time comparison caveat: DGA times were measured on a 2.3 GHz MacBook Pro, while GNN times were extracted from Fig. 5 of the original paper and include post-processing, since the original authors give no per-step timing; the commenters argue the post-processing (checking the output is an IS) should be linear in n, so most of that time should be GNN computation.",
          "Comparison with simple greedy algorithms",
          "The latter correspond to the aggregated run-time that includes the post-processing, because the authors furnish no additional information on the time needed for the diﬀerent steps of the computation."),
         ("Recommendation: such a simple greedy algorithm should be considered a minimal benchmark that any new algorithm must beat to be taken seriously.",
          "Discussion",
          "We have reported in detail the performances of DGA because we believe that such a simple greedy algorithm should be considered as a minimal benchmark and any new algorithm must perform at least better than DGA to be taken into serious consideration."),
         ("Benchmark hardness: the authors argue MIS on d-regular random graphs (d-RRG) with d < 16 is likely easy (citing a statistical-physics study of the independent-set space) and propose d > 16 as a harder benchmark, starting from results in their earlier work for d = 20 and d = 100.",
          "Discussion",
          "So, a possible answer to the fundamental question above is to study MIS on d-RRG with d > 16."),
     ],
     "notes": "Short comment arising from Schuetz et al., Nature Machine Intelligence (doi 10.1038/s42256-022-00468-6); the evaluated GNN paper is not carded here. The authors declare no competing interests. Affiliations: Sapienza University of Rome, INFN, CNR-NANOTEC. The GNN numbers are taken from the original paper's figures (not re-run). The comment also quotes MCMC (simulated annealing, parallel tempering) and belief propagation with reinforcement approximation ratios from the authors' earlier work (Ref. [13]) as doing better than DGA, and says the same conclusion holds for Max-Cut per a concurrent comment by Boettcher. It also mentions that in planted clique on dense graphs, a cited NN does not reach message passing or parallel tempering performance. In the Discussion the authors give as their opinion that, at present, NN-based optimizers (like Schuetz et al.'s) do not meet their requirements and cannot compete with simple standard algorithms on hard optimization problems; this is an opinion beyond their d = 3, 5 MIS experiment. The paradigm tag 'unsupervised' refers to the evaluated GNN. Numeric results (approximation ratios, speedups) not recorded."},

    {"id": "arxiv-2006.07054",
     "title": "Learning the Travelling Salesperson Problem Requires Rethinking Generalization",
     "authors": ["Chaitanya K. Joshi", "Quentin Cappart", "Louis-Martin Rousseau", "Thomas Laurent"],
     "year": 2020, "version": "arXiv v6",
     "links": {"arxiv": "https://arxiv.org/abs/2006.07054", "code": "https://github.com/chaitjo/learning-tsp"},
     "tasks": ["combinatorial-optimization"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised", "reinforcement-learning"],
     "proposes": ["Unified end-to-end neural combinatorial optimization pipeline for TSP (problem definition, graph embedding, solution decoding, solution search, policy learning) used for controlled experiments on zero-shot generalization from small training sizes to larger TSPs"],
     "claims": [
         ("Main claim: learning-driven TSP approaches perform close to classical solvers when trained on trivially small sizes but cannot generalize the learnt policy to larger instances at practical scales.",
          "Abstract",
          "While state-of-the-art learning-driven approaches for TSP perform closely to classical solvers when trained on trivially small sizes, they are unable to generalize the learnt policy to larger instances at practical scales."),
         ("Protocol (training): ablations train on variable-size TSP20-50 (compared with fixed sizes up to TSP100); nodes uniform in the unit square; SL uses 1,280,000 instances with Concorde tours as labels for 10 epochs, RL uses 128,000 freshly generated unlabelled instances per epoch for 100 epochs, so both see 12,800,000 samples in total; models have approximately 350,000 parameters.",
          "Experimental setup",
          "We perform ablation studies of each component of the pipeline by training on variable TSP20-50 graphs for rapid experimentation."),
         ("Protocol (evaluation): test set of 1,280 instances for each size TSP10 to TSP200, metric is optimality gap w.r.t. Concorde, beam search width 128; a non-learnt furthest insertion heuristic is used as the reference for 'good' generalization.",
          "Experimental setup",
          "We compare models on a held-out test set of 25,600 TSPs, consisting of 1,280 samples each of TSP10, TSP20, . . . , TSP200."),
         ("Critique of evaluation practice: the authors state that the prevalent paradigm of measuring on fixed or trivially small sizes hides poor generalization.",
          "Introduction",
          "The prevalent evaluation paradigm overshadows models’ poor generalization capabilities by measuring performance on ﬁxed or trivially small TSP sizes."),
         ("Train/test size result: variable-size training helps within the training range but does not improve generalization to larger problems over training on TSP50; TSP20-trained models fail to generalize to large sizes and TSP100-trained models do poorly on small sizes, which the authors take as evidence that evaluation on training sizes (citing Kool et al. and Joshi et al.) hides brittle out-of-distribution performance.",
          "Results",
          "Learning from small TSP20 is unable to generalize to large sizes while TSP100 models generalize poorly to trivially easy sizes, suggesting that the prevalent protocol of evaluation on training sizes [42, 37] overshadows brittle out-of-distribution performance."),
         ("Classical baseline (Figure 1 setting: three identical autoregressive GNN models trained via RL on 12.8 million instances - from scratch on TSP200, on TSP20-50 zero-shot, and pretrained then fine-tuned on 1.28 million TSP200 - plus Active Search, evaluated on 1,280 held-out TSP200 instances): within the authors' computational budget a simple non-learnt furthest insertion heuristic still outperforms all models.",
          "Introduction",
          "Within our computational budget, a simple non-learnt furthest insertion heuristic still outperforms all models."),
         ("Recommendation: GNN layers, normalization schemes, graph sparsification and learning paradigms need to be explicitly re-designed with out-of-distribution generalization in mind; the authors advocate training on small instances and transferring zero-shot or via fast fine-tuning rather than expensive large-scale training.",
          "Conclusion",
          "Our ﬁndings suggest that key design choices such as GNN layers, normalization schemes, graph sparsiﬁcation, and learning paradigms need to be explicitly re-designed to consider out-of-distribution generalization."),
     ],
     "notes": "Affiliations: University of Cambridge, Ecole Polytechnique de Montreal, Loyola Marymount University; no company funding found in the text. Further findings listed in the Introduction: autoregressive decoding improves generalization over non-autoregressive models but costs more inference time; models trained with expert supervision are more amenable to post-hoc search, while RL scales better with more computation as it does not rely on labelled data. Section 6 (Recent case studies) reports that learning within local search (e.g. NeuroLKH improving LKH) implicitly gives better zero-shot generalization than constructive approaches, but names as a limitation the need for hand-designed local search heuristics; it also describes GNN + dynamic programming / MCTS search replacing the decoder search. The paper cites Bengio et al.'s three-way taxonomy (arxiv-1811.06128). Compute: the Introduction says it is difficult to outperform a simple insertion heuristic when directly training on 12.8 million TSP200 samples for 500 hours on university-scale hardware; Appendix B: PyTorch on an Intel Xeon E5-2690 v4 server with four 1080Ti GPUs, one GPU per experiment, lowest training time across runs reported. Footnote: the largest TSP solved by Concorde has 109,399 nodes with 7.5 months running time. Results not recorded."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): algorithm design techniques (divide and conquer, dynamic programming, branch and bound, local search) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
