import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-2305.05176",
     "title": "FrugalGPT: How to Use Large Language Models While Reducing Cost and Improving Performance",
     "authors": ["Lingjiao Chen", "Matei Zaharia", "James Zou"],
     "year": 2023, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2305.05176"},
     "tasks": ["model-selection"],
     "fam": ["model-cascades", "large-language-models"], "par": ["supervised", "post-hoc"],
     "proposes": ["FrugalGPT: an LLM cascade over commercial LLM APIs that queries a learned list of APIs in sequence and stops when a learned generation scoring function (a DistilBERT regressor in the case study) scores the answer above a per-position threshold; the API list and thresholds are chosen by a constrained optimization under an average-cost budget. Also outlines prompt adaptation and LLM approximation (completion cache, fine-tuning) as cost-reduction strategies"],
     "claims": [
         ("Switching signal: the cascade decides whether to accept an API's answer or call the next API using a generation scoring function g(query, answer) in [0,1]; the authors state it can be obtained by training a simple regression model that predicts whether a generation is correct from the query and the generated answer (i.e. the score is computed after the cheaper model has answered).",
          "LLM cascade",
          "The scoring function can be obtained by training a simple regression model that learns whether a generation is correct from the query and a generated answer."),
         ("Thresholds and budget: the API list and the per-position threshold vector are learned jointly by maximizing expected reward subject to an average-cost budget b; because this is a mixed-integer problem, the authors use a specialized optimizer that prunes API lists with small answer disagreement and approximates the objective by interpolation over a few samples.",
          "LLM cascade",
          "To address this issue, we develop a specialized optimizer that (i) prunes the search space of L by ignoring any list of LLMs with small answer disagreement, and (ii) approximates the objective by interpolating it within a few samples."),
         ("Evaluation setup (models and cost): 12 commercial LLM APIs from OpenAI, AI21, CoHere, Textsynth and ForeFrontAI; cost is computed from the providers' per-token input/output prices and per-request fees (Table 1, prices retrieved March 2023).",
          "Experiments",
          "We have selected 12 LLM APIs from 5 mainstream providers, namely, OpenAI [Ope], AI21 [AI2], CoHere [CoH], Textsynth [Tex], and ForeFrontAI [FFA]."),
         ("Evaluation protocol: three datasets (HEADLINES financial news, OVERRULING legal sentences, COQA reading comprehension adapted to direct query answering), cascade length fixed at 3, and each dataset randomly split into a training set used to learn the cascade (its components being the scoring function and the API list with thresholds) and a test set. Thresholds are thus set on the training split; no separate validation split for threshold setting or scorer tuning was found in the text, and no shifted or out-of-distribution test set is used (random split only).",
          "Experiments",
          "Each dataset is randomly split into a training set to learn the LLM cascade and a test set for evaluation."),
         ("Main empirical claim (abstract): FrugalGPT can match the best individual LLM (e.g. GPT-4) with up to 98% cost reduction, or improve accuracy over GPT-4 by 4% at the same cost.",
          "Abstract",
          "Our experiments show that FrugalGPT can match the performance of the best individual LLM (e.g. GPT-4) with up to 98% cost reduction or improve the accuracy over GPT-4 by 4% with the same cost."),
         ("Failure mode of the switching mechanism: in an example where all LLMs in the chain give the same answer, FrugalGPT is unsure whether the first LLMs are correct and queries every LLM in the chain; the authors call avoiding such cases an open problem.",
          "Experiments",
          "However, FrugalGPT is unsure if the ﬁrst LLMs are correct, resulting in the need to query all LLMs in the chain."),
         ("Stated limitations: training the cascade needs labeled examples, and for the cascade to work well the training examples should come from the same or a similar distribution as the test examples; learning the cascade is an upfront cost that pays off when the final query set is larger than the training data.",
          "Discussions, Limitations and Future Prospects",
          "And in order for the cascade to work well, the training examples should be from the same or similar distribution as the test examples."),
     ],
     "notes": "Affiliation stated in the PDF: Stanford University (no company affiliation or funding statement found). Evaluated models are commercial APIs (OpenAI GPT-Curie/ChatGPT/GPT-3/GPT-4, AI21 J1 family, Cohere Xlarge, ForeFrontAI QA, Textsynth GPT-J/FAIRSEQ/GPT-Neox). The cascade calls several LLMs for one query (later routing papers RouteLLM and Hybrid LLM contrast themselves with this). Cost throughout is a dollar cost computed from the providers' March 2023 list prices (Table 1), not a share of calls to the strongest model. Numeric discrepancies within the paper: the abstract says accuracy gain up to 4% at the same cost while the Figure 5 caption says 'up to 5%'; the text says Table 3 cost savings 'range from 50% to 98%' while Table 3 lists 98.3%, 73.3% and 59.2%. The paper also reports a diversity measure (maximum performance improvement, MPI) between API pairs. Generalization to unseen query distributions or new APIs was not evaluated (random train/test split only)."},

    {"id": "arxiv-2406.18665",
     "title": "RouteLLM: Learning to Route LLMs with Preference Data",
     "authors": ["Isaac Ong", "Amjad Almahairi", "Vincent Wu", "Wei-Lin Chiang", "Tianhao Wu", "Joseph E. Gonzalez", "M Waleed Kadous", "Ion Stoica"],
     "year": 2024, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2406.18665"},
     "tasks": ["model-selection"],
     "fam": ["model-cascades", "large-language-models"], "par": ["supervised", "post-hoc"],
     "proposes": ["RouteLLM: a framework for learning binary strong/weak LLM routers from human preference data (Chatbot Arena battles grouped into model tiers) plus data augmentation (MMLU golden labels, GPT-4-judge labels); a win-prediction model P(strong wins | query) is thresholded by a cost threshold alpha, with four parameterizations (similarity-weighted Bradley-Terry ranking, matrix factorization, BERT classifier, Llama 3 8B causal classifier); evaluated with APGR and CPT metrics"],
     "claims": [
         ("Routing decision: before any LLM is called, a win-prediction model estimates the probability that the strong model beats the weak model on the query, and the query goes to the strong model when this probability is at least a cost threshold alpha; a higher alpha favours the weak model (stricter cost), a lower alpha favours the strong model. Each query is sent to a single LLM.",
          "Problem formulation",
          "The threshold α controls the trade-off between quality and cost: a higher value of α enforces stricter cost constraints by favoring weak models more often, while a lower α biases toward higher-quality (but more expensive) strong models."),
         ("Training signal: the primary preference data are 80k Chatbot Arena battles in which users vote between two anonymous models; to reduce label sparsity, models are clustered into 10 tiers by Arena leaderboard score, the top two tiers form the strong class and the third tier the weak class, and only winner identities (not responses) are kept.",
          "Chatbot Arena data",
          "Our primary source for preference data is the 80k battles from the online Chatbot Arena platform (Chiang et al., 2024), where users submit prompts and receive responses from two anonymous models."),
         ("Cost/quality metrics and thresholds: cost is measured as the percentage of calls to the strong model and quality relative to the weak-strong gap (performance gap recovered, PGR); APGR averages PGR over 10 discretized call percentages, choosing for each the threshold that satisfies that cost constraint, and CPT(x%) is the minimum percentage of strong-model calls needed to reach a PGR of x%. The text does not say on which data the thresholds for each call percentage are determined.",
          "Metrics",
          "For each ci, we determine the threshold αi that satisfies the cost constraint."),
         ("Evaluation protocol: MMLU, MT Bench (LLM-as-a-judge) and GSM8K, after discarding evaluation examples flagged by an embedding similarity search against the training data with a threshold of 0.95 (Appendix B); the authors present these public benchmarks as a test of out-of-domain generalization; main strong/weak pair gpt-4-1106-preview / Mixtral 8x7B; the baseline is a random router under the same cost constraint; BERT and causal-LLM routers use 5k samples held out from the Arena data as a validation set for model selection.",
          "Experiments",
          "MMLU (Hendrycks et al., 2020) consisting of 14,042 questions across 57 subjects, MT Bench (Zheng et al., 2023) with 160 open-ended questions using LLM-as-a-judge, and GSM8K (Cobbe et al., 2021) with over 1,000 grade school math problems"),
         ("Failure under query-distribution shift: routers trained only on Arena data perform at the level of the random router on MMLU (and close to random on GSM8K), which the authors attribute to most questions being out-of-distribution; adding about 1500 golden-labeled questions from MMLU's own validation split (for MMLU; i.e. in-domain data for that benchmark) or the roughly 120K GPT-4-judge labels on Nectar queries (for GSM8K) brings them above random. The authors relate router quality to an embedding-based benchmark-dataset similarity score.",
          "Results",
          "On MMLU (Table 2), all routers perform poorly at the level of the random router when trained only on Arena dataset, which we attribute to most MMLU questions being out-of-distribution (see Section 5.3)."),
         ("Generalization to unseen model pairs: the same routers (trained on Arena + judge data) are applied without retraining to Claude 3 Opus / Claude 3 Sonnet and Llama 3.1 70B / Llama 3.1 8B, which are not in the training data (the judge-labeled augmentation data compare GPT-4 and Mixtral responses); the authors report performance on MT Bench comparable to the original pair and significantly stronger than random. This transfer test is reported on MT Bench only, not on MMLU or GSM8K.",
          "Adaptability across models",
          "Importantly, we use the same routers as before without any retraining, and only replace the strong and weak model routed to."),
         ("Stated limitations: real-world query distributions may differ substantially from the evaluated benchmarks (the authors suggest collecting a small amount of in-domain data for augmentation); only two-model routing is studied; and performance of different routers trained on the same data can vary widely on the same benchmark without a clear explanation.",
          "Conclusion",
          "First, although we evaluate on a diverse set of benchmarks, real-world applications may have distributions that differ substantially from these benchmarks."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2025. Affiliations: UC Berkeley, Anyscale, Canva; funding acknowledgment lists gifts from Accenture, AMD, Anyscale, Google, IBM, Intel, Microsoft, MBZUAI, Samsung SDS, SAP, Uber and VMware. Several authors (Chiang, Gonzalez, Stoica) are among the authors of the Chatbot Arena paper (Chiang et al., 2024; source of the training data) and of the MT Bench / LLM-as-a-judge paper (Zheng et al., 2023; one of the evaluation benchmarks and the judge protocol used for the augmentation labels), per the reference list. Stoica is also affiliated with Anyscale, which is among the listed gift funders. Evaluated models: OpenAI GPT-4, Mistral Mixtral 8x7B, Anthropic Claude 3 Opus/Sonnet, Meta Llama 3.1; OpenAI text-embedding-3-small is used for embeddings. Cost in the metrics (and in the abstract's 'over 2 times') is the share of calls to the strong model, not dollars. The Table 6 'cost saving ratio' (up to 3.66x) is the inverse ratio of GPT-4 calls of the best router vs. the random baseline; dollar prices enter only as the justification that GPT-4 cost dominates (estimated averages of $24.7 for GPT-4, from gpt-4-1106 list prices and assumed prompt/response lengths, and $0.24 for Mixtral per million tokens; Appendix D). Appendix E compares against commercial routers (Unify AI, Martian) on MT Bench. Router overhead measured on Google Cloud VMs (Table 7). The paper says it open-sources the framework but no code URL was found in the PDF text. It criticizes Hybrid LLM (arxiv-2404.14618) for evaluating only on the MixInstruct test split without out-of-domain evidence (Related work)."},

    {"id": "arxiv-2404.14618",
     "title": "Hybrid LLM: Cost-Efficient and Quality-Aware Query Routing",
     "authors": ["Dujian Ding", "Ankur Mallick", "Chi Wang", "Robert Sim", "Subhabrata Mukherjee", "Victor Ruhle", "Laks V. S. Lakshmanan", "Ahmed Hassan Awadallah"],
     "year": 2024, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2404.14618", "code": "https://github.com/m365-core/hybrid_llm_routing"},
     "tasks": ["model-selection"],
     "fam": ["model-cascades", "large-language-models"], "par": ["supervised", "post-hoc"],
     "proposes": ["Hybrid LLM: a DeBERTa-v3-large query router that predicts the probability that a small model's response quality (BART score) is at least that of a large model (quality gap), with deterministic labels, probabilistic soft labels from 10 sampled responses per model, and a relaxed-label data transformation Pr[H(x) >= -t] for large quality gaps (t chosen by grid search); a test-time threshold on the router score trades quality for cost"],
     "claims": [
         ("Main empirical claim (abstract): routing on predicted query difficulty allows up to 40% fewer calls to the large model with no drop in response quality; the desired quality level can be tuned at test time.",
          "Abstract",
          "In experiments our approach allows us to make up to 40% fewer calls to the large model, with no drop in response quality."),
         ("Routing decision: an encoder router scores each query before generation, with a score designed to be large for 'easy' queries where the small model's quality is likely close to the large model's (an estimate of the quality gap tail probability); at test time a threshold on the score is tuned, and queries scoring above it go to the small model. Each query is sent to a single LLM.",
          "Hybrid LLM Inference",
          "At test time we achieve the desired performance accuracy tradeoff by tuning a threshold on the score and routing queries with score above the threshold to the small model."),
         ("Evaluation protocol: MixInstruct (real-world instructions from four public datasets); 10k training queries sampled from its training split with 10 responses per LLM, validation and test splits of 5k each from MixInstruct (the validation set is also used to choose router checkpoints); quality is BART score and cost is 'cost advantage' (fraction of queries routed to the small model); baselines are all-at-large, all-at-small and random routing. Models: FLAN-T5 (800m, 11b), Llama-2 (7b, 13b), GPT-3.5-turbo.",
          "Evaluation Setup",
          "We use BART score [Yuan et al., 2021] as the quality metric and use fraction of queries routed to the small model (cost advantage) as the efficiency metric (see Section 2.3)."),
         ("Failure mode: when the large model is much stronger than the small one (e.g. FLAN-t5 800m vs Llama-2 13b), the empirical probability that the small model is at least as good is near zero for most queries, giving a weak training signal; the deterministic and probabilistic routers then improve little over random assignment, which motivates the relaxed-label transformation.",
          "Section 3.3",
          "Because q(S(x)) << q(L(x)) for most queries in this case, it provides an extremely weak signal for training using Equation (2) and as shown in Section 4 both rdet and rprob fail to provide much improvement over random query assignment in this case."),
         ("Threshold selection: the authors recommend default thresholds from a small calibration set (500 random samples from the MixInstruct validation split, evaluated on the MixInstruct test split, grid search for the highest cost advantage with at most 1% BART-score drop) and report that test-set results closely follow validation results; for the Llama-2 7b/13b pair the performance drop increases slightly from validation to test, which they suggest handling with a more conservative limit.",
          "Section 4.5",
          "This clearly illustrates that a threshold chosen on the validation set generalizes well to the test set."),
         ("Generalization to other model pairs (on MixInstruct with BART-score quality gaps; the specific pairs are not named in the text): routers applied to LLM pairs different from their training pair generalize well when the quality gaps of the test pair correlate strongly with those of the training pair, and performance decays as the correlation weakens; the authors propose this correlation as an early indicator of whether a router can be reused. A similar dependence on correlation is reported when evaluating with GPT-4 scores instead of BART score (Section 4.6).",
          "Section 4.7",
          "Similar to our observation in Section 4.6, our routers can generalize well if the quality gaps of testing LLM pairs exhibit strong positive correlation with the quality gaps of the training pairs."),
         ("Stated limitation: the model pair and data distribution are fixed across training and testing; the authors note that training a new router for every new model pair and data distribution may be cumbersome or infeasible and list out-of-distribution generalization as future work (along with task-aware routing, N-model routing and better evaluation metrics).",
          "Discussion and Conclusion",
          "In this work, the model pair and data distribution is fixed across training and testing."),
     ],
     "notes": "Affiliations: University of British Columbia, Microsoft (first author's work performed during an internship at Microsoft), Hippocratic AI (one author's work performed while at Microsoft). Evaluated models include OpenAI GPT-3.5-turbo (via API), Meta Llama-2 and Google FLAN-T5; no conflict-of-interest statement found. The abstract's 'no drop in response quality' at up to 40% fewer large-model calls corresponds to the small-performance-gap pair (Llama-2 7b vs 13b); Table 1 reports larger drops at 40% cost advantage for medium and large gaps. Numeric/wording discrepancies within the paper: the abstract says 'no drop in response quality' while the conclusion says 'no significant drop'; Table 3 (thresholds chosen on 500 validation samples with <=1% drop) gives test cost advantages above 96% for the Llama-2 7b/13b pair, far above the abstract's 'up to 40%', with test drops of 1.39-1.60% exceeding the 1% limit (and rtrans 1.02% for the FLAN-t5/Llama-2 13b pair). Cost is a proxy (fraction routed to the small model), not API prices; router latency is measured but GPT-3.5-turbo latency is not. RouteLLM (arxiv-2406.18665) later criticizes this paper for lacking out-of-domain evaluation; this paper itself states the distribution is fixed (claim on limitations)."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model fallback and model selection in MLOps (meta-learned selection, dynamic selection, abstention/deferral, switching triggers, cascades/routing, monitoring); carded by a subagent. Results tables not recorded; claims only.")
