import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ai_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1111.4246",
     "title": "The No-U-Turn Sampler: Adaptively Setting Path Lengths in Hamiltonian Monte Carlo",
     "authors": ["Matthew D. Hoffman", "Andrew Gelman"],
     "year": 2011, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1111.4246"},
     "tasks": ["posterior-inference"],
     "fam": ["mcmc"],
     "proposes": ["No-U-Turn Sampler (NUTS): an extension of HMC that removes the number-of-steps parameter L by repeatedly doubling a leapfrog trajectory forwards or backwards in time (building a balanced binary tree) until some subtree starts to make a U-turn, then sampling the next state from the visited states in a way that preserves detailed balance",
                  "A dual-averaging scheme (adapted from Nesterov's primal-dual algorithm) that adapts the step size during burn-in so that an average acceptance statistic matches a target delta, for both HMC and NUTS"],
     "claims": [
         ("Motivation (citing Creutz, 1988): the cost of HMC per independent sample from a D-dimensional target is roughly O(D^(5/4)), in contrast with O(D^2) for random-walk Metropolis. The price is that HMC needs the gradient of the log-posterior and the user must set a step size and a number of steps, and a poor choice of either causes a dramatic drop in efficiency.",
          "Introduction",
          "which stands in sharp contrast with the O(D2) cost of random-walk Metropolis (Creutz, 1988)"),
         ("The naive rule of running leapfrog steps until the trajectory starts moving back towards the starting point does not guarantee time reversibility and therefore is not guaranteed to converge to the correct distribution; NUTS instead uses a recursive doubling procedure (reminiscent of Neal's slice-sampling doubling) and must exclude from the candidate set any states that could not have generated the same tree.",
          "Section 3.1",
          "Unfortunately this algorithm does not guarantee time reversibility, and is therefore not guaranteed to converge to the correct distribution."),
         ("Besides the U-turn rule, NUTS stops doubling when the simulation error becomes extremely large (the log joint density of a leaf falls more than Delta_max below the slice variable); the authors note this may happen if the step size is too large or if hard constraints make the log density go to minus infinity in some regions.",
          "Section 3.1.1",
          "We also want to stop expanding B if the error in the simulation becomes extremely large, indicating that any states discovered by continuing the simulation longer are likely to have astronomically low probability."),
         ("Step-size adaptation: Robbins-Monro diminishing step sizes give disproportionate weight to early iterations, so the authors adapt dual averaging (with shrinkage target mu, free parameters gamma, t0 and kappa) to drive an acceptance statistic towards a target delta, with x = log(epsilon); for NUTS the statistic is the average HMC acceptance probability of the states explored during the final doubling. In Algorithms 5 and 6 adaptation runs for M_adapt iterations and the step size is then fixed.",
          "Section 3.2",
          "However, the diminishing step sizes of Robbins-Monro give disproportionate weight to the early iterations, which is the opposite of what we want."),
         ("The dual-averaging parameters (gamma = 0.05, t0 = 10, kappa = 0.75) were chosen by trying a few settings by hand on the stochastic volatility model; the authors say they seem to work consistently well for all models tested but that it is entirely possible they may not work as well for other samplers or other statistics.",
          "Section 3.2",
          "Better results might be obtained with further tweaking, but these default parameters seem to work consistently well for both NUTS and HMC for all of the models that we tested."),
         ("Evaluation protocol: four targets (a 250-dimensional correlated multivariate normal, Bayesian logistic regression and hierarchical logistic regression on the German credit data, and a 3001-dimensional stochastic volatility posterior); each run has 2000 iterations with step-size adaptation in the first 1000, HMC with 10 simulation lengths and several delta targets, 10 seeds per setting. Efficiency is ESS per gradient evaluation, taking the minimum over dimensions of the ESS for the mean and the second central moment, with reference mean and variance from a separate 50,000-iteration NUTS run (delta = 0.5).",
          "Section 4",
          "We measure the eﬃciency of each algorithm in terms of eﬀective sample size (ESS) normalized by the number of gradient evaluations used by each algorithm."),
         ("Recommended targets: HMC's best performance seems to occur around delta = 0.65 and NUTS's around delta = 0.6, without strong dependence on delta within [0.45, 0.65] for NUTS, so the authors suggest 0.6 as a reasonable default for NUTS.",
          "Section 4.4",
          "δ = 0.6 therefore seems like a reasonable default value for NUTS."),
         ("Comparison with HMC (text statement from Figure 6): on the two logistic regression problems NUTS is about as efficient as HMC, on the multivariate normal and stochastic volatility problems NUTS with delta = 0.6 outperforms HMC's best ESS by about a factor of three; the best HMC simulation lengths varied by about a factor of 100 across targets, so the authors say the results suggest NUTS is at least as efficient as HMC even ignoring HMC's tuning runs.",
          "Section 4.4",
          "The results in Figure 6 suggest that NUTS can generate samples at least as eﬃciently as HMC, even discounting the cost of any preliminary runs needed to tune HMC’s simulation length."),
         ("Scope limits: NUTS was compared only with basic HMC (not its extensions) and only with an identity mass matrix; like HMC it can only resample unconstrained continuous variables with respect to which the target is differentiable almost everywhere, so discrete variables must be summed out or handled by other algorithms such as Gibbs sampling.",
          "Section 5 (Discussion)",
          "Like HMC, NUTS can only be used to resample unconstrained continuous-valued variables with respect to which the target distribution is diﬀerentiable almost everywhere."),
     ],
     "notes": "Affiliation: Columbia University. The arXiv comment gives only '30 pages, 7 figures' and the v1 PDF does not name a journal; no venue recorded (later versions may have been published elsewhere, not checked). Section numbers are from numbered headings in the PDF. Conflict of interest: the authors state they are developing Stan with NUTS as its core algorithm (Discussion), and the qualitative comparison with random-walk Metropolis and Gibbs (Section 4.5, Figure 7) is informal. The efficient NUTS (Algorithm 3) stores O(j) states instead of O(2^j); the U-turn checks cost about as many inner products as leapfrog steps, which the authors say is usually negligible compared with gradient cost. Most trajectory lengths were powers of two (Section 4.3). ESS estimator: autocorrelations truncated when they first dip below 0.05 (Appendix A). Discussion notes that a mass matrix approximating the posterior covariance would help both NUTS and HMC. Results figures not recorded."},

    {"id": "arxiv-1701.02434",
     "title": "A Conceptual Introduction to Hamiltonian Monte Carlo",
     "authors": ["Michael Betancourt"],
     "year": 2017, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1701.02434"},
     "tasks": ["posterior-inference"],
     "fam": ["mcmc"],
     "proposes": [],
     "claims": [
         ("Typical set: in high dimensions the neighbourhood around the mode has large density but little volume and the far tails have large volume but negligible density, so expectations are dominated by an intermediate region called the typical set, which becomes narrower (more singular) as dimension grows; the author presents this as a manifestation of concentration of measure.",
          "Section 1.4",
          "The only signiﬁcant contributions come from the neighborhood between these two extremes known as the typical set (Figure 3)."),
         ("Random Walk Metropolis in high dimensions: almost every proposal lands outside the typical set and is rejected, while shrinking the proposal makes moves tiny; the author states that however it is tuned, the chain explores the typical set extremely slowly in all but the lowest dimensional spaces.",
          "Section 2.4",
          "Regardless of how we tune the covariance of the Random Walk Metropolis proposal or the particular details of the target distribution, the resulting Markov chain will explore the typical set extremely slowly in all but the lowest dimensional spaces."),
         ("Why momentum is needed: the gradient of the target density is parameterization-dependent and following it leads towards the mode rather than through the typical set; HMC adds auxiliary momentum with a probabilistic structure that gives conservative (Hamiltonian) dynamics, so trajectories glide along the typical set.",
          "Section 3.1",
          "Following the guidance of the gradient pulls us away from the typical set and towards the mode of the target density."),
         ("Pathologies and split R-hat: a typical set that pinches into a region of high curvature is missed by most Markov transitions, causing biased and oscillating estimators; the sufficient condition for a CLT is geometric ergodicity, which is hard to verify, so empirical diagnostics are used; the author calls split R-hat (across chains started from different points) the most powerful, and says values not near 1 should raise suspicion.",
          "Section 2.3",
          "Consequently, when split ˆR is not near the nominal value of 1, we should be suspicious of geometric ergodicity being satisﬁed and hence the practical utility of any resulting estimators."),
         ("Integration time: integrating too briefly wastes HMC's coherent exploration and integrating too long gives diminishing returns; the optimal time differs between trajectories (in a one-dimensional family it grows into the tails for heavy-tailed targets), so the author argues for choosing it dynamically, e.g. with the No-U-Turn criterion, which has proven an empirical success though near-optimality is shown only in some simple cases.",
          "Section 4.3",
          "In general, this optimal integration time will vary strongly depending on which trajectory we are considering: no single integration time will perform well everywhere."),
         ("Step size: for the simple static implementation, bounds between cost and average acceptance probability (citing Betancourt, Byrne and Girolami, 2014) underlie an adaptation that tunes the step size during an extended warm-up to an average Metropolis acceptance probability between 0.6 and 0.8; the author notes that more work is needed to formalize the corresponding results for more sophisticated implementations.",
          "Section 5.3",
          "These bounds provide the basis for an automated tuning algorithm that adapts the step size during an extended warm-up to achieve an average Metropolis acceptance probability between 0.6 and 0.8"),
         ("Divergences: regions of high curvature (characteristic of many models, in particular hierarchical models, citing Betancourt and Girolami, 2015) make symplectic integrators unstable so that trajectories diverge; any divergent transition should prompt suspicion of the estimators. Mild cases can be fixed by decreasing the step size, but often divergences persist however small the step, indicating significant bias, and the target itself must be regularized (stronger priors or an alternative representation such as switching centered/non-centered parameterizations).",
          "Section 6.2",
          "In particular, any divergent transitions encountered in a Hamiltonian Markov chain should prompt suspicion of the validity of any Markov chain Monte Carlo estimators."),
         ("Heavy tails and the kinetic energy: a poorly chosen kinetic energy can make the marginal energy distribution heavy-tailed so that exploration between energy level sets is incomplete; this is identified by comparing the marginal energy and energy-transition distributions, formalized as the energy Bayesian fraction of missing information (E-BFMI), with values below 0.3 empirically problematic but no formal threshold.",
          "Section 6.1",
          "Empirically, values of this energy Bayesian fraction of missing information below 0.3 have proven problematic"),
         ("Limits of the diagnostics: the E-BFMI and divergence diagnostics are only necessary, not sufficient, conditions for valid estimators; without explicit theoretical analysis there is no guarantee that a target will not have subtler pathologies, although the author argues that combined with split R-hat over multiple chains they make HMC uniquely robust.",
          "Section 6.3",
          "Although these two diagnostics are powerful means of identifying many pathological target distributions, they are only necessary and not suﬃcient conditions for the validity of the Markov chain Monte Carlo estimators."),
     ],
     "notes": "Affiliation: Applied Statistics Center, Columbia University (previously Warwick). Review/tutorial; no experiments. No venue is stated in the PDF or the arXiv comment ('60 pages, 42 figures'); none recorded. Section numbers are from numbered headings in the PDF (e.g. '2.3 Pathological Behavior', '6.2 Diagnosing Regions of High Curvature'). Conflict of interest: the author thanks the Stan development team 'with whom the implementations were developed' and repeatedly presents Stan as the reference implementation; many of the cited diagnostics and results (E-BFMI, step-size bounds, exhaustive termination) are the author's own earlier work. Other content not carded as claims: metric (mass matrix) adaptation by estimating the posterior covariance in warm-up (Section 4.2.1); Riemannian HMC; Stan replaced NUTS's slice sampling with multinomial sampling and a generalized No-U-Turn criterion (Appendix A.5). No discussion of multimodality was found in the text (searched for multimodal, multi-modal, metastab, modes)."},

    {"id": "arxiv-1402.4102",
     "title": "Stochastic Gradient Hamiltonian Monte Carlo",
     "authors": ["Tianqi Chen", "Emily B. Fox", "Carlos Guestrin"],
     "year": 2014, "venue": "ICML 2014", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1402.4102"},
     "tasks": ["posterior-inference"],
     "fam": ["mcmc", "bayesian-deep-learning"], "par": ["supervised"],
     "proposes": ["Stochastic gradient HMC (SGHMC): HMC with minibatch gradients plus a friction term in the momentum update (second-order Langevin dynamics), with a user-specified friction C >= B_hat and injected noise N(0, 2(C - B_hat) eps), run without a Metropolis-Hastings step"],
     "claims": [
         ("Naive stochastic-gradient HMC: approximating the minibatch gradient noise as Gaussian (central limit theorem), replacing the gradient adds diffusion to the momentum, and the target pi(theta, r) is no longer invariant (Corollary 3.1); Theorem 3.1 shows the entropy increases, which the authors say hints that the distribution tends toward a uniform distribution.",
          "Section 3.1",
          "Formally, as given by Corollary 3.1 of Theorem 3.1, when B is nonzero, π(θ, r) of Eq. (3) is no longer invariant under the dynamics described by Eq. (7)."),
         ("Correcting naive SG-HMC with Metropolis-Hastings creates a trade-off: an MH step after short simulations needs a full-data computation each time, while long simulations between MH steps lead to very low acceptance rates.",
          "Section 3.1",
          "Each of these MH steps requires a costly computation using all of the data, thus defeating the computational gains of considering noisy gradients."),
         ("Friction: adding a friction term B M^-1 r to the momentum update gives second-order Langevin dynamics for which pi(theta, r) is the unique stationary distribution of the continuous system (Theorem 3.2); the authors relate it to partial momentum refreshment, which had not greatly improved HMC with noise-free gradients (citing Neal, 2010).",
          "Section 3.2",
          "The key was to introduce a friction term using second-order Langevin dynamics."),
         ("Relation to SGLD: SGLD's first-order Langevin dynamics can be viewed as the limiting case of SGHMC's dynamics with a large friction term.",
          "Section 3.2",
          "In particular, the dynamics of SGLD can be viewed as second-order Langevin dynamics with a large friction term."),
         ("In practice the gradient-noise covariance B is unknown; with a user-set friction C dominating an estimate B_hat (e.g. B_hat = 0), exact correctness is obtained only as the step size goes to zero, and decreasing step sizes reduce efficiency, so like SGLD the authors use a small non-zero step size, accepting some bias (a finite-step error analysis is in the supplement).",
          "Section 3.3",
          "As in (Welling & Teh, 2011; Ahn et al., 2012) for SGLD, we consider using a small, non-zero ϵ leading to some bias."),
         ("No Metropolis-Hastings correction is used in SGHMC; the authors note that, as in SGLD, an MH correction is not even possible because the probability of the reverse dynamics cannot be computed.",
          "Section 3.3 (footnote 1)",
          "We note that, just as in SGLD, an MH correction is not even possible because we cannot compute the probability of the reverse dynamics."),
         ("The supplementary error analysis (Theorem F.1, chi-squared divergence decreasing as the noise-estimation error shrinks) assumes a mixing-rate bound; the authors state that such bounds exist for SGLD but are unclear for SGHMC because the process is irreversible, and leave this for future work.",
          "Appendix F",
          "but the corresponding bounds for SGHMC are unclear due to the irreversibility of the process"),
         ("Experiments: a 1-D simulated target with synthetic gradient noise (naive SG-HMC deviates from the truth unless MH is added, SGHMC without MH is close), a correlated bivariate Gaussian against SGLD, a Bayesian two-layer network on MNIST, and online Bayesian PMF on MovieLens ml-1M; on MovieLens both SGHMC and SGLD beat the optimization baselines and the authors report SGLD and SGHMC results as very similar.",
          "Section 4.3",
          "In this experiment, the results for SGLD and SGHMC are very similar."),
     ],
     "notes": "Affiliation: University of Washington. Venue from the PDF first page ('Proceedings of the 31 st International Conference on Machine Learning, Beijing, China, 2014') and the arXiv comment. Section numbers from numbered headings. Simulated-experiment conclusions (Figures 1-3) are figure-based; the MNIST result (SGHMC converging to low test error faster than SGLD, sampling methods better than SGD) is shown only as a figure. Hyperparameters for all methods were selected on a held-out validation set (MNIST: 10,000 of the training images) or by cross-validation (MovieLens), with small grids listed in Appendix H; momentum term alpha fixed (0.01 MNIST, 0.05 MovieLens) and beta_hat = 0. No gold-standard posterior is used for the real-data experiments; evaluation is predictive (test error, RMSE). Appendix G gives practical settings (minibatch of hundreds, alpha 0.01 or 0.1, eta = gamma/|D|) and the SGD-with-momentum parameterization."},

    {"id": "arxiv-1909.11827",
     "title": "Convergence diagnostics for Markov chain Monte Carlo",
     "authors": ["Vivekananda Roy"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1909.11827"},
     "tasks": ["posterior-inference"],
     "fam": ["mcmc"],
     "proposes": [],
     "claims": [
         ("Scope: the review distinguishes convergence of the chain to stationarity (deciding burn-in) from convergence of Monte Carlo estimators (deciding when to stop); rigorous answers need theoretical analysis (e.g. total-variation bounds or a Markov chain CLT), and otherwise empirical diagnostics are used, which the author says cannot determine convergence with certainty.",
          "Introduction",
          "In the absence of such theoretical analysis, often empirical diagnostic tools are used to check convergence of MCMC samplers and estimators, although, as shown through examples in Section 3, these tools cannot determine convergence with certainty."),
         ("Honest stopping rules: the fixed-width stopping rule stops when the half-width of a confidence interval for the estimate falls below a preset threshold (after a minimum number of iterations); its validity needs a Markov chain CLT and a consistent asymptotic-variance estimator, usually obtained by proving geometric ergodicity (drift and minorization conditions).",
          "Section 2.1",
          "Jones and Hobert (2001) refer to this method as the honest way to stop the chain."),
         ("Gelman-Rubin diagnostic: m chains started from over-dispersed points; the potential scale reduction factor compares a pooled variance estimate with the within-chain variance and simulation stops when it is close to 1, with the cutoff 1.1 generally used (as recommended by Gelman et al., 2014); a multivariate version (MPSRF) exists.",
          "Section 2.4",
          "The cutoﬀvalue 1.1 is generally used by MCMC practitioners, as recommended by Gelman et al. (2014)."),
         ("Assumptions: the Geweke and Heidelberger-Welch spectral diagnostics, ESS and the Gelman-Rubin diagnostic all assume the existence of a Markov chain CLT, which the author says emphasizes the need for theoretical analysis.",
          "Section 2.5",
          "Finally, we would like to mention that the two spectral density based methods mentioned here, just like the ESS and the GR diagnostic, assume the existence of a Markov chain CLT (2), emphasizing the importance of the theoretical analysis discussed in Section 2.1."),
         ("Exponential target example (independence Metropolis): with the well-mixing sampler, R-hat over four chains fell below 1.1 within 100 iterations while the estimate of the mean at that point was 1.109 (SE 0.111) against the true value 1, so the author concludes the GR diagnostic leads to premature termination; for the poorly mixing (subgeometric) sampler, the Geweke and Heidelberger-Welch tests were passed in a 1,000-iteration run.",
          "Section 3.1",
          "Thus, GR diagnostic leads to premature termination of simulation and the inference drawn from the resulting samples can be unreliable."),
         ("Multimodal example (six modes, Metropolis-within-Gibbs): when four chains start at the same local mode, the trace and autocorrelation plots, Geweke, Heidelberger-Welch and Raftery-Lewis diagnostics, PSRF and MPSRF (below 1.1) all fail to detect non-convergence, because the diagnostics use only the samples, which all lie around one mode.",
          "Section 3.2",
          "Since all four chains are stuck at the same local mode, that is, these are not run long enough to move between the modes, the convergence diagnostics, including PSRF, MPSRF get fooled into thinking that the target distribution is unimodal and hence falsely detect convergence."),
         ("The author's own Tool 2 (Dixit and Roy, 2017; the reviewer is a co-author) compares a kernel density estimate of the chain with the unnormalized target density and detected the stuck chains in the multimodal example; the author notes that because it involves numerical integration it cannot be used in high-dimensional examples.",
          "Section 3.2",
          "Thus, Dixit and Roy (2017)’s Tool 2 is successful in detecting the divergence of the chains."),
         ("Bayesian logistic regression example (10 parameters, random-walk Metropolis via MCMCpack): after burn-in, all PSRF and the MPSRF were below 1.1 and the KL tool was passed, yet the largest 95% confidence-interval half-width was 0.112 against a target of 0.01, so a much longer run was needed for the desired precision.",
          "Section 3.3",
          "On the other hand, the maximum half-width among the 10 regression parameters is 0.112, much larger than the cutoﬀ0.01."),
         ("Recommendations: empirical diagnostics can falsely detect convergence when chains do not move between modes and may stop the simulation prematurely, so the author recommends fixed-width and ESS-based stopping rules, single long runs for final inference, and caution when relying purely on empirical diagnostics, especially if multiple modes are suspected.",
          "Section 4 (Conclusions and discussion)",
          "Practitioners should be careful while depending purely on empirical convergence diagnostic tools, especially if the presence of multiple modes is suspected."),
     ],
     "notes": "Affiliation: Iowa State University. The PDF uses an Annual Reviews template with placeholder metadata ('xxxxxx 0000. 00:1-25', 'Copyright 0000 by Annual Reviews') and does not name the journal; the arXiv record given to the carder has no comment or journal_ref, so no venue is recorded. Section numbers from numbered headings. Conflict of interest: the KL-divergence diagnostics (Tool 1, Tool 2, tile-plot visualization) are from Dixit and Roy (2017), co-authored by the reviewer, and are the only tools shown succeeding in the multimodal example; several cited CLT results are also the author's own work. The review covers random-walk/independence Metropolis and Gibbs samplers; HMC-specific diagnostics (divergences, E-BFMI) and the rank-normalized split R-hat are not discussed (searched for Hamiltonian, HMC, split; 'divergence' appears only for KL divergence and for chains that have not mixed). ESS and mESS cutoffs are derived from the desired relative precision (Vats et al. 2019). Thinning is recommended only when storage or evaluating g is expensive (Section 4)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
