import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-2005.10242",
     "title": "Understanding Contrastive Representation Learning through Alignment and Uniformity on the Hypersphere",
     "authors": ["Tongzhou Wang", "Phillip Isola"],
     "year": 2020, "venue": "ICML 2020", "version": "arXiv v10",
     "links": {"arxiv": "https://arxiv.org/abs/2005.10242"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised", "unsupervised"],
     "proposes": ["Alignment loss L_align: expected distance (to the power alpha) between the l2-normalized features of positive pairs",
                  "Uniformity loss L_uniform: log of the average pairwise Gaussian potential between normalized features, whose unique minimizer on the hypersphere is the uniform distribution",
                  "Analysis showing that, as the number of negatives goes to infinity, the contrastive loss with normalized features optimizes alignment and uniformity"]
     ,
     "claims": [
         ("Setting and assumption: positive pairs are typically two independent random augmentations of the same sample; the analysis assumes the positive-pair distribution is symmetric and that its marginal matches the data distribution, and studies one specific form of contrastive loss (normalized features, temperature tau, M negatives drawn from the data distribution).",
          "Section 3",
          "Based on empirical practices, we assume the following property."),
         ("Instead of reading the contrastive loss as a lower bound on mutual information, the authors analyse the loss itself, because (citing Tschannen et al., 2019) the bound interpretation is known to have issues in practice, e.g. maximizing a tighter bound often gives worse downstream performance.",
          "Section 3",
          "However, this interpretation is known to have issues in practice, e.g., maximizing a tighter bound often leads to worse downstream task performance (Tschannen et al., 2019)."),
         ("Theorem 1 (limit of infinitely many negatives, fixed tau): the first term of the limiting loss is minimized iff the encoder is perfectly aligned, perfectly uniform encoders, if they exist, are the exact minimizers of the second term, and the deviation from the limit decays as O(M^-1/2).",
          "Section 4.2 (Theorem 1)",
          "If perfectly uniform encoders exist, they form the exact minimizers of the second term.", 6),
         ("Perfect uniformity is not always realizable (e.g. when the data manifold is lower-dimensional than the feature space), and when the pair distributions come from augmenting a finite dataset no encoder can be both perfectly aligned and perfectly uniform; perfectly uniform encoders do exist when n >= m - 1 and the data distribution has bounded density.",
          "Section 4.2 (Realizability of perfect uniformity)",
          "Moreover, in the case that pdata and ppos are formed from sampling augmented samples from a ﬁnite dataset, there cannot be an encoder that is both perfectly aligned and perfectly uniform, because perfect alignment implies that all augmentations from a single element have the same feature vector."),
         ("On the latent-class analysis (citing Saunshi et al., 2019): the authors say it gives nice theoretical insights but has a rather large gap with practice, because its result that representation quality suffers with a large number of negatives is inconsistent with empirical observations.",
          "Section 2 (Related Work)",
          "Analysis based on the assumption of latent classes provides nice theoretical insights (Saunshi et al., 2019), but unfortunately has a rather large gap with empirical practices"),
         ("Evaluation protocol: 304 STL-10, 64 NYU-Depth-V2, 45 ImageNet-100 (MoCo-based) and 108 BookCorpus (Quick-Thought-based) encoders are trained with weighted combinations of the three losses; for the tables, the 'best' encoder is selected by cross-validation on the training set (5-fold for STL-10) and then reported on the validation set.",
          "Table 1",
          "The best result is picked by encoder outputs linear classiﬁer accuracy from a 5-fold training set cross validation, among all 150 encoders trained from scratch with 128-dimensional output and 768 batch size."),
         ("Encoders trained only with L_align and L_uniform consistently outperformed their contrastive-loss counterparts in the STL-10 and NYU-Depth-V2 tables; the authors suggest that directly optimizing the two properties can be superior in practice when only finite negatives are available.",
          "Section 5",
          "This empirical performance gap suggests that directly optimizing these properties can be superior in practice, when we can only have ﬁnite negatives."),
         ("Both properties are needed: weighting alignment much higher than uniformity produces a degenerate (collapsed) solution mapping all inputs to the same feature; as long as the weight ratio is not too large (e.g. < 4), representation quality stays relatively good and insensitive to the exact weights.",
          "Section 5",
          "When Lalign is weighted much higher than Luniform, degenerate solution occurs and all inputs are mapped to the same feature vector (exp Luniform = 1)."),
     ],
     "notes": "Affiliation: MIT CSAIL. Venue from the PDF first page ('Proceedings of the 37th International Conference on Machine Learning, Online, PMLR 119, 2020') and the arXiv comment. The analysis is restricted to l2-normalized features; Section 6 states that why the unit hypersphere is a nice feature space is not yet rigorously answered. The changelog notes Theorem 1's convergence rate was corrected to O(M^-1/2) and two STL-10 encoders were removed in 2022. A weaker result for a single negative (M = 1) is given in the appendix. Full-ImageNet MoCo v2 comparison (Table 5, 200 epochs) uses MoCo v2 numbers from the official implementation. Saunshi et al. (2019) is the reference entry for arXiv 1902.09229 (Arora et al. in this index). Results tables not recorded."},

    {"id": "arxiv-1902.09229",
     "title": "A Theoretical Analysis of Contrastive Unsupervised Representation Learning",
     "authors": ["Sanjeev Arora", "Hrishikesh Khandeparkar", "Mikhail Khodak", "Orestis Plevrakis", "Nikunj Saunshi"],
     "year": 2019, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1902.09229"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["unsupervised"],
     "proposes": ["A latent-class framework for contrastive learning in which similar pairs are i.i.d. draws from the same latent class and downstream tasks consist of subsets of the same latent classes",
                  "Generalization bounds relating the unsupervised contrastive loss to the average linear (mean-classifier) classification loss on downstream tasks",
                  "CURL: a contrastive objective that uses blocks of similar points (averaging positive and negative blocks) instead of pairs"],
     "claims": [
         ("Core assumption (latent classes): similar points x, x+ are i.i.d. draws from the same class distribution D_c for a class c drawn from rho, and negatives are drawn from the marginal; i.e. the pair is conditionally independent given the latent class. Classes may overlap and no functional form is assumed for D_c or rho.",
          "Section 2 (Semantic Similarity)",
          "To formalize similarity, we assume similar data points x, x+ are i.i.d. draws from the same class distribution Dc for some class c picked randomly according to measure ρ."),
         ("The guarantees depend on downstream tasks being made of the same latent classes, with the same class distributions, as the unlabeled data; downstream classes are assumed uniformly distributed in the main-paper theorems (general case in the appendix).",
          "Section 2 (Supervised Tasks)",
          "A key subtlety in this formulation is that the classes in downstream tasks and their associated data distributions Dc are the same as in the unlabeled data."),
         ("Price of negative sampling (class collision): because the negative can come from the same class as the positive pair, the unsupervised loss is at least tau (the probability that two sampled classes coincide), and without further assumptions on f it can be far from tau, making the Theorem 4.1 bound useless; the authors then control this term with an intraclass-deviation quantity s(f) (Theorem 4.5).",
          "Section 4.2",
          "In general, without any further assumptions on f, Lun(f) can be far from τ, rendering the bound in Theorem 4.1 useless."),
         ("Limitation: the ideal guarantee (competing with the best supervised representation in the class F) is shown not to hold, with two counterexamples attributed to the algorithm rather than the analysis; contrastive learning will not always work when the only guarantee is that F can make the supervised loss small.",
          "Section 5.1",
          "Hence, contrastive learning will not always work when the only guarantee we have is that F can make Lsup small."),
         ("A weaker, competitive bound (Corollary 5.1.1, for the mean classifier) holds under additional assumptions: representations that are concentrated within classes (sub-Gaussian in every direction) and a mean classifier with good (high-margin) performance.",
          "Introduction",
          "However, if the representations are well-concentrated and the mean classiﬁer (Deﬁnition 2.1) has good performance, we can show a weaker version of the ideal result (Corollary 5.1.1)."),
         ("Contrary to the belief that more negatives always help, the analysis shows that larger k can hurt: with rho close to uniform and k = Omega(|C|), frequent class collisions can prevent learning the supervised-optimal representation (the coefficient of s(f) grows with k).",
          "Section 6.2",
          "However, we ﬁnd that such a phenomenon does not always hold for contrastive learning – larger k can hurt performance for the same inherent reasons highlighted in Section 5.1, as we illustrate next."),
         ("Controlled experiments (CIFAR-100 with VGG-16, Wiki-3029 with a GRU) simulate the assumed data model by sampling similar pairs/blocks from the same labelled class and negatives at random, and compare with supervised training of the same architecture; the main evaluation is average k-wise classification with the mean classifier, while full multiclass accuracy (TOP-R) is reported but not covered by the theory.",
          "Section 8.1",
          "Contrastive learning was done using our objectives (5), and compared to performance of standard supervised training, with both using the same architecture for representation f."),
         ("Scope: the framework ignores efficient minimization of the losses and studies only the relations between their minimizers and the sample complexity needed to generalize; the authors call it a first cut.",
          "Conclusion",
          "The framework currently ignores issues of efﬁcient minimization of various loss functions, and instead studies the interrelationships of their minimizers as well as sample complexity requirements for training to generalize, while clarifying what generalization means in this setting."),
     ],
     "notes": "Affiliations: Princeton University, Institute for Advanced Study, Carnegie Mellon University. The PDF (arXiv v1) carries only 'Copyright 2019 by the authors' and states no venue; none recorded (other papers cite it as ICML 2019, not used). Related Work notes the data model can be seen as a special case of co-training's conditionally independent views with identical conditional distributions, but without labelled data. Table 1 caption: full multiclass (TOP-R) 'is not covered by our theory'. The block extension CURL is compared with Quick-Thought (QT) on IMDb using the same GRU architecture. Wang & Isola (arXiv 2005.10242) criticize the negative-count prediction as inconsistent with practice. Results tables not recorded."},

    {"id": "arxiv-2005.10243",
     "title": "What Makes for Good Views for Contrastive Learning?",
     "authors": ["Yonglong Tian", "Chen Sun", "Ben Poole", "Dilip Krishnan", "Cordelia Schmid", "Phillip Isola"],
     "year": 2020, "venue": "NeurIPS 2020", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2005.10243"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["The InfoMin principle: good views share the minimal information necessary for the downstream task (reduce I(v1; v2) while keeping task-relevant information)",
                  "Unsupervised (adversarial) and semi-supervised view learning with invertible pixel-wise flow generators",
                  "InfoMin Aug: a stronger augmentation set (with a PIRL-style JigSaw branch) motivated by the principle"],
     "claims": [
         ("InfoMin principle: a good set of views shares the minimal information necessary to perform well on the downstream task; the authors argue that maximizing information is useful only insofar as it is task-relevant.",
          "Introduction",
          "A good set of views are those that share the minimal information necessary to perform well at the downstream task."),
         ("Proposition 3.1 assumes minimal sufficient encoders and a downstream task known in advance: the optimal views minimize I(v1; v2) subject to I(v1; y) = I(v2; y) = I(x; y), and the representation learned from them is then optimal for the task.",
          "Proposition 3.1",
          "More formally, the following InfoMin proposition articulates which views are optimal supposing that we know the speciﬁc downstream task T in advance."),
         ("Caveat on applying the proposition: unlike the information-bottleneck setting, contrastive learning usually has no labelled training set specifying the downstream task, so the task-relevant information in views cannot easily be evaluated during training; views are instead guided by domain knowledge.",
          "Three Regimes of Information Captured",
          "Unlike in information bottleneck, for contrastive learning we often do not have access to a fully-labeled training set that speciﬁes the downstream task in advance, and thus evaluating how much task-relevant information is contained in the views and representation at training time is challenging."),
         ("Measurement caveat: mutual information between views is measured with I_NCE as a neural proxy, which depends on the network architecture, so each plot varies only the input views while keeping other settings fixed.",
          "View Selection Inﬂuences Mutual Information and Accuracy",
          "We use INCE as a neural proxy for I, and note it depends on network architectures."),
         ("The reverse-U relationship between shared information and downstream performance is presented as an upper bound that might not be reached if views share noise rather than signal.",
          "View Selection Inﬂuences Mutual Information and Accuracy",
          "The upper-bound reverse-U might not be reached if views are selected that share noise rather than signal."),
         ("Task dependence (Colorful Moving-MNIST toy, frozen backbone with a linear task head): what the views share determines which factors are learned; when background is shared, digit information is left out, which the authors say might be because background bits predominate and act as a shortcut for the contrastive task.",
          "Optimal Views Depend on the Downstream Task",
          "This might because the information bits of background predominates, and the encoder chooses the background as a “shortcut” to solve the contrastive pre-training task."),
         ("Learning views without labels (adversarially minimizing I_NCE with a flow generator) in most cases over-reduces I_NCE and was unstable across runs with the same hyperparameters; the authors conjecture the generator, lacking task knowledge, breaks the constraint of Proposition 3.1, and add a semi-supervised variant that uses a handful of downstream labels.",
          "Unsupervised View Learning: Minimize I(v1; v2)",
          "In addition, we found this GAN-style training is unstable, as different runs with the same hyper-parameter vary signiﬁcantly."),
         ("Augmentation strength: varying the magnitude of RandomResizedCrop and Color Jittering traces reverse-U shapes on ImageNet, and the sweet spots (crop area bound 0.2, jitter strength 1.0) are identified from these plots (MoCo framework, 100 pre-training epochs, linear classifier trained for 60 epochs, per Appendix C).",
          "Data Augmentation to Reduce Mutual Information between Views",
          "The plots on ImageNet [16] are shown in Fig. 5, where we identify a sweet spot at 1.0 for Color Jittering and 0.2 for RandomResizedCrop."),
     ],
     "notes": "Affiliations: MIT CSAIL, Google, Brown University, Google Research. Venue from the PDF first page ('34th Conference on Neural Information Processing Systems (NeurIPS 2020)') and the arXiv comment. Funding: Google (Y. Tian as a student researcher); four authors are Google employees (competing-interests statement). The headline ImageNet result (73.0% top-1 linear readout, ResNet-50) is obtained with InfoMin Aug + JigSaw, a 2-layer MLP head and 800 epochs (Appendix C.3); SimCLR and other baselines in Table 1 are cited. Transfer: COCO (Mask R-CNN R50-FPN, Detectron2, 200-epoch pre-training) and Pascal VOC (Faster R-CNN R50-C4, average of 5 runs, some baseline numbers copied from MoCo). Broader Impact notes that view constructions are not bias free. Results tables not recorded."},

    {"id": "arxiv-2110.09348",
     "title": "Understanding Dimensional Collapse in Contrastive Self-supervised Learning",
     "authors": ["Li Jing", "Pascal Vincent", "Yann LeCun", "Yuandong Tian"],
     "year": 2021, "venue": "ICLR 2022", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2110.09348"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["Two mechanisms for dimensional collapse in contrastive learning: strong augmentation (single linear layer) and implicit regularization (over-parametrized linear networks)",
                  "DirectCLR: apply InfoNCE directly to a fixed sub-vector of the backbone representation, without a trainable projector"],
     "claims": [
         ("Empirical observation: for a SimCLR model with a two-layer MLP projector trained 100 epochs on ImageNet, the singular-value spectrum of the covariance of 128-d embeddings on the validation set has a number of singular values collapsing to zero, although negatives prevent complete collapse.",
          "Dimensional Collapse",
          "We observe that a number of singular values collapse to zero, thus representing collapsed dimensions."),
         ("Mechanism 1 (single linear layer, additive-noise augmentation, InfoNCE, plain SGD without momentum or weight decay): the weight update is driven by the difference of a weighted data covariance and a weighted augmentation covariance; if augmentation is strong enough that this matrix has negative eigenvalues, the weight matrix gets vanishing singular values and the embedding covariance becomes low-rank.",
          "Dimensional Collapse Caused by Strong Augmentation (Theorem 1)",
          "With ﬁxed matrix X (deﬁned in Eqn 6) and strong augmentation such that X has negative eigenvalues, the weight matrix W has vanishing singular values."),
         ("The strong-augmentation theory is limited to linear networks; for nonlinear networks the authors say 'strong augmentation' would depend on more complicated properties (higher-order statistics, manifold properties) conditioned on network capacity.",
          "Dimensional Collapse Caused by Strong Augmentation",
          "Our theory in this section is limited to linear network settings."),
         ("Mechanism 2 (implicit regularization): with small augmentation and an over-parametrized two-layer linear network (no bias, unnormalized output), adjacent weight matrices align and small singular values grow much more slowly, so the embedding covariance becomes low-rank; this happens only with more than one layer.",
          "Dimensional Collapse Caused by Implicit Regularization (Corollary 2)",
          "With small augmentation and over-parametrized linear networks, the embedding space covariance matrix becomes low-rank."),
         ("The alignment result (Theorem 2) assumes distinct singular values; the toy experiment initializes non-degenerate singular values, and with random initialization in real scenarios only block-diagonal alignment is expected.",
          "Weight Alignment",
          "In real scenario, when weight matrices are randomly initialized, we will only observe the alignment matrix to converge to a block-diagonal matrix, with each block representing a group of degenerate singular values."),
         ("Role of the projector: comparing SimCLR trained with and without a projector, dimensional collapse in the representation (backbone output) space appears without a projector, so the projector prevents collapse there.",
          "DirectCLR (Motivation)",
          "The dimensional collapse in representation space happens when the model is trained without a projector."),
         ("Stated limit of the theory: it can explain a linear projector (DirectCLR replaces it) but cannot fully explain why a nonlinear projector prevents dimensional collapse, and DirectCLR still relies on the last nonlinear backbone block for that mechanism.",
          "DirectCLR (Disclaimer)",
          "But our theory is not able to fully explain why a nonlinear projector is able to prevent dimensional collapse."),
         ("Protocol: ResNet-50, SimCLR recipe for 100 epochs (LARS, batch size 4096 on 32 GPUs); the sub-vector size d0 was tuned on ImageNet linear-probe top-1 accuracy. No separate held-out split for this tuning was found in the text (searched for validation, held-out, tuning).",
          "Appendix E (Figure 12)",
          "Hyperparameter tuning on d0 based on ImageNet linear probe Top-1 accuracy."),
     ],
     "notes": "Affiliation: Facebook AI Research. Venue from the PDF header ('Published as a conference paper at ICLR 2022') and the arXiv journal_ref. Conflict of interest: Yuandong Tian is a co-author both here and of the non-contrastive dynamics paper it builds on and cites (Tian et al. 2021, arXiv 2102.06810); the paper states its Lemma 2 is more general than Theorem 4 of Tian et al. (2020). Augmentations: random crop, resize, flip, color jitter, grayscale, blur, solarization. Baselines (SimCLR with/without projector) are the authors' own runs. Appendix C extends the theory to multilayer and nonlinear settings (not read in detail). Results tables not recorded."},

    {"id": "arxiv-2102.06810",
     "title": "Understanding self-supervised Learning Dynamics without Contrastive Pairs",
     "authors": ["Yuandong Tian", "Xinlei Chen", "Surya Ganguli"],
     "year": 2021, "venue": "ICML 2021", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2102.06810"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["A gradient-flow analysis of non-contrastive SSL (BYOL/SimSiam) in a bias-free linear model with online, predictor and EMA target weights, explaining the roles of predictor, stop-gradient, EMA, relative predictor learning rate and weight decay",
                  "DirectPred: setting the linear predictor directly from the eigen-decomposition of the estimated correlation matrix of its inputs, without gradient training"],
     "claims": [
         ("Theorem 2 (SimSiam case, W_a = W): removing the stop-gradient turns the update into a PSD-matrix flow, and if its minimal eigenvalue stays bounded below the weights go to zero; the authors say this proves, in this simple setting, collapse without stop-gradient (and similarly without a predictor).",
          "Two-layer linear model (Theorem 2)",
          "Thus we have proven analytically in this simple setting that removing the stop-gradient leads to representational collapse"),
         ("Theorem 1: weight decay promotes balancing between predictor and online weights, so what the predictor learns the online network also learns; a nonzero weight decay could help remove the initialization-dependent constant.",
          "Two-layer linear model (Theorem 1)",
          "Instead what the predictor learns, the online network will also learn, which is important as the online network’s representations are what is used for downstream tasks."),
         ("Simplifying assumptions behind the analytic results: (1) the EMA target stays proportional to the online network, (2) isotropic data (zero mean, identity covariance) and isotropic augmentation noise, (3) a symmetric predictor; the authors report that the predictions still hold qualitatively when the assumptions do not.",
          "How multiple factors affect learning dynamics (Assumption 2)",
          "We assume the data distribution p(x) has zero mean and identity covariance, while the augmentation distribution paug(·|x) has mean x and covariance σ2I."),
         ("Theorem 3: under these assumptions the eigenspaces of the predictor and of the correlation matrix of its inputs gradually align (given a positive-definite condition), giving decoupled per-mode dynamics; the non-symmetric-predictor case is left for future work.",
          "Section 3.1",
          "When Assumption 3 is absent, the analysis is much more convoluted."),
         ("Collapse in the decoupled dynamics: a collapsed fixed point always exists; with weight decay there is a basin of attraction to collapse that grows with weight decay, and under strong enough weight decay collapse is unavoidable.",
          "Section 3.2",
          "Under such strong weight decay collapse is unavoidable (Obs#5)."),
         ("EMA can act as an automatic curriculum by setting a small initial goal for the predictor eigenvalues and raising it gradually, with the trade-offs of slow training for slow EMA and more modes possibly trapped in the collapsed basin.",
          "Section 3.2 (Role of EMA)",
          "Therefore, EMA can serve as an automatic curriculum (Obs#8)"),
         ("Experimental protocol: STL-10/CIFAR-10 use ResNet-18, SGD (lr 0.03, momentum 0.9, weight decay 0.0004, EMA 0.996), 5 repeats per setting; ImageNet uses the authors' own BYOL implementation with ResNet-50, with architecture, augmentations and linear classification protocol strictly following BYOL (60-epoch and 300-epoch settings).",
          "Optimization-free Predictor Wp (ImageNet experiments)",
          "The architecture design (e.g., feature dimensions), augmentation strategies (e.g., color jittering, blur (Chen et al., 2020a), solarization, etc.) and linear classiﬁcation protocol strictly follow BYOL (Grill et al., 2020)."),
         ("Scope: the theory covers a linear predictor; for the 2-layer predictor used in practice the authors give no formal analysis, only an intuition that its wide hidden layer offers 'lucky' initial directions that speed up eigenspace alignment.",
          "Section 5 (Discussion)",
          "While we don’t provide a formal analysis and the math can be quite complicated"),
     ],
     "notes": "Affiliations: Facebook AI Research, Stanford University. Venue from the PDF first page ('Proceedings of the 38th International Conference on Machine Learning, PMLR 139, 2021'). Conflict of interest: Xinlei Chen is a co-author of SimSiam (Chen & He, 2020), one of the two methods analysed; Yuandong Tian later co-authored the dimensional-collapse paper (arXiv 2110.09348) that cites this work. The analysis is a gradient flow in the limit of large batch sizes and small learning rates. Table 1 reports that plugging in the 'optimal' linear predictor performs poorly, which the authors use against the always-optimal-predictor conjecture. Symmetric predictors without EMA fail unless the relative predictor learning rate is > 1 or weight decay is applied only to the predictor (Tables 3, 5; Figure 6). Results tables not recorded."},
]

from topic_ssl_common import BASE_NOTE, CREATED  # noqa: E402

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
