import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_gnn_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2006.05205",
     "title": "On the Bottleneck of Graph Neural Networks and its Practical Implications",
     "authors": ["Uri Alon", "Eran Yahav"],
     "year": 2020, "venue": "ICLR 2021", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2006.05205", "code": "https://github.com/tech-srl/bottleneck/"},
     "tasks": ["graph-node-prediction", "graph-level-prediction"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["Over-squashing: an explanation for GNNs' difficulty with long-range interactions, in which information from a receptive field that grows exponentially with the number of layers is compressed into fixed-length node vectors",
                  "Fully-adjacent (FA) last layer: in the K-th layer only, every pair of nodes is connected (N_v := V), used as a diagnostic to show that breaking the bottleneck helps existing tuned models",
                  "Tree-NeighborsMatch: a synthetic problem with controllable problem radius r used to observe over-squashing in training accuracy"],
     "claims": [
         ("Bottleneck argument: with problem radius r, a GNN needs K >= r layers (otherwise distant nodes cannot interact, which the authors later call under-reaching), but the receptive field grows exponentially with K (citing Chen et al., 2018), so an exponentially growing amount of information is squashed into a fixed-length vector; the model then learns only short-range signals and 'might generalize poorly at test time'.",
          "Section 3",
          "When a prediction problem relies on long-range interaction between nodes, the GNN must have as many layers K as the estimated range of these interactions, or otherwise, these distant nodes would not be able to interact."),
         ("Layer definitions used in the analysis: a GNN layer is h_v^(k) = f_k(h_v^(k-1), {h_u^(k-1) | u in N_v}; theta_k); GCN sums c_uv W^(k) h_u^(k-1) over N_v together with v itself, with normalization c_uv often set to sqrt(|N_v||N_u|) or |N_v| (citing Hamilton et al., 2017), followed by a nonlinearity; GIN applies an MLP to (1 + eps) h_v plus the sum of neighbor states. For graph prediction a permutation-invariant readout (sum, average or weighted sum) aggregates the final-layer nodes.",
          "Preliminaries",
          "The design of the function f is what mostly distinguishes one type of GNN from the other."),
         ("On Tree-NeighborsMatch (binary trees, r = depth, r+1 layers, training accuracy measured), GCN and GIN perfectly fit r = 3 at most, while GGNN and GAT also reach 100% at r = 4, and at r = 5 no GNN fits the data perfectly. The authors explain this by aggregation: GCN and GIN aggregate all neighbors before combining with the target node, whereas GAT's attention lets the target ignore the irrelevant incoming edge at the last layer; they hypothesize (following Levy et al., 2018) that the GRU in GGNN filters edges similarly.",
          "Section 4.1",
          "GCN and GIN managed to perfectly ﬁt r=3 at most, while GGNN and GAT also reached 100% accuracy at r=4."),
         ("FA-layer protocol: the K-th layer of an existing, extensively tuned model is turned into a fully-adjacent layer (no change of layer type, no added weights), and models are re-trained with the original authors' code without additional tuning, to rule out hyperparameter tuning as the source of improvement. The authors stress that the FA layer is merely a simple demonstration, not their main contribution.",
          "Section 4.2",
          "A fully-adjacent layer is a GNN layer in which every pair of nodes is connected by an edge."),
         ("Over-squashing vs. under-reaching on QM9 (models and 500-configuration tuning from Brockschmidt, 2020; 5 runs per property): the average graph diameter is 6.35±0.91 (maximum 10, 90th percentile 8) while most models use K = 8; models with 10 layers did not improve over the base, models with doubled hidden size improved by only 5.5% versus 42% for the FA layer, and making all K layers fully adjacent gave 1500% higher error. The authors conclude the gain comes from reduced over-squashing, not increased reachability.",
          "Section 4.2",
          "We conclude that the source of improvement was clearly not the increased reachability, but instead, the reduction in over-squashing."),
         ("Biological benchmarks: using the implementation, 10 folds and splits of Errica et al. (2020) (30 test runs = 10 folds x 3 seeds), converting the last layer to FA gave GIN+FA an improvement of 1.5% over GIN on NCI1, and on ENZYMES (where Errica et al. found the structure-agnostic baseline better than all GNNs) GIN+FA improved by 8.1% over GIN and by 2.5% over the No Struct baseline; on average FA reduced the error rate by 12% on ENZYMES and 4.8% on NCI1.",
          "Biological benchmarks",
          "We used the same 10-folds and split as Errica et al. (2020)."),
         ("Combinatorial lower bound (analysis stated to hold for GCN and GIN): a d-dimensional vector of f-bit floats must distinguish all (m^r)!/(m!)^(m^r - 1) label assignments of the tree leaves, so with d = 32 the maximal radius is r = 7. Empirically the required d is higher because gradient descent need not find a solution; even d = 512 fits r = 7 at most. Attention-based aggregation like GAT compresses only half of the leaves, raising the bound on r by up to 1.",
          "Section 5",
          "That is, a model with d=32 cannot obtain 100% accuracy for r>7."),
         ("Relation to over-smoothing: the authors hypothesize that in long-range problems the degraded performance is explained by over-squashing rather than over-smoothing, which was mostly demonstrated on short-range tasks; in Appendix E they argue the two are disparate (a 3-node triangle graph with r = 1 can over-smooth without over-squashing, while Tree-NeighborsMatch can over-squash without over-smoothing).",
          "Section 6",
          "We hypothesize that in long-range problems, the explanation for the degraded performance is over-squashing rather than over-smoothing."),
     ],
     "notes": "Affiliation: Technion. Venue from the PDF header ('Published as a conference paper at ICLR 2021') and the arXiv comment ('Accepted to ICLR'2021'); year is the first arXiv version (2020). Section numbers: Section 3, 4, 4.1, 4.2, 4.4, 5, 6 and Appendix E are confirmed by cross-references in the PDF; the 'Preliminaries' and 'Biological benchmarks' sections are named only (their numbers are not stated). VarMisuse (Section 4.4, implementation of Brockschmidt, 2020 with 30 configurations per GNN, 6-10 layers best): the paper says the FA layer improves all GNNs on SeenProjTest and some/most on UnseenProjTest; table values not recorded. Tables 1-3 (QM9, NCI1/ENZYMES, VarMisuse) are not recorded. The base numbers are re-used from Brockschmidt (2020) and Errica et al. (2020) ('previously reported ... and reproduced by us' for QM9); the acknowledgments thank Errica and Brockschmidt for help with their frameworks. Appendix A states that to rule out tuning as the cause of degraded Tree-NeighborsMatch performance, activations, normalization, residuals, batch sizes and weight unrolling were varied, and a chain-shaped control (long distance with r=2-level squashing) was fitted close to 100%. No conflict of interest found: the authors do not evaluate their own earlier GNN models."},

    {"id": "arxiv-1811.05868",
     "title": "Pitfalls of Graph Neural Network Evaluation",
     "authors": ["Oleksandr Shchur", "Maximilian Mumme", "Aleksandar Bojchevski", "Stephan Günnemann"],
     "year": 2018, "venue": "Relational Representation Learning Workshop (R2L 2018), NeurIPS 2018", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1811.05868", "code": "https://www.kdd.in.tum.de/gnn-benchmark"},
     "tasks": ["graph-node-prediction"],
     "fam": ["graph-neural-networks", "deep-learning", "linear-models"], "par": ["semi-supervised"],
     "proposes": ["A standardized evaluation of GCN, MoNet, GAT and GraphSAGE variants for transductive semi-supervised node classification: same training procedure, same hyperparameter-selection strategy, 100 random train/validation/test splits with 20 random initializations each",
                  "Four new node-classification datasets: Coauthor CS, Coauthor Physics, Amazon Computers and Amazon Photo"],
     "claims": [
         ("Critique of common practice: many proposed models were tested only on the same train/validation/test splits of CORA, CiteSeer and PubMed from Yang et al. (2016), which the authors say favors the model that overfits the most; second, new models are often trained with a procedure different from the baselines', making it hard to tell whether gains come from the architecture or from better-tuned training/hyperparameters (citing Lipton and Steinhardt, 2018).",
          "Section 1",
          "Such experimental setup favors the model that overﬁts the most and defeats the main purpose of using a train/validation/test split — ﬁnding the model with the best generalization properties [Friedman et al., 2001]."),
         ("Training procedure: model architectures are kept as in the original papers (2 layers; 8 attention heads for GAT, 2 Gaussian kernels for MoNet), but all models use the same optimizer (Adam with default parameters), Glorot initialization with zero biases, no learning-rate decay, the same maximum epochs, early-stopping criterion, patience and validation frequency, and full-batch training. Appendix A documents that the original procedures differed (e.g. GraphSAGE used mini-batches of 512 and no early stopping).",
          "Section 3",
          "For a more balanced comparison, however, we use the same training procedure for all the models."),
         ("Split protocol: for every dataset, 20 labeled nodes per class for training, 30 per class for validation and the rest for test, with 100 random splits and 20 random weight initializations per split; graphs are treated as undirected and restricted to the largest connected component.",
          "Section 3",
          "In all cases, we use 20 labeled nodes per class as the training set, 30 nodes per class as the validation set, and the rest as the test set."),
         ("Hyperparameter selection: the same grid search (learning rate, hidden size, L2 strength, dropout) for every model, restricted so that every model has at most the same number of trainable parameters; the configuration with the best average accuracy on Cora and CiteSeer (over 100 splits x 20 initializations) is then used for all datasets, so the other six datasets are not tuned individually.",
          "Section 3",
          "For every model, we picked the hyperparameter conﬁguration that achieved the best average accuracy on Cora and CiteSeer datasets (averaged over 100 train/validation/test splits and 20 random initializations for each)."),
         ("Baselines and overall result: the GNNs (GCN, MoNet, GAT, GraphSAGE) significantly outperform all baselines - attribute-only MLP and logistic regression, and structure-only label propagation (plain and normalized-Laplacian) - on all 8 datasets, but among the GNNs there is no clear winner across datasets; for 5 of 8 datasets the 2nd and 3rd best are within 1% of the best average.",
          "Section 3",
          "Among the GNN approaches, there is no clear winner that dominates across all the datasets."),
         ("Averaged over datasets and splits (relative accuracy and average rank), GCN achieves the best performance; the authors relate this to findings in other fields that simpler models often outperform more sophisticated ones if hyperparameter tuning is performed equally carefully (citing Melis et al., 2018 and Lucic et al., 2017).",
          "Section 3",
          "We observe that GCN is able to achieve the best performance across all models."),
         ("Effect of the split: on the Planetoid split of Yang et al. (2016), GAT scores best on CORA and CiteSeer and GCN on PubMed, but on a different random split with the same set sizes GCN is first on CORA and CiteSeer and MoNet wins on PubMed; the authors conclude that results from a single split are fragile and misleading and that multiple-split evaluation is needed.",
          "Section 3",
          "This shows how fragile and misleading results obtained on a single split can be."),
         ("GAT's lower average and high variance on Amazon Computers and Amazon Photo comes from rare outliers: median scores of all GNNs are very close, but GAT produces extremely low scores (below 40%) for some weight initializations, in 138 of 2000 runs on Amazon Photo.",
          "Section 3",
          "While these outliers occur rarely (for 138 out of 2000 runs), they signiﬁcantly lower the average score of GAT."),
     ],
     "notes": "Affiliation: Technical University of Munich. Venue from the PDF page-1 footer ('Relational Representation Learning Workshop (R2L 2018), NeurIPS 2018, Montréal, Canada'); the arXiv record has no comment or journal_ref. Section numbers are from numbered headings (1 Introduction, 2 Models, 3 Evaluation, 4 Conclusion). The text says 'extensive grid search' and then 'We restricted the random search space'; the Appendix C grid lists hidden size [8,16,32,64], 5 learning rates, 7 dropout values and 7 L2 strengths, a unified early-stopping rule (stop when total validation loss does not improve for 50 epochs, restore the best weights) and at most 100k epochs. A footnote warns that standard deviations are not the best representation of variance because scores are not normally distributed. Table 1/2 values are not recorded. Possible conflict of interest: CORA-Full comes from Bojchevski and Günnemann (2018), co-authors of this paper; no model by the authors is among the compared GNNs."},

    {"id": "arxiv-1912.09893",
     "title": "A Fair Comparison of Graph Neural Networks for Graph Classification",
     "authors": ["Federico Errica", "Marco Podda", "Davide Bacciu", "Alessio Micheli"],
     "year": 2019, "venue": "ICLR 2020", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1912.09893", "code": "https://github.com/diningphil/gnn-comparison"},
     "tasks": ["graph-level-prediction"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["A standardized evaluation protocol for graph classification: 10-fold stratified CV for model assessment with an inner 90%/10% holdout for model selection, three final training runs per fold, pre-computed shared splits and identical node features",
                  "Structure-agnostic baselines (a Molecular Fingerprint sum-pooling + MLP for chemical data, and a DeepSets-style MLP-sum-MLP for social data and ENZYMES) to test whether GNNs exploit graph structure"],
     "claims": [
         ("Risk assessment (model assessment): k-fold CV uses k training/test splits, and for each split an internal model selection picks hyperparameters using the training data only, so test data is never used for model selection; because each split may select a different configuration, the estimate refers to the performance of a class of models.",
          "Section 3",
          "This way, test data is never used for model selection."),
         ("Model selection (hyperparameter tuning on a validation set or inner split) gives biased, generally over-optimistic estimates of generalization (citing Cawley & Talbot, 2010); the authors state that clearly separating model selection and model assessment estimates is their main contribution and is lacking or ambiguous in the reviewed literature.",
          "Section 3.2",
          "Consequently, model selection results are generally over-optimistic; this issue is thoroughly documented in Cawley & Talbot (2010)."),
         ("Review of DGCNN, DiffPool, ECC and GIN (based solely on the papers and available code at submission time): model-selection code is not provided for any of them; GIN, as stated in its paper and review discussion, reports validation accuracy of 10-fold CV; for DiffPool it is unclear whether results are on a test set, and its splits are random without a seed; ECC reports no standard deviations; DGCNN tunes learning rate and epochs on one fold only.",
          "Section 4",
          "In other words, reported results refer to model selection and not to model evaluation."),
         ("Experimental setting: 10-fold CV for assessment, an inner 90%/10% holdout for selection, then three training runs on the whole training fold (each holding out a random 10% for early stopping) averaged to smooth unfavorable initializations; all splits are pre-computed and stratified. Grid search over 32 to 72 configurations per model (always including those used by the original authors), more than 47000 training runs in total, with a 72-hour limit per training.",
          "Experiments",
          "Our experimental approach is to use a 10-fold CV for model assessment and an inner holdout technique with a 90%/10% training/validation split for model selection."),
         ("Features: all models get the same node features - one-hot atom types for chemical datasets (plus 18 available features on ENZYMES) and, for social datasets without features, either an uninformative constant feature or the node degree. The authors note that GIN's one-hot degree features trade improved performance for inability to generalize to graphs with arbitrary node degree.",
          "Experiments",
          "In general, good experimental practices suggest that all models should be consistently compared to the same input representations."),
         ("Baselines that ignore topology: if a GNN performs close to a structure-agnostic baseline, either the task does not need topology or the GNN is not exploiting structure adequately; the latter is harder to assess (training data size, inductive bias, hyperparameters), while significant improvements over the baseline are a strong indicator that topology has been exploited.",
          "Experiments",
          "As a matter of fact, if GNN performances are close to the ones of a structure-agnostic baseline, one can draw two possible conclusions: the task does not need topological information to be effectively solved, or the GNN is not exploiting graph structure adequately."),
         ("Results: on D&D, PROTEINS and ENZYMES none of the five GNNs improves over the structure-agnostic baseline, while on NCI1 the baseline is clearly outperformed; an over-parameterized baseline (10000 hidden units, no regularization) reaches around 67% training accuracy on NCI1 whereas GIN can easily overfit (≈100%). The authors suggest that small gains on these datasets are likely caused by other factors such as random initialization rather than exploiting structure.",
          "Results and Discussion",
          "Importantly, we discover that on D&D, PROTEINS and ENZYMES none of the GNNs are able to improve over the baseline."),
         ("Node degree on social datasets: adding degrees as features is almost always beneficial, enough for the baseline to improve by ≈15% and achieve the best result on IMDB-BINARY, and it drastically changes the model ranking; it matters less for most GNNs except DGCNN; across folds the median number of layers drops by ≈1 (GraphSAGE excepted), which the authors say 'may be due to' architectures computing the degree in the first layer.",
          "Results and Discussion",
          "Based on our results, using node degrees as input features is almost always beneﬁcial to increase performances on social datasets, sometimes by a large amount."),
     ],
     "notes": "Affiliation: University of Pisa. Venue from the PDF header ('Published as a conference paper at ICLR 2020') and the arXiv comment ('Extended version of the paper published at ICLR 2020. Additional results are shown in the appendix'); the v3 PDF is dated 17 Feb 2022; year is the first arXiv version (2019). Section numbers 3, 3.2 and 4 are confirmed by cross-references ('described in Section 3', 'discussed in Section 3.2', 'we saw in Section 4'); the Experiments and Results sections are named only. Also stated: test accuracies 'are in most cases different from what reported in the literature' and average validation accuracies are always higher than or equal to test results, 'as expected' (Comparison with published results; from Figure 1, values not recorded). Tables 3-4 and the appendix results are not recorded. GraphSAGE was adapted to graph classification with max-pooling readout and no neighbor sampling. Datasets: D&D, PROTEINS, NCI1, ENZYMES (chemical), IMDB-BINARY, IMDB-MULTI, REDDIT-BINARY, REDDIT-5K, COLLAB (social). No conflict of interest found: the compared models are not by the authors (the authors' own earlier work, e.g. Bacciu, Errica and Micheli 2018 CGMM, is cited but not evaluated). This framework is later re-used by arxiv-2006.05205 for its NCI1/ENZYMES experiments."},

    {"id": "arxiv-2006.11468",
     "title": "Beyond Homophily in Graph Neural Networks: Current Limitations and Effective Designs",
     "authors": ["Jiong Zhu", "Yujun Yan", "Lingxiao Zhao", "Mark Heimann", "Leman Akoglu", "Danai Koutra"],
     "year": 2020, "venue": "NeurIPS 2020", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2006.11468", "code": "https://github.com/GemsLab/H2GCN"},
     "tasks": ["graph-node-prediction"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["semi-supervised"],
     "proposes": ["Edge homophily ratio h: the fraction of edges connecting nodes with the same class label, used to characterize homophily (h -> 1) versus heterophily (h -> 0)",
                  "Three designs for heterophily: (D1) ego- and neighbor-embedding separation, (D2) higher-order neighborhoods, (D3) combination of intermediate representations",
                  "H2GCN: graph-agnostic feature embedding, K rounds of aggregation over 1-hop and 2-hop neighborhoods excluding the ego (concatenated, degree-normalized, without per-round nonlinearity), and concatenation of all rounds for classification"],
     "claims": [
         ("Definition 1: the edge homophily ratio h is the fraction of edges connecting nodes with the same class label (intra-class edges); graphs with strong homophily have h -> 1 and strong heterophily h -> 0. The authors stress that heterophily is distinct from heterogeneity (multiple node/edge types), and that homophily may vary across class pairs (captured by a class compatibility matrix in App. B).",
          "Section 2",
          "is the fraction of edges in a graph which connect nodes that have the same class label (i.e., intra-class edges)."),
         ("Motivating failure: on the synthetic syn-cora benchmark with h = 0.1, all existing GNNs tested fail to beat an MLP with 1 hidden layer that ignores the graph, and GCN and GAT are up to 42% worse than MLP, suggesting that methods that work well under high homophily may not be appropriate under low/medium homophily.",
          "Section 3",
          "Especially, GCN [17] and GAT [36] show up to 42% worse performance than MLP, highlighting that methods that work well under high homophily (h = 0.7) may not be appropriate for networks with low/medium homophily."),
         ("D1 and Theorem 1: under specific conditions (no self-loops, one-hot label features, equal class counts in training, all training nodes of degree d with a proportion h of same-class neighbors and the rest uniform over other classes, and h below a threshold depending on |Y| and d), a GCN layer (A + I)XW that co-embeds ego and neighbor features misclassifies under smaller train/test deviations than an AXW layer that separates them; the authors note the theorem applies to specific conditions and support more general cases empirically.",
          "Section 3.1",
          "We prove theoretically that, under some conditions, a GCN layer that co-embeds ego- and neighbor-features is less capable of generalizing to heterophily than a layer that embeds them separately."),
         ("D2 and Theorem 2: under heterophily the immediate neighborhood may be heterophily-dominant while higher-order neighborhoods may be homophily-dominant; assuming neighbors' labels are conditionally independent given y_v with P(y_u = y_v) = h and the rest uniform, the 2-hop neighborhood is always homophily-dominant in expectation.",
          "Section 3.1",
          "In the case of heterophily, we have seen empirically that although the immediate neighborhoods may be heterophily-dominant, the higher-order neighborhoods may be homophily-dominant and thus provide more relevant context."),
         ("D3 and Theorem 3: assuming GCN-style propagation acts as a low-pass filter (citing [37], the SGC paper), earlier rounds keep more high-frequency components; for label signals with edge homophily h_s < h_t, s has more energy in the high-frequency components of the unnormalized Laplacian spectrum, so combining intermediate representations (as in jumping knowledge networks) captures both low- and high-frequency information.",
          "Section 3.1",
          "In other words, in heterophily settings, the label distribution contains more information at higher than lower frequencies (see proof in App. C.3)."),
         ("H2GCN: (S1) a graph-agnostic dense embedding r_v^(0) = sigma(x_v W_e); (S2) K rounds where r_v^(k) concatenates aggregations over the 1-hop and 2-hop neighborhoods excluding v, each a degree-normalized sum with weights d_{v,i}^(-1/2) d_{u,i}^(-1/2), without per-round nonlinear transformations as in SGC (found to work better); (S3) softmax classification of the concatenation of r^(0)..r^(K). Aggregation costs O(2^K (|E| + |E2|) p) plus O(|E| d_max) to derive 2-hop neighborhoods.",
          "Section 3.2",
          "We found that removing the usual nonlinear transformations per round, as in SGC [37], works better (App. D.2), in which case we only need to include the ego-embedding in the ﬁnal representation."),
         ("Evaluation protocol and a split discrepancy: synthetic graphs (syn-cora, syn-products, 3 graphs per h) use 25%/25%/50% per-class splits; real benchmarks (except Cora-Full) use the features, labels and 10 random splits provided by Geom-GCN [26], which the authors report as 48%/32%/20%, noting that [26] claims 60%/20%/20%, different from the splits shared on GitHub; Cora-Full uses 3 random 25%/25%/50% splits. All models are tuned on the same train/validation splits (App. F).",
          "Section 5.2",
          "claims that the ratios are 60%/20%/20%, which is different from the actual data splits shared on GitHub."),
         ("On real benchmarks, MLP is a competitive baseline under heterophily (average rank 6.2), which the authors read as many existing models not using graph information effectively or the graph being misleading; all models perform poorly on Squirrel and Actor 'likely due to' low-quality node features, and Squirrel and Chameleon are dense with many nodes sharing the same neighbors. GEOM-GCN ranks are taken from its paper rather than re-run.",
          "Section 5.2",
          "We note that MLP is a competitive baseline under heterophily (ranked 6.2), indicating that many existing models do not use the graph information effectively, or the latter is misleading in such cases."),
         ("Data limitations: Cora, Pubmed and Citeseer all have h >= 0.7, which the authors say masked the limitations of the homophily assumption, and the OGB datasets they examined have h > 0.5; the heterophily benchmarks used also have limitations - small sizes (WebKB), artificial classes (Squirrel and Chameleon labels from page-traffic ranking) and unusual dense structure.",
          "Appendix H",
          "As a result, the wide adaptation of these benchmarks have masked the limitations of the homophily assumption in many existing GNN models."),
     ],
     "notes": "Affiliations: University of Michigan, Carnegie Mellon University. Venue from the PDF page-1 footer ('34th Conference on Neural Information Processing Systems (NeurIPS 2020), Vancouver, Canada') and the arXiv comment ('Accepted to NeurIPS 2020; version with full appendix'). Section numbers confirmed by cross-references in the PDF (§ 2, § 3, § 3.1, § 3.2, § 5.1, § 5.2, App. H). Conflict of interest: the authors propose and evaluate their own model H2GCN against baselines; the paper states that all methods including H2GCN were tuned per benchmark 'To avoid bias' (App. F.2). Numbers in the body such as ablation gains (up to 40% on synthetic graphs, up to 27% on real heterophily graphs, low- vs high-degree gap 13%/10% vs <3%) are not recorded as results; tables (Table 1, Table 4 ranks, Table 5 accuracies) and Figures 2-3 are not recorded. Datasets: Texas, Wisconsin, Cornell (WebKB), Squirrel, Chameleon, Actor, Cora Full, Citeseer, Pubmed, Cora; heterophily benchmarks defined as h <= 0.3, homophily as h >= 0.7."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
