import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_diff_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2105.05233",
     "title": "Diffusion Models Beat GANs on Image Synthesis",
     "authors": ["Prafulla Dhariwal", "Alex Nichol"],
     "year": 2021, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/2105.05233"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["supervised", "unsupervised"],
     "proposes": ["ADM: an improved UNet architecture for diffusion models found by ablations (more attention heads, multi-resolution attention, BigGAN up/downsampling residual blocks, adaptive group normalization)",
                  "Classifier guidance: shifting the mean of each reverse step (or, for DDIM, the epsilon prediction) by the gradient of a classifier trained on noisy images, with a gradient scale s that trades diversity for fidelity"],
     "claims": [
         ("Overview: the authors state that a single hyperparameter, the scale of the classifier gradients, can be tuned to trade off diversity for fidelity, and that this scale can be increased by an order of magnitude without obtaining adversarial examples.",
          "Introduction",
          "We ﬁnd that a single hyperparameter, the scale of the classiﬁer gradients, can be tuned to trade off diversity for ﬁdelity, and we can increase this gradient scale factor by an order of magnitude without obtaining adversarial examples [61]."),
         ("Approximation in the derivation (following Sohl-Dickstein et al.): the classifier-conditioned reverse transition is approximated by a Gaussian whose mean is shifted by Sigma times the classifier gradient, assuming log p(y|x_t) has low curvature compared to Sigma^-1; the authors call this assumption reasonable in the limit of infinite diffusion steps. For deterministic DDIM sampling this derivation does not apply, and a score-based conditioning trick adapted from Song et al. is used instead.",
          "Classifier Guidance (Conditional Reverse Noising Process)",
          "This assumption is reasonable in the limit of inﬁnite diffusion steps, where ||Σ|| →0."),
         ("Extra model and why the scale exceeds 1: the classifier (the UNet downsampling trunk with an attention pool) is trained on the same noising distribution as the diffusion model; with an unconditional ImageNet model and scale 1 the classifier gave about 50% probability to the desired classes but samples did not match the classes on visual inspection, and scaling up the gradients remedied this.",
          "Section 4.3",
          "When using a scale of 1, we observed that the classiﬁer assigned reasonable probabilities (around 50%) to the desired classes for the ﬁnal samples, but these samples did not match the intended classes upon visual inspection."),
         ("Interpretation of the scale: s times the classifier gradient equals the gradient of a renormalized distribution proportional to p(y|x)^s, which is sharper than p(y|x) when s > 1; the authors say a larger scale focuses more on the classifier's modes, which is potentially desirable for higher-fidelity but less diverse samples.",
          "Section 4.3",
          "In other words, using a larger gradient scale focuses more on the modes of the classiﬁer, which is potentially desirable for producing higher ﬁdelity (but less diverse) samples."),
         ("Diversity-fidelity trade-off: for a class-conditional ImageNet 128x128 model (Figure 4), raising the gradient scale beyond 1.0 smoothly trades recall (diversity) for higher precision and IS (fidelity); FID and sFID, which depend on both, are best at an intermediate scale. The trade-off is shown in figures; no values are recorded here.",
          "Section 4.3",
          "We see that scaling the gradients beyond 1.0 smoothly trades off recall (a measure of diversity) for higher precision and IS (measures of ﬁdelity)."),
         ("Compared with BigGAN-deep's truncation trick on ImageNet 128x128 (Figure 5), classifier guidance is reported as strictly better when trading FID for IS, but on the precision/recall trade-off it is only better up to a certain precision threshold, beyond which it cannot achieve better precision.",
          "Section 4.3",
          "Less clear cut is the precision/recall trade-off, which shows that classiﬁer guidance is only a better choice up until a certain precision threshold, after which point it cannot achieve better precision."),
         ("Evaluation protocol: FID is the default metric (Precision or IS for fidelity, Recall for diversity); metrics for other methods are recomputed from public samples or models whenever possible, using the entire training set as the reference batch and the same codebase for all models. Table 5 marks some baseline values as taken from previous papers because public models or samples were lacking, and the architecture ablation curves in Figure 2 use FID over 10k instead of 50k samples.",
          "Sample Quality Metrics",
          "To ensure consistent comparisons, we use the entire training set as the reference batch [23, 5], and evaluate metrics for all models using the same codebase."),
         ("Guidance-scale selection: the 'optimal' classifier scales were chosen by sweeping a small grid per resolution and sampler (e.g. [0.5, 1, 2] for ImageNet 128 and 256 with the 250-step sampler). The text does not state which metric or which data were used to define 'optimal' or that a held-out set was used (searched for swept, optimal, select).",
          "Appendix I (Hyperparameters)",
          "When choosing optimal classiﬁer scales for our sampler, we swept over [0.5, 1, 2] for ImageNet 128×128 and ImageNet 256×256, and [1, 2, 3, 3.5, 4, 4.5, 5] for ImageNet 512×512."),
         ("Compute accounting: training compute is compared in V100-days with StyleGAN2 and BigGAN-deep; BigGAN-deep's TPU-v3 estimates were converted at 2 TPU-v3 days = 1 V100 day and StyleGAN2's from reported throughput. The authors note that classifier training is relatively lightweight compared with training the generative model.",
          "Appendix A.3",
          "We note that our classiﬁer training is relatively lightweight compared to training the generative model."),
         ("Stated limitations: diffusion models remain slower than GANs at sampling time because of multiple denoising steps, and classifier guidance is limited to labeled datasets, with no effective strategy provided for trading off diversity for fidelity on unlabeled data.",
          "Limitations and Future Work",
          "Our proposed classiﬁer guidance technique is currently limited to labeled datasets, and we have provided no effective strategy for trading off diversity for ﬁdelity on unlabeled datasets."),
     ],
     "notes": "Affiliation: OpenAI. No venue is stated in the PDF (arXiv v4; the v4 comment says compute requirements were added, which is Appendix A). The ADM baseline builds on the authors' own earlier improved DDPM (Nichol and Dhariwal [43]), which is also a comparison row in Table 5. Results tables (Tables 1-10) not recorded; the FID numbers in the abstract are not recorded as claims."},

    {"id": "arxiv-2207.12598",
     "title": "Classifier-Free Diffusion Guidance",
     "authors": ["Jonathan Ho", "Tim Salimans"],
     "year": 2022, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2207.12598"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["supervised"],
     "proposes": ["Classifier-free guidance: jointly training a conditional and an unconditional diffusion model in one network by dropping the conditioning with probability p_uncond, and sampling with the score combination (1 + w) eps(z, c) - w eps(z)"],
     "claims": [
         ("Motivation: classifier guidance requires training an extra classifier on noisy data (so a pre-trained classifier generally cannot be plugged in), and because it mixes in classifier gradients it can be interpreted as a gradient-based adversarial attack, raising the question whether its gains on classifier-based metrics (FID, IS) are partly adversarial.",
          "Introduction",
          "Classiﬁer guidance complicates the diffusion model training pipeline because it requires training an extra classiﬁer, and this classiﬁer must be trained on noisy data so it is generally not possible to plug in a pre-trained classiﬁer."),
         ("Method and cost at training time: a single network parameterizes both models, with a null token as the class input for the unconditional model, trained jointly by randomly setting the conditioning to null with probability p_uncond; joint training (rather than separate models) is chosen because it is simple and does not increase the total number of parameters.",
          "Classifier-free guidance",
          "(It would certainly be possible to train separate models instead of jointly training them together, but we choose joint training because it is extremely simple to implement, does not complicate the training pipeline, and does not increase the total number of parameters.)"),
         ("Caveat on the implicit-classifier interpretation: the guided score is inspired by the gradient of an implicit classifier p(z|c)/p(z), but the authors note that with a misspecified model, classifiers derived by Bayes' rule can be inconsistent (citing Grünwald & Langford) and all guarantees on their performance are lost; the effectiveness is therefore shown empirically.",
          "Classifier-free guidance",
          "In cases such as ours, where we expect the model to be misspeciﬁed, classiﬁers derived by Bayes’ rule can be inconsistent (Gr¨unwald & Langford, 2007) and we lose all guarantees on their performance."),
         ("Experimental setup: class-conditional ImageNet at 64x64 and 128x128, framed as a proof of concept rather than pushing to state of the art; architectures and hyperparameters are those of Dhariwal & Nichol's guided diffusion models (apart from continuous-time training), which the authors note were tuned for classifier guidance and may be suboptimal for classifier-free guidance.",
          "Experiments",
          "those hyperparameter settings were tuned for classiﬁer guidance and hence may be suboptimal for classiﬁer-free guidance."),
         ("Evaluation protocol: guidance strength w is swept over {0, 0.1, ..., 4} and FID and IS are computed with 50000 samples for each value, following Heusel et al. and Salimans et al. No statement of which real-image set provides the FID reference statistics was found in the text (searched for reference, training set, validation, statistics).",
          "Varying the classifier-free guidance strength",
          "calculate FID and Inception Scores with 50000 samples for each value following the procedures of Heusel et al. (2017) and Salimans et al. (2016)"),
         ("Quality-diversity trade-off: the best FID is obtained with a small amount of guidance and the best IS with strong guidance, with a trade-off between the two in between; samples show decreasing variety and increasing individual fidelity as guidance grows. The 'best' w is read off the same sweep that is reported; no separate selection set is described.",
          "Varying the classifier-free guidance strength",
          "We obtain the best FID results with a small amount of guidance (w = 0.1 or w = 0.3, depending on the dataset) and the best IS result with strong guidance (w ≥4)."),
         ("Training hyperparameter p_uncond (64x64 ImageNet, 400k steps each): p_uncond = 0.5 was consistently worse than 0.1 or 0.2 across the IS/FID frontier, while 0.1 and 0.2 performed about equally; the authors conclude only a relatively small portion of model capacity needs to go to unconditional generation.",
          "Varying the unconditional training probability",
          "We ﬁnd puncond = 0.5 consistently performs worse than puncond ∈{0.1, 0.2} across the entire IS/FID frontier; puncond ∈{0.1, 0.2} perform about equally as well as each other."),
         ("Sampling cost: each sampling step evaluates the denoising model twice (conditional and unconditional), so with the same architecture as ADM-G the speed-matched comparison is the T = 128 setting, which underperforms ADM-G in FID. In the Discussion the authors add that classifier-guided sampling may be faster since classifiers can be smaller than generative models.",
          "Varying the number of sampling steps",
          "Because we used the same model architecture as ADM-G, the fair comparison in terms of sampling speed would be our T = 128 setting, which underperforms compared to ADM-G in terms of FID score."),
         ("Stated concern about reduced diversity: any guidance method that raises fidelity at the expense of diversity faces the question of whether decreased diversity is acceptable; the authors say there may be negative impacts in deployed models where parts of the data are underrepresented.",
          "Discussion",
          "There may be negative impacts in deployed models, since sample diversity is important to maintain in applications where certain parts of the data are underrepresented in the context of the rest of the data."),
     ],
     "notes": "Affiliation: Google Research, Brain team. No venue recorded: the PDF and the arXiv comment say a short version appeared in the NeurIPS 2021 Workshop on Deep Generative Models and Downstream Applications; this arXiv v1 is the full paper. Conflict of interest: both authors are co-authors of CDM (Ho et al., 2021), which is a comparison row in Tables 1-2. The text says FID is 'monotonically decreasing' with w between the best-FID and best-IS settings, whereas Tables 1-2 list FID values that grow with w beyond the best setting; that sentence is not recorded as a claim. Results tables (Tables 1-2) not recorded."},

    {"id": "arxiv-2112.10752",
     "title": "High-Resolution Image Synthesis with Latent Diffusion Models",
     "authors": ["Robin Rombach", "Andreas Blattmann", "Dominik Lorenz", "Patrick Esser", "Björn Ommer"],
     "year": 2021, "venue": "CVPR 2022", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2112.10752"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models", "autoencoders"], "par": ["unsupervised", "supervised"],
     "proposes": ["Latent diffusion models (LDMs): training a diffusion model in the latent space of a separately pre-trained, mildly compressing autoencoder (perceptual + patch-adversarial loss, KL- or VQ-regularized latent) with downsampling factor f",
                  "Cross-attention conditioning of the denoising UNet on a domain-specific encoder of the conditioning input (e.g. a transformer for text)"],
     "claims": [
         ("Motivation, citing Dhariwal & Nichol [15]: the most powerful pixel-space diffusion models take hundreds of GPU days to train (150-1000 V100 days in [15]) and inference is also expensive because of repeated network evaluations.",
          "Introduction",
          "As an example, training the most powerful DMs often takes hundreds of GPU days (e.g. 150 - 1000 V100 days in [15]) and repeated evaluations on a noisy version of the input space render also inference expensive,"),
         ("First-stage autoencoder: to avoid arbitrarily high-variance latents, two regularizations are studied, a slight KL penalty toward a standard normal (VAE-like) and a vector-quantization layer within the decoder; because the diffusion model works on the 2D latent, relatively mild compression suffices.",
          "Section 3.1",
          "The ﬁrst variant, KL-reg., imposes a slight KL-penalty towards a standard normal on the learned latent, similar to a VAE [46, 69], whereas VQ-reg. uses a vector quantization layer [96] within the decoder."),
         ("Regularization vs sample quality: LDMs trained in VQ-regularized latent spaces sometimes achieve better sample quality even though VQ-regularized first stages reconstruct slightly worse than their continuous (KL) counterparts.",
          "Section 4",
          "Interestingly, we ﬁnd that LDMs trained in VQ-regularized latent spaces sometimes achieve better sample quality, even though the reconstruction capabilities of VQ-regularized ﬁrst stage models slightly fall behind those of their continuous counterparts, cf. Tab. 8."),
         ("Compression trade-off (downsampling factor f in {1,...,32}, single A100, same steps and parameter count, class-conditional ImageNet for 2M steps): small f (1, 2) trains slowly and large f stagnates in fidelity; the authors attribute this to leaving most perceptual compression to the diffusion model versus information loss from too strong first-stage compression, and conclude LDM-4 and -8 offer the best conditions.",
          "Section 4.1",
          "we attribute this to i) leaving most of perceptual compression to the diffusion model and ii) too strong ﬁrst stage compression resulting in information loss and thus limiting the achievable quality."),
         ("Protocol of the efficiency analysis: the sample-quality curves in Figures 6, 7 and 17 are computed on 5k samples for efficiency, so they may differ from the 50k-sample results in Tables 1 and 10; learning rates were maximized per model subject to stable training and therefore vary slightly between runs.",
          "Appendix E.3.5",
          "For efﬁciency reasons we compute the sample quality metrics plotted in Fig. 6, 17 and 7 based on 5k samples."),
         ("FID protocol for unconditional and class-conditional results: statistics from 50k model samples and the entire training set, computed with torch-fidelity and cross-checked with Dhariwal and Nichol's script; scores mainly coincided with slight differences on ImageNet and LSUN-Bedrooms, and the authors emphasize the importance of a unified procedure for sample quality assessment. Text-to-image FID/IS use 30000 MS-COCO validation samples, and some Table 2 baseline numbers are taken from other papers.",
          "Appendix E.3.1",
          "We follow common practice and estimate the statistics for calculating the FID-, Precision- and Recall-scores [29,50] shown in Tab. 1 and 10 based on 50k samples from our models and the entire training set of each of the shown datasets."),
         ("Guidance in latent space: classifier-free guidance (cited as [32]) greatly boosts text-to-image sample quality on MS-COCO; reported guided settings use scales 1.5 (text-to-image, ImageNet LDM-4-G) and 1.25 (ImageNet, Table 10). No description of how the guidance scale was chosen was found in the text (searched for sweep, select, choose, tune).",
          "Section 4.3.1",
          "We note that applying classiﬁer-free diffusion guidance [32] greatly boosts sample quality, such that the guided LDM-KL-8-G is on par with the recent state-of-the-art AR [26] and diffusion models [59] for text-to-image synthesis, while substantially reducing parameter count."),
         ("Compute comparison: competing methods' compute (V100-days) is taken from [15] unless stated otherwise, and the authors' single-A100 training days are converted to V100-days by assuming a 2.2x A100-over-V100 speedup.",
          "Appendix F (Computational Requirements)",
          "we convert the A100 days to V100 days by assuming a ×2.2 speedup of A100 vs V100"),
         ("Stated limitations: sequential sampling is still slower than GANs, and the autoencoder's reconstruction capability can become a bottleneck for tasks needing fine-grained pixel accuracy even though the f = 4 quality loss is very small; the authors assume their super-resolution models are already somewhat limited in this respect.",
          "Section 5",
          "Moreover, the use of LDMs can be questionable when high precision is required: although the loss of image quality is very small in our f = 4 autoencoding models (see Fig. 1), their reconstruction capability can become a bottleneck for tasks that require ﬁne-grained accuracy in pixel space."),
     ],
     "notes": "Affiliations: Ludwig Maximilian University of Munich & IWR Heidelberg University; Runway ML. Venue from the arXiv comment ('CVPR 2022'); the PDF itself does not state it. Conflict of interest: the first-stage autoencoder is based on VQGAN [23] (Esser, Rombach, Ommer), by three of the authors, and VQGAN/ImageBART variants appear as baselines. Funding: German Federal Ministry for Economic Affairs and Energy, DFG. Results tables not recorded; main text and Appendix E/F only were read for the claims."},

    {"id": "arxiv-2206.00364",
     "title": "Elucidating the Design Space of Diffusion-Based Generative Models",
     "authors": ["Tero Karras", "Miika Aittala", "Timo Aila", "Samuli Laine"],
     "year": 2022, "venue": "NeurIPS 2022", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2206.00364"},
     "tasks": ["generative-modeling"],
     "fam": ["diffusion-models"], "par": ["unsupervised", "supervised"],
     "proposes": ["A common framework that separates the design choices of diffusion models (noise schedule sigma(t), scaling s(t), time steps, ODE solver, preconditioning c_skip/c_out/c_in/c_noise, training noise distribution and loss weighting)",
                  "EDM choices: Heun 2nd-order deterministic sampler with rho-parameterized time steps and sigma(t) = t, s(t) = 1; a stochastic sampler with tunable 'churn'; preconditioning derived from unit-variance requirements; log-normal training noise distribution with matching loss weights; non-leaky augmentation"],
     "claims": [
         ("Sampler as a separable component: the authors hypothesize that sampling choices are largely independent of architecture and training, and test this by plugging different samplers into three pre-trained models (DDPM++ VP and NCSN++ VE on unconditional CIFAR-10, ADM on class-conditional ImageNet-64); their reimplementations in the unified framework gave similar but consistently better results than the original samplers.",
          "Section 3",
          "Our hypothesis is that the choices related to the sampling process are largely independent of the other components, such as network architecture and training details."),
         ("Cost-quality accounting: quality is plotted against NFE (number of D_theta evaluations per image), and each curve is summarized by the lowest NFE whose FID is within 3% of the lowest observed FID. With Heun's method (one extra evaluation per step, O(h^3) local error), rho = 7 time steps and sigma(t) = t, s(t) = 1, the NFE needed for high-quality results drops by large factors relative to the original samplers.",
          "Section 3",
          "Together, they reduce the NFE needed to reach high-quality results by a large factor: 7.3× for VP, 300× for VE, and 3.2× for DDIM, corresponding to the highlighted NFE values in Figure 2."),
         ("Stochasticity has drawbacks: excessive Langevin-like noise addition and removal causes gradual loss of detail and a drift toward oversaturated colors; the authors suspect practical denoisers induce a slightly non-conservative vector field, and counter it heuristically (stochasticity only in a noise-level range, S_noise slightly above 1).",
          "Section 4",
          "We suspect that practical denoisers induce a slightly non-conservative vector ﬁeld in Eq. 3, violating the premises of Langevin diffusion and causing these detrimental effects."),
         ("Evaluation concern stated by the authors: the stochastic-sampler parameters {S_churn, S_tmin, S_tmax, S_noise} had to be found case by case with grid search, which raises the concern that using stochastic sampling as the main evaluation may inadvertently influence architecture and training design choices.",
          "Section 4",
          "This raises a general concern that using stochastic sampling as the primary means of evaluating model improvements may inadvertently end up inﬂuencing the design choices related to model architecture and training."),
         ("Preconditioning: D_theta = c_skip x + c_out F_theta(c_in x; c_noise), with c_in and c_out chosen for unit-variance inputs and targets, c_skip to amplify network errors as little as possible, and c_noise chosen empirically. In the ablation (Table 2, deterministic sampler) the preconditioning alone left results largely unchanged except VE at 64x64; its stated main benefit is more robust training, after which the log-normal p_train and lambda = 1/c_out^2 gave a dramatic FID improvement.",
          "Section 5",
          "Instead of improving FID per se, the main beneﬁt of our preconditioning is that it makes the training more robust, enabling us to turn our focus on redesigning the loss function without adverse effects."),
         ("Stochastic sampling revisited: with the authors' training setup on CIFAR-10 the best results came from deterministic sampling and any stochasticity was detrimental, whereas for class-conditional ImageNet-64 stochastic sampling was clearly better than deterministic, which the authors say suggests more diverse datasets continue to benefit from it.",
          "Section 5",
          "When using our training setup in CIFAR-10 (Figure 5b), the best results were obtained with deterministic sampling, and any amount of stochastic sampling was detrimental."),
         ("FID protocol: FID between 50,000 generated images and all available real images without x-flip augmentation, using the StyleGAN3 Inception-v3 model (verified to match Dhariwal and Nichol and Karras et al.); to reduce random variation of typically about ±2%, FID is computed three times per experiment and the minimum is reported.",
          "Appendix F.1",
          "To reduce the impact of random variation, typically in the order of ±2%, we compute FID three times in each experiment and report the minimum."),
         ("Checkpoint selection: models were trained for 200 Mimg (about 400,000 iterations at batch 512), snapshots saved every 2.5 Mimg, and results reported for the snapshot with the lowest FID under the deterministic sampler at NFE = 35 or 79 depending on resolution; i.e. the reported snapshot is selected by the evaluation metric itself.",
          "Appendix F.3",
          "We saved a snapshot of the model every 2.5 million images and reported results for the snapshot that achieved the lowest FID according to our deterministic sampler with NFE = 35 or NFE = 79, depending on the resolution."),
         ("Compute and scope: the project consumed about 250 MWh on an in-house cluster of NVIDIA V100s; the authors also note that many parameter values may need re-adjustment for higher-resolution datasets.",
          "Conclusions (Societal impact)",
          "our project consumed ∼250MWh on an in-house cluster of NVIDIA V100s."),
     ],
     "notes": "Affiliation: NVIDIA (all authors). Venue from the PDF footer ('36th Conference on Neural Information Processing Systems (NeurIPS 2022)') and the arXiv comment. Conflict of interest: the augmentation pipeline is borrowed from the authors' own GAN work [25] (Karras et al., ADA) and the FID implementation uses the Inception model shipped with their StyleGAN3 [26]; StyleGAN-XL is cited as a comparison point. The paper notes that many of its parameter values may need to be re-adjusted for higher-resolution datasets. Results tables (Tables 2, appendix) not recorded; main text and Appendices E.2/F were read for the claims."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
