import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_bo_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1206.2944",
     "title": "Practical Bayesian Optimization of Machine Learning Algorithms",
     "authors": ["Jasper Snoek", "Hugo Larochelle", "Ryan P. Adams"],
     "year": 2012, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1206.2944"},
     "tasks": ["hyperparameter-optimization", "image-classification"],
     "fam": ["bayesian-optimization", "gaussian-processes"],
     "proposes": ["GP-based Bayesian optimization of ML hyperparameters with an ARD Matern 5/2 kernel and a fully Bayesian treatment of the GP hyperparameters: the expected improvement is integrated over GP hyperparameter samples drawn by slice sampling ('GP EI MCMC')",
                  "Expected improvement per second: a cost-aware acquisition that models the log duration of an evaluation with a separate GP (assumed independent of the objective)",
                  "Monte Carlo acquisition for parallel/asynchronous BO: the acquisition is averaged over sampled outcomes ('fantasies') of pending evaluations"],
     "claims": [
         ("Choice of acquisition: the paper focuses on expected improvement because it has been shown to be better-behaved than probability of improvement and, unlike GP-UCB, needs no tuning parameter of its own; the authors add that the regret formalization is more appropriate for many settings.",
          "Section 2.2",
          "In this work we will focus on the expected improvement criterion, as it has been shown to be better-behaved than probability of improvement, but unlike the method of GP upper conﬁdence bounds (GP-UCB), it does not require its own tuning parameter."),
         ("Kernel: the ARD squared exponential kernel, often a default for GP regression, gives sample functions that are unrealistically smooth for practical optimization problems; the authors instead propose the ARD Matern 5/2 kernel, whose samples are twice differentiable.",
          "Section 3.1",
          "However, sample functions with this covariance function are unrealistically smooth for practical optimization problems."),
         ("GP hyperparameters: typically D + 3 of them (D length scales, amplitude, observation noise, constant mean). Instead of the commonly advocated point estimate by maximizing the marginal likelihood, the acquisition is integrated over the GP hyperparameter posterior, estimated by Monte Carlo with slice sampling. The authors argue this is sensible because both optimization and MCMC are dominated by the cubic cost of solving an N-dimensional linear system and function evaluations are assumed to be much more expensive.",
          "Section 3.1",
          "As both optimization and Markov chain Monte Carlo are computationally dominated by the cubic cost of solving an N-dimensional linear system"),
         ("Cost-aware acquisition: because wallclock time matters more than the number of evaluations, the authors propose expected improvement per second; the unknown duration function is modelled as ln c(x) with a GP, and it is assumed independent of the objective, although the coupling may be captured with multi-task GP variants.",
          "Section 3.2",
          "In this work, we assume that these functions are independent of each other, although their coupling may be usefully captured using GP variants of multi-task learning (e.g., Teh et al. (2005); Bonilla et al. (2008))."),
         ("Parallel BO: roll-outs of the acquisition policy are generally intractable, so the next point is chosen while other evaluations are pending by computing Monte Carlo estimates of the acquisition over possible outcomes of the pending evaluations (a J-dimensional Gaussian under the GP).",
          "Section 3.3",
          "Instead we propose a sequential strategy that takes advantage of the tractable inference properties of the Gaussian process to compute Monte Carlo estimates of the acquisiton function under diﬀerent possible results from pending function evaluations."),
         ("Evaluation protocol for online LDA (3 parameters; the original authors' 6 x 6 x 8 grid of 288 configurations, each evaluation taking 5 to 10 hours): the BO strategies were restricted to the exact grid points, each optimization was repeated 100 times with two random initial experiments, and mean and standard error are reported against evaluations and days. The authors state that integrating over GP hyperparameters was superior to a point estimate, and that parallelized GP EI MCMC found the best parameters in significantly less time though single GP EI MCMC was most efficient per evaluation.",
          "Section 4.2",
          "That is, the algorithms were restricted to only the exact parameter settings as evaluated by the grid search."),
         ("Kernel comparison on structured SVM (M3E) motif finding, 100 repetitions per covariance: the authors state that the choice of covariance significantly affects performance, that length-scale estimation is critical, and that the infinite differentiability imposed by the squared exponential is too restrictive for this problem.",
          "Section 4.3",
          "The assumption of the inﬁnite diﬀerentiability of the underlying function as imposed by the commonly used squared exponential is too restrictive for this problem."),
         ("Cost-aware vs per-evaluation efficiency on M3E (grid of 1,400 combinations, each evaluated over 5 random 50-50 train/test splits, BO constrained to grid points, 100 repetitions): GP EI MCMC is better per function evaluation, while GP EI per Second finds better parameters faster in wallclock time because it learns to use a less strict convergence tolerance early on.",
          "Section 4.3",
          "In this case, GP EI MCMC is superior to GP EI per Second in terms of function evaluations but GP EI per Second ﬁnds better parameters faster than GP EI MCMC as it learns to use a less strict convergence tolerance early on while exploring the other parameters."),
         ("CIFAR-10 protocol: nine hyperparameters of a three-layer convolutional network (Krizhevsky's code; the expert-tuned setting gives 18% test error) are optimized on a withheld validation set; mean validation error and standard error over five randomly initialized runs are reported, and the best hyperparameters found by GP EI MCMC give 14.98% test error, which the authors describe as over 3% better than the expert and the state of the art (without data augmentation).",
          "Section 4.4",
          "We optimize over the nine parameters for each strategy on a withheld validation set and report the mean validation error and standard error over ﬁve separate randomly initialized runs."),
         ("Notation in Section 2.2 (minimization): x_best = argmin_{x_n} f(x_n), Phi is the standard normal CDF and phi the standard normal density; acquisition functions depend on the GP only through the predictive mean mu(x) and predictive variance sigma^2(x).", "Section 2.2", "In the proceeding, we will denote the best current value as xbest = argminxn f(xn), Φ(·) will denote the cumulative distribution function of the standard normal, and φ(·) will denote the standard normal density function."),
         ("Probability of improvement (Eq. 1): a_PI(x) = Phi(gamma(x)) with gamma(x) = (f(x_best) - mu(x)) / sigma(x).", "Section 2.2", "One intuitive strategy is to maximize the probability of improving over the best current value (Kushner, 1964)."),
         ("Expected improvement in closed form under the GP (Eq. 2): a_EI(x) = sigma(x) (gamma(x) Phi(gamma(x)) + N(gamma(x); 0, 1)).", "Section 2.2", "This also has closed form under the Gaussian process:"),
         ("GP lower confidence bound (Eq. 3; upper when maximizing): a_LCB(x) = mu(x) - kappa sigma(x), with a tunable kappa to balance exploitation against exploration.", "Section 2.2", "with a tunable κ to balance exploitation against exploration."),
     ],
     "notes": "Affiliations: University of Toronto, Universite de Sherbrooke, Harvard University. No venue is stated in the PDF text (arXiv v2, no journal_ref given), so none is recorded. All experiments ran on identical Amazon EC2 machines (footnote; the work was supported by an Amazon Web Services grant). Section 4.1 compares with TPA (Bergstra et al. 2011, hyperopt public code) on Branin-Hoo (100 runs) and MNIST logistic regression with 4 hyperparameters (10 runs); the text states that on Branin-Hoo integrating over GP hyperparameters beats a point estimate and GP EI significantly outperforms TPA. Although Section 2.2 promises a direct comparison with GP-UCB in Section 4.1, GP-UCB appears only as a curve in Fig. 3a and its result is not discussed in the text (figure values not recorded). Fig. 4c compares grid-constrained vs off-grid BO on LDA (figure only). Code release is stated as future ('will be made publicly available')."},

    {"id": "arxiv-1012.2599",
     "title": "A Tutorial on Bayesian Optimization of Expensive Cost Functions, with Application to Active User Modeling and Hierarchical Reinforcement Learning",
     "authors": ["Eric Brochu", "Vlad M. Cora", "Nando de Freitas"],
     "year": 2010, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1012.2599"},
     "tasks": ["black-box-optimization"],
     "fam": ["bayesian-optimization", "gaussian-processes"],
     "proposes": ["Tutorial: Bayesian optimization with GP priors (covariance functions, PI / EI / GP-UCB acquisition functions, Gaussian noise), its history (kriging, EGO, experimental design, active learning), and two extensions with experiments: preference galleries from pairwise discrete-choice data and hierarchical reinforcement learning"],
     "claims": [
         ("The acquisition function automatically trades off exploration (where the objective is very uncertain) and exploitation (where it is expected to be high); the technique aims to minimize the number of objective evaluations and, the authors say, is likely to do well even with multiple local maxima.",
          "Introduction",
          "This optimization technique has the nice property that it aims to minimize the number of objective function evaluations."),
         ("Problem assumptions: the objective is a black box, assumed Lipschitz-continuous with a typically unknown constant, over a bounded axis-aligned hyperrectangle. Citing Betro (1991), guaranteeing an epsilon-optimal observation in the worst case requires (C/2 epsilon)^d samples, which the authors call an incredibly expensive premium against unlikely scenarios; BO instead relaxes worst-case guarantees toward an average-case approach.",
          "Section 2 (The Bayesian Optimization Approach)",
          "This can be an incredibly expensive premium to pay for insurance against unlikely scenarios."),
         ("The choice of GP covariance function is crucial because it determines the smoothness of samples; the plain squared exponential is called a little naive since all features affect the covariance equally, so length-scale (including ARD) hyperparameters are added, and the Matern kernel adds a smoothness parameter.",
          "Section 2.2",
          "The choice of covariance function for the Gaussian Process is crucial, as it determines the smoothness properties of samples drawn from it."),
         ("GP hyperparameters are typically learned by seeding with a few random samples and maximizing the log-likelihood of the evidence (citing several works), often aided by an informative hyperprior such as a log-normal prior; more efficient ways of learning them are described as an active subfield of research.",
          "Section 2.2",
          "Typically, the hyperparameter values are learned by “seeding” with a few random samples and maximizing the log-likelihood of the evidence given θ"),
         ("Exploration parameter of EI: citing Lizotte (2008), setting xi = 0.01 (scaled by the signal variance if necessary) works well in almost all cases, while a cooling schedule for xi (explore early, exploit later) does not work well empirically, contrary to intuition (a schedule might slightly help short runs of PI).",
          "Section 2.3",
          "Lizotte’s experiments suggest that setting ξ = 0.01 (scaled by the signal variance if necessary) works well in almost all cases"),
         ("GP-UCB as summarized by the tutorial: for the confidence-bound criteria kappa is otherwise left to the user; with the schedule of Srinivas et al. (2010) the method is no-regret with high probability. A footnote cautions that these bounds hold for reasonably smooth kernels and their exact form depends on the kernel, referring readers to the original paper.",
          "Section 2.3 (footnote 2)",
          "These bounds hold for reasonably smooth kernel functions, where the exact formulation of the bounds depends upon the form of kernel used."),
         ("Noise: additive Gaussian noise is handled by adding sigma_noise^2 I to the kernel matrix; for PI and EI the incumbent is redefined as the sampled point with the highest posterior mean rather than the best noisy observation (resampling incumbents, 'intensification', is also mentioned).",
          "Section 2.4",
          "This avoids the problem of attempting to maximize probability or expected improvement over an unreliable sample."),
         ("Stated shortcomings: the design of the prior is absolutely critical; GPs are not always the best or easiest solution and kernels need great care; with little known about an expensive objective, either strong unverified assumptions or a weak prior must be used; and it is often unclear how to set the exploration-exploitation trade-off.",
          "Section 5",
          "A particular issue is that the design of the prior is absolutely critical to eﬃcient Bayesian optimization."),
         ("Further shortcomings: these problems are exacerbated as dimensionality grows (more samples to cover the space, more parameters and hyperparameters to tune), which may require automatic feature selection or optimizing each dimension independently; and the acquisition is currently myopic and allows only one sample per iteration, whereas looking ahead to a horizon or selecting batches would be valuable.",
          "Section 5",
          "In order to deal with this problem eﬀectively, it may be necessary to do automatic feature selection, or assume independence and optimize each dimension individually."),
     ],
     "notes": "Affiliation not extracted from the PDF text. No venue recorded: the arXiv record has no journal_ref, and Frazier (arXiv:1807.02811) cites it as UBC Technical Report TR-2009-023 (a technical report, not a venue). The acquisition function is maximized with DIRECT (Section 2.3). The two extensions (preference galleries with a probit/Thurstone-Mosteller GP model; hierarchical RL on a simulated driving task) are authored by the same group and evaluate their own methods; their results are figure-only and not recorded. The tutorial predates most BO-for-hyperparameter work and does not run hyperparameter-optimization experiments; the task tag is the closest registered one. No discussion of categorical/conditional search spaces or of the cubic GP cost was found (searched for categor, conditional, cubic, overhead, computational); it states only that in sequential decision making the number of query points is relatively small so GP predictions are easy to compute."},

    {"id": "arxiv-1807.02811",
     "title": "A Tutorial on Bayesian Optimization",
     "authors": ["Peter I. Frazier"],
     "year": 2018, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1807.02811"},
     "tasks": ["black-box-optimization"],
     "fam": ["bayesian-optimization", "gaussian-processes"],
     "proposes": ["Tutorial: GP regression, expected improvement, knowledge gradient, entropy search and predictive entropy search, and 'exotic' BO problems (noise, parallel evaluations, constraints, multi-fidelity / multi-information source, environmental conditions, multi-task, derivatives)",
                  "An argument that the KGCP acquisition of Scott et al. (2011) is the most natural generalization of expected improvement to noisy evaluations"],
     "claims": [
         ("Scope of BO: it is best suited to continuous domains of fewer than 20 dimensions and tolerates stochastic noise; the introduction adds that d <= 20 in most successful applications and that the feasible set is typically a hyper-rectangle or simplex.",
          "Abstract",
          "It is best-suited for optimization over continuous domains of less than 20 dimensions, and tolerates stochastic noise in function evaluations."),
         ("'Expensive to evaluate' means the number of evaluations is limited, typically to a few hundred, because each evaluation takes substantial time (typically hours) or has a monetary or opportunity cost; the objective is also treated as a derivative-free black box.",
          "Section 1 (Introduction)",
          "f is “expensive to evaluate” in the sense that the number of evaluations that may be performed is limited, typically to a few hundred."),
         ("Noise assumption: in almost all BO work, noise is assumed independent across evaluations and Gaussian with constant variance (the tutorial itself assumes noise-free observations until Section 5).",
          "Section 1 (Introduction)",
          "In almost all work on Bayesian optimization, noise is assumed independent across evaluations and Gaussian with constant variance."),
         ("GP hyperparameters (kernel and mean parameters) are typically chosen by maximum likelihood, by MAP with a prior on the hyperparameters (useful if MLE sometimes gives unreasonable values), or by a fully Bayesian approach that marginalizes them, approximated by MCMC samples such as slice sampling; MAP can be seen as an approximation to fully Bayesian inference.",
          "Section 3.2",
          "To choose the hyperparameters, three approaches are typically considered."),
         ("Expected improvement is the most commonly used acquisition, performs well and is easy to use; knowledge gradient, entropy search and predictive entropy search are most useful in exotic problems where EI's assumption that the benefit of sampling comes through improvement at the sampled point no longer holds.",
          "Section 4",
          "These alternate acquisition functions are most useful in exotic problems where an assumption made by expected improvement, that the primary beneﬁt of sampling occurs through an improvement at the point sampled, is no longer true."),
         ("Knowledge gradient values improvement of the maximum of the posterior mean over the whole domain; it gives a small benefit in the standard noise-free problem and, citing works that include the author's own, tends to significantly outperform EI when such effects are first-order (noise, multi-fidelity, derivatives, environmental conditions).",
          "Section 4.2",
          "When such phenomenon are ﬁrst-order, KG tends to signiﬁcantly outperform EI (Wu et al., 2017; Poloczek et al., 2017; Wu and Frazier, 2016; Toscano-Palmerin and Frazier, 2018)."),
         ("Noisy evaluations: noise variance is usually unknown and treated as a common hyperparameter. Direct use of EI is conceptually challenging because improvement is not easily defined, so heuristic substitutes are used; citing works co-authored by the author, KG can outperform EI substantially under substantial noise.",
          "Section 5",
          "Because of these approximations, KG can outperform EI substantially in problems with substantial noise (Wu and Frazier, 2016; Frazier et al., 2009)."),
         ("Multi-step lookahead: EI, KG, ES and PES are one-step optimal; exact multi-step optimal acquisition is extremely challenging (curse of dimensionality in dynamic programming), and approximate methods do not yet seem deployable broadly because their error and extra cost often overwhelm the benefit. In specific settings where multi-step optimal algorithms can be computed, existing one-step acquisitions perform almost as well.",
          "Section 4.4",
          "These methods do not yet seem to be in a state where they can be deployed broadly for practical problems, because the error and extra cost introduced in solving stochastic dynamic programming problems approximately often overwhelms the beneﬁt that considering multiple steps provides."),
         ("Open problems: no finite-time bounds explain the near-optimal empirical performance of the acquisitions used in practice and little is known about convergence rates; GPs are used in most BO work but other models may suit some problems better; and BO that works well in high dimensions is of great interest, possibly via structure-exploiting models or new acquisition functions.",
          "Section 7",
          "It is also possible that new acquisition functions may provide substantial value in high dimensional problems."),
         ("GP prior (Eq. 2): the values f(x_1:k) at a finite set of points are jointly Normal with mean vector mu_0(x_1:k) from a mean function and covariance matrix Sigma_0(x_1:k, x_1:k) from a kernel; the kernel is chosen so that closer points have larger positive correlation, and it must give a positive semi-definite covariance matrix.", "Section 3", "The kernel is chosen so that points xi, xj that are closer in the input space have a large positive correlation, encoding the belief that they should have more similar function values than points that are far apart."),
         ("GP posterior mean (Eq. 3): given noise-free observations f(x_1:n), f(x) is Normal with mean mu_n(x) = Sigma_0(x, x_1:n) Sigma_0(x_1:n, x_1:n)^-1 (f(x_1:n) - mu_0(x_1:n)) + mu_0(x), which the tutorial describes as a weighted average between the prior mu_0(x) and an estimate based on the data, with a weight that depends on the kernel.", "Section 3", "The posterior mean µn(x) is a weighted average between the prior µ0(x) and an estimate based on the data f(x1:n), with a weight that depends on the kernel."),
         ("GP posterior variance (Eq. 3): sigma_n^2(x) = Sigma_0(x, x) - Sigma_0(x, x_1:n) Sigma_0(x_1:n, x_1:n)^-1 Sigma_0(x_1:n, x), i.e. the prior variance less a term corresponding to the variance removed by observing f(x_1:n).", "Section 3", "is equal to the prior covariance Σ0(x, x) less a term that corresponds to the variance removed by observing f(x1:n)."),
         ("EI definition (Eq. 7, maximization, noise-free): with f*_n = max_{m<=n} f(x_m) the best value observed so far, the improvement from evaluating x is [f(x) - f*_n]^+ (positive part), and EI_n(x) = E_n[[f(x) - f*_n]^+], the expectation under the GP posterior given the n evaluations.", "Section 4.1", "What we can do, however, is to take the expected value of this improvement and choose x to maximize it."),
         ("EI closed form (Eq. 8, transcribed as printed in the PDF): EI_n(x) = [Delta_n(x)]^+ + sigma_n(x) phi(Delta_n(x)/sigma_n(x)) - |Delta_n(x)| Phi(Delta_n(x)/sigma_n(x)), with Delta_n(x) = mu_n(x) - f*_n; it is obtained by integration by parts (citing Jones et al. 1998 and Clark 1961), and the next point is x_{n+1} = argmax EI_n(x) (Eq. 9).", "Section 4.1", "The expected improvement can be evaluated in closed form using integration by parts, as described in Jones et al. (1998) or Clark (1961)."),
         ("EI trade-off: EI_n(x) is increasing in both Delta_n(x) and sigma_n(x), balancing high expected quality against high uncertainty (exploration vs. exploitation).", "Section 4.1", "EIn(x) is increasing in both ∆n(x) and σn(x)."),
         ("EI is smallest (0) at previously evaluated points, where the posterior standard deviation is 0 and the posterior mean is no larger than the best previously evaluated value.", "Section 4.1", "The smallest expected improvement is 0, at points where we have previously evaluated."),
     ],
     "notes": "Affiliation not extracted from the PDF text. No venue stated in the PDF (arXiv v1, no journal_ref given). Conflict of interest: the author co-authored the knowledge-gradient method and several of the works cited for KG's advantages (Frazier et al. 2009; Wu and Frazier 2016; Toscano-Palmerin and Frazier 2018; Wu et al. 2017; Poloczek et al. 2017 - all list Frazier as an author in the references), and Cornell MOE is listed among software; no competing-interest statement was found. Parallel EI (Section 5): the Constant Liar approximation and stochastic-gradient optimization of parallel EI (used for up to q = 128 parallel evaluations). The cross-validation folds case is described as an environmental-conditions problem. No discussion of categorical or conditional (tree-structured) search spaces was found (searched for categor, conditional, discrete; 'discrete' appears only for KG over a finite domain and discrete-event simulation). No statement on the cubic cost of GP inference was found (searched for cubic, O(n, overhead); it recommends Cholesky solves and a 1e-6 diagonal jitter for numerical stability)."},

    {"id": "arxiv-0912.3995",
     "title": "Gaussian Process Optimization in the Bandit Setting: No Regret and Experimental Design",
     "authors": ["Niranjan Srinivas", "Andreas Krause", "Sham M. Kakade", "Matthias Seeger"],
     "year": 2009, "venue": "ICML 2010", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/0912.3995"},
     "tasks": ["black-box-optimization"],
     "fam": ["bayesian-optimization", "gaussian-processes", "kernel-methods"],
     "proposes": ["Regret analysis of GP-UCB (x_t = argmax mu_{t-1}(x) + beta_t^{1/2} sigma_{t-1}(x)): cumulative-regret bounds of the form O*(sqrt(T beta_T gamma_T)) in terms of the maximum information gain gamma_T, for f sampled from a known GP (finite or compact convex domain) and for f with bounded RKHS norm",
                  "Bounds on the maximum information gain via submodularity and kernel operator spectra for linear, squared exponential and Matern kernels"],
     "claims": [
         ("Setting: optimizing an unknown, noisy, expensive function is cast as a multi-armed bandit where the payoff function is either sampled from a GP or has low RKHS norm; performance is measured by cumulative regret (sum of f(x*) - f(x_t)), and bounds on average regret translate into convergence rates.",
          "Abstract",
          "We formalize this task as a multi-armed bandit problem, where the payoﬀfunction is either sampled from a Gaussian process (GP) or has low RKHS norm."),
         ("Motivation for the UCB rule: picking the point of maximum posterior mean is too greedy too soon and tends to get stuck in shallow local optima, while the experimental-design rule (maximum variance) reduces uncertainty globally rather than where maxima might be; GP-UCB combines the mean with beta_t^{1/2} times the standard deviation.",
          "Section 3",
          "However, this rule is too greedy too soon and tends to get stuck in shallow local optima."),
         ("Theorem 1 (finite domain): if f is a sample from a zero-mean GP with known covariance k (k(x,x) <= 1), observed with i.i.d. Gaussian noise of variance sigma^2, and beta_t = 2 log(|D| t^2 pi^2 / 6 delta), then with probability at least 1 - delta the cumulative regret is at most sqrt(C1 T beta_T gamma_T) for all T, with C1 = 8 / log(1 + sigma^-2).",
          "Section 4",
          "This theorem shows that, with high probability over samples from the GP, the cumulative regret is bounded in terms of the maximum information gain, forging a novel connection between GP optimization and experimental design."),
         ("Theorem 2 (compact convex D in [0, r]^d) additionally assumes a high-probability bound on the derivatives of GP sample paths and uses a beta_t that grows with an extra 2d log term. This holds for stationary kernels that are four times differentiable, such as squared exponential and Matern with nu > 2, but is violated for the Ornstein-Uhlenbeck kernel, for which the authors conjecture a result of this form does not hold.",
          "Section 4",
          "The smoothness assumption on k(x, x′) disqualiﬁes GPs with highly erratic sample paths."),
         ("Theorem 3 (agnostic case): if f lies in the RKHS of k with squared norm at most B and the noise is a martingale difference sequence bounded by sigma, GP-UCB run with a GP(0, k) prior and Gaussian noise model (both misspecified) and beta_t = 2B + 300 gamma_t log^3(t/delta) still attains sublinear regret with high probability over the noise. It needs an upper bound on the RKHS norm (guess-and-doubling is suggested if unknown); GP samples have infinite RKHS norm almost surely, so neither Theorem 2 nor 3 encompasses the other.",
          "Section 4",
          "Note that we still run the same GP-UCB algorithm, whose prior and noise model are misspeciﬁed in this case."),
         ("Information gain bounds (Theorem 5, compact convex D, k(x,x) <= 1): gamma_T = O(d log T) for linear kernels, O((log T)^{d+1}) for the squared exponential, and a power law in T for Matern kernels with nu > 1; together with Theorems 2 and 3 this gives sublinear regret in any dimension. For the squared exponential, d enters only as the exponent of log T, which the authors attribute to the high smoothness of its sample paths.",
          "Section 5.2",
          "the high degree of smoothness of the sample paths eﬀectively combats the curse of dimensionality"),
         ("beta in practice vs theory: on the synthetic experiments (functions sampled from a squared exponential kernel with lengthscale 0.2, D = [0, 1] discretized into 1000 points, noise variance 0.025, T = 1000, delta = 0.1, 30 trials), the Theorem 1 beta_t gives competitive performance, but scaling beta_t down by a factor of 5, found by cross-validation, improves the algorithm; the authors note they did not optimize the constants in the bounds.",
          "Section 6",
          "While the choice of βt as recommended by Theorem 1 leads to competitive performance of GP-UCB, we ﬁnd (using cross-validation) that the algorithm is improved by scaling βt down by a factor 5."),
         ("Sensor experiments: the kernel matrix is the empirical covariance computed from the first two-thirds of the data, and objectives come from the remaining third (temperature: 46 sensors, T = 46, averaged over 2000 objectives; traffic: 357 sensors, T = 357, 900 runs; 5% noise, delta = 0.1). GP-UCB is compared with EI, MPI, mean-only and variance-only rules: on temperature data GP-UCB and EI clearly outperform the others without significant difference between them, and on synthetic and traffic data MPI does equally well.",
          "Section 6",
          "In summary, GP-UCB performs at least on par with the existing approaches which are not equipped with regret bounds."),
     ],
     "notes": "Affiliations: California Institute of Technology, University of Pennsylvania, Saarland University. Venue: a footnote on the first page says 'This is the longer version of our paper in ICML 2010'; the card is for that longer arXiv v4 version, and the venue field records the ICML 2010 paper it extends. The analysis assumes the kernel (and, for Theorems 1-2, the noise variance) is known; no discussion of learning kernel hyperparameters during optimization was found (searched for hyperparam, lengthscale, estimat, misspecif). Maximizing the UCB index over an infinite D may be hard; the authors say global search heuristics are very effective in practice and that evaluating f is generally assumed to cost more than maximizing the index. The bounds concern cumulative regret; the max of the first T values is no further from f(x*) than the average. Whether the down-scaled beta_t was also used on the sensor data is not stated. Comparison results are shown only in Figure 5 (not recorded). No hyperparameter-optimization experiments are run; the task tag is the closest registered one."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
