import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1511.08228",
     "title": "Neural GPUs Learn Algorithms",
     "authors": ["Łukasz Kaiser", "Ilya Sutskever"],
     "year": 2015, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1511.08228",
               "code": "https://github.com/tensorflow/models/tree/master/neural_gpu"},
     "tasks": ["algorithm-learning"],
     "fam": ["deep-learning"], "par": ["supervised"],
     "proposes": ["Neural GPU: a highly parallel convolutional gated recurrent architecture trained on short instances of algorithmic tasks (binary addition/multiplication, copying, reversing, duplicating, sorting bits) and tested on much longer ones; training techniques incl. parameter sharing relaxation, curriculum, small dropout and gradient noise"],
     "claims": [
         ("Contribution: the paper proposes the Neural GPU, built on a convolutional gated recurrent unit, presented as computationally universal like the Neural Turing Machine but highly parallel, which the authors say makes it easier to train and efficient to run.",
          "Abstract",
          "We present a neural network architecture to address this problem: the Neural GPU."),
         ("Main empirical claim (length generalization): trained on binary numbers of up to 20 bits, the Neural GPU shows no errors at test time even on much longer numbers (tasks include long binary addition and multiplication).",
          "Abstract",
          "We train the Neural GPU on numbers with up-to 20 bits and observe no errors whatsoever while testing it, even on much longer numbers."),
         ("Test input sizes: for binary multiplication, trained on numbers of up to 20 bits, the authors report no error on any inputs they tested, with tests on numbers up to 2000 bits long; they also say technical limits of their implementation prevented testing much above 2000 bits (Results paragraph).",
          "Introduction",
          "Trained on up-to 20-bit numbers, we see no single error on any inputs we tested, and we tested on numbers up-to 2000 bits long."),
         ("Success metric: Table 1 reports the fraction of test cases in which every bit of the model's output is correct (whole-sequence exact match), not per-bit accuracy.",
          "Experiments (Table 1 caption)",
          "The table shows the fraction of test cases for which every single bit of the model’s output is correct."),
         ("Relation to sorting: one of the simpler tasks is sorting a bit sequence; the authors note that with only two symbols this is a counting task (count the 0s). For the simpler tasks of Section 3.2 the authors state that, after training on sequences of length up to 41, they found no error on any length tested (up to 4001); for duplication, however, the same section states training on inputs of up to 20 bits and testing on inputs of up to 2000 bits.",
          "Other algorithmic tasks",
          "Since there are only 2 symbols to sort, this is a counting tasks – the network must count how many 0s are in the input and produce the output accordingly, as in the example below."),
         ("Baseline protocol: the stack-RNN baseline was not trained with the authors' training regime but with its released source code (n_max = 41); to match the authors' procedure it was run 729 times with different seeds and the best result is reported. The LSTM+attention baseline (about 200k parameters vs about 30k for the Neural GPU) was trained with the same techniques as the Neural GPU, including curriculum training and gradient noise.",
          "Addition and multiplication (Models)",
          "To match our training procedure, we ran it 729 times (cf. Section 3.3) with different random seeds and we report the best obtained result."),
         ("Failure modes: often only a few of the 729 grid-search models generalize to very long unseen instances (usually many generalize to 40 or even 200 bits, but only a few work without error for 2000-bit numbers); dropout and gradient noise improve reliability, and the authors suggest another technique might help more.",
          "Discussion",
          "Another problem is that often only a few models in a 729 grid search generalize to very long unseen instances."),
     ],
     "notes": "Affiliation: both authors Google Brain (title page). PDF states: Published as a conference paper at ICLR 2016. Training data: 10k random examples per training length (about 200k total for up to 20-bit numbers). Curriculum: train on longer numbers only after crossing a progress threshold on shorter ones, with 20% random-length minibatches. Dropout was stated to be necessary for multiplication models that generalize to 2000 bits, and parameter sharing relaxation 'crucial for learning multiplication'. Ensembles of 5 models are said to 'almost always generalize perfectly on binary tasks'. Model selection: Section 3.3 states 'Each result we report is obtained by running a grid search over 3^6 = 729 instances' (3 settings each of learning rate, initial parameter scale, relaxation pull factor, curriculum progress threshold, gradient noise scale, dropout); for the stack-RNN baseline the text says the best of 729 seeded runs is reported; for the Neural GPU the text does not spell out the selection rule among the 729 runs. Loss: softmax over output logits with negative log probability of the target (output symbols only); no supervision on intermediate algorithm steps is described. Data efficiency: with only about 100 examples per length, some binary addition models generalized to 200-bit numbers, but the authors never managed to train a good binary multiplication model with that little data. Additional failure mode from the text (Discussion): decimal inputs degrade performance; long decimal multiplication was not learned, while m=128 allows learning all other tasks in decimal. CLRS algorithms are not used (paper predates CLRS)."},

    {"id": "arxiv-1910.10593",
     "title": "Neural Execution of Graph Algorithms",
     "authors": ["Petar Veličković", "Rex Ying", "Matilde Padovano", "Raia Hadsell", "Charles Blundell"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1910.10593"},
     "tasks": ["algorithm-learning"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["neural graph algorithm execution: encode-process-decode GNNs supervised on every intermediate step of classical graph algorithms (BFS reachability, Bellman-Ford shortest paths, Prim's MST), with a max-aggregation MPNN processor shared across algorithms and a learned termination network"],
     "claims": [
         ("Contribution and algorithms: GNN architectures are trained to imitate individual steps of classical graph algorithms, both parallel (breadth-first search, Bellman-Ford) and sequential (Prim's algorithm for minimum spanning trees).",
          "Abstract",
          "Here, instead, we focus on learning in the space of algorithms: we train several state-of-the-art GNN architectures to imitate individual steps of classical graph algorithms, parallel (breadth-ﬁrst search, Bellman-Ford) as well as sequential (Prim’s algorithm)."),
         ("Architecture hypothesis: because graph algorithms usually make discrete decisions within neighbourhoods, the authors hypothesise that maximisation-based message passing networks are best suited, and report validating this empirically (MPNN-max vs mean/sum MPNNs, GAT variants and an LSTM on serialised edge lists).",
          "Abstract",
          "As graph algorithms usually rely on making discrete decisions within neighbourhoods, we hypothesise that maximisation-based message passing neural networks are best-suited for such objectives, and validate this claim empirically."),
         ("Supervision: the training signal follows how the classical algorithm processes the input, including relevant intermediate outputs (step-wise supervision, i.e. hints), rather than only the final solution.",
          "Introduction",
          "The supervision signal is driven by how a known classical algorithm would process such inputs (including any relevant intermediate outputs), providing explicit (and reusable) guidance on how to tackle graph-structured problems."),
         ("Train vs test sizes: for each of seven synthetic graph categories (ladder, 2D grid, trees, Erdos-Renyi, Barabasi-Albert, 4-Community, 4-Caveman), 100 training and 5 validation graphs of only 20 nodes are generated; test graphs have 20, 50 and 100 nodes (5 per category). The stated motivation is a 'programmer' perspective: inspect small graphs, apply to arbitrarily large ones.",
          "Experimental setup",
          "For each category, we generate 100 training and 5 validation graphs of only 20 nodes."),
         ("Larger-input generalization: the authors state that the desirable properties of MPNN-max persist on graphs up to 75x larger than training graphs; Table 4 covers shortest-path predecessor accuracy of MPNN-max trained jointly with reachability on 20-node graphs, tested at 20 to 1500 nodes.",
          "Results and discussion",
          "Desirable properties of the MPNN-max as an algorithm executor persist when generalising to even larger graphs, as we demonstrate in Table 4—demonstrating favourable generalisation on graphs up to 75× as large as the graphs originally trained on."),
         ("Intermediate-step supervision vs outputs only: in the no-algo ablation (predicting predecessors and termination directly from inputs, which the authors call the primary approach of prior GNN work), they conclude there is a clear benefit to supervising on the intermediate distance information, giving an additional improvement over only supervising on final downstream outputs (shortest-path task).",
          "Results and discussion",
          "Similarly, considering the no-algo experiment, we conclude that there is a clear beneﬁt to supervising on the distance information—giving an additional performance improvement compared to the standard approach of only supervising on the ﬁnal downstream outputs."),
         ("Metric limitation stated by the authors: accuracy is reported both averaged over all steps and at the last step, but the last-step metric says nothing about faithfulness to the algorithm and the mean-step metric can be inflated by terminating later; they add per-step plots and leave a better single-number metric to future work.",
          "Additional metrics",
          "the last-step performance provides no indication of faithfulness to the original algorithm, while the mean-step performance may be artiﬁcially improved by terminating the algorithm at a latter point"),
     ],
     "notes": "Affiliation: DeepMind (Veličković, Hadsell, Blundell); Ying and Padovano work performed while at DeepMind (title page). PDF states: Published as a conference paper at ICLR 2020. Training protocol: K=32 latent features, Adam, initial learning rate 0.0005, early stopping on validation predecessor accuracy (patience 10 epochs); termination assumed at |V| steps if not predicted earlier. No per-model hyperparameter tuning is described in the text (searched: tuned, hyperparameter, grid); all models appear to share this setup. Edge weights drawn uniformly from [0.2, 1], which the authors say essentially guarantees a unique solution; corner cases such as negative weight cycles are ignored and left to future work. BFS and Bellman-Ford are learned simultaneously; a curriculum (BFS first, then Bellman-Ford) performed worse than joint training. Appendix C: training on 100-node graphs and testing on 1000-node graphs. Table 5: training on a single graph type (Erdos-Renyi or trees) biases the model toward that type's structure. Appendix B gives an information-theoretic argument (conditional mutual information) for multi-algorithm learning, assuming the two algorithms share subroutines (positive conditional mutual information) and that the simpler algorithm's output can be fully learnt on its own. Prim's algorithm (Results): a non-sequential no-algo MPNN-max variant trained to predict predecessors directly generalised poorly to larger graphs, weaker than even the LSTM sequential baseline. Sorting/binary search/greedy activity selection are not studied. The paper calls Prim's algorithm 'sequential' and does not use the word 'greedy' (Prim's is a greedy MST algorithm by standard textbook classification, not by this paper's wording)."},

    {"id": "arxiv-1905.13211",
     "title": "What Can Neural Networks Reason About?",
     "authors": ["Keyulu Xu", "Jingling Li", "Mozhi Zhang", "Simon S. Du", "Ken-ichi Kawarabayashi", "Stefanie Jegelka"],
     "year": 2019, "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1905.13211"},
     "tasks": ["algorithm-learning"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["algorithmic alignment: a PAC-style measure of how well a network's computation structure matches a reasoning algorithm, with a sample complexity bound that decreases with better alignment; GNNs aligned with dynamic programming (e.g. Bellman-Ford); Neural Exhaustive Search for subset sum"],
     "claims": [
         ("Contribution: the paper formally defines algorithmic alignment between a network's computation structure and the algorithmic structure of a reasoning process, and derives a sample complexity bound that decreases with better alignment.",
          "Abstract",
          "We formally deﬁne this algorithmic alignment and derive a sample complexity bound that decreases with better alignment."),
         ("Definition (informal): a network aligns with an algorithm if it can simulate the algorithm with a limited number of modules, each of which is simple (low sample complexity); e.g. a GNN simulates Bellman-Ford by learning only the relaxation step, whereas an MLP would have to learn the whole for-loop.",
          "Formalization of algorithmic alignment",
          "Formally, a neural network aligns with an algorithm if it can simulate the algorithm via a limited number of modules, and each module is simple, i.e., has low sample complexity."),
         ("GUARANTEE and its assumptions: the theorem linking alignment to sample complexity holds only in a simplifying setting where the network's modules are trained sequentially with auxiliary labels (Theorem 3.6 additionally assumes i.i.d. samples with bounded universe size |S| < N, algorithm stability of the module learner, sequential learning, and Lipschitzness of the learned modules; the paper illustrates module sample complexity with Theorem 3.5, an NTK-based result for overparameterized two-layer MLPs, and says other module bounds can be used). The same paragraph says auxiliary labels are not available in practice, that the same pattern is observed for end-to-end learning in the experiments (empirical, not covered by the theorem), and leaves end-to-end sample complexity analysis to future work.",
          "Better algorithmic alignment implies better generalization",
          "Theorem 3.6 states that, in a simplifying setting where we sequentially train modules of a network with auxiliary labels, the sample complexity bound increases with algorithmic alignment value M."),
         ("GNNs and dynamic programming: interpreting GNN aggregation as the DP update, the authors argue Theorem 3.6 suggests a GNN with enough iterations can sample-efficiently learn any DP algorithm with a simple update function such as sum/min/max (shortest paths via Bellman-Ford as the example).",
          "Dynamic programming",
          "Therefore, Theorem 3.6 suggests that a GNN with enough iterations can sample efﬁciently learn any DP algorithm with a simple DP-update function, e.g. sum/min/max."),
         ("Scope assumption: the framework is restricted to reasoning tasks whose underlying reasoning process is exact and has clear algorithmic structure; approximation algorithms and unknown structures are left to future work.",
          "Theoretical framework",
          "In this paper, we focus on reasoning tasks whose underlying reasoning process is exact and has clear algorithmic structure."),
         ("Evaluation protocol: for each task's dataset (Appendix G), each model's reported test accuracy uses the hyperparameter setting with the best validation accuracy; train, validation and test sets are sampled from the same generator (e.g. 50,000/5,000/5,000 for maximum value difference with 25 treasures), so no larger-input test is described (searched: larger, extrapolat). Section 4 adds that all models are made to perfectly fit their training sets through extensive hyperparameter tuning so test accuracy reflects generalization.",
          "Appendix G (Dataset generation)",
          "For each model, we report the test accuracy with the hyperparameter setting that achieves the best validation accuracy.", 16),
         ("Relation to sorting: on the maximum value difference task an MLP does not generalize, but if the treasures are sorted by value the MLP achieves perfect test accuracy, which the authors explain as the algorithm reducing to a single subtraction.",
          "Summary statistics",
          "Interestingly, if we sort the treasures by value (Sorted MLP in Fig. 3a), MLP achieves perfect test accuracy."),
     ],
     "notes": "Affiliations (title page): MIT, University of Maryland, IAS, National Institute of Informatics. PDF states: Published as a conference paper at ICLR 2020. Tasks (all synthetic, in-distribution test): maximum value difference and furthest pair over 25 'treasures', monster trainer (a shortest-path variant with 10 monsters and an unknown cost function), subset sum over 6 numbers. Supervision: final answers only (end-to-end). Hyperparameter grids per model are listed in Appendix G (learning rates, batch size, hidden sizes, layers). Monster trainer: GNNs with 4 iterations nearly match 7 iterations, explained as aligning with a bidirectional Bellman-Ford needing half the iterations (Appendix G.3). The paper states subset sum 'is NP-hard (Karp, 1972) and cannot be solved by DP' and that GNNs therefore cannot sample-efficiently learn it; it proposes Neural Exhaustive Search (enumerating all subsets) instead. Proposition 3.1/3.2: GNNs and MLPs are universal approximators for the relevant functions, so the authors attribute performance differences to generalization rather than expressiveness. CLRS (arxiv-2205.15659) cites this paper for the claim that architectures better aligned with the algorithm 'can be proven to have better sample complexity' and motivates its graph encoding with it."},

    {"id": "arxiv-2205.15659",
     "title": "The CLRS Algorithmic Reasoning Benchmark",
     "authors": ["Petar Veličković", "Adrià Puigdomènech Badia", "David Budden", "Razvan Pascanu", "Andrea Banino",
                 "Misha Dashevskiy", "Raia Hadsell", "Charles Blundell"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2205.15659", "code": "https://github.com/deepmind/clrs"},
     "tasks": ["algorithm-learning"],
     "fam": ["graph-neural-networks", "deep-learning"], "par": ["supervised"],
     "proposes": ["CLRS-30 benchmark: input/output and intermediate 'hint' trajectories for 30 algorithms from the CLRS textbook (sorting, searching, divide and conquer, greedy, dynamic programming, graphs, strings, geometry) in a graph encoding, with a fixed in-distribution validation (16 nodes) and out-of-distribution test (64 nodes) protocol; baseline processors Deep Sets, GAT, Memory Networks, MPNN, PGN"],
     "claims": [
         ("Contribution: CLRS-30 is a dataset of trajectories (inputs, outputs and optional intermediate targets) for 30 classical algorithms covering sorting, searching, dynamic programming, geometry, graphs and strings, proposed to unify evaluation that prior work did on bespoke data.",
          "Introduction",
          "we propose and evaluate on CLRS-30: a dataset containing trajectories—a trajectory is formed of inputs, the corresponding outputs and optional intermediary targets—of 30 classical algorithms"),
         ("Sorting algorithms included: insertion sort, bubble sort, heapsort and quicksort. (Searching includes minimum, binary search and quickselect; merge sort is excluded because it needs memory not attached to input objects.)",
          "CLRS Algorithmic Reasoning Benchmark",
          "Sorting: Insertion sort, bubble sort, heapsort (Williams, 1964), quicksort (Hoare, 1962)."),
         ("Greedy algorithms included: activity selection and task scheduling.",
          "CLRS Algorithmic Reasoning Benchmark",
          "Greedy: Activity selection (Gavril, 1972), task scheduling (Lawler, 1985)."),
         ("Train vs test sizes: training and validation inputs have 16 nodes (1,000 training and 32 validation trajectories; validation measures in-distribution generalisation), and the test set measures out-of-distribution generalisation with 32 trajectories on inputs of 64 nodes (more for graph-level outputs). Most graph-algorithm inputs are Erdos-Renyi graphs; scalar inputs are U(0,1).",
          "Dataset statistics",
          "For testing, we measure out-of-distribution generalisation, and sample 32 trajectories for inputs of 64 nodes."),
         ("Supervision with hints: baselines both decode hints (in the loss) and encode them as inputs, with noisy teacher forcing at training time (ground-truth hints fed back with probability 0.5); at evaluation the number of processor steps is set by the number of ground-truth hints, a requirement the authors say could be lifted, e.g., with termination networks.",
          "Baseline models",
          "The quantity of hints is still used to determine the number of processor steps to perform at evaluation time."),
         ("Out-of-distribution failure: MPNNs, which appear to dominate in-distribution for most tasks (Section 4.3: over 90% F1 for nearly all of them on validation), do not transfer their gains to graphs four times larger (64 vs 16 nodes); PGN becomes the most performant model when averaged across task types, which the authors say aligns with prior research (Veličković et al., 2020).",
          "Test (out-of-distribution) performance",
          "MPNNs are unable to transfer their impressive gains to graphs that are four times larger"),
         ("Stated failure modes: the authors say the OOD version of CLRS-30 is highly challenging and far from solved for most tasks; PGNs struggled on tasks requiring long-range rollouts (e.g. DFS) or recursive reasoning (e.g. Quicksort, Quickselect); string matching (e.g. KMP) may need more specialised inductive biases; the processor tended to do best on tasks with favourable (sublinear) hint counts such as BFS, Bellman-Ford and task scheduling.",
          "Test (out-of-distribution) performance",
          "In particular, PGNs struggled on tasks requiring long-range rollouts (such as DFS), or recursive reasoning (such as Quicksort and Quickselect)."),
     ],
     "notes": "Affiliation: all authors DeepMind (title page). PDF states: Proceedings of the 39th International Conference on Machine Learning (ICML 2022), PMLR 162. Full algorithm list (Section 3): Sorting (insertion, bubble, heapsort, quicksort); Searching (minimum, binary search, quickselect); D&C (maximum subarray, Kadane's variant: one algorithm); Greedy (activity selection, task scheduling); DP (matrix chain multiplication, LCS, optimal BST); Graphs (DFS, BFS, topological sort, articulation points, bridges, Kosaraju SCC, Kruskal, Prim, Bellman-Ford, Dijkstra, DAG shortest paths, Floyd-Warshall); Strings (naive matching, KMP); Geometry (segment intersection, Graham scan, Jarvis' march). Exclusions: NP-hard tasks and approximation algorithms, tasks needing numerical outputs, standalone data structures, algorithms needing dynamically allocated memory (merge sort, Hierholzer, finite-automaton string matching). Sorting is encoded as predicting predecessor pointers (no value swapping); insertion sort's inner backward scan is compressed into one step. Metric: test micro-F1 averaged per algorithm class (Table 1), plus a win/tie/loss count across 30 algorithms (Appendix C: model A outperforms B on an algorithm if mean(A) - std(A) > mean(B)); validation curves averaged over three seeds. Training: batch 32, Adam lr 0.001, 10,000 steps, early stopping on in-distribution validation, one V100. Hyperparameters: 'We provide all implementations and hyperparameters within our codebase'; no per-model tuning procedure is described in the text. Authors cite Xu et al. (arxiv-1905.13211) on algorithmic alignment and Veličković et al. 2019 (arxiv-1910.10593) for the MPNN max aggregator. The first author is also first author of the cited works that introduced baseline components used here (Veličković et al., 2019 for the max-aggregator MPNN executor; Veličković et al., 2020 for PGN; he is also first author of the GAT paper used as a baseline processor); Hadsell and Blundell are co-authors of arxiv-1910.10593 too (reference list). CLRS's statement that better-aligned architectures 'can be proven to have better sample complexity' (Xu et al.) should be read with the assumptions of that proof (arxiv-1905.13211 c3: sequential training with auxiliary labels)."},

    {"id": "arxiv-2207.04901",
     "title": "Exploring Length Generalization in Large Language Models",
     "authors": ["Cem Anil", "Yuhuai Wu", "Anders Andreassen", "Aitor Lewkowycz", "Vedant Misra", "Vinay Ramasesh",
                 "Ambrose Slone", "Guy Gur-Ari", "Ethan Dyer", "Behnam Neyshabur"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2207.04901"},
     "tasks": ["algorithm-learning"],
     "fam": ["large-language-models", "deep-learning"], "par": ["in-context-learning", "supervised"],
     "proposes": ["empirical study of length generalization in pretrained transformer LMs (LaMDA) on parity and Boolean variable assignment, comparing finetuning, few-shot prompting and scratchpad (chain-of-thought) and their combinations, with failure analyses (non-sequential shortcuts, distractor tokens)"],
     "claims": [
         ("Main claim (finetuning): naively finetuning transformers on length generalization tasks shows significant generalization deficiencies independent of model scale (Section 3.1: finetuned LaMDA models of 244m to 64b parameters, on parity and variable assignment).",
          "Abstract",
          "We ﬁrst establish that naively ﬁnetuning transformers on length generalization tasks shows signiﬁcant generalization deﬁciencies independent of model scale."),
         ("Main claim (prompting): combining pretrained LLMs' in-context learning with scratchpad prompting (outputting solution steps before the answer) gives a dramatic improvement in length generalization (prompting experiments in Section 5 use the pretrained LaMDA 128b model without finetuning; parity phrased as coin flips, evaluated up to 20 flips).",
          "Abstract",
          "We then show that combining pretrained large language models’ in-context learning abilities with scratchpad prompting (asking the model to output solution steps before producing an answer) results in a dramatic improvement in length generalization."),
         ("Scope (tasks): the study focuses on two simple algorithmic tasks, parity and Boolean variable assignment, chosen because the model must track a state to extrapolate to longer lengths.",
          "Introduction",
          "In particular, we focus on two simple algorithmic tasks, parity and variable assignment, in which the model needs to keep track of a state in order to extrapolate to longer lengths (see Figure 1)."),
         ("Scope (models and lengths): four pretrained LaMDA decoder-only models (244m, 422m, 1b, 64b parameters) are finetuned on parity with training bitstrings of length 10 to 21 and evaluated on lengths 3 to 40; on chain-like variable assignment, training lengths are 3 to 8 and test lengths 3 to 19. Model scale is reported to have little effect on length generalization.",
          "Scale doesn't improve length generalization",
          "We ﬁnetuned four pretrained LaMDA models with 244m, 422m, 1b and 64b parameters on the parity task, where the training distribution included randomly sampled bitstrings of length 10 to 21."),
         ("Disagreement with prior work: finetuning with a scratchpad (step-by-step targets) also fails to generalize to longer problems, which the authors say contrasts with what previous work [3] (Nye et al., scratchpads) suggests; among positional encoding, distractors and end-of-sequence prediction, they conclude distractors are the main culprit.",
          "Introduction (contributions)",
          "We establish ﬁnetuning with scratchpad also fails to generalize to longer problems, in contrast to what is suggested by previous works [3]."),
         ("Failure mode: transformers finetuned on sequential length generalization problems are biased toward non-sequential 'shortcut' solutions that fail on longer instances (e.g. on parity with fixed length and varied number of ones, in-distribution accuracy was 100% while OOD was roughly random, suggesting counting-and-thresholding).",
          "Transformers prefer parallel strategies over sequential ones",
          "The results presented in Section 3.1 establish that, when presented with sequential length generalization problems, transformers are biased toward learning non-sequential “shortcut” solutions that fail at longer problem instances."),
         ("Evaluation practice: different finetuning hyperparameters had a large effect on length generalization while barely changing in-distribution performance, which the authors call surprising; in-distribution performance therefore did not indicate OOD length generalization in these finetuning experiments.",
          "Introduction (contributions)",
          "Surprisingly, different hyperparameter choices for ﬁnetuning have a large effect on length generalization performance, while having minimal effect on the ﬁnal in-distribution performance (Section 3.3)."),
     ],
     "notes": "Affiliation: Google Research (Blueshift Team), Google Research, University of Toronto/Vector Institute; first author interning at Google Research. LaMDA models are Google models, and a footnote says the model name was omitted for anonymization (yet LaMDA is named in this version). PDF states: 36th Conference on Neural Information Processing Systems (NeurIPS 2022). Prompting experiments use the pretrained LaMDA 128b model (parity phrased as a coin-flip task, prompts with short exemplars, tested up to 20 flips); OpenAI Codex is also evaluated on variable assignment (Figure 7). Few-shot finetuning with scratchpad helped on parity but not on variable assignment; the authors hypothesise this depends on the base model's non-finetuned performance and leave rigorous evaluation to future work (Section 5.1; prompt-style sanity check in Appendix E). Model scope: finetuning uses LaMDA 244m/422m/1b/64b (Section 3.1; a 255m model on the diverse variable-assignment split in Section 3.2), prompting uses LaMDA 128b; all decoder-only; tasks are only parity and Boolean variable assignment (synthetic). Conclusion scope statement: length generalization 'is a challenge for language models at least up to the 100B parameter scale'. Appendix F: masking all distractor tokens gives perfect length generalization in their parity scratchpad experiments; input distractors hurt more. Hyperparameters (Appendix C): learning-rate sweep per model size, preferring the largest stable learning rate because larger rates gave the best length generalization; AdaFactor; greedy decoding. Inconsistency: Section 3.1 gives parity training lengths 10 to 21, while Appendix A.1 gives 3 to 20 for training and 3 to 40 for validation/test; the card follows Section 3.1 in claim c4 and flags this here. Author overlap: reference [3] (Nye et al., 'Show your work: Scratchpads...'), whose length-generalization suggestion this paper disputes, lists Anders Johan Andreassen, Guy Gur-Ari and Aitor Lewkowycz, who are also authors of this paper; the entry is truncated with 'et al.', so further overlap cannot be checked from this PDF. Only parity and variable assignment are studied; no sorting, binary search or greedy tasks."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): classical algorithms (sorting, binary search, greedy) and machine learning; carded by a subagent. Results tables not recorded; claims only.")
