import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_automl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1208.3719",
     "title": "Auto-WEKA: Combined Selection and Hyperparameter Optimization of Classification Algorithms",
     "authors": ["Chris Thornton", "Frank Hutter", "Holger H. Hoos", "Kevin Leyton-Brown"],
     "year": 2012, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1208.3719"},
     "tasks": ["model-selection", "hyperparameter-optimization", "tabular-classification"],
     "fam": ["automl-systems", "bayesian-optimization"], "par": ["supervised"],
     "proposes": ["The combined algorithm selection and hyperparameter optimization (CASH) problem: jointly choose a learning algorithm and its hyperparameters to minimize k-fold cross-validation loss, reformulated as one hierarchical hyperparameter optimization problem with a root-level hyperparameter that selects the algorithm",
                  "Auto-WEKA: a CASH search space over all WEKA classifiers (27 base, 10 meta, 2 ensemble methods) and feature selection (3 search methods, 8 evaluators), with 786 hierarchical parameters, searched with the Bayesian optimizers SMAC (random-forest model) or TPE"],
     "claims": [
         ("CASH can be reformulated as a single combined hierarchical hyperparameter optimization problem whose parameter space is the union of the algorithms' hyperparameter spaces plus a new root-level hyperparameter selecting among the algorithms; the root-level parameters of each subspace are conditional on that choice. The authors name Bayesian optimization, in particular sequential model-based optimization (SMBO), as a promising approach because it handles categorical and continuous hyperparameters and conditional structure.",
          "Section 3",
          "We note that this problem can be reformulated as a single combined hierarchical hyperparameter optimization problem"),
         ("SMAC (as used here, with random-forest models) instantiates inactive conditional parameters to defaults, uses expected improvement, and evaluates cross-validation folds one at a time: a new configuration must beat the incumbent on every comparison over the folds used so far, so a poor configuration can be dropped after a single fold; every second configuration is selected at random as a diversification safeguard.",
          "Section 3.1",
          "This means that a poorly performing conﬁguration can be discarded after considering as little as a single fold."),
         ("TPE models p(lambda | c) with two density estimates, l for configurations with loss below the gamma-quantile threshold (default gamma = 0.15) and g for the rest, and picks candidates with the smallest g/l among randomly generated ones; because of its tree-structured 1-D Parzen estimators it assumes independence for hyperparameters that never appear together on a root-to-leaf path.",
          "Section 3.2",
          "Note that this means that TPE assumes independence for hyperparameters that do not appear together along any path from the tree’s root to one of its leaves."),
         ("Search space: two top-level Booleans (base classifier vs. ensemble/meta classifier; feature selection on/off) with conditional choices below (meta-methods take one base classifier, ensembles up to five), giving four hierarchical layers and 786 parameters in total; the authors estimate that discretizing each domain to at most 10 values would give over 10^47 settings.",
          "Section 4",
          "This results in a very wide tree that captures all the hierarchical nature of the model hyperparameters, and allows the creation of a single hyperparameter optimization problem with four hierarchical layers of a total of 786 parameters."),
         ("Protocol: 21 datasets (15 UCI, convex, MNIST basic, rotated MNIST with background images, KDD Cup 09 appetency, CIFAR-10 and a 10,000-point subset); predefined splits or a random 70/30 train/test split, with test data used once offline. Runs on Intel Xeon X5650 machines with a 3GB RAM limit per classifier (exceeding it counts as 100% error), a per-fold training timeout of 150 minutes (15 for feature search/evaluation), and a 30-hour budget per optimizer; 25 seeded runs per method, with bootstrap sampling of 4 runs (keeping the best cross-validation run) to simulate a 4-core workstation.",
          "Section 5.1",
          "For each method, we performed 25 runs of this process with diﬀerent random seeds and then – in order to simulate parallelization on a typical workstation – used bootstrap sampling to repeatedly select 4 random runs and report the performance of the one with best cross-validation performance."),
         ("Baselines: Ex-Def picks, by 10-fold cross-validation, the best of the 39 WEKA classifiers at default hyperparameters; Random Grid performs random search over the union of hyperparameter grids for the 27 base classifiers plus the 39 defaults, which the authors call a simple CASH algorithm. Random Grid used 400 CPU hours per dataset on average (at least 120), versus 4 x 30 CPU hours for Auto-WEKA. Best/worst 'oracle' columns are measured on the test set.",
          "Section 5.2",
          "We executed this Random Grid search for all our datasets in parallel, using 400 CPU hours on average per dataset (at least 120 hours for each)."),
         ("On test data the differences were less pronounced than in cross-validation: the text reports Auto-WEKA outperforming Random Grid and Ex-Def in 15/21 cases with 3 ties and 3 losses, and Random Grid beating Ex-Def in only 9/21 cases. Auto-WEKA performed best on all 11 largest datasets, which the authors attribute to overfitting risk decreasing with dataset size.",
          "Section 5.4",
          "Notably, Auto-WEKA performed best on all of the 11 largest datasets; we attribute this to the fact that the risk of overﬁtting decreases with dataset size."),
         ("Overfitting check: Auto-WEKA optimizes on 70% of its training set and afterwards evaluates the trajectory of incumbents on the withheld 30%, reporting the Spearman rank correlation between cross-validation and held-out performance; the correlation tends to drop as the cross-validation/test gap grows (e.g. GermanCredit), but the authors caution that this weak signal gives no guarantee that a large correlation means a small gap or vice versa.",
          "Section 5.4",
          "We do note, however, that this weak signal has to be used with caution: there is no guarantee that large correlation coeﬃcients yield a small gap and vice versa."),
         ("Stated limitation: Auto-WEKA still shows larger improvements in cross-validation performance than on test data, which the authors take as a reason to investigate more sophisticated methods for detecting and avoiding overfitting than their correlation-based approach.",
          "Section 6",
          "First, Auto-WEKA still shows larger improvements in cross-validation performance than on test data, suggesting the investigation of more sophisticated methods for detecting and avoiding overﬁtting than our simple correlation-based approach."),
     ],
     "notes": "Affiliation: University of British Columbia. No venue is stated in the arXiv PDF (v2, dated 6 Mar 2013) or in the arXiv comment/journal_ref; none recorded. Year is the first arXiv version. Section numbers are from numbered headings in the PDF. Conflict of interest: SMAC, one of the two compared optimizers and the recommended one, is by Hutter, Hoos and Leyton-Brown (reference [14]), three of the four authors; TPE (Bergstra et al.) is not; the authors thank the SMAC and TPE authors for access to their implementations. Both optimizers were run with their own default meta-hyperparameters; meta-hyperparameter optimization was not attempted (Section 4, which says a separate meta-train/validation split would be needed to guard against over-fitting). The intro states the authors found no evidence that CASH had previously been considered. Section 5.2 also reports that the best/worst default-classifier gap exceeded 20% on 14 of 21 datasets even among a few popular classifiers, from which the authors conclude some form of algorithm selection is essential. Table 4 values (median error over 100,000 bootstrap samples) are not recorded. The cross-validation comparison (SMAC better than TPE on 19/21, Auto-WEKA better than Random Grid on 20/21) is in Section 5.3."},

    {"id": "arxiv-1603.06212",
     "title": "Evaluation of a Tree-based Pipeline Optimization Tool for Automating Data Science",
     "authors": ["Randal S. Olson", "Nathan Bartley", "Ryan J. Urbanowicz", "Jason H. Moore"],
     "year": 2016, "venue": "GECCO 2016", "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1603.06212", "code": "http://github.com/rhiever/tpot"},
     "tasks": ["model-selection", "hyperparameter-optimization", "tabular-classification"],
     "fam": ["automl-systems"], "par": ["supervised"],
     "proposes": ["TPOT: tree-based machine learning pipelines (scikit-learn preprocessors, decomposition, feature selection and models; multiple copies of the data can be combined) whose structure and operator parameters are evolved with genetic programming (DEAP) to maximize classification accuracy",
                  "TPOT-Pareto: NSGA-II selection on two objectives, pipeline accuracy and pipeline complexity (number of operators), to obtain compact pipelines"],
     "claims": [
         ("Method: TPOT uses genetic programming (as implemented in DEAP) to evolve both the sequence of pipeline operators and each operator's parameters, maximizing the classification accuracy of the pipeline; changes can modify, remove or insert sequences of operators. At the end of a run the single best pipeline ever found (by accuracy) is used.",
          "Section 3.3",
          "In TPOT, we use GP to evolve the sequence of pipeline operators as well as each operator’s parameters (e.g., the number of trees in a random forest or the number of feature pairs to select during feature selection) to maximize the classiﬁcation accuracy of the pipeline."),
         ("Pipeline representation: pipelines are trees whose leaves are copies of the input data and whose nodes are operators (preprocessing, decomposition, feature selection, models), with a combination operator to merge copies; when data passes through a modeling operator, the newest classifier's predictions override earlier ones and earlier predictions are kept as a new feature, allowing arbitrary (including stacked) pipeline structures.",
          "Section 3.2",
          "Each time a data set is passed through a modeling operator, the resulting classiﬁcations are stored such that the most recent classiﬁer to process the data overrides any previous predictions, and the earlier classiﬁer’s predictions are stored as a new feature."),
         ("Fitness evaluation split: data is divided into stratified 75% training and 25% testing sets and pipelines are evaluated by classification accuracy on the testing set; the Results section reports balanced accuracy on 25% holdout sets (figure captions call these 'balanced cross validation accuracies on the holdout set', over 30 data sets or 30 cross-validation divisions). A validation split separate from the set used for GP fitness, or a discussion of overfitting that set, was not found in the text (searched for 'validation', 'overfit', 'holdout', 'cross').",
          "Section 3.3",
          "In this paper, TPOT pipelines are evaluated based on their classiﬁcation accuracy on the testing set."),
         ("TPOT-Pareto optimizes two objectives, maximizing classification accuracy and minimizing pipeline complexity (total number of operators); since no solution is globally optimal for both, it keeps a Pareto front and selects pipelines for reproduction with NSGA-II.",
          "Section 3.3",
          "we maintain a Pareto front in TPOT-Pareto and select the pipelines for reproduction according to the NSGA-II selection strategy"),
         ("Data: 360 simulated GAMETES data sets (12 genetic models; 3 heritabilities x 4 sample sizes from 200 to 1600 x 30 replicates; 100 SNPs of which 8 predictive, with purely epistatic interactions and no main effects) and 9 UCI data sets that the authors describe as hand-picked.",
          "Section 3.5",
          "To further demonstrate TPOT’s capabilities, we evaluate it on 9 hand-picked benchmark supervised learning data sets from the well-known UC-Irvine Machine Learning Repository [12]."),
         ("Controls: a random forest with 500 trees (a basic analysis with a state-of-the-art model) and TPOT-Random, which randomly generates the same number of pipelines, to test whether guided search is useful.",
          "Section 4",
          "The second control, TPOT-Random, is a version of TPOT where the same number of pipelines are randomly generated, which is meant to explore whether guided search is useful for pipeline optimization."),
         ("On the GAMETES data, all TPOT versions performed more or less the same on average in most cases, which the authors say suggests guided search may not be vital because random search generally performs as well; TPOT-Pareto tended to be more consistent (lower variance). On UCI data TPOT-Random also typically performed as well as guided search.",
          "Section 4",
          "This result suggests that guided search may not be vital for the automated design of pipelines because random search generally performs as well as guided search."),
         ("Pipeline bloat and cost: randomly generated pipelines tend to be needlessly complex (6 operators on average vs. 4 for TPOT and 2 for TPOT-Pareto, per the text), are slower, and on the larger Hill-Valley and spambase data sets no TPOT-Random replicate finished within 120 hours, whereas all TPOT and TPOT-Pareto replicates finished the same number of evaluations in under 48 hours.",
          "Section 4",
          "Furthermore, even though TPOT-Random pipelines perform nearly as well as regular TPOT pipelines, TPOT-Random pipelines tend to be needlessly complex and contain 6 pipeline operators on average (Figure 5)."),
         ("Stated limitation: TPOT is in early development, is still fairly slow on large data sets and often needs several hours (if not days); the authors plan to seed the population (e.g. with auto-sklearn) and bias mutation/crossover with a learning system.",
          "Section 5",
          "In particular, TPOT is still fairly slow on large data sets and often requires several hours (if not days) to properly analyze a large data set."),
     ],
     "notes": "Affiliations: University of Pennsylvania (Olson, Urbanowicz, Moore), University of Chicago (Bartley). Venue: the PDF carries the ACM block 'GECCO ’16 Denver, CO, USA' and the arXiv comment says 'preprint to appear in GECCO 2016, edits not yet made from reviewer comments'; recorded as 'GECCO 2016', but this arXiv v1 is the pre-revision preprint. GP settings (Table 1): population 100, 100 generations, 30 replicate runs (the Discussion restates 10,000 pipelines = 100 x 100). Conflict of interest: all compared variants are the authors' own; the GAMETES simulator (references [18], [19]) is by co-author Urbanowicz; no external AutoML system is compared (auto-sklearn is only discussed in Related Work, where the authors argue its fixed pipeline shape cannot produce arbitrarily large pipelines). Results are shown as box plots (Figures 3-5); only numbers written in the text are quoted. The text states that RF achieved only 63% accuracy on average on the easiest GAMETES setting while all TPOT versions reached 80%+ (Section 4)."},

    {"id": "arxiv-2003.06505",
     "title": "AutoGluon-Tabular: Robust and Accurate AutoML for Structured Data",
     "authors": ["Nick Erickson", "Jonas Mueller", "Alexander Shirkov", "Hang Zhang", "Pedro Larroy", "Mu Li", "Alexander Smola"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2003.06505", "code": "https://github.com/awslabs/autogluon"},
     "tasks": ["tabular-classification", "tabular-regression", "model-selection"],
     "fam": ["automl-systems", "heterogeneous-ensembles", "gradient-boosted-trees", "deep-learning"], "par": ["supervised"],
     "proposes": ["AutoGluon-Tabular: an AutoML framework that, instead of CASH, trains a fixed, ordered set of models (neural network, LightGBM, CatBoost, random forest, extra trees, k-NN) with predefined hyperparameters and combines them by multi-layer stack ensembling",
                  "Multi-layer stacking in which every base model type is reused as a stacker, stackers also receive the original features (skip connection), and the last layer is ensemble selection; all layers are trained on out-of-fold predictions from (n-repeated) k-fold bagging",
                  "A tabular neural network with per-categorical-feature embeddings and a linear skip connection to the output"],
     "claims": [
         ("The authors argue that prior work focused almost exclusively on CASH and that, since this search is typically intractable (nonconvex/nonsmooth), CASH algorithms are expensive, spending significant compute on poor configurations.",
          "Section 1",
          "Their brute-force search expends signiﬁcant compute evaluating poor model/hyperparameter conﬁgurations that no reasonable data scientist would consider."),
         ("Stacking design: whereas traditional stacking uses simpler stacker models to avoid another CASH problem, AutoGluon reuses all base-layer model types with the same hyperparameter values as stackers; the stackers take the original features concatenated with lower-layer predictions, and the final layer aggregates stackers with ensemble selection (citing Caruana et al., 2004).",
          "Section 2.5",
          "AutoGluon instead simply reuses all of its base layer model types (with the same hyperparameter values) as stackers."),
         ("Caveat of k-fold bagging: higher layers must be trained only on out-of-fold (OOF) predictions, but OOF predictions can still be slightly overfit because training of some models is influenced by OOF data (e.g. through the early-stopping criterion), and a stacker trained on overfit lower-layer predictions may amplify this through the layers; repeated k-fold bagging on n random partitions is proposed to mitigate it.",
          "Section 2.6",
          "While k-fold bagging efﬁciently reuses training data, it remains susceptible to a subtle form of over-ﬁtting."),
         ("In the benchmark, AutoGluon's hyperparameter_tune option was not used (auto_stack=True, 2-layer stacking with repeated bagging within the time limit); the authors state this demonstrates for the first time that high-accuracy AutoML is achievable entirely without CASH.",
          "Section 4.1",
          "This demonstrates for the ﬁrst time that high-accuracy AutoML is achievable entirely without CASH."),
         ("The default hyperparameter values of AutoGluon's models were chosen a priori and not tuned on the datasets used for benchmarking in the paper (they are in the AutoGluon source code); the neural network's layer sizes are scaled adaptively to the data in a fixed manner rather than by hyperparameter optimization.",
          "Appendix A",
          "These default hyperparameter values were chosen a priori and not tuned based on the particular datasets used for benchmarking in this paper."),
         ("Benchmark protocol: 39 OpenML AutoML Benchmark datasets (Gijsbers et al., 2019), each with the original 10 train/test splits (390 problems), 1h and 4h limits, loss 1-AUC (binary) or log-loss (multi-class), scored with the original benchmark code on an AWS m5.2xlarge (8 vCPU, 32 GiB) as in the original benchmark; plus 11 Kaggle competitions scored by Kaggle's server on hidden labels (4h and 8h, m5.24xlarge with 96 vCPU, 384 GiB). Averages and counts are taken only over datasets where all frameworks ran without error.",
          "Section 4.1",
          "Each AutoML framework is extensively evaluated in this benchmark through replicate runs on 10 different training/test splits for each dataset, making 390 prediction problems in total (splits provided by original benchmark, and reported numbers are averaged over them)."),
         ("Baseline configuration: Auto-WEKA, auto-sklearn, TPOT, H2O AutoML and GCP-Tables were run with default settings except where package authors suggested improvements in private communication; Auto-WEKA, TPOT and auto-sklearn were given data preprocessed by AutoGluon's own pipeline (Appendix C), and all frameworks ran on the same EC2 instance type with identical time limits except GCP-Tables (92 Google Cloud servers by default); actual training times are reported because some frameworks only loosely respected the limits.",
          "Section 4.1",
          "Each was run with default settings except where the package authors suggested an improved setting in private communication."),
         ("Because running GCP-Tables on all 390 AutoML Benchmark problems was economically infeasible (4h runs would exceed $30k), it was run only on the first fold of each of the 39 datasets, and comparisons with AutoGluon use only that fold.",
          "Appendix C",
          "Because running GCP-Tables on all 390 prediction problems of the AutoML benchmark was economically infeasible (4h runs would total over $30k), we only ran this AutoML tool on the ﬁrst fold of each of the 39 datasets."),
     ],
     "notes": "Affiliation: Amazon (all authors; AutoGluon is an awslabs project). No venue is stated in the arXiv v1 PDF or arXiv metadata; none recorded. Conflict of interest: the authors benchmark their own system against competitors; the paper does not state this as a conflict of interest. Mitigations stated in the paper: competitors' settings confirmed with the original package authors (Appendix C), and Table S3 compares the authors' runs of H2O, auto-sklearn, TPOT and Auto-WEKA with the original AutoML Benchmark results (counts above/below original are roughly balanced). Software versions: TPOT 0.11.1, Auto-WEKA 2.6, H2O 3.28.0.1, auto-sklearn 0.5.2 (0.6.0 was not used because of a dependency conflict with AutoGluon). Sagemaker AutoPilot was only included in the raw-accuracy comparison (Table S8) because it does not output class probabilities. AutoGluon itself failed on Dionis in the 4h runs (Appendix E.1.1). Win/loss tables, ablations (NoRepeat, NoMultiStack, NoBag, NoNetwork) and Kaggle placements are not recorded as results. Section numbers are from numbered headings in the PDF."},

    {"id": "arxiv-1911.04706",
     "title": "FLAML: A Fast and Lightweight AutoML Library",
     "authors": ["Chi Wang", "Qingyun Wu", "Markus Weimer", "Erkang Zhu"],
     "year": 2019, "venue": "MLSys 2021", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1911.04706", "code": "https://github.com/microsoft/FLAML"},
     "tasks": ["hyperparameter-optimization", "model-selection", "tabular-classification", "tabular-regression"],
     "fam": ["automl-systems", "gradient-boosted-trees"], "par": ["supervised"],
     "proposes": ["FLAML: a low-cost AutoML library that searches over learner, hyperparameters, training sample size and resampling strategy, choosing the next trial by estimated cost for improvement (ECI)",
                  "Learner proposer sampling each learner with probability proportional to 1/ECI; hyperparameter/sample-size proposer combining randomized direct search from a low-cost starting configuration (Wu et al., 2021) with progressive increase of the sample size; a threshold rule choosing cross-validation or holdout"],
     "claims": [
         ("Problem framing: the cost of one trial is jointly decided by the learner, a subset of its hyperparameters, the training data size and the resampling strategy, which also jointly affect the trial error; the goal is to minimize the total cost before finding a model with the lowest test error.",
          "Section 1",
          "We recognize that the cost of one trial is jointly decided by the following variables: the choice of learner, a subset of the hyperparameters for the chosen learner, the size of the training data, and the resampling strategy."),
         ("FLAML deliberately does not rely on meta-learning or ensembles at first order, for usability reasons: no need to collect meta-training datasets, easy customization of learners/search spaces/metrics without re-running meta-learning, and the authors' customers preferring single learners for complexity, latency, deployment, debuggability and explainability.",
          "Section 2",
          "FLAML is designed to perform efﬁciently and robustly without relying on meta-learning or ensemble at ﬁrst order, for several usability reasons."),
         ("Step 0 (resampling): cross-validation is used if the training set has fewer than 100K instances and #instances x #features / budget is below 10M/hour, otherwise holdout; defaults are 5-fold cross-validation and a holdout ratio of 0.1. The authors note this simple rule could be replaced by more complex rules, e.g. from meta-learning.",
          "Section 4.2",
          "If the training dataset has fewer than 100K instances and # instances × # features / budget is smaller than 10M/hour, we use cross validation."),
         ("Step 1 (learner choice): each learner is sampled with probability proportional to 1/ECI rather than taking the minimum ECI, so every learner keeps a chance to be searched again and estimation errors are tolerated; ECI is updated dynamically, which the authors describe as self-correcting.",
          "Section 4.2",
          "With the concept of ECI introduced, we design a search strategy where each learner l is chosen with probability proportional to 1/ECI(l)."),
         ("Step 2 (hyperparameters and sample size): each learner starts at a small sample size (10K); if ECI1 >= ECI2 the current hyperparameters are kept and the sample size increased, otherwise randomized direct search proposes new hyperparameters at the current size. Once a learner reaches the full data size it keeps it, which the authors say reduces the risk of pruning good configurations compared to multi-fidelity pruning.",
          "Section 4.2",
          "Speciﬁcally, we begin with a small sample size (10K) for each l."),
         ("Protocol: 53 datasets (39 classification tasks from the AutoML Benchmark of Gijsbers et al. (2019) and 14 PMLB regression datasets with more than 10,000 instances), 10 OpenML folds averaged, 1 CPU core per solution on an Intel Xeon Gold 6140 server with 512GB RAM, budgets from one minute to one hour; scores are calibrated so a constant class-prior predictor is 0 and a tuned random forest is 1. Compared: auto-sklearn 0.9.0, H2O AutoML 3.30.0.3, TPOT 0.10.1, an unnamed commercial cloud-automl, and HpBandSter 0.7.4 (BOHB).",
          "Section 5",
          "We use 1 CPU core for each compared solution and vary the time budget from one minute to one hour."),
         ("Baseline configuration: all libraries use different search spaces by design except HpBandSter, which uses FLAML's search space and resampling strategy; FLAML's space neither subsumes nor is subsumed by the others', and the authors consider equalizing search spaces very challenging, if not impossible. Competitors are run with their default settings.",
          "Section 5",
          "We use their default setting and do not introduce our own bias."),
         ("Results framing and caveat: under equal budgets the authors report that FLAML clearly outperforms every competitor with large margins in most cases and underperforms by a small margin in a small fraction of cases; they add that the prior libraries are not primarily designed for the same low-resource setting.",
          "Section 5.1",
          "To be fair, the prior libraries are not primarily designed for the same low-resource setting as ours."),
     ],
     "notes": "Affiliation: Microsoft Corporation (all authors). Venue from the arXiv comment ('published in Fourth Conference on Machine Learning and Systems (MLSys 2021)'); the PDF itself only says 'Copyright 2020 by the author(s)'. Year is the first arXiv version (2019); the carded PDF is v3 (19 May 2021). Conflict of interest: the authors benchmark their own library; the randomized direct search used in Step 2 (Wu, Wang and Huang, AAAI 2021, 'Frugal optimization for cost-related hyperparameters') and the selectivity-estimation baseline/datasets (Dutt et al., co-authored by Chi Wang) are by overlapping authors; the commercial competitor is anonymized ('one major cloud provider'). The paper does not state a conflict of interest. The intro motivates the work by saying that, given one CPU hour, state-of-the-art solutions underperform a tuned random forest on 36-51% of AutoML Benchmark tasks. Ablation (roundrobin, fulldata, cv) and comparisons are figure-only (Figures 5-8) and not recorded; Table 9 percentages are not recorded. Future work (Section 6): meta-learning and ensembles in the cost-optimizing framework."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
