import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_bo_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2104.10201",
     "title": "Bayesian Optimization is Superior to Random Search for Machine Learning Hyperparameter Tuning: Analysis of the Black-Box Optimization Challenge 2020",
     "authors": ["Ryan Turner", "David Eriksson", "Michael McCourt", "Juha Kiili", "Eero Laaksonen", "Zhen Xu", "Isabelle Guyon"],
     "year": 2021, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2104.10201"},
     "tasks": ["hyperparameter-optimization"],
     "fam": ["bayesian-optimization", "gaussian-processes"], "par": ["supervised"],
     "proposes": ["Analysis of the NeurIPS 2020 black-box optimization (BBO) challenge: open-source optimizers tuned the validation-set performance of scikit-learn-style models on hidden problems (models x datasets x loss functions) with 16 batches of 8 suggestions, scored with Bayesmark's normalized score relative to random search"],
     "claims": [
         ("Problem set: optimization problems are combinations of ML models, datasets and loss functions (validation-set metrics; classification and regression use different losses, so the Cartesian product is violated slightly); keeping many datasets hidden gives test problems unknown to participants, and the search space varies by model and is provided to the optimizer by the benchmark.",
          "Section 3.2 (The Optimization Problems)",
          "The search space varied by ML model and was provided to the algorithm by the benchmark."),
         ("Budget: each problem is optimized for 16 iterations of batches of k = 8 parallel suggestions (128 function evaluations), with 640 seconds of compute for making suggestions (40 seconds per iteration); optimizers exceeding the limit were cut off and their best point so far was used. ",
          "Section 3.4 (Evaluation Environment)",
          "The optimizers had a total of 640 seconds compute time for making suggestions on each problem (16 iterations with batch size of 8); or 40 seconds per iteration."),
         ("Repetitions: the feedback leaderboard used M = 60 problems with N = 10 repeated trials, and a separate, randomly split set of M = 60 final problems used N = 30 trials; to ensure the final score was not due to chance the top-20 were re-run with N = 100.",
          "Section 3.4 (Evaluation Environment)",
          "To ensure the ﬁnal score was not due to chance, we re-ran the top-20 with N = 100 for the ﬁnal leaderboard ranking."),
         ("Scoring (Bayesmark): because raw scores are on different scales, performance on each problem is normalized so that a single random-search suggestion averages 1 and the (best known) global optimum is 0, then averaged across problems; the leaderboard score is 100 x (1 - normalized mean performance), described as ranging from 0 (on average about as good as a single random-search guess) to 100 (finds the best known optimum every time).",
          "Section 3.3 (Evaluation Metrics)",
          "First, we normalize the performance on each problem so that a single RS suggestion has an average score of 1, and the global optimum has a score of 0."),
         ("Baselines were run with default options of each package (TuRBO, pySOT, Scikit-Optimize, Ax, GPyOpt, hyperopt, Nevergrad, pycma, OpenTuner, random search). TuRBO and pySOT (SRBF), both trust-region inspired, performed best out of the box, followed by packages with traditional BO defaults, and both groups beat the three EA-based packages; the authors caution that this compares the packages' default methods rather than showing one package is better.",
          "Section 4.2 (Performance of the Baselines)",
          "Note that this comparison does not necessarily show that one package is better than another; it rather compares the performance of their default methods."),
         ("Outcome: of 65 teams on the final leaderboard, 61 beat the random-search baseline and 23 beat TuRBO, the strongest starter-kit baseline; most teams' gains persisted on the previously unseen final problems, which the authors take to mean submissions did not simply overfit the practice or feedback problems.",
          "Section 4 (Learnings and Key Results)",
          "Out of the 65 total teams whose results appeared in the ﬁnal leaderboard in Table 2, 61 beat the baseline random search and 23 beat TuRBO which was the strongest baseline provided in the starter kit."),
         ("Random-search baseline definition: random search samples uniformly in the warped space of the search configuration (e.g. log vs linear scale), so it already outperforms a naive random search that ignores the warping; nonetheless participants gained orders of magnitude greater search efficiency than random search (Table 2).",
          "Section 4.3 (Bayesian Optimization was Consistently Effective)",
          "Note also that the baseline random search samples uniformly in the warped space from the search conﬁguration."),
         ("Conclusion: the challenge is presented as demonstrating decisively the benefits of BO over random search, with top submissions showing over 100x sample-efficiency gains compared to random search (how this factor is computed is in the notes); all top teams used some form of BO ensemble.",
          "Section 6 (Conclusions)",
          "The top submissions showed over 100× sample efﬁciency gains compared to random search."),
         ("Ensembles: the second-placed submission, a simple ensemble taking 50% of suggestions each from TuRBO and Scikit-Optimize, beat both components used individually by a large margin; the per-model comparison only hints that ensembling may help avoid failures where an individual BO algorithm makes little progress.",
          "Section 4.4 (Ensemble Methods)",
          "This analysis hints that ensembling may be useful in avoiding failed models where an individual BO algorithm makes little progress."),
     ],
     "notes": "Affiliations on the PDF: Twitter, Facebook, SigOpt (an Intel company), Valohai, 4Paradigm, ChaLearn. Venue not recorded: the PDF only thanks the 'NeurIPS 2020 competition track organizers' and does not state a publication venue, and no comment/journal_ref was given. Conflict of interest: the reference list shows Turner and Eriksson among the authors of TuRBO [15] (the strongest baseline and used by 6 of the top-10 teams), Eriksson among the authors of pySOT [14], and Turner as author of Bayesmark [62], the scoring/execution package; McCourt is at SigOpt, an HPO-as-a-service company mentioned in the text. Section 4.5 says the prevalence of TuRBO 'may indicate' a non-smooth landscape favouring local models, 'Or, it may indicate' that TuRBO was simply the best baseline provided. Integer/categorical parameters could be treated as continuous; TPE was not used by any participant. A separate warm-start leaderboard (parameter names revealed; final testing otherwise used anonymized names) is in Section 4.7/Appendix A. Scope limits named in the Discussion: no multi-fidelity, synchronous batches of 8, unconstrained single-objective only. The 'RS efficiency' factor (Table 2 caption) is the number of random-search evaluations needed to reach the same mean score divided by the 128 evaluations allowed, read off a random-search curve estimated by pooling N = 256 random-search runs per problem (Figure 1 caption). Appendix B: per-problem scores are clipped at the median score of a single random-search evaluation, and the mean rather than the median is used because medians can hide a high percentage of failed runs. Submissions were evaluated only a single time on the final problems to prevent overfitting (Competition Setup). A post-hoc bootstrap (B = 10^4) over the N = 100 reruns gave 90% certainty in the final top-5 (Section 4.1). Scores in Tables 2 and 4 not recorded."},

    {"id": "arxiv-2107.05847",
     "title": "Hyperparameter Optimization: Foundations, Algorithms, Best Practices and Open Challenges",
     "authors": ["Bernd Bischl", "Martin Binder", "Michel Lang", "Tobias Pielok", "Jakob Richter", "Stefan Coors", "Janek Thomas",
                 "Theresa Ullmann", "Marc Becker", "Anne-Laure Boulesteix", "Difan Deng", "Marius Lindauer"],
     "year": 2021, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2107.05847"},
     "tasks": ["hyperparameter-optimization", "model-selection"],
     "fam": ["bayesian-optimization", "multi-fidelity-optimization", "gaussian-processes", "random-forests"], "par": ["supervised"],
     "proposes": ["A review of HPO for supervised ML (grid/random search, evolution strategies, Bayesian optimization, Hyperband, racing) with practical recommendations on resampling, nested resampling, search spaces, algorithm choice, budgets and parallelization, plus recommended search spaces for common learners (appendix)"],
     "claims": [
         ("Random vs grid search: citing Bergstra and Bengio (2012b), HPO problems often have low effective dimensionality (few HPs matter), so random search covers the influential HPs better than a grid of the same size and can easily be extended with more samples; this makes RS preferable to GS and a surprisingly strong baseline.",
          "Section 4.2.1",
          "Altogether, this makes RS preferable to GS and a surprisingly strong baseline for HPO in many practical settings."),
         ("BO surrogate costs: GP regression is used most often when the space is purely real-valued, and the choice of surrogate has great influence on BO performance. A basic GP surrogate does not support non-numeric or conditional HPs and tends to deteriorate beyond roughly ten dimensions, and standard GPs have runtime cubic in the number of samples, which can be a significant overhead for large archives.",
          "Section 4.2.3",
          "Most importantly, standard GPs have runtime complexity that is cubic in the number of samples, which can result in a signiﬁcant overhead when the archive A becomes large."),
         ("Multi-fidelity assumptions: a fidelity HP monotonically increases the cost of fitting (e.g. epochs, boosting iterations, training-data subsample fraction); the review assumes that performance changes somewhat smoothly with fidelity so that low-fidelity evaluations at least indicate the true ranking, while noting that overfitting can occur at high fidelity (e.g. many epochs).",
          "Section 4.2.4",
          "Furthermore, we assume that the relationship of the ﬁdelity to the prediction performance changes somewhat smoothly."),
         ("Overtuning: nested resampling (an outer resampling loop around the inner HPO resampling) ensures unbiased outer evaluation but does not help build a better model; after many evaluations, wrong HPCs might be selected due to stochasticity or overfitting to the inner splits. This is called overtuning, meta-overfitting or oversearching; it seems partly related to multiple hypothesis testing, has not been analysed very well, and few countermeasures are known.",
          "Section 4.4",
          "This eﬀect has been called either overtuning, meta-overﬁtting or oversearching (Ng, 1997; Quinlan & Cameron-Jones, 1995)."),
         ("Resampling in nested HPO: the outer level is regular ML evaluation, while at the inner level very accurate estimates are not needed, only a correct ranking of HPCs, so repetitions can be scaled down; it might be appropriate to use 10-fold CV outside but only 2 folds or holdout inside. Controlling inner repetitions should probably be automated by the tuner, which few current tuners do (racing being an exception).",
          "Section 6.1",
          "Hence, it might be appropriate to use a 10-fold CV on the outside to ensure proper generalization error estimation of the tuned learner, but to use only 2 folds or simple holdout on the inside."),
         ("Search-space design: encoding categorical HPs as integers is a common mistake that degrades distance-based optimizers such as BO; numeric HPs must typically be bounded to plausibly well-performing values, and HPs bounded only from below should often be tuned on a log scale with a generous upper bound, since the influence of larger values often diminishes.",
          "Section 6.2",
          "Encoding categorical values as integers is a common mistake that degrades the performance of optimizers that rely on information about distances between HPCs, such as BO."),
         ("When simple methods suffice: methods based on BO are often more sample-efficient but have more components that can fail, so when evaluations are cheap and the search space is small it may be beneficial to fall back on simple, robust approaches (RS, Hyperband, or tuners with minimal inference overhead); implementation availability and quality also matter, since porting an algorithm costs evaluations that could have been run.",
          "Section 6.3",
          "When performance evaluations are cheap and the search space is small, it may therefore be beneﬁcial to fall back on simple and robust approaches such as RS, Hyperband, or any tuner with minimal inference overhead."),
         ("Benchmark caveat: no single benchmark covers all relevant scenarios, so results only indicate performance for the selected datasets, budget, parallelization, learners and search spaces, and extensive comparison studies are missing. Citing Eggensperger et al. (2013): GP-based BO was strong for small continuous spaces with few evaluations, RF-based BO for mixed spaces with a few hundred evaluations, and evolution strategies were best for large spaces and many evaluations.",
          "Section 6.3",
          "However, no single benchmark exists which includes all relevant scenarios and whose results generalize to all possible applications."),
         ("Budget: choosing the HPO budget or when to terminate is a difficult, unsolved practical challenge; a runtime fixed in advance is what happens nearly exclusively in practice. A simple rule of thumb is to scale the number of evaluations linearly with search-space dimensionality l (50 x l or 100 x l), but it is nearly impossible to tell whether such a budget is enough.",
          "Section 6.5",
          "A simple rule-of-thumb might be scaling the budget of HPC evaluations with search space dimensionality in a linear fashion like 50 × l or 100 × l, which would also deﬁne the number of full budget units in a multi-ﬁdelity setup."),
     ],
     "notes": "Affiliations: LMU Munich, TU Dortmund, Leibniz University Hannover. No venue recorded: the PDF text does not state one and no comment/journal_ref was given (searched the dump for WIREs/accepted/submitted; WIREs appears only in a reference). Section 6 opens by stating that some recommendations are rules of thumb based solely on experience and others are at least partially confirmed by benchmarks, which are only as good as the selected datasets. Section 6.3 also states that GPs 'scale cubically with the number of dimensions', which differs from Section 4.2.3 (cubic in the number of samples); only the latter is recorded as a claim. Section 4.4 illustrates the optimistic bias of reporting the tuned resampling error with a learner that ignores the data (true error 0.5), citing Bischl et al. (2012). Section 8 (open challenges) suggests HPO tools should probably increase the number of folds as tuning runs longer, calling the schedule under-explored. Authors include developers of mlr3/mlrMBO and SMAC-related work (Lindauer, Deng), which the review lists among implementations; it does not run a new benchmark. Other Section 6 guidance not recorded as claims: Section 6.1 suggests repeated CV with many repetitions for n < 500, usually 5- or 10-fold CV for 500 <= n <= 50000, and possibly holdout beyond that; Section 6.2 warns that too-wide intervals or inadequate HPs can hurt tuning within the budget and advises tuning as few HPs as possible; Section 6.3 says GS may be useful only with up to about 2-3 HPs, BO with GPs works well for up to around 10 HPs, BO with random forests has been used with hundreds of HPs, and RS/Hyperband work well in very large spaces if the effective dimension is low. Appendix search-space tables not recorded."},

    {"id": "arxiv-2109.06716",
     "title": "HPOBench: A Collection of Reproducible Multi-Fidelity Benchmark Problems for HPO",
     "authors": ["Katharina Eggensperger", "Philipp Müller", "Neeratyoy Mallik", "Matthias Feurer", "René Sass", "Aaron Klein",
                 "Noor Awad", "Marius Lindauer", "Frank Hutter"],
     "year": 2021, "venue": "NeurIPS 2021 Datasets and Benchmarks Track", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2109.06716", "code": "https://github.com/automl/HPOBench"},
     "tasks": ["hyperparameter-optimization", "neural-architecture-search", "tabular-classification"],
     "fam": ["bayesian-optimization", "multi-fidelity-optimization", "gaussian-processes", "random-forests"], "par": ["supervised"],
     "proposes": ["HPOBench: 12 benchmark families (7 existing, 5 new) with more than 100 multi-fidelity HPO problems under one API, each packaged in a Singularity container, with raw, tabular and surrogate versions for cheap evaluation"],
     "claims": [
         ("Motivation: prior HPO method papers often relied on artificial test functions and low-dimensional toy problems, sometimes introduced their own problems, ran on different environments with different requirements and interfaces, and often did not open-source code, making methods hard to compare.",
          "Introduction",
          "All of these make it difﬁcult to compare and develop methods, necessitating an evolving set of relevant and up-to-date benchmark problems which drives continued and quantiﬁable progress in the community."),
         ("Surrogate benchmarks (an ML model trained on recorded evaluations predicts function values in the original, non-discretized space) are similarly cheap to query as tabular lookup benchmarks but add complexity, and their quality crucially depends on the surrogate model and its training data; because they are a drop-in replacement for raw benchmarks they are widely adopted.",
          "Section 4.2",
          "While surrogate benchmarks are similarly cheap to query, the surrogate’s internal ML model adds extra complexity and the benchmark’s quality crucially depends on the quality of this model and its training data."),
         ("Reproducibility scope: each benchmark is packaged with its dependencies in a container so that it can be used without reinstalling dependencies, but this does not immediately make optimization results replicable; users still need enough seed replicates and must account for hardware differences when comparing optimizer overhead.",
          "Section 4.3",
          "This does not immediately lead to replicability on the level of the optimization results."),
         ("New benchmark families (SVM, LogReg, XGBoost, RandomForest, MLP; scikit-learn and XGBoost) use 20 OpenML AutoML-benchmark datasets (8 for MLP); 33% of each fixed OpenML training split is held out (stratified, fixed seed) as validation, the model is trained on the remaining 67%, and fidelities are trees, iterations, epochs or data subsets (SVM). Tabular versions discretize each HP and fidelity and record 5 seeds per grid configuration.",
          "Section 4.4.2",
          "We give the OpenML [75] task IDs in Table 7 in Appendix D, which provide ﬁxed train-test splits; for each such task, we used 33% of the training set as the validation split, determined through stratiﬁed sampling under a ﬁxed seed."),
         ("Experimental protocol: 13 optimizers on the 12 families, 32 seeds per benchmark and optimizer, minimizing 1 - accuracy on the new benchmarks (using their tabular versions); budgets as in Table 1, counting benchmark time (recorded, predicted or wall-clock) plus optimizer wall-clock time. Results are aggregated as final performance, performance over time or rank over time; for tabular and surrogate benchmarks the optimization regret to the best-known value is reported (footnote 4: validation performance, the objective seen by the optimizer).",
          "Section 5.1",
          "For each benchmark and optimizer, we conducted 32 repetitions with different seeds to avoid reliance on individual seeds [65]."),
         ("Optimizer configuration: all tools and implementations of the compared optimizers (RS, DE, BO with GP, RF and KDE models, HEBO; HB, BOHB, SMAC-HB, DEHB, Dragonfly, Optuna) were run with their default settings.",
          "Appendix G",
          "We note that we used the default settings for all tools and implementations."),
         ("RQ1 (advanced methods vs random search): counting wins/ties/losses with a sign test on the existing community benchmarks (new benchmarks reported as similar in Appendix H), four of five black-box methods are significantly better than RS, but only two of four multi-fidelity methods are significantly better than HB and one is consistently worse than HB; the authors conclude that advanced methods consistently outperform random search.",
          "Section 5.3",
          "We can observe that four out of ﬁve black-box methods are signiﬁcantly better than RS."),
         ("RQ2 (multi-fidelity vs black-box at a fixed time budget): multi-fidelity optimizers outperform black-box optimizers for relatively small budgets, and with enough budget black-box optimizers become competitive (DE and BORF did very well in the end). On the community benchmarks the catch-up, if any, happens only after a very substantial (simulated) wall-clock time, so the authors consider multi-fidelity methods crucial for real, expensive problems.",
          "Section 5.4",
          "Overall, multi-ﬁdelity optimizers outperform black-box optimizers for relatively small compute budgets."),
         ("Caveats: multi-fidelity methods are clearly beneficial in general when low fidelities are available and representative of the true objective; DEHB and SMAC-HB were reliable across the collection while other multi-fidelity optimizers did not consistently improve over HB, black-box methods can beat multi-fidelity methods at very high budgets, and even advanced methods can be beaten by RS on individual benchmarks.",
          "Section 5.4",
          "By exploring a very broad range of benchmarks, we also found an existence proof that black-box methods can outperform multi-ﬁdelity methods for very high budgets and that even advanced methods can be outperformed by RS in individual benchmarks."),
     ],
     "notes": "Affiliations: University of Freiburg, Leibniz University Hannover, Amazon, Bosch Center for AI. Venue from the PDF first-page footer ('35th Conference on Neural Information Processing Systems (NeurIPS 2021) Track on Datasets and Benchmarks') and the arXiv comment. Conflict of interest: the authors' group (Hutter, Lindauer, Eggensperger, Feurer, Awad, Mallik, Klein) developed several compared optimizers per the reference list — BOHB [22] (Falkner, Klein, Hutter), DEHB [5] (Awad, Mallik, Hutter), SMAC3/SMAC-HB [78] (Lindauer, Eggensperger, Feurer, Sass, Hutter et al.) and the existing BNN/Cartpole/Net benchmarks from [22]; the paper does not state this as a conflict. The paper says DEHB and SMAC-HB were reliable. Dragonfly's poor ranks are attributed to its overhead (footnote), and Optuna runs are penalized because HPOBench is stateless (no freeze-thaw). Section 5.2 says the optimizer selection does not aim at finding the best algorithm but at covering a broad range of implementations and tools. Section 5.3 (Figure 4) also reports that BO improves over DE early but, except HEBO, loses to it in the very long run on the community benchmarks, and that HEBO substantially improved over the other black-box methods. Section 5.4 notes that at the full budget no advanced multi-fidelity method is statistically better than its black-box counterpart. Table 2/3 p-values and win/tie/loss counts not recorded."},

    {"id": "arxiv-1902.07638",
     "title": "Random Search and Reproducibility for Neural Architecture Search",
     "authors": ["Liam Li", "Ameet Talwalkar"],
     "year": 2019, "venue": "UAI 2019", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1902.07638", "code": "https://github.com/liamcli/randomNAS_release"},
     "tasks": ["neural-architecture-search", "hyperparameter-optimization", "image-classification"],
     "fam": ["deep-learning", "multi-fidelity-optimization"], "par": ["supervised"],
     "proposes": ["Random search with early-stopping (ASHA) as a NAS baseline at a compute budget comparable to DARTS",
                  "Random search with weight-sharing: shared weights trained with one uniformly sampled architecture per minibatch, then many random architectures ranked with the shared weights on held-out data"],
     "claims": [
         ("Exact reproducibility (reproducing reported results) requires search code, evaluation code, hyperparameter-tuning documentation and random seeds; of 12 NAS papers at NeurIPS, ICML and ICLR since 2018, none is exactly reproducible, each missing some combination of these. Broad reproducibility (robustness of results) is hard to measure because of compute cost and the high variance of extremal statistics.",
          "Introduction",
          "For example, of the 12 papers published since 2018 at NeurIPS, ICML, and ICLR that introduce novel NAS methods (see Table 1), none are exactly reproducible."),
         ("Weak published baselines: some NAS works compare to random search with only a few evaluations or to BO without efficient evaluation schemes, while others compare to random search with full training even though partial-training methods have been shown to be orders of magnitude faster.",
          "Section 2.1 (Inadequate Baselines)",
          "Some works either compare to random search given a budget of just of few evaluations [34, 41] or Bayesian optimization methods without efficient architecture evaluation schemes [23]."),
         ("ASHA protocol: architectures are searched by partial training of the stage-2 evaluation network, starting at 1 epoch up to 300 epochs, promoting the top 1/4 with 4x more resource each round. The architecture found is then evaluated in stage (3).",
          "Section 4 (Experiments)",
          "For both benchmarks, we run ASHA with a starting resource per architecture of r = 1 epoch, a maximum resource of 300 epochs, and a promotion rate of η = 4, indicating the top 1/4 of architectures will be promoted in each round and trained for 4× more resource."),
         ("Hedged finding: with roughly the same compute as DARTS, random search with early-stopping is a much more competitive baseline on PTB and CIFAR-10 than the published random-search baselines; DARTS still outperforms it, but the gap is not nearly as large as previously suggested.",
          "Introduction",
          "While SOTA NAS methods like DARTS still outperform this baseline, our results demonstrate that the gap is not nearly as large as that suggested by published random search baselines on these tasks [34, 41]."),
         ("Tuning asymmetry: the authors lightly tuned the meta-hyperparameters of random search with weight-sharing starting from DARTS' settings, and it is unclear whether DARTS' settings required considerable tuning; ASHA reached nearly competitive performance with its default settings at roughly the same total computation.",
          "Section 4.3 (Computational Cost)",
          "In contrast, we were able to achieve nearly competitive performance with the default settings of ASHA using roughly the same total computation as that needed by DARTS and random search with weight-sharing."),
         ("No extra tuning of final architectures: besides high variance across trials and differing convergence rates, a third potential source of variation, which could adversely affect the weight-sharing results, is that no additional hyperparameter tuning was done in stage (3); the training hyperparameters tuned by Liu et al. for DARTS' final architecture were reused.",
          "Section 4.1.3",
          "we did not perform any additional hyperparameter tuning in stage (3); instead we used the same training hyperparameters that were tuned by Liu et al. [34] for the final architecture found by DARTS."),
         ("Broad reproducibility: on CIFAR-10, 2 of 5 additional independent runs of random search with weight-sharing matched the first run, while 3 underperformed (still better than ASHA); together with unstable rankings of DARTS architectures between 100 and 600 training epochs, this shows high variance between runs and the risk of noisy performance signals.",
          "Section 4.2.3",
          "These broad reproducibility results show that random search with weight-sharing has high variance between runs, which is not surprising given the change in intermediate rankings that we observed for DARTS."),
         ("Data used for selection: the CIFAR-10 meta-hyperparameter section states that in stage (1) the trained shared weights are used to evaluate randomly sampled architectures on the test set, and stage (2) then retrains the best one per trial from scratch for 600 epochs (Appendix A.2 instead describes the stage (1) evaluation on the validation set; see notes).",
          "Section 4.2.2",
          "In stage (1), we train the shared weights and use them to evaluate a given number of randomly sampled architectures on the test set."),
         ("Reproducibility recommendation: in traditional HPO results are standardly reported over 10 independent runs, whereas NAS results are often from a single run without exact reproducibility, a consequence of steep cost (this paper's experiments took several months of wall-clock time and tens of thousands of dollars); because extremal statistics are reported, results need several independent runs, so more compute or more tractable benchmarks are needed, and robustness across runs should be evaluated alongside accuracy.",
          "Section 5 (Conclusion)",
          "Consequently, we conclude that either significantly more computational resources need to be devoted to evaluating NAS methods and/or more computationally tractable benchmarks need to be developed to lower the barrier for performing adequate empirical evaluations."),
     ],
     "notes": "Affiliations: Carnegie Mellon University; Talwalkar also Determined AI. Venue from the arXiv journal_ref (Conference on Uncertainty in Artificial Intelligence, UAI 2019); the PDF text itself does not state it. Conflict of interest: ASHA [30] ('Massively parallel hyperparameter tuning') is by L. Li, ..., A. Talwalkar, i.e. the authors' own method, used as the HPO baseline; Hyperband/successive halving [29] is also from overlapping authors. ASHA runs used non-deterministic code and asynchronous updates, so ASHA results are not exactly reproducible (Appendix A.2). GPU time on V100 converted to P100 with a factor of 1.5. On PTB, ENAS's published result could not be reproduced with the released code. Search spaces follow DARTS; the zero operation was excluded on PTB but included on CIFAR-10. Budgets: ASHA used 2 GPU days on PTB (equal to DARTS second-order total cost) and 9 GPU days on CIFAR-10 (vs 10 GPU days for the authors' DARTS run), evaluating over 300 and over 700 architectures, versus 1 architecture for ENAS's and 8 (PTB) / 24 (CIFAR-10) for DARTS's published random-search baselines (Sections 4.1, 4.2). Doubt: Section 4.2.2 says stage (1) evaluates sampled architectures 'on the test set', whereas Appendix A.2 says each architecture is evaluated on 10 minibatches and the best 10 per 1000 on the full validation set; Table 7 ranks DARTS trials by test error after 100/600 epochs. The text does not reconcile these, so whether test data influenced selection is unclear. Perplexity/error tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
