import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_ssl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-2006.07733",
     "title": "Bootstrap your own latent: A new approach to self-supervised Learning",
     "authors": ["Jean-Bastien Grill", "Florian Strub", "Florent Altché", "Corentin Tallec", "Pierre H. Richemond",
                 "Elena Buchatskaya", "Carl Doersch", "Bernardo Avila Pires", "Zhaohan Daniel Guo",
                 "Mohammad Gheshlaghi Azar", "Bilal Piot", "Koray Kavukcuoglu", "Rémi Munos", "Michal Valko"],
     "year": 2020, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2006.07733", "code": "https://github.com/deepmind/deepmind-research/tree/master/byol"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["BYOL: an online network (encoder, projector, predictor) is trained to predict the projection of a different augmented view produced by a target network whose weights are an exponential moving average of the online weights, with a stop-gradient on the target and no negative pairs"],
     "claims": [
         ("The BYOL objective admits collapsed solutions (e.g. the same output for every image); the authors show empirically that BYOL does not converge to them and hypothesize that the combination of the predictor and the slow-moving-average target network avoids collapse.",
          "Introduction",
          "While this objective admits collapsed solutions, e.g., outputting the same vector for all images, we empirically show that BYOL does not converge to such solutions."),
         ("Status of the explanation: BYOL's dynamics still admit undesirable equilibria; the authors did not observe convergence to them, and their argument that collapsed equilibria are unstable assumes an optimal predictor (and, for simplicity, no normalization or symmetrization).",
          "Section 3.2",
          "While BYOL’s dynamics still admit undesirable equilibria, we did not observe convergence to such equilibria in our experiments."),
         ("Hypothesis on the role of the moving-average target: to keep the predictor near-optimal during training; the authors say Section 5 and Appendix I give some empirical support for this interpretation.",
          "Section 3.2",
          "We hypothesize that the main role of BYOL’s moving-averaged target network is to ensure the near-optimality of the predictor over training; Section 5 and Appendix I provide some empirical support of this interpretation."),
         ("Ablation of the target decay rate (300-epoch runs, linear evaluation): updating the target instantaneously (tau = 0) destabilizes training, while never updating it (tau = 1) is stable but gives a low-quality representation; a trade-off exists between the two.",
          "Section 5 (Bootstrapping)",
          "Instantaneously updating the target network (τ = 0) destabilizes training, yielding very poor performance while never updating the target (τ = 1) makes the training stable but prevents iterative improvement, ending with low-quality ﬁnal representation."),
         ("Ablation between BYOL and SimCLR (Table 5b): without negative examples (beta = 0) the only variant that performs well is BYOL with both a target network and a predictor; adding negatives to BYOL without re-tuning the temperature hurts it.",
          "Section 5 (Ablation to contrastive methods)",
          "The only variant that performs well without negative examples (i.e., with β = 0) is BYOL, using both a bootstrap target network and a predictor."),
         ("Without a target network, collapse could be avoided by making the predictor near-optimal (an optimal linear predictor fitted on the batch, or a higher predictor learning rate); the authors say this seems to indicate that keeping the predictor near-optimal is important to prevent collapse, which may be one role of the target network.",
          "Section 5 (Importance of a near-optimal predictor)",
          "This seems to indicate that keeping the predictor near-optimal at all times is important to preventing collapse, which may be one of the roles of BYOL’s target network."),
         ("Batch size (Figure 3a, 128 to 4096, 300 epochs): BYOL stays stable from 256 to 4096 and drops only for smaller values, which the authors attribute to batch normalization. To avoid re-tuning, smaller batches were emulated by averaging gradients over N steps, so only the batch-normalization statistics see the smaller batch.",
          "Section 5 (Batch size)",
          "In contrast, the performance of BYOL remains stable over a wide range of batch sizes from 256 to 4096, and only drops for smaller values due to batch normalization layers in the encoder."),
         ("Linear evaluation protocol on ImageNet: linear classifier on the frozen representation (no update of weights or batch statistics), SGD with Nesterov momentum for 80 epochs without regularization; the learning rate is chosen from 5 values on a local validation set of 10009 images held out from the ImageNet train set, and accuracy is reported on the public ILSVRC2012 validation set as test set.",
          "Appendix C.1",
          "We ﬁnally sweep over 5 learning rates {0.4, 0.3, 0.2, 0.1, 0.05} on a local validation set (10009 images from ImageNet train set), and report the accuracy of the best validation hyperparameter on the test set"),
         ("Stated limitation: BYOL depends on augmentation sets specific to vision; other modalities would need similarly suitable augmentations, whose design may require significant effort and expertise.",
          "Conclusion",
          "Nevertheless, BYOL remains dependent on existing sets of augmentations that are speciﬁc to vision applications."),
     ],
     "notes": "Affiliations: DeepMind and Imperial College. No venue recorded: the arXiv record has no comment/journal_ref and the v3 PDF has no conference header or footer. Pre-training: ResNet-50 for 1000 epochs, batch 4096 on 512 TPU v3 cores (about 8 hours); ablations at 300 epochs, 3 seeds. Augmentations are the SimCLR set plus solarization. Section 5 also states that removing the predictor gives an unsupervised Mean-Teacher-like variant that collapses, and that removing weight decay makes BYOL or SimCLR diverge. The 9th claim (augmentation limitation) was kept as a key caveat. Results tables not recorded."},

    {"id": "arxiv-2011.10566",
     "title": "Exploring Simple Siamese Representation Learning",
     "authors": ["Xinlei Chen", "Kaiming He"],
     "year": 2020, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2011.10566"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["SimSiam: a weight-shared Siamese network (backbone + projection MLP) with a prediction MLP on one branch and a stop-gradient on the other, trained with a symmetrized negative cosine similarity; no negative pairs, no momentum encoder, no large batches"],
     "claims": [
         ("Main finding: collapsing solutions exist for the SimSiam loss and architecture, but a stop-gradient operation plays an essential role in preventing collapse.",
          "Abstract",
          "Our experiments show that collapsing solutions do exist for the loss and structure, but a stop-gradient operation plays an essential role in preventing collapsing."),
         ("Removing only the stop-gradient (architecture and hyperparameters unchanged) gives chance-level linear accuracy; collapse is diagnosed by the loss reaching its minimum of -1 and by the per-channel std of the l2-normalized output going to zero. The authors note in a footnote that chance-level accuracy alone does not indicate collapse, since a diverging loss can also give it.",
          "Section 4.1",
          "Solely removing stop-gradient, the accuracy becomes 0.1%, which is the chance-level guess in ImageNet."),
         ("The predictor is needed: removing it (identity mapping) collapses, which is expected for the symmetrized loss; the asymmetric loss also fails without it; a predictor fixed at random initialization fails without collapsing (training does not converge).",
          "Section 4.2",
          "The model does not work if removing h (Table 1a), i.e., h is the identity mapping."),
         ("Batch size (64 to 4096, plain SGD, 100-epoch pre-training): SimSiam works reasonably well over the whole range, unlike SimCLR and SwAV which the authors say need large batches; the result is lower with 4096, which they attribute to SGD with very large batches.",
          "Section 4.3",
          "Our method works reasonably well over this wide range of batch sizes."),
         ("Batch size, batch normalization, similarity function and symmetrization may affect accuracy, but the authors saw no evidence that they are related to collapse prevention; it is mainly the stop-gradient.",
          "Section 4.7",
          "The optimizer (batch size), batch normalization, similarity function, and symmetrization may affect accuracy, but we have seen no evidence that they are related to collapse prevention."),
         ("On BYOL's momentum encoder: the authors argue that the importance of stop-gradient can be obscured by a momentum encoder (always accompanied by stop-gradient), and that moving averaging may improve accuracy but is not directly related to preventing collapse.",
          "Related Work (BYOL)",
          "While the moving-average behavior may improve accuracy with an appropriate momentum coefﬁcient, our experiments show that it is not directly related to preventing collapsing."),
         ("Hypothesis, not proof: SimSiam is hypothesized to be an EM-like alternating optimization over network weights and per-image representations (Section 5); the authors state that this hypothesis is about what the optimization problem can be, that it does not explain why collapse is prevented, and that non-collapse remains an empirical observation.",
          "Section 5.3",
          "We point out that SimSiam and its variants’ non-collapsing behavior still remains as an empirical observation."),
         ("Comparisons on ImageNet linear evaluation use the authors' own reproductions of all competitors (some improved over the original papers), each with its original hyperparameter and augmentation recipe, ResNet-50 and two 224x224 views.",
          "Section 6.1",
          "For fair comparisons, all competitors are based on our reproduction, and “+” denotes improved reproduction vs. the original papers (see supplement)."),
     ],
     "notes": "Affiliation: Facebook AI Research (FAIR). arXiv comment 'Technical report'; no venue recorded. Linear evaluation (supplement): linear classifier on frozen pool5 features, LARS, 90 epochs, batch 4096, evaluated on the center crop of the ImageNet validation set; no separate held-out split for probe hyperparameters was found in the text (searched for validation, held-out). Disclosure: Kaiming He is an author of MoCo/MoCo v2, which are among the reproduced baselines. The paper footnote notes that BYOL's arXiv v3 reports 66.9% without a momentum encoder when the predictor learning rate is increased, concurrently with this work. Results tables not recorded."},

    {"id": "arxiv-2006.09882",
     "title": "Unsupervised Learning of Visual Features by Contrasting Cluster Assignments",
     "authors": ["Mathilde Caron", "Ishan Misra", "Julien Mairal", "Priya Goyal", "Piotr Bojanowski", "Armand Joulin"],
     "year": 2020, "venue": "NeurIPS 2020", "version": "arXiv v5",
     "links": {"arxiv": "https://arxiv.org/abs/2006.09882", "code": "https://github.com/facebookresearch/swav"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["SwAV: online clustering in which codes (soft assignments of features to trainable prototypes) are computed per batch with the Sinkhorn-Knopp algorithm under an equipartition constraint, and the code of one view is predicted from the feature of another view (swapped prediction)",
                  "Multi-crop: two standard-resolution crops plus several low-resolution crops per image, with codes computed only from the full-resolution crops"],
     "claims": [
         ("Collapse prevention: codes are computed so that the examples in a batch are equally partitioned among the prototypes; this equipartition constraint keeps codes of different images distinct and prevents the trivial solution where every image has the same code.",
          "Method (Computing codes online)",
          "This equipartition constraint ensures that the codes for different images in a batch are distinct, thus preventing the trivial solution where every image has the same code."),
         ("A strong entropy regularization (high epsilon) generally leads to a trivial solution where all samples collapse to a single representation and are assigned uniformly to all prototypes, so epsilon is kept low.",
          "Method (Computing codes online)",
          "We observe that a strong entropy regularization (i.e. using a high ε) generally leads to a trivial solution where all samples collapse into an unique representation and are all assigned uniformely to all prototypes."),
         ("Small batches: when the batch is too small compared with the number of prototypes, an equal partition is impossible, so features from previous batches are stored to augment the assignment problem (around 3K features, i.e. the last 15 batches of 256, versus the 65K instances the authors say contrastive methods typically store).",
          "Method (Working with small batches)",
          "Therefore, when working with small batches, we use features from the previous batches to augment the size of Z in Prob. (3)."),
         ("Batch size caveat: the headline ImageNet linear result is from 800 epochs with batches of 4096; results with shorter training and small batches are given separately (Fig. 3, Table 3).",
          "Main Results",
          "Note that we train SwAV during 800 epochs with large batches (4096)."),
         ("Cost in the small-batch setting (batch 256): SwAV with multi-crop runs 1.2x slower per epoch than SimCLR and about 1.4x slower than MoCov2; one epoch of MoCov2 or SimCLR is faster, but the authors say these methods need more epochs for good downstream performance.",
          "Training with small batches",
          "Hence, one epoch of MoCov2 or SimCLR is faster in wall clock time than one of SwAV, but these methods need more epochs for good downstream performance."),
         ("Sinkhorn iterations ablation: 3 iterations suffice for convergence; with fewer iterations the loss fails to converge, and more iterations slightly alter transfer performance (conjectured to be due to converging too rapidly, as with discrete codes).",
          "Appendix C.4",
          "When performing less iterations, the loss fails to converge."),
         ("Prototypes: learning them improves over fixed random prototypes only modestly; the authors say the prototypes are not strongly encouraged to be categorical, and that they help contrast views without pairwise comparisons with many negatives.",
          "Appendix (Learning the prototypes)",
          "Indeed, the prototypes in SwAV are not strongly encouraged to be categorical and random ﬁxed prototypes work almost as well."),
         ("Multi-crop improves several self-supervised methods (SimCLR, SeLa-v2, DeepCluster-v2, SwAV) in the authors' re-implementations with matched augmentation, epochs and batch size, and seems to benefit clustering-based methods more than contrastive ones; it does not improve the supervised model.",
          "Ablation Study (Applying the multi-crop strategy to different methods)",
          "Interestingly, multi-crop seems to beneﬁt more clustering-based methods than contrastive methods."),
     ],
     "notes": "Affiliations: Inria and Facebook AI Research. Venue from the PDF footer ('34th Conference on Neural Information Processing Systems (NeurIPS 2020)') and the arXiv comment. Linear evaluation (Appendix A.3): linear classifier on frozen 2048-d ResNet-50 features, 100 epochs, lr 0.3, cosine decay, batch 256, RandomResizedCrop and flips; no held-out split for probe hyperparameters was found in the text (searched for validation, held-out). Prototypes are frozen during the first epoch 'to help the very beginning of the optimization' (Appendix). Disclosure: Caron, Bojanowski and Joulin are authors of DeepCluster, which is re-implemented here as DeepCluster-v2. Results tables not recorded."},

    {"id": "arxiv-2103.03230",
     "title": "Barlow Twins: Self-Supervised Learning via Redundancy Reduction",
     "authors": ["Jure Zbontar", "Li Jing", "Ishan Misra", "Yann LeCun", "Stéphane Deny"],
     "year": 2021, "venue": "ICML 2021", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2103.03230", "code": "https://github.com/facebookresearch/barlowtwins"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["Barlow Twins: a loss that pushes the cross-correlation matrix (computed along the batch) between the embeddings of two distorted views towards the identity: an invariance term on the diagonal and a redundancy-reduction term on the off-diagonal, weighted by lambda"],
     "claims": [
         ("Claim of the method: Barlow Twins needs neither large batches nor asymmetry between the twins (predictor, stop-gradient, moving-average weights), and benefits from very high-dimensional output vectors.",
          "Abstract",
          "BARLOW TWINS does not require large batches nor asymmetry between the network twins such as a predictor network, gradient stopping, or a moving average on the weight updates."),
         ("Loss ablation (300-epoch runs; Table 5 caption, with the body text saying the same): removing either the invariance (on-diagonal) term or the redundancy-reduction (off-diagonal) term gives worse or collapsed solutions.",
          "Table 5",
          "We ablate the invariance and redundancy terms in our proposed loss and observe that both terms are necessary for good performance."),
         ("Batch size: with a LARS learning-rate grid search per batch size, performance is almost unaffected down to batch 256, unlike SimCLR. The BYOL and SimCLR curves in Figure 2 are taken from their papers, not re-run.",
          "Section 4 (Robustness to Batch Size)",
          "We ﬁnd that, unlike SIMCLR, our model is robust to small batch sizes (Fig. 2), with a performance almost unaffected for a batch as small as 256."),
         ("Augmentations: Barlow Twins is not robust to removing some augmentations, like SimCLR and unlike BYOL; the authors present this as a possible disadvantage, or as the representation being better controlled by the chosen distortions.",
          "Section 4 (Effect of Removing Augmentations)",
          "We ﬁnd that our model is not robust to removing some types of data augmentations, like SIMCLR but unlike BYOL (Fig. 3)."),
         ("Projector dimensionality: performance keeps improving with all output dimensionalities tested, while other methods saturate (data for SimCLR and BYOL taken from their papers), even though the 2048-d ResNet output is a bottleneck.",
          "Section 4 (Projector Network Depth & Width)",
          "Other methods rapidly saturate when the dimensionality of the output increases, but our method keeps improving with all output dimensionality tested (Fig. 4)."),
         ("Adding BYOL/SimSiam-style asymmetry (a predictor and/or a stop-gradient) slightly decreases Barlow Twins' performance.",
          "Section 4 (Breaking Symmetry)",
          "We ﬁnd that these asymmetries slightly decrease the performance of our network (see Table 6)."),
         ("The authors argue that asymmetric methods (BYOL, SimSiam) cannot be described as optimizing an overall objective, since trivial solutions exist that they avoid through implementation choices or learning dynamics, whereas Barlow Twins avoids them by construction.",
          "Section 5.1 (Asymmetric Twins)",
          "It should be noted however that these asymmetric methods cannot be described as the optimization of an overall learning objective."),
         ("Theory caveat: the information-bottleneck interpretation assumes Gaussian representations, and the actual loss is linked to it only through listed simplifications and approximations (e.g. replacing the log-determinant by a decorrelation proxy, cross- instead of auto-correlation).",
          "Appendix A",
          "In order to circumvent this difﬁculty, we make the simplifying assumption that the representation Z is distributed as a Gaussian."),
     ],
     "notes": "Affiliations: Facebook AI Research and New York University. Venue from the PDF footer ('Proceedings of the 38th International Conference on Machine Learning, PMLR 139, 2021') and the arXiv comment. Pre-training: ResNet-50, 1000 epochs, batch 2048, LARS, 8192-d 3-layer projector, BYOL augmentations; 32 V100 GPUs for about 124 hours. lambda = 5e-3 was found by a search; the data used for that search was not found in the text (searched for search, validation, tuned). Linear evaluation (Appendix B.1): 100 epochs, SGD, lr 0.3, batch 256; results reported on the ImageNet validation set. Results tables not recorded."},

    {"id": "arxiv-2105.04906",
     "title": "VICReg: Variance-Invariance-Covariance Regularization for Self-Supervised Learning",
     "authors": ["Adrien Bardes", "Jean Ponce", "Yann LeCun"],
     "year": 2021, "venue": "ICLR 2022", "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2105.04906"},
     "tasks": ["representation-learning", "image-classification"],
     "fam": ["joint-embedding"], "par": ["self-supervised"],
     "proposes": ["VICReg: a joint-embedding loss with an invariance term (mean squared distance between embeddings), a variance term (hinge on the per-dimension standard deviation over the batch) and a covariance term (squared off-diagonal covariances), with variance and covariance applied to each branch separately"],
     "claims": [
         ("Claim of the method: the variance and covariance terms explicitly avoid collapse, so VICReg does not require weight sharing, batch or feature-wise normalization, quantization, stop-gradient or memory banks.",
          "Abstract",
          "Unlike most other approaches to the same problem, VICReg does not require techniques such as: weight sharing between the branches, batch normalization, feature-wise normalization, output quantization, stop gradient, memory banks, etc."),
         ("Using the standard deviation rather than the variance in the hinge is crucial: with the variance, the gradient vanishes near the mean and the embeddings collapse.",
          "Method",
          "Using the standard deviation and not directly the variance is crucial."),
         ("Coefficient ablation: without the variance term the representations immediately collapse to a single vector, and the covariance term, which has no repulsive effect, has no impact; the invariance term is necessary; variance and covariance are complementary.",
          "Appendix D.4",
          "Without variance regularization the representations immediately collapse to a single vector and the covariance term, which has no repulsive effect preventing collapse, has no impact."),
         ("Combining components (Table 4, 100 epochs): with variance regularization, adding a predictor makes no significant difference (redundant); without it, the representations collapse and both stop-gradient and predictor are necessary.",
          "Analysis (Asymmetric networks)",
          "In comparison, without VR, the representations collapse, and both stop-gradient (SG) and PR are necessary."),
         ("Adding variance regularization to stop-gradient or momentum-encoder setups gives small gains, which the authors suggest might be because those tricks do not perfectly maintain the variance, i.e. very slow collapse is happening.",
          "Analysis (Asymmetric networks)",
          "which might be explained by the fact that these architectural tricks that prevent collapse are not perfectly maintaining the variance of the representations, i.e. very slow collapse is happening with these methods."),
         ("Batch size (128 to 4096, base learning rate grid-searched per size): small drops at 256 and 128, which the authors call comparable to the batch-size robustness of Barlow Twins and SimSiam.",
          "Appendix D.7",
          "We observe a 0.7% and 1.2% drop in accuracy with small batch size of 256 and 128 which is comparable with the robustness to batch size of Barlow Twins Zbontar et al. (2021) and SimSiam Chen & He (2020)"),
         ("Selection of the loss coefficients: the final values were the ones that worked best (by a small margin) on ImageNet; the authors add that they could have tuned them by cross-validation on validation sets of smaller datasets (MNIST, CIFAR), where the same values also worked well.",
          "Appendix D.4",
          "that setting lambda = mu = 25 and nu = 1 works best (by a small margin) for Imagenet"),
         ("Non-shared weights: going from shared to different weights, performance drops by 2.1% for VICReg and 4.5% for Barlow Twins; the authors conclude VICReg is more robust in these scenarios.",
          "Analysis (Weight sharing)",
          "The performance drops by 2.1% with VICReg and 4.5% with Barlow Twins, between the shared weights scenario (SW) and the different weight scenario (DW)."),
     ],
     "notes": "Affiliations: Facebook AI Research; Inria/ENS; NYU. Venue from the PDF header ('Published as a conference paper at ICLR 2022') and the arXiv comment. Although the abstract says batch normalization is not required, the default expander uses BN in its hidden layers (Implementation details), and Appendix D.5 reports a drop when it is removed. Linear evaluation (Appendix C.2): SGD, lr 0.02, 100 epochs, batch 256, reported on the ImageNet validation set. Main ImageNet results are means over 3 runs; semi-supervised and later sections are single runs. Disclosure: Yann LeCun is a co-author of Barlow Twins, the main comparison method; BYOL and SimSiam in Table 4 are the authors' own re-implementations. Results tables not recorded."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
