import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_automl_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1611.01578",
     "title": "Neural Architecture Search with Reinforcement Learning",
     "authors": ["Barret Zoph", "Quoc V. Le"],
     "year": 2016, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1611.01578"},
     "tasks": ["neural-architecture-search", "image-classification", "language-modeling"],
     "fam": ["deep-learning"], "par": ["reinforcement-learning"],
     "proposes": ["Neural Architecture Search: an autoregressive RNN controller emits the architectural hyperparameters of a child network as a variable-length token sequence; the child is trained and its held-out validation accuracy is used as the reward to update the controller with REINFORCE (exponential-moving-average baseline)",
                  "Extensions of the controller: set-selection attention (anchor points with sigmoids) to propose skip connections, and a tree-structured search space for recurrent cells (combination method and activation per node, plus cell-memory connections)",
                  "Distributed asynchronous training with a parameter server, K controller replicas and m child models trained in parallel per replica"],
     "claims": [
         ("Method: a recurrent controller generates a string describing a child network; the child is trained on the real data, its validation-set accuracy is used as the reward, and the policy gradient of this reward updates the controller so that it assigns higher probability to architectures that receive high accuracies.",
          "Introduction",
          "Using this accuracy as the reward signal, we can compute the policy gradient to update the controller."),
         ("Training: because the reward R (validation accuracy of the trained child) is non-differentiable, the controller parameters are updated with the REINFORCE rule (citing Williams, 1992), averaged over m sampled architectures per batch; to reduce the high variance of this unbiased estimate, a baseline is subtracted, which is an exponential moving average of the previous architecture accuracies.",
          "Section 3.2",
          "In this work, our baseline b is an exponential moving average of the previous architecture accuracies."),
         ("Motivation relative to hyperparameter optimization (citing Bergstra et al., Snoek et al. and others): these methods only search fixed-length spaces, making it difficult to generate a variable-length configuration specifying network structure and connectivity, and in practice they often work better when supplied with a good initial model; Bayesian optimization methods that search non-fixed-length architectures exist but are described as less general and less flexible than the proposed method.",
          "Related Work",
          "Despite their success, these methods are still limited in that they only search models from a ﬁxed-length space."),
         ("Compute for the CIFAR-10 search: parameter-server shards S = 20, controller replicas K = 100 and child replicas m = 8, so 800 networks are trained on 800 GPUs concurrently at any time; each sampled child is trained for 50 epochs and the reward is the maximum validation accuracy of the last 5 epochs cubed, with 5,000 training examples held out as the validation set.",
          "Section 4.1",
          "which means there are 800 networks being trained on 800 GPUs concurrently at any time."),
         ("Selection protocol on CIFAR-10: after the controller trains 12,800 architectures, the architecture with the best validation accuracy is taken, a small grid search over learning rate, weight decay, batchnorm epsilon and the learning-rate decay epoch is run, and the best model from this grid search is run until convergence before computing test accuracy; the paper states that test performance is computed only once for the network that achieves the best result on the held-out validation set.",
          "Section 4.1",
          "After the controller trains 12,800 architectures, we ﬁnd the architecture that achieves the best validation accuracy."),
         ("Comparison caveats in the CIFAR-10 results: the best reported NAS error is obtained after adding 40 more filters to each layer of the searched architecture (in a setting where the controller predicts 13 layers, each a fully connected block of 3 layers, with pooling layers inserted at fixed positions); the authors note the DenseNet model with a lower error uses 1x1 convolutions to reduce parameters, which they did not do, so it is not an exact comparison.",
          "Section 4.1",
          "uses 1x1 convolutions to reduce its total number of parameters, which we did not do, so it is not an exact comparison."),
         ("Recurrent-cell search space on Penn Treebank: with base number 8, the search space has approximately 6 x 10^16 architectures, much larger than the 15,000 architectures the controller is allowed to evaluate; this search used S = 20, K = 400 and m = 1, i.e. 400 networks trained on 400 CPUs concurrently, with each child trained for 35 epochs.",
          "Section 4.2",
          "which is much larger than 15,000, the number of architectures that we allow our controller to evaluate."),
         ("Control experiment against random search (motivated, citing Bergstra & Bengio, 2012, by random search often being very hard to surpass): the authors state that both the best model and the average of the top models found with policy gradient are better than those found by random search; the comparison is reported only as perplexity improvements over iterations in a figure.",
          "Section 4.2",
          "The results show that not only the best model using policy gradient is better than the best model using random search, but also the average of top models is also much better."),
         ("REINFORCE gradient with baseline: the controller gradient is estimated as (1/m) sum_{k=1}^{m} sum_{t=1}^{T} grad_theta_c log P(a_t | a_(t-1):1; theta_c) (R_k - b), over m sampled architectures with T controller actions each, where R_k is the validation accuracy of the k-th child; subtracting a baseline b that does not depend on the current action keeps the estimate unbiased while reducing its variance.", "Section 3.2", "As long as the baseline function b does not depend on the on the current action, then this is still an unbiased gradient estimate."),
     ],
     "notes": "Affiliation: Google Brain (Zoph as a Google Brain Residency member). Venue: the arXiv v2 PDF header reads 'Under review as a conference paper at ICLR 2017' and the arXiv record has no comment or journal_ref, so no venue is recorded (ENAS, arxiv-1802.03268, cites it as 'In ICLR, 2017', but that is a third-party citation). Total GPU-days of the search are not stated in this PDF (searched for days, hours, cost, expensive); later papers quote such figures for it (e.g. DARTS Table 2 lists '1e4 CPU days' for NAS on PTB), not recorded here. Results (CIFAR-10 error, PTB perplexity, character-level PTB, GNMT BLEU) are in tables or the abstract and are not recorded as results. The test perplexity for the 16.28M character model is taken 'where the validation set perplexity is highest' (Section 4.2, as written). Control Experiment 1 (adding max and sin to the search space) reports 'somewhat comparable performance' without numbers. No repetition of the search over seeds is described. Same group (Le) co-authors arxiv-1802.01548 and arxiv-1802.03268, which compare against this method or its successor NASNet."},

    {"id": "arxiv-1802.01548",
     "title": "Regularized Evolution for Image Classifier Architecture Search",
     "authors": ["Esteban Real", "Alok Aggarwal", "Yanping Huang", "Quoc V. Le"],
     "year": 2018, "venue": "AAAI 2019", "version": "arXiv v7",
     "links": {"arxiv": "https://arxiv.org/abs/1802.01548",
               "code": "https://colab.research.google.com/github/google-research/google-research/blob/master/evolution/regularized_evolution_algorithm/regularized_evolution.ipynb"},
     "tasks": ["neural-architecture-search", "image-classification"],
     "fam": ["deep-learning"],
     "proposes": ["Aging (regularized) evolution: tournament selection (best of S random population members is mutated) in which the oldest model, rather than the worst, is removed from the population each cycle",
                  "Hidden-state and op mutations (plus identity) that cover the NASNet cell search space",
                  "AmoebaNet-A, the evolved normal/reduction cell architecture"],
     "claims": [
         ("Aging evolution: instead of the common step of discarding the worst model in the random S-sample (called non-aging evolution here), each cycle removes the oldest model in the population (the one trained earliest), which favors newer models; the authors state this lets the search explore more instead of zooming in on good models too early, as non-aging evolution would.",
          "Methods (Evolutionary Algorithm)",
          "in this paper we prefer a novel approach: killing the oldest model in the population"),
         ("Controlled comparison protocol: evolution, RL (the algorithm and code of the NASNet baseline study, an LSTM controller) and random search ran under identical conditions with the same code for network construction, training and evaluation, searching on CIFAR-10 in the NASNet search space until 20k models were evaluated. Evolution was tuned over 5 P/S configurations (best P=100, S=25); RL started from parameters tuned in the baseline study and its learning rate was further optimized over 8 values; the identity-mutation probability (0.05) was not tuned; tuning runs were excluded from the plots, as decided a priori, to avoid selection bias.",
          "Methods Details",
          "To avoid selection bias, plots do not include optimization runs, as was decided a priori."),
         ("Compute: during the search phase each model was trained for 25 epochs at N=3/F=24 on 1 GPU, and each experiment ran on 450 K40 GPUs for 20k models (approximately 7 days); the best 20 models of each experiment were then augmented to N=6/F=32 and trained for 600 epochs.",
          "Methods Details",
          "Each experiment ran on 450 K40 GPUs for 20k models (approx. 7 days)."),
         ("Search-progress comparison (5 repeats of each algorithm, shown in a figure): evolution yielded more accurate models at earlier stages, which the authors say could matter when experiments must be stopped early; when run for the full 20k models, evolution produced models with similar accuracy to RL; both compared favorably against random search. The authors note the figure shows accuracy only, not the compute cost of the models.",
          "Results (Comparison With RL and RS Baselines)",
          "At the later stages, if we allow to run for the full 20k models (as in the baseline study), evolution produced models with similar accuracy."),
         ("Augmented top models from the 5 experiments per algorithm on CIFAR-10 (figure only): evolved architectures had higher accuracy and similar FLOPs compared with random search, and lower FLOPs with similar accuracy compared with RL; parameter counts behaved similarly to FLOPs.",
          "Results (Comparison With RL and RS Baselines)",
          "Evolved architectures had higher accuracy (and similar FLOPs) than those obtained with RS, and lower FLOPs (and similar accuracy) than those obtained with RL."),
         ("The comparison of AmoebaNet-A with the results reported by the NASNet baseline study (as opposed to the authors' reproduction) is stated to be not entirely controlled, because identical training code and an equal number of experiments to obtain the final model cannot be ensured.",
          "Results (Comparison With RL and RS Baselines)",
          "Such a comparison is not entirely controlled, as we have no way of ensuring the network training code was identical and that the same number of experiments were done to obtain the ﬁnal model."),
         ("Scope caveat: the authors state some findings may be restricted to the search spaces and datasets used; preliminary small-compute experiments (CPU, F=8, N=1) over three search spaces and three datasets (gray-scale CIFAR-10, MNIST, gray-scale ImageNet) are presented in a supplement, where evolution reached equal or better accuracy in all cases.",
          "Discussion (Scope of results)",
          "Some of our ﬁndings may be restricted to the search spaces and datasets we used."),
         ("Tuning caveat: the authors acknowledge that with careful tuning RL might produce even better models than evolution, though such tuning would likely involve running many experiments and be more costly, and that random search might produce equally good models if run for a very long time, which would be very costly.",
          "Discussion (Simplicity of aging evolution)",
          "It is possible that through careful tuning, RL could be made to produce even better models than evolution, but such tuning would likely involve running many experiments, making it more costly."),
         ("Conjectured mechanism (speculative): under noisy training, non-aging evolution can keep models that were lucky the first time they trained, whereas under aging evolution an architecture can persist only by being inherited and re-training well repeatedly; the authors call this a form of regularization, report a supporting toy experiment with noisy evaluation in a supplement, and leave further verification to future work.",
          "Discussion (Understanding aging evolution and regularization)",
          "We can speculate that aging may help navigate the training noise in evolutionary experiments, as follows."),
     ],
     "notes": "Affiliation: Google Brain. Venue: page 1 footnote 'Accepted for publication at AAAI 2019, the Thirty-Third AAAI Conference on Artificial Intelligence' and the same arXiv comment; year is the first arXiv version (2018). Sections are unnumbered in the PDF, so section names are used. Conflict of interest / relatedness: the RL baseline is the NASNet study [54] (Zoph, Vasudevan, Shlens and Le), co-authored by Le, who is also an author here; the acknowledgments thank Zoph and Vasudevan for help with the code and experiments of that paper. Parameter S controls exploitation: 'S = 1 reduces to a type of random search' (Methods). The random-search baseline samples all models uniformly, as in the initial population. Small-compute experiments comparing aging and non-aging evolution (CPU, gray-scale CIFAR-10; Discussion and Supplement B) are figure-only. AmoebaNet-A was evolved on CIFAR-10 and transferred to ImageNet; the authors note it 'cannot have overfit the ImageNet dataset'. ImageNet/CIFAR-10 accuracies are in tables and the abstract; not recorded as results."},

    {"id": "arxiv-1802.03268",
     "title": "Efficient Neural Architecture Search via Parameter Sharing",
     "authors": ["Hieu Pham", "Melody Y. Guan", "Barret Zoph", "Quoc V. Le", "Jeff Dean"],
     "year": 2018, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1802.03268"},
     "tasks": ["neural-architecture-search", "image-classification", "language-modeling"],
     "fam": ["deep-learning"], "par": ["reinforcement-learning"],
     "proposes": ["ENAS: represent the NAS search space as one large DAG whose subgraphs are child models; all child models share the parameters of the DAG, and an LSTM controller trained with REINFORCE selects subgraphs",
                  "Alternating training of the shared weights (SGD on cross-entropy of sampled child models, M = 1 sample) and of the controller (reward on validation minibatches, moving-average baseline)",
                  "Recurrent-cell, macro (whole convolutional network) and micro (convolutional/reduction cell) search spaces"],
     "claims": [
         ("Motivation: citing Zoph et al. (2018), NAS is described as computationally expensive (450 GPUs for 3-4 days); the authors identify the bottleneck as training each child model to convergence only to measure its accuracy and then discarding the trained weights, and propose forcing all child models to share weights.",
          "Introduction",
          "We observe that the computational bottleneck of NAS is the training of each child model to convergence, only to measure its accuracy whilst throwing away all the trained weights."),
         ("Cost claim: in all experiments a single Nvidia GTX 1080Ti GPU was used and the architecture search took less than 16 hours, which the authors describe as a reduction of GPU-hours by more than 1000x compared to NAS.",
          "Introduction",
          "Compared to NAS, this is a reduction of GPU-hours by more than 1000x."),
         ("Shared-weight training: with the controller policy fixed, the shared weights are updated by SGD using a Monte Carlo gradient over M sampled child models; this estimate is unbiased but has higher variance than standard SGD with a fixed model, and the authors find, describing it as perhaps surprising, that M = 1 works just fine. The controller is then trained with REINFORCE and a moving-average baseline, with the reward computed on the validation set (a minibatch of validation data).",
          "Section 2.2",
          "Nevertheless – and this is perhaps surprising – we ﬁnd that M = 1 works just ﬁne, i.e. we can update ω using the gradient from any single model m sampled from π(m; θ)."),
         ("Deriving the final architecture: several models are sampled from the trained policy, each is scored on a single validation minibatch using the shared weights, and only the highest-reward model is retrained from scratch; the authors acknowledge results could be improved by training all sampled models from scratch and selecting on a separate validation set as other works do, but say their method yields similar performance while being much more economical.",
          "Section 2.2",
          "We then take only the model with the highest reward to re-train from scratch."),
         ("Penn Treebank protocol: no post-training techniques (neural cache, dynamic evaluation), cell size limited to 24M parameters, no extensive hyperparameter tuning (unlike Melis et al., 2017) and no training of multiple architectures with selection by validation perplexity (unlike Zoph & Le, 2017); on this basis the authors argue ENAS is not at an advantage and that its improved performance is only due to the cell's architecture.",
          "Section 3.1",
          "Therefore, ENAS is not at any advantage, compared to Zoph & Le (2017); Yang et al. (2018); Melis et al. (2017), and its improved performance is only due to the cell’s architecture."),
         ("Explanation of the remaining CIFAR-10 gap to NAS: perturbing the found models (e.g. randomly changing connections in the micro-space cells) increased test error, which the authors read as the models being local minima; they believe the ENAS controller is as good as the NAS controller and attribute the gap to not sampling, training and selecting among multiple architectures on validation data.",
          "Section 3.2",
          "the performance gap between NAS and ENAS is due to the fact that we do not sample multiple architectures from our trained controller, train them, and then select the best architecture on the validation data."),
         ("Random-architecture comparison ('Guided Random Search'), addressing whether the search space design rather than ENAS explains performance: a uniformly sampled recurrent cell, entire convolutional network and pair of convolutional/reduction cells were trained to convergence with the same settings; the random recurrent cell reached test perplexity 81.2 versus ENAS's 55.8, and the random convolutional network and random cells reached 5.86% and 6.77% test error versus ENAS's 4.23% and 3.54%. The text describes one sampled architecture per search space.",
          "Section 3.3",
          "Our random recurrent cell achieves the test perplexity of 81.2 on Penn Treebank, which is far worse than ENAS’s perplexity of 55.8."),
         ("Disabling the search: training only the shared weights with an untrained random controller in the macro space gave 8.92% error at convergence, and an ensemble of 250 Monte Carlo configurations of this model reached 5.49% test error; the authors conclude that appropriate training of the controller is crucial.",
          "Section 3.3",
          "We therefore conclude that the appropriate training of the ENAS controller is crucial for good performance."),
         ("Stability caveat: for CIFAR-10 the authors use 1x1 convolutions (with batch normalization and ReLU) after concatenating skip-connection inputs and global average pooling, stating these tricks are extremely important because gradient updates of the shared weights have very high variance, and that without them ENAS training is very unstable.",
          "Appendix B",
          "In fact, we ﬁnd that without these two tricks, the training of ENAS is very unstable."),
     ],
     "notes": "Affiliations: Google Brain, CMU, Stanford. No venue is stated in the arXiv v2 PDF ('Copyright 2018 by the authors') and the arXiv record has no comment or journal_ref; none recorded. Conflict of interest: Zoph and Le are authors of the main baseline NAS (arxiv-1611.01578) and of NASNet (Zoph et al., 2018), and NAS numbers in the comparison tables are taken from those papers rather than re-run. The 'more than 50,000x' GPU-hour reduction for the macro search space (Section 3.2) is relative to NAS's reported cost. Reported search times: about 10 hours for the PTB cell, about 7 hours for the macro CIFAR-10 network, 11.5 hours for the micro cells (single GTX 1080Ti). No repetition over seeds of the search or of final training is described (searched for seed, repeat, runs). The weight-sharing ranking correlation between shared-weight rewards and stand-alone accuracy is not evaluated in the text (searched for correlation, rank). Controller tricks: tanh constant 2.5, temperature 5.0, entropy bonus; macro space adds a KL penalty toward skip-connection probability 0.4. Results tables (PTB perplexity, CIFAR-10 errors) are not recorded as results."},

    {"id": "arxiv-1806.09055",
     "title": "DARTS: Differentiable Architecture Search",
     "authors": ["Hanxiao Liu", "Karen Simonyan", "Yiming Yang"],
     "year": 2018, "venue": "ICLR 2019", "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1806.09055", "code": "https://github.com/quark0/darts"},
     "tasks": ["neural-architecture-search", "image-classification", "language-modeling"],
     "fam": ["deep-learning"],
     "proposes": ["Continuous relaxation of a cell search space: each edge of the cell DAG computes a softmax-weighted mixture of candidate operations parameterized by architecture variables alpha",
                  "Bilevel formulation (alpha minimizes validation loss, weights minimize training loss) solved approximately by alternating gradient steps, with a one-step unrolled (second-order) or first-order architecture gradient and a finite-difference Hessian-vector approximation",
                  "Discretization by keeping the top-k strongest non-zero operations per node (k = 2 for convolutional, k = 1 for recurrent cells)"],
     "claims": [
         ("Continuous relaxation: the categorical choice of an operation on each edge is replaced by a softmax over all candidate operations, weighted by architecture parameters alpha; at the end of search a discrete architecture is obtained by replacing each mixed operation with its most likely operation.",
          "Section 2.2",
          "To make the search space continuous, we relax the categorical choice of a particular operation to a softmax over all possible operations:"),
         ("Bilevel formulation: the architecture alpha (upper level) minimizes the validation loss of weights w*(alpha) that minimize the training loss (lower level); the authors relate this to gradient-based hyperparameter optimization, noting alpha can be viewed as a special type of hyperparameter of substantially higher dimension and harder to optimize.",
          "Section 2.2",
          "This implies a bilevel optimization problem (Anandalingam & Friesz, 1992; Colson et al., 2007) with α as the upper-level variable and w as the lower-level variable:"),
         ("Approximation: because the exact architecture gradient requires the expensive inner optimization, w*(alpha) is approximated by a single training step; the authors state they are not aware of convergence guarantees for the resulting algorithm but that in practice it reaches a fixed point with a suitable choice of the inner step size. The second-order term is approximated by finite differences, reducing complexity from O(|alpha||w|) to O(|alpha| + |w|).",
          "Section 2.3",
          "While we are not currently aware of the convergence guarantees for our optimization algorithm, in practice it is able to reach a ﬁxed point with a suitable choice of"),
         ("First-order variant: with the inner step size set to 0, the architecture gradient is simply the validation-loss gradient at the current weights (treating w as w*(alpha)), which the authors report gives some speed-up but empirically worse performance in their CIFAR-10 and PTB experiments.",
          "Section 2.3",
          "This leads to some speed-up but empirically worse performance, according to our experimental results in Table 1 and Table 2."),
         ("Selection and evaluation protocol: DARTS is run four times with different random seeds and the best cell is chosen by validation performance after a short training from scratch (100 epochs on CIFAR-10, 300 on PTB), which the authors say is particularly important for recurrent cells because outcomes can be initialization-sensitive; the selected architecture is re-initialized and trained from scratch, and the test set is never used for search or selection. The table captions state that reported DARTS search costs exclude the selection cost and the final evaluation cost.",
          "Section 3.2",
          "We note the test set is never used for architecture search or architecture selection."),
         ("CIFAR-10 setup: half of the CIFAR-10 training data is held out as the validation set for search; an 8-cell network is searched for 50 epochs (one day on a single GPU; all experiments on GTX 1080Ti); the evaluation network has 20 cells trained for 600 epochs with cutout, path dropout and auxiliary towers. Because CIFAR results have high variance even with the same setup (citing Liu et al., 2018b), the mean and standard deviation of 10 independent runs are reported for the full model, and the NASNet-A and AmoebaNet-A cells were retrained in the authors' framework under the same settings.",
          "Appendix A.2.1",
          "Since the CIFAR results are subject to high variance even with exactly the same setup (Liu et al., 2018b), we report the mean and standard deviation of 10 independent runs for our full model."),
         ("Random search baseline: the authors note random search is competitive for both convolutional and recurrent models, which they say reflects the importance of search space design; DARTS improves on it with comparable or less search cost (2.76 +/- 0.09 vs 3.29 +/- 0.15 test error on CIFAR-10; 55.7 vs 59.4 perplexity on PTB). Per the table footnotes, the random baseline is the best of 24 (CIFAR-10) or 8 (PTB) sampled architectures selected by short-training validation error.",
          "Section 3.3",
          "It is also interesting to note that random search is competitive for both convolutional and recurrent models, which reﬂects the importance of the search space design."),
         ("Ablation of the bilevel formulation: jointly optimizing alpha and w over the union of training and validation sets by coordinate descent gave a best cell (of 4 runs) with 4.16 +/- 0.16% test error, worse than random search, and simultaneous SGD on alpha and w over all data gave 3.56 +/- 0.10%; the authors hypothesize these heuristics make alpha overfit the training data.",
          "Section 3.3",
          "We hypothesize that these heuristics would cause α (analogous to hyperparameters) to overﬁt the training data, leading to poor generalization."),
         ("Stated limitation: the method may suffer from discrepancies between the continuous architecture encoding and the derived discrete architecture, which the authors suggest could be alleviated, e.g., by annealing the softmax temperature to enforce one-hot selection.",
          "Section 4",
          "For example, the current method may suffer from discrepancies between the continuous architecture encoding and the derived discrete architecture."),
         ("Mixed operation (Eq. 2): on edge (i, j), o_bar(x) = sum_{o in O} [exp(alpha_o^(i,j)) / sum_{o' in O} exp(alpha_o'^(i,j))] o(x), a softmax-weighted sum of all candidate operations; the bilevel problem is min_alpha L_val(w*(alpha), alpha) subject to w*(alpha) = argmin_w L_train(w, alpha).", "Section 2.2", "To make the search space continuous, we relax the categorical choice of a particular operation to a softmax over all possible operations:"),
         ("One-step approximation (Eq. 6-7): the architecture gradient grad_alpha L_val(w*(alpha), alpha) is approximated by grad_alpha L_val(w - xi grad_w L_train(w, alpha), alpha), whose chain-rule expansion grad_alpha L_val(w', alpha) - xi grad^2_{alpha,w} L_train(w, alpha) grad_w' L_val(w', alpha) uses the one-step forward weights w' = w - xi grad_w L_train(w, alpha); the second-order term is approximated by finite differences.", "Section 2.3", "denotes the weights for a one-step forward model."),
     ],
     "notes": "Affiliations: CMU (Liu, Yang; Liu's current affiliation Google Brain) and DeepMind (Simonyan). Venue: PDF header 'Published as a conference paper at ICLR 2019' and arXiv comment 'Published at ICLR 2019'; year is the first arXiv version (2018). Relatedness: Liu and Simonyan co-authored Hierarchical evolution (Liu et al., 2018b), one of the compared methods (numbers taken from that paper). ENAS was re-run 8 times with the authors' released code for the CIFAR-10 table and re-trained under the DARTS setup for PTB/WT2. Zero operations are excluded when deriving the discrete cell because their strength is underdetermined under batch normalization (Section 2.4). The PTB cell was weaker when transferred to WikiText-2, which the authors attribute possibly to the small size of PTB (Section 3.3). The paper itself does not discuss a collapse of the searched cells to skip connections or parameter-free operations (searched for collapse, skip, parameter-free); the learned cells are shown only as figures. Results in tables (CIFAR-10, PTB, ImageNet mobile, WT2) are not recorded as results; the random-search comparison numbers above are from the body text."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
