import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-2402.03885",
     "title": "MOMENT: A Family of Open Time-series Foundation Models",
     "authors": ["Mononito Goswami", "Konrad Szafer", "Arjun Choudhry", "Yifu Cai", "Shuo Li", "Artur Dubrawski"],
     "year": 2024, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2402.03885", "code": "https://github.com/moment-timeseries-foundation-model/moment-research"},
     "tasks": ["time-series-forecasting", "time-series-anomaly-detection", "time-series-classification"],
     "fam": ["time-series-foundation-model", "deep-learning"], "par": ["self-supervised"],
     "proposes": ["MOMENT (open-source family of transformer time-series foundation models pre-trained by masked time series modeling)",
                  "Time Series Pile (collection of public time series for pre-training)",
                  "multi-task limited-supervision benchmark extending the TimesNet benchmark"],
     "claims": [
         ("MOMENT is a family of high-capacity transformer models pre-trained with a masked time series prediction task on large amounts of time series from diverse domains; the authors present it as the first family of open-source large pre-trained time series models.",
          "Introduction",
          "MOMENT is a family of high-capacity transformer models, pre-trained using a masked time series prediction task on large amounts of time series data drawn from diverse domains."),
         ("Pre-training data and contamination control: the Time Series Pile collates the Informer long-horizon forecasting datasets, the Monash archive, the UCR/UEA classification archive and TSB-UAD; every dataset is split into disjoint train/validation/test splits (creators' splits, otherwise a random 60/10/30 split) and only the training splits are used for pre-training. The Informer collection listed as part of the Pile comprises ETT, Electricity, Traffic, Weather, ILI and Exchange-rate.",
          "Methodology (Figure 2 caption)",
          "We only use the training splits of all datasets for pre-training."),
         ("Zero-shot short-horizon forecasting follows the setting of Oreshkin et al. (2021): MOMENT is fine-tuned on a source dataset and evaluated on a target dataset of the same temporal resolution. Results are reported only on the portion of M3 and M4 unseen during pre-training and on the frequencies with the most data; the authors say daily, hourly and weekly frequencies had very little data and they could not get promising zero-shot performance for any of the deep learning models.",
          "Appendix (Zero-shot short-horizon forecasting)",
          "our results are reported only (1) on 40% of the M3 and M4 datasets that were unseen during pre-training, (2) a subset of frequencies with largest support in the datasets."),
         ("Tuning protocol: the main text states that no hyper-parameter tuning is performed (the appendix says no 'extensive' tuning); MOMENT-Large is fine-tuned with a fixed batch size and a one-cycle schedule, and baselines use the recommended settings from their papers and public repositories. Long-horizon forecasting uses linear probing (only the forecasting head is trained).",
          "Experimental Setup and Results",
          "We do not perform hyper-parameter tuning."),
         ("Long-horizon forecasting: linearly probed MOMENT is near state-of-the-art on most datasets and horizons but second to PatchTST, which generally achieves the lowest MSE; LLM-based forecasters (Time-LLM, GPT4TS) perform worse than MOMENT on many datasets and horizons, and N-BEATS outperforms several recent methods.",
          "Results (Long-horizon forecasting)",
          "Linearly probing MOMENT achieves near state-of-the-art performance on most datasets and horizons, and is only second to PatchTST which generally achieves the lowest MSE (Tab. 2)."),
         ("Zero-shot short-horizon forecasting is where the authors see the largest scope for improvement: statistical methods such as Theta and ETS outperformed the deep models, although on some datasets MOMENT had lower sMAPE than ARIMA.",
          "Results (Zero-shot short-horizon forecasting)",
          "Statistical methods such as Theta and ETS outperformed their deeper counterparts."),
         ("Negative finding across tasks: the authors found that statistical and non-transformer approaches (ARIMA for short-horizon forecasting, N-BEATS for long-horizon forecasting, k-nearest neighbors for anomaly detection) outperform many deep and transformer-based models, and argue such baselines are needed to assess practical utility.",
          "Experimental Setup and Results (Baselines)",
          "We found that statistical and non-transformer-based approaches like ARIMA for short-horizon forecasting, N-BEATS for long-horizon forecasting, and k-nearest neighbors for anomaly detection outperform many deep and transformer-based models."),
     ],
     "notes": "PDF states: Proceedings of the 41st International Conference on Machine Learning (ICML), PMLR 235, 2024. Authors at Carnegie Mellon University (Auton Lab) and University of Pennsylvania; funding from NIH and U.S. Army. Anomaly detection is evaluated with adjusted best F1 and VUS-ROC on a subset of the UCR anomaly archive; classification via SVM on unsupervised representations on 91 UCR datasets. Models and the Time Series Pile are released on Hugging Face (AutonLab); the reproducibility statement gives the research-code URL github.com/moment-timeseries-foundation-model/moment-research. The appendix hyper-parameter paragraph describes different default fine-tuning settings (MOMENT-Base, batch size 16, cosine schedule) from the main text (MOMENT-Large, batch size 64, one-cycle). Reviewer inference, not stated as such in the paper: the long-horizon evaluation datasets in Table 1 (ETT, Electricity, Traffic, Weather, Exchange, ILI) are the Informer datasets included in the Time Series Pile, so their training splits (and only those, per Section 3.1) were seen in pre-training; long-horizon results are therefore not out-of-distribution with respect to pre-training data."},

    {"id": "arxiv-2310.03589",
     "title": "TimeGPT-1",
     "authors": ["Azul Garza", "Cristian Challu", "Max Mergenthaler-Canseco"],
     "year": 2023, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2310.03589"},
     "tasks": ["time-series-forecasting"],
     "fam": ["time-series-foundation-model", "deep-learning"], "par": ["supervised"],
     "proposes": ["TimeGPT (Transformer encoder-decoder forecasting foundation model, zero-shot inference; conformal prediction intervals)"],
     "claims": [
         ("Pre-training data: TimeGPT was trained on what the authors describe as the largest collection of publicly available time series, over 100 billion data points from domains such as finance, economics, healthcare, weather, IoT, energy, web traffic, sales and transport; the individual datasets are not named in the text.",
          "Training dataset",
          "TimeGPT was trained on, to our knowledge, the largest collection of publicly available time series, collectively encompassing over 100 billion data points."),
         ("Zero-shot definition: the test set (over 300 thousand series from finance, web traffic, IoT, weather, demand and electricity) is described as never seen by the model during training; the authors argue a per-series train/test cutoff is not strict enough for a foundation model. The specific test datasets are not named in the text.",
          "Experimental Results",
          "In this section, we explore TimeGPT’s capabilities as a forecasting foundation model by testing it in a large and diverse set of time series that were never seen by the model during training."),
         ("Evaluation protocol: only the last forecasting window of each series is evaluated, with frequency-dependent horizons (12 monthly, 1 weekly, 7 daily, 24 hourly); metrics are rMAE and rRMSE relative to Seasonal Naive (both point-error metrics; no probabilistic metric is reported in the results tables).",
          "Experimental Results",
          "The evaluation is performed in the last forecasting window of each time series, varying in length by the sampling frequency."),
         ("Baseline protocol: baselines and statistical models are fit per series on the history before the last window, while machine learning and deep learning models are trained as one global model per frequency on all series of the test set; Prophet and ARIMA were excluded for computational cost. How baseline hyperparameters were chosen was not found in the text (the 'hyperparameter exploration' mentioned concerns TimeGPT's own training).",
          "Experimental Results",
          "Some popular models like Prophet [Taylor and Letham, 2018] and ARIMA were excluded from the analysis due to their prohibitive computational requirements and extensive training times."),
         ("Main empirical claim: zero-shot TimeGPT outperforms the compared statistical and deep learning models, ranking among the top-3 performers across frequencies.",
          "Zero-shot inference",
          "Remarkably, TimeGPT outperforms a comprehensive collection of battle-tested statistical models and SoTA deep learning approaches, ranking among the top-3 performers across frequencies."),
         ("Hedge in the discussion: the authors relate their results to scaling laws and say simpler models might outperform Transformers on smaller datasets, so simpler models might be more fitting when large datasets or compute are limited.",
          "Discussion and Future Research",
          "In situations where there are limitations on the availability of large datasets or computational resources, simpler models might be more fitting."),
         ("Affiliation/product disclosure: all authors are at Nixtla, and TimeGPT is offered as a Python SDK and REST API in private beta; the paper is thus a vendor evaluating its own model.",
          "Appendix (Access and early testing)",
          "TimeGPT is accessible through both a Python SDK and a REST API endpoint, currently available in private beta."),
     ],
     "notes": "The 'Comparison with recent Foundation Models' section of v3 contains only 'Work in progress.'; no comparison with other foundation models is reported. Searched 'leak', 'overlap', 'tuned', 'default': no statement on pretraining/test overlap checks or baseline tuning found. Fine-tuning results are shown only as a figure on a subset of the test set."},

    {"id": "arxiv-2407.07874",
     "title": "Toto: Time Series Optimized Transformer for Observability",
     "authors": ["Ben Cohen", "Emaad Khwaja", "Kan Wang", "Charles Masson", "Elise Ramé", "Youssef Doubli", "Othmane Abou-Amal"],
     "year": 2024, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2407.07874"},
     "tasks": ["time-series-forecasting"],
     "fam": ["time-series-foundation-model", "deep-learning"], "par": ["supervised"],
     "proposes": ["Toto (decoder-only time series foundation model for observability)",
                  "Proportional Factorized Space-Time Attention", "Student-T mixture model output head",
                  "Datadog observability forecasting benchmark"],
     "claims": [
         ("Pre-training data: Toto was trained on about one trillion time series points, of which 75% are anonymous observability metrics from the Datadog platform, alongside publicly available time series datasets.",
          "Abstract",
          "Alongside publicly available time series datasets, 75% of the data used to train Toto consists of fully anonymous numerical metric data points from the Datadog platform."),
         ("The training-data section says the non-Datadog points come from the LOTSA collection; a later subsection adds synthetic data (generated similarly to TimesFM) at approximately 5% of the training dataset. Whether the LSF evaluation datasets were excluded from the LOTSA portion is not stated in the text (searched for leakage, overlap, exclusion, held-out: not found).",
          "Training data",
          "The remaining points come from the LOTSA dataset [15], a compilation of publicly-available time series datasets across many different domains."),
         ("Architecture: Toto is a decoder-only forecasting model that uses causal next-patch prediction, techniques from recent LLM architectures (pre-normalization, RMSNorm, SwiGLU feed-forward layers), and a novel adaptation of multi-head attention to multivariate time series.",
          "Model architecture",
          "Toto is a decoder-only forecasting model."),
         ("LSF evaluation protocol: ETTh1, ETTh2, ETTm1, ETTm2, Electricity and Weather with horizons 96 to 720 in sliding windows of stride 512, context 512, median of 200 samples, normalized MAE/MSE.",
          "Experiments (LSF benchmark)",
          "We evaluate with forecast lengths of 96, 192, 336, and 720 time steps, in sliding windows with stride 512, and average the results."),
         ("Baselines on LSF are not rerun: Toto is compared with results reported in the Moirai and TimesFM papers for zero-shot foundation models and with reported results for full-shot models.",
          "Experiments (LSF benchmark)",
          "We compared Toto's performance with the reported results of other recent zero-shot foundation models [15, 19], as well as full-shot time series forecasting models [14, 16, 17, 36, 44–47]."),
         ("Datadog benchmark: on an in-house benchmark of 82 multivariate observability series (sMAPE, sMdAPE; other foundation models run with the sampling procedures from their papers), the authors suggest that open datasets may not provide sufficient information for observability data, highlighting training on more relevant data.",
          "Experiments (Datadog benchmark)",
          "These results suggest that current open datasets may not provide suﬃcient information to extrapolate to the speciﬁc nuances of observability data, highlighting the importance of training on more relevant data as demonstrated by Toto's superior performance."),
         ("Affiliation/conflict of interest: this is a Datadog technical report (all authors at datadoghq.com) evaluating Datadog's own model, partly on a benchmark built from Datadog data.",
          "Introduction",
          "We present Toto, a groundbreaking time series forecasting foundation model developed by Datadog."),
     ],
     "notes": "Technical report; the authors announce a forthcoming paper with more details. No code or weights URL found in the text; the responsible-AI section says Toto is not intended for mass distribution."},

    {"id": "arxiv-2410.10393",
     "title": "GIFT-Eval: A Benchmark For General Time Series Forecasting Model Evaluation",
     "authors": ["Taha Aksu", "Gerald Woo", "Juncheng Liu", "Xu Liu", "Chenghao Liu", "Silvio Savarese", "Caiming Xiong", "Doyen Sahoo"],
     "year": 2024, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2410.10393", "code": "https://github.com/SalesforceAIResearch/gift-eval"},
     "tasks": ["time-series-forecasting"],
     "fam": ["time-series-foundation-model", "deep-learning", "linear-models"], "par": ["supervised", "self-supervised"],
     "proposes": ["GIFT-Eval benchmark (train/test component + non-leaking pretraining corpus)"],
     "claims": [
         ("GIFT-Eval's train/test component has 23 datasets (over 144,000 series, 177 million points) across seven domains, 10 frequencies, univariate and multivariate inputs, and short to long horizons; results are aggregated over 97 dataset/frequency/horizon configurations with MAPE and CRPS normalized by Seasonal Naive plus an average CRPS rank.",
          "Abstract",
          "GIFT-Eval encompasses 23 datasets over 144,000 time series and 177 million data points, spanning seven domains, 10 frequencies, multivariate inputs, and prediction lengths ranging from short to long-term forecasts."),
         ("The benchmark also provides a pretraining corpus (71 univariate and 17 multivariate datasets) stated to have no leakage into the train/test split, so that foundation models pretrained on it can be fairly evaluated.",
          "Benchmark (Pretraining data)",
          "Notably this collection of data has no leakage issue with the train/test split and can be used to pretrain foundation models that can be fairly evaluated on GIFT-Eval."),
         ("Leakage: the pretraining sets of public TimesFM, Chronos and Moirai partially overlap with GIFT-Eval; the authors retrained Moirai on the non-leaking split for the main tables and compared it with the original Moirai, finding that in most cases leakage can boost test performance, more so at longer horizons, which they read as memorization.",
          "Appendix (Data leakage effect in foundation models)",
          "In most cases, data leakage from training sets can boost performance on the corresponding test sets, with this effect becoming more pronounced as prediction length increases."),
         ("Tuning asymmetry: deep learning baselines are tuned with 15 trials per model for each of the 97 runs (validation = last training window), whereas foundation models are evaluated zero-shot on the test split, with TimesFM and VisionTS settings taken from their papers/defaults, a context-length search for Moirai, and a seasonality search on validation data for VisionTS (see notes on which Moirai checkpoints are used).",
          "Appendix (Deep learning models)",
          "We search for 15 trials for each deep learning model per each of the 97 runs."),
         ("Overall result: PatchTST has the top average scores in all metrics, with MoiraiLarge second; by best/second-best counts Crossformer is most often best and MoiraiLarge most often in the top 2.",
          "Results (Overall)",
          "PatchTST emerges as the most dominant model, securing the top average scores in all metrics, with MoiraiLarge consistently following in second place."),
         ("Foundation models (particularly Moirai variants) lead on short horizons (and, in the separate frequency analysis, on daily to yearly data), but TimesFM and Chronos decline at medium/long horizons (attributed to recursive decoding error accumulation) and deep models such as PatchTST do better there; the authors also report that GIFT-Eval does not consistently support scaling laws for TSFMs.",
          "Results (Prediction length)",
          "Thus despite the progress in foundational time series research, there remains a notable performance gap between deep learning and foundation models for medium to long-term predictions,"),
         ("Affiliation: authors are at Salesforce AI Research (and NUS); the paper's own reference for Moirai lists Woo, C. Liu, Kumar, Xiong, Savarese and Sahoo, five of whom are GIFT-Eval authors, i.e. the benchmark authors overlap with the authors of one of the evaluated models (no explicit conflict-of-interest statement found).",
          "References",
          "Gerald Woo, Chenghao Liu, Akshat Kumar, Caiming Xiong, Silvio Savarese, and Doyen Sahoo."),
     ],
     "notes": "Inconsistency in the text: the introduction gives the pretraining component as 88 datasets with 240 billion points, the abstract and Section 3 as about 230 billion. Appendix A says foundation models use 'public versions available online' (e.g. Salesforce/moirai-1.1-R), while Appendix F.2 says the main tables use Moirai retrained on the GIFT-Eval pretraining split; which Moirai appears in which table should be checked. Moirai checkpoints are hosted under the Salesforce Hugging Face organization (Appendix A)."},

    {"id": "arxiv-2403.14735",
     "title": "Foundation Models for Time Series Analysis: A Tutorial and Survey",
     "authors": ["Yuxuan Liang", "Haomin Wen", "Yuqi Nie", "Yushan Jiang", "Ming Jin", "Dongjin Song", "Shirui Pan", "Qingsong Wen"],
     "year": 2024, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2403.14735"},
     "tasks": ["time-series-forecasting"],
     "fam": ["time-series-foundation-model", "large-language-models", "deep-learning"], "par": ["self-supervised", "supervised"],
     "proposes": ["methodology-centric taxonomy of time-series foundation models (architecture, pre-training, adaptation, modality)"],
     "claims": [
         ("Survey scope: a methodology-centric taxonomy of time-series foundation models by model architecture, pre-training technique, adaptation method and data modality, covering standard time series, spatial time series, trajectories and events.",
          "Abstract",
          "To address this gap, our survey adopts a methodology-centric classification, delineating various pivotal elements of time-series FMs, including model architectures, pre-training techniques, adaptation methods, and data modalities."),
         ("Two routes to TSFMs are distinguished: repurposing pretrained LLMs for time series, or training a Transformer from scratch on time series.",
          "Model architecture",
          "This includes either repurposing pretrained LLMs for time series to leverage their preexisting sequence modeling strengths [102], or directly using Transformer as a base for TSFMs, training from scratch"),
         ("Architecture choice is unsettled: encoder-only, encoder-decoder and decoder-only TSFMs all exist, unlike the trend to decoder-only models in NLP.",
          "Model architecture",
          "The choice of foundation model framework remains debated in the realm of time series analysis, contrasting the trend towards decoder-only models in natural language processing."),
         ("Pre-training mechanisms are categorized by learning objective into fully-supervised, self-supervised (generative, contrastive, hybrid) and others; the authors consider self-supervised pre-training more generic and realistic than fully-supervised pre-training.",
          "Pre-training",
          "Compared with fully-supervised pre-training, it provides a more generic and realistic solution for the acquisition of a time series foundation model."),
         ("On zero-shot (direct) usage, the survey notes that good zero-shot performance can also indicate homogeneity between the pre-training data and the target data, especially for domain-specific foundation models.",
          "Adaptation",
          "It can also indicate the homogeneity between the pre-trained dataset and target dataset, especially for some real-world applications where a foundation model is built to fulfill domain-specific tasks [4, 13]."),
     ],
     "notes": "PDF states: KDD '24 (30th ACM SIGKDD Conference), Barcelona. Survey without its own experiments; searched 'benchmark', 'leak', 'evaluation': no discussion of evaluation benchmarks or pretraining/test leakage found. Future directions listed in the appendix: multi-modality, efficient architectures (e.g. Mamba), temporal distribution shift and interpretability, privacy."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): time-series foundation models and forecasting; carded by a subagent. Results tables not recorded; claims only.")
