import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402
from topic_tree_common import BASE_NOTE, CREATED  # noqa: E402

SPECS = [
    {"id": "arxiv-1005.0208",
     "title": "Analysis of a Random Forests Model",
     "authors": ["Gérard Biau"],
     "year": 2010, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1005.0208"},
     "tasks": ["tabular-regression"],
     "fam": ["random-forests"], "par": ["supervised"],
     "proposes": ["Consistency and rate-of-convergence analysis of a simplified random forests model suggested by Breiman (2004 draft): data-independent randomization, midpoint splits, coordinate j chosen with probability p_nj, trees of ceil(log2 k_n) levels, under a sparsity assumption (regression function depends on S strong features)"],
     "claims": [
         ("The paper analyses a random forests model suggested by Breiman in a short draft, which the author describes as very close to the original algorithm, and shows that it is consistent and adapts to sparsity (its rate depends only on the number of strong features, not on the number of noise variables).",
          "Abstract",
          "In this paper, we oﬀer an in-depth analysis of a random forests model suggested by Breiman in [12], which is very close to the original algorithm."),
         ("Simplifying assumption: the randomizing variable Theta is independent of X and of the training sample, which excludes any bootstrapping/resampling step and any data-dependent split search on the training observations (a second, independent sample is allowed); each tree splits ceil(log2 k_n) times, choosing coordinate j with probability p_nj and cutting at the midpoint of the chosen side.",
          "Introduction (The model)",
          "This excludes in particular any bootstrapping or resampling step in the training set."),
         ("Theorem 2.1 covers the 'purely random' case (coordinate chosen uniformly, p_nj = 1/d), which is consistent if k_n goes to infinity and k_n/n to 0; the author calls this a radically simplified version of practical random forests that does not explain the algorithm's good performance.",
          "Asymptotic analysis (Theorem 2.1)",
          "This is however a radically simpliﬁed version of the random forests used in practice, which does not explain the good performance of the algorithm."),
         ("Proposition 2.1 (X uniform, bounded conditional variance): the forest variance is O(k_n / (n (log k_n)^{S/2d})), so even with k_n = n it still tends to 0, whereas a single tree's variance is of order k_n/n; the log term comes from the Theta-averaging (correlation between trees). The author believes this offers a perspective on why unpruned trees still work, while noting that the bias bound (Proposition 2.2) contains a term e^{-n/2k_n} that prevents the extreme choice k_n = n.",
          "Asymptotic analysis (Proposition 2.1)",
          "We believe that it provides an interesting perspective on why random forests are still able to do a good job, despite the fact that individual trees are not pruned."),
         ("Proposition 2.2 / Corollary 2.1 (X uniform, r* Lipschitz on the S strong coordinates, p_nj = (1/S)(1 + xi_nj) for strong j with xi_nj log n -> 0): the bias rate depends on S rather than d, and the overall rate n^{-0.75/(S log 2 + 0.75)} is faster than the d-dimensional rate n^{-2/(d+2)} as soon as S <= floor(0.54 d).",
          "Asymptotic analysis (Proposition 2.2)",
          "In other words, when the number of active variables is less than (roughly) half of the ambient dimension, the bias of the random forests regression estimate decreases to 0 much faster than the usual rate."),
         ("Remark 2: the reduced-dimensional rate is strictly slower than the S-dimensional optimal rate n^{-2/(S+2)}, and the author does not know whether that optimal rate can be achieved by the algorithm.",
          "Asymptotic analysis (Remark 2)",
          "We do not know whether the latter rate can be achieved by the algorithm."),
         ("Gap to Breiman's algorithm: a CART-like procedure that chooses the best split among M_n random coordinates on a second sample is described as close to random forests, but the original algorithm searches cuts on the training data itself; the author does not know whether the results hold when Theta depends on the training data (as in CART) and calls the heuristic argument a rough approach needing more theoretical work.",
          "Discussion",
          "We do not know whether our results are still true if Θ depends on Dn (as in the CART algorithm), but the analysis does not appear to be simple."),
         ("Variable importance: the out-of-bag permutation importance used by random forests has, as far as the author is aware, no systematic mathematical study; such a study is said to be beyond the paper's scope.",
          "Discussion",
          "As far as we are aware, there is to date no systematic mathematical study of this criterion."),
         ("Simulation (Sinus, Friedman #1, Tree models; test set of 50 000; 100 data sets): Breiman's forests (R randomForest, mtry automatically tuned by the package, 1000 trees, minimum node size 5) are compared with an alternative that fixes the number of terminal nodes to ceil(n/5) but otherwise splits on the actual sample like CART; the author reports very similar overall performance and takes this as confirming that the analysed model is a good approximation. Note: the alternative still uses data-dependent CART splits, unlike the analysed model.",
          "A small simulation study",
          "This conﬁrms our idea that the model discussed in the present paper is a good approximation of the authentic Breiman’s forests."),
     ],
     "notes": "Affiliations: Université Pierre et Marie Curie – Paris VI and Ecole Normale Supérieure. No venue statement was found in the arXiv v3 PDF (searched for journal, JMLR, published, to appear), so no venue is recorded (the Biau & Scornet survey, arxiv-1511.05741, cites it as Biau (2012); not used as a source). Section 3 also discusses an idealized mtry scheme (strong set known) in which M_n -> infinity and M_n/log n -> infinity are required, which the author says is not consistent with the belief that M_n should not depend on n. MSE results are shown as figures only (Figures 6-8); no numbers recorded."},

    {"id": "arxiv-1511.05741",
     "title": "A Random Forest Guided Tour",
     "authors": ["Gérard Biau", "Erwan Scornet"],
     "year": 2015, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/1511.05741"},
     "tasks": ["tabular-regression", "tabular-classification", "model-explanation"],
     "fam": ["random-forests", "decision-trees"], "par": ["supervised"],
     "proposes": [],
     "claims": [
         ("Survey's description of Breiman's algorithm: three parameters a_n (points sampled per tree), mtry (directions tried per node) and nodesize; in the regression mode of the R package randomForest the defaults are mtry = ceil(p/3), a_n = n (bootstrap) and nodesize = 5.",
          "The random forest estimate (Algorithm)",
          "an is set to n, and nodesize is set to 5."),
         ("Theoretical studies have so far considered simplified versions because bagging and the CART split are hard to analyse: typically the bagging step is ignored and/or CART-split selection is replaced by a more elementary cut protocol; in Breiman's forests, leaves typically contain between 1 and 5 observations.",
          "Introduction",
          "This is often done by simply ignoring the bagging step and/or replacing the CART-split selection by a more elementary cut protocol."),
         ("Centered (purely random) forests: no resampling, uniformly chosen coordinate, split at the cell centre, k levels; they are consistent if k -> infinity and n/2^k -> infinity, but the unpruned choice k ~ log n violates this condition, there is no bagging, and forest consistency follows from tree consistency, so the authors judge the model too simple to explain Breiman's forests.",
          "Simplified models",
          "Overall, this model does not demonstrate the beneﬁt of using forests in place of individual trees and is too simple to explain the mathematical forces driving Breiman’s forests."),
         ("The sparsity-adaptive rate for centered forests (Breiman 2004; Biau 2012), depending only on the number of strong variables |S|, is obtained by assuming that the splitting probabilities on informative variables tend to 1/|S|, i.e. that the procedure selects the informative variables, which the authors call a strong assumption.",
          "Simplified models",
          "Of course, this is achieved by assuming that the procedure succeeds in selecting the informative variables for splitting, which is indeed a strong assumption."),
         ("The role of the bootstrap is still poorly understood: most analyses (citing Mentch and Hooker 2015; Wager 2014; Scornet et al. 2015) replace it by subsampling without replacement with a_n < n, usually with a_n/n -> 0, which excludes the bootstrap regime.",
          "The resampling mechanism",
          "The role of the bootstrap in random forests is still poorly understood and, to date, most analyses are doomed to replace the bootstrap by a subsampling scheme"),
         ("Little has been proven for Breiman's original procedure; citing Breiman (2001), the forest error is bounded in terms of the correlation between tree errors and the strength of individual trees; consistency and asymptotic normality results (Wager 2014; Mentch and Hooker 2015) replace bootstrap by subsampling and simplify the splitting step.",
          "Consistency, asymptotic normality, and more",
          "All in all, little has been proven mathematically for the original procedure of Breiman."),
         ("Citing Scornet et al. (2015): consistency in additive regression models was proved for a pruned version of Breiman's forest, while consistency of the unpruned procedure depends on a conjecture about CART that is difficult to verify.",
          "Consistency, asymptotic normality, and more",
          "Unfortunately, the consistency of the unpruned procedure comes at the price of a conjecture regarding the behavior of the CART algorithm that is diﬃcult to verify."),
         ("Open problems: the default bootstrap mode (a_n = n with replacement) seems to give excellent results but has no supporting theory; the impact of tree depth on statistical performance is also stated to be an open question.",
          "Conclusion and perspectives",
          "By default, the algorithm runs in bootstrap mode (i.e., an = n points selected with replacement) and although this seems to give excellent results, there is to date no theory to support this choice."),
         ("Variable importance caveats (citing empirical studies): correlated variables negatively affect MDA (permutation importance), and Archer and Kimes (2008) found both MDA and MDI behave poorly as correlation increases; Strobl et al. (2008) attribute MDA's bias to evaluating marginal rather than conditional importance.",
          "Variable importance (Related works)",
          "Similarly, the empirical study of Archer and Kimes (2008) points out that both MDA and MDI behave poorly when correlation increases"),
         ("Split-selection bias (citing Breiman et al. 1984; Segal 1988; Kim and Loh 2001): splits in random forests are known to be biased toward covariates with many possible splits or with missing values; Hothorn et al. (2006) correct this by first selecting the variable and then the cut position.",
          "Decision splits",
          "Splits in random forests are known to be biased toward covariates with many possible splits (Breiman et al., 1984; Segal, 1988) or with missing values (Kim and Loh, 2001)."),
         ("The authors conclude that present results are insufficient to explain random forests' behaviour in full generality; their intuition (stated as such) is that tree aggregation can estimate patterns not characterized by standard sparsity or smoothness conditions.",
          "Conclusion and perspectives",
          "It remains however that the present results are insuﬃcient to explain in full generality the remarkable behavior of random forests."),
     ],
     "notes": "Affiliation: Sorbonne Universités, UPMC Univ Paris 06 (Biau also Institut universitaire de France). Review article; the acknowledgments thank 'the Editors and three anonymous referees' but the arXiv v1 PDF names no journal, so no venue is recorded (Curth et al., arxiv-2402.01502, cite it as 'Test, 25:197–227, 2016'; not used as a source). Disclosure: many of the reviewed theoretical results are the authors' own (Biau 2012 = arxiv-1005.0208; Scornet et al. 2015 = arxiv-1405.2881; Scornet 2015a/b; Biau and Devroye 2010; Biau et al. 2008). The survey also covers parameter tuning (out-of-bag error lets parameters be adjusted without a validation set; nodesize defaults 1/5 'not supported by solid theory'), the LNN / kernel view of forests, and Louppe et al. (2013)'s MDI decomposition for totally randomized trees on categorical variables."},

    {"id": "arxiv-1405.2881",
     "title": "Consistency of random forests",
     "authors": ["Erwan Scornet", "Gérard Biau", "Jean-Philippe Vert"],
     "year": 2014, "venue": "Annals of Statistics", "version": "arXiv v4",
     "links": {"arxiv": "https://arxiv.org/abs/1405.2881", "doi": "https://doi.org/10.1214/15-AOS1321"},
     "tasks": ["tabular-regression"],
     "fam": ["random-forests", "decision-trees"], "par": ["supervised"],
     "proposes": ["L2 consistency of Breiman's random forests (CART splits on mtry random directions, subsampling without replacement instead of bootstrap) in additive regression models: Theorem 1 with a limited number of leaves t_n, Theorem 2 with fully grown trees under subsampling rate a_n log n / n -> 0 and an extra assumption (H2)"],
     "claims": [
         ("Contribution: a consistency result for Breiman's original random forest algorithm in the context of additive regression models, with insight into how forests adapt to sparsity.",
          "Abstract",
          "In the present paper, we take a step forward in forest exploration by proving a consistency result for Breiman’s [Mach. Learn. 45 (2001) 5–32] original algorithm in the context of additive regression models."),
         ("Modification of the algorithm analysed: each tree uses a_n points drawn without replacement instead of a bootstrap sample of n points drawn with replacement; the authors state this is harmless and only avoids the mathematical difficulties of the bootstrap. Trees stop when the number of cells reaches t_n.",
          "Section 2",
          "is harmless—in fact, it is just a means to avoid mathematical diﬃculties induced by the bootstrap"),
         ("Assumption (H1): Y is a sum of continuous univariate functions of the coordinates plus independent centered Gaussian noise, with X uniform on [0,1]^p; the authors say the analysis is facilitated within additive models.",
          "Section 3",
          "Although random forests fall into the family of nonparametric procedures, it turns out that the analysis of their properties is facilitated within the framework of additive models."),
         ("Theorem 1 (under H1): forests are consistent if a_n -> infinity, t_n -> infinity and t_n (log a_n)^9 / a_n -> 0; it still holds with a_n = n (subsampling plays no role, depth control suffices), and an easy adaptation shows CART is consistent under the same assumptions.",
          "Section 3",
          "We note in passing that an easy adaptation of Theorem 1 shows that the CART algorithm is consistent under the same assumptions."),
         ("Theorem 2 (fully grown trees, t_n = a_n) additionally requires (H2), a condition on how Y-values influence connection probabilities; it holds when the partition is independent of the Y_i or without noise, but in general the authors do not know whether (H2) holds.",
          "Section 3",
          "However, in the most general context, the partitions strongly depend on the whole sample Dn, and unfortunately, we do not know whether or not (H2) is satisﬁed."),
         ("The authors state that, apart from replacing bootstrapping by subsampling, Theorems 1 and 2 are the first consistency results for Breiman's forests, since most previously studied models are built independently of the data.",
          "Section 3",
          "To our knowledge, apart from the fact that bootstrapping is replaced by subsampling, Theorems 1 and 2 are the ﬁrst consistency results for Breiman’s (2001) forests."),
         ("In Theorem 2 the estimation error is controlled by a subsampling rate a_n/n = o(1/log n) (a_n/n -> 0 with bounded noise), ensuring a query point is not connected to the same observation in many trees; subsampling is the key component imposing tree diversity, and the individual one-point-per-leaf trees are not consistent.",
          "Section 4",
          "In our approach, the subsampling is the key component for imposing tree diversity."),
         ("Proposition 1 (H1, mtry = p, no strong component constant on any interval): with probability 1 - xi, for n large enough, the first k cuts are along the S informative variables, so forests behave as if data were projected onto those variables.",
          "Section 3",
          "Since the algorithm selects splits mostly along informative variables, everything happens as if data were projected onto the vector space generated by the S informative variables."),
         ("Limitation: the analysis does not carry over to high dimensions with p = p_n growing with n (possibly larger than n); (H2.1) may then be too restrictive.",
          "Section 3",
          "Unfortunately, our analysis does not carry over to this context."),
     ],
     "notes": "Affiliations: Sorbonne Universités and MINES ParisTech, PSL-Research University. Venue from the PDF header ('The Annals of Statistics 2015, Vol. 43, No. 4, 1716–1741', DOI 10.1214/15-AOS1321) and the arXiv journal_ref. Proofs of intermediary results are in a supplemental article. The authors also note that their results cannot be directly extended to pointwise consistency (citing Wager 2014, forests can be inconsistent at fixed points, particularly near edges), and that results extend to heteroscedastic sub-Gaussian noise. No experiments."},

    {"id": "arxiv-2402.01502",
     "title": "Why do Random Forests Work? Understanding Tree Ensembles as Self-Regularizing Adaptive Smoothers",
     "authors": ["Alicia Curth", "Alan Jeffares", "Mihaela van der Schaar"],
     "year": 2024, "version": "arXiv v1", "license": "CC BY 4.0",
     "links": {"arxiv": "https://arxiv.org/abs/2402.01502"},
     "tasks": ["tabular-regression", "tabular-classification"],
     "fam": ["random-forests", "gradient-boosted-trees", "decision-trees"], "par": ["supervised"],
     "proposes": ["Interpreting trees and tree ensembles as adaptive smoothers (weighted averages of training labels) and quantifying their smoothing with the effective-parameter measure of Curth et al. (2023), separately at training and test inputs",
                  "A decomposition of forest-over-tree gains into reduced sampling variation (label noise), reduced model variability, and reduced representation bias"],
     "claims": [
         ("Main thesis: forests improve upon trees by three distinct, usually entangled mechanisms: smoothing reduces variance due to outcome noise, reduces variability in the quality of the learned function given fixed inputs, and reduces potential bias by enriching the hypothesis space.",
          "Abstract",
          "Instead, we show that forests can improve upon trees by three distinct mechanisms that are usually implicitly entangled."),
         ("Argument for interpolating (full-depth) ensembles: each tree acts as a 1-NN estimator at both training and test inputs, but different randomized trees can place an unseen input in leaves with different training points, so the forest is smoother at test inputs than at training inputs and smoother than individual trees there.",
          "Section 2.5",
          "Therefore, interpolating forests should be expected to (i) be smoother when issuing predictions for testing examples than for training examples and (ii) be smoother than individual trees at previously unseen test inputs"),
         ("Evaluation setup: the 'MARSadd' simulation (d = 5 uniform features, n_train = n_test = 500, sigma = 1 by default), averaged over 10 seeds; Appendix C replicates analyses on 4 datasets from Grinsztajn et al. (2022) subsampled to 2000 train/test points; trees, forests and boosting use scikit-learn RandomForestRegressor / GradientBoostingRegressor. Results are shown as figures.",
          "Section 3 (Experimental setup)",
          "All experiments are averaged over 10 replications with different random seeds and shaded areas in plots represent 95% confidence intervals."),
         ("Spiked-smooth behaviour (Wyner et al. 2017) is quantified as a gap between train-time and test-time effective parameters; it also appears in non-interpolating forests (limited number of leaves) but is much more pronounced for interpolating trees, leading the authors to conjecture it appears whenever there is some overfitting.",
          "Section 3.1.2",
          "We thus conjecture that spiked-smooth behavior appears whenever there is some degree of overfitting to the training data."),
         ("For ensembles of 50 interpolating trees, adding randomness by lowering the fraction m of features per split appears to improve generalization at first, then hurts once tree construction becomes too random (a U-shape, analogous to k in k-NN); adding more trees never hurt generalization error in their experiments.",
          "Section 3.1.1",
          "We observe that in-troducing more randomness (by decreasing m) appears to improve generalization initially, until a turning point is reached when additional randomness hurts performance – this is when tree construction becomes too random."),
         ("The covariance-based degrees of freedom used by Mentch and Zhou (2020) cannot fully explain forest-vs-tree performance differences (e.g. it is constant across ensemble sizes); the authors argue Wyner et al.'s spiked-smooth explanation is a special case of Mentch and Zhou's randomization-as-regularization explanation.",
          "Section 3",
          "We show that their chosen measure for degrees of freedom cannot fully explain the success of forests relative to trees"),
         ("Trees and forests (built from i.i.d. Theta) have the same statistical bias, so classically all gains are attributed to variance reduction; the authors argue this notion misses differences in what trees and forests can represent, and propose distinguishing them by representation bias (forests' hypothesis class contains that of trees).",
          "Section 4.1.3",
          "We therefore argue that distinguishing trees and forests by their representation bias can be more meaningful."),
         ("In the noiseless setting (sigma = 0), bagging full-depth trees worsened in-sample error relative to interpolating trees, while for unseen test inputs forests improved over individual trees even without label noise (shown in Figure 10).",
          "Section 4.2.1",
          "when given previously unseen test examples, Panel (A) of Fig. 10 highlights that forest predictions can improve upon individual trees even in the absence of any label noise (σ = 0)!"),
         ("Protocol caveat for the RepBias/ModVar analysis: 50 re-seeded versions of each model are trained on a fixed noiseless train-test set (delta = 0.1) and the best one is selected using oracle knowledge of the test outcomes as a proxy for representation bias.",
          "Section 4.2.2",
          "Among these 50 models, we measure performance on the test set and identify the best-performing model"),
         ("Practical takeaway: bootstrapping mainly affects in-sample error (ability to overfit labels at observed inputs), whereas randomness in feature selection matters much more for out-of-sample performance, especially when trees fit the training data perfectly; too much randomness can hurt.",
          "Conclusion (Practical takeaways)",
          "Randomness in feature selection, especially when the training data can be fit perfectly, is much more important for out-of-sample prediction performance."),
     ],
     "notes": "Affiliation: University of Cambridge. No venue statement found in the arXiv v1 PDF; license CC BY 4.0 stated on page 1. Disclosure: the effective-parameter measure used throughout is from the authors' own earlier work (Curth, Jeffares and van der Schaar, NeurIPS 2023, 'A U-turn on double descent', per the reference list: same three authors). All results are figures (no tables); no numbers recorded. Boosted ensembles are also shown to be smoothers (Appendix B) and to display spiked-smooth behaviour (Fig. 5)."},
]

if __name__ == "__main__":
    build(SPECS, base_note=BASE_NOTE, **CREATED)
