import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-2206.07682",
     "title": "Emergent Abilities of Large Language Models",
     "authors": ["Jason Wei", "Yi Tay", "Rishi Bommasani", "Colin Raffel", "Barret Zoph", "Sebastian Borgeaud",
                 "Dani Yogatama", "Maarten Bosma", "Denny Zhou", "Donald Metzler", "Ed H. Chi", "Tatsunori Hashimoto",
                 "Oriol Vinyals", "Percy Liang", "Jeff Dean", "William Fedus"],
     "year": 2022, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2206.07682"},
     "tasks": ["scaling-laws"], "fam": ["large-language-models"], "par": ["in-context-learning"],
     "proposes": ["definition of 'emergent abilities' of large language models (not present in smaller models, present in larger ones) and a survey of examples from prior work"],
     "claims": [
         ("Definition used by this paper: an ability is emergent if it is not present in smaller models but is present in larger models; the paper says such abilities therefore cannot be predicted simply by extrapolating smaller models' performance.",
          "Abstract",
          "We consider an ability to be emergent if it is not present in smaller models but is present in larger models."),
         ("Operational pattern: on a scaling curve (model scale vs performance), the paper describes emergent abilities as near-random performance until a critical threshold of scale, after which performance rises substantially above random (it calls this a phase transition).",
          "Emergent Abilities Definition",
          "When visualized via a scaling curve (x-axis: model scale, y-axis: performance), emergent abilities show a clear pattern—performance is near-random until a certain critical threshold of scale is reached, after which performance increases to substantially above random."),
         ("Scale measure: scaling curves use training compute in FLOPs on the x-axis (parameter-count plots are given in an appendix); the paper says training dataset size is not plotted because many model families use a fixed number of training examples for all sizes, and that no single proxy captures all aspects of scale.",
          "Emergent Abilities Definition",
          "In this paper, we will analyze scaling curves by plotting the performance of diﬀerent models where training compute for each model is measured in FLOPs on the x-axis (Hoﬀmann et al., 2022)."),
         ("Nature of the evidence: the paper is a survey of results in the existing literature and does not propose new methods or models (the surveyed examples include model families such as GPT-3, LaMDA, Gopher, Chinchilla and PaLM; the paper adds its own cross-entropy re-analysis of six BIG-Bench tasks, see c7).",
          "Broader Impact Statement",
          "In this paper, we surveyed results in the existing literature, without proposing new methods or models."),
         ("Scope caveat: the authors state that the scale at which an ability emerges is not an immutable property (e.g. emergence may occur with less training compute or fewer parameters for models trained on higher-quality data; today's models are likely not trained optimally), and that they do not claim a specific scale is required.",
          "Emergent Abilities Definition",
          "Our goal in this paper is not to characterize or claim that a speciﬁc scale is required to observe emergent abilities, but rather, we aim to discuss examples of emergent behavior in prior work."),
         ("Metric caveat stated by the authors themselves (citing BIG-Bench): exact string match on long targets may disguise compounding incremental improvements as emergence; but they argue metrics without partial credit are at best an incomplete explanation because emergence is also observed on many classification tasks.",
          "Potential explanations of emergence (Discussion)",
          "using evaluation metrics that do not give partial credit are at best an incomplete explanation, because emergent abilities are still observed on many classiﬁcation tasks (e.g., the tasks in Figure 2D–H)"),
         ("Cross-entropy analysis on six emergent BIG-Bench tasks, which the paper says follows the BIG-Bench (2022) setup and affirms BIG-Bench's conclusions (i.e. the observation originates with BIG-Bench): cross-entropy loss improves even at scales where exact match / BLEU / accuracy stay near random, i.e. log-likelihood improvements can be masked by downstream metrics; the authors add that this does not explain why downstream metrics are emergent or predict the emergence scale.",
          "Potential explanations of emergence (Discussion)",
          "Namely, cross-entropy loss improves even for small model scales where the downstream metrics (exact match, BLEU, and accuracy) are close to random and do not improve, which shows that improvements in the log-likelihood of the target sequence can be masked by such downstream metrics."),
     ],
     "notes": "PDF states: Published in Transactions on Machine Learning Research (08/2022). Affiliations on the title page: Google Research, Stanford University, UNC Chapel Hill, DeepMind (several surveyed model families, e.g. LaMDA, PaLM, Gopher, Chinchilla, come from these organizations). Appendix A.1 specifies that the cross-entropy analysis uses six few-shot BIG-Bench tasks considered emergent for LaMDA models and concludes that all six fall under 'Outcome 2' (loss improves while EM/BLEU/acc is random), while the tasks 'are still considered emergent'. The paper (footnote 1) says the survey focuses on pre-trained Transformer language models. Augmented prompting strategies (chain of thought, instruction tuning, scratchpad, calibration) are counted as emergent if they show no improvement or harm until a large-enough scale. Critiqued by arxiv-2304.15004 (metric-choice explanation)."},

    {"id": "arxiv-2304.15004",
     "title": "Are Emergent Abilities of Large Language Models a Mirage?",
     "authors": ["Rylan Schaeffer", "Brando Miranda", "Sanmi Koyejo"],
     "year": 2023, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2304.15004"},
     "tasks": ["scaling-laws", "image-classification"], "fam": ["large-language-models", "deep-learning"], "par": ["in-context-learning"],
     "proposes": ["alternative explanation of emergent abilities: nonlinear/discontinuous metrics (and too few test examples) make smooth per-token improvements look sharp and unpredictable"],
     "claims": [
         ("Main claim, presented as an alternative explanation: for a given task and model family, with fixed model outputs, emergent abilities appear due to the researcher's choice of metric rather than fundamental changes in model behavior with scale; nonlinear or discontinuous metrics produce apparent emergence, linear or continuous ones smooth changes. The abstract's conclusion is hedged: emergent abilities 'may not be a fundamental property of scaling AI models'.",
          "Abstract",
          "Here, we present an alternative explanation for emergent abilities: that for a particular task and model family, when analyzing ﬁxed model outputs, emergent abilities appear due the researcher’s choice of metric rather than due to fundamental changes in model behavior with scale."),
         ("Definition being questioned: the paper quotes the definition of arxiv-2206.07682 (its reference [33]) and, from that quotation together with one from Ganguli et al. [8], identifies two defining properties, sharpness and unpredictability; what it calls into question is specifically sharp and unpredictable changes in model outputs as a function of scale on specific tasks.",
          "Introduction",
          "In this paper, we call into question the claim that LLMs possess emergent abilities, by which we speciﬁcally mean sharp and unpredictable changes in model outputs as a function of model scale on speciﬁc tasks."),
         ("Two factors: primarily a metric that nonlinearly or discontinuously deforms per-token error rates, and secondarily too few test examples to estimate smaller models' performance (so they appear wholly unable to do the task).",
          "Introduction",
          "our alternative posits that emergent abilities are a mirage caused primarily by the researcher choosing a metric that nonlinearly or discontinuously deforms per-token error rates, and secondarily by possessing too few test data to accurately estimate the performance of smaller models"),
         ("Scope of the direct test: outputs of the InstructGPT/GPT-3 family (chosen because it is publicly queryable) on two arithmetic tasks; according to the authors, switching from Accuracy to Token Edit Distance with fixed outputs gave smooth, predictable improvement, and generating additional test data showed all models in the family achieve above-chance accuracy.",
          "Analyzing InstructGPT/GPT-3's Emergent Arithmetic Abilities",
          "To test these predictions, we collected outputs from the InstructGPT/GPT-3 family on two tasks: 2-shot multiplication between two 2-digit integers and 2-shot addition between two 4-digit integers."),
         ("Meta-analysis scope (BIG-Bench published results, with hand-annotated emergent task-metric-model family triplets from Wei's '137 emergent abilities' list): emergence appears under 4 of 39 metrics and two metrics, Multiple Choice Grade and Exact String Match, account for more than 92% of claimed emergent abilities.",
          "Meta-Analysis of Claimed Emergent Abilities",
          "we also analyzed hand-annotated task-metric-model family triplets [32], which revealed emergent abilities appear with 4/39 metrics (Fig. 5B), and 2 metrics account for > 92% of claimed emergent abilities (Fig. 5C): Multiple Choice Grade and Exact String Match"),
         ("Metric swap on LaMDA (outputs available through BIG-Bench): on tasks where LaMDA showed emergence under Multiple Choice Grade, the emergence disappeared under the continuous Brier Score.",
          "Meta-Analysis of Claimed Emergent Abilities",
          "LaMDA’s emergent abilities on the discontinuous Multiple Choice Grade disappeared when we changed the metric to the continuous Brier Score (Fig. 6)."),
         ("Hedge stated by the authors: they do not claim that LLMs cannot display emergent abilities; their message is that previously claimed emergent abilities (including those in arxiv-2206.07682, their reference [33]) might likely be a mirage induced by researcher analyses.",
          "Discussion",
          "We emphasize that nothing in this paper should be interpreted as claiming that large language models cannot display emergent abilities; rather, our message is that previously claimed emergent abilities in [3, 8, 28, 33] might likely be a mirage induced by researcher analyses."),
     ],
     "notes": "PDF states: Preprint. Under review. Affiliation: Computer Science, Stanford University. Exact scope of the critique: (1) InstructGPT/GPT-3 via the OpenAI API (footnote: as of 2023-03-15, 4 models with 350M, 1.3B, 6.7B, 175B parameters) on 2-digit multiplication and 4-digit addition only; (2) a meta-analysis of published BIG-Bench results using the BIG-Bench emergence score and the hand annotations of [32] (Jason Wei, '137 emergent abilities of large language models'); the authors say other model families are not publicly queryable, so they were limited to published results; (3) the metric swap to Brier Score only for LaMDA; (4) metric-induced 'emergence' in vision models (shallow autoencoders on CIFAR100 with a thresholded reconstruction metric, autoregressive transformers on Omniglot and LeNet on MNIST with subset accuracy). The mathematical model assumes independent per-token errors; footnote 1 says this assumption is not true but the approximation qualitatively matches. Related work: the paper says Srivastava et al. (BIG-Bench) had already hypothesized that emergence may be partially attributed to the metric, and that this paper converts that discussion into predictions and concludes 'metric choice is likely wholly responsible' (stronger wording than the Discussion's hedge in c7). Reviewer cross-reference, not stated in this paper: arxiv-2206.07682 itself discussed the exact-match caveat and cross-entropy masking (see that card's c6/c7). The Discussion also raises multiple comparisons across ~10^6 BIG-Bench task-metric-model family triplets as a possible issue ('possibly infected')."},

    {"id": "arxiv-2306.09479",
     "title": "Inverse Scaling: When Bigger Isn't Better",
     "authors": ["Ian R. McKenzie", "Alexander Lyzhov", "Michael Pieler", "Alicia Parrish", "Aaron Mueller", "Ameya Prabhu",
                 "Euan McLean", "Aaron Kirtland", "Alexis Ross", "Alisa Liu", "Andrew Gritsevskiy", "Daniel Wurgaft",
                 "Derik Kauffman", "Gabriel Recchia", "Jiacheng Liu", "Joe Cavanagh", "Max Weiss", "Sicong Huang",
                 "The Floating Droid", "Tom Tseng", "Tomasz Korbak", "Xudong Shen", "Yuhui Zhang", "Zhengping Zhou",
                 "Najoung Kim", "Samuel R. Bowman", "Ethan Perez"],
     "year": 2023, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2306.09479", "code": "https://github.com/inverse-scaling/prize"},
     "tasks": ["scaling-laws"], "fam": ["large-language-models"], "par": ["in-context-learning"],
     "proposes": ["Inverse Scaling Prize: 11 prize-winning datasets showing inverse scaling",
                  "four potential causes of inverse scaling (strong prior, unwanted imitation, distractor task, spurious few-shot)"],
     "claims": [
         ("Main claim: the paper presents evidence that LMs may show inverse scaling (worse task performance with increased scale), e.g. due to flaws in the training objective and data, based on 11 datasets collected through a public contest.",
          "Abstract",
          "Here, we present evidence for the claim that LMs may show inverse scaling, or worse task performance with increased scale, e.g., due to flaws in the training objective and data."),
         ("Experimental range: submissions were evaluated zero-shot and few-shot on model series from OpenAI, Anthropic and DeepMind spanning 10^18 to 10^23 training FLOPs (the paper says 'over 5 orders of magnitude'), with and without instruction tuning; GPT-4 and PaLM results were added after the contest (PaLM results taken from Wei et al. 2022a).",
          "Introduction",
          "We evaluated submissions in zero-shot (no examples provided in the input) and few-shot (a few examples provided) settings across model series from OpenAI, Anthropic, and DeepMind, covering over 5 orders of magnitude: 1018 to 1023 training FLOPs."),
         ("Compute counting: where training-FLOP estimates were unavailable, they used the 6ND approximation (N parameters, D training tokens); fine-tuning FLOPs (Context Distilled, FeedME, RLHF) were not counted, as hard to estimate and a small fraction of pretraining.",
          "Appendix C (FLOP Computation)",
          "Where an estimate of training FLOPs was not available, we estimate them using the 6ND approximation from Kaplan et al. (2020), where N is the number of model parameters and D is the number of training tokens."),
         ("Caveat on the x-axis: training FLOPs are used rather than parameters (citing Hoffmann et al. as a better proxy), but the authors warn that FLOP-based comparisons between model families can be misleading because families differ in model-size-to-data ratios.",
          "Introduction (footnote)",
          "However, since different model families have different ratios of model size to data quantity, comparisons based on FLOPs between model families can be misleading."),
         ("U-shaped and inverted-U scaling: trends can reverse at larger scale (U-shaped, e.g. several tasks on PaLM; inverted-U, e.g. Prompt Injection), which the authors say shows that even the direction of scaling trends found with smaller models may not hold for larger ones.",
          "Introduction",
          "Such results show that even the direction of scaling trends found with smaller models may not hold with larger models, making it challenging to predict the novel capabilities and failures of future LMs."),
         ("Attribution of the U-shaped finding: the paper states that Wei et al. (2022a), evaluating PaLM up to 540B parameters, found performance started to improve for 7 of the 11 winning tasks; this paper notes that for Resisting Correction, Memo Trap and NeQA the larger PaLM sizes are still below the small PaLM sizes.",
          "Discussion (U-Shaped Scaling)",
          "count Resisting Correction, Memo Trap, and NeQA, among the U-shaped tasks, though we note that performance on larger PaLM sizes is still below performance on small PaLM sizes on these tasks"),
         ("Model access / affiliations: held-out private model series were provided by Anthropic and DeepMind; several authors list Anthropic, Google or Stability AI affiliations (Bowman and Perez list Anthropic, Parrish and Kim list Google, Pieler lists Stability AI; the footnote says Pieler's work was done at FAR AI, Bowman's at NYU, Perez's at FAR AI and NYU).",
          "Models Evaluated",
          "Private models were provided by Anthropic (models trained in Bai et al., 2022)2 and DeepMind (Gopher: Rae et al. 2021, and Chinchilla: Hoffmann et al. 2022)."),
     ],
     "notes": "PDF states: Published in Transactions on Machine Learning Research (10/2023). Data released at https://inversescaling.com/data under CC BY 4.0 (per the text). Winning tasks use the classification loss metric, except Prompt Injection (sequence prob). Models: GPT-2, GPT-3, OPT, Anthropic LM, Gopher, Chinchilla (pretraining only), plus GPT-3 FeedME, Anthropic Context Distilled and RLHF; GPT-4 / GPT-4 RLHF results for five tasks came via private correspondence and PaLM results are taken from Wei et al. (2022a). Footnote 3: Anthropic Context Distilled/RLHF inputs were not reformatted as dialog, 'which may influence the results'. Anthropic LM was also evaluated through training (checkpoints from 33.6M to 400B tokens) and few-shot from 1 to 72 shots. Section 3.5: no grand or second prizes were awarded because many tasks 'did not sufficiently demonstrate real-world implications of failure on the task'. Funding: Open Philanthropy funded the prize. Related: arxiv-2206.07682 (Wei et al. 2022b, emergence) is cited for emergent behaviors."},

    {"id": "arxiv-2408.03314",
     "title": "Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters",
     "authors": ["Charlie Snell", "Jaehoon Lee", "Kelvin Xu", "Aviral Kumar"],
     "year": 2024, "version": "arXiv v1",
     "links": {"arxiv": "https://arxiv.org/abs/2408.03314"},
     "tasks": ["scaling-laws", "efficiency-evaluation"], "fam": ["large-language-models"], "par": [],
     "proposes": ["'compute-optimal' test-time scaling strategy: choose test-time hyperparameters (search method, sequential vs parallel ratio) per question-difficulty bin",
                  "FLOPs-matched comparison of test-time compute against scaling model parameters"],
     "claims": [
         ("Main claim (abstract wording), for PaLM 2-S* on MATH only: allocating test-time compute adaptively per prompt (by difficulty bin) improves the efficiency of test-time compute scaling by more than 4x compared to a best-of-N baseline. The body states 'up to 4x less test-time compute' (for PRM search it only 'nearly' outperforms best-of-N; with predicted rather than oracle bins some benefits diminish at higher budgets), and the Discussion states 2-4x.",
          "Abstract",
          "Using this compute-optimal strategy, we can improve the efficiency of test-time compute scaling by more than 4× compared to a best-of-N baseline."),
         ("FLOPs-matched claim (PaLM 2-S* on MATH): on problems where the smaller base model has somewhat non-trivial success rates, test-time compute can outperform a ~14x larger pretrained model (greedy decoding, parameters scaled with fixed data); per Section 7 this depends on difficulty bin and the inference/pretraining token ratio R (see c5).",
          "Abstract",
          "Additionally, in a FLOPs-matched evaluation, we find that on problems where a smaller base model attains somewhat non-trivial success rates, test-time compute can be used to outperform a 14× larger model."),
         ("Experimental range: a single base model, PaLM 2-S* (Codey), fine-tuned for revisions or used with a PRM verifier, evaluated only on MATH with the 12k train / 500 test split of Lightman et al.; the authors say they believe the model is representative and think the findings likely transfer to similar models (not tested).",
          "Experimental Setup",
          "We conduct our analysis using the PaLM 2-S* [3] (Codey) base model."),
         ("Compute counting: pretraining FLOPs approximated as 6 N D_pretrain and inference FLOPs as 2 N D_inference; the exchange depends on R = D_inference / D_pretrain, compared at R = 0.16, 0.79 and 22.",
          "Exchanging Pretraining and Test-Time Compute",
          "To determine pretraining FLOPs, use use the common approximation 𝑋= 6𝑁𝐷pretrain [14], and for inference FLOPs, we use 𝑌= 2𝑁𝐷inference [29]."),
         ("Not 1-to-1 exchangeable (FLOPs-matched comparison with PaLM 2-S* on MATH, oracle difficulty bins, R = 0.16/0.79/22): on easy/medium questions or with small inference requirements test-time compute can cover for additional pretraining, but on challenging questions outside the base model's capabilities or under higher inference load, pretraining is likely more effective.",
          "Exchanging Pretraining and Test-Time Compute (takeaways)",
          "However, on challenging questions which are outside a given base model’s capabilities or under higher inference requirement, pretraining is likely more effective for improving performance."),
         ("Cost not counted: estimating question difficulty itself costs inference compute, and the experiments do not account for this cost, for simplicity.",
          "How to Scale Test-Time Computation Optimally",
          "This is a crucial avenue for future work (see Section 8) and our experiments do not account for this cost largely for simplicity, since our goal is to present some of the first results of what is in fact possible by effectively allocating test-time compute."),
         ("Oracle difficulty in the FLOPs-matched figure: the pretraining-vs-test-time comparison (Figure 9) plots the compute-optimal policy within oracle difficulty bins, i.e. bins computed from ground-truth correctness of 2048 samples per question (the paper also defines model-predicted bins from verifier scores and uses them in e.g. Figures 4 and 8, but Figure 9 shows only the oracle-bin policy, which assumes ground-truth access unavailable at deployment).",
          "Exchanging Pretraining and Test-Time Compute (Figure 9)",
          "Each line represents the performance of scaling test-time compute with our compute-optimal policy in each oracle difficulty bin."),
     ],
     "notes": "Affiliations: UC Berkeley and Google DeepMind (first author's work done during an internship at Google DeepMind); the base model PaLM 2 is a Google model. Protocol details: strategies are selected per difficulty bin with two-fold cross-validation on the test set (select on one fold, evaluate on the other). The FLOPs-matched comparison scales parameters with a fixed amount of training data (matching the LLaMA approach); compute-optimal pretraining with data and parameters scaled together is left to future work. The ~14x larger model is not named in the text found. For search methods, cost is measured in generations (lookahead costs N x (k+1) samples). Capability-specific fine-tuning was needed for revision and verification (footnote 1). The authors report small gains on hard problems and that on the most difficult questions (level 5) no method makes much meaningful progress."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model size, data, compute and performance (scaling laws, compute-optimal training, cost measurement); carded by a subagent. Results tables not recorded; claims only.")
