import sys

sys.path.insert(0, "scripts/cards")
from _spec_builder import build  # noqa: E402

SPECS = [
    {"id": "arxiv-1610.02136",
     "title": "A Baseline for Detecting Misclassified and Out-of-Distribution Examples in Neural Networks",
     "authors": ["Dan Hendrycks", "Kevin Gimpel"],
     "year": 2016, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/1610.02136", "code": "https://github.com/hendrycks/error-detection"},
     "tasks": ["selective-prediction", "dataset-shift-detection", "image-classification"],
     "fam": ["deep-learning"], "par": ["post-hoc"],
     "proposes": ["Maximum softmax probability (MSP) of a trained classifier as a baseline score for detecting misclassified and out-of-distribution examples, with standard detection tasks and threshold-independent metrics (AUROC, AUPR); plus an auxiliary-decoder 'abnormality module' that beats the baseline on some tasks"],
     "claims": [
         ("Selection signal: correctly classified examples tend to have a higher maximum softmax probability than misclassified and out-of-distribution examples, which allows detecting the latter (the baseline needs no change to the classifier).",
          "Abstract",
          "Correctly classiﬁed examples tend to have greater maximum softmax probabilities than erroneously classiﬁed and out-of-distribution examples, allowing for their detection."),
         ("Caveat: the softmax prediction probability, viewed in isolation, corresponds poorly to confidence; the authors' point is that it still ranks examples usefully (incorrect / out-of-distribution examples tend to get lower values), not that it is calibrated.",
          "Introduction",
          "Throughout our experiments we establish that the prediction probability from a softmax distribution has a poor direct correspondence to conﬁdence."),
         ("Evaluation metric: because a detector needs a score threshold that trades off false negatives and false positives, the paper uses threshold-independent AUROC, plus AUPR (reported with success/in-distribution and with error/out-of-distribution as the positive class) because AUROC is not ideal when base rates differ greatly; no operating threshold is chosen.",
          "Problem formulation and evaluation",
          "Faced with this issue, we employ the Area Under the Receiver Operating Characteristic curve (AUROC) metric, which is a threshold-independent performance evaluation (Davis & Goadrich, 2006)."),
         ("OOD protocol (vision): all in-distribution test examples are positives; out-of-distribution negatives are realistic images and noise: SUN scenes for CIFAR-10/100; Omniglot, notMNIST and black-and-white CIFAR-10 for MNIST; Gaussian and uniform noise. Other tasks use other text corpora, held-out topics, and noise-mixed or Chinese speech.",
          "Computer vision",
          "For out-of-distribution (negative) examples, we use realistic images and noise."),
         ("Failure mode: when distorted inputs degrade the classifier only slightly (a noise-robust fully connected TIMIT network), softmax statistics alone did not give useful out-of-distribution detection, while the trained abnormality module did. Separately (Section 3.2, POS tagging with the WSJ-trained tagger), the authors state that out-of-distribution weblog text, being closer in style to newswire than tweets are, is harder to detect than tweets.",
          "Abnormality detection with auxiliary decoders",
          "Because the classiﬁcation degradation was only slight, the softmax statistics alone did not provide useful out-of-distribution detection."),
         ("Evaluation recommendation: report AUPR and AUROC together with the underlying classifier's accuracy, because an always-wrong classifier gets maximum AUPR for error detection when error is the positive class; new detectors should be compared against the softmax baseline of their own classifiers on a variety of datasets and architectures.",
          "Discussion and future work",
          "Reporting the AUPR and AUROC values is important, and so is the underlying classiﬁer’s accuracy since an always-wrong classiﬁer gets a maximum AUPR for error detection if error is the positive class."),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2017. Affiliations: UC Berkeley (work done at TTIC), Toyota Technological Institute at Chicago; NVIDIA donated GPUs (Acknowledgments). Tasks span vision (MNIST, CIFAR-10/100), NLP (IMDB sentiment, 20 Newsgroups/Reuters topic, WSJ/Twitter POS tagging) and speech (TIMIT); image-classification tag covers only part of it. The authors also tried KL divergence from uniform and found it highly correlated with MSP (footnote 3). Ranking quality only: the paper does not set or calibrate a deployment threshold. Tag note: the task tags are approximations. No calibration / uncertainty / OOD-detection tag exists yet (a user decision on adding one is pending); selective-prediction and dataset-shift-detection are the closest existing tags and do not exactly describe this paper (it scores misclassified / OOD inputs, it does not abstain or detect dataset-level shift itself)."},

    {"id": "arxiv-1706.04599",
     "title": "On Calibration of Modern Neural Networks",
     "authors": ["Chuan Guo", "Geoff Pleiss", "Yu Sun", "Kilian Q. Weinberger"],
     "year": 2017, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1706.04599", "code": "http://github.com/gpleiss/temperature_scaling"},
     "tasks": ["selective-prediction", "image-classification"],
     "fam": ["deep-learning"], "par": ["post-hoc"],
     "proposes": ["Temperature scaling: a single-parameter variant of Platt scaling that divides the logits by a scalar T fitted by NLL on a held-out validation set; plus an empirical study of miscalibration in modern networks and a comparison of post-processing calibration methods"],
     "claims": [
         ("Main observation: modern neural networks, unlike those from a decade ago, are poorly calibrated (confidence does not match the probability of being correct).",
          "Abstract",
          "We discover that modern neural networks, unlike those from a decade ago, are poorly calibrated."),
         ("Factors (correlational, not causal): increased model capacity and lack of regularization are closely related to miscalibration; the paper examines depth, width, Batch Normalization and weight decay.",
          "Observing miscalibration",
          "Though we cannot claim causality, we ﬁnd that increased model capacity and lack of regularization are closely related to model miscalibration."),
         ("Mechanism of temperature scaling: a single scalar T > 0 for all classes divides the logits, T is optimized with respect to NLL on the validation set, and since it does not change the softmax argmax, class predictions and accuracy are unchanged.",
          "Calibration methods",
          "In other words, temperature scaling does not affect the model’s accuracy."),
         ("Calibration set and scope: all compared methods are post-processing steps that need a hold-out validation set (in practice possibly the same set used for hyperparameter tuning), and the paper assumes training, validation and test sets are drawn from the same distribution; all calibration results in the paper are therefore in-distribution, and nothing is claimed about calibration under dataset shift.",
          "Calibration methods",
          "We assume that the training, validation, and test sets are drawn from the same distribution."),
         ("Main empirical result: temperature scaling outperforms all other compared methods on the vision tasks and performs comparably on the NLP datasets (compared: histogram binning, isotonic regression, BBQ, vector and matrix scaling).",
          "Results",
          "Temperature scaling outperforms all other methods on the vision tasks, and performs comparably to other methods on the NLP datasets."),
         ("Evaluation metric: ECE with equally spaced confidence bins (M = 15 in the results table) is the primary calibration metric, with MCE and NLL also defined. In Results, the authors note that the one dataset temperature scaling did not calibrate, Reuters, was already well calibrated (ECE <= 1%), and say it is 'also possible' that their measurements there are affected by the dataset split or the binning scheme.",
          "Definitions",
          "We use ECE as the primary empirical metric to measure calibration."),
         ("Failure mode of richer calibrators: matrix scaling performs poorly with hundreds of classes and fails to converge on 1000-class ImageNet; the authors state any calibration model with tens of thousands or more parameters will overfit a small validation set even with regularization.",
          "Results",
          "Any calibration model with tens of thousands (or more) parameters will overﬁt to a small validation set, even when applying regularization."),
     ],
     "notes": "PDF states: Proceedings of the 34th International Conference on Machine Learning, Sydney, Australia, PMLR 70, 2017. Affiliation: Cornell University; NSF, Bill and Melinda Gates Foundation, Office of Naval Research support. Datasets: Birds, Cars, ImageNet 2012, CIFAR-10/100, SVHN (image); 20 News, Reuters, SST binary/fine-grained (text). Networks trained with 'the data preprocessing, training procedures, and hyperparameters as described in each paper'; Birds/Cars fine-tuned from ImageNet; DAN/TreeLSTM with authors' default hyperparameters. Validation sets are carved from the same distribution (e.g. 45,000/5,000/10,000 for CIFAR). All evaluation is in-distribution (train/validation/test from the same distribution); behaviour under dataset shift is not studied in this paper (see arxiv-1906.02530, which tests temperature scaling under shift). Tag note: the task tags are approximations. No calibration tag exists yet (a user decision on adding one is pending); selective-prediction is the closest existing tag and does not exactly describe this paper, which studies calibration, not abstention (it only motivates calibration by handing control to other sensors or human doctors when confidence is low)."},

    {"id": "arxiv-1906.02530",
     "title": "Can You Trust Your Model's Uncertainty? Evaluating Predictive Uncertainty Under Dataset Shift",
     "authors": ["Yaniv Ovadia", "Emily Fertig", "Jie Ren", "Zachary Nado", "D Sculley", "Sebastian Nowozin", "Joshua V. Dillon", "Balaji Lakshminarayanan", "Jasper Snoek"],
     "year": 2019, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/1906.02530", "code": "https://github.com/google-research/google-research/tree/master/uq_benchmark_2019"},
     "tasks": ["selective-prediction", "dataset-shift-detection", "image-classification"],
     "fam": ["deep-learning"],
     "proposes": ["Large-scale benchmark of predictive uncertainty (accuracy, NLL, Brier, ECE, entropy, confidence-vs-accuracy) under increasing dataset shift and on fully OOD data, across image, text and categorical (ad-click) classification"],
     "claims": [
         ("Methods compared (all model p(y|x) only): vanilla maximum softmax probability, temperature scaling on a validation set, MC dropout, deep ensembles of independently trained networks (M = 10), stochastic variational inference, and last-layer SVI / last-layer dropout.",
          "Methods and metrics",
          "(Ensembles) Ensembles of M networks trained independently on the entire dataset using random initialization (Lakshminarayanan et al., 2017) (we set M = 10 in experiments below)"),
         ("Shift protocol: models are trained and validated i.i.d., then evaluated on (i) shifted versions of test inputs whose labels stay in the k classes (covariate shift: corruptions and perturbations from Hendrycks & Dietterich 2019 on CIFAR-10/ImageNet, rotations/translations on MNIST, randomly reassigned categorical tokens on Criteo), and (ii) completely different OOD datasets (e.g. Not-MNIST, SVHN for CIFAR-10, LM1B for text), for which only label-free diagnostics (entropy, confidence histograms, confidence vs accuracy) are reported. Exception: for 20 Newsgroups the 'shifted' set is the 10 odd-numbered classes held out from training, i.e. its labels are not among the training classes.",
          "Background",
          "We use shifts such as corruptions and perturbations proposed by Hendrycks & Dietterich (2019), and ideally would like the model predictions to become more uncertain with increased shift, assuming shift degrades accuracy."),
         ("Tuning protocol: hyperparameters were optimized by Bayesian optimization (Google Vizier), maximizing log-likelihood on a validation set held out from the (unshifted) training data; the main text says this applies to all methods except on ImageNet.",
          "Appendix (Hyperparameter tuning)",
          "We maximized the log-likelihood on a validation set that was held out from training (10K examples for MNIST and CIFAR-10, 125K examples for ImageNet)."),
         ("Failure of i.i.d. calibration under shift (CIFAR-10 / ImageNet): temperature scaling achieves low ECE for small shift but ECE increases significantly as shift increases, so calibrating on an i.i.d. validation set does not guarantee calibration under distributional shift.",
          "Experiments and results",
          "Interestingly, while temperature scaling achieves low ECE for low values of shift, the ECE increases signiﬁcantly as the shift increases, which indicates that calibration on the i.i.d. validation dataset does not guarantee calibration under distributional shift."),
         ("On the Criteo ad-click data with categorical-feature shift, temperature scaling had a worse Brier score than the vanilla model, which the authors read as post-hoc calibration on the validation set actually harming calibration under dataset shift.",
          "Experiments and results",
          "Strikingly, temperature scaling has a worse Brier score than Vanilla indicating that post-hoc calibration on the validation set actually harms calibration under dataset shift."),
         ("Take-home: along with accuracy, uncertainty quality consistently degrades with increasing dataset shift for every method tested.",
          "Takeaways and recommendations",
          "Along with accuracy, the quality of uncertainty consistently degrades with increasing dataset shift regardless of method."),
         ("Take-home (hedged): deep ensembles 'seem to' perform best across most metrics and be more robust to shift, and a small ensemble (e.g. M = 5) may be sufficient; the authors also note the best-performing methods tend to be more expensive in compute and memory, and that the method ordering on MNIST does not reflect the other datasets.",
          "Takeaways and recommendations",
          "Deep ensembles seem to perform the best across most metrics and be more robust to dataset shift."),
     ],
     "notes": "PDF states: 33rd Conference on Neural Information Processing Systems (NeurIPS 2019), Vancouver, Canada. Affiliations: Google Research and DeepMind (all authors). Reviewer observation (NOT stated by the paper, which does not discuss it): corresponding author Balaji Lakshminarayanan is the first author of the deep ensembles method (Lakshminarayanan et al., 2017, 'Simple and Scalable Predictive Uncertainty Estimation Using Deep Ensembles', in the reference list) that the paper finds 'seem to' perform best; readers may weigh that finding accordingly. Other observations relevant to switching: on MNIST most methods give low-entropy, high-confidence predictions on entirely OOD data ('confidently wrong'); in the text experiment temperature scaling 'does not appear to increase uncertainty significantly on the shifted data'; LL-SVI and LL-Dropout perform worse than vanilla on shifted data and SVHN. Higher-capacity vanilla/dropout models (double filters) did not explain the ensemble advantage. Data: MNIST, CIFAR-10, ImageNet, 20 Newsgroups, Criteo (37M examples, 13 numeric + 26 categorical features), plus a genomics problem in the appendix. Tag note: the task tags are approximations. No calibration / uncertainty-evaluation tag exists yet (a user decision on adding one is pending); selective-prediction and dataset-shift-detection are the closest existing tags and do not exactly describe this paper, which benchmarks uncertainty quality under shift rather than proposing an abstention or shift-detection method. Data tag image-classification covers only part (text and Criteo tabular-like data also used)."},

    {"id": "arxiv-2201.04234",
     "title": "Leveraging Unlabeled Data to Predict Out-of-Distribution Performance",
     "authors": ["Saurabh Garg", "Sivaraman Balakrishnan", "Zachary C. Lipton", "Behnam Neyshabur", "Hanie Sedghi"],
     "year": 2022, "version": "arXiv v3",
     "links": {"arxiv": "https://arxiv.org/abs/2201.04234", "code": "https://github.com/saurabhgarg1996/ATC_code"},
     "tasks": ["mlops", "dataset-shift-detection", "image-classification"],
     "fam": ["deep-learning"], "par": ["post-hoc"],
     "proposes": ["Average Thresholded Confidence (ATC): pick a threshold on a confidence score (max confidence or negative entropy) on labeled source validation data so that the fraction below it equals source error, then predict target error as the fraction of unlabeled target points below it; plus an identifiability/impossibility analysis of target-accuracy estimation"],
     "claims": [
         ("Method: ATC learns a threshold on model confidence and predicts target accuracy as the fraction of unlabeled target examples whose confidence exceeds it, using only labeled source data and unlabeled target data.",
          "Abstract",
          "We propose Average Thresholded Conﬁdence (ATC), a practical method that learns a threshold on the model’s conﬁdence, predicting accuracy as the fraction of unlabeled examples for which model conﬁdence exceeds that threshold."),
         ("Threshold choice: the threshold is chosen on held-out source validation data so that the fraction of source examples scoring above it matches their accuracy; the same threshold is then applied to the target (the authors note a different target threshold would in principle exist, but the source one worked well in their experiments).",
          "Introduction",
          "ATC selects a threshold on validation source data such that the fraction of source examples that receive the score above the threshold match the accuracy of those examples."),
         ("Impossibility statement (theory, Section 3.1): the setting is knowledge of the full labeled source distribution p_s(x,y) and the unlabeled target marginal p_t(x), with no assumptions on the classifier f (f may be any classifier on X). Proposition 1: absent further assumptions, target accuracy is identifiable iff p_t(y|x) is uniquely identified given p_s(x,y) and p_t(x) (e.g. it is, under covariate shift with target support inside source support, or under label shift). Corollary 1: absent assumptions on the classifier f, no method of estimating accuracy works for all natures of distribution shift. Example 1 (binary Gaussian mixture) shows the same p_s(x,y), p_t(x) give different target errors under covariate shift vs label shift, so a method consistent under one is wrong under the other.",
          "Accuracy estimation: possibility and impossibility results",
          "Corollary 1. Absent assumptions on the classiﬁer f, no method of estimating accuracy will work in all scenarios, i.e., for different nature of distribution shifts."),
         ("Stated limitation following from the theory: ATC, like all methods, must fail (give inconsistent estimates) on certain types of distribution shift. The main-text positive guarantee (Theorem 1, informal) is for a toy setting: binary classification with an invariant feature and a spurious feature, a linear sigmoid classifier with w_inv > 0, the max-confidence score, and target shift only in the degree of spurious correlation; there, ATC is consistent. In that same toy model, shrinking the support of the target class-conditional p_t(x_inv|y) can make ATC over-estimate target accuracy. Appendix D.1 is said to give a more general (less interpretable) classifier-dependent shift condition under which ATC is consistent.",
          "Introduction",
          "Finally, we note that although ATC achieves superior performance in our empirical evaluation, like all methods, it must fail (returns inconsistent estimates) on certain types of distribution shifts, per our impossibility result."),
         ("Evaluation protocol: metric is mean absolute error between true target accuracy and the estimate on the same unlabeled examples (target labels used only for the true value); models use standard training with benchmarked hyperparameters (the reproducibility statement says no hyperparameter tuning was done); for all methods, temperature-scaling calibration is fitted on source validation data, and results are reported both before and after it; baselines are AC, DOC (the DOC-Feat variant of Guillory et al.), importance re-weighting (IM) and GDE; MAE aggregated over 4 seeds.",
          "Experiments",
          "To compare methods, we report average absolute difference between the true accuracy on the target data and the estimated accuracy on the same unlabeled examples."),
         ("Where it works and fails: MAE is small on BREEDS shifts from the same subpopulation, but on shifts with novel subpopulations MAE is significantly higher for all methods (ATC still best among them); the conclusion repeats that ATC still suffers large estimation error on novel-population datasets such as BREEDS. Shift families tested: synthetic corruptions (ImageNet-C, CIFAR-10-C/100-C), dataset reproduction (ImageNetV2, CIFARv2), renditions/sketch, BREEDS subpopulations, WILDS, MNIST to USPS/SVHN/QMNIST.",
          "Results",
          "While we observe a small MAE (i.e., comparable to our observations on other datasets) on BREEDS with natural and synthetic shifts from the same sub-population, MAE on shifts with novel population is signiﬁcantly higher with all methods."),
         ("Garg et al.'s critique and re-evaluation of prior work (Deng et al.; Guillory et al.'s DoC with regression): in this paper's view, methods that fit a regression on labeled target domains rely on unseen target domains being strongly linearly correlated with the seen ones on the distance measure, and can be rendered ineffective otherwise. Garg et al.'s own re-evaluation (Section 5.1, BREEDS): they observe a poor linear correlation across subpopulations (Living-17 shown); they fit a robust (Siegel) linear regression for DOC 'as in Guillory et al.' on labeled natural and synthetic shifts of the source subpopulations, evaluate on shifts with novel subpopulations, and find the fitted DOC improves over unfitted DOC while ATC without any regression performs better or similar. This is Garg et al.'s result in their setting, not a finding of Guillory et al.",
          "Introduction",
          "methods that leverage labeled data from target domains rely on the fact that unseen target domains exhibit strong linear correlation with seen target domains on the underlying distance measure"),
     ],
     "notes": "PDF states: Published as a conference paper at ICLR 2022. Affiliations: Carnegie Mellon University; Google Research (Blueshift team, Brain team); first author interned at Google. Also cites Ovadia et al. (2019) for the claim that models calibrated on source are not, in general, calibrated on an unseen target domain. Architectures: DenseNet121 and ResNet50 (vision), DistilBERT-base-uncased (Amazon/CivilComments-WILDS), MLP (MNIST); results aggregated over 4 seeds. Temperature scaling substantially improved MAE for all methods in their experiments. Garg et al. also characterize Guillory et al. (2021) as requiring calibration on the target domain for consistent estimates; that is Garg et al.'s characterization. Tag note: the task tags are approximations. No performance-estimation tag exists yet (a user decision on adding one is pending); mlops and dataset-shift-detection are the closest existing tags and do not exactly describe this paper, which estimates target accuracy from unlabeled data rather than detecting shift."},

    {"id": "arxiv-2107.03315",
     "title": "Predicting with Confidence on Unseen Distributions",
     "authors": ["Devin Guillory", "Vaishaal Shankar", "Sayna Ebrahimi", "Trevor Darrell", "Ludwig Schmidt"],
     "year": 2021, "version": "arXiv v2",
     "links": {"arxiv": "https://arxiv.org/abs/2107.03315"},
     "tasks": ["mlops", "dataset-shift-detection", "image-classification"],
     "fam": ["deep-learning", "linear-models"], "par": ["post-hoc"],
     "proposes": ["Difference of confidences (DoC): the drop in average max-softmax confidence from the base (held-out training-distribution) set to an unlabeled target set, used directly (DoC-Feat) or as a feature for a linear regressor fitted on labeled calibration shifts, to predict accuracy on unseen distributions; DoE uses average entropy instead"],
     "claims": [
         ("Proposed signal: DoC is defined as the base set's average confidence minus the target set's average confidence (over classes shared by both); it is used as a feature for a regressor of the accuracy gap or directly as an accuracy estimate, motivated by average confidence (AC) being an overly optimistic accuracy predictor for miscalibrated models.",
          "Predicting performance with difference of confidences",
          "We propose difference of conﬁdences DoC as a way to quantify distribution shifts:"),
         ("Negative finding: common distributional distances such as Frechet distance and MMD fail to give reliable performance estimates under distribution shift; in Results, when calibrated on synthetic shifts, A-proxy and discriminator AUC did not significantly improve on the naive base-accuracy baseline for natural shifts.",
          "Abstract",
          "Our investigation determines that common distributional distances such as Frechet distance or Maximum Mean Discrepancy, fail to induce reliable estimates of performance under distribution shift."),
         ("Evaluation protocol: ImageNet is the base distribution; regressors are trained on labeled 'calibration' groupings of shifts and evaluated on held-out 'validation' groupings, with similar shifts placed in the same group to avoid leakage; the main setting calibrates on synthetic shifts (ImageNet-C) and predicts on natural shifts (ImageNet-V2, ImageNet-Vid-Robust, ImageNet-Rendition, ImageNet-Sketch), averaged over many pretrained architectures; metric is MAE of predicted accuracy.",
          "Experiments",
          "Our work’s chief concern is the ability to predict natural distribution shifts, and as such focuses on settings with synthetic calibration and natural validation datasets."),
         ("Failure mode (synthetic shifts): although DoC improved on the AC baseline for every natural shift, it decreased prediction accuracy on 2 of 8 synthetic shifts (Defocus Blur and Gaussian Blur).",
          "Results",
          "While DoC improves upon the AC baseline for each form of natural distribution shift, we note that in 2 of the 8 synthetic shifts explored (Defocus Blur and Gaussian Blur) DoC actually decreases the accuracy of the predictions."),
         ("Failure mode (training interventions): the improvement from DoC declines steeply for models trained with synthetic corruptions (AugMix, AugMix-DeepAugment), and DoC did not improve the AugMix-DeepAugment model; the authors think the distances are likely off because AugMix corruptions were not replicated between base and calibration sets.",
          "Results",
          "Furthermore, we observe a steep decline in the magnitude of improvement offered from our DoC approach as it is evaluated over models which incorporate synthetic corruptions into the training process (Augmix, AM-DeepAugment)."),
         ("Failure mode (adversarially collected shift): ImageNet-A produced the highest accuracy-prediction error of all shifts studied for every approach; when calibrated on synthetic shifts, DoC was the only approach to noticeably improve on AC there; calibrating on natural shifts instead improved all approaches, but only DoE and DoC then beat AC (the others stayed significantly worse than AC), which the authors take as showing the importance of calibrating and evaluating on natural shifts and as highlighting limitations of these approaches.",
          "Results",
          "In Figure 7, we observe that this distribution shift produces the highest predicted accuracy error of shifts we have studied across all approaches."),
         ("Stated limitation: the authors call their results a promising step for detecting performance drop under shift but say the problem is far from solved; they also echo Ovadia et al. that many methods designed for uncertainty prediction seem to fall short of simpler baselines. No impossibility or identifiability result is stated in the text.",
          "Conclusion",
          "While our results present a promising step forward for detecting performance drop under distribution shift, we note that the problem is far from solved."),
     ],
     "notes": "Affiliations: UC Berkeley, Amazon (Vaishaal Shankar), Toyota Research Institute (Ludwig Schmidt); funding from DoD/DARPA XAI and LwLL programs and Berkeley's BAIR industrial alliance programs. Venue not stated in the arXiv v2 PDF text. Regression-based variants need labeled target-like shifts (calibration groupings); DoC-Feat needs none. Experiments with non-linear regressors in the supplement are said to follow the same trends as linear ones. The paper also reports DoC on a single ResNet-101 beating a ResNet ensemble at predicting accuracy. Later work, not this paper: Garg et al. (arxiv-2201.04234) use DoC-Feat as a baseline and, on BREEDS, fit a robust linear regression for DOC on labeled shifts of the source subpopulations and test on novel subpopulations; they report that their ATC without regression performs better or similar, and argue that regression on labeled target domains can fail when unseen shifts are not linearly correlated with seen ones. Those are Garg et al.'s findings in their setting. This paper itself evaluates only on ImageNet-based shifts and states no impossibility result. Tag note: the task tags are approximations. No performance-estimation tag exists yet (a user decision on adding one is pending); mlops and dataset-shift-detection are the closest existing tags and do not exactly describe this paper, which predicts accuracy under shift rather than detecting shift; linear-models is for the linear regressor."},
]

build(SPECS, base_note="Selected for the topic article requested by the user (2026-10-03): model fallback and model selection in MLOps (meta-learned selection, dynamic selection, abstention/deferral, switching triggers, cascades/routing, monitoring); carded by a subagent. Results tables not recorded; claims only.")
